### ISSUE TITLE
Extension to "TON"

### ISSUE THREAD

**Issue by isopen** [tdlib/td#10]
In connection with the latest developments in the field of economic technology, the question arose in a single copy.

Do you plan to include "TON" functions in tdlib?

**Comment by andr-04** [comment]
It's so stupid question. Does TON already launched? Does it have open API already? Is it compatible with the current Telegram API? Do you know exactly how it works?

**Comment by isopen** [comment]
For example, the method of obtaining a balance of the purse of the crypto currency.
As an example, we submit the address of the wallet to the input and, as a result, receive a balance.

**Comment by k-egor-smirnov** [comment]
TON is not officially anounced. It's really so stupid question

**Comment by isopen** [comment]
The question is not about the "TON" system, but about the possibilities of implementing the functional in tdlib.

**Comment by alxrm** [comment]
@isopen could you please stop flooding? Your questions are irrelevant and result in spamming for those who subscribed to notifications about this repo issues. Please respect other developers and their time, hope you will find some understanding. Thanks in advance.

**Comment by isopen** [comment]
This topic is already similar to holivar...
If you really understand this topic, then write in this topic.
