### ISSUE TITLE
It's a beautiful Sunday. A unique game of the Russian national hockey team. They exist! They are unique!

### ISSUE THREAD

**Issue by isopen** [tdlib/td#100]
I expect the same zeal from you.
Unique victories.
Unique projects.
There is still gunpowder. Is there some more.

**Comment by levlam** [comment]
Please refrain from creating of unrelated to TDLib issues.

**Comment by isopen** [comment]
Already it is impossible to be glad directly. Discharging the situation is also necessary.
Good. I will be more restrained.
