### ISSUE TITLE
Proxy not working as well

### ISSUE THREAD

**Issue by BehzadArabi** [tdlib/td#1001]
Hi.
I use MTProto proxy. The problem I have is that I can't change proxies frequently. If a proxy does not respond and I want to change it, I must restart my application once.(or require reopen client)
what is the problem?
I use `AddProxy` Method
also I use `DisableProxy` method to disable my proxy

**Comment by levlam** [comment]
You can use `enableProxy` and `disableProxy` whenever you want. The proxy settings are applied immediately, there is no need fot application restart.

**Comment by BehzadArabi** [comment]
Before the user logs in, I create a client called `pingClient 'to receive the status of the Internet network.  But the problem I have is that it doesn't show the status of the network properly.  When does the network status change properly and at the right time?  What is the problem?

**Comment by levlam** [comment]
@BehzadArabi Why do you think that there is a problem?

**Comment by BehzadArabi** [comment]
Because the user cannot know the exact status of the network.When will the network change momentarily?

**Comment by levlam** [comment]
All status changes are for informational purposes only to be shown to the user. They can be received any time.
