### ISSUE TITLE
Stop getting updates

### ISSUE THREAD

**Issue by guyho2** [tdlib/td#1005]
Seems like after running for few minutes I am stop getting updates somehow.
As you can see below are the logs printed by my application. After ~15 minutes I got updateHavePendingNotifications event, and from this point the app stop getting updates from any kind.
Do you know what can cause it? 

updateUserStatus
Got event updateUserStatus
19:14:48.890-Got update message. Message=??, MessageDate=19:14:48,ChannelName=
Got event updateChatLastMessage
Got event updateUserStatus
Got event updateUserStatus
19:16:23.249-Got update message. Message=?, MessageDate=19:16:23, ChannelName=
Got event updateChatLastMessage
Got event updateUserStatus
Got event updateUserStatus
Got event updateUserStatus
Got event updateHavePendingNotifications
Got event updateHavePendingNotifications

**Comment by levlam** [comment]
No. Please send TDLib's log with verbosity level 4 to @tdlib_bot.

**Comment by guyho2** [comment]
I think I find the issue.
I am using a nuget package from buget as a wrapper for .net core tdlib.
Seems like this library not calling the setoption online, and maybe because of it I am stop getting updates from time to time?
I added this code that once a minute refresh my status to online.

                var timer = new System.Timers.Timer(60000){AutoReset = true, Enabled = true};
                timer.Elapsed += async (sender, args) =>
                {
                    try
                    {
                        await client.ExecuteAsync(new TdApi.SetOption
                        {
                            Name = "online",
                            Value = new TdApi.OptionValue.OptionValueBoolean {Value = true}
                        });
                        await Console.Out.WriteLineAsync($"{DateTime.Now:HH:mm:ss.fff}-status set to online");
                    }
                    catch (Exception ex)
                    {
                        _logger.Error("Failed to set user status online", ex);
                    }
                };

Can it be the issue? Should I call it once a minute or can I call it only once in the startup of the app?

**Comment by levlam** [comment]
No, it can't be the reason. And it is useless to set an option to its current value, so you need to set "online" only once.

**Comment by guyho2** [comment]
Thanks. log file with level 4 sent to @tdlib_bot. Will the answer be sent to this chat (the bot one)?

**Comment by guyho2** [comment]
Seems like it stop working after getting this event: UpdateHavePendingNotifications

**Comment by levlam** [comment]
In the sent logs everything works as expected. You hust have no new messages and have no new updates.

**Comment by guyho2** [comment]
No. I have new updates. I sent dummy updates all the time... but stop getting it after the UpdateHavePendingNotifications...

**Comment by guyho2** [comment]
I guess its the same issue as described by telegram for the UpdatesTooLong
https://core.telegram.org/constructor/updatesTooLong

**Comment by levlam** [comment]
No, from the log it definitely follows, that there is no issue. New messages from big channels can be delivered with some delay.

**Comment by Karmageddonium** [comment]
Hi, how have u solved your problem?
