### ISSUE TITLE
Disable link preview on sent messages

### ISSUE THREAD

**Issue by solarin** [tdlib/td#1006]
Hello,

I have been scaffolding a lot but i could not find a way to disable the preview on a message containing links. 

I know it is possible because the mobile phone and desktop client allow to do it.

Am I missing something or this feature is not exposed?

Thank you

**Comment by zevlg** [comment]
Here is `disable_web_page_preview` in:

```
inputMessageText text:formattedText disable_web_page_preview:Bool clear_draft:Bool = InputMessageContent;
```

**Comment by solarin** [comment]
you are completely right sorry, it was just under my eyes

thank you
