### ISSUE TITLE
TDLib Android licences clarification

### ISSUE THREAD

**Issue by alkber** [tdlib/td#1007]
Hi, there

I'm sorry if i have asked in the wrong thread for this topic, however i couldn't find other issue tracker for asking this question. 

I have downloaded the Android library with jni wrappers. I would like to use it in an application while using the telegram features. I'm worried about the two types of licences seen. The thee are 3 java source files with GNU 2.0 v, respectively Client, NativeClient, TdApi. As for tdlib is concerned  it is under the BOOST Licences. The android application that is being developed is not an opensource nor can its sources be disclosed. Neither do we plan to modify tdlib. Boot licences allow this linking. However this thin layer of jni wrappers are GNU.  What can i do here, would it be legal for me to create jni wrappers and use the native library, this is the only solution i can see.

**Comment by levlam** [comment]
The license is LGPL 2 or later and not GPL, so you need to open-source only wrapper's modifications. But it doesn't supposed to be LGPL 2 either now. It will be relicensed to Boost, as is done for almost the same JNI-wrapper, available at https://github.com/tdlib/td/tree/master/example/java/org/drinkless/tdlib.

**Comment by levlam** [comment]
The source code of prebuilt TDLib for Android was relicensed to Boost Software License 1.0.
