### ISSUE TITLE
Handle PHONE_CODE_INVALID or switch account during login

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#1008]
Hi,
Could you please clarify what is the correct way of handling case when user is logging-in, promted to enter his phone code (or at next step - password), but enters it wrong or decides to switch to another Telegram account at this point? 
It is not correct to send TdApi.LogOut cuz user is not logged-in yet, but seems that it is not correct to send TdApi.Close either?
Are there any suggestions on how to 'interrupt' login process in such cases?

**Comment by levlam** [comment]
Calling `logOut` is a correct way to handle this. It guarantees that the user will no be accidentally logged in by a pending request.
Calling `close` is a correct way, if the user wants to continue logging in later.
Also, `setAuthenticationPhoneNumber` can be called directly without `logOut` if there is no pending authentication query and the current authorization state is `authorizationStateWaitCode`, `authorizationStateWaitRegistration`, or `authorizationStateWaitPassword`.
