### ISSUE TITLE
About keyboard messages

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#1010]
@levlam 
- I'm sorry to bother you again, but this problem really caused me trouble. When I sent a "/ start" command to the robot, I got the following
- "reply_markup":
- {
- "@type": "replyMarkupInlineKeyboard",
- "rows":
- [
- [
- {
- "@type": "inlineKeyboardButton",
- "text": "\ ud83d \ udd25 \ u6295 \ u653e \ u5e7f \ u544a",
- "type":
- {
- "@type": "inlineKeyboardButtonTypeUrl",
- "url": "https://t.me/hao1234bot_changelogs/124"
- }
- },
- {
- "@type": "inlineKeyboardButton",
- "text": "\ u25b6 \ ufe0f \ u4e0b \ u4e00 \ u9875",
- "type":
- {
- "@type": "inlineKeyboardButtonTypeCallback",
- "data": "OXhPUw =="
- }
- }
- ],
- [
- {
- "@type": "inlineKeyboardButton",
- "text": "\ u21a9 \ ufe0f \ u8fd4 \ u56de",
- "type":
- {
- "@type": "inlineKeyboardButtonTypeCallback",
- "data": "Yj1yYW5k"
- }
- }
- ]
- ]
- },
- "reply_to_message_id": 0,
- 
- How should I deal with this message? When my user selected a certain ButtonCallback, I tried to use the SendMessage method to deal with it, but I got an error, Error: 0: Expected Array, got Object. I do n’t know the reason for this error. Test code

- Json :: Value reply_markup = root ["reply_markup"] ["rows"];
- Json :: Value sendMessageJson;
- Json :: Value sendMessageOptions;
- Json :: Value ReplyMarkup;
- Json :: Value inlineKeyboardButton;
- Json :: Value InlineKeyboardButtonType;
- 
- InlineKeyboardButtonType ["data"] = reply_markup [0] [1] ["type"] ["data"]. AsString ();
- InlineKeyboardButtonType ["@ type"] = "inlineKeyboardButtonTypeCallback";
- inlineKeyboardButton ["text"] = "";
- inlineKeyboardButton ["type"] = InlineKeyboardButtonType;
- inlineKeyboardButton ["@ type"] = "inlineKeyboardButton";
- ReplyMarkup ["rows"] = inlineKeyboardButton;
- ReplyMarkup ["@ type"] = "replyMarkupInlineKeyboard";
- sendMessageJson ["reply_markup"] = ReplyMarkup;
- 
- sendMessageJson ["@ type"] = "sendMessage";
- sendMessageJson ["chat_id"] = 401234702;
- sendMessageJson ["reply_to_message_id"] = root ["message"] ["id"]. asString ();
- 
- Json :: Value InputMessageContent;
- Json :: Value formattedText;
- Json :: Value textEntity;
- Json :: Value TextEntityType;
- 
- sendMessageJson ["reply_to_message_id"] = 0;
- 
- formattedText ["text"] = "";
- InputMessageContent ["text"] = formattedText;
- InputMessageContent ["@ type"] = "inputMessageText";
- sendMessageJson ["input_message_content"] = InputMessageContent;
- td_json_client_send (client, sendMessageJson.toStyledString (). c_str ());
- 
- -

**Comment by levlam** [comment]
> ReplyMarkup ["rows"] = inlineKeyboardButton;

`rows` must be an array of arrays of `inlineKeyboardButton`.

Between, only bots can use reply markup.

**Comment by AquariusHunters** [comment]
@levlam 
So what method should I use to respond to the boardButton message sent by the bot? When I want to achieve the same effect as the client, I click the button to send the corresponding message to get different content

**Comment by AquariusHunters** [comment]
@levlam Or is this actually similar to the command information of a bot, but how do I send the command information corresponding to each button?

**Comment by levlam** [comment]
@AquariusHunters You can't send a message by clicking on an inline keyboard button. Inline keyboard buttons never send messages. If you want to click a callback inline keyboard button, you must use `getCallbackQueryAnswer` method.

**Comment by AquariusHunters** [comment]
@levlam 
Okay, thank you, this has troubled me for an afternoon, it seems that my previous ideas have gone wrong

**Comment by AquariusHunters** [comment]
But I feel that this may not be the result I want, I think I can test it and then choose whether to continue to consult or close the issues

**Comment by AquariusHunters** [comment]
I have tried to log in to my account on the client, operated the button, and I got this message about updateMessageEdited
