### ISSUE TITLE
updateUnreadChatCount does not include unread channels

### ISSUE THREAD

**Issue by MattNguyen** [tdlib/td#1011]
According to the [documentation](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_unread_chat_count.html), `updateUnreadChatCount` handles the following:

> Number of unread chats, i.e. with unread messages or marked as unread, has changed

With message database turned on, I am able to receive this event and properly handle it within my application. However I noticed that this event only accounts for private chats, basic groups, and non-channel supergroups.

I expect that an unread and unmuted channel with unread messages should increment the `unread_unmuted_count` field.

**Comment by levlam** [comment]
The update includes all chats, including channel supergroups. The problem must be somewhere else.

**Comment by MattNguyen** [comment]
You're right. We were not handling the user's default notification settings. Sorry for the trouble!
