### ISSUE TITLE
How to check internet usage

### ISSUE THREAD

**Issue by BehzadArabi** [tdlib/td#1014]
How can I check the internet usage of this library? Completely and clearly

**Comment by BehzadArabi** [comment]
What advice do you have for reducing internet usage?

**Comment by levlam** [comment]
Use `getNetworkStatistics` to get network usage statistics.

It is not possible to reduce network usage. TDLib does only needed things.

**Comment by BehzadArabi** [comment]
`getNetworkStatistics` What information does it provide?

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_network_statistics.html
