### ISSUE TITLE
How to get the dc_id of a file using TDLib

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1015]
As far as I know, on the jvm platform, only the official Android client maintains an active MTProto client library, but his TLRPC is incomplete and difficult to use on the jse platform. Unfortunately, TDLib hides a lot of low-level implementations, So much so that I don't know how to view the dc_id of a file.

**Comment by levlam** [comment]
TDLib doesn't provide such information. Moreover, a lot of TDLib files don't have вс_шв at all.
