### ISSUE TITLE
Can't find class

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#1017]
Hi. I recently built `libtdjni.so` file on a new machine and while running the jar file (which contains tdlib as llibrary) I faced with this error:
`[ 1][t 0][1587667401.696010351][tl_jni_object.cpp:37]	Can't find class [org/drinkless/tdlib/TdApi$AuthorizationStateWaitOtherDeviceConfirmation]`

**Comment by levlam** [comment]
This class was added in TDLib 1.6.0, so it seems that you have new TDLib, but didn't updated corresponding autogenerated Java classes.

**Comment by yasharzb** [comment]
Thank u so much!
