### ISSUE TITLE
createNewSecretChat limits

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#1019]
Are there some limitation in using createNewSecretChat to create chats with different users? I mean is there a maximum number of secret chat you can create per day or per minute?
I ask because I have an environment with thousand users and I have to create one secret chat per user. But after few secretchat created in a day the server seams to reply with error and tell me to wait for an amount of time before create another one. The chat are created with different users obviously, but it's always my tdlib client that start it. Let me know the limitation

**Comment by levlam** [comment]
Every request has limits. For createNewSecretChat the limit is very tight, at most 30 new chats daily.

**Comment by micheleselea** [comment]
Ok I understand, so now I can schedule the creation. Thank you

**Comment by micheleselea** [comment]
Probably that kind of limitation should be written in function docunentation so developer can take care of it

**Comment by levlam** [comment]
@micheleselea All flood limits are subject to change, so developer must not assume any specific limit.

**Comment by micheleselea** [comment]
I understand but at list know that some limit exists and what is the currebt limit could help to develop software that take care of it. I can't take care of something that is not known

**Comment by levlam** [comment]
Limit, explicit or implicit, exists for every method. The basic rule is that ordinary usage should never trigger them, and anything beyond ordinary usage will be limited.

**Comment by micheleselea** [comment]
I agree but it's just difficult to deal with it if you do not know them. Is there a page where function limitation is written so I can check if I'm using function in a wrong way?

**Comment by levlam** [comment]
No, there is no such page.

**Comment by micheleselea** [comment]
@levlam do you know if the 30/day newsecretchat limit is a solar day limit so it's 30 from 00:00 till 23:59 or it's a shift queue so in latest 24 ours you have maximum 30 newsecretchat regardless from start/end time?
I don't know if the question is enough clear

**Comment by levlam** [comment]
It is closer to the second.
