### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SayedSadat** [tdlib/td#102]
i need _download_ **permission** on this version of td

https://bitbucket.org/drinkless/td/commits/a546914423f2

for this user 

https://bitbucket.org/ShafiqSadat/

**Comment by levlam** [comment]
This is a private TDLib version with minor differences and we can't give access to it. Between, this commit is too old. Probably, what you are looking for is already publicly available as an [example](https://github.com/tdlib/td/tree/master/example).
