### ISSUE TITLE
Chat folders support in tdlib

### ISSUE THREAD

**Issue by shah-sudeep** [tdlib/td#1020]
Is 'Chat folders' still not supported by tdlib? 
Telegram X says that it is still not available in tdlib but I saw it's implementation in plus messenger already. So is it supported or not?

Also please make the "All" chat folder too editable so that it won't have to sit as the home page and can be removed or at least changed tab position.

**Comment by RememberTheAir** [comment]
> but I saw it's implementation in plus messenger

Plus Messenger doesn't use tdlib. It is a fork of the standard android app, which uses its own MTProto implementation to interact with the API

> Also please make the "All" chat folder too editable so that it won't have to sit as the home page and can be removed or at least changed tab position.

This is up to the app I guess

Anyway, there's already an issue about support for Telegram folders: #976

**Comment by Domingowen** [comment]
TDlib web is supported. But TDlib doesn't release it to the public.

**Comment by zevlg** [comment]
> TDlib web is supported. But TDlib doesn't release it to the public.

Folders already in TDLib’s master, search for `chatListFilter`

**Comment by FalconEagleTest** [comment]
hi,
yes i could find how to filter chat list by the "chat_filter_id" but how do i get a list of the folders with there names and ids?
thanks

**Comment by levlam** [comment]
@FalconEagleTest You need to handle `updateChatFilters`.

**Comment by FalconEagleTest** [comment]
> updateChatFilters

which function can i use to get the list of folders?
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html
thanks.

**Comment by levlam** [comment]
No. All the changes are received through the update.

**Comment by WinnerOK** [comment]
@levlam could you clarify how an app should initially load a list of ChatFilters (folders) ?

I can handle `updateChatFilters` to get updates that user is making on other device, but how can I know the list of folders to show it right after first user login? I did not get an `updateChatFilters` update after a successful authorization

**Comment by levlam** [comment]
You will receive `updateChatFilters`. This will happen right after the authorization.
