### ISSUE TITLE
error creating SecretChat

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#1022]
Hi, I did a test using Telegram official App from Play Store (Android). I have my client develop with TDLib and sometimes when I start a NEW SecretChat from Telegram App, in TDLib I receive following log lines:

```
[ 2][t 5][1587999734.939820528][SecretChatActor.cpp:1926][#1][!SecretChat -1925878728]  Close Secret chat because it is empty
[ 1][t 5][1587999762.870630741][SecretChatActor.cpp:706][#1][!SecretChat -1471153339]   Fatal error: [Error : 0 : Chat discarded]
TDLIB updateSecretChat: [id_:-1471153339] [user_id_:17742932] status: secretChatStatePending
TDLIB updateSecretChat: [id_:-1471153339] [user_id_:17742932] status: secretChatStateClosed
```

And the secret chat is "aborted" but on TelegramApp is active as if the initialization is ok.
Do you know what is happening here?

**Comment by levlam** [comment]
The secret chat is accepted by some other client.

**Comment by micheleselea** [comment]
Ok thanks I'll double check
