### ISSUE TITLE
SecretChat on iOS/iPhone chat not found

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#1024]
Hi @levlam I have a strange behavior that happens with iPhone device.
Usually my TDlib client create a secretchat with users for sending data. Suppose you have an iPhone user, the chat is created and used correcty. Suddenly happens that TdLib client have to send a message and the sendMessage function receive the error, using the same chat_id I used before:
```
 error {
  code = 5
  message = "Chat not found"
}
```
So the only thing I can do is to delete is and re/create.
300 users active happens only to 5/6 iPhone users. Have you ever experience that?

**Comment by levlam** [comment]
The only reason for "Chat not found" error is a wrong chat_id. You can collect TDLib's log with verbosity level 4 and send it in Telegram to @tdlib_bot to know what exactly happens.

**Comment by micheleselea** [comment]
Can a chat_id of a created secretchat change? I cannot understand why I have problem judt with iphone and not with android.

**Comment by micheleselea** [comment]
Chat not found is a server reply or can be a tdlib internal status? I'm wondering if can be related to the configuration I use to avoid all possible data saved in db

**Comment by levlam** [comment]
A chat_id can't change.

It could be related to disabled message database. If message database is disabled, then you must create the chat using `createSecretChat` method before it can be used.

**Comment by micheleselea** [comment]
Ok let's view a time sequence:

- I create a new SecretChat

- I receive `updateSecretChat` -> `secretChatStateReady` I obtain secret_chat_id

- I have to call `createSecretChat` in order to obtain id_ (chat_id) that is used to send message

So now it's all working fine, I have the chat working. Now I suppose that all should work fine if nothing change.
Suppose now I restart the tdlib client. I have a list of the secret_chat_id id_ that my client load at startup, but I have these parameters:
```
use_file_database_=false 
use_chat_info_database_=false
use_message_database_=false

```
So do you think now that some of the id_ that I have before now for TDlib are unknown chat_id? If so, what I should do? Have aI to re-call  `createSecretChat` for all my secret chat in list?

**Comment by levlam** [comment]
Calling `createSecretChat` after restart could help if `use_message_database_=false`.

**Comment by micheleselea** [comment]
So do you think it's better than I call createSecretChat every time I load client on all my secret_chat ids? in order to let Tdlib know the underline chat_id of the secret chat?

**Comment by micheleselea** [comment]
consider that I can have 1000 or more secret_caht_id, it's ok to call createSecretChat 1000 times? or there are limitations?

**Comment by levlam** [comment]
It is ok, but it is better to call it before first usage.

**Comment by micheleselea** [comment]
Yes I already call the `createSecretChat` before the first usage when new secret chat is created.
My point was about call `createSecretChat` for all secret_chat_id when I start the client, and so before the first usage of secret chat. I'll try that and let you know...I hope server does not ban me if I do a lot of `createSecretChat` requests

**Comment by micheleselea** [comment]
ok I try with createSecretChat on start using my chat_id saved and I see a lot of
```
error {
  code = 6
  message = "Chat info not found"
}
```
what do you think is related to? use_chat_info_database_=false?

**Comment by micheleselea** [comment]
do you think that now chat id that gives me "Chat info not found" will give me the "chat not found" when I'll try to send mesage?

**Comment by micheleselea** [comment]
Yes @levlam I verified and the chat_id that gives me "Chat info not found" are the same id that gives me error on send message. So I think I'm stuck with the problem, I do not understand why I end up with that error. Can be just boolean parameters on stardtup?

**Comment by levlam** [comment]
You must have chat info database enabled to be able to successfully call `createSecretChat`. The chat info database shouldn't be too big.

**Comment by micheleselea** [comment]
So I should configure tdlib as

use_file_database_=true
use_chat_info_database_=true

What informations are stored in chat info db? Are stored in sqlite format? Are encrypted?

**Comment by levlam** [comment]
Information about users, basic groups, supergroups, secret chats.
Yes, this is an encrypted SQLite database.

**Comment by micheleselea** [comment]
ok anyway, I think the documentation should mention that if you disable use_chat_info_database_ SecretChat ID can disappear. I can't understand what is the logic because it happens to me only with iPhone and regadless from when the chat is created

**Comment by levlam** [comment]
The current description `the library will maintain a cache of users, basic groups, supergroups, channels and secret chats` means exactly that without the chat info database, you can't get these objects by their ID after restart.

**Comment by micheleselea** [comment]
Ok but I expect the behavior is the same for all devices id. If I use the use_chat_info_database_=false and I see than when I restart I can use without problem some SecretChat and some other no it make me think the problem is not the use_chat_info_database_=false
Anyway I'll use with true

**Comment by CompSciFutures** [comment]
See https://github.com/tdlib/td/issues/2780
