### ISSUE TITLE
chat not found

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#1027]
Hi. I use `SearchForPublicChat` , `JoinChat` for joining the chat and I save the `chatId`. But sometimes when I restart the client and I use `TdApi.GetChat` method (using `chatId`) I receive error that `chat not found`. Why does that happen?

**Comment by levlam** [comment]
There can be a lot of reasons. This question can't be answered without TDLib logs with verbosity level 4.

**Comment by yasharzb** [comment]
Let me describe. I restart my client and I want to get message from chat with and Id. But when I use the `TdApi.GetMessage(...)` method I get this error :`{"code": 6, "message": "Chat not found"}`. So solved it by `TdApi.SearchPublicChat` and the `TdApi.JoinChat` but obviously I've been there before and this solution doesn't seem sensible.
And -because of that maybe - I get error `{"code":429,"message":"Too Many Requests: retry after 13078"}`. Can you please explain what does that mean and where did it come from?

**Comment by levlam** [comment]
You don't need to call `TdApi.JoinChat` at all. The flood wait is likely to be cause by too often calls to `TdApi.SearchPublicChat`. To be able to use chat_id after restart, you need to enable message database.

**Comment by yasharzb** [comment]
What do you mean by "enable message"? Imagine I wanna get the message(after restart) what should I do?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/791.

**Comment by yasharzb** [comment]
I saw that. So you mean using `TdApi.GetChats(....)` before getting message? If that what should be the value of `offsetOrder` and `offsetChatId`?

**Comment by levlam** [comment]
The linked issue contains a lot of answers, which explain all possible cases and ways to resolve them. Calling GetChats is not a reliable option usually.
