### ISSUE TITLE
error message 400 with SecretChat

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#1028]
For one chat it happens that on sending message I receive this:

error {
  code = 400
  message = "Have no write access to the chat"
}

What is the reason? I mean, it's a temporary problem? Or that chat will never be writeble?

**Comment by levlam** [comment]
You need to check `secretChat.state` to know whether it is `secretChatStateReady`. You can't send messages to a `Pending` or a `Closed` secret chat.

**Comment by micheleselea** [comment]
Ok that was a SecretChat active and running and I already used it to send message. I think that is another strange behavior like "chat not found"
Probably is always related to chat info db. I don't have managed to using info db yet, I will, because probably chats cannot be correctly handled without it, at least SecretChat

**Comment by levlam** [comment]
Couldn't it be `Closed` by the other side.

**Comment by micheleselea** [comment]
could...but if so it's really another kind of problem because means I did not received the secretChatStateClosed state that let me remove the closed ID...so I hope it's not that case.
So basically the error "Have no write access to the chat" means the chat does not exists (because keep in mind if it's there I was able to send message to), ah than I just have to remove it, correct?

**Comment by levlam** [comment]
No. "Have no write access to the chat" means that the chat esists, but it is Pending or Closed. In your case it means that the chat was closed. You should have received `updateSecretChat` with the `secretChatStateClosed` before this response.

**Comment by micheleselea** [comment]
mmmm....very strange because I don't see the reason why I do not received the closed state. Anyway I think that I have to set up client to use chat_info db otherwise I can't be sure where is the problem

**Comment by micheleselea** [comment]
Using
```
use_file_database_=true
use_chat_info_database_=true
```
I never end with a "Have no write access to the chat" or "chat not found" errors.
I think at least with SecretChat that two params MUST be true
