### ISSUE TITLE
can not received sms code in production config

### ISSUE THREAD

**Issue by kitoytimmy** [tdlib/td#1031]
I have encountered this problem. I use example of tdlib c#,and can not received sms code.  The updateinfo like following,but i cannot received the smscode, even if i change three phone number. I use the number in OpenTI.ClientApi( another C# telegram apl lib), I received the sms code.

And in the test config of tdlib ,i use 11111 as sms code , i get the authorizationStateReady .

[production]
authorizationStateWaitCode {
  code_info = authenticationCodeInfo {
    phone_number = "+**********"
    type = authenticationCodeTypeSms {
      length = 5
    }
    next_type = null
    timeout = 0
  }
}

**Comment by kitoytimmy** [comment]
Did someone encountered this problem?

**Comment by kitoytimmy** [comment]
I have sent tdlib.log  to @tdlib_bot, it seem the bot is in work.

**Comment by kitoytimmy** [comment]
After 1 hour, i received 3 sms code.

**Comment by levlam** [comment]
In the log everything works as expected. Probably, you was detected by the antiflood system because of many authorizations and banned from the future authorizations.

**Comment by kitoytimmy** [comment]
thanks a lot . i guess  i will encounter this problem in the future.

**Comment by Mashi-91** [comment]
same error.
