### ISSUE TITLE
how the check a user is or not a member of a group

### ISSUE THREAD

**Issue by kitoytimmy** [tdlib/td#1032]
this is my procedure:
1)client input username, i use searchPublicChat to getChatID of a group,
2) i  send  fuction GetChatMember with para chatID and userID.

Yes,i got result like this:
 chatMember {
  user_id = 1******6
  inviter_user_id = 0
  joined_chat_date = 1588733337
  status = chatMemberStatusMember {
  }
  bot_info = null
}
It seems can judge whether a user is a member of a group. but! where is the chatID, I can not find the ChatID.

help:
what is the right way to check a user is in a basicGroup/SuperGroup/Channel, especailly you cannot use searchPublicChat to get a basicGroup.

**Comment by levlam** [comment]
If you have access to a chat member list, you can use `getChatMember` to get user's status.
If you don't have access to a chat, you clearly can't receive user statuses.

**Comment by kitoytimmy** [comment]
I still think it should set a field named chatId in chatMember result .
thanks a lot.
close
