### ISSUE TITLE
how can i get testProxy result

### ISSUE THREAD

**Issue by kitoytimmy** [tdlib/td#1033]
I send testProxy before authorization. But i can not get the result by ClientResultHandler. 
The following text is sent to console directly. 
How can i get testProxy result.?
:)
============================================
[ 3][t 4][1588771487.691665173][Td.cpp:3592][#1][!Td][&td_requests]     Receive request 1: testProxy {
  server = "167.71.210.64"
  port = 443
  type = proxyTypeMtproto {
    secret = "7qNjm1VVx3d9iIjxUW4eL6xpbnN0YWdyYW0uZnNqcDUtMS5mbmEuZmJjZG4ubmV0"
  }
  dc_id = 1
  timeout = 120.000000
}
[ 3][t 4][1588771487.693996191][ConnectionCreator.cpp:723][#1][!TestProxyRequest][&connections] Create new transparent proxy connection TestPingDC2
[ 3][t 4][1588771487.694107294][ConnectionCreator.cpp:765][#1][!TestProxyRequest]       Start TLS: TestPingDC2
[ 4][t 4][1588771487.694262981][TransparentProxy.cpp:55][#1][!TestTlsInit][&proxy]      Begin to connect to proxy
[ 4][t 4][1588771487.698523521][BufferedFd.h:198][#1][!TestTlsInit]     Flush write: +517B[left:0B]
[ 4][t 4][1588771487.890404940][BufferedFd.h:189][#1][!TestTlsInit]     Flush read: +512B[total:512B]
[ 4][t 4][1588771487.890616655][BufferedFd.h:189][#1][!TestTlsInit]     Flush read: +643B[total:1155B]
[ 4][t 4][1588771487.890892744][TransparentProxy.cpp:37][#1][!TestTlsInit][&proxy]      Finish to connect to proxy
[ 3][t 4][1588771487.892082691][RawConnection.cpp:56][#1][!TestProxyRequest]    Send handshake packet:

**Comment by levlam** [comment]
`testProxy` is an ordinary request and will return result as such.

You specified timeout of 120 seconds, so if the proxy doesn't work, you shouldn't expect еру response before 120 seconds pass.

**Comment by kitoytimmy** [comment]
@levlam ,thanks. By the way, in this request ,how can i get the correct dc_id. or just input dc_id=1

**Comment by kitoytimmy** [comment]
i set timeout value=5 or 10, only received the result 

ok {
}

**Comment by levlam** [comment]
This is the result.

Didn't you want to use `pingProxy` instead?
