### ISSUE TITLE
Issue with unreadCount and isMarkedAsUnread

### ISSUE THREAD

**Issue by Xiryl** [tdlib/td#1034]
I'm working on android (java)
When I catch the `GetChatHistory` event, I check if there are unread messages by checking if `Chat.lastReadOutboxMessageId` field is the same as `Chat.lastMessage.id`.

I have an issue with the official Telegram chat (the one that gives me the code for the 2fa): even if I read the chat on the telegram client for android and the client for mac os and web browser, when i get the chat from `GetChatHistory` event, the `Chat.unreadCount` is still 1.  I understand that if the `Chat.unreadCount` equals to 1, it indicates that there's an unread message in the chat (but that actually on every client telegram I've read and it's not marked as unreaded message).

So I also tried to look at the isMarkedAsUnread field, but since it is `false`, this field also indicates that the chat has been read.

So I wanted to know if the `Chat.unreadCount` field is correct or a bug, and how can I tell if there are actually unread messages on the cat.

**Comment by levlam** [comment]
> Chat.lastReadOutboxMessageId field is the same as Chat.lastMessage.id

Chat.lastReadOutboxMessageId is not guaranteed to be an identifier of an existing message. Read messages are the messages with `messageId <= Chat.lastReadOutboxMessageId`.

> So I also tried to look at the isMarkedAsUnread field, but since it is false, this field also indicates that the chat has been read.

isMarkedAsUnread can be true, only if unreadCount == 0. Unread count counts only unread messages.

> So I wanted to know if the Chat.unreadCount field is correct or a bug, and how can I tell if there are actually unread messages on the cat.

The `Chat.unreadCount` field is correct. Some Telegram messages are local and aren't synchronized between clients. Service notification about logging in on another device is one of them. It needs to be read on every client independently, so the intruder can't mark it as read or delete. There are a lot of other ways to get local messages, including `addLocalMessage` method.

A chat has unread messages if `Chat.unreadCount` > 0.

**Comment by Xiryl** [comment]
Hi @levlam, thanks for the response.

In my app I just want to keep the unreaded messages. From all chat everythings works fines, but I've this problem on the Telegram chat (and an another chat channel).  

In the case of the Telegram chat, wich tells me that `Chat.unreadCount = 1` how can I know that the message is local and i can assume that is read? Could I assume that if `messageId <= Chat.lastReadInboxMessageId` even with `Chat.unreadCount = 1` the message is readed? But also in this case, I have `Chat.unreadCount = 1` and the `messageId` grater than `Chat.lastReadInboxMessageId` and `Chat.lastReadOutboxMessageId` (wich means that is a newer message). 

So, how can I check if the message is local and I can assume that is marked as read on the client?
Thanks.

**Comment by levlam** [comment]
If `Chat.unreadCount == 1` then the message is not read. The last messageId can't be <= Chat.lastReadInboxMessageId if `Chat.unreadCount == 1`. The data provided by TDLib is right and consistent.

**Comment by Xiryl** [comment]
Sorry, i confuse >= with <=.

For the Telegram chat, I have the following status
```
Chat.lastReadInboxMessageId = 248291262464
Chat.lastReadOutboxMessageId = 14389608448
Chat.lastMessage.id = 248291262466
Chat.lastMessage.content.text = "New login..."
Chat.isMarkedAsUnread = false
Chat.unreadCount = 1
Chat.id = 777000
```

Where, `unreadCount = 1` and `lastMessage.id >= lastReadInboxMessageId`. And that's right, the TDLib tells the that there is an unread message (wich is the message that comes after the 2fa code "_New login. Dear XXX, we detected a login into your account from a new device on dd/mm/yyyy at hh:mm:ss UTC."_)
With that, how I do with the other chats, I fetch the last message (id: 248291262466) with `GetChatHistory` and save to my unreadedMessages List.

The difference between the other chat and the Telegram chat is that, if on the client i read the message, I received an update on the TDLib which update the `unreadCount` to 0 for the appropriate that (and with that I'll remove the message from my unreadMessages List). With the Telegram chat I don't have any update for the last message (which is got readed on the clients) and it stills remain on my application marked as unread.

You tell me that the message could be a local message: how can I understand that the message that's marked as unread is actually local, so can I mark it as read on my messages list of the application?

**Comment by levlam** [comment]
"local" message means a message existing only on a specific device. It exists only on the current device and is effectively unread until it isn't read on the every device. If you don't want to show such messages to the user, you can just hide messages from the chat 777000, which will cover most of the cases.

**Comment by Xiryl** [comment]
ok! thank you so much for your help!

**Comment by Xiryl** [comment]
I'm reopening the issue because I'm facing with the same problem of the Telegram chat with a SuperGroup Channel chat. The `unreadCount` is `1`, and the message on all client is marked as read (even if I clear all the cache and data and try to make the first login, the message is marked as read, how can other client can be know that if the unreadCount is still to 1?). 

You told me that "local messages" are handled by the client. But how all other telegram client know that the message is readed even if is marked as unreadCount? 

I need to use a collection list in my client to store the messages that the user read instead of using the unreadCount value and check the id every time to avoid this problem? I search on the tdlib sdk a solution but I don't found anything.

And, what defines a message as "local"? Why the last message of a supergroup channel is "local"?

**Comment by levlam** [comment]
If the unreadCount is 1 in TDLib, then there is 1 unread message in the chat. You can verify that by calling getChatHistory. Where do you see unreadCount 1 and where do you see that the message is read?

**Comment by Xiryl** [comment]
1. I call `TdApi.GetChats` for get the chat ids
2. Inside `TdApi.Chats.CONSTRUCTOR`, for each `chatId` I call `TdApi.GetChat(chatID)`
3. Inside `TdApi.Chat.CONSTRUCTOR` I get the `TdApi.Chat chat` object where I see that the chat type is a supergroup, and the `isChannel` is set to true; also the `chat.unreadCount` is `1` and if the `chat.lastReadMessageId < chat.lastmessage.id` (which is true because unreadCount is 1) I call the GetChatHistory, where i get the last message, which is the last unreaded message.

When in the other chats, like for example here, there is a message marked as unread and from the web client I read it, an event in the library is activated that tells the chat has been updated and I see the new value of unreadedCount = 0 removing the messages of the chat from my unreaded messages list.

Instead, in this chat, as in the Telegram one, from the clients the message is marked as read and even if I tried to reopen the chat (to make it look like I read the message) no event is triggered, and I don't find a way to know how to mark the message as read even if is "local" or already readed

**Comment by Xiryl** [comment]
I exit and re-enter the channel, and the value of `unreadcount` is now at 0, correctly. What could have been the problem? Am I to expect that could happen with other chats or channels?

**Comment by levlam** [comment]
If you read a message from another client, then there can be a delay before it will be marked as read on the other clients. But if both clients have reliable network connection, the delay rarely exceeds 5 seconds.

**Comment by Xiryl** [comment]
Thank you
