### ISSUE TITLE
failed: unable to open database file

### ISSUE THREAD

**Issue by EbrahimING** [tdlib/td#1037]
[ 0][t28][1588918682.959041119][SqliteConnectionSafe.cpp:18][#77][!KV] Can't open database of size 1154048: [Error : 0 : Can't open database: [query:SELECT count(*) FROM sqlite_master] to database "/data/data/org.thunderdog.challegram/files/tdlib79/db.sqlite" failed: unable to open database file]

**Comment by levlam** [comment]
How much accounts and which Android version do you have?

**Comment by EbrahimING** [comment]
Hi, It's Android 8.0 O (26) . More than a hundred accounts ...

**Comment by levlam** [comment]
Then this is a duplicate of https://github.com/tdlib/td/issues/902. This can't be fixed on TDLib's side. You need to wait for Telegram X update with the fix, or update to Android 9.0+ if possible.

**Comment by EbrahimING** [comment]
How much accounts does Telegram X support and when will that update arrive?

**Comment by levlam** [comment]
Less than 50 should work.

Noone knows when the issue will be fixed.

**Comment by levlam** [comment]
Closing as a duplicate.
