### ISSUE TITLE
How to detect if a message comes from a group?

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#1042]
When I get an updateNewMessage event, is there a way to detect if this messge comes from a group or from a 'normal' user? For channels there is the field is_channel_post_ in message object, why there so not such field for groups?

**Comment by levlam** [comment]
`is_channel_post` field is redundant curently, because every message has `chat_id` field.

**Comment by MalteToenjes** [comment]
Okay but still I would like to distinguish between message from group and message from a 'normal' chat...is there no way?

**Comment by levlam** [comment]
`chat_id` gives you complete information about the chat including its type.
