### ISSUE TITLE
Client connection through an HTTP proxy does not properly format IPv6 addresses

### ISSUE THREAD

**Issue by AmoVanB** [tdlib/td#1043]
Hi,

We are using the library to contact Telegram servers through an HTTP proxy. When connecting to the proxy, the library does not properly format IPv6 addresses and sends the following HTTP request:

```
CONNECT 2001:67c:4e8:f004::a:443 HTTP/1.1
Host: 2001:67c:4e8:f004::a:443
```
Our proxy can't properly parse such a request. Indeed, if I'm not mistaken, according to IETF standards (https://tools.ietf.org/html/rfc7230#section-5.4 and https://tools.ietf.org/html/rfc3986#section-3.2.2), IPv6 addresses must always be surrounded by square brackets (to avoid the confusion with the `:` that announces the port number).

The request sent by the client should hence rather look like that:
```
CONNECT [2001:67c:4e8:f004::a]:443 HTTP/1.1
Host: [2001:67c:4e8:f004::a]:443
```

The problem seems to come from https://github.com/tdlib/td/blob/master/tdnet/td/net/HttpProxy.cpp#L23 where the HTTP CONNECT request is built. 

Wouldn't a diff like (or something in the same vein, I'm not sure about all the available helper methods)
```diff
diff --git a/tdnet/td/net/HttpProxy.cpp b/tdnet/td/net/HttpProxy.cpp
index b604e2e3..bc5716f3 100644
--- a/tdnet/td/net/HttpProxy.cpp
+++ b/tdnet/td/net/HttpProxy.cpp
@@ -20,7 +20,13 @@ void HttpProxy::send_connect() {
   CHECK(state_ == State::SendConnect);
   state_ = State::WaitConnectResponse;
 
-  string host = PSTRING() << ip_address_.get_ip_str() << ':' << ip_address_.get_port();
+  string host;
+  if (ip_address_.is_ipv6()) {
+    host = PSTRING() << '[' << ip_address_.get_ip_str() << ']' << ':' << ip_address_.get_port();
+  }
+  else {
+    host = PSTRING() << ip_address_.get_ip_str() << ':' << ip_address_.get_port();
+  }
   string proxy_authorization;
   if (!username_.empty() || !password_.empty()) {
     auto userinfo = PSTRING() << username_ << ':' << password_;
```
solve that? What do you think? 

Cheers!
Amaury

**Comment by levlam** [comment]
You are absolutely right that an IPv6 address must always be surrounded by square brackets in CONNECT requests.

The proposed fix is also correct. I will gladly accept it if you send it as a pull request. Or if you prefer, I can apply the fix myself.

**Comment by AmoVanB** [comment]
I created the pull request: https://github.com/tdlib/td/pull/1046

Just a side note: the proposed change is quite "specific" because that is the only place in the code that seems to impact our use case, but maybe are there other places where a similar problem happens? This is something I don't know, but I'm just raising your attention on that before the issue gets closed! :)

**Comment by levlam** [comment]
Yes, some other places are probably affected, but I will fix them later myself.

**Comment by levlam** [comment]
Thanks, @AmoVanB!
The pull request was accepted. Other affected places are also fixed in master.
