### ISSUE TITLE
DownloadFile - get bytes array and give directly to client, not waiting file being downloaded

### ISSUE THREAD

**Issue by Teramaks** [tdlib/td#1047]
Im creating web Telegram application using Spring Boot. When I download file its firstly download to server where my app deployed, but I want client gets file directly from telegram server. Is it possible?

**Comment by levlam** [comment]
Only those who sent request to Telegram server can receive the response. But this doesn't prevent from using a partly downloaded file. You can use `readFilePart` to read a part of downloaded file and handle `updateFile` to know, which parts of the file has already been downloaded.
