### ISSUE TITLE
No documentation on building documentation

### ISSUE THREAD

**Issue by mgrandi** [tdlib/td#1049]
according to this: https://core.telegram.org/tdlib/docs/#building  , it says that PHP and doxygen are needed for documentation, but doesn't explain how to actually generate the documentation. 

I had to look through the source of `DoxygenTlDocumentationGenerator.php` to figure out that you just simply run `doxygen` in the root `td` folder and it generates it, although it doesn't look like the HTML documentation that is on the website (say, https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1accept_call.html for example)

Maybe add a note about it on the building page? :)

**Comment by levlam** [comment]
PHP is needed for source code documentation generation. It is generated automatically if PHP is found, so there is nothing to explain there.

`doxygen` is needed for HTML documentation generation for C++ interface. Its usage is described on its site: http://www.doxygen.nl/manual/doxygen_usage.html. Giving that there is pregenerated on-site documentation and outside of IDE it is simpler to use documentation directly from td_api.tl, doxygen is hardly needed to anyone.

The on-site documentation is generated by Doxygen, but uses custom header, footer and CSS styles suitable for Telegram's site.

**Comment by mgrandi** [comment]
Correct me if I'm wrong but I don't think doxygen is run from cmake, only TiDocumentationGenerator.php (or the other php file whose name I forget), which seems to only edit the td_api.h file to add additional stuff that doxygen uses. Unless there is a cmake target I'm not using, I had to manually run `doxygen` myself to generate the HTML documentation

I was wanting to make a https://kapeli.com/dash docset for the TDLib classes as it's much faster that going to the class list every time, but seeing how the doxygen generated documentation is very....c++ centric, I might just make my own that focuses on the TDLib types and not the c++ implementations

**Comment by levlam** [comment]
`doxygen` is not run at all, because it would take a lot of time and we don't expect anyone to need the HTML documentation for С++-code.

If you want to generate a documentation in some other format, it would be much simpler to do that directly from td_api.tl.
