### ISSUE TITLE
MessageState is not full?

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#105]
Hello!

Trying to find method to display message sending state (sended, one check for recieving via server, two checks for reading by recepient). But message object contains only two states - [Failed and pending.](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_message_sending_state.html)

How to get message state?

**Comment by levlam** [comment]
The second check can be found by comparing message.id with chat.last_read_outbox_message_id.

**Comment by blacksailer** [comment]
And if null then message has single check?

**Comment by levlam** [comment]
Yes. If a message is outgoing and its sending_state is null, than the message has at least 1 check.

**Comment by blacksailer** [comment]
Thanks!
