### ISSUE TITLE
Missing tags for releases

### ISSUE THREAD

**Issue by xvitaly** [tdlib/td#1052]
Can you create Git tags for releases, please? GNU/Linux maintainers need them to build and push updates to repositories.

**Comment by levlam** [comment]
The latest release was 1.6.0. The patch versions 1.6.1-1.6.4 can be considered as preview versions before actual 1.7 is released. See also https://github.com/tdlib/td/issues/913 for more details.

**Comment by xvitaly** [comment]
You can just mark them as pre-releases using GitHub releases feature.

**Comment by levlam** [comment]
They aren't fully tested and go through pre-release testing cycle, so there is no specific commit which can be marked with a tag suitable for production. They aren't a real pre-release versions either, because there will be a lot of possibly breaking changes before the actual release.

**Comment by isopen** [comment]
There should be no preliminary releases in production. Rather, it’s alpha that is better not to use in production. @levlam speaks on TOP!

**Comment by askovpen** [comment]
getMessageThread and other functions in production (official client). why here is alpha?

**Comment by TrueCarry** [comment]
Even if you treat last version as alpha/preview, libs depend on them. Can you at least create releases for last commit in specific version? For example airgram states that it need tdlib@1.6.9 built from master to work, but code from master builds as 1.6.10 and missing td_create_client makes it unusable. I've tried building commit that changes 1.6.8 to 1.6.9 and it returns same error.

Maybe every lib author should state which commit of tdlib to build, but I think it'll benefit everyone if tdlib would be compatible across all commits with same version.

**Comment by levlam** [comment]
Tagged TDLib 1.7.0 version has been released.

**Comment by isopen** [comment]
@levlam Please tell me when will the moment 1.8.0 be ready? Will the tag be released?

**Comment by g000sha256** [comment]
@xvitaly, @isopen
If anyone still needs it, I maintain a [TDLib mirror](https://github.com/g000sha256/TDLib) that auto-syncs with upstream and publishes a [semver tag](https://github.com/g000sha256/TDLib/tags) and a [GitHub Release](https://github.com/g000sha256/TDLib/releases) for every `TDLib` version.

**Comment by chimruiza-collab** [comment]
Hola oye como recupero mi gmail
