### ISSUE TITLE
What kind of RSA is Telegram using?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1053]
Looking at the spec: https://core.telegram.org/mtproto/auth_key#presenting-proof-of-work-server-authentication  
The encrypted data is just said to be encrypted with RSA without further explanation, but from the source code in this repo it looks like RSA PKCS1 OAEP. If this is indeed the case, does it matter which hash function I use when doing the padding for RSA PKCS1 OAEP? If it's not that then, what is it? Just modular exponentiation?

**Comment by levlam** [comment]
RSA is used exactly as written: "a 255-byte long number (big endian) is raised to the requisite power over the requisite modulus, and the result is stored as a 256-byte number."
The data is padded exactly as written in the pevious step: "SHA1(data) + data + (any random bytes); such that the length equals 255 bytes".

You can find RSA encrypt implementation in https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/mtproto/crypto.cpp#L97.

**Comment by isopen** [comment]
Too many questions, but isopen has regulated. You can find many realizations from Telegram.  👍
