### ISSUE TITLE
Tap on inline button

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#1054]
Hello , how can we tap on inline keyboard in telegram-bot ??

**Comment by IRGC** [comment]
i think you need to try getCallbackQueryAnswer 🤔

**Comment by Kia-Pashang** [comment]
> i think you need to try getCallbackQueryAnswer 🤔

![Capture](https://user-images.githubusercontent.com/26571020/82147005-b9558400-9801-11ea-93c1-6ae2778055fb.PNG)

I mean how to select on of these buttons in inline mode ?

**Comment by IRGC** [comment]
See https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/generate/scheme/td_api.tl#L3595

**Comment by IRGC** [comment]
chat_id,message_id you know payload is data of button

**Comment by Kia-Pashang** [comment]
> chat_id,message_id you know payload is data of button

I dont know what is payload would you please explain it for me ?

**Comment by IRGC** [comment]
see here https://core.telegram.org/bots/api#inlinekeyboardbutton
callback_query is the payload

**Comment by Kia-Pashang** [comment]
> see here https://core.telegram.org/bots/api#inlinekeyboardbutton `callback_data` is the `payload`

would you please show me an example to how to use **payload** ?? i mean as callback_data what should i set ?

**Comment by IRGC** [comment]
in your example did you make the inline button using normal bot api or tdlib ?
if its tdlib then you need to see this https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/generate/scheme/td_api.tl#L771 data param
if its normal bot api see this  https://core.telegram.org/bots/api#inlinekeyboardbutton  callback_data param

**Comment by Kia-Pashang** [comment]
> in your example did you make the inline button using normal bot api or tdlib ? if its tdlib then you need to see this https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/generate/scheme/td_api.tl#L771 data param if its normal bot api see this https://core.telegram.org/bots/api#inlinekeyboardbutton callback_data param

i use cli bot with telegram-bot and i want to on a button of inline message with my cli bot

**Comment by IRGC** [comment]
can you post here example code you are using to send the message with the button?

**Comment by IRGC** [comment]
when you receive a message that has inline buttons then you need to check the reply_markup of the message  which contains replyMarkupInlineKeyboard https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/generate/scheme/td_api.tl#L806 inside the replyMarkupInlineKeyboard for each button there is inlineKeyboardButton   https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/generate/scheme/td_api.tl#L771 which contains the data of button. If you want to click/tap on the button  you need to put that data in`CallbackQueryPayload    then use that in  `getCallbackQueryAnswer https://github.com/tdlib/td/blob/f2cb3afaef62f2dba2a0dc3dc63e374beabcb2df/td/generate/scheme/td_api.tl#L3595

its hard to explain if you don't know basics of .tl  🤔

**Comment by rnyPlanet** [comment]
> Hello , how can we tap on inline keyboard in telegram-bot ??

https://stackoverflow.com/questions/56923326/how-to-answer-on-replymarkup-using-telegram-java-tdapi

try this. maybe u know how to tap on ReplyKeyboardMarkup button?)
