### ISSUE TITLE
addProxy and removeProxy took too long

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1055]
This is a bit unfriendly to bot. Every add or remove uses about 100ms.

**Comment by levlam** [comment]
This is not possible. Those are local requests, which return response immediately. The problem is somewhere else.

**Comment by nekohasekai** [comment]
@levlam I retested it with the latest commit and it does use 100ms

![image](https://user-images.githubusercontent.com/56506714/82886967-e16b8280-9f79-11ea-90b6-fe24069e8942.png)

**Comment by nekohasekai** [comment]
Ok this is not a problem, I solved it using asynchronous

**Comment by levlam** [comment]
@nekohasekai This looks like an overhead of interaction with TDLib in your wrapper. Probably, it fetches responses only every 100 ms.

**Comment by nekohasekai** [comment]
@levlam No, my delay is 10ms, other methods return normally, but the proxy-related functions are not.
