### ISSUE TITLE
error when searchChatMessages: receive 27 valid messages out of 26 in 27 messages

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1056]
```
[ 1][t 4][1589817461.682636023][MessagesManager.cpp:8244][#1][!Td]      Receive 27 valid messages out of 26 in 27 messages
```
[log.txt](https://github.com/tdlib/td/files/4645229/log.txt)

**Comment by levlam** [comment]
The server returned wrong total count of messages. TDLib fixed the total count to the correct value and outputed a warning about wrong server response. Then the client received a correct response from TDLib. Everything works as expected there in TDLib.
