### ISSUE TITLE
Telegram uses webp pictures as stickers

### ISSUE THREAD

**Issue by feralheart** [tdlib/td#1057]
### Steps to reproduce
1. Send a webp image
2. ???
3. Profit

### Expected behaviour
When send in a webp it's an image and you can open it, save it and zoom in it

### Actual behaviour
It's a sticker and you see as big as the other stickers even it's a whole page image.

**Comment by levlam** [comment]
This is current expected behavior. If you want it to be changed, you can send general suggestions through in-app support or by menthioning @telegram on Twitter.
