### ISSUE TITLE
Send file to saved messages (favourites)

### ISSUE THREAD

**Issue by Teramaks** [tdlib/td#1058]
I found SendMessage function but there are too many classes I need to specify, and how to define InputMessageContent? Or maybe there is fresh example on Java?

**Comment by Teramaks** [comment]
`InputFileLocal file = new InputFileLocal(
        "/local.path");`
    `InputMessageDocument document = new InputMessageDocument(file, null, null);`

**Comment by isopen** [comment]
InputMessageContent resembles a base class. I think it's worth a look at the implementation.

**Comment by levlam** [comment]
@Teramaks Yes, this looks like a right way to specify sent file.
