### ISSUE TITLE
Chat history is not up-to-date

### ISSUE THREAD

**Issue by MatthewKirik** [tdlib/td#1059]
Hi! I'm trying to monitor channel state via tdlib (i.e which msgs are actually there and which were deleted). 

The problem is "getChatHistory" request returning messages which were deleted as if they are still in channel. I don't see a way to check if the message is deleted. As I understand messages are cached in db, but the problem still occurs even with "useMessagesDatabase" set to false.

Can you please explain me where I get it wrong and what are the possible sollutions to this?

**Comment by levlam** [comment]
You need to join the channel and process `updateNewMessage`/`updateDeleteMessages` instead of constantly using `getChatHistory`.

**Comment by MatthewKirik** [comment]
I'm currently trying to process updateDeleteMessages and a lot of updates are lost. I get like 25% of them. Why so?

**Comment by levlam** [comment]
Users aren't supposed to receive all updates in supergroups/channels. The state is synchronyzed only when the user opens the chat.

**Comment by MatthewKirik** [comment]
What does it mean "open the chat" in the terms of tdlib?

getChatHistory returns old state even after getChat/getChats
updateDeleteMessages not coming

How do I get actual state of db after all? This is absolutely unclear.

**Comment by levlam** [comment]
"open the chat" means to call the `openChat` method.

**Comment by MatthewKirik** [comment]
So can I call opanChat for a list of channels one by one and receive all the updates? Anyway thaks for the help, this is pain in the ass.

**Comment by levlam** [comment]
You can, but it is not supposed to have more than one chat open at the same time, so you could be flood-limited by the server.

**Comment by MatthewKirik** [comment]
Thank you for your clarifications! Hope this will solve my issue.
