### ISSUE TITLE
[Exploratory] Possibility of programmatic voice call

### ISSUE THREAD

**Issue by devxpy** [tdlib/td#106]
Hello, I want to do a voice call from pure python code. Is something like that even possible?
I didn't see anything like that in the API.

**Comment by levlam** [comment]
You can receive new calls through updateCall and create new calls using createCall, but calls encrypted data transfer isn't handled by TDLib. You will need to use [libtgvoip](https://github.com/grishka/libtgvoip) for that.

**Comment by devxpy** [comment]
Does this provide the same level of quality as telegram apps? I haven't seen such call quality ever, over the internet.

Its for an IOT project and I will use this on a raspberry pi.

**Comment by cosmonawt** [comment]
libtgvoip is used internally by the apps, so it will likely be the same quality.

**Comment by devxpy** [comment]
Ok, i will see if i can fashion a python wrapper for this

**Comment by levlam** [comment]
Yes. All Telegram apps use libtgvoip for voice calls.
