### ISSUE TITLE
SecretChat

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#1060]
Hi @levlam I have one strange behavior I want to describe you to understand what can be a solution.
In my application I have hundreds of Secretchat working. So my TdLib client use all the chat without problem. One particular SecretChat, that was working without problem, start having some notification problem. When I send a message to that chat the process from my side it's ok, the device receive a notification of new message received but nothing appear on the chat. on the other side if from that secret chat they try to write a message, the message seems to be sent, but on tdlib client I never receive an updateNewMessage notification.
Moreover if I try to do a createSecretChat on that secret chat ID the reply is ok with the information about the SecretChat.
I don't understand if it's a temporary problem of telegram server (happened since 10 Hours) or if the chat is somehow broken I can't figure out how to verify it on my tdlib client: apparently I have no error messages

So just to recap:

1. I have a Secret chat that is working
2. Suddenly the secret chat stop working so the behavior is that
3. I do sendMessage
4. I receive updateMessageSendSucceeded
5. The user receive a system notification of new message but the message is not on the chat
6. I never receive the updateChatReadOutbox with that message read

 I think that for now I have no way to understand that the chat is broken or some problem is there

**Comment by levlam** [comment]
> I don't understand if it's a temporary problem of telegram server (happened since 10 Hours)

Secret chats are peer-to-peer, so this is very unlikely to be caused by the server. Instead this could be a bug in secret chat implementaion in one of the clients. What client is on the other side? Could you collect and send TDLib's log with verbosity level 4 to @tdlib_bot? The log should include sending of an outgoing message and receiving an incoming message.

**Comment by micheleselea** [comment]
Other side is an iPhone 11 pro device os version 13.3.1 with the standard Telegram application taken from the apple store.
I had to restore the chat for security reason so I deleted the secret chat and recreate it. As soon as that happen again (I hope not) I'll do the log collect.
Anyway Keep in mind that tdlib side seems to be ok because the notification of "new incoming mesage" on iPhone appear correctly: but the chat show no messages like it's not downloaded. I'm talk about text messages as well images. Moreover in tdlib I can't receive incoming message notification sent by iPhone secret chat.

**Comment by levlam** [comment]
The problem can be caused by a bug in iPhone implementation of secret chats, but it could be also triggered by something that is sent by TDLib, so the logs from both apps are desirable to find the cause. In most such cases creation of new secret chat resolves the problem.

**Comment by micheleselea** [comment]
Yes indeed the creation of new chat solved the problem. The point here is that the tdlib client is a standalone application so I have to find a way to recognize that condition in order to inform the end user that something wrong is going on his secret chat. I do not have find yet the "check" I'just thinking to check for the read notification, but it's still a weak check

**Comment by micheleselea** [comment]
Today 12 hours  without one connection problem or 429 code.....I think saturday something wrong with connection and or telegram server
