### ISSUE TITLE
How to get only one message from history with message id

### ISSUE THREAD

**Issue by BehzadArabi** [tdlib/td#1061]
I'm only going to get one message from history, but I feel that tdlib is getting more messages from Telegram because more Internet is being used. Is there a way to chat just one message using MessageID from history?

**Comment by levlam** [comment]
Have you tried to use `getMessage`?

**Comment by BehzadArabi** [comment]
I use `getMessages`

**Comment by BehzadArabi** [comment]
Are newer versions of tdlib consuming more internet?

**Comment by levlam** [comment]
`getMessages` allows to get more messages at once.

Network usage should be almost the same for any TDLib version.

**Comment by BehzadArabi** [comment]
Do you have statistics on Internet usage per message? (No photos or files)

**Comment by BehzadArabi** [comment]
Is it possible that when I want to get the information of a message via `getMessages`, tdlib will also receive messages before and after it?

**Comment by levlam** [comment]
You can collect statistics yourself using `getNetworkStatistics`.

**Comment by levlam** [comment]
Is it possible that when I want to get the information of a message via getMessages, tdlib will also receive messages before and after it?

> This is not possible.

**Comment by BehzadArabi** [comment]
> > Is it possible that when I want to get the information of a message via getMessages, tdlib will also receive messages before and after it?
> 
> This is not possible.

This method says the size of the internet usage, but I want to know exactly why my internet usage is so high.

**Comment by BehzadArabi** [comment]
Is it possible for the `OpenChat` method to receive many messages automatically?

**Comment by levlam** [comment]
`openChat` call implies that you need to receive as fast as possible all the updates from the chat, so it definitely can cause some additional network usage.
