### ISSUE TITLE
Connection problems on Linux

### ISSUE THREAD

**Issue by Teramaks** [tdlib/td#1063]
When I use Windows native libraries all goes well, but when run application on Linux I get "Another authorization query has started". Ok well, I fixed it using vpn but now application freezes after some time of working and I need to reload it every time. The same project code. Just native libraries are changed.

**Comment by Teramaks** [comment]
Tested even using Example.java (maybe I have mistaken writing my projects's structure) but no. On Windows all good - On Linux - problems

**Comment by levlam** [comment]
"Another authorization query has started" is always a problem in the application logic.

**Comment by Teramaks** [comment]
Okay, will try to find out where I have been mistaken. But why this object not returns when I test my app on Windows OS?

**Comment by Teramaks** [comment]
Mayb Windows native libraries better) Just cause I got AuthorizationStateReady entering verification code and password and can get messages.
