### ISSUE TITLE
"searchChatsNearby" returning chats from previous search

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1064]
First I searched chats nearby my current location in Moscow.  It returns some relevant chats.

Then I searched chats using some location in Berlin.  It returns relevant chats as well.

However, then I searched again chats nearby my current location in Moscow and TDLib v1.6.4 returned list of chats from Berlin search.

After this, any request to `searchChatsNearby` returns chat list from the Berlin

Is it ok, and Telegram just prevents searching random locations?

Is there a way to reset it, so it will return correct results for my current location?

Thanks

**Comment by levlam** [comment]
Yes, Telegram definitely prevents searching chats nearby from random locations.

If your location is moving too fast, you will be banned for some time, The ban will be lifted itself after some time.
