### ISSUE TITLE
Waveform encoding

### ISSUE THREAD

**Issue by dhgelling** [tdlib/td#1065]
I understand that the number of bars in a waveform for voice notes might vary per client, but I'm wondering how an edge case is supposed to be handled: When encoding the bars into 5 bits, you might be left with 5 or more bits left over in the byte buffer. How do you indicate that these bits don't represent the last bar but instead are just (zeroed) data? Or is it assumed that you chose a number that fits into 8 bits without leaving 5 bits extra?

**Comment by levlam** [comment]
It couldn't be indicated, so as much bits as possible are used. Usually, clients encode 100 bars, so only 4 bits are left in the last byte, which are ignored after decoding. Anyway, zero height is the right height for the bar after the end of the voice message.
