### ISSUE TITLE
updateMessageSendFailed code 400 can't merge files

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#1066]
I received that error message, do you know what can cause it?
the description tells me something about "Different size: 106960 and 111244"

**Comment by levlam** [comment]
@micheleselea Do you use `inputFileGenerated`?

**Comment by micheleselea** [comment]
yes

**Comment by micheleselea** [comment]
expected_size_ differ from size sent?

**Comment by levlam** [comment]
The error means that the same `inputFileGenerated` lead to two different files. Previously the size of generated file was 111244 and now it is 106960.
