### ISSUE TITLE
generate pkgconfig file

### ISSUE THREAD

**Issue by poscat0x04** [tdlib/td#1067]
Some build tools (cabal for example) relies on pkg-config to discover c libraries. Would it be possible to generator this file when building tdlib?

**Comment by levlam** [comment]
It will be added someday, but likely not soon, unless a pull request is provided.
There is a try to generate pkg-config files in https://github.com/tdlib/td/pull/867, but it covers only one TDLib's interface, doesn't specify dependencies correctly for static build and creates a superflous top-level directory. Nevertheless this could be enough for your needs.
