### ISSUE TITLE
Android| Downloading a file

### ISSUE THREAD

**Issue by rben820** [tdlib/td#1068]
Hey everyone,
I'm trying to use TdLib in order to download a file (to an Android device).
I have a few problems when and I'm trying to figure out how to download a file using this library.

I already managed to sign in and to get all the messages and the chats lists, but when I'm trying to download the file, nothing happened.
I used class called `DownloadFile` and `TdApi.GetFile()` But I think that I'm doing that wrong. 
I tried to Google that, but I didn't find anything about how to do that in Android devices (using Java).
I will be more than happy if someone can help me or guiding me how to do that.

Thanks!!

**Comment by levlam** [comment]
Call to the `TdApi.DownloadFile` nethod adds the specified file to a list of files to be downloaded. Then you will receive updateFile updates with information about download progress. When the file is fully downloaded it will have is_downloading_completed field set to true.

You can also set the parameter `synchronous` to true, which causes the `TdApi.DownloadFile` request to return a result only after the download is completed or failed, which should be sufficient for basic usages.

**Comment by rben820** [comment]
> Call to the `TdApi.DownloadFile` nethod adds the specified file to a list of files to be downloaded. Then you will receive updateFile updates with information about download progress. When the file is fully downloaded it will have is_downloading_completed field set to true.
> 
> You can also set the parameter `synchronous` to true, which causes the `TdApi.DownloadFile` request to return a result only after the download is completed or failed, which should be sufficient for basic usages.

Hey, thank you for your help!
I did it! 
But..... I have another question and I will be more than happy if you can help me with that :)
I would like to get the URL link for a specific file, in order to download it on the device (or there is an option to watching the video file even even if it's downloading it?).
I saw a few options to do that:
Using `GetRemoteFile` and/or `RemoteFile` .
Problem is that I am not getting any results from that, the code I use:
`        ChatActivity.client.send(new TdApi.GetRemoteFile("STRING",new TdApi.FileTypeVideo()), new Client.ResultHandler() {
            @Override
            public void onResult(TdApi.Object object) {
            }
        });`

Problem is that I got an error which said `Type of file mismatch` .
What should I do?

Thanks!

**Comment by levlam** [comment]
Telegram files can't be downloaded through HTTP and so they don't have an HTTP link.

"Watching the video file even even if it's downloading it" is a feature of a video player, called streaming. For example, official Telegram clients implemented built-in video players capable of this. `TdApi.DownloadFile` has `offset` and `limit` parameters, which could be used to download only needed part of the file and jump to the requested part of the video, `TdApi.UpdateFile` notifies app about download progress, so the file can be used before it is downloaded. These features are enough to implement video streaming in the app.

**Comment by ranbd4** [comment]
> Telegram files can't be downloaded through HTTP and so they don't have an HTTP link.
> 
> "Watching the video file even even if it's downloading it" is a feature of a video player, called streaming. For example, official Telegram clients implemented built-in video players capable of this. `TdApi.DownloadFile` has `offset` and `limit` parameters, which could be used to download only needed part of the file and jump to the requested part of the video, `TdApi.UpdateFile` notifies app about download progress, so the file can be used before it is downloaded. These features are enough to implement video streaming in the app.

Thank you again for your answer!
I just want to clarify something, when I use `TdApi.DownloadFile` , it starts to download the file, but the file located at 'temp' folder and not as a video file type, and I can't use it. How can I use the file before? Even when I limited the `limit` to 20 MB, the file remains at the `temp` folder.
Only when I set the limit == 0, it worked.

**Comment by levlam** [comment]
The file will be located in `temp` folder under temporary name until it is fully downloaded. This doesn't prevent if from being accessed in any way. But to stream the video, file parts are needed to be downloaded in a special order, so the file is very unlikely to be playable by an external video player

**Comment by rben820** [comment]
> The file will be located in `temp` folder under temporary name until it is fully downloaded. This doesn't prevent if from being accessed in any way. But to stream the video, file parts are needed to be downloaded in a special order, so the file is very unlikely to be playable by an external video player

First of all, thank you very much for your help again :)

I'm trying to understand how exactly it works, I saw a few YouTube videos (in the 'regular' Telegram app) that the temporary files are located under the cash folder and they're ending with `.temp`, while in my app they are ending without any end. I tried to open the temp file with a few different apps, but no one of them opened those files. 
How can I open or play those temp files? Is there anything that I can try to play those videos files before the file is completely downloaded?

**Comment by levlam** [comment]
File name doesn't matter. I don't think that a partly downloaded file can be played by an external player due to reasons stated above. An external player has no chance to correctly play the file, because it doesn't know which parts of the file was already downloaded.

**Comment by rben820** [comment]
> File name doesn't matter. I don't think that a partly downloaded file can be played by an external player due to reasons stated above. An external player has no chance to correctly play the file, because it doesn't know which parts of the file was already downloaded.

If I want to download only part of the file and start playing it, is it possible to do that? I tried to use `TdApi.DownloadFile` with a limit of X MB, but I can't play the file. Can you please help to figure out how to solve this issue? Even if I want to download small pieces of the file every time, how can I get access to the file before it completely downloaded?

Thanks again for your help that your (very) quick responses!

**Comment by levlam** [comment]
The video contains a very old suggestion. Telegram clients can stream video inside the app natively now. They do this using ffmpeg and manual video decoding. You can find the implementation of video streaming somewhere in the source code of official Android app: https://github.com/DrKLO/Telegram. The same can be implemented using TDLib. It is likely that the implementation can be ported with minor changes.

> Even if I want to download small pieces of the file every time, how can I get access to the file before it completely downloaded?

TDLib sends `updateFile` updates with information about partly downloaded file, including path to the file and number of downloaded bytes.

**Comment by rishabhhgupta** [comment]
Hey levlam, how I able to show uploading progress, I try this method
client.send(uploadFile, new Client.ResultHandler() {
                            @Override
                            public void onResult(TdApi.Object object) throws IllegalAccessException {
                                switch (object.getConstructor()){
                                    case TdApi.Error.CONSTRUCTOR:
                                        System.err.println("Receiveanerror:" + newLine + object);
                                        break;
                                    case TdApi.Ok.CONSTRUCTOR:
                                        Log.i("myLogFilee",object.toString());
                                        break;

                                    default:
                                        TdApi.UpdateFile updateFile1 = new TdApi.UpdateFile((TdApi.File) object);
                                            Log.i("uploadinggfILE", updateFile1.toString());





                                }
                            }
                        });

here client is my Client, uploadFile is TdApi.UploadFile

In my log I got output of like 

UpdateFile {
      file = File {
        id = 652
        size = 187218
        expectedSize = 187218
        local = LocalFile {
          path = "/storage/emulated/0/Pictures/RepostForInsta/1654674168199.jpg"
          canBeDownloaded = false
          canBeDeleted = false
          isDownloadingActive = false
          isDownloadingCompleted = true
          downloadOffset = 0
          downloadedPrefixSize = 187218
          downloadedSize = 187218
        }
        remote = RemoteFile {
          id = ""
          uniqueId = ""
          isUploadingActive = true
          isUploadingCompleted = false
          uploadedSize = 187218
        }
      }
    }


I did't get any progess time or I have to make any looping to show progress changes?, please any suggestion!!!

**Comment by rishabhhgupta** [comment]
Thank you for soo quick response, as in the documentation it's give as 
![chrome_WepuYYqUtM](https://user-images.githubusercontent.com/66349860/172630369-507f7dd1-d420-448a-914b-edeef5e62b93.png)

updateFile is used to notify upload progress, but in result i only get file as you mentioned

**Comment by rishabhhgupta** [comment]
are you there levlam, please give some suggestions

**Comment by IRGC** [comment]
@rishabhhgupta you will get similar response that will have `isUploadingCompleted = true` , as file size is around 130kb you will not get many more update. but you will definitely get update that have `isUploadingCompleted = true`. you should log all response inspect one by one.

**Comment by IRGC** [comment]
i suggest you to try to upload large file and log all response and watch the field  `remote.uploaded_size` do some math with `local.downloaded_size `
`progress = ( remote.uploaded_size / local.downloaded_size ) * 100;`

**Comment by rishabhhgupta** [comment]
Thank you for suggestion IRGC, I try with loop and without loop remote.uploaded_size value are not changes, I get same value, no any number changes of uploaded size. Did I miss something? only one data is shown, no any changes of data

**Comment by rishabhhgupta** [comment]
Thank you soo much IRGC and levlam I got my answer, without you I didn't get my answer, love you

**Comment by rishabhhgupta** [comment]
hey @rben820 , which fileid do you use, I get different file in downloading, can you share your uploading and downloading code with me, so i can check what's i'm doing wrong

you can take a look into my issue 
https://github.com/tdlib/td/issues/2013?notification_referrer_id=NT_kwDOA_RrJLMzODM0NjQwMzQ2OjY2MzQ5ODYw#issuecomment-1166415262

thank  you

**Comment by Mashi-91** [comment]
> How I get uploading file progress

First U have to get length of file 
then show it on progress bar.
