### ISSUE TITLE
I have something talk with telegram officer

### ISSUE THREAD

**Issue by domingowensnsoft** [tdlib/td#1069]
Dear officer: 
Why not provider china services support in tdlib. when I using tdlib library to make custom something functional provide to Chinese people use. I found it can't connect in china. OMG. the perfect library can't support china. because I want to use tdlib to develop china's small telegram provide channel and fully asynchronous save messages services. I want to make more and more Chinese can enjoy tdlib provide convenient services. that's why I submit these issue. I want to do that.
best regards.
look forward to reply.

**Comment by levlam** [comment]
Telegram is blocked in some parts of China. You need to use VPN or add a proxy via `addProxy` method to connect to Telegram.

**Comment by domingowensnsoft** [comment]
> Telegram is blocked in some parts of China. You need to use VPN or add a proxy via `addProxy` method to connect to Telegram.

as you say. i can't create VPN. but I can create a database in china. Is the telegram backend server can custom by myself?

**Comment by levlam** [comment]
No.

**Comment by domingowensnsoft** [comment]
thank you for reply.
if I use tdlib library as a server. access really server wrapped it and then request tdlib to get data. maybe can achieve it right? I want to use tdlib fully asynchronous and channel functional.
could you mind tell me what's your idea?

**Comment by levlam** [comment]
No. TDLib is not a server, TDLib is a client, connecting to Telegram servers.

**Comment by domingowensnsoft** [comment]
thanks. I know that. And I found something another library can solve my issues. I will create a server and through TDLib request Telegram servers request data. The data through my server and I send it to the user. look the same as a proxy. Lol
[airgram](https://github.com/airgram/airgram)

**Comment by levlam** [comment]
Airgram - is a very convenient JavaScript wrapper for TDLib. It only provides access to TDLib from JavaScript/TypeScript.
