### ISSUE TITLE
How are Vectors (defined in td_api.tl) getting encoded to json?

### ISSUE THREAD

**Issue by poscat0x04** [tdlib/td#1070]
As defined in td_api.tl, `Vector`s take an anonymous/unnamed parameter with the type `nat` and a list of anonymous parameters with the type `t`. My guess is that `Vector`s are simply encoded as JSON lists but I'm not 100% sure since that implies the implicit `nat` never gets used.

**Comment by levlam** [comment]
Vector is encoded as JSON Array. This is described in JSON interface documenation there: https://core.telegram.org/tdlib/docs/td__json__client_8h.html.

**Comment by poscat0x04** [comment]
oof how could I miss that. sorry for the inconvenience
