### ISSUE TITLE
Client's thread

### ISSUE THREAD

**Issue by Teramaks** [tdlib/td#1071]
I cant create more than 1 client. When create 2nd, its thread just freezes, setting only TdLib parameters and dont go on further. Coding on Java. Can I create more client to provide more users cause Im using Spring Security via session managment.

**Comment by Teramaks** [comment]
`new Thread(client, "TDLib thread").start();`
How do I should define client in new thread and is It possible to use for all clients one thread? Please, I need to resolve this problem very quickly, and what about ExecutorService?

**Comment by levlam** [comment]
You can't simultaneously use the same database directory from 2 or more TDLib instances. One user = one directory = one instance.

**Comment by Teramaks** [comment]
So, I just need to load new native library for new client?

**Comment by Teramaks** [comment]
`
try {
      java.io.File directory = new java.io.File(libDir);
      java.io.File nativeLibrary = FileUtils.getFile(directory, "libtdjni.so");

      Path newLibraryPath = Paths.get(libDir + "lib" + userLogin + ".so");

      try {
        Files.copy(nativeLibrary.toPath(), newLibraryPath, StandardCopyOption.REPLACE_EXISTING);
      } catch (IOException exception) {
        logger.severe(exception.getMessage());
      }

      java.io.File newLibrary = FileUtils.getFile(newLibraryPath.toString());

      logger.info("New instance of native library: " + newLibrary.getAbsolutePath());
      System.load(newLibrary.getAbsolutePath());
    } catch (UnsatisfiedLinkError e) {
      e.printStackTrace();
    }
`
I did like this, but no success

**Comment by levlam** [comment]
If you want to log in as a different user, then yes.
