### ISSUE TITLE
Searching chat for messages with location

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1072]
Is it possible somehow to search chat messages with location as content?

Looks like there is no `searchMessagesLocation` search message filter.

Is there plans to add one?

Thanks

**Comment by levlam** [comment]
The closest thing is `searchChatRecentLocationMessages`.

Indices for message search are added only when strictly necessary and the corresponding filter is needed in the interface of an official client. I'm not aware of plans to add such filter.
