### ISSUE TITLE
Does anyone have a list of the fingerprints for the public keys?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1075]
So I can see the public keys here, and also what looks like a hash, are these SHA1 hashes of the PEM or something? Or are they the SHA1 hashes of the serialized public keys?
https://github.com/tdlib/td/blob/d2b441f812b632baf244f701a3e45cb9c9f6f4ba/td/telegram/net/PublicRsaKeyShared.cpp#L56  
I'm just looking for a precomputed list of the fingerprints for these public keys

**Comment by levlam** [comment]
This isn't a fingerprint. The fingerprint is calculated there: https://github.com/tdlib/td/blob/d2b441f812b632baf244f701a3e45cb9c9f6f4ba/td/mtproto/crypto.cpp#L78.
