### ISSUE TITLE
Unexpected exit with code -1073741571 (0xC00000FD)

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1079]
there is no error level log, it no longer appears after deleting the data, maybe

last line is `[3][t 5][1591159052.329422712][MessagesManager.cpp:17447][#1][!Td] Loaded message of size 1028 from database`

log has been sent to @tdlib_bot

**Comment by levlam** [comment]
Which TDLib version are you using?

**Comment by nekohasekai** [comment]
@levlam [e2fd1c13e9a0fbb21aa2992b7b2b2b4a7e66204a](https://github.com/tdlib/td/tree/e2fd1c13e9a0fbb21aa2992b7b2b2b4a7e66204a)

**Comment by levlam** [comment]
The issue was introduced on May 22 and fixed on May 31. I pushed the latest TDLib 1.6.6, which includes the fix.
