### ISSUE TITLE
🌼Permission required

### ISSUE THREAD

**Issue by isopen** [tdlib/td#108]
```
thr = []
100000000.times do |n|
  thr << Thread.new(n) do |_i|
    td_send({'@type': 'getAuthorizationState', '@extra': 1.01234})
  end
end
thr.each(&:join)
```
If you involve in the scheme all the known "unique network", then you can generally get the meat.
Even worse, when parameters are set for the passage inside api.

As far as I understand you do not mind it? Do you leave this meat at the library level?

Perhaps this is related to this https://github.com/tdlib/td/issues/58

**Comment by arseny30** [comment]
getAuthorizationState is executed locally and do not send any network queries.

**Comment by isopen** [comment]
You made me happy

**Comment by isopen** [comment]
Do you allow to do this with 100000000 numbers? 🌼
