### ISSUE TITLE
How to start create customized telegram application with tdlib ?

### ISSUE THREAD

**Issue by mehrdadMP** [tdlib/td#1082]
I downloaded the tdlib library and plan to design a personalized telegram Application . But the problem is, I don't know exactly where to start. In fact, I first created an activity called "StartActivity" and wanted to design the first page similar to the first page of telegram X Application . (initially, when an account was not yet created, there was only one activity that included a button called "Start messaging" below The screen and View Pager are located in the middle of the screen, and at the top of the screen you can see the phrase "connecting ...").Inside the tdlib project is an "Example" class that contains the Main method. I was going to start with this method to understand the workflow of the program and find the method that would do the "connecting" operation and move it to StartActivity, but I was completely confused and didn't know where to start . Anyone can help me?

**Comment by levlam** [comment]
You need to begin with https://github.com/tdlib/td#examples-and-documentation and especially https://core.telegram.org/tdlib/getting-started for a brief introduction.
