### ISSUE TITLE
music time shifting snippet 

### ISSUE THREAD

**Issue by alighamari** [tdlib/td#1083]
on telegram android & IOS and telegram desktop if you reply a music or video and write a time (like 2:02) it gets like a link and if you click on it it opens the music or video and seek to that exact time
please add this feature.

**Comment by isopen** [comment]
@levlam **Draft** between devices takes a long time.
I think it can be sent here. Check the function between Desktop -> Android.

There is no synchronization in the input field when both clients are in the chat.

**Comment by levlam** [comment]
@isopen In most clients you need to leave the chat to synchronize draft.

**Comment by isopen** [comment]
@levlam Exiting Deskop client on Android, Draft does not come.

**Comment by levlam** [comment]
@isopen You must not close the client, you must close only the chat.

**Comment by isopen** [comment]
@levlam On both devices, close only chat?

**Comment by isopen** [comment]
@levlam gas is not wasted if you close only the chat on Desktop.
On Android, fresh Draft does not come to chat.

**Comment by isopen** [comment]
@levlam I suggest not saving gas. Due to gas savings, synchronization does not work well.

**Comment by isopen** [comment]
> on telegram android & IOS and telegram desktop if you reply a music or video and write a time (like 2:02) it gets like a link and if you click on it it opens the music or video and seek to that exact time
> please add this feature.

@levlam This functional function does not always work in bots on Android and Desktop.
eg: on incoming music files from the bot.

**Comment by isopen** [comment]
@levlam When forwarding messages with reply. No reply **Gas** is emitted.

**Comment by levlam** [comment]
Automatic search for entities of a new type `textEntityTypeMediaTimestamp` was implemented in the latest TDLib version.
