### ISSUE TITLE
Are encoded big integers allowed to have leading zeroes?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1084]
I do realise I'm asking alot of questions about MTProto but this seems to be the place where everyone who knows anything is.  
Just wondering if I can leave leading zeroes in for optimization's sake.

**Comment by levlam** [comment]
Where do you want to keep leading zeros? If you want to properly calculate RSA fingerprint, then there should be no leading zeros in numbers, otherwise the fingerprint will be completely different.

**Comment by faissaloo** [comment]
For example when I send the values pq, p and q for SendReqDhParams

**Comment by levlam** [comment]
I don't think that leading zeroes are allowed there.

**Comment by faissaloo** [comment]
Could you expand on why that might be the case? Just so I can have a better understanding

**Comment by levlam** [comment]
Because it works so. There is no reason to accept numbers with leading zeros in req_DH_params as there is no reason to accept numbers in binary, octal or hexadecimal form there.
