### ISSUE TITLE
Subsequent messages terminate TCP stream?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1086]
Executing `req_pq` runs fine and I receive the data I expect, after processing it accordingly I send `req_DH_params` but upon waiting for the response I find the connection has closed, this also happens if I try sending an additional `req_pq`.  

What could be causing this specifically and under what conditions does MTProto close a TCP connection? Is there some sort of acknowledgement I have to send before my data? Or am I expected to open a new connection?

**Comment by levlam** [comment]
You should receive an MTProto error before the connection is closed. Usually, the error means that you violated the protocol.

**Comment by faissaloo** [comment]
I don't seem to be receiving any error information, the connection literally just closes after it receives my data.

**Comment by levlam** [comment]
The sent data is likely to be completely wrong. You can find handshake examples in https://core.telegram.org/mtproto/samples-auth_key.

**Comment by faissaloo** [comment]
It does look like I'm encoding everything correctly and the request I'm sending is definitely the right size, here's a log of the responses and requests:  
```
REQUEST SENT: eeeeeeee280000000000000000000000000000007037ee5e14000000f18e7ebe303d562b8c4854a7f9debb5403800023
RESPONSE RECIEVED: 0000000000000000018012787037ee5e4800000063241605303d562b8c4854a7f9debb540380002344c3ab94f11a05d26497d1d72165a14a08286f4331ac0a8b0500000015c4b51c02000000029f4ba16d109296216be86c022bb4c3
REQUEST SENT: eeeeeeee540100000000000000000000000000008e37ee5e40010000bee412d7303d562b8c4854a7f9debb540380002344c3ab94f11a05d26497d1d72165a14a045c5cd5570000000470126d03000000216be86c022bb4c3fe00010005eff8b98b855778f4d6151656d6fbe0a47f4dafa407c735fbd950816f513317b56bbdf44a682b22022dba8857016bd4bfa5fe01067fcb4238896844c3d8c8d4dd1a703e804bfba8a0a327bd745b6483eb4474821e7436c4ca7b99eb5758e94e50869db39ae25f4f39eeb35c3ebf86ab06496c9d649889c38f95582bcfa90180d3c7c7ec1c2704240bb9e1bea33189ab4eb5621eac2e7d3f3471707d8d785d38cbf3c779787595ced7e63c35d788f2a2305b703b73a2391e889f6517d07450aaf43a211227dd8e7fcd2b96f6c96d3b9e98d60c639dbc1a9d1970994761a2070d4922e3bb2988d649906f75b3f2c9f2be786ddf58a3cf65c432be0d456aadcf92
END OF TCP STREAM
```

**Comment by faissaloo** [comment]
Is the encrypted checked to ensure it's padded with secure randomness by any chance? It's the only thing I can think of that might be the problem

**Comment by faissaloo** [comment]
Tried it, still broken

**Comment by levlam** [comment]
@faissaloo Random padding should be used only when connecting through dd/ee MTProto-proxies.

**Comment by faissaloo** [comment]
Does that go for this too? https://core.telegram.org/mtproto/auth_key#presenting-proof-of-work-server-authentication  
It says `data_with_hash := SHA1(data) + data + (any random bytes); such that the length equals 255 bytes;`

**Comment by levlam** [comment]
No, this padding must always have specified length.

**Comment by faissaloo** [comment]
Using the auth key tutorial I've managed to verify that I'm generating the correct bytes for p_q_inner_data at least, my prime decomposition is also verified so the only thing I can think that it might be is something to do with the RSA encrypting things wrong.  
Is the padding available for the auth key tutorial? Or would you be able to provide an unencrypted vs encrypted example and the fingerprint for the public key that encrypted it?

**Comment by levlam** [comment]
I can only point you to RSA implementation in TDLib: https://github.com/tdlib/td/blob/f45d80fe16f99d112d545b7cd74ce46342fe3437/td/mtproto/RSA.cpp.

**Comment by faissaloo** [comment]
Hmm, ok I'll take a look at that and try comparing it to my implementation, thanks. Let me know if you want the test vectors once I finish capturing a few results from it.

**Comment by faissaloo** [comment]
How do I `#include` the RSA implementation? `#include <td/mtproto/RSA.h>` doesn't seem to work

**Comment by levlam** [comment]
This is a private header. You need to include all TDLib's source code for that.

**Comment by faissaloo** [comment]
Seems like the RSA is working as intended
![image](https://user-images.githubusercontent.com/8840681/85950567-71c02d00-b955-11ea-9c98-cae4d0486edb.png)

**Comment by faissaloo** [comment]
Actually here's a question, should I be creating a new connection when sending `req_DH_params` or is it ok to continue to use the same connection I used to send `req_pq`?

**Comment by levlam** [comment]
You must not create new connection.

**Comment by faissaloo** [comment]
Does `req_pq_multi` pay attention to the message id? I'm wondering if perhaps my message id implementation is broken and only the second message causes it to fail somehow?

**Comment by levlam** [comment]
In case of incorrect `message_id` you should receive corresponding error from MTProto, not connection close.

You need to choose and use public RSA key corresponding to the given fingerprint. Obviously, you need only one RSA key.

**Comment by faissaloo** [comment]
Ok so it seems like that stuff's not the problem. I went ahead and implemented a ping/pong and it seems to indicate the problem is deeper, when I send pings I don't get a response and after the second ping the stream terminates. I find it strange that I `req_pq_multi` gets a response but `ping` doesn't. I don't need to be authenticated to perform pings right?

**Comment by faissaloo** [comment]
Wait a second, do I not need to send the transport code before every message?

**Comment by levlam** [comment]
As I know, you need to be authenticated by MTProto to use `ping`.

Transport code is sent only once. Then you need to send only packet length before each packet.

**Comment by faissaloo** [comment]
Alright looks like that got it, I was sending the transport code on every request. Thanks a ton.

**Comment by levlam** [comment]
And the server closed the connection because too big packet length was received. Congratulations!
