### ISSUE TITLE
Marking nullable objects with a "Maybe" type instead of the "may be null" comment

### ISSUE THREAD

**Issue by poscat0x04** [tdlib/td#1087]
Right now the td api spec uses comments to mark which fields are nullable. This is undesirable for the following reasons

1. The comments should not effect the semantics of the language.
2. This is quite ambiguous (#1016)

It would be great if we could use a `Maybe` type to precisely describe nullable types. `Maybe`s are commonly used in Haskell to denote optional values. It has 2 constructors `Nothing` and `Just`, `Nothing` takes no values and denotes that the value is not present whereas `Just` takes 1 parameter and denotes that the value is present.

The `Maybe` type can be translated into the following tl code:
```
nothing {t:type} = maybe t;
just {t:type} t = maybe t;
```
With the maybe type, we could distinguish between an array that's nullable and an array of nullable objects:

```
// nullable array
maybe<vector<objectType>>
// array of nullable object
vector<maybe<objectType>>
```

**Comment by levlam** [comment]
These comments describe some guarantees provided by TDLib and should be read as "if the field is not marked as `may be null`, then it is fine to access it without additional checks and report a bug if it is null". These guarantees doesn't differ from any other guarantees provided by TDLib such as `supergroup.member_count` is known before response to `searchPublicChats`, `updateNewChat` is received before `chat_id`, or entities in `formattedText` are valid.  From the other side, TDLib itself doesn't require any such guarantees from the application, in particular, any field in an incoming request to TDLib can be null or omitted.

`Maybe` definitely can be represented in `TL`, but it is very hard to effectively represent generic `TL` types in most programming languages. We don't want to create additional layer of indirection there, so the generated API classes will be the same with and without `Maybe`.

TDLib API has no nullable arrays, so there is no reason to differentiate them from array of nullable objects.

**Comment by ColonelThirtyTwo** [comment]
Having this would be helpful for generating bindings for languages where objects cannot be null, ex. Rust. I have to wrap everything in an `Option`.

**Comment by levlam** [comment]
@ColonelThirtyTwo Yes, we expected that every object can be null when designed the API in this way. In С++ we use `unique_ptr` to represent all objects, so the same is true for the native C++ implementation.

**Comment by poscat0x04** [comment]
@levlam The user does have to interpret `Maybe` as a generic/algebraic data type, they can choose to interpret it as a nullable pointer.
Since virtually everyone checks "may be null" in the comments when generating bindings to tdlib:
https://github.com/fewensa/fantasy/blob/master/fantasy/src/tokenwrap.rs#L74
https://github.com/poscat0x04/tdlib-gen/blob/master/src/Codegen.hs#L68
https://github.com/Bannerets/tdl/blob/master/packages/tdlib-types/src/lib.js#L75
It might be useful to express that in TL instead of in the comments.

**Comment by levlam** [comment]
@ColonelThirtyTwo @poscat0x04 The latest TDLib version documents function parameters, for which null is an expected valid value, with "; pass null ..." phrase. So, if a field isn't marked as "; may be null" or "; pass null", then it can be treated as non-nullable. It is still possible to pass `null` as the value of such fields, because we can't prohibit this in the С++ interface, but the behavior is unspecified, so this possibility can be safely removed in wrappers.
