### ISSUE TITLE
Escaping markdown being passed in to parseTextEntities?

### ISSUE THREAD

**Issue by watzon** [tdlib/td#1088]
So I'm using tdlibjson and attempting to send text that has been parsed with `parseTextEntities`. The problem is, when text needs to be escaped before being passed in to `parseTextEntities` it seems to not work. For instance, when attempting to create an inline mention of a user with special characters in their name:

```
Joey [*NO PMs*] Smalls
```

This text should be escaped before being passed in to an inline mention, no? So the inline mention should look like this:

```
[Joey \[\*NO PMs\*\] Smalls](tg://user?id=1234567890)
```

tdlib seems to be interpreting the slashes literally though. Is there anything I can do about that?

**Comment by levlam** [comment]
TextParseMode type is Telegram Bot API parse mode and it is completely described in the Bot API documentation: https://core.telegram.org/bots/api#formatting-options.

In this particular case you need to remove all ']' chatacters from the name or switch to MarkdownV2.

**Comment by watzon** [comment]
So it's not possible to just escape the ']' characters? I guess I could probably just substitute them with a similar looking character.

**Comment by levlam** [comment]
From https://core.telegram.org/bots/api#markdown-style: "Escaping inside entities is not allowed".

**Comment by watzon** [comment]
Gotcha, alright then. Thanks for the help :)
