### ISSUE TITLE
macOS Catalina build fail

### ISSUE THREAD

**Issue by bluzye** [tdlib/td#1089]
clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

build output:
In file included from /Users/dev/works/td/td/telegram/Td4.cpp:7:
In file included from /Users/dev/works/td/td/telegram/Td.h:9:
In file included from /Users/dev/works/td/td/telegram/files/FileId.h:9:
In file included from /Users/dev/works/td/tdutils/td/utils/common.h:47:
In file included from /Users/dev/works/td/tdutils/td/utils/unique_ptr.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1466:59: error: incomplete type
      'td::NetQueryDispatcher' used in type trait expression
    : public integral_constant<bool, __is_base_of(_Bp, _Dp)> {};
                                                          ^
/Users/dev/works/td/tdutils/td/utils/unique_ptr.h:40:52: note: in instantiation of template class
      'std::__1::is_base_of<td::DialogFilter, td::NetQueryDispatcher>' requested here
  template <class S, class = std::enable_if_t<std::is_base_of<T, S>::value>>
                                                   ^
/Users/dev/works/td/tdutils/td/utils/unique_ptr.h:41:3: note: in instantiation of default argument for 'unique_ptr<td::NetQueryDispatcher>' required here
  unique_ptr(unique_ptr< S > &&other) noexcept : ptr_(static_cast<S *>(other.release())) {

/Users/dev/works/td/td/telegram/Global.h:116:12: note: while substituting deduced template arguments into function template 'unique_ptr'
      [with S = td::NetQueryDispatcher, $1 = (no value)]
    return net_query_dispatcher_ != nullptr;
           ^
/Users/dev/works/td/td/telegram/Global.h:44:7: note: forward declaration of 'td::NetQueryDispatcher'
class NetQueryDispatcher;
      ^
In file included from /Users/dev/works/td/td/telegram/Td4.cpp:7:
In file included from /Users/dev/works/td/td/telegram/Td.h:9:
In file included from /Users/dev/works/td/td/telegram/files/FileId.h:9:
In file included from /Users/dev/works/td/tdutils/td/utils/common.h:47:
In file included from /Users/dev/works/td/tdutils/td/utils/unique_ptr.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1466:59: error: incomplete type
      'td::ConfigShared' used in type trait expression
    : public integral_constant<bool, __is_base_of(_Bp, _Dp)> {};
                                                          ^
/Users/dev/works/td/tdutils/td/utils/unique_ptr.h:40:52: note: in instantiation of template class 'std::__1::is_base_of<td::DialogFilter, td::ConfigShared>'
      requested here
  template <class S, class = std::enable_if_t<std::is_base_of<T, S>::value>>
                                                   ^
/Users/dev/works/td/tdutils/td/utils/unique_ptr.h:41:3: note: in instantiation of default argument for 'unique_ptr<td::ConfigShared>' required here
  unique_ptr(unique_ptr< S > &&other) noexcept : ptr_(static_cast<S *>(other.release())) {

/Users/dev/works/td/td/telegram/Global.h:122:11: note: while substituting deduced template arguments into function template 'unique_ptr'
      [with S = td::ConfigShared, $1 = (no value)]
    CHECK(shared_config_ != nullptr);
          ^
/Users/dev/works/td/td/telegram/ConfigManager.h:30:7: note: forward declaration of 'td::ConfigShared'
class ConfigShared;
      ^
2 errors generated.
make[3]: *** [CMakeFiles/tdcore.dir/td/telegram/Td4.cpp.o] Error 1
make[2]: *** [CMakeFiles/tdcore.dir/all] Error 2
make[1]: *** [CMakeFiles/tdjson.dir/rule] Error 2
make: *** [tdjson] Error 2

**Comment by levlam** [comment]
The mentioned template methods are not used in the specified code and shouldn't be instantiated, so it looks like a compiler bug. We will try to fix this still.

**Comment by bluzye** [comment]
I fix it like this:
return !!net_query_dispatcher_ ;

**Comment by levlam** [comment]
@bluzye 
Does
```
return net_query_dispatcher_ ;
```
works?

**Comment by levlam** [comment]
We can't reproduce the issue with `Apple clang version 11.0.3 (clang-1103.0.32.59)`. Does it reproduce every time with `clang-1103.0.32.62`?

**Comment by isopen** [comment]
@bluzye real-time build https://github.com/isopen/td/runs/766515911?check_suite_focus=true

**Comment by bluzye** [comment]
@levlam When I use:
return net_query_dispatcher_ ;

output:
In file included from /Users/dev/works/td/td/telegram/AnimationsManager.cpp:15:
In file included from /Users/dev/works/td/td/telegram/files/FileManager.h:22:
In file included from /Users/dev/works/td/td/telegram/Location.h:9:
/Users/dev/works/td/td/telegram/Global.h:116:12: error: no viable conversion from returned value of type 'const
      unique_ptr<td::NetQueryDispatcher>' to function return type 'bool'
    return net_query_dispatcher_;
           ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by bluzye** [comment]
> We can't reproduce the issue with `Apple clang version 11.0.3 (clang-1103.0.32.59)`. Does it reproduce every time with `clang-1103.0.32.62`?

yes, I run these commands to build master:
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 ..
cmake --build . --target prepare_cross_compiling
cd .. && php SplitSource.php
cd build
cmake --build . --target tdjson

**Comment by isopen** [comment]
`return net_query_dispatcher_ ;` diff from `return net_query_dispatcher_;`

**Comment by isopen** [comment]
space

**Comment by isopen** [comment]
https://tdlib.github.io/td/build.html?language=C%2B%2B
```
xcode-select --install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install gperf cmake openssl
git clone https://github.com/tdlib/td.git
cd td
git checkout v1.6.0
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target install
cd ..
cd ..
ls -l td/tdlib
```

**Comment by isopen** [comment]
@bluzye Real-time build macos_1.5gb(split_source) https://github.com/isopen/td/runs/767934865?check_suite_focus=true

**Comment by isopen** [comment]
@levlam
In file included from /Users/runner/runners/2.263.0/work/td/td/tdutils/td/utils/unique_ptr.h:10:
/Applications/Xcode_11.5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1466:59: error: incomplete type 'td::ConfigShared' used in type trait expression
    : public integral_constant<bool, __is_base_of(_Bp, _Dp)> {};
                                                          ^
/Users/runner/runners/2.263.0/work/td/td/tdutils/td/utils/unique_ptr.h:40:52: note: in instantiation of template class 'std::__1::is_base_of<td::DialogFilter, td::ConfigShared>' requested here
  template <class S, class = std::enable_if_t<std::is_base_of<T, S>::value>>
                                                   ^
/Users/runner/runners/2.263.0/work/td/td/tdutils/td/utils/unique_ptr.h:41:3: note: in instantiation of default argument for 'unique_ptr<td::ConfigShared>' required here
  unique_ptr(unique_ptr<S> &&other) noexcept : ptr_(static_cast<S *>(other.release())) {
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/runners/2.263.0/work/td/td/td/telegram/Global.h:122:11: note: while substituting deduced template arguments into function template 'unique_ptr' [with S = td::ConfigShared, $1 = (no value)]
    CHECK(shared_config_ != nullptr);
          ^
/Users/runner/runners/2.263.0/work/td/td/td/telegram/ConfigManager.h:30:7: note: forward declaration of 'td::ConfigShared'
class ConfigShared;
      ^
2 errors generated.

**Comment by isopen** [comment]
@bluzye Most likely the master in this context is a branch for development.
Real-time split_source v1.6.0 https://github.com/isopen/td/runs/768101746?check_suite_focus=true

**Comment by levlam** [comment]
@bluzye Fixed in master. Could you check it?

**Comment by bluzye** [comment]
> @bluzye Fixed in master. Could you check it?

It worked.
