### ISSUE TITLE
TDLib SendChatAction management for uploading files

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#109]
For now, all clients are forced to call `SendChatAction` by themselves for uploads of any file type, while the rest of upload process is fully managed by TDLib

But this logic should be moved to TDLib, because it's common for any non-bot usage cases and there's no robust way implementing such thing on client side:
- Upload may start by TDLib itself (e.g. send a file without network access, restart TDLib, turn on network access) – no information about file type available on client side to make `SendChatAction` calls
- Not clear how often this method should be called
- No potential of network request optimizations on client side (e.g. probably upload status requests could be sent alongside with saveFilePart networks query or etc)

**Comment by levlam** [comment]
Implemented in TDLib 1.2.0.
