### ISSUE TITLE
I can't browse sensitive content on Android

### ISSUE THREAD

**Issue by kouhe3** [tdlib/td#1093]
![搜狗截图20200614074819](https://user-images.githubusercontent.com/25522053/84581585-63322b80-ae15-11ea-8dcd-4bea78f35054.png)
![Screenshot_20200613-211301](https://user-images.githubusercontent.com/25522053/84581592-6cbb9380-ae15-11ea-89fb-c7e199abcefa.jpeg)
But I can browse it on the web and on desktop

**Comment by levlam** [comment]
This is not related to TDLib in any way. Plus Messenger doesn't even use TDLib.

**Comment by kouhe3** [comment]
![photo_2020-07-06_18-09-02](https://user-images.githubusercontent.com/25522053/86582160-cbf36a80-bfb3-11ea-9c52-1efdec11b36d.jpg)

**Comment by kouhe3** [comment]
![photo_2020-07-06_18-09-02](https://user-images.githubusercontent.com/25522053/86582235-e88fa280-bfb3-11ea-97cd-45ebd398fd60.jpg)

**Comment by levlam** [comment]
This is still not related to TDLib in any way.

**Comment by kouhe3** [comment]
@levlam 
How can I solve this problem?

**Comment by levlam** [comment]
@kouhe3 Contact in-app support.
