### ISSUE TITLE
[Feature Request] Better privacy settings/antispam

### ISSUE THREAD

**Issue by rdlrt** [tdlib/td#1096]
(PS: Duplicate of [this](https://github.com/telegramdesktop/tdesktop/issues/8079) issue, but raising on both repos as there are UI and library side of things to look at)
### Is your feature request related to a problem?
Over past couple of years, Telegram has been attracting lot of spammers across various _public_ super groups - especially related to financial platforms. While we can prevent Messages typed in groups via bots, scammers have been able to utilise telegram's weaknesses in two ways:
1. A proxy account can join the group and download user's list in the group
2. Use another account to directly DM members of that group.

### Describe the solution you'd like
1. Option to restrict who can see members in a group to Administrators.
2. A default option to reduce who can privately message you to "My Contacts Only"

### Describe alternatives you've considered
- Making public group private is not an option. Even then, a user can still join the group and attract members.
- Making educational posts for users to beware and alerting every new joinee.
The above does not help much - as most of the users (annoyingly) dont read the warnings.

### Additional context
There have been thousands of cases where naive/noob users have been scammed of thousands/millions and its high time these limitations of the platform should be addressed.

**Comment by RememberTheAir** [comment]
You should bring this to the in-app support or [Twitter[(https://twitter.com/telegram). tdlib is a library that wraps the Telegram API, and what you're requesting should be implemented in the API itself

**Comment by rdlrt** [comment]
Thanks @RememberTheAir - Yip, raised on twitter (before), and now on Telegram Desktop repo and here.

**Comment by levlam** [comment]
It is useless to hide member list in groups, because all active members can be found in the message history. Also, as @RememberTheAir noted, this is not related to TDLib. You can send general suggestions through in-app support or by menthioning @telegram on Twitter.
