### ISSUE TITLE
MessageId is too high

### ISSUE THREAD

**Issue by thekeithwaters** [tdlib/td#1097]
Good Day.     I'm getting these errors.     I suspect it is related to the PC going into hibernation and then coming out of hibernation.     What can I do to avoid this?

[ 2][t 4][1592462486.066897869][SessionConnection.cpp:343][#1][!Session:4:main] [session_id:0x0000026fd22c60e0] [msg_id:0x5eeb0cd42621bdb8] [seq_no:0x00000000]: MessageId is too high. Session will be closed
[ 2][t 4][1592462486.067425728][Session.cpp:572][#1][!Session:4:main]   Session failed: [Error : 0 : MessageId is too high]
[ 2][t 4][1592462486.068441629][Session.cpp:145][#1][!SessionProxy:4:main]      Generate new session_id 17413905461598381657 for auth key 14***********************10 for main DC4
[ 2][t 4][1592462486.068856716][Session.cpp:472][#1][!Session:4:main]   Session closed: [Error : 0 : MessageId is too high] Session:4:main::Connect::Tcp::[149.154.167.91:80] to DcId{4} from [0.0.0.0:65181]
[ 2][t 4][1592462492.051829100][SessionConnection.cpp:343][#1][!Session:4:main] [session_id:0x0000026fd22c60e0] [msg_id:0x5eeb0cda243121f0] [seq_no:0x00000000]: MessageId is too high. Session will be closed
[ 2][t 4][1592462492.052320719][Session.cpp:572][#1][!Session:4:main]   Session failed: [Error : 0 : MessageId is too high]
[ 2][t 4][1592462492.053615093][Session.cpp:145][#1][!SessionProxy:4:main]      Generate new session_id 14257949745556800836 for auth key 14***********************10 for main DC4
[ 2][t 4][1592462492.054013968][Session.cpp:472][#1][!Session:4:main]   Session closed: [Error : 0 : MessageId is too high] Session:4:main::Connect::Tcp::[149.154.167.91:5222] to DcId{4} from [0.0.0.0:65186]
[ 2][t 4][1592462500.259677887][SessionConnection.cpp:343][#1][!Session:4:main] [session_id:0x0000026fd22c60e0] [msg_id:0x5eeb0ce24a8babf4] [seq_no:0x00000000]: MessageId is too high. Session will be closed
[ 2][t 4][1592462500.259968281][Session.cpp:572][#1][!Session:4:main]   Session failed: [Error : 0 : MessageId is too high]
[ 2][t 4][1592462500.260511637][Session.cpp:145][#1][!SessionProxy:4:main]      Generate new session_id 8885507958018688236 for auth key 14***********************10 for main DC4
[ 2][t 4][1592462500.260729551][Session.cpp:472][#1][!Session:4:main]   Session closed: [Error : 0 : MessageId is too high] Session:4:main::Connect::Tcp::[196.53.9.106:7701] to DcId{4} from [0.0.0.0:65189]
[ 2][t 4][1592462504.025126457][SessionConnection.cpp:343][#1][!Session:4:main] [session_id:0x0000026fd22c60e0] [msg_id:0x5eeb0ce61e64e2c0] [seq_no:0x00000000]: MessageId is too high. Session will be closed
[ 2][t 4][1592462504.025653601][Session.cpp:572][#1][!Session:4:main]   Session failed: [Error : 0 : MessageId is too high]
[ 2][t 4][1592462504.029791117][Session.cpp:145][#1][!SessionProxy:4:main]      Generate new session_id 15500084882689577521 for auth key 14***********************10 for main DC4
[ 2][t 4][1592462504.030200720][Session.cpp:472][#1][!Session:4:main]   Session closed: [Error : 0 : MessageId is too high] Session:4:main::Connect::Tcp::[149.154.167.91:443] to DcId{4} from [0.0.0.0:65191]
[ 2][t 4][1592462508.076359749][SessionConnection.cpp:343][#1][!Session:4:main] [session_id:0x0000026fd22c60e0] [msg_id:0x5eeb0cea287d4d90] [seq_no:0x00000000]: MessageId is too high. Session will be closed
[ 2][t 4][1592462508.077564478][Session.cpp:572][#1][!Session:4:main]   Session failed: [Error : 0 : MessageId is too high]
[ 2][t 4][1592462508.082567453][Session.cpp:145][#1][!SessionProxy:4:main]      Generate new session_id 2307115735341733614 for auth key 14***********************10 for main DC4
[ 2][t 4][1592462508.083201170][Session.cpp:472][#1][!Session:4:main]   Session closed: [Error : 0 : MessageId is too high] Session:4:main::Connect::Tcp::[149.154.167.91:80] to DcId{4} from [0.0.0.0:65192]
[ 2][t 4][1592462512.024454832][SessionConnection.cpp:343][#1][!Session:4:main] [session_id:0x0000026fd22c60e0] [msg_id:0x5eeb0cee1e601590] [seq_no:0x00000000]: MessageId is too high. Session will be closed
[ 2][t 4][1592462512.024688721][Session.cpp:572][#1][!Session:4:main]   Session failed: [Error : 0 : MessageId is too high]
[ 2][t 4][1592462512.026062727][Session.cpp:145][#1][!SessionProxy:4:main]      Generate new session_id 6464312396022131780 for auth key 14***********************10 for main DC4
[ 2][t 4][1592462512.026182175][Session.cpp:472][#1][!Session:4:main]   Session closed: [Error : 0 : MessageId is too high] Session:4:main::Connect::Tcp::[149.154.167.91:5222] to DcId{4} from [0.0.0.0:65196]

**Comment by levlam** [comment]
What is your OS?

**Comment by thekeithwaters** [comment]
dont laugh... I'm running this on node.js in windows.

Kind regards,
Keith

**Comment by levlam** [comment]
The latest TDLib version should correctly recover after such errors.
