### ISSUE TITLE
updateUsersNearby sent before results to searchChatsNearby

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1098]
Docs say that `updateUsersNearby` is sent ~60s after results for `searchChatsNearby` is received.  However, sometimes (after searching same location for the second or third time), I see `updateUsersNearby` event just before results for `searchChatsNearby` is sent.

`updateUsersNearby@users_nearby` value is identical to `chatsNearby@users_nearby` received as result for `searchChatsNearby`.

Is it ok behaviour?  I'm using TDLib 1.6.4

Thanks

**Comment by levlam** [comment]
This is expected behavior. `updateUsersNearby` can be received any time after first `searchChatsNearby` call. The description means that without repeated calls to `searchChatsNearby` every 60 seconds the list of users nearby will become empty soon.
