### ISSUE TITLE
[Question] native C client

### ISSUE THREAD

**Issue by Marukesu** [tdlib/td#1099]
There's a way to build tdlib exporting the c client and the tdc_api header?

**Comment by levlam** [comment]
Do you really need С interface with pregenerated structures instead of C JSON interface?

In that case you can build it by explicitly specifying it as a target: `cmake --build . --target tdc`, but you need to be aware that it is untested for a long time.

**Comment by Marukesu** [comment]
The idea was to build a Vala binding from it, instead of the Json client like #505 do

**Comment by levlam** [comment]
This would be a very hard way. The much better approach is to generate Vala classes from td_api.tl scheme and automatically parse JSON to them.
