### ISSUE TITLE
[Question] start bot from TDLib

### ISSUE THREAD

**Issue by LuckyCoders** [tdlib/td#1100]
How I can start telegram conversation with new bot with help TDLib? 
Private message /start to bot doesn’t work(

**Comment by levlam** [comment]
This is the correct way. You can achieve the same behavior using `sendBotStartMessage` in the latest TDLib version.

**Comment by LuckyCoders** [comment]
> This is the correct way. You can achieve the same behavior using `sendBotStartMessage` in the latest TDLib version.

should I set _chat_id__ to my user profile Id?

**Comment by levlam** [comment]
@LuckyCoders You need to call `createPrivateChat` with bot's `user_id` to create a chat with the bot and send the message to that chat.
