### ISSUE TITLE
searchChatsNearby results

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1101]
There are many location based chats near 55.73N,37.63E location.  Two of them are:
https://t.me/zamoskvoreche_moscow (location=55.730083N,37.62837E) and another has no username associtated having `chat_id=-1001279441535` (location=55.737356N,37.636652E).  I can't find proper location so `searchChatsNearby` would return them both in the list.

If I `searchChatsNearby 55.734N,37.63E`, then only https://t.me/zamoskvoreche_moscow is returned along with other chats.
If I `searchChatsNearby 55.735N,37.63E` then only chat with chat_id=-1001279441535 is returned along with other chats.

I simple can't find location when both these chats are returned from `searchChatsNearby`

Why so?  Those location are extremely close, and even I choose location just inbetween chats location, then only one is returned.  I'm using TDLib 1.6.4

Thanks

**Comment by levlam** [comment]
The chats are located too far from each other (in 960m away) to be returned together. There can be some chats with a bigger distance between them returned together, but this is accidental..
