### ISSUE TITLE
error in data type size

### ISSUE THREAD

**Issue by Andrysky** [tdlib/td#1104]
generateChatInviteLink  accepts   std::int64_t | chat_id_
createNewSupergroupChat return chat with std::int64_t | id_

but setSupergroupUsername  accepts  std::**int32_t** | supergroup_id_.  -WTF?
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_supergroup_username.html

**Comment by levlam** [comment]
This is covered in details in https://core.telegram.org/tdlib/getting-started#tdlib-glossary.

**Comment by Andrysky** [comment]
@levlam I did not find a description of my problem at the link (

**Comment by levlam** [comment]
@Andrysky Among other things Getting Started describes difference between supergroups and chats and how they are connected. You need to inspect `Chat.type` field.

**Comment by Andrysky** [comment]
@levlam 
thanks for the tip on Chat.type
can you tell me why such a horrible design is made that in fact we should use the int32 id from ChatType and not Chat std :: int64_t id_ which is described as "Chat unique identifier."?
about https://core.telegram.org/tdlib/getting-started
after you said to look at the type of chat just now drew attention to chat_id / supergroup_id - since before that I thought it was "Chat unique identifier" and I can use it

**Comment by levlam** [comment]
You can use setSupergroupUsername only with supergroups, because among 4 chat types you can change username only for supergroups,

**Comment by Andrysky** [comment]
@levlam 
I understand, I'm talking about what for need - Chat std :: int64_t id_  "Chat unique identifier."

**Comment by levlam** [comment]
Yes, chat_id is a unique identifier of a chat. But `username` is not a `chat` object field. It is a field of the `supergroup` object.
