### ISSUE TITLE
Link error with -ltdapi in Alpine Linux (musl-dev)

### ISSUE THREAD

**Issue by matryoshkababushka** [tdlib/td#1105]
# Summary

Trivial Dockerfile for building **td** is not valid anymore as it does not really build **tdapi** on v1.6.0.

# Error

It builds fine. 

Only linking with it fails with an error (alpine3.10 in docker):
```
...
# github.com/Arman92/go-tdlib
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -ltdapi
collect2: error: ld returned 1 exit status
```

# Version of source

Commit hash `945a3a1dc395bde69d63fff89d6936cd295be0d9`  (Feb 8 2020)

# Steps to reproduce

Run `docker build -t tdlib .` with the Dockerfile:

**Dockerfile below respects official build instructions for td**

```Dockerfile

FROM alpine:3.10 as tdlib

RUN apk --no-cache add git alpine-sdk linux-headers zlib-dev openssl-dev gperf cmake make

RUN git clone --branch v1.6.0 --depth 1 https://github.com/tdlib/td /td

RUN cd /td && \
  mkdir build && cd build && \
  cmake -DCMAKE_BUILD_TYPE=Release .. && \
  cmake --build . -- -j$(nproc) && \
  make install

# ARTIFACTS:
# /usr/local/include/td
# /usr/local/lib/libtd*

# LINKED LIBRARIES (apk --no-cache add):
# zlib openssl libstdc++

```

This builds OK and gives Alpine Linux based tdlib image with artifacts inside. 

However, something has changed in Alpine Linux or elsewhere; linking tdlib's artifacts is no more possible. Like in my Go app's Dockerfile:

```Dockerfile

FROM golang:1.13-alpine3.10
USER root
RUN apk add --no-cache make protoc build-base linux-headers \
  zlib-dev openssl-dev openssl libstdc++

COPY --from=tdlib /usr/local/lib/libtd* /usr/local/lib/
COPY --from=tdlib /usr/local/include/td /usr/local/include/td

RUN go install <my app uses go-tdlib>

ENTRYPOINT [ /root/go/bin/my-app ]
```

Fails on last **RUN** command. What is "-ltdapi" and where is it located after build?

# Debug

After build of tdlib, container has these libraries:

```sh
/ # find /usr/local/lib -name "*td*"
/usr/local/lib/libtdcore.a
/usr/local/lib/libtdclient.a
/usr/local/lib/libtdsqlite.a
/usr/local/lib/libtddb.a
/usr/local/lib/libtdnet.a
/usr/local/lib/libtdjson_static.a
/usr/local/lib/libtdjson_private.a
/usr/local/lib/libtdjson.so
/usr/local/lib/libtdjson.so.1.6.0
/usr/local/lib/libtdactor.a
/usr/local/lib/libtdutils.a
/ # 
```

# Details

The way cgo is used to link with tdlib is in this file:
https://github.com/Arman92/go-tdlib/blob/master/tdlib.go

Application code

main.go:

```go
package main

import (
	"github.com/Arman92/go-tdlib"
)

func main() {
	tdlib.SetLogVerbosityLevel(1) // test require linking 
	tdlib.SetFilePath("./errors.txt")
}

```

`docker build -t example .` with this `main.go` will trigger link error with using Dockerfile:

```Dockerfile

FROM golang:1.11-alpine3.10

RUN apk --no-cache add git alpine-sdk linux-headers zlib-dev openssl-dev gperf cmake make

COPY --from=tdlib /usr/local/include/td /usr/local/include/td
COPY --from=tdlib /usr/local/lib/libtd* /usr/local/lib/

ENV GOPATH=/root/go

COPY . /root/app

RUN mkdir -p /root/go/src/github.com/example
RUN ln -sf /root/app /root/go/src/github.com/example/example
RUN go get -d github.com/example/example

RUN go install github.com/example/example

ENTRYPOINT [ "/root/go/bin/example" ]
````

Expected behaviour: all dockerfiles here worked before

Actual behaviour: link error with `-ltdapi`

**Comment by matryoshkababushka** [comment]
The problem can be resolved by using older go-tdlib version (commit `7c37656671155fe845b368dba82ca6d4aa8914a0`) that does not have `-ltdapi` linking in command for cgo.

This is a workaround only. What should be done to fix missing tdapi after build?

**Comment by levlam** [comment]
There was no `tdapi` static library in 1.6.0, so it is expected that it wasn't created. The best way is to use master branch of TDLib instead of TDLib 1.6.0. It is stable enough for most use cases. You can also use old commit of `go-tdlib` or manually remove `-ltdapi` if you want to use newest `go-tdlib` version with TDLib 1.6.0.

**Comment by matryoshkababushka** [comment]
Does that mean building with `-ltdapi` is not actually tagged/released yet?

**Comment by supolka** [comment]
Using master is not an option since API has changed. E.g. the recommended way of fetching chats works a bit differently now because `updateChatOrder` has been deleted https://github.com/tdlib/td/commit/06136146511a46bcc26fcb936e3e9ae42130e92c, and not all libraries are updated to reflect this change
