### ISSUE TITLE
use_test_dc and obtaining Authentication Code

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#111]
Setting use_test_dc=true before calling setAuthenticationPhoneNumber makes it impossible to obtain the code since Telegram tries to send it to a client (in test environment??) instead of sending it as SMS. How do I connect to the test env to get the code?

**Comment by arseny30** [comment]
You need 'resendAuthenticationCode' query. It will resend code with the next available method.
The next method with other information can be found in `code_info` field of `authorizationStateWaitCode`.

Also you can login into the test datacenter here: http://web.telegram.org/?test=1

**Comment by x2bool** [comment]
Thank you!
