### ISSUE TITLE
[Question] How can i create public channel through JNI interface of TDlib?

### ISSUE THREAD

**Issue by banzecrew** [tdlib/td#1110]
Now i trying to create public channel by calling **TdApi.CreateNewSupergroupChat** method, and it creates a private channel. 

How can i create public instead?

**Comment by IRGC** [comment]
You may need to use setSupergroupUsername to make it public.  🤔 see https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L4159

**Comment by banzecrew** [comment]
> You may need to use setSupergroupUsername to make it public. 🤔 see https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L4159

Hmm. Very confusing but it works.

Many thanks!
