### ISSUE TITLE
[Bug report] some Emojis cause entity offsets to be wrong

### ISSUE THREAD

**Issue by mktdw** [tdlib/td#1113]
Hello,

some emojis like 🔹 and 🔴 cause the response for the offset of entities to be wrong, while other like ❤️ do not cause any issue.
For example if i have the following message to a group chat:
```
はじめまして ❤️🔴
🔹
http://www.google.com
```
and get the chat history for that group, the entity offset for www.google.com is { offset: 15, length: 21 }
if I use hearts instead,
```
はじめまして ❤️❤️
❤️
http://www.google.com
```
I get the same offset and length, however in terms of uncode character sizes, ❤️ are 2 runes, while 🔹 and 🔴 are 1 rune. (rune being the term for unicode character in my programming language).
So for those two cases if I debug the first, I get:
```
[6]:32 (space)
[7]:10084 (❤️ 1st rune/unicode character)
[8]:65039 (❤️ 2nd rune/unicode character)
[9]:128308 (🔴 only rune/unicode character)
[10]:10 (new line)
[11]:128313 (🔹 only rune/unicode character)
[12]:10 (new line)
```
thus for the first example I start my entity at rune/unicode character number 13 (not 15), which is wrong

on the second example I get:
```
[6]:32 (space)
[7]:10084 (❤️ 1st rune/unicode character)
[8]:65039 (❤️ 2nd rune/unicode character)
[9]:10084 (❤️ 1st rune/unicode character)
[10]:65039 (❤️ 2nd rune/unicode character)
[11]:10 (new line)
[12]:10084 (❤️ 1st rune/unicode character)
[13]:65039 (❤️ 2nd rune/unicode character)
[14]:10 (new line)
```
thus for the second example I start my entity at rune/unicode character number 15 which is correct.

Thus I would like to know if it is possible to change the offset returned by tdlib to match either the correct /unicode character count.

Thank you very much for your time

**Comment by levlam** [comment]
Offset and length in `textEntity` object are in UTF-16 code units as described in the documentation. UTF-16 is used for internal string representation in the most popular programming languages and frameworks, so this allows fast and simple access to text entities. If this isn't a case for your programming language, then you need to convert message text to UTF-16 first.

**Comment by mktdw** [comment]
Thank you very much for the information, I will make the necessary changes to the code!
Best regards!
