### ISSUE TITLE
Unable to clear history for all users

### ISSUE THREAD

**Issue by eos1d3** [tdlib/td#1115]
Using the Java version, I can clear history with this:

` client.send(new TdApi.DeleteChatHistory(-1001234567890L, false, true), defaultHandler);`

However, other users are still seeing all messages in a chat.

I know `chat` has `can_be_deleted_for_all_users_`, but how to implement this in Java?

Thanks!

**Comment by levlam** [comment]
This field informs you whether it is possible to delete chat history for all users. If it is false, then deletion for all users is impossible. Probably, you are looking for `toggleSupergroupIsAllHistoryAvailable` instead.

**Comment by eos1d3** [comment]
> This field informs you whether it is possible to delete chat history for all users. If it is false, then deletion for all users is impossible. Probably, you are looking for `toggleSupergroupIsAllHistoryAvailable` instead.

From the doc, it says `toggleSupergroupIsAllHistoryAvailable` toggles whether the message history of a supergroup is available to new members. So it is not related to delete messages for all user, right?

How to set can_be_deleted_for_all_users_ to true?

**Comment by levlam** [comment]
You can't set `can_be_deleted_for_all_users`. You can only check it to know what is possible and what is impossible.

**Comment by eos1d3** [comment]
Still can't fix the problem. What I am going to do is to clear all user history in a group or super group. 

By using `TdApi.DeleteChatHistory`, only my own history is cleared. Of course my account has admin rights.

So any idea to clear all history for all users with TDLib?

**Comment by levlam** [comment]
If the flag is `false`, then it is not possible to do this using the method. You can try to delete them one-by-one.
