### ISSUE TITLE
"Could NOT find gperf.  Add path to gperf executable to PATH environment"

### ISSUE THREAD

**Issue by DorsiFlexionDev** [tdlib/td#1116]
I followed the instructions in this [document](https://tdlib.github.io/td/build.html?language=C%23) and after I run:
 `cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..`
I get:
`CMake Error at tdutils/generate/CMakeLists.txt:22 (message):
  Could NOT find gperf.  Add path to gperf executable to PATH environment
  variable or specify it manually using GPERF_EXECUTABLE option, i.  e.
  'cmake -DGPERF_EXECUTABLE:FILEPATH="<path to gperf executable>"'.

-- Configuring incomplete, errors occurred!`

(I have installed gperf and added the exe to the path environment variable)

**Comment by levlam** [comment]
Have you reopened console after PATH environment variable change?

**Comment by DorsiFlexionDev** [comment]
> Have you reopened console after PATH environment variable change?

yes

**Comment by levlam** [comment]
Are you able to run `gperf` from console without specifiying its full path?

**Comment by DorsiFlexionDev** [comment]
> Are you able to run `gperf` from console without specifiying its full path?

no

**Comment by levlam** [comment]
You can also run `echo %PATH%` to check what is wrong with it. If you restarted console, then an incorrect path was added to it.

**Comment by DorsiFlexionDev** [comment]
> You can also run `echo %PATH%` to check what is wrong with it. If you restarted console, then an incorrect path was added to it.
Yes, the path is there.
The path is 'C:\Program Files (x86)\GnuWin32\bin\gperf.exe' when I open it through the file explorer the exe window opens so it should be correct

**Comment by levlam** [comment]
You should add a directory to the PATH variable, not the full path to the executable.

**Comment by DorsiFlexionDev** [comment]
> You should add a directory to the PATH variable, not the full path to the executable.
Thanks, now its working
