### ISSUE TITLE
[Question] Clarification on updates and cache

### ISSUE THREAD

**Issue by lppedd** [tdlib/td#1117]
I just started trying out the Java wrapper over `tdlib`, and after checking out the various `Update` types on the TL schema I got confused.

The `Update` types shows for example

```
updateNewMessage
updateNewChannelMessage
updateNewScheduledMessage
```

So, is it correct that `tdlib` merges those events over a single `UpdateNewMessage` object?

------

I'm not a C++ expert, but after looking at the sources, it seems that methods such as `get_user` cache the result from network. Is it correct that subsequent requests for the same `user_id` will not go over the network again? How is this established?

**Comment by levlam** [comment]
The mentioned updates exist in the Telegram API. TDLib provides high level interface independent of chat type and have compelely different API. List of updates provided by TDLib can be found there: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_update.html.

`getUser` supposed to be never needed by ordinary applications using TDLib. See https://core.telegram.org/tdlib/getting-started for the explanation.

**Comment by lppedd** [comment]
Thanks @levlam 
So, if I understood correctly, the relevant paragraph would be

> updateUser — This update is received whenever a new user has been discovered or some data about a known user has changed. This update is guaranteed to come before the user identifier is returned to the Application. So, whenever an Application receives a user_id, it never needs to use the getUser request to receive the user object. Instead it should maintain a cache of users received through this update and take all the necessary data about users from this cache.

This means if an `UpdateNewMessage` is received and I need info about the sender `User` via its `Message#senderUserId`, the User object wuould have been already cached by TDLib thanks to the `UpdateUser` event.

Am I right?

**Comment by levlam** [comment]
The edit is correct. You need to cache it whenever `updateUser` is received and take the `User` object from the cache.

**Comment by lppedd** [comment]
@levlam thanks for the answers!
