### ISSUE TITLE
Please add folder feature to TDlib Library

### ISSUE THREAD

**Issue by Domingowen** [tdlib/td#1118]
Hi guys. hope you have a nice day.
I think the folder feature is so great. but it still doesn't use in TDlib library.
PLS add folder feature to TDlib library. thank you.

**Comment by levlam** [comment]
Full filters (aka folders) support was added more than a month ago and is available in the latest version.

**Comment by Domingowen** [comment]
but I can't find it in TDlibraray API documents. [https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html)
😂

**Comment by levlam** [comment]
On-site documentation is for release 1.6.0 version. You can find documentation for the latest version in https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.
