### ISSUE TITLE
Missing dll files

### ISSUE THREAD

**Issue by DorsiFlexionDev** [tdlib/td#1119]
I'm trying to run the csharp example but I get an error that the following files are missing:
LIBEAY32.dll
zlibd1.dll (missing only in the release folder)
SSLEAY32.dll
I tried to delete the build64 folder and do the installation again but the reasult is the same.
I'm also getting a warning that those file does not exist in the "build" folder, but im using build64. Do I need to to install both(I have already installed x32 but deleted because those files were missing)?

**Comment by DorsiFlexionDev** [comment]
Tried to download all the files again got this error:
LogEventHelper.h(47): fatal error C1001: Internal compiler error. [C:\Users\User\td2\td\build\tdcore.vcxproj]

**Comment by levlam** [comment]
Try the latest TDLib version, i.e. remove `git checkout v1.6.0` line from the build instructions.

**Comment by DorsiFlexionDev** [comment]
CMake Warning at CMakeLists.txt:279 (message): Not found OpenSSL: skip TDLib, tdactor, tdnet, tddb
now there is no debug and release folders in build64

**Comment by DorsiFlexionDev** [comment]
Now it's working, thank you!
