### ISSUE TITLE
ClientActor interface

### ISSUE THREAD

**Issue by bortoz** [tdlib/td#1120]
Hi, I'm trying to use the [`td::ClientActor`](https://core.telegram.org/tdlib/docs/classtd_1_1_client_actor.html) class in a C++ project, but when I run the code I get an error at [scheduler.h:101](https://github.com/tdlib/td/blob/master/tdactor/td/actor/impl/Scheduler.h#L101):
```
Thread #1 5948 [core: 1] (Suspended : Signal : SIGSEGV:Segmentation fault)	
	td::Scheduler::register_actor_impl<td::MultiTimeout>() at Scheduler.h:101 0x804c8507	
	td::Scheduler::register_actor<td::MultiTimeout>() at Scheduler.h:91 0x804c84ac	
	td::register_actor<td::MultiTimeout>() at Scheduler.h:379 0x804c820a	
	td::MultiTimeout::MultiTimeout() at Timeout.h:87 0x8048bcfd	
	td::Td::Td() at Td.h:281 0x81209b88	
	td::Scheduler::create_actor<td::Td, td::unique_ptr<td::TdCallback> >() at Scheduler.h:81 0x8039099a	
	td::create_actor<td::Td, td::unique_ptr<td::TdCallback> >() at Scheduler.h:369 0x8038f5ae	
	td::ClientActor::ClientActor() at ClientActor.cpp:16 0x80395702
```
I'm using tdlib 1.6.0.

Does anyone know why I'm getting this error or should I just use `td::Client` interface instead?
Thank you!

**Comment by levlam** [comment]
You should use td::Client, which is much simpler, unless you really need something that can be achieved only with td::ClientActor. Currently, the only significant difference is that you can receive all updates and request responses in the same thread using td::ClientActor.

You can find example of td::ClientActor creation and usage in https://github.com/tdlib/td/blob/f45d80fe16f99d112d545b7cd74ce46342fe3437/td/telegram/cli.cpp#L4401.

**Comment by bortoz** [comment]
I have tried to spawn a thread in which I receive updates through `td::Client`, but when I join the thread (without closing the client) I have to block the main thread until the `td::Client::receive` timeout expires. Is there any way to avoid it, like `td::ClientActor` callbacks?

Thanks for your time!

**Comment by levlam** [comment]
You need to call `close` to close the TDLib instahce and wait for `updateAuthorizationState` with `authorizationStateClosed`. The latter is written in td::Client documentation: https://github.com/tdlib/td/blob/f45d80fe16f99d112d545b7cd74ce46342fe3437/td/telegram/Client.h#L36.

**Comment by bortoz** [comment]
What I'm trying to do is to stop the thread where I recive the updates without closing the client (and later I want to spawn the thread again). Using `td::Client`, I have to wait the `td::Client::receive` timeout, is there any way to stop the thread without closing the client?

**Comment by levlam** [comment]
You can send any request which will return response immediately.

**Comment by bortoz** [comment]
Thank you!
