### ISSUE TITLE
[Question] Clarification on TDLib instance and active bots

### ISSUE THREAD

**Issue by lppedd** [tdlib/td#1122]
In the TDLib advantages I read:

> In the Telegram Bot API, each TDLib instance handles more than 24,000 active bots simultaneously

Being that _instance_ = `Client`, and that a `Client` authorizes a single Bot token, what does _active bots_ means?

**Comment by levlam** [comment]
*Active* means "running simultaneously". There also thousands bots using long polling which wasn't recently active, so they instances are not run.

**Comment by lppedd** [comment]
@levlam Thanks!
But I don't really understand how a single TDLib instance can handle more than one auth token.
Maybe I'm missing something

**Comment by levlam** [comment]
One client = one token. There is one TDLib instance for each bot.

**Comment by lppedd** [comment]
@levlam perfect, thanks!
