### ISSUE TITLE
[Question] Function call's paramaters default values & nulls

### ISSUE THREAD

**Issue by lppedd** [tdlib/td#1123]
Lat's say I use the `SendMessage` function. In Kotlin/JVM it is represented as

    class SendMessage(
        val chatId: Long = 0L,
        val replyToMessageId: Long = 0L,
        val options: SendMessageOptions? = null,
        val replyMarkup: ReplyMarkup? = null,
        val inputMessageContent: InputMessageContent? = null
    ) : Function() {
        override val constructor: Int get() = -1314396596
    }

As you can see many parameters can be `null`. Should I always try to minimize the amout of information sent, or TDLib will remove redundant structures by itself? Example, let's say we pass to TDLib an `SendMessageOptions` object with all default values (so redundant values)

    class SendMessageOptions(
        val disableNotification: Boolean = false,
        val fromBackground: Boolean = false,
        val schedulingState: MessageSchedulingState
    ) : Object() {
        override val constructor: Int get() = 669760254
    }

Is this something to avoid or should I just don't care?

**Comment by levlam** [comment]
This shouldn't matter, because the overhead for object creation should be neglible.

**Comment by lppedd** [comment]
@levlam I'm not worried about object allocation in memory, I'm worried that this might increase the network payload. Sounds plausible?

**Comment by levlam** [comment]
TDLib API has nothing to do with network requests. And even it would, the overhead would be neglible. Use whatever is simpler to you.
