### ISSUE TITLE
Q: How to refresh latest channel messages

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1125]
I use getChatHistory to read the latest messages from my channel, but I found that it keeps returning to the cache after the first call.

**Comment by levlam** [comment]
You need to join the channel and process `updateNewMessage` instead of constantly using `getChatHistory`.

**Comment by nekohasekai** [comment]
If I join the channel, does getChatHistory work properly? It is a scheduled task.

**Comment by levlam** [comment]
You should never call `getChatHistory` to get new messages. Instead you need to handle`updateNewMessage` in a joined chat.
