### ISSUE TITLE
Unique id for right answers in quiz

### ISSUE THREAD

**Issue by bsde1234** [tdlib/td#1128]
When we download chat history of telegram group or channel, I would like to have a unique id for right answer of quiz and quizbot.

**Comment by levlam** [comment]
What methods are you talking about?

**Comment by bsde1234** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7857

**Comment by levlam** [comment]
Telegram Desktop doesn't use TDLib, so this is absolutely irrelevant to TDLib.

Between, there is no way to know right quiz answer before answering it.

**Comment by bsde1234** [comment]
> Between, there is no way to know right quiz answer before answering it.

Chat history takes after answering to the quiz by group members.
