### ISSUE TITLE
bot reply

### ISSUE THREAD

**Issue by tingfeng-key** [tdlib/td#1130]
I see that some robots can implement this function, but I can't find it in the API documentation.

Operation process: I send instructions to the robot, such as / add, and the robot will reply to my message, and the message I will reply to the robot is prepared in the input box of my telegram client.

Question: why can a robot operate my input box? How does this work?

**Comment by levlam** [comment]
It can't. Probably, you are talking about https://core.telegram.org/bots/api#inlinekeyboardbutton with `switch_inline_query_current_chat`, or https://core.telegram.org/bots/api#replykeyboardmarkup.
