### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#1131]
Hello , I have this error ,

[ 0][t 0][1594485596.271106005][LogEvent.h:212][!Td][&version() < static_cast<int32>(Version::Next)]    Wrong version 25

**Comment by levlam** [comment]
You have tried to downgrade TDLib. This can't be possible, you can only update TDLib to a newer version.

**Comment by marckohlbrugge** [comment]
@levlam I've got this same error (albeit with a higher version code). When you say you cannot downgrade TDLib in which context do you mean? If I remove the newer TDLib from my system, should I be able to install an older version? Or is it version somehow linked to my Telegram app?

**Comment by marckohlbrugge** [comment]
Okay I figured it out. In my case I had some cached data created by `tdlib-ruby` which was created with tdlib 1.7.0 but I downgraded to tdlib 1.6.0

So to summarise the version isn't locked to your app. If you get this "Wrong version 25" error, it means you still have some configuration data or cache somewhere that was created with a different tdlib version.
