### ISSUE TITLE
No response after keyin phone number

### ISSUE THREAD

**Issue by luluwin** [tdlib/td#1133]
Hi, I am trying to learn Telegram API from you C# example. When I run the code, the console asks phone number and when I key in and enter, there is no response at all. I did not receive any verification code. I tried Telegram App on my desktop and everything is fine. When I run the program step by step, I found it went though UpdatesHandler : Td.ClientResultHandler and AuthorizationRequestHandler : Td.ClientResultHandler a few times after _client.Send(new TdApi.SetAuthenticationPhoneNumber(phoneNumber, null), new AuthorizationRequestHandler()); and then stuck. 
Tdlib log file is 
[ 0][t 0][1594736212.364305735][TsList.h:169]	Check `ListNode::empty()` failed

For your information, the Telegram.Td.dll was built on another laptop win10 and I am run the sample code on a desktop win10.

Thanks

**Comment by luluwin** [comment]
Some more information about the issue:
The desktop which I run the example code failed to build the Telegram.Td.dll as it shows -- Detecting CXX compiler ABI info - failed. That is why I use the other laptop to build the dll.

**Comment by levlam** [comment]
Could you comment the line https://github.com/tdlib/td/blob/f45d80fe16f99d112d545b7cd74ce46342fe3437/example/csharp/TdExample.cs#L219 and send the TDLib log to @tdlib_bot in Telegram?

**Comment by luluwin** [comment]
Done and sent to @tdlib_bot. The desktop I tried the example code is my company's computer with McAfee antivirus and behind a very strict firewall.

**Comment by levlam** [comment]
@luluwin TDLib is unable to create a network connection to Telegram servers. Even HTTPS requests to ordinary sites don't work. Probably, you need to add a proxy using `addProxy` method: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_proxy.html.

**Comment by luluwin** [comment]
@levlam Thanks for your advice. I will try addProxy but it is gonna pretty hard for me to figure it out as I am just a beginner for Telegram programming right now. I am just wondering, why my program for Bot Api can work without a proxy?

**Comment by levlam** [comment]
@luluwin Firewall can allow connections to Bot API.

**Comment by nekohasekai** [comment]
I have also seen `Check ListNode::empty() failed`, which usually occurs when TDLib is not properly stopped when the program is killed.

**Comment by levlam** [comment]
`Check ListNode::empty() failed` can happen only while the program is terminated, so it can't cause any harm.

**Comment by luluwin** [comment]
@levlam After working with our IT department and get the proxy setting and put addProxy before authentication code. The example code works perfect. Learnt a lot from this project. Thanks and appreciate!
