### ISSUE TITLE
how to get my group list?

### ISSUE THREAD

**Issue by haozia816** [tdlib/td#1136]
how to get my group list? like 'getContacts'

**Comment by levlam** [comment]
You can only filter them from main chat list: https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats.

**Comment by ozzzzz** [comment]
Another way:
- make folder with only chats
- go to web-version, open this folder
- run this code in console: `copy($$(".dialog-title .peer-title").map(function(e){return e.textContent}))`, list groups below and repeat it several time till the last group
- profit
