### ISSUE TITLE
"Unknown constructor found" suddenly in the log and chats don´t load for 1 user only

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1137]
Hi there,

I got a bug report about TELEports not being able to load an messages into chats, and asked for the log of the user. This is what I got: https://paste.ubuntu.com/p/jqKNVCyJBf/ - I assume the unknown constructor is a new type that tdlib 1.4 does not understand - but why does it appear at all? Aren´t you using API level on MTProto so that only known constructors will be delivered? Also, I am rather clueless why no messages are being loaded. I will eventually send him a debug log but so far this is the only report about such an issue.

**Comment by levlam** [comment]
> I assume the unknown constructor is a new type that tdlib 1.4 does not understand - but why does it appear at all?

This is an update from an old layer, which can be occasionally sent by the server. It is expensive to support all outdated layers, so this is a feature and not a bug. The update is handled in the exact way it is supposed to be handled, namely by client manually fetching updates from the server. So this shouldn't affect chat list load.

Could the user collect the log verbosity level 4 and send it to @tdlib_bot?

**Comment by levlam** [comment]
@Flohack74 Do you have any update on this?

**Comment by Flohack74** [comment]
Yes we can close it, the unknown constructor was solved and we have tdlib finally on 1.6 now ;)
