### ISSUE TITLE
How to add channel administrator?

### ISSUE THREAD

**Issue by moneymc** [tdlib/td#1138]
Hi there,

I can't find a method for adding channel administrators. Like that:
![image](https://user-images.githubusercontent.com/3620646/87924125-1e8a5780-ca87-11ea-89d7-5f18e1b78cf7.png)

**Comment by levlam** [comment]
The method `setChatMemberStatus` can be used for most changes of the status.

**Comment by moneymc** [comment]
> The method `setChatMemberStatus` can be used for most changes of the status.

Thanks for your answer!

One more situation. How can I add bot to channel and make him administrator?

**Comment by levlam** [comment]
The method setChatMemberStatus can be used for most changes of the status.

**Comment by moneymc** [comment]
> The method setChatMemberStatus can be used for most changes of the status.

I'm trying to add the bot as admin with setChatMemberStatus, addChatMember, and addChatMembers. But every time I get the error: 400 USER_BOT.

**Comment by levlam** [comment]
You should use `setChatMemberStatus` and specify correct administrator rights. You are likely specifying empty list of rights in `chatMemberStatusAdministrator` and an administrator must have at least one administrator right.

**Comment by moneymc** [comment]
> You should use `setChatMemberStatus` and specify correct administrator rights. You are likely specifying empty list of rights in `chatMemberStatusAdministrator` and an administrator must have at least one administrator right.

OMG, you're right, thanks! Sorry for dumb question...
