### ISSUE TITLE
Question: does the prebuild java bins are up to date ? what version are they ?

### ISSUE THREAD

**Issue by comm-amir-david** [tdlib/td#1140]
Hi,
does the pre build java tdlib are up to date ?
if not then what version are they ?
and when are you updating them ?

**Comment by levlam** [comment]
Prebuilt version for Android is updated whenever new stable TDLib version is released. If you need newer version, you can build it from Github master branch.

**Comment by comm-amir-david** [comment]
OK Great thanks again.
:-)
