### ISSUE TITLE
how to use SendBotStartMessage parameters (Deep linking)

### ISSUE THREAD

**Issue by hossein1113** [tdlib/td#1142]
how to use SendBotStartMessage parameters?
what's wrong?
bot start correctly but parameter not working.
 TdApi.SendBotStartMessage sendBotStartMessage = new TdApi.SendBotStartMessage();
 sendBotStartMessage.chatId = ((TdApi.Chat) object).id;
 sendBotStartMessage.botUserId = 98093;
 sendBotStartMessage.parameter = "start=916271871";

**Comment by levlam** [comment]
Are you sure that parameter should be "start=916271871" and not "916271871"?

**Comment by hossein1113** [comment]
I want to start bot with deep linking same this link.
https://t.me/NitroSeenBot?start=916271871.

**Comment by IRGC** [comment]
@hossein1113 i think parameter should be just 916271871   and bot will receive incoming message as /start 916271871

**Comment by hossein1113** [comment]
@IRGC Thanks.
