### ISSUE TITLE
Connecting over port 5222?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1143]
Apparently I cannot use ports 443 or 80 as socket ports due to restrictions placed on them in J2ME on a number of devices. According to [the MTProto documentation](https://core.telegram.org/mtproto/transports#tcp) I can use 5222 instead however, just changing the port doesn't seem to work, my connection just gets closed.  
What's difference protocol-wise between 5222 and 443 or 80?

**Comment by faissaloo** [comment]
I switched the IP to `149.154.175.10` and that seems to work, I was previously using `149.154.167.40` which is listed here as if it should be possible to connect over 5222: https://github.com/tdlib/td/blob/master/td/telegram/net/ConnectionCreator.cpp#L1196  
Potential bug?

**Comment by levlam** [comment]
You can break a lot of things by changing these IP addresses. You must not change 149.154.167.40 to 149.154.175.10, because these IP addresses belong to different datacenters. The set of open ports is not fixed and can vary over time, you can't rely on it on make any assumption about it. If it is possible to connect on 5222 port, TDLib will automatically do that.

**Comment by faissaloo** [comment]
Why is it a problem if I connect to a different datacenter, what might break? How frequently might the set of open ports change? I'm unfortunately going to have to make that at least one of the IPs has 5222 open since I won't be able to use ports 443 or 80 due to this: https://docs.huihoo.com/symbian/s60-3rd-edition-cpp-developers-library-v1.1/GUID-35228542-8C95-4849-A73F-2B4F082F0C44/html/SDL_93/doc_source/faqSDK/faq_1289.html

**Comment by levlam** [comment]
@faissaloo Why is the problem if instead of telegram.org you will send HTTP requests to google.com? That's exactly the problem. The prots are just numbers and can change any time. If you can't use ordinary ports, then just set up proxy on any other port and use the proxy.

**Comment by faissaloo** [comment]
>Why is the problem if instead of telegram.org you will send HTTP requests to google.com?  
  
I'm not sure what you mean by this, both IPs are Telegram MTProto server IPs.  
  
>The ports are just numbers and can change any time.  

I can obviously use MTProto proxies yes, but I'm speaking in terms of having reasonable defaults for my application. I know that in theory the ports can change at any time, but I want to understand the likelihood of that (or at least, how many times has it happened before?) so that I can avoid disruption to users when it does happen.

**Comment by levlam** [comment]
> > Why is the problem if instead of telegram.org you will send HTTP requests to google.com?
> 
> I'm not sure what you mean by this, both IPs are Telegram MTProto server IPs.
> 

Both telegram.org and google.com are HTTPS server URLs. There is no difference still.

> I can obviously use MTProto proxies yes, but I'm speaking in terms of having reasonable defaults for my application. I know that in theory the ports can change at any time, but I want to understand the likelihood of that (or at least, how many times has it happened before?) so that I can avoid disruption to users when it does happen.

It has happened before. For countries with blocked Telegram it happens every 5 minutes. And you should not edit default configuration, because you are very likely to break things hardly. To access Telegram from restricted environments there is support for all popular kinds of proxy,

**Comment by faissaloo** [comment]
>It has happened before. For countries with blocked Telegram it happens every 5 minutes. And you should not edit default configuration, because you are very likely to break things hardly. To access Telegram from restricted environments there is support for all popular kinds of proxy,

Ok I think I see where the misunderstanding is, I'm not modifying TDLib itself, I'm writing my own implementation of MTProto and using TDLib as a reference. It is not the actual IP for Telegram that is being blocked by an ISP or government, it is that I as a developer cannot open socket connections on port 80 or 443 at the device level due to a peculiarity of the runtime. Connecting over 5222 works fine for `149.154.175.10` but not `149.154.167.40` and I was simply concerned that this was unintentional as the documentation makes it sound like I should be able to any of those 3 ports at any time.

**Comment by levlam** [comment]
You can use any specified in the default configuration port, but 5222 is the least reliable of them and can be blocked by providers.

Those are IP addresses of different test datacenters and there are a lot of things, intentionally disabled for testing purposes there, so clients can be tested for a lot of rare cases.

**Comment by faissaloo** [comment]
Ok perfect, that's helpful and I see what you mean now. Is there a place where the differences between the datacenters is documented or is it expected that a developer will just discover and deal with them when implementing MTProto?

**Comment by levlam** [comment]
Most requests must be sent to the main DC assigned to the user. You can find more information about DCs in https://core.telegram.org/api/datacenter.

**Comment by faissaloo** [comment]
Thank you!
