### ISSUE TITLE
td::Client deconstructor crash

### ISSUE THREAD

**Issue by bortoz** [tdlib/td#1144]
Hi, I'm trying to use tdlib in a C++ project. I'm using the `td::Client` interface, but every time I run the program it crashes after closing client. I tried to run gdb, but this time somehow it does not crash.

This is the stack trace, although it is not very helpful.
```
Callstack Information (PID:3929)
Call Stack Count: 5
 0: (0xb6a1b962) [/usr/lib/libc-2.24.so] + 0x126962
 1: (0xb6a4a420) [/usr/lib/libc-2.24.so] + 0x155420
 2: __libc_thread_freeres + 0x22 (0xb6a4a372) [/usr/lib/libc-2.24.so] + 0x155372
 3: (0xb76fb5e7) [/usr/lib/libpthread-2.24.so] + 0x65e7
 4: clone + 0x6e (0xb69eb3ae) [/usr/lib/libc-2.24.so] + 0xf63ae
End of Call Stack
```
I have investigated and I found that the problem is in the [ThreadPthread::join](https://github.com/tdlib/td/blob/master/tdutils/td/utils/port/detail/ThreadPthread.cpp#L74) function, I also tried using `std::thread` instead but there was no difference.

Does anyone know what the problem is?

**Comment by levlam** [comment]
You need to show your code.

**Comment by bortoz** [comment]
Nothing particular, only this:
```
td::Client* client = new td::Client();
delete client; // sigsev
```
I'm building tdlib inside Tizen Studio so maybe I have some wrong compiling configuration.

**Comment by levlam** [comment]
We implemented ThreadPthread specifically for Tizen, because std::thread crashed with SIGSEGV on construction. ThreadPthread worked correctly on Tizen for us back then.

**Comment by bortoz** [comment]
I have used std::thread in other parts of the project and it works fine, but for some reason both std::thread and ThreadPthread crash in that situation, I'll continue to investigate but now I have no idea of the cause.
I'm using the latest Tizen compiler avaible (gcc 6.2.1).

**Comment by bortoz** [comment]
Not sure but the problem could be caused by logging:

https://github.com/tdlib/td/blob/10a7edfbea98fd34dee5ff1c3190b8fe934c5407/tdutils/td/utils/logging.cpp#L206

I think `dlog_print` internally call a function like `vfprintf`, the function is called with an unsafe format string and that might cause this strange behavior.

**Comment by levlam** [comment]
Thanks, @bortoz! This is definitely a bug, caused by copy-paste from __android_log_write function usage. I have just pushed a fix for it. Could you check, whether the crash still happens?

**Comment by levlam** [comment]
The "%" character should be used very-very rare in the log, so I'm not sure that this bug is actually related to the crash.

Also there were a lot of internal changes in Client implementation, so updating to the new version can help itself.

**Comment by bortoz** [comment]
I updated to the latest version of tdlib and Tizen Studio and it does not crash anymore.
Thanks for your time!
