### ISSUE TITLE
req_dh_params sometimes returns error -404?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1145]
Hi, all of a sudden sending `req_dh_params` is occasionally (1/5 chance) giving me a `-404` response, it was fine until a few hours ago. It seems like this guy had a similar problem a few years back: https://github.com/Fnux/telegram-mt-elixir/issues/1 but it doesn't look like `req_dh_params` is documented as being able to return `-404` anywhere. Given `-404` means 'auth key not found' but `req_dh_params` is being sent as an unencrypted message I'm not sure why this happens?

**Comment by levlam** [comment]
-404 likely means that you didn't send a correct request with wrong first bytes, which must be all zero for unauthorized requests.

**Comment by faissaloo** [comment]
My first bytes are definitely all 0:
![image](https://user-images.githubusercontent.com/8840681/88468157-5ce4a400-ced7-11ea-8dba-968e55a14bed.png)
Could this be caused by an incorrect message id?

**Comment by levlam** [comment]
In which DC are you testing?

**Comment by VChernomYA** [comment]
https://github.com/tdlib/td/issues/1145#issuecomment-663916917

**Comment by levlam** [comment]
@VChernomYA I don't see datacenter ID there.

**Comment by faissaloo** [comment]
It happens on 149.154.167.40:443 and 149.154.175.10:5222 at least, which I think correspond to DC 2 and DC 1

**Comment by VChernomYA** [comment]
149.154.167.40:443

**Comment by levlam** [comment]
@faissaloo @VChernomYA By coinsidence these are exactly the DC and IP, which are used in TDLib's handshake test: https://github.com/tdlib/td/blob/1b628d3ab7be515c8c6a916e7e955403fbc07b2a/test/mtproto.cpp#L404.

And the test never fails for us. You can run it as `./run_all_tests --filter handshake` to see that it never prints an error.
You can add line
```
SET_VERBOSITY_LEVEL(5);
```
at the beginning of step() method to see in the log exact send MTProto handshake packets.

**Comment by VChernomYA** [comment]
https://github.com/tdlib/td/blob/1b628d3ab7be515c8c6a916e7e955403fbc07b2a/test/mtproto.cpp

**Comment by levlam** [comment]
-404 can also mean that you send an incorrect `req_dh_params` request, for example, with wrongly encrypted `encrypted_data` inside it. You need to check your RSA implementation.

**Comment by faissaloo** [comment]
Turns out my RSA implementation was sometimes encoding BigIntegers incorrectly, thanks for the help
