### ISSUE TITLE
Cant login via proxy

### ISSUE THREAD

**Issue by Losses** [tdlib/td#115]
I'm using the UWP version of Telegram, Unigram, and unable to login via proxy since it switched to `tdlib`.

It's said that proxy is handled by TDLib, so I submited the issue here.

Original issue post: **https://github.com/UnigramDev/Unigram/issues/545**

**Comment by isopen** [comment]
Show logs

**Comment by levlam** [comment]
There is no need for logs. The issue is already fixed, the fix is coming in the next update.

**Comment by levlam** [comment]
Fixed in TDLib 1.2.0.
