### ISSUE TITLE
Fatal error after updating to TDLib 1.6.7

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1151]
After updating TDLib into 1.6.7 from 1.6.6 and restarting client, I got fatal error:
```
[ 0][t 4][1595777790.565771818][MessagesManager.cpp:4757][#1][!MessagesManager][&static_cast<size_t>(size) <= first_database_message_id_by_index.size()]	963641344 16
```
Removing database directory and restarting client helps however.
Is it ok or TDLib should workaround this somehow?

Thanks

**Comment by hihain** [comment]
I reinstalled my app to run stable after updating to 1.6.7 from 1.6.6.1. Before it crashed, but I did not debug unmanaged code. So I guess I encountered the same / a similar issue?

**Comment by levlam** [comment]
@zevlg This shouldn't happen in the first place. The error means that new version wasn't able to parse some database entry.

**Comment by levlam** [comment]
@zevlg Could you reproduce this?

**Comment by zevlg** [comment]
> @zevlg Could you reproduce this?

Yeah, reproduces on every start.  Should I provide full log?

**Comment by levlam** [comment]
@zevlg 
Could you add line
```
  LOG(ERROR) << "Parsing " << dialog_id << ": " << format::as_hex_dump<4>(value.as_slice());
```
at the beginning of `MessagesManager::parse_dialog` method and send log with verbosity level 3 from last such logged line to @tdlib_bot?

**Comment by zevlg** [comment]
> @zevlg
> Could you add line
> 
> ```
>   LOG(ERROR) << "Parsing " << dialog_id << ": " << format::as_hex_dump<4>(value.as_slice());
> ```
> 
> at the beginning of `MessagesManager::parse_dialog` method and send log with verbosity level 3 from last such logged line to @tdlib_bot?

done!  verbosity might be higher though

**Comment by levlam** [comment]
@zevlg I pushed the fix to Github. Could you confirm it?

**Comment by zevlg** [comment]
> @zevlg I pushed the fix to Github. Could you confirm it?

Yes, works perfectly, no errors!
