### ISSUE TITLE
Unable to download files larger than 1.5GB - TdLib for Android

### ISSUE THREAD

**Issue by rben820** [tdlib/td#1152]
Hey, 
I tried to download a file above 1.5 GB using the latest version of TdLib for Android, and it failed. 
Is the TdLib for Android support the new file size limit?

**Comment by levlam** [comment]
How do you build it and what is returned by TdApi.GetOption("version")?

**Comment by ranbd4** [comment]
It returned - 1.6.0, which means that I have an old version, I downloaded the library from GitHub yesterday.

**Comment by rben820** [comment]
It returned - 1.6.0, which means that I have an old version, I downloaded the library from GitHub yesterday.

**Comment by levlam** [comment]
You need to ignore line `git checkout v1.6.0` in build instructions to build the latest version.

**Comment by ranbd4** [comment]
Thank you for your answer.
I opened this website: 
https://tdlib.github.io/td/build.html

When I chose Java/Android it gave me the option to download the library, so I switched to macOS instead.
After a few minutes, when it's done, I got the new library. What's next?

**Comment by rben820** [comment]
Thank you for your answer.
I opened this website: 
https://tdlib.github.io/td/build.html

When I chose Java/Android it gave me the option to download the library, so I switched to macOS instead.
After a few minutes, when it's done, I got the new library. What's next? The files that I have in the Android library are different from the files I have in the TdLib (from the GitHub). 
Can you guide me, please....?

**Comment by levlam** [comment]
If you want to use TDLib in Android, you need to follow instructions from https://github.com/tdlib/td/issues/77#issuecomment-640719893.

**Comment by rben820** [comment]
First, thank you very much for your help!
I tried to do that, but I have a lot of errors, especially when I run the `export.sh` .
Will Telegram teem update the Android library soon?

**Comment by levlam** [comment]
Prebuilt version is unlikely to be updated soon.

**Comment by rben820** [comment]
Thanks.
So I'll try again 😊
A question about your response, should I download all the three zip files? And if so, should I repeat about the last step three times?

**Comment by levlam** [comment]
No, you need to download the one more appropriate to you.

**Comment by rben820** [comment]
I don't think they get it, 
I want to update the library, based on your response, I have to choose one of the following options:
`libtdjni.zip` OR `libtdjsonandroid.zip ` OR `libtdjsonjava.zip` ? 
How should I choose? 
Sorry for my questions, but I really don't know what should I do with that.

**Comment by levlam** [comment]
The difference is described in the comment:
```
libtdjni.zip - native JNI wrapper for TDLib with autogenerated Java classes.
libtdjsonandroid.zip - TDLib JSON interface built for Android. All TDLib JSON interface methods have ordinary names prefixed with undescore, for example _td_json_client_create.
libtdjsonjava.zip - JNI wrapper for TDLib JSON interface.
```
If you want to use TDLib from Java using autogenerated Java classes, then download only libtdjni.zip.

**Comment by rben820** [comment]
Okey, I did it, but....

`CMake Error at /usr/local/Cellar/cmake/3.18.0/share/cmake/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file:
  /ndk-bundle/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!`

What am I doing wrong?
I have "Ninja" and Android Studio installed.

**Comment by levlam** [comment]
> Make sure that ANDROID_SDK_ROOT environment variable is correctly set before using the scripts.

**Comment by rben820** [comment]
Thanks, but now I got that error :(

`
/Users/userrr/td/tdutils/td/utils/BigNum.cpp:16:10: fatal error: 
      'openssl/bn.h' file not found
#include <openssl/bn.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[3]: *** [td/tdutils/CMakeFiles/tdutils.dir/td/utils/BigNum.cpp.o] Error 1
make[2]: *** [td/tdutils/CMakeFiles/tdutils.dir/all] Error 2
make[1]: *** [td/CMakeFiles/prepare_cross_compiling.dir/rule] Error 2
make: *** [prepare_cross_compiling] Error 2
`

**Comment by levlam** [comment]
Have you downloaded, unarchived and built OpenSSL 1.1.1?

**Comment by rben820** [comment]
Yes,
I downloaded the OpenSSL (the tar.gs file), and I pasted it in the folder you mentioned in your post. 
Should I put it in another folder?

**Comment by levlam** [comment]
Have you downloaded, **unarchived** and **built** OpenSSL 1.1.1 as specified in the build instructions?

**Comment by rben820** [comment]
Yes, 
After I installed it I received this message:
 `
**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
`
What am I doing wrong?
Thank you again for your help!

**Comment by levlam** [comment]
You don't need to use brew at all. It can't install Android libraries. You need to follow the build instructions to build OpenSSL for Android.

**Comment by rben820** [comment]
Okay, I have a progress, 
now I got that thing:
`
[  9%] Built target tdtl
[ 19%] Built target generate_common
[ 23%] Generate common tl source files
[ 23%] Built target tl_generate_common
[ 28%] Built target generate_mime_types_gperf
[ 28%] Built target tdmime_auto
[100%] Built target tdutils
[100%] Linking CXX executable generate_json
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [td/td/generate/generate_json] Error 1
make[2]: *** [td/td/generate/CMakeFiles/generate_json.dir/all] Error 2
make[1]: *** [td/CMakeFiles/prepare_cross_compiling.dir/rule] Error 2
make: *** [prepare_cross_compiling] Error 2
reeeeeee@eeee-MacBook-Pro libtdjni % 
`

In the `build.sh` I defined the `HOST_ARCH` as: `darwin-x86_64` , I think that this is my problem, but I don't know what I should define there...

**Comment by levlam** [comment]
https://stackoverflow.com/questions/58446253/xcode-11-ld-error-your-binary-is-not-an-allowed-client-of-usr-lib-libcrypto-dylib

Native OpenSSL is not needed at all and `build.sh` is not related to the error. Ho did cmake find that OpenSSL?

**Comment by rben820** [comment]
I used this line to define it:
`OPENSSL_DIR=$/Users/user/td/example/libtdjni/third_party/crypto/openssl-OpenSSL_1_1_1g`
I used this tutorial:
https://proandroiddev.com/tutorial-compile-openssl-to-1-1-1-for-android-application-87137968fee
Is it okay?

**Comment by levlam** [comment]
[This](https://github.com/tdlib/td/files/4991433/crypto.zip) is prebuilt OpenSSL 1.1.1 for Android. You can place the content of the archive in third-party folder and switch to TDLib building.

**Comment by rben820** [comment]
First, thank you so much for your help!
The error that I received was after I ran the script `export.sh` from the unpacked archive top-level directory.

**Comment by rben820** [comment]
@levlam 
Thank you so much for your help and for your patient, I really appreciate it!
We did it! 
I changed line 5 in the `build.sh` file. Instead of using the path `{ANDROID_SDK_ROOT}` I have written the full path. 
All I have to do is replace the new `libtdjni.so` files with the old files inside the `libtd` folder (in the Android project's file)?

Thanks again!
