### ISSUE TITLE
Unsupported secret Mtproto TLS

### ISSUE THREAD

**Issue by hidufer** [tdlib/td#1153]
I'm trying to check an MTProto TLS proxy but I keep revising this error
{'@type': 'error', 'code': 400, 'message': 'Unsupported secret', '@extra': {'request_id': '5c4164bace2f4772804f43caf1eab104'}}
my secret is : "ee32b920dffb51643028e2f6b878d4eac16661712e77686174736170702e636f6d"
it's work fine with normal secret like "dd00000000000000000000000000000000" but When I try to check an mtproto proxy with fake tls is said :  Unsupported secret

**Comment by levlam** [comment]
You are using very old TDLib version.
