### ISSUE TITLE
updateDiceEmojis in TDLib 1.6.7

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1154]
I've got two different emojis in `updateDiceEmojis` - "⚽" and "⚽\xfe0f".

If I send dice message with "⚽\xfe0f" emoji, then official client displays it correctly.  However if I send dice message with "⚽" emoji, official client fails to display it correctly.

What is the reason to have these two emojis and what is the difference between them?

Thanks

**Comment by levlam** [comment]
IOS and macOS uses "⚽\xfe0f" and other OS uses plain "⚽". To allow dice replacement when any of this is entered using keyboard the server return both to all clients. Both should be displayed correctly by clients. Which client fails to do that?

**Comment by zevlg** [comment]
> IOS and macOS use "soccer\xfe0f" and other operating systems use plain "soccer". To allow dice replacement when any of them is entered via emoji keyboard, the server return both to all clients. Both should be displayed correctly by clients. Which client fails to do that?

Here is the behaviour I've got in official Telegram v6.3 on iOS - http://lgarc.narod.ru/pics/IMG_0705.MP4

If dice value already has been seen earlier, then final image is displayed without animation.  If value was not seen previously, then full animation is displayed.  However for *both* (I've been mistaken in first message) football emojis dice message is displayed as infinite initial animation for "unknown" values and as final image for "known" images.
