### ISSUE TITLE
Upload File API

### ISSUE THREAD

**Issue by azaz5959** [tdlib/td#1155]
Hi and thanks in advance.
I'm building a client using tdlib and I have a question on uploading files.
According to the documents , we should use [upload.saveFilePart](https://core.telegram.org/method/upload.saveFilePart) API for small files and [upload.saveBigFilePart](https://core.telegram.org/method/upload.saveBigFilePart) for files greater than 10MB size.
I wanted to know if there is a performance issue for client or server which forces Telegram to provide separate  APIs for uploading files?

**Comment by levlam** [comment]
Yes, there are a lot of issues which requires to use different methods for files of different size. But you are saying that you are "building a client using tdlib" and those are Telegram API methods, not TDLib API methods. In TDLib you just specify a file to send using InputFile and everything other is handled by TDLib.

**Comment by VChernomYA** [comment]
boolFalse#bc799737 = Bool;
boolTrue#997275b5 = Bool;
---functions---
upload.saveFilePart#b304a621 file_id:long file_part:int bytes:bytes = Bool;
