### ISSUE TITLE
where getParticipants ?

### ISSUE THREAD

**Issue by Lynatik911** [tdlib/td#1156]
Hi and thanks in advance.

How can I find out if a person is subscribed to a channel or not? - as an option, the channel cannot be mine. I found out that there is such a method
https://core.telegram.org/method/channels.getParticipants/
But this is no longer supported. Are there any analogues?

**Comment by levlam** [comment]
Of course, you can't find anythinhg besides member count, unless you are an administrator of the channel. If you are an administrator of the channel, you can call `getChatMember`.
