### ISSUE TITLE
Cannot delete message

### ISSUE THREAD

**Issue by eos1d3** [tdlib/td#1157]
I use  TdApi.DeleteMessages to delete a message in SuperGroup, 

```
long[] messageIds = {565722};
client.send(new TdApi.DeleteMessages(-100xxxxxxxxxxL, messageIds, true), defaultHandler);
```

When messageIds contains my own message, it returns, but the message is still there.
```
Ok {
}
```

When messageIds contains messages from others, it returns

```
Error {
  code = 6
  message = "Invalid message identifier"
}
```

My Telegram account is administrator and can delete anyone's message with Telegram clients. So what is the problem?
`Example.java` run normally and can list those groups I join.

**Comment by c0re100** [comment]
Message id should be checked to be divisible by 1048576.
So message id in TDLib is 565722 * 1048576 = 593202511872
https://github.com/tdlib/td/issues/69

**Comment by eos1d3** [comment]
Just tested with

`long[] messageIds = { 565723 * 1048576};`
or
`long[] messageIds = { 593202511872L};`

It returned 
```
Ok {
}
```

But the message is not deleted. What can be wrong?

**Comment by levlam** [comment]
The message IDs are still wrong. You need to receive correct message ID from TDLib. You can check that the ID is right using `getMessage` method.

Between, 593202511872L != 565723 * 1048576.

**Comment by eos1d3** [comment]
I am sure the message ID is correct. Verified by Telegram BOT API logging, Chrome browser Inspect and Telegram link:

`t.me/groupname/565722`

All three confirm the message id is 565722, and the link can show the message.

Using these values, none can be deleted.
[long[] messageIds = { 565722 * 1048576};
long[] messageIds = { 565723 * 1048576};](url)


PS: The 593202511872L is just another message (565723) to test.

**Comment by levlam** [comment]
Check with `getMessage` through TDLib.

**Comment by eos1d3** [comment]
`getMessage` needs parameter `messageId` which is in question.

`public GetMessage(long chatId, long messageId);`

Do you mean`messageId` ID in `GetMessage` does not need conversion?

**Comment by levlam** [comment]
You can check through `getMessage` that passed messageId is wrong. 

Between,
long[] messageIds = { 565722 * 1048576};
creates array with value 497025024 and not 593202511872 due to integer overflow.

**Comment by eos1d3** [comment]
@levlam Thanks for your advice. Retest again and it works now. There are somethings to confirm:

1. What is the meaning of * 1048576?
2. For getting correct value of message ID after integer overflow, I use 
`messageID * 1048576) & 0xFFFFFFFFL`
Is this correct? Is it because C library is 32-bit long and Java is 64-bit long?

**Comment by levlam** [comment]
1. See https://github.com/tdlib/td/blob/3282a873cb24b0c975b6929aeb71a00fc6a18b7c/td/telegram/MessageId.h#L36.
2. No, this formula is still wrong.

**Comment by eos1d3** [comment]
`server_message_id` is 31-bit, so 0xEFFFFFFFL instead of 0xFFFFFFFFL?

**Comment by levlam** [comment]
No. Is there a misprint in `(messageID * 1048576) & 0xFFFFFFFFL`?

**Comment by eos1d3** [comment]
I think not. Just verified:

`System.out.println((565722 * 1048576) & 0xFFFFFFFFL);`

This gives exact result of 497025024 which is the same from yours.

**Comment by levlam** [comment]
And this is exactly Integer overflow and the bug.
