### ISSUE TITLE
Cannot compile, error C1001

### ISSUE THREAD

**Issue by SpriteOvO** [tdlib/td#1158]
```
  Generating Code...
D:\1\td\td\telegram\logevent\LogEventHelper.h(47): fatal error C1001: Internal compiler error. [D:\1\td\build\tdcore.vcxproj]
  (compiler file 'd:\agent\_work\2\s\src\vctools\Compiler\Utc\src\p2\main.c', line 181)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
```

Always get that error.

I've tried compiling tdlib in the virtual machine, installing the latest VS2019 with only the English package selected, and I've tried increasing the system memory to 8GB, but to no avail.

**Comment by levlam** [comment]
This is an MSVC bug. There is a workaround for it in the latest version. You need to ignore `git checkout ...` line in the build instructions to build the latest version.

**Comment by SpriteOvO** [comment]
It works, thank you!
