### ISSUE TITLE
assertion failed!

### ISSUE THREAD

**Issue by SayedSadat** [tdlib/td#116]
why i cant send msg ?

lua » tdbot (https://github.com/vysheng/tdbot)

if msg.content.text.text == 'ping'  then 
   assert (tdbot_function ({_="sendMessage", chat_id=msg.chat_id, reply_to_message_id=msg.id, disable_notification=false, from_background=true, reply_markup=nil, input_message_content={_="inputMessageText", text="pong", disable_web_page_preview=true, clear_draft=false, entities={}, parse_mode=nil}}, dl_cb, nil))

error is  `assertion failed!`

**Comment by levlam** [comment]
What error is received?

**Comment by SayedSadat** [comment]
[ 0][t 0][1520012849.978344202][clilua.cpp:186][!Td]    lua: /home/redis-cli/bot/base.lua:1223: `assertion failed!`

**Comment by levlam** [comment]
Call to lua_pcall has failed.
This error is from tdbot and isn't directly related to TDLib.

**Comment by Mygihub0** [comment]
You need to edit
_ = sendMessage,
