### ISSUE TITLE
Error: check(!td.empty()) failed.

### ISSUE THREAD

**Issue by zerodwide** [tdlib/td#1160]
Hi Brogrammers

1. please guide me how to avoid getting this error?
` check(!td.empty()) failed`
i'm using c# sample codes and sometimes getting this error and then app crushing.
i'm pretty sure that TdClient has been initialized already and most of times works without error.
also i had checked client is not null and not disposed then i send requests but no luck!

2. How to handle native/unmanaged/unsafe errors from TdLib in c#?
i had put try catch everywhere why that native error won't caught? 
after some googling found out try{}catch(Exception){} wont work on native unmanaged codes
so i have used try{}catch(){} but still when error occurred it will crush my app!

**Comment by levlam** [comment]
What TDLib version are you using? The latest from master, TDLib 1.6.0 or older? Could you send log with verbosity level 4 to @tdlib_bot?

This is a failed assertion and a critical error, which excludes possibility of further program run after it is happenned. This is not an exception or an ordinary error, so it can't be catched to continue execution normally.

**Comment by zerodwide** [comment]
thanks @levlam for replying.
Yes TDLib is 1.6.0
my exact latest commit: 945a3a1dc395bde69d63fff89d6936cd295be0d9 on 2020-02-09
I will set verbosity level on 4 and wait for happening again

**Comment by levlam** [comment]
@zerodwide Have you managed to reproduce this?

**Comment by zerodwide** [comment]
@levlam actually i have set many more try/catch so i never again saw that error!
I think you should close the issue, if i saw it in future again, i will append logs
