### ISSUE TITLE
[URGENT] Tdlib Dotnet Build For Arm 

### ISSUE THREAD

**Issue by bsglinux16** [tdlib/td#1165]
guys

C # Xamarin requires arm assemblies of libtdjson.so file
I tried it with CMake but failed.

I have 64 bit builds
I need arm compilations urgently

If I Only Learn How To Build Arm On A 64-bit System, It Will Be Enough For Me

Many Thanks In Advance

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/906.
