### ISSUE TITLE
Different photo compression between desktop client and tdlib?

### ISSUE THREAD

**Issue by omgitsraven** [tdlib/td#1166]
I just sent myself an image as a photograph (i.e. compressed), in the Telegram desktop client.

This is the file that I sent:
![RAW](https://user-images.githubusercontent.com/8540042/89852567-2d7f9980-db5d-11ea-9133-55f0d6c33267.png)

This is a screenshot of how it looks when it's viewed in the Telegram desktop client, after it's been compressed:
![COPY](https://user-images.githubusercontent.com/8540042/89852863-d1694500-db5d-11ea-93e3-09e9a84695df.png)

Downloading the actual file in the telegram desktop client instead of screenshotting actually adds MORE compression ( https://github.com/telegramdesktop/tdesktop/issues/4619 ), so I wrote a tdlib client to save photos instead, in an attempt to work around this bug.

HOWEVER: when I download the file in tdlib, it actually shows up with MORE compression than it does in the desktop client (and yet, LESS than when it's SAVED in the desktop client!)
![FROMNODE](https://user-images.githubusercontent.com/8540042/89853062-52284100-db5e-11ea-9423-7e9e1a8c5c05.jpg)

tdlib only returned two sizes for this photo; a tiny thumbnail, and the one I attached.
Why does it not return the file that's visible in the desktop client?

**Comment by levlam** [comment]
Telegram Desktop can likely show original file until you restart the client, which was not saved on Telegram servers.
Clients doesn't compress downloaded photos, which would be very strange. Also, TDLib doesn't compress photos itself at all, which is app responsibility.

**Comment by omgitsraven** [comment]
Ahh, good point -- OK, here is a copy that a friend sent to *me*, then:

Screenshotted from desktop client:
![desktop](https://user-images.githubusercontent.com/8540042/89899735-b70c8700-dbb0-11ea-8795-6ff521be304c.png)

Retrieved from tdlib:
![5012669749095672291_(0)](https://user-images.githubusercontent.com/8540042/89899825-d73c4600-dbb0-11ea-960e-94fb55f92bf5.jpg)

They still aren't the same file:
![difference](https://user-images.githubusercontent.com/8540042/89899964-11a5e300-dbb1-11ea-9d42-3b6d0b8cdb9f.png)

in case that difference image is too dark for your monitor, here it is with the levels exaggerated:
![difference_leveled](https://user-images.githubusercontent.com/8540042/89900000-1ff3ff00-dbb1-11ea-9817-d18d69c1c56d.png)

**Comment by omgitsraven** [comment]
also, just to rule out it being some kind of color profile difference, there's nothing of the sort in the file downloaded from tdlib:

![image](https://user-images.githubusercontent.com/8540042/89900157-5a5d9c00-dbb1-11ea-9743-6c33ab958ecc.png)

also, to rule out it being some artifact of the screenshotting process; using telegram desktop's "copy" feature produces the same pixels as screenshotting does:
![screenshot](https://user-images.githubusercontent.com/8540042/89900513-d6f07a80-dbb1-11ea-8438-1ee2adeb97f5.png)![copy](https://user-images.githubusercontent.com/8540042/89900514-d6f07a80-dbb1-11ea-8f23-cddf66a9ba78.png)![difference_screenshot_copy](https://user-images.githubusercontent.com/8540042/89900515-d6f07a80-dbb1-11ea-9daa-22331d5b77a4.png)

**Comment by levlam** [comment]
The available photo sizes are definitely the same for all clients.

**Comment by omgitsraven** [comment]
Then what is this? ![89900000-1ff3ff00-dbb1-11ea-9817-d18d69c1c56d](https://user-images.githubusercontent.com/8540042/89901106-a0672f80-dbb2-11ea-8b54-989d801ec2ff.png)

**Comment by levlam** [comment]
Whatever it is, this is not a difference between downloaded files.
