### ISSUE TITLE
Time skew?

### ISSUE THREAD

**Issue by terrytw** [tdlib/td#1167]
There have been user reports from both python and go implementation of mtproxy, that Telegram X Android client tries to reach mtproxy server with wrong time, causing connection issues: https://github.com/9seconds/mtg/issues/155, https://github.com/alexbers/mtprotoproxy/issues/223

It only happens with faketls mode. 

From my observation, it seems that after successfully connecting to a server, Telegram X client's time starts to skew, you can see it from
![90004337-07c2d380-dcc8-11ea-9fa3-0a94bf749bc5](https://user-images.githubusercontent.com/24227628/90005131-5c1a8300-dcc9-11ea-9776-84bc528429c1.png)
Note that client reported timestamp is about 2 minutes behind actual time. 

Once successfully connecting to server, time is calibrated, connection could resume functioning, but only for a short period of time, before the same problem occurs. 

Vanilla telegram android client does not have this kind of problem. 
(Actually vanilla telegram had this problem for a short time, it was introduced in https://github.com/DrKLO/Telegram/commit/2eafc07314532d9ec31bdb63378a30a4969c26db and fixed by https://github.com/DrKLO/Telegram/commit/df90eface5ebd755ea86c3a4eec66fe5b6e29041, according to mtg's developer 9seconds)

**Comment by levlam** [comment]
The used time is synced through a lot of external sources and should be always correct. There was no issues found or reported about this synchronization. Please collect TDLib logs for 2-5 minutes with verbosity level 6 and send the log file to @tdlib_bot.

**Comment by terrytw** [comment]
@levlam Can you please tell me how to do it with Telegram X?

**Comment by Sajilck** [comment]
@terrytw 
 Please go to settings > version number > application logs > TDLib logs, then:
1. change verbosity level to MORE > 6
2. increase Max Log size to 100000000 bytes
3. delete old TDLib logs
4. reproduce the issue
5. change TDLib log verbosity back to ASSERT
6. send the file to @tdlib_bot in PM

**Comment by terrytw** [comment]
@Sajilck Thank you!
I have sent log to tdlib_bot. 
I would like to add a few explainations.
In the log, at timestamp 1597313767, telegram closed session and tried to establish a new mtproto connection. On the server side, I got a handshake with a timestamp of 1597313649.

**Comment by levlam** [comment]
@terrytw The cause of the issue was likely mitigated in TDLib.

**Comment by terrytw** [comment]
@levlam Good to know! 
I gues it is https://github.com/tdlib/td/commit/9c40e372885d25eb03fa528fc6b5a63aabdda3dc and https://github.com/tdlib/td/commit/775ef44ed8f6d52db99f570568092cd6effb870e, right? 
I will close this issue for now and wait for telegram X to implement the fix.

**Comment by levlam** [comment]
@terrytw Right.
