### ISSUE TITLE
Android| Can't get the most recent messages from a public channel

### ISSUE THREAD

**Issue by rben820** [tdlib/td#1168]
Hey,
I have an odd problem using TdLib for Android.
I try to get messages from a public channel, and I used `GetChatHistory` in order to get the messages from it.
In order to get the `chatId`, I use `SearchPublicChat` and it works (I get the `chatId`). 
The problem is that sometimes I get old messages and not the most recent ones. 
I have noticed that only if I join the channel the problem solved (and I get the most recent messages every time). Just want to clarify that I'm not changing anything on my Code, and the only thing that I did was to join the channel.

For any case, here is how I get the messages:
(The first time: `fromMessageId == 0`)

`Client.getClientIfNotNull().send(new TdApi.GetChatHistory(chatId, fromMessageId, 0, howManyToAdd, false)` 

Thanks!

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/1125.
