### ISSUE TITLE
CSharp Samples outdated

### ISSUE THREAD

**Issue by habeebmatrix** [tdlib/td#1169]
The CSharp example seems to be outdated.
The nuget package reference and namespace and class names in the sample doesn't exist anymore.
Any hint on Signing in with new API?

**Comment by levlam** [comment]
The NuGet package is provided by the third party. The code in https://github.com/tdlib/td/tree/master/example/csharp is on a par with up-to-date TDLib version.

**Comment by habeebmatrix** [comment]
Thanks for the confirmation. I was confused between the nuget package and this repository. Now I know why the namespaces and classes in the nuget package is different. 
Thanks for the prompt reply.
