### ISSUE TITLE
Getting Tdlib Java new master branch compiled ?

### ISSUE THREAD

**Issue by comm-amir-david** [tdlib/td#1172]
Hi,
can someone please send me new Compiled Tdlib for java android ?
the new master branch and not the 1.60 version ?.

Thanks.

**Comment by levlam** [comment]
You need to build it yourself as described in https://github.com/tdlib/td/issues/77#issuecomment-640719893.

**Comment by Cavallium** [comment]
I have a repository in which I build automatically TDLib for java.
This is the latest release with tdlib binaries compiled today:
https://github.com/tdlight-team/tdlight-java/releases/tag/v3.168.3-tdlib

**Comment by comm-amir-david** [comment]
Hi,

Thank you very much

But I was unable to add this to my project I am getting unable to resolve ?

I added the repository to the gradle app build script.

And the implementation to the project gradle file.

 

What am I doing wrong ??

**Comment by levlam** [comment]
@comm-amir-david I can't understand what you did. You need to compile the latest TDLib first before you can use it.

**Comment by levlam** [comment]
Prebuilt TDLib for Android was updated to 1.7.0: https://core.telegram.org/tdlib/tdlib.zip.
