### ISSUE TITLE
building tdweb fails with error: no member named 'pop_front'...

### ISSUE THREAD

**Issue by hnz101** [tdlib/td#1175]
Building tdweb with emsdk 1.39.5 fails with the following errors.
The last time I build it was on 31.07.2020 without any problems.

> ./build-tdlib.sh
> [...]
> Scanning dependencies of target tdclient
> [ 97%] Building CXX object CMakeFiles/tdclient.dir/td/telegram/Client.cpp.o
> /build/td/td/telegram/Client.cpp:70:18: error: no member named 'pop_front' in 'std::__2::queue<td::MultiClient::Response, std::__2::deque<td::MultiClient::Response, std::__2::allocator<td::MultiClient::Response> > >'
>       responses_.pop_front();
>       ~~~~~~~~~~ ^
> /build/td/td/telegram/Client.cpp:82:27: error: no member named 'push_back' in 'std::__2::queue<td::MultiClient::Response, std::__2::deque<td::MultiClient::Response, std::__2::allocator<td::MultiClient::Response> > >'
>         impl_->responses_.push_back({client_id_, id, std::move(result)});
>         ~~~~~~~~~~~~~~~~~ ^
> /build/td/td/telegram/Client.cpp:85:27: error: no member named 'push_back' in 'std::__2::queue<td::MultiClient::Response, std::__2::deque<td::MultiClient::Response, std::__2::allocator<td::MultiClient::Response> > >'
>         impl_->responses_.push_back({client_id_, id, std::move(error)});
>         ~~~~~~~~~~~~~~~~~ ^
> /build/td/td/telegram/Client.cpp:92:27: error: no member named 'push_back' in 'std::__2::queue<td::MultiClient::Response, std::__2::deque<td::MultiClient::Response, std::__2::allocator<td::MultiClient::Response> > >'
>         impl_->responses_.push_back({client_id_, 0, nullptr});
>         ~~~~~~~~~~~~~~~~~ ^
> /build/td/td/telegram/Client.cpp:156:3: error: constructor cannot be redeclared
>   Impl() = default;
>   ^
> /build/td/td/telegram/Client.cpp:108:3: note: previous definition is here
>   Impl() {
>   ^
> /build/td/td/telegram/Client.cpp:207:16: error: 'Impl' is a private member of 'td::MultiClient'
>   MultiClient::Impl impl_;
>                ^
> /build/td/td/telegram/Client.h:164:9: note: declared private here
>   class Impl;
>         ^
> 6 errors generated.
> shared:ERROR: '/build/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=5 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/build/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/build/emsdk/upstream/emscripten/system/include -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/build/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/build/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/build/emsdk/upstream/emscripten/cache/wasm-obj/include -D_FILE_OFFSET_BITS=64 -I/build/td -I/build/td/td/generate/auto -I/build/td/tdactor -I/build/td/tdutils -I/build/td/example/web/build/wasm/tdutils -I/build/td/tdnet -I/build/td/tddb -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wpointer-arith -Wcast-qual -Wsign-compare -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wc++14-compat-pedantic -Wdeprecated -Qunused-arguments -Wodr -DNDEBUG -Os -fPIC -c -DEMSCRIPTEN /build/td/td/telegram/Client.cpp -fno-inline-functions -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/tdclient.dir/td/telegram/Client.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
> make[3]: *** [CMakeFiles/tdclient.dir/build.make:64: CMakeFiles/tdclient.dir/td/telegram/Client.cpp.o] Error 1
> make[2]: *** [CMakeFiles/Makefile2:118: CMakeFiles/tdclient.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:463: CMakeFiles/td_wasm.dir/rule] Error 2
> make: *** [Makefile:292: td_wasm] Error 2

**Comment by levlam** [comment]
Thanks for the report. This should be fixed in the master now. Could you confirm?

**Comment by hnz101** [comment]
> 
> 
> Thanks for the report. This should be fixed in the master now. Could you confirm?

Yes, the build issue is fixed. Thank you!
