### ISSUE TITLE
At which point in login sequence can one start sending requests?

### ISSUE THREAD

**Issue by ars3niy** [tdlib/td#1176]
A tdlib-based client will go through a login sequence where authorization state will go from authorizationStateWaitTdlibParameters, authorizationStateWaitEncryptionKey, eventually reaching authorizationStateReady, and connection state will go from connectionStateConnecting to connectionStateUpdating to connectionStateReady.

I'd like to ask, at which point in login sequence can one start sending "normal" requests, such as sendMessage, downloadFile etc.? I don't want to experiment because experiments don't guarantee that observed behaviour will not change in future versions of tdlib. What's the official answer?

**Comment by levlam** [comment]
Ignore connection state updates, they are to show a human-readable hint status and are completely irrelevant.

You can send most requests only if the authorization state is `authorizationStateReady`. If a request is documented as "Can be called before authorization", it can be called any time before authorization and TDLib will process it as soon as possible. Authentication requests documented as "Works only when the current authorization state is ..." can be called in the corresponding authorization states.

**Comment by ars3niy** [comment]
Thanks for clarification!
