### ISSUE TITLE
tdlib java replaces characters in message text randomly

### ISSUE THREAD

**Issue by schlierf-io** [tdlib/td#1177]
Reading messages with tdlib java replaces sometimes single characters. For example

![image](https://user-images.githubusercontent.com/48359013/91484086-f9201300-e8a8-11ea-95f0-cd5efaca40c5.png)

The MessageText object contains Chfjoy instead of Chfjpy.

Why is the p replaced by an o?

**Comment by levlam** [comment]
It definitely doesn't. The error is in some other place. You can enable TDLib logs to see that and probably to debug the issue.

**Comment by dudy86** [comment]
Dakujem, aj ked neviem za čo.

**Comment by dudy86** [comment]
zedli ste mi vsetci kokot
