### ISSUE TITLE
Forward failed - Code-5 Chat to forward messages to not found

### ISSUE THREAD

**Issue by habeebmatrix** [tdlib/td#1178]
I am trying to forward message. The message update is received and Forward is called. But actual forward doesn't happen and it says "5 message = "Chat to forward messages to not found". What could be the reason? I have confirmed that the source, destination id and message id are valid.

```
New Message: TdLib.TdApi+MessageContent+MessageText - -457416738 - 8/28/2020 9:30:23 AM
[ 3][t 5][1598607023.301416636][Td.cpp:3592][#1][!Td][&td_requests]     Receive request 6: forwardMessages {
  chat_id = -10014947xxxxx
  from_chat_id = -45741xxxx
  message_ids = vector[1] {
    47605xxxx
  }
  options = sendMessageOptions {
    disable_notification = false
    from_background = true
    scheduling_state = null
  }
  as_album = true
  send_copy = true
  remove_caption = false
}
[ 3][t 0][1598607023.301571131][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 0.100000
[ 3][t 5][1598607023.305535555][Td.cpp:4737][#1][!Td][&td_requests]     Sending error for request 6: error { code = 5 message = "Chat to forward messages to not found" }
```

**Comment by levlam** [comment]
You must receive all IDs from TDLib before you can use them. See https://github.com/tdlib/td/issues/791.

**Comment by habeebmatrix** [comment]
What exactly is it to receive all Ids mean?
As mentioned in the other thread, I tried making a call to GetChats before forwarding message, but that didnt help.

**Comment by levlam** [comment]
The ID -1001494740234 was not received from the TDLib instance and is hard-coded somewhere in the code (ore received from some other external source). You can't use it before the chat is known to the TDLib instance. GetChats return some chats from the top of the main chat list. There is no guarantee that the chat will be among these chats.

**Comment by habeebmatrix** [comment]
Thanks. The issue is solved by calling GetChats once before first sending message.
