### ISSUE TITLE
tdjson <=> jni

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1181]
Is there any way to call tdjson api from jvm or convert between jni object and tdjson string?

Sometimes there are multiple programs that need to interoperate...

**Comment by levlam** [comment]
You can use JSON interface from Java in the same way as from any other programming language. But you can't receive all updates and responses twice through different interfaces, so you can't use two interfaces simultaneously.

You should never need to pass data from one TDLib instance to another, so just use the same interface on all platforms.
