### ISSUE TITLE
Voicenote: Cleanup after upload

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1183]
When sending a voicenote we want to clean up the temp file as soon as possible. As upload happens asynchronously in tdlib, how could we know when uploading has finished to delete the temp ogg file?

Bonus question, how can this be done for any other attachment/content/input message?

Thanks BR Florian

**Comment by levlam** [comment]
Do you use `inputFileGenerated` to upload the file while it is created?

**Comment by Flohack74** [comment]
No, currently we point to inputFileLocal.

**Comment by levlam** [comment]
Then switching to `inputFileGenerated` will rid you from managing temporary file lifetime.

Otherwise, the file can be deleted only after the message is successfully (or unsuccessfully) sent. But then the file will need to be redownloaded from the server.

**Comment by Flohack74** [comment]
Ok so is there any description of hw to use it? Our first test seems to be unsuccessful :)

**Comment by levlam** [comment]
https://github.com/tdlib/td/issues/126

**Comment by Flohack74** [comment]
Ok so I could "fake" generation if the file exists already, and on receiving start immediately finish it? And then receive stop and it can be deleted?

**Comment by levlam** [comment]
You may be asked to regenerate the file any time, so immediate deletion sometimes isn't appropriate.

Why do you need to delete the file if it existed previously? If it didn't exist, then you can create it directly in the location specified in the update `updateFileGenerationStart`. After that file lifetime is managed by TDLib.

**Comment by Flohack74** [comment]
Well its a voice note recording, so user presses record on the UI, and we need to start to buffer the audio data somewhere. Or how would that be solved.

**Comment by levlam** [comment]
You can buffer it to the file pointed by TDLib and even upload the file while it is still recorded. Just use the method `uploadFile` with `inputFileGenerated`.

**Comment by mymike00** [comment]
So, to be sure to have understand everything correctly:

1. the user presses the button to record a voice note
2. we send a `sendMessage` with `input_message_content` containing
```
{
  "@type": "inputMessageVoiceNote",
  "voice_note": {
    "@type": "inputFileGenerated",
    "original_path": ".ogg",
    "conversion": "record_voice"
  }
}
```
3. we wait for `updateFileGenerationStart` and read the field `destination_path`
4. only then we can actually start recording the voice note in the file pointed by `destination_path`
5. when the users finishes to record the voice note we can send a `finishFileGeneration` with the same `generation_id` as the one received in `updateFileGenerationStart`
- if the users discards the voice note we send a `finishFileGeneration` with something written in the `error` field and we should receive a `updateFileGenerationStop`

Question: is `updateFileGenerationStart` guaranteed to arrive immediately after the `sendMessage` with `inputFileGenerated`? If not we may want to start the voice note recording immediately when the users presses on the button, record the file in a location outside tdlib's file system and move the file later on when the update is received. In that case, should we put the file real path in `original_path` inside `inputFileGenerated`? That way the file gets moved by tdlib when we send `finishFileGeneration`, right?

**Comment by levlam** [comment]
> `updateFileGenerationStart` guaranteed to arrive immediately after the `sendMessage` with `inputFileGenerated`?

Yes.

Instead of `sendMessage` you can call `uploadFile` and use `sendMessage` only if the user didn't cancel recording.

If you want to upload the file during recording, you can use `setFileGenerationProgress`.

**Comment by Flohack74** [comment]
@levlam we went for the easier route with sendMessage but it also seems to work quite well. 2 remarks:
- It should be written somewhere that tdlib creates the target file for the generation in advance
- Also original_path must be unique, otherwise tdlib reuses the first file ever sent and not even asks for a generation

**Comment by levlam** [comment]
@Flohack74 
1. TDLib creates the target file to ensure that the target path is unique.
2. In fact, the `conversion` and not `original_path` needs to be unique if the result file needs to be different.
