### ISSUE TITLE
Check if chat member has read / seen / viewed message in Chat

### ISSUE THREAD

**Issue by prominence-paper** [tdlib/td#1185]
How can I check if a chat member has read/seen/viewed message in Chat?

**Comment by RememberTheAir** [comment]
It's not possible, Telegram doesn't allow to do that

**Comment by prominence-paper** [comment]
![image](https://user-images.githubusercontent.com/53373631/92453851-58a7e800-f1f2-11ea-8e55-3f3cbd101578.png)
If that is the case, what does the 2 ticks on the bottom right means?

**Comment by RememberTheAir** [comment]
In supergroups, they appear when one of the members views the message. In normal groups it is shown when all members view it (I'm not sure about this one). Anyway, the Telegram API doesn't expose any method to see who viewed a message in a group chat

**Comment by prominence-paper** [comment]
Thanks for the explaination. I find this is quite an essential requirement to be aware own sent messages are being read/seen/viewed by chat members. Do you know any reasons for not exposing it on Telegram API?

**Comment by levlam** [comment]
@RememberTheAir In all chats the second tick is shown when the message is read by any other chat member.

**Comment by levlam** [comment]
@prominence-paper Unlike in other messengers Telegram chats can have up to 200000 members. It is not possible to store for each message all 200000 times when the message was viewed. It would also lead to enormous amount of the network data usage.

**Comment by prominence-paper** [comment]
Appreciate the Telegram's capability to hold large members in a chat and understand the enormous load to keep the status of every single message. 
How about just storing the last read/seen/viewed message id or timestamp of a chat member? Any messages before the last are considered read/seen/viewed? This way, the load should be much lesser.

**Comment by levlam** [comment]
Such message IDs are stored, but they are available only to the user itself. Synchronization of 200000 such IDs for every member of a big chat will also create enormous load.

**Comment by prominence-paper** [comment]
Understood having such feature for supergroup chat type contributes enormous load.
How about provide this capability for other chat types (private, secret and, basic group that limits members up to 200)? My requirement is for these chat types only.

**Comment by levlam** [comment]
It is generally bad to have a feature that disappears when the chat grows, but this can be theoretically added in the future.

**Comment by prominence-paper** [comment]
Thanks for consideration. 
I believe majority of Telegram chat groups have small number of members. Till date, Telegram Party public chat group only hit 15K members. Having this essential feature will certainly benefit the Telegram community and, grow the creativity and usage of well loved tdlib API :D

**Comment by levlam** [comment]
15K is much more than a possible limit for that feature. The most common public group size is 1000-10000 members, so the feature is suitable only for small private groups. Nevertheless, this must be implemented server-side and can't be implemented in TDLib without server-side support.

**Comment by prominence-paper** [comment]
Thanks for sharing insights on Telegram usage and the limits. 
Kindly share how to contact server-side team and raise this feature request.

**Comment by levlam** [comment]
You can send general suggestions through in-app support or by menthioning @telegram on Twitter.
