### ISSUE TITLE
How does the bot check if it is deactivated by a user

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1186]
Can only send messages and handle error 400?

**Comment by levlam** [comment]
There is a `userTypeDeleted` for that, but errors on message sending needs to be handled anyway.

**Comment by nekohasekai** [comment]
@levlam What I mean is to check if the bot is disabled by the user (block), not whether the user's account is deleted

**Comment by nekohasekai** [comment]
What I mean is to check if the bot is disabled by the user (block), not whether the user's account is deleted

**Comment by levlam** [comment]
Yes, the bot must handle the error in `updateMessageSendFailed`.
