### ISSUE TITLE
Receive updates for multiple instances

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1187]
Starting a thread for each instance or sequential reading with timeout is not suitable for many instances.

Now my implementation is to use receive with 0 timeout for all instances, even if the delay is executed in the case of empty updates, sometimes I still receive the "updates.gitdiff...rate limit" warning, which seems to warn me Read updates too frequently

**Comment by levlam** [comment]
Starting a thread for each instance is the expected behavior.

By passing timeout 0 you just vaste your CPU time. This doesn't affect TDLib's behavior.
