### ISSUE TITLE
Missed Implementation of account.setContactSignUpNotification#cff43f61

### ISSUE THREAD

**Issue by zerodwide** [tdlib/td#1188]
Hi, I saw that some methods are not available in tdlib like `account.setContactSignUpNotification#cff43f61`
Is there any special reason that some methods are eliminated?
I understand that some method has changed but has same functionality with different name.

Is there any equivalent to account.setContactSignUpNotification?
Thanks

**Comment by levlam** [comment]
It is accessible via option "disable_contact_registered_notifications".

**Comment by zerodwide** [comment]
Thanks @levlam!
