### ISSUE TITLE
inlineKeyboardButtonTypeLoginUrl button continues querying for the login

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1189]
I've got the `inlineKeyboardButtonTypeLoginUrl` from the https://comments.app domain.  In order to add comment I need to login into this domain first, so I've executed `getLoginUrlInfo` method and got `loginUrlInfoRequestConfirmation` in the reply.  Next I've executed `getLoginUrl` to get the url to login.  Official "Telegram" user notified me that "comments.app" website has been connected, and I see it in the results of the `getConnectedWebsites` method.  And I'm able to add comments

Next, I see another message with `inlineKeyboardButtonTypeLoginUrl` button of "comments.app" domain, and I've expected `getLoginUrlInfo` for this button to return `loginUrlInfoOpen` (since website is already connected), but got `inlineKeyboardButtonTypeLoginUrl` instead.

What is the conditions for `loginUrlInfoOpen` to be returned for the `getLoginUrlInfo` method?

Thanks

**Comment by levlam** [comment]
@zevlg Have you allowed the bot to write you?

**Comment by zevlg** [comment]
No I did not.  With `allow_write_access` set to true `loginUrlInfoOpen` is returned for the second `getLoginUrl` request, as expected.

This is a bit confusing though.  Because each time you need to open `inlineKeyboardButtonTypeLoginUrl` you have to bypass login confirmation (or allow write access to the bot) and official "Telegram" user notifies you.  What is also confusing, if you login for the first time, and do not login (just open button's url as is) for the second time, you appears as logged in user anyway

If user wants to change his mind about `allow_write_access` he could disconnect the site and perform confirmation once more

**Comment by levlam** [comment]
The bot asks for access to write you messages, so you will be prompted each time before the access is given.

If user opens the URL as is, you need to manually log in on the site. The site can save any data in cookies, so it can keep you logged in.

If user chooses to automatically login, then basic information about you will be appended to the URL as described in https://core.telegram.org/widgets/login#receiving-authorization-data. The login data will be stored in the cookies of the third-party site, so there is no way to delete it. Disconnecting the site in the settings only removes automatic appending of user information to the URL and restores the confirmation flow.

If user allows write access, then a service notification will be sent to the bot on behalf of the user, effectively allowing the bot to write the user. To remove write access the user needs to block (a.k.a. stop) )the bot.

**Comment by zevlg** [comment]
So, everything works as designed and that is expected behaviour.  To get `loginUrlInfoOpen` I need to allow write access, correct?

**Comment by levlam** [comment]
> To get loginUrlInfoOpen I need to allow write access, correct?

If the bot asks for write access, then yes.

**Comment by zevlg** [comment]
Got it, thanks!
