### ISSUE TITLE
[ARM] Undefined reference to __atomic_compare_exchange_8

### ISSUE THREAD

**Issue by looki** [tdlib/td#1191]
On a Raspberry Pi 4 running Raspbian 10 Kernel 4.19.97 using GCC 8, I tried to build the library with the Github instructions, but received the error in the title in tdutils/td/utils/Time.cpp.

Luckily, the error was easily fixed by making a small change to tdutils/CmakeLists.txt:

```diff --git a/tdutils/CMakeLists.txt b/tdutils/CMakeLists.txt
index 504ae8e5..c289d06e 100644
--- a/tdutils/CMakeLists.txt
+++ b/tdutils/CMakeLists.txt
@@ -345,6 +345,8 @@ endif()
 
 if (CMAKE_HOST_SYSTEM_NAME MATCHES "NetBSD")
   target_link_libraries(tdutils PUBLIC /usr/pkg/gcc5/i486--netbsdelf/lib/libatomic.so)
+else()
+  target_link_libraries(tdutils PUBLIC atomic)
 endif()
```
No idea why libatomic is not being linked and whether it's supposed to be, but as far as I can tell I followed the instructions exactly.

**Comment by levlam** [comment]
This is the right fix.

We don't know a universal way to determine whether `libatomic` needs to be linked in. The proposed change will break the build on some platforms, so for now we don't link `libatomic` explicitly and expect CMakeLists.txt to be manually edited on the minority of the platforms, which actually requires linking against libatomic.

**Comment by looki** [comment]
I see, thanks. It's an unfortunate situation, but not a huge deal.
