### ISSUE TITLE
Option to limit the size of pending updates

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1192]
If I open a tdlib session after some days, Telegram sends to tdlib an huge amount of updates.
If the session has a lot of chats, the queue becomes very big (sometimes the ram usage grows by 2 or more GiB), before shrinking after some seconds.
The problem is that the memory will not be reclaimed by the os after the queue has reduced in size.

It will be very helpful to add an Option to set the maximum unprocessed data before pausing the reception of new updates from the server.

Now TDLib can store tens of millions updates or more, causing the crash of the process when there is no more ram available.

**Comment by levlam** [comment]
The app is supposed to process the updates fast enough to this never happen. Updates aren't generated solely by the server, there are a lot of other update sources. It is not possible to completely stop library execution, because the app is too slow in updates handling.

**Comment by Cavallium** [comment]
I know that the app should process everything in time, but the problem is that in the real world this situation happens.
There are a lot of other update sources but remote telegram updates are almost the only cause of this problem: I can't imagine other sources causing this high throughput of requests in a small fraction of time.

**Comment by Cavallium** [comment]
If the addition of an user configurable option is too difficult, it might help just to hardcode a simple upper bound of the data to process with an absurd number.

**Comment by levlam** [comment]
It is not possible to stop the updates. You can try to use `setNetworkType` with `networkTypeNone` to disable network for TDLib, but there can't be any guarantees that this helps.
