### ISSUE TITLE
Return error using tdjson.dll in Delphi {"@type": "error", "code": 400, "message": "Failed to parse request as JSON object: Unexpected string end"}

### ISSUE THREAD

**Issue by dieletro** [tdlib/td#1195]
I am developing a test project using tdjson on the return of the request.
I pass the parameters according to the example in Python but I get this error message

After activating the receiver of tdjson it returns this

{"@type": "updateOption", "name": "version", "value": {"@ type": "optionValueString", "value": "1.6.0"}}
{"@type": "updateAuthorizationState", "authorization_state": {"@ type": "authorizationStateWaitTdlibParameters"}}

which leads me to think that the interface part of the dll is ok, since I get a login return from api tdlib

**Comment by levlam** [comment]
You are sending wrong request, which is not a JSON-encoded object. What exactly you are sending?

**Comment by dieletro** [comment]
I'm sending this
 
{"@type": "setTdlibParameters", "parameters": {
   "database_directory": "tdlib",
   "use_message_database": True,
   "use_secret_chats": True,
   "api_id": '+ ApiId +',
   "api_hash": "'+ ApiHash +'",
   "system_language_code": "en",
   "device_model": "Desktop",
   "application_version": "1.0",
   "enable_storage_optimizer": True}}

As soon as I receive the return of
{"@type": "updateAuthorizationState", "Authorization_state": {"@ type": "AuthorStateWaitTdlibParameters"}}

**Comment by levlam** [comment]
It is likely, that something is wrong with ApiId or ApiHash. Print the resulting JSON to see the issue.

**Comment by dieletro** [comment]
I need to send this request before
{"@type": "authorizationStateWaitTdlibParameters", "@ extra": 783690200}

this field "@extra" is for me to associate my requests with an ID and I can generate randomly or do I need to respect any criteria for that?

**Comment by dieletro** [comment]
> É provável que algo esteja errado com ApiId ou ApiHash. Imprima o JSON resultante para ver o problema.

The return I receive when sending that json authentication object is exactly this
{"@type": "error", "code": 400, "message": "Failed to parse request as JSON object: Unexpected string end"}

**Comment by dieletro** [comment]
This is the outgoing json
{"@type": "setTdlibParameters", "parameters": {"database_directory": "tdlib", "use_message_database": true, "use_secret_chats": true, "api_id": 1303XXX, "api_hash": "2e608983b702XX467b67676 system_language_code ":" en "," device_model ":" Desktop "," application_version ":" 1.0 "," enable_storage_optimizer ": true}}

**Comment by dieletro** [comment]
[Video_Exemple_TDLIb_Delphi_Error.zip](https://github.com/tdlib/td/files/5243346/Video_Exemple_TDLIb_Delphi_Error.zip)
See this video I made of the error being displayed at the time of authentication

**Comment by levlam** [comment]
The only way to receive "Failed to parse request as JSON object:" is to send a wrong request. Just print all the requests and find the one which is incorrectly encoded in JSON. Also ensure that UTF-8 is used as an internal JSON encoding.

**Comment by dieletro** [comment]
ok, i will do these procedures and return as soon as i can, informing what i have as json object being sent and the issue of encoding for UTF8 too

**Comment by dieletro** [comment]
Hello, levlam!
I was able to find the cause of the problem and I am completing the tests in the Delphi language and I am willing to share this with the community and if it is possible, tell me how I can make this sample project using tdjson.dll available with Delphi and lazarus.

Thanks a lot for the help!

**Comment by dieletro** [comment]
The problem was only in a type conversion to prepare the data for the pointers, a failure of mine when I did not observe the types that should be declared!

> Hello, levlam!
> I was able to find the cause of the problem and I am completing the tests in the Delphi language and I am willing to share this with the community and if it is possible, tell me how I can make this sample project using tdjson.dll available with Delphi and lazarus.
> 
> Thanks a lot for the help!

**Comment by levlam** [comment]
If you publich the source code on Github or on some other source code sharing website, I would add the link to it to the list of examples.

**Comment by dieletro** [comment]
> If you publich the source code on Github or on some other source code sharing website, I would add the link to it to the list of examples.

OK!

**Comment by dieletro** [comment]
> If you publich the source code on Github or on some other source code sharing website, I would add the link to it to the list of examples.

would it be possible for me to be part of the TDLib contributors?

**Comment by levlam** [comment]
@dieletro If you provide the changes to https://github.com/tdlib/td/blob/master/example/README.md via pull request, Github will automatically add you to https://github.com/tdlib/td/graphs/contributors.

**Comment by dieletro** [comment]
> @dieletro If you provide the changes to https://github.com/tdlib/td/blob/master/example/README.md via pull request, Github will automatically add you to https://github.com/tdlib/td/graphs/contributors.

ok, thanks, I'll do it!
