### ISSUE TITLE
Getting know new message was scheduled

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1196]
In official client notification for scheduled messages differs from ordinary messages, by adding 📅 prefix to the title.  Official client knows, that message was scheduled.

Is there some way in TDLib to know that new message actually was scheduled?

Thanks

**Comment by levlam** [comment]
This is possible if you use the TDLib Notification API. There was field `is_outgoing` added to the class `notificationTypeNewPushMessage` for this purpose. For `notificationTypeNewMessage`, you can use `message.is_outgoing`. Also all notifications in the Saved Messages chat are reminders.

**Comment by zevlg** [comment]
I emulate notification API using simple heuristics on `updateNewMessage` event, one of the heuristics was "do not notify if message is outgoing",  I think I could tweak it a bit to treat unread outgoing messages as scheduled

Thanks
