### ISSUE TITLE
Is there an update on new member joining the chat?

### ISSUE THREAD

**Issue by supolka** [tdlib/td#1198]
Bot API has [a way to receive an update about new chat member](https://core.telegram.org/bots/api#message). But it doesn't look such update exists for tdlib. I found [getChatEventLog](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_event_log.html) which does have the information about new and departed chat members, but that is not an update.

Is there such an update, or periodically calling `getChatEventLog` is a preferred way to react on new / banned members? If so - what are the rate limits for this method? (if this info could be shared)

Thank you

**Comment by levlam** [comment]
This is not an update, this is a message with the content `messageChatAddMembers`.

The rate limits are subject to change, especially if a method will be used in an unsupposed way.

**Comment by supolka** [comment]
Oh, so all of these are not updates, but messages with specific content type. It all makes sense now, thank you!
