### ISSUE TITLE
I need  determinate when user change avatar.

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#1199]
Currently  i getting updates of type "**UpdateUser**" and  checking my local database and checking new userProfilePhoto (from this update) and old userProfilePhoto (from my local database) and if they not equal i am updating picture in my app.

It is very long process, because "**updateUser**" my app getting every time (even when the users hasn't changed anything!)

May be has better way for detrminate - user changed avatar or no?

Thank you

**Comment by levlam** [comment]
No, there is no such way. The app isn't supposed to save anything between client restarts. The user's photo is saved by TDLib and can be received any time from TDLib.

**Comment by merlinkory** [comment]
-
