### ISSUE TITLE
I cannot build it on Ubuntu 16.04

### ISSUE THREAD

**Issue by Mygihub0** [tdlib/td#120]
[ 71%] Linking CXX executable example
/usr/bin/ld: cannot open output file example: Is a directory
collect2: error: ld returned 1 exit status
td/tdactor/CMakeFiles/example.dir/build.make:98: recipe for target 'td/tdactor/example' failed
make[2]: *** [td/tdactor/example] Error 1

**Comment by danog** [comment]
See #117

**Comment by Mygihub0** [comment]
Thanks!

**Comment by isopen** [comment]
https://github.com/isopen/docker/blob/master/tdlib/Dockerfile.ubuntu
