### ISSUE TITLE
Cannot install profile photo

### ISSUE THREAD

**Issue by churiy97** [tdlib/td#1200]
I tried to set profile photo for current user with this query:
td_send({'@type': 'setProfilePhoto', 'photo': {'@type': 'inputFile', 'path': 'test.png'}, '@extra': 'Set photo'})

But it wrote 'Failed to parse JSON object as TDLib request: Unknown class "inputFile"'

What type should be in the photo?

**Comment by levlam** [comment]
There is no such class as `inputFile`. The abstract class `InputFile` has 4 constructors, one of which must be used:
```
inputFileId id:int32 = InputFile;
inputFileRemote id:string = InputFile;
inputFileLocal path:string = InputFile;
inputFileGenerated original_path:string conversion:string expected_size:int32 = InputFile;
```

Also, the `setProfilePhoto` has changed type of the `photo` parameter in the latest TDLib version, so you may need to use another class.

**Comment by churiy97** [comment]
@levlam Thank you for reply
I tried all this constructors and have the same results (Failed to parse JSON object as TDLib request: Unknown class "inputFileLocal") 
Please, tell me where i can find information about new parameters?

**Comment by levlam** [comment]
In the scheme for the latest TDLib version: https://github.com/tdlib/td/blob/83c9f5180bf9738df2667841ed0c4df9ebeaec40/td/generate/scheme/td_api.tl#L4243.

**Comment by churiy97** [comment]
@levlam I also tried InputChatPhoto in my query before, maybe I have trouble with smth different?

**Comment by churiy97** [comment]
@levlam i realized my problem, thank you fro helping! I should to use one of this constructors:
inputChatPhotoPrevious, inputChatPhotoStatic etc
