### ISSUE TITLE
authorizationStateWaitTdlibParameters

### ISSUE THREAD

**Issue by raifpy** [tdlib/td#1202]
I try to fix this status on GoLang 

[ 3][t 4][1600551236.340809583][Td.cpp:4490][#1][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

So , i send "@type":"setTdlibParameters" (with my config (hash , id , db ... )) for fix ;

code = 400 message = "Parameters aren't specified"

 This state sometimes it comes .

So , what can i do :)

**Comment by levlam** [comment]
Your request doesn't have `parameters` field.

**Comment by raifpy** [comment]
> Your request doesn't have `parameters` field.

But i don't know what is this parameters ..

**Comment by levlam** [comment]
The `setTdlibParameters` request has only one parameter, called `parameters`.

**Comment by raifpy** [comment]
> The `setTdlibParameters` request has only one parameter, called `parameters`.
![image](https://user-images.githubusercontent.com/50047969/93690149-a8818b80-fadd-11ea-8910-030fee888530.png)
i found it , thanks bro ..
