### ISSUE TITLE
Empty "restriction_reason" for some restricted channels

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1203]
Older TDLib used to report "restricted_reason" in supergroup info with suffixes such as "-ios", "-all" etc.  However TDLib 1.6.8 reports empty "restricted_reason" for channels restricted on iOS (can't view them in official iOS client)

Is that because restriction now is client-type specific and reported differently for different clients?  Is it possible somehow to determine that channel is restricted on iOS using TDLib?

Thanks

**Comment by levlam** [comment]
No, this is not possible. TDLib will return restriction reason, only if the chat/message must be restricted by the current client.
