### ISSUE TITLE
Getting 400:API_ID_INVALID

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#1207]
Out of nowhere I'm getting a API_ID_INVALID error when I try to connect with tdlib. I've tried with different numbers and with one it was successful but with two others I got this error. I'm sure I used the right API_ID from my.telegram.com. Could there be other reasons?

**Comment by levlam** [comment]
Are you sure about "my.telegram.com"?

**Comment by levlam** [comment]
And no, the error can be produced only if the provided api_id is invalid.

**Comment by MalteToenjes** [comment]
Yeah sry I meant"my.telegram.de"...but not sure was the issue was, because it was no typo, but anyway next day it worked...
