### ISSUE TITLE
getContacts don't returns contact updates

### ISSUE THREAD

**Issue by sergeydi** [tdlib/td#1209]
Hi,

To receive user contacts I use "getContacts Class Reference". It works perfect, but if I change some contact info (first name or last name) from the native app, getContacts returns contact without changes. Why?

**Comment by levlam** [comment]
This depends on a lot of factors. Generally, you can't count upon immediate change of the user name on all other devices.

**Comment by sergeydi** [comment]
@levlam It must take some time?

**Comment by levlam** [comment]
It depends. But you definitely should receive actual names in 1-2 days.

**Comment by ichi0609** [comment]
- @sergeydi

**Comment by ichi0609** [comment]
iPhoneから送信

**Comment by sergeydi** [comment]
Also, I still don't received updates using getContacts. May be I need some additional command to update/import changes?

**Comment by levlam** [comment]
@sergeydi How do you update contacts list?

You can also manually update information about given user by calling `getUserFullInfo`.

**Comment by sergeydi** [comment]
@levlam I used **importContacts()** but _updateUser_ response returns the old one FirstName and LastName.

> You can also manually update information about a given user by calling getUserFullInfo.
Hot to update or receive all contacts in actual state?

**Comment by levlam** [comment]
You can manually update information about a given user by calling `getUserFullInfo`. There are no other ways.

**Comment by sergeydi** [comment]
How can I be notified that user info was changed or every time I need to receive a contact list I must execute `getUserFullInfo` for each contact?

I mean what is the correct way to receive a contact list with actual user information?

**Comment by levlam** [comment]
The correct way is to call `getContacts`. The rest is assured by TDLib and Telegram servers in the best possible way, but it is sometimes possible that the data will be outdated.

**Comment by sergeydi** [comment]
Thank you so much.

**Comment by sergeydi** [comment]
Just a few minutes ago I received over `getContacts` an actual FirstName and LastName.
