### ISSUE TITLE
LogStreamFile should not redirect stderr

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [tdlib/td#1211]
Apparently `LogStreamFile` works by replacing the stderr file descriptor, so that everything that writes to stderr ends up in tdlib's log file instead.

This isn't documented anywhere. It's also sloppy and breaks a bunch of stuff.

**Comment by levlam** [comment]
In our experience the stderr redirect was a very helpful feature in most cases, but you are right, that there are environments, where this behavior is undesirable. The underlying `FileLog` interface already allows to disable the redirect: https://github.com/tdlib/td/blob/83c9f5180bf9738df2667841ed0c4df9ebeaec40/tdutils/td/utils/FileLog.h#L25

So I will add the ability to disable the redirect to TDLib's interface using a new boolean field in the `logStreamFile` class in the next update.

**Comment by ColonelThirtyTwo** [comment]
Even if some people find it "convenient", in my opinion it's a massive violation of the library's boundaries to edit a process-global resource like that. I spent a few hours trying to find out where my log messages were going before I realized it was this "feature".

**Comment by levlam** [comment]
@ColonelThirtyTwo And this is why I agree that this feature should be optional.

**Comment by levlam** [comment]
This behavior has been made optional in the TDLib 1.6.9.
