### ISSUE TITLE
In h5 project，missing the chat datas when refresh the page

### ISSUE THREAD

**Issue by chinafelix** [tdlib/td#1213]
In the h5 project, the chat list and chat content are not on the same routing; when I refreshed in the chat content page , the previous chat data cannot be obtained

**Comment by levlam** [comment]
What do you mean?

**Comment by chinafelix** [comment]
missing the chat data when reload the chat page

**Comment by levlam** [comment]
To have chat data saved between TDLib restarts you must have at least chat_info_database enabled, or better message_database enabled.

**Comment by chinafelix** [comment]
thanks
