### ISSUE TITLE
How Can I Compile TdLib Independent of Processor Architecture?

### ISSUE THREAD

**Issue by bsglinux16** [tdlib/td#1214]
Hello

I am using Tdlib on Android on Xamarin.

But I Have a Problem That Each .so File Of Tdlib Represents A Separate Processor Architecture.
arm,arm64,x86, x86_64 vs vs

How Do We Make Them Independent?

It Is Really Difficult To Download .so File According To The Processor Architecture Of User's Device

In short, I need a Tdlib Library Independent of the Processor Architecture.

Urgent!

**Comment by levlam** [comment]
This is not possible. The correct library version should be chosen automatically when the app is installed on the device.

**Comment by bsglinux16** [comment]
> This is not possible. The correct library version should be chosen automatically when the app is installed on the device.

okay.
Well, can we reduce the size of the .so file to less than 20mb?

**Comment by levlam** [comment]
No, Unzipped size of arm64-v8a binary is near 20 megabytes. The armeabi-v7a version is 1.5-2 times smaller. Packed size should be a lot smaller.

**Comment by bsglinux16** [comment]
> No, Unzipped size of arm64-v8a binary is near 20 megabytes. The armeabi-v7a version is 1.5-2 times smaller. Packed size should be a lot smaller.

thanks 
i am zip the binaries
