### ISSUE TITLE
getting update from users.

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#1215]
1. When tdlib session start getting updates about some user, when i called "getUser" or getting first update "updateUser", right?

2. If tdlib session started getting update about some users, has any way to stop getting it (for specific user(s) ) ? 

3. May be tdlib session stop  getting update from some specific user after for a while?

**Comment by levlam** [comment]
TDLib never "start getting updates about some user". This is absolutely not how the update work.

**Comment by merlinkory** [comment]
_"start getting updates about some user"_ i meant when  my app discover new user and therefore start getting updates like "updateUser".

**Comment by levlam** [comment]
When a user is discovered for the first time, the app will get one `updateUser` update. After that it may or may not receive `updateUser` updates if some information about the user has changed.

**Comment by merlinkory** [comment]
> When a user is discovered for the first time, the app will get one `updateUser` update. After that it may or may not receive `updateUser` updates if some information about the user has changed.

I understanding it. But my question is:
can i stop getting "updateUser" about user (if user changing something) or not?

Or if app once discovered user, app will be receiving "updateUser" each time  when he change something?

**Comment by levlam** [comment]
No, app usually receives nothing if the user changes something. It will receive the changes, only if it needs them.

**Comment by lunam42** [comment]
hello, my question is partially similar to question above: in docs is written: "This update is guaranteed to come before the user identifier is returned to the Application. So, whenever an Application receives a user_id, it never needs to use the getUser request to receive the user object. Instead it should maintain a cache of users received through this update and take all the necessary data about users from this cache", but how i can take all necessary information from application's cache? what should i do to receive information from cache instead of making getUser request?

**Comment by levlam** [comment]
@lunam42 
Application's cache is a cache maintained by your application in the memory. Application itself should save the data in the memory and can get the data afterwards before instance is closed.

**Comment by merlinkory** [comment]
> No, app usually receives nothing if the user changes something. It will receive the changes, only if it needs them.

Could you clear following situation:
1. user "A" participant of some supergroup 
2. user "B"  join to this supergroup and user "A" receive update (about join some user into supergroup)
3.  user "B" change self data e.g.  first name or avatar, and user "A" not receive "updateUser" about "B".

But if someone in supergroup send any message then user "A" receive update about this message and also getting old "updateUser"  (about user "B"). Why?

And also if "B" send some message to "A"(directly) , then "A" will be receive "userUpdate" about  "B" everytime when "B" change something.  Why?

Please.

**Comment by levlam** [comment]
> But if someone in supergroup send any message then user "A" receive update about this message and also getting old "updateUser" (about user "B"). Why?

This should almost never happen.

> And also if "B" send some message to "A"(directly) , then "A" will be receive "userUpdate" about "B" everytime when "B" change something. Why?

This sometimes can happen, but generally this doesn't happen.

**Comment by merlinkory** [comment]
> > But if someone in supergroup send any message then user "A" receive update about this message and also getting old "updateUser" (about user "B"). Why?
> 
> This should almost never happen.
> 
> > And also if "B" send some message to "A"(directly) , then "A" will be receive "userUpdate" about "B" everytime when "B" change something. Why?
> 
> This sometimes can happen, but generally this doesn't happen.

Where i can find information about:
"Which in situations app receive "updateUser"" ?
I think should be clearly documentation out:about it.

**Comment by levlam** [comment]
It is received when it is needed by the app to **show** the correct data to the user. Nothing besides that.

**Comment by ElmiraNa** [comment]
hi @levlam 
i have a question a bout the way of synchronization between user phone book accounts, when I create an account in telegram, i can see which of my phone books have account too. in a big database with so many clients like telegram, how its server search my phone book and can know which one of them has telegram's account?
Is there any scenario in your mind to help me to know how this synchronization process happens very fast?
(excuse me for asking irrelevant question with this topic)

**Comment by levlam** [comment]
@levlam I can't help you with a server-side behavior.
