### ISSUE TITLE
@Channel_Bot as sender for channel posts

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1217]
I've noticed that messages to the channels are reported with non-0 `sender_user_id`, however docs states that "it is unknown for channel posts"

`sender_user_id` points to some strange https://t.me/Channel_Bot, which not marked as `is_verified` and responses with
```
Sorry, I'm not a real bot, they just made me for backward compatibility. I can't really answer any questions.
```
to `/start` command.

What all this means, is this something on TDLib-side or server side?  Should docs for the `sender_user_id` be changed in this case?

Thanks

**Comment by levlam** [comment]
It was a temporary server-side issue, affecting all clients and the Bot API. It is fixed now.
