### ISSUE TITLE
Channel replies are shown as #ID777000 Telegram

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1218]
Every channel reply is shown as the official telegram user, with id 777000. This can also create security problems because that user is an official telegram user.

**Comment by levlam** [comment]
Bots receive 777000 as a sender of messages with unknown sender. I don't see, how this can create a security problem.

**Comment by levlam** [comment]
This behavior was changed in TDLib and sender_user_id is kept 0 even for bots. The 777000 will be still returned in Bot API as a sender of the messages for the backward compatibility.
