### ISSUE TITLE
The sender of anonymous admin messages is Telegram instead of 0

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1221]
I am using the latest commit of tdlib

![屏幕截图 2020-10-02 004952](https://user-images.githubusercontent.com/56506714/94839153-3435d900-0449-11eb-913f-affe5751fc66.png)

**Comment by levlam** [comment]
This is true only for bots. You can check sender_chat_id first for them.

**Comment by nekohasekai** [comment]
This is indeed a bot account ....

**Comment by levlam** [comment]
This is a backward compatibility feature. Use
```
if (message.sender_chat_id != 0) {
  // use message.sender_chat_id
} else {
  // use message.sender_user_id
}
```
if your code is ready to process messages sent by anonymous administrators.

**Comment by nekohasekai** [comment]
thanks

**Comment by levlam** [comment]
This behavior was changed in TDLib and sender_user_id is now 0 even for bots. The 777000 will still be returned in Bot API as a sender of the messages for the backward compatibility.
