### ISSUE TITLE
Deleted private chat has type of SecretChat and CanBeDeletedForAllUsers is false

### ISSUE THREAD

**Issue by hihain** [tdlib/td#1224]
Problem: If a chat gets deleted only for me and I enter the chat again its type is not ChatTypePrivate, but SecretChat. Also, CanBeDeletedForAllUsers  is false instead of true.

Currently my workaround is to just sent anything in the chat, so the properties gets changed to Chat.Type == ChatTypePrivate and CanBeDeletedForAllUsers  == true.

Example for consequences: https://github.com/UnigramDev/Unigram/issues/2061

**Comment by levlam** [comment]
Chat type can't change. The assumption "its type is not ChatTypePrivate, but SecretChat" is definitely wrong.

But I seems to understand what you are complaining about. This will be fixed.

**Comment by levlam** [comment]
Fixed in master.
