### ISSUE TITLE
List of Objects that can be received?

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [tdlib/td#1226]
Is there a list of `Object`s that can be returned from the `td_json_client_receive` function?

Obviously, all of the objects that have a `Function` pointing to them as the response type can be received, but there are a few classes that are received without a corresponding request, like `Update`. Is there a comprehensive list of those?

**Comment by levlam** [comment]
Yes, there is a list and you have just written it almost correctly.
1. Any function can return the specified object or an `error` as result.
2. TDLib can send `Update` objects to the application.
