### ISSUE TITLE
How to retrieve messages after re-login

### ISSUE THREAD

**Issue by ashvydkyi** [tdlib/td#1230]
Hey guys, I hope it is a plain question.
After TDLib LogOut, some **messages** were posted to my account/chat, when I am LogIn/Authorize back with TDLib - none of these **messages** retrieved/handled. 
How to retrieve these **messages**? Thx.

**Comment by levlam** [comment]
You can't get these messages through updates. You can try to call `getChats` and `getChatHistory` to fetch the messages from the message history.

**Comment by ashvydkyi** [comment]
Understood, thx @levlam
