### ISSUE TITLE
createNewBasicGroupChat don't create new chat

### ISSUE THREAD

**Issue by sergeydi** [tdlib/td#1231]
Several times I used Command `createNewBasicGroupChat` to create new groups and everything works perfect. But then something happens and `createNewBasicGroupChat` don't create new chat but response **["@type"] = "updateNewChat"** returns the old one. Why?

**Comment by levlam** [comment]
`createNewBasicGroupChat` returns a `chat`, not `updateNewChat`. You seems to wrongly match requests and responses.

**Comment by sergeydi** [comment]
Hm, thank you. What is the correct way to create new group chat?

**Comment by levlam** [comment]
The correct way is to call `createNewBasicGroupChat`. But limits are very tight for the method, you will be able to create only a few chats daily anyway.

**Comment by sergeydi** [comment]
I found `["@type"] = "chat"` response, but it also returns the old one group chat, not the new. Why?

**Comment by levlam** [comment]
This is impossible. You are likely to still confuse responses. You must match requests and responses using "@extra" field.

**Comment by sergeydi** [comment]
> You must match requests and responses using "@extra" field.

Not understand. Now my request on Lua looks like:

```
tdClient:send(({["@type"] = "createNewBasicGroupChat",
            title = groupName,
            user_ids = groupContacts
        }))
```

What I need to add to `"@extra"` field?

**Comment by IRGC** [comment]
@sergeydi  may be this? 
```
tdClient:send(({["@type"] = "createNewBasicGroupChat",
            title = groupName,
            user_ids = groupContacts
        ,['@extra'] = 12345}))
```

**Comment by levlam** [comment]
@sergeydi See https://core.telegram.org/tdlib/getting-started#tdlib-interface.

**Comment by sergeydi** [comment]
It was a bug on my side. Issue may be closed.
