### ISSUE TITLE
Rate limits for tdlib?

### ISSUE THREAD

**Issue by jagzmz** [tdlib/td#1236]
What is the rate limits of the tdlib client for sending messages, the same chat, and different chats per second/minute?

Is there a list out there that gives an idea of all the rate limits that you can face?

**Comment by levlam** [comment]
TDLib has no limits. Server-side limits are subject to change based on a lot of unpredictable events. You don't need to know them in advance and you shouldn't assume any particular limits, you just need to properly handle 429th errors.

**Comment by jagzmz** [comment]
Ok thanks.

**Comment by sesu07** [comment]
rete limit for tdlib to send bulk messages?

**Comment by dejesusmartinezwilsonjavier-cloud** [comment]
Toda vía sigue bloqueado mi número en telegram

Wilson
