### ISSUE TITLE
replyToMessageId is 0 in some cases?

### ISSUE THREAD

**Issue by jagzmz** [tdlib/td#1237]
when trying to send a message with replyToMessageId, the response which comes in a sendMessage API has `replyToMessageId:0`.

This happens in the case if the message does not exist in the chat with the given id. but in some cases, it returns as 0, even tho message exists in that chat. This happened to a day old message. and the TDLib instance was restarted within that period. does it have to do with the caching of messages in some sort? do I have to use the `useMessageDatabase` flag?

What are the case's in which response comes as `replyToMessageId:0` after sending a message with a `replyToMessageId`?

**Comment by levlam** [comment]
The message must be known to TDLib. If you don't use message database, you need to preload it using the method `getMessage`.

**Comment by jagzmz** [comment]
@levlam Knew it! I had a doubt this would be the fix, anyways what is the timing that TDLib makes a cache of a message? 
Because even without using the `useMessageDatabase` flag, TDLib is able to preload a message and work with `replyToMessageId` as expected.

**Comment by levlam** [comment]
If a message became known to TDLib after instance launch, it can be forgotten by TDLib only if the logged in user is a bot.

For ordinary users if message database is used, the message will be unloaded from memory, but it will be automatically loaded from the database when needed. If message database isn't used, then messages are never unloaded from the memory.

**Comment by jagzmz** [comment]
> For ordinary users if message database is used, the message will be unloaded from memory, but it will be automatically loaded from the database when needed. If message database isn't used, then messages are never unloaded from the memory.

I don't think that I get understood you. 
I am was not using the message database till now, but still, the TDLib was able to use old message id's as replyToMessageId without any issue even upon re-starting / resetting the application memory. According to your saying, my setup should never unload the message from the memory, right? So how come it was able to use replyToMessageId even after application restart without using message database.

**Comment by levlam** [comment]
If message database is not used, then this shouldn't work after client restart without the replied message received again from the server. The message can be automatically received from the server if it is the last chat message or a pinned message. Otherwise, if the client didn't load the message explicitly, it should be impossible to reply to it. If you want to know, what exactly happens, you can send TDLib's log with verbosity level 4 to @tdlib_bot in Telegram.

**Comment by jagzmz** [comment]
This was figured out, using the messageDatabse flag.
also,
 @tdlib_bot doesn't reply with any message

**Comment by levlam** [comment]
The @tdlib_bot works as expected. It is not supposed to answer to commands.

**Comment by Fxlr8** [comment]
@levlam `getMessage` didn't work for me, it returned `undefined`. But `getMessages` worked and found the message in the exact same conditions. How and why?

**Comment by levlam** [comment]
@Fxlr8 I don't think this is possible. Could you send TDLib's log with verbosity level 4 to @tdlib_bot?
