### ISSUE TITLE
Missing library needed to build tdlib with windows

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1238]
When compiling tdlib for windows, tdutils CMakeLists.txt don't link a library needed by openssl: crypt32.
This problem emerges by using static openssl.

Here's an example of this fix:
https://github.com/tdlight-team/tdlight/commit/be83b71452454bbdf1e73db58025256a93a6b320

**Comment by levlam** [comment]
Have you tested this in the latest TDLib version after the commit https://github.com/tdlib/td/commit/ab5d35371b1fdcfb30dfa981ede54ec83db214a9?

**Comment by Cavallium** [comment]
I tested with the latest commit, but it fails in tdutils

**Comment by Cavallium** [comment]
The problem does occur only when openssl is linked statically

**Comment by levlam** [comment]
Ok, thanks. It seems that the static linker needs crypt32 for some OpenSSL versions, despite it isn't actually used. I will fix this.

**Comment by levlam** [comment]
Fixed in master.
