### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by hassandg** [tdlib/td#124]
Hi
When the next version will be released?

**Comment by isopen** [comment]
The question is interesting. I am waiting too.

**Comment by levlam** [comment]
It will be released when other clients will be updated.

**Comment by isopen** [comment]
Leo, what new in new release?

**Comment by isopen** [comment]
You need to introduce something cool. For example, intellectual prompts during construction on a library. Recently I talked a little about AI.

**Comment by PeyTy** [comment]
@levlam 
> It will be released when other clients will be updated.

When.. approximately? March? We experience tdlib bugs :(

**Comment by levlam** [comment]
@PeyTy What bugs?

**Comment by isopen** [comment]
On the opensource, it's better to update in real-time.

**Comment by levlam** [comment]
TDLib 1.2.0 is released.
