### ISSUE TITLE
error make install 

### ISSUE THREAD

**Issue by dAvagimyan** [tdlib/td#1241]
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libtdjson.so.1.6.9
-- Up-to-date: /usr/local/lib/libtdjson.so
-- Installing: /usr/local/lib/libtdjson_static.a
-- Installing: /usr/local/lib/libtdjson_private.a
-- Installing: /usr/local/lib/libtdclient.a
-- Installing: /usr/local/lib/libtdcore.a
-- Installing: /usr/local/lib/libtdapi.a
CMake Error at cmake_install.cmake:93 (file):
  file INSTALL cannot find "/home/developerd/td/pkgconfig/tdutils.pc".

I don't have a "pkconfig" directory in my td. I've tried installing on ubuntu 16, 18. I see this directory at / home / developerd / td / build / pkgconfig / tdutils. But I still get the error.

**Comment by Mazuh** [comment]
I'm having the same issues. I came to this by following the https://tdlib.github.io/td/build.html?language=C%2B%2B tutorial.

**Comment by Mazuh** [comment]
fyi, this happens at:

```
CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DTD_ENABLE_LTO=ON -DCMAKE_AR=/usr/bin/llvm-ar-10 -DCMAKE_NM=/usr/bin/llvm-nm-10 -DCMAKE_OBJDUMP=/usr/bin/llvm-objdump-10 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-10 ..

cmake --build . --target install
```

--------------------------------------------------------------

I saw a few @levlam recent changes on building steps, so now I'll clean all my outputs and try to run the steps again in the latest tagged release `v1.6.0` of this repo.

**Comment by dAvagimyan** [comment]
Ok! thank you. I will wait

**Comment by Mazuh** [comment]
@dAvagimyan, it worked on the latest tagged release instead of master head. I completed the steps with no errros so far.

That said, this is officially a **bug introduced recently**. And I'm available to the maintainers in any way I can.

**Comment by levlam** [comment]
The fix will be pushed soon.

**Comment by dAvagimyan** [comment]
I was able to install successfully under tag 1.6.0. Thank you Mazuh

**Comment by Mazuh** [comment]
you're welcome!

(I'd say to keep this opened until the fix is pushed, tho)

**Comment by levlam** [comment]
The fix has been pushed.
