### ISSUE TITLE
Race condition in the new multi client design

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1242]
When creating a new client, you can receive updates for that client before the function returns the new client id, making impossible to send them to the correct handler.

**Comment by levlam** [comment]
Thanks!

If receive and create_client are run in parallel in different threads, it is impossible for TDLib to guarantee that receiver thread knows about the newly created client ID.

One of the ways to remove the race is to create clients only on the thread, which calls receive. This will need some support from the app or the wrappers.
 
Another way is to return void from create_client and make client creation always asynchronous. The client will be created after receiving a first update for it.

Another way is to allow the app to specify client_id in create_client.

Another way is to implicitly create the client on the first send call.

**Comment by Cavallium** [comment]
The first approach is the one that I'm using on my wrapper but obviously it's quite inefficient.

Since the wrappers must already specify the sequential id of every request, I think that the simplest and most familiar approach is the specification of the client id by the app/wrapper.

The asynchronous solution can be nice but it can be difficult to handle if the clients are managed synchronously.

Implicitly creating clients on the first send call can be also viable and it's very similar to the approach of the user-defined ids.

**Comment by levlam** [comment]
We found one more way to fix the race: the client will send updates only after first `td_send` call. The downside of this solution is that a dummy request needs to be sent after the client is created.

**Comment by levlam** [comment]
The method `create_client` was renamed to `create_client_id`, which only assigns and returns a new opaque client ID. The client is launched and begins to send updates after a first request is sent to it. Thanks, @Cavallium!

**Comment by Cavallium** [comment]
I still find this issue also with newer versions of tdlib, is this fix working properly when multiple instances are created?

**Comment by levlam** [comment]
Yes. Are you sure that receiver thread knows about the client_id? You need to use some synchronization primitive with acquire/release semantics like mutex to guarantee this.
