### ISSUE TITLE
Use tags on version bumps

### ISSUE THREAD

**Issue by oz** [tdlib/td#1243]
Could you tag the releases when they happen to make packaging a little cleaner than checking git daily?

The last release is apparently 1.6.0 but it's been replaced a while ago.

**Comment by levlam** [comment]
The last release is still 1.6.0. All later version are development versions with continuously changing API. They all can be called 1.7.0-beta-X instead. Before TDLib 1.5.0 they wasn't even published on Github until next minor release. The 1.7.0 version will have a tag as soon it is ready.

**Comment by oz** [comment]
Thanks for the clarification. 👍🏻
