### ISSUE TITLE
Build Warning when compiling TDLib master for X86 (32-bit)

### ISSUE THREAD

**Issue by mrkiko** [tdlib/td#1246]
When compiling, I get something like this (sorry for the ANSI color codes all around):

[ 80%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/SendCodeHelper.cpp.o[0m
[ 81%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/SequenceDispatcher.cpp.o[0m
[ 81%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/SpecialStickerSetType.cpp.o[0m
[ 81%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/StateManager.cpp.o[0m
[ 81%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/StickersManager.cpp.o[0m
[ 82%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/StorageManager.cpp.o[0m
[ 82%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/SuggestedAction.cpp.o[0m
[ 82%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/Td.cpp.o[0m
In file included from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdutils/td/utils/logging.h:28[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdutils/td/utils/ObjectPool.h:10[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/impl/ActorId-decl.h:9[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/impl/Actor-decl.h:9[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/impl/Actor.h:9[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/actor.h:9[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/td/telegram/StickersManager.h:9[m[K,
                 from [01m[K/home/mrkiko/telegram-tdlib/src/td-master/td/telegram/StickersManager.cpp:7[m[K:
In lambda function,
    inlined from ‘[01m[Kvoid td::detail::LambdaPromise<ValueT, FunctionOkT, FunctionFailT>::do_error(td::Status&&) [with ValueT = td::Unit; FunctionOkT = td::StickersManager::get_stickers(td::string, td::int32, bool, td::Promise<>&&)::<lambda(td::Result<td::Unit>)>; FunctionFailT = td::PromiseCreator::Ignore][m[K’ at [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/PromiseFuture.h:294:9[m[K,
    inlined from ‘[01m[Ktd::detail::LambdaPromise<ValueT, FunctionOkT, FunctionFailT>::~LambdaPromise() [with ValueT = td::Unit; FunctionOkT = td::StickersManager::get_stickers(td::string, td::int32, bool, td::Promise<>&&)::<lambda(td::Result<td::Unit>)>; FunctionFailT = td::PromiseCreator::Ignore][m[K’ at [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/PromiseFuture.h:277:13[m[K,
    inlined from ‘[01m[Ktd::detail::LambdaPromise<ValueT, FunctionOkT, FunctionFailT>::~LambdaPromise() [with ValueT = td::Unit; FunctionOkT = td::StickersManager::get_stickers(td::string, td::int32, bool, td::Promise<>&&)::<lambda(td::Result<td::Unit>)>; FunctionFailT = td::PromiseCreator::Ignore][m[K’ at [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/PromiseFuture.h:278:3[m[K:
[01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdutils/td/utils/Slice.h:270:45:[m[K [01;35m[Kwarning: [m[K‘[01m[Kint __builtin_memcmp_eq(const void*, const void*, unsigned int)[m[K’ reading 18 bytes from a region of size 13 [[01;35m[K-Wstringop-overflow=[m[K]
  270 |   return a.size() == b.size() && [01;35m[Kstd::memcmp(a.data(), b.data(), a.size())[m[K == 0;
      |                                  [01;35m[K~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[K
In lambda function,
    inlined from ‘[01m[Kvoid td::detail::LambdaPromise<ValueT, FunctionOkT, FunctionFailT>::do_error(td::Status&&) [with ValueT = td::Unit; FunctionOkT = td::StickersManager::get_stickers(td::string, td::int32, bool, td::Promise<>&&)::<lambda(td::Result<td::Unit>)>; FunctionFailT = td::PromiseCreator::Ignore][m[K’ at [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/PromiseFuture.h:294:9[m[K,
    inlined from ‘[01m[Ktd::detail::LambdaPromise<ValueT, FunctionOkT, FunctionFailT>::~LambdaPromise() [with ValueT = td::Unit; FunctionOkT = td::StickersManager::get_stickers(td::string, td::int32, bool, td::Promise<>&&)::<lambda(td::Result<td::Unit>)>; FunctionFailT = td::PromiseCreator::Ignore][m[K’ at [01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdactor/td/actor/PromiseFuture.h:277:13[m[K:
[01m[K/home/mrkiko/telegram-tdlib/src/td-master/tdutils/td/utils/Slice.h:270:45:[m[K [01;35m[Kwarning: [m[K‘[01m[Kint __builtin_memcmp_eq(const void*, const void*, unsigned int)[m[K’ reading 18 bytes from a region of size 13 [[01;35m[K-Wstringop-overflow=[m[K]
  270 |   return a.size() == b.size() && [01;35m[Kstd::memcmp(a.data(), b.data(), a.size())[m[K == 0;
      |                                  [01;35m[K~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[K
[ 82%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/TdDb.cpp.o[0m
[ 83%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/TermsOfService.cpp.o[0m
[ 83%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/TopDialogManager.cpp.o[0m
[ 83%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/UpdatesManager.cpp.o[0m
[ 83%] [32mBuilding CXX object CMakeFiles/tdcore.dir/td/telegram/Venue.cpp.o[0m
...

G++ 10.2.0; thank you guys!

**Comment by levlam** [comment]
The compiler doesn't like string comparison in
```
if (result.is_error() && result.error().message() != "STICKERSET_INVALID") {
```
but this is definitely a false positive, which was added in GCC 10 due to "Enhancements to existing warnings": https://gcc.gnu.org/gcc-10/changes.html.

You can safely ignore the warning.

**Comment by mrkiko** [comment]
thank you very much. Closing this issue right now.

**Comment by levlam** [comment]
Between, I can't reproduce the warning in g++ 10.2.1 or in g++ 10.0.1.
