### ISSUE TITLE
Inclusion of automatic translator in the telegram

### ISSUE THREAD

**Issue by dieletro** [tdlib/td#1247]
I recently had this idea of ​​having a form of automatic translation of messages received, since since we have the user's language code, it would be nice that if he enabled this option, the telegram could already show the messages already translated to the user and that would be something very interesting and almost unique in the message market, do you think it would be possible?

**Comment by levlam** [comment]
This needs to be supported server-side first. You can send general suggestions through in-app support or by menthioning @telegram on Twitter.
