### ISSUE TITLE
LocalFile filename

### ISSUE THREAD

**Issue by MarioSaldanhaLobo** [tdlib/td#1248]
Hello,
I need to save some of the received files elsewhere, for re-usage.
How can I know the filename of a downloaded file?

Thanks.

**Comment by levlam** [comment]
The app is notified about download progress via `updateFile` updates. Whenever a file is downloaded, you will receive an `updateFile` with `file.local.is_downloading_completed == true` and non-empty `file.local.path`. Then you can copy the file.
