### ISSUE TITLE
Add equals(x) and hashCode() functions for java classes in TdApi.java

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1249]
Equality checks on TdApi classes is broken because they don't implement an appropriate equals/hashcode function.
Every instance compared with another one always returns false because they inherit the default equality check from java.lang.Object.
Since that classes can be used in collections like Set or HashMap by the end user, they need that methods.

**Comment by levlam** [comment]
This is intended for now, because we don't want to generate thousands of methods, from which only a few will be used. The generated methods will significantly increase binary size and, more importantly, will be counted towards 65536 methods limit for dex format on Android.

**Comment by Cavallium** [comment]
There are two possible solutions that don't involve creating too many methods.
1. Implementing equals and hashcode in Object and Function by comparing the string representation created by tdlib:
public int hashCode() {
   return this.toString();
}

2. Implementing a native solution from td_jni.cpp or from tdlib itself.

**Comment by levlam** [comment]
The first way can ignore difference in the fields of the type `bytes`. This is acceptable for hashCode() but not for equals.

The second way will significantly increase binary size.

We thought about manually specifying the list of classes, for which the method `equals` is generated, but this can help only if TDLib is build for a specific app.

**Comment by andrew-ld** [comment]
if you still want these functions inside tdapi you can use tdlight-java which automatically integrated, or you can use our generator (https://git.ignuranza.net/windoz/tdlib-serializer), plus we also have a method to serialize and deserialize in binary format the various TdApi objects, this is useful if you want to use an IPC

I leave you in attachment tdapi generated by our software
[tdapi.zip](https://github.com/tdlib/td/files/5394212/tdapi.zip)
