### ISSUE TITLE
[DATA LOSS] tdlib removes files

### ISSUE THREAD

**Issue by ildar** [tdlib/td#1250]
Using https://github.com/ars3niy/tdlib-purple/ client, related issue: https://github.com/ars3niy/tdlib-purple/issues/85

In ~/.config/purple/tdlib/\<myphoneno\>/ I have some folders replaced by symlinks:
> documents → /some/storage/folder
> thumbnails → /tmp/cache/
> music → /some/storage/folder
> photos → /some/storage/folder
> stickers → /some/storage/folder/stickers

Suddenly I got /some/storage/folder emptied (DATA LOSS!)
And `documents` recreated (as folder).

Please don't do that. Please fix ASAP.

**Comment by levlam** [comment]
Don't replace folders by simlinks.

The subfolders of `files_directory` are controlled by TDLib and are used to cache downloaded files. The cached files can be deleted by expicit calls to `optimizeStorage` or automatically if storage optimizer is enabled in TDLib parameters. Replacing the folders with symlinks to the same folder will cause wrong `storageStatistics` result and may lead to a lot of other problems.

**Comment by ildar** [comment]
Thanks for clarification.
Am I getting it right that `../tdlib/documents` and such are actually
*cache* folders? Fairly speaking, the name is misguiding then.
> Don't replace folders by simlinks.

This is hard to tolerate! `tdlib` folder has settings and cache data
intermixed which is a bad idea to start with. And having prohibited to
separate it manually makes the situation even worse.
Would you please elaborate the whole approach?

**Comment by levlam** [comment]
Yes, in Telegram every data available locally is *cache*.

The file cache directory is supposed to be managed solely by TDLib. The content of the `files_directory` and, in particular, subfolder names are internal implementation details and are subject to change any time. The app must not suppose any internal layout of files in the `files_directory` or interfere with it.

**Comment by ildar** [comment]
I see. Yet `db.sqlite` and some others are NOT cache files, right?
Would you please comment on the "intermixing" part?

**Comment by levlam** [comment]
They are "cache files". Some data from the database or the whole "db.sqlite" file can be deleted any time.

**Comment by levlam** [comment]
Even existence "db.sqlite" file is an internal implementation detail, which can be changed any time without notice.

**Comment by ildar** [comment]
I see. Thanks a lot.
