### ISSUE TITLE
Is getChats(nullptr, ...) behaves just like getChats(chatListMain, ...)?

### ISSUE THREAD

**Issue by leiless** [tdlib/td#1253]
Hi, @levlam, is [`getChats(nullptr, ...)`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html) behaves just like as if we called `getChats(std::move(td_api::make_object<td_api::chatListMain>()), ...)`?

Or `nullptr` meaning to search in all chats regardless of their chat list?

But as I tested out, passing `nullptr` seems have the same effect as to passing `chatListMain`.

**Comment by levlam** [comment]
`getChats` returns chats in the main chat list by default. TDLib has no way to return all chats regardless of their chat list, because there is no single order on all chats. For example, different chats can be pinned in different chat lists.

**Comment by leiless** [comment]
bq. `getChats` returns chats in the main chat list by default.
So it means `nullptr` have the same effect as `chatListMain`?

BTW, how can I get the chat list from a folder by TDLib?

**Comment by levlam** [comment]
You can use `chatListFilter chat_filter_id:int32 = ChatList;` for that.

**Comment by leiless** [comment]
> You can use `chatListFilter chat_filter_id:int32 = ChatList;` for that.

Gotcha!

It seems that docs about `chatListFilter` not yet listed in https://core.telegram.org/tdlib/docs/classes.html by now, please update it accordingly :-P

**Comment by levlam** [comment]
The on-site docuemntation is for the latest minor version TDLib 1.6.0. It will be updated after the next release.
