### ISSUE TITLE
TdLib Can`t upload file.

### ISSUE THREAD

**Issue by EgartSites** [tdlib/td#1257]
var file = await _client.UploadFileAsync(new TdApi.InputFile.InputFileLocal
                                {
                                    Path = "SpokenText.ogg"
                                }, new TdApi.FileType.FileTypeVoiceNote { }, 1);

Returning: TdLib.TdException: 'File must be non-empty'

**Comment by levlam** [comment]
Thre file "SpokenText.ogg" is empty.

**Comment by levlam** [comment]
Between, you don't need to call `UploadFile` in almost all cases, You should call `SendMessage` directly instead.

**Comment by EgartSites** [comment]
I had tried to directly send voice message and error the same 

> Between, you don't need to call `UploadFile` in almost all cases, You should call `SendMessage` directly instead.

**Comment by levlam** [comment]
Yes, because the file "SpokenText.ogg" is empty. But you still don't need to use `UploadFile`.
