### ISSUE TITLE
Error compiling golang application. Operating system linux ubuntu 20

### ISSUE THREAD

**Issue by dAvagimyan** [tdlib/td#1258]
I am getting an error while trying to compile my application.

/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x51): неопределённая ссылка на «std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)»
/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x65): неопределённая ссылка на «std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)»
/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x7a): неопределённая ссылка на «std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)»
s

**Comment by dAvagimyan** [comment]
Install files from 1.6.0 branch

**Comment by levlam** [comment]
There was no errors in TDLib build. You are linking golang binary with the wrong standard C++ library, using one of "-lstdc++" or "-lc++" instead of another.

**Comment by dAvagimyan** [comment]
Sorry, but could you tell me what to do? I am not good at C ++.

**Comment by dAvagimyan** [comment]
Do I need to rebuild a library under a different assembly?

**Comment by levlam** [comment]
No, the library is build correctly. You need to change the source of your Go wrapper, particularly, the line similar to
https://github.com/zelenin/go-tdlib/blob/a5d1c7ffe705c2d89e1b9ec21c4d59e805540a64/client/tdjson_static.go#L8

**Comment by dAvagimyan** [comment]
Ty, working.
