### ISSUE TITLE
what is inputFileGenerated?

### ISSUE THREAD

**Issue by sajjad-ser** [tdlib/td#126]
hi every one what is what is inputFileGenerated and what's it usage?

**Comment by levlam** [comment]
It should be used whenever not yet existed file needs to be sent. For example,
1. A compressed photo, generated from an existing one.
2. A compressed video, generated from an existing one.
3. A file, which first needs to be downloaded from an HTTP URL.
4. A currently recording voice/video note.
5. A file outside library cache that needs to be copied and stored in the cache.
To achieve that the client specifies two pretty arbitrary strings `original_path` and `conversion` and should be able to generate the file based on value of these parameters whenever it receives `updateFileGenerationStart`.
For example, a client can use for the mentioned cases:
1. Path to the original photo as `original_path` and "compress_photo" as conversion.
2. Path to the original video as `original_path` and "compress_video" as conversion.
3. URL of the file as `original_path` and "download" as conversion.
4. "<current unix time>.ogg" as `original_path` and "record_voice" as conversion.
5. Path to the original file as `original_path` and "copy" as conversion.

There are a lot of more complex cases when inputFileGenerated can be used. Basically all cases except sending a local/already sent file should be covered by inputFileGenerated.

**Comment by sajjad-ser** [comment]
tanks

**Comment by blacksailer** [comment]
is there any list of conversions? Or should dev implement each?

**Comment by levlam** [comment]
There is no built-in conversions except "#url#" used for files, which need to de downloaded from an HTTP/HTTPS URL. But even that conversion needs to be handled and implemented by the client.

Also, all conversions beginning with '#' are reserved for internal TDLib usage.

**Comment by blacksailer** [comment]
How to register conversion so tdlib can know which method to call?

**Comment by blacksailer** [comment]
Should I use  updateFileGenerationStart and updateFileGenerationStop as wrapper?

**Comment by FrayxRulez** [comment]
You must handle `updateFileGenerationStart` and `updateFileGenerationStop` updates from TDLib, and then provide progress about the generation using `setFileGenerationProgress` and `finishFileGeneration`.

**Comment by levlam** [comment]
Since TDLib 1.4.0 you can also use the method `writeGeneratedFilePart` if you have no direct access to TDLib's file system.
