### ISSUE TITLE
Error compiling tdlib v1.6.9 for other languages following the build guide available

### ISSUE THREAD

**Issue by dieletro** [tdlib/td#1262]
Hello, I'm trying to compile tdlib in version 1.6.9 but I'm only managing to compile version 1.6.0 that is already in Release with the tag v1.6.0, it would be possible to create a new tag for this new version or there is something in the step guide step I must change to get version 1.6.9 to use tdjson.dll

1. This is the first error:

Error: Building package zlib: x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `. \ Vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
   Package: zlib: x86-windows
   Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

2. This is the second error:

   Generating Code ...
LINK: fatal error LNK1181: e file could not be opened
'ZLIB_LIBRARY-NOTFOUND.lib' entry [E: \ 00 - ComponentsDelphi \ TIn
ject \ API_Telegran \ Dev \ TL \ TDLib \ Generating DLL \ td \ build \ td \ generate \ g
enerate_json.vcxproj]

3. These are the steps I followed:

Choose a programming language, from which you want to use TDLib:
Other

Choose an operating system, on which you want to use TDLib:
Windows

Build binary debug. Debug binaries are much larger and slower than release one.

Choose which shell application you want to use for building:
(X) PowerShell () mintty / Bash

Choose for which bitness you want to build TDLib:
(X) 32 () 64

TDLib can be used from any other programming language on Windows through the JSON interface.
See examples of such usage and already available third-party frameworks.

Here is complete instruction for TDLib binaries building:

Note that Windows Subsystem for Linux (WSL) and Cygwin are not Windows environments, so you need to use instructions for Linux instead for them.
Download and install Microsoft Visual Studio. Enable C ++ support while installing.
Download and install CMake; choose "Add CMake to the system PATH" option while installing.
Download and install Git.
Download and install gperf. Add the path to gperf.exe to the PATH environment variable.
Download and unpack PHP. Add the path to php.exe to the PATH environment variable.
Close and re-open PowerShell if PATH environment variable was changed.
Run these commands in PowerShell to build TDLib and to install it to td / tdlib:

git clone https://github.com/tdlib/td.git
cd td
git checkout v1.6.0
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg.exe install openssl: x86-windows zlib: x86-windows
CD ..
Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
mkdir build
cd build
cmake -A Win32 -DCMAKE_INSTALL_PREFIX: PATH = .. / tdlib -DCMAKE_TOOLCHAIN_FILE: FILEPATH = .. / vcpkg / scripts / buildsystems / vcpkg.cmake ..
cmake --build. --target install --config Release
CD ..
CD ..
dir td / tdlib

**Comment by levlam** [comment]
2020.06.15 looks like a pretty old vcpkg version. Did you do `git clone https://github.com/Microsoft/vcpkg.git`?

**Comment by dieletro** [comment]
> 2020.06.15 looks like a pretty old vcpkg version. Did you do `git clone https://github.com/Microsoft/vcpkg.git`?

yes, i followed exactly the steps of the guide, i created a new empty folder and inside it i started the whole process

**Comment by levlam** [comment]
`vcpkg` needs English language pack for MSVC to build some libraries. Have you installed it? You can also look vcpkg logs for the exact error details.

**Comment by levlam** [comment]
I have just successfully built zlib using the latest vcpkg.
Try again from the command
```
./vcpkg.exe install openssl: x86-windows zlib: x86-windows
```
