### ISSUE TITLE
Why are files still accessible even after they have been deleted by user?

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1264]
When have received the image,my bot saves its id, then I delete the message, but the image is still accessible or can be the paramter to InputFileRemote, which is different from the document description.

`For example, if the file is from a message, then the message must be not deleted and accessible to the user`

But this does not work in http api, the file is deleted and immediately inaccessible, is it attached, or is this restriction strictly enforced?

Is it temporary? Or is there a time limit for this? Or is it not available in the future?

**Comment by levlam** [comment]
Currently, bots are allowed to reuse files: https://core.telegram.org/bots/faq#can-i-count-on-file-ids-to-be-persistent.

**Comment by nekohasekai** [comment]
> Currently, bots are allowed to reuse files: https://core.telegram.org/bots/faq#can-i-count-on-file-ids-to-be-persistent.

Can you confirm or explain whether it is not available in http api?
