### ISSUE TITLE
getSuitableDiscussionChats returns chat that can't be used as discussion group for a channel

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1267]
With TDLib 1.6.9 I'm trying to set channel's discussion group to existing chat.  I've selected chat from return value of `getSuitableDiscussionChats` method and executed `setChatDiscussionGroup` method with corresponding "discussion_chat_id" argument.

In return I've got error 400 (MEGAGROUP_PREHISTORY_HIDDEN).

I this expected?  Why `getSuitableDiscussionChats` returns a chat that is not suitable to be used as discussion group.

Thanks

**Comment by levlam** [comment]
This is intended and documented in the description of the parameter `setChatDiscussionGroup.discussion_chat_id`:
> Identifier of a new channel's discussion group. Use 0 to remove the discussion group. Use the method getSuitableDiscussionChats to find all suitable groups. Basic group chats need to be first upgraded to supergroup chats. If new chat members don't have access to old messages in the supergroup, then toggleSupergroupIsAllHistoryAvailable needs to be used first to change that

**Comment by levlam** [comment]
I added the same note to the `getSuitableDiscussionChats` documentation.
