### ISSUE TITLE
[Question] Using some tdlib methods without user authentication 

### ISSUE THREAD

**Issue by tharindusathis** [tdlib/td#1269]
I needed to get an Instant View for a web page, but without authenticating as a user or bot. Is it allowed to call methods like [getWebPageInstantView](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_web_page_instant_view.html), [getWebPagePreview](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_web_page_preview.html), etc. without auth ?

Do we need to authenticate the user before utilizing all the methods in `TDlid`?

**Comment by levlam** [comment]
The methods which can be before authentication are documented as "Can be called before authorization". getWebPageInstantView and getWebPagePreview aren't among of them.
