### ISSUE TITLE
Mistake/ambiguity in documentation

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1271]
https://core.telegram.org/mtproto/auth_key#presenting-proof-of-work-server-authentication
In the section beginning 'Thereafter, auth_key equals' it incorrectly states that the client calculates the auth_key using `(g_a)^b mod dh_prime`, because previous code uses `pow()` a reader might take `^` to mean 'xor' as I did, but upon comparing results with the sample auth key documentation `pow(g_a, b) mod dh_prime` is the calculation that gives the correct result.

As an aside it'd be good if there was a git repository for the documentation so I could just put in a pull request instead of having you do the work, but that's up to you guys of course.

**Comment by levlam** [comment]
pow and ^ are used interchangeably on the page. Xor is meaningless in the mentioned context, but you are right that for consistency in that place pow needs to be used instead of ^. The documentation was changed. Thanks.
