### ISSUE TITLE
Could not find module 'tdjson.dll'

### ISSUE THREAD

**Issue by dm-sizov** [tdlib/td#1272]
`FileNotFoundError: Could not find module 'tdjson.dll' (or one of its dependencies). Try using the full path with constructor syntax.`
I've already built TDlib. How can I solve this problem?

**Comment by levlam** [comment]
You didn't placed built library in the folder where your program can find it. Try to place it in the folder, from which the script is run. Also don't forget to copy all other dependent DLLs to the same folder.

**Comment by dm-sizov** [comment]
> You didn't placed built library in the folder where your program can find it. Try to place it in the folder, from which the script is run. Also don't forget to copy all other dependent DLLs to the same folder.

I also can't find any .dll files in the library.

**Comment by levlam** [comment]
Are you sure that you built TDLib? Have you used the build instruction from https://tdlib.github.io/td/build.html?

**Comment by dm-sizov** [comment]
> Are you sure that you built TDLib? Have you used the build instruction from https://tdlib.github.io/td/build.html?

Yes, but I had some messages about missing English in VS while building. Is it possible that I installed the library incompletely?

**Comment by levlam** [comment]
The last command in the build instructions shows you the built library. If you see nothing, then you didn't build it. Show all console output of build commands, so I can tell you, what went wrong.

**Comment by dm-sizov** [comment]
> The last command in the build instructions shows you the built library. If you see nothing, then you didn't build it. Show all console output of build commands, so I can tell you, what went wrong.

TDLib was not fully installed due to errors during the installation of openssl and zlib. This was caused by the lack of English in Visual Studio. Now I have tdjson.dll file, but my Python program can't find this file even if I place it in the program's folder.

**Comment by levlam** [comment]
You need to also copy all dependent DLLs from td/tdlib directory, i.e. OpenSSL and zlib DLLs.

**Comment by dm-sizov** [comment]
> You need to also copy all dependent DLLs from td/tdlib directory, i.e. OpenSSL and zlib DLLs.

So I have only tdjson.dll in td/tdlib.

**Comment by levlam** [comment]
Нщг can find OpenSSL and zlib DLLs are in vcpkg folder. They should be named like
```
zlib1.dll
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
```

You need to choose the correct one based on the target architecture and Debug/Release build.

**Comment by dm-sizov** [comment]
> 
> 
> Нщг can find OpenSSL and zlib DLLs are in vcpkg folder. They should be named like
> 
> ```
> zlib1.dll
> libcrypto-1_1-x64.dll
> libssl-1_1-x64.dll
> ```
> 
> You need to choose the correct one based on the target architecture and Debug/Release build.

Thank you for your help! I solved this by using all these files and os,path:
`path = os.path.dirname(os.path.realpath((__file__)))
tdjson = CDLL(os.path.join(path, 'tdjson.dll'))`
