### ISSUE TITLE
 Private Group

### ISSUE THREAD

**Issue by pmhatre0077** [tdlib/td#1273]
Building an Unofficial Private Telegram App in which we are customizing many features of telegram.

Need some help to achieve one of the features where group created in our unofficial telegram app should not visible or accessible with the same account of telegram app

@kossnocorp @aurimasniekis @moldabekov @KrauseFx @levlam

**Comment by levlam** [comment]
This is impossible if you want to use Telegram groups. The list of chats is synchronized between all clients.
