### ISSUE TITLE
compile windows x-64 for java fails, how to set DTd_DIR and DCMAKE_INSTALL_PREFIX?

### ISSUE THREAD

**Issue by lmcmceo** [tdlib/td#1274]
![image](https://user-images.githubusercontent.com/71498780/98081027-d8b79a80-1e8f-11eb-8164-307a33746623.png)

cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) ..

When I execute this, it shows
![image](https://user-images.githubusercontent.com/71498780/98081139-fe44a400-1e8f-11eb-8049-1bada7c863f5.png)

**Comment by levlam** [comment]
Are you trying to use `cmd` instead of `PowerShell`?
