### ISSUE TITLE
Private proxy

### ISSUE THREAD

**Issue by dm-sizov** [tdlib/td#1276]
The official library documentation for the [addProxy()](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_proxy.html) function does not say anything about the username and password arguments. Does the library support private proxies, and if so, how?

**Comment by levlam** [comment]
[proxyTypeHttp](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1proxy_type_http.html).
[proxyTypeSocks5](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1proxy_type_socks5.html).
[proxyTypeMtproto](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1proxy_type_mtproto.html).

**Comment by dm-sizov** [comment]
> [proxyTypeHttp](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1proxy_type_http.html).
> [proxyTypeSocks5](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1proxy_type_socks5.html).
> [proxyTypeMtproto](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1proxy_type_mtproto.html).

`td_send({'@type': 'testProxy',
         'server': ip,
         'port': port,
         'type': ?})`
How is it possible to implement type?

**Comment by levlam** [comment]
For example, `{'@type': 'proxyTypeSocks5.', ...}`.

**Comment by dm-sizov** [comment]
> For example, `{'@type': 'proxyTypeSocks5.', ...}`.
@type denotes the method to dispatch. Before "?" everything is fine, instead of this symbol the program asks for an object. I don't understand in what format to transfer the last element of the dictionary.
