### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by Oisin-Kelly** [tdlib/td#1278]
I’m not sure whether this is old code but in c++ examples there is an include td_api.h, and i cannot seem to find this file anywhere. There is another file called td_api.hpp which I cannot find, and therefore I cant test the example?  I’m not too sure on how to install dependencies as I’m relatively new to c++. Any criticism is welcome, thanks.

**Comment by levlam** [comment]
Those are TDLib headers which are installed along with TDLib library. As stated in the C++ example README, you can install TDLib in the subdirectory of `example/cpp`:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../example/cpp/td ..
```
and then specify that directory to build еру example:
```
cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=<full path to TDLib sources>/example/cpp/td/lib/cmake/Td ..
```
