### ISSUE TITLE
When I receive message(a link, like https://t.me/tdlibchat), then I call GetMessageLinkInfo, but get Wrong message link URL

### ISSUE THREAD

**Issue by lmcmceo** [tdlib/td#1279]
long queryId = currentQueryId.incrementAndGet();
queryIdMapHandler.put(queryId, new Handler(updatesHandler, null));
logger.info("Call GetMessageLinkInfo");
Client.nativeClientSend(nativeClientId,queryId,  new TdApi.GetMessageLinkInfo(url));   

Error {
  code = 400
  message = "Wrong message link URL"
}

**Comment by levlam** [comment]
This is not a message link, this is a link to a chat. If you want to find a chat by its username, then you can use `searchPublicChat` method for that.

**Comment by lmcmceo** [comment]
I try searchPublicChat it works
