### ISSUE TITLE
Can't build TDLib

### ISSUE THREAD

**Issue by OleksiyMoroz** [tdlib/td#128]
Hello! While building tdlib have this issues, but have this issue and failed tests, can any help?
![image](https://user-images.githubusercontent.com/20989635/37063961-e87ce6be-21a3-11e8-8a92-0c3c2c26f027.png)

**Comment by isopen** [comment]
These environment variables can be ignored.

**Comment by arseny30** [comment]
@OleksiyMoroz Those are not errors, you may just ignore them.
Which tests are failing?

**Comment by isopen** [comment]
Most likely, the screenshot was made because of the wild love for TDLib.

**Comment by OleksiyMoroz** [comment]
@isopen Reinstall windows for compile one lib? Why not

**Comment by isopen** [comment]
Try virtual machines

**Comment by OleksiyMoroz** [comment]
@isopen And this guide do not compile binaries, it's unpacking solution. When i trying build solution have other errors.
Can anyone post here and/or send me to telegram the lib "libtdjson.dll"? 
My telegram: https://t.me/cyberskind

**Comment by isopen** [comment]
Try https://aws.amazon.com

**Comment by OleksiyMoroz** [comment]
@isopen sec

**Comment by OleksiyMoroz** [comment]
@isopen Error while trying build release:
![image](https://user-images.githubusercontent.com/20989635/37079990-51a3a472-21ed-11e8-889c-04ae373e18c2.png)

**Comment by isopen** [comment]
This does not seem to be a mistake. If you want to avoid this, try Linux.

**Comment by OleksiyMoroz** [comment]
@isopen )) how you love windows

**Comment by OleksiyMoroz** [comment]
@isopen and this from VS 2017 last update:
![image](https://user-images.githubusercontent.com/20989635/37080382-b9812316-21ee-11e8-9e46-87d811ed8b7b.png)

**Comment by arseny30** [comment]
Have you installed `gpref`?

**Comment by isopen** [comment]
Instructions for installing gperf can be found here.
https://medium.com/@mrmakss635/preparing-packages-for-building-tdlib-on-windows-10-b5a4bf7c0815

**Comment by isopen** [comment]
Here you need the advice of the expert @levlam

**Comment by OleksiyMoroz** [comment]
Do any have JSON lib for windows?)

**Comment by isopen** [comment]
Or use the Preston cycle

**Comment by OleksiyMoroz** [comment]
@isopen trying this exactly, but...
![image](https://user-images.githubusercontent.com/20989635/37085008-b14ed7d4-21fc-11e8-8160-26d6365e8296.png)

**Comment by isopen** [comment]
I think that Preston will eventually publish ready-made assemblies.

**Comment by levlam** [comment]
@OleksiyMoroz Could you update TDLib to the recent version and reopen the issue with mentioning the exact errors if the build still fails?

**Comment by OleksiyMoroz** [comment]
@levlam Thank you, will look
