### ISSUE TITLE
[C#] TdExample. The referenced component 'Telegram.Td' could not be found

### ISSUE THREAD

**Issue by PickGG** [tdlib/td#1280]
![telegram Td](https://user-images.githubusercontent.com/35164385/98223784-6b316a00-1f74-11eb-9100-7e1e077b0a44.PNG)

I followed the instructions: https://github.com/tdlib/td/tree/master/example/csharp

And also in folder "csharp" the file Telegram.Td.dll not exists

Logs
`
C:\dev\tdlib_src\example\csharp\build>cmake -A Win32 -DTD_ENABLE_DOTNET=ON -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake ../../..
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: C:/dev/vcpkg/installed/x86-windows/include C:/dev/vcpkg/installed/x86-windows/debug/lib/libssl.lib;C:/dev/vcpkg/installed/x86-windows/debug/lib/libcrypto.lib
-- Found ZLIB: C:/dev/vcpkg/installed/x86-windows/include optimized;C:/dev/vcpkg/installed/x86-windows/lib/zlib.lib;debug;C:/dev/vcpkg/installed/x86-windows/debug/lib/zlibd.lib
-- Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
-- Could NOT find Readline (this is NOT an error)
-- Configuring done
CMake Warning in CMakeLists.txt:
  For the target "tddotnet" the /clr compiler flag was added manually.  Set
  usage of C++/CLI by setting COMMON_LANGUAGE_RUNTIME target property.

-- Generating done
-- Build files have been written to: C:/dev/tdlib_src/example/csharp/build

C:\dev\tdlib_src\example\csharp\build>cmake --build . --config Release
Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Checking Build System
  Generate git_commit.h
  Building Custom Rule C:/dev/tdlib_src/CMakeLists.txt
  generate_mime_types_gperf.vcxproj -> C:\dev\tdlib_src\example\csharp\build\tdutils\generate\Release\generate_mime_typ
  es_gperf.exe
  Generating ../../../../../tdutils/generate/auto/mime_type_to_extension.cpp
  "C:\dev\gperf\bin" не является внутренней или внешней
  командой, исполняемой программой или пакетным файлом.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231
,5): error MSB6006: "cmd.exe" завершилась с кодом 9009. [C:\dev\tdlib_src\example\csharp\build\tdutils\generate\tdmime_
auto.vcxproj]
  tdsqlite.vcxproj -> C:\dev\tdlib_src\example\csharp\build\sqlite\Release\tdsqlite.lib
  tdtl.vcxproj -> C:\dev\tdlib_src\example\csharp\build\tdtl\Release\tdtl.lib
  generate_common.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Release\generate_common.exe
  Generate common tl source files
  td_generate_dotnet_api.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Release\td_generate_dotnet_api.ex
  e
  Generate .NET API files
  remove_documentation.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Release\remove_documentation.exe
  Remove C++ documentation from sources
  Building Custom Rule C:/dev/tdlib_src/CMakeLists.txt
  generate_c.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Release\generate_c.exe
  td_generate_java_api.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Release\td_generate_java_api.exe

C:\dev\tdlib_src\example\csharp\build>cmake --build . --config Debug
Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Checking Build System
  Generate git_commit.h
  Building Custom Rule C:/dev/tdlib_src/CMakeLists.txt
  generate_mime_types_gperf.vcxproj -> C:\dev\tdlib_src\example\csharp\build\tdutils\generate\Debug\generate_mime_types_gperf.exe
  Generating ../../../../../tdutils/generate/auto/mime_type_to_extension.cpp
  "C:\dev\gperf\bin" не является внутренней или внешней
  командой, исполняемой программой или пакетным файлом.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" завершилась с кодо
м 9009. [C:\dev\tdlib_src\example\csharp\build\tdutils\generate\tdmime_auto.vcxproj]
  tdsqlite.vcxproj -> C:\dev\tdlib_src\example\csharp\build\sqlite\Debug\tdsqlite.lib
  tdtl.vcxproj -> C:\dev\tdlib_src\example\csharp\build\tdtl\Debug\tdtl.lib
  generate_common.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Debug\generate_common.exe
  Generate common tl source files
  td_generate_dotnet_api.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Debug\td_generate_dotnet_api.exe
  Generate .NET API files
  remove_documentation.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Debug\remove_documentation.exe
  Remove C++ documentation from sources
  Building Custom Rule C:/dev/tdlib_src/CMakeLists.txt
  generate_c.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Debug\generate_c.exe
  td_generate_java_api.vcxproj -> C:\dev\tdlib_src\example\csharp\build\td\generate\Debug\td_generate_java_api.exe
`

**Comment by PickGG** [comment]
I also added this to PATH.
C:\dev\gperf\bin
C:\Program Files\CMake\bin.
Gperf version 3.0.1
CMake version 3.18.4

**Comment by levlam** [comment]
```
"C:\dev\gperf\bin" не является внутренней или внешней
```
You seems to have specified wrong path to gperf. Have you used `-DGPERF_EXECUTABLE:FILEPATH=C:\dev\gperf\bin` in one of the previous invocations? Now you need to manually edit CMakeCache.txt file and replace the value of GPERF_EXECUTABLE variable with the correct path to the correct executable.

**Comment by PickGG** [comment]
> Have you used `-DGPERF_EXECUTABLE:FILEPATH=C:\dev\gperf\bin` in one of the previous invocations?

No. But I added C:\dev\gperf\bin to PATH

**Comment by PickGG** [comment]
> ```
> "C:\dev\gperf\bin" не является внутренней или внешней
> ```
> 
> You seems to have specified wrong path to gperf. Have you used `-DGPERF_EXECUTABLE:FILEPATH=C:\dev\gperf\bin` in one of the previous invocations? Now you need to manually edit CMakeCache.txt file and replace the value of GPERF_EXECUTABLE variable with the correct path to the correct executable.

This problem appeared because on the first build I forgot to add gperf to PATH. And the path was set wrong
