### ISSUE TITLE
Point coordinates in map thumbnail picture returned by getMapThumbnailFile

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1281]
Is there a way to find point coordinates inside map thumbnail picture using lat/long values?  For example, I've fetched map thumbnail using `getMapThumbnailFile` with lat/long=50.0/60.0 width/height=800/600 zoom/scale=Z/S.  So point corresponding to lat/long(=50/60) is at x/y=400/300 coordinates.   I want to get x/y for say lat/long=49.05/60.01 point, what is the correct formula to calculate point coordinates?

Thanks

**Comment by levlam** [comment]
See https://en.wikipedia.org/wiki/Web_Mercator_projection.
