### ISSUE TITLE
getChatAdministrators triggers updateSupergroupFullInfo event

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1284]
I've noticed that `getChatAdministrators` triggers `updateSupergroupFullInfo` event even if nothing is changed in the corresponding supergroup.

Calling `getChatAdministrators` method twice in a row, triggers two identical `updateSupergroupFullInfo` events.   Is this expected?  Why update event is triggered when there is nothing changed in supergroup's full info?

Thanks

**Comment by levlam** [comment]
The supergroup's full info is different and differs in `administrator_count`, which accidentally changes to 0. This is still a bug.

**Comment by levlam** [comment]
This was fixed in master.
