### ISSUE TITLE
Call to checkAuthenticationCode unexpected

### ISSUE THREAD

**Issue by joaopaulomouram** [tdlib/td#1288]
Hey guys, I tested the lib locally and it works fine, but now I installed it on a VPS from Canada, I did the same steps, the SMS (Message on telegram) arrived but when I try to send the "checkAuthenticationCode" I am getting the response

Return from checkAuthenticationCode => `Call to checkAuthenticationCode unexpected`
Return from getAuthorizationState => `authorizationStateWaitPhoneNumber`

I saw an old ticket telling to send the logs for @tdlib_bot, but the bot is not answering and also I didn't find how to generate the local log file.

**Comment by levlam** [comment]
Have you implemented update-drievn authirization as described in https://core.telegram.org/tdlib/getting-started#user-authorization?

**Comment by joaopaulomouram** [comment]
Yes, I am using the client.php page, it works locally but on VPS no.

**Comment by levlam** [comment]
I don't know, what is client.php, but the error means that you are calling `checkAuthenticationCode` without receiving `authorizationStateWaitCode`.

**Comment by joaopaulomouram** [comment]
This is the problem, I am doing these steps:

1) setAuthenticationPhoneNumber -> Received the code on telegram
2) Then I try to checkAuthenticationCode with the code that I received and I got this return 

```
Return from checkAuthenticationCode => Call to checkAuthenticationCode unexpected
Return from getAuthorizationState => authorizationStateWaitPhoneNumber
```
But before execute the second step I can see the `authorizationStateWaitCode`

**Comment by levlam** [comment]
Are you sure that TDLib instance isn't restrted after `authorizationStateWaitCode` state?

And yes, it can be clearly seen in the logs, what happens.

**Comment by joaopaulomouram** [comment]
If I not do the 2. step (checkAuthenticationCode) I can see the same getAuthorizationState response (authorizationStateWaitCode) a lot of times.
But when I try to checkAuthenticationCode it seems to be "restarted".

How can I check the logs?

**Comment by joaopaulomouram** [comment]
This is what I am doing

```
TDApi\LogConfiguration::setLogVerbosityLevel(\TDApi\LogConfiguration::LVL_ERROR);

    $client = new TDLib\JsonClient();
    $state = $client->getAuthorizationState();

    $tdlibParams = new TDApi\TDLibParameters();
    $tdlibParams
        ->setParameter(TDApi\TDLibParameters::USE_TEST_DC, false)
        ->setParameter(TDApi\TDLibParameters::DATABASE_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDApi\TDLibParameters::FILES_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDApi\TDLibParameters::USE_FILE_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_CHAT_INFO_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_MESSAGE_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_SECRET_CHATS, false)
        ->setParameter(TDApi\TDLibParameters::API_ID, $api_id)
        ->setParameter(TDApi\TDLibParameters::API_HASH, $api_hash)
        ->setParameter(TDApi\TDLibParameters::SYSTEM_LANGUAGE_CODE, 'en')
        ->setParameter(TDApi\TDLibParameters::DEVICE_MODEL, php_uname('s'))
        ->setParameter(TDApi\TDLibParameters::SYSTEM_VERSION, php_uname('v'))
        ->setParameter(TDApi\TDLibParameters::APPLICATION_VERSION, '0.0.10')
        ->setParameter(TDApi\TDLibParameters::ENABLE_STORAGE_OPTIMIZER, true)
        ->setParameter(TDApi\TDLibParameters::IGNORE_FILE_NAMES, false);
    $result = $client->setTdlibParameters($tdlibParams);
    $result = $client->setDatabaseEncryptionKey(); // checkDatabaseEncryptionKey(key) or DESTROY

    $result = $client->setAuthenticationPhoneNumber($phone_number, 3); // wait response 3 seconds. default - 1.
```

Then I have a "OK" result and the getAuthorizationState => authorizationStateWaitPhoneNumber

After this I execute this code

```
TDApi\LogConfiguration::setLogVerbosityLevel(\TDApi\LogConfiguration::LVL_ERROR);

    $client = new TDLib\JsonClient();
    $state = $client->getAuthorizationState();

    $tdlibParams = new TDApi\TDLibParameters();
    $tdlibParams
        ->setParameter(TDApi\TDLibParameters::USE_TEST_DC, false)
        ->setParameter(TDApi\TDLibParameters::DATABASE_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDApi\TDLibParameters::FILES_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDApi\TDLibParameters::USE_FILE_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_CHAT_INFO_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_MESSAGE_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_SECRET_CHATS, false)
        ->setParameter(TDApi\TDLibParameters::API_ID, $api_id)
        ->setParameter(TDApi\TDLibParameters::API_HASH, $api_hash)
        ->setParameter(TDApi\TDLibParameters::SYSTEM_LANGUAGE_CODE, 'en')
        ->setParameter(TDApi\TDLibParameters::DEVICE_MODEL, php_uname('s'))
        ->setParameter(TDApi\TDLibParameters::SYSTEM_VERSION, php_uname('v'))
        ->setParameter(TDApi\TDLibParameters::APPLICATION_VERSION, '0.0.10')
        ->setParameter(TDApi\TDLibParameters::ENABLE_STORAGE_OPTIMIZER, true)
        ->setParameter(TDApi\TDLibParameters::IGNORE_FILE_NAMES, false);
    $result = $client->setTdlibParameters($tdlibParams);
    $result = $client->setDatabaseEncryptionKey(); // checkDatabaseEncryptionKey(key) or DESTROY
    $result = $client->query(json_encode(['@type' => 'checkAuthenticationCode', 'code' => 'XXXXX', 'first_name' => 'FIRST NAME HERE', 'last_name' => 'LAST NAME HERE']), 10);
```

**Comment by levlam** [comment]
This is wrong? Why do you restart TDLib?

**Comment by joaopaulomouram** [comment]
I am following the steps recommended here https://github.com/yaroslavche/phptdlib/blob/master/php_examples/client.php

Now I tried a logout and nothing works anymore, it stopped on authorizationStateLoggingOut

**Comment by levlam** [comment]
This is a wrong way to authorize. Application is supposed to implement update-driven authorization as described in https://core.telegram.org/tdlib/getting-started#user-authorization.

**Comment by joaopaulomouram** [comment]
Ok, it worked now, I cleaned my tmp folder, did the same process and it works fine now, closing the issue, thanks for your time.
