### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by DobrySiabar** [tdlib/td#1289]
I'm making a custom telegram app, there are ways to change device name of the app thru "authorizationStateWaitTdlibParameters", but I can't see the way to change app version. Every time on the field of previous sessions I got "tdlibexample 1.0, TDLib 1.6.9":
![image](https://user-images.githubusercontent.com/45755611/98938807-8878b200-24f9-11eb-8f7d-b63ab4fc1605.png)

We have a Session class with an "application_name" parameter, but I can't figure out when to call this request.

**Comment by levlam** [comment]
Application version is specified in `setTdlibParameters`. Application name was specified in https://my.telegram.org.

**Comment by DobrySiabar** [comment]
> Application version is specified in `setTdlibParameters`. Application name was specified in https://my.telegram.org.

Thanks. I used id and hash from github example, now it's clear what's what.

**Comment by DobrySiabar** [comment]
I just changed id and hash to my personal, and from the official app it shows the same...
![Screen Shot 2020-11-12 at 3 43 40 PM](https://user-images.githubusercontent.com/45755611/98941644-ead3b180-24fd-11eb-96f9-31384a1a7a15.png)
![Screen Shot 2020-11-12 at 3 44 35 PM](https://user-images.githubusercontent.com/45755611/98941687-faeb9100-24fd-11eb-969a-a844dbaf59ef.png)

**Comment by DobrySiabar** [comment]
UPD. Short name was changed, TDLib 1.6.9 sign remains the same

**Comment by levlam** [comment]
TDLib version is added by TDLib.

**Comment by DobrySiabar** [comment]
> TDLib version is added by TDLib.

So there is no way to remove TDLib version, and every user will see that?

**Comment by levlam** [comment]
Yes, unless you want to patch TDLib source code.
