### ISSUE TITLE
Compiled binaries 

### ISSUE THREAD

**Issue by OleksiyMoroz** [tdlib/td#129]
Hello! I think many of you have issues with compiling TDLib by yourself
Propose the Telegram group for binaries source: https://t.me/joinchat/D1EEGBBIssaSbO0l81bF8w
If you successfully build it please upload there.
Now required libtdjson.dll for windows 10

**Comment by isopen** [comment]
Be afraid of viruses. Be afraid.

**Comment by OleksiyMoroz** [comment]
@isopen feel free to post viruses)

**Comment by isopen** [comment]
Let's wait for the answers of experts

**Comment by PeyTy** [comment]
Uploaded 32-bit Windows, 64-bit Linux libtdjson's

**Comment by ahvahsky2008** [comment]
Where i can found this?

**Comment by levlam** [comment]
I personally don't recommend to download precompiled binaries from random sources. TDLib has minimal number of dependencies and it is supposed to be easily built.

**Comment by dancojocaru2000** [comment]
> TDLib _[...]_ is supposed to be easily built.

Requiring Visual Studio is not a light requirement. Having a `.dll` to download and use in languages like Python is pretty great.

Furthermore, I've had compile times of tdlib up to 10 minutes. When you want to quickly tinker a little bit, 10 minutes is a mood breaker.

**Comment by isopen** [comment]
@dancojocaru2000 Try `clang ninja`
