### ISSUE TITLE
chat.positions behaviour with new 'chatFilter' feature

### ISSUE THREAD

**Issue by Michael-Kr** [tdlib/td#1290]
I use tdlib for an iOS application. Version 1.6.10, build from main.

I am trying to support the chat filters feature in my project but struggle to understand the exact logic of `chat.positions` property updates. 

Initially, everything works as I expect, both the relevant updates and responses to `getChat` have the information about all the chat positions in all the lists. But as I restart the application a few times (use_chat_info_database set to true) I notice that after some point the `updateNewChat` update starts to come with an empty positions array and the responses to `getChat` only have the position in the main list. 

What is the correct strategy to keep the `chat.positions` property up to date? 
If I can't rely on the values in the updates and `getChat` responses, does it mean that I have to manually call `getChats` for each `chatList` every app start (every chat or position update?) to calculate the positions manually?

**Comment by levlam** [comment]
Chat lists and position of the chats in them are loaded from the database/server only after explicit call to `getChats`. For each chat list you need to maintain list of chats from the chat list, ordered by (order, chat.id). Whenever you need to show a chat list and you don't have enough chats to show, you need to call `getChats`. If you receive empty response, then you can mark the chat list as fully know and skip future calls to `getChats` .

**Comment by Michael-Kr** [comment]
So it is not possible to get the chat.positions for all the chatFilters at once,
but once I've reached a chat in a chatList using getChats I can now on rely on the updates only to support this chat position in this (and only this) chatList, correct? 

Now I don't really understand why did I initially got all the chats positions in all the filters correctly without any `getChats` requests. But probably it is due to some internal tdlib logic on the first launch.

**Comment by levlam** [comment]
Yes, it is impossible to get order of a chat in a chat list before loading the chat list. Once you loaded a chat list up to some *position*, you can rely on the updates to maintain the chat list up to **this position**. If a chat goes below **that postiion**, its order can became unknown again, despite it still belongs to the chat list.

> Now I don't really understand why did I initially got all the chats positions in all the filters correctly without any getChats requests. But probably it is due to some internal tdlib logic on the first launch.

TDLib was likely to preload archive chat list. Preloading main and archive chat list is enough to eventually find positions of chats in all chat list.

**Comment by Michael-Kr** [comment]
Thank you for the clarification! 

May I suggest to add a note to the `getChat` request and `updateNewChat` description that they depend on the previous calls to the `getChats`? And maybe general note that tdlib is not stateless?
