### ISSUE TITLE
Invalid message sender specified

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1291]
Searching for a user's message in a group: why invalid?

![image](https://user-images.githubusercontent.com/56506714/99144319-ca435d00-269f-11eb-8e3c-97c7e32bc71b.png)

**Comment by levlam** [comment]
You can use only user IDs, which you received from TDLib after restart. See https://github.com/tdlib/td/issues/578 for more details.

**Comment by nekohasekai** [comment]
@levlam In my code, the id comes from the sender of the message I just received, so I don't think this should be the case.

**Comment by levlam** [comment]
Where from did you get the user ID?

**Comment by nekohasekai** [comment]
@levlam (Message.sender as MessafeSenderUser).id

**Comment by levlam** [comment]
Could you send TDLib's log with verbosity level 4 to @tdlib_bot in Telegram?

**Comment by nekohasekai** [comment]
Sorry, I cannot reproduce the error.
