### ISSUE TITLE
[Java] RegisterNatives failed for createNativeClient with signature ()I

### ISSUE THREAD

**Issue by darmiel** [tdlib/td#1294]
After exporting my Java project using Maven and the Shade plugin, I get the following error message on startup:
```
# java -Djava.library.path="libs" -jar telegram-client-core-1.0-SNAPSHOT.jar
[ 1][t 0][1605390602.289887428][tl_jni_object.cpp:37]   RegisterNatives failed for createNativeClient with signature ()I
FATAL ERROR in native method: RegisterNatives failed for createNativeClient with signature ()I
        at java.lang.ClassLoader$NativeLibrary.load0(java.base@11.0.9/Native Method)
        at java.lang.ClassLoader$NativeLibrary.load(java.base@11.0.9/ClassLoader.java:2442)
        at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.9/ClassLoader.java:2498)
        - locked <0x000000008b101e20> (a java.util.HashSet)
        at java.lang.ClassLoader.loadLibrary0(java.base@11.0.9/ClassLoader.java:2694)
        at java.lang.ClassLoader.loadLibrary(java.base@11.0.9/ClassLoader.java:2659)
        at java.lang.Runtime.loadLibrary0(java.base@11.0.9/Runtime.java:830)
        at java.lang.System.loadLibrary(java.base@11.0.9/System.java:1873)
        at io.d2a.tdclient.core.ClientMain.<clinit>(ClientMain.java:47)
Aborted
```

This problem first appeared on my Linux server.  
Locally on macOS everything works with the *.dylib, but with the *.so on the Linux server the error occurs.

I built the *.so file according to these instructions: https://tdlib.github.io/td/build.html?language=Java

Does anyone have an idea why this problem occurs?

**Comment by darmiel** [comment]
Seems that TdLib has updated since my local file (libtdjni.dylib).  
I will update my project accordingly and if it still doesn't work, I will reopen the issue.

**Comment by levlam** [comment]
Yes, internal interface was changed. You need to update libtdjni and Java classes simultaneously.

**Comment by darmiel** [comment]
Thank you @levlam for your answer.
I've built the library and source files using GitHub Actions (https://github.com/darmiel/tdlib-macos-build/blob/main/.github/workflows/macos-build.yml) [I hope it is okay if the repository is public. If not, of course I will make it private.]

Now I get the following error:
```
java.lang.UnsatisfiedLinkError: /Users/user/src/project/libs/libtdjni.dylib: dlopen(/Users/user/src/project/libs/libtdjni.dylib, 1): Library not loaded: /usr/local/opt/openssl@1.0.2t/lib/libssl.1.0.0.dylib
  Referenced from: /Users/user/src/project/libs/libtdjni.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
java.lang.UnsatisfiedLinkError: org.drinkless.tdlib.Client.nativeClientExecute(Lorg/drinkless/tdlib/TdApi$Function;)Lorg/drinkless/tdlib/TdApi$Object;
	at org.drinkless.tdlib.Client.nativeClientExecute(Native Method)
	at org.drinkless.tdlib.Client.execute(Client.java:83)
```

The runner has openssl 1.1.1h installed, just like on my computer, but libtdjni seems to access an outdated version 1.0.2t. 
Can I define the openssl version on build or do I have to install openssl 1.0.2t?

**Comment by levlam** [comment]
You have built TDLib with OpenSSL 1.0.2, so you must install OpenSSL 1.0.2 to use the library.

**Comment by darmiel** [comment]
Hey @levlam,

I've updated my project to the new API, but now I'm getting weird libc-errors.
I'm getting to the point where I'm prompted for my phone number, but immediately after that, the program crashes with the following message:
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

**Comment by levlam** [comment]
@darmiel Could you try to build the latest TDLib for Java using exact instructions from https://tdlib.github.io/td/build.html?language=Java locally and check that the [Java example](https://github.com/tdlib/td/tree/master/example/java) works? I have just checked that it works for me on macOS. I expect that you have some incompatible libraries between the Docker container and your system.

**Comment by darmiel** [comment]
@levlam Yeah, you're right. 
The example from the td/ repository works. 
The error-message only appears in the example when I close the program with CTRL+C.

Then I will see what it could be. Docker won't be a problem as I start the application directly from the IDE. 
And it shouldn't be the libraries either. With the "old" TDLib it still worked. 

But thanks for your help!

**Comment by darmiel** [comment]
Got it!

Had to add an empty loop:
```java
    while (true) {
      try {
        Thread.sleep(100);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
```

**Comment by levlam** [comment]
@darmiel Crash on CTRL + C was a bug. I pushed a fix for it. Thanks!

**Comment by levlam** [comment]
@darmiel But it is impossible to completely prevent crashes on Ctrl + С on macOS, so the only way to reliably fix it is to catch Ctrl + С by the app and generously close all TDLib instances before exiting.
