### ISSUE TITLE
Vector with messages ID

### ISSUE THREAD

**Issue by DobrySiabar** [tdlib/td#1295]
forwardMessages method require to put id's array to parameter message_ids
Can't figure out how should it look like in json manner.

`{
        "@type" = "forwardMessages",
        "chat_id" = 12345,
        "from_chat_id" = 12345,
        "message_ids" = ??????,
        "options" = {"@type": "sendMessageOptions",
                    "disable_notification" = true,
                    "from_background" = false,
                    "scheduling_state" = { "send_date" = 0 } 
                           },
        "as_album" = false,
        "send_copy" = false,
        "remove_caption" = false
        }`

And second, is the 'options' parameter written correctly?

**Comment by DobrySiabar** [comment]
From the documentation:
forwardMessages message_ids:vector<int53>
@message_ids Identifiers of the messages to forward

**Comment by levlam** [comment]
The correct way depends on your programming language. "vector" is an alias for "array".

"options" looks correct to me, exceptthat  in the latest TDLib versions its type was renamed to `messageSendOptions`.

**Comment by DobrySiabar** [comment]
> The correct way depends on your programming language.

Let it be just clean json. I'll translate it to my language.

> "vector" is an alias for "array".

I guessed, but when I put just an array of some integers, then an error pops up 'Can't find field "@type" '
What type? What syntax of json? No answers in the documentation, so inconveniently

**Comment by DobrySiabar** [comment]
Can you help with it?

**Comment by levlam** [comment]
The error is in the "scheduling_state" field, which type isn't specified. You can use `null` as scheduling state is you wan to send message immediately.

**Comment by DobrySiabar** [comment]
It works, thanks
