### ISSUE TITLE
Question: Control local caches size

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1296]
Just stumbled upon the Android app´s option to set cache expiry time with a slider, and I think thats really neat! Is this a function of tdlib already, so to set cache expiry by timeline, not by size?

**Comment by levlam** [comment]
TDLib gives much more flexibility in cache expiry settings. See the method https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1optimize_storage.html for more details.

You can also use undocumented options "storage_max_files_size" (in kilobytes), "storage_max_time_from_last_access", "storage_max_file_count" and "storage_immunity_delay" to change default storage optimizer parameters.

**Comment by Flohack74** [comment]
Wonderful thank you!
