### ISSUE TITLE
Question: Video thumbnail extraction

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1297]
Currently our TELEports Telegram client cannot supply a thumbnail on video upload. What do you think is the best way to do this? A quick google search just showed lots of complicated ways using ffmpeg, gstreamer and other 3rd party dependencies that might be hard to link into an app. How do the official apps handle this?

**Comment by levlam** [comment]
Most official apps use compiled in ffmpeg. Some use OS-provided API for thumbnail extraction.

**Comment by Flohack74** [comment]
Ok then we might consider this, thanks!
