### ISSUE TITLE
How to set ChatNotificationSettings as mute forever

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1299]
The document does not specify a certain value, but "If user is banned for more than 366 days or less than 30 seconds from the current time they are considered to be banned forever" in the http api document, is this complete?

**Comment by levlam** [comment]
You have cited documentation of a completely unrelated to notification settings field. You can specify mute time in the field `chatNotificationSettings.mute_for`. Just specify 2**31 - 1 (the maximum value of signed 32-bit integer) for the maximum mute time.

**Comment by nekohasekai** [comment]
thanks
