### ISSUE TITLE
Too Many Request

### ISSUE THREAD

**Issue by msh15** [tdlib/td#130]
Hello everyone, I'v received this error
{u'message': u'Too Many Requests: retry after 74447', u'code': 429, u'@extra': None, u'@type': u'error'}
when i was trying to login with a number to telegram with my tdlib client,
And it's appearing every time even after i send {'@type': 'logOut'} request.
How do i dismiss old requests to server and start fresh connectoin?

**Comment by msh15** [comment]
And now it's been received in every login request with any number :-|

**Comment by isopen** [comment]
Expect. But let's wait for the opinion of experts.

**Comment by msh15** [comment]
I think it's Telegram servers problem, because i logged out my tdesktop and try to re-login and i get the same error, this time without error code of course :-D

**Comment by isopen** [comment]
Presumably this is a protection against ddos.

**Comment by isopen** [comment]
🙈(monkey->client{forms validation}) ->
💊(tdlib{data validation->ai stop atack->'tsl+mtproto'}) ->
🍙(api{data validation->ai stop atack}->home) ->
🔑(cloud{data validation->ai stop atack->cloud data}) <- (reverse)
This is the standard application design pattern.

**Comment by levlam** [comment]
You have tried to log in too much times. You can't now log in again until flood control expires an need to wait for 74447 seconds.

**Comment by isopen** [comment]
Oh, such a cool scheme turned out. Such a scheme can show a lot of new things. It was not perfect, but very realistic.

**Comment by isopen** [comment]
I told you in the first message about the test servers. Here is another example of what you need as test data and test servers. The second kind is. The first is not. Servers on which you can break limits (not to wait long).

**Comment by isopen** [comment]
forbs zhget. kakaja-to dich' voobshhe

**Comment by msh15** [comment]
oh i got that, thanks for the tip.

**Comment by isopen** [comment]
Need test servers for third-party developers.
Looking ahead I started talking here: https://github.com/tdlib/td/issues/5

**Comment by leoMehlig** [comment]
@levlam Is there a way to lift the block again. I was testing my login flow and now cannot login anymore...

**Comment by levlam** [comment]
@leoMehlig No, it isn't possible. You can only use test_dc to double number of tries or use another phone number.

**Comment by wecodexyz** [comment]
@levlam i use another phone number and got the same error.
