### ISSUE TITLE
About making the function of importing mobile phone contacts

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#1300]
I use importContacts to import the numbers I get from the phone’s address book to check if any of my contacts and friends have used this application, but I haven’t got any returned importedContacts information. I’m stuck here. Think i need your help!
@levlam

**Comment by levlam** [comment]
This is up to server. If it doesn't return anything, then this is desired behavior.

**Comment by AquariusHunters** [comment]
So, what method should I use to achieve this function? @levlam

**Comment by levlam** [comment]
It is `importContacts`. But if it doesn't work for you, this is intended.

**Comment by AquariusHunters** [comment]
Thank you, I think this should be able to meet my requirements. After all, everyone has 500 contacts, which in my opinion is already a very large social circle. @levlam

**Comment by levlam** [comment]
@AquariusHunters What do you mean?
