### ISSUE TITLE
Encryption data padding between 12..1024

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1304]
https://core.telegram.org/mtproto/description#encrypted-message-encrypted-data
Is the amount of padding mentioned here padded according to an alignment, up to a certain length of content or is it random?

**Comment by levlam** [comment]
It is up to the implementation. TDLib uses two different strategies used in different situations: https://github.com/tdlib/td/blob/1557fbcfe9f134c930d3d271d9aa0d22e3886b17/td/mtproto/Transport.cpp#L188.

**Comment by faissaloo** [comment]
Is the contents of the padding ever tested for sufficient entropy? Or can I just pad with zeroes for testing?

**Comment by levlam** [comment]
It is not possible to test a data for "sufficient entropy".

You must not pad with zeroes and always use a cryptographically secure random number generator.

**Comment by faissaloo** [comment]
> You must not pad with zeroes and always use a cryptographically secure random number generator.

I understand that I shouldn't, I'm just trying to figure out if I've done everything else right. If I don't do this (for the time being, where it's just me testing requests) can it cause the server to reject my request? Or because as you say it is not possible to test for 'sufficient entropy' will it just assume that whatever is in my padding is securely randomised?

**Comment by levlam** [comment]
Wherever the error, it isn't in padding, so there are no reasons to compromise the encryption even for testing.
