### ISSUE TITLE
Helppp

### ISSUE THREAD

**Issue by JohnSmith2000** [tdlib/td#131]
any method to check invite link info like members, group type , group name... by api ?
like `checkChatInviteLink`

**Comment by levlam** [comment]
It is checkChatInviteLink. What else do you want?

**Comment by isopen** [comment]
Most likely to talk

**Comment by JohnSmith2000** [comment]
I want to get link information using the api robot
As:
Group members
Type of group (super group or normal group)
Group name and ...

I used this method but did not answer
`https://api.telegram.org/bot`TOKEN`/checkChatInviteLink?invite_link=https://t.me/joinchat/BsTkekiL-HmVJhoTyfyc5Q`

Result
`{"ok":false,"error_code":404,"description":"Not Found: method not found"}`

**Comment by levlam** [comment]
This method isn't available in the Bot API and it will not be added soon.

**Comment by JohnSmith2000** [comment]
any another method for doing this with the api robot?

**Comment by levlam** [comment]
No. It is not possible to do with the Bot API.
