### ISSUE TITLE
"archive_and_mute_new_chats_from_unknown_users" option is not available

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1310]
With TDLib 1.6.10 I'm trying to set "archive_and_mute_new_chats_from_unknown_users" option with `setOption` method, but got "AUTOARCHIVE_NOT_AVAILABLE" error in return.

In TDLib logs I see:
```
[ 3][t 4][1606422923.759482383][ConfigManager.cpp:1473][#1][!ConfigManager]	Receive app config jsonObject {
...
    jsonObjectValue {
      key = "autoarchive_setting_available"
      value = jsonBool {
        value = false
      }
    }
...
```

Why this option is not available, and is there a way to make it available?

Thanks

**Comment by levlam** [comment]
The option documentation and change log describes this: "The option can be set only if the change was suggested by the server". You need to wait for corresponding `updateSuggestedActions` to be able to use this option.

**Comment by zevlg** [comment]
Ah, sorry, missed this

**Comment by levlam** [comment]
The option "can_archive_and_mute_new_chats_from_unknown_users" was added in TDLib 1.7.0, showing whether the option "archive_and_mute_new_chats_from_unknown_users" can be changed by the user.

**Comment by zevlg** [comment]
Thanks, that simplifies things!  Before this, I was tracking proposed actions from the server and make "archive_and_mute_new_chats_from_unknown_users" available if corresponding action is proposed.  Now I can do similar as for "ignore_sensitive_content_restrictions" option
