### ISSUE TITLE
Stop the bot

### ISSUE THREAD

**Issue by DobrySiabar** [tdlib/td#1311]
I am trying to use 'deleteChatHistory', but the bot is still sending me messages. 
How do I stop the bot and delete the entire chat?

**Comment by levlam** [comment]
You need to block the user. You can use `toggleMessageSenderIsBlocked` in the latest TDLib version for that.

**Comment by DobrySiabar** [comment]
What is the syntax for it? 
Can't find
![Screen Shot 2020-11-27 at 11 59 28 AM](https://user-images.githubusercontent.com/45755611/100430657-2185fc00-30a8-11eb-82d3-4e54b2319947.png)

**Comment by levlam** [comment]
https://github.com/tdlib/td/blob/56866524aaa2d474871a60befd6b175a704ba92e/td/generate/scheme/td_api.tl#L4273
