### ISSUE TITLE
Contacts Import

### ISSUE THREAD

**Issue by dm-sizov** [tdlib/td#1312]
`td_send({'@type': 'importContacts', 'contacts': [{'@type': 'contact', 'phone_number': '+7952077****'}, {'@type': 'contact', 'phone_number': '+7996121****'}]})`
When I'm trying to import registered users, I get 0 IDs, why does it happen?
`{'@type': 'importedContacts', 'user_ids': [0, 0], 'importer_count': [1, 1], '@extra': 12}`

**Comment by levlam** [comment]
Because you are restricted by the server from importing random people. This is expected behavior.

**Comment by dm-sizov** [comment]
> Because you are restricted by the server from importing random people. This is expected behavior.

When can I get ID of my contacts? What should happen?

**Comment by levlam** [comment]
What are you trying to achieve?

**Comment by dm-sizov** [comment]
> What are you trying to achieve?

I need to create a new chat with some registered users from my contacts list. Is it possible?

**Comment by levlam** [comment]
If you can't import the contact and can't find the user in another way, then this is impossible.

**Comment by dm-sizov** [comment]
> If you can't import the contact and can't find the user in another way, then this is impossible.

Can I use `AddContact()` without user_id? Will it work? Some trying result was 'User not found', when user is registeted.
And when `importContacts` can show users ID's?

**Comment by levlam** [comment]
`addContact` adds contacts by their `user_id`, but you must receive the user from TDLib first. Also, you don't actually need to add users to contacts to be able to message them.

`importContacts` will return users whenever appropriate and possible, i.e. the user allowed to find themselves by phone number.

**Comment by dm-sizov** [comment]
> `addContact` adds contacts by their `user_id`, but you must receive the user from TDLib first. Also, you don't actually need to add users to contacts to be able to message them.
> 
> `importContacts` will return users whenever appropriate and possible, i.e. the user allowed to find themselves by phone number.

Are there some ways to get user_id using phone number?

**Comment by levlam** [comment]
Yes, using `importContacts`. But if the user_id isn't returned, this is expected behavior.

**Comment by dm-sizov** [comment]
> Yes, using `importContacts`. But if the user_id isn't returned, this is expected behavior.

I solved it. The reason was in `use_test_dc`. Thank you for help!
