### ISSUE TITLE
Wrong invite link

### ISSUE THREAD

**Issue by dm-sizov** [tdlib/td#1313]
When I'm trying to join chat by `joinChatByInviteLink`, I get `error 3: Wrong invite link`. The same happens with `getDeepLinkInfo`. What should I do to solve this problems?

**Comment by levlam** [comment]
You need to read method documentation:
```
@invite_link Invite link to import; should begin with "https://t.me/joinchat/", "https://telegram.me/joinchat/", or "https://telegram.dog/joinchat/"
```

**Comment by levlam** [comment]
The parameter name is `invite_link`.

**Comment by dm-sizov** [comment]
> The parameter name is `invite_link`.

Woops, thank you. Are there any ways to join channels through link?

**Comment by levlam** [comment]
No.
