### ISSUE TITLE
setChatMemberStatus do not generate updateSupergroup event after sync with server

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1315]
I call "setChatMemberStatus" to set my "custom_title" in a supergroup.   In official client I see that custom_title is applied, so info has been synchronized with the server and I was expecting "updateSupergroup" to be delivered after sync with server, however got no such event.

What is the correct way to ensure that my chat member status has been successfully updated and synchronized with the server?

Thanks

**Comment by levlam** [comment]
This is expected behavior for now, because server doesn't provide this information. It is documented in `supergroup.status` documentation: "Status of the current user in the supergroup or channel; custom title will be always empty".

**Comment by levlam** [comment]
If the request returns `ok`, then the status has been successfully updated.
