### ISSUE TITLE
how to user getchats in libtdjson.so

### ISSUE THREAD

**Issue by mhbesharatnia** [tdlib/td#1316]
hey
i send this message to Tdlib via libtdjson but get error 
how to set chat_list in json format?
$tdlib->send([
        "@type" => "getChats",
        "chat_list"=>[
            "@type"=>"ChatList",
            "ChatList"=>"chatListMain"
            ],
        "offset_order" => 9223372036854775807,
        "offset_chat_id" => 0,
        "limit" => 200,
    ]);
{"@type":"error","code":400,"message":"Failed to parse JSON object as TDLib request: Unknown class \"ChatList\""}

**Comment by IRGC** [comment]
try

$tdlib->send([
"@type" => "getChats",
"chat_list"=>[
"@type"=>"chatListMain",
],
"offset_order" => 9223372036854775807,
"offset_chat_id" => 0,
"limit" => 200,
]);

**Comment by mhbesharatnia** [comment]
> try $tdlib->send([ "@type" => "getChats", "chat_list"=>[ "@type"=>"chatListMain", ], "offset_order" => 9223372036854775807, "offset_chat_id" => 0, "limit" => 200, ]);

I try this
get new error:
{"@type":"error","code":401,"message":"Unauthorized"}

**Comment by IRGC** [comment]
means you are not logged in? 😟

**Comment by mhbesharatnia** [comment]
> means you are not logged in?

it's true 
the is some problem with session
thank
