### ISSUE TITLE
The new tdjni did not automatically send updates

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1317]
Everything was fine before [tdjni.cpp was updated](https://github.com/TdBotProject/LibTDJni/commit/f7b37f9c9da652c84d04c709195fd182793ad4ec)

There is no log except after fc:

```
[ 2][t 4][1606997810.004823207][Td.cpp:4110][#1][!Td]	Close Td in state 0
[ 4][t 4][1606997810.004904985][Td.cpp:3957][#1][!Td]	Decrease request actor count to 0
[ 2][t 4][1606997810.004922151][Td.cpp:3959][#1][!Td]	Have no request actors
[ 4][t 4][1606997810.004939079][Td.cpp:3867][#1][!Td]	Decrease reference count to 0
[ 2][t 4][1606997810.004952192][Td.cpp:3935][#1][!Td]	ON_CLOSED
[ 3][t 4][1606997810.005754232][Td.cpp:3850][#1][!Td]	Receive Td::hangup
[ 2][t 4][1606997810.005800008][Td.cpp:3945][#1][!Td]	Stop Td
```

**Comment by nekohasekai** [comment]
Sorry i don't understand cpp, but it looks stuck.

![image](https://user-images.githubusercontent.com/56506714/101017767-7ee8e400-35a5-11eb-8ae8-d01fa6e7c444.png)

**Comment by nekohasekai** [comment]
I disabled the mute of td_requests, it shows:

```
[ 3][t 4][1606999087.460821151][Td.cpp:4588][#1][!Td][&td_requests]	Sending update: UpdateOption {
  name = "version"
  value = OptionValueString {
    value = "1.7.0"
  }
}
[ 3][t 4][1606999087.460904121][Td.cpp:4588][#1][!Td][&td_requests]	Sending update: UpdateAuthorizationState {
  authorizationState = AuthorizationStateWaitTdlibParameters {
  }
}
[ 3][t 4][1606999087.460921287][Td.cpp:3449][#1][!Td][&td_requests]	Receive request 1: Close {
}
[ 3][t 4][1606999087.460932254][Td.cpp:4603][#1][!Td][&td_requests]	Sending result for request 1: Ok {
}
[ 2][t 4][1606999087.460940122][Td.cpp:4110][#1][!Td]	Close Td in state 0
[ 4][t 4][1606999087.460961103][Td.cpp:3957][#1][!Td]	Decrease request actor count to 0
[ 2][t 4][1606999087.460970163][Td.cpp:3959][#1][!Td]	Have no request actors
[ 4][t 4][1606999087.460981130][Td.cpp:3867][#1][!Td]	Decrease reference count to 0
[ 2][t 4][1606999087.460991144][Td.cpp:3935][#1][!Td]	ON_CLOSED
[ 3][t 4][1606999087.461001157][Td.cpp:4588][#1][!Td][&td_requests]	Sending update: UpdateAuthorizationState {
  authorizationState = AuthorizationStateClosed {
  }
}
[ 3][t 0][1606999087.461199283][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 0x7fa1300018c0
[ 3][t 0][1606999087.461255073][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1606999087.461292028][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 0x7fa1300019e0
[ 3][t 0][1606999087.461298942][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1606999087.461308002][Client.cpp:282][&td_requests]	End to wait for updates, returning object 1 0x7fa130001af0
[ 3][t 0][1606999087.461314201][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1606999087.461318016][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 0x7fa1a0054270
[ 3][t 4][1606999087.461357116][Td.cpp:3850][#1][!Td]	Receive Td::hangup
[ 2][t 4][1606999087.461370944][Td.cpp:3945][#1][!Td]	Stop Td
[ 3][t 0][1606999087.462033033][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 100.000000
[ 3][t 0][1606999087.462071180][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1606999087.462283134][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1606999087.462311029][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1606999087.462419033][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 100.000000
[ 3][t 0][1606999087.491509199][Client.cpp:282][&td_requests]	End to wait for updates, returning object 2 0x7fa13400f650
[ 3][t 0][1606999087.491559982][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1606999087.491578102][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 (nil)

```

But I am sure I did not send Close

**Comment by nekohasekai** [comment]
I found that after sigtrem/sigkill, it returns all cumulative updates.

![image](https://user-images.githubusercontent.com/56506714/101020676-d1c49a80-35a9-11eb-82a3-a7ba06f8160b.png)

**Comment by nekohasekai** [comment]
When I set timeout to 0.1, it also keeps returning empty.

![image](https://user-images.githubusercontent.com/56506714/101021444-e48b9f00-35aa-11eb-9f47-c8cc99ec2419.png)

**Comment by levlam** [comment]
@nekohasekai How do you close the application?

`tdjni` now has a daemon thread, which is never stopped until the application exists. Because the thread is daemon, application shouldn't wait it to finish. The thread should be automatically killed whenever the application exits.

**Comment by levlam** [comment]
`TdApi.Close` request is sent automatically by `Client` finalizer in case the application forgotten to call it.

**Comment by nekohasekai** [comment]
Use the IDE's termination button, as SIGINT

**Comment by levlam** [comment]
Which IDE on what OS? I expect that it somehow prevents the daemon thread from termination.

**Comment by nekohasekai** [comment]
@levlam intellij idea on manjaro

**Comment by nekohasekai** [comment]
I forgot to mention that I did send close to all active clients in the runtime shutdown hook of java, that is the only place

**Comment by nekohasekai** [comment]
I temporarily solved the problem: sending a testUseUpdate after starting the loop thread, which verified my guess.

**Comment by nekohasekai** [comment]
Maybe the problem has been found. My program is designed to wait for the first updateAuthorizationState, which used to be no problem.

**Comment by levlam** [comment]
@nekohasekai As I said the thread is daemon and it is not supposed to finish, but being daemon it shouldn't prevent application from quitting.

**Comment by nekohasekai** [comment]
@levlam This was made by me...Wait until tdlib exits.

**Comment by levlam** [comment]
How do you detect that TDLib exited?

**Comment by levlam** [comment]
You said that you waited for `updateAuthorizationState`, but you should receive at least `AuthorizationStateWaitTdlibParameters` after a client is created.

**Comment by nekohasekai** [comment]
@levlam I mean when AuthorizationStateClosed is received

**Comment by nekohasekai** [comment]
> You said that you waited for `updateAuthorizationState`, but you should receive at least `AuthorizationStateWaitTdlibParameters` after a client is created.

Yes, the problem now is that I will not receive any updates before executing `nativeClientSend`

**Comment by levlam** [comment]
@nekohasekai Have you updated all Java files? You seems to use outdated Client.java.

**Comment by nekohasekai** [comment]
@levlam Using an old version of client.java will of course cause it to fail to run.

![image](https://user-images.githubusercontent.com/56506714/101118659-84394380-3624-11eb-808a-c0ec76f293f0.png)

**Comment by levlam** [comment]
@nekohasekai There was a lot Client.java versions between current one and the old one. The current one always sends `TdApi.getOption` request right after the client is created: https://github.com/tdlib/td/blob/eb80924dad30af4e6d8385d058bb7e847174df5e/example/java/org/drinkless/tdlib/Client.java#L185-L191
But your log doesn't have this request.

**Comment by nekohasekai** [comment]
I used to think that updateOption should be received even if the getOption function is not sent, maybe the document needs to be changed.

**Comment by levlam** [comment]
@nekohasekai So you deleted the `GetOption` call from Client.java?

This call isn't related to `UpdateOption` though and the update will be received regardless of this request. But since TDLib 1.7.0 client is created asynchronously after first request is sent to it. The Java wrapper uses `GetOption` request to start the client after it is ready to accept updates from it.

**Comment by nekohasekai** [comment]
@levlam Except for native methods, I rewrote everything. I will pay attention to the change next time. . .

**Comment by levlam** [comment]
@nekohasekai Thanks, that explains the issue. The main difference of new interface is that updates for all clients are received in the same thread now, so there is only one update receiver and one receiver thread.
