### ISSUE TITLE
Source file path strings in compiled library

### ISSUE THREAD

**Issue by Wunderfitz** [tdlib/td#1318]
When building TDLib with the standard instructions (taken from https://tdlib.github.io/td/build.html?language=C%2B%2B) under Linux (more precisely: Sailfish OS 3.3), the final *.so files always contain strings with the file paths of the original sources. Example:

```
strings libtdjson.so.1.7.0 | grep mersdk

/home/mersdk/share/git/td/tdutils/td/utils/Status.h
/home/mersdk/share/git/td/tdutils/td/utils/Slice.h
/home/mersdk/share/git/td/tdutils/td/utils/JsonBuilder.h
/home/mersdk/share/git/td/td/telegram/ClientJson.cpp
/home/mersdk/share/git/td/tdutils/td/utils/MpscPollableQueue.h
/home/mersdk/share/git/td/td/telegram/Client.cpp
...
```
While that doesn't affect its productive use (by the way thank you very much for providing TDLib, it's a pleasure to work with it!), it's probably an issue when I want to pass the [Jolla Harbour](https://harbour.jolla.com/) rules as the validator complains about hard-coded file paths in my application. Yes, I could argue that it's a false-positive and get admitted anyway, but I wanted to check if there is a way to avoid it as it's specific to TDLib (other libraries and sources don't show that) and I haven't found anything in the sources or in the issues here yet (OK, it's a lot and the solution probably easy to miss...).

Anybody here who knows what to change in the original source or which flag I need to set in order to avoid that the source file path strings are in the compiled library? 

Thanks in advance for any help. Regards, Sebastian

**Comment by levlam** [comment]
All these paths come from the __FILE__ macros, which is used by the logging system, so I don't think there is a way to easily remove them.

**Comment by Wunderfitz** [comment]
Thanks @levlam for the hint! In the meantime, I tried it with the "false-positive" approach and was successful (well, it is a false positive, right? ;)). So from my perspective there is no further need to keep this one open. I'll close it.

**Comment by levlam** [comment]
@Wunderfitz You can find some workarounds in https://reproducible-builds.org/docs/build-path/.
