### ISSUE TITLE
get update when new user added to supergroup

### ISSUE THREAD

**Issue by graymind123** [tdlib/td#1319]
Is there any way to get new UpdateSupergroup or UpdateSupergroupFullinfo when new user added to supergroup.
suppose the user is admin of private channel.

**Comment by levlam** [comment]
There is no way to receive such update, but most of the time you will receive `updateNewMessage` with a message of type `messageChatAddMembers`.

**Comment by graymind123** [comment]
but according [this issue](https://github.com/tdlib/td/issues/374), MessageChatAddMembers don't fires most of the time.
 What is the best way to know we have a new subscriber? except polling GetSupergroupFullinfo or GetSupergroup?

**Comment by levlam** [comment]
MessageChatAddMembers is never sent in channels, but it is almost always sent in supergorups. There is no desired way to know when a subsciber is added to a channel.
