### ISSUE TITLE
Analog of sendInvoice in tdlib

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1320]
Hello, i'm trying to embed payments in my bot. In Bot API I found algorithm https://core.telegram.org/bots/payments
First of all is sendInvoice, but i can't find his analog in tdlib

**Comment by levlam** [comment]
See https://github.com/tdlib/telegram-bot-api/blob/e2ae8dad02a7c0046e162e12bc0c0c077fff5d14/telegram-bot-api/Client.cpp#L6079.

**Comment by HellFinger-s** [comment]
Thank`s for example, but I'm sorry, I'm pretty bad at c++. Can i ask you to write the name of the method(s) that are used for payment, please.

**Comment by levlam** [comment]
You can't find them in that code. You don't need to know C++ to be able to identify function calls and used td_api:: classes.

**Comment by HellFinger-s** [comment]
sendMessage with inputMessageContent => inputMessageInvoice will send invoice to chat, am i right?

**Comment by levlam** [comment]
Yes.

**Comment by HellFinger-s** [comment]
Thanks, i will try

**Comment by HellFinger-s** [comment]
https://pastebin.com/7mjKnAbH
try this code, but i got Failed to parse JSON object as TDLib request: Expected Object, got Array

**Comment by levlam** [comment]
You passed an Array instead of an Object. You need to follow the documentation to find error source.

**Comment by HellFinger-s** [comment]
Yes, you are right i fixed it. Another question what should i write in payload? I put '' but there is an error invalid_invoice_payload

**Comment by levlam** [comment]
https://core.telegram.org/bots/api#sendinvoice

**Comment by HellFinger-s** [comment]
Sorry, forgot to look there. Pu for example '12' in payload but got error Wrong padding length

**Comment by levlam** [comment]
In JSON interface payload must be base64-encoded as any otjer field of type `bytes`.

**Comment by HellFinger-s** [comment]
Thank's, it works. If someone needs it, here is aworking example https://pastebin.com/HqANJXT7
