### ISSUE TITLE
Support for video start text entity

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1323]
Official clients supports next feature:  If video message is sent with caption that contains say "0:10", then "0:10" is shown as link and when pressed video starts playing from 10s second.

Maybe add something like:
```
textEntityTypeVideoStart start:int32 = TextEntityType;
```

To simplify implementing this feature by TDLib clients.  What do you think?

Thanks

**Comment by levlam** [comment]
This is a part of the feature, requested in https://github.com/tdlib/td/issues/1083. It is supposed to be added someday.

**Comment by zevlg** [comment]
I’ll close this then, will monitor #1083 for updates
