### ISSUE TITLE
memory goes too high by Java

### ISSUE THREAD

**Issue by pomhubkok** [tdlib/td#1324]
hello sir.  i use tdlib 1.6.0 by Java.   
 int resultN = nativeClientReceive(nativeClientId, eventIds, events, timeout);
        for (int i = 0; i < resultN; i++) {
            processResult(eventIds[i], events[i]);
            events[i] = null;
        }
i find out that when i join some group,the events[] will return too many Tdlib.Message Object and the memory will always goes too high. both the whole linux os memory will goes high.    From jmap i can see all the  "]C" maybe "String" Object.     
How can i solve this.?May i stop receiving message from group? or any other way?

**Comment by pomhubkok** [comment]
besides i set useMessagedatabase=false

**Comment by levlam** [comment]
You can stop receiving messages from a group only by leaving it.

Without message database messages are never unloaded from memory, so app can use them in the future. This definitely causes a steady grow of used memory.

**Comment by pomhubkok** [comment]
> You can stop receiving messages from a group only by leaving it.
> 
> Without message database messages are never unloaded from memory, so app can use them in the future. This definitely causes a steady grow of used memory.

So i should use message database and clean the database  maybe every month?  Is there an api to clean that or tdlib will do it itself?  I think it should be an api.

**Comment by levlam** [comment]
There is no API for that.

**Comment by pomhubkok** [comment]
> There is no API for that.

thank u for help.   I set message database true and stop use getChats and send CloseChat.   It looks stable now but the cathe looks cost too much.     I will use multi accounts to have a check if the memory cost i can accept(even if do nothing but many groups)....   and the db.sqlite looks really big(bigger and bigger as i can see now) .     And is Java not suitable for doing this cause huge memory cost? Will it be better if I use golang?

**Comment by pomhubkok** [comment]
> You can stop receiving messages from a group only by leaving it.
> 
> Without message database messages are never unloaded from memory, so app can use them in the future. This definitely causes a steady grow of used memory.

May i stop receiving any messages and just open it when neccesary; Will it be too too many messages when open it so that i can't get what i need actually?

**Comment by pomhubkok** [comment]
> You can stop receiving messages from a group only by leaving it.
> 
> Without message database messages are never unloaded from memory, so app can use them in the future. This definitely causes a steady grow of used memory.

Maybe I should use tdlight instead?

**Comment by levlam** [comment]
> May i stop receiving any messages and just open it when neccesary; 

No. You can only close and reopen TDLib instance.

**Comment by pomhubkok** [comment]
> > May i stop receiving any messages and just open it when neccesary;
> 
> No. You can only close and reopen TDLib instance.

> > May i stop receiving any messages and just open it when neccesary;
> 
> No. You can only close and reopen TDLib instance.             

> > May i stop receiving any messages and just open it when neccesary;
> 
> No. You can only close and reopen TDLib instance.

Does it mean that I should stop the CLIENT thread and create a new one next time? And the events arrays will be fewer than the thread always runs?I'll have a try tomorrow thank you.

**Comment by levlam** [comment]
@pomhubkok No, it will be bigger. If you really want to receive only real-time updates, you need to disable all databases and set "ignore_background_updates" option to True.

**Comment by pomhubkok** [comment]
> @pomhubkok No, it will be bigger. If you really want to receive only real-time updates, you need to disable all databases and set "ignore_background_updates" option to True.
It works.Thank you.

**Comment by CaliforniaMountainSnake** [comment]
> You can stop receiving messages from a group only by leaving it.

@levlam Hello, I have a problem. The fact is I **continue** to receive updates for the group even after I have left it. It seems this happens ~5-10 minutes. Then the updates for the left group don't come.

**Comment by levlam** [comment]
@CaliforniaMountainSnake This is expected behavior if the group was recently opened.

**Comment by CaliforniaMountainSnake** [comment]
@levlam Sometimes the account still receives updates from the group even multiple hours after it had left the group. Does a particular timeout exist for this behavior?

**Comment by levlam** [comment]
@CaliforniaMountainSnake This is possible and depends on many factors.

**Comment by CaliforniaMountainSnake** [comment]
@levlam Thank you. How would you advise to remove from the RAM the updates that are coming from the left chats (the chats where the user already is not a member)?

**Comment by levlam** [comment]
@CaliforniaMountainSnake Just ignore them. The messages will be unloaded as any other messages.
