### ISSUE TITLE
setProfilePhoto doesn't change user photo

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1325]
I'm using php extension phptdlib, and I'm trying to change my photo by using setProfilePhoto, but when i call function from main loop it doesn't change photo.
Code: https://pastebin.com/SicEtajj
file_exists returns true

**Comment by levlam** [comment]
You are sending a wrong request. The method has one parameter, names "photo". And you must specify its type using field "@type".

**Comment by HellFinger-s** [comment]
Yes, thank's
