### ISSUE TITLE
Updates from WebSocket

### ISSUE THREAD

**Issue by hossein-zare** [tdlib/td#1326]
Hello,
Are all those updates such as `updateUser` `updateNewMessage` coming from the WebSocket one by one or TDLib is separating and returning them to the user?

I receive about 50 or more `updateUser` updates when i run the app.

**Comment by levlam** [comment]
TDLib (and Telegram) has nothing to do with WebSockets.

Updates are sent whenever they are needs to be sent. There can be a lot of needed updates, often thousands of them.

**Comment by hossein-zare** [comment]
Well in my case **Telegram React** is connected to `wss://vesta.web.telegram.org/apiws`
Aren't they coming from `wss://vesta.web.telegram.org/apiws`?

Thanks for your quick response!

**Comment by hossein-zare** [comment]
Well in my case **Telegram React** is connected to `wss://vesta.web.telegram.org/apiws`
Aren't they coming from `wss://vesta.web.telegram.org/apiws`?

Thanks for your quick response!

**Comment by levlam** [comment]
They can come from a lot of sources. But wherever they come from, they are definitely come in a different form.
