### ISSUE TITLE
Can i get user_id, if I know user_name?

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1328]
I wan't to know full information about user, by sending his user_name. But getUser and getUserFullInfo need user_id  to return information about user. So how could i get user_id, from user_name?

**Comment by levlam** [comment]
`searchPublicChat`, but this method has very tight flood limits, so you will be flood-limited soon.

**Comment by HellFinger-s** [comment]
Where I could find them? Maybe there are ways to solve this problem, for example calls method after some time interval?

**Comment by levlam** [comment]
> Maybe there are ways to solve this problem, for example calls method after some time interval?

No. You can't send more requests if you send them rarely.

**Comment by HellFinger-s** [comment]
So if I use searchPublicChat first time, i could't use it more? What do you mean that I will be flood-limited soon, how it express

**Comment by RememberTheAir** [comment]
@HellFinger-s after a number of attempts, Telegram will raise an exception and tell you to stop and wait n seconds. What's the threshold? Nobody knows, you have to properly handle the server response and adjust your attempts based on this response and/or past metrics. These limits often change server-side and they are not documented. This one is especially tight

**Comment by HellFinger-s** [comment]
@RememberTheAir thank's for your answer, i will try
