### ISSUE TITLE
Telegram group for sharing experiance, use cases and just common talk about tdlib 

### ISSUE THREAD

**Issue by OleksiyMoroz** [tdlib/td#133]
Hi everyone!
We already have few working use cases with telegram api on .net core 2(using another lib), but now exploring TDLib and welcome to everyone who can share knowledge or ask something
Join us: https://t.me/joinchat/D1EEGFGryrpjJL97jnnnEA

**Comment by isopen** [comment]
bio https://github.com/tdlib/td/issues/5

**Comment by newsh** [comment]
https://t.me/joinchat/D1EEGFGryrpjJL97jnnnEA
> "This invite link is broken or has expired."  
😪

**Comment by mkliu** [comment]
link is broken. anything new?

**Comment by niklzz** [comment]
@newsh please, give a new link to group

**Comment by OleksiyMoroz** [comment]
Hello everyone! New link 
https://t.me/tdlibcommon
