### ISSUE TITLE
Error when sending photo

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1330]
Hello, i'm trying to send Photo to user. Got error: expected object, got array. I uderstand what error mean, but i can't uderstand how express object in php.
code: https://pastebin.com/6858QmJ4
call function by sendPhoto('path_to_file', $client, $chat_id, [])
file_exists('path_to_file') prints true

**Comment by levlam** [comment]
sendPhoto is defintely not related to TDLib. Consult your wrapper documentation.

**Comment by HellFinger-s** [comment]
I mean sendMessage with input_message_content => inputMessagePhoto

**Comment by levlam** [comment]
"thumbnail" must be an object, not an array.

**Comment by HellFinger-s** [comment]
So, how i can understand, object specifically in php is an array with '@type' and parameters

**Comment by levlam** [comment]
You can use null if don't want to specify an object.

**Comment by HellFinger-s** [comment]
Like 'thumbnail => null ?

**Comment by levlam** [comment]
Yes.

**Comment by HellFinger-s** [comment]
Thank's
