### ISSUE TITLE
Changed bot_token to new one, and bot doesn't working.

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1332]
Hi, I changed bot token to new, I set new folder in td_parameters in 'database_directory'. Bot doesn't handle updates, just print NULL. Before I change  token, bot works correctly at all.
code: https://pastebin.com/F7sXyy5M

**Comment by levlam** [comment]
Send TDLib log with verbosity level 4 to @tdlib_bot in Telegram.

**Comment by HellFinger-s** [comment]
Nothing new

**Comment by levlam** [comment]
@HellFinger-s You didn't send logs.

**Comment by HellFinger-s** [comment]
https://pastebin.com/R0JUVUJU

**Comment by levlam** [comment]
@HellFinger-s You are unauthorized and don't handle properly update
```
updateAuthorizationState {
  authorization_state = authorizationStateWaitPhoneNumber {
  }
}
```

**Comment by HellFinger-s** [comment]
Yes, you are right. I forgot to send bot_token in authorization. Probable I delete it by mistake. Thank you.
