### ISSUE TITLE
Build error about unrecognized command line option ‘-Qunused-arguments’ in file td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o

### ISSUE THREAD

**Issue by SakuraPuare** [tdlib/td#1333]
I have some build error about unrecognized command line option ‘-Qunused-arguments’ in file td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o
It happend when I was building [telegram-bot-api](https://github.com/tdlib/telegram-bot-api)
I don't know how to deal with it 
Server is running on Debian 4.9.246 and all dependences are installed 

root@v2-hk1:/SakuraPuare/telegram-bot-api/build# cmake --build . --target install
[  0%] Building C object td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o
cc: error: unrecognized command line option ‘-Qunused-arguments’; did you mean ‘-Wunused-argument’?
td/sqlite/CMakeFiles/tdsqlite.dir/build.make:62: recipe for target 'td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o' failed
make[2]: *** [td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o] Error 1
CMakeFiles/Makefile2:1207: recipe for target 'td/sqlite/CMakeFiles/tdsqlite.dir/all' failed
make[1]: *** [td/sqlite/CMakeFiles/tdsqlite.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by levlam** [comment]
Could you show output of `cc --version` and to clarify, what do you mean by "Debian 4.9.246"?

**Comment by SakuraPuare** [comment]
cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
I think it's up-to-date

**Comment by SakuraPuare** [comment]
![image](https://user-images.githubusercontent.com/52142762/102499811-98fee800-40b6-11eb-81e5-3842a6f2280f.png)

**Comment by SakuraPuare** [comment]
Well it is very strange

**Comment by levlam** [comment]
Remove the build directory and begin building from scratch using instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Linux.

**Comment by SakuraPuare** [comment]
got it, thanks
