### ISSUE TITLE
"updateMessageInteractionInfo" event before "updateNewMessage"

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1334]
Sometimes I see "updateMessageInteractionInfo" events with "interaction_info.last_message_id" that is not yet known to the client.  New message with that message id arrives just after the "updateMessageInteractionInfo" event.  This adds a bit inconvenience to the client code, because if there is some logic related to "interaction_info.last_message_id" in "updateMessageInteractionInfo", client should delay that event processing waiting for the message to arrive and only then apply the logic.

Could order of the "updateMessageInteractionInfo" and "updateNewMessage" events be changed, so when "updateMessageInteractionInfo" event arrives, the message with "interaction_info.last_message_id" will be already known to the client?  Similarly to "updateChatLastMessage" event arriving **after** "updateNewMessage"

Thanks

**Comment by levlam** [comment]
There is no way to do that generally. TDLib can't preload last messages in all message threads, so message `reply_info.last_message_id` often will not be available to the client. The primary purpose of this field is to trigger message loading when `reply_info.last_message_id` increases and user is at the bottom of the message thread. But usually you will receive `updateNewMessage` for `reply_info.last_message_id` right after that, so you don't need to call `getChatHistory`. Is it the problem you want to fix?

**Comment by zevlg** [comment]
Yes, my client outlines current history load state based on "last_message_id" and the last message displayed for this threa.  If "last_message_id" is larger, then client thinks that not all thread history is loaded and visualizes this to user.  After this,  "updateNewMessage" arrives and client knows that all thread history is loaded and "not all history loaded" visualization is removed.  So I get annoying visual blinks.  I can actually live with this, however I'm planning to implement more logic and more visualizations, so that could be a problem.

In general, I want same behaviour for treads as "updateChatLastMessage" do, i.e. update last message in the chat after "updateNewMessage" is received

**Comment by levlam** [comment]
@zevlg `updateMessageInteractionInfo` for root thread message should be sent after `updateNewMessage`/`updateMessageSendSucceeded` in the latest TDLib version.

**Comment by zevlg** [comment]
Fantastic work, thank you!
