### ISSUE TITLE
tdlib on Swift

### ISSUE THREAD

**Issue by DobrySiabar** [tdlib/td#1337]
Hello. I am using tdlib built for Swift. Very often I got a fatal error with the message Terminating app due to uncaught exception 'NSRangeException' ... index 1 beyond bounds [0 .. 0]', 
in this part of the code:

private func queryResultAsync(_ result: String) {
        tdlibQueryQueue.async {
            let json = try? JSONSerialization.jsonObject(with: result.data(using: .utf8)!, options:[])
            if let dictionary = json as? [String:Any] {
                if let extra = dictionary["@extra"] as? Int64 {
                    let index = self.queryF.index(forKey: extra)!
                    self.queryF[index].value(dictionary)
                    self.queryF.remove(at: index)
                } else {
                    self.updateF!(dictionary)} } } }

I think this 
`let index = self.queryF.index(forKey: extra)!`
is the main reason of throwing errors. Force unwrapping of non-existent index.

**Comment by levlam** [comment]
This seems to happen when you are sending a query without specifying a callback for response.

**Comment by levlam** [comment]
No, sending a query without a callback should lead to call of `self.updateF` on the response. I can't see when this can cause a fatal error.

**Comment by levlam** [comment]
Do you have an exact trace? The exception message seems to refer to a wrong NSArray usage and this code doesn't have arrays at all.

**Comment by DobrySiabar** [comment]
I use toggleMessageSenderIsBlocked and deleteChatHistory, and it throws, but from time to time (1 fatal error in 5-10 method uses)

**Comment by DobrySiabar** [comment]
I just replaced the code to 
`if let dictionary = json as? [String:Any] {
                if let extra = dictionary["@extra"] as? Int64,
                    let index = self.queryF.index(forKey: extra) {
                        self.queryF[index].value(dictionary)
                        self.queryF.remove(at: index)
                } else {
                    self.updateF!(dictionary)
                }

            }`

and now I got Terminating app due to uncaught exception 'NSRangeException', ...index 1 **beyond** bounds [0 .. 0]'

**Comment by levlam** [comment]
This code can't throw the mentioned exception. You need to check your code. Finding exact exception trace should help.

**Comment by DobrySiabar** [comment]
What can be the reason for such an error in the bundle of using the deleteChatHistory method?

I check it in the official app, and it works (the chat history is deleted there too). But when an error occurs, chat history is still there. So the main reason is calling deleteChatHistory (with or without toggleMessageSenderIsBlocked).

**Comment by DobrySiabar** [comment]
![Uploading Screen Shot 2020-12-23 at 11.42.44 AM.png…]()

**Comment by DobrySiabar** [comment]
![Screen Shot 2020-12-23 at 11 42 44 AM](https://user-images.githubusercontent.com/45755611/102977432-0629d780-4514-11eb-8a4b-08fc26ef4887.png)

**Comment by DobrySiabar** [comment]
I'll try to work without this methods and I'll write here, if I get the same error without them.

**Comment by levlam** [comment]
The error is somewhere in your code in an access to an NSArray.
