### ISSUE TITLE
tdweb build fails with "undeclared identifier 'threads_'"

### ISSUE THREAD

**Issue by hnz101** [tdlib/td#1338]
building tdweb fails with the following error:

>[...]
 [ 26%] Built target tdapi
Scanning dependencies of target tdactor
[ 26%] Building CXX object tdactor/CMakeFiles/tdactor.dir/td/actor/ConcurrentScheduler.cpp.o
/build/td/tdactor/td/actor/ConcurrentScheduler.cpp:142:25: error: use of undeclared identifier 'threads_'; did you mean 'thread'?
    for (auto &thread : threads_) {
                        ^~~~~~~~
                        thread
/build/td/tdactor/td/actor/ConcurrentScheduler.cpp:142:16: note: 'thread' declared here
    for (auto &thread : threads_) {
               ^
/build/td/tdactor/td/actor/ConcurrentScheduler.cpp:142:23: error: invalid range expression of type 'auto'; no viable 'begin' function available
    for (auto &thread : threads_) {
                      ^ ~~~~~~~~
2 errors generated.
em++: error: '/build/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/build/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/build/emsdk/upstream/emscripten/system/include -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/build/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/build/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/SSE -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/neon -Xclang -isystem/build/emsdk/upstream/emscripten/system/lib/compiler-rt/include -Xclang -isystem/build/emsdk/upstream/emscripten/system/lib/libunwind/include -Xclang -isystem/build/emsdk/upstream/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -D_FILE_OFFSET_BITS=64 -I/build/td/tdactor -I/build/td/tdutils -I/build/td/example/web/build/wasm/tdutils -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wpointer-arith -Wcast-qual -Wsign-compare -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wc++14-compat-pedantic -Wno-unused-command-line-argument -Qunused-arguments -Wodr -DNDEBUG -Os -fPIC -o CMakeFiles/tdactor.dir/td/actor/ConcurrentScheduler.cpp.o -c /build/td/tdactor/td/actor/ConcurrentScheduler.cpp -Xclang -isystem/build/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/tdactor.dir/td/actor/ConcurrentScheduler.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
make[3]: *** [tdactor/CMakeFiles/tdactor.dir/build.make:64: tdactor/CMakeFiles/tdactor.dir/td/actor/ConcurrentScheduler.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:686: tdactor/CMakeFiles/tdactor.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:463: CMakeFiles/td_wasm.dir/rule] Error 2
make: *** [Makefile:292: td_wasm] Error 2

**Comment by levlam** [comment]
Thanks. This should be fixed in master.

**Comment by hnz101** [comment]
builds fine now.
Thank You
