### ISSUE TITLE
Message Doesn't sending keyboard without errors

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1340]
Hello, I'm trying to send message with keyboard. Message sending, but keyboard not, and there are no errors.
My code: https://pastebin.com/uvL7CdMk
Logs: https://pastebin.com/Aantcq2n

**Comment by levlam** [comment]
Only bots can send messages with keyboards.

**Comment by HellFinger-s** [comment]
But I'm authorize like a bot

**Comment by levlam** [comment]
You are sending this as keyboard:
```
  reply_markup = replyMarkupShowKeyboard {
    rows = vector[2] {
      vector[1] {
        keyboardButton {
          text = ""
          type = null
        }
      }
      vector[1] {
        keyboardButton {
          text = ""
          type = null
        }
      }
    }
```

**Comment by HellFinger-s** [comment]
Thank's, i figured it out. Here is example of working keyboard https://pastebin.com/aQFE76ur
