### ISSUE TITLE
Integrate tl-parser into tdlib, remove .tlo binaries from the repository

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1341]
Integrate tl-parser in td/generate to remove the generated .tlo files from the source code.

Since tl-parser is currently using a broken build system, and it's not portable, I and Arves100 revamped tl-parser code to make it work on unix-based systems and windows.
The build system has been rewritten in cmake.

[TL-Parser](https://github.com/tdlight-team/tl-parser) is the repository with the modified code and the new build system.

I already tested it adding an additional build phase in td/generate cmakelists.txt and it works as expected.

**Comment by levlam** [comment]
This was implemented in master branch in https://github.com/tdlib/td/commit/a87af24fb907b4eff269fe87c7d8c8b63a91bfe1.

tlo files was removed form the repository, are generated automatically and placed in the directory `td/generate/auto/tlo/`.
