### ISSUE TITLE
"\n" and "</br>" does not work when sending message with markdown 

### ISSUE THREAD

**Issue by GavinToHill** [tdlib/td#1342]
I use the following code to format markdown , but it does not newline
TdApi.ParseTextEntities("11111\n22222", new TdApi.TextParseModeMarkdown(1))
TdApi.ParseTextEntities("11111<br/>22222", new TdApi.TextParseModeMarkdown(1))

I also try
TdApi.ParseTextEntities("11111\n22222", new TdApi.TextParseModeMarkdown(2))
TdApi.ParseTextEntities("11111<br/>22222", new TdApi.TextParseModeMarkdown(2))
How to newline when use TextParseModeMarkdown ?

**Comment by levlam** [comment]
This is not a question about TDLib, this is a question about basic Java programming. New line character is an ordinary character and it is no different from any other cheracter. `"11111\n22222"` definitely works:
```
TdApi.FormattedText text = (TdApi.FormattedText) Client.execute(new TdApi.ParseTextEntities("11111\n22222", new TdApi.TextParseModeMarkdown(1)));
```
