### ISSUE TITLE
Receive channel update in invalid chat 0 from updateNewChannelMessage

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1345]
`Receive channel update in invalid chat 0 from updateNewChannelMessage: updateNewChannelMessage { message = messageEmpty { id = 25644 } pts = 66926 pts_count = 1 }`

This happens randomly (in latest commit) and does not exist in tdlib 1.7.0

**Comment by levlam** [comment]
This is just a new log message and doesn't cause real issues. Nothing essential has changed.
