### ISSUE TITLE
remoteFileId is empty

### ISSUE THREAD

**Issue by zyadomer999** [tdlib/td#1347]
Hello,
Could you please let me know why remoteFielId is empty when I am trying to upload a file, as shown in the image?
<img width="735" alt="Screen Shot 2020-12-29 at 3 53 09 PM" src="https://user-images.githubusercontent.com/66646536/103285010-f6b3fe00-49ed-11eb-9e32-bb30ba813401.png">

**Comment by levlam** [comment]
Because the file is not updloaded and sent yet. The file isn't on Telegram servers, so there is no way it can have a remote ID.

**Comment by zyadomer999** [comment]
Thanks for answering,
Ok, but how can I know that the file uploading is finished and then how to get the remote id when finished?
This is the first update I get
<img width="497" alt="Screen Shot 2020-12-29 at 5 37 16 PM" src="https://user-images.githubusercontent.com/66646536/103291321-82348b80-49fc-11eb-80c6-91db2835320e.png">

This is the last update
<img width="473" alt="Screen Shot 2020-12-29 at 5 37 56 PM" src="https://user-images.githubusercontent.com/66646536/103291370-98dae280-49fc-11eb-91c2-e04615ffa8f2.png">

thanks for answering,

**Comment by levlam** [comment]
Because the file is not sent yet. The file isn't on Telegram servers, so there is no way it can have a remote ID.

**Comment by zyadomer999** [comment]
Okay, but how to know that the file uploading has finished and how to get remoteId after the file finished?

**Comment by levlam** [comment]
This is the documentation of the `uploadFile` method:
>Asynchronously uploads a file to the cloud without sending it in a message. updateFile will be used to notify about upload progress and successful completion of the upload. The file will not have a persistent remote identifier until it will be sent in a message`

Genrerally, you should not use `uploadFile` at all and need to use `sendMessage` instead.

**Comment by zyadomer999** [comment]
Thank you very much
