### ISSUE TITLE
No reply from GetChat() - God knows I tried

### ISSUE THREAD

**Issue by MarioSaldanhaLobo** [tdlib/td#1349]
Hello,
I think I have gone through every single page where "GetChats" appears. I still don't manage to get even a reply from the server. There is no feedback at all. And I even logged all the returned updates names to triple-check it.

I'm using C# (I'm a researcher on political science trying to get the dust off 20 years old development skills) and I try this that follows. What am I doing wrong? :/
I do get results from (nearly) all other requests I make.

client.Send(
       new tdApi.GetChats()
       {
                ChatList = new tdApi.ChatListMain(),
                Limit = 99,
                OffsetOrder = long.MaxValue,
                OffsetChatId = 0
       },
       new UpdatesHandler(this));

Thank you a lot

**Comment by levlam** [comment]
Send TDLib's log to @tdlib_bot in Telegram.

**Comment by MarioSaldanhaLobo** [comment]
Done

**Comment by MarioSaldanhaLobo** [comment]
For those stumbling on this thread.
The way to ask the chat list is the correct one. I was just using too much time processing other information.
Thanks @levlam

**Comment by dima279** [comment]
Hi! You're welcome, too, thank you, please
