### ISSUE TITLE
Sending error for request 1: Error

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#135]
When I use a precompiled Library the libtd：[https://core.telegram.org/tdlib](https://core.telegram.org/tdlib)
When I execute the send method, it's like this：
`TdApi.TdlibParameters authStateRequest = new TdApi.TdlibParameters();
  authStateRequest.apiId = 157364;
  authStateRequest.apiHash = "<censored>";
 Client.send(new TdApi.SetTdlibParameters(authStateRequest),new AuthorizationRequestHandler());`\

A mistake like this：
Sending error for request 1: Error { code = 30 message = "File "/td.binlog" can't be opened/created for reading and writing" }

How should I solve it？

**Comment by levlam** [comment]
You should specify a lot more tdlibParameters in order to properly init the library. The error happens because you haven't specified writable databaseDirectory, but there are a lot of other parameters which should be also set with a correct value in setTdlibParameters. And please don't publish your apiHash, it should be kept secret.

**Comment by liaoyu1992** [comment]
I modified the code
`TdApi.TdlibParameters authStateRequest = new TdApi.TdlibParameters();
        authStateRequest.apiId = 157364;
        authStateRequest.useMessageDatabase = true;
        authStateRequest.useSecretChats = true;
        authStateRequest.systemLanguageCode = PhoneUtils.getLocale(this).getISO3Language();
        authStateRequest.deviceModel = PhoneUtils.getModel();
        authStateRequest.systemVersion = PhoneUtils.getVersion();
        authStateRequest.applicationVersion = "5.0.2";
        authStateRequest.enableStorageOptimizer = true;
        TgClient.send(new TdApi.SetTdlibParameters(authStateRequest));`
Still appear this error
`The error happens because you haven't specified writable databaseDirectory.`
How can I specify a writable databaseDirectory

**Comment by levlam** [comment]
On Android you can use getApplicationContext().getFilesDir().getAbsolutePath() for example.

**Comment by liaoyu1992** [comment]
thank you,this error is solved.But now there's a new problem:
`Sending error for request 2: Error { code = 401 message = "Database encryption key is needed" }`
What is the database encryption key？How to set up it?

**Comment by liaoyu1992** [comment]
How to send messages to the bot？

**Comment by steelfl** [comment]
> On Android you can use getApplicationContext().getFilesDir().getAbsolutePath() for example.

I do not understand what I need to do with this?

**Comment by levlam** [comment]
@steelfl Pass a subdirectory of this directory as `database_directory` to TDLib.
