### ISSUE TITLE
Total price must be positive, but it is.

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1350]
Hi, I'm working with payments and at one point, the code began to give an error: total price must be positive, but it is positive.
My code: https://pastebin.com/5G1egc9P
Logs: https://pastebin.com/Gjej3XQa
I changed amount to 100*100 for example, but nothing changed.

**Comment by levlam** [comment]
You use wrong parameter name `priceParts`.

**Comment by HellFinger-s** [comment]
Thank you, I didn't notice
