### ISSUE TITLE
No updateNewMessage for messages arrived while offline in a particular chat

### ISSUE THREAD

**Issue by ars3niy** [tdlib/td#1353]
Launching a tdlib client after not having run it for some time normally results in an updateNewMessage for every message that this client hasn't seen. However, I'm facing a situation where one particular supergroup only shows the last message.

Tried with 1.6.0 and 1.6.5, with the database prior to launch from being from tdlib 1.6.0 in both cases.

How to get all the messages?

**Comment by ars3niy** [comment]
Sent (hopefully) logs to the bot. They contain a little bit more than tdlib messages but it's not much. Chat id in question is -1001355357904.

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/896.

**Comment by ars3niy** [comment]
And after receive an updateChatLastMessage with null message, is there any way to know what the last received message prior to that was using tdlib means?

**Comment by levlam** [comment]
App receives updates of last chat message with `updateChatLastMessage` from TDLib and can track its value.

**Comment by ars3niy** [comment]
Thanks for info!
