### ISSUE TITLE
Finding UserID by his/her username

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1355]
How can I find user_id of someone by username of his/her Account?

One of my Ideas was to use `SearchPublicChatsRequest` method by username of that user as query parameter and then find chat ID,
but with the chatID, even if I get the Chat object, I can't find the ID of my desired user 😢

**Comment by levlam** [comment]
Method `searchPublicChat` is supposed to be used for that. If returned `chat` has `type` `chatTypeUser`, then you can `user_id` from `chat.type`.
