### ISSUE TITLE
Wrong padding length

### ISSUE THREAD

**Issue by zyadomer999** [tdlib/td#1357]
Hello, could you please explain why I do usually face this problem when passing different strings to the callback_data of inline_keyboard_markup? For some strings, the error does not occur while for most does occur. I am using nodejs.
<img width="1015" alt="Screen Shot 2021-01-03 at 4 46 09 PM" src="https://user-images.githubusercontent.com/66646536/103480081-3199a580-4de3-11eb-9fd5-15a648d5855e.png">

Thanks

**Comment by dima279** [comment]
🔑

Отправлено с iPhone

3 янв. 2021 г., в 15:46, zyadomer999 <notifications@github.com> написал(а):

﻿

Hello, could you please explain why I do usually face this problem when passing different strings to the callback_data of inline_keyboard_markup? For some strings, the error does not occur while for most does occur. I am using nodejs.
[Screen Shot 2021-01-03 at 4 46 09 PM]<https://user-images.githubusercontent.com/66646536/103480081-3199a580-4de3-11eb-9fd5-15a648d5855e.png>

Thanks

**Comment by zyadomer999** [comment]
Could you please tell me how to solve it Mr, Dima?

**Comment by levlam** [comment]
In JSON interface all binary strings of type `bytes` must be base64-encoded.

**Comment by zyadomer999** [comment]
Thank you very much.
