### ISSUE TITLE
Calls does not work in official app if TDLib client is running

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1358]
I'm facing problem, that if TDLib client is running and there is incoming (voice) call, that I accept in official app, it won't connect stalling in "Connecting..." state.  Even if I quit TDLib client, calls from official app to official app still won't connect.  However, if I restart official app and TDLib client is not running, then calls connects successfully.

Is there something in TDLib client I should do to make calls in official app connect?

Thanks

**Comment by levlam** [comment]
I can't see a way one app can affect another app in the specified way. Calls are completely independent and whatever app accept it first, can connect to it. Another app will receive an error for `acceptCall` request.

**Comment by zevlg** [comment]
Just tried on fresh start for both apps (official and TDLib client) and official app successfully accepted the call.  Looks like it long time running official app just stopped accepting the calls and restart fixed this
