### ISSUE TITLE
Strange searchChatMembers behavior

### ISSUE THREAD

**Issue by psalajka** [tdlib/td#1359]
Hello, 

I encountered a strange searchChatMembers behavior. I search for "Josef" and I receive a user "Pepa Novák" (with an empty username). "Pepa" is a familiar form of "Josef" in Czech. I know he used to use the name "Josef Novák" and he changed it recently (a few days). Moreover, there is a user "Karel Bláha" who is not returned by any non-empty query string. Do you have any idea what's happening? I first encountered this through tdjson but the official desktop app behaves the same way.

I search a channel. Names are fictitious but the idea remains the same.

Thank you.

**Comment by levlam** [comment]
Do you have these users as your contacts?

**Comment by psalajka** [comment]
The first one "Josef/Pepa Novák" - yes., the second one - no. When I search my contacts for "Pepa" I got "Pepa". When I search channel subscribers for "Pepa" I got nothing, when I search for Josef, I got Pepa ... I was thinking about some cache problem, but it's the same, official desktop app, phone app, or my tdjson app, still the same.

**Comment by levlam** [comment]
For your contacts you always see the name specified by you, when the user was added to contacts. This name is used when you search your contacts or chats. But when you search channel subscribers, the user's self-specified name is used to search for them. You describe a correct behavior when user named himself "Josef Novák" and you added him to contacts with name "Pepa Novák".

**Comment by psalajka** [comment]
OK, thanks, I catch the idea. I made an experiment. There is a user "Jana". I added her to the channel and in my contacts, I renamed her to "Janča". Then I could search for "Jana" or "Janča" (in the channel subscribers), both worked. Well, I agree that this is probably the correct behavior, although I'm still not 100% sure. I have to search for "Josef" to get "Pepa". Search for "Pepa" doesn't work.

But there is a second user. I joined both questions together because I was pretty sure it's one issue.
I search the channel subscribers (query = 'stano') and
1) The official app returns exactly 1 matching user,
2) the TDJSON lib (searchChatMembers) returns none.

I deleted everything and rewrite my app twice. I recompiled the TDLib on Windows 10 and Ubuntu 20, the latest master and the latest tag. Still the same. And there is no such problem with any of the other 640 subscribers.

That's why I believe there is some kind of error.

**Comment by levlam** [comment]
Which filter do you use to search for "stano"?

Could you send corresponding TDLib log to @tdlib_bot?

**Comment by psalajka** [comment]
I don't specify any filter, i.e. default value.

Sorry, I'm a little confused, you want me to send the log to a Telegram Bot? :-O :-)

**Comment by levlam** [comment]
> I'm a little confused, you want me to send the log to a Telegram Bot?

Yes. To @tdlib_bot in Telegram.
