### ISSUE TITLE
ViewMessages should mark as read incrementally

### ISSUE THREAD

**Issue by FrayxRulez** [tdlib/td#136]
Telegram clients are now marking messages as read as the user scrolls the chat history.

Would be great if `ViewMessages` would behave the same, marking as read only seen messages, and not all the history at once.

**Comment by blacksailer** [comment]
is it marks all? there is parameter message_id

**Comment by levlam** [comment]
`ViewMessages` mark as read only seen messages since TDLib 1.3.0.
