### ISSUE TITLE
msg_container padding?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1360]
Hi, I've been trying to workout how msg_container works, at this point I've established a connection and I've sent a ping to the server, this is the response to that. I broke down the contents of said response and it looks as follows:
```
    [02000000: int 2 length]-
    [01XXXXXXXXXXf45f: long message_id]-
    [01000000: 1 int seqno]
    [1c000000: int bodylength]
    
    [[0809c29e: new_session_created int message_type]-
    [00000000XXXXf45f: long first_msg_id]-
    [XXXXXXXXXXXXXXXX: long unique_id]
    [XXXXXXXXXXXXXXXX: long server_salt]
    XXXXXXXXXXXX- 6 bytes of padding?]
    
    [[02000000: 2 int seqno]
    [14000000: 20 int bodylength]
    [c5737734: pong int message_type]-
    [00000000XXXXf45f: long message_id]-
    [dd63000000000000: long ping_id]]
```
Assuming those 6 bytes I've pointed out are indeed padding I'm not sure what algorithm determines how much padding gets added and I can't seem to find anything explicitly discussing it in https://core.telegram.org/mtproto/service_messages#containers

**Comment by levlam** [comment]
There is no way an object can have padding of 6 bytes. Every object length is divisible by 4 if protocol isn't obfuscated. Moreover TL serialization doesn't have any implicit paddings with exception for stored strings. In place denoted by "6 bytes of padding" there should be "long message_id" of the next message.

**Comment by faissaloo** [comment]
Thanks, turns out my problem was that I'd read some data in and skipped too far along the byte array.
