### ISSUE TITLE
What messages cause rpc_result to be sent back?

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1364]
https://core.telegram.org/mtproto/service_messages#response-to-an-rpc-query
Looking here `rpc_result` has a `result` of type `Object`, I was wondering what messages cause an `rpc_result` to be sent back, are only a subset of calls considered 'RPC queries' and if so how can I see what this subset consists of?

**Comment by levlam** [comment]
All functions require response from the server. Functions have separate section in TL-scheme.

**Comment by faissaloo** [comment]
I presume this doesn't include basic mtproto functions like `req_pq`, `req_DH_params` and `set_client_DH_params` since they don't give me `rpc_result`? So other than those, all other functions will give me an `rpc_result`?

**Comment by levlam** [comment]
Those are requests sent before `auth_key` is created. They are not related in any way to ordinary MTProto usage phase.

**Comment by faissaloo** [comment]
Thanks!
