### ISSUE TITLE
Chat not found!

### ISSUE THREAD

**Issue by zyadomer999** [tdlib/td#1365]
Hello, is there any solution for that error (chat not found) that occurs when I want to send a message to a user with a chat_id before the user interacts with the bot even if he already started the bot? If the user sends the bot a message, the error automatically disappears and I can send the user messages with no problem. 

Thanks for answering

**Comment by levlam** [comment]
Are you talking about a real bot?

**Comment by zyadomer999** [comment]
I am talking about a bot. First, I start the tdlib with nodejs and send a message to my bot on telegram app and get the chat id of the user, and then I stop the tdlib and make some changes to my bot and start the tdlib again and trying to send the user a message, it fails and says the chat not found. However, if i start the tdlib and the user sends the bot a message on telegram app, and then I send the user a message, the error will not occur.
This is true each time I make some chabges to the bot and start the tdlib. In a nutshell, a user must interact with the bot then the bot can send him messages.

**Comment by jumoog** [comment]
All chats are unknown at the start. Therefore you have to use `getChat()` as bot at startup. This ensures that the bot recognizes the chat ID.  As soon as the bot receives a message, the chat id is also known.

**Comment by zyadomer999** [comment]
Thanks dear for answering I get the point.

But I am concerned about something that may be associated with my problem and I want to make sure if you solve the problem the same way I do.

When I start the bot for the first time, the tdlib library creates two folders, namely _td_database and _td_files. However when I make some changes to my bot and start it again it shows me this error:

<img width="1077" alt="Screen Shot 2021-01-09 at 5 41 52 PM" src="https://user-images.githubusercontent.com/66646536/104094545-943ae780-52a2-11eb-893a-c5d05d93400a.png">

I solve this by putting this snippet of code at the start of my code which deletes the two folders:

<img width="496" alt="Screen Shot 2021-01-09 at 5 47 09 PM" src="https://user-images.githubusercontent.com/66646536/104094564-b3397980-52a2-11eb-8860-1960aeaf1e76.png">

Then the following code as before and as the initial start will create the two folders again:

<img width="908" alt="Screen Shot 2021-01-09 at 5 48 45 PM" src="https://user-images.githubusercontent.com/66646536/104094604-eda31680-52a2-11eb-8dfe-37a7dc3f6cdb.png">

I think when I delete the two folders all the database will be lost and is of no use.
Is there any other solution?

**Comment by zyadomer999** [comment]
Please Someone answer. I really need that

**Comment by levlam** [comment]
@zyadomer999 As error message tells, the database folder is already in use. You didn't stop your bot and try to launch it again in the same working folder.
