### ISSUE TITLE
Getting "Invalid ping query" on occasion

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#1367]
When I send a ping I sometimes get an RPC error as a response, the error is as follows:
`error_code = -500; error_message = "Invalid ping query"`
What can cause an invalid ping query? It's clearly able to parse the message correctly and I'm not changing the ping_id. Can this happen as a result of a problematic message_id or some other such issue?

**Comment by levlam** [comment]
This means that you are sending a query of wrong length.

**Comment by faissaloo** [comment]
I'm doing alot of testing right now but that doesn't seem to be an issue, if I intentionally send a query of the wrong length I get a regular -404 protocol error, not an rpc error of -500. I've also checked and this happens even if the message is the same size each time.
I've noticed that if I purposefully provide a message id that's calculated in a strange way it will give me the -500 error every time:
`((time_ms*((1L<<32)/1000L))>>>2)<<2` always produces the rpc error -500
The regular way I calculate it is with `(time_ms/1000L)<<32` and with this I only sometimes receive the rpc error -500 (although notably this doesn't have a fractional part
If I put something ridiculous as the message id I'll still get the regular bad msg errors of 16, 17 and 18 respectively though, so I'm really quite stumped about what's going on here.

**Comment by levlam** [comment]
No, this is the only reason to receive "Invalid ping query". You must specify a correct query length, but the length is wrong for sent requests. For example, ping_delay_disconnect length must be always 16 including magic.

**Comment by IRGC** [comment]
Can anyone make briefly described mtproto documentation?

**Comment by faissaloo** [comment]
> No, this is the only way to receive "Invalid ping query". You must specify a correct query length, but the length is wrong for sent query. For example, ping_delay_disconnect length must be always 16 bytes long including magic.

Alright thanks alot, I'm confused as to why it only happens intermittently and why message id stuff I described before happens but nonetheless I've found the culprit:
![Screenie_2](https://user-images.githubusercontent.com/8840681/104317843-6fc75100-54d6-11eb-96ac-68a515e4525e.png)
Yeah not my brightest moment...
