### ISSUE TITLE
Manage and control more than one telegram account

### ISSUE THREAD

**Issue by Xilosof** [tdlib/td#1368]
Is there a way to add multiple accounts to one program? Sorry for the stupid question. I tried to find information in issues and documentation

**Comment by levlam** [comment]
Yes, One accout = one database directory. Different database directory = different accounts.

**Comment by Xilosof** [comment]
Thanks for answer. 
If I understand correctly, I will create my own clients (.NET) for each user.

I still saw a problem that active maintenance of several users can cause a flood error. Its can be solved by using different proxy?

**Comment by levlam** [comment]
Flood limits for different users are completely independent.

**Comment by Xilosof** [comment]
Thanks for answer!
