### ISSUE TITLE
[Question] How to get TdApi.ChatInfo by the chatId/userId in Java?

### ISSUE THREAD

**Issue by sapelkinAV** [tdlib/td#137]
I'm looking about information about current chat. I need to use TdApi.SearchChatMessages, to filter messages by content type, but it's asking for senderUserId. I have separated list of chats(from one of it I want to get messages) and users. Is there any way to get userId by chatId in Java?

**Comment by sapelkinAV** [comment]
As I explored chatID is equals UserId. I'm closing issue.

**Comment by levlam** [comment]
It seems that you are misunderstanding meaning of senderUserId. It is used to additionally filter messages inside a chat by their sender. If you don't need to get messages from a specific user than just pass 0. There should be no reason to convert chatId to userId here. If it should be done anyway, then Chat.type of type ChatTypePrivate contains required userId.

**Comment by sapelkinAV** [comment]
Thanks for explanation.
