### ISSUE TITLE
Fix chats printing in the Example.java

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlib/td#1372]
https://github.com/tdlib/td/blob/27d3fdd09d90f6b77ecbcce50b1e86dc4b3dd366/example/java/org/drinkless/tdlib/example/Example.java#L288

If you set the `limit` bigger than the count of your chats, then you will give NotSuchElement exception.

The fix:
```java
for (int i = 0; i < mainChatList.size() && i < limit; i++) {
```

**Comment by levlam** [comment]
Thanks. This was fixed in master.
