### ISSUE TITLE
How to add Contact without having phone number?

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1373]
Hi
How can I add a new contact with it's Telegram ID? or Telegram username?
I've used ImportContacts method by leaving phone_number part free and setting the UserID value to TelegramID of the user that I wanted to add but it didn't work

**Comment by levlam** [comment]
> How can I add a new contact?

Have you tried `addContact`?

**Comment by telexengineering** [comment]
Yes I've tried that

**Comment by levlam** [comment]
Then you used it in a wrong way.

**Comment by telexengineering** [comment]
Yes I tried it again I should send SharePhoneNumber parameter true for it to work
