### ISSUE TITLE
Download old files failed

### ISSUE THREAD

**Issue by airani** [tdlib/td#1374]
I'm trying to download an audio file of July 2017 from a channel but I got this error:

```
400 File download has failed or was cancelled
```
when i called getFile `size` and `expectedSize` is `0`

I worked with TdLib v1.7.0 and I checked with official client and this file exists and downloaded correctly

**Comment by levlam** [comment]
You seems to use `inputFileRemote`. This is a description of the class:
```
A file defined by its remote ID. The remote ID is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application
```

**Comment by airani** [comment]
@levlam oh! thank you
