### ISSUE TITLE
Android file system support

### ISSUE THREAD

**Issue by datdefboi** [tdlib/td#1375]
While using TdLib on android, a problem was noticed in working with the android file system. If before version API 29 it was possible to use direct paths, then starting from version 30, the only URI is used to access files. Could you please explain how to pass the file address to the inputFileLocal class?

**Comment by jumoog** [comment]
you still can use direct paths see: https://developer.android.com/training/data-storage/shared/media#direct-file-paths

**Comment by levlam** [comment]
You need to use `inputFileGenerated` instead of `inputFileLocal` if the file is not available through a direct path.

**Comment by datdefboi** [comment]
> You need to use `inputFileGenerated` instead of `inputFileLocal` if the file is not available through a direct path.

Do I need to pass some internal `conversion_` value or directly pass URI to `original_path_`  to use URI-like paths?

**Comment by levlam** [comment]
@datdefboi See https://github.com/tdlib/td/issues/126#issuecomment-370568361.
