### ISSUE TITLE
Persisting data in tdweb

### ISSUE THREAD

**Issue by iTNTPiston** [tdlib/td#1376]
I followed the instruction in example/web and got the TD client working in a browser. However, after I use the client to authenticate, I couldn't find a way to persist the authentication state, which means I need to authenticate again after reloading the page. Is there any way to persist the logged-in state in tdweb? Thanks in advance!

**Comment by levlam** [comment]
This is done automatically by tdweb. All the data is saved in localStorage and IndexedDB.

**Comment by levlam** [comment]
What Emscripten version are you using to build tdweb? Could you try with emsdk 2.0.6, recommended in README.md?

**Comment by iTNTPiston** [comment]
I installed the latest from the link given in README.md. I will try with 2.0.6. 
Also, if I have authenticated before and launch a new instance of TdClient, does the authorization state go through wait phone number and code, or does it go directly to state ready?

**Comment by levlam** [comment]
If client with the same `options.instanceName` has been already authenticated, it doesn't need to authenticate again. You will receive `authorizationStateReady` directly after `authorizationStateWaitEncryptionKey` in that case.
