### ISSUE TITLE
 "Bad Request: USER_IS_BOT",

### ISSUE THREAD

**Issue by sachinTechugo** [tdlib/td#1377]
i tried to create a new sticker pack its giving me
{
    description = "Bad Request: USER_IS_BOT";
    "error_code" = 400;
    ok = 0;
}
and other api have no issue regrading that user id

**Comment by levlam** [comment]
You can't pass a bot's `user_id` to `createNewStickerSet`. You must specify a `user_id` of a user, using the bot, on behalf of which the sticker set will be created.

**Comment by sachinTechugo** [comment]
but for uploadStickerFile its working fine and i am using bot id as user id
and how we get user_id if a user as you commented

**Comment by levlam** [comment]
Bots can create sticker sets only on behalf of a user. The user will be able to manage the sticker set through @stickers bot. This is up to you to know, for which user you are creating the sticker set.

**Comment by sachinTechugo** [comment]
how do we get user_id to which we can create sticker set via bot

https://core.telegram.org/bots/api#createnewstickerset by using this api

**Comment by levlam** [comment]
The bot must know on behalf of which user it wants to create a sticker set.

**Comment by levlam** [comment]
Your question is like "How do we get chat_id to which we can send a message via bot by using https://core.telegram.org/bots/api#sendmessage?" And the answer would be "Use chat_id of the chat to which you want to send the message."

**Comment by sachinTechugo** [comment]
my requirement is to send stickers from my ios native app to telegram app 
so i will use createNewStickerSet api but for that user id is required 
but if i use that bot id it will showing error 
so how can i achieve this can you explain in brief?

**Comment by levlam** [comment]
You don't need to create a sticker set to send a sticker. Any webp file inscribed in 512x512 square is shown as a sticker.

**Comment by serbadima** [comment]
6677be47862043e
