### ISSUE TITLE
How to close the log for libtd?

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#138]
When I use a precompiled Library the libtd：[https://core.telegram.org/tdlib](https://core.telegram.org/tdlib)
How to close the output log in logcat？

**Comment by arseny30** [comment]
You should set log verbosity level to zero.
```
#include <td/telegram/Log.h>
//...
td::Log::set_verbosity_level(0);
```

**Comment by levlam** [comment]
Or Client.setLogVerbosityLevel(0) in the prebuilt library for Android.

**Comment by isopen** [comment]
You can write your function in the source code of tdlib and compile it. Then use in your code.

**Comment by liaoyu1992** [comment]
thank you.
