### ISSUE TITLE
Failed to add multiple contacts via ImportContact method

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1381]
Hi everyone
I tried to iterate over csv of my phone contacts (500 to 1000) and generate this struct:

importContactsReq := client.ImportContactsRequest{
		Contacts: contactsToBeImported,
}
but when I call tdlibClient.ImportContacts(importContactsReq) method, I receive this error:

error: 429 Too Many Requests: retry after 3600
Although I haven't sent many requests to telegram server, I got this error!
At first I tried inserting 500 contacts and received the error, then I tried to add 100 contacts on another account and got that error again!
There isn't any way to insert batch of contacts (0 to 1000) in a single request?
because when I call the tdlibClient.ImportContacts method on every phone number that I have in my contact list, very soon I will get blocked :( even If i put a 1 minute delay between my requests :'(
Is there anyway to do this without these strange limits!? or your TDLib client can't add contacts just the way as Telegram client on mobile do (I have 1000 contacts on my phone and when I create new account and tick the "Sync Contacts" checkbox, It'll be done in a few seconds!)?

I should say that when I created the app Id and api hash_id on my telegram panel, I set the mode on "Desktop" one, can this cause this type of very tight limits?

**Comment by levlam** [comment]
This method has very tight limits. There is no way to avoid the limits. If you reached them, then this is intended behavior.

**Comment by telexengineering** [comment]
I know that the limits are so tight but I don't know how to import my contacts by one request like a human 😆

**Comment by levlam** [comment]
You can't avoid the limits. If you receive the error, then it is impossible to import your contacts.

**Comment by telexengineering** [comment]
How does telegram syncs contacts with its own servers at the first time when an account is created?
Is the ImportContacts method is called with all of clients contacts or TDLib is not something that is being used in Telegram Clients?
Shall I test MTProto clients?

**Comment by levlam** [comment]
They call ImportContacts. But I can repeat again that if it doesn't work for you, it is a feature.

**Comment by yoking1341** [comment]
@levlam can tdlib be used to verified if a phone number register on instagram?
