### ISSUE TITLE
Notifications not being received on android or ios

### ISSUE THREAD

**Issue by vidit-bhatia** [tdlib/td#1382]
I have setup the apns certificate for the app as well as the FCM key .

The register-device is working fine and I am getting the push receiver id as well.

If I try to send a notification on my device using the FCM key id and the certificate uploaded on my telegram I get notifications in my device. 

But I am not getting any notifications from telegram messages. neither from apns nor from FCM any help will be highly appreciated 

One more info I am using the dev server. Not sure if this must be an issue.

for ios I am passing is_app_sandbox: false

**Comment by levlam** [comment]
> I have setup the apns certificate for the app as well as the FCM key .

So you are using two different api_id for Android and iOS?

> One more info I am using the dev server. Not sure if this must be an issue.

Push notifications are better to be tested in production DC.

**Comment by vidit-bhatia** [comment]
ok I will try in production DC . No I am using the same api_id for android and ios seems to work fine

**Comment by levlam** [comment]
Do you still have problem with push notifications receiving?
