### ISSUE TITLE
update tdweb/types

### ISSUE THREAD

**Issue by zeinali0** [tdlib/td#1383]
Can you please update @types/tdweb? it's version 1.4.1

**Comment by dima279** [comment]
get_updates

**Comment by dima279** [comment]
> get_updates

**Comment by levlam** [comment]
We don't have official typings for tdweb.

> These definitions were written by Alexander Krisko.

You can try to find him and ask him for update.

**Comment by dima279** [comment]
Извини ты кот ты хорошо видиш,а я нет))

Отправлено с iPhone

25 янв. 2021 г., в 13:44, Aliaksei Levin <notifications@github.com> написал(а):

﻿

We don't have official typings for tdweb.

These definitions were written by Alexander Krisko.

You can try to find him and ask him for update.
