### ISSUE TITLE
"Message can't be edited" 

### ISSUE THREAD

**Issue by zyadomer999** [tdlib/td#1384]
Hello
When I try to edit a message sent by a user or bot, I face this { _: 'error', code: 5, message: "Message can't be edited" }.

This is my code, is there anything wrong with my code?
<img width="637" alt="Screen Shot 2021-01-25 at 8 52 01 PM" src="https://user-images.githubusercontent.com/66646536/105745302-2f90b580-5f4f-11eb-892c-8403dce97dde.png">

**Comment by levlam** [comment]
You are trying to edit a message, which can't be edited by the current user. You can use `message.can_be_edited` field to check whether a message can be edited.

**Comment by zyadomer999** [comment]
So how can I make a message editable? I used the telegram-bot-api with telegraf and there almost every message could be edited. What should I do?

**Comment by levlam** [comment]
You can't make a message editable. You can edit a message or you can't.

> there almost every message could be edited.

Most messages are incoming private/group messages and they can't be edited.

See also https://core.telegram.org/bots/api#updating-messages for the most common reason, why an outgoing message can't be edited.

**Comment by zyadomer999** [comment]
But I do not think so that " almost every message could be edited", at least for me. I tried almost every tyoe of message from both the user and bot and all of then return "can_be_edited: false".
What can be the problem?

**Comment by jumoog** [comment]
Your sending_state is `messageSendingStatePending`
Once your message is finished you get a new ID from the Server.
https://github.com/tdlib/td/issues/700

**Comment by zyadomer999** [comment]
Thank you very much
