### ISSUE TITLE
Default video resolution

### ISSUE THREAD

**Issue by zyadomer999** [tdlib/td#1385]
Is there anyway to tell the telegram to upload a video with its original resolution?
<img width="913" alt="Screen Shot 2021-01-26 at 1 34 20 PM" src="https://user-images.githubusercontent.com/66646536/105834178-37963700-5fdb-11eb-8783-60abf8e7df1c.png">

When I use this code to send  a video, the video quality on telegram is so low and awkward.

**Comment by jumoog** [comment]
If you do not want the quality of the video to change, you must send the video as a document.

**Comment by levlam** [comment]
Videos aren't comressed server-side for now. If you are using `inputMessageVideo` then the file is sent in the exactly original form.

Are you using the latest TDLib version?

**Comment by zyadomer999** [comment]
But what If I want to send it as a video and specify the width and video but still low resolution?

**Comment by jumoog** [comment]
When I send a video I never specify the resolution and on the client side the video is displayed as in the original. Do you use mp4?

**Comment by zevlg** [comment]
Probably related to https://github.com/tdlib/td/issues/1379

**Comment by levlam** [comment]
@zevlg Animations sent via `inputMessageAnimation` are compressed by the server, but videos sent via `inputMessageVideo` are never altered. This shouldn't be related.

**Comment by levlam** [comment]
@zyadomer999 Which TDLib version are you using?

**Comment by zyadomer999** [comment]
Dears, the problem was due to I used a format different from MP4, thank you for your help.
But could you please tell me what type and codec the video should exactly be for the telegram to create automatic thumbnail and support streaming?

**Comment by levlam** [comment]
Thumbnails are generated only for videos less than 10 megabytes. Most codecs, which can be found on mobile devices, are supported.

Streaming support is not about codec, it is about data layout within the file. Video channel must be intermixed with audio channel for better streaming and moov atom must be at the beginning or at the end of the file.

**Comment by zevlg** [comment]
> Thumbnails are generated only for videos less than 10 megabytes. Most codecs, which can be found on mobile devices, are supported.
> 
> Streaming support is not about codec, it is about data layout within the file. Video channel must be intermixed with audio channel for better streaming and moov atom must be at the beginning or at the end of the file.

For my info, does Telegram server supports fragmented mp4 with moof atoms(instead of moov at the beginning), so data can be streamed before video capturing is finished?

**Comment by levlam** [comment]
@zevlg Streaming is entirely a client-side feature. Cideo can't be sent in a message until it is fully uploaded. Some clients can support streaming of moof videos.

**Comment by zyadomer999** [comment]
Dear with the streaming I meant that some videos can be played without downloading them while other you have to download the entire video before you can play it. Is there any relation between the type of the video and this feature?

**Comment by levlam** [comment]
And I answered that
> Streaming support is not about codec, it is about data layout within the file. Video channel must be intermixed with audio channel for better streaming and moov atom must be at the beginning or at the end of the file.

So this is about the way video data is placed in the container.

Apps also use `video,supports_streaming` flag set by video sender as a hint, whether video needs to be tried to play without full downloading.

**Comment by zyadomer999** [comment]
Thanks I got your point
