### ISSUE TITLE
Old_Message_Id use

### ISSUE THREAD

**Issue by zyadomer999** [tdlib/td#1386]
Is there any method that uses old_message_id? 
I want to use the old_message_id to get the new message id of a message after sending_pending state?

**Comment by levlam** [comment]
You must wait for message to be sent and handle `updateMessageSendSucceeded`/`updateMessageSendFailed`/`updateDeleteMessages` to find permanent message ID or that message send failed.

**Comment by zyadomer999** [comment]
So you mean tgere is no way to use old message id?

**Comment by jumoog** [comment]
Yes

**Comment by zyadomer999** [comment]
Thanks
