### ISSUE TITLE
[WinError 127] The specified procedure could not be found.

### ISSUE THREAD

**Issue by Thoufak** [tdlib/td#1387]
Hi. I'm having trouble with using the TDLib on my Windows machine. I followed [the steps to build the lib](https://tdlib.github.io/td/build.html?language=Python). Then, I copied all the .dll and .lib files I could find in the td/tdlib/ folder to my script's folder (see the screenshot attached). I then tried using a [python wrapper for TDLib](https://github.com/alexander-akhmetov/python-telegram), but got an error:
```
Traceback (most recent call last):
  File "src\main.py", line 84, in <module>
    main()
  File "src\main.py", line 63, in main
    set_username=config.set_username,
  File "C:\Users\Administrator\Desktop\TDLib_tests\src\launcher.py", line 57, in __init__
    self._tdlib_client = self._make_tdlib_client()
  File "C:\Users\Administrator\Desktop\TDLib_tests\src\launcher.py", line 181, in _make_tdlib_client
    registration_last_name=generate_username(),
  File "C:\Users\Administrator\Desktop\TDLib_tests\src\tdlib\client.py", line 140, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity, logs_file=logs_file)
  File "C:\Users\Administrator\Desktop\TDLib_tests\src\tdlib\tdjson.py", line 30, in __init__
    self._build_client(library_path, verbosity, logs_file=logs_file)
  File "C:\Users\Administrator\Desktop\TDLib_tests\src\tdlib\tdjson.py", line 40, in _build_client
    self._tdjson = CDLL(library_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] Не найдена указанная процедура
```

Please also note a few points:
1. I made it work on my Mac OS machine, but not on Windows (Windows Server 2016, to be precise).
2. I specified the full path to the tdjson.dll.
3. I built the binaries on the same machine which I'm trying to use them on.
4. Find the build-logs attached.

![image](https://user-images.githubusercontent.com/40132582/105872464-80fe7a80-600b-11eb-919a-f476ce1ec07f.png)
[TDLib build.txt](https://github.com/tdlib/td/files/5874601/TDLib.build.txt)

**Comment by levlam** [comment]
Everything is correct, it should work.

Could you print and show `library_path`?

**Comment by Thoufak** [comment]
Yes. In fact, I even hardcoded it, so that I'm sure it's correct.

![Screenshot 2021-01-26 at 21 45 57](https://user-images.githubusercontent.com/40132582/105890315-418e5900-6020-11eb-9af7-723c92354538.png)
![Screenshot 2021-01-26 at 21 47 00](https://user-images.githubusercontent.com/40132582/105890318-43581c80-6020-11eb-97e6-906c71e8287f.png)

**Comment by levlam** [comment]
You have built x64 library. Are you using 64-bit Python?

**Comment by Thoufak** [comment]
This is what my python says. I guess this means it's 64-bit?

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('64bit', 'WindowsPE')
```

**Comment by levlam** [comment]
`python -c "import ctypes; print(8 * ctypes.sizeof(ctypes.c_voidp))"` should be more reliable, But nevertheless Python seems to be 64-bit.

Could you try to use relative path "tdjson.dll"? For me both absolute and relative path work, but this needs to be tried.

If this doesn't work, you can use dependency walker to try to find a missing dependency of tdjson.dll, but all of them seems to be present.

**Comment by Thoufak** [comment]
> python -c "import ctypes; print(8 * ctypes.sizeof(ctypes.c_voidp))"
This outputs 64.

Using relative path to tdjson.dll throws the same error.

Also I tried using the Dependency Walker, but I'm not sure how to make sense of its output. Could you help? See the screenshot attached.

![image](https://user-images.githubusercontent.com/40132582/105963534-28be8b80-6092-11eb-824f-e015069640ca.png)

**Comment by jumoog** [comment]
it looks like it can't find some dlls.. have you installed Visual C++ Redistributable Packages for Visual Studio? https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Thoufak** [comment]
When Itried running this exe, I got an alert saying it's already installed. Anyway, I uninstalled it and then installed again. The error in my script is still the same, though.
