### ISSUE TITLE
System.BadImageFormatException:“Could not load file or assembly 'Telegram.Td, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 

### ISSUE THREAD

**Issue by forconz** [tdlib/td#1388]
https://tdlib.github.io/td/build.html?language=C%23
C#
Windows （.NET Core)
Build the debug binary
PowerShell
64
![20210128113959](https://user-images.githubusercontent.com/9990289/106086727-b4511e80-615d-11eb-8d6a-c64d4b4c1400.png)

I build project

System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'Telegram.Td, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 
  Source=Puppet
  StackTrace:
   at Puppet.Program.<>c__DisplayClass0_0.<Main>b__1(HostBuilderContext context, IServiceCollection services) in D:\Projects\dev\Puppet\Puppet\Puppet\Program.cs:line 163
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Puppet.Program.Main(String[] args) in D:\Projects\dev\Puppet\Puppet\Puppet\Program.cs:line 75

**Comment by forconz** [comment]
https://tdlib.github.io/td/build.html?language=C%23
C#
Windows （.NET Core)
Build the debug binary
PowerShell
32

I using the 32-bit version

System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'Telegram.Td, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 
  Source=Puppet
  StackTrace:
   在 Puppet.Program.<>c__DisplayClass0_0.<Main>b__1(HostBuilderContext context, IServiceCollection services)  D:\Projects\dev\Puppet\Puppet\Puppet\Program.cs 163 line
   在 Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   在 Microsoft.Extensions.Hosting.HostBuilder.Build()
   在 Puppet.Program.Main(String[] args) 在 D:\Projects\dev\Puppet\Puppet\Puppet\Program.cs 中: 第 75 行

**Comment by levlam** [comment]
This error usually means that library was built for a wrong architecture. Your binary is built for Debug, but x64 instead of x32. It can be used in x64 Debug build.

**Comment by forconz** [comment]
do the tdlib support .net 5.0?

**Comment by levlam** [comment]
Yes.

**Comment by forconz** [comment]
I build tdlib for 32-bit/x86 architecture, or 64-bit/x86, System.BadImageFormatException throwed, the exceptions are same.

**Comment by forconz** [comment]
<ItemGroup>
    <Content Include="build64\Debug\Telegram.Td.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

I use in x64 and .net 5.0, but it is not builded well.

but I use the same dll in x64 and .net framework 6.1, It work well.

**Comment by pingu2k4** [comment]
Also getting the same issue here.

**Comment by levlam** [comment]
@forconz @pingu2k4 Do you have the same issue as in https://github.com/tdlib/td/issues/1508#issuecomment-826498519?
