### ISSUE TITLE
How can I match the responses and requests when using td JSON?

### ISSUE THREAD

**Issue by Trumeet** [tdlib/td#1389]
Hi, I'm using td JSON for one of my C projects. I found it is useful and simple to use send and receive functions to interact with tdlib, but quickly I came up with a question: How can I match the responses and requests? I found there is no request ID like parameters in the JSON, which made it impossible to know which response is related to which request. For example, if I call sendMessage twice, I could not know which Message is the response of the first request, and which is the second. What is the solution here? If this feature is not yet available, could you add something like request ID in the JSON request? Thanks.

**Comment by levlam** [comment]
https://github.com/tdlib/td/blob/312e3b740afbc9dbc8b8a539d4fb0d510b614779/td/telegram/td_json_client.h#L21

**Comment by Trumeet** [comment]
> https://github.com/tdlib/td/blob/312e3b740afbc9dbc8b8a539d4fb0d510b614779/td/telegram/td_json_client.h#L21-L22

Thanks! I never noticed that.
