### ISSUE TITLE
string received instead of int

### ISSUE THREAD

**Issue by aCLr** [tdlib/td#1390]
Greetings.
Today I upgraded tdlib from 1.6.0 to 1.7.0.

Now I receive string instead of int in `value` field:
```
{"@type":"updateOption","name":"unix_time","value":{"@type":"optionValueInteger","value":"1612006226"}}
```

Is it correct?

**Comment by levlam** [comment]
Yes. In 1.7.0 type of the field `value` in the class `optionValueInteger` was changed from `int32` to `int64`, which is encoded as string in JSON interface to never loss precision. You can find full list of changes in https://github.com/tdlib/td/blob/master/CHANGELOG.md.

**Comment by aCLr** [comment]
Oh, missed that change. 
Do all the values of int64 within tdjson encoded as strings?

**Comment by aCLr** [comment]
And what about requests? For example getChats.offset_order. Should I encode any int64-parameter as string in my requests?

**Comment by levlam** [comment]
> Do all the values of int64 within tdjson encoded as strings?

Yes, otherwise most parsers save it to double with precision loss.

> Should I encode any int64-parameter as string in my requests?

TDLib is able to parse int64 as number without loss of precision, but it is unlikely that you can store it without loss of precision. Passing int64 as string is the safest way.

**Comment by aCLr** [comment]
> Yes, otherwise most parsers save it to double with precision loss.
Looks like it is not. For example, Chat.id is the real int64. I can assume that all `id` fields are numbers.

Is there any other exception?

**Comment by levlam** [comment]
Chat.id is int53: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat.html#ae1eaecac992cac27502334d1cc8bfd8a. int53 can be stored as Number in JSON.

**Comment by aCLr** [comment]
I see. Ok, thank you for answers.
