### ISSUE TITLE
Static link with C program = lots of undefined references

### ISSUE THREAD

**Issue by MLXProjects** [tdlib/td#1391]
Hi, I'm trying to get started with TDLib and have a simple test program: 

    #include <stdlib.h>
    #include <stdio.h>
    #include <td/telegram/td_json_client.h>
    #include <td/telegram/td_log.h>
    int main(){
        printf("starting tdclient\n");
        void *client = td_json_client_create();
        const double WAIT_TIMEOUT = 10.0;
        int is_closed = 0;
        while (!is_closed) {
            const char *result = td_json_client_receive(client, WAIT_TIMEOUT);
            if (result) {
                printf("result obtained\n");
            }
        }
        td_json_client_destroy(client);
        return 0;
    }

and I try to build it with this command: 

    arm-linux-gnueabihf-g++ main.c -o test -static \
    -I/home/mlx/projects/tdlib_arm/include \
    -L /home/mlx/projects/tdlib_arm/lib \
    -L /home/mlx/projects/ssllib/lib \
    -L /home/mlx/projects/zlib/lib \
    -ltdutils -ltdactor -ltdnet -ltdsqlite -ltddb -ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdapi
but it fails with A LOT of undefined references. 
I've tried with the library order used [here](https://github.com/Arman92/go-tdlib/blob/master/tdlib.go), but the same issue. 
Issue #408 refers to a very similar problem, but there was no exact solution as the user finished using the shared library. 
I need to statically link this as it's for an embedded system. 
If a log of all the undefined errors is needed, please tell me and I'll upload it! (they're actually a lot, really).

**Comment by levlam** [comment]
The library linking order is VERY important. Your order make no sense and the order in https://github.com/Arman92/go-tdlib/blob/master/tdlib.go is correct and should work. Use it and then send a few left undefined symbols.

**Comment by MLXProjects** [comment]
Used the linking order from that link and the same issue persists, here are a few of the undefined references: 

    undefined reference to `operator delete(void*, unsigned int)'
    undefined reference to `__atomic_fetch_add_8'
    undefined reference to `__atomic_load_8'
    undefined reference to `pthread_mutex_lock'
    undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned int&, unsigned int)'
    undefined reference to `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned int, unsigned int, unsigned int) const'

Currently I'm using GCC 4.7 (the target I use needs such an old compiler), but tried building with musl 6.3 and there are other issues: 

    undefined reference to `fcntl64'
    undefined reference to `getcontext'
    undefined reference to `setcontext'
    undefined reference to `makecontext'

**Comment by levlam** [comment]
You can't build TDLib with GCC 4.7. The build should fail long before linking.

**Comment by MLXProjects** [comment]
Okay, compiled TDLib in a Alpine ARM chroot (using musl gcc10) and it worked. 
Anyway, tdlib cross-compiling is really broken, really would like being able to compile it without a qemu-powered chroot  but that's what we have now. I'll close this, as (in my case) it was my compiler and libraries fault.

**Comment by MLXProjects** [comment]
Note for future guys like me who are doing this, for some reason -ltdapi is missing in the link above. Added it and works :D

**Comment by levlam** [comment]
@MLXProjects Separate `tdapi` static library didn't exist back then.
