### ISSUE TITLE
Link to a message on iOS

### ISSUE THREAD

**Issue by Michael-Kr** [tdlib/td#1392]
Is there a way to force 'getMessageLink' to return 'tg://' link and not 'https://'?

**Comment by levlam** [comment]
No, internal links are never returned by this method.

**Comment by zevlg** [comment]
It could be converted to tg:// representation, like in https://github.com/zevlg/telega.el/blob/2c9fb8914902b3cce623447b68fe20c8ea27c324/telega-tme.el#L276

**Comment by Michael-Kr** [comment]
Lisp is hard to read 😅   Fortunately, I only care about _privatepost_ and _resolve_
Thank you!
