### ISSUE TITLE
searchChatMembers different results for same query

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1393]
I've noticed different `searchChatMembers` results for the same search query if using different chat members filter.

Chat has a user with name "Вова" and no username set, here is what I got:
```
[ 3][t 4][1612082248.796341896][Td.cpp:3352][#1][!Td][&td_requests]	Receive request 2503: searchChatMembers {
  chat_id = -1001147249123
  query = "vo"
  limit = 50
  filter = null
}
...
[ 3][t 4][1612082248.878133058][Td.cpp:4513][#1][!Td][&td_requests]	Sending result for request 2503: chatMembers {
  total_count = 1
  members = vector[1] {
    chatMember {
      user_id = 597208700
      inviter_user_id = 0
      joined_chat_date = 1547317421
      status = chatMemberStatusMember {
      }
      bot_info = null
    }
  }
}
```

Now I'm applying `chatMembersFilterMention`, using same search query:
```
[ 3][t 4][1612082259.150395393][Td.cpp:3352][#1][!Td][&td_requests]	Receive request 2509: searchChatMembers {
  chat_id = -1001147249123
  query = "vo"
  limit = 50
  filter = chatMembersFilterMention {
    message_thread_id = 0
  }
}
...
[ 3][t 4][1612082259.222798347][Td.cpp:4513][#1][!Td][&td_requests]	Sending result for request 2509: chatMembers {
  total_count = 0
  members = vector[0] {
  }
}
```

This was unexpected, I thought same user (as for no-filter call) should be returned.  Also, if I change "vo" to "во", then same user returns correctly.

I'm using this method to complete mentions in  the chat, I would like to use `chatMembersFilterMention` members filter, so it will take into account current messages thread.   Could `searchChatMembers` return same users for same query if those users can be mentioned in the given messages thread?

Thanks

**Comment by levlam** [comment]
Could you still reproduce this?

**Comment by zevlg** [comment]
Yes, still reproduciable (TDLib 1.7.1):
```
1612113519: OUTPUT: send 150 (:@type "searchChatMembers" :chat_id -1001147249123 :query "vo" :limit 50 :filter (:@type "chatMembersFilterMention" :message_thread_id 0) :@extra 39)
1612113519: event IN: (:@type "chatMembers" :total_count 0 :members [] :@extra 39)
...

1612113541: OUTPUT: send 85 (:@type "searchChatMembers" :chat_id -1001147249123 :query "vo" :limit 50 :@extra 40)
1612113541: event IN: (:@type "chatMembers" :total_count 1 :members [(:@type "chatMember" :user_id 597208700 :inviter_user_id 0 :joined_chat_date 1547317421 :status (:@type "chatMemberStatusMember"))] :@extra 40)
```

**Comment by levlam** [comment]
Both requests are sent to the server with minimal changes. Could you send TDLib log to @tdlib_bot, so I can find server-side requests and their responses?

**Comment by levlam** [comment]
This looks like a cache issue, which should already be fixed by itself.

Generally, filter `chatMemberStatusMember` can return more users then `chatMembersFilterMention` only when the user is your contact and is found only by name you gave to the contact. But this unlikely was a case there.

**Comment by zevlg** [comment]
> This looks like a cache issue, which should already be fixed by itself.
> 
> Generally, filter `chatMemberStatusMember` can return more users then `chatMembersFilterMention` only when the user is your contact and is found only by name you gave to the contact. But this unlikely was a case there.

It probably was that case actually!  He is in my contacts and I don't remember how I've created that contact, probably given name by myself.

I'll stick to `chatMemberStatusMember` in small private groups and to `chatMembersFilterMention` in large public groups

Thanks
