### ISSUE TITLE
Error: Receive is called after Client destroy, or simultaneously from different threads

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlib/td#1394]
I want to create a multi-threaded system that uses TDLib.
I wrote a Runnable class where I create a tdlib client and set an updates handler.
Each thread has its own TelegramClient and its own updates handler. Each class manages its own telegram account.

If I run only 1 thread, all works good, but if I run 2 or more threads, I got this error after the second TelegramClient was created:

`[ 0][t 0][1612181768.710582017][Client.cpp:279] Receive is called after Client destroy, or simultaneously from different threads`

I should use 1 global updates handler for all clients?

**Comment by CaliforniaMountainSnake** [comment]
I am quite sure this issue is tied with this one: https://github.com/tdlib/td/issues/1242

**Comment by levlam** [comment]
You can't receive this error if you called `td_json_client_receive` for different TDLib instances.

You can find description of JSON interface in  https://github.com/tdlib/td/blob/312e3b740afbc9dbc8b8a539d4fb0d510b614779/td/telegram/td_json_client.h#L24 and description of new JSON interface in https://github.com/tdlib/td/blob/312e3b740afbc9dbc8b8a539d4fb0d510b614779/td/telegram/td_json_client.h#L105.

If you are using new interface, then all updates are received by the same thread and needs to be dispatched by it.

**Comment by comerc** [comment]
My hack of tdlib.go for DestroyInstance()

**Comment by comerc** [comment]
My hack of tdlib.go for DestroyInstance()
```go
var IsClosed = false

func NewClient(config Config) *Client {
  // ...
	go func() {
		for !IsClosed {
      // ...
    }
  }()
  // ...
}
```

**Comment by comerc** [comment]
My hack of tdlib.go for DestroyInstance()

```go
var IsClosed = false

func NewClient(config Config) *Client {
  // ...
	go func() {
		for !IsClosed {
      // ...
    }
  }()
  // ...
}
```

usage:

```go
  tdlib.IsClosed = true
  time.Sleep(1 * time.Second)
  client.DestroyInstance()
```
