### ISSUE TITLE
viewMessages and secret chat do not work

### ISSUE THREAD

**Issue by ionwerz** [tdlib/td#1395]
I'm trying to get marked messages as read in a secret chat:
`{"@type":"viewMessages","chat_id":-1998211077445,"force_read":1,"message_thread_id":0}
{"@type":"ok"}
`
But messages do not turn marked as read. 
I used to try `openChat` and then `viewMessages`, but no result. What I do wrong?

**Comment by levlam** [comment]
You didn't specified identifiers of messages, which was viewed.

**Comment by ionwerz** [comment]
What Function I have to use so be able to get identifiers of all messages in the chat?

**Comment by levlam** [comment]
If you want to read all messages, you can pass identifier of the `chat.last_message` message.
