### ISSUE TITLE
Why is my pc too slow with tdlib?

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1397]
Hello,

My macbook pro is too slow when using the tdlib library with nodejs. It is slow to a degree that I have to wait about 10 seconds for vscode to show me the suggestions and while I am coding, my pc processors work loudly.
There might be problems with the vscode because when I run my project, it is so smooth and everything works perfectly.
 I am really frustrated, please someone help me:

These are features of my macbook:
<img width="575" alt="Screen Shot 2021-02-02 at 11 26 42 PM" src="https://user-images.githubusercontent.com/78375592/106658255-1c649200-65ae-11eb-8974-80c2e71ae29f.png">

As you can see in this image, the idl is too slow in showing the suggestions
<img width="1440" alt="Screen Shot 2021-02-02 at 11 27 14 PM" src="https://user-images.githubusercontent.com/78375592/106658325-31412580-65ae-11eb-9a9a-f4844831c506.png">

**Comment by levlam** [comment]
I don't think this can be related to TDLib.

**Comment by zyadomer98** [comment]
But it is not like that for other projects and as you can see my pc ability is good enough to go with that smoothly. 
What can be wrong, in your opinion?

**Comment by levlam** [comment]
You can try to report this to vscode. Nothing can be done by TDLib.

**Comment by zyadomer98** [comment]
Okay Thanks
