### ISSUE TITLE
deleteChatHistory / updateDeleteMessages

### ISSUE THREAD

**Issue by hossein-zare** [tdlib/td#1398]
Hello,
I want to use `deleteChatHistory` to delete a chat history, When another client _(which is connected to the same account)_ gets online must receive an update for the called method by another client, But i can't find any **Update** in the https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_update.html other than `updateDeleteMessages`, I didn't see anything like `updateDeleteChatHistory`.

Will the second client receive the `updateDeleteMessages` when the `deleteChatHistory` method has been called previously?

**Comment by levlam** [comment]
Yes. When `deleteChatHistory` is used, all messages are deleted independently. Other (and this) client receive `updateDeleteMessages` update(s).
