### ISSUE TITLE
File Name of the remote file or local file.

### ISSUE THREAD

**Issue by Dhina17** [tdlib/td#1399]
Is there any way to get the filename before the file download completion? path of the local file can be retrieved only after download completion
or anyother way to get the file name using remote file id or local file id?

**Comment by levlam** [comment]
Path of partially downloaded file is available as soon as download begins. Check https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1local_file.html.

**Comment by Dhina17** [comment]
Sorry I haven't checked this clearly. Thanks

**Comment by Dhina17** [comment]
@levlam temp path is only available. and also the file name is not correct. it shows the file name as one number(1,2,3 like this). I need the filename . Is there any way to get that?

**Comment by levlam** [comment]
You don't need to download a file to know its original name. Moreover name of downloaded file can be very different from that name. Original name is available in message content properties if known, foк example, see https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1document.html#a8256a02421f888a2a69fab487a1670b4.

**Comment by Dhina17** [comment]
Thanks again.
