### ISSUE TITLE
how to leave from group/channel?

### ISSUE THREAD

**Issue by Behnam-Emamian** [tdlib/td#140]
Hi Guys

I have found an API for leaving from group/channel.
telegram_api::channels_leaveChannel

but this api implemented in telegram_api namespace and I cannot call it by client_->send because send method just accept the td_api namespace commannd.

```
auto input_channel = get_input_channel(Supergroup->supergroup_id_);
auto send_message = td::telegram_api::make_object<td::telegram_api::channels_leaveChannel>(std::move(input_channel));

send_query(std::move(send_message), 
	[this](Object object) {
		int x=0;
	});
```

Is there any advice? how can I send a command from telegram_api namespace.

Best regards
Ben

**Comment by levlam** [comment]
You can't use telegram_api directly. It isn't a part of a TDLib public interface.
You should use TDLib method instead. Namely, td_api::setChatMemberStatus should be used to manage member statuses.

**Comment by Behnam-Emamian** [comment]
Thanks a lot, it is working

sample code:

```
td::tl_object_ptr<td::td_api::ChatMemberStatus> MemberLeftStatus = td::make_tl_object<td::td_api::chatMemberStatusLeft>();
send_query(td::td_api::make_object<td::td_api::setChatMemberStatus>(chat_->id_, XXXXXXX, std::move(MemberLeftStatus)),
	[this](Object object) {
		if (object->get_id() == td::td_api::error::ID)
						return;
	});
```

**Comment by levlam** [comment]
Since TDLib 1.3.0 you can alternatively use `leaveChat` instead of `setChatMemberStatus` for that.

**Comment by pabx06** [comment]
latest tdlibjson
have use tdlib sucessfully until i try joinChat and leaveChat:

[ClientJson.cpp:76][&status.is_error()]	Failed to parse [request:{\0042@type\0042:\0042leaveChat\0042,\0042chat_id\0042:-100XXXXXXXXX}] [Error : 0 : Unknown class]

**Comment by levlam** [comment]
@pabx06 The error means, that method `leaveChat` is not found. Are you sure that it is a TDLib 1.3.0? You can check TDLib version via `getOption("version")`.

**Comment by pabx06** [comment]
My bad i was using 1.2. Tried 1.3 it works

**Comment by jnxyatmjx** [comment]
> Since TDLib 1.3.0 you can alternatively use `leaveChat` instead of `setChatMemberStatus` for that.

why i get **call setTdlibParameters first** error when call leaveChat use TDlib 1.8.23

**Comment by levlam** [comment]
Because you didn't call `setTdlibParameters` with correct parameters. The method was changed some time ago and now it receives all parameters directly.

**Comment by jnxyatmjx** [comment]
> Because you didn't call `setTdlibParameters` with correct parameters. The method was changed some time ago and now it receives all parameters directly.

thanks, i solve the 400 error. beacause I call leaveChat before setTdlibParameters

**Comment by jnxyatmjx** [comment]
a other question please. 
when I call **leaveChat** (with a public channel id) multiple times, every response is 'ok'. 
But I did't Leave the channel , is this method real work or configuration error of me.

**Comment by levlam** [comment]
@jnxyatmjx There is nothing wrong with receiving of new messages from a public channel.

**Comment by jnxyatmjx** [comment]
> @jnxyatmjx There is nothing wrong with receiving of new messages from a public channel.
even i never join or have leaved the channel?

**Comment by levlam** [comment]
Yes.
