### ISSUE TITLE
How to send a user to a telegram profile?

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1400]
Is there anyway to make an inline keyboard button that sends the user to the telegram profile of a user, a channel or a group?

**Comment by levlam** [comment]
You can use t.me/username link if the user or the chat has username. Otherwise, no.

**Comment by zyadomer98** [comment]
Thanks, but with which method I can do that?

**Comment by levlam** [comment]
Use `inlineKeyboardButtonTypeUrl` with "https://t.me/username" URL.

**Comment by zyadomer98** [comment]
I have never seen anyone on github to be responsive and diligent as much as you are. Thank you very much dear levlam

**Comment by zyadomer98** [comment]
Dear, it is not a method, it is an object. In which of the methods I can find that object?
