### ISSUE TITLE
Report options: Admin / Non-Admin

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1401]
Hi,

according to tdlib docs, reportSupergroupSpam can only be used by admins of a supergroup. However, on desktop clients I can do:

- If I am admin, delete a message and choose to report spam, delete all messages, block user OR choose report spam
- If I am not an admin, only report spam

What are the underlying tdlib calls for that? I found reportSupergroupSpam, deleteChatMessagesFromUser. How can I ban users actually?

Also, can users report spam with reportSupergroupSpam in contrast to whats in the docs?

**Comment by levlam** [comment]
The documentation is correct.
If you want to report a specific user and some of their messages, then you must be an administrator in the supergroup. You can use `reportSupergroupSpam` for that.
Ordinary users can report only the whole chat and can attach some messages to their report. They can use `reportChat` for that. In fact, it is misleading to show report option on specific messages for them and this UI can be improved in the future.

> How can I ban users actually?

Any changes to chat member statuses are donw via `setChatMemberStatus`.

**Comment by Flohack74** [comment]
Ok got it, so thats actually reporting the whole chat? (Nachricht melden = Report message)
![grafik](https://user-images.githubusercontent.com/16186470/107043470-5c509280-67c3-11eb-9b2b-5f1c4e5d3671.png)

**Comment by Flohack74** [comment]
Ah ok but reportChat allows to add message IDs, I did not see this in my first read. I think question is answered :)
