### ISSUE TITLE
How to stop listening for updates, e.g. from updateNewMessage?

### ISSUE THREAD

**Issue by nikolaygit** [tdlib/td#1402]
After the client has started listening for new messages using [updateNewMessage](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_new_message.html) how can the client stop listening for them? While still remaining authorized and being able to call other API methods.

_Note_: looking for a solution that stops the updates on the network level (not on the software level with if statements)

**Comment by levlam** [comment]
There is no way to do that. It is impossible to send messages and do a lot of other things without processing updates. If you don't need some updates, you can just ignore them.

**Comment by nikolaygit** [comment]
thanks!

**Comment by rsibweza** [comment]
am struggling to access the updates messages please help me to get the message for me to process the items being received.
