### ISSUE TITLE
Please tag the 1.7.1 release

### ISSUE THREAD

**Issue by D4N** [tdlib/td#1403]
Version 1.7.1 appears to have been released with 312e3b740afbc9dbc8b8a539d4fb0d510b614779, but no tag has been made. Could you please add a tag for that commit so that all kinds of automations can kick in?

**Comment by levlam** [comment]
1.7.1 is a rolling version tag of a current development version. In a traditional semver it would be named 1.8.0-alpha1. The exact commit in which version was changed to 1.7.1 is not recommended for anyone to use. If you want to use the latest version, you need to use TDLib from master, which contains some important improvements.

**Comment by D4N** [comment]
Ah, ok, thanks for clarifying this!
