### ISSUE TITLE
User not found errors while adding contact by Telegram ID via addContact method

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1404]
Hi
I have 2 phone numbers, from one of them , I exported all of my contacts with their telegram IDs.
In my other phone number by which I created a brand-new Telegram account, when I want to iterate over csv of my contact's telegramIDs and add them one by one by their Telegram IDs via addContact method, I get these errors:
```
 3 User not found
 ```
 and some times
 ```
  6 User not found
  ```
  It's weird to me because these telegram IDs are real and I've exported them from my contacts on my other Telegram account.
  What's the meaning of These errors and what should I do?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/578.
