### ISSUE TITLE
Getting chat data

### ISSUE THREAD

**Issue by mark-greg** [tdlib/td#1405]
Hi there. I tried **getChat** with a **user_id** as **chat_id_** but returned nothing, is something wrong?

**Comment by levlam** [comment]
A method can't return "nothing". It always return a response or an error.

You shouldn't mix identifiers of different kind, Despite private chat with a user has the same numerical identifier as the user identifier, they are identifiers of different objects and are not interchangeable. To create a private chat with a given user, you need to use `createPrivateChat` method.
