### ISSUE TITLE
Question: Independent updates and events

### ISSUE THREAD

**Issue by mark-greg** [tdlib/td#1406]
Hi there again.
I have two questions.

1. Are updates/events that happen in a Group/Channel created for each member of the chat?
2. Can those independent updates be fetched by **updates.getDifference** even though they are deleted?

**Comment by levlam** [comment]
1. There are a lot of updates with different behavior.
2. TDLib has no such method as `updates.getDifference`. It is nevertheless not possible to receive something that is definitely deleted already.
