### ISSUE TITLE
Decoding animated stickers in Linux and Qt/QML

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1407]
So I read the docs:

_True, if the sticker is an animated sticker in TGS format._

Whats TGS format? Is there any documentation how to decode this and feed it into a media pipeline in Linux or Qt/QML? Thanks!

**Comment by levlam** [comment]
Use zlib to uncompress data and use https://github.com/TelegramMessenger/rlottie to render the data frame per frame.

**Comment by Flohack74** [comment]
Cool thanks!

**Comment by Flohack74** [comment]
We finally achieved it:
![grafik](https://user-images.githubusercontent.com/16186470/122648366-4798e980-d129-11eb-95aa-82a5930e8f7e.png)
Though the playback is still a bit slower than on the official clients. What we have used:
- https://github.com/TelegramMessenger/rlottie for decoding
- https://gitlab.com/mymike00/rlottie-qml for render support in QML

Kudos to Telegram devs, once more!
