### ISSUE TITLE
new tdjson interface

### ISSUE THREAD

**Issue by aCLr** [tdlib/td#1408]
Hello.

I'm trying to use new tdjson interface (1.7.0) and can't figure out what the first request should be.
Should I send `set_tdlib_parametrs` as the first request? Or is there another better request?

**Comment by jumoog** [comment]
you request the Version
https://github.com/tdlib/td/blob/master/example/cpp/tdjson_example.cpp#L22

**Comment by levlam** [comment]
@aCLr See https://core.telegram.org/tdlib/getting-started.

**Comment by aCLr** [comment]
@jumoog `getOption` version works fine, thank you.
