### ISSUE TITLE
Auto-generating classes: used TL schema in tdlib?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1410]
For our old Telegram client, using our own implementation of the client libs, we had a convenient generator to take a TL schema and generate C++ classes out of it. So now that we use tdlib, we still need to map objects into Qt classes due to the QML property generation etc.

Question, a) is the TL schema accessible on the TL overview page, I think its 121, the current one, and b) where in the tdlib code I can get the used schema of each release?

**Comment by RememberTheAir** [comment]
Telegram's tl schema reference: https://core.telegram.org/api#api-tl-schema-as-json

tdlib's schema files are [here](https://github.com/tdlib/td/tree/master/td/generate/scheme)

**Comment by Flohack74** [comment]
Thanks, that second link is what I was looking for ;)
