### ISSUE TITLE
Building 32bit fails

### ISSUE THREAD

**Issue by pingu2k4** [tdlib/td#1411]
Bulding for 64 bit seems to work fine, but 32bit doesn't put anything in the output directory when running the `cmake --build . --config Debug` command. It runs for a short time (much shorter in comparison to building the 64 bit), and stops after:

  tl_writer_java.cpp
  Generating Code...
  td_generate_java_api.vcxproj -> ...\example\csharp\build\td\generate\Debug\td_generate_java_api.exe
  Building Custom Rule .../td/CMakeLists.txt

**Comment by levlam** [comment]
Could you show whole output from all commands?
