### ISSUE TITLE
How to set make -j when compile

### ISSUE THREAD

**Issue by lmcmceo** [tdlib/td#1413]
In my centos, 2core, 4G memery, When I compile, it has error, I think it need to set make -j 1

[ 33%] Built target tdnet
[ 34%] Building CXX object CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [CMakeFiles/tdcore.dir/build.make:1246: CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:234: CMakeFiles/tdcore.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2

**Comment by levlam** [comment]
Compilation is single-threaded by default in make/gmake. To build with GCC see https://tdlib.github.io/td/build.html and check 'I have less than 3.5 GB of RAM." checkbox.

**Comment by lmcmceo** [comment]
@levlam it works, thanks
