### ISSUE TITLE
Unable to use .so file in Android JNI project with CMake

### ISSUE THREAD

**Issue by Vishnooo** [tdlib/td#1417]
I am trying to load an external C++ shared library (.so) to an Android JNI Cmake project, but I am getting error. I tried so many solutions available on the internet but nothing worked. I am kind of stuck here. Please check build log below:-
![build_log](https://user-images.githubusercontent.com/20800221/107757195-40ad3500-6d4b-11eb-869b-f307f8fc8990.PNG)

Please check the attached CMakeLists.txt too.

[CMakeLists.txt](https://github.com/tdlib/td/files/5971099/CMakeLists.txt)

**Comment by levlam** [comment]
The error tells you that your CMakeLists.txt has wrong syntax.
It should be
```
set_target_properties(pal PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/jniLibs/${ANDROID_ABI}/libpal.so)
```

**Comment by Vishnooo** [comment]
> 
> 
> The error tells you that your CMakeLists.txt has wrong syntax.
> It should be
> 
> ```
> set_target_properties(pal PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/jniLibs/${ANDROID_ABI}/libpal.so)
> ```

Thanks a lot for the response @levlam, I should have seen that. That problem got resolved, but now another error is popping up. I googled, but got no satisfying answers. Can you please check this too? The error is as follows:-

C:/Users/GET IT RENT/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: E:/MyAppCppSO/app/src/main/cpp/jniLibs/armeabi-v7a/libpal.so: not an object or archive

![image](https://user-images.githubusercontent.com/20800221/107911673-0332ec80-6f83-11eb-801e-00ecc93c31f0.png)

**Comment by levlam** [comment]
libpal.so is in the wrong format. Are you sure that this file was built for armeabi-v7a?

**Comment by Vishnooo** [comment]
Not sure..i just made this sample file for test. I am doing this for the first time and just pasted the same libpal.so file in all the arm64-v8a, armeabi, armeabi-v7a, x86 and x86_64 folders as seen in most of the tutorials. Now when I am building the project, this libpal.so file is being picked up from any of these folders according to some logic. This error is actually coming when I am trying to link this library to native-lib as shown in the below snapshot:-
![image](https://user-images.githubusercontent.com/20800221/108024290-4c01a880-704a-11eb-8519-38a82de60e4d.png)

If I remove the linkage, there are no errors; but without linking it we won't be able to use the library right?

**Comment by levlam** [comment]
You need to build library for different architectures and copy a library for appropriate architecture to corresponding folder. It is impossible to use the same binary for different architectures.
