### ISSUE TITLE
How to use inlineKeyboardButtonTypeLoginUrl?

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1418]
Can someone please explain to me how to use this type "inlineKeyboardButtonTypeLoginUrl" of replay_markup and what should I put in these properties (forward_text and id)? It would be great if you explain with an example

Thanks

**Comment by levlam** [comment]
See https://github.com/tdlib/telegram-bot-api/blob/e2ae8dad02a7c0046e162e12bc0c0c077fff5d14/telegram-bot-api/Client.cpp#L4350.

**Comment by levlam** [comment]
And https://core.telegram.org/bots/api#loginurl.

**Comment by zyadomer98** [comment]
Thanks for answering. But I am still not sure what to put in the id property of that object.

**Comment by levlam** [comment]
Bot's user identifier if write access is requested and -bot_user_id otherwise. You can find documentation for these parameters in https://core.telegram.org/bots/api#loginurl..

**Comment by zyadomer98** [comment]
Thanks
