### ISSUE TITLE
Error running in the background on ubuntu 16.04

### ISSUE THREAD

**Issue by MyGitHub5** [tdlib/td#142]
```
[Epoll.cpp:56][!CliClient][&err == -1]  [PosixError : Operation not permitted : 1 : epoll_ctl ADD failed], epoll_fd = 10, fd = 0
```
run with "systemctl start ---"

**Comment by levlam** [comment]
Are you using tdbot?
It seems that this error isn't related to TDLib and you need to comment lines 364-365 here: https://github.com/vysheng/tdbot/blob/0141cc01510ba6ff7988034c15d5ad047306c406/cliclient.cpp#L364
to disable using of stdin/stdout.

**Comment by MyGitHub5** [comment]
still same error 

[Epoll.cpp:56][!CliClient][&err == -1]	[PosixError : Operation not permitted : 1 : epoll_ctl ADD failed], epoll_fd = 10, fd = 0

**Comment by levlam** [comment]
Are you sure that you have recompiled tdbot? You can also comment lines 361-362 before recompilation to make sure that stdin and stdout aren't used.

**Comment by MyGitHub5** [comment]
yes i'm using tdbot on tdlib v1.1.1
i'm adding // in lines 361+362+364+365 and still error if i running in the backround with systemd on ubuntu 16.04

```
[Epoll.cpp:56][!CliClient][&err == -1]	[PosixError : Operation not permitted : 1 : epoll_ctl ADD failed], epoll_fd = 10, fd = 0
```

**Comment by levlam** [comment]
Could you add
```
LOG(ERROR) << "Before init CliStdFd";
```
on line 363,
add
```
LOG(ERROR) << "After init CliStdFd";
```
on line 366, recompile tdbot, set log verbosity to 30 (parameter -vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv), redirect the log to file and send the log to @tdlib_bot?
