### ISSUE TITLE
Telegram X

### ISSUE THREAD

**Issue by poweeer** [tdlib/td#1420]
Здравствуйте! Пользуясь приложением Telegram X ,у меня появилась вот такая ошибка. Кто подскажет что с этим делать?
![Screenshot_2021-02-16-23-04-39-495_org thunderdog challegram](https://user-images.githubusercontent.com/79169646/108117242-b5ff6980-70ad-11eb-9eec-3cdc4b0a13e9.jpg)

**Comment by levlam** [comment]
Database is broken. This can be fixed only by obtaining root rights and manual deletion db.sqlite file in the Telegram X data folder, or by clearing all application data in system settings and logging in again.
