### ISSUE TITLE
Can't use on Windows

### ISSUE THREAD

**Issue by AlexanderKudinov** [tdlib/td#1422]
Hi! Could you help me to solve the issue please? I managed to build tdlib on Ubuntu using the g++ compiler. Then I put the lib/bin/org/drinkless/tdlib folder in a jar file and started using it in Windows. I can create objects of all classes, but when I try to run code in the file example.class by changing the line System.LoadLibrary("tdjni") to System.load (path/to / libtdjni.so), but the java.lang.UnsatisfiedLinkError error occurs: Can't load this .dll (machine code=0x2200) on a AMD 64-bit platform. Can you tell me how to fix this problem?
Thanks!

**Comment by levlam** [comment]
Native libraries are not protable. You must build TDLib for each arcitecture and for each OS you want to use it from Java.
