### ISSUE TITLE
How to build dll on Linux?

### ISSUE THREAD

**Issue by AlexanderKudinov** [tdlib/td#1425]
Hello! I'd like to use tdlib in Windows, but I can only build it on Linux . Could you tell me if it is possible to build a tdlib with a native dll format library on Linux? And if so, how should I change the build conditions? 
Thanks for your answer!

**Comment by levlam** [comment]
You can use a cross compiler like mingw for that. Search for CMake cross-compilation guides and don't forget to generate needed source files using native compiler before cross-compialtion:
```
mkdir native-build
cd native-build
cmake ..
cmake --build . --target prepare_cross_compiling
cd ..
```
