### ISSUE TITLE
Handling of chat lists (archived chats, custom lists)

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1426]
Using tdlib 1.6: So https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat.html seems not to be the most recent document for the following questions:

- We want to switch between normal and archived chats. So far we know that we can set chat_list on GetChatsRequest to be either chatListMain or chatListArchived
- So for getting the archived chats, would we send this request and remove all "main" chats from the chatlist model in the App? Does tdlib then switch to sending only updates for archived chats?
- Or is it simply 2 requests to be sent for getting both archived and main chats at the same time, and also their updates?

**Comment by levlam** [comment]
> Does tdlib then switch to sending only updates for archived chats?

TDLib sends updates for all chats, regarding to which chat list they belong. In TDLib 1.6.0 there was a field `chat.chat_)list`, denoting the list to which the chat belongs.

**Comment by Flohack74** [comment]
Ok yes the field is clear, but after an initial getChats I only get chats for main, except I set "Archive" on that request, then I seem only to get archived chats. Is there a way to get all of them all the time :)

**Comment by levlam** [comment]
Yes. Send two requests, one for Main chat list and one for Archive chat list.

**Comment by Flohack74** [comment]
Alright answered thanks!
