### ISSUE TITLE
Cant build on Windows

### ISSUE THREAD

**Issue by GuilhermeAmado** [tdlib/td#1427]
` Generating Code...
  tdutils.vcxproj -> C:\TDLib\td\build\tdutils\Release\tdutils.lib
  Building Custom Rule C:/TDLib/td/tdactor/CMakeLists.txt
  ConcurrentScheduler.cpp
  Scheduler.cpp
  MultiPromise.cpp
C:\TDLib\td\tdactor\td/actor/PromiseFuture.h(317): error C2672: 'promise_interface_ptr': no matching overloaded functio
n found [C:\TDLib\td\build\tdactor\tdactor.vcxproj]
  C:\TDLib\td\tdactor\td/actor/PromiseFuture.h(716): note: see reference to function template instantiation 'td::Promis
  e<td::Unit>::Promise<td::unique_ptr<td::detail::EventPromise>>(F &&)' being compiled
          with
          [
              F=td::unique_ptr<td::detail::EventPromise>
          ]
  C:\TDLib\td\tdactor\td/actor/PromiseFuture.h(716): note: see reference to function template instantiation 'td::Promis
  e<td::Unit>::Promise<td::unique_ptr<td::detail::EventPromise>>(F &&)' being compiled
          with
          [
              F=td::unique_ptr<td::detail::EventPromise>
          ]
C:\TDLib\td\tdactor\td/actor/PromiseFuture.h(317): error C2783: 'auto td::promise_interface_ptr(F &&)': could not deduc
e template argument for 'from_promise_interface' [C:\TDLib\td\build\tdactor\tdactor.vcxproj]
  C:\TDLib\td\tdactor\td/actor/PromiseFuture.h(241): note: see declaration of 'td::promise_interface_ptr'`

**Comment by levlam** [comment]
Could you tell exact compiler version?
Could you change compiler output to verbose and show full error message?

**Comment by GuilhermeAmado** [comment]
> Could you tell exact compiler version?
> Could you change compiler output to verbose and show full error message?

Sure, here's the full log, including the instructions found on the **TDLib build instructions generator**:

[https://pastebin.com/gYWFRpbv](url)

DCMAKE_VERBOSE_MAKEFILE=ON
-- Building for: Visual Studio 14 2015
-- Selecting Windows SDK version  to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.0.24210.0
-- The C compiler identification is MSVC 19.0.24210.0

The build options are:
- JavaScript
- Windows (Node.js)
- PowerShell
- 64-bit

**Comment by levlam** [comment]
Thanks.

This looks like a VS 2015 bug, which needs to be workarounded.

You have two options:
- Use TDLib 1.7.0 by invoking `git checkout v1.7.0`, which is tested to be succesfully built by Visual Studio 2015.3.
- Update Visual Studio to 2017+.

**Comment by GuilhermeAmado** [comment]
> * Use TDLib 1.7.0 by invoking `git checkout v1.7.0`, which is tested to be succesfully built by Visual Studio 2015.3.

Using TDLib 1.7.0 worked for me. Thanks!

**Comment by levlam** [comment]
This was fixed in master.
