### ISSUE TITLE
[question] How to change a sticker's emoji(s)?

### ISSUE THREAD

**Issue by RememberTheAir** [tdlib/td#1428]
Hello there,

I have a bot I use to automatically manage a sticker pack based on a chat's activity. I was looking through the documentation and I don't see any method to change an existing sticker's emojis, although I can see the method to [change a sticker position in a pack](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_sticker_position_in_set.html), which [@stickers](https://t.me/stickers) offers as an option in the same command used to edit a sticker emojis (`/editsticker`).

Is it possible to do it from tdlib?

**Comment by levlam** [comment]
It is not possible to do directly. You can only delete the sticker and readd it to the sticker pack.

**Comment by RememberTheAir** [comment]
Oh, that's a shame. Thanks for the answer!
