### ISSUE TITLE
Chat History for new members

### ISSUE THREAD

**Issue by hossein1113** [tdlib/td#1430]
I have two questions:
1-how to check and change chat history for new members in tdlib?
2-Is there any way to show the chat history to a member of the group that has already been added to the group in hide (chat history is hide) mode?

**Comment by levlam** [comment]
1. In TDLib it is called `is_all_history_available`. You can find all related fields and methods in https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.
2. No.
