### ISSUE TITLE
How to check actual AuthorizationState

### ISSUE THREAD

**Issue by sergeydi** [tdlib/td#1431]
1) Login to app
2) send request `getAuthorizationState`
3) Received status `authorizationStateReady`
4) From desktop close session (1)
5) Send request `getAuthorizationState`
6) Received status `authorizationStateReady`

But when I try to send message I got `authorizationStateLoggingOut`

Why if I close session from desktop, I still receive `authorizationStateReady` response to `getAuthorizationState` request?

**Comment by levlam** [comment]
Because there is no update from the server, when session is terminated. App notice this on the next request to the server.

**Comment by sergeydi** [comment]
@levlam Thanks, how to get the actual AuthorizationState?

**Comment by levlam** [comment]
Ready is actual autorization state. There are can't be more "actual" state, because whatever you would receive from the server, it is already outdated.

**Comment by sergeydi** [comment]
How to receive  authorizationState is `authorizationStateLoggingOut` before sanding message attempt?

**Comment by levlam** [comment]
It is not possible and generally useless.

**Comment by sergeydi** [comment]
So the only one case to know that user is logged out is try to send message?

**Comment by levlam** [comment]
Or any other request to the server.
