### ISSUE TITLE
getCreatedPublicChats returns empty list

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1432]
With TDLib 1.7.2 I got next:
```
[ 3][t 3][1614863559.940842390][Td.cpp:3351][#1][!Td][&td_requests]	Receive request 1707: getCreatedPublicChats {
  type = publicChatTypeHasUsername {
  }
}
[ 3][t 3][1614863559.941066265][Td.cpp:4512][#1][!Td][&td_requests]	Sending result for request 1707: chats {
  total_count = 0
  chat_ids = vector[0] {
  }
}
```
I definitely have few public chats I've created, they been returning in older TDLib.  What I'm doing wrong?

Thanks

**Comment by levlam** [comment]
Could you send log to @tdlib_bot?

**Comment by zevlg** [comment]
Can't reproduce after restart, now all chats are returned.

Specific of that case was that I firstly not specified "type" at all and then only requested with "type" set to "publicChatTypeHasUsername"

After restart I first requested with "type" specified, all my chats are returned.  Then tried without "type" as in the case before restart, non returned, then once again requested with "type" specified and all chats returns correctly.
