### ISSUE TITLE
tdweb not found

### ISSUE THREAD

**Issue by nizom333** [tdlib/td#1433]
![image](https://user-images.githubusercontent.com/28598438/110222103-aecfbc80-7ef1-11eb-9ad3-fa5cfd0fa283.png)

**Comment by levlam** [comment]
This is a private package. You need to use a publicly available `tdweb` package.

**Comment by nizom333** [comment]
> This is a private package. You need to use a publicly available `tdweb` package.

Where you can get it from, you can send the link?

**Comment by levlam** [comment]
https://www.npmjs.com/package/tdweb
