### ISSUE TITLE
TdJSON API in c++ not finding tons of references

### ISSUE THREAD

**Issue by cl-ement05** [tdlib/td#1437]
My code here :
```
#include <td/telegram/Client.h>
#include <td/telegram/td_json_client.h>
#include <td/telegram/tdjson_export.h>
#include <stdlib.h>
#include <stdio.h>

void *client = td_json_client_create();
const double WAIT_TIMEOUT = 10.0;
int is_closed = 0;
int main(void) {
	while (!is_closed) {
	  const char *result = td_json_client_receive(client, WAIT_TIMEOUT);
	  if (result) {
	    printf("result is here !\n");
	  }
	}
	td_json_client_destroy(client);
	return 0;
}
```
All of this in main.cpp which I compile using g++ V7.5 using ```g++ main.cpp -ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdapi -ltdactor -ltddb -ltdsqlite -ltdnet -ltdutils -lstdc++ -lssl -lcrypto -ldl -lz -lm -lpthread```

However, this is generating a lot of not found libraries error (terminal buffer even gets full, and I can't even see the root error)

![image](https://user-images.githubusercontent.com/64481347/110674358-1b88d680-81d2-11eb-9e5f-ba525a15383c.png)

**Comment by levlam** [comment]
Why do you specify `-lstdc++` explicitly?

**Comment by cl-ement05** [comment]
> 
> 
> Why do you specify `-lstdc++` explicitly?

Oh the flags idk I just found this link https://github.com/Arman92/go-tdlib/blob/master/tdlib.go (go to line 6) on an issue and someone said I should use these flags

**Comment by levlam** [comment]
How did you build TDLib and what your OS?

**Comment by cl-ement05** [comment]
> 
> 
> How did you build TDLib and what is your OS?

I built TDLib using instructions at https://tdlib.github.io/td/build.html. Currently running on Ubuntu 18.04 LTS

**Comment by levlam** [comment]
Did you choose g++ or clang in the build instructions generator?

**Comment by cl-ement05** [comment]
> 
> 
> Did you choose g++ or clang in the build instructions generator?

No lol I am sorry I am such an idiot I compiled using clang
