### ISSUE TITLE
[Feature Request] getRemoteFile to accept unique_id

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1439]
It will be very useful to be able to `getRemoteFile` using `unique_id` instead of `remote_file_id`, so method signature could look like:

```
getRemoteFile remote_file_id:string unique_id:string file_type:FileType = File;
```

so `remote_file_id` or `unique_id` can be specified to get the file.  `unique_id` is much shorter than `remote_file_id` and it is more UI friendly to be used for client functionality.

What do you think?

Thanks

**Comment by levlam** [comment]
This is not possible. `unique_id` can be used only to compare two files, but it contains much less information that is needed to create a working `file` object. If you don't need to work this function between client restarts, then you can use `file.id` instead.

**Comment by zevlg** [comment]
I see! Thanks
