### ISSUE TITLE
Getting update messages too late

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#1440]
Hi. I am using ver. 1.5 and I have a problem. Sometimes, I receive update messages for channels several hours later and that's driving me crazy (e.g. a message posted in channel A at 23:00 and I get it next day at 8:00) . BTW I have 2 clients on my server (8GB ram) that only gets update messages (doesn't process downloading). Can you please help?

**Comment by levlam** [comment]
This is expected in all old clients. You need to update TDLib.

**Comment by yasharzb** [comment]
Hi. I've updated my tdlib version from 1.5 to 1.7. But I still have this problem. In my program, I wait for an `UpdateNewMessage` and then I process it. But sometimes I don't receive them for some channels. And the weird thing is that when I open the channel in a gui client (like android) suddenly my program receives the updates. Can you please help?

**Comment by levlam** [comment]
TDLib 1.7.0 is already too old for some users/channels. You need to try the recent version from master.
