### ISSUE TITLE
TdLib always triggering the "please enter code sent on your other devices"

### ISSUE THREAD

**Issue by cl-ement05** [tdlib/td#1441]
Even if I already signed in previously. Is there anyway to whitelist a device to prevent this from happening so I don't have each time to open telegram on another client, select the code and enter it.. ?

**Comment by levlam** [comment]
TDLib always saves authorization state between client restarts if you specify a persistent directory as `database_directory`.

**Comment by cl-ement05** [comment]
Oh sorry I hadn't heard of this parameter before
