### ISSUE TITLE
How to handle local data and remote data

### ISSUE THREAD

**Issue by eos1d3** [tdlib/td#1443]
I find when using `getChatMember`, `getUser`, `deleteChatMessagesFromUser` and other similar methods,  without calling `getSupergroupRecentMembers` at the beginning, user Ids are mostly not found.

So it is obvious that local database does not have the user data. So what is the correct way to call above methods without causing user not found error?

I read the comment https://github.com/tdlib/td/issues/578#issuecomment-500232877. I do use `getChats` whenever TdLib starts, but this does not solve the user id issue. Using `getSupergroupRecentMembers` or getUser() always works.

So what is suggested way to handle user data before related methods? Calling `getUser` every time to make sure user data is avaialable?

Thanks!

**Comment by levlam** [comment]
If you are 100% sure that user has been seen previously, i.e. you received user_id from TDLib on the previous launch, and chat_info_database is enabled, then the user can be preloaded using the method `getUser`.

The mentioned comment describes all available options.

**Comment by eos1d3** [comment]
Thanks! Just want to know what are the commonly used methods to get user data to TDLib?

Besides `getContact`, `getChats` and `GetSupergroupMembers`, are there and any others?

**Comment by levlam** [comment]
Any method, returning users or chats.

**Comment by eos1d3** [comment]
Actually why I answered this question is because of `TdApi.DeleteChatMessagesFromUser`. 

These are the sequences of the calls whenever I start the TDLib program
1. The first is to call `getChats` to retrieve the chat list. 
2. Wait a few seconds
3. Then call `TdApi.DeleteChatMessagesFromUser` and it always returns user not found even the user data is already in database.

But calling `getUser` before calling `TdApi.DeleteChatMessagesFromUser` will fix the issue.
Actually calling `TdApi.DeleteChatMessagesFromUser` with chatId and userId are enough, I just can't understand the need to call `getUser`.

**Comment by levlam** [comment]
@eos1d3 This is exactly written in the mentioned comment. You must call `getUser` to load information about a user from the database.

**Comment by eos1d3** [comment]
@levlam Sorry to ask again, I just can't get it why does `TdApi.DeleteChatMessagesFromUser` need to load user information from the database as I have already known and passed the user id and chat id to it.  So does it mean further user information from database is required to send the request to Telegram server?

**Comment by levlam** [comment]
> So does it mean further user information from database is required to send the request to Telegram server?

Exactly.

**Comment by eos1d3** [comment]
No wonder it works like this!! Now I fully understand. Big thanks again for your prompt reply!
