### ISSUE TITLE
use tdlib in c# windows Form

### ISSUE THREAD

**Issue by AbakSource** [tdlib/td#1444]
Hi!

i want to use tdlib in windows forms, i have a problem

i want to login in a new form dialog, but when use showDialog,  the ClientResultHandler event, when the form dialog is open, not work and whenever i close the form dialog, the ClientResultHandler start to work, but i need the events in Login dialog.
However, whenever i use .show() for show dialog, the child dialog freez!
 i try with Invoke for show dialog in main thread but However the ClientResultHandler don't work

please Help me... 
Thank's

**Comment by levlam** [comment]
Is it possible that you are blocking the thread, invoking all result handlers? You shouldn't do any blocking action in result handlers.

**Comment by AbakSource** [comment]
> Is it possible that you are blocking the thread, invoking all result handlers? You shouldn't do any blocking action in result handlers.

oh yeah, it's true, the reason of the problem was thread blocking, i show the new dialog in main thread and then was solved. 
`Form insForm = new Form();
Invoke((MethodInvoker)delegate() {
    insForm.show();
});`
thanks for attention :)
