### ISSUE TITLE
Notifications not working using original Telegram sources

### ISSUE THREAD

**Issue by scognito** [tdlib/td#1446]
I'm trying to build Telegram reading the official docs, but I'm having trouble in getting notification work.
Steps I did:

1. Registered my app at https://my.telegram.org, and obtained api_id and api_hash (app Android).
2. Cloned the official repo and updated BuildVars.java adding APP_ID and APP_HASH
3. Created 2 app in my Firebase Console (org.telegram.messenger and org.telegram.messenger.beta
4. Downloaded the google-services.json of the beta (for testing) and put in the root of my project
5. I'm not sure about this step: On Firebase Console, Cloud Messaging Tab, I took the server key and put it in https://my.telegram.org, on section **GCM API key** . Is this correct?
6. Compiled with Android Studio, installed on my device, app runs ok, I can chat but cannot receive notifications

When I run the application, I get a Firebase error:
```
Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
```
Am I missing some step? Thanks

**Comment by levlam** [comment]
This is completely unrelated to TDLib.

Between, steps 1, 2, 5 and 6 are correct. Probably, https://stackoverflow.com/questions/60635672/e-firebaseinstanceid-failed-to-get-fis-auth-token can help. You also definitely can't use package names of official Telegram apps (org.telegram.messenger and org.telegram.messenger.beta).

**Comment by scognito** [comment]
Ok sorry for the unrelated posting, I post the (partial) solution for anyone who faces this problem.

I had 2 problems: 
- wrong google-services.json location (was root of the project, instead it is TMessagesProj
- wrong key: it is not the server key of the Firebase console. Instead it is API key in Google, instead it is the API Key in console.cloud.google.com

Now the initialization is ok, but background notifications doesn't work...

**Comment by bantonen** [comment]
@scognito Could you please tell us in detail where you got the GCM API key
