### ISSUE TITLE
Compliling TdLib client in NATIVE C++ (not CMake)

### ISSUE THREAD

**Issue by cl-ement05** [tdlib/td#1448]
Hello,

I am writing a client in cpp and I need it to be native (no Cmake or whatever). Moreover, I must compile my project using clang. So I built TdLib using build instructions (and I chose clang) but building fails when entering ```clang main.cpp```. On the g++ version I use these flags ```-ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdapi -ltdactor -ltddb -ltdsqlite -ltdnet -ltdutils -lssl -lcrypto -ldl -lz -lm -lpthread````. Do i need the same in the clang version ? Because I get a lot of undefined references 

![image](https://user-images.githubusercontent.com/64481347/111285928-f23cd000-8641-11eb-86d0-8bc8fb9b41b4.png)

**Comment by levlam** [comment]
> "need it to be native (no Cmake or whatever)".

What exactly do you need? There can't be anything more native than CMake, which supports all popular "native" build systems.

> Do i need the same in the clang version ?

You forgotten to link with `-llibc++`.

**Comment by cl-ement05** [comment]
> > "need it to be native (no Cmake or whatever)".
> 
> What exactly do you need? There can't be anything more native than CMake, which supports all popular "native" build systems.
> 
Well it does not support the build system I am using that's to say Tizen Studio which compiles using clang and ninja.

**Comment by levlam** [comment]
You are right. Tizen is the only supported by TDLib operating system, which lacks CMake support.
You can find a brief description of build workflow for Tizen in https://github.com/tdlib/td/issues/908#issuecomment-580769345.
