### ISSUE TITLE
Add client support for a Flutter project

### ISSUE THREAD

**Issue by rben820** [tdlib/td#1449]
Hey!
Do you have any examples of how to use TdLib for a Flutter project and have it also support web functionality? 
The examples I see include support only for Android and/or iOS, but not for the web as well. 

Thank!

**Comment by levlam** [comment]
See https://github.com/tdlib/td/tree/master/example#dart. In web you likely need to use https://www.npmjs.com/package/tdweb.

**Comment by rben820** [comment]
Thank you for your response!
I tried to use tdweb, and I don't know if you can help with the implementation process for the web, but if you do, I didn't understand how to connect the tdweb.js with the dart file. If you can help with that, I'll be more than thankful!
Thanks ahead!

**Comment by levlam** [comment]
tdweb is an ordinary JavaScript package. You can use it as any other JavaScript code: https://dart.dev/web/js-interop.
