### ISSUE TITLE
Precise and clear instructions / way of including TdLib in a Tizen Project

### ISSUE THREAD

**Issue by cl-ement05** [tdlib/td#1450]
Part of the answer is in https://github.com/tdlib/td/issues/908#issuecomment-801237582 but nothing is very precise and obvious. 
Extract from TdLib README :
>
> Cross-platform: TDLib can be used on Android, iOS, Windows, macOS, Linux, FreeBSD, OpenBSD, NetBSD, Windows Phone, WebAssembly, watchOS, tvOS, Tizen, Cygwin. It should also work on other *nix systems with or without minimal effort.
>
Well here for Tizen this is clearly not the case. I went through a lot of hassles and I still don't have a working TdLib to use for my Project. Could someone please explain **clearly** how to port TdLib to Tizen (given the fact that building on Tizen Studio does not support CMakeLists)

**Comment by levlam** [comment]
This is fully described in https://github.com/tdlib/td/issues/908#issuecomment-580769345.

There are no exact build instructions, because it is hard to build anything for Tizen without a lot of manual interactions with Tizen Studio like project creation. Built shared library can be added to any Tizen project and used in it.

**Comment by cl-ement05** [comment]
> This is fully described in https://github.com/tdlib/td/issues/908#issuecomment-580769345.
> 
> There are no exact build instructions, because it is hard to build anything for Tizen without a lot of manual interactions with Tizen Studio like project creation. Built shared library can be added to any Tizen project and used in it.

And how can a built shared library can be included/added to a project ??

**Comment by levlam** [comment]
> And how can a built shared library can be included/added to a project ??

This is not specific to TDLib or related in any way to TDLib itself. You need to search for the answer in Tizen manuals. For example, for a C++ project you can do something similar to https://developer.tizen.org/community/code-snippet/native-code-snippet/how-make-shared-libary-and-link-it.
