### ISSUE TITLE
Invalid or cached user status data

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1453]
Hi.
I am using Go TDLib library (https://github.com/zelenin/go-tdlib/) and I've started three clients with it with different phone numbers and I've added my real phone number to each of them.
when I was checking my profile data via `GetUser` method of TDLib, I realized that the status and last seen of my real telegram account seems to be different from what I was seeing in a real phone having telegram app on it , and had added my phone number as a contact before.
For example, In one of those `TDLib` clients, My real phone account was online and the status of the `User` result from `GetUser` method was offline and had an old last seen. Moreover, in some cases one of my Tdlib clients was consuming my real telegram account as online while a different Tdlib client was consuming me as offline! but I have to say that I had chat messages with one of those clients and I think it might have affected online status of me on that phone.
So My questions are: "Is data which is given by Tdlib `GetUser` and `GetUserFullInfo` methods is somehow cached? so may I see a user `online` while he/she is offline in real and vice versa?"
The other thing that I experienced is that when I changed my username, `GetUser` method detected it fast, while my status data (online/offline last seen) remained unchanged!
When I changed my bio, in t.me/$myusername, I checked that my new bio had been set successfully but in Tdlib It lasted for about 1 hour for me to be able to get uncached real value for it.
Do we have such caches in a real telegram app or these caches are implemented by `Go-tdlib` library? or because I was fetching my `UserProfile` in an infinite loop such cache mechanism activated?

**Comment by levlam** [comment]
> So My questions are: "Is data which is given by Tdlib GetUser and GetUserFullInfo methods is somehow cached? so may I see a user online while he/she is offline in real and vice versa?"

It is definitely cached, but this is not the cause of this behavior. Telegram has hundreds of millions registered users. It is not possible for each of them to know exact status of each of them. Even sending an update after status change of any contact would result in enormous number of updates and a lot of network traffic. Actual status and other information about another user are often received only when they are needed. For example, when you open a private chat with the user, or open user's profile. Without an active action with the user any data can be outdated, which is expected behavior.

You can use `getUserFullInfo` to update information about a user with at most a minute delay.

**Comment by telexengineering** [comment]
> You can use `getUserFullInfo` to update information about a user with at most a minute delay.
According to this sentence, Will I be able to check status of a user (online/offline) from `getUserFullInfo` method with at most 1 minute delay without having a chat with him/her?
Because when I call `getUserFullInfo` method, the `User` field in it is empty and It seems weird to me!

**Comment by levlam** [comment]
`userFullInfo` has no field `user`: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1user_full_info.html.

**Comment by telexengineering** [comment]
Thanks

**Comment by telexengineering** [comment]
Well, I still have some questions. What's the difference between the `GetUser` method and the methods which a Telegram application on a mobile phone calls?; Because I've checked 3 Telegram mobile clients, some of which don't have even a chat conversation with me, but they detect online/offline of my account ASAP. Why they are able to detect status changes of my account so fast but TDlib clients on my laptop couldn't?
To explain more, I want to create a server application which checks online/offline times and online duration of my account and logs that data. I want to be able to find out status changes of my telegram account as soon as possible. Do you suggest another way for me to be to able to fulfill this goal?

**Comment by levlam** [comment]
> Actual status and other information about another user are often received only when they are needed. For example, when you open a private chat with the user, or open user's profile. Without an active action with the user any data can be outdated, which is expected behavior.

This behavior doesn't depend on which client is used.

> I want to be able to find out status changes of my telegram account as soon as possible. 

You should always receive updates about changes in online status of **your** account immediately. You can't expect the same for other accounts.

**Comment by telexengineering** [comment]
> You should always receive updates about changes in online status of **your** account immediately. You can't expect the same for other accounts.

Yes I know that. but when I was talking about my phone, I meant my real phone number which had been added as a contact to that telegram client running on Tdlib via a virtual phone.
I said that when I check my profile on an Android Telegram client ,connecting to telegram using that virtual phone, and go to my chat (a simple draft message with no conversation) and go to my profile page, I see online status of my real phone,  correctly; But when I use Tdlib client and call `GetUser` method, Event if I had observed the sequence of API calls like mobile app one (fetch chat and then fetch user via `GetUser` method), the online status would seem to be a cached one.
I mean, What step do you think I haven't done well, that I see such a different behavior?

**Comment by levlam** [comment]
>  go to my chat (a simple draft message with no conversation) and go to my profile page, I see online status of my real phone, correctly; But when I use Tdlib client and call GetUser method,

Because noone ever uses `getUser`. Apps use `getUserFullInfo` to obtain full information about the user when corresponding chat is opened.

**Comment by telexengineering** [comment]
Ok, but for checking last seen of a user, what method do Telegram mobile apps use?

**Comment by levlam** [comment]
They don't "checking last seen of a user". Instead "Actual status and other information about another user are often received only when they are needed. For example, when you open a private chat with the user, or open user's profile." using `get*FullInfo`.

**Comment by telexengineering** [comment]
I didn't find out the place from which the Telegram mobile clients retrieve last seen of a user.

**Comment by levlam** [comment]
I told you, what exactly they are doing.
