### ISSUE TITLE
Trying to open sqlite database

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1454]
Hi.
I've tried to open sqlite database of tdlib in sqlite DB Browser (https://sqlitebrowser.org/dl/)
the app asks me for encryption password or encryption Raw key of the database.
Where can I find such a key?

**Comment by levlam** [comment]
TDLib doesn't provide a way to get it. Anyway, data stored in the database as binary blobs, which can be parsed only by TDLib itself, so it is useless.
