### ISSUE TITLE
How to write a draft message via TDLib

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1456]
Hi.
In a Telegram application, when you've added a new contact, you will be able to open a chat with that account and start typing, that message will be drafted.
In a Tdlib client, when I've added a Telegram contact, I want to draft a message for him but the `SetChatDraftMessage` method needs two other parameters named `chat_id` and `message_thread_id`. Where can I find those params?

**Comment by levlam** [comment]
You can create a chat with a user using `createPrivateChat` method.

> @message_thread_id If not 0, a message thread identifier in which the draft was changed

Only supergroups has support for message threads.

**Comment by telexengineering** [comment]
thanks
