### ISSUE TITLE
Cannot find created private chat

### ISSUE THREAD

**Issue by telexengineering** [tdlib/td#1457]
Hi.
I added a telegram contact to my TDLlib client and created a private chat via `CreatePrivateChat` method of TDLib and then drafted a message on that chat. Those operations was successful because I saw drafted messages on a mobile app which was using the same phone which was running on my TDLib client.
after a moment, when I wanted to find that chat (which it's ID was the telegramID of my desired user), I saw "Chat Not found" error!
What's the reason of such a problem?

**Comment by levlam** [comment]
What is "to find that chat"?

**Comment by telexengineering** [comment]
I meant the chat in which I've written a drafted message

**Comment by levlam** [comment]
How are you trying to find the chat?
