### ISSUE TITLE
FormData header parsing does not support quotes or semicolons

### ISSUE THREAD

**Issue by KnorpelSenf** [tdlib/td#1459]
I cannot figure out how to send a file that has a double quotes character (") or a semicolon (;) in the filename. According to [the Telegram Bot API docs](https://core.telegram.org/bots/api#sending-files), files are uploaded "the usual way". I interpret this as "according to the specs" of multipart/form-data uploads. The content-disposition header should then respect "name", "filename", and "filename*" directives ([reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#directives)). Following the referenced specification, simple ASCII file names (e.g. `file.txt`) could be send as `filename="file.txt"`, but anything else (e.g. `file"with"quotes.txt`) may be encoded as specified by [RFC 5987](https://datatracker.ietf.org/doc/html/rfc5987) and sent under `filename*`, i.e. `filename*=UTF-8''file%22with%22quotes.txt`.

Looking at the code,

https://github.com/tdlib/td/blob/70b71d569b81c66b25f8f77d9536b1d41fbf091d/tdnet/td/net/HttpReader.cpp#L348

it does not seem like the header parsing is compliant with the specs. Neither would `filename="file;with;semi.txt"` be parsed correctly (the parser scans for the first occurrence of ; without regarding quotes), nor is there any support of `filename*` directives.
https://github.com/tdlib/td/blob/70b71d569b81c66b25f8f77d9536b1d41fbf091d/tdnet/td/net/HttpReader.cpp#L352

I tried sending the various different headers and it is indeed not possible to send a file that contains " or ; (unless I am missing something, please correct me if I'm wrong).

I don't think exact compliance with the specs is necessary as long as there is a workaround for sending files with arbitrary names, that would absolutely do it for me. Do you have any advice how to send files with these names?

**Comment by KnorpelSenf** [comment]
Missing context: I'm using telegram-bot-api with relies on tdlib. I'm trying to send a file with a Telegram bot.

**Comment by levlam** [comment]
Content-Disposition header parsing was fixed in 48aecf88371a8f27517ff2fc817a9b64b38714ab 3 days ago. It prevented only sending files with a semicolon in the name.

There are no plans to support "filename*" directive, but UTF-8 characters are allowed in "filename", so it can be used to send files with arbitrary names.

`"` and some other characters are intentionally replaced by spaces in the function https://github.com/tdlib/td/blob/c6dec21cb691f1a47b2f97f1c2fb4217af6a154d/tdutils/td/utils/filesystem.cpp#L102, to mitigate possible security vulnerabilities.

**Comment by KnorpelSenf** [comment]
Amazing, thank you! Any ETA when the new code will go live? I may decide to host my own instance if you plan on waiting with that for now.

**Comment by levlam** [comment]
@KnorpelSenf No, no ETA. Bot API source code is likely to be updated soon to TDLib 1.7.2, but there was no bot-related features in the release, so it is unknown when api.telegram.org will be updated.

**Comment by KnorpelSenf** [comment]
I see. Is there a way to be notified about a new deployment, or to find out which version is currently running?

**Comment by levlam** [comment]
All Bot API updates are announced in @BotNews. To receive a notification, when Bot API public source code is updated, you need to watch the repository https://github.com/tdlib/telegram-bot-api.

**Comment by KnorpelSenf** [comment]
Ahhh thanks for the clarification! I assumed there could be minor fixes in between, therefore my question.
