### ISSUE TITLE
When should I erase the key-value in the "handlers" map?

### ISSUE THREAD

**Issue by SpriteOvO** [tdlib/td#1461]
https://github.com/tdlib/td/blob/c6dec21cb691f1a47b2f97f1c2fb4217af6a154d/example/cpp/td_example.cpp#L156-L176

I found that after calling `send_query` with a `handler`, memory will always increase and not decrease, which seems to be directly related to `handlers_`, the example always inserts the key-value into `handlers_` without erasing it.

Is this a bug? When should I erase key-values that are no longer needed? Does `tdlib` guarantee to always reply to me only one `response` after I call `send`? If so, I can erase the key-value after calling the `handler` once.

If this is not a bug, how should I mitigate this problem?

Thanks in advance!

**Comment by levlam** [comment]
Yes, this is a bug in the example. Handler was supposed to be erased after line 174.
