### ISSUE TITLE
Error TDLIB for Android 11

### ISSUE THREAD

**Issue by Ermiya12** [tdlib/td#1462]
How can I fix the cause of the error and failure to update?

**Comment by levlam** [comment]
What is the error?

**Comment by Ermiya12** [comment]
TDLib fatal error. Version: 1.6.4.1362
[ 0][t 4][1616685368.470860243][FileDb.cpp:253][#1][!MessagesManager]	Cycle in file database?

**Comment by Ermiya12** [comment]
TDLib fatal error. Version: 1.6.4.1362
[ 0][t 4][1616685368.470860243][FileDb.cpp:253][#1][!MessagesManager]	Cycle in file database?

**Comment by moin123-1** [comment]
Solved your problem?

**Comment by levlam** [comment]
@moin123-1 This problem wasn't unrelated to any particular Android version and was solved. What's your problem?

**Comment by Twin2021** [comment]
My telegram x is not opening due to database, I have tried to delete some certain things on my phone but it never open

**Comment by levlam** [comment]
@Twin2021 Which exactly problem do you have?

**Comment by Twin2021** [comment]
LDB problems, due to the problem my telegram kept logout
