### ISSUE TITLE
Failed to parse Unknown class

### ISSUE THREAD

**Issue by lucian-ma** [tdlib/td#1465]
Hi. I am using ver. 1.4 and I have a problem

Failed to parse [request:{\042@type\042:\042addContact\042,\042contact\042:{\042@type\042:\042contact\042,\042phone_number\042:\042+86**********\042,\042first_name\042:\042yang\042,\042last_name\042:\042yang\042,\042vcard\042:null,\042user_id\042:null},\042share_phone_number\042:false,\042@extra\042:14}] [Error : 0 : Unknown class]

**Comment by levlam** [comment]
Method `addContact` was added in TDLib 1.6.0.

**Comment by lucian-ma** [comment]
thanks
