### ISSUE TITLE
Problem sending a text message

### ISSUE THREAD

**Issue by sheko016** [tdlib/td#1468]
Hello team, I hope you are very well.

This is to notify that I am testing TDLIB for the first time, it should be noted that these tests are being performed with [PHPTDLIB](https://github.com/yaroslavche/phptdlib)

The problem I have is that I want to send a message to one of my contacts with TDLIB, the answer that sendMessage gives me is:
```
string(798) "{"@type":**"message","id":1**,"sender":
{"@type":"messageSenderUser","user_id":1236147314},"chat_id":272691213,"sending_state":{"@type":"messageSendingStatePending"},"is_outgoing":true,"is_pinned":false,"can_be_edited":false,"can_be_forwarded":true,"can_be_deleted_only_for_self":false,"can_be_deleted_for_all_users":true,"can_get_statistics":false,"can_get_message_thread":false,"is_channel_post":false,"contains_unread_mention":false,"date":1616864570,"edit_date":0,"reply_in_chat_id":0,"reply_to_message_id":0,"message_thread_id":0,"ttl":0,"ttl_expires_in":0.000000,"via_bot_user_id":0,"author_signature":"","media_album_id":"0","restriction_reason":"","content":{"@type":"messageText","text":{"@type":"formattedText","text":"Hello how are you.?","entities":[]}},"@extra":1649760492}"
```

But this message does not reach my contact.

How can I check if the message was sent?
why the message_id = 1.?

waiting for your valuable response, I say goodbye.

Greetings.

**Comment by levlam** [comment]
You will receive `updateMessageSendFailed` if the message has failed to send. You will receive `updateMessageSendSucceeded` if the message is successfully sent. You need to waid for the corresponding update.

**Comment by sheko016** [comment]
Good afternoon @levlam.

I would like to know how I can check the update

GreetingsGood afternoon @levlam.

I would like to know how I can check the update

Greetings

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started

**Comment by sheko016** [comment]
okay thank you very much.

Yes, I have read that many times. but I have a hard time understanding it.

But read him again.

Greetings.

**Comment by mantsurovr** [comment]
@sheko016, same issue, did you resovle it?

**Comment by GuHuGroup** [comment]
> https://core.telegram.org/tdlib/getting-started

I have the same issue, but my question is why is the pending state here? what kind of situation here will be a pending state?
