### ISSUE TITLE
Get the last message

### ISSUE THREAD

**Issue by cosimof** [tdlib/td#1469]
Hello sirs,
I'm wondering what's the best way to get the last message of a chat. I'm trying to create a function that given a chatID returns the last message of that chat as a String.
I've tried casting things but actually i didn't find a straight way to do it.

Kind regards,
cosimof

**Comment by levlam** [comment]
There is no way to obtain any data just by a chat_id.

**Comment by cosimof** [comment]
Oh, ok, let me clarify. I've joined a channel that periodically sends messages containing data about something and what I want to do is to save that data in order to do some calculation. What's the best way to retrieve and store that messages if that is possible?
Thank you for your time.

**Comment by levlam** [comment]
You must listen to updates from TDLib. See https://core.telegram.org/tdlib/getting-started.
