### ISSUE TITLE
how to remove ', TDLib 1.6.0' from aplication_version value in Telegram session

### ISSUE THREAD

**Issue by alirayaneh** [tdlib/td#1470]
hi
when we create session by tdlib that add extra string to application_version value in telegram session
this is my parameter value
tdlibParameters: {
device_model: 'Firefox',
system_version: 'Windows',
application_version: '5.7.0',
enable_storage_optimizer: true,
apiId: api_id,
apiHash: api_hash
}
but when i see telegram sessions

application_version: 5.7.0, TDLib 1.6.0

how to caler this copy right

i have used native build from tdlib nativ

**Comment by levlam** [comment]
It can't be removed without altering TDLib's source code.

**Comment by alirayaneh** [comment]
thanks .
for some business  competitive  and security reason, I have to hide the connection method and the method used in the sessions. .

but which file and which line ?

**Comment by levlam** [comment]
I can't help with that.
