### ISSUE TITLE
Client.send doesn't return a response

### ISSUE THREAD

**Issue by Vladislav-ux** [tdlib/td#1473]
During the synchronized main Chat List and the specific chat, I am trying to send a request to get information about the current user.
It looks like this: client.send(new TdApi.GetMe(), new resultHandler () { ... };), but I don't get any response to the request. Please tell me what could be the problem?

**Comment by levlam** [comment]
All updates and request responses are processed in a dedicated thread. You need to ensure that this thread isn't blocked.

**Comment by Vladislav-ux** [comment]
I think I figured out what the problem was. I was sending a new request inside the processing of the current request. That is, the following hierarchy was obtained:
client.send(new GetUser(), new ResultHandler() { 
          client.send(new GetMe(), new ResultHandler(){ ... }); 
});
Do I understand correctly that with this request structure, the internal request will not be executed?

**Comment by levlam** [comment]
All requests will be executed. But all requests are asynchronous. You can't expect immediate response or even a response while another ResultHandler is running. The issue is not in the request itself, but in a try to synchronously wait the response somewhere in your code.

**Comment by Vladislav-ux** [comment]
I understand, thank you!
