### ISSUE TITLE
how to get the member list from BasicGroup

### ISSUE THREAD

**Issue by lucian-ma** [tdlib/td#1475]
how to get the member list from BasicGroup?

**Comment by levlam** [comment]
Use `getBasicGroupFullInfo`.

**Comment by lucian-ma** [comment]
> Use `getBasicGroupFullInfo`.

yes it works, but i can only get ChatMember list,ChatMember only contains userId,if i want to get more ChatMember userInfo i need call GetUserFullInfo one by one?

**Comment by levlam** [comment]
No. You need to read https://core.telegram.org/tdlib/getting-started.
