### ISSUE TITLE
how to get userId by phoneNumber?

### ISSUE THREAD

**Issue by lucian-ma** [tdlib/td#1476]
i want to add a contact with phoneNumber , firstname ,lastname , 
but return  {"@type":"error","code":3,"message":"User not found","@extra":8} 
 i donot know how to get the userId by phoneNumber

**Comment by levlam** [comment]
Which method are you using? `importContacts` can't return "User not found" error.

**Comment by levlam** [comment]
`addContact` adds a user to the contact list or edits an existing contact by their user identifier.
`importContats` adds new contacts or edits existing contacts by their phone numbers.

**Comment by anonym24** [comment]
@levlam adding a new contact doesn't work:

```
                client.send(
                    AddContact(
                        Contact(
                            PHONE_NUMBER, "Test1", null, null, 0L
                        ), false
                    ), Example.defaultHandler
                )
```

I receive an error:

```
Error {
  code = 400
  message = "User not found"
}
```
