### ISSUE TITLE
Telegram has failed to launch because of tdlib fatal error

### ISSUE THREAD

**Issue by moin123-1** [tdlib/td#1477]
Please solve my issue
![Screenshot_2021-03-30-15-46-22-89_1149b56b894fd37d9a6fe46f85aae740](https://user-images.githubusercontent.com/81621252/112973601-29959b80-916f-11eb-9cea-6ee5427aac2a.jpg)

**Comment by moin123-1** [comment]
> You need to share error details with @tdlib_bot.

I reply to bot but no reply

**Comment by levlam** [comment]
Do you have an error now?

**Comment by moin123-1** [comment]
> You need to update Telegram X. You use a very old and outdated version.

If I update app all my account will lost

**Comment by levlam** [comment]
@moin123-1 No, nothing will be lost. Why do you think so?

**Comment by levlam** [comment]
Unlimited, except there can be some issues on old Android versions.

**Comment by moin123-1** [comment]
> Unlimited, except there can be some issues on old Android versions if you have 100+ accounts.

I have android version 10 and account 50+ then why I am facing issue

**Comment by levlam** [comment]
What issue are you facing? The issue shown on the screenshot happens, because you are using a very old Telegram X version.

**Comment by birdmone1** [comment]
hello i have the same problem

**Comment by levlam** [comment]
@birdmone1 What exactly problem do you have?

**Comment by cYoonSeeun** [comment]
![Screenshot_20220412_225043](https://user-images.githubusercontent.com/103517910/163002857-3faa747f-173f-4035-b72a-3fb452d7521f.jpg)
what should I do?
