### ISSUE TITLE
get chat list error 

### ISSUE THREAD

**Issue by lucian-ma** [tdlib/td#1479]
i create a basic group then i leave the group ,when i restart the app, i still get the update from this group,

 {"@type":"updateNewChat","chat":{"@type":"chat","id":-501282784,"type":{"@type":"chatTypeBasicGroup","basic_group_id":501282784},"title":"test group","permissions":{"@type":"chatPermissions","can_send_messages":true,"can_send_media_messages":true,"can_send_polls":true,"can_send_other_messages":true,"can_add_web_page_previews":true,"can_change_info":true,"can_invite_users":true,"can_pin_messages":true},"positions":[],"is_marked_as_unread":false,"is_blocked":false,"has_scheduled_messages":false,"can_be_deleted_only_for_self":true,"can_be_deleted_for_all_users":false,"can_be_reported":false,"default_disable_notification":false,"unread_count":0,"last_read_inbox_message_id":0,"last_read_outbox_message_id":118043443200,"unread_mention_count":0,"notification_settings":{"@type":"chatNotificationSettings","use_default_mute_for":true,"mute_for":0,"use_default_sound":true,"sound":"default","use_default_show_preview":true,"show_preview":false,"use_default_disable_pinned_message_notifications":true,
"disable_pinned_message_notifications":false,"use_default_disable_mention_notifications":true,"disable_mention_notifications":false},"reply_markup_message_id":0,"client_data":""}}

{"@type":"updateChatLastMessage","chat_id":-501282784,"last_message":{"@type":"message","id":118043443200,"sender":{"@type":"messageSenderUser","user_id":693461571},"chat_id":-501282784,"is_outgoing":true,"is_pinned":false,"can_be_edited":false,"can_be_forwarded":false,"can_be_deleted_only_for_self":true,"can_be_deleted_for_all_users":true,"can_get_statistics":false,"can_get_message_thread":false,"is_channel_post":false,"contains_unread_mention":false,"date":1617259802,"edit_date":0,"reply_in_chat_id":0,"reply_to_message_id":0,"message_thread_id":0,"ttl":0,"ttl_expires_in":0.000000,"via_bot_user_id":0,"author_signature":"","media_album_id":"0","restriction_reason":"","content":{"@type":"messageChatDeleteMember","user_id":693461571}},"positions":[]}

{"@type":"updateChatPosition","chat_id":-501282784,"position":{"@type":"chatPosition","list":{"@type":"chatListMain"},"order":"6946077958725547967","is_pinned":false}}

**Comment by levlam** [comment]
This is absolutely correct. You still have access to messages in that group, received while you was a member of that group. You need to use `deleteChatHistory` with `remove_from_chat_list` to remove the group from the chat list.
