### ISSUE TITLE
Deallocation of Messages

### ISSUE THREAD

**Issue by leoMehlig** [tdlib/td#148]
I'm downloading a lot of messages in my iOS app and the memory usages increases quickly. But even when I no longer use them, the memory does not decrease. When I look in the memory debugger I see a lot of active Message object, that I don't have access to.
How could does the memory management work here or how could I "force" release them?

I'm accessing the library with the JSON interface.

**Comment by levlam** [comment]
Have you enabled message_database in tdlibParameters? Messages are unloaded from memory only if they can be quickly reloaded from the database.

**Comment by leoMehlig** [comment]
Hi @levlam, 
Yes, I'm using the message_database. Just to clarify: Memory is around 200MB after loading a couple of thousands of messages.
Also is there a way to prevent tdlib from deleting messages from the database after sometime. I'd like to keep them all locally forever.

**Comment by levlam** [comment]
Than messages should be unloaded from a memory within a minute. 200MB is a very high memory consumption, It can't be caused by few thousands of messages anyway. There must be some other reason for that.

TDLib doesn't removes old messages from the database unless they are deleted.

**Comment by leoMehlig** [comment]
Mmh. I just created a small iOS sample project with the code from the swift example and memory usage is good now. 
Although when I load the messages from one chat (42k in this case) they get reloaded from the network (including waiting for the "flood delay") every time. If I use the "only_local" (@type = "getChatHistory") parameter on the second run, zero messages get returned. 
Is there a way to keep them stored locally, since it takes a lot of time to download them again?

**Comment by leoMehlig** [comment]
[Here](https://1drv.ms/u/s!AqYxkz1lMfsTuUk99cCG6Bu6pjYL) is a sample project. Just replace the last_message_id.

**Comment by levlam** [comment]
You have enabled message database, so messages should be stored locally. You can try to load messages, switch off the network, kill the app, open the app and try to load messages again. It should succeed without network requests. If not, please set TDLib log verbosity level to 3, repeat these actions and send the log to @tdlib_bot in Telegram.

**Comment by underlow** [comment]
Seems like I'm facing pretty similar issue. Either I'm doing something wrong or there is a bug.
My use-case (I use library from java app with message_database turned on): 

- search public chat I'm not subscribed to
- save returned chat object
- from time to time request last chat messages 

At this moment I can see that memory consumption increases and never decreases

I'm not clearly understand what is going on under the hood and probably I'm doing something wrong so some clarification would be really appreciated

**Comment by leoMehlig** [comment]
Hi, I solved the issue by doing the conversion from `String` to `Data` in another thread. When I did that in the same thread are calling `td_json_client_receive` the memory would never get freed.

```
self.queue.async { [weak self] in
            while self?.isListing ?? false {
                if let response = td_json_client_receive(self!.client, 10) {
                    let string = String(cString: response)
// Not converting to Data here
                    self?.streamQueue.async {
                        if let data = string.data(using: .utf8) {
                            self?.stream.current = .value(data)
                        }
                    }
                }
            }
        }
```

Don't now how this works in java with GC, but this fixed my problem.

**Comment by levlam** [comment]
@underlow Memory footprint should remain small. How big it is and how fast it grows? Do you know whether native or Java memory consumption increases?

**Comment by underlow** [comment]
It's big, I'd say it's too big to say it's not messages, my guess it's pictures/video
It is not java definitely, I've checked it, but I am not familiar with instrumenting native.

I'd say that it's related either to java or the fact that I get history of chat I'm not a member of.

Is there anything I can do to find out the cause?

**Comment by levlam** [comment]
If it uses approximately by 2 kilobytes per photo and 1 kilobyte per video, than it is expected behavior for now. So you need to load more than 50,000 photos/100,000 videos to rich 100 MB of used memory.

**Comment by underlow** [comment]
Do I get it right, all photos and videos stay in memory? Sounds pretty strange. 
Or there is some option to unload them?

Anyway it seems strange that without doing something special I get infinite memory increase

**Comment by levlam** [comment]
Yes, some data about files stays in the memory forever, because currently there is no way to unload it.

**Comment by underlow** [comment]
Any plans on changing that behaviour?
Thanks anyway

**Comment by levlam** [comment]
There is no way to change that without making working with files much-much harder. Basically, we can't unload files, because client may store their identifiers and use them any time.

**Comment by mib32** [comment]
I had run a test - running getChatHistory in the loop, with same parameters, always fetching the same messages - and memory does leak. With 1.6.0 version

**Comment by levlam** [comment]
It definitely doesn't leak in TDLib. How do you run the test?

**Comment by mib32** [comment]
I think that it actually might be SQLite. I noticed that the leaking is
much more happening with the client that has _very_ big message database.

чт, 29 окт. 2020 г. в 20:58, Aliaksei Levin <notifications@github.com>:

**Comment by levlam** [comment]
@mib32 If you fetch the same messages over and over, the SQLite didn't involved.

**Comment by mib32** [comment]
@levlam I made a test once again thoroughly. You are right - it doesn't leak when I loop over one channel messages. On first loop it increases, but after second loop memory increase stops.

However, if I then go to another chat to fetch all messages, the memory will increase again. And on to the next chat - will increase once more again! And like that infinitely. It reaches big scales pretty quickly, with the rate somewhere about 40 MB per 3k messages.

I am pretty sure memory not leaking in my parts of code, because if I loop over and over - I don't see leakage.
However it makes sense - I understand that messages are loaded into the memory, otherwise they would be had to fetched over and over again. I guess nothing can be done easily, though it would be very nice to have the ability to save this memory for low-memory environments.

Details of testing:
TDLib 1.6.0, used from ruby via FFI.
use_message_database: **false**
use_chat_info_db: **true**

**Comment by levlam** [comment]
The messages are unloaded after 60 seconds in closed chats if message database is used. After that most of the memory can be reused. If message database isn't used, then messages aren't unloaded to guarantee that a message_id received from TDLib can be used by the application.

**Comment by AleksanderZverev** [comment]
Hello. We have the same problem with memory leaking on C# .NET TdLib. Unmanaged memory increases over time, but .NET Memory  almost not increases, so we suppose it's a problem under the TdLib.

For 24 hours it took almost 500 MB of RAM
![image](https://user-images.githubusercontent.com/67056960/133544754-f9a2c8d2-411a-4b7f-a144-36bb9cf4288d.png)
