### ISSUE TITLE
updatenewmessage message sender is always null

### ISSUE THREAD

**Issue by akhibing** [tdlib/td#1480]
I use tdlib and get messages with updatenewmessage but always message sender is null. how can I get message sender data so?

**Comment by levlam** [comment]
Message sender can't be null. It is always non-null.

Are you sure that you use new enough TDLib version, which has this field?

**Comment by P9os** [comment]
![изображение](https://user-images.githubusercontent.com/39376957/114462672-cf7be800-9bfc-11eb-9808-b0272c7d9a03.png)
TdLib version v1.7.0 with bindings on .net core

<details>
  | Name | Value | Type
-- | -- | -- | --
◢ | updateNewMessage | {TdLib.TdApi.Update.UpdateNewMessage} {$1} | TdLib.TdApi.Update.UpdateNewMessage
  | DataType | "updateNewMessage" | string
  | Extra | null | string
  | ◢ Message | {TdLib.TdApi.Message} | TdLib.TdApi.Message
  | AuthorSignature | "" | string
  | CanBeDeletedForAllUsers | false | bool
  | CanBeDeletedOnlyForSelf | false | bool
  | CanBeEdited | false | bool
  | CanBeForwarded | true | bool
  | CanGetMessageThread | false | bool
  | CanGetStatistics | false | bool
  | ChatId | -1001066857984 | long
  | ContainsUnreadMention | false | bool
  | ▶ Content | {TdLib.TdApi.MessageContent.MessageText} | TdLib.TdApi.MessageContent {TdLib.TdApi.MessageContent.MessageText}
  | DataType | "message" | string
  | Date | 1618261346 | int
  | EditDate | 0 | int
  | Extra | null | string
  | ForwardInfo | null | TdLib.TdApi.MessageForwardInfo
  | Id | 1087788548096 | long
  | InteractionInfo | null | TdLib.TdApi.MessageInteractionInfo
  | IsChannelPost | false | bool
  | IsOutgoing | false | bool
  | IsPinned | false | bool
  | MediaAlbumId | 0 | long
  | MessageThreadId | 0 | long
  | ReplyInChatId | 0 | long
  | ReplyMarkup | null | TdLib.TdApi.ReplyMarkup
  | ReplyToMessageId | 1087781208064 | long
  | RestrictionReason | "" | string
  | SchedulingState | null | TdLib.TdApi.MessageSchedulingState
  | Sender | null | TdLib.TdApi.MessageSender
  | SendingState | null | TdLib.TdApi.MessageSendingState
  | Ttl | 0 | int
  | TtlExpiresIn | 0 | double?
  | ViaBotUserId | 0 | int
</details>

**Comment by levlam** [comment]
@P9os What is returned by GetOption("version")?

**Comment by P9os** [comment]
> 
> 
> @P9os What is returned by GetOption("version")?

Yes, you are true. I am use tdlib version 1.6.0. and tdlib bindings net core 1.7.0 [https://github.com/egramtel/tdsharp](url).
I think this issue want to close.
Thanks
