### ISSUE TITLE
How to get update of all messages in album for ForwardMessages()

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1482]
We have and ForwardMessages() with message_ids and as_album - cool!

But I get update only one message via UpdateNewMessage each time when use SendMessageAlbum()

Please help me :)

**Comment by levlam** [comment]
`updateNewMessage` is sent for every new message. If you are sending a lot of messages at once, there will be a lot of `updateNewMessage`.

Between, `as_album` parameter was removed from `forwardMessages` and album structure is always automatically kept now.

**Comment by comerc** [comment]
```go

**Comment by comerc** [comment]
Hmmm. I get multiple separated messages when I try to forward an album. For example, via zelenin/go-tdlib wrapper
```go
	dscChatId := -12345678
	for update := range listener.Updates {
		if update.GetClass() == client.ClassUpdate {
			if updateNewMessage, ok := update.(*client.UpdateNewMessage); ok {
				src := updateNewMessage.Message
				forwardedMessages, err := tdlibClient.ForwardMessages(&client.ForwardMessagesRequest{
					ChatId:     int64(dscChatId),
					FromChatId: src.ChatId,
					MessageIds: []int64{src.Id},
					Options: &client.MessageSendOptions{
						DisableNotification: false,
						FromBackground:      false,
						SchedulingState: &client.MessageSchedulingStateSendAtDate{
							SendDate: int32(time.Now().Unix()),
						},
					},
					SendCopy:      false,
					RemoveCaption: false,
				})
				if err != nil {
					log.Print(err)
				} else if forwardedMessages.TotalCount == 0 {
					log.Print("Invalid TotalCount")
				}
			}
		}
	}
```

**Comment by levlam** [comment]
You forward messages one by one. You need to forward all messages together.

**Comment by comerc** [comment]
But how do I know if I have received all messages from one album?

**Comment by levlam** [comment]
There is no way to know this. You need to use some timeout.
