### ISSUE TITLE
How to reset API_HASH if he was compromised

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1483]
I don't want to delete my account. Maybe there is other way.

**Comment by levlam** [comment]
There is no way to do that, because it would affect all current app users.

**Comment by comerc** [comment]
There are no users there yet. But they will appear in the future and may suffer in this case. :)

**Comment by levlam** [comment]
There is still no way to change API_HASH.

**Comment by dancojocaru2000** [comment]
So if an API_HASH is accidentally exposed, the only two "solutions" are deleting someone's personal account with all the chats and data in it or letting allowing the leaked API_HASH to be used and potentially abused?

**Comment by levlam** [comment]
@dancojocaru2000 Yes. You need to take care of your API_HASH.

**Comment by mbasaglia** [comment]
Is there any way of keeping API_HASH secure if you are distributing compiled applications to end users?

**Comment by levlam** [comment]
@mbasaglia No, but this isn't needed.
