### ISSUE TITLE
TdLib: 1.7.3 AuthorizationState suddenly changes to closing state

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#1484]
Hi. I recently upgraded my tdlib from 1.5 to last version (1.7.3 - with cloning not using the tag). I've used tdlib in my own java code (not the example). But now when I start my program, I get `closing` and `closed` logs from `onAuthorizationStateUpdated`. Is there something new that I might haven't checked?

**Comment by levlam** [comment]
Check the TDLib's log. TDLib is never closes itself without explicit `close` request. You can only receive `LoggingOut` and then `Closed` of the current user was logged out from another device.
