### ISSUE TITLE
how to use chatList

### ISSUE THREAD

**Issue by AbakSource** [tdlib/td#1485]
hi

i use the tdlib in c# windows forms 🙂

i want to get list of chats for example just supergroups or related chats, must i to use chatList in getChats class or other ? 🤔 

how i can use the chatList ?? 😐

please explain me with a simple code of chatList 😅

TNX 😊

**Comment by levlam** [comment]
This is descibed in https://core.telegram.org/tdlib/getting-started.

**Comment by AbakSource** [comment]
tnx for answer but i cant understand how to use ChatList class

exist a sample code ? 

``

**Comment by AbakSource** [comment]
tnx for answer but i cant understand how to use ChatList class

exist a sample code for C# ?
i already use this way
`new TAPI.GetChats(null, Int64.MaxValue, 0, 20)
`
but i want to get just superGroup chats, must i use this way ? :

`new TAPI.GetChats(`ChatList instance`, Int64.MaxValue, 0, 20)
`
what can i do?

please explan with example code

**Comment by levlam** [comment]
If there is no example in https://github.com/tdlib/td/tree/master/example#csharp, then there is no example in C#.

You can't receive just supergorups. You need to receive the whole chat list and filter it manually by the field `chat.type`.
