### ISSUE TITLE
[CONSULTATION NEEDED] Receive new events more quickly

### ISSUE THREAD

**Issue by livelace** [tdlib/td#1486]
Hi. I have an app that just listening for new events (text, files etc.) in a loop. This app doesn't invoke any API methods, just listening. Ocaisonally some events can arrive with a huge delay (in coparison to mobile app), delay can reach tens hours.

Example:

1. Original event has timestamp - 2021-04-05 16:27:35 +0000 UTC
2. Delivered to the app - 2021-04-06 08:49:12 +0000 UTC

It looks like some actions might trigger all events delivering. 
**Question: how to decrease time (in a right way) for new events receiving ?**

**Comment by levlam** [comment]
Are you talking about `updateNewMessage` events or some other events?

**Comment by livelace** [comment]
>Are you talking about updateNewMessage events or some other events?

Yes.

**Comment by levlam** [comment]
Do you have TDLib's log with verbosity level 4 for the whole time frame from the original event to the time the message was received?

**Comment by livelace** [comment]
Nope. I think it would be a huge log file. But I have something interesting.

Consider such situation:

0. App and Mobile Client use the same number and work with the same set of channels.
1. A, B, C - public channels with new events (non-stop arriving).
2. X - special public channel for testing.

0. We don't have new events in App.
1. We go to Mobile Client and post something (random typing) in the channel X.
2. App! received new events from the channel A. B and C sent nothing.

**Comment by levlam** [comment]
Are you a mamber of the channels?

**Comment by livelace** [comment]
Yep.

**Comment by levlam** [comment]
How much active sessions does the account have?

**Comment by livelace** [comment]
Currently it's 6 devices. But I don't see correlation right now. Previously I thought the same and killed all sessions from Mobile Client and nothing had changed.

**Comment by levlam** [comment]
The described delay could happen if you had 10+ sessions.

**Comment by levlam** [comment]
You can also try to bring the account online by setting option "online" to true.

**Comment by livelace** [comment]
Could you expand landscape of the problem ?

**Comment by levlam** [comment]
There should be no problem if the user is a member of the channels and has less than 10 active sessions.

**Comment by borzovplus** [comment]
I'am a member of the channel and I have less than 10 active session (6), but I have problem that server client gets event updateNewMessage only if I read this message of desktop or mobile client

**Comment by livelace** [comment]
@borzovplus Have you tried to use different account ?

**Comment by borzovplus** [comment]
@livelace yea, other accounts work correctly. And moreover, what is very strange - this problem is not with all channels in problem account. I passed "online: true" in the parameters of tdlib now and checking (but it doesn't look like that's the problem). I also tried restarting and deleting it .tlg but it didn't help.

I'm completely confused ((

**Comment by levlam** [comment]
@borzovplus 1.6.0 is too old. You need to regularly update TDLib to keep receiving updates in time.

**Comment by livelace** [comment]
Well, 1.6.0 gave me immediate delivery inside testing channels and delayed delivering with other channels. I switched my app to 1.7.0 and messages now delivering fast, but I'm not sure why it's happening because:

1. I used to use multiple td clients withing one app (1.6.0).
2. 1.7.0 version has huge changes and [some of them](https://github.com/tdlib/td/issues/1242) have forced me to use only one td client per app instance.

**Comment by levlam** [comment]
None of these. You just need to update TDLib frequently regardless any changes in TDLib.

**Comment by livelace** [comment]
To be honest, I don't expect so huge differences between minor releases.

**Comment by levlam** [comment]
It doesn't depend on actual changes in TDLib at all.

**Comment by livelace** [comment]
>It doesn't depend on actual changes in TDLib at all.

Good to know. So, does it mean that "older" clients receive events more slowly by design (and bo doing this you force people to move to newer versions) ? 

PS. Just blink, if so :)

**Comment by levlam** [comment]
Yes, "older" clients doesn't receive events in big channels in real time, but this is completely unrelated to forcing someone to update their clients.
