### ISSUE TITLE
Permissions for "Replies" chat

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1488]
Currently, "Replies" chat's "permissions" have `can_send_messages` set to true,  however, if you send a message to the chat it results in an error.

Maybe set `can_send_messages` to false, so client won't have any specific treatment for "Replies" chat and handle permissions (and UI for them) as for ordinary chats, what do you think?

Thanks

**Comment by levlam** [comment]
The "Replies" chat needs some additional handling anyway, like support of the method `blockMessageSenderFromReplies`, so only the option "replies_bot_chat_id" was added instead. But you aren't the first to ask for this feature and the feature will not harm, so it was implemented in the recent master version.
