### ISSUE TITLE
getUser returns 'User not found'

### ISSUE THREAD

**Issue by leiniercs** [tdlib/td#1489]
Hello.

Every time I send the 'getUser' request, it returns an error with 'code = 6' (user not found). I'm using valid users id and I can correctly get the user information on Telegram app. Is there a procedure to achieve this?

**Comment by leiniercs** [comment]
I saw the class 'createPrivateChat' and I think it should be called first in order to send a message or get the user information, but, it returns the same error with 'code = 6' (chat info not found). I believe there is a procedure and I don't know which is.

If someone knows then tell me, please.

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/578.

**Comment by leiniercs** [comment]
Thank you. I already discovered that the client (the software using TDLib C++) needs to receive an interaction from that user, i.e.: message, newChat, etc. I solve this by forward a message from the user to the private chat of my bot, or to the group in which the bot is joined, and then I can invoke getUser method with success.

I'm closing this thread now. Thank you all.
