### ISSUE TITLE
TDlib for UWP

### ISSUE THREAD

**Issue by HolzingerAlexander** [tdlib/td#149]
When is the UWP Version of TDlib going to be released? It is already used by the open source third party client [Unigram](https://github.com/UnigramDev/Unigram), and seems to be stable enought to be released. Thank you in advance

**Comment by FrayxRulez** [comment]
I’d say duplicate: https://github.com/tdlib/td/issues/27

**Comment by levlam** [comment]
See [example](https://github.com/tdlib/td/tree/master/example/uwp) for TDLib SDK for Universal Windows Platform build instructions and usage example.
