### ISSUE TITLE
Questions about the MTProto ws connection

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#1491]
Hello, I am using the ws(s) protocol to communicate to Telegram through Cloudflare CDN (because I don't understand C++ and not proficient in cryptography, so I forward the MTProto TCP traffic directly to the WebSocket endpoint through the socks5 server) to bypass the censorship.

The problem now is that if the account is not logged in using this method to connect, it will be directly disconnected by the server during the handshake with code=4096/1000, reason=404 (all dc). And disconnected by media connection (dc2/dc4 ).

This seems to happen in the second phase of the handshake, I suspect.

About (...).web.telegram.org/apiws: It will check Host and return 302, so we directly resolve the domain name to the dc IP addresses.

Thanks if you are willing to explain.

**Comment by levlam** [comment]
Could you explain what exactly are you doing and the exact problem?

**Comment by nekohasekai** [comment]
@levlam I made a socks5 server, and directly forwarded the traffic as a websocket bytearray frame to the ip corresponding to the dc corresponding to the ip (via cloudflare proxy).

The problem is that without a login account, the connection will be closed continuously, websocket close code=4096/1000 reason=404

![20210412_092045](https://user-images.githubusercontent.com/56506714/114328867-7bc3bd00-9b70-11eb-802a-5d2b895c3a1a.jpg)

![20210412_092245](https://user-images.githubusercontent.com/56506714/114328921-a9106b00-9b70-11eb-80cc-898a9bf5c893.jpg)

In addition, if the media connection of dc2 and dc4 cannot be connected too, the handshake failure will be disconnected due to the same error.

**Comment by nekohasekai** [comment]
I seem to find some built-in URLs ending with /apiws in tdlib, but I haven't found how tdlib connects through ws. My implementation does not seem to be much different from MadelineProto?

**Comment by levlam** [comment]
You can't reliably match an IP address to the corresponding DC ID without external knowledge, so I'm not sure that this approach can work in practice. But besides that I don't see any reason for this to fail. Emscripten is capable to wrap raw TCP traffic into WebSocket traffic and back. TDLib never uses WebSockets directly, but this way it works in all browsers using Emscripten. If you would wrap the raw TCP data in the way Emscripten does, it should work.

**Comment by UjuiUjuMandan** [comment]
@nekohasekai 

I think @tehcneko misunderstood something here. He named this trick as [WSProxy](https://github.com/Nekogram/WSProxy), but there's no WebSocket used at all.

The Cloudflare relay is using standard HTTP transport defined here: https://core.telegram.org/mtproto/transports, pure HTTP POSTs.

I've tested with [NekoXProxy](https://github.com/UjuiUjuMandan/NekoXProxy) with WebSocket forward **disabled** in Cloudflare console and it still works.

**Comment by tehcneko** [comment]
What are you talking about? WSProxy is using WebSocket, your project is using a completely different method.
