### ISSUE TITLE
How to use EditMessageText() / EditMessageCaption()

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1495]
SendMessage() with ReplyToMessageId work fine, but EditMessageText() / EditMessageCaption() raise error: "5 Message not found"

example via https://github.com/zelenin/go-tdlib/issues/49
```go
	// fine
	dsc, err := tdlibClient.SendMessage(&client.SendMessageRequest{
		ChatId: dscChatId,
		InputMessageContent: &client.InputMessageText{
			Text:                  formattedText,
			DisableWebPagePreview: true,
			ClearDraft:            true,
		},
		ReplyToMessageId: getMessageId(srcChatId, srcId, dscChatId),
	})

	// error
	dsc, err := tdlibClient.EditMessageText(&client.EditMessageTextRequest{
		ChatId:    dscChatId,
		MessageId: getMessageId(srcChatId, srcId, dscChatId),
		InputMessageContent: &client.InputMessageText{
			Text:                  formattedText,
			DisableWebPagePreview: true,
			ClearDraft:            true,
		},
	})

	// error
	dsc, err := tdlibClient.EditMessageCaption(&client.EditMessageCaptionRequest{
		ChatId:    dscChatId,
		MessageId: getMessageId(srcChatId, srcId, dscChatId),
		Caption:   formattedText,
	})
```

Please help me!

**Comment by levlam** [comment]
You are passing a wrong message ID of an ID of unknown message.

**Comment by levlam** [comment]
If replied message isn't found, the message will be sent but it will not be a reply.

**Comment by comerc** [comment]
But SendMessage() with ReplyToMessageId work fine, when MessageId is the same. I see valid result:

![Снимок экрана от 2021-04-14 02-23-02](https://user-images.githubusercontent.com/1025241/114633008-75485900-9cc8-11eb-89de-49e654817bc3.png)

**Comment by levlam** [comment]
You can check TDLib's log to see exact message identifiers, which are sent in the requests.
Also see https://github.com/tdlib/td/issues/511 and ensure that you don't try to use temporary message identifier to edit messages.

**Comment by comerc** [comment]
It's work! Thanks :)
