### ISSUE TITLE
is there a way to use proxychains by tdlib

### ISSUE THREAD

**Issue by alirayaneh** [tdlib/td#1496]
i want to use tdlib bhind proxychains service to mang and controll proxys and
internet access in local network
is there a way to do it ?
 for example use tdlib for nodejs :
proxychains4 node telegram.js

**Comment by levlam** [comment]
Isn't it work out of the box?

**Comment by levlam** [comment]
If it doesn't work, you can ask TDLib to use a Socks5, an HTTP or an MTProto proxy, which can be enabled using the method [addProxy](https://github.com/tdlib/td/blob/9964d24ec8e03bd0bc4d5fe33438f056d133fc1a/td/generate/scheme/td_api.tl#L5211). You can pass a local proxy server to TDLib in that method.

**Comment by erik-888** [comment]
Привет

**Comment by alirayaneh** [comment]
no not work . 
thanks .
