### ISSUE TITLE
Get information about archived chats in 1.7.0

### ISSUE THREAD

**Issue by OlivierFreyssinet** [tdlib/td#1497]
Hi, I'm trying to update from 1.6.0 to 1.7.0 and so far all good but because of the breaking changes introduced with the ability to have multiple chats lists, I'm having trouble understanding if there is a straightforward way to know if a specific chat is archived.

This is how we used to do it before:
```java
    public static boolean isChatArchived(TdApi.Chat telegramChat) {
        if (telegramChat.chatList == null)
            return false;
        return telegramChat.chatList.getConstructor() == TdApi.ChatListArchive.CONSTRUCTOR;
    }
```

Now the `chatList` property is not available on `TdApi.Chat` — if I understand well, because now a chat can be in multiple chatLists ? — but then how would one do to determine if a specific instance of a TdApi.Chat represents an archived chat. Is that even still possible now without more context?

**Comment by levlam** [comment]
If a chat is in a known part of Archived chat list, it will have corresponding entry in the list of `chat.positions` with `position.list` being `chatListArchive`.

**Comment by OlivierFreyssinet** [comment]
Ah ok indeed that makes sense, for some reason I thought that positions was just an array of `int`, thanks for clarifying!
