### ISSUE TITLE
Playing video file while downloading file

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1498]
Official client has a feature to start viewing video file while the file is still downloading.
I can achieve same behaviour if `moov` atom is placed before `mdat` atom, however I definitely see official client playing video, where `moov` is a trailing atom.

For example, video file for this message (video content for this message even marked with "supports_streaming" property) - https://t.me/hype_videos1/15419
It has next layout:
```console
[ftyp] size=8+24
  major_brand = isom
  minor_version = 200
  compatible_brand = isom
  compatible_brand = iso2
  compatible_brand = avc1
  compatible_brand = mp41
[free] size=8+0
[mdat] size=8+5196669
[moov] size=8+60023
```

How official client do this?

Possible this is not the best place to ask, but I have no other place to ask, sorry

Thanks for your advice!

**Comment by zevlg** [comment]
Remote file-id for the example is "BAACAgIAAx0CRzJDzgACPDtgdwXKDplviQf9M7ZqNTvSvyDsPAACegoAAqKjqEukRxiWA9U90R4E"

**Comment by levlam** [comment]
"supports_streaming" means audio and video streams are interchanged. moov atom can be in the beginning or in the end of the video and both cases will be supported. Official clients use ffmpeg, which asks for specific parts of the file to play it. It likely scans the file and skips unneeded data to find moov atom, parses it and then begins to play the video, requesting data from mdat.

**Comment by levlam** [comment]
Between, remote file IDs can't be transferred between users. Only one user can use specific remote file ID.

**Comment by zevlg** [comment]
> "supports_streaming" means audio and video streams are interchanged. moov atom can be in the beginning or in the end of the video and both cases will be supported. Official clients use ffmpeg, which asks for specific parts of the file to play it. It likely scans the file and skips unneeded data to find moov atom, parses it and then begins to play the video, requesting data from mdat.

Oh, I think I got it!  It first downloads beginning and ending of the file searching for the `moov` atom and then only downloads parts of the file it needs to play media at the current seek position?

Can this logic be done using TDLib?  I'm now stick only to `downloadFile` method

**Comment by zevlg** [comment]
Yeah, I got it, if I request `downloadFile` with `offset` (at the end), temporary file will create gap in the file and fill ending with the fetched data.

Thanks

**Comment by levlam** [comment]
Yes, that is how `downloadFile` is supposed to be used for streaming.

**Comment by zevlg** [comment]
Just for my info: Is there any guarantee that parts of the file requested with higher download priority will appear first in the temporary file?

**Comment by levlam** [comment]
@zevlg You can have only one active download for a file. All subsequent `downloadFile` requests cancel previous one. Files with higher download priority will be downloaded first, but in-flight requests aren't canceled, so you may receive a few parts from another files first.
