### ISSUE TITLE
detecting first time chats

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [tdlib/td#1499]
Please is there a way to detect if a number is chatting with us for the very first time?

On Telegram desktop, we get a prompt to add the user, but we also see the user's messages.

I am unable to get messages from brand new users using tdlib.

My code is listening for this pattern presently:  `@type `= **updateNewMessage**

**Comment by levlam** [comment]
There is no such thing as "a prompt to add the user". Probably, you are talking about `ChatActionBar`, which exists purely for informational purposes.

Messages in all chats are received in absolutely the same way. There are no differencies between "old" and "new" chats.

**Comment by CharlesOkwuagwu** [comment]
Thanks for the reply.

I am unable to see `updateNewMesage `from new users, I am now logging `updateNewChat`, but I am not clear why I don't see the new chats on tdlib, the same messages show up on the Telegram Desktop.

I have deleted the Telegram Desktop Account, to ensure that the only active is tdlib, but still, no new messages, only `updateNewChat `is received.

**Comment by levlam** [comment]
Could you check in TDLib's log with verbosity level 3 that the `updateNewMesage` was sent?

**Comment by CharlesOkwuagwu** [comment]
I will check

**Comment by CharlesOkwuagwu** [comment]
> Could you check in TDLib's log with verbosity level 3 that the `updateNewMesage` was sent?

This client has all logs turned off for performance reasons.

**Comment by levlam** [comment]
I'm pretty sure that `updateNewMessage` can't be missed and the problem is somewhere else.

**Comment by CharlesOkwuagwu** [comment]
@levlam Hello, 

As a follow-up to the issue, I raised concerning first-time contact messages, see below a full log of the first few messages received from a new contact interacting with me for the first time.

The first updateUser comes without the contract's mobile number, and it is impossible for us to identify who the contact/customer is. Also, the first message comes in and we still have no mobile number or idea who this person is, hence initial messages like this are skipped.

In this case, I had to go to Telegram Desktop App and manually click the pop-up message `ADD Contact` before we finally started getting the mobile number attached to the Contact.

Please is there a setting or message I can send back direct from TDLib that will auto Add Contacts or am I missing something else?

See the attached.
[first.txt](https://github.com/tdlib/td/files/6598009/first.txt)

**Comment by levlam** [comment]
You can't know users phone number before added the user to contacts using the phone number. See https://telegram.org/faq#q-who-can-see-my-phone-number.

**Comment by CharlesOkwuagwu** [comment]
> You will not receive user's phone number before the user is added to contacts using the phone number, unless the user explicitly shared the phone number with you. See https://telegram.org/faq#q-who-can-see-my-phone-number.

Ok, that now makes sense
