### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#150]
Support .NET Core in C# implementation (https://github.com/tdlib/td/issues/27)

Update:
(For people coming from search: https://github.com/x2bool/tdsharp - TDLib JSON interface bindings for .NET)

**Comment by levlam** [comment]
It is impossible to do without some kind of serialization/deserialization, which is exactly what tdjson does. The binding also can be tried to be generated automatically using [CppSharp](https://github.com/mono/cppsharp), but I doubt that it will be more performant or easier to use than TDLib JSON interface.

**Comment by levlam** [comment]
@x2bool It seems that you have answered your own question. Thanks for creation of [tdsharp](https://github.com/x2bool/tdsharp). I've mentioned it in the [example list](https://github.com/tdlib/td/blob/master/example/README.md) as the best way to use TDLib from .NET Core.
