### ISSUE TITLE
Spontaneous UpdateDeleteMessages call

### ISSUE THREAD

**Issue by Vladislav-ux** [tdlib/td#1500]
Good time! I am using tdlight-api version 3.2.54. The application is running on the server. After the history of a certain dialog is loaded, the request is accepted from the telegram server by UpdateDeleteMessages. At that time, not a single message in the client's telegram was deleted. Please explain how this is possible?

**Comment by Vladislav-ux** [comment]
One more question. If all work with the Telegram server takes place on the server, then when transmitting TdlibParameters, do I need to set DeviceModel and systemVersion parameters for a specific phone or I can leave the Desktop in DeviceModel?

**Comment by levlam** [comment]
`UpdateDeleteMessages` can be sent when messages are unloaded from the memory. In this case `from_cache` field will be set to true. Also, if `is_permanent` is set to false, the messages aren't deleted for other users.
