### ISSUE TITLE
Telegram servers doesn't deliver spam/scam status in getUser method

### ISSUE THREAD

**Issue by leiniercs** [tdlib/td#1502]
Hello, TDLib developres.

It is happening that Telegram servers are not setting the variables related to scam/fake and I believe neither the verified/support. I have a bot and I checked this with two accounts: 45743297 (this was marked and recently released) and 680591055 (this is currently marked).

**Comment by levlam** [comment]
Why do you think so? Flags `user.is_scam` and `user.is_fake` contains the last known correct value.

**Comment by leiniercs** [comment]
Did you checked the two user ID I gave you in my previous message? Check them out and you will see.

**Comment by levlam** [comment]
It is not possible to check random user IDs.

**Comment by leiniercs** [comment]
Well, The last user ID is reported right now (he can not send message to non-contacts nor join new groups/channels) and the variables 'is_fake_', 'is_scam_' nor 'restriction_reason_' are filled.

**Comment by levlam** [comment]
"he can not send messages to non-contacts nor join new groups/channels" is completely unrelated to being "fake", "scam" or having "restriction_reason".

**Comment by leiniercs** [comment]
Okay. I understand. Closing the ticket. Thank you.
