### ISSUE TITLE
About FileId for GetAttachedStickerSetsRequest

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1504]
We have two variant: 

-		FileId: int32(convertToInt(messageVideo.Video.Video.Remote.Id)),
-		FileId: messageVideo.Video.Video.Id,

It is true?
```go
if messageVideo.Video.HasStickers {
	tdlibClient.GetAttachedStickerSets(&client.GetAttachedStickerSetsRequest{
		FileId: messageVideo.Video.Video.Id,
	})
}
```

Via [zelenin/go-tdlib](https://github.com/zelenin/go-tdlib)

**Comment by levlam** [comment]
You definitely can't convert Remote.Id to int32. You shouldn't try to trick type system. It's never needed to cast one type to another.

**Comment by comerc** [comment]
OK, thanks! But how to get AddedStickerFileIds via GetAttachedStickerSets() for InputMessagePhoto or InputMessageVideo?

**Comment by levlam** [comment]
If you didn't draw stickers on the photo/video, then you must not specify `AddedStickerFileIds`.
