### ISSUE TITLE
[Question] All possible errors scheme

### ISSUE THREAD

**Issue by pylakey** [tdlib/td#1507]
Hello 🤝

Is there a way to get and parse completed list of possible errors for each function of tdlib? It could be useful for catching exceptions more granularly

For example: 
searchPublicChat "request" could "return" an error with code 400 and message "USERNAME_NOT_OCCUPIED", so it could be useful to throw an exception such as UsernameNotOccupied and then catch only this type of exception for example

**Comment by levlam** [comment]
No, there is no way to do that. List of possible error messages is open and is often updated/extended. Nevertheless, you can handle some specific errors like "USERNAME_NOT_OCCUPIED".

**Comment by pylakey** [comment]
Thank you, but where can I get them if they are open?

**Comment by levlam** [comment]
The list of possible errors is "open", i.e. there is no list of returned errors, which is complete and fixed.

**Comment by pylakey** [comment]
Oh, sorry, misunderstood you.

Thanks for answer
