### ISSUE TITLE
Add support to build TdLib in .NET Core C#

### ISSUE THREAD

**Issue by Muaath5** [tdlib/td#1508]
When you build [`td/example/csharp/`](https://github.com/tdlib/td/tree/master/example/csharp), Then try to use it with **Any** .NET Core project (Winforms Or Console) you'll get the error below:

> **System.BadImageFormatException**: 'Could not load file or assembly 'Telegram.Td, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'

And I suggest to add support to build TdLib with .NET Core, because it's better than .NET Framework

**Comment by levlam** [comment]
`td/example/csharp/` is an example of building a managed DLL to be used from a C# project. If you need a native DLL to use it through PInvoke, you can build it as usual.

**Comment by Muaath5** [comment]
I fixed the issue.

The problem was that TdLib Libraries (`libssl-1_1-x64.dll`, `libcrypto-1_1-x64.dll`, `tdjson.dll` and `zlib1.dll`) **WASN'T** in the same folder that `"app.exe"` was in.

You should put all these in `/bin/x64/Debug` in Visual Studio.
Also you **shouldn't** make your project CPU type = `Any CPU`.

Thanks for TdLib.

**Comment by ContecHarry** [comment]
I have a similar problem with you.
I solved it using the following method.
```
1. Add CLR library (DLL) project to C# solution
2. Project Reference > Project > Solution > Select CLR library
```
