### ISSUE TITLE
My bot is not receiving the Telegram Passport updates

### ISSUE THREAD

**Issue by leiniercs** [tdlib/td#1509]
Hello, TDLib developres.

I have a bot, which invoke the Telegram Passport window on Telegram Desktop and after I press 'Authorize' button my bot is not receiving any updates.

Portion of Javascript code to invoke the Telegram Passport window on Telegram Desktop:
```
<script>
	Telegram.Passport.createAuthButton('telegram_passport_login_btn', {
		bot_id: 1250980023,
		scope: {
			data: [
				{
					type: 'identity_card',
					selfie: true
				},
				'personal_details',
				'address',
				'phone_number',
				'email'
			],
			v: 1
		},
		public_key: `-----BEGIN PUBLIC KEY-----\n..........\n-----END PUBLIC KEY-----`,
		nonce: 'another_key'
	}, {
		text: 'Authorize',
		radius: 6
	});
</script>
```

My development bot ID is: 1250980023

I set correcly the public key on @BotFather and Javascript code. What is happening? Is there a procedure to receive the updates and handle the Telegram Passport data in the bot?

**Comment by leiniercs** [comment]
I managed to get it work. Thank you all. Closing.

**Comment by chenshiwei100** [comment]
Can you explain why? I had the same problem
