### ISSUE TITLE
Massage id

### ISSUE THREAD

**Issue by Vladislav-ux** [tdlib/td#1510]
Hi! There is a problem with the fact that telegram returns different message ids for the same message. When a new message is sent to Telegram, the UpdateNewMessage receives a Message object with a single message id. When messages are deleted or edited, messages with different message ids are sent to Update Delete Messages or Update Message Content.

For my app, I need to make sure that when you delete or edit a message, the message id is the same as when you send it, otherwise I won't be able to change the message inside the app. Can you tell me how to solve this problem and what it is related to?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/511.

**Comment by zaxwed-8huzca-timrYq** [comment]
****
