### ISSUE TITLE
getMessages returns null as one of the message

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1511]
Sometimes `getMessages` methods returns `null` as one of the message, such as:
```
[ 3][t 4][1619118350.636655569][Td.cpp:4523][#1][!Td][&td_requests]	Sending result for request 1739: messages {
  total_count = 3
  messages = vector[3] {
    null
    message {
      id = 4410310656
      sender = messageSenderChat {
        chat_id = -1001361320510
      }
      chat_id = -1001361320510
      sending_state = null
 ...
```

is it ok?  Is this somewhere documented that `message` object can be `null`?  And what does it mean if message is `null`?

Thanks

**Comment by levlam** [comment]
Yes. This behavior is explicitly documented in the [description of the method `getMessages`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_messages.html) and in the [documentation of the class `messages`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1messages.html#aba32b0e1752646140e43e7e5f7931466).

**Comment by zevlg** [comment]
`null` means the message is inaccessible, right?

**Comment by zevlg** [comment]
> `null` means the message is inaccessible, right?

yeah, as documentation states.  Thanks!
