### ISSUE TITLE
Remote File

### ISSUE THREAD

**Issue by Vladislav-ux** [tdlib/td#1512]
I am interested in the question, does the tdlib api have the ability to upload a file to my storage? In general, I need to save images of chats in my storage. If I use the DownloadFile function, then in the UpdateFile handler I actually get the path to the file downloaded to a specific folder (parameters.databaseDirectory/profile_photos/). I could take this file and place it remotely on the storage. But I would like to know if it is possible to save a file remotely immediately, without downloading it locally?

**Comment by Vladislav-ux** [comment]
Do I understand correctly that the stdlib api does not allow you to get the path as a url to a photo stored on the telegram side?

**Comment by levlam** [comment]
TDLib can download files only locally.

Sent in Telegram files aren't available through HTTP.
