### ISSUE TITLE
how to mark the chat is read

### ISSUE THREAD

**Issue by lucian-ma** [tdlib/td#1513]

**Comment by lucian-ma** [comment]
when i open a chat , how can i get "updateUnreadMessageCount","updateUnreadChatCount" update

**Comment by levlam** [comment]
> how to mark the chat is read

You need to properly call `openChat`, `closeChat` and `viewMessages` for that. TDLib automatically marks viewed messages as read.

> when i open a chat , how can i get "updateUnreadMessageCount","updateUnreadChatCount" update

This is unrelated and you can't invluence receiving of these updates.
