### ISSUE TITLE
setChatMemberStatus throws error

### ISSUE THREAD

**Issue by Haaayk** [tdlib/td#1519]
I want to create a basic group and set administrator someone, but **setChatMemberStatus** throws error with error message **Administrators editing is disabled in the group chat**. When I manually set administrator someone, after that I can do it with tdlib. Here is my code:

```
this.client.invoke({
    _: 'setChatMemberStatus',
    chat_id: chatId,
    user_id: userId,
    status: {
      _: 'chatMemberStatusAdministrator',
      custom_title: '',
      can_be_edited: true,
      can_change_info: true,
      can_post_messages: true,
      can_edit_messages: true,
      can_delete_messages: true,
      can_invite_users: true,
      can_restrict_members: true,
      can_pin_messages: true,
      can_promote_members: true,
      is_anonymous: false,
    }
})
```

**Comment by levlam** [comment]
This error message doesn't exist in TDLib for more than 2 years. You need to update TDLib.

**Comment by Haaayk** [comment]
> This error message doesn't exist in TDLib for more than 2 years. You need to update TDLib.

**Comment by Haaayk** [comment]
> This error message doesn't exist in TDLib for more than 2 years. You need to update TDLib.

I have already updated TDLib to the latest version. But now this function throws error with message **Chats can't be members of basic groups**. What is wrong? Thank you.

**Comment by levlam** [comment]
You are passing a wrong value in the parameter `member_id`. You need to use `messageSenderUser` with a corresponding user identifier.

**Comment by Haaayk** [comment]
But there is no member_id in function arguments.
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_chat_member_status.html

**Comment by levlam** [comment]
There is in TDLib 1.7.4: https://github.com/tdlib/td/blob/ed291840d3a841bb5b49457c88c57e8467e4a5b0/td/generate/scheme/td_api.tl#L4420. On-site documentation is for the latest release version 1.7.0.

**Comment by Haaayk** [comment]
Thank you. It works)
