### ISSUE TITLE
GetRemoteFile always throws TdApi.Error object. 

### ISSUE THREAD

**Issue by Dhina17** [tdlib/td#1520]
It works fine before. Haven't done anything related to that. 

```

GetRemoteFile getRemoteFile = new GetRemoteFile();
getRemoteFile.remoteFileId = remoteFileId;
Client.client.send(getRemoteFile, new ResultHandler() {
            @Override
            public void onResult(Object object) {
                File remoteFile = (File) object;
                int localFileId = remoteFile.id; // here its null 
               // further actions.....
            }
}

```

**Comment by levlam** [comment]
`getRemoteFile` returns an error only if `remoteFileId` is invalid. It also returns, what is exactly wrong with the ID.

**Comment by Dhina17** [comment]
@levlam  It shows the same error for all the files. No idea why this happens for all files even it has correct. btw I m getting id from bot.

**Comment by levlam** [comment]
Do you have an ID example?

**Comment by Dhina17** [comment]
```
Audio  - CQACAgIAAx0CWJJjlAACBBxgiq5JU7jgcZTZZ1qCahe7ikniVgACIwwAAkfkcUqBl6heoTxd0R8E
Document (text) - BQACAgUAAx0CWJJjlAACBBFgiqrtQO96gmAfOJQJbrfWuomZjwAC1QEAAr_JiVRxt0TwP62nXx8E
```

**Comment by levlam** [comment]
These are correct remote file identifiers, which are accepted by `getRemoteFile` without any errors.

**Comment by Dhina17** [comment]
I got error with these IDs.

**Comment by levlam** [comment]
What TDLib version are you using?

**Comment by Dhina17** [comment]
1.7.3

**Comment by levlam** [comment]
You need to update to TDLib 1.7.4+ to be able to use remote file identifiers created by TDLib 1.7.4.

**Comment by Dhina17** [comment]
> You need to update to TDLib 1.7.4+ to be able to use remote file identifiers created by TDLib 1.7.4.

Ok let me try and close this issue after verifying. Thank you.

**Comment by Dhina17** [comment]
works fine after updating to 1.7.4+
