### ISSUE TITLE
How to get order of chats

### ISSUE THREAD

**Issue by rsommerfeld** [tdlib/td#1521]
Hi, I'm trying to update from v1.6.0 to v1.7.0.

According to the Getting Started section, the order should just be derived from the chat.positions_ attribute.

> The correct order of chats in chat lists is maintained by TDLib, so the Application only needs to listen to updates that change the chat.positions field and sort all chats by the pair (position.order, chat.id) in a given position.list

However, positions is always an empty array. I found the following description of getChats:
> Returns an ordered list of chats in a chat list. Chats are sorted by the pair (chat.position.order, chat.id) in descending order.

In fact, the order of the chats sorted by arrival of their updateNewChat events is correct. But once a message arrives / the order changes for other reasons, my application would have to derive the order again by itself, or query getChats again. Both wouldn't really contribute to a good architecture.

Is there something I have missed? How is the functionality of the order attribute now represented in 1.7.0?

**Comment by levlam** [comment]
Do you listen to and process all updates, which change the positions? You need to handle `updateChatPosition`, `updateChatLastMessage` and `updateChatDraftMessage` to maintain correct chat position in chat lists.

**Comment by rsommerfeld** [comment]
I missed the updateChatPosition one, thanks!

When the positions array of updateChatLastMessage and updateNewChat are empty (such as in my tests), what do I set the position of the chat to? Do I only update the chat position when they contain a non-empty positions array?

**Comment by levlam** [comment]
If it is empty, then the positions are unknown. Chats need to be placed in a chat list only if their positions are known.

**Comment by rsommerfeld** [comment]
Which means I only need the updates from updateChatPosition?

**Comment by levlam** [comment]
You need to handle `updateChatPosition`, `updateChatLastMessage`, and `updateChatDraftMessage` updates. As soon as chat position become known, one of these updates is sent.

**Comment by rsommerfeld** [comment]
Got it, thank you!
