### ISSUE TITLE
Worflow to receive a Call

### ISSUE THREAD

**Issue by tilibougnia** [tdlib/td#1522]
I worked in java environment. I find how to acceptCall, but I didn't find what I must do after send the TdApi.AcceptCall. 

Can you help me ?

**Comment by levlam** [comment]
When the call is ready to be used, you will receive a corresponding `upateCall` update with state `callStateReady` and need to use [tgcalls](https://github.com/TelegramMessenger/tgcalls) to send and receive voice data.

**Comment by tilibougnia** [comment]
Thanks @levlam 

But I'm in Java environnment so how I can use tgcall ?

**Comment by levlam** [comment]
You need a JNI wrapper for it as for any other native library. You should be able to find an example of such wrapper in the source code of the official Android app.

**Comment by tilibougnia** [comment]
Ok, so I will try in C++, did you have a sample ?

**Comment by levlam** [comment]
See https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/jni/voip.

**Comment by tilibougnia** [comment]
Thanks a lot :)
