### ISSUE TITLE
Using use_test_dc=true always results in PHONE_CODE_INVALID

### ISSUE THREAD

**Issue by tom-richter** [tdlib/td#1524]
What is the right way of using the Test Data Centers? I'm using alexander-akhmetov/python-telegram, but I think the issue is not with the python wrapper. I set `use_test_dc=True` and the entered 33333 for the example below because I used Datacenter 3.  ([Docs](https://core.telegram.org/api/auth#test-phone-numbers)) However I'm always getting an PHONE_CODE_INVALID. I tried different servers and phone numbers. Am I missing something? Do I have to set the Test configuration IP somewhere as a parameter? 

```python
from telegram.client import Telegram
tg = Telegram(
    api_id='1',
    api_hash='1',
    phone='9996639876',  
    database_encryption_key='changekey123',
    use_test_dc=True
)
tg.login()
params = {'offset_chat_id': 0, 'limit': 100, 'offset_order': 9223372036854775807}
result = tg.call_method('getChats', params)
result.wait()
print(result.update)
tg.stop()
```

![Screenshot from 2021-05-04 21-46-21](https://user-images.githubusercontent.com/68494402/117061577-aa255a00-ad22-11eb-880a-fa4d09e72e88.png)

**Comment by levlam** [comment]
Try "333333" instead.

**Comment by tom-richter** [comment]
Thanks, that solves it. I recommend that the docs should be updated from XXXXX to XXXXXX.

**Comment by levlam** [comment]
The documentation ignores the fact that authorization codes can be of different lengths. You receive expected code length in `authenticationCodeTypeSms.length` inside `authorizationStateWaitCode`.
