### ISSUE TITLE
Change chat history option

### ISSUE THREAD

**Issue by Haaayk** [tdlib/td#1526]
Can I change basic group's chat history option in settings?
I want to change chat history option from **hidden** to **visible**.

![photo_2021-05-05_16-33-16](https://user-images.githubusercontent.com/42375221/117183606-ca1f5100-ade8-11eb-9a5c-573efcb60d63.jpg)

**Comment by levlam** [comment]
Basic groups history can't be visible to new members. The option effectively upgrades the basic group to a supergroup, which can be done using the method `upgradeBasicGroupChatToSupergroupChat`.

**Comment by Haaayk** [comment]
Thank you. But I have one question. Can I handle new user join in supergroup by invite link?

**Comment by levlam** [comment]
What do you mean by "handle"?

**Comment by Haaayk** [comment]
Check when new user joined to group

**Comment by levlam** [comment]
Only bots have updates for these events.

**Comment by Haaayk** [comment]
I have already set webhook for my bot. But when someone joins the group via invite link telegram does not call to my API.
Webhook works successfully for another events.

**Comment by levlam** [comment]
If you are asking about Bot API, you can find all details about the updates in https://core.telegram.org/bots/api#march-9-2021.
