### ISSUE TITLE
Async requests show strange behaviour (C#) 

### ISSUE THREAD

**Issue by tuchkovnick** [tdlib/td#1529]
Hello everyone! 
Trying to get information using getChatAsync or getChatHistoryAsync methods I encountered a problem: the async methods just refuse to return a result in some cases and my program freezes. It's 100% not flood. 
In the log I see that there is the response I need, but my program somehow does not catch it . 
I also noticed that there is an [!GetChatRequest][&update_file] request from telegram right after my request to it (maybe it will help).

Hope someone will tell me what am I doing wrong.

**Comment by levlam** [comment]
All updates and request responses are handled in a dedicated thread. If you do a synchronous request during processing of an update or a request response, you block the thread, which results in exactly described behavior.

**Comment by levlam** [comment]
TDLib doesn't provide async/await interface itself. This is done by your wrapper. The default TDLib C# interface uses callbacks instead and all the callbacks are called in the same dedicated thread. Hence the wrapper must ensure that there are no deadlocks during processing of request responses.

**Comment by tuchkovnick** [comment]
I've understood my mistake. Im pretty new with the lib and have a lot to learn.
Thank you so much!
