### ISSUE TITLE
I want all messages from chat with getHistoryChat()

### ISSUE THREAD

**Issue by WolfAlm** [tdlib/td#1530]
I tried to follow this documentation: https://core.telegram.org/tdlib/getting-started and checked here issuses.

But I still don't understand. I need to download all messages from a particular chat. I'm sending a request first getChatHistory with last_message_id = 0. I expect to see the events of the UpdateNewMessage, but they are not. I realized that they were only for new messages. 

And because of this, I do not understand how to add messages and track from which message you need to go up? The only option I saw was in the handler when sending a request to server. Is it right? 

And when do I need to stop sending requests, when i get last message, so as not to go into infinite recursion? 

And from here: https://github.com/tdlib/td/issues/743#issuecomment-545042514, is the restriction the same now?

**Comment by WolfAlm** [comment]
> And when do I need to stop sending requests, when i get last message, so as not to go into infinite recursion?

I realized that I need to add all messages to Set, then check if the size has changed, and if so, call again. 

> And from here: [#743 (comment)](https://github.com/tdlib/td/issues/743#issuecomment-545042514), is the restriction the same now?

Just here, I put 1 second with the timeout, and I get messages all the same for 50, although the limit is 100, and offset -1, -5, -50. How do I get it to get 100 messages to get all the messages faster? How do I get the library to optimize to 100 messages per second?

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started#getting-chat-messages

**Comment by WolfAlm** [comment]
> https://core.telegram.org/tdlib/getting-started#getting-chat-messages

So there is nothing about my questions. I managed to get up to 100 messages if the timeout is set to 0.1 seconds instead of a second. But what about the end of parsing?

**Comment by levlam** [comment]
Timeout in receive is irrelevant to getting request responses. Probably, the whole https://core.telegram.org/tdlib/getting-started can help you.

**Comment by WolfAlm** [comment]
I figured it out and started receiving 100 messages a second. But, after a while, my account stopped receiving answers, although answers are still received from a friend's account. What could be the problem?

Log by my account: 
I compared the logs of accounts, I saw the difference only in these lines:

My account wait for auth:
```
[ 3][t 5][1620857913.844129085][NetQuery.h:244][#1][!MessagesManager][&net_query]	[Query:[id:2031616][tl:0xdcbb8260][state:Query]] [state:sent to main session multi proxy DcId{2}]
[ 3][t 5][1620857913.844146728][NetQuery.h:244][#1][!SessionProxy:2:main][&net_query]	[Query:[id:2031616][tl:0xdcbb8260][state:Query]] [state:SessionProxy:2:main: wait for auth]
```

Friend accout all ok:
```
[ 3][t 4][1620858247.615891695][NetQuery.h:244][#1][!MessagesManager][&net_query]	[Query:[id:851968][tl:0xdcbb8260][state:Query]] [state:sent to main session multi proxy DcId{2}]
[ 3][t 4][1620858247.615906476][NetQuery.h:244][#1][!SessionProxy:2:main][&net_query]	[Query:[id:851968][tl:0xdcbb8260][state:Query]] [state:SessionProxy:2:main: sent to session]
```

how to solve this problem?

**Comment by levlam** [comment]
Probably, you was logged out. Try to launch TDLib with log verbosity level 2 to check that.
