### ISSUE TITLE
Message forwarding

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1531]
Hello,

How can I forward a message so that it has a link to the original message. I used the forwardMessage method and it forwards the message but has no link to to the original message.

Note: I use the method as bot.

If it is not possible, could you please let me know if there is any method to edit a forwarded message  in a way that it get edited to all of my users.

**Comment by levlam** [comment]
There is no way to edit a message and all its forwards. If original message is in a public chat, you can send a link to the message instead.

**Comment by zyadomer98** [comment]
Okay How can I send a link to the message?

**Comment by levlam** [comment]
https://t.me/<username>/<message_id>

**Comment by zyadomer98** [comment]
How can I get the message_Id?

**Comment by levlam** [comment]
What do you pass to `forwardMessages`?

**Comment by zyadomer98** [comment]
Chat_id of the user that I want to forward the message to and the chat_id and message_id of the chat from which I am forwarding the message.

**Comment by levlam** [comment]
So you know the message_id of the forwarded message. If the chat from which you forward the message is a public supergroup/channel, then you can send a linkt to the message.

**Comment by Flohack74** [comment]
But @levlam aren´t the IDs in this case local tdlib IDs and so if I add them to a link the receiver wont be able to use it?

**Comment by levlam** [comment]
@Flohack74 
Apps must use `getMessageLink` to get a link to a message. The method documents for which messages it is possible to get a link. For most other link types apps are expected to use `getInternalLink` or other relevant methods.
