### ISSUE TITLE
Download photo

### ISSUE THREAD

**Issue by WolfAlm** [tdlib/td#1532]
I get all the chats, then I download their photos.  
I do this via DownloadFile(file.id, 1, 0, 0, true) where file is chat.photo.small. The download process is going well and I'm waiting for all the processes to finish, but for some reason after that I can't see the path to the files in the chats, but I start to see it after restarting application. how can I make it so that I can see it the first time?

**Comment by levlam** [comment]
You receive `updateFile` updates when information about a file changes. You need to update ChatPhoto cache using these updates.
