### ISSUE TITLE
Get user's first and last name with updateNewMessage

### ISSUE THREAD

**Issue by tom-richter** [tdlib/td#1533]
Hi, the updateNewMessage event only contains the sender's user_id:

`'sender': {'@type': 'messageSenderUser', 'user_id': 1769246852},`

Is it possible to get the user's first and last name with the same request or do I have to make a new request with getUser?  

It could be a parameter like this: `updateNewMessage(include_sender: true)`

**Comment by levlam** [comment]
No, you don't need any additional requests. See https://core.telegram.org/tdlib/getting-started.
