### ISSUE TITLE
Test Data Center - Test message sending if no chats present

### ISSUE THREAD

**Issue by tom-richter** [tdlib/td#1534]
Hi, we're experiencing some difficulties with the Test Data Centers. As far as I understand this concept, there are several phone numbers from which everybody can send and receive messages etc. From time to time all chats get cleared by Telegram. This makes testing a bit difficult because we don't know what we can expect. For example we've got a test for message sending. We're selecting the first chat where we have the permissions to send a new message. However, sometimes there are no chats and the test fails. Should we create a new chat before we send the message? What if this chat gets deleted by Telegram if it's currently used by our test? Is there something like a stable instance that always contains the same chats?

**Comment by levlam** [comment]
You need to register the account again and create the chat again if the account was deleted. You need a real account in test DC registered with a real phone number if you want it to persist longer and to be accessible only by you. But you will not be able to log in to such account automatically, so it will not be suitable for CI.

**Comment by levlam** [comment]
Also, if CI is public, anyone can use the same test account.
