### ISSUE TITLE
Method searchChatMessages specification error?

### ISSUE THREAD

**Issue by modestman** [tdlib/td#1536]
When I parsed the [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) file, I used the comment `may be null` to define Optional types for Swift language. 

In the method declaration `searchChatMessages`, I see comment for argument `sender` (row: 3954)
> `//@sender If not null, only messages sent by the specified sender will be returned. Not supported in secret chats`

This comment implies that `sender` may be null, but does not directly contain this keywords, and I cannot automatically mark the type of this argument as Optional in generated Swift code.

Please update the `@sender` comment for the `searchChatMessages` method in td_api.tl file to clearly understand whether the argument `may be null` or not.

**Comment by levlam** [comment]
Any direct or indirect function parameter can be specified to be null. In all function null objects are allowed by TDLib in incoming requests. Passing null may result in a valid or invalid request depending on the function or values of other parameters.

**Comment by modestman** [comment]
Ok. Thank you
