### ISSUE TITLE
getBasicGroupFullInfo returns None on valid basic_group_id

### ISSUE THREAD

**Issue by tom-richter** [tdlib/td#1539]
I retrieved the basic_group_id of a chat with getChat: `'type': {'@type': 'chatTypeBasicGroup', 'basic_group_id': 384597309}`
However if I call getBasicGroupFullInfo with basic_group_id=384597309 I get the response 'None'. (Using https://github.com/alexander-akhmetov/python-telegram). The strange thing is that getBasicGroupFullInfo does work in my case. What is missing here?

**Comment by levlam** [comment]
TDLib can't return anything like "None".

**Comment by tom-richter** [comment]
Ok, its an issue with python-telegram.
