### ISSUE TITLE
Bresh in a telegram on java

### ISSUE THREAD

**Issue by isopen** [tdlib/td#154]
Maybe it's not really about tdlib.
But I do not know where to write, therefore I write to you.
1. Log in from two clients telegram and telegram x.
2. Close customer telegram
3. Go to telegram x
4. End all active sessions via telegram x
5. Go to Telegram application
A layer with dialogs appears. A few seconds later is replaced by the entry form. 
Perhaps this is a small vulnerability of the user.
I would like to check the other way around.
But the official telegram application reports an unknown error.

**Comment by levlam** [comment]
That is expected behavior. There is no magic which can immediately log out all other client while they have no access to the Internet.

**Comment by isopen** [comment]
The fact is that access to the Internet is excellent.

**Comment by isopen** [comment]
It is safer to lead through a particular shape, but less convenient

**Comment by isopen** [comment]
It would be cool to see this in Telegram X
