### ISSUE TITLE
messages.uploadMedia

### ISSUE THREAD

**Issue by Maverick1983** [tdlib/td#1543]
How can I use this method with tdlib?

https://core.telegram.org/method/messages.uploadMedia

**Comment by levlam** [comment]
You can't use Telegram API methods with TDLib.

**Comment by Maverick1983** [comment]
I'm lost. What is the difference with Tdlib and API?

**Comment by levlam** [comment]
https://core.telegram.org/api#tdlib--build-your-own-telegram
