### ISSUE TITLE
send message: Have no rights to send a message

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#1544]
I use this lib to send messages to Group on telegram .and I often take a message like that 'Have no rights to send a message' when I send a message to a group.so any one can help me?

**Comment by levlam** [comment]
You receive this error when toy have no rights to send messages to the group.

**Comment by FunkyYang** [comment]
I want to get the time which until after times I can send message.I saw the PC client has that

**Comment by levlam** [comment]
If you have no rights to send messages, then this is likely a permanent restriction.

**Comment by FunkyYang** [comment]
not yet,I saw that tips on PC clients.and this message will be showed on message input area.and  some time after.I can send message continue.

**Comment by FunkyYang** [comment]
``` 
the admin of this group restricted you from writing message here until 21.06.01
```
this is tips

**Comment by levlam** [comment]
You can check supergroup.status.restricted_until_date, but in most cases it will be 0, i.e. the restrictions are permanent.
