### ISSUE TITLE
Would like to understand the cloud compatibility of a server side application to manage multiple accounts using tdlib

### ISSUE THREAD

**Issue by MKVoxsmart** [tdlib/td#1545]
Hello tdlib people,

I am currently working on building a solution that is going to be managing multiple user accounts using tdlib and capturing messages only on specific groups and persisting them in an external database.
I have so far managed to build this and test it such that it can listen for updates for multiple client sessions as a prototype.

Few Questions:

1: Though it requires file persistence for each user account, is it possible to change database_directory to handle an aws s3 resource instead of a local file path?
2: would like to understand the threshold of the users one process would be able to handle, would you be able to provide any guidance on it?
3: Also is it possible to provide a custom generator for the client id as currently the tdlib generates its own nativeClientId.
4: I have disabled useMessageDatabase, useChatDatabase, useFileDatabase, then does this reduce the amount of data it stores in the database?
5: If our application goes down what is the action needed to revive all the sessions, is there a specific function call provided we have access to all the directories etc?
6: Would you know of any strategy to be able to load balance the receipt of the updates, like can multiple consumers join a group to receive the updates..so that one node is not responsible for all the processing?

It will be really helpful if you could provide your guidance, as this is going to impact our decision making.

Thanks and Regards,
Masuma

Becoming a Telegram lover :)

**Comment by levlam** [comment]
1. No.
2. It is limited only by your server power.
3. This sounds useless and unrelated to TDLib usage.
4. There will be no SQLite database.
5. List of user accounts isn't managed by TDLib in any way.
6. This is not possible.

**Comment by MKVoxsmart** [comment]
Thankyou for your reply. That’s very helpful.

Also then a follow up question on that, I have observed with my testing that once the client session is established the directory is initialised and there are some files created. 

If then the application restarts and if the session is requested then the application starts receiving updates without the need of sending the auth code. So does this mean that the  presence of the initialised directory holds onto to the knowledge of credentials and so there is then no need to reauthenticate?

**Comment by levlam** [comment]
All needed data is managed by TDLib in the database_directory. TDLib is stateful as other Telegram clients and the data contains a lot of state-related information. You can't reuse the data without resetting the whole state, which would result in receiving again all messages from that state..

**Comment by MKVoxsmart** [comment]
That is very helpful. Thankyou.

**Comment by wind-hx** [comment]
@MKVoxsmart Have you migrated the database_directory file generated by TDlib to the remote database?

**Comment by wind-hx** [comment]
I am looking for a solution for horizontal expansion of TDlib server
