### ISSUE TITLE
.binlog file

### ISSUE THREAD

**Issue by Vladislav-ux** [tdlib/td#1546]
Good day! I have a question about the binary log file. It is created for each user in a specific folder structure. Now if I try to copy the .binnlog file, I will not be able to do it, since the file is in use. What should be done to stop the file? I understand that user logout request will help, but are there any other ways?

**Comment by levlam** [comment]
The binlog file isn't supposed to be copied. You can move the whole folder when the corresponding TDLib instance is closed.

**Comment by Vladislav-ux** [comment]
Can a file be paused?

**Comment by levlam** [comment]
No.

**Comment by Vladislav-ux** [comment]
I understood. Can you tell me how to solve the following problem? The tdlib api is used on the server, so when the user logs in, a folder with the file .binlog is created on the server, but when I rediploy the server the folder is deleted and as a result, the information that the user has entered the telegram, but has not yet left, is deleted. The banal way is to copy the file, but since it is not possible to copy this file, is it possible to save the user's session so that he does not have to log in again?

**Comment by levlam** [comment]
1. Close the TDLib instance and ensure that it isn't reopened.
2. Move the database directory.
3. Reinitialize the TDLib instance with new database directory.

**Comment by Vladislav-ux** [comment]
You said about closing the instance, but is there a way to close the instance without the user logging out?

**Comment by levlam** [comment]
[`close`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1close.html).

**Comment by Vladislav-ux** [comment]
Thanks! But I would like to clarify about the second solution. How can I move the database if the folder structure is created automatically after the user logs in using the path specified in the authorization parameters? If the api is running on the server, there is no way to make the user folder created somewhere outside the server.

**Comment by Vladislav-ux** [comment]
Thank you very much!
