### ISSUE TITLE
json unmarshal loss field value

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#1550]
when I receive a message from tdlib and message type is updateNewMessage,I saw the original string contains textEntityTypeTextUrl,but when I use tdlib.UpdateNewMessage to unmarshal it,I can't find which field contains textEntityTypeTextUrl,so any one could help.
this is the code
```
                               ack := &tdlib.UpdateNewMessage{}
				if err := json.Unmarshal(update.Raw, ack); err != nil {
					log.Printf("解码失败,原因:%s", err.Error())
					continue
				}
				log.Printf("会话id:%d", ack.Message.ChatID)
				switch ack.Message.Content.(type) {
				case *tdlib.MessageText:
					content := ack.Message.Content.(*tdlib.MessageText)
					if content.Text != nil {
						log.Printf("内容:%s", content.Text.Text)
						entityes := content.Text.Entities
						for _, e := range entityes {
							log.Printf("offset:%d,length:%d,type:%v", e.Offset, e.Length, e.Type)
							switch e.Type.(type) {
							case *tdlib.TextEntityTypeTextURL:
								eType := e.Type.(*tdlib.TextEntityTypeTextURL)
								log.Printf("URL:%s", eType.URL)
							}
						}
					}
				default:
				}
```
I can't get e.Type

**Comment by FunkyYang** [comment]
the third package is  go-tdlib(https://github.com/Arman92/go-tdlib)

**Comment by levlam** [comment]
If the field is returned by TDLib, this can't be a TDLib issue.

**Comment by FunkyYang** [comment]
yes ,I saw the receive chan ,and print origin bytes .could see that .but I use tdlib.UpdateNewMessage to unmarshal , the value loss
