### ISSUE TITLE
Unexpected messages after authorization

### ISSUE THREAD

**Issue by Vladislav-ux** [tdlib/td#1551]
Good day! Why do I receive messages from various dialogs in UpdateNewMessage immediately after authorization? For accounts with a small number of messages, I do not receive such messages, and if there are a lot of dialogs, then the problem occurs. Moreover, there is no connection between these messages and the dialogs, they can be either the last unread, or they have been read for a long time.

**Comment by levlam** [comment]
Send logs to @tdlib_bot in Telegram.

**Comment by levlam** [comment]
`updateNewMessage` is sent if a "new" message is received in a chat. "new" means that this is the last known message in the chat, after which there are no other messages. In supergroups and channels, this can be the latest message in the chat, regardless actual date, when the message was sent. For example, Bot API checks message date to skip such messages:
https://github.com/tdlib/telegram-bot-api/blob/bcd0c8eaa56920a951e3710671702a049157b706/telegram-bot-api/Client.cpp#L8728-L8731.

**Comment by Vladislav-ux** [comment]
Yes, I understand that I will solve the problem by checking the time when the message was sent. But I don't fully understand why updateNewMessage gets messages that aren't always the latest in history. Moreover, some messages may already be read. I repeat that messages start being received immediately after authorization.

**Comment by levlam** [comment]
If a supergroup/channel is received without the last message and the current state, then the state is automatically repaired by TDLib by fetching the latest updates in the supergroup. The last message in the supergroup then can be sent in an `updateNewMessage` update.
