### ISSUE TITLE
using GetCallbackQueryAnswer for answer reply throw error  error! code: %!d(float64=400) msg: Failed to parse JSON object as TDLib request: Unknown class ""

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#1553]
I use ``` GetCallbackQueryAnswer(ack.Message.ChatID, ack.Message.ID, &tdlib.CallbackQueryPayloadData{Data: mmType.Data}) ``` and return thus error,some one can help?

**Comment by levlam** [comment]
The error `Unknown class ""` means that you are parsing a request with invalidely specified "@type" as the empty string "". You need to debug your wrapper, which generates JSON request.

**Comment by FunkyYang** [comment]
yes ,you're riight
