### ISSUE TITLE
Can't finish ./build.sh on arm Mac

### ISSUE THREAD

**Issue by sapoepsilon** [tdlib/td#1555]
After installing all the dependencies and building OpenSSL for iOS, watchOS, tvOS, and macOS I am not able to build tdLIB. When I am running  `cd <path to TDLib sources>/example/ios
./build.sh`

I am getting this error. Am I getting this error because I have an M1 MAC, or am I doing something incorrectly ?
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [benchmark/check_tls] Error 1
> make[1]: *** [benchmark/CMakeFiles/check_tls.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 33%] Linking CXX executable rmdir
> ld: warning: ignoring file ../../../third_party/openssl/macOS/lib/libcrypto.a, missing required architecture arm64 in file ../../../third_party/openssl/macOS/lib/libcrypto.a (1 slices)
> [ 33%] Built target rmdir
> [ 33%] Linking CXX static library libtdapi.a
> [ 33%] Built target tdapi
> make: *** [all] Error 2
>

**Comment by levlam** [comment]
Yes, this is a possible reason, but it should affect only building for macOS and not other operating systems.

To build TDLib for macOS you can use https://tdlib.github.io/td/build.html. This will generate some required source files and you would be able to use the same source tree to build TDLib for iOS, watchOS and tvOS. You will need to remove macOS from the list of platforms in `build.sh` and `build-openssl.sh` and should be able to continue building of the `example/ios` after that.

**Comment by sapoepsilon** [comment]
Looks like I haven't paid close attention while I was building everything. Cmake can't find OpenSSL, although OpenSSL is installed. 

After cloning the library, I am creating `native-build` directory. And then when I am entering `cmake ..` I am getting this error:

> machinegun@Ismatullas-MacBook-Air native-build % cmake ..
-- Could NOT find ccache (this is NOT an error)
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) 
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libz.tbd
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) 
CMake Warning at CMakeLists.txt:167 (message):
  Can't find OpenSSL: stop TDLib building

**Comment by levlam** [comment]
OpenSSL isn't needed for source code generation. Now you can run native build with `cmake --build .` and continue to build TDLib for iOS/watchOS/tvOS.

**Comment by sapoepsilon** [comment]
I don't know man... I could not build it. Nevertheless, thank you for your help.
