### ISSUE TITLE
copyMessage like Bot Api?

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1556]
Hello

Is there any method in tdlib to copy messages like that one in the bot api?
<img width="840" alt="Screen Shot 2021-06-04 at 3 16 55 PM" src="https://user-images.githubusercontent.com/78375592/120800297-723f4b80-c548-11eb-9728-20c2af959ad3.png">

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/1538.

**Comment by zyadomer98** [comment]
Mr. Levlam it is really difficult to understand it. I am using this library for nodejs https://github.com/Bannerets/tdl. Do you know how to do the process with that library?

**Comment by levlam** [comment]
See Bot API implementation. The API is the same in Node.JS and C++.

**Comment by zyadomer98** [comment]
https://user-images.githubusercontent.com/78375592/120817264-3d3bf480-c55a-11eb-9bd9-8be76992e49d.mov

**Comment by zyadomer98** [comment]
I cannot find that method there.

**Comment by zyadomer98** [comment]
Thanks I could solve it
