### ISSUE TITLE
How to Handle loggingOut?

### ISSUE THREAD

**Issue by v4to** [tdlib/td#1559]
Hi. For example I successfully authorized on one device using tdlib and later i closed this session on other device. After that i'm receiving only authorizationLoggingOut update. In this state I can't requestQrCode. How can I reset authorizationState and start all over again?

**Comment by levlam** [comment]
TDLib instance can't be reused. You need to create a new TDLib instance after this one is completely closed.

**Comment by v4to** [comment]
Thanks. That works. Another question. When I try to log in account with 2 step verification enabled and I terminate session on other device while waiting password, my authorizationState gets stuck on authorizationStateWaitPassword. I don't receive any new updates. How do I know on this so-called half finished authorization step that user terminated session on other device?

**Comment by levlam** [comment]
You will receive `authorizationStateLoggingOut` after the first server-side request, for example, a try to enter a password.

Also, check that you use the latest TDLib version, because this specific transition was broken and then fixed recently.
