### ISSUE TITLE
ignore auto download files

### ISSUE THREAD

**Issue by sajjad-ser** [tdlib/td#156]
hi
how can i ignore auto downloading files like photo?

**Comment by levlam** [comment]
Smallest photo size is always available along with the photo. It is part of a message, so it is not possible to prevent it downloading.

**Comment by levlam** [comment]
TDLib 1.3.0 has new writable option `ignore_inline_thumbnails` which can be used to prevent file thumbnails sent by the server along with messages from being saved on the disk.
