### ISSUE TITLE
Mtproto Warning - Type not Found

### ISSUE THREAD

**Issue by BelgenOp** [tdlib/td#1560]
I am using a Mtproto Telegram Lib, which is in python.
I have justed updated its layer to 129 and getting  Mtproto Warnings 

Trace back is Pasted Here - https://del.dog/raw/inefuttupi

It's there something missed while updating Layer? Or am I at wrong place asking for this? 
Can any pls guide me, where should I go and ask for this?

**Comment by BelgenOp** [comment]
@levlam , sorry for mentioning, but can u check please

**Comment by levlam** [comment]
I can't help with a third-party MTProto library.

**Comment by BelgenOp** [comment]
I have asked it's owner too, he replied - "Telegram is sending something unexpected"

And I am getting this log on layer 129, maybe I am bit sure, it's something related to updates with Voice Call

**Comment by levlam** [comment]
There is no layer 129 yet. It isn't released.
