### ISSUE TITLE
GetMessage() with empty title link

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1562]
[This message](https://t.me/Full_Time_Trading/46292) have link with empty title (if copy text with desktop client via clipboard):

>🇺🇸🚘 ЧИНОВНИКИ ПО КРАЙНЕЙ МЕРЕ ДВУХ ПРАВИТЕЛЬСТВЕННЫХ УЧРЕЖДЕНИЙ В ПЕКИНЕ И ШАНХАЕ ПОЛУЧИЛИ УСТНЫЕ ИНСТРУКЦИИ ОТ НАДЗОРНЫХ ОРГАНОВ НЕ ПАРКОВАТЬ СВОИ ЭЛЕКТРОМОБИЛИ TESLA $TSLA НА РАБОТЕ
>
>👉 Сотрудникам некоторых китайских правительственных учреждений было приказано не парковать свои автомобили Tesla Inc внутри правительственных зданий из-за проблем с безопасностью из-за камер, установленных на транспортных средствах.
>
>📅 В марте автомобилям Tesla было запрещено въезжать на некоторые военные комплексы в Китае, ссылаясь на опасения по поводу безопасности автомобильных камер.
>
>🇺🇸 Это ограничение является новым свидетельством сохраняющейся настороженности Китая по отношению к американскому производителю электромобилей на фоне напряженности в отношениях с Вашингтоном.
> (https://tesla-cdn.thron.com/delivery/public/image/tesla/56cb8c41-e898-44ce-b6b7-fe9b9a05f529/bvlatuR/std/1200x628/MS-Social)
>📣 Илон часто комментировал ценность данных, которые собирают автомобили Tesla, которые могут быть >использованы для разработки автономного вождения.
>
>🚙 Через несколько дней после мартовского запрета на автомобили Tesla в военных комплексах Маск появился на китайском форуме, заявив, что если Tesla использует автомобили для шпионажа в Китае или где-либо еще, она будет закрыта.

But `getMessage` not have entity for this link and `getMarkdownText` not have link too.

**Comment by levlam** [comment]
What exactly do you mean?

**Comment by comerc** [comment]
I have many similar cases. [Other message](https://t.me/Full_Time_Trading/50135) have link for https://www.finversia.ru/site/public/files/24/23616-analitika_16.03.2021_3.jpg (and shown it as preview)

> What exactly do you mean?

getMessage not have entity for this link and getMarkdownText not have link too.

**Comment by levlam** [comment]
TDLib doesn't allow entities, which contains only new line characters.

**Comment by comerc** [comment]
But Telegram work with this markdown hack. And I cannot copy messages like this with preview.

**Comment by levlam** [comment]
It was intended behavior, but it doesn't solve issues it was supposed to solve. Therefore, in the latest TDLib version 1.7.5 TextUrl entities are allowed to contain only new line characters.
