### ISSUE TITLE
getMarkdownText for link

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1564]
### Case 1

if source text:
```md
[qqqq](https://t.me)
```
then `getMarkdownText` work fine:
```md
[qqqq](https://t.me)
```

### Case 2

but if source text with escaped square brackets:
```md
[\[qqqq\]](https://t.me)
```
then `getMarkdownText` work wrong:
```md
[qqqq]
```

**Comment by levlam** [comment]
`getMarkdownText` returns a user-friendly formatted Markdown text by an ordinary formatted text. It doesn't receive anything like "[\[qqqq\]](https://t.me)".
