### ISSUE TITLE
Can't send message after running for a long time

### ISSUE THREAD

**Issue by eos1d3** [tdlib/td#1566]
I always find a problem for TDLib Java for my applications. Two accounts running with two different applications separately show the same problem.

Usually after running for around 1 -2  weeks, it can't send message at all. And restart will fix the problem. But it is strange that after restart, the previous  message(s) which can't be sent will appear immediately automatically without resending again. This happened so many times already and I can't find any cause for this.

I also find `haveAuthorization` is already true.

Any suggestion for this issue?

**Comment by levlam** [comment]
What do you mean by "it can't send message at all"? What exactly happens? Do the messages stuck in the `messageSendingStatePending` state or something other?

**Comment by eos1d3** [comment]
Hi,

This is the method to send message:

```
public static void sendMessage(long chatId, String message, CommandResultHandler resultHandler) {
	TdApi.InputMessageContent content = new TdApi.InputMessageText(new TdApi.FormattedText(message, null), false, true);
	client.send(new TdApi.SendMessage(chatId, 0, 0, null, null, content), resultHandler);
}
```

When the problem happens, the above method still returns normally without causing any exception. But the message is not appeared. If I send other messages, all these messages can't be seen too until I shutdown and restart the application. 

The strangest thing is that Telegram server have all these messages pending. When I restart the application, all these messages will then be released and appear. Of course my application does not resend them.

I do not know what `messageSendingStatePending` is. But it is likely to be related to this issue. How can I check with this?

Thanks!

**Comment by levlam** [comment]
A message returned by `sendMessage` is yet unsent and has a temporary message ID, because persistent message ID can be assigned only by the server. You need to handle `updateMessageSendSucceeded`, `updateMessageSendFailed` and `updateDeleteMessages` updates as described in https://core.telegram.org/tdlib/getting-started to correctly handle message sending.

If you send a message to a private chat after the client wasn't used for a long time, the message can be sent only after the client state is synchronized with the server and the connection state doesn't change to `connectionStateReady`. This could take some time, if you have a lot of private messages.

**Comment by eos1d3** [comment]
These do not seem to really explain the problem.

Firstly, for handling send message updates (`updateMessageSendSucceeded`, `updateMessageSendFailed` and `updateDeleteMessages`) none of these can make the message send finally even I wait for hours. I understand that they are useful to know the send message results. But the only way to fix the issue is restarting the application as I can do.  Without a restart, all messages sent by the application can't be seen at all even wait for many hours.

I just check `messageSendingStatePending`,  it shows message has not yet been delivered to the server. But waiting for max 10 hours can't see the message.

And I send at least one message to a private supergroup per day by this application. So does it caused by "the client wasn't used for a long time" ?

Finally for `connectionStateReady` issue, even waiting for 10 hours, the messages are not shown until a restart. How can I force client state to be synchronized if this is the root cause?

And the group messages are around 100-200 per day. So this does seem to be the issue with too many messages.

The hint is the restart fixs the problem and all messages will immediately appear. So what is the likely cause?

**Comment by levlam** [comment]
> I send at least one message to a private supergroup per day by this application.

It doesn't matter how much messages is sent by this application, the total number of messages sent and received in private chats and small groups does matter.

Could you collect TDLib log with verbosity level 4 from the time application is started and up to one minute after the connection state is changed to `connectionStateReady`, but the message isn't actually sent and send it to @tdlib_bot in Telegram?

**Comment by eos1d3** [comment]
Sure! I will try to collect TDLib log. But I need to wait for this issue as it usually takes more than a week to happen. 

Thank you!

**Comment by levlam** [comment]
@eos1d3 Did you manage to reproduce it?

**Comment by eos1d3** [comment]
Reproducing this problem is very easy as it always happens. But for safety issue, I do not run them recently. I have one log file after the issue was found. The issue caused ForwardMessage failed, but not SendMessage. I will send the log on coming Monday.

I will test this issue later.

**Comment by levlam** [comment]
@eos1d3 Do you still have the issue?

**Comment by mrbesen** [comment]
> A message returned by `sendMessage` is yet unsent and has a temporary message ID

This should be updated in the [sendMessage](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html) docs. Currently it says:
> Returns the sent message.

That is quite confusing and i found it sometimes never returns at all.
