### ISSUE TITLE
GPlv3 license violation in one of the introduced libraries

### ISSUE THREAD

**Issue by tdlua** [tdlib/td#1568]
Hello sir, I have contacted you with permission from [giuseppeM99](https://github.com/giuseppeM99).

In the "[Using TDLib in Lua projects](https://github.com/tdlib/td/blob/master/example/README.md#lua)", among the list of Lua libraries there is one library called [luagram ](https://github.com/Luagram/LuagramProject) and it's based on [tdlua](https://github.com/giuseppeM99/tdlua), but it violated GPLv3 license because:

1) They stole [giuseppeM99](https://github.com/giuseppeM99)'s code.
2) They edited the code a bit to remove any trace of [tdlua](https://github.com/giuseppeM99/tdlua), and they renamed [tdlua ](https://github.com/giuseppeM99/tdlua)to [luagram](https://github.com/Luagram/LuagramProject).
The developer of [tdlua ](https://github.com/giuseppeM99) knows this because he had to de-compile the binary they gave and he checked that the functions name are the same as in [tdlua ](https://github.com/giuseppeM99/tdlua) and that they just changed the prefix [tdlua ](https://github.com/giuseppeM99/tdlua) with [luagram](https://github.com/Luagram/LuagramProject), eg the function _tdlua_send_ has been renamed to _luagram_send_.
3) Then they uploaded just the binary under their name and they didn't mention [giuseppeM99 ](https://github.com/giuseppeM99) anywhere and they didn't disclose the source code of their project too.

I raised an issue on [their github page](https://github.com/Luagram/LuagramProject) a few hours ago, **they currently deleted the repo**.
I'm kindly asking you to remove [luagram ](https://github.com/Luagram/LuagramProject) from the [readme file](https://github.com/tdlib/td/blob/master/example/README.md#lua) and other places until they fix the GPLv3 violations.

**Comment by levlam** [comment]
Given that the link doesn't work anymore, it can be safely removed.

**Comment by tdlua** [comment]
It is still there.

**Comment by levlam** [comment]
And it will be there until the next TDLib 1.7.5 update.
