### ISSUE TITLE
QMake, C++ and undefined references

### ISSUE THREAD

**Issue by N1coc4colA** [tdlib/td#1569]
Hi, it's my first time with TDLib. I compiled using the way proposed by the automated generator for the build, and I tried to build it by my own too (as it usually works).
But all the time I want to use it, I get: "undefined reference to `td::Scheduler::instance()`". TDLib Client lib gets built as a static one (*.a), I have all the libraries included (openssl, zlib, tdlib...).
And I just don't understand the undefined reference, it is the 1.7.0 tdlib version, with g++ version 8.3.x
I'm trying to compile the C++14 example (but still using QMake). The example works perfectly, but not when I try to use QMake...
: [
If you have any tips

**Comment by levlam** [comment]
td::Scheduler::instance() is in `libtdactor.a`.

Between, what is your OS?

**Comment by N1coc4colA** [comment]
Deepin 20, Qt 5.15. But I changed to full CMake. QMake have strange behaviour with this library (I had no issue with other C/C++ libs and pkgconfig). Btw did not tell it, but I used pkgconfig to link the libs to my project

**Comment by levlam** [comment]
We automatically generate pkgconfig files using CMake, which should be always correct.

**Comment by Flohack74** [comment]
If you want an example of how to build with CMake we have TELEports here: https://gitlab.com/ubports/apps/teleports/-/tree/master - Though its using a tool called clickable on top of CMake, you could trace the necessary settings for a successful build.
