### ISSUE TITLE
messages.deleteHistory for channel

### ISSUE THREAD

**Issue by OleksiyMoroz** [tdlib/td#157]
messages.deleteHistory will return "invalid peer id" if try clean history of the Channel. Any way to delete messages in the channel using API?

**Comment by levlam** [comment]
messages.deleteHistory isn't a TDLib method. And as clearly stated in description of deleteChatHistory, it "Cannot be used in channels and public supergroups". Channels can be only deleted along with the chat through deleteSupergroup method.

**Comment by OleksiyMoroz** [comment]
@levlam Thank you for the answer. But admin can delete channel messages by himself, how its possible then?

**Comment by OleksiyMoroz** [comment]
@levlam 
Methods that presented here https://core.telegram.org/methods, are they show the latest Layer?

**Comment by levlam** [comment]
It isn't TDLib methods. TDLib documentation is [here](https://core.telegram.org/tdlib/docs/) or [there](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) if you prefer a text file. Messages can be deleted using `deleteMessages` method.
