### ISSUE TITLE
is it posible to decompile libtdjni.so (JNI interface ) and convert it to tdlibjson.so ?

### ISSUE THREAD

**Issue by alirayaneh** [tdlib/td#1570]
is it posible to decompile libtdjni.so (JNI interface ) and convert it to tdlibjson.so ?
i have a compiled JNI inteface named libtdjni.so 

Which is very customized. But I got lost that  sources
Now I want to launch a web client based on nodejs. 
how to decompile or convert or re use it for node js?

**Comment by levlam** [comment]
This is not possible.
