### ISSUE TITLE
Add in the documentation if method can be used by bots or not

### ISSUE THREAD

**Issue by Muaath5** [tdlib/td#1571]
Please add in the documentation if this method can be used by bots, Or not.
Because some methods can't be used by bots that authenticated with bot token.
This feature is already implemented in [Telegram API docs](https://core.telegram.org/api), See [an example](https://core.telegram.org/method/channels.getMessages).

I imagine it like this in the documentation:

> # `sendMessage` method
> some description, bla bla ....
> ### Parameters
> ### This method can be used by bots

**Comment by levlam** [comment]
The documentation is oriented toward ordinary users. This will not be documented to reduce documentation size and simplify documentation usage. You still can check whether specific method is available for bots by looking in the source code of td/telegram/Td.cpp and checking, whether corresponding on_request method has no "CHECK_IS_USER();".

**Comment by Muaath5** [comment]
@levlam, What about adding an option to `split_source.php` if created documentation should has Bots information or Not?

**Comment by levlam** [comment]
@Muaath5 
Documentation is not created from nowhere. It is written in https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.
