### ISSUE TITLE
Include used invite_link in supergroup, identical to private groups

### ISSUE THREAD

**Issue by khmikkelsen** [tdlib/td#1573]
Currently, when new members join a private group using an invite link, the link they used is listed under `update.chat_member.invite_link`.

However, if the group is a supergroup, this attribute is not passed on. 

Expected behavior:
`update.chat_member.invite_link` should be present with the used invite link regardless if the group is a supergroup or private.

**Comment by levlam** [comment]
If new member joins a public group using an invite link, then the invite link is also included in the update. You can check this by using `joinChatByInviteLink` request from TDLib. It is a specific app, which directly joins the public group, instead of joining it via invite link.

**Comment by khmikkelsen** [comment]
Resolved [here](https://github.com/tdlib/telegram-bot-api/issues/148#issuecomment-870985673)
