### ISSUE TITLE
GetSupergroupMembers don't returning chat members user_id

### ISSUE THREAD

**Issue by gabigart** [tdlib/td#1574]
I'm trying to get all members of a chat via GetSupergroupMembers, I get all ChatMember list but each ítem only contains the JoinChatDate and I need the UserID.

**Comment by levlam** [comment]
See the latest TDLib API scheme: https://github.com/tdlib/td/blob/e1ebf743988edfcf4400cd5d33a664ff941dc13e/td/generate/scheme/td_api.tl#L496.
