### ISSUE TITLE
inlineKeyboardButtonTypeCallback not work when Turn page some time

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#1575]
inlineKeyboardButtonTypeCallback not work when Turn page some time,then I click the next page on Desktop Manual then it works,I debug it ,and next tags [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] it works,and [20,22,24] need  Manual click

**Comment by levlam** [comment]
You must take callback data from the inline keyboard object.

**Comment by FunkyYang** [comment]
yes I did

**Comment by levlam** [comment]
Then there should be no problems if you have the latest message version. And to have it, you must have the chat with the message open.

**Comment by FunkyYang** [comment]
you means execute ```OpenChat``` when I send message to chat after

**Comment by FunkyYang** [comment]
that sounds block.and click next page will be ok,?

**Comment by FunkyYang** [comment]
I request Frequent?

**Comment by levlam** [comment]
I don't understand.
