### ISSUE TITLE
C++ MessageContent crash 1.7.0

### ISSUE THREAD

**Issue by N1coc4colA** [tdlib/td#1577]
Hi, I'm using C++14 with TD 1.7.0. I'm trying to do a small client for users. I can get the chats properly but all the time I try to access:
td::td_api::message::content_ (td::td_api::MessageContent), my app just crash, and I just don't see why. Here is my sample:

`
    //The messages comes from getChatHistory
    std::cout << "Adding an msg!" << std::endl;
    td::td_api::message *object = std::move(msg);
    if (!object->content_) {
        std::cout << "Invalid MSG content :/" << std::endl;
        return;
    }
`

Just trying to access the message's content causes a crash...
If you have a tip or anything...

**Comment by levlam** [comment]
The line
```
td::td_api::message *object = std::move(msg);
```
have no sense. What are you trying to move there?

**Comment by N1coc4colA** [comment]
I tried std::move here, that was just a try... My function:
`
void MSList::handleNewMessage(td::td_api::object_ptr<td::td_api::message> &msg)
 /*What I sent*/
}
`
But with or without the std::move, it gives the same (and I know this try was dumb as I use &).

**Comment by N1coc4colA** [comment]
So I tried to debug. And all the outputs says that accessing any method of td::tl::unique_ptr<typename T> cause a crash, seems to be the reason why I can't access td::td_api::MessageContent from td::td_api::message. But I don't know why...

**Comment by levlam** [comment]
It seems that `msg == nullptr` in your code.

**Comment by N1coc4colA** [comment]
Ok, so I checked in all my code and the issue was in the use of T *ptr, td::td_api::object_ptr<T>::get() and other stuff. Now works well, unique_ptr are sometimes a mess for me, sry :/ All is good in your lib :+1:
