### ISSUE TITLE
How do I log in with my account and password

### ISSUE THREAD

**Issue by Android-Distance** [tdlib/td#1578]
How do I log in with my account and password

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started

**Comment by Android-Distance** [comment]
I found the verification `code login` and `url login` in the document, but did not find the `password login`
* machine translation *

**Comment by levlam** [comment]
There are no such things as "code login" and "url login". https://core.telegram.org/tdlib/getting-started contains all relevant information.
