### ISSUE TITLE
Unable to download large files

### ISSUE THREAD

**Issue by wh3r3areyou** [tdlib/td#1580]
If you receive a message containing a video, image or other files larger than 17 MB, then this error occurs:
[ 0][t 4][1623680187.638983726][Binlog.cpp:667][#1][!Td][&fd_size_ == detail::file_size(path_)]

**Comment by KaoriEl** [comment]
pizdec realno

**Comment by wh3r3areyou** [comment]
@levlam Linux, but the fact is that when uploading small images, everything works well, and when uploading large files, the process crashes with such an error

**Comment by levlam** [comment]
These events are unrelated. The problem is somewhere in the filesystem used by your docker container.
