### ISSUE TITLE
Some messages aren't displayed in the group chat

### ISSUE THREAD

**Issue by MarcAnt01** [tdlib/td#1581]
I noticed that Unigram started to loose some messages, I created this ticket in Unigram repository, but Fela told me to reach out to you
https://github.com/UnigramDev/Unigram/issues/2433

**Comment by levlam** [comment]
Does the messages appear when you reply them from another client?

**Comment by MarcAnt01** [comment]
@levlam as you can see from the ticket, they're properly displayed from Telegram for iOS

**Comment by levlam** [comment]
@MarcAnt01 This doesn't mean anything.

**Comment by MarcAnt01** [comment]
Do you need to know if they are displayed properly from another client? I can check in case

**Comment by levlam** [comment]
I need to know, whether they appear in Unigram after being replied.

**Comment by MarcAnt01** [comment]
> I need to know, whether they appear in Unigram after being replied.

They have showed up

**Comment by levlam** [comment]
Good. The cause can be found only if there is a log with verbosity level 4, covering the time when the messages were sent.

**Comment by MarcAnt01** [comment]
I'll keep an eye on that, to see if this happens again 👌

**Comment by levlam** [comment]
This can't be investigated further without logs. Please create a new issue, if this happens again and there will be TDLib logs available.

**Comment by MarcAnt01** [comment]
I'll open an issue again in case it happens, but haven't experienced that any longer
