### ISSUE TITLE
Please tag 1.7.3

### ISSUE THREAD

**Issue by yurivict** [tdlib/td#1582]
This commit changed the version: https://github.com/tdlib/td/commit/302e5940d4bf6c1299673dd05ee926f945d82cc3

But it isn't tagged,

**Comment by levlam** [comment]
This commit isn't recommended for anyone to use. Use the latest version from master instead.

**Comment by yurivict** [comment]
```CMakeLists.txt``` in ```master``` now says that the version is ```1.7.4``` but the latest tag is ```1.7.0```.

**Comment by levlam** [comment]
Yes. See https://github.com/tdlib/td/issues/1403 for the explanation.
