### ISSUE TITLE
Please allow shared libraries

### ISSUE THREAD

**Issue by yurivict** [tdlib/td#1584]
Currently all built libraries are static due to the ```STATIC``` keyword added to all ```add_library``` instructions.

Without such keywords cmake allows to control what kind of libraries to build with ```BUILD_SHARED_LIBS```, see https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

It's better to leave the control over library kind to the user.

**Comment by levlam** [comment]
All TDLib interface libraries can be built as shared libraries using `BUILD_SHARED_LIBS`. The user has a full control over that.

You will need also to apply https://github.com/tdlib/td/pull/1542 to fix linking with `tdapi` library.

**Comment by levlam** [comment]
The mentioned pull request was applied, so `BUILD_SHARED_LIBS` should again work out of the box.
