### ISSUE TITLE
how can I receive a message from the server which means my account is spamed?

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#1585]

**Comment by FunkyYang** [comment]
I send a message using linux desktop ,and receive a tip which report my account be spamed,and I want to kown which class should I can use with tdlib package

**Comment by FunkyYang** [comment]
and my account  ```IsScam,IsFake``` false

**Comment by FunkyYang** [comment]
the tip
```
unfortunately,you are banned from participating in public groups
```

**Comment by FunkyYang** [comment]
this type message will be in msg chan?

**Comment by levlam** [comment]
This is not a message. This is an error returned to sendMessage request.

**Comment by FunkyYang** [comment]
e....,I want to cache that

**Comment by levlam** [comment]
This is https://translations.telegram.org/en/tdesktop/groups_and_channels/lng_error_public_groups_denied. You can search Telegram Desktop code to find when the error is shown.

**Comment by FunkyYang** [comment]
I have no idea to find out which method will be throw this error

**Comment by FunkyYang** [comment]
I have no idea to find out which method will be throw this error
