### ISSUE TITLE
Channel list was imported using ChatListArchive. But up to 102 can be loaded.

### ISSUE THREAD

**Issue by lkm0307** [tdlib/td#1587]
There are many channels in my Telegram account.
However, only up to 102 IDs are displayed and no other IDs are displayed.
The total count shows the exact number of channels.

The language you are using is c#.

> `client.Send(new GetChats(new ChatListArchive(), Int64.MaxValue, 0, int.MaxValue), _defaultHandler);`

Response to Code

```
chats {
  total_count = 141
  chat_ids = vector[102] {
    -111111111
    ...
  }
}
```

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats

**Comment by am1654aa** [comment]
> https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats

Can you explain it in more detail? That's what I need, too.

**Comment by levlam** [comment]
No. The link explains everything:
```
If the Application needs more chats, it should repeat the request with adjusted offset_order and offset_chat_id parameters.
```

**Comment by am1654aa** [comment]
> r

So its size can be appropriated to 102 or more? Is it something you can't do? Just tell me that.

**Comment by am1654aa** [comment]
> 아니요. 링크는 모든 것을 설명합니다.
> 
> ```
> If the Application needs more chats, it should repeat the request with adjusted offset_order and offset_chat_id parameters.
> ```

So its size can be appropriated to 102 or more? Is it something you can't do? Just tell me that.

**Comment by am1654aa** [comment]
> 아니요. 링크는 모든 것을 설명합니다.
> 
> ```
> If the Application needs more chats, it should repeat the request with adjusted offset_order and offset_chat_id parameters.
> ```

Can you show me the example source code? I still don't get it.

**Comment by levlam** [comment]
Examples are linked at https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats.

**Comment by am1654aa** [comment]
> 예제는 https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats 에 링크되어 [있습니다](https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats) .

I do not know the language of Java.
I want to know the code in C#. There's only one line of code I want. Help me.

**Comment by levlam** [comment]
If you know C#, you should be able to implement this in C#.

**Comment by am1654aa** [comment]
> If you know C#, you should be able to implement this in C#.

I don't know what to put in the offset and offset ID. I'm gonna ask you a favor, because you're better than me.
Please give me an example code in C#.

**Comment by lkm0307** [comment]
> If you know C#, you should be able to implement this in C#.

Thank you. I solved it thanks to you.

**Comment by lkm0307** [comment]
> If you know C#, you should be able to implement this in C#.

Thank you. I solved it thanks to you.
