### ISSUE TITLE
Get response from td_json_client_create() which is an Int64 data type of length 15 characters

### ISSUE THREAD

**Issue by sangle1996** [tdlib/td#1589]
![image](https://user-images.githubusercontent.com/42021108/124080608-c1f43280-da74-11eb-9895-db4093642575.png)
Hi guys, im creating a plugin for flutter using TDLib c++. But i don't know how to get the clientID which is an Int64 data type of length 15 characters (like Swift and Kotlin response from this).  How can i get this. Thanks

**Comment by levlam** [comment]
`client_id` exists only in the new JSON interface and is returned by `td_create_client_id`. The old interface returned raw pointer.
