### ISSUE TITLE
ForwardMessages changed photo unique file id

### ISSUE THREAD

**Issue by lmcmceo** [tdlib/td#1590]
when I ForwardMessages with sendCopy=true, I found that, video unique file id does not change, but photo unique file id changed, is it reasonable?

**Comment by lmcmceo** [comment]
And what is the difference from ForwardMessages and SendMessage with inputMessageForwarded ?

**Comment by levlam** [comment]
I can't reproduce this. `unique_id` stays the same all the time. Are you talking about "Values of the field file_unique_id in objects of the type PhotoSize and of the fields small_file_unique_id and big_file_unique_id in objects of the type ChatPhoto were changed" from https://core.telegram.org/bots/api-changelog#june-25-2021?

**Comment by levlam** [comment]
You can forward/copy only one message with `inputMessageForwarded`, but it is easier to use.
