### ISSUE TITLE
GetChatsAsync not work

### ISSUE THREAD

**Issue by elmagekmosaad** [tdlib/td#1593]
![image](https://user-images.githubusercontent.com/19142989/124310891-25fa2200-db6d-11eb-80de-b03e52156632.png)
my code
Dim a As ChatListMain = New ChatListMain
Dim mg1 As Chats = Await client.GetChatsAsync(a, 9223372036854775807L, 0, 10)

how to get groups !?
#c or vb.net

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats.

**Comment by elmagekmosaad** [comment]
> 
> 
> See https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats.

yes i dided and my code
Dim a As ChatListMain = New ChatListMain
Dim mg1 As Chats = Await client.GetChatsAsync(a, 9223372036854775807L, 0, 10)



but return 0

**Comment by levlam** [comment]
What do you mean by "return 0"?

**Comment by elmagekmosaad** [comment]
> 
> 
> What do you mean by "return 0"?

chatids = 0

**Comment by elmagekmosaad** [comment]
not get any group

**Comment by levlam** [comment]
`getChats` returns an object, not integer.

**Comment by elmagekmosaad** [comment]
> 
> 
> `getChats` returns an object, not an integer.

i mean count of grops extracted = 0

**Comment by levlam** [comment]
Check that you are sending a correct request using TDLib's log.

**Comment by elmagekmosaad** [comment]
where i can find log it's not in application folder !
and give me right code for #c or vb.net

**Comment by levlam** [comment]
By default they are written to stderr. You can change this using the method `setLogStream`.

**Comment by elmagekmosaad** [comment]
give me right code for #c or vb.net to try it
my code is
Dim a As ChatListMain = New ChatListMain
Dim mg1 As Chats = Await client.GetChatsAsync(a, 9223372036854775807L, 0, 10)

but not get any groups

**Comment by levlam** [comment]
I can't provide a code. But the only way to receive 0 chats and 205 TotalCount is to provide invalid OffsetOrder. You can check exact value, which was received by TDLib in the TDLib's log.

**Comment by levlam** [comment]
In TDLib 1.8.0 `getChats` was replaced with `loadChats`, so it is impossible to pass a wrong `offset_order` to it now.
