### ISSUE TITLE
New custom InputMessageContent 

### ISSUE THREAD

**Issue by sajjademad** [tdlib/td#1595]
Is it possible to make a new inherited class of InputMessageContent to handle a custom form of message?  For example, making a type of message that consists of title and body or a more complicated form of message. And if I can't do such a thing with TDlib, will it be possible to do by integrating it with a separate backend server? I searched through the documentation and the web and couldn't find an answer.

**Comment by levlam** [comment]
This is not possible, Telegram clients support only messages, which can be sent using existing `inputMessageContent` classes. In your own client, you can treat differently messages with some specific content, but they will be shown as is in all other clients.

**Comment by sajjademad** [comment]
@levlam Thanks for your help.
