### ISSUE TITLE
How to get contacts profilePhoto?

### ISSUE THREAD

**Issue by sergeydi** [tdlib/td#1597]
I received all contacts by command `getContacts`. For each contact object I have `profilePhoto` and `remoteFile` objects. How to get profile image for each contact?

**Comment by levlam** [comment]
You can use `downloadFile` to download them.

**Comment by sergeydi** [comment]
@levlam I need to execute `downloadFile` for each contact or it can be done by one command for all contacts?

**Comment by levlam** [comment]
See documentation of the request.

**Comment by sergeydi** [comment]
@levlam Is it required to be signed in for loading images?

**Comment by levlam** [comment]
Defniitely.

**Comment by sergeydi** [comment]
If I have `profilePhoto.id` and `remoteFile.id`, is there any solution to get image using only **App api_id** and **App api_hash**?

**Comment by levlam** [comment]
No.

**Comment by sergeydi** [comment]
@levlam thanks.

**Comment by sergeydi** [comment]
@levlam I am looking into [downloadFile](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1download_file.html) Documentation and can't find where to sent `remoteFile.id` which I want to download, file_id parameter takes only `int` value, or I misunderstand something?

**Comment by zelenin** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_remote_file.html
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1file.html

**Comment by sergeydi** [comment]
@zelenin Thanks.
