### ISSUE TITLE
getMessage of channel

### ISSUE THREAD

**Issue by amin1softco** [tdlib/td#16]
hi
i want call getmessage method on public channel like this https://t.me/myid/12345 but when send 12345 get invalid message how convert 12345 to correct message_id ? like this 4365221888 when gethistory say invalid_bot_method 

really i need opposite this function 

>//@description Returns public HTTPS link to a message. Available only for messages in public channels @chat_id Identifier of the chat, message belongs to @message_id Identifier of the message
getPublicMessageLink chat_id:int53 message_id:int53 = PublicMessageLink;

**Comment by levlam** [comment]
Such function will be added in the future. For now you can pass (message_id * 1048576) as message_id to getMessage method as a workaround.

**Comment by amin1softco** [comment]
work great. tnx

**Comment by zevlg** [comment]
Any updates on this issue?

Is there any way to get message id by its `post` value, without scanning all the messages requesting their public link, which is extremely heavy?

**Comment by zelenin** [comment]
@zevlg 
> by its post value

what is a post value?

**Comment by zevlg** [comment]
> what is a post value?

Post value is the number at the end of the url https://t.me/myid/12345

i.e. 12345, but real message-id is something different

**Comment by zelenin** [comment]
@zevlg https://github.com/tdlib/td/issues/16#issuecomment-362257275

**Comment by zevlg** [comment]
> @zevlg [#16 (comment)](https://github.com/tdlib/td/issues/16#issuecomment-362257275)

ahh, thanks! missed this comment for some reason

**Comment by levlam** [comment]
The method `getMessageLinkInfo` for getting information about a link to a message in a chat was added in TDLib 1.5.0.
