### ISSUE TITLE
Java build fails, cannot find -ltdcore

### ISSUE THREAD

**Issue by Ferro219** [tdlib/td#160]
I'm trying to compile the java client on Linux Mint 17.2, 64 bit.

Installing dependencies went find, had to add new repos for G++ and CMake because the version in Mint was outdated, but nothing out of the ordinary.

The first part (jni) of the Java build seems to be fine.

When I try to build the second part I get the following output:
`[ 50%] Built target generate_javadoc
Scanning dependencies of target build_java
[ 75%] Building Java code
[ 75%] Built target build_java
Scanning dependencies of target tdjni
[100%] Building CXX object CMakeFiles/tdjni.dir/td_jni.cpp.o
Linking CXX shared library libtdjni.so
/usr/bin/ld: cannot find -ltdcore
collect2: error: ld returned 1 exit status
make[2]: *** [libtdjni.so] Error 1
make[1]: *** [CMakeFiles/tdjni.dir/all] Error 2
make: *** [all] Error 2
`

I also notice that the docs and bin folders appear directly in the example folder, instead of the java folder.

**Comment by levlam** [comment]
It's a CMake bug. You need to update CMake or manually replace in the file example/java/td/lib/cmake/Td/TdTargets.cmake all 3 occurrences of 
"LINK_ONLY:td" with "LINK_ONLY:Td::td". Replacement should be case sensitive to not replace "LINK_ONLY:Td".

**Comment by Koekerk** [comment]
Thanks for your fast response.

After using a case sensitive search and replace I managed to finish the build and eventually send a 'test' message to my own account.

However, the class files and docs still ended up within the example/bin and example/docs folder, while the .so file ended up in the example/java/bin folder.
I expected everything to end up in the example/java/bin and example/java/docs folder.

**Comment by levlam** [comment]
The class files and docs are placed relative to a folder specified using CMAKE_INSTALL_PREFIX option to cmake. Have you built from `build` folder and specified `-DCMAKE_INSTALL_PREFIX:PATH=..` to cmake?

**Comment by Koekerk** [comment]
These are the commands I used for the second part:
cd ~/Downloads/tdlib/example/java
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=~/Downloads/tdlib/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. ..
cmake --build . --target install
```

**Comment by levlam** [comment]
Could you show value of `CMAKE_INSTALL_PREFIX` from `CMakeCache.txt`, for example,
```
grep CMAKE_INSTALL_PREFIX ~/Downloads/tdlib/example/java/build/CMakeCache.txt
```
?

**Comment by Koekerk** [comment]
The specific line you asked:
CMAKE_INSTALL_PREFIX:PATH=..

I've attached the entire file (replaced my actual home dir by ~ just before uploading)

[CMakeCache.txt](https://github.com/tdlib/td/files/1899724/CMakeCache.txt)

**Comment by levlam** [comment]
Thanks. @Koekerk.

**Comment by levlam** [comment]
The bug exists only in very old CMake versions and build instructions generator contains a workaround for it, so there are no much reasons to keep it open.
