### ISSUE TITLE
ban my number

### ISSUE THREAD

**Issue by abbasbamaram** [tdlib/td#1602]
I'm trying to use my mobile phone number: 989913743812
But Telegram says it's banned. Please help.

App version: T7.8.0 - P9.0 (23605)
OS version: SDK 29
Device Name: XiaomiM2010J19CG
Locale: fa

**Comment by levlam** [comment]
You received all relevant instructions in the error messages.

**Comment by THAESUMON30** [comment]
Hi, my phone number in Telegram is +959423501808 Laugh +959898732639 Please check each post and reply

**Comment by THAESUMON30** [comment]
Hi, my phone number in Telegram is +959423501808 Laugh +959898732639 Please check each post and

**Comment by THAESUMON30** [comment]
My email address maymaysameelayy@gmail.com 
sumonthel610@gmail.com 
Telegram

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.Please help. I haven't been working for over a week. Please check the PC

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en 

Help, I haven't worked for over a week+959423501808 Please check the file and extract it.

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 989913743812
But Telegram says it's banned. Please help.

App version: T7.8.0 - P9.0 (23605)
OS version: SDK 29
Device Name: XiaomiM2010J19CG
Locale: fa
 

Oh, my phone number is not working My phone number is +959423501808

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 989913743812
But Telegram says it's banned. Please help.

App version: T7.8.0 - P9.0 (23605)
OS version: SDK 29
Device Name: XiaomiM2010J19CG
Locale: fa
 

Oh, my phone number is not working My phone number is +959423501808ပါ

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51432)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51432)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en help me

**Comment by THAESUMON30** [comment]
![Uploading Screenshot_၂၀၂၄-၀၈-၂၁-၁၁-၂၇-၀၄-၇၆၉_org.telegram.messenger.web.jpg…]()
