### ISSUE TITLE
Unmanaged code error when using .NET wrapper

### ISSUE THREAD

**Issue by kasparas12** [tdlib/td#1604]
Hello, 

I am using .NET wrapper of tdlib with my WPF .NET application and in that I am trying to open multiple
TDLib clients but I get this error:

[ 0][t129][1625828531.163790941][ThreadLocalStorage.h:50]	Check `0 <= thread_id && static_cast<size_t>(thread_id) < nodes_.size()` failed

Somehow this line CHECK fails:

![image](https://user-images.githubusercontent.com/31854474/125071095-8505ec80-e0c1-11eb-9624-f32b037a4b6e.png)

Could you know the reason why? Something messed up with OS Threads because I am initiating each TDLibClient in separate Task.

Interesting thing that this error is not persisting in every PC, so I guess it is related to specific device. Maybe CPU instruction set? 

Thank you for your suggestions and support,

Kasparas

**Comment by levlam** [comment]
This should happen only if PC has more then 20 logical processors and only on Windows.

**Comment by kasparas12** [comment]
Thank you for insight. So there is no workaround in such case?

**Comment by levlam** [comment]
It will be fixed in the TDLib 1.7.6 soon.
