### ISSUE TITLE
Local cache configuration?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1605]
Hi, can tdlib already configure the local caches? 
![grafik](https://user-images.githubusercontent.com/16186470/125165810-e056de00-e198-11eb-944b-5a9a4f951e06.png)

**Comment by levlam** [comment]
See `optimizeStorage` method.

**Comment by Flohack74** [comment]
Thanks, and the size of the sqlite db for message cannot be limited? What are the constraints there, after which time are messages deleted?

**Comment by levlam** [comment]
Size of message database isn't limited.

**Comment by Flohack74** [comment]
Alright thx!
