### ISSUE TITLE
unfortunately,you are banned from participating in public groups

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#1606]
I have no idea to find out which method will be throw this error?the ```sendMessage```  told that ```you hava no rights will be access this chat ```

**Comment by levlam** [comment]
This is not a Telegram API or a TDLib error. This is a part of a string from an app localization. You need to inspect source code of the app.

**Comment by HandsomeTopKhi** [comment]
> I have no idea to find out which method will be throw this error?the `sendMessage` told that `you hava no rights will be access this chat `

Were you ever able to get this solved ?

**Comment by Vitalicus** [comment]
Closed but not solved
**you are banned from participating in public groups**
