### ISSUE TITLE
High CPU usage with getSupergroupMembers

### ISSUE THREAD

**Issue by Kreonid** [tdlib/td#1607]
Hi there!

I'm experiencing a high CPU usage in my script, and I found out the problem is related to one particular request: getSupergroupMembers. When a big enough list of chat members is fetched, the CPU usage increases dramatically. 

I am using Python, and to demonstrate the issue I have modified the [Python example](https://github.com/tdlib/td/blob/master/example/python/tdjson_example.py) provided in the repo. I tried to make as few changes as possible, so that it's a minimal example that reproduces the problem. It takes a chat and fetches the first 10K memebrs from it. This is repeated for 5 chats in a row to see the problem more clearly. Please find the code attached. Simply launch it, and the script will perform the members fetching after the regular auth process.

I've inserted 3-second sleeps between each of the groups to better understand the results. When a new group starts being processed, the CPU usage rises to about 50%. During the 3-second sleep it comes back to normal.
Tested on:
- Windows 10
- Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50 GHz
- 4GB RAM
- TDLib 1.7.0 (built in release mode)

I've noticed that TDLib sends an updateUser for each of the fetched users, and thought maybe a huge number of incoming updates cause the CPU spike. Anyway, you'll know it better than me.
If you need some more test-cases/debugging or anything else that I can provide, please let me know.

[cpu_tests.py.zip](https://github.com/tdlib/td/files/6800392/cpu_tests.py.zip)

**Comment by levlam** [comment]
In my tests, high CPU usage was caused mostly by outputing of 80 megabytes of result data to a console. 
If the script is run with output redirected to a file like `python cpu_tests.py > out.txt`, the resulting file is generated in a matter of seconds with short CPU bursts. The CPU usage can be reduced by approximately 50% if all databases are disabled, but given the amount of data, which needs to be processed, some CPU usage is expected. It can be reduced further only by removing even more TDLib functionality. For example, complete ignoring of user profile photos should decrease CPU usage by another 50%. You can add `return;` as the first line of ContactsManager::on_update_user_photo if you don't need the photos.
