### ISSUE TITLE
Some chats don't receive the correct order value when they are deleted from another client

### ISSUE THREAD

**Issue by melix99** [tdlib/td#1608]
When I delete some chat types from a different client (I tried with Telegram for Android), I receive updates in the tdlib client that updates the chats position (so `updateChatLastMessage` or `updateChatPosition`), but their order value is not zero as I expected it to be (as they are deleted, so they should be hidden in the chat list).

I reproduced this bug with bots and groups. Channels work correctly apparently.

@levlam confirmed that this bug still happens with the latest version.

**Comment by levlam** [comment]
Thanks. Fixed in master.
