### ISSUE TITLE
Td::TdJson error parse string

### ISSUE THREAD

**Issue by Triquetras** [tdlib/td#1609]
I am trying to send a phone number with this command:
```
td_send(client_id, "{\"@type\":\"setAuthenticationPhoneNumber\", \"phone_number_\":\"+71234567890\" }");
```
In response, I receive an error "The number cannot be empty"
I looked through the order of calls when parsing with the debugger and found that the phone number with json_string_decode for some reason does not get into the result, only "}" remains.

**Comment by levlam** [comment]
In JSON interface field names doesn't end with underscore, so it should be "phone_number" instead of "phone_number_".

**Comment by Triquetras** [comment]
> In JSON interface field names doesn't end with underscore, so it should be "phone_number" instead of "phone_number_".

It`s work! Thanks!
