### ISSUE TITLE
TdWeb JavaScript Authorization

### ISSUE THREAD

**Issue by psemotiuk** [tdlib/td#1610]
Guys, can you please explain me how to make authorization to Telegram. I can't understand how I can take authorizationState and all of that updates?

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.

**Comment by psemotiuk** [comment]
> See https://core.telegram.org/tdlib/getting-started.

**Comment by psemotiuk** [comment]
> > See https://core.telegram.org/tdlib/getting-started

How implement for example this classes authorizationStateWaitPhoneNumber, authorizationStateWaitCode, authorizationStateWaitRegistration and authorizationStateWaitPassword 

I tried, to use send() method, but receive Promise <pending>. I can't understand, how it use...

**Comment by levlam** [comment]
Try to look at the examples.
