### ISSUE TITLE
DownloadFile ：Invalid file identifier

### ISSUE THREAD

**Issue by FixedYangSir** [tdlib/td#1611]
By using TdApi.GetChats to return the chat list, and then I use DownloadFile to download the chat avatar, some can be successful, but some return Invalid file identifier error code 400, what is the reason for this?
![1626316493(1)](https://user-images.githubusercontent.com/15099876/125719220-f0b0beb4-3a2a-4fad-b92b-2277ca84a57a.jpg)
![1626316599(1)](https://user-images.githubusercontent.com/15099876/125719223-312b36e4-acbd-4cc7-8758-55fb1947515d.jpg)

**Comment by levlam** [comment]
File identifiers aren't persistent. You can't save it and use in another TDLib instance.

**Comment by FixedYangSir** [comment]
Thank you very much. It worked
