### ISSUE TITLE
getchat:member invalid member

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#1612]
in version 1.7.5
there is an error in the method
getchat sometimes works sometimes not
and method getchatmember
error code Invalid member identifier specified

in the previous version version 1.7.3 everything was normal please fix this issue thanks issue

**Comment by levlam** [comment]
Which exactly error did you receive for `getChat`?

Between, parameters of `getChatMember` has changed. It is
```
getChatMember chat_id:int53 member_id:MessageSender = ChatMember;
```
now.

**Comment by azkadev** [comment]
getChatMember(chat_ids, user_ids) {
        var data = {
            '_': "getChatMember",
            chat_id: chat_ids,
            user_id: user_ids
        }
        return this.handle.invoke(data)
    }
code error
Member identifier is not specified
and now i build td lib again td lib but getchatmember still not working?
please fix it because in the previous version it was normal

**Comment by levlam** [comment]
getChatMember has parameters `chat_id` and `member_id` in the latest TDLib version.

**Comment by azkadev** [comment]
async getChatMember(chat_ids, user_id) {
        var data = {
            '_': "getChatMember",
            chat_id: chat_ids,
            member_id: user_id
        }
        var get = await this.handle.invoke(data)
        console.log(get)
        return get
    }

EROR Failed to parse JSON object as TDLib request: Expected Object, got Number

**Comment by levlam** [comment]
```
getChatMember chat_id:int53 member_id:MessageSender = ChatMember;
```

`member_id` must be of the type `MessageSender`. See the latest scheme at https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.
