### ISSUE TITLE
Autotests

### ISSUE THREAD

**Issue by AlekseyDryuk** [tdlib/td#1614]
My name is Alexey and I am writing a project of autotests, covering the bot telegram through your library in the company. Please tell me why Telegram marks my frequent requests as a flood? If I make, for example, 10 requests in 5 seconds, then he will tell you to wait 25 seconds to avoid flooding and then I can send requests again, but after 10 requests, wait again. How can I avoid this?

**Comment by levlam** [comment]
Flood limits can't be avoided.
