### ISSUE TITLE
API_ID_INVALID error response with new account api_id/api_hash pair

### ISSUE THREAD

**Issue by kasparas12** [tdlib/td#1616]
Strange thing happening since yesterday (07-15) with new account (generated API id and hash)

I am not getting other messages from Telegram after I send tdapi.AuthorizationStateWaitPhoneNumber (no verification code request is sent)

The account is working good in web client or mobile client though.

Also tried tdlib with older api_id/hash and it is working good.

When debugging tdlib in full debug mode I get these API_ID_INVALID errors even though I am sure api_id/api_hash pair is correct.

`[ 4][t 5][1626439689.948137521][Session.cpp:800][#1][!Session:1:main]	Session::on_message_result_error [id:6985505267723495176][error_code:400][msg:API_ID_INVALID]
[ 3][t 5][1626439689.948167085][Session.cpp:809][#1][!Session:1:main][&net_query]	Return query error [Query:[id:262144][tl:0xa677244f][state:Query]]
[ 3][t 5][1626439689.948194503][NetQuery.h:322][#1][!Session:1:main][&net_query]	Got error [Query:[id:262144][tl:0xa677244f][state:Query]] [Error : 400 : API_ID_INVALID]
[ 3][t 5][1626439690.710546016][NetQuery.h:244][#1][!Session:1:main][&net_query]	[Query:[id:262144][tl:0xa677244f][state:Error][Error : 400 : API_ID_INVALID]] [state:sent to callback]
[ 3][t 5][1626439690.710739850][AuthManager.cpp:805][#1][!AuthManager]	Receive result of query 262144, expecting 262144 with type 3
[ 3][t 5][1626439690.711037635][Td.cpp:4547][#1][!Td][&td_requests]	Sending error for request 28: error { code = 400 message = "API_ID_INVALID" }`

Any suggestions? Maybe something is wrong on the Telegram server end?

**Comment by levlam** [comment]
How much API ID did you created?
