### ISSUE TITLE
Why Thumbnail disappears?

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1617]
When I send a video to one of my users, the video appears with the thumbnail without any problems. But when I tap on the video and play it for a while, the thumbnail disappears and a black thumbnail appears instead. What is wrong?

**Comment by levlam** [comment]
Does the Message object have thumbnail after `updateMessageSendSucceeded`?

**Comment by zyadomer98** [comment]
Yes

**Comment by levlam** [comment]
Is it the same thumbnail that you specified for the file?

**Comment by zyadomer98** [comment]
Yes. As I mentioned in the question everything works perfectly and the selected thumbnail uploads appears with no problems. But when you play through the video for a while, the thumbnail disappears and a black screen appears instead.

**Comment by IRGC** [comment]
more likely a client side bug i used to experience this in TDesktop mostly occurred to small sized videos. 
can you tell what client your friend is using to play the video?

**Comment by zyadomer98** [comment]
It is same on macbook pro and iphone 7

**Comment by levlam** [comment]
Some clients regenerates video thumbnail after the beginning of the video is downloaded. If you see a black thumbnail, that's because the first frame of the video is black.

**Comment by zyadomer98** [comment]
Is there any way to prevent the auto-regeneratin of the thumbnail and keep mine?

**Comment by levlam** [comment]
No. Video thumbnail is supposed to be the same as the first frame of videos.

**Comment by zyadomer98** [comment]
I think it should be fixed because most of the times the first frame is not suitable for the thumbnail. Or at least make the first frame as the thumbnail when the video has no thumbnail

**Comment by levlam** [comment]
This is expected behavior and it is not expected to be changed.

**Comment by zyadomer98** [comment]
Okay thanks
