### ISSUE TITLE
getChats callback not raised

### ISSUE THREAD

**Issue by NaderStar** [tdlib/td#162]
assert (tdbot_function ({
  ["@type"] = 'getChats',
  offset_order = '9223372036854775807',
  offset_chat_id = 0,
  limit = 20
}, mycallback, data))

mycallback called by chance 4-5 times in a day

**Comment by iceberg1369** [comment]
I have the same problem with over 1000 chats. none of getChats or SearchPublicChat works. althougth I receive update Messages through handlers but aformentioned methods do nothing  at all

**Comment by levlam** [comment]
@iceberg1369 Have you specified a correct ResultHandler when calling Client.send? This problem also can happen when a dedicated thread used for calling callbacks is blocked, for example, when trying to send a request from a ResultHandler and synchronously waiting for its result.

**Comment by levlam** [comment]
I hope that the problem was resolved. Please reopen the issue and provide additional details if it still happens to you.

**Comment by hosseinGanjyar** [comment]
@NaderSetarei I need call you, please comment your contact info.
Thanks
