### ISSUE TITLE
TelegramX: Extract Chats from db.sqlite - messages table 

### ISSUE THREAD

**Issue by Eniplay** [tdlib/td#1621]
Hey there,

Is there a possibility of extracting the individual messages from the unencryptedTelegramX -  db.sqlite database? 
It seems like all Messages are in the 'messages' table in the 'data' Row but I can't really figure out how they are stored there.

Thx

**Comment by levlam** [comment]
TDLib doesn't provide a way to do that.

**Comment by Eniplay** [comment]
Yeah... that was my apprehension. 
But how exactly does TdLib natively save the messages of chats to the database?

**Comment by levlam** [comment]
In an unspecified and changed with every TDLib update way.

**Comment by Flohack74** [comment]
@Eniplay you should not mess with direct db access as its an implementation detail behind a comprehensive API. In theory all your data you should be able to get from the tdlib interface.
