### ISSUE TITLE
Deleting primary invite link

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1622]
I remember times when TDLib allowed to create channels without link at all, and you had to call `generateChatInviteLink` to get a link to the channel.

Nowadays in TDLib 1.7.5 it looks like it is not possible to create a channel without an invite link.  If I revoke/delete all links, then a new link creates automatically and `getChatInviteLinks` always returns a link.

Is it possible somehow to create a channel without *any* links to it?  I want to have a private channel to store text files and don't want anybody to access it.  If a link exists it can leak from client or be exposed somehow

Thanks

**Comment by levlam** [comment]
Previously, if `generateChatInviteLink` was called at least once, then the supergroup will always have an invite link after that. It was possible to revoke the link using another call to `generateChatInviteLink`, but a new link was immediately created in place.

Now, the behavior is the same, but additionally the invite link is automatically created whenever you call `getBasicGroupFullInfo`/`getSupergroupFullInfo`, which happens on every chat opening.

There is no way to avoid this behavior, but if you don't share the link, it shouldn't be exposed to anyone.
