### ISSUE TITLE
Generate tdlib objects for Qt

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1628]
Hi once again,

we want to start working on the upgrade for tdlib 1.7 - due to the amount of changes this time i see a big risk of actually breaking features when we manually add and edit all our objects that interface with the Json API. Rather I would like to generate our Qt bindings. Is there a way we could get a formal description of the tdlib interface, bascially also what the web page shows us, but in a machine-readable form?

thx

**Comment by Flohack74** [comment]
Oh maybe I found it, is it https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl ? Can you confirm that this is not the layer tl file?

**Comment by levlam** [comment]
Yes, this is the TDLib API scheme from which all the bindings and documentation are generated.

**Comment by Flohack74** [comment]
Ok thanks!
