### ISSUE TITLE
compile in (or for) ubuntu 14.04

### ISSUE THREAD

**Issue by danielecr** [tdlib/td#163]
Is it possible?
Installed clang-3.9, setted the CC and CXX env, followed hints in https://stackoverflow.com/a/7032021/250970
but I have this (in log, during configuration):

```
Building CXX object CMakeFiles/cmTC_affc6.dir/src.cxx.o
/usr/bin/clang++-3.9     -pthread -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wpointer-arith -Wcast-qual -Wsign-compare -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wc++14-compat-pedantic -Qunused-arguments -Wodr -DHAVE_CXX_FLAG_FLTO_ODR_TYPE_MERGING -flto-odr-type-merging -fPIE   -flto-odr-type-merging -o CMakeFiles/cmTC_affc6.dir/src.cxx.o -c /home/redmine/TDlib/td/build/CMakeFiles/CMakeTmp/src.cxx
clang: error: unknown argument: '-flto-odr-type-merging'
clang: error: unknown argument: '-flto-odr-type-merging'
make[1]: *** [CMakeFiles/cmTC_affc6.dir/src.cxx.o] Error 1
```

**Comment by levlam** [comment]
It is definitely possible.

`clang: error: unknown argument: '-flto-odr-type-merging'` is not an error, it's a failed check for a compiler flag support, so the flag will not be used during the build. The problem is somewhere else.

**Comment by danielecr** [comment]
Thank you. Yes, of course the problem is during compilation, I just tried to guess from configuration step, and I failed. Anyway this is during build:

```
$ cmake --build .
--
Scanning dependencies of target tdtl
[  1%] Building CXX object tdtl/CMakeFiles/tdtl.dir/td/tl/tl_config.cpp.o
In file included from /home/redmine/TDlib/td/tdtl/td/tl/tl_config.cpp:7:
In file included from /home/redmine/TDlib/td/tdtl/td/tl/tl_config.h:9:
In file included from /home/redmine/TDlib/td/tdtl/td/tl/tl_core.h:11:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
using ::gets;
~~^
1 error generated.
make[2]: *** [tdtl/CMakeFiles/tdtl.dir/td/tl/tl_config.cpp.o] Error 1
make[1]: *** [tdtl/CMakeFiles/tdtl.dir/all] Error 2
make: *** [all] Error 2
```

I have only gcc 4.8 available for ubuntu 14.04, but I specified to use clang-3.9 and clang++-3.9. I can not understand why includes came from gcc 4.8,  anyway I think this also is not really the problem, or is it?

**Comment by levlam** [comment]
clang fails to parse libstdc++ headers.
You need to uncomment line
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
in CMakeLists.txt to force it to use libc++ headers.

You may need also to uncomment previous line
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem /usr/include/c++/v1")
but it has worked for me without that.

**Comment by danielecr** [comment]
in what exactly cmake is better than autoconf/automake?

**Comment by levlam** [comment]
You need to find where libc++ headers was installed and specify it in that line
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem <path to libc++ headers>")
For example, they can be in `/usr/include/c++/v1`.

**Comment by levlam** [comment]
I hope that the problem was resolved. Please reopen the issue if you need more help with TDLib building.

**Comment by Denis-Oakley** [comment]
> You need to find where libc++ headers was installed and specify path to them in that line
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem <path to libc++ headers>")
> For example, they can be in `/usr/include/c++/v1`.

Hi, what does 'in that line' main?
