### ISSUE TITLE
Failed to Download file

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1630]
I am trying to download some files from the server. But it raises with this error `Failed to Download file 7(0) of type photos: [PosixError : No such file or directory : 2 : Can't rename "/Users/zyadomer/Desktop/bots/translator/_td_files/temp/18" to "/Users/zyadomer/Desktop/bots/translator/_td_files/photos/200325700091_256948.jpg"`. I do not know what the problem is becuase I can download other files without any problems, and I thing it was not like that before.

**Comment by zyadomer98** [comment]
It shows this error
![Uploading Screen Shot 2021-07-24 at 5.09.19 PM.png…]()

**Comment by levlam** [comment]
The error means that someone deleted the file "/Users/zyadomer/Desktop/bots/translator/_td_files/temp/18" with a partially downloaded photo before it was moved to the final location.

**Comment by zyadomer98** [comment]
Yes exactly, it was due to that. Thanks
