### ISSUE TITLE
How to make answering callback queries synchronous?

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1631]
Is there any way to make the responses of callback queries of a message occur in row and one by one? For example, I made a message in a channel that have some inline keyboard on the message. There are many users in the channel and they may tap on the button simultaneously and the bot will respond to all of them at the same time. I want to make the responses to occur one by one (when one ends then the other starts instead of answering all together at the same time).

**Comment by levlam** [comment]
This is up to your bot and its code.

**Comment by zyadomer98** [comment]
Thanks
