### ISSUE TITLE
How can i download sticker set thumb? 

### ISSUE THREAD

**Issue by JanChing6** [tdlib/td#1633]
Note : I am Using Github Version of Tdlib

I tried `getFileRequest` and often Fall into errors. 
Maybe, i am trying the wrong way

Can anyone help & Explain how can i download Sticker Set thumb / InputStickerSetThumb?

**Comment by IRGC** [comment]
you need to use `downloadFile` with `file_id` parameter. 
`file_id` can be found in the json just after `"@type":"file"`
more info https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L4633

**Comment by levlam** [comment]
Also, file identifiers aren't persistent. You must pass a file identifier received from TDLib in `stickerSetInfo.thumbnail.file.id` without trying to save it for later reuse.
