### ISSUE TITLE
getBasicGroupFullInfo and getSupergroupMembers troubles

### ISSUE THREAD

**Issue by EgartSites** [tdlib/td#1635]
Hi! Method getBasicGroupFullInfo stops thread without any exceptions. Method getSupergroupMembers return zero values array for *Members*. Tested on tdlib (1.7.4 and 1.7.6) Ubuntu 20.04 and Windows 10 x64. Using .NET Core 5.0

**Comment by levlam** [comment]
> Method `getBasicGroupFullInfo` stops thread without any exceptions.

All updates and request responses are handled in a dedicated thread. If you do a synchronous request during processing of an update or a request response, you block the thread, which results in exactly described behavior.

> Method `getSupergroupMembers` return zero values array for Members.

There are no known issues with that method. Could you show the whole request?

**Comment by EgartSites** [comment]
After calling getBasicGroupFullInfo main app thread continue working. Any synchronous request in the code. 
![image](https://user-images.githubusercontent.com/68100167/127395599-7242528c-83e7-4e39-8687-be7291d7460d.png)
Returns true members count, true members invite id, but members id`s is always 0, like {0,0,0,0,0}

**Comment by levlam** [comment]
> After calling getBasicGroupFullInfo main app thread continue working. 

Because the thread, which handes responses, isn't main thread. You need to check, how async/await interface is implemented in your wrapper for TDLib requests. TDLib-provided interface uses callbacks instead, so the wrapper implementing async/await must ensure that the dedicated thread isn't blocked.

> Returns true members count, true members invite id, but members id`s 

Because you pass Limit == 0. supegroup.MemberCount is unkown as stated in its documentation:
```
Number of members in the supergroup or channel; 0 if unknown. Currently it is guaranteed to be known only if the supergroup or channel was received through searchPublicChats, searchChatsNearby, getInactiveSupergroupChats, getSuitableDiscussionChats, getGroupsInCommon, or getUserPrivacySettingRules
```

**Comment by EgartSites** [comment]
Yep, I'm trying getBasicGroupFullInfo in main thread, but also without results. Limit not 0. Members count is actual members count. Lol, did you read my message? I receiving members array. For every member I have inviteUserId and I'd. inviteUserId id true for all members. But I'd always 0

**Comment by EgartSites** [comment]
Moving to other issue
