### ISSUE TITLE
Errors getting TdLib to work Java on MacOS

### ISSUE THREAD

**Issue by UjuE** [tdlib/td#1637]
Error: FATAL ERROR in native method: Can't find field [memberId] with signature [Lorg/drinkless/tdlib/TdApi$MessageSender;]

Operating System: macOS Big Sur Version 11.2.3(20D91)

Java version: openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

I have compared a number of classes documentation and the java classes them selves.
For example SetChatMemberStatus expects member TdApi.MessageSender memberId and it is not present.

**Comment by levlam** [comment]
You are using different versions of TDLib shared library and autogenerated TdApi.java. They must be created together from the same commit.
