### ISSUE TITLE
Member Id always 0

### ISSUE THREAD

**Issue by EgartSites** [tdlib/td#1639]
I`m trying to get all members id`s in groups (basic and super). But everytime i`m receiveng that:
![image](https://user-images.githubusercontent.com/68100167/127467962-6523592b-8433-45b4-9a43-dfc00b79086b.png)
![image](https://user-images.githubusercontent.com/68100167/127468140-364932e0-7d55-440f-bc00-ce070cff50cf.png)
![image](https://user-images.githubusercontent.com/68100167/127468207-719f600e-ac96-4cc6-b97d-041361427b78.png)
Why users Id always 0? Help please...

**Comment by EgartSites** [comment]
@levlam

**Comment by levlam** [comment]
You are likely to use incompatible TDLib version. If your wrapper has autogenerated classes for API, you need to use exacty the same TDLib version, for which the classes were generated. The latest TDLib version has the field `member_id` instead of `user_id`.

**Comment by EgartSites** [comment]
Oh. Thank you very much. Going to fix source code of wrapper =D
