### ISSUE TITLE
There is no TextEntity in the received message

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#164]
When I send a message,like this:

       TdApi.TextEntity entities = new TdApi.TextEntity(0,"test".length(),new   TdApi.TextEntityTypeHashtag());

       TdApi.InputMessageText inputMessageText = new TdApi.InputMessageText(new TdApi.FormattedText("test", new TdApi.TextEntity[]{entities}), false, false);

        TdApi.SendMessage sendMessage = new TdApi.SendMessage(chat.id, 0, false, true, null, inputMessageText);

       Client.send(sendMessage);

There is no TextEntity in the received message,like this:

     mediaAlbumId = 0

       content = MessageText {

       text = FormattedText {

        text = "test"

        entities = Array[0] {

        }

    }

     webPage = null

     }

    replyMarkup = null

**Comment by levlam** [comment]
You can'r mark arbitrary text as a hashtag, they are found automatically. From InputMessageText.text documentation: "Formatted text to be sent. Only Bold, Italic, Code, Pre, PreCode and TextUrl entities are allowed to be specified manually"

**Comment by liaoyu1992** [comment]
thank you.

**Comment by liaoyu1992** [comment]
How do I send a message containing a webpage？

**Comment by levlam** [comment]
All kinds of messages that can be sent are described in InputMessageContent subclasses. Web pages are attached to a message automatically if the message contains a link.

**Comment by liaoyu1992** [comment]
thanks
