### ISSUE TITLE
Okay... What you say for that?

### ISSUE THREAD

**Issue by EgartSites** [tdlib/td#1640]
![image](https://user-images.githubusercontent.com/68100167/127553198-007c0acc-f991-4170-aa6c-5fcdbf286197.png)
https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl

**Comment by AYMENJD** [comment]
What is your problem?

**Comment by EgartSites** [comment]
Offical documentation says that member_id should be Int32. Here we can see MessageSender

**Comment by AYMENJD** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_sender_user.html

**Comment by EgartSites** [comment]
> https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_sender_user.html

Please, read all the text on screenshot and my message. And i`m waiting for the owner of repository :)

**Comment by zelenin** [comment]
look last stable version https://github.com/tdlib/td/blob/eb80924dad30af4e6d8385d058bb7e847174df5e/td/generate/scheme/td_api.tl#L486

**Comment by EgartSites** [comment]
> look last stable version
> 
> https://github.com/tdlib/td/blob/eb80924dad30af4e6d8385d058bb7e847174df5e/td/generate/scheme/td_api.tl#L486

user_id returns 0. I`m opened an issue and owner of the repository told me use member_id instead of user_id. But its not helped... After that i`m start searching in repository and found that (screenshot on the top)

**Comment by c0re100** [comment]
Obviously, you're using newest TDLib(latest commit?) with older wrapper(1.7.0?)...
If you want to `user_id`, please make sure your TDLib version is pull from [v1.7.0](https://github.com/tdlib/td/tree/v1.7.0)
FYI: Official documentation is for v1.7.0 and update when TDLib stable come out.

**Comment by EgartSites** [comment]
> Obviously, you're using newest TDLib(latest commit?) with older wrapper(1.7.0?)...
> If you want to `user_id`, please make sure your TDLib version is pull from [v1.7.0](https://github.com/tdlib/td/tree/v1.7.0)
> FYI: Official documentation is for v1.7.0 and update when TDLib stable come out.
> 
> and `MessageSender` here
> https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L679

Latest tdlib and fixed wrapper

**Comment by AYMENJD** [comment]
> I dont need message sender. I need ChatMember -_-

messageSender is type. if @levlam told you to use `member_id` that means you should use the latest tdlib version (v1.7.6).
if you want to access user_id it Should be like `chatMember.member_id.user_id`. otherwise check your wrapper.

`{'@type': 'chatMember', 'member_id': {'@type': 'messageSenderUser', 'user_id': 1088394097}...`

**Comment by c0re100** [comment]
Please check it-_-
https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L498

`chatMember member_id:MessageSender.......`
`chatMember` is using `member_id`, not `user_id`.......
and `member_id` stored in MessageSender.

**Comment by levlam** [comment]
`member_id` is of type `MessageSender` in the latest TDLib version. `MessageSender` can be one of two types `messageSenderUser` or `messageSenderChat`. If it is `messageSenderUser`, then it has `user_id` field inside.

**Comment by EgartSites** [comment]
> `member_id` is of type `MessageSender` in the latest TDLib version. `MessageSender` can be one of two types `messageSenderUser` or `messageSenderChat`. If it is `messageSenderUser`, then it has `user_id` field inside.

Yay! Thank you. So in my wrapper I need to change chatMember->memberId to MessageSender type and then parse messageSenderUser?

**Comment by EgartSites** [comment]
> Please check it-_-
> https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L498
> 
> `chatMember member_id:MessageSender.......`
> `chatMember` is using `member_id`, not `user_id`.......
> and `member_id` stored in MessageSender.

Okay, thanks.

**Comment by EgartSites** [comment]
> > I dont need message sender. I need ChatMember -_-
> 
> messageSender is type. if @levlam told you to use `member_id` that means you should use the latest tdlib version (v1.7.6).
> if you want to access user_id it Should be like `chatMember.member_id.user_id`. otherwise check your wrapper.
> 
> `{'@type': 'chatMember', 'member_id': {'@type': 'messageSenderUser', 'user_id': 1088394097}...`

Okay, thanks.

**Comment by EgartSites** [comment]
> > Please check it-_-
> > https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L498
> > 
> > `chatMember member_id:MessageSender.......`
> > `chatMember` is using `member_id`, not `user_id`.......
> > and `member_id` stored in MessageSender.
> 
> Okay, thanks. :)

**Comment by EgartSites** [comment]
@levlam @AYMENJD @c0re100 
Guys, thanks you all very much! It's worked. Closing issue)
