### ISSUE TITLE
SIGABRT using commit d4dc4f2a50f39b1c05efd955a6e9de0db2b197bc

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1641]
`[ 0][t 3][1627604606.817476034][MessagesManager.cpp:33091][#51][!Td][&*it != nullptr]   chat xxxxxxx server message 4706480 update_message`

**Comment by levlam** [comment]
I pushed a likely fix, but do you have a log with an example of requests, which lead to the issue?

**Comment by Cavallium** [comment]
No, that error happened twice today, randomly. I can't reproduce it in any
way.

**Comment by levlam** [comment]
This should be fixed in master.
