### ISSUE TITLE
sendAnimated Stikers

### ISSUE THREAD

**Issue by jiren85** [tdlib/td#1642]
Hello, 
I have a question..I'm tring to send an animated stickers  through "sendMessage Class"...the static stickers works but the animated stickers doesn't work. 
What a kind of class i use to send an Animated Stickers?
My project is in C++.

Thank you.

**Comment by levlam** [comment]
Animated stickers are not different from ordinary stickers and can be sent using `inputMessageSticker`.

Are you sure that your animated stickers has a correct TGS format?

**Comment by jiren85** [comment]
Hello.
Thank you for the answer. Yes for test i downloaded the tgs file from telegram server.
I think I understand where is the problem...If i send animated sticker to a secret chat id the messagge is an empty space, if I send the same animated sticker and I change only the "chat_id_" with "open chat" is working.
Static stickers, however, also work in secret chat.

**Comment by levlam** [comment]
Only animated stickers from sticker packs will work in secret chats.

**Comment by jiren85** [comment]
Thank you so much.
