### ISSUE TITLE
ApplicationVersion tdlib 

### ISSUE THREAD

**Issue by delsi24hh** [tdlib/td#1643]
Hello, I am writing a client application based on TDLiB and I have a question about the data transfer:

           If ( _authorizationState is TdApi . AuthorizationStateWaitTdlibParameters )
            {
                TdApi . TdlibParameters = new TdApi . TdlibParameters () ;   
                parameters . DatabaseDirectory = " tdlib " ;
                parameters . UseMessageDatabase = true ;
                parameters . UseSecretChats = true ;
                parameters . ApiId = 94575 ;
                parameters . ApiHash = " a3406de8d171bb422bb6ddf3bbd800e2 " ;
                parameters . SystemLanguageCode = " ru " ;
                parameters . DeviceModel = " desktop " ;
                **the parameters . ApplicationVersion = " 1.0 " ;**
                the parameters . EnableStorageOptimizer = true ;

ApplicationVersion = " 1.0 ", is this correct? because I release applications with exposures and different releases 1.0 (2390), 1.1 (2395)

TDLib doesn't correctly display my application on version - **(2390) instead of 1.0**

**Comment by levlam** [comment]
"ApplicationVersion" is the version of youк application. It can be arbitrary.

Where application version is displayed incorrectly?

**Comment by delsi24hh** [comment]
![testing](https://user-images.githubusercontent.com/88209186/127700333-8c97e4e3-9297-4721-8088-4daeb397d5a1.jpg)

My clients started noticing that telegram didn't accept my versions correctly, so I decided to beta-test the version and this is what my clients sent me:

I have a test version and it's: 6.2.3.4 (3766281)

6.2.3.4 - test version
(3766281) - android version of the system

1 session - we did via telethon
2 session - directly tdlib

why tdlib does not see 6.2.3.4 and gives out (3766281)
because telethon was able to accept 6.2.3.4 (3766281) and telegram gave out my test version

**Comment by levlam** [comment]
Check TDLib logs to see what exactly is sent in `setTdlibParameters`. TDLib only adds its own version to application version, but doesn't process application version in any other way.

**Comment by delsi24hh** [comment]
**TDLib only adds its own version to application version**

Yes, I also have a question, the own version of TDLiB is added, can it be removed?

Is there any risk that there is an addition? My app is designed for businesses and won't Telegram ban my clients because my app made a connection and added a parameter I can't change...

**Comment by levlam** [comment]
> Yes, I also have a question, the own version of TDLiB is added, can it be removed?

TDLib doens't provide a way to do that.

> Is there any risk that there is an addition?

Tehre are no risks.

**Comment by delsi24hh** [comment]
![testing](https://user-images.githubusercontent.com/88209186/127734045-2e7c544c-0fd1-47f2-bf70-068ff2cdf69a.jpg)

I got it, thanks.

Regarding the TDLiB logging - I looked at the logging of the appliation version, it accepts the transmission, but the output of the TDLiB does not show as it should...

Is this critical?

**Comment by levlam** [comment]
Could you check response of `getActiveSessions` method and the value of the field `application_version` there? Is it correct?

**Comment by delsi24hh** [comment]
session {
      id = 0
      is_current = true
      is_password_pending = false
      api_id = ///////
      application_name = "WeTel"
      application_version = "6.2.3.2 (3766281), TDLib 1.7.4"
      is_official_application = false
      device_model = "Sony Xperia L"
      platform = "Android"
      system_version = "10 Q (29)"
      log_in_date = 1628163409
      last_active_date = 1628163409
      ip = "///////////"
      country = "////////"
      region = ""
    }

**Comment by delsi24hh** [comment]
The transmission is correct, I also decided to check how your official Android app transmits and here are the results:

session {
      id = -2116957015588904764
      is_current = false
      is_password_pending = false
      api_id = 6
      application_name = "Telegram Android"
      application_version = "7.9.1"
      is_official_application = true
      device_model = "Huawei Honor 8C"
      platform = "Android"
      system_version = "8.1 O MR1 (27)"
      log_in_date = 1603924397
      last_active_date = 1628163055
      ip = ""
      country = ""
      region = ""
      
It turns out that the exposure in general is unnecessary? because in the technical documentation and even in the telegram version is X.X. (ХХХХХХ), but for some reason, as I sent above only X.X.X.

**Comment by levlam** [comment]
The Android app sends only app version without build number to the server.

**Comment by delsi24hh** [comment]
it turns out that the build version is redundant and I can remove it from the release to connect to telegram.... I understand correctly, since even the official application does not transfer
