### ISSUE TITLE
`Cache miss` when try to send message to a new user

### ISSUE THREAD

**Issue by haihongS** [tdlib/td#1646]
# Goals:
Use tdlib, I try to find a new user by username and then send message to him/her.

# Steps:
- SearchPublicChat
- CreatePrivateChat
- SendMessage

# Problems
The user received the message, but in my side, another client(mac) showed the user information(Cache Miss).

![image](https://user-images.githubusercontent.com/8394303/128307565-ff88aa4d-1610-4a5c-adb5-321f64a578b6.png)

**Comment by levlam** [comment]
This is the user's name.

**Comment by haihongS** [comment]
Correct, this is the privacy settings.
