### ISSUE TITLE
Uploading only changes to the file

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1647]
I use `editMessageMedia` with `inputFileLocal` to update contents of the previously uploaded text file.  Often change to the file is very small comparing to the total size of the file.  Is it possible to upload just difference for local/remote files instead of the whole file?

For relatively small files uploading the whole file is not a problem, however, for files growing in size, this became kind of a "problem" at some moment (f.i. you start uploading new file update while previous file update is still uploading).

Will it be difficult to implement `inputFileDiff diff:bytes = InputFile` in the TDLib?

Thanks

**Comment by levlam** [comment]
This is not possible. The whole file will be needed to uploaded by TDLib anyway.

>  you start uploading new file update while previous file update is still uploading

If this happens, the previous upload is automatically canceled. It shouldn't cause any problem.

**Comment by zevlg** [comment]
> This is not possible. The whole file will be needed to uploaded by TDLib anyway.
> 
> > you start uploading new file update while previous file update is still uploading
> 
> If this happens, the previous upload is automatically canceled. It shouldn't cause any problem.

This does not cause actual problems, eventually latest file changes uploads, but I’ve noticed it takes some time for large files comparing to small files that uploads instantly
