### ISSUE TITLE
How to add InlineKeyboardButton for sendMessageAlbum()

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1648]
I not found ReplyMarkup field :-(

**Comment by comerc** [comment]
... and tdliblib return error when call editMessageReplyMarkup()

"Message can't be edited"

**Comment by comerc** [comment]
... but getMessageLink has parametr for_album

I need some one for inline keyboard :-)

**Comment by levlam** [comment]
Clients aren't able to show inline buttons for media albums, so there is no way to add them.
