### ISSUE TITLE
java.lang.RuntimeException: TDLib fatal error: [ 0][t 0][1522309470.928822041][misc.h:343]

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#165]
I have encountered this error：

    java.lang.RuntimeException: TDLib fatal error:
     [ 0][t 0][1522309470.928822041][misc.h:343
    ][&(detail::is_same_signedness<RT, AT>::value) 
    || ((static_cast<RT>(r) < RT{}) == (static_cast<AT>    (a) < AT{}))]	
                                                 
      at org.drinkless.td.libcore.telegram.Client$1ThrowError.run(Client.java:284)
       at java.lang.Thread.run(Thread.java:848)

How do I solve this error？

**Comment by levlam** [comment]
When the error happens? Is it reproducible? Is it happens on the latest TDLib version?

**Comment by levlam** [comment]
Could you set log verbosity to 20, redirect log to a file by setLogFilePath and, when it happens next time in TDLib 1.2.0, send the log to @tdlib_bot?

**Comment by liaoyu1992** [comment]
ok

**Comment by liaoyu1992** [comment]
This error is reproduced and I send the log to @tdlib_bot.
