### ISSUE TITLE
Question | Generation and decode persistent_id

### ISSUE THREAD

**Issue by Keller18306** [tdlib/td#1650]
I use bot api to upload files to telegram servers, but it was very slow and didn't allow upload large files. I write in TypeScript and don't understand C ++. I found a library for working with MTProto, but after downloading the files, the data returned is not the same as from tdlib or bot-api.

![image](https://user-images.githubusercontent.com/23178771/128712401-fc44ab7f-400b-4e95-a8f5-524987fe9dcb.png)

I spent a few hours to figure it out and I realized that tdlib forms its file_id. I even found this place in the code, but I cannot understand what and how.

![image](https://user-images.githubusercontent.com/23178771/128712631-970b534f-ebef-4684-9dca-9d92d8251bec.png)

All I could understand is:
The last byte is the file_id version.
The first byte is the file type.

Could you explain how the file_id is formed?

**Comment by AYMENJD** [comment]
May this help you [tg-file-decoder](https://github.com/danog/tg-file-decoder)

**Comment by levlam** [comment]
Exact data encoded in `file_id` is a TDLib-specific implementation detail, which can change any time. Only the current source code can explain, what exactly and how is stored there.

**Comment by Keller18306** [comment]
It is understandable that the format will change. Probably for this there are versions.

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/129956191-858852f1-35f3-4b60-87b0-059a6608ba9d.png)
![image](https://user-images.githubusercontent.com/23178771/129956226-5aa61576-636a-4400-ba1e-4948a82fee96.png)
I cannot understand why there is a filling with zero bytes at the end of the line?

**Comment by levlam** [comment]
This is TL serialization format.

**Comment by Keller18306** [comment]
> This is TL serialization format.

But why was this done? Does this give any performance or read speed? As for me, it would be easier without them.

**Comment by levlam** [comment]
It does.
