### ISSUE TITLE
[HELP] Get updates for a specific chat

### ISSUE THREAD

**Issue by vfsoraki** [tdlib/td#1651]
I'm using https://gitlab.com/Fnux/elixir-tdlib/-/tree/master which uses https://github.com/oott123/tdlib-json-cli.

I've done logging in and it worked OK. My database is also OK, and I can restart app and I'm signed in.

First, I wait until I get `updateAuthorizationState` with an `authorization_state` of `authorizationStateReady`.

What I do is call `openChat` with a specific chat id, then I wait for `updateNewMessage` and check if this message is for the chat I'm interested in. If it is, I process message and then send a `viewMessages` for that message to let servers know that this message was viewed.

It kind of works. I also have my account open in desktop app. 

What I observe is that my app receives `updateNewMessage` with a delay of about 2 minutes. IDK why, and I'm asking if I'm doing it OK.

This 2 minutes delay is what I observe, and is not an exact value, but it feels like it always is the same. I'm sure I get the updates with a delay, but the value may vary.

IDK, is there anything I should call that makes this delay vanish? I've debugged for some hours, but I couldn't find the issue.

I've also tried listening for `updateNewChat`, and after I see that specific chat I call `openChat`. I sometimes get `updateNewChat` and sometimes not, but it does not make a difference.

Any help or tip is greatly appreciated!

**Comment by levlam** [comment]
> What I observe is that my app receives updateNewMessage with a delay of about 2 minutes.

This could happen if you are using not up-to-date version of TDLib. You need to update it frequently to avoid the delay.
