### ISSUE TITLE
[TelegramAPI] Can't sing in with test phone numbers

### ISSUE THREAD

**Issue by dosy4ev** [tdlib/td#1652]
There is a doc describing test phone numbers https://core.telegram.org/api/auth#test-phone-numbers
Is it still relevant?

I use test configuration from `https://my.telegram.org/apps`, phone numbers `99966XYYYY` and `XXXXX` as code (`22222` for my dc)
But still getting `The phone code entered was invalid (caused by SignInRequest)`

**Comment by levlam** [comment]
Yes, but code length was increased to 6 digits for the test numbers, so you need to use XXXXXX.

**Comment by dosy4ev** [comment]
Thank you. Six digit code is working.
