### ISSUE TITLE
Messages only arrive after I open them in Telegram

### ISSUE THREAD

**Issue by morseton** [tdlib/td#1657]
Hello, I'm having an issue with getting message updates.
Sometimes, there's a huge delay when receiving new message updates, and they only arrive once I open them in the official Telegram application.

I'm using tdweb version 1.6.10.

Is there any way to fix this?

Thanks.

**Comment by levlam** [comment]
You need to use the latest TDLib version and build the latest `tdweb` yourself to avoid this.

**Comment by morseton** [comment]
> You need to use the latest TDLib version and build the latest `tdweb` yourself to avoid this.

Ok, I'll try to update the tdweb version and see if it gets better. Thanks fo your time.
