### ISSUE TITLE
CMake failure

### ISSUE THREAD

**Issue by Jayceeit** [tdlib/td#1658]
I am unable to preform CMake on either my MacOS Big Sur or my Debian 9 server. The server completes the original make request, but the build-install requests results in the failure:
" error: no matching constructor for initialization of
      'unique_ptr<PromiseInterface<td::IPAddress> >'"
As well as a second error:
"/dev/td/tdutils/td/utils/unique_ptr.h:103:31: error: call to implicitly-deleted copy constructor of 'td::Promise<td::IPAddress>'
  return unique_ptr<Type>(new Type(std::forward<Args>(args)...));"

I'm not sure how to troubleshoot from here....Note this is from following the build instructions provided in the readme link.

**Comment by levlam** [comment]
Could you paste the whole compiler output?

**Comment by Jayceeit** [comment]
sudo cmake --build . --target install
[  0%] Built target tdsqlite
[  1%] Built target generate_mime_types_gperf
[  1%] Built target tdmime_auto
[ 18%] Built target tdutils
[ 19%] Built target tdactor
[ 22%] Built target tddb
[ 23%] Built target memprof
[ 25%] Built target tl-parser
[ 25%] Generate TLO files
[ 25%] Built target tl_generate_tlo
[ 27%] Built target tdtl
[ 29%] Built target generate_common
[ 30%] Generate common TL source files
[ 30%] Built target tl_generate_common
[ 31%] Built target tdapi
[ 32%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/GetHostByNameActor.cpp.o
In file included from /dev/td/tdnet/td/net/GetHostByNameActor.cpp:7:
In file included from /dev/td/tdnet/td/net/GetHostByNameActor.h:10:
/dev/td/tdactor/td/actor/PromiseFuture.h:317:20: error: no matching constructor for initialization of
      'unique_ptr<PromiseInterface<td::IPAddress> >'
  Promise(F &&f) : promise_(promise_interface_ptr<T>(std::forward<F>(f))) {
                   ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/utility:349:15: note: in instantiation of function template specialization
      'td::Promise<td::IPAddress>::Promise<td::Promise<td::IPAddress> &>' requested here
              second(_VSTD::forward<typename tuple_element<1,
              ^
/usr/include/c++/v1/vector:878:21: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<std::__1::pair<int, td::Promise<td::IPAddress> > >
      >::__construct_backward<std::__1::pair<int, td::Promise<td::IPAddress> > *>' requested here
    __alloc_traits::__construct_backward(this->__alloc(), this->__begin_, this->__end_, __v.__begin_);
                    ^
/usr/include/c++/v1/vector:1625:5: note: in instantiation of member function 'std::__1::vector<std::__1::pair<int,
      td::Promise<td::IPAddress> >, std::__1::allocator<std::__1::pair<int, td::Promise<td::IPAddress> > >
      >::__swap_out_circular_buffer' requested here
    __swap_out_circular_buffer(__v);
    ^
/usr/include/c++/v1/vector:1643:9: note: in instantiation of function template specialization
      'std::__1::vector<std::__1::pair<int, td::Promise<td::IPAddress> >, std::__1::allocator<std::__1::pair<int,
      td::Promise<td::IPAddress> > > >::__emplace_back_slow_path<int &, td::Promise<td::IPAddress> >' requested here
        __emplace_back_slow_path(_VSTD::forward<_Args>(__args)...);
        ^
/dev/td/tdnet/td/net/GetHostByNameActor.cpp:141:18: note: in instantiation of function template specialization
      'std::__1::vector<std::__1::pair<int, td::Promise<td::IPAddress> >, std::__1::allocator<std::__1::pair<int,
      td::Promise<td::IPAddress> > > >::emplace_back<int &, td::Promise<td::IPAddress> >' requested here
  query.promises.emplace_back(port, std::move(promise));
                 ^
/dev/td/tdutils/td/utils/unique_ptr.h:24:3: note: candidate constructor not viable: no known conversion from
      'unique_ptr<td::Promise<td::IPAddress>>' to 'const unique_ptr<td::PromiseInterface<td::IPAddress>>' for 1st argument
  unique_ptr(const unique_ptr &other) = delete;
  ^
/dev/td/tdutils/td/utils/unique_ptr.h:26:3: note: candidate constructor not viable: no known conversion from
      'unique_ptr<td::Promise<td::IPAddress>>' to 'unique_ptr<td::PromiseInterface<td::IPAddress>>' for 1st argument
  unique_ptr(unique_ptr &&other) noexcept : ptr_(other.release()) {
  ^
/dev/td/tdutils/td/utils/unique_ptr.h:36:3: note: candidate constructor not viable: no known conversion from
      'td::unique_ptr<td::Promise<td::IPAddress> >' to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument
  unique_ptr(std::nullptr_t) noexcept {
  ^
/dev/td/tdutils/td/utils/unique_ptr.h:38:12: note: candidate constructor not viable: no known conversion from
      'td::unique_ptr<td::Promise<td::IPAddress> >' to 'td::PromiseInterface<td::IPAddress> *' for 1st argument
  explicit unique_ptr(T *ptr) noexcept : ptr_(ptr) {
           ^
/usr/include/c++/v1/type_traits:225:78: note: candidate template ignored: disabled by 'enable_if'
      [with S = td::Promise<td::IPAddress>]
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
                                                                             ^
/dev/td/tdutils/td/utils/unique_ptr.h:23:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  unique_ptr() noexcept = default;
  ^
/dev/td/tdutils/td/utils/unique_ptr.h:103:31: error: call to implicitly-deleted copy constructor of 'td::Promise<td::IPAddress>'
  return unique_ptr<Type>(new Type(std::forward<Args>(args)...));
                              ^    ~~~~~~~~~~~~~~~~~~~~~~~~
/dev/td/tdactor/td/actor/PromiseFuture.h:242:14: note: in instantiation of function template specialization
      'td::make_unique<td::Promise<td::IPAddress>, td::Promise<td::IPAddress> &>' requested here
  return td::make_unique<std::decay_t<decltype(promise_interface<T>(std::forward<F>(f)))>>(
             ^
/usr/include/c++/v1/utility:349:15: note: in instantiation of function template specialization
      'td::Promise<td::IPAddress>::Promise<td::Promise<td::IPAddress> &>' requested here
              second(_VSTD::forward<typename tuple_element<1,
              ^
/usr/include/c++/v1/vector:878:21: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<std::__1::pair<int, td::Promise<td::IPAddress> > >
      >::__construct_backward<std::__1::pair<int, td::Promise<td::IPAddress> > *>' requested here
    __alloc_traits::__construct_backward(this->__alloc(), this->__begin_, this->__end_, __v.__begin_);
                    ^
/usr/include/c++/v1/vector:1625:5: note: in instantiation of member function 'std::__1::vector<std::__1::pair<int,
      td::Promise<td::IPAddress> >, std::__1::allocator<std::__1::pair<int, td::Promise<td::IPAddress> > >
      >::__swap_out_circular_buffer' requested here
    __swap_out_circular_buffer(__v);
    ^
/usr/include/c++/v1/vector:1643:9: note: in instantiation of function template specialization
      'std::__1::vector<std::__1::pair<int, td::Promise<td::IPAddress> >, std::__1::allocator<std::__1::pair<int,
      td::Promise<td::IPAddress> > > >::__emplace_back_slow_path<int &, td::Promise<td::IPAddress> >' requested here
        __emplace_back_slow_path(_VSTD::forward<_Args>(__args)...);
        ^
/dev/td/tdnet/td/net/GetHostByNameActor.cpp:141:18: note: in instantiation of function template specialization
      'std::__1::vector<std::__1::pair<int, td::Promise<td::IPAddress> >, std::__1::allocator<std::__1::pair<int,
      td::Promise<td::IPAddress> > > >::emplace_back<int &, td::Promise<td::IPAddress> >' requested here
  query.promises.emplace_back(port, std::move(promise));
                 ^
/dev/td/tdactor/td/actor/PromiseFuture.h:325:35: note: copy constructor of 'Promise<td::IPAddress>' is implicitly deleted because
      field 'promise_' has a deleted copy constructor
  unique_ptr<PromiseInterface<T>> promise_;
                                  ^
/dev/td/tdutils/td/utils/unique_ptr.h:24:3: note: 'unique_ptr' has been explicitly marked deleted here
  unique_ptr(const unique_ptr &other) = delete;
  ^
2 errors generated.
tdnet/CMakeFiles/tdnet.dir/build.make:62: recipe for target 'tdnet/CMakeFiles/tdnet.dir/td/net/GetHostByNameActor.cpp.o' failed
make[2]: *** [tdnet/CMakeFiles/tdnet.dir/td/net/GetHostByNameActor.cpp.o] Error 1
CMakeFiles/Makefile2:1239: recipe for target 'tdnet/CMakeFiles/tdnet.dir/all' failed
make[1]: *** [tdnet/CMakeFiles/tdnet.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by levlam** [comment]
Could you attach also `build/CMakeCache.txt` file?
