### ISSUE TITLE
Ability to resend messages / get all failed messages in a chat

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#166]
For now, there's no option to attempt message resend, when messages are not get delivered because of server issues. Unable to find a way to get all failed messages in a chat (for "Resend X messages" button).

**Comment by zevlg** [comment]
Does this issue have resolution with TDLib 1.4.0 ?

**Comment by levlam** [comment]
@zevlg It would be closed in that case.

**Comment by levlam** [comment]
Support for resending messages which failed to send was added in TDLib 1.5.0 via method `resendMessages`.

**Comment by levlam** [comment]
Support for getting all failed to send messages was added in TDLib 1.6.5 via the filter `searchMessagesFilterFailedToSend`.
