### ISSUE TITLE
Can not generate jni

### ISSUE THREAD

**Issue by mickeymgk** [tdlib/td#1661]
Followed the instruction in the read me but I get error while trying to generate JNI bindings. The error is: _No rule to make target '../td/bin/td_generate_java_api', needed by 'CmakeFiles/td_generate_java_api' . Stop_ _

**Comment by levlam** [comment]
It seems that build of TDLib wasn't successful.

Could you try build instructions from https://tdlib.github.io/td/build.html?language=Java?

**Comment by mickeymgk** [comment]
Yes here's what I tried
1. cloned tdlib in another directory
2. Installed dependencies with vcpkg
3. Run the first command from the build instruction selecting Java & windows 64
It compiled then said installing so I checked the example/java/td & all files were written done then went to java/build and run the Last command but I got the same error: 
mingw32-make.exe[2]: *** No rule to make target '../td/bin/td_generate_java_api' needed by 'CMakeFiles/td_generate_java_api'. Stop.
mingw32-make.exe[1] ** [CMakeFiles2:85: CMakeFiles/td_generate_java_api.dir/all] Error 2
mingw32-make.exe: ** [Makefile:135: all] Error 2

**Comment by levlam** [comment]
It is unusual that mingw32-make is used instead of MSBuild on Windows. Nevertheless, if TDLib's build was successful and it was installed to example/java/td, there should be no such error.

Could you attach the whole output of all commands?

**Comment by mickeymgk** [comment]
Sorry if I'm wasting your time, Here are the command outputs
[logs1.txt](https://github.com/tdlib/td/files/7092429/logs1.txt)
[logs2.txt](https://github.com/tdlib/td/files/7092431/logs2.txt)
As you might you notice, it is the second build command that fails, I even tried to run PowersShell as an Admin but with no luck I see ".exe" files being generated.
If the problem is with GCC let me know

**Comment by levlam** [comment]
Thanks.
Could you try to use full path instead ".." in the end of the command `cmake -G "MinGW Makefiles" ...`?

**Comment by levlam** [comment]
If this wouldn't help. try to rename "../td/bin/td_generate_java_api.exe" to "../td/bin/td_generate_java_api".

**Comment by mickeymgk** [comment]
When I use "..." it says no such file or directory

Then when I try to remove the ".exe" extension I get:
[20%] Generating Java TDLib Api source
 'td\bin\td_generate_java_api' is not recognized as an internal or external command

**Comment by levlam** [comment]
I meant not "...", but `cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) $(Resolve-Path ..)`.

Also, if you have already renamed the `td_generate_java_api` binary, then you can try to repeat original commands from the build instructions generator.

**Comment by mickeymgk** [comment]
Solved the problem by removing ".exe" then manually executing the make command by entering the build directory 
```
> make -f Makefile td_generate_java_api
> make -f Makefile build_java
> make -f Makefile generate_javadoc
```
Then comment out the add_custom_target() methods from CMakeLists.txt 

Excute the cmake command to generate build commands then build & install after that I got
A .dll file in the bin directory.

I'll automate this with batch file

Thanks for helping out

**Comment by levlam** [comment]
Did `cmake --build .` still fail after renaming the binary?

**Comment by mickeymgk** [comment]
Yeah it's weird but it failed 
One thing I noticed is that I had to rename "tdjni" to "libtdjni" in Example.java 

Can you help me on how to make a .so library to include it in a jar so it can be portable

**Comment by levlam** [comment]
What exactly do you mean by "portable"? Native code is non-portable by definition and you will need separately build shared libraries at least for each pair OS + processor architecture.

I'm not sure whether there is a standard way to bundle shared libraries in jar.
