### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#1662]
Hello , when i wanna build telegram-bot ill face this error : 

/root/tdbot/main.cpp: In function ‘void main_loop()’:
/root/tdbot/main.cpp:409:7: error: ‘ConcurrentScheduler’ is not a member of ‘td’
   td::ConcurrentScheduler scheduler;
       ^~~~~~~~~~~~~~~~~~~
/root/tdbot/main.cpp:410:3: error: ‘scheduler’ was not declared in this scope
   scheduler.init(4);
   ^~~~~~~~~
/root/tdbot/main.cpp:412:42: error: expected primary-expression before ‘>’ token
   scheduler.create_actor_unsafe<CliClient>(0, "CliClient", port, accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                          ^
/root/tdbot/main.cpp:412:47: warning: left operand of comma operator has no effect [-Wunused-value]
   scheduler.create_actor_unsafe<CliClient>(0, "CliClient", port, accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                               ^~~~~~~~~~~
/root/tdbot/main.cpp:412:60: warning: right operand of comma operator has no effect [-Wunused-value]
   scheduler.create_actor_unsafe<CliClient>(0, "CliClient", port, accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                            ^~~~
/root/tdbot/main.cpp:412:107: warning: right operand of comma operator has no effect [-Wunused-value]
 ent>(0, "CliClient", port, accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                     ^~~~~~~~~~~
/root/tdbot/main.cpp:412:120: warning: second operand of conditional expression has no effect [-Wunused-value]
 lient", port, accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                     ^~~~~~~~~~
/root/tdbot/main.cpp:412:120: warning: third operand of conditional expression has no effect [-Wunused-value]
/root/tdbot/main.cpp:412:132: warning: right operand of comma operator has no effect [-Wunused-value]
 , accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                     ^~~~~~~~~~
/root/tdbot/main.cpp:412:144: warning: right operand of comma operator has no effect [-Wunused-value]
 _tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                     ^~~~~
/root/tdbot/main.cpp:412:151: warning: right operand of comma operator has no effect [-Wunused-value]
 nnections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                     ^~~~~~~~
/root/tdbot/main.cpp:412:161: warning: right operand of comma operator has no effect [-Wunused-value]
 ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                     ^~~~~
/root/tdbot/main.cpp:412:168: error: ‘struct td::TdParameters’ has no member named ‘release’
 .0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();
                                                                      ^~~~~~~
CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:87: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:164: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2

**Comment by levlam** [comment]
Did you tried to update TDLib without updating tdbot's source?

**Comment by Kia-Pashang** [comment]
> Did you tried to update TDLib without updating tdbot's source?

i wanna build it in this way https://github.com/rizaumami/tdbot , now i faced that error please help me to fix it

this error is about this part : 

**void main_loop() {
  if (logname.length () > 0) {
    static td::FileLog file_log;
    file_log.init (logname);
    td::log_interface = &file_log;
  }

  SET_VERBOSITY_LEVEL(VERBOSITY_NAME(FATAL) + verbosity);

  td::ConcurrentScheduler scheduler;
  scheduler.init(4);

  scheduler.create_actor_unsafe<CliClient>(0, "CliClient", port, accept_any_tcp_connections ? "0.0.0.0" : "127.0.0.1", lua_script, login_mode, phone, bot_hash, param).release();

  scheduler.start();
  while (scheduler.run_main(100)) {
  }
  scheduler.finish();
}**

**Comment by levlam** [comment]
The latest TDLib's version, supported by tdbot is 1.7.0: https://github.com/vysheng/tdbot.

**Comment by Kia-Pashang** [comment]
> The latest TDLib's version, supported by tdbot is 1.7.0: https://github.com/vysheng/tdbot.

Thanks a million "SOLVED"
