### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by thomasd3** [tdlib/td#1663]
Is it possible to get messages through push notifications (using .net)?
We have a project where someone implemented a telegram interface using this lib, but he does polling to get the latest messages.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started, especially section about updates handling and `updateNewMessage`.

**Comment by thomasd3** [comment]
I went through it, but this doesn't help me to know if the updateNewMessage event is triggered through a message received by a push notification, or is the result of polling inside the lib.
The app in question uses Telegram to pass trading signals so latency is very important which is why I am curious about the internal implementation.

**Comment by levlam** [comment]
There is no such thing as "polling" in Telegram. TCP connections are bidirectional, so most updates are "pushed" by the server if client has an active network connection.

**Comment by thomasd3** [comment]
ok, thanks; I have to understand what he did; he used TLSharp and has somewhere a polling interval of 300ms. I have no idea what he did exactly, but I'll investigate.
