### ISSUE TITLE
How to change log verbosity level?

### ISSUE THREAD

**Issue by pylakey** [tdlib/td#1664]
[td_set_log_verbosity_level](https://core.telegram.org/tdlib/docs/td__log_8h.html#aebf8cd00741501f033c47e2e0ed8a15b) is deprecated, by how log verbosity level could be changed?

**Comment by levlam** [comment]
See original documentation: https://github.com/tdlib/td/blob/7135caa2bef38939f58e9e206db83fd316236682/td/telegram/td_log.h#L49.

**Comment by pylakey** [comment]
Thanks a lot
