### ISSUE TITLE
What is the lowest latency method to get messages from a channel?

### ISSUE THREAD

**Issue by thomasd3** [tdlib/td#1668]
I'm dealing with latency sensitive messages and would like to find how to get a new message as fast as possible on a server.

Would opening a listening socket and connecting with the client as 'web' work?

**Comment by levlam** [comment]
Channels are not suitable for receiving messages with "low latency". Only bots and channel administrator receive channel messages as soon as possible.

**Comment by thomasd3** [comment]
I know, Telegram is a horrible choice for this, but it's out of our hands: the people sending the signals have decided to use Telegram.

The current client code is calling (from TeleSharp) "Client.SendRequestAsync<TLAbsDifference>(req, canceller.Token)" in a loop, every 300ms; I don't even know what TeleSharp does under the hood, I wasn't involved with this part.

I am looking for an example where we could just use tdlib directly and get updates sent to a listening socket, but I can't seem to find an example listening to events; I saw examples sending messages but not that.

**Comment by levlam** [comment]
There are no updates sent to a socket for ordinary channel subscribers.

**Comment by thomasd3** [comment]
so as a channel subscriber, the only option is to poll regularly?

**Comment by levlam** [comment]
You can be flood-limited if too much requests are sent.

**Comment by thomasd3** [comment]
so I am a little bit confused. When I started to look into this, I asked another question regarding push notifications. At that time you told me
"There is no such thing as "polling" in Telegram. TCP connections are bidirectional, so most updates are "pushed" by the server if client has an active network connection."

But now so that I can understand:
- there is no push to socket
- I can't poll too often and your answer said there is no polling?

what is the underlying mechanism used? I'm sorry if this seems like a basic question, but I'm a bit lost here :)

**Comment by levlam** [comment]
The updates are pushed, but there is no way to immediately push an update to all channel subscribers. You will receive an update eventually, but there will be some delay incompatible with "low latency".

**Comment by thomasd3** [comment]
so the library is listening for updates on a socket, from Telegram, but these updates are propagated in some unpredictable manner? we're the receiving party in this case.

**Comment by levlam** [comment]
Yes.

**Comment by p-i-** [comment]
> There are no updates sent to a socket for ordinary channel subscribers.

This confuses me.
How is TDLib getting new message notifications if not through an open socket with a Telegram data center?
My assumption was that Telegram servers allow remote socket connections, and when a message arrives at their datacenter they emit a packet to all relevant socket connections.

How else could they possibly function?
Is TDLib therefore sending periodic requests for updates?

**Comment by levlam** [comment]
>  and when a message arrives at their datacenter they emit a packet to all relevant socket connections.

This would result in enormous network and CPU usage bursts. Instead packets are slowly propagated to all channel subscribers through opened socket connections and eventually reach all of them.

**Comment by BertramPetersen** [comment]
> Channels are not suitable for receiving messages with "low latency". Only bots and channel administrator receive channel messages as soon as possible.

Does that mean that if all subscribers of a telegram channel, would be bots, all would receive messages faster, or would this just displace the issue?

**Comment by levlam** [comment]
Bots can't be channel subscribers. They can be added to channels only as administrators.

**Comment by BertramPetersen** [comment]
I'm sorry if it's inappropriate to ask here, but I've read the referenced materials and I think I understand the issue somewhat. But now my question is this, if telegram is simply not suitable for 'low latency bulk messaging' then what would be? Do you know if any paid services that offer dedicated 'bandwidth' to achieve latency less than a second?

**Comment by levlam** [comment]
I don't know such services.

**Comment by BertramPetersen** [comment]
As I understand it, the size of the Channel has a great impact on the avg latency, but in that case, would multiple smaller channels not eliminate this factor to an extend?

**Comment by p-i-** [comment]
Discord has a far lower latency. It's based on Erlang as I understand, which was created for telecoms.

**Comment by levlam** [comment]
Programming language doesn't matter. It can't affect physics law.

**Comment by pjpjq** [comment]
@levlam  Can I get message faster by keep polling `GetChannelDifference`?

**Comment by ghoshben** [comment]
one question does telegram premium somehow helps it ?

**Comment by levlam** [comment]
No.
