### ISSUE TITLE
Moving `is_blocked` from `userFullInfo` to `user` itself

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1669]
For chats `is_blocked` is available in the chat struct itself, without the need to request corresponding `getXXXFullInfo`.  On the other hand, for users you need to request `getUserFullInfo` in order to get value for `is_blocked`.  Is it possible to move `is_blocked` from userFullInfo to user struct itself as it is done for chats?

In our client it is possible to ignore messages in the chat from blocked users, however, in large groups this leads to thousands of `getUserFullInfo` requests to find out that user is blocked.

One workaround we come up with is to fetch blocked users with `getBlockedMessageSenders` at start and then keep this list in sync with `updateUserFullInfo` updates, but it looks a bit ugly.  With chats there is no such complications, `is_blocked` is always available without additional requests.

What do you think?

Thanks

**Comment by levlam** [comment]
> For chats is_blocked is available in the chat struct itself, without the need to request corresponding getXXXFullInfo.

In fact, this is not true. TDLib calls `getXXXFullInfo` once under the hood to fetch the value of this field.

As you correctly noted, automatic call of `getXXXFullInfo` for all users can lead to thousands otherwise useless requests, so it is not possible to move `is_blocked` to the `user` object.

**Comment by zevlg** [comment]
> > For chats is_blocked is available in the chat struct itself, without the need to request corresponding getXXXFullInfo.
> 
> In fact, this is not true. TDLib calls `getXXXFullInfo` once under the hood to fetch the value of this field.

Ah, I see!

> As you correctly noted, automatic call of `getXXXFullInfo` for all users can lead to thousands otherwise useless requests, so it is not possible to move `is_blocked` to the `user` object.

Yeah, we'll stick with `getBlockedMessageSenders` and `updateUserFullInfo` solution then.
