### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#1670]
Hello , what is the methods for AddProxy , Edit Proxy , Disable or Enable Proxy , Get Proxies and Remove Proxy for telegram-bot (tdbot) ?

**function tdbot.setProxy(proxy, server, port, username, password, callback, data)
  assert (tdbot_function ({
    ["@type"] = 'setProxy',
    proxy = {
      ["@type"] = 'proxy' .. proxy,
      server = server,
      port = port,
      username = username,
      password = password
    }
  }, callback or dl_cb, data))
end**
This is not working anymore ..

**Comment by levlam** [comment]
See [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) for the latest TDLib API scheme and [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the list of TDLib API changes. The method `setProxy` was removed in TDLib 1.3.0.
