### ISSUE TITLE
How to add tdlib to a gradle project?

### ISSUE THREAD

**Issue by shrey-183** [tdlib/td#1671]
I have followed the documentation and have build TDlib on my linux machine. My goal is to integrate tdlib to a Java project and I am not sure how to do that. Here is a brief tree structure of the project: 

```
.
├── archive-aws.Dockerfile
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
├── README.md
├── services
│   └── recorder
│       ├── application
│       │   ├── build.gradle
│       │   └── src
│       │       └── main
│       │           ├── java
│       │           │   └── com
│       │           │       └── organization-name
│       │           │           └── project-name
│       │           │               └── recorder
│       │           │                   └── application
│       │           │                       └── RecorderApplication.java
│       │           └── resources
│       │               ├── application-local.yml
│       │               └── application.yml
│       ├── shipping
│       │   ├── build.gradle
│       │   └── src
│       │       └── main
│       │           └── java
│       │               └── com
│       │                   └── organization-name
│       │                       └── project-name
│       │                           └── recorder
│       │                               └── shipping
│       │                                   └── MessageSink.java
└── settings.gradle
```

I would like to use the tdlib in `MessagesSink.java` however I am not sure how to do that. I am guessing that something needs to be added to the `build.gradle` file, either under the directory `shipping` or under the the main directory. But I don't know what I should add and in which file. Any advice regarding this issue would be much appreciated. Thanks in advance!

**Comment by levlam** [comment]
Tou need to add org/drinkless/tdlib/{Client,Log,TdApi].java files as a source files and the binary libtdjni as a JNI library to your project. Adding the library to a "lib" directory should be enough. See https://stackoverflow.com/questions/60402296/add-smartid-reader-jni-library-into-existing-gradle-project for more examples and details.

**Comment by shrey-183** [comment]
Thank you very much for your reply!
