### ISSUE TITLE
Changed tdbot_function

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#1672]
Hello , all the tdbot_function are changed where should i get the functions ?
for example i use wanna leave a chat ; i use

**local function chatMemberStatusLeft(chatid)
local Botid=tonumber(Database:get("botid"))
local chat_member_status={}
chat_member_status["@type"]="chatMemberStatus".."Left"
tdbot_function({["@type"]="setChatMemberStatus",chat_id=chatid,user_id=Botid,status=chat_member_status},Dc,data)
end**
but i face this :

**{
  ["@type"] = "error",
  code = 400,
  message = "Member identifier is not specified"
}**

**Comment by Kia-Pashang** [comment]
Hello ??

**Comment by AYMENJD** [comment]
Because `member_id` is object not number.

**Comment by Kia-Pashang** [comment]
> Because `member_id` is object not number.
> See #1640.

So , user_id gives this error

{
["@type"] = "error",
code = 400,
message = "Member identifier is not specified"
}

i wanna use this : 
local function chatMemberStatusLeft(chatid)
local Botid=tonumber(Database:get("botid"))
local chat_member_status={}
chat_member_status["@type"]="chatMemberStatus".."Left"
tdbot_function({["@type"]="setChatMemberStatus",chat_id=chatid,user_id=Botid,status=chat_member_status},Dc,data)
end

how can i use it in telegram-bot ? for both user_id and member_id gives those errors

**Comment by AYMENJD** [comment]
I don't know in lua how but that is wrong you should use `member_id` with `MessageSender` type.
See levlam https://github.com/tdlib/td/issues/1640#issuecomment-889519396

**Comment by levlam** [comment]
On-site documentation was updated to match TDLib 1.8.0 API.
