### ISSUE TITLE
Why does getSupergroupFullInfo take an int32 ID but my group has an int64 ID?

### ISSUE THREAD

**Issue by dominique120** [tdlib/td#1673]
I'm trying to run ```getSupergroupFullInfo``` for a group but the id of this group is an int64 so whenever I compile I get the usual warning for possible loos of data and then when executing I always get that the group does not exist.

Am I misunderstanding what the correct id for the group is? Is it local or is it something on Telegrams server?

I've had the same issue with all the other functions related to supergroups.

**Comment by AYMENJD** [comment]
Because you are using `chat_id` not `supergroup_id`.
Every supergroup has `supergroup_id` that you can get it by calling `getChat` then `chat.type.supergroup_id`.

**Comment by dominique120** [comment]
That was it, thanks!
