### ISSUE TITLE
Search members of a channel by Farsi characters

### ISSUE THREAD

**Issue by ariamousavi945** [tdlib/td#1674]
The `supergroupMembersFilterSearch` class is get a `std::string` parameter for search. 
How can we set Farsi characters as search string ?

**Comment by levlam** [comment]
All strings are UTF-8 encoded in TDLib.

**Comment by ariamousavi945** [comment]
@levlam When I use Farsi characters for search, the result is not correct. The TDLib server is return all members in channel not those that contain search string in their first name, last name or username?

**Comment by levlam** [comment]
Do you have an example of a public group and a search request, which returns an incorrect result?

**Comment by ariamousavi945** [comment]
for example when I search the term "حسن" in the following supergroup, it returns all members that doesn't  even contain "حسن":
[https://t.me/villa_markett](https://t.me/villa_markett)

**Comment by levlam** [comment]
I have just tested through TDLib that it works absolutely correct, returning only members with that string in the name.

**Comment by ariamousavi945** [comment]
Did you run the api in C++?

**Comment by levlam** [comment]
I tested through Unigram, but there is no difference.

**Comment by ariamousavi945** [comment]
@levlam Thank you. It was my mistake and now I can get correct result for Farsi characters search

**Comment by ariamousavi945** [comment]
@levlam I have another question. Is there any way to search regular expression in `supergroupMembersFilterSearch` class?

**Comment by levlam** [comment]
No.
