### ISSUE TITLE
donot join the Supergroup but get the updateNewChat noti

### ISSUE THREAD

**Issue by lucian-ma** [tdlib/td#1675]
i donnot join this Supergroup , but get this

{
    "@type": "updateNewChat",
    "chat": {
        "@type": "chat",
        "id": -1001075793644,
        "type": {
            "@type": "chatTypeSupergroup",
            "supergroup_id": 1075793644,
            "is_channel": true
        },
        "title": "\u5e01\u5b89\u516c\u544a",
        "photo": {
            "@type": "chatPhotoInfo",
            "small": {
                "@type": "file",
                "id": 113,
                "size": 0,
                "expected_size": 0,
                "local": {
                    "@type": "localFile",
                    "path": "",
                    "can_be_downloaded": true,
                    "can_be_deleted": false,
                    "is_downloading_active": false,
                    "is_downloading_completed": false,
                    "download_offset": 0,
                    "downloaded_prefix_size": 0,
                    "downloaded_size": 0
                },
                "remote": {
                    "@type": "remoteFile",
                    "id": "AQADBQATxfRqanQAAwIAAxShO-sW____3do6NxcYQgIy6gIAAR4E",
                    "unique_id": "AQADxfRqanQAAzLqAgAB",
                    "is_uploading_active": false,
                    "is_uploading_completed": true,
                    "uploaded_size": 0
                }
            },
            "big": {
                "@type": "file",
                "id": 114,
                "size": 0,
                "expected_size": 0,
                "local": {
                    "@type": "localFile",
                    "path": "",
                    "can_be_downloaded": true,
                    "can_be_deleted": false,
                    "is_downloading_active": false,
                    "is_downloading_completed": false,
                    "download_offset": 0,
                    "downloaded_prefix_size": 0,
                    "downloaded_size": 0
                },
                "remote": {
                    "@type": "remoteFile",
                    "id": "AQADBQATxfRqanQAAwMAAxShO-sW____3do6NxcYQgI06gIAAR4E",
                    "unique_id": "AQADxfRqanQAAzTqAgAB",
                    "is_uploading_active": false,
                    "is_uploading_completed": true,
                    "uploaded_size": 0
                }
            },
            "has_animation": false
        },
        "permissions": {
            "@type": "chatPermissions",
            "can_send_messages": false,
            "can_send_media_messages": false,
            "can_send_polls": false,
            "can_send_other_messages": false,
            "can_add_web_page_previews": false,
            "can_change_info": false,
            "can_invite_users": false,
            "can_pin_messages": false
        },
        "positions": [],
        "is_marked_as_unread": false,
        "is_blocked": false,
        "has_scheduled_messages": false,
        "can_be_deleted_only_for_self": false,
        "can_be_deleted_for_all_users": false,
        "can_be_reported": true,
        "default_disable_notification": false,
        "unread_count": 0,
        "last_read_inbox_message_id": 0,
        "last_read_outbox_message_id": 2251799812636672,
        "unread_mention_count": 0,
        "notification_settings": {
            "@type": "chatNotificationSettings",
            "use_default_mute_for": true,
            "mute_for": 0,
            "use_default_sound": true,
            "sound": "default",
            "use_default_show_preview": true,
            "show_preview": true,
            "use_default_disable_pinned_message_notifications": true,
            "disable_pinned_message_notifications": false,
            "use_default_disable_mention_notifications": true,
            "disable_mention_notifications": false
        },
        "reply_markup_message_id": 0,
        "client_data": ""
    },
    "@client_id": 1
}

**Comment by levlam** [comment]
`updateNewChat` is sent for every chat, which should be known to the app. Positions of a chat in chat list are described by the field "positions", which will remain empty for this chat.

**Comment by lucian-ma** [comment]
> `updateNewChat` is sent for every chat, which should be known to the app. Positions of a chat in chat list are described by the field "positions", which will remain empty for this chat.

yes i can ignore it by  "positions",but i still want to know why i can receive this msg

**Comment by levlam** [comment]
Because this chat is needed for some request response or another update.

**Comment by daniloavilez** [comment]
I'm listening to `updateNewChat` as well in my app and I had same behavior described by you. What I understood is that these events are kind of history linked with a group is in your chat you have now. I haven't found informations about it to confirm my theory.
