### ISSUE TITLE
Memory Leaking on C# .NET.

### ISSUE THREAD

**Issue by AleksanderZverev** [tdlib/td#1676]
Hello. We have a problem with memory leaking on C# .NET TdLib. Unmanaged memory increases over time, but .NET Memory almost not increases, so we suppose it's a problem under the TdLib.

I tried enable all databases and it made leaking much faster than it's not enabled.

For 24 hours it took almost 500 MB of RAM:
![image](https://user-images.githubusercontent.com/67056960/133545053-f3f71625-4ddb-43fb-880f-4d4f6ec23bf8.png)

**Comment by AleksanderZverev** [comment]
Stable increasing after user authorization:
![image](https://user-images.githubusercontent.com/67056960/133547782-45f00f93-3d7d-4b36-9afe-8fbcdb935c15.png)

**Comment by levlam** [comment]
We tested a lot of times that TDLib properly releases all allocated memory.

TDLib has a cache of users and chats, which speeds up all requests and gives a big flexibility for the application. The size of the in-memory cache grows over time, so if app wants to flush it, it needs to close and reopen TDLib instance. Also, note that default memory allcoators usually don't return memory to operating system, but instead the memory is reused for subsequent unmanaged memory allocations.

Between, when all databases are enabled, TDLib is able to unload messages from the cache, so the memory usage should grow slower in this case.

**Comment by AleksanderZverev** [comment]
Ok, we'll try to enable all databases. I'll write about the results in a week later.

**Comment by AleksanderZverev** [comment]
Enabling all databases made memory growing more slowly. But disposing TdLib instance doesn't give any effect.
We disposed it  at 00:00 and created new at 01:00, how can u see, it doesn't released memory at all.

*yellow line means that new version of project was deployed and start working.
![image](https://user-images.githubusercontent.com/67056960/134615306-68a81c13-c57b-4eb8-a0c9-23d2e88395ff.png)

**Comment by AleksanderZverev** [comment]
That is the code which we called:
![image](https://user-images.githubusercontent.com/67056960/134615730-c2c90881-2e9b-4c9e-80a5-dd30ba8c15ed.png)

**Comment by AleksanderZverev** [comment]
Local test shows that disposing client releases only .net memory and doesn't effect to unmanage memory (which is used by C++ JsonTdClient?).

![image](https://user-images.githubusercontent.com/67056960/134617256-fae7b774-0dad-42e7-9e4b-979e7bce8597.png)
![image](https://user-images.githubusercontent.com/67056960/134617299-a932c812-3bef-476e-873c-5e39528d1076.png)

**Comment by levlam** [comment]
> Also, note that default memory allcoators usually don't return memory to operating system, but instead the memory is reused for subsequent unmanaged memory allocations.

Your memory profiler is C#-specific and doesn't distinguish between being used and freed (and ready to reuse) unmanaged memory.

Between, how much threads are you using to send requests to TDLib?

**Comment by AleksanderZverev** [comment]
> Between, how much threads are you using to send requests to TDLib?
It's an asynchronous application, so we use many "await" constructions and it results in many threads are used.

**Comment by levlam** [comment]
If you don't create threads explicitly, then C# uses only limited number of threads from a thread pool, which is fine..

**Comment by AleksanderZverev** [comment]
So how to resolve the problem? Only reopen the application?

**Comment by levlam** [comment]
Instance recreation should also help, because the new instance will reuse memory freed by the previous instance. But if it has no significant impact for you, then only closing the whole application can help to deal with heap fragmenttion.

**Comment by AleksanderZverev** [comment]
> Between, how much threads are you using to send requests to TDLib?

If we set less limit threads, will it reduce the memory using?

**Comment by levlam** [comment]
> If we set less limit threads, will it reduce the memory using?

This is very unlikely to help.

**Comment by AleksanderZverev** [comment]
Ok, understood. Thank you very much for your help, levlam! :)
