### ISSUE TITLE
Type of receiving update

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1677]
I use searchPublicChat function, but I don`t completely understand which update from this [list](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_update.html) 
should handle as answer from this function

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#tdlib-interface.

**Comment by HellFinger-s** [comment]
I read it, but I didn't fully understand it. When I use SearchPubliсChat, an object of the chat type is returned to me. I don't quite understand which update is responsible for this

**Comment by levlam** [comment]
This is not an update. This is an object of the type `Chat` sent to you, which you can receive through a `receive` method and match with the corresponding request using request ID/`@extra` field/whatever way provided by your wrapper.

**Comment by HellFinger-s** [comment]
I figured it out, thank you.
