### ISSUE TITLE
Efficient downloading of photo in message where image-CDN does not match bot-DC

### ISSUE THREAD

**Issue by p-i-** [tdlib/td#1678]
I'm currently working with Telethon and experiencing an issue downloading the contained photo from a message.

I'm trying to get the time from message-send to image-download as close to a theoretical minimum as I am able.

The problem occurs when there is a mismatch between the DC that the bot/telegram-account was registered to and the CDN holding the image.

If they match I get a download time of ~20ms from a server near the target CDN. However if the user is registered with a different DC, I get download times upwards of one second.

Would I be likely to bump into the same problem with tdlib?
If it is solvable, while I will try myself, I would gladly pay for a solution and I invite any interested engineer to contact me pi[at]pipad[dot]org
🙏

**Comment by levlam** [comment]
You wouldn't know, unless you try.

**Comment by p-i-** [comment]
I tried, alas I still do not know.  Issue migrated to https://github.com/tdlib/td/issues/1686

**Comment by AYMENJD** [comment]
I recommend you to move from github to https://t.me/tdlibchat.
