### ISSUE TITLE
"unix_time" Option

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1681]
There is "unix_time" option exists, that, I believe, is used by clients to synchronize client/server clocks to correctly display timing info received from the server.  To do so, when client receives `updateOption` for "unix_time" it calculates adjustment for the local clock, so client/server clocks are in sync.

However, if there is a delay before `updateOption` is processed by client (say client processes events sequently and there is a bunch of heavy events to process before `updateOption`), then client's local clock drifts and calculated clock adjustment became incorrect.

Maybe send "unix_time_diff" option along the side with "unix_time", which denotes client/server clock difference, what do you think?

Thanks

**Comment by levlam** [comment]
It would be impossible to define from what exactly the difference is calculated. Descriptions like `from std::chrono::steady_clock::now()` would be useless for anyone programming not in C++ or using a different STL implementation. Descriptions like `if used on Linux >= 2.6.39, then from clock_gettime(CLOCK_BOOTTIME, ...); if used on Linux >= 2.6.28, then from clock_gettime(CLOCK_MONOTONIC_RAW, ...), ...` can help to correctly interpret the difference for С programmers, but would be useless for everyone else. There is no way to predict, what the app would use to calculate monotonic time, so there is no way to provide it with a difference.

If you really think that the delay between update sending and receiving matters, then you can call `getOption` explicitly any time to receive a better estimate.

**Comment by zevlg** [comment]
Yeah, one of the approaches I come with is to explicitly request for `getOption` to make sure events processing queue is empty, however I’ve got some problems with it, I need time to check everything before describing them. Another approach is to process `updateOption` events as out-of-band events, so there will be no local clock drift due to other events processing

Let me keep this issue open for few days to check everything with explicit `getOption` request approach

**Comment by zevlg** [comment]
Explicitly requesting `getOption` "unix_time" while client is in idle state does the trick, thanks!
