### ISSUE TITLE
Does TDLib support an in-memory/non-persestent session (equivalent to Telethon's StringSession)?

### ISSUE THREAD

**Issue by p-i-** [tdlib/td#1684]
In Telethon it is not necessary to have a persistent .session file.  Instead one may create a StringSession: https://github.com/LonamiWebs/Telethon/blob/master/telethon/sessions/string.py

This contains:
```
.dc_id
._server_address
._auth_key
```

Is the same model possible with TDLib?  i.e. Can I re-use the data from an existing (Telegram) StringSession to create an in-memory session with TDLib?

Or does creating a session in TDLib require creating a .sqlite DB?

**Comment by levlam** [comment]
You can't transfer sessions between different implentations.

**Comment by p-i-** [comment]
Thankyou!
How about the title-question... is it possible to make an in-memory session with TDLib?
And can I download a photo to memory?
I'm currently using:
```
    td_send({'@type': 'downloadFile', 'file_id': photos[1]['photo']['id'],'priority':32,'offset':0,'limit':0,'synchronous':True})
```
But that saves to disk, and emits a 'did-download' notification:
```
    if event['@type'] == 'file':
        dlfilepath = event['local']['path']
        im  = Image.open(dlfilepath)
```
Is it possible to download straight to memory?

**Comment by levlam** [comment]
No. Persistent storage is required for database and files.
