### ISSUE TITLE
Check phone number

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#1685]
Hi. Is it possible to check the client's phone number from the data in `tdlib` directory? Or is there any other ways?

**Comment by levlam** [comment]
Use `getMe` request. There are no other ways.

**Comment by yasharzb** [comment]
Thanks. As is there any fix chatId for the announcement service? the one which sends the client things like verification code?

**Comment by levlam** [comment]
You can use `getOption("telegram_service_notifications_chat_id")` to get the chat ID.
