### ISSUE TITLE
Long download time (~2s) for downloading message photo

### ISSUE THREAD

**Issue by p-i-** [tdlib/td#1686]
I tried 2 experiments:
On DC1-group.
Session with DC1-user, on USA server.

FIRST TEST

Posting from DC1 user

1632812344.0733573 ⚡️ {'@type': 'updateNewMessage'
1632812344.0758429 ⚡️ {'@type': 'file'

So, ~20ms from getting the message to completing the download

SECOND TEST:

Post from a DC4 user to the same group:

1632812504.2836902 ⚡️ {'@type': 'updateNewMessage'
1632812506.1265829 ⚡️ {'@type': 'file'

It's nearly 2 seconds.

So if the image is getting stashed on CDN1 we get a fast download.
But if it's getting stashed on CDN4, the download is _really_ slow.

Is there any way to speed this up?

**Comment by p-i-** [comment]
Edit: Experimenting, I find that while the first download on a new CDN file is slow, subsequent downloads from that same CDN are fast. But now the next download from the _original_ CDN is slow. And so on. Presumably TDLib is creating a remote-tunnel to the desired CDN.

Is it possible to EXPLICITLY point it at a particular CDN? (As opposed to IMPLICITLY pointing it by downloading content from that CDN)?

And if it _does_ IMPLICITLY re-point itself, is it guaranteed to remain aimed at that target until redirected elsewhere by a different-CDN download request?

(Asking because Telethon uses a borrowed exporter which destructs shortly after the download has completed).

**Comment by levlam** [comment]
There is nothing like connection "pointing", TCP connections can be kept opened for all datacenters simultaneously. Download connections are closed only after 5 minutes of inactivity.

**Comment by p-i-** [comment]
Good intel, thanks!
Is there any way to keep them open (even if it's setting a flag and recompiling)?
It feels like bad engineering to do a dummy download once every 4 mins just to keep the connection open...

**Comment by levlam** [comment]
There is no way to keep them open. Unused connections aren't supposed to kept open and if they are used, they don't closed,
