### ISSUE TITLE
Can I get the message on one client and download the photo on another?

### ISSUE THREAD

**Issue by p-i-** [tdlib/td#1687]
My client gets a message, and downloads it:
```
    td_send(
        {
            '@type': 'downloadFile',
            'file_id': photos[1]['photo']['id'],
            'priority': 32,
            'offset': 0,
            'limit': 0,
            'synchronous': True
        }
    )
```

Question is: Is it possible to throw a data packet to a different client (maybe the same user on a different box) and THAT client downloads it?

Looks impossible, as presumably that `file_id` is the index of the image on the database of the session that picked up the message.  And if the message isn't yet on the target-box's session DB, it can't pull out the image access-hash etc.

But I thought I'd ask just in case there is a way...

**Comment by levlam** [comment]
No, this is generally impossible. See documentation of `inputFileRemote`:

> The remote ID is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application
