### ISSUE TITLE
How to create TDLib for Windows Phone 8.1 (WinRT C#)

### ISSUE THREAD

**Issue by jp-weber** [tdlib/td#169]
Is there a way to create a VS extension for Windows Phone 8.1 like TDLib for Universal Windows Platform?

**Comment by levlam** [comment]
Microsoft didn't created Windows Phone 8.1 SDK compatible with Visual Studio 2015, so code for Windows Phone 8.1 must be compiled using compiler from Visual Studio 2013. This compiler don't support C++14, so to compile TDLib for 8.1 the library source code should be first transformed to a form suitable for compilation by the compiler from Visual Studio 2013. It is a hard task, but there should be some automatic converters. For example, there exist commercial C++ -> C converters, but we have never tested them and don't know whether it is a feasible way to compile TDLib for Windows Phone 8.1.

**Comment by jp-weber** [comment]
But what compatibility problem exists with Visual Studio 2015 and the Windows Phone 8.1 SDK? I program hobby moderately with VS2015 WP8.1 apps, because it doesn't work with VS2017 anymore, but I never had problems with VS2015.

**Comment by levlam** [comment]
See, for example, https://stackoverflow.com/questions/31452290/c11-14-features-for-windows-phone-8-1:
"From the Visual Studio 2015 IDE, you can use the Visual C++ 2013 toolset and libraries to build for Windows Phone 8.1. ... You cannot use the Visual C++ 2015 toolset and libraries to build for Windows Phone 8.1."

**Comment by jp-weber** [comment]
Thanks for the example. This is very sadly that only the Visual C++ 2013 toolset works. 

It is also sadly that the official Telegram app for Windows Phone is not released on github. So it is hard to understand how some functions like the secret chat and the cache are implemented.

**Comment by FrayxRulez** [comment]
Telegram for WP just stores messages/users/chats vectors to disk serializing them using TL. 
It also doesn’t support full cache, apart from secret chats:
It just writes to disk the last 20 active dialogs, corresponding peer, last message and last message sender.

**Comment by levlam** [comment]
We have no plans to try to officially support Windows 8.1, especially because the platform ends its life cycle, so I'm closing this issue.
