### ISSUE TITLE
Sometimes we do not receive an authentication code when we are in the AuthorizationStateWaitCode state

### ISSUE THREAD

**Issue by leonidUH** [tdlib/td#1692]
We've had a lot of login issues over the past few weeks.
When we call TdApi.SetAuthenticationPhoneNumber in the AuthorizationStateWaitPhoneNumber and get the AuthorizationStateWaitCode, we don't get the authentication code either to the phone via SMS or in the app.
Sometimes everything works fine for several days in a row, and sometimes it doesn't work all day.
It was tested on AWS and Azure clouds with TdLib version 1.6.0 and 1.7.8, with and without http proxy.
The login result has not changed in any way due to all these changes.
 The logs also look the same and no contain errors - not when we got  authentication code or not.

**Comment by levlam** [comment]
You are limited by the server. Likely, because you are logging in too often.

**Comment by leonidUH** [comment]
Yes, I know that each number can only log in a few times a day and then get  TOO_MANY_REQUESTS 429 error.
But we use a new phone number on each new try, and I repeat that we don't get any errors until we reach to the AuthorizationStateWaitCode. 
We just didn't get the authentication code.

**Comment by p-i-** [comment]
Yesterday I ran fresh tdlib code, which requested an auth-code, which arrived for my TelegramDesktop's user.
As I had logging enabled, the console output was a mess and I quickly did ctrl+c to terminate the program.

Fixed the logging and ran again.
But no new code came.

Turned out I just had to enter the old code I had got from the previous run.
It was 20 minutes stale, but still worked.

Looks like this is no solution to your particular issue, but I figured it's worth mentioning.

**Comment by levlam** [comment]
@leonidUH 
> But we use a new phone number on each new try

This sounds exactly as "you are logging in too often". Automatic logs in are often banned (usually along with the accounts).

**Comment by p-i-** [comment]
This was happening to me with Telegram.
I was logging into a fresh account with a StringSession.
And then boom, Telegram bans the account, and I have to send an email to recover@telegram.org to explain, and they were kind enough to restore it.

But I wonder how Telegram knows if a login is automatic.
Even logging in with my phone app, it's going to be automated by the app source code.
So I'm not sure what is the criterion.

Maybe a StringSession has to fetch some initial state from the servers, as does a fresh TDLib `database_directory`, and this is what trips the switch.
