### ISSUE TITLE
OSError: libtdjson.so.1.7.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by p-i-** [tdlib/td#1693]
I've fixed this; putting up an issue in case it helps others.
Also including a suggestion to add `ldconfig` as a final step to the autogenerated shell instructions at https://tdlib.github.io/td/build.html?language=Python

That link, with these settings:
> Python / Linux / Ubuntu20 / [y]EnableLinkTimeOpt / [n]BuildDebug / [y]InstallTo_usr/local / Clang
... gives the following BASH command sequence:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake clang-10 libc++-dev libc++abi-dev
git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DTD_ENABLE_LTO=ON -DCMAKE_AR=/usr/bin/llvm-ar-10 -DCMAKE_NM=/usr/bin/llvm-nm-10 -DCMAKE_OBJDUMP=/usr/bin/llvm-objdump-10 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-10 ..
cmake --build . --target install
cd ..
cd ..
ls -l /usr/local
```

After executing these commands from the terminal, the following Python code now works:

```
from ctypes.util import find_library
from ctypes import CDLL

tdjson_path = find_library('tdjson') ;  print('Found tdjson lib at:', tdjson_path)
tdjson = CDLL(tdjson_path)
```
..., printing "Found tdjson lib at: libtdjson.so.1.7.8"

However automating the script for deployment onto another (identical) Ubuntu box:
```

function install_tdlib {
    # installs tdlib to /usr/local

    # https://tdlib.github.io/td/build.html?language=Python
    # Python / Linux / Ubuntu20 / [y]EnableLinkTimeOpt / [n]BuildDebug / [y]InstallTo_usr/local / Clang

    commands=$(cat <<-EOF
        set -x ;

        mkdir -p gold/ ;
        cd gold ;

        sudo apt install -y 
            make git zlib1g-dev libssl-dev gperf php-cli 
            cmake clang-10 libc++-dev libc++abi-dev ;

        git clone https://github.com/tdlib/td.git ;
        cd td ;

        rm -rf build ;
        mkdir build ;
        cd build ;

        CXXFLAGS="-stdlib=libc++"
        CC=/usr/bin/clang-10
        CXX=/usr/bin/clang++-10

        cmake 
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX:PATH=/usr/local
            -DTD_ENABLE_LTO=ON
            -DCMAKE_AR=/usr/bin/llvm-ar-10
            -DCMAKE_NM=/usr/bin/llvm-nm-10
            -DCMAKE_OBJDUMP=/usr/bin/llvm-objdump-10
            -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-10
            .. ;

        cmake --build . --target install ;
EOF
    )

    ssh -i $pem  $login  $commands
}
```

... again:

```
tdjson_path = find_library('tdjson') ;  print('Found tdjson lib at:', tdjson_path)
```
... correctly prints "Found tdjson lib at: libtdjson.so.1.7.8"

However:
```
tdjson = CDLL(tdjson_path)
```
... now throws:
```
Traceback (most recent call last):
  File "/root/gold/sync/TDBot/TDWrapper.py", line 13, in <module>
    tdjson = CDLL(tdjson_path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtdjson.so.1.7.8: cannot open shared object file: No such file or directory
```

The difference between the boxes can be observed by:
```
ldconfig -p | grep tdjson
```

On the failbox it is empty whereas on the working box it reports:
```
        libtdjson.so.1.7.8 (libc6,x86-64) => /usr/local/lib/libtdjson.so.1.7.8
        libtdjson.so (libc6,x86-64) => /usr/local/lib/libtdjson.so
```

The solution is to simply run `ldconfig`. Then `ldconfig -p | grep tdjson` will print the correct output and the Python code will execute correctly.

I can't think why this failure occurred, but it wouldn't hurt to add `ldconfig` as a final step in the autogenerated .sh command sequence, just to ensure the newly created library is added to the system cache, and can therefore be found by `CDLL`.

**Comment by levlam** [comment]
@p-i- Thank you for the reminder about the necessity to update shared library cache for some usages. I don't think, that this needs to be included in the build instructions generator, but at least they can now find this issue.

**Comment by p-i-** [comment]
My own priinciiple is that my own products should work out of the  box intuitively. No gotchas.. This makes sure users don't suffer a negativei iinitiial expereiine. I've been in s/w 20 years and it threw me. And there's those rare individuals even more than a chump than I am.
