### ISSUE TITLE
Starting conversation with unknown users and Spam/Flood control

### ISSUE THREAD

**Issue by Beyerheiser** [tdlib/td#1696]
I would like to know if is it right solution for the following case?

I have a constantly growing clients base with phone numbers and it's not known whether these phones are connected with Telegram. I want to initiate a conversation with these clients every day (tens or even hundreds of clients) from my app.
Therefore, first I must find out if the client has a telegram using the API (ImportContact) and if there is, import the contact and send him a message. I've heard about the flood control rules. If I try to import contacts through the API dozens of times a day, is there a chance that I will get a ban? Which solution is more appropriate?

**Comment by levlam** [comment]
You are very likely to be banned with such workflow.

Instead, you need to create a bot (https://core.telegram.org/bots) and ask your clients to write to the bot.
