### ISSUE TITLE
NetFrameWork 4.5.2

### ISSUE THREAD

**Issue by botmastak** [tdlib/td#170]
Can this library be compiled for .Net Framework 4.5.2? Compiled in strict accordance with the instruction, however it is not added to my project

**Comment by levlam** [comment]
Whether our test C# project works for you?

**Comment by botmastak** [comment]
This library is not added to the program that runs on .NET 4.5.2
Can I write you in Russian? :)

**Comment by levlam** [comment]
You can write in Russian to @tdlib_bot.

**Comment by isopen** [comment]
Yes, you can write in other languages.

**Comment by botmastak** [comment]
@isopen у меня нестандартный вопрос. Можете дать свои контакты? Уже неделю воюю с этой либой:)

**Comment by levlam** [comment]
I hope that your problem was resolved. Please reopen the issue if the problem still persists.
