### ISSUE TITLE
how to build cross platform?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#1700]
few days ago I managed to build telegram-bot-api for android because [commented-lifegpc](https://github.com/tdlib/telegram-bot-api/issues/180#issuecomment-926999504)

I tried run command
cmake --build .
andr result failed 

```bash
../td/mtproto/Handshake.cpp:12:10: fatal error: 'td/mtproto/mtproto_api.h' file not found
#include "td/mtproto/mtproto_api.h"
```

how to fix this?

**Comment by azkadev** [comment]
> prepare_cross_compiling

now result eror:(
ninja: error: unknown target 'prepare_cross_compiling'

**Comment by levlam** [comment]
You must build it during a native build, not Android one.
