### ISSUE TITLE
Cannot forward messages to all users.

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/td#1701]
I have a bot with around 20,000 users, and I want to forward a message from a channel to all of my users. However, the message is sent to only a small number of my users although I selected all the users. 
I am aware of the sending message limit that is why I forward a message at a rate of 1 message / 1 second.

I am using the tdlib API.

What might be wrong? Would it be solved If I switch to telegram bot api server?

Please help me...

**Comment by aaalzya** [comment]
> I have a bot with around 20,000 users, and I want to forward a message from a channel to all of my users. However, the message is sent to only a small number of my users although I selected all the users. I am aware of the sending message limit that is why I forward a message at a rate of 1 message / 1 second.
> 
> I am using the tdlib API.
> 
> What might be wrong? Would it be solved If I switch to telegram bot api server?
> 
> Please help me...

773852362
