### ISSUE TITLE
Use generics to define TdApi.Function return type

### ISSUE THREAD

**Issue by cavallium** [tdlib/td#1708]
Since Java is a strongly typed language, using TDLib functions in a project can lead to runtime ClassCast exceptions without any warning in the source code.

TdAPI.Function should specify the return type using generics.

Example:

```java
public abstract static class Function<R extends TdApi.Object> extends TdApi.Object {
  public native String toString();
}

/**
* Returns information about a chat by
* its identifier, this is an offline
* request if the current user is not a bot.
* <p> Returns {@link Chat Chat} </p>
*/
public static class GetChat extends Function<TdApi.Chat> {

}
```

**Comment by levlam** [comment]
I will not have the time to work on this in the foreseeable future, but the corresponding pull requests are likely to be accepted.
