### ISSUE TITLE
Problem building for Windows x64

### ISSUE THREAD

**Issue by smileyjoe8** [tdlib/td#1709]
I get the following failure from cmake:

![imagen](https://user-images.githubusercontent.com/19175525/138268789-12a13c31-ec03-4c63-bfec-64907791574d.png)

Does anybody knows where the TdTargets.cmake file is?

**Comment by levlam** [comment]
You need to specify full path to "/example/java/td/lib/cmake/Td" as Td_DIR instead of the source code root directory.
