### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by hoopan** [tdlib/td#171]
MessageEntity.cpp(816): error C3688: invalid literal suffix '銈汇兗銉'; literal operator or literal operator template 'operator ""銈汇兗銉' not found

**Comment by hoopan** [comment]
Find the solution.

According to the compiler error, you can get rid of the code string and compile it successfully.

**Comment by levlam** [comment]
I can't see these characters on line 816: https://github.com/tdlib/td/blob/cfe4d9bdcee9305632eb228a46a95407d05b5c7a/td/telegram/MessageEntity.cpp#L816.

Of course, you can delete some lines there, but then some URLs will not be properly found inside a message.

Could you try to rollback your change, replace line https://github.com/tdlib/td/blob/cfe4d9bdcee9305632eb228a46a95407d05b5c7a/CMakeLists.txt#L151
with
```
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GR- /W4 /wd4100 /wd4127 /wd4324 /wd4505 /wd4702 /utf-8")
```
and try to recompile?

**Comment by hoopan** [comment]
Sorry, I can't verify because I've changed the operating system

**Comment by greyyoung** [comment]
@levlam hi , I meet the same error and I modify CMakeList.txt add utf-8 mark as you said and it's works fine.
