### ISSUE TITLE
Tag releases again

### ISSUE THREAD

**Issue by SuperSandro2000** [tdlib/td#1718]
If releases are tagged it is way easier for downstream users like Distros to track updates.

**Comment by ildar** [comment]
@levlam , I understand your discourse. But the issue here is a mere tagging of the versions you produce here. If you think it's meaningless then why changing versions at all?
> Even in the latter case, it would be really hard to have two apps using TDLib on the same system simultaneously, because they will need different, conflicting TDLib versions. 

This makes tagging even more important just to find the required version easily.
thanks.

**Comment by levlam** [comment]
> If you think it's meaningless then why changing versions at all?

Versions are changed mostly based on the API they provide.
