### ISSUE TITLE
Can't launch app

### ISSUE THREAD

**Issue by bryanyee33** [tdlib/td#1721]
After the latest 0.24.1.1457, I can no longer launch the app.

The error details are below:

External error
SetTdlibParameters: #400: Can't init files directory "/storage/emulated/0/Android/data/org.thunderdog.challegram/files/": [PosixError : Read-only file system : 30 : Can't create directory "/storage/emulated"]

I'm on android 11, oneplus 6
![Screenshot_20211105-064914200](https://user-images.githubusercontent.com/65088428/140431050-cc92d029-9e3d-4bf7-923c-db35fa7dd0d8.jpg)

**Comment by levlam** [comment]
Did you follow all three steps from the screenshot?

**Comment by bryanyee33** [comment]
> Did you follow all three steps from the screenshot?

yup. 70gb left, no sdcards, all other apps working fine so i'm assuming no storage issues, restarted a few times alr

**Comment by vkryl** [comment]
> > Did you follow all three steps from the screenshot?
> 
> 
> 
> yup. 70gb left, no sdcards, all other apps working fine so i'm assuming no storage issues, restarted a few times alr

Could you please check on 0.24.1.1459? https://t.me/tgx_log/197 If there is still an error, please send a new error message.

**Comment by bryanyee33** [comment]
> > > Did you follow all three steps from the screenshot?
> > 
> > 
> > yup. 70gb left, no sdcards, all other apps working fine so i'm assuming no storage issues, restarted a few times alr
> 
> Could you please check on 0.24.1.1459? https://t.me/tgx_log/197 If there is still an error, please send a new error message.

Still the same error:

External error
SetTdlibParameters: #400: Can't init files directory "/storage/emulated/0/Android/data/org.thunderdog.challegram/files/": [PosixError : No such file or directory : 2 : Can't create directory "/storage/emulated/0/Android/data/org.thunderdog.challegram/files": [PosixError : Read-only file system : 30 : Can't create directory "/storage/emulated"]]

![Screenshot_20211106-065115947](https://user-images.githubusercontent.com/65088428/140586863-f6a1264d-7112-4296-8ab8-8dda1242b4ca.jpg)

**Comment by levlam** [comment]
Could you please check on 0.24.1.1461? Does media download works? If there is still an error, please send a new error message.

**Comment by bryanyee33** [comment]
> Could you please check on 0.24.1.1461? Does media download works? If there is still an error, please send a new error message.

do you mean 0.24.2.1461?

External error
SetTdlibParameters: #400: Can't init files directory "/storage/emulated/0/Android/data/org.thunderdog.challegram/files/": [PosixError : No such file or directory : 2 : Realpath failed for "/storage/emulated/0/Android/data/org.thunderdog.challegram/files/"]

![Screenshot_20211108-085904327](https://user-images.githubusercontent.com/65088428/140669338-ae5b6826-1e47-4a93-a7f7-3bb532b1d5db.jpg)

**Comment by bryanyee33** [comment]
> > Could you please check on 0.24.1.1461? Does media download works? If there is still an error, please send a new error message.
> 
> do you mean 0.24.2.1461?
> 
> External error SetTdlibParameters: #400: Can't init files directory "/storage/emulated/0/Android/data/org.thunderdog.challegram/files/": [PosixError : No such file or directory : 2 : Realpath failed for "/storage/emulated/0/Android/data/org.thunderdog.challegram/files/"]
> 
> ![Screenshot_20211108-085904327](https://user-images.githubusercontent.com/65088428/140669338-ae5b6826-1e47-4a93-a7f7-3bb532b1d5db.jpg)

the folder in /storage/emulated/0/Android/data/org.thunderdog.challegram/files is being created, but the telegram app can't access it
![Screenshot_20211108-090159742](https://user-images.githubusercontent.com/65088428/140669459-802e5e99-a10f-4b91-ab46-f62f221b52e4.jpg)

**Comment by vkryl** [comment]
Could you send a build information about your system? It's clearly bugged.

**Comment by bryanyee33** [comment]
> Could you send a build information about your system? It's clearly bugged.

oneplus 6, syberia os android 11.

but the thing is the app launched fine until i updated to 0.24.1.1457, and no other apps are facing this issue

**Comment by vkryl** [comment]
It's started crashing because the build of Android you use has a bug in scoped storage implementation, which is now enabled in Telegram X after upgrading targetSdkVersion to 30.

**Comment by vkryl** [comment]
> > Could you send a build information about your system? It's clearly bugged.
> 
> 
> 
> oneplus 6, syberia os android 11.
> 
> 
> 
> but the thing is the app launched fine until i updated to 0.24.1.1457, and no other apps are facing this issue

Please send full build details from "about" in your phone settings.

**Comment by bryanyee33** [comment]
![Screenshot_20211108-091140425](https://user-images.githubusercontent.com/65088428/140670013-1f382614-f026-4386-91ef-9068ecf16031.jpg)

**Comment by bryanyee33** [comment]
> It's started crashing because the build of Android you use has a bug in scoped storage implementation, which is now enabled in Telegram X after upgrading targetSdkVersion to 30.

ok my bad, then it was probably because i disabled scoped storage using

su
sm set-isolated-storage off

now, it launches normally after i enabled it again

**Comment by levlam** [comment]
Apps targeting SDK version 30 can't work without scoped storage and only such apps can be updated through Google Play since November. This likely can't be fixed app-side, so the issue can be closed.
