### ISSUE TITLE
Using firebase to subscribe to PUSH notifications

### ISSUE THREAD

**Issue by Onionus007** [tdlib/td#1725]
I am at a complete loss as to how to obtain the token required to subscribe to push notifications using FCM. I have found no information about what the token is and how to obtain it, I am aware that this might not be the best place to ask questions, but I feel like it would be the quickest way to actually get the answer. Could anyone please explain how to get the token?

**Comment by Onionus007** [comment]
Ok, I figured out the token stuff, but now I am facing a problem that even though I am listening to the stream and have sent deviceRegister() to Telegram server, the messages sent directly from FMC come through, but the telegram ones don't.

**Comment by Onionus007** [comment]
Well, I have gotten past that problem as well, but the last problem is that the messages I am receiving from FMC have .data which contains _internalLinkedHashmap with length 0, which doesn't contain any data... any help is much appreciated....

**Comment by levlam** [comment]
If you wouldn't pass `encrypt` == true, then push notifications will be sent without payload. The app is supposed to fetch updates in the usual way then.
