### ISSUE TITLE
Analog searchChatsNearby method in MTProto

### ISSUE THREAD

**Issue by LazarenkoA** [tdlib/td#1726]
there is a searchChatsNearby method in TDLib (https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1search_chats_nearby.html), because TDLib uses the MTProto protocol, there should be an analog in the protocol, but I can't find it in the scheme (https://core.telegram.org/schema/mtproto), how to understand what features of the MTProto scheme the searchChatsNearby method is implemented?

**Comment by RememberTheAir** [comment]
It's [`contacts.getLocated`](https://core.telegram.org/method/contacts.getLocated), which returns both users and groups

**Comment by LazarenkoA** [comment]
thanks
