### ISSUE TITLE
The return parameter of'groupCallParticipant' is wrong.

### ISSUE THREAD

**Issue by StevenMichael3213** [tdlib/td#1727]
The [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) document shows that there are many parameters of **groupCallParticipant**, including `participant_id`, `is_hand_raised`, etc., but when I tested [Telegram React](https://github.com/evgeny-nadymov/telegram-react), I found that the parameters in the groupCallParticipant object obtained were few, as shown in the screenshot(Logs printed out by the web console). There is no` participant_id` and `is_hand_raised`, but `user_id` is included. I don't know if it is the cause of tdlib or Telegram React. When I was running Telegram React, I followed the author's suggestion. First execute `npm ci`, then execute `cp node_modules/tdweb/dist/* public/`, so my tdweb code should be the latest. Do you know the reason? 
![image](https://user-images.githubusercontent.com/31765462/140974670-9c8ac94d-0b4b-4c54-add9-61b7de085416.png)

![image](https://user-images.githubusercontent.com/31765462/140974570-8b419cd8-6772-4690-9576-bccd26eb3693.png)

**Comment by levlam** [comment]
You look at documentation from the latest TDLib version, but use much older `tdweb` 1.7.2. You need TDLib 1.7.2 documentation, which you can obtain from git history.

**Comment by StevenMichael3213** [comment]
Thank you very much for your answer. I read the previous api document, and it turns out that the id_raise_hand field was added after 1.7.2.

It seems that I need to recompile the tdweb library.

Thanks again.

**Comment by levlam** [comment]
Yes. If you want the latest tdweb, you need to rebuild it from the source code.
