### ISSUE TITLE
wasm-ld: error: unknown argument: --exclude-libs

### ISSUE THREAD

**Issue by StevenMichael3213** [tdlib/td#1729]
CMake version is: 3.10.2-lubuntu2.18.04.2
gcc: 7..5.0

![image](https://user-images.githubusercontent.com/31765462/141137636-808e1b76-4c3f-4c02-93ab-11f5827079a2.png)

**Comment by levlam** [comment]
Could you try with emsdk 2.0.6?
Alternatively, you can try to comment the line https://github.com/tdlib/td/blob/33c689aacc78ef5a68973552b968a3bb68cdd7c6/CMake/TdSetUpCompiler.cmake#L64.

**Comment by StevenMichael3213** [comment]
After using the emsdk 2.0.6 version, an error will still be reported. 

Comment out that line of code to package successfully. 

Thanks.
