### ISSUE TITLE
How to correctly destroy objects returned from TdCClientReceive

### ISSUE THREAD

**Issue by Trumeet** [tdlib/td#1730]
Hi, I am using the tdc C interface to build a TDLib application. However, I do not know how to destroy objects returned from `TdCClientReceive`. It returns a `TdResponse`, with a `TdObject` object. However, there are no such thing like `TdDestroyObject` to automatically determine what the type is and free the memory, and I seem to have to detect the type myself and use the corresponding functions like `TdDestroyObjectUpdate` or `TdDestroyObjectOk`, but there are hundreds of types, so having a giant switch case is definitely not an option.

Are there better solutions for that? Thank you.

**Comment by levlam** [comment]
There is
```
void TdDestroyObjectObject (struct TdObject *var);
```
which is autogenerated and is declared in td_tdc_api.h. `TdDestroyObject` also exists, but as an internal function declared in td_tdc_api_inner.h.

**Comment by Trumeet** [comment]
@levlam Thank you. This is pretty helpful.
