### ISSUE TITLE
joinGroupCall api call problem

### ISSUE THREAD

**Issue by StevenMichael3213** [tdlib/td#1734]
I ran into a problem when calling joinGroupCall on the web. How to assign the payload parameter in the call method of joinGroupCall? I do not quite understand. The api document says that the payload can be received from tgcalls but I don't understand tgcalls. Is there any other documentation? Or can you explain the parameters in the payload?

I tried to parse the ufrag, pwd, hash, setup, fingerprint, source from the sdp and create an object {ufrag, pwd, hash, setup, fingerprint, source }.
And converted to a string through JSON.stringify, and finally assigned to the payload, but received a GROUPCALL_SSRC_DUPLICATE_MUCH error

**Comment by levlam** [comment]
There is no documentation besides `tgcalls` source code. The error means that the `payload` has no field `ssrc`. You seem to use the name `source` for the field instead.
