### ISSUE TITLE
TdApi.GetTextEntities usage

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#1737]
Hello, could you please provide more examples or more description on TdApi.GetTextEntities function usage?

Here is few words from documentation:
_Returns all entities (mentions, hashtags, cashtags, bot commands, URLs, and email addresses) contained in the text. This is an offline method. Can be called before authorization. Can be called synchronously._

I see there is one option of usage in examples code:
`new TdApi.GetTextEntities("@telegram /test_command https://telegram.org telegram.me @gif @test")`

But why this request string constructed that way? Maybe there is some more detailed documentation about it? Can I call it any other way(s)?

Thanks!

**Comment by levlam** [comment]
> But why this request string constructed that way?

The parameter isn't constructed in any way. You pass a text, for which you need to get entities.

**Comment by Mike497** [comment]
So, basically any text can be passed there?)

**Comment by levlam** [comment]
Yes.
