### ISSUE TITLE
Is it safe to fork before closing?

### ISSUE THREAD

**Issue by Trumeet** [tdlib/td#1738]
I made a bot daemon using TDLib, and want it to fork into the background after `authorizationStateReady` is received, so the administrator would know whether its login is successful or not. I did some attempts but they ended up in failures. May I do it safely? If so, how? Thank you very much.

**Comment by levlam** [comment]
You can't fork a process while TDLib is run.

**Comment by Trumeet** [comment]
@levlam Ok, that's pretty unfortunate. Thank you anyways.
