### ISSUE TITLE
I can't execute cmake in Ubuntu 20.04

### ISSUE THREAD

**Issue by krassergey** [tdlib/td#1739]
When trying to execute cmake --build . --target install in Ubuntu 20.04, an error message is displayed:

[ 11%] Building CXX object tdutils/CMakeFiles/tdutils.dir/td/utils/BigNum.cpp.o
/home/user/td/tdutils/td/utils/BigNum.cpp:152:16: error: use of undeclared identifier 'BN_check_prime'
  int result = BN_check_prime(impl_->big_num, context.impl_->big_num_context, nullptr);
               ^
1 error generated.
make[2]: *** [tdutils/CMakeFiles/tdutils.dir/build.make:518: tdutils/CMakeFiles/tdutils.dir/td/utils/BigNum.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:757: tdutils/CMakeFiles/tdutils.dir/all] Ошибка 2
make: *** [Makefile:141: all] Ошибка 2

**Comment by krassergey** [comment]
[CMakeCache.txt](https://github.com/tdlib/td/files/7543917/CMakeCache.txt)

**Comment by levlam** [comment]
What is output of `openssl --version`. It seems that you have a pre-release OpenSSL 3.0 installed.

**Comment by krassergey** [comment]
> What is output of `openssl --version`. It seems that you have a pre-release OpenSSL 3.0 installed.

user@123:~/td/build$ openssl version
OpenSSL 3.0.0-dev xx XXX xxxx

**Comment by levlam** [comment]
"OpenSSL 3.0.0-dev" - is a pre-release OpenSSL beta version, which you installed manually. You need to update it to the release 3.0.0 version or replace it with a system-provided package.
