### ISSUE TITLE
Is there a way to obtain chat room messages in positive order through tdlib, or through the message index ID?

### ISSUE THREAD

**Issue by ellermister** [tdlib/td#1745]
Is there a way to obtain chat room messages in positive order through tdlib, or through the message index ID?

For example t.me/PublicTestGroup/1
or

t.me/PublicTestGroup/10000

How to get the message content based on this index ID?

**Comment by levlam** [comment]
You must not try to get all messages in a chat by their identifiers. You can use `getChatHistory` with negative `offset` to receive messages newer than the given.
