### ISSUE TITLE
does tdlib has Two-Step Verification reset password without recovery email?

### ISSUE THREAD

**Issue by rexi1r** [tdlib/td#1747]
Hi, Telegram has a feature that you can reset your two-step verification password even if you don't have access or set your recovery email.
```
If you forget your password, you can only reset it using the recovery email you add during setup. 

However, if you are still logged in and can't access that email, you can request a password reset, which will remove the password after 7 days – but can be canceled from any of your devices.

Go to Settings > Privacy and Security > Two-Step Verification to add or change your password.
```

does the last version of TDLIB has it?

**Comment by levlam** [comment]
Definitely. You can request a password reset using the method `resetPassword`.

**Comment by rexi1r** [comment]
Thanks @levlam , It needs to be called in the logged-in account or I can call this method at login screen?

**Comment by levlam** [comment]
**if you are still logged in ...**

**Comment by moin123-1** [comment]
I can't find reset password option on telegram x on latest version

**Comment by levlam** [comment]
@moin123-1 This is unrelated to TDLib.

**Comment by rexi1r** [comment]
> I can't find reset password option on telegram x on the latest version

Yes, They said that updated to the latest version of TDLib, but I think it's not correct because I can't find the reset password option there, too.

**Comment by levlam** [comment]
@rexi1r Updating to the latest version of TDLib doesn't mean supporting all TDLib abilities.
