### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by KossGuk** [tdlib/td#1748]
OS: Ubuntu 18
TDLib - latest
Building for nodeJS
I built TDlib - success. Were created all files.
Run `make install` - all good
Starting my app and recieved the error segmentation fault on step `new TDLib(libTdPath)` (libTdPath -> /usr/local/lib/libtdjson.so)
`node -p process.versions`:
{
  node: '12.22.7',
  v8: '7.8.279.23-node.56',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '8',
  llhttp: '2.1.4',
  http_parser: '2.9.4',
  openssl: '1.1.1l',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}

OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

**Comment by levlam** [comment]
There should be no issues if both TDLib and OpenSSL are built with the same OpenSSL version 1.1.1. Could you try to find stacktrace of the crash using GDB?

**Comment by KossGuk** [comment]
@levlam Thank you for your reply. Unfortunatelly I'm not familiar with GDB so it will take some time.

**Comment by levlam** [comment]
@KossGuk Do you have any update on the issue?
