### ISSUE TITLE
No callServerTypeTelegramReflector servers

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [tdlib/td#1750]
I'm using tdlib 1.7.0 c++ bindings. I'm accepting call with
```
    callProtocol->udp_p2p_ = true;
    callProtocol->udp_reflector_ = true;
```
    
both `udp_p2p_` and `udp_reflector_` set to true but when handling `callStateReady` i only get `callServerTypeWebrtc` servers. I tried setting `udp_p2p_` to false but result was the same. I don't know what i have to do to get reflector servers. And because of that calls with anyone that isn't in same lan fail.

**Comment by levlam** [comment]
You need to specify valid `library_versions` in `callProtocol` to receive reflectors specific to these versions. Between, `callServerTypeTelegramReflector` are relevant only for very old `libtgvoip` libraries.

**Comment by Michal-Szczepaniak** [comment]
Ah ye my bad i had some issue with connecting to TURN servers, Everything's okay now
