### ISSUE TITLE
Invalid url in sponsored message

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1751]
Sometimes I get weird URL in sponsored message:
```
[ 3][t 4][1638006234.646610975][Td.cpp:3107][#1][!Td][&td_requests]	Receive request 6256: getChatSponsoredMessages {
  chat_id = -1001042239832
}
[ 3][t 4][1638006234.646824836][Td.cpp:4289][#1][!Td][&td_requests]	Sending result for request 6256: sponsoredMessages {
  messages = vector[1] {
    sponsoredMessage {
      id = 26
      sponsor_chat_id = -1001579620324
      link = internalLinkTypeMessage {
        url = "https://t.me//c1579620324/0"
      }
...
```
This URL does not look right to me.

How to open such URLs in the client application?

Thanks

**Comment by levlam** [comment]
Thank you! I pushed fix for the issue, now the url should be always valid.

In this particular case, the `link` will be null, denoting that the chat -1001579620324 needs to be opened. Links of type `internalLinkTypeMessage` are supposed to be handled by a call to `getMessageLinkInfo`.
