### ISSUE TITLE
Sponsored messages: Various questions

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1753]
Hello,

Some questions re sponsored messages:
- according to https://corefork.telegram.org/api/sponsored-messages we need to support sponsored messages fully by Jan 1st. 2022 - However I also found a date talking about Dec 15th - which is the correct one?
- tdlib as per today in v 1.7.0 does not seem to support all functions for sponsored messages, at least I do not find code behind getSponsoredMessages, only the entry in the TL schema file. Is that correct?

BR Florian

**Comment by levlam** [comment]
The official documentation mandates Jan 1st 2022.

Yes, only the latest TDLib from master (1.7.9, currently) supports sponsored messages.

**Comment by maciek134** [comment]
Will there be a 1.8.0 release before the deadline?

**Comment by levlam** [comment]
1.8.0 is likely to be released in 2021, but there is no way to guarantee this. If it will be released in hurry, it could be less stable than the current master version.

**Comment by livelace** [comment]
1.8.0 is good to have. Same worries about sponsored messages.

**Comment by Wunderfitz** [comment]
Are there some test channels around to validate that an updated app works correctly?

**Comment by levlam** [comment]
@Wunderfitz Yes. You can use https://t.me/SecretAdTestChannel for testing.

**Comment by levlam** [comment]
Tagged TDLib 1.8.0 version has been released. API for sponsored message can be found in the Change Log and the documentation.

**Comment by Flohack74** [comment]
@levlam as we are finally implementing this 1 year later :P - so is it expected that when opening a channel, we call `getChatSponsoredMessage `at the end of the message loading, and if its not 404 we add this message to the chat - should this be repeated periodically, or only when entering the chat? 
And if it was read (`viewMessages`), will it 404 so that users do not see it again?

**Comment by levlam** [comment]
If its not 404, you add the message below the last message. You need to call the method only once per chat opening.

It is unspecified, how many times a sponsored message will be shown to the user.

**Comment by Flohack74** [comment]
Thanks and happy new year, all the best for 2023 for you and your team. You are doing amazing work, keep on!
