### ISSUE TITLE
Persistent banning of users that change phone numbers cannot be perma blocked.

### ISSUE THREAD

**Issue by mechanator** [tdlib/td#1756]
I am a QA, coder, and tester for Oxen.io. I administrate the chat for the Oxen Community channel and for service node information.
It's a crypto project. 
Recently there has been a rash of silent users that join, don't say anything and retrieve the list of all members. 
Then they either offer spam/scam invite with another account pretending to be the admin or dev of the project.
The usually do this in direct message mode.
No matter how we pin a message or educate the community users, these hackers persist.
We warn the regular users that Admins do not DM first.

If they are removed from the group, they come back with a different username. 
Sometimes referring to being banned and came right back.  Sometimes using the same automated bot in DM to users to attempt to steal their crypto coins or tokens.
One particular disgruntled user has been evading ban and reports to telegram for the content he has posted in channel.
Either the report and ban feature is broken or they have a way to change phone numbers or credentials that Telegram uses.
This is a security concern since the hacker(s)/trolls might be able to login as an administrator of the group and wreak havoc.

I don't want to know the identity of the offenders, as that would go against the privacy principles of the project.
However, I want to be able to permanently ban the user/hacker/troll using maybe the mac address of the device(that can be changed), the IMEI of the phone(that is really hard to change on phones), or IP range of the ISP they use.

Is there a way to construct such a bot or a process to submit the information to Telegram for banning which is persistent from certain groups.  

I am not asking for a global ban for a user of the whole Telegram network.  Although the administrators of Telegram should have a link on their homepage to report constant abuse and hacker attacks.

**Comment by levlam** [comment]
Users are banned in chats by their unique identifiers. There is no way to ban users in other ways.

Anyway, this is not related to TDLib. You can send general feedback through in-app support.

**Comment by mechanator** [comment]
This is a security and code concern. There's no point in using the product if there are devils breaking the harmony of civil chat all the time.

**Comment by mechanator** [comment]
This is a project engineering failure on both UX and UI. Priority 2
