### ISSUE TITLE
Database encryption key is needed: call checkDatabaseEncryptionKey first"

### ISSUE THREAD

**Issue by ngockhanh14** [tdlib/td#1757]
![image](https://user-images.githubusercontent.com/71579877/144038210-f6fe2032-c1c3-4d77-a628-eccc64d48bd9.png)

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.

**Comment by ngockhanh14** [comment]
i fixed it by
![image](https://user-images.githubusercontent.com/71579877/144041930-ea110e3c-633d-4b1f-ae8e-1569065e3db3.png)

**Comment by RamPanjwani** [comment]
I got this error while working with tdweb. I am using tdweb with react js for a web project.
I am too naive to understand documentation.Also this is my first time working api.
![image](https://github.com/user-attachments/assets/25979ea8-359e-47c7-8cd2-480a2404133b)

**Comment by RamPanjwani** [comment]
inside src folder there is file tdlib.js. it's code -
`import TdClient from 'tdweb';
const options = {
  logVerbosityLevel: 1,
};

const client = new TdClient(options);

export default client;`

then inside Actions folder there is initializeClient.js. it's code -
`import client from "../tdlib";
import packageJson from '../../package.json';

function initializeClient() {
  try {
    console.log("Initializing Client ..");
    client.send({
      '@type': 'setTdlibParameters',
      parameters: {
        '@type': 'tdParameters',
        use_test_dc: false,
        api_id: "api id",
        api_hash: "api hash",
        system_language_code: 'en',
        device_model: 'Unknown',
        system_version: 'Unknown',
        application_version: packageJson.version,
        // use_secret_chats: false,
        // use_message_database: true,
        // use_file_database: false,
        // database_directory: '/db',
        // files_directory: '/'
      }
    });
  } catch (error) {
    console.error("Couldn't initialize client: ", error);
  }
}
export default initializeClient`
then inside app.jsx i am just using useEffect to call the function.
Sorry, if it the problem is naive, i am a beginner.

**Comment by levlam** [comment]
@RamPanjwani See https://core.telegram.org/tdlib/getting-started and documentation for authorization states for your TDLib version.

Also. you seems to use a very old TDLib version and might want to build the latest TDLib version instead as described at https://github.com/tdlib/td/tree/master/example/web.

**Comment by RamPanjwani** [comment]
Thank you for your response. I guess I build tdweb following instructions from the [https://github.com/tdlib/td/tree/master/example/web](url). How can i use that in my project ? Do I need to import TdClient from index.js and make its instance ?
![tdwebfolder](https://github.com/user-attachments/assets/037179f8-e748-4bbd-a44b-6b88e2b8b8b2)

**Comment by levlam** [comment]
The example builds an NPM package, which can be used as any other package.

You can also import index.js, which exports TdClient by default.

**Comment by RamPanjwani** [comment]
Thanks for the help @levlam. I was able to fix the issue 😄.
