### ISSUE TITLE
Error: Building package gperf:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by chenyu1990** [tdlib/td#1762]
`
PS C:\src\td\vcpkg> ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
Computing installation plan...
The following packages will be built and installed:
    gperf[core]:x64-windows -> 3.1#2
    openssl[core]:x64-windows -> 1.1.1l#4
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-11-01
    zlib[core]:x64-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from C:\Users\86198\AppData\Local\vcpkg\archives in 266.5 us. Use --debug to see more details.
Starting package 1/5: gperf:x64-windows
Building package gperf[core]:x64-windows...
-- Using cached gperf-3.1.tar.gz.
-- Cleaning sources at C:/src/td/vcpkg/buildtrees/gperf/src/gperf-3-d4135ad4b1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/td/vcpkg/downloads/gperf-3.1.tar.gz
-- Using source at C:/src/td/vcpkg/buildtrees/gperf/src/gperf-3-d4135ad4b1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/src/td/vcpkg/buildtrees/gperf/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\td\vcpkg\buildtrees\gperf\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/gperf/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package gperf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gperf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gperf]+Build+error
including:
  package: gperf[core]:x64-windows -> 3.1#2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 163065a35 2021-12-02 (4 hours ago)

Additionally, attach any relevant sections from the log files above.
`

cmake 3.22.0
windows 10
gperf 3.1 https://mirrors.gigenet.com/OSDN//sfnet/e/ez/ezwinports/gperf-3.1-w32-bin.zip

**Comment by levlam** [comment]
You seems to have `ninja` in your PATH, but it doesn't work as expected.

**Comment by levlam** [comment]
Also, ensure that you have English language pack installed for Visual Studio, which is required by `vcpkg`.

**Comment by levlam** [comment]
The exact error can be found in the log C:\src\td\vcpkg\buildtrees\gperf\config-x64-windows-out.log.

**Comment by chenyu1990** [comment]
VS version problem.
