### ISSUE TITLE
Gif load limit

### ISSUE THREAD

**Issue by SupinePandora43** [tdlib/td#1763]
# Official clients results

## Telegram X

Limit is around 200 (I'm bad at counting)

## Telegram

Limit is smaller in comparison with Telegram X, probably around 100.

# Steps to reproduce

1. Save a lot of gifs (>200 for X and maybe >100 for normal version).
2. Notice that not all gifs show up in client.
3. Delete some of gifs.
4. Missing Gifs appear again.

# What's the issue?

Not all saved gifs are shown.

**Comment by levlam** [comment]
What's the issue?

**Comment by SupinePandora43** [comment]
> What's the issue? You have just described expected behavior of the clients.

Not all saved gifs are shown

**Comment by levlam** [comment]
This is expected behavior of Telegram Android client. And it is absolutley unrelated to TDLib.

**Comment by SupinePandora43** [comment]
> This is expected behavior of Telegram Android client. And it is absolutley unrelated to TDLib.

**expected**?

P.S. telegram x doesn't have github repo, telegram repository have disabled issues.

**Comment by levlam** [comment]
Yes. The app is written to show at most 100 last saved GIFs.

**Comment by SupinePandora43** [comment]
> Yes. The app is written to show at most 100 last saved GIFs.

I would like it to be bigger or not exist at all (same goes for favourite stickers)

**Comment by levlam** [comment]
This is still not related to TDLib. You can send general suggestions through in-app support or at https://bugs.telegram.org.

**Comment by 0823969789** [comment]
#
Duplicate of #

**Comment by 0823969789** [comment]
> `
Duplicate of #`

**Comment by SupinePandora43** [comment]
https://bugs.telegram.org/c/4120
