### ISSUE TITLE
Option to ignore background updates for bots

### ISSUE THREAD

**Issue by pylakey** [tdlib/td#1764]
Is there a way to ignore updates sent when Bot was offline?

**Comment by levlam** [comment]
See description of the option "ignore_background_updates": https://core.telegram.org/tdlib/options. This is the only possible solution.

**Comment by pylakey** [comment]
Thanks. That is what I was looking for

**Comment by pylakey** [comment]
Are options beginning with 'x' or 'X' shared between two independent tdlib instances?

**Comment by levlam** [comment]
No, options can't be shared between different instances.

**Comment by pylakey** [comment]
@levlam, what is the best moment for setting options? Is it ok to do it before call to `setTdlibParameters`?

**Comment by levlam** [comment]
@pylakey Yes, it is ok. Options can be set any time and some even must be set before `setTdlibParameters`.
