### ISSUE TITLE
importContacts result in popularContact

### ISSUE THREAD

**Issue by farhad-rad** [tdlib/td#1765]
when I call [contacts.importContacts](https://core.telegram.org/method/contacts.importContacts) method, some of data get added. The rest of them will not be added. I repeated the method for those remaining data. I figured out there is something called ```popular_invites``` of type [Vector of PopularContact](https://core.telegram.org/type/PopularContact) inside the [contacts.importedContacts](https://core.telegram.org/constructor/contacts.importedContacts) (Actual Result of the Method); and my data is there :(
I don't know how to really save those ```PopularContact```s into my contact list. The further problem is that I can not get the ```access_hash``` of those contacts so that I can send messages. HOW IS THAT POSSIBLE??? 
I have the phone number and there is no way to send message! Can anyone please help?

**Comment by levlam** [comment]
This is not related to TDLib . The mentioned methods are from Telegram API, not TDLib.

**Comment by farhad-rad** [comment]
@levlam I used tdlib library for .Net to call those methods I mentioned.

**Comment by levlam** [comment]
The library is not TDLib, so this is not related to the repository.
