### ISSUE TITLE
Clone of telegram x crashing

### ISSUE THREAD

**Issue by moin123-1** [tdlib/td#1766]
I have made clones of telegram x  3-4 months before yesterday I update telegram x and when I update clone of telegram x and start it crashing what the error I can't understand

**Comment by levlam** [comment]
Share error details.

**Comment by moin123-1** [comment]
![Screenshot_2021-12-04-12-29-51-06](https://user-images.githubusercontent.com/81621252/144700886-8812f42f-b0c7-4acf-9088-fcd686483fa4.jpg)
This coming after updating clone telegram x

**Comment by levlam** [comment]
This doesn't look like an error related to the app.
