### ISSUE TITLE
Error during tdlib build (C1061: compiler limit on cli.cpp)

### ISSUE THREAD

**Issue by floralbxhh** [tdlib/td#1769]
Hello guys,
I wanted to report a build time error that happened to me. The error was caused by cli.cpp file, currently on line 2546, because conditional blocks are exceeding the compiler limit. I am currently doing the build on Windows. Below is the image I get during build.
Thank you have a nice weekend.

![cli cpp](https://user-images.githubusercontent.com/51860703/144728000-0bf7ca07-da01-4534-9954-46ce54f9f091.png)

**Comment by levlam** [comment]
This has already been fixed in master.
