### ISSUE TITLE
[tdlib_json] no response to loadChats and flood limit

### ISSUE THREAD

**Issue by v-atamanenko** [tdlib/td#1770]
Hello! I'm having an issue.
In a C client using tdlib_json, written pretty much adhering to the recommended Java example, I've encountered a strange problem that doesn't seem to be covered here before.

First of all, the client starts normally, goes through authorization, receives automatically requested by tdlib updates normally. No errors, etc.

But then, to populate the main chat list, as per the mentioned Java example, I send loadChats request like this:
```
{"@type":"loadChats", "limit": 10, "@extra":"chats_loadMainList"}
```

After that, I receive a number of updateUser, updateSupergroup, updateNewChat, etc. But at some point there is no more updates, 5-10 seconds of nothing, and then:

```
[ 2][t 4][1638671959.992311954][NetQueryDelayer.cpp:83][#1][!NetQueryDelayer]	Delay: [Query:[id:10223616][tl:0x08736a09][state:Query]] [timeout:3.000000][total_timeout:3.000000] because of [Error : 420 : FLOOD_WAIT_3] from Session:2:main::Connect::Tcp::[149.154.167.50:443] to DcId{2} from [192.168.1.14:41970]
[ 2][t 4][1638671959.992473602][NetQueryDelayer.cpp:83][#1][!NetQueryDelayer]	Delay: [Query:[id:10289152][tl:0xaeb00b34][state:Query]] [timeout:3.000000][total_timeout:3.000000] because of [Error : 420 : FLOOD_WAIT_3] from Session:2:main::Connect::Tcp::[149.154.167.50:443] to DcId{2} from [192.168.1.14:41970]
[ 2][t 4][1638671991.224948406][NetQueryDelayer.cpp:83][#1][!NetQueryDelayer]	Delay: [Query:[id:13369344][tl:0xaeb00b34][state:Query]] [timeout:3.000000][total_timeout:3.000000] because of [Error : 420 : FLOOD_WAIT_3] from Session:2:main::Connect::Tcp::[149.154.167.50:443] to DcId{2} from [192.168.1.14:41970]
[ 2][t 4][1638671993.311224222][NetQueryDelayer.cpp:83][#1][!NetQueryDelayer]	Delay: [Query:[id:13500416][tl:0x08736a09][state:Query]] [timeout:3.000000][total_timeout:3.000000] because of [Error : 420 : FLOOD_WAIT_3] from Session:2:main::Connect::Tcp::[149.154.167.50:443] to DcId{2} from [192.168.1.14:41970]
```

No expected `@type:ok` response, whether with `@extra:...` or not. Also, why the flood_wait? I'm positive that no requests are sent explicitly after loadChats.

What could be wrong?
Latest tdlib, ubuntu 20.04.

**Comment by levlam** [comment]
It is hard to tell the cause without full TDLib logs. Could you set log verbosity level to 4, set log stream to `logStreamFile` of size 100000000 and send the log to @tdlib_bot in Telegram?

**Comment by v-atamanenko** [comment]
I've sent the log to @tdlib_bot. Looking through the log myself, I see that `@extra` field somehow gets lost between my call to td_send and the actual processing of request.

The code sending request:
```
char req[128];
sprintf(req, "{\"@type\":\"loadChats\", \"limit\": %i, \"@extra\":\"chats_loadMainList\"}", limit);
td_send(client_id, req);
```

printf(req):
```
{"@type":"loadChats", "limit": 10, "@extra":"chats_loadMainList"}
```

log:
```
[ 3][t 4][1638806787.711705207][Td.cpp:3071][#1][!Td][&td_requests]     Receive request 4: loadChats {
  chat_list = null
  limit = 10
}
```

**Comment by levlam** [comment]
In base interface requests and responses are matched by request_id. The @extra field exists only in JSON interface, which stores it and adds back when the resulting object is returned.

Requests leading to FLOOD_WAIT_3 are sent by TDLib and are needed to get missing information about chats. They are sent to the server, because local database is disabled.

**Comment by levlam** [comment]
Binlog stores only essential data. These additional requests are needed to get blocking state, theme, TTL setting of chats and some other important data. These requests are rate-limited to one request per 2 seconds on the TDLib side, so they shouldn't affect performance.

**Comment by v-atamanenko** [comment]
The issue is resolved. The behavior described here was caused by premature `break`ing of the main loop (with `td_receive`).
