### ISSUE TITLE
Receive hint_unread_count = 0, but found 1 unread messages in chat

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#1772]
I'm using `libtdjson.so`  version 1.7.9 in `Ubuntu` 20.04. I got following error:

`[ 1][t16][1638705592.259085178][MessagesManager.cpp:11394][#44][!Td]    Receive hint_unread_count = 0, but found 1 unread messages in chat -1001715303932`

Is this a bug? I did not receive such error in version 1.2 or 1.7.0 of `tdlib`

**Comment by levlam** [comment]
This is not an issue. Server returned that there are no unread messages in the chat, but TDLib known that there is one. Server is wrong, but TDLib fixed its mistake. Just ignore the warning.

**Comment by aghasi** [comment]
I didn't see this error before, but i see that after upgrading my `tdlib` to 1.7.9

**Comment by levlam** [comment]
The warning existed in TDLib 1.7.0. It didn't exist in TDLib 1.2.
