### ISSUE TITLE
1.7.9: sendChatSetTtlMessage unknown

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1773]
Hi,
after update to 1.7.9 we get:

![grafik](https://user-images.githubusercontent.com/16186470/144747462-4ceec5d3-cf07-4a83-af55-4cc44ff35417.png)

Is this intentional, was the call changed? Thanks!

**Comment by levlam** [comment]
Yes. The method was replaced with `setChatMessageTtlSetting` and works for all chat types.
