### ISSUE TITLE
error /usr/bin/ld: cannot find -ltdjson_static

### ISSUE THREAD

**Issue by miketsukuba** [tdlib/td#1774]
Dear All,

I'm trying to use td in ubuntu 18 64x, go 1.17,
When I try to build a go program:
go build prog_name.go
I receive:
/usr/bin/ld: cannot find -ltdjson_static
/usr/bin/ld: cannot find -ltdjson_private
/usr/bin/ld: cannot find -ltdclient
/usr/bin/ld: cannot find -ltdcore
/usr/bin/ld: cannot find -ltdapi
/usr/bin/ld: cannot find -ltdactor
/usr/bin/ld: cannot find -ltddb
/usr/bin/ld: cannot find -ltdsqlite
/usr/bin/ld: cannot find -ltdnet
/usr/bin/ld: cannot find -ltdutils
/usr/bin/ld: cannot find -lc++

I think td was installed correctly, but can not find these libraries, I would be thankful to help me with thsi.

Cheers

**Comment by miketsukuba** [comment]
I tried to copy the libtd* files from td/tdlib/lib/ to /user/local/lib 
and after only error of /usr/bin/ld: cannot find -lc++ remained

I tried to improve it by installing libc++-dev and the asked for libc++Abi (/usr/bin/ld: cannot find -lc++Abi) I tried to install libc++Abi as well, and now there is big error.
Maybe I'm not doing the right way with libc++.

cheers

**Comment by levlam** [comment]
It seems that you built TDLib against libstdc++ instead of libc++, so you need to link with `-lstdc++` instead of `-lc++`.

**Comment by miketsukuba** [comment]
Thanks, I checked again, copied libstdc++.a, libstdc++.so from
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so
to:
/usr/local/include/

but still the error regarding -lc++ remained.

Cheers

**Comment by levlam** [comment]
You shouldn't need with libc++ at all. You built TDLib against libstdc++ and need to link with libstdc++ instead.

**Comment by miketsukuba** [comment]
Thanks, for building, I used:

sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake g++
git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target install
cd ..
cd ..
ls -l td/tdlib

Maybe the problem of asking for libc++ is due to the way I built,
Should I change the building to:

cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .

Cheers

**Comment by levlam** [comment]
There are no problems in TDLib building. You build everything correctly. The problem in the go wrapper which tries to link with libc++, but must link with libstdc++ when TDLib is built this way. Search wrapper's code to fins metions of "lc++" and replace them with "lstdc++".

**Comment by miketsukuba** [comment]
Thanks for your help and the message declaring the situation.
I searched for the lc++, seems in the previous version, the developer was using lstdc++ and in the new version it uses lc++.
I try to copy the old version in the pkg/mod/github.com folder, but it again try to download form github.
the package is https://github.com/Arman92/go-tdlib/issues.

Attached please find the old and new versions of tdlib.go
[tdlib_old.go.txt](https://github.com/tdlib/td/files/7666127/tdlib_old.go.txt)
[tdlib.go_new.txt](https://github.com/tdlib/td/files/7666130/tdlib.go_new.txt)
o

**Comment by levlam** [comment]
You need to edit source code of the module and replace "lc++" with "llibc++", which was actually used. Or rebuild TDLib with clang and libc++.

**Comment by miketsukuba** [comment]
Thanks for your help.
I tried to use the previous td which was built against lstdc++,
Now it compiles almost successfully, but I receive the error of gcc as:

# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.

(go version is 1.13, amd64, gcc version is 7.5.0,
I used following as well and the same error exits:
export CXXFLAGS="-stdlib=libstdc++"
CC=/usr/bin/gcc CXX=/usr/bin/g++)

Thanks.
Cheers

**Comment by levlam** [comment]
> collect2: fatal error: ld terminated with signal 9 [Killed]

The error means that you are out of RAM.

**Comment by miketsukuba** [comment]
Many thanks for your helps.
I will try with more RAM, I think the problem will be resolved.
