### ISSUE TITLE
Failed to sync binlog

### ISSUE THREAD

**Issue by farhad-rad** [tdlib/td#1775]
Running some methods of TdSharp results in below error which is actually related to tdlib
Here is the info in the debug console after calling ```TdLib.TdClient.CheckDatabaseEncryptionKeyAsync```:
```
[Client.cpp:278][&td_requests]   Begin to wait for updates with timeout 0.100000
[Td.cpp:3072][#1][!Td][&td_requests]     Receive request 3: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}
[Binlog.cpp:419][#1][!Td][&status.is_error()]    Failed to sync binlog: [WindowsError : Insufficient system resources exist to complete the requested service. : 1450 : Sync failed]
(process 5840) application exited with code -1073740791.
```
The method calls a method of ```tdjson``` with the same name. Then error occurs.
I'm using ```Tdlib v1.7.9``` and ```TdLib.Native 1.7.9``` which are .net bindings for ```tdlib```. I'm using these on x64 windows 11 Pro. The project is built over .Net 5 for web (Actual target OS is windows server 2019)
I double checked system resources. There was only 15% CPU usage and almost 3 Gb of RAM.
I also disabled anti-virus (i found out it might be the cause) with no luck!
It there something im missing?

**Comment by levlam** [comment]
This is an error, returned by FlushFileBuffers. It should mean that file system resources are exhausted. Could you check nonpaged kernel memory as described in https://docs.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/backup-program-unsuccessful-large-system-volume#symptoms?

**Comment by farhad-rad** [comment]
@levlam 
Kernel paged memory 749 Mb
nonpages 760 Mb
values change since ```PagedPoolSize``` registry is equal to zero. I've tried solutions described in the page you mentioned. No luck!
is there any way to cancel the whole backup thing. i dont need to store anything but session.

**Comment by levlam** [comment]
This is unrelated to backups. It fails exactly when session data is flushed to disk.

**Comment by levlam** [comment]
I expect that some other program extensively writes to disk.
