### ISSUE TITLE
binlog failed to rename on WSL2

### ISSUE THREAD

**Issue by DerAlSem** [tdlib/td#1776]
Built tdlib for python on WSL2 (Ubuntu 20.04.3):

```
[ 0][t 1][1638739435.433779001][Binlog.cpp:676][#1][!Binlog /mnt/d/Dev/tdlib/db/td.binlog]      Failed to rename binlog of size 44800 to /mnt/d/Dev/tdlib/db/td.binlog: [PosixError : No such file or directory : 2 : Stat for file "/mnt/d/Dev/tdlib/db/td.binlog" failed]. Old file size is 0
Exception ignored on calling ctypes callback function: <function on_log_message_callback at 0x7f8730ddec10>
Traceback (most recent call last):
  File "/mnt/d/Dev/tdlib/modules/tdjson.py", line 37, in on_log_message_callback
    sys.exit('TDLib fatal error: %r' % message)
SystemExit: TDLib fatal error: b'[ 0][t 1][1638739435.433779001][Binlog.cpp:676][#1][!Binlog /mnt/d/Dev/tdlib/db/td.binlog]\tFailed to rename binlog of size 44800 to /mnt/d/Dev/tdlib/db/td.binlog: [PosixError : No such file or directory : 2 : Stat for file "/mnt/d/Dev/tdlib/db/td.binlog" failed]. Old file size is 0\n'
```

Exactly the same script on Ubuntu 20.04 on VDS runs flawlessly.

So it's more WSL2-related issue, rather than tdlib itself, still i hope it could be fixed.

**Comment by levlam** [comment]
Could you try to move the working directory to /home instead of /mnt?

**Comment by DerAlSem** [comment]
> Could you try to move the working directory to /home instead of /mnt?

Can't reproduce the issue after moving to /home.

99% sure it's not related to tdlib, rather than to WSL itself.

**Comment by levlam** [comment]
@DerAlSem I added a possible workaround for the issue. Could you update TDLib to the latest version, move back to /mnt and check whether the crash still happens?

**Comment by DerAlSem** [comment]
1.7.10

```
[ 0][t 1][1639258351.047240018][Binlog.cpp:681][#1][!Binlog /mnt/d/Dev/py-tg/db/td.binlog]  Failed to rename binlog of size 27288 to /mnt/d/Dev/py-tg/db/td.binlog: [PosixError : No such file or directory : 2 : Stat for file "/mnt/d/Dev/py-tg/db/td.binlog" failed]. Temp file size is 0, new size 0
Exception ignored on calling ctypes callback function: <function on_log_message_callback at 0x7fb0746d9e50>
Traceback (most recent call last):
  File "/mnt/d/Dev/py-tg/modules/tdjson.py", line 37, in on_log_message_callback
    sys.exit('TDLib fatal error: %r' % message)
SystemExit: TDLib fatal error: b'[ 0][t 1][1639258351.047240018][Binlog.cpp:681][#1][!Binlog /mnt/d/Dev/py-tg/db/td.binlog]\tFailed to rename binlog of size 27288 to /mnt/d/Dev/py-tg/db/td.binlog: [PosixError : No such file or directory : 2 : Stat for file "/mnt/d/Dev/py-tg/db/td.binlog" failed]. Temp file size is 0, new size 0\n'
Aborted

```

**Comment by denistsyplakov** [comment]
Just got the same issue with WSL 
2023-07-21 00:10:24,979 ERROR [Thread-1698610] it.tdlight.TDLight                      : [ 0][t 1][1689883824.979019403][Binlog.cpp:689][#1][!Binlog /mnt/c/_work/__rnd/press-center/tg.press/session/data/td.binlog]   Failed to rename binlog of size 5515496 to /mnt/c/_work/__rnd/press-center/tg.press/session/data/td.binlog: [PosixError : No such file or directory : 2 : Stat for file "/mnt/c/_work/__rnd/press-center/tg.press/session/data/td.binlog" failed]. Temp file size is 0, new size 0

**Comment by levlam** [comment]
@denistsyplakov 
This is likely to be a bug in the `drvfs` file system, mounted to "/mnt/c" in WSL. The error shows that the "td.binlog" file disappeared after a call to `rename` function and can't be found neither by the old, or the new name. The only known workaround is to avoid usage of the `drvfs` filesystem and use any other path as TDLib working directory.
