### ISSUE TITLE
is tdweb deprecated or

### ISSUE THREAD

**Issue by rahimi7k** [tdlib/td#1778]
TdWeb last update was v1.7.2 for 9 month ago and with Telegram new update it is broken now. 
Why Telegram did not release the update before closing the previous versions, it is very unprofessional!
Does tdweb deprecated and not support? If not when exactly new update will release?

**Comment by levlam** [comment]
It isn't deprecated. You just need to build it yourself as described in https://github.com/tdlib/td/tree/master/example/web.

**Comment by rahimi7k** [comment]
Thank You very much for answer, but in description it says Update version to 1.7.0. and it is for 12 moth ago!
it isn't old source code?

**Comment by levlam** [comment]
`tdweb` is a wrapper for TDLib. It can have no commits for years, but still remain compatible with the up-to-date TDLib version.

**Comment by fantasthu** [comment]
> 

have u resolved the problem of tbweb ID problem? thank you

**Comment by levlam** [comment]
tdweb 1.7.10 was publiched on npm.
