### ISSUE TITLE
Block behind the screen

### ISSUE THREAD

**Issue by isopen** [tdlib/td#178]
If you leave it as it is now, then it's uncomfortable to search on your mobile phone.
https://drive.google.com/file/d/1zyG39ghdsWvu8-8jJajke__MIygsTIUq/view?usp=drivesdk

**Comment by isopen** [comment]
Leo you have the documentation collected on one canvas in pdf?

**Comment by levlam** [comment]
You can read https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.

**Comment by isopen** [comment]
Super mega thing. Thanks Leo

**Comment by isopen** [comment]
Do you mind if I borrow this mega thing in my repository?
