### ISSUE TITLE
[build] bench_db.cpp fails build of the entire project

### ISSUE THREAD

**Issue by andrew-phi** [tdlib/td#1782]
Problem
Build fails

Command
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DTD_ENABLE_LTO=ON ..
cmake --build . --target install
```

Output
```Scanning dependencies of target bench_db
[ 42%] Building CXX object benchmark/CMakeFiles/bench_db.dir/bench_db.cpp.o
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so: undefined reference to `pthread_create'
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so: undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so: undefined reference to `pthread_detach'
collect2: error: ld returned 1 exit status
tddb/CMakeFiles/binlog_dump.dir/build.make:100: recipe for target 'tddb/binlog_dump' failed
```
Tools:
cmake version 3.9.1
gcc 7.2.0
libc6 Version: 2.26-0ubuntu2.1

Probable cause:
Unknown. Don't include benchmarks in production builds!
Also, size of  433M  libtdcore.a is ridiculously large!!

**Comment by levlam** [comment]
Your toolchain has problems with LTO. Try to build without it.

> Unknown. Don't include benchmarks in production builds!

This is nonsense. You will have the same link error for all binaries.

> Also, size of 433M libtdcore.a is ridiculously large!!

This is completely irrelevant. Report this to compiler developers.

**Comment by andrew-phi** [comment]
>> This is nonsense. You will have the same link error for all binaries.
Really? I've built all other subprojects successfully, otherwise I wouldn't be able to list library size.

**Comment by levlam** [comment]
Could you send output of the command `rm tg_cli && make VERBOSE=1` launched from the build directory?

**Comment by andrew-phi** [comment]
Unfortunately, not anytime soon, sorry. It's hard to steal an hour from that production machine. ( I'll try.

**Comment by levlam** [comment]
This command should run really fast in the directory in which TDLib has already been built.

**Comment by jlove456** [comment]
i think i may have cause a failed build
what should i do
