### ISSUE TITLE
1.7.9: pinned chats not being sent as pinned

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1785]
I have the following pinned chat in Desktop client:
![grafik](https://user-images.githubusercontent.com/16186470/145111249-ba1bc1eb-a891-4f8b-a2e0-af0569a52458.png)

However, on tdlib 1.7.9 this chat is reported as:
`Title: "No Band Name" Order: 7039080068156986014 Pinned: false`

The chat is not in any chat list, and our code anyways only processes chatListMain positions currently. So, order is okay, but pinned boolean not. What could this be? Did we miss anything here?

**Comment by Flohack74** [comment]
For the 2 pinned chats that are working I get:
```
Title: "Nina Testor" Order: 9221294784512000002 Pinned: true
Title: "Gruppe für 3 Leute" Order: 9221294784512000001 Pinned: true
```
So there is definitely a huge difference in the ID was well when a chat is pinned.

**Comment by levlam** [comment]
Could you archive and unarchive the chat?

**Comment by Flohack74** [comment]
Yes suddenly it appeared after unarchiving:
![grafik](https://user-images.githubusercontent.com/16186470/145199093-3469402f-3e9c-422e-8f29-2d281f0e06cf.png)

**Comment by Flohack74** [comment]
It also survived a restart. I will keep monitoring it...

**Comment by levlam** [comment]
TDLib missed update about pinning of the chat. Archiving/unarchiving allowed to synchronize the chat's pinned state.

**Comment by Flohack74** [comment]
@levlam ok I see but the thing is, this was a 1.6.0 database before, and there the pinning was okay, so maybe this was messed up during migration?

**Comment by Flohack74** [comment]
Ok we will relay this to our community, I hope it does not affect many ;)
