### ISSUE TITLE
Issue when parsing long user identifiers. So users with long identifier 64-bit integer can't work with the bot.

### ISSUE THREAD

**Issue by saidgadjiev** [tdlib/td#1786]
[ 4][t 1][1638944335.698203086][HttpReader.cpp:625][#1171565679][!Connect:3840] Parse JSON parameters: "{"timestamp":"2021-12-08T06:18:55.696+0000","status":400,"error":"Bad Request","message":"JSON parse error: Numeric value (5012338965) out of range of int (-2147483648 - 2147483647); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Numeric value (5012338965) out of range of int (-2147483648 - 2147483647)\n at [Source: (PushbackInputStream); line: 2, column: 46] (through reference chain: org.telegram.telegrambots.meta.api.objects.Update["message"]->org.telegram.telegrambots.meta.api.objects.Message["from"]->org.telegram.telegrambots.meta.api.objects.User["id"])","path":"/callback"}"

**Comment by levlam** [comment]
This is response of your server to a webhook request by Bot API. The exception happened in your code, so the code needs to be fixed. There are no issues in TDLib or Bot API.

**Comment by saidgadjiev** [comment]
Understand. Thanks.
