### ISSUE TITLE
PEER_ID_NOT_SUPPORTED error when searching for call messages in a private chat

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1788]
If I search for Call or MissedCall in a private chat, I get the `PEER_ID_NOT_SUPPORTED` error, here is logs
```
[ 3][t 2][1638980563.946912765][Td.cpp:3055][#1][!Td][&td_requests]	Receive request 1187: searchChatMessages {
  chat_id = 56973539
  query = ""
  sender_id = null
  from_message_id = 217745195008
  offset = -1
  limit = 30
  filter = searchMessagesFilterMissedCall {
  }
  message_thread_id = 0
}
...
...
[ 3][t 2][1638980564.023834943][Td.cpp:4256][#1][!Td][&td_requests]	Sending error for request 1187: error { code = 400 message = "PEER_ID_NOT_SUPPORTED" }
```

Some time ago I definitely remember this functionality was working well.

Thanks

**Comment by levlam** [comment]
This error was returned in the last 4 years at least. Filters `searchMessagesFilterCall` and `searchMessagesFilterMissedCall` seems to be completely useless and can be safely removed.
