### ISSUE TITLE
Sponsored Messages is always required starting 2022?

### ISSUE THREAD

**Issue by dariocode** [tdlib/td#1794]
The info about "Sponsored Messages" says:
<<If their app allows its users to access content from Telegram channels, third-party developers using the Telegam API are required to support and properly display official sponsored messages in their apps by January 1, 2022. Unfortunately, Telegram cannot financially sustain third-party apps that do not display sponsored messages and they will have to be disconnected.>>

If my app does not allow to access to Telegram Channels, I have to support the Sponsored Messages? I would like develop an app to chat only by "secret chat" betwewn specific users. Should I implement some API regarding Sponsored Messages for this scope?

**Comment by levlam** [comment]
No.
