### ISSUE TITLE
Logout will destory all the data but proxy settings?

### ISSUE THREAD

**Issue by Livins1** [tdlib/td#1795]
after i ran the logout function, 
GetProxies just return empty list.
is this right? 
if so, when i dev a new app,  should I hold the proxy settings data on file?

**Comment by levlam** [comment]
`logOut` destroys all data, including proxy settings. If you want to synchronize them between accounts, you need to store the list of proxies yourself.

**Comment by Livins1** [comment]
Okay, thanks.
