### ISSUE TITLE
tdlib "forwardmessages" doesn't show forward source

### ISSUE THREAD

**Issue by wozhendeaa** [tdlib/td#1796]
Like the title says, I use the forwardMessages function to resend it to other places but it shows the messages as if my account sent it, it doesn't contain any information about the original sender. I have checked the privacy settings responsible for whom can forward my messages but I don't think that's what this is about. 
how do I forward the messages and it will look like how it behaves like when I'm using the app

**Comment by levlam** [comment]
The method `forwardMessages`  keeps reference to the original sender unless you explicitly ask it to only copy the message content by specifying `send_copy == true`.

Could you `setLogVerbosityLevel` to 4, `setLogStream` to `logStreamFile("tdlib_log.txt", 100000000, false)`, reproduce the issue and send the log to https://t.me/tdlib_bot?

**Comment by wozhendeaa** [comment]
thanks so much for your reply. Looks like that's the issue. I checked very hard but somehow I missed that argument. I was losing my mind.

**Comment by jnxyatmjx** [comment]
> logStreamFile
Could you please show me the example of how to use **setLogStream** with TDlib python API?
by the way, is there any way to find the TDlib **response types for special functions**( e.g function forwardMessages response type for TDlib python api)

**Comment by levlam** [comment]
@jnxyatmjx
All requests can be used according to the schema https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl for your TDLib version. You can find description of how to serialize objects to JSON at https://github.com/tdlib/td/blob/master/td/telegram/td_json_client.h.
Each method can return only value of the specified in the scheme type, or an object of the type `error`.

**Comment by jnxyatmjx** [comment]
> `setLogStream`
My code like bellow:
`# setting TDLib log verbosity level to 2 (errors)
        res_ = td_execute({'@type': 'setLogVerbosityLevel', 'new_verbosity_level': 2, '@extra': 1.00001})
        logger.info(f"{threading.get_native_id()} --> {str(res_).encode('utf-8')}")

        log_str_ = td_execute({'@type': 'logStreamFile', 'path': './tdlib_log.txt', 'max_file_size': 26214400, 'redirect_stderr': False, '@extra': 1.00002})
        td_execute({'@type': 'setLogStream', 'log_stream': log_str_, '@extra': 1.00003})`

**Comment by levlam** [comment]
The calls look correct, but using a library from https://github.com/tdlib/td/tree/master/example#python may simplify interaction with TDLib.

**Comment by jnxyatmjx** [comment]
> The calls look correct, but using a library from https://github.com/tdlib/td/tree/master/example#python may simplify interaction with TDLib.

got the error 
{\'@type\': \'error\', \'code\': 400, \'message\': \'Failed to parse JSON object as TDLib request: Unknown class "logStreamFile"\', \'@extra\': 1.00002}'
when call 
```python
log_str_ = td_execute({'@type': 'logStreamFile', 'path': 'tdlib_log.txt', 'max_file_size': 26214400, 'redirect_stderr': False, '@extra': 1.00002})
```

**Comment by jnxyatmjx** [comment]
> > The calls look correct, but using a library from https://github.com/tdlib/td/tree/master/example#python may simplify interaction with TDLib.
> 
> got the error use **libtdjson.so.1.8.22** {'@type': 'error', 'code': 400, 'message': 'Failed to parse JSON object as TDLib request: Unknown class "logStreamFile"', '@extra': 1.00002}' when call
> 
> ```python
> log_str_ = td_execute({'@type': 'logStreamFile', 'path': 'tdlib_log.txt', 'max_file_size': 26214400, 'redirect_stderr': False, '@extra': 1.00002})
> ```

below is correct
```python
td_execute({'@type': 'setLogStream', 'log_stream': {'@type': 'logStreamFile', 'path': 'tdlib_log.txt', 'max_file_size': 26214400, 'redirect_stderr': False}, '@extra': 1.00002}) 
```

**Comment by jnxyatmjx** [comment]
is there any way to reset  **api_id** and **api_hash** ?

**Comment by levlam** [comment]
@jnxyatmjx No.

**Comment by jnxyatmjx** [comment]
> @jnxyatmjx No.

bad news but precisely
