### ISSUE TITLE
[Error : 400 : Chat not found] flaky issue

### ISSUE THREAD

**Issue by davydof** [tdlib/td#1798]
`[!GetChatRequest] Receive error for query: [Error : 400 : Chat not found]`

```ts
import { Airgram, Auth, prompt } from 'airgram';

const airgram = new Airgram({
  apiId: 667788,
  apiHash: 'hgfhgfhh',
  logVerbosityLevel: 4,
  useChatInfoDatabase: false,
});

airgram.use(
  new Auth({
    code: () => prompt(`Please enter the secret code:\n`),
    password: () => prompt(`Please enter the password:\n`),
    phoneNumber: '786878',
  }),
);

airgram.api.setLogStream({
  logStream: {
    _: 'logStreamFile',
    path: './log.txt',
    maxFileSize: 100000000,
  },
});

await airgram.api.getChat({
  chatId: -7658,
});
```

```
[ 3][t 4][164000.77437][Td.cpp:3072][#1][!Td][&td_requests]	Receive request 7: getChat {
  chat_id = -7658
}
[ 3][t 4][164000.77404][RequestActor.h:112][#1][!GetChatRequest]	Receive error for query: [Error : 400 : Chat not found]
[ 3][t 4][164400.7743][Td.cpp:4266][#1][!Td][&td_requests]	Sending error for request 7: error { code = 400 message = "Chat not found" }
[ 4][t 4][1600.7714][Td.cpp:3568][#1][!Td]	Decrease request actor count to 1
```

hi, for the same chat id sometimes I can get chat data and sometimes - can't

after I try to set `useChatInfoDatabase` to `false`, it helps for some chats but I can't get chat data sometimes, it looks flaky

how I can understand the reason and fix it?

thank you

**Comment by levlam** [comment]
Chats are saved to the database and can be received using `getChat` after restart, only if message database is enabled.

This is nevertheless an unreliable way to get chats after restart, because chats can be deleted if the database is broken, or during database optimization.

**Comment by davydof** [comment]
I enable it and at the first time I get all chat get successfully but next time some getChat requests are failed
why they are not stable at all? how I can them stable?

**Comment by davydof** [comment]
My final goal is to forward messages from one chat to another
And what is interesting: if I post some message manually(by mac desktop telegram app) - the messages are forwarding correctly but not every time, it's flaky :/

Without that posted message I have
`Sending error for request 8: error { code = 400 message = "Chat to forward messages to not found" }`
But the channel exists

How I can fix it? What the checks I should do?

**Comment by levlam** [comment]
You need to get the chat from TDLib after restart before you can use its ID. It is wrong to use hardcoded identifiers, so you need to receive the chat by calling a TDLib method.

**Comment by davydof** [comment]
> to get the chat from TDLib after restart
to receive the chat by calling a TDLib method

Could you please provide the example?

**Comment by levlam** [comment]
> Could you please provide the example?

No. There are a lot of ways to receive chats from TDLib and any of them can be appropriate for your case.

> So I think it's ok to have hardcoded chat ids

It's still not ok, because it's not enough to use just IDs to do anything with the chats and your script can break any time. To get chats from your chat list you can use `loadChats`/`searchChatsOnServer`. For example, add all the chats to a filter and load the corresponding chat list.
