### ISSUE TITLE
when i TdApi.SetAuthenticationPhoneNumber, tip me this error

### ISSUE THREAD

**Issue by lichegn** [tdlib/td#1803]
[ 3][t 0][1640592231.262546777][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 5][1640592231.264299392][MessagesManager.cpp:12992][#1][!MessagesManager]	Receive ttl_db query result [new expires_till:-1][got messages:0]
[ 3][t 5][1640592231.264306306][MessagesManager.cpp:12949][#1][!MessagesManager]	Begin ttl_db loop: [expires_from:1640592246][expires_till:-1][has_query:false]
[ 3][t 5][1640592231.264308214][MessagesManager.cpp:12958][#1][!MessagesManager]	Finish ttl_db loop
[ 2][t 3][1640592231.517184495][Session.cpp:1335][#1][!Session:1:main::HandshakeActor]	Failed to open connection: [WindowsError : 远程主机强迫关闭了一个现有的连接。 : 10054 : Error on [fd:0000000000000A60] : [149.154.175.50:443] to DcId{1} from [0.0.0.0:52643]]
[ 2][t 5][1640592231.517450332][Session.cpp:1267][#1][!Session:1:main]	Handshake is not yet ready
[ 3][t 5][1640592231.517468929][Session.cpp:1305][#1][!Session:1:main]	Create GenAuthKeyActor 0
[ 3][t 5][1640592231.517495393][ConnectionCreator.cpp:634][#1][!ConnectionCreator][&connections]	Request connection for [client:0xc61f110ac50dc335] to DcId{1} [allow_media_only:false]
[ 3][t 5][1640592231.517505884][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592231.517518043][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 0.614280
[ 3][t 5][1640592232.139786481][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592232.139842987][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592232.139879465][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592232.139902353][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [149.154.175.50:80] to DcId{1}
[ 3][t 5][1640592232.140199184][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [149.154.175.50:80] to DcId{1} from [0.0.0.0:52644]
[ 3][t 5][1640592232.140217542][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 2.991580
[ 3][t 5][1640592232.140259981][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [149.154.175.50:80] to DcId{1} from [0.0.0.0:52644] without auth data
[ 3][t 5][1640592232.140287637][RawConnection.cpp:88][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [0.0.0.0:52644]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 000000f0 be7e8ef1 40e54a13 ce3ca327 c180a95d 1f765679 0bf53648 8d97669b 20b97a5b 63ef302c b803c1b7 1fc26dc6
76112814 e06cf0a2 0d60df76 8e194177 5a0c4215 e5e04f1a 5448589e 714e2183 b60383d7 400a1bfe 7184ed45 e99b0ce9 0e01eae9 69e515dd f7a7e894 f78cc483
eeed2e5d 2b667e9a 15a8714b 30cbfec9 cd58f5c2 cb59852a 0e2c807a d5f2766b ff46c584 2d4afc76 0947b51e 1931cd7e 18bd081d 8678f4ec 0054b930 b368b4a7
f1d18211 b853aa92 561f3d12 c54fbae1 999d3aa0 61f0cf09 df6a17fd 3f8c4aee 82395d58 45d15aad 659e159b fa93dd44 fc54099f 34990ca6 8c0ea725 16303f90
42ac2da9
[ 4][t 5][1640592232.140301704][BufferedFd.h:207][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [0.0.0.0:52644]>]	Flush write: +328B[left:0B]
[ 3][t 5][1640592232.260391950][StateManager.cpp:130][#1][!State manager]	Auto set net_type = Other
[ 3][t 5][1640592232.260410785][ConnectionCreator.cpp:547][#1][!ConnectionCreator][&connections]	Receive network flag true with generation 1
[ 3][t 5][1640592232.260415077][ConnectionCreator.cpp:552][#1][!ConnectionCreator][&connections]	Set proxy query token to 0: 1 1
[ 3][t 5][1640592232.260418891][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592232.260429143][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592232.260446310][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [149.154.175.50:5222] to DcId{1}
[ 3][t 5][1640592232.260656595][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [149.154.175.50:5222] to DcId{1} from [0.0.0.0:52645]
[ 3][t 5][1640592232.260676145][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 0.871121
[ 3][t 5][1640592232.260710239][ConfigManager.cpp:773][#1][!Recoverer][&config_recoverer]	Failed to connect for 1.002851
[ 3][t 5][1640592232.260715723][ConfigManager.cpp:847][#1][!Recoverer][&config_recoverer]	Wakeup in 3997.1ms
[ 3][t 5][1640592232.260761499][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [149.154.175.50:5222] to DcId{1} from [0.0.0.0:52645] without auth data
[ 3][t 5][1640592232.260777473][RawConnection.cpp:88][#1][!PingActor<[149.154.175.50:5222] to DcId{1} from [0.0.0.0:52645]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 000000a0 be7e8ef1 e4e85587 496d84e0 60b83ac9 781e56f2 d69d581a c484cc24 46d31c5e b69eb625 caa96adb 8ec7809e
5fccf188 1cec18e7 fa834020 e880661d cb754da9 7aeb629c 98d7b7ea 122446b0 0b2aa215 d200ef4c 0c9858cc 8e8d26b2 b896e2bd c87c9812 9148feb7 80807410
79319b78 170082a0 9743acb5 e87013ce c2299f09 6e0490a6 359e8a20 b9035bff a6068b06 51debd24 b4cfb6b8 7638a1ef e82948a6
[ 4][t 5][1640592232.260795593][BufferedFd.h:207][#1][!PingActor<[149.154.175.50:5222] to DcId{1} from [0.0.0.0:52645]>]	Flush write: +248B[left:0B]
[ 3][t 5][1640592232.358684539][ConnectionCreator.cpp:983][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [0.0.0.0:52644]>][&connections]	Failed connection (checked) [WindowsError : 远程主机强迫关闭了一个现有的连接。 : 10054 : Failed to read from connection] [149.154.175.50:80] to DcId{1} from [0.0.0.0:52644]
[ 3][t 5][1640592232.358767509][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592232.358778953][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 0.773019
[ 3][t 5][1640592232.505817413][ConnectionCreator.cpp:983][#1][!PingActor<[149.154.175.50:5222] to DcId{1} from [0.0.0.0:52645]>][&connections]	Failed connection (checked) [WindowsError : 远程主机强迫关闭了一个现有的连接。 : 10054 : Error on [fd:0000000000000A70]] [149.154.175.50:5222] to DcId{1} from [0.0.0.0:52645]
[ 3][t 5][1640592232.505853891][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592232.505857467][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 0.625940
[ 3][t 5][1640592233.134357690][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592233.134378433][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592233.134393930][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592233.134423255][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [[2001:b28:f23d:f001::a]:443] to DcId{1}
[ 3][t 5][1640592233.134648084][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52646]
[ 3][t 5][1640592233.134672403][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 2.997125
[ 3][t 5][1640592233.134751558][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52646] without auth data
[ 3][t 5][1640592233.134789228][RawConnection.cpp:88][#1][!PingActor<[[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52646]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 000000d0 be7e8ef1 b191d3ce 0f00fa90 a274d199 e685c7c1 29b2fe71 c11dcece 52606f6e 0dd8821b 2fd837ce e31148d2
2bf447b6 11d64036 60974e1e 15e93709 d90b1834 4609e5af 869ce864 18724099 cdadd123 6674747b 4032ff9b e72aff99 08c5dc37 4bd53ea7 26898c10 b8f0d509
196683c0 bdef6617 725cce0a d932bde6 a3024ccf 8fc3ed78 f29bb6ab c29b01c5 2d901d35 489d450e f6386230 15e55bb1 3b8265a1 b24783a6 f1828844 508ecb8a
b32a1387 79725479 bd4a75be 0406533c 14833912 074c7a80 b985b086 3e10f653 2bc536bb
[ 3][t 5][1640592233.134814262][ConnectionCreator.cpp:983][#1][!PingActor<[[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52646]>][&connections]	Failed connection (checked) [WindowsError : 向一个无法连接的网络尝试了一个套接字操作。 : 10051 : Error on [fd:0000000000000A74]] [[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52646]
[ 3][t 5][1640592233.134845972][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592233.134849786][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 2.996948
[ 3][t 5][1640592236.145224571][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592236.145275592][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592236.145304679][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592236.145353794][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [[2001:b28:f23d:f001::a]:80] to DcId{1}
[ 3][t 5][1640592236.145639419][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [[2001:b28:f23d:f001::a]:80] to DcId{1} from [[::]:52647]
[ 3][t 5][1640592236.145654678][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 3.986143
[ 3][t 5][1640592236.145699262][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [[2001:b28:f23d:f001::a]:80] to DcId{1} from [[::]:52647] without auth data
[ 3][t 5][1640592236.145709753][RawConnection.cpp:88][#1][!PingActor<[[2001:b28:f23d:f001::a]:80] to DcId{1} from [[::]:52647]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 000000d0 be7e8ef1 8fd1dbc7 a1e31eb2 19cb3ccd f8bbd21d 6d3a5d46 f83ca36d 2ce5185f 3c2701a9 99582db7 9c4c3347
ad10f18d a5fbce89 e4912bda f28e5747 1de575aa d41a020f f273c13a 8ce83ce7 de63eaa6 bc8afd2f 4fbca777 7f5f8144 b1f787f4 36fd605f 8468f2cd 6ca48005
785c276a 583e6677 342c07cb 37a45368 81f5bbec 6e90a68c f070b452 c13f5542 4e4e4879 d48588c6 c98c5322 5bb29d71 621c3ac7 6d5d5b5a 155bda1f 7cf95f40
1933223b d0b11609 07372e55 5e865fc8 5a1dffb6 32f7e503 76c87c65 1a9a5d1e 8334891d
[ 3][t 5][1640592236.145725250][ConnectionCreator.cpp:983][#1][!PingActor<[[2001:b28:f23d:f001::a]:80] to DcId{1} from [[::]:52647]>][&connections]	Failed connection (checked) [WindowsError : 向一个无法连接的网络尝试了一个套接字操作。 : 10051 : Error on [fd:0000000000000A74]] [[2001:b28:f23d:f001::a]:80] to DcId{1} from [[::]:52647]
[ 3][t 5][1640592236.145746231][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592236.145748138][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 3.986050
[ 3][t 5][1640592236.271572589][ConfigManager.cpp:773][#1][!Recoverer][&config_recoverer]	Failed to connect for 5.013707
[ 3][t 5][1640592236.271646022][ConfigManager.cpp:802][#1][!Recoverer][&config_recoverer]	Ask simple config with turn 0
[ 3][t 5][1640592236.271676063][ConfigManager.cpp:214][#1][!Recoverer][&config_recoverer]	Request simple config from https://dns.google/resolve?name=apv3.stel.com&type=TXT
[ 3][t 5][1640592236.271693229][ConfigManager.cpp:850][#1][!Recoverer][&config_recoverer]	Wakeup never
[ 4][t 2][1640592236.272877216][SslStream.cpp:191][#1][!Wget]	Begin to load system store
[ 4][t 2][1640592236.308978080][SslStream.cpp:224][#1][!Wget]	End to load system store
[ 4][t 2][1640592236.309051513][SslStream.cpp:324][#1][!Wget]	Set verification host to dns.google
[ 4][t 2][1640592236.309059381][SslStream.cpp:337][#1][!Wget]	Set SNI host name to dns.google
[ 4][t 2][1640592236.309231519][SslStream.cpp:455][#1][!Connect]	SSL_WANT_READ
[ 4][t 2][1640592236.309239387][SslStream.cpp:455][#1][!Connect]	SSL_WANT_READ
[ 4][t 2][1640592236.309241771][HttpConnectionBase.cpp:152][#1][!Connect]	Can write to the connection
[ 4][t 2][1640592236.309243917][BufferedFd.h:207][#1][!Connect]	Flush write: +312B[left:0B]
[ 4][t 2][1640592236.309247732][SslStream.cpp:455][#1][!Connect]	SSL_WANT_READ
[ 4][t 2][1640592236.309249162][HttpConnectionBase.cpp:152][#1][!Connect]	Can write to the connection
[ 4][t 2][1640592236.309255838][SslStream.cpp:455][#1][!Connect]	SSL_WANT_READ
[ 4][t 2][1640592236.309257268][HttpConnectionBase.cpp:152][#1][!Connect]	Can write to the connection
[ 3][t 5][1640592240.137808322][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592240.137850284][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592240.137876510][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592240.137918710][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [[2001:b28:f23d:f001::a]:5222] to DcId{1}
[ 3][t 5][1640592240.138275623][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [[2001:b28:f23d:f001::a]:5222] to DcId{1} from [[::]:52654]
[ 3][t 5][1640592240.138320922][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 7.993477
[ 3][t 5][1640592240.138399839][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [[2001:b28:f23d:f001::a]:5222] to DcId{1} from [[::]:52654] without auth data
[ 3][t 5][1640592240.138422489][RawConnection.cpp:88][#1][!PingActor<[[2001:b28:f23d:f001::a]:5222] to DcId{1} from [[::]:52654]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 00000020 be7e8ef1 17565133 2d6ad766 0d2a61ad 3c32e093 91ab7e07 4e400586 71d8fbd7
[ 3][t 5][1640592240.138470172][ConnectionCreator.cpp:983][#1][!PingActor<[[2001:b28:f23d:f001::a]:5222] to DcId{1} from [[::]:52654]>][&connections]	Failed connection (checked) [WindowsError : 向一个无法连接的网络尝试了一个套接字操作。 : 10051 : Error on [fd:0000000000000ABC]] [[2001:b28:f23d:f001::a]:5222] to DcId{1} from [[::]:52654]
[ 3][t 5][1640592240.138508796][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592240.138517618][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 7.993280
[ 3][t 5][1640592246.275190114][ConfigManager.cpp:676][#1][!Recoverer][&config_recoverer]	Get SimpleConfig error [Error : 0 : Response timeout expired]
[ 3][t 5][1640592246.275210142][ConfigManager.cpp:773][#1][!Recoverer][&config_recoverer]	Failed to connect for 15.017350
[ 3][t 5][1640592246.275231122][ConfigManager.cpp:847][#1][!Recoverer][&config_recoverer]	Wakeup in 305.0s
[ 3][t 5][1640592248.132371902][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592248.132393121][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592248.132408142][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592248.132429361][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [149.154.175.50:443] to DcId{1}
[ 3][t 5][1640592248.132689476][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [149.154.175.50:443] to DcId{1} from [0.0.0.0:52655]
[ 3][t 5][1640592248.132715463][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.999082
[ 3][t 5][1640592248.132761240][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [149.154.175.50:443] to DcId{1} from [0.0.0.0:52655] without auth data
[ 3][t 5][1640592248.132786273][RawConnection.cpp:88][#1][!PingActor<[149.154.175.50:443] to DcId{1} from [0.0.0.0:52655]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 000000d0 be7e8ef1 c276254f 3a9299f1 a7b6952c 1f362daa 9b4b1afb 9db0137a 73ca4e3c a4152318 13e025e2 ed57828a
ab95978b 3a1f0a43 6f243a6a 4214e950 0a447df9 7bb4dff3 71592814 5803cfcb 70c05694 72e6ac89 e4677838 4d92eb15 ffd3f144 7c699d14 ffe274a2 b85c57c1
b959a95c 22b8147b bb5e9f0d c3bcbf1b f503b940 c70607ce dd4cbd8c b1f05433 f83d6173 d31839f5 8b089b98 1f64df03 f061a72d f80c57b1 d6f594c4 a8ae0137
9e11e603 54a5d529 eb4edf94 23d210ad c110b973 8aeb426b f586984f eac2baba df57132d
[ 4][t 5][1640592248.132801294][BufferedFd.h:207][#1][!PingActor<[149.154.175.50:443] to DcId{1} from [0.0.0.0:52655]>]	Flush write: +296B[left:0B]
[ 3][t 5][1640592248.384631395][ConnectionCreator.cpp:983][#1][!PingActor<[149.154.175.50:443] to DcId{1} from [0.0.0.0:52655]>][&connections]	Failed connection (checked) [WindowsError : 远程主机强迫关闭了一个现有的连接。 : 10054 : Error on [fd:0000000000000AB4]] [149.154.175.50:443] to DcId{1} from [0.0.0.0:52655]
[ 3][t 5][1640592248.384651660][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592248.384654998][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.747143
[ 3][t 5][1640592264.133131027][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592264.133151769][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592264.133162498][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592264.133181095][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [149.154.175.50:80] to DcId{1}
[ 3][t 5][1640592264.133414745][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [149.154.175.50:80] to DcId{1} from [0.0.0.0:52663]
[ 3][t 5][1640592264.133438348][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.998359
[ 3][t 5][1640592264.133501529][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [149.154.175.50:80] to DcId{1} from [0.0.0.0:52663] without auth data
[ 3][t 5][1640592264.133529663][RawConnection.cpp:88][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [0.0.0.0:52663]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 00000110 be7e8ef1 7f4991e0 261354d5 e7a5e031 c103e0bb 98e40116 e3b8ee1f 38b02c8e b4df5d6b c8a07b58 ae970d51
24e3572d 6d1ec03f 4d3bf741 dfe498f1 135fb542 1843ad91 4a11e9f9 85e40654 32686cc4 72ebea0c 839012ea 7ff31ce4 d15865b4 8a6dba15 ffda6e18 a213441c
dd2b152b 33fac79b d26f8201 ad7e9b12 ce2795e4 f4cf0eff 7be27c79 ab17d9ac c95f34d9 57d012d4 64a345c9 38b9b966 37ab49d8 755d1672 a858125b de4a3d66
a10ab60c 321f0e26 36b4a14f b04b1e9c 23883c7f e666500e 78a3a438 9acee9d7 c0e76592 449d6429 38d4bdcc e65fddd1 c7267208 b832fd22 243dcd1b f88b2145
076e5c21 36c811c9 844c6f7a a6ed2e3e cb58a248 7663e812 c99aeac7 f6bee48e 549986ff
[ 4][t 5][1640592264.133547782][BufferedFd.h:207][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [0.0.0.0:52663]>]	Flush write: +360B[left:0B]
[ 3][t 5][1640592264.364235639][ConnectionCreator.cpp:983][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [0.0.0.0:52663]>][&connections]	Failed connection (checked) [WindowsError : 远程主机强迫关闭了一个现有的连接。 : 10054 : Error on [fd:0000000000000A88]] [149.154.175.50:80] to DcId{1} from [0.0.0.0:52663]
[ 3][t 5][1640592264.364254474][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592264.364257812][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.767540
[ 3][t 5][1640592280.138956546][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592280.139000654][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592280.139031887][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592280.139077425][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [149.154.175.50:5222] to DcId{1}
[ 3][t 5][1640592280.139579772][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [149.154.175.50:5222] to DcId{1} from [0.0.0.0:52670]
[ 3][t 5][1640592280.139636039][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.992162
[ 3][t 5][1640592280.139729499][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [149.154.175.50:5222] to DcId{1} from [0.0.0.0:52670] without auth data
[ 3][t 5][1640592280.139759778][RawConnection.cpp:88][#1][!PingActor<[149.154.175.50:5222] to DcId{1} from [0.0.0.0:52670]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 000000b0 be7e8ef1 1ec52dd2 f29de345 ed065a64 b68ac0bc 5d8ec9c8 d5c5cb3b b42cacc1 6f05d8b4 34f50819 d0bd9e53
afc41b85 f4c3fc5e 88895a09 70d990e3 c449e8b4 2bd35eaf 79ef5d3a 56a229d8 c123ee23 375b1c95 ca84c131 e61ccd13 4d5bba70 9fd57b82 ffcb5b3f 4286b5bb
4ffdfc79 9a1e55cc 3fec04d7 78463755 524c2e23 5f8b286c 36809766 0c318f6d 5a0432f9 3bfb4518 33dec28f 8a0f0830 80f9917b 344ab1f8 cd1c5272 1b05d9a2
370c0f48
[ 4][t 5][1640592280.139790296][BufferedFd.h:207][#1][!PingActor<[149.154.175.50:5222] to DcId{1} from [0.0.0.0:52670]>]	Flush write: +264B[left:0B]
[ 3][t 5][1640592280.393078327][ConnectionCreator.cpp:983][#1][!PingActor<[149.154.175.50:5222] to DcId{1} from [0.0.0.0:52670]>][&connections]	Failed connection (checked) [WindowsError : 远程主机强迫关闭了一个现有的连接。 : 10054 : Failed to read from connection] [149.154.175.50:5222] to DcId{1} from [0.0.0.0:52670]
[ 3][t 5][1640592280.393114566][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592280.393133401][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.738664
[ 3][t 5][1640592296.136826276][ConnectionCreator.cpp:1049][#1][!ConnectionCreator][&connections]	[hash:0xc61f110ac50dc335] wakeup
[ 3][t 5][1640592296.136850833][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 4][t 5][1640592296.136866569][DcOptionsSet.cpp:56][#1][!ConnectionCreator]	Find all connections in DcId{1}. use_static = false, prefer_ipv6 = false, only_http = false
[ 3][t 5][1640592296.136890172][ConnectionCreator.cpp:735][#1][!ConnectionCreator][&connections]	Create: [[2001:b28:f23d:f001::a]:443] to DcId{1}
[ 3][t 5][1640592296.137007474][ConnectionCreator.cpp:815][#1][!ConnectionCreator][&connections]	Create new direct connection [[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52675]
[ 3][t 5][1640592296.137023687][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.994774
[ 3][t 5][1640592296.137055635][ConnectionCreator.cpp:1004][#1][!ConnectionCreator][&connections]	Start check: [[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52675] without auth data
[ 3][t 5][1640592296.137064695][RawConnection.cpp:88][#1][!PingActor<[[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52675]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 00000050 be7e8ef1 8d8b0255 20d9c2de edb6c397 a4803fd8 2b42cbb3 e1828204 dde79cdf 85e0991b 484ef6c4 65f2619a
9540081f 12cb75a6 bbf11dad b42ac863 d05f39ec 1245025d dff053e0 f964306c fcc490ab
[ 3][t 5][1640592296.137074232][ConnectionCreator.cpp:983][#1][!PingActor<[[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52675]>][&connections]	Failed connection (checked) [WindowsError : 向一个无法连接的网络尝试了一个套接字操作。 : 10051 : Error on [fd:0000000000000650]] [[2001:b28:f23d:f001::a]:443] to DcId{1} from [[::]:52675]
[ 3][t 5][1640592296.137085914][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xc61f110ac50dc335]
[ 3][t 5][1640592296.137087106][ConnectionCreator.cpp:1018][#1][!ConnectionCreator][&connections]	[client:0xc61f110ac50dc335] set timeout in 15.994710

**Comment by levlam** [comment]
Telegram is blocked in your area.
