### ISSUE TITLE
Enhancement for the build instruction generator

### ISSUE THREAD

**Issue by stephan-ansems** [tdlib/td#1804]
I use automation when generating the instructions for the build for java on several linux distros and use it as a script in a ci/cd pipeline. However i found that i had to manually add the `#/bin/bash` to the start and the `-y` flag to the `apt-get` instructions after generating. These could easily be added to the generator. 

So the first few lines of instructions would change from this:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake default-jdk clang-10 libc++-dev libc++abi-dev
```

to this:
```
#/bin/bash
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake default-jdk clang-10 libc++-dev libc++abi-dev```

This would save me and probably others a bit of frustration.

**Comment by levlam** [comment]
> #/bin/bash

There are a lot of other shell applications except bash. Also, the instuctions are supposed to be run mostly as is without pasting them to a shell script file.

Adding `-y` flag can simplify the build instructions usage, but `sudo` still requires password for the most users. Moreover, these commands are potentially dangerous and can break user environment, so by default they ask for user confirmation. Adding `-y` is good for CI/CD, but it is not advisable for general users.

So, I would keep build instructions as is and those who need to use them from CI/CD can apply the proposed changes themself.
