### ISSUE TITLE
Sometimes when starting the program about 20 message (including old messages will post)

### ISSUE THREAD

**Issue by miketsukuba** [tdlib/td#1805]
Dear All,

I have a program that reads some messages form another channel and post it accordingly to other channel for some certain times.
Sometimes when the code restarts, it post bulk of previous messages as well which is not desired.
(normal posting is 1 message if there is updates from original channel)
In case could it it be due tdlib?

Cheers

**Comment by levlam** [comment]
Usually, you receive all messages missed while the instance wasn't active. If there were a lot of missed messages, you will receive a lot of `updateNewMessage` updates soon after start.

**Comment by miketsukuba** [comment]
Thanks @levlam and sorry for being late.
Exactly the same.
In case is there any method or trick to avoid this issue?
For example controlling the bot that writes to the destination channel?

Cheers

**Comment by levlam** [comment]
What do you mean by "exactly the same"?

**Comment by miketsukuba** [comment]
Thanks, I mean, I have experience as you described. As before starting lots of updates remained, about 20 messages will print each time that I run the code.

**Comment by levlam** [comment]
You can skip all updates about messages, which were sent before instance launch, by examining their send `date`.

**Comment by miketsukuba** [comment]
Many thanks @levlam, I will try.
