### ISSUE TITLE
what is this error

### ISSUE THREAD

**Issue by lichegn** [tdlib/td#1807]
![image](https://user-images.githubusercontent.com/21340057/147521845-89efb4d7-44fe-4417-b290-4f578654e548.png)

**Comment by levlam** [comment]
You must create your own API ID and API hash at https://my.telegram.org to avoid this error.

**Comment by lichegn** [comment]
> 

![image](https://user-images.githubusercontent.com/21340057/147523624-4a004f43-4533-402e-bf3e-2b6e1ea01644.png)
tip me this error

**Comment by levlam** [comment]
Is my.telegram.org available without VPN?

**Comment by lichegn** [comment]
i use VPN

**Comment by levlam** [comment]
And this is the cause of the error.

**Comment by dekeyel** [comment]
Try to use another browser, in my case chrome didnt work, but safari worked

**Comment by lichegn** [comment]
resolved
