### ISSUE TITLE
[ 1][t 0][1640699632.541493654][tl_jni_object.cpp:39]	Can't find field [id] with signature [I]

### ISSUE THREAD

**Issue by shrey-183** [tdlib/td#1808]
Hi,
I am working on a project in Java with Spring where we are using tdlib. While running the application we encountered the following error:
```[ 1][t 0][1640699632.541493654][tl_jni_object.cpp:39]	Can't find field [id] with signature [I]``` 

We are not sure what this means, perhaps someone could explain what this means?

Thank you for your time!

**Comment by levlam** [comment]
You are using TdApi.java and `tdjni` library from different TDLib versions.
