### ISSUE TITLE
Problems while encoding russian symbols

### ISSUE THREAD

**Issue by Yiour** [tdlib/td#181]
I have built a c++ example for tdlib and tried out to get chats, messages, etc. and there are problems with encoding russian. For example I get this string  ╨в╨╡╤Б╤В for "Привет". Please tell how to deal with it

**Comment by levlam** [comment]
It's a problem with encoding of characters in your console. You should set encoding to UTF-8.

**Comment by MedvedevIgor** [comment]
I use example\csharp. How to fix the problem?
![1](https://user-images.githubusercontent.com/32822474/38472379-c9a4191c-3b87-11e8-97b1-ce148ef68aa1.png)

**Comment by isopen** [comment]
Текст должен быть закодирован в UTF-8

**Comment by MedvedevIgor** [comment]
String Class - Represents text as a sequence of **UTF-16** code units. https://msdn.microsoft.com/en-us/library/system.string(v=vs.110).aspx

**Comment by isopen** [comment]
https://github.com/isopen/tdlib/blob/master/U%2B1910Preston.cs

**Comment by MedvedevIgor** [comment]
I use Telegram.Td.dll https://github.com/tdlib/td/tree/master/example/csharp

**Comment by isopen** [comment]
You can improve the sample and load it for testing.

**Comment by MedvedevIgor** [comment]
Проект доступен по ссылке https://github.com/tdlib/td/tree/master/example/csharp, что еще от меня требуется? Ваш пример основан на tdjson.dll, а я хочу использовать Telegram.Td.dll. Разница в том, что первый способ оперирует строками json, а второй объектами. Я описываю проблему для второго случая. Строки в c# в памяти всегда хранятся как UTF-16, требование передавать строки в формате UTF-8 выглядит несколько странно. Проблема с русскими символами не только при передаче в td, но и при получении. Проблема похоже в том, что в нутрях td строки хранятся как UTF-8 и некорректно конвертируются в формат c# т.е. UTF-16.

**Comment by levlam** [comment]
@MedvedevIgor Strings supposed to be automatically converted from UCS-2 to UTF-8 when transferring between C# and C++. We need to investigate further, why this doesn't currently work.

**Comment by isopen** [comment]
Есть ссылка на проект с Вашими экспериментами?

**Comment by MedvedevIgor** [comment]
Ссылки на проект нет. Я взял тот проект, собрал, запустил, ввел телефон, код, мне вывелся список id чатов, далее я ввел команду gc <id>, где id идентификатор чата в описании которого есть русские буквы. В консоли вместо русских букв непонятно что, я посмотрел в отладчике, там тоже нет русских букв. Потом я еще поигрался с контрольными значениями (см. скриншот в моем первом сообщении) и написал сюда. Пример могу сделать, если конечно в этом есть смысл.

**Comment by levlam** [comment]
@MedvedevIgor There is no need in an example. Non-latin symbols can be shown wrong in the console, this is hard to fix portably. But there should be no problems with sending non-latin symbols in messages, so there should be a bug somewhere.

**Comment by isopen** [comment]
В примере нет смысла, если у Вас не сделано. Я попробую сейчас поиграть с этим.

**Comment by isopen** [comment]
http://joxi.ru/bmoxqXaFxZJ8B2

**Comment by isopen** [comment]
```
[DllImport("kernel32.dll")]
private static extern Int32 WideCharToMultiByte(UInt32 CodePage, UInt32 dwFlags, [MarshalAs(UnmanagedType.LPWStr)] String lpWideCharStr, Int32 cchWideChar, [Out, MarshalAs(UnmanagedType.LPStr)] StringBuilder lpMultiByteStr, Int32 cbMultiByte, IntPtr lpDefaultChar, IntPtr lpUsedDefaultChar);
public static string Utf16ToUtf8(string utf16String)
{
  Int32 iNewDataLen = WideCharToMultiByte(Convert.ToUInt32(Encoding.UTF8.CodePage), 0, utf16String, 
  utf16String.Length, null, 0, IntPtr.Zero, IntPtr.Zero);
  if (iNewDataLen > 1)
  {
    StringBuilder utf8String = new StringBuilder(iNewDataLen);
    WideCharToMultiByte(Convert.ToUInt32(Encoding.UTF8.CodePage), 0, utf16String, -1, utf8String, utf8String.Capacity, IntPtr.Zero, IntPtr.Zero);
     return utf8String.ToString();
   }
   else
   {
      return String.Empty;
    }
}
https://stackoverflow.com/questions/6198744/convert-string-utf-16-to-utf-8-in-c-sharp
```
@MedvedevIgor попробуйте пожалуйста эту хрень на своем примере.
На номере телефона у меня отработало.
После этого соответственно за флуд меня блокнуло т.к. строка подошла.) удачи с C#

**Comment by MedvedevIgor** [comment]
@isopen я уверен почти на 100% что подобный подход может сработать, но он жутко неудобный, т.к. придется все строки конвертировать, я не буду это использовать. Спасибо за помощь!

**Comment by isopen** [comment]
Расширьте класс String или напишите собственный, но лучше первое в данном случае.

**Comment by MedvedevIgor** [comment]
Забавная штука. В общем я выяснил, что маршалинг выполняется в модуле CxCli.h в "inline std::string string_to_unmanaged(String^ str)", проверка выполняется в модуле utf8.cpp в процедуре "bool check_utf8(CSlice str)" и туда приходит строка в кодировке windows-1251...
Смотрим сюда https://msdn.microsoft.com/ru-ru/library/bb384865.aspx, используется marshal_cppstd.h - все правильно.
Открываем marshal_cppstd.h  и вижу в методе "inline std::string marshal_as(System::String^ const & _from_obj)" строку "details::WriteAnsiString(_dest_buf, _size, _from_obj);"
Вывод: ошибка в модуле CxCli.h, конвертация строки выполняется неправильно.

**Comment by levlam** [comment]
@MedvedevIgor You've found everything right. The question is why the marshalling is done in such way? By documentation I've managed to found msclr::interop::marshal_as<std::string> supposed to convert string to UTF-8, so I don't know yet, why it doesn't work. And if it shouldn't work then what is a right way to convert .NET String to UTF-8 С++ string in C++/CLI?

**Comment by MedvedevIgor** [comment]
@levlam Я не практикую писать на cpp, поэтому могу ошибаться. Я бы сделал как-то так:
1) сначала конвертировал строку c# в UTF-8 с помощью (надо переписать на cpp):
byte[] data = System.Text.Encoding.UTF8.GetBytes("Привет");
2) скопировал байты из одного массива в другой.

**Comment by isopen** [comment]
Ну давайте UTF-16 внутрь tdlib.

**Comment by isopen** [comment]
Далеко не шутки. Microsoft специпльно делает хрень.

**Comment by isopen** [comment]
Т.е. Вы уводите конвертр внутрь tdlib. Да вы гоните что ли оба два. Это косяк Microsoft. Пусть исправляют!!!

**Comment by isopen** [comment]
Лев способ изначально с маршалингом был не рабочим т.к. похер на utf-16. Utf-16 это вообще дичь.

**Comment by isopen** [comment]
https://msdn.microsoft.com/ru-ru/library/bb531313.aspx

**Comment by MedvedevIgor** [comment]
@isopen, строки в java тоже хранятся как UTF-16, а там есть такая проблема? Похоже придется написать свой маршалер для строк, но хочу заметить что он ненужен для tdjson.dll, а нужен только для Telegram.Td.dll.
Ещё хочу обратить внимание на то, что tdjson представляет русские символы в формате "u\1234", таким образом строки UTF-8 и Ansi будут полностью совпадать.   В итоге используя tdjson.dll строки всегда приходится конвертировать в utf-16.

**Comment by isopen** [comment]
Отличный план.

![image](https://user-images.githubusercontent.com/7373292/38665578-ebb677a2-3e66-11e8-815b-a20b3a3ac031.png)

**Comment by isopen** [comment]
Ну что мужики готов у кого-нибудь костыль для файла CxCli.h?

**Comment by isopen** [comment]
https://msdn.microsoft.com/en-us/library/ms235219.aspx

**Comment by isopen** [comment]
Лев по завершению рефакторинга сделай деплой.

**Comment by isopen** [comment]
Вероятно можно ещё маршала использовать, но это очередная птица
https://msdn.microsoft.com/ru-ru/library/1b4az623.aspx

**Comment by MedvedevIgor** [comment]
@isopen, я вообще то не умею на cpp писать)) рефакторинг должен сделать профи

**Comment by isopen** [comment]
Тогда кому-то нужно позвонить в Microsoft. Думаю Арсений может сделать это.

**Comment by restYura** [comment]
@isopen A temporary solution approached me

**Comment by UnblockerUsername** [comment]
It's unforgettably cool :) utf-8 earned from me. I try to improve the functionality.

**Comment by UnblockerUsername** [comment]
I think here can only help @levlam. @levlam please improve the solution. @isopen something there said in the end. You can obviously optimize it and publish it in the comments.

**Comment by UnblockerUsername** [comment]
@MedvedevIgor There is already a crossed bulldog with a behemoth. So I'm sure that you can write better CxCli than @levlam.

**Comment by levlam** [comment]
Fixed in TDLib 1.3.0. Thanks again, @MedvedevIgor.
