### ISSUE TITLE
Calling MTProto RPC functions directly

### ISSUE THREAD

**Issue by KishanBagaria** [tdlib/td#1811]
Does tdlib provide a way to call [MTProto RPC functions](https://core.telegram.org/schema) directly? We want to use it for sending reactions.

**Comment by levlam** [comment]
No.

**Comment by KishanBagaria** [comment]
Would you consider adding something like that? A function that accepts a JSON string and returns the resulting data as JSON?

**Comment by KishanBagaria** [comment]
Would you consider adding something like that? A function that accepts a JSON string and returns the resulting data as JSON.

**Comment by levlam** [comment]
No. This would interfere with a lot of TDLib functionality.

**Comment by KishanBagaria** [comment]
Fair enough. Hope the reaction functionality comes soon.
