### ISSUE TITLE
Setting Option during state "AuthorizationStateReady" sometimes returns 401 Unauthorised

### ISSUE THREAD

**Issue by Drumbard8** [tdlib/td#1812]
Once my application has finished logging in and I've got the `AuthorizationStateReady` response, I then try to set the option `ignore_inline_thumbnails`, most of the time it works, however sometimes I get an error response `401, Unauthorized`.

[This issue](https://github.com/tdlib/td/issues/675#issuecomment-524497192) says how we might get a 401, but I have verified that the account its still fine and isn't banned. I only ever try to set this option just after I enter the `AuthorizationStateReady` state, so I'm not sure how this has occurred. I didn't have this issue on v1.6.0 so maybe there's something new I'm missing?

**Comment by levlam** [comment]
The only way to receive 401 is to be logged out. You received `updateAuthorizationState` with `authorizationStateLoggingOut` before this response. You can see TDLib logs with verbosity level 3 to check this.

**Comment by Drumbard8** [comment]
Thanks @levlam . I don't get the 401 too frequently, so for now I'll set my log verbosity level to 3, wait, then check the logs when this next occurs. I'll close the issue now.
