### ISSUE TITLE
Telegram x consuming lot of mobile data even the app is not open 
(also enabled data saver mode)

It consumes 10-50 kbps each seconds as long as it running in background and Foreground.

It is okay when Iam downloading something.
But this isn't okay to consume this amount of data continuously. It cause my limited data pack Expiring in short time. 

I checked bot telegram and Telegram x while telegram do not consuming this amount of data for receiving messages in background and Foreground.!
You can see the video that I am attached. 

### ISSUE THREAD

**Issue by Ziyad030** [tdlib/td#1813]
[https://t.me/datacusunes123/2]()

**Comment by levlam** [comment]
Messages are received in incoming updates from the server. There is no any difference between clients there. You should be a member of a few very active groups to have so much incoming messages.

Apps are allowed to work in background for 1 minute and Telegram X doesn't disable network access after going to background, so you will not see "Updating" when returning to the app.

It is impossible to tell, what exactly is downloaded, without TDLib logs. If you would set TDLib log verbosity level to DEBUG, increase log size to 100000000 bytes, reproduce the issue and send the logs to https://t.me/tdlib_bot, I can tell you the exact reason of the data usage.

**Comment by levlam** [comment]
According to the log, the big data usage is caused by a bot, which very often edits a lot of big messages.
