### ISSUE TITLE
searchChatMessages issue

### ISSUE THREAD

**Issue by andyliu1985** [tdlib/td#1814]
When I search Chinese characters or a partial word, no message returns. 
It only returns messages when typing in the whole message as the search keywords. This happens in Web Version Z and Android.

Current Behaviour
![Error1](https://user-images.githubusercontent.com/43029777/148296494-c34b586b-2b68-425a-afc2-c671724a5938.jpg)
![Error2](https://user-images.githubusercontent.com/43029777/148296498-2c025977-5631-4560-b9a4-5a36f3b88577.jpg)

Better Behaviour 
![Correct1](https://user-images.githubusercontent.com/43029777/148296484-bfebe424-ba18-4c63-b119-5054f182611e.jpg)
![Correct2](https://user-images.githubusercontent.com/43029777/148296489-f525ba66-eb92-4103-a90e-ae6ef46821a8.jpg)

**Comment by levlam** [comment]
The search is done server-side, so this is unrealted to TDLib. See https://bugs.telegram.org/c/724 for more details.

**Comment by andyliu1985** [comment]
Thank you very much!On 7/01/2022 01:16, Aliaksei Levin ***@***.***> wrote:
The search is done server-side, so this is unrealted to TDLib. See https://bugs.telegram.org/c/724 for more details.

**Comment by andyliu1985** [comment]
> The search is done server-side, so this is unrealted to TDLib. See https://bugs.telegram.org/c/724 for more details.

Thank you very much!
