### ISSUE TITLE
Too Many Requests: retry after

### ISSUE THREAD

**Issue by lichegn** [tdlib/td#1816]
o.d.tdlib.utils.AuthorizationRequestHandler| Receive an error: Error {
  code = 429
  message = "Too Many Requests: retry after 142"
}

when auth firth account, it tip me this error.
how to deal it?

**Comment by AYMENJD** [comment]
You have exceeded limits. Just wait 142 seconds then retry

**Comment by lichegn** [comment]
auth some account need wait some minutes?

**Comment by lichegn** [comment]
> Reference in new

how to remove this limit

**Comment by AYMENJD** [comment]
Limits can't be removed, just wait for 142 then try again.
