### ISSUE TITLE
joinChatByInviteLink question

### ISSUE THREAD

**Issue by MoroZvlg** [tdlib/td#182]
In api doc 'class | td::td_api::joinChatByInviteLink': 
```
Detailed Description
Uses an invite link to add the current user to the chat if possible. The new member will not be added until the chat state has been synchronized with the server.

Returns object_ptr<Chat>.
```

but i get:
`{"@type"=>"ok", "@extra"=>"29931932465703432271523009436.925586"}`

what i miss?

**Comment by levlam** [comment]
`Chat` object is returned since TDLib 1.2.0.

**Comment by forconz** [comment]
new TdApi.JoinChatByInviteLink("https://t.me/joinchat/happysxlife666")

I Sends the request to the TDLib, but the logged user can not join the chat..

**Comment by levlam** [comment]
@forconz This is not a valid invite link. "happysxlife666" looks like a chat username instead.
