### ISSUE TITLE
There was a bug in tdlib that crashed my whole program

### ISSUE THREAD

**Issue by HuMzan** [tdlib/td#1820]
TDLib fatal error: [ 0][t36][1641700688.451681137][Td.h:140][#3634][!MessagesManager][&close_flag_ < 1] 1 td::ActorId td::Td::create_net_actor(ArgsT&& ...) [with ActorT = td::SendMessageActor; ArgsT = {}]

This is the only information I get useful

My guess might be that the client exit and send message concurrently happened

Can avoid the entire program crashing due to a client error?

**Comment by levlam** [comment]
Fatal errors can't be avoided or recovered. There is no way to continue execution of the process after them.

Between, which TDLib version is it?

**Comment by HuMzan** [comment]
> Fatal errors can't be avoided or recovered. There is no way to continue execution of the process after them.
> 
> Between, what TDLib version is it?

tdlib1.80 version

**Comment by levlam** [comment]
In TDLib 1.8.0 this check is on the line 133, not on the line 140. Was it modified somehow?

**Comment by HuMzan** [comment]
no

**Comment by levlam** [comment]
Do you close TDLib right after receiving response to `sendMessage`? The message isn't sent yet.

**Comment by HuMzan** [comment]
> Do you close TDLib right after receiving response to `sendMessage`? The message isn't sent yet.

I'm not sure, but I think it's more likely and I'll test. Because I automatically quit periodically to reduce memory

**Comment by levlam** [comment]
This should be fixed in TDLib 1.8.1.
