### ISSUE TITLE
Bot message detection

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#1823]
Hi!
Could you please tell how to understand whether incoming message was sent from bot?
I can see 'viaBotUserId' field in Message class, but it is always 0 - doesn't matter bot sent message or not.
Maybe there are some other options how it can be detected?

**Comment by Mike497** [comment]
Ok, but how to detect that exactly bot sent incoming message to the user?
At the moment I see that there is an option to make additional request via GetUser for user id from Message.sender.userId and to get user type from response.

**Comment by levlam** [comment]
You never need to call `getUser` to get information about a `user_id`. See description of `updateUser` updates in https://core.telegram.org/tdlib/getting-started#handling-updates.
