### ISSUE TITLE
There is a crash log

### ISSUE THREAD

**Issue by HuMzan** [tdlib/td#1826]
[hs_err_pid15100.log](https://github.com/tdlib/td/files/7863495/hs_err_pid15100.log)

**Comment by levlam** [comment]
Could you try to increase threads stack size?

**Comment by levlam** [comment]
Does it crash on the first received message?

**Comment by HuMzan** [comment]
> Could you try to increase threads stack size?

I try

**Comment by HuMzan** [comment]
> Does it crash on the first received message?

Sorry, I didn't find its crash time, and the runtime log was not saved correctly

**Comment by levlam** [comment]
@HuMzan What is output of `ulimit -s`?

**Comment by HuMzan** [comment]
> @HuMzan What is output of `ulimit -s`?

8192

**Comment by levlam** [comment]
If automatic stack expansion is enabled, there should be no issues with stack size with this limit.

**Comment by levlam** [comment]
`td::is_emoji` implementation was rewritten in TDLib 1.8.1, so this may be fixed.
