### ISSUE TITLE
signal: aborted - app crashes when calling tdlib methods 

### ISSUE THREAD

**Issue by Zoha** [tdlib/td#1828]
Hi. 
I'm using tdlib for my telegram client 
and for `tdjson` binding in golang I'm using [go-tdlib ]([url](https://github.com/Arman92/go-tdlib)) 
so in some cases, my app crashes without any error ( from golang side ) 
this error is happening with no specific rule 
sometimes right after running the project when I'm creating a new client 
sometimes after calling one of the methods like `getChats`
but most of the time when I'm trying to download a file from telegram with the `DownloadFile` function 
my console just says this simple message 
`signal: aborted`
and app crashes ( exited )

I deleted all my build files and tdlib database files several times. but still getting the same error 
I'm handling all the errors in my app. it just crashes without any throwing error in my app

this message is  in my errors file : 
`
[ 0][t 1][1642109675.091958522][Binlog.cpp:667][#1][!Binlog /demo/dev/tdlib-db/td.binlog][&fd_size_ == detail::file_size(path_)]	11412 0 105 /demo/dev/tdlib-db/td.binlog
`

![image](https://user-images.githubusercontent.com/16442858/149415240-1d5f594e-b484-402b-b249-7d9ce65821e6.png)

any idea what is the problem

**Comment by levlam** [comment]
The issue happens on some filesystems (usually some virtual filesystems), but we can't reproduce it for investigation. We check that after renaming the file, it exists and can be accessed with its new name, but on some filesystems the check fails. This results in the assertion failure.

On Windows, the order of calls is
```
MoveFileFromAppW(old_file_name, new_file_name);
CreateFile(new_file_name, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_DELETE | FILE_SHARE_WRITE, nullptr, 0, FILE_FLAG_BACKUP_SEMANTICS, nullptr);
```
The second call fails to open the file, despite `MoveFileFromAppW` succeeded and the file exists.

**Comment by Zoha** [comment]
thanks for your reply @levlam 
I'm using docker on windows. is there any way to fix this issue? 
if not, is there any way to handle this error for preventing app to crash?
