### ISSUE TITLE
Send existing phot in SendMessage, InputMessagePhoto

### ISSUE THREAD

**Issue by Arman92** [tdlib/td#183]
I want to send an existing photo by it's file id

[inputFileID](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_id.html) has a 32bit id which a fileID that has a length of 64 bits, won't fit it.
[inputFileRemote](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_remote.html) does not seem to work

only [inputFileLocal](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_local.html) worked for me, which upload the photo every time.

I get the photo's file id  in a received message (content->messagePhoto->photo->id)

**Comment by levlam** [comment]
You are trying to use a photo identifier instead of a file identifier. You need content->messagePhoto->photo->sizes->photo->id instead. Be aware that file_ids aren't persistent, so they can be used only within one library launch. If you need persistent identifiers, you can use content->messagePhoto->photo->sizes->photo->remote->id and inputFileRemote.

**Comment by Arman92** [comment]
Thanks a lot dude

**Comment by shironoY6** [comment]
Thanks for this info! With this, I managed to get very close.

@Arman92 @levlam 
Would you mind helping me out about `inputFileRemote`?

I can post a photo with `inputFilelocal` to a channel that my bot is an admin. But if I try to use a `inputFileRemote` instead, my query becomes pending state forever `messageSendingStatePending`...

I use `python-telegram` package.

```
# I get a message (with `messagePhoto` content) in a public channel by
msg = tg.tg.get_chat_history(chat_id, from_message_id)

remoteFileID = msg['content']['photo']['sizes'][0]['photo']['remote']['id'] # try to get the persistent identifier

data = {
    '@type': 'sendMessage',
    'chat_id': -10XXXXXXX,  # my bot is an admin
    'input_message_content': {
        '@type': 'inputMessagePhoto',
        'photo': {
            "@type": "inputFileRemote",
            "id": remoteFileID
        },
    }
}

r = tg._send_data(data)
```
`r.error` is False, meaning it's not an error at least.

But the update object `r.update` reports that 

```
'sending_state': {'@type': 'messageSendingStatePending'}
```

Here is the warning in the log:

In [23]: [ 2][t 4][1638630894.771120548][FileManager.cpp:3686][#1][!FileManager]	Failed to UploadWaitFileReference file 2851(0) of type photos: [Error : 0 : FILE_UPLOAD_RESTART_WITH_FILE_REFERENCE]
[ 2][t 4][1638630894.771162509][FileManager.cpp:3686][#1][!FileManager]	Failed to UploadWaitFileReference file 2851(0) of type photos: [Error : 0 : Can't upload file: have no valid file reference]
[ 2][t 4][1638630894.771236181][MessagesManager.cpp:8850][#1][!MessagesManager]	File 2852(2850) has upload error [Error : 0 : Need full local (or generate, or inactive remote) location for upload]

The original post still exists and my bot can fetch it but how come I see ` Can't upload file: have no valid file reference`?


FYI, if I replace the `inputFileremote` to `inputFilelocal` for `inputMessagePhoto`:

```
        'photo': {
            "@type": "inputFileLocal",
            "path":  "/path/2/my_image.png"
        }
```

The query works.

**Comment by shironoY6** [comment]
I figured out. My code was actually just fine. 

The remoteFile that I was trying to use was in a public chat that my bot cannot use (BANNED?). Another remoteID from a different channel just worked fine.

**Comment by levlam** [comment]
@shironoY6 Between, you should have received `updateMessageSendFailed` for the message.

**Comment by shironoY6** [comment]
How do I receive it? Logger (with what verbosity?)? I tried to `r.wait()` or `r = td._send_data(data, block=True)` but no luck...

By the way, when I used `td.get_chat_history` to refresh the local cache in the same session, everything started working... I was re-using pickled message in another session when it failed.

**Comment by levlam** [comment]
`updateMessageSendFailed` is an update and is received as any other update: https://core.telegram.org/tdlib/getting-started#handling-updates.
