### ISSUE TITLE
How do I use the test DC to test auth flow?

### ISSUE THREAD

**Issue by UjuE** [tdlib/td#1830]
I am following the instruction on https://core.telegram.org/api/auth#test-accounts
I am definitely setting my useTestDc parameter to true
My test number is 9996625555
I entered OTP 222222
The Phone Code is invalid.

What am I doing wrong?

**Comment by levlam** [comment]
The code was changed back to "22222" (5 digits).

**Comment by UjuE** [comment]
Thank you. That worked
