### ISSUE TITLE
Which .lib files contains declaration for td_json_client header? (windows)

### ISSUE THREAD

**Issue by Yaroslav1233** [tdlib/td#1832]
Which .lib files contains declaration for td_json_client header? (windows)

**Comment by levlam** [comment]
`tdjson.lib` is import library for `tdjson.dll`, `tdjson_static.lib` is a statically linked library for JSON interface.

**Comment by Yaroslav1233** [comment]
@levlam Thank you. What's tdjson_private.lib?

**Comment by levlam** [comment]
It is a common private part of `tdjson.lib` and `tdjson_static.lib`.
