### ISSUE TITLE
addProxy doesn't work

### ISSUE THREAD

**Issue by 50u1w4y** [tdlib/td#1833]
Since telegram is blocked, the example code will stop after `Enter phone number:`.

So, I want to add a proxy for telegram based on the [example code](https://github.com/tdlib/td/tree/master/example/cpp).

I add the following code after cilent ID created:

```
send_query(td_api::make_object<td_api::addProxy>("127.0.0.1", 10808, true, td_api::object_ptr<td_api::proxyTypeSocks5>()), {});
```

I am running v2ray on my computer and it works well when using web browser. However, the example code also stop after `Enter phone number:`.

I also test port 10809 for v2ray http proxy and port 1080 for shadowsocks. All of them get the same result.

Is my call for addProxy wrong or maybe something else?

Thank you.

**Comment by levlam** [comment]
What do you mean by "the example code also stop"? You can also set log verbosity level to 4 and check TDLib logs for details.

**Comment by robinfoxnan** [comment]
yes, I got it , Thanks
