### ISSUE TITLE
limits in tdlib

### ISSUE THREAD

**Issue by hasanizadt** [tdlib/td#1834]
in telegram bot api mentioned : 
In the local mode the Bot API server allows to:
Set max_webhook_connections up to 100000.
----
1- what is that mean?
in the normal bot, we can send 30 request in second. with bot api, can we 100,000 request in second?
2- if answer is NO, how many is the limit on the number of requests?
3- Do we have access to these feature in td ?

**Comment by levlam** [comment]
1, No, this is completely unrelated. See `max_connections` in https://core.telegram.org/bots/api#setwebhook.
2, This is absolutely the same server, which is used at api.telegram.org.
3. What features?

**Comment by hasanizadt** [comment]
thanks.
what is number of request limit for api bots?

**Comment by levlam** [comment]
> what is number of request limit for api bots?

There is no such thing generally.

**Comment by hasanizadt** [comment]
i read this and misunderestand.
API requests frequency (can be raised by BotSupport). up to 30 requests per second.
what is API requests frequency ?

**Comment by levlam** [comment]
There is no such thing as "API requests frequency". The only place which mentions 30 requests per second is https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once, which explicitly talks about bulk notifications.
