### ISSUE TITLE
What are the reasons why the client cannot be closed for a long time? 

### ISSUE THREAD

**Issue by HuMzan** [tdlib/td#1840]
When I execute new TdApi.Close() ,After receiving the TdApi.AuthorizationStateClosing notification, it takes a very long time to receive the TdApi.AuthorizationStateClosed

So I don't know if the unknown conditions are not met, resulting in a prolonged shutdown.

I want to kill a client quickly

![2022-01-24 140045](https://user-images.githubusercontent.com/24567958/150838640-bde7383b-c1ee-4d81-994d-94ec04b4593d.png)

**Comment by levlam** [comment]
It should be pretty fast. Could you send TDLib logs with verbosity level 14 to @tdlib_bot, starting from the call to `TdApi.Close`?

**Comment by HuMzan** [comment]
> It should be pretty fast. Could you send TDLib logs with verbosity level 14 to @tdlib_bot, starting from the call to `TdApi.Close`?

ok

**Comment by HuMzan** [comment]
> It should be pretty fast. Could you send TDLib logs with verbosity level 14 to @tdlib_bot, starting from the call to `TdApi.Close`?

When I execute TdApi.SetLogVerbosityLevel(14), an error will be reported：

TDLib fatal error: [PosixError : Bad file descriptor : 9 : Write to [fd:336] has failed] in /usr/src/tdlight-java-natives/generated/implementation/tdutils/td/utils/FileLog.cpp at 84

**Comment by levlam** [comment]
Have you specified aт acessible and writable path in `TdApi.LogStreamFile`?

**Comment by HuMzan** [comment]
> Have you specified aт acessible and writable path in `TdApi.LogStreamFile`?

Yes, there is a default path

**Comment by HuMzan** [comment]
> Have you specified aт acessible and writable path in `TdApi.LogStreamFile`?

 
![2022-01-27 141509](https://user-images.githubusercontent.com/24567958/151302472-9062a6e1-2ded-4407-b12e-4044a55f8869.png)
 After pressing the above settings, my program crashes

tdTest.binlog The contents of the document are:

TDLib fatal error: [PosixError : Bad file descriptor : 9 : Write to [fd:331] has failed] in /usr/src/tdlight-java-natives/generated/implementation/tdutils/td/utils/FileLog.cpp at 84

**Comment by levlam** [comment]
Try to use another path. Between, the log is common for all bots and must be opened once.
