### ISSUE TITLE
Error: java.lang.UnsatisfiedLinkError. Library not loaded

### ISSUE THREAD

**Issue by Dust09** [tdlib/td#1841]
Im trying to execute my code, but it calls error : "Caused by: java.lang.UnsatisfiedLinkError" with text "Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib"
Im also tried create link by command : "ln -sf /opt/homebrew/opt/openssl@3 /usr/local/opt/"
and it created link in /usr/local/opt. Also i checked the file which was in log "../openssl@3/lib/libssl.3.dylib" and it exist. I guess its connected with openssl, how can i solve this problem?

my equipment: Mac m1

P.S the same code i executed on windows and it work

**Comment by levlam** [comment]
What is output of `which java` and `java --version`?

**Comment by Dust09** [comment]
> 

java -version: 
openjdk version "1.8.0_312"
OpenJDK Runtime Environment Corretto-8.312.07.1 (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM Corretto-8.312.07.1 (build 25.312-b07, mixed mode)

which java: 
/usr/bin/java

**Comment by Dust09** [comment]
I changed version. Now i getting another error :
Caused by: it.tdlight.common.utils.CantLoadLibrary: Native libraries for platform OSX-AARCH64 not found! Required version: tdlight osx aarch64 4.0.219

my gradle dependences:

> dependencies {
    implementation platform('it.tdlight:tdlight-java-bom:2.8.0.5')
    implementation 'it.tdlight:tdlight-java'
    **implementation 'it.tdlight:tdlight-natives-osx-amd64'**
}

**Comment by levlam** [comment]
"-amd64" library is definitely not suitable for aarch64 Java.

**Comment by Dust09** [comment]
is there any plan in future to add support for osx-aarch64?

**Comment by levlam** [comment]
TDLib supports aarch64. You are trying to use prebuilt tdlight package, which is unrelated to TDLib.

**Comment by Dust09** [comment]
Thanks for your answers
