### ISSUE TITLE
How to keep talking with server?

### ISSUE THREAD

**Issue by Yaroslav1233** [tdlib/td#1842]
How to keep talking with server? I don't want to get timeout error from receive.

**Comment by levlam** [comment]
You must call `td_receive` in a cycle to receive new data.

**Comment by Yaroslav1233** [comment]
@levlam I know about it. But timeout is end. And i get error. How to prevent it

**Comment by Yaroslav1233** [comment]
@levlam I have auth successfully

**Comment by levlam** [comment]
You can't get an error from `td_receive`. If timeout is exceeded, then it returns NULL and you can repeat the call to td_receive.

**Comment by Yaroslav1233** [comment]
I made error in my cpp shell script. So I got error.
