### ISSUE TITLE
[feature] Introduce type lists

### ISSUE THREAD

**Issue by egorpugin** [tdlib/td#1845]
Hi,

Files with downcast calls are too big (td_api.hpp and telegram_api.hpp).
The following link demonstrates improvements over them.
https://godbolt.org/z/68Wdo58Ws

It will cut down those files to a few lines and greatly improve parsing time.
Type lists may be useful for users as well.

What should be done for this:
1. Autogeneration of type lists with their base (lines 22-23)
```
using all_types = type_list<object, a,b,c,d,e,f>;
using updates = type_list<update, e,f>;
```
2. Inserting hand-written the most basic templated downcast_call (lines 27-33)
```
template <typename TypeList>
bool downcast_call(typename TypeList::base &obj, auto &&f) {
    auto id = obj.get_id();
    return [&]<typename Base, typename ... Types>(type_list<Base, Types...>) {
        return (... || (id == Types::ID && (f(static_cast<Types&>(obj)), true)));
    }(TypeList{});
}
```
3. Autogeneration of specific downcast_calls (can be wrapped into a macro `DOWNCAST_CALL(base, typelist)`) (lines 34-41)
```
bool downcast_call(object &obj, auto &&f) {
    return downcast_call<all_types>(obj, f);
}
```

I can try to prepare a PR with changes.
To prevent breaking existing code, new generated files could be named as `td_api_cpp20.hpp` and `telegram_api_cpp20.hpp`.

**Comment by levlam** [comment]
".hpp" files are much smaller than corresponding ".h" files. They should be parsed much faster, given that they contains only templates, instantiated on-demand. So they relative impact on build time should be small. Do you have any figures about parsing time improvements?

Additionally, we can't use features of C++20 or C++17, because many supported OS have only C++14-compatible compilers.

Also, have you tested performance implications of your approach? It uses chain of if statements instead of single switch, which should have visible performance impact in run-time and lead to increase of executable size.

> Autogeneration of specific downcast_calls (can be wrapped into a macro DOWNCAST_CALL(base, typelist)

There are no reasons to use simple macros in auto-generated code.

**Comment by egorpugin** [comment]
With simple type map there is no need in specific downcast calls.
https://godbolt.org/z/jMW1rdYha

**Comment by egorpugin** [comment]
> Additionally, we can't use features of C++20 or C++17, because many supported OS have only C++14-compatible compilers.

Yes, separate files can do the trick.

> Do you have any figures about parsing time improvements?

I did not test it yet. Maybe I'll try to test it some time.

> It uses chain of if statements instead of single switch

Compilers MUST be smart enough.

**Comment by egorpugin** [comment]
I'm thinking about improvements, because simple `downcast_call(*obj, [](auto &&){});` repeated 100-200 times make TU compilation time more than 5 minutes.

I do not get numbers with proposed approach yet.

**Comment by egorpugin** [comment]
@levlam 

After some thinking, I see that modern C++ allows to introduce downcast_call on the user side.

To do this we need two things:
1. Type lists as the title states. The example is in the first post. Should be a useful addition exactly for this task.
2. Information about type bases for the leaf types. A bit increate of huge td_api.h, but that's the cost.
```
struct chat : object {
    using base_type = object;
   ...
```

Is it possible to add such metainformation?

---

Example of custom downcast_call with additions above
```

template <typename T>
bool downcast_call(T &obj, auto &&f) {
    constexpr auto base_type = [](){
        if constexpr (requires { typename T::base; })
            return type_id_v<typename T::base>;
        else
            return type_id_v<T>;
    }();
    using BaseType = decltype(base_type)::type;
    auto id = obj.get_id();
    return [&]<typename Base, typename ... Types>(type_list<Base, Types...>) {
        return (... || (id == Types::ID && (f(static_cast<Types&>(static_cast<BaseType&>(obj))), true)));
    }(typename decltype(map::value(type_id_v<BaseType>))::type{});
}
```

Complete example https://godbolt.org/z/KPbn8vKa1

**Comment by levlam** [comment]
> Yes, separate files can do the trick.

There will be no ways to use the headers in TDLib, so there are no much reasons to include them in TDLib. They can be generated from td_api.tl by the app, which wants to use them as extension.

> I did not test it yet. Maybe I'll try to test it some time.

I will not be surprised if your approach will build slower and will use more memory during compilation.

> Compilers MUST be smart enough.

They aren't. You shouldn't expect from compilers more than they are intended to provide.

> I'm thinking about improvements, because simple downcast_call(*obj, [](auto &&){}); repeated 100-200 times makes TU compilation time more than 5 minutes.

This happens because the template is instantiated each time with a different lambda type. It is unrelated to the way downcast_call is declared and implemented. I also expect that with your approach build time will be even longer. This needs to be tested first.

**Comment by egorpugin** [comment]
30 `downcast_call(*o, [](auto &&){});`
current - https://pastebin.com/pixs7hZ6
proposed - https://pastebin.com/vkwChLFC

You are right. Results are worse.

So, to speedup builds `if (ID == ` should be used?
What do you think about adding `base_type` and type lists still? Maybe somewhere they'll be useful.

**Comment by levlam** [comment]
> You are right. Results are worse.

Also, does the final executable bigger and slower?

> So, to speedup builds if (ID == should be used?

It will not help. The only thing, which can help, is to make downcast_call non-template, accepting a fixed class, so it can be instantiated only once.

**Comment by egorpugin** [comment]
> It will not help. The only thing, which could help, is to make downcast_call non-template, accepting a fixed class, so it can be instantiated only once.

But the handler is always different, isn't it?
In case of lambdas.

**Comment by egorpugin** [comment]
While it is not very meaningful to measure on such hello world.
Also there is other PCH from this project that causes some minimum binary size.
```
  --- 30 downcast_call -O0 ---
approach    | build time    | binary size   | run time          | gcc -ftime-report
-----------------------------------------------------------------------------------
current     | 18.94         | 190130040     | 0.000130921 s.    | https://pastebin.com/pixs7hZ6
proprosed   | 41.18         | 192193720     | 0.000280693 s.    | https://pastebin.com/vkwChLFC
swl variant | 95.23         | 536447336     | 0.000041078 s.    | https://pastebin.com/3zKdZgTL
std variant | did not compile even with zero std::visit's

```

**Comment by levlam** [comment]
> But the handler is always different, isn't it?
In case of lambdas.

Yes, but the handler can be made opaque like std::function can make opaque a single function.
