### ISSUE TITLE
I don't understand how the new TDJson interface works.

### ISSUE THREAD

**Issue by jawhien** [tdlib/td#1846]
Объясните, пожалуйста некоторые моменты в документации по TDJson.

> New updates and responses to requests can be received through td_receive from any thread after the first request has been sent to the > client instance. This function must not be called simultaneously from two different threads.

так всё таки можно или нельзя получать обновления из любого потока?
Или обновления через td_receive можно получать только в одном потоке, в котором был отправлен первый запрос? Или как-то иначе?

> TDLib client instances are destroyed automatically after they are closed. All TDLib client instances must be closed before application > termination to ensure data consistency.

Тоже не понял, уничтожаются автоматически или должны быть закрыты? Если должны, то каким образом?

**Comment by levlam** [comment]
`td_receive` can be called from arbitrary thread. But there must be no two simultaneous calls from different threads.

Client is destroyed automatically after it is closed. To close a client you need to call `close` TDLib method and wait `updateAuthorizationState` with `authorizationStateClosed`.

**Comment by jawhien** [comment]
@levlam 
Thanks!
