### ISSUE TITLE
TdLib get stuck when getting chats list

### ISSUE THREAD

**Issue by AliaksandrZhloba** [tdlib/td#1847]
The account has about 500 very active chats (a lot of new messages from different chats per second).
All I want is to get the list of all chats.
I've tried:
```
- await _client.ExecuteAsync(new TdApi.LoadChats() { ChatList = new TdApi.ChatList.ChatListMain(), Limit = 100 })
- await _client.ExecuteAsync(new TdApi.GetChats { Limit = 1 });
```

Both lines neither finish execution nor throw any exception.

In tdlib's log I see:
`Delay: [Query:[id:22806528][tl:0x4423e6c5][state:Query]] [timeout:29.000000][total_timeout:29.000000] because of [Error : 420 : FLOOD_WAIT_29] from Session:5:main::Connect::Tcp::[] to DcId{5} `

and sometimes:
```
[ 1][t 4][1643094983.597940683][UpdatesManager.cpp:965][#1][!UpdatesManager]	Receive updates.getDifference error: [Error : 500 : Unknown constructor found 0xeb0467fb]
[ 1][t 4][1643094983.602462530][Td23.cpp:268][#1][!Td]	Failed to fetch update: Unknown constructor found 0xc37521c9
```

Does anyone have an idea what's wrong and what can be done?
Does anyone know what "Unknown constructor found" means?

TDLib 1.7.9
var bindings = Interop.AutoDetectBindings();

**Comment by levlam** [comment]
The mentioned log lines aren't related to `loadChats`/`getChats`.

Could you `setLogStream` to `logStreamFile` of a big enough size, reproduce the issue with log level 4 and send the log to https://t.me/tdlib_bot?

**Comment by levlam** [comment]
You need to
1. Find `loadChats` request in the log and note it's identifier from the line "Receive request <id>: loadChats".
2. Then find in the log line "Sending result for request <id>" with the same ID.

The presence of the second line in the log means that TDLib sent response, but your code or code of the wrapper blocked the thread handling responses from TDLib. All updates and request responses are handled in a dedicated thread, which must not be blocked.

**Comment by AliaksandrZhloba** [comment]
What if I couldn't find any loadChats request in the log? And no lines with "Receive request" at all?
TdLib log verbosity level: 4

**Comment by levlam** [comment]
If you didn't change 'td_request' log tag verbosity level, then there must be "Receive request" lines in the log with verbosity level >= 3. For example, there must be a line with `setTdlibParameters` request.

**Comment by AliaksandrZhloba** [comment]
``> 2\. Sending result for request

So, log has
```
[ 3][t 4][1644941505.929350614][Td9.cpp:196][#1][!Td][&td_requests]	Receive request 3: loadChats {
  chat_list = chatListMain {
  }
  limit = 100
}
```

And doesn't have `Sending result for request 3:` at all.

Some more lines related to LoadChats:
```
[ 3][t 4][1644941505.929453611][MessagesManager17.cpp:183][#1][!LoadChatsRequest]	Get chats in chat list folder 0 with offset [9223372036854775807, 0] and limit 100. last_dialog_date = [9223372036854775807, 0], last_pinned_dialog_date_ = [9223372036854775807, 0], are_pinned_dialogs_inited_ = false
[ 3][t 4][1644941505.929483652][MessagesManager25.cpp:219][#1][!LoadChatsRequest]	Load dialog list in folder 0 with limit 100
[ 4][t 4][1644941505.929494857][MultiPromise.cpp:15][#1][!LoadChatsRequest]	Add promise #1 to LoadDialogListMultiPromiseActor
[ 3][t 4][1644941505.929501056][MessagesManager25.cpp:229][#1][!LoadChatsRequest]	Get chats from [9221294780217032704, 0]
[ 4][t 4][1644941505.929507493][MultiPromise.cpp:15][#1][!LoadChatsRequest]	Add promise #2 to LoadDialogListMultiPromiseActor
[ 4][t 4][1644941505.929517984][MultiPromise.cpp:30][#1][!LoadChatsRequest]	Get promise #1 for LoadDialogListMultiPromiseActor
[ 4][t 4][1644941505.929525852][MultiPromise.cpp:30][#1][!LoadChatsRequest]	Get promise #2 for LoadDialogListMultiPromiseActor
[ 4][t 4][1644941505.929656505][MultiPromise.cpp:30][#1][!LoadChatsRequest]	Get promise #3 for LoadDialogListMultiPromiseActor
[ 3][t 4][1644941505.929750204][MessagesManager41.cpp:674][#1][!LoadChatsRequest]	Wait for loading of 100 chats in chat list folder 0
```

**Comment by levlam** [comment]
> And doesn't have `Sending result for request 3:` at all.

Does it have "Sending error for request 3:"?

**Comment by AliaksandrZhloba** [comment]
> > And doesn't have `Sending result for request 3:` at all.
> 
> Does it have "Sending error for request 3:"?

No, it doesn't.

**Comment by levlam** [comment]
Do other requests work at the same time, for example, `getActiveSessions`?

**Comment by AliaksandrZhloba** [comment]
No any other requests and no any other activity in the application during loading list of chats at all.

```
[ 3][t 4][1644941119.146164655][Td9.cpp:196][#1][!Td][&td_requests]	Receive request 1: setTdlibParameters {
  parameters = tdlibParameters { ... }
}

[ 3][t 4][1644941119.146771907][Td29.cpp:301][#1][!Td][&td_requests]	Sending result for request 1: ok { }

[ 3][t 4][1644941119.157260417][Td9.cpp:196][#1][!Td][&td_requests]	Receive request 2: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}

[ 3][t 4][1644941119.171381235][Td29.cpp:301][#1][!Td][&td_requests]	Sending result for request 2: ok { }

[ 3][t 4][1644941119.213018655][Td9.cpp:196][#1][!Td][&td_requests]	Receive request 3: loadChats {
  chat_list = chatListMain { } limit = 100
}
```

No any other requests are initiated.

**Comment by levlam** [comment]
The only way to receive no response at all is to have no active connection to Telegram servers. That's why I asked to check wome other request like `getActiveSessions`.

**Comment by AliaksandrZhloba** [comment]
On the other hand, tdlib raises a lot of event all the time (like UpdateDiceEmojis, UpdateChatThemes, UpdateScopeNotificationSettings  and many others). Does it signalize that the connection to Telegram servers is established and OK?

**Comment by levlam** [comment]
`loadChats` must always return something if there is network access and Telegram isn't blocked. I couldn't check without the log, whether Telegram servers are reachable, so I proposed to check this by sending the request. The mentioned events tells nothing about presense of network connection.

**Comment by AliaksandrZhloba** [comment]
I updated the app, now I'm periodically making a request `getActiveSessions`. And in the tdlib's log I see
```
Receive request X: getActiveSessions
Sending result for request X: sessions {...}
```
So, I believe everything is OK with the connection.
But for `loagChats` I'm still have

`Receive request 4: loadChats {...}`

and doesn't have `Sending result for request 4`.

**Comment by levlam** [comment]
The answer is still somewhere in the log, but I can't guide you further without it.
