### ISSUE TITLE
Locked file

### ISSUE THREAD

**Issue by vgb0332** [tdlib/td#1848]
Hi. thanks for your work I love it!
I've been testing on with multiple clients simultaneously working time to time.
But there are some cases where another client is created when previous client(s) is(are) still active (not closed I guess).
Is there any way that I can get the information about the zombie client and safely close if above error happens?

**Comment by levlam** [comment]
Client instances are independent and know nothing about each other. Only your app knows, which instances are still open and needs to be closed, before they can be reopened.

**Comment by vgb0332** [comment]
First of all, thanks for a quick reply.
and Yes, I absolutely agree with you except how would an app know which clients are dead or not?
For example, let's say you create a client on normal http request procedure, and somehow the client isn't shut after the response is sent. After another request is given, the client wouldn't be recreated since the previous one is roaming around.
If this is the case, I want to safely close the zombie client, but I'm not sure if there is a method for it smt like Clinet.getClients().

**Comment by levlam** [comment]
Your backend creates clients, so only it can know, which instances are used now. The instances are independent and know nothing about each other. 

Between, TDLib instances should not be opened and closed often. This would lead to a very bad performance and can lead to exceeding of server-side flood limits. They need to be opened once and used for a long time to answer incoming requests.

**Comment by vgb0332** [comment]
Hmm thats what i guessed so as well. I know this is somewhat off rhe
purpose of this package but what if i have to work with multiple instances
and these instances are accessed only when they are needed? Specifically i
want to use them dynamically in node Express where tdl clients luve shortly
in nature. I have already implemented in node express and it is working
without any significant error so far but it would be super nice if i can
guided to use this package for my case.

2022년 2월 1일 (화) 오전 3:37, Aliaksei Levin ***@***.***>님이 작성:
