### ISSUE TITLE
Parser for documentation

### ISSUE THREAD

**Issue by isopen** [tdlib/td#185]
Leo is a code element. About the documentation.
Note how the fork is obtained in the middle of the parser.
https://github.com/isopen/tdlib/blob/master/tdspider/index.rb
Is the make-up artist okay?

**Comment by isopen** [comment]
Do you mind if this function starts in multiple threads and writes the text to different files, and then converts everything into one?

**Comment by isopen** [comment]
Leo give a signal for running the script in several threads ...

**Comment by levlam** [comment]
There is nothing wrong in parsing documentation in several threads, but if you want to parse something it's much easier to parse TDLib API scheme at https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.

**Comment by isopen** [comment]
I agree. Most likely it's easier to parse this mega thing. But it's not so much fun. With this mega thing, all mega is simple.
