### ISSUE TITLE
Can't get user by ID when there's no private chat with that user

### ISSUE THREAD

**Issue by 0x25CBFC4F** [tdlib/td#1850]
Hello. 👋 

**Before I begin I need to mention that my application does not save tdlib state (and removes td.binlog on restart) because of containerized architecture and custom backend configuration. td.binlog can't be persisted between restarts. Possible cache issue or artificial limiting?**

When I successfully authenticate first thing I do is trying to get user by ID.
In response I get this:
```
[ 3][t 5][1644017576.734203100][Td.cpp:3072][#1][!Td][&td_requests]     Receive request 5: getUser {
  user_id = <user_id_i'm_trying_to_resolve>
}
[ 3][t 5][1644017576.736390352][RequestActor.h:112][#1][!GetUserRequest]        Receive error for query: [Error : 400 : User not found]
[ 3][t 5][1644017576.736519813][Td.cpp:4266][#1][!Td][&td_requests]     Sending error for request 5: error { code = 400 message = "User not found" }
[ 3][t 0][1644017576.736596822][Client.cpp:286][&td_requests]   End to wait for updates, returning object 5 000001FBC175D410
```

I spent many hours trying to debug what's exactly wrong until I realized that my test project successfully resolves user by ID.
The only difference was that my test project was querying chat list right before doing that.

So, I obviously tried to get chat list, then query for specific user. tdlib successfully found that user.

```
[ 3][t 5][1644017799.886877059][Td.cpp:4252][#1][!Td][&td_requests]     Sending result for request 246: user {
  id = <my_user!>
  first_name = "First"
  last_name = "Last"
```

Then, I tried to query for user that I did not had a private chat with (random user from 5k+ participants chat).
tdlib returned same error "User not found"

It feels like this is artificial limiting on Telegram's side or in tdlib

Any way to get ANY user by user ID?
Obviously I can first send message to target user but that seems like a bad workaround.

Any help is appreciated!

**Comment by 0x25CBFC4F** [comment]
Found a workaround: you can resolve a user via username. I'd still like to know what's going on though.

**Comment by zelenin** [comment]
https://github.com/tdlib/td/issues/1716

**Comment by 0x25CBFC4F** [comment]
@zelenin so basically it's just a limitation with no workaround (for IDs atleast). Thank you for your quick reply! Closed.
