### ISSUE TITLE
Telegram Notification: New login

### ISSUE THREAD

**Issue by MetBorman** [tdlib/td#1851]
Hello everybody. Can someone explain the following situation:
1. Created a custom Telegram client using TDLib (1.7.9) - Python programming language.
2. After authorization, the main client receives a notification:
- Login code ....
- New login ... Device: ... Location .... etc.
3. After a certain period of time (from 1 hour to 10 hours) arrives again notification from the telegram to the main device:
- New login ... Device: ... Location .... etc.

Questions:
1. Why does the notification arrive 2 times?
2. Why at different times (from 1 hour to 10 hours) but with the same time in the message?

**Comment by levlam** [comment]
It is a bug in the client used on your main device. TDLib-based clients wouldn't show the duplicate notification.
