### ISSUE TITLE
TDLib return only one emoji for sticker

### ISSUE THREAD

**Issue by AlexMercier** [tdlib/td#1853]
TDLib return only one emoji linked for sticker. Even if sticker have two or more linked emojis.
See the screenshots.

With TDLIb You can see only 1 emoji:
![2022-02-09_145112](https://user-images.githubusercontent.com/6580198/153196034-4273465d-352f-47b3-bdd1-4415ad3f4148.png)

But in fact same sticker have 3 emoji:
![2022-02-09_145119](https://user-images.githubusercontent.com/6580198/153196164-8c9d3f9b-619c-492f-a202-82e0270501cd.png)

I'm using TDLib for Android. But I think same problem have all tdlib projects.
v 1.8.1

**Comment by levlam** [comment]
Use `getStickerEmojis` to fetch full list of emojis.
