### ISSUE TITLE
MessageContent.MessageUnsupported for all messages in a group

### ISSUE THREAD

**Issue by KomodoCrypto** [tdlib/td#1856]
I am receiving MessageContent.MessageUnsupported for all messages retrieved with the method GetChatHistory.
How can I get more information about it?
Does the admin of the group have any option to encrypt messages to get them not accessible? I can see the messages in the telegram App properly, and some of them are text and some pictures. However, all are received as unsupported content when I am trying to get them through the lib. Thanks

**Comment by KomodoCrypto** [comment]
I am using v1.7.9. There is not a new version in nugget package manager.

**Comment by levlam** [comment]
You can build TDLib yourself.

**Comment by KomodoCrypto** [comment]
I am trying to build it for .Net but I am dealing with some issues... Is there a plan to be published as a Nuget package?

**Comment by KomodoCrypto** [comment]
I already upgrade from 1.7.9 to 1.8.1. However, it doesn't workk. I am still getting TdLib.TdApi.MessageContent.MessageUnsupported for all messages in a chat.
What could be the reason? It is possible that the sender encrypts the message? Is there any other method to receive the raw data?

**Comment by KomodoCrypto** [comment]
Thanks. However, I can read messages from other chats properly but not the one that I am interested. This chat doesn't allow to copy images or text messages for example (using telegram app), that's why I am asking if the administrator has some options to encrypt the messages to prevent its access through the api or any other option. Does it?

**Comment by KomodoCrypto** [comment]
Ok, thank you for the clarification! I am building again 1.8.1 and I will test it based on the TdExample. Thank you for TDLib and huge efforts.
