### ISSUE TITLE
[Unity] Telegram.Td.dll - Assets\Example.cs(4,12): error CS0246: The type or namespace name 'Telegram' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by taeyeonlee** [tdlib/td#1857]
Hi  @levlam
When using your library (Telegram.Td.dll) in Unity (Windows OS),  it logged this error,  Any ideas ?      
When using this library (Telegram.Td.dll) in Visual Studio (Windows OS), it's working fine.    

Unity Error log : Assets\Example.cs(4,12): error CS0246: The type or namespace name 'Telegram' could not be found (are you missing a using directive or an assembly reference?)

Example.cs    (in Unity)
--------------------------------------------------------
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Td = Telegram.Td;
public class Example : MonoBehaviour
{
}
--------------------------------------------------------
Unity : https://unity.com/

**Comment by levlam** [comment]
You missing an assembly reference to Telegram.Td.dll.

See https://github.com/tdlib/td/blob/1e1ab5d1b0e4811e6d9e1584a82da08448d0cada/example/csharp/TdExample.csproj#L62 for example of referencing the dll from a csproj file. There were no way to correctly add the reference through IDE interface, so it was edited manually.

**Comment by taeyeonlee** [comment]
Thanks for the information.							
When I add the line in the file "Assembly-CSharp.csproj",  Visual Studio is working fine.							
but, Unity C# compiler (roslyn) still returns the same error.							

"Assembly-CSharp.csproj"
----------------------------------------------------------------
    <Reference Include="Telegram.Td">
      <HintPath>Assets\Plugins\Telegram.Td.dll</HintPath>
    </Reference>    
----------------------------------------------------------------

Unity C# compiler : https://docs.unity3d.com/2022.1/Documentation/Manual/CSharpCompiler.html

![image](https://user-images.githubusercontent.com/86475892/153580818-c09c11a3-20c7-49c6-abe5-d92c823eafe6.png)

![image](https://user-images.githubusercontent.com/86475892/153580922-ecfbbabd-65ca-4f4a-8667-1696e49aa3ba.png)

**Comment by levlam** [comment]
Why are you trying to import it with DllImport? Telegram.Td.dll contains managed classes and code, so it can't be imported with DllImport.

**Comment by levlam** [comment]
See https://docs.unity3d.com/Manual/UsingDLL.html.

**Comment by taeyeonlee** [comment]
Without DllImport, Unity C# compiler (roslyn) still returns the same error.

![image](https://user-images.githubusercontent.com/86475892/153707196-b8f5c68a-170e-467f-8dae-9535c4a28e8e.png)
![image](https://user-images.githubusercontent.com/86475892/153707209-6c8322ab-8813-47c5-bca5-0937024df854.png)
