### ISSUE TITLE
Incorrect chats count

### ISSUE THREAD

**Issue by AliaksandrZhloba** [tdlib/td#1860]
Hello.
I'm trying to get list of chats of the account using approach described here: [official java example](https://github.com/tdlib/td/blob/b3ab664a18f8611f4dfcd3054717504271eeaa7a/example/java/org/drinkless/tdlib/example/Example.java#L248)
Very often I'm getting incorrect total number of chats (several chats are missed).

Account has ~140 chats.
Tdlib log contains following lines:

```
[ 3][t 5][1644914324.994471549][Td.cpp:3072][#1][!Td][&td_requests]	Receive request 3: loadChats { chat_list = chatListMain {  } limit = 100 }

[ 3][t 5][1644914325.804481029][Td.cpp:4252][#1][!Td][&td_requests]	Sending result for request 3: ok {}

[ 3][t 5][1644914326.456643104][Td.cpp:3072][#1][!Td][&td_requests]	Receive request 4: loadChats { chat_list = chatListMain {  } limit = 100 }

[ 3][t 5][1644914326.648770570][Td.cpp:4252][#1][!Td][&td_requests]	Sending result for request 4: ok {}


[ 3][t 5][1644914327.048007726][Td.cpp:3072][#1][!Td][&td_requests]	Receive request 5: loadChats { chat_list = chatListMain {  } limit = 100 }

[ 3][t 5][1644914327.048026323][Td.cpp:4252][#1][!Td][&td_requests]	Sending result for request 5: null
```

Could you please say what I'm doing wrong?

**Comment by levlam** [comment]
Do you handle `updateChatLastMessage`, `updateChatPosition` and `updateChatDraftMessage` updates? 

Do you receive the correct list of chats using `getChats`?

**Comment by AliaksandrZhloba** [comment]
Yes, I do handle `updateChatLastMessage`, `updateChatPosition `and `updateChatDraftMessage `updates.

That's strange but sometimes through `updateChatLastMessage `I'm getting chat ids that are not in account's chats list (Telegram WebZ 1.32.3 shows that these channels are not in my list and offers to join them).

**Comment by levlam** [comment]
You can receive `updateChatLastMessage` in non-joined chats, in which case `update.positions` will be empty. You can receive any `updateChat*` update about non-joined chats.

**Comment by AliaksandrZhloba** [comment]
Is it OK to use `getChats`? As I remember, the example and documentation was changed to use `loadChats` approach, on different forums I saw a lot of recommendations to use `loadChats` and not to use (https://github.com/tdlib/td/issues/1789#issuecomment-991764708, https://github.com/tdlib/td/issues/1683#issuecomment-927671985).
And anyway, I'm trying to use `loadChats` because of https://github.com/tdlib/td/issues/1847.

**Comment by levlam** [comment]
It is OK to use `getChats` if you need chat list prefix in a fixed moment of time. If you are going to maintain the chat list in the correct state by updates, then you should use `loadChats`.

**Comment by AliaksandrZhloba** [comment]
> 
Hm.. Thanks for clarifying. Although it's not obvious because sometimes chat ids from my chats list also come in `updateChatLastMessage`/`UpdateChatLastMessage `events with empty `update.positions`.

Can `UpdateChatPosition` event be received with chat id not from my chats list? Will in this case `updateChatPosition.Position` be null?

**Comment by levlam** [comment]
>  Although it's not obvious because sometimes chat ids from my chats list also come in updateChatLastMessage/UpdateChatLastMessage events with empty update.positions.

This is also possible. if the chat doesn't belong to the known prefix of the chat list.

> Can UpdateChatPosition event be received with chat id not from my chats list? 

Yes, if you are leaving the chat. `updateChatPosition.position` can't be null, because you must know, from which chat list the chat is removed, but it will have `order == 0`.

**Comment by AliaksandrZhloba** [comment]
Thanks.
Knowing these nuances helped.
The issue can be closed.
