### ISSUE TITLE
Increase TDLib performance

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#1869]
Is there any way to increase `TDLib` performance? 

I'm running multiple account simultaneously and the CPU sticks at 100%

**Comment by levlam** [comment]
Have you disabled TDLib logs and redirected them to a file?

**Comment by aghasi** [comment]
> Have you disabled TDLib logs and redirected them to a file?

i have set log level to 1 which makes a few logs.( about one log per 5 minutes)

**Comment by levlam** [comment]
Then there is no more bottlenecks and performance  can't be increased further. Between, multiple accounts are run in different threads, so there should be no 100% CPU usage for a specific CPU because of that.

**Comment by aghasi** [comment]
> Then there is no more bottlenecks and performance can't be increased further. Between, multiple accounts are run in different threads, so there should be no 100% CPU usage for a specific CPU because of that.

I have one CPU core so all threads run on one core and cause 100% CPU usage.

How about `-DTD_ENABLE_LTO=ON ..` compiling option? Does it make any performance optimization?

I have two idea. Have these any effect in performance?
1. Increase optimization level of C++
2. Removing processing of some messages in `TDLib`. For example some update messages. I know that removing handler of these make `TDLib` incomplete but i don't need many updates like when someone is typing in a group.

**Comment by levlam** [comment]
> How about -DTD_ENABLE_LTO=ON .. compiling option? Does it make any performance optimization?

It should, but I didn't see any performance improvements when it is enabled.

**Comment by levlam** [comment]
> Increase optimization level of C++

If you aren't building Debug binaries, then you already use the highest optimization level.

> Removing processing of some messages in TDLib.

The changes will be neglible, There is no single place, which consumes most CPU.
