### ISSUE TITLE
Failed to receive the SMS verification code

### ISSUE THREAD

**Issue by liuxingyubm** [tdlib/td#1871]
We registered our api_id and api_hash with our phone，If you are a new user (unregistered mobile phone number), you cannot receive the SMS verification code. If it is a telegram registered user can receive a captcha. I saw on Github that someone said they could send messages to their email address. But the telegram never came back to us. We are very distressed，I beg your help

**Comment by levlam** [comment]
This is up to the server. It decides, which authentication methods are available for users.

**Comment by LvBing1990** [comment]
> 这取决于服务器。它决定哪些身份验证方法可供用户使用。

So what happens? Our new users have to register to use it, or they can't use it

**Comment by levlam** [comment]
They should be able to log in using the way specified by the server.
