### ISSUE TITLE
Can I customize messages?

### ISSUE THREAD

**Issue by LvBing1990** [tdlib/td#1873]
Can I customize messages? what should I do

**Comment by levlam** [comment]
What do you mean by "customize"? It is up to you, how messages are shown, but Telegram can transfer only predefined types of messages.

**Comment by LvBing1990** [comment]
For example, I want to add a message for a business card to my app, send a business card, and then display the business card, because I don't have that type of message in telegrams

**Comment by levlam** [comment]
You can only reuse some existing message type and customize its appearance in your app.
