### ISSUE TITLE
IOS  how to play. Oga format audio

### ISSUE THREAD

**Issue by LvBing1990** [tdlib/td#1874]
The voice of the telegram is OGA format, but I don't know how to play it successfully

**Comment by LvBing1990** [comment]
> 这是 OGG 容器中的 OPUS 编码音频。可以使用 libopus 对其进行解码。

Do you have any specific examples of how to achieve it，I searched github for libopus，But it can't be solved. Can you explain it in more detail

**Comment by levlam** [comment]
You can find an example in source code of the Telegram iOS app: https://github.com/TelegramMessenger/Telegram-iOS.
