### ISSUE TITLE
Is translate function available in json?

### ISSUE THREAD

**Issue by victorccaldas** [tdlib/td#1876]
Hi, I'd like to use this library with python through the json client you offer. But I couldn't find in json docs any reference to the language translating function. Is it accessible in json or any api, or something like that?

Doc: https://core.telegram.org/tdlib/docs/td__json__client_8h.html

**Comment by levlam** [comment]
TDLib has `translateText` method, but you need a working app to use it and even in this case it can return 404.

**Comment by victorccaldas** [comment]
Hey @levlam thanks for the response, any known reasons on why it would return 404? I plan to use it in my client app, which doesn't exist yet.

**Comment by zevlg** [comment]
> TDLib has `translateText` method, but you need a working app to use it and even in this case it can return 404.

Inside https://github.com/zevlg/telega.el app it always returns 404 for now
