### ISSUE TITLE
How do I determine whether a message is unread

### ISSUE THREAD

**Issue by LvBing1990** [tdlib/td#1878]
How do I determine whether a message is unread，can_get_viewers？But this field alone is wrong。Does it work with getmessageviewers。And this seems to apply to both fundamental groups and super groups，I don't know which one to use

**Comment by levlam** [comment]
You need to compare `Message.id` and `Chat.last_read_inbox_message_id`. All messages with identifier bigger than `Chat.last_read_inbox_message_id` are unread.

**Comment by LvBing1990** [comment]
thank you
