### ISSUE TITLE
Chatbot feature

### ISSUE THREAD

**Issue by AndrewTran2018** [tdlib/td#1879]
As I know there is something called ChatBotApi for doing it. However, I'm using tdlib. Can I implement chatbot with tdlib? @levlam

**Comment by levlam** [comment]
There is nothing like that in TDLib.

**Comment by AndrewTran2018** [comment]
> There is nothing like that in TDLib.

Thank you!
-------------------------------------
So the process is:
1. Create a new bot by interacting with BotFather
2. Get bot toke
3. Use bottoken to new botinstance and communicate with bot by sung bot api.
Is that correct? @levlam

**Comment by levlam** [comment]
Yes.

**Comment by AndrewTran2018** [comment]
Hi @levlam,
Can I automate the process calling our backend api by using a chat bot?

**Comment by AndrewTran2018** [comment]
> No.

Hmm,I find that a bot can be configured with a webhook calling our backend api to automating interaction with the bot. It looks interesting. Is that ok?  @levlam 
https://core.telegram.org/bots/webhooks

**Comment by AndrewTran2018** [comment]
@levlam The [hello bot webhook](https://core.telegram.org/bots/samples/hellobot) example here allows automated communication with the bot?

**Comment by levlam** [comment]
You can find description of what can be achieved with bots at https://core.telegram.org/bots. Then you can ask bot-related questions at https://t.me/BotTalk.
