### ISSUE TITLE
setEncyptionKey Usage

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#188]
Hello!

Usability question. Should I let choose encryption key to user or generate it randomly? 
Which path is better (or recommended)?

**Comment by isopen** [comment]
I think it's best that you do not know the encryption key yourself.

**Comment by levlam** [comment]
For maximum security, the recommended way is to store a random 256-bit key in a hardware security module, which is accessible only after user enters his password.

If hardware module isn't available or application must work without user interaction, then PBKDF2-HMAC-SHA256 of user password may be used or random key may be stored in a hardware security module and got using constant password.

If hardware module isn't available and application must work without user interaction, then it is hard to achieve security better than provided TDLib by default, so empty key may be used.

**Comment by isopen** [comment]
I fully agree with Leo. Try it. Please describe what you managed to achieve on this issue.

**Comment by blacksailer** [comment]
@levlam if I understand correctly, for custom Telegram app I should use PBKDF2-HMAC-SHA256 of password entered by user (because smartphone has no HSM)?

**Comment by levlam** [comment]
Yes. If there is no HSM, the best you can do is to use PBKDF2-HMAC-SHA256 of user password.

**Comment by isopen** [comment]
Another moment. Do not show the encryption key to anyone.

**Comment by blacksailer** [comment]
I'm sorry I'm confused.
How should I use hash exactly? I never work with user passwords before, please help.

1. I ask user to input password
2. I hash it with  PBKDF2-HMAC-SHA256 with random salt
3. That hash i use for encryption and store in file system? 

Or

1. I ask user to input password and store it as plain text
2.  I hash it with  PBKDF2-HMAC-SHA256 with public salt (That only developer knew)
3. I use that hash for encryption?

Please explain me how to use password hashing, because both scenarios not looking good IMHO.

**Comment by levlam** [comment]
1. You ask user to input password
2. You hash it with PBKDF2-HMAC-SHA256 with random salt generated on the client and stored somewhere.
3. That hash you use as encryption key.

**Comment by blacksailer** [comment]
I understand that it becoming more a disscusion, but I do not understand.

If I use hash of a password for encryption, why attacker can't copy db and hash of a password from device too? He can get data with that files, right?

I'm developing for Sailfish OS and there is no secure place to store a password. And also I can't ask user to enter pass every time, it's annoying (even TelegramX do not ask that). And I'm planning to release code to github.
So for security I have to either ask user for password either do not encrypt at all?

Sorry to bother, never worked with encryption before.

Thanks in advance.

**Comment by isopen** [comment]
If an attacker got root access to your device, then he can do anything he wants and can.

**Comment by isopen** [comment]
If hardware module isn't available and application must work without user interaction, then it is hard to achieve security better than provided TDLib by default, so empty key may be used.
c @levlam

**Comment by isopen** [comment]
Try to implement the server part too. If you really want to encrypt.

**Comment by isopen** [comment]
All the schemes for implementing this have been opened to you by cool developers from tg.

**Comment by isopen** [comment]
Regarding the function setEncyptionKey Usage. I'm sad.

**Comment by blacksailer** [comment]
@levlam thanks for answer! is it possible to reencrypt with setEncrypionKey? (of course knowing old password)

@isopen Don't be sad, be awesome instead.

**Comment by isopen** [comment]
Unfortunately, nothing is surprising...Everything is realized within the framework of a possible...

**Comment by isopen** [comment]
Maybe in the future Leo will make the method getUserPassword by user_id.

**Comment by levlam** [comment]
@blacksailer You can use setEncryptionKey any time to change database encryption key.

**Comment by yoking1341** [comment]
@levlam  PBKDF2-HMAC-SHA256 seems not workable for td_example.cpp td_api::authorizationStateWaitEncryptionKey

**Comment by levlam** [comment]
@yoking1341 What do you mean?

**Comment by yoking1341** [comment]
@levlam I run the tdlib example which is td_example.cpp, it requests me to input the encryption key.
I tried to input  PBKDF2-HMAC-SHA256 but failed to authenticate.
How can I get this encrytion key?
Thank you very much

**Comment by levlam** [comment]
Just use an empty key if you didn't set one. Or use the same key, you have entered first time.

**Comment by Mansour911** [comment]
Hi

**Comment by yoking1341** [comment]
> Just use an empty key if you didn't set one. Or use the same key, you have entered first time.

@levlam Thanks for your prompt reply.
Yes, empty key is workable.
But after I input phone number following the tips, then no response.
May I ask if tdlib has any interface which can be used to verify the phone number register the instagram or not?

Best regards

**Comment by levlam** [comment]
There is no way to verify, whether a phone number is registered in Telegram.

**Comment by yoking1341** [comment]
But why I can not pass though the td_api::authorizationStateWaitPhoneNumber verification because I can not get the response after input the phone number.

**Comment by levlam** [comment]
Likely, Telegram is blocked in your area or there are some other issues interfering with connection to Telegram servers.

**Comment by yoking1341** [comment]
Thank you very much!
