### ISSUE TITLE
Write messages to a channel as a bot

### ISSUE THREAD

**Issue by cplankl** [tdlib/td#1880]
Hello everyone,

I want to create a new channel and add a bot as an administrator and that bot should be able to send messages to that channel. I don't know if this is possible in telegram. What I have done so far is to create a new channel with
`CreateNewSupergroupChat(...)` 
and I set the channel flag to true.

I don't know if its possible for a bot to send messages to the channel or what the corret prerequisites are for this task. Does anybody have a hint?

**Comment by levlam** [comment]
Are you talking about https://core.telegram.org/bots bots?

**Comment by cplankl** [comment]
Yes I created such a bot

**Comment by levlam** [comment]
You can ask questions about bots at https://t.me/bottalk.
