### ISSUE TITLE
setOption online not working

### ISSUE THREAD

**Issue by mschadev** [tdlib/td#1883]
Library: [TdSharp](https://github.com/egramtel/tdsharp), `TDLib 1.7.9`, `tdlib.native 1.7.9.1`
```cs
_tdClient.SetOptionAsync("online", new OptionValueBoolean { Value = online }).GetAwaiter().GetResult();
```
It's not set online. What's the problem?

**Comment by levlam** [comment]
Why do you think that it doesn't work?

**Comment by mschadev** [comment]
sorry, I was mistaken.
It was set to `Privacy and Security > Last Seen`: `Nobody`.
It's working now.
