### ISSUE TITLE
How to judge the aspect ratio shown in pictures and videos

### ISSUE THREAD

**Issue by liuxingyubm** [tdlib/td#1887]
I need to specify the width and height when I send pictures or videos.But the width and height will be returned to me only after it is successfully sent,So the width and height displayed when sending is defined when sending itself. Currently, I use wide 320 and high adaptive for iOS，So I don't know if it's right, so how do you do it.

**Comment by levlam** [comment]
You need to find them from the sent file and pass to `inputMessagePhoto`/`inputMessageVideo`.
