### ISSUE TITLE
How to integrate the whole telegraph project in the app without writing each function separately?

### ISSUE THREAD

**Issue by yjsbutinghua** [tdlib/td#1888]
How to integrate the whole telegraph project in the app without writing each function separately?

**Comment by levlam** [comment]
What are you calling "telegraph project"?

**Comment by yjsbutinghua** [comment]
Integrate the whole telegram project into my own app,don't need to write it yourself

**Comment by yjsbutinghua** [comment]
> 你叫什么“电报项目”？



> Integrate the whole telegram project into my own app,don't need to write it yourself

Integrate the whole telegram project into my own app,don't need to write it yourself

**Comment by levlam** [comment]
You need to fork one of existing app for this: https://telegram.org/apps#source-code.

**Comment by yjsbutinghua** [comment]
> 您需要为此创建一个现有应用程序：[https](https://telegram.org/apps#source-code) ://telegram.org/apps#source-code 。

Directly integrate the telegram source code?

**Comment by levlam** [comment]
Use the way, suitable for your app.
