### ISSUE TITLE
Download remote file with the database file disable

### ISSUE THREAD

**Issue by ctaity** [tdlib/td#1889]
Hi, I need to know how to download a file when the file database is disabled, the documentation says: "If the file database is disabled, then the corresponding object with the file must be preloaded by the application."
How do I preload the corresponding object? I have this data: 

`RemoteFile {
  id = "AgACAgEAAx0CUgABONIAAQFgy2IxU5rfYKwuXijWGzTcrhqUkSitAALBqTEbzzjgRILyT1wXNDVPAQADAgADbQADIwQ"
  uniqueId = "AQADwakxG8844ERy"
  isUploadingActive = false
  isUploadingCompleted = true
  uploadedSize = 9040
}`

I am using tdlib through java. 

Thanks for all.

**Comment by levlam** [comment]
"the corresponding object" usually is a message, containing the file, so you need to load the message and download the file from the message.
