### ISSUE TITLE
VK uses React

### ISSUE THREAD

**Issue by isopen** [tdlib/td#189]
In particular, for them you can make a few examples of how to make a social network easier.
Using React + tdlib.
Do you like the idea?

**Comment by isopen** [comment]
I think that even you can open specialized courses for them.

**Comment by isopen** [comment]
I would not be surprised if they already use tdlib in conjunction with React.

**Comment by isopen** [comment]
Vue is steeper! https://vuejs.org
Recommend to the guys from VKontakte already today to start rewriting Vkontakte.

**Comment by isopen** [comment]
But Angular gives more than react and vue.

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/38536297-b5ca67bc-3cb2-11e8-8c8b-85f0429dd475.png)
Here, too, the race for adaptability began, but not in such a large number. The code is much cleaner.

**Comment by finethanks** [comment]
Really, I have read a monologue

**Comment by restYura** [comment]
@isopen These are good layouts. In practice, one can meet worse.
