### ISSUE TITLE
deleteMessages

### ISSUE THREAD

**Issue by yjsbutinghua** [tdlib/td#1890]
How do I know if I can delete  messages for all users?
I am group creator,but "canBeDeletedForAllUsers" int "Chat" is false.

**Comment by levlam** [comment]
You need to use `message.canBeDeletedForAllUsers` flag. It is true if and only iа the message can be deleted for all users.

**Comment by yjsbutinghua** [comment]
> 您需要使用`message.canBeDeletedForAllUsers`标志。当且仅 iа 该消息可以为所有用户删除时，这是真的。
But I delete multiple messages at once,How do I know if these messages can delete for all users?

**Comment by levlam** [comment]
You need to check the flag for all messages and act accordingly.

**Comment by yjsbutinghua** [comment]
> You need to check the flag for all messages and act accordingly.

If I choose ten messages, nine of them can be deleted for all users,one is not,then i use "DeleteMessages" ,the parameter "revoke" should be "true" or "false"?

**Comment by levlam** [comment]
If `revoke` is set to "true", but this can't be achieved for a specific message, than `revoke` is just ignored.
