### ISSUE TITLE
Q: Payments 2.0 API fully supported?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1891]
Just because we never had payments on Ubuntu Touch: Is there anything we need to know (known issues) about payments 2.0 API in tdlib? Does this need any integration with the platform API of the respective device (Android, iOS)? Or can it be self-contained, and also work on desktop etc?
Thanks!

**Comment by levlam** [comment]
TDLib has full support for Payments 2.0. Payments 2.0 are self-contained, but they require in-app browser.

**Comment by Flohack74** [comment]
Thanks, so in-app browser means the App request a URL to be opened and the browser redirects to a local listener after Auth, like OAuth 2?

**Comment by levlam** [comment]
There is no authentication involved, but app needs to receive a callback from the browser after payment data is completed.

**Comment by Flohack74** [comment]
Alright thanks!
