### ISSUE TITLE
add library libssl.so.3 android flutter project

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#1894]
I'm trying to build telegram app using flutter but I don't understand how to add ssl library to apk bundle

![Screenshot from 2022-03-21 09-03-29](https://user-images.githubusercontent.com/82513502/159196854-4338e1bf-d47b-4464-9371-08a3bc3baeef.png)

I'm trying to build telegram app using flutter but I don't understand how to add ssl library to apk bundle

![Screenshot from 2022-03-20 20-26-33](https://user-images.githubusercontent.com/82513502/159196878-85c3d1ea-5da3-4d50-b154-71863f633348.png)

libtdjson file added successfully but libssl.so.3 didn't

![Screenshot from 2022-03-20 20-29-33](https://user-images.githubusercontent.com/82513502/159196888-eb6ecb89-bb58-41be-901e-e67eb51aa299.png)

how to add libssl.so.3 to apk?

**Comment by levlam** [comment]
libssl.so can't be used without libcrypto.so.

Also, how did you build `libtdjson.so` for Android that it needs `libssl.so` at all? In build scripts from https://github.com/tdlib/td/issues/77#issuecomment-640719893 OpenSSL is linked statically, so `libssl.so` isn't needed.
