### ISSUE TITLE
Possible bug in MessageReaction.cpp

### ISSUE THREAD

**Issue by krelly** [tdlib/td#1895]
Seeing a lot of errors like this:
[ 1][t 4][1647894954.457206010][MessageReaction.cpp:327][#1][!Td]	Have no info about user 1801269513
[ 1][t 4][1647894954.457215070][MessageReaction.cpp:327][#1][!Td]	Have no info about user 1454385607
[ 1][t 4][1647894962.534953117][MessageReaction.cpp:327][#1][!Td]	Have no info about user 759722839
[ 1][t 4][1647894962.534973144][MessageReaction.cpp:327][#1][!Td]	Have no info about user 880116084

How to reproduce:
Post a message in public group using send_message message method and when other telegram user leaves a reaction to this message updateMessageUnreadReactions is not sent and also the following error can be seen in tdlib logs: 
[ 1][t 4][1647894964.927133083][MessageReaction.cpp:327][#1][!Td]	Have no info about user 1801269513
Where 1801269513 - would be the user id, who left the reaction.

**Comment by levlam** [comment]
Could you send full log with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by krelly** [comment]
This seems to happen only if the user leaving reaction is not in the group where a message is posted (can be a public group or comments to channel posts for example). Anyways I have sent a full log to a bot.

**Comment by levlam** [comment]
Thank you for the log. Can you confirm that the issue is fixed?

**Comment by krelly** [comment]
Yes, I'm not seeing this error in logs anymore, thanks @levlam (=
