### ISSUE TITLE
disableProxy not work before authorization

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#1897]
I'm using `TDLib`  1.7.11 (json version) in python. I'm using `disableProxy` after calling `td_json_client_create`. The `disableProxy` not work at all, while the document says that:

> Disables the currently enabled proxy. Can be called before authorization.

It works after authorization!!!

**Comment by levlam** [comment]
`disableProxy` definitely works before authorization. Why do you think that it doesn't work?

**Comment by levlam** [comment]
Probably, you expected it to return before `setTdlibParameters` and `checkDatabaseEncryptionKey` without actually opening any TDLib instance. There is no way it could do something reasonable before successful call to `checkDatabaseEncryptionKey`, but you definitely can call it beforehand.
