### ISSUE TITLE
Feature: AI/ML on Telegram

### ISSUE THREAD

**Issue by elimc** [tdlib/td#1898]
I'm interested in connecting NLP to Telegram. Specifically, when a scammer messages me, I want to be able to take their message and pass it to my python code to then process and spit back an AI driven reply, thereby wasting the spammers time/money.

I have seen the ability to create a bot that users can ask questions to receive a reply (similar to here: [https://github.com/ibrdrahim/telegram-auto-reply](https://github.com/ibrdrahim/telegram-auto-reply)). However, I would like to know if Telegram has an inbuilt API for me to be able to set off my python script based on my input after receiving the scam message, and then take it from there.

In other words,
1) Scammer messages me randomly and I recognize they are scammer because of their behavior (talking about mobile mining, attractive PFP, Asian phone number, etc...).
2) I type in keywords to allow AI to take over chat. For example, I type "Hello, dear". This keyword sets off my script that takes over conversation for me.
3) The scammers messages are passed to GPT2 and then GPT2 sends realistic messages back to scammer through API.
4) Scammers are essentially DDOSed by GPT2.

I feel that there are no technological blocks to the AI side. But, before I take on this task, I want to see if the existing API will work with step 2, and if not, if this is a possible feature that could be added due to the increase in crypto scams ([https://www.reddit.com/r/Scams/comments/njimju/pigbutchering_scam_sha_zhu_pan_photos_of_training/](https://www.reddit.com/r/Scams/comments/njimju/pigbutchering_scam_sha_zhu_pan_photos_of_training/))

**Comment by levlam** [comment]
Telegram has nothing like that.

**Comment by elimc** [comment]
Just to be clear, it seems like I can already write a Telegram bot connected to AI, based on the following link ([https://leihao0.github.io/How-to-auto-reply-send-msg-with-telegram/](https://leihao0.github.io/How-to-auto-reply-send-msg-with-telegram/)).

So, my thinking is that I should already be able to direct spammers to a new contact, which is my AI bot that will talk to them. So, my idea should already be doable to an extent.

The real question is if I can do this easier? Can I read information that is coming to my Telegram personal message and send it to my bot via a flag I decide on? Basically, I want the UX/UI to be very simple. Are you saying that there is no way for me to programmatically read messages from someone that is sending me messages to my regular number?

**Comment by RememberTheAir** [comment]
You can use tdlib to process every incoming message your account receives, feed them to a ML/AI algorithm that will decide what to answer, and send the reply. The docs contain more information and example

**Comment by elimc** [comment]
Thankyou @RememberTheAir I'll look into it.
