### ISSUE TITLE
Inputthumbnail

### ISSUE THREAD

**Issue by yjsbutinghua** [tdlib/td#1899]
Why do I send a video with "Inputthumbnail" set, but in the message thumbnail is empty. My thumbnail size is less than 200K and JPEG format.

**Comment by levlam** [comment]
Does thumbnail width or height exceed 320 pixels? Do you upload the file for the first time?

**Comment by yjsbutinghua** [comment]
> 缩略图宽度或高度是否超过 320 像素？您是第一次上传文件吗？

yes

**Comment by levlam** [comment]
"Yes" to what?
Is your thumbnail bigger than 320x320?

**Comment by Flohack74** [comment]
Sorry to hijack this, but while my thumbnail uploading works, the aspect ratio is changed. The thumbnail is squared. I am sending

`"{\"@type\":\"inputMessageVideo\",\"caption\":{\"@type\":\"formattedText\",\"entities\":[],\"text\":\"\"},\"thumbnail\":{\"@type\":\"inputThumbnail\",\"thumbnail\":{\"@type\":\"inputFileLocal\",\"height\":180,\"path\":\"/run/user/32011/confined/teleports.ubports/thumbnail-zvfTYq.jpg\",\"width\":320}},\"video\":{\"@type\":\"inputFileLocal\",\"path\":\"/home/phablet/.cache/teleports.ubports/teleports.ubports/HubIncoming/15/video20220413_073352930.mp4\"}}"`

So height is 180, width 320 and the file opened with an image viewer shows exactly those dimensions. Still I seem to get a 320x320 thumbnail. Any input for this? Thanks!

**Comment by levlam** [comment]
@Flohack74 What is exact size of the video?

**Comment by Flohack74** [comment]
@levlam 1280x720

**Comment by levlam** [comment]
You need to specify the dimensions in `inputMessageVideo`.

**Comment by Flohack74** [comment]
@levlam indeed seems we are missing size in both images and videos upload. I will check thiss but first tesst seems it fixes the problem :)
