### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by haecker-felix** [tdlib/td#19]
Fedora Rawhide

#...

[ 33%] Generate JSON tl source files
[ 33%] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/SqliteKeyValueAsync.cpp.o
[ 34%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/HttpOutboundConnection.cpp.o
[ 34%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/HttpQuery.cpp.o
[ 34%] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/detail/RawSqliteDb.cpp.o
[ 34%] Built target tl_generate_json
Scanning dependencies of target example
Scanning dependencies of target bench_actor
[ 35%] Linking CXX static library libtddb.a
[ 35%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/HttpReader.cpp.o
[ 35%] Building CXX object benchmark/CMakeFiles/bench_actor.dir/bench_actor.cpp.o
[ 36%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/Socks5.cpp.o
[ 36%] Building CXX object tdactor/CMakeFiles/example.dir/example/example.cpp.o
[ 36%] Linking CXX executable bench_actor
[ 37%] Linking CXX executable example
[ 37%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/SslFd.cpp.o
[ 37%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/TcpListener.cpp.o
[ 37%] Built target tddb
**/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot open output file example: Is a directory**
collect2: error: ld returned 1 exit status
make[2]: *** [tdactor/CMakeFiles/example.dir/build.make:99: tdactor/example] Error 1
make[1]: *** [CMakeFiles/Makefile2:1012: tdactor/CMakeFiles/example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object tdnet/CMakeFiles/tdnet.dir/td/net/Wget.cpp.o
Scanning dependencies of target binlog_dump
[ 38%] Linking CXX static library libtdnet.a
[ 39%] Building CXX object tddb/CMakeFiles/binlog_dump.dir/td/db/binlog/binlog_dump.cpp.o
[ 39%] Built target tdnet
[ 39%] Built target bench_actor
[ 39%] Linking CXX executable binlog_dump
[ 39%] Built target binlog_dump

**Comment by arseny30** [comment]
You probably should run cmake from a separate empty directory.

mkdir build
cd build
cmake ..
make

**Comment by haecker-felix** [comment]
Nevermind, it was a issue of my flatpak manifest. I forgot to add the `"builddir": true,` option. Thanks.
