### ISSUE TITLE
Telegram FLUD and other limitations 

### ISSUE THREAD

**Issue by OleksiyMoroz** [tdlib/td#190]
Hello! Can any help, where I can find information about limitations with sending/forwarding and other operations in Telegram API? Bot API have FAQ where I can read about this, but can't find for Telegram API the same

**Comment by levlam** [comment]
Nowhere, because they don't supposed to be exceeded by ordinary users.

**Comment by OleksiyMoroz** [comment]
@levlam What about developers who working with custom telegram client? We even don't know what issues can be?

**Comment by levlam** [comment]
There is no difference between custom and official client if the client will be used by an ordinary user. Errors handling is the same and doesn't depend on particular limits.

**Comment by OleksiyMoroz** [comment]
@Ok. Thank you

**Comment by isopen** [comment]
You can read the tdlib code.
Rejoice and enjoy.

You can read the code tdlib.
Be happy and write your client based on it.

You can first rejoice.
You can read the code tdlib.
You can second rejoice.
You can even write an application using tdlib.
At this stage you will begin to understand that you do not know how information behaves outside the framework of tdlib.
Then you start trying to find a ninja that will help you figure it out.
You will definitely find it. As a result, you will not get the help you expected.
You will start looking for the next ninja.
The result is the Preston cycle.
This is the best way.

**Comment by restYura** [comment]
@isopen I'm guessing you did not compile tdlib.

**Comment by OleksiyMoroz** [comment]
@restYura It's the test. If you can compile, you deserve to use it, if not - get out from this branch.

**Comment by OleksiyMoroz** [comment]
@restYura No. I asked a month ago, no help. Using another lib and all OK

**Comment by mkliu** [comment]
@OleksiyMoroz which lib are you using?
