### ISSUE TITLE
when i send message tip this error

### ISSUE THREAD

**Issue by lichegn** [tdlib/td#1907]
Error {
  code = 500
  message = "Request aborted"
}

what reason ?  how to search tdlib error log

**Comment by lichegn** [comment]
[ 3][t 0][1648436719.071460247][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436719.071497678][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436719.071638345][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 0][1648436721.071973562][Client.cpp:286][&td_requests]	End to wait for updates, returning object 430 0x7f70e87fd5f0
[ 3][t 0][1648436721.072012424][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436721.072036981][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436721.072201490][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t19][1648436721.572911739][ConfigManager.cpp:775][#57][!Recoverer][&config_recoverer]	Successfully connected in 352.905342
[ 3][t19][1648436721.572952747][ConfigManager.cpp:850][#57][!Recoverer][&config_recoverer]	Wakeup never
[ 3][t 0][1648436723.072474241][Client.cpp:286][&td_requests]	End to wait for updates, returning object 431 0x7f70e8666260
[ 3][t 0][1648436723.072509527][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436723.072533369][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436723.072665452][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 0][1648436725.072946071][Client.cpp:286][&td_requests]	End to wait for updates, returning object 432 0x7f70e8666260
[ 3][t 0][1648436725.072995424][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436725.073019504][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436725.073153495][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 0][1648436727.073438882][Client.cpp:286][&td_requests]	End to wait for updates, returning object 433 0x7f70e87fd5f0
[ 3][t 0][1648436727.073473453][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436727.073503732][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436727.073728084][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 0][1648436729.073944091][Client.cpp:286][&td_requests]	End to wait for updates, returning object 434 0x7f70e87fd5f0
[ 3][t 0][1648436729.073983430][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436729.074008464][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436729.074261426][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 0][1648436731.074524402][Client.cpp:286][&td_requests]	End to wait for updates, returning object 435 0x7f70e8666260
[ 3][t 0][1648436731.074564695][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436731.074588537][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436731.074758768][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000
[ 3][t 0][1648436733.075050115][Client.cpp:286][&td_requests]	End to wait for updates, returning object 436 0x7f70e8666260
[ 3][t 0][1648436733.075098752][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1648436733.075129032][Client.cpp:286][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 0][1648436733.076104640][Client.cpp:278][&td_requests]	Begin to wait for updates with timeout 100000.000000


this is console log

**Comment by levlam** [comment]
The error is returned for all pending requests whenever TDLib is closed. `sendMessage` returns response immediately, so it is very hard to receive the error for it.
