### ISSUE TITLE
td_receive no response

### ISSUE THREAD

**Issue by kikyou2022** [tdlib/td#1912]
I am using td_json !

**Comment by kikyou2022** [comment]
* send>>>11770759:{"@type":"getMe","@extra":"nnnnnn"}
* send>>>11774534:{"@type":"getMe","@extra":"nnnnnn"}
* send>>>11776000:{"@type":"getMe","@extra":"nnnnnn"}
* receive>>>11827886：

{"@type":"user","id":5013113861,"first_name":"test2022234","last_name":"","username":"

test202211","phone_number":"79111821275","status":

{"@type":"userStatusOnline","expires":1648882482},"is_contact":false,"is_mutual_contac

t":false,"is_verified":false,"is_support":false,"restriction_reason":"","is_scam":fals

e,"is_fake":false,"have_access":true,"type":

{"@type":"userTypeRegular"},"language_code":"","@extra":"nnnnnn","@client_id":1}
* receive>>>11832239：

{"@type":"user","id":5013113861,"first_name":"test2022234","last_name":"","username":"

test202211","phone_number":"79111821275","status":

{"@type":"userStatusOnline","expires":1648882482},"is_contact":false,"is_mutual_contac

t":false,"is_verified":false,"is_support":false,"restriction_reason":"","is_scam":fals

e,"is_fake":false,"have_access":true,"type":

{"@type":"userTypeRegular"},"language_code":"","@extra":"nnnnnn","@client_id":1}
* receive>>>11833050：

{"@type":"user","id":5013113861,"first_name":"test2022234","last_name":"","username":"

test202211","phone_number":"79111821275","status":

{"@type":"userStatusOnline","expires":1648882482},"is_contact":false,"is_mutual_contac

t":false,"is_verified":false,"is_support":false,"restriction_reason":"","is_scam":fals

e,"is_fake":false,"have_access":true,"type":

{"@type":"userTypeRegular"},"language_code":"","@extra":"nnnnnn","@client_id":1}



This is the test result sent to tdlib and returned, it took 57s in total

I have set the Log Verbosity Level to 0 otherwise it will take longe

Other update pushes are normal, only the response to the request initiated by the initiative will be delayed

Please tell me what might be causing this This problem has been bothering me for a long time thanks

**Comment by kikyou2022** [comment]
@levlam

**Comment by kikyou2022** [comment]
> 我正在使用 td_json ！
> 
> 账号只有几个群的时候（群里人少，没有聊天），所有函数调用都是正常的，但是如果我加入一个几千人的群，群里有很多人在聊天, tdlib 响应需要很长时间，有时几分钟，有时甚至 10 分钟，无论是什么方法，比如 getUser searchPublicChat getMe....
> 
> 网络：proxyTypeSocks5 不是代理问题，因为我在官方客户端用这个代理没有问题
> 
> 请告诉我为什么

**Comment by FunkyYang** [comment]
How fix?

**Comment by FunkyYang** [comment]
@kikyou2022
