### ISSUE TITLE
Maybe its mistype?

### ISSUE THREAD

**Issue by hndrbrm** [tdlib/td#1913]
In the transport Obfuscation.
The first 8 bytes of the random generated bytes, must not clash with HTTP and MTProto Transport Identifier.
But i read this on the code 0x02010316, which i think its not HTTP and Transport Identifier.
I think this is a mistake, is it?

https://github.com/tdlib/td/blob/461b740987101972cce65d1d5c996f455e4891ee/td/mtproto/TcpTransport.cpp#L158

**Comment by levlam** [comment]
There is no mistake. Those are first 4 bytes of any HTTPS request.

**Comment by hndrbrm** [comment]
Ah i see. Thank you for answering. I cant find any documentary about those special bytes. Hopefully this could help others with the same question.
