### ISSUE TITLE
How do I save multi-user sessions in c# projects？

### ISSUE THREAD

**Issue by yunzhiyan** [tdlib/td#1914]
I'm using c# to build a telegram. How can I save sessions with multiple accounts?

**Comment by ghmarko** [comment]
Just make a function called createtdClient to make a  client and change Database Directory with a unique name

**Comment by yunzhiyan** [comment]
Is the user's session stored in the binlog file? After I change the database directory, another folder is generated. How can I avoid it and store only session?

**Comment by levlam** [comment]
All required data for a user account is stored in its database directory, so each account must have its own database directory.
