### ISSUE TITLE
Can I resent SMS code to my phone if i missed it?

### ISSUE THREAD

**Issue by FiksUpped** [tdlib/td#1915]
Hello

In desktop or phone app is a function to resent sms code after 2 minutes to phone. I know that only way to send sms is `resendAuthenticationCode` having `authenticationCodeTypeSms` in `next_type`. Can I resent sms having `authenticationCodeTypeSms` in current `type`?

**Comment by levlam** [comment]
No. You can only use `resendAuthenticationCode` to switch to the next authentication type, provided by the server.
