### ISSUE TITLE
is there some method in tdlib that allows you to get the version\application\client name on the other side during a connet call?

### ISSUE THREAD

**Issue by tgtglove** [tdlib/td#1918]
is there some method in tdlib that allows you to get the version\application\client name on the other side during a connet call?

I need to understand somehow a call comes in to the application version 8.5.0 or 8.6.2

I need to understand what version of the application is used on the other side

I understand correctly that this is not possible?

**Comment by levlam** [comment]
It is definitely impossible to know anything about application of the other user. But you receive supported by the peer tgcalls versions in `callStateReady.protocol.versions`.
