### ISSUE TITLE
tdlib with Unity (C#)

### ISSUE THREAD

**Issue by Jeffy94** [tdlib/td#1919]
Please help me find a solution!
I need to integrate the Telegram API (tdlib) into the **Unity (C#)** application and build the **Android** application.
After installing TDLib, TDLib.Api, tdlib.native, Newtonsoft.Json from www.nuget.org application works correctly on Windows 10.
But APK on Android (IL2CPP .NET Standard 2.0) throws an error.
![image](https://user-images.githubusercontent.com/83750645/161696694-53d83939-436d-4517-b515-8316470da7b9.png)

Perhaps need to add some native Android library (for example .so) for C# applications. 
**Is it possible to use the tdlib library with Unity (C#) and build an application on Android? And how can this be done? Or can another library be used for this purpose?**

Links to used libraries:
https://www.nuget.org/packages/TDLib/
https://www.nuget.org/packages/TDLib.Api/
https://www.nuget.org/packages/tdlib.native/
https://www.nuget.org/packages/Newtonsoft.Json/
Link to instructions:
https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/unity-scripting-upgrade#add-packages-from-nuget-to-a-unity-project

**Comment by levlam** [comment]
This looks unrelated to TDLib itself. The mentioned packages aren't official and are provided by third parties.

It is strange that it tries to find .DLL instead of .SO.

Also, note that on Android names of JSON methods are prefixed with underscore in our build scripts, but this was handled automatically in some C# wrappers.

**Comment by Jeffy94** [comment]
https://www.nuget.org/packages/TDLib/
https://www.nuget.org/packages/TDLib.Api/
Are these not official packages? **Where can I download the official C# and Android previews?**

**Or what option would you recommend for integrating Tdlib into Unity (C#) for building on Android?**

**Comment by levlam** [comment]
> Are these not official packages? Where can I download the official prebuilt TDLib versions for C# and Android?

They aren't. There is no official prebuilt TDLib version, suitable for usage from C#. We only provide build instructions and build scripts for different operating systems.

**Comment by levlam** [comment]
> But for android and ios version I can't use c#?

You can. You can use https://github.com/tdlib/td/tree/master/example/ios to build TDLib for iOS. There is no up-to-date example for building TDLib for Android, but libtdjsonandroid.zip from https://github.com/tdlib/td/issues/77#issuecomment-640719893 can be used with minimal changes for this. All needed changes to the build scripts are mentioned in the issue below the comment.

**Comment by Jeffy94** [comment]
I'm trying to build a windows version using the [official instructions](https://tdlib.github.io/td/build.html?language=C%23).
But after the successful execution of the script, I get in the \td\tdlib\bin directory:
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
tdjson.dll
zlib1.dll

Where can I read the instructions for building tdlib.dll to use all this in a Unity project?

**Comment by levlam** [comment]
You need to use tdjson.dll, Other three DLLs are also needed, because they are internally used by tdjson.dll.

**Comment by Jeffy94** [comment]
Thank you! 
Can you suggest how to solve [**these** ](https://github.com/tdlib/td/issues/77#issuecomment-1091180569) errors?
