### ISSUE TITLE
Tags for smaller updates

### ISSUE THREAD

**Issue by MrTomRod** [tdlib/td#1920]
Hey!

Not sure if this is deliberate, but there are no [tags](https://github.com/tdlib/td/tags) for versions `v1.8.1` and `v1.8.2`.

Please add them, so that [automated build systems](https://src.fedoraproject.org/rpms/tdlib) can pick them up!

Best, MrTomRod

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/1790 and discussion in the mentioned related issues.
