### ISSUE TITLE
Telegram project

### ISSUE THREAD

**Issue by yjsbutinghua** [tdlib/td#1921]
My APP project needs to integrate telegram functions. Do I need to complete each function of tdlib by myself or import all functions directly? For example, I have integrated other chat projects before. I just need to import it as a module without writing each interface myself. However, at present, the telegram needs to handle each function by itself, which is too cumbersome and complex.Is there a faster and simpler way to integrate telegram?

**Comment by levlam** [comment]
When you use TDLib, you need to implement the whole interface yourself. Most of the time TDLib will tell you what and how to show, but you will still need to implement everything yourself. If you want to have a complete application with interface, you need to fork one of our existing official apps: https://telegram.org/apps#source-code.
