### ISSUE TITLE
about close() destroy()

### ISSUE THREAD

**Issue by kikyou2022** [tdlib/td#1922]
After the instance runs for a long time, the memory usage is very large。

I plan to shut down the instance regularly and restart it to release the memory

But calling close() or destroy() to return authorizationStateClosed takes a long time

The longer the instance runs, the longer the return time

Is there any way to shorten this time?

Disable the database and enable the database I tested the results are the same

**Comment by kikyou2022** [comment]
If it only runs for a few minutes  close() is executed it is fast, if it runs for an hour it takes a long time.

Or the account does not join many groups, and the running time is very long when there are few messages. It is also fast.
I am using tdjson

**Comment by levlam** [comment]
`close` needs to release all allocated memory and it could take some time if there is a lot of data allocated. If you have message database enabled, then messages are automatically unloaded 60 seconds after they are received, so close() should be relatively fast. Otherwise, it may need to unload a lot of messages and there is no way to speed up this. This shouldn't harm though, except that the instance will not be active during closing and reopening,

**Comment by kikyou2022** [comment]
> `close` needs to release all allocated memory and it could take some time if there is a lot of data allocated. If you have message database enabled, then messages are automatically unloaded 60 seconds after they are received, so close() should be relatively fast. Otherwise, it may need to unload a lot of messages and there is no way to speed up this. This shouldn't harm though, except that the instance will not be active during closing and reopening,

{
    "@type" : "setTdlibParameters",
    "parameters":{
        "database_directory": "tdlib",
        "use_message_database": true,
        "use_chat_info_database" : true,
        "use_secret_chats": true,
        "api_id": 16957848,
        "api_hash": "b82262e666f735491c13b0ddd438d0c6",
        "system_language_code": "en",
        "device_model": "Desktop",
        "application_version": "1.0",
        "enable_storage_optimizer": true
    }
}

I have enabled the database correctly, but the message doesn't seem to be unloading properly. I only have one instance running, and its memory usage reaches 500MB after running for an hour. I call close() and it returns authorizationStateClosed. It takes 10 minutes, and the memory occupied after returning authorizationStateClosed will clear.

**Comment by kikyou2022** [comment]
> `close` needs to release all allocated memory and it could take some time if there is a lot of data allocated. If you have message database enabled, then messages are automatically unloaded 60 seconds after they are received, so close() should be relatively fast. Otherwise, it may need to unload a lot of messages and there is no way to speed up this. This shouldn't harm though, except that the instance will not be active during closing and reopening,

{
    "@type" : "setTdlibParameters",
    "parameters":{
        "database_directory": "tdlib",
        "use_message_database": true,
        "use_chat_info_database" : true,
        "use_secret_chats": true,
        "api_id": *****,
        "api_hash": "b82262e666f735491c1*****",
        "system_language_code": "en",
        "device_model": "Desktop",
        "application_version": "1.0",
        "enable_storage_optimizer": true
    }
}


I have enabled the database correctly, but the message doesn't seem to be unloading properly. I only have one instance running, and its memory usage reaches 500MB after running for an hour. I call close() and it returns authorizationStateClosed. It takes 10 minutes, and the memory occupied after returning authorizationStateClosed will clear.

**Comment by levlam** [comment]
Despite possible, both numbers sounds strange to me. The user should meet a lot of other users to have so big memory usage after an hour. Also, I've seen high-loaded bots which used 50+GB of RAM and they took only about 30 seconds to close their instance, which it 2000 times relatively faster than "10 minutes for 500 MB".

Between, what is your OS and did you build TDLib in Debug or Release mode?

**Comment by kikyou2022** [comment]
> Despite possible, both numbers sounds strange to me. The user should meet a lot of other users to have so big memory usage after an hour. Also, I've seen high-loaded bots which used 50+GB of RAM and they took only about 30 seconds to close their instance, which it 2000 times relatively faster than "10 minutes for 500 MB".
> 
> Between, what is your OS and did you build TDLib in Debug or Release mode?

Yes, the user has joined a lot of groups with a lot of messages. The operating system I use is win7, and I use Release mode. The tdlib I built is 32-bit. I don't know if it has anything to do with this?

**Comment by kikyou2022** [comment]
* send:{"@type":"close","@extra":"close"}
* receive{"@type":"ok","@extra":"close","@client_id":1}
* 8784416:{"@type":"updateAuthorizationState","authorization_state":{"@type":"authorizationStateClosing"},"@client_id":1}
* 8890200:{"@type":"updateAuthorizationState","authorization_state":{"@type":"authorizationStateClosed"},"@client_id":1}

This is what I just tested, the time taken from authorizationStateClosing to authorizationStateClosed: 105784ms
It only runs for less than 2 minutes, and the memory occupies about 50MB

**Comment by levlam** [comment]
There should be no issues with performance of Release builds on Windows. Debug Windows builds can be thousands times slower on Windows though.

I can't see, how freeing 50 MB оf memory can take 105 seconds. Can you send TDLib's log with verbosity level 4 from the call to `close` up to sending of `authorizationStateClosed` to https://t.me/tdlib_bot?

**Comment by kikyou2022** [comment]
After I use setLogVerbosityLevel() to set the level to 4, the response of tdlib becomes very slow, and it takes a long time to receive a receive. When the level is set to 0, everything is normal

**Comment by kikyou2022** [comment]
> 在 Windows 上发布版本的性能应该没有问题。不过，在 Windows 上调试 Windows 版本可能会慢数千倍。
> 
> 我看不出，释放 50 MB 的内存需要 105 秒。您可以将 TDLib 的详细级别为 4 的日志从调用`close`发送到发送`authorizationStateClosed`到https://t.me/tdlib_bot吗？

I have sent a log file with log level 4 to @tdlib_bot

**Comment by levlam** [comment]
The sent log contains absolutely nothing except calls to `td_receive` with timeout 0, which just results in 100% CPU usage.

**Comment by kikyou2022** [comment]
> 发送的日志除了`td_receive`超时 0 的调用外，绝对不包含任何内容，这只会导致 100% 的 CPU 使用率。

 now back to normal. Very grateful for your help
