### ISSUE TITLE
TdLib doesn't respond after AuthorizationStateWaitPhoneNumber 

### ISSUE THREAD

**Issue by EinTheFrog** [tdlib/td#1924]
I'm trying to implement an android client using TdLib Java example. After this line of code TdLib stops responding:
`client.send(new TdApi.SetAuthenticationPhoneNumber("9996621111", null), new AuthorizationRequestHandler());`

Log file is empty.

How can I solve this problem?

**Comment by levlam** [comment]
What exactly do you mean by "not responding"? Do you receive answers for other requests if you would send them?

> Log file is empty.

Check that you specified log verbosity level at least 3. The log is expected to be empty with log verbosity level 0.

**Comment by EinTheFrog** [comment]
Changed log verbosity level. The problem was that I didn't add `android.permission.INTERNET` for my app. Closing the issue. Thank you for your answer.
