### ISSUE TITLE
[Help] Multiple questions: chat/user ids, session status etc.

### ISSUE THREAD

**Issue by livelace** [tdlib/td#1925]
Hello. I have multiple questions:

1. Are users and chats IDs mutable ? In what cases if so ?
2. How session is considered to be active ?
3. How tdlib handles connection problems ? Are there any properties like reconnection timeout, connection timeout, tries number etc. ?
4. What's the best way to export channel history (messages, files, etc) ?

**Comment by levlam** [comment]
1. This is unspecified.
2. All non-terminated sessions are "active sessions".
3. Everything just works. Apps don't need to adjust anything.
4. The best way is to use Telegram Desktop to export chat history.

**Comment by livelace** [comment]
>This is unspecified.

It looks like I already ran into this.

>All non-terminated sessions are "active sessions".

Does it mean that an "active session" has persistent connection to telegram servers ?

>Everything just works. Apps don't need to adjust anything.

Is there any method to show status of "everything just works" ?

>The best way is to use Telegram Desktop to export chat history.

It requires the desktop app installed. I rather asked about methods and structures.

**Comment by levlam** [comment]
> Does it mean that an "active session" has persistent connection to telegram servers ?

There is no notion of "active sessions" besides response of `getActiveSessions` and it returns all non-terminated sessions.

> Is there any method to show status of "everything just works" ?

There is `updateConnectionState`.

> Is there any method to show how stable (how many errors) connection to telegram servers is ?

You are very oversimplifying things. There is no such thing as connection errors, reconnect timeout, tries number. The whole logic is much more complicated.

> It requires the desktop app installed. I rather asked about methods and structures.

TDLib doesn't support chat history export.

**Comment by livelace** [comment]
>There is no notion of "active sessions" besides response of getActiveSessions and it returns all non-terminated sessions.

Ok. If I set session ttl to 366 and just listen for new messages (no sending). How soon my session will be terminated ?

>There is updateConnectionState.
Looks interesting.

>You are very oversimplifying things.
I'm trying to figure out why one of two client (the same phone number, different instances/apps) stops working after ~24 hours. And I need some tools for investigation.

>TDLib doesn't support chat history export.

Are there any plans to add this feature in near future ?

**Comment by livelace** [comment]
@levlam ping

**Comment by levlam** [comment]
> Ok. If I set session ttl to 366 and just listen for new messages (no sending). How soon my session will be terminated ?

After 366 days.

> I'm trying to figure out why one of two clients (the same phone number, different instances/apps) stops working after ~24 hours. 

If you have a lot of active sessions only limited number of them will receive updates.

> Are there any plans to add this feature in near future ?

No, unless Telegram Desktop is going to use TDLib.
