### ISSUE TITLE
Telegram x fatal error

### ISSUE THREAD

**Issue by cYoonSeeun** [tdlib/td#1927]
![Screenshot_20220412_225043](https://user-images.githubusercontent.com/103517910/163003015-0a9a5627-82db-4f61-9460-b7a23c495a70.jpg)
what should I do?

**Comment by levlam** [comment]
Does it crash all the time?

Have you tried to reboot the phone?

**Comment by cYoonSeeun** [comment]
Yes, yesterday I tried rebooting

Pada tanggal Sel, 12 Apr 2022 23.40, Aliaksei Levin <
***@***.***> menulis:

**Comment by levlam** [comment]
Is your phone Samsung A series, for example, A50?

**Comment by cYoonSeeun** [comment]
no, I'm using a vivo cellphone

Pada tanggal Rab, 13 Apr 2022 04.06, Aliaksei Levin <
***@***.***> menulis:

**Comment by levlam** [comment]
Could you change log verbosity level to ERROR and following the instructions send the log to https://t.me/tdlib_bot after app launch?

**Comment by cYoonSeeun** [comment]
thanks for the advice, have a nice day!!

Pada tanggal Rab, 13 Apr 2022 14.22, Aliaksei Levin <
***@***.***> menulis:

**Comment by levlam** [comment]
Filesystem on the phone is broken.

The file /data/data/org.thunderdog.challegram/files/tdlib32/td.binlog needs to be deleted somehow. Given the app can do nothing with the file, it may be impossible to delete the file even manually.

Anyway, you have these options:
1. Delete and reinstall the app. After this you will need to log in again to all accounts.
2. Root the phone and try to delete the file /data/data/org.thunderdog.challegram/files/tdlib32/td.binlog through a file manager. This way you will be logged out only from the affected account.

**Comment by Abvinco** [comment]
![image](https://user-images.githubusercontent.com/118875799/203479975-1c041a08-fb0a-4ddc-a481-de836fc2ecbc.jpg)
What should I do pls resolve

**Comment by levlam** [comment]
@Abvinco You have 100+ accounts and Android < 9.0. Telegram X has issues with so many accounts on the old OS, and there is no solution for now, except rooting the phone and manually delete some accounts with their directories. See https://github.com/tdlib/td/issues/902 for a little bit more details.
