### ISSUE TITLE
The reaction isn't available for the message

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#1928]
I want to submit a reaction on a post. I can do that on Telegram Desktop, while `TDLib` does not work. Here are related logs:

```
[ 3][t 4][1649854261.256315946][Td.cpp:3029][#1][!Td][&td_requests]  Receive request 12: setMessageReaction {
  chat_id = -1001599786763
  message_id = 11534336
  reaction = "👍"
  is_big = true
}
[ 3][t 4][1649854261.256380319][Td.cpp:4090][#1][!Td][&td_requests]  Sending error for request 12: error { code = 400 message = "The reaction isn't available for the message" }
```

**Comment by levlam** [comment]
You need to use `getMessageAvailableReactions` to get the list of reactions available to set for a given message. This information is updated automatically whenever user opens the chat.

**Comment by aghasi** [comment]
That works. Thank you.
