### ISSUE TITLE
New connection receives: FRESH_RESET_AUTHORISATION_FORBIDDEN

### ISSUE THREAD

**Issue by livelace** [tdlib/td#1930]
Hello. Have multiple separated (different containers) clients for single phone number.

**A** - old one.
**B** - new one.

1. **A** works as expected (login date: 2022-03-31 15:55:40).
2. **B** always receive 406 FRESH_RESET_AUTHORISATION_FORBIDDEN (the same for different hosts).

Tried to remove **B** data dir completly, but that didn't help.
I don't terminate any sessions or close client in my code.

**Comment by levlam** [comment]
This is expected error for new sessions.

**Comment by livelace** [comment]
>This is expected error for new sessions.

What does it mean specifically ? 
Why this happens ? 
Can I ignore this error ? 
Will client be Ok with that ?

```
406 FRESH_RESET_AUTHORISATION_FORBIDDEN

You can't logout other sessions if less than 24 hours have passed since you logged on the current session.
```

I'm not trying to "logout" or something. I just try to establish client connection.

BTW. I have <10 active sessions.

**Comment by levlam** [comment]
> I'm not trying to "logout" or something. I just try to establish client connection.

You are calling specific method, which returns this error.
