### ISSUE TITLE
It's been 24 hours but I still receive: Error {   code = 429   message = "Too Many Requests: retry after 3600" }

### ISSUE THREAD

**Issue by anonym24** [tdlib/td#1937]
```
Error {
  code = 429
  message = "Too Many Requests: retry after 3600"
}
```

This message is wrong. 3600 seconds has be passed a long time ago from my last request using TDLib. It's been 24 hours and I still receive this error

**Comment by levlam** [comment]
The error tells that you can try again after an hour. It doesn't promise that the request will succeed, this is up to the server.

**Comment by anonym24** [comment]
@levlam so this message is random, it's been two days.
I believe this is related to the war, to prevent spam

**Comment by levlam** [comment]
It is up to the server, which types of requests to prevent.

**Comment by pedroanhaia** [comment]
I have the same problem, my account just can call "login" and "logout".
