### ISSUE TITLE
getNearestDc on Java

### ISSUE THREAD

**Issue by cronytabed** [tdlib/td#1938]
I built tdlib Java example with clang compiler. Built client run perfectly, but I didn't find the getNearestDc method in TdApi.java. This method presence in `td/generate/scheme/telegram_api.tl`, so I added it to `td/generate/scheme/td_api.tl`. After my changes build fails with:
```
Type NearestDc has no constructors
gmake[2]: *** [td/generate/CMakeFiles/tl_generate_tlo.dir/build.make:83: td/generate/CMakeFiles/tl_generate_tlo] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:886: td/generate/CMakeFiles/tl_generate_tlo.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2
```
Apparently, I need to create a few classes to implement this method's functionality. But I don't know C++ and failed on my tries. Please, could you give me instructions on how to do it?

**Comment by levlam** [comment]
The only helpful information from `help.getNearestDc` is returned by the method `getCountryCode`.

**Comment by cronytabed** [comment]
@levlam Thank you for the response. But this method will not return the nearest DC. The library also has not implemented other methods which present in the TL schema. I know that these methods are not needed for most developers and I think is no need to add them to the official lib. I only ask how to implement them in the custom client.

**Comment by levlam** [comment]
There is no method returning "nearest DC" in TDLib, because it is absolutely useless to know "nearest DC" even in a custom client.

**Comment by levlam** [comment]
But you can add such method, following implementation of any other simple method.

**Comment by cronytabed** [comment]
@levlam Okay, you're right. I will continue to study your library at my leisure because it is a pleasure to work with it. You make a unique product, thank you for your work
