### ISSUE TITLE
TdApi.searchPublicChat() return nothing while the query contains Chinese character

### ISSUE THREAD

**Issue by qing-wang** [tdlib/td#1939]
I am using the Java version of TdApi. I try to pass Chinese query string into TdApi.searchPublicChats() but return nothing. The code works well  while the passed query string is English words. Is there any encoding issue ?

**Comment by levlam** [comment]
Description of `searchPublicChat`: "Searches a public chat by its **username**".

**Comment by qing-wang** [comment]
sorry, there is a typo in the above comment. The API I used is TdApi.searchPublicChats().

**Comment by levlam** [comment]
The search is done by prefixes of phrases without spaces. This is the same issue as in https://bugs.telegram.org/c/724.

**Comment by qing-wang** [comment]
thanks for you reply.
