### ISSUE TITLE
Stuck at cmake building on ubuntu 16.04

### ISSUE THREAD

**Issue by HellScre4m** [tdlib/td#194]
Hi
This is the problem I'm facing, running on a VPS with 1GB of ram and 1GB of swap:
![image](https://user-images.githubusercontent.com/17533431/38666899-52a8972c-3e55-11e8-81f4-387636f995ff.png)
and it sticks everytime! When I refer to `htop` I see lots of memory and virtual memory is being used by gcc (though I use `ccache`). Making seems never end, however after a long time it crashes.
![image](https://user-images.githubusercontent.com/17533431/38667180-01489d7c-3e56-11e8-9148-9965415c5ee1.png)

**Comment by levlam** [comment]
Yes, this will not be enough for gcc, but 2GB of RAM should be enough for clang.

**Comment by HellScre4m** [comment]
Thanks for your hlep, but are you sure? Because I set up building project on a Ubuntu18.04 machine with 4GBs of RAM running via HyperV (Type1 you know) on my own PC, and it's still draining all of RAM I assigned demands much more. Without making swap file available to VM it will be a nightmare and VM becomes completely unresponsive. Honestly, I think it's better you optimize cmake process, draining so much RAM is weird.

**Comment by HellScre4m** [comment]
I hotplugged more 2GB RAM and it's going a little bit smoother.
Assuming we use tdlib inside a telegram bot project which should be built in a VPS, 6GB of RAM is much expensive while when running a telegram bot is possible even with 1GB of RAM (on top of tdlib ofcourse).
It's unfair, to get a 6GB RAM VPS to only compile tdlib and then use 1~2GB of it.

**Comment by isopen** [comment]
Clang definitely will not help. Everything will hang with him.

You can automate the assembly on a computer with 8GB RAM. Then automate sending to VPS.

**Comment by restYura** [comment]
@isopen I had a 2GB RAM + Swap. The assembly was successful. Now I'm trying to assemble in RAM disk.

**Comment by UnblockerUsername** [comment]
I'm using ssd and 4gb ram

**Comment by levlam** [comment]
TDLib 1.4.0 includes a lot of compilation memory usage optimizations and a new script `SplitSource.php`, which can be used to split some source code files before building the library to reduce maximum RAM usage per file at the expense of increased build time. In our tests clang 6.0 with libc++ required less than 500 MB of RAM per file and GCC 4.9/6.3 used less than 1 GB of RAM per file.
