### ISSUE TITLE
webrtc

### ISSUE THREAD

**Issue by LvBing1990** [tdlib/td#1940]
Can webrTC in the telegram be found on Git。If I import my iOS project directly from the telegram source code,I'm going to delete a lot of files that the telegram didn't import, and change the path of each file's import header，A little bit of work。

**Comment by levlam** [comment]
Telegram apps are open source, so you can find all the code.

**Comment by LvBing1990** [comment]
> Telegram 应用程序是开源的，因此您可以找到所有代码。

I just read the telegram source code。I will telegram source weBRTC into my iOS project, or individual file error, iOS12。
<img width="560" alt="WeChatb3618388fc9efcadf1dcfe4763cef30b" src="https://user-images.githubusercontent.com/100563041/163958786-4ce46139-6c64-43a7-b89c-bb81005d2ef8.png">
<img width="1504" alt="WeChatb1c5fa2eb6f7ef53323460bbc77f8e7d" src="https://user-images.githubusercontent.com/100563041/163958809-9dfad3a4-3e4c-485a-9ff3-dfd689431625.png">
The header files are all system，
<img width="700" alt="WeChatca22c3e3ffa2f035b2ce6f640a6ea9f0" src="https://user-images.githubusercontent.com/100563041/163959085-5b8dd1bb-cc93-4dce-91ab-e6de22294608.png">
We can't even get a global search for these

**Comment by LvBing1990** [comment]
> Telegram apps are open source, so you can find all the code.
<img width="1258" alt="WeChatf63700d9b52b525422bfeeffad7e41ec" src="https://user-images.githubusercontent.com/100563041/163969877-bc3543e9-203f-4015-8166-eb7ce1c961ed.png">

I do not know why the error is reported, I are directly taken from the tetegram source code
