### ISSUE TITLE
Telegram API Terms of Service

### ISSUE THREAD

**Issue by Jeffy94** [tdlib/td#1941]
The task is to implement a mobile application using the tdlib library. The application will interact with our third party server and with the Telegram server. Authorization in Telegram and access to chats and groups will be implemented through the tdlib library. As planned, the application will send (directly or through a telegram bot) and store on our third party server data about visited chats and groups (chat ID, group ID, etc.).

**Question**: What information and how can we send and store on our third-party server without violating the Telegram security policy? If it's allowed.

**Comment by levlam** [comment]
https://core.telegram.org/api/terms#1-privacy--security:
```
1.1. Telegram is a privacy-oriented platform. All client apps must, therefore, guard their users' privacy with utmost care....```
