### ISSUE TITLE
Integration with TDLIB on backend

### ISSUE THREAD

**Issue by dhalahayeu** [tdlib/td#1942]
Hi. I've checked the https://core.telegram.org/mtproto/security_guidelines article, but for me, it's still unclear. Is it allowed according to telegram policy to integrate with a telegram via a backend service. I will try to give your more details on it to clarify the question:
1. The backend will create and store authentication keys(https://core.telegram.org/mtproto/auth_key) for multiple users.
2.  The backend will directly communicate with TDLib on behalf of multiple users. 
3. The backend will store only ids for users, chats, groups, etc. No user or chat messages will be stored.

The idea of this backend is to have one integration with TDLib instead of multiple client integrations. Could you please clarify is such flow allowed?

**Comment by IRGC** [comment]
I think everything is allowed except spam.

**Comment by IRGC** [comment]
For example artificially increasing members, views, sending unsolicited  messages.

**Comment by levlam** [comment]
TDLib isn't intended for such usage. TDLib is stateful, you can't just send arbitrary requests. If you need stateless API, then you can use https://core.telegram.org/api#telegram-api, but then there is no reason to use your own server as a proxy.

You can find general API terms of service at https://core.telegram.org/api/terms.
