### ISSUE TITLE
How does ios import telegram files

### ISSUE THREAD

**Issue by liuxingyubm** [tdlib/td#1943]
I downloaded the telegram source code using bazel to manage the project, but I didn't use it. I have to import many of the telegram modules, such as tgcalls,Tgcalls contains the webrTC source code， if I added them directly to my project, then many of the header files would have to be modified, such as
<img width="1204" alt="WeChatbcaceaf3896b2ff832ff2a368198cb44" src="https://user-images.githubusercontent.com/100563041/164405856-c7c17971-8d6d-4c37-bf99-2a175f354d11.png">
I can't change the header of every file. There are hundreds of files.
And different cable modules may have the same file, in iOS projects cannot have the same file, may cause an error。So, I was wondering what methods people use to import the code from the telegram into their own projects。I've been thinking about a lot of ideas that don't work。Hope to get help, thank you。

**Comment by levlam** [comment]
I can't help with iOS app building, But it is definitely unneeded to change app's source code to build it.

**Comment by liuxingyubm** [comment]
is there an iOS guru who can give us some feedback，I have been doing this for a few days, but I still haven't succeeded. I am very anxious

**Comment by levlam** [comment]
https://github.com/TelegramMessenger/Telegram-iOS#compilation-guide

**Comment by liuxingyubm** [comment]
> https://github.com/TelegramMessenger/Telegram-iOS#compilation-guide

You this is to obtain the source code, I have obtained, just want to import part of the source code module into my project

**Comment by liuxingyubm** [comment]
> > https://github.com/TelegramMessenger/Telegram-iOS#compilation-guide
> 
> You this is to obtain the source code, I have obtained, just want to import part of the source code module into my project，Or do I also have to use Bazel to manage my projects?

**Comment by levlam** [comment]
This is a link to complete compilation guide.
