### ISSUE TITLE
Short filename

### ISSUE THREAD

**Issue by makapoh** [tdlib/td#1944]
Why filename of uploaded files has max_length=60 in td/utils/filesystem.cpp:162 (clean_filename())?

**Comment by IRGC** [comment]
It is the server side limit.

**Comment by makapoh** [comment]
Wait... When i send file from desktop client to bot, filename not cuted, i have 63 chars in filename + '.xml'.

**Comment by makapoh** [comment]
@levlam I change max_length to 65 and now my bot send right full filename of file. Function clean_filename is realy related with filename of uploaded file. And server no limit length of filename.

**Comment by makapoh** [comment]
@levlam try it self
sample file with name R2_6827017555_032_18042022_1A984741-6C33-41FD-B10D-67DB03D8DDBF.xml: https://disk.yandex.ru/d/W8-tkc-dazd7tg

send it to @AlcoDeclarantBot, bot convert file, change R2 in filename to 08 and send it to you. Name of received file will be truncated to 60 chars, "DBF" in end of file name will be lost.

Now, send that file to @localo_botobot, bot send converted file via local telegram-bot-api and filename not truncated to 60 chars, because i change limit in clean_filename to 65.

**Comment by levlam** [comment]
Now you are talking about Bot API server and not TDLib. Bot API server truncates file name whenever an [InputFile](https://core.telegram.org/bots/api#inputfile) is uploaded and a temporary file needs to be saved locally by the Bot API server. If you would use file:// protocol in the Bot API server without patches to send the file, the file name also will not be altered by TDLib or Bot API server.

**Comment by makapoh** [comment]
Bot Api Server based on TDLib. I POST file in multipart/form-data, bot parse headers and truncate filename to 60 chars with TDLib filesystem.cpp clean_filename function. Thank for "file://", need to try it. But, i hope this problem will be solved in local server and api.telegram.org.

And i have another bug with this files, when i send file to bot, all "-" in filename replaced with "_". When bot send file back "-" not replaced to "_". Where is replacement does? On Telegram servers, on client, or in TDLib?

**Comment by levlam** [comment]
> Bot Api Server based on TDLib. 

This doesn't make file name truncation for sent files in any way related to TDLib. This is intended security behavior of Bot API server.

> And i have another bug with this files, when i send file to bot, all "-" in filename replaced with " _ ". When bot send file back "-" not replaced to " _ ".

This is also server-side behavior.
