### ISSUE TITLE
type = 'AUTH_KEY_DROP_DUPLICATE_'

### ISSUE THREAD

**Issue by babakkhan375** [tdlib/td#1947]
Hello, I have been facing this error for several days. What is the reason and what is the solution?

**Comment by babakkhan375** [comment]
Please help

**Comment by levlam** [comment]
You copied TDLib database directory and it became unusable. You must delete it, log in again and avoid TDLib database directory in the future.

**Comment by babakkhan375** [comment]
Nothing is not copied sir

**Comment by babakkhan375** [comment]
The file script is executed only once as an argv

Example :
lua5.3 script.lua 1

**Comment by babakkhan375** [comment]
> You copied TDLib database directory and it became unusable. You must delete it, log in again and avoid TDLib database directory copying in the future.

Please read my message

**Comment by levlam** [comment]
There is no way to receive this error from the server without copying TDLib's database directory. If you didn't do this manually, this was done by the hosting, you use.

**Comment by babakkhan375** [comment]
> 

So what is the solution to this problem ???

**Comment by levlam** [comment]
Find who and when copied TDLib's database directory and avoid that.

**Comment by babakkhan375** [comment]
> 
So what do I do to use multisession?

**Comment by levlam** [comment]
You must log in again if you want to use account from another place.

**Comment by levlam** [comment]
Specify different database directories for them.

**Comment by babakkhan375** [comment]
> 
Well, that's exactly what I did when I got the error

**Comment by levlam** [comment]
No. There is only one way to get the error.

**Comment by babakkhan375** [comment]
> 

What way ????

**Comment by levlam** [comment]
You copied TDLib database directory.

**Comment by babakkhan375** [comment]
> You copied TDLib database directory.


client:send({ 
["@type"] = "setTdlibParameters", 
parameters = { 
["@type"] = "setTdlibParameters", 
use_message_database = true, 
api_id = redis:get(arg[1]..'api_id'), 
api_hash = redis:get(arg[1]..'api_hash'), 
sessions_name = arg[1], 
system_language_code = "en", 
device_model = redis:get(arg[1]..'device_model'), 
system_version = redis:get(arg[1]..'system_version'), 
application_version = redis:get(arg[1]..'application_version') or '1.0', 
enable_storage_optimizer = true, 
use_pfs = true, 
database_directory = './td/'..arg[1]}})


Is this a problem?

**Comment by levlam** [comment]
A request to TDLib can't be a problem. The problem is that you interfered with TDLib database storage by copying it.

**Comment by babakkhan375** [comment]
> 

Is there a way to solve this issue ???

**Comment by levlam** [comment]
To avoid the issue, you must not copy TDLib's database directory.

**Comment by babakkhan375** [comment]
> To avoid the issue, you must not copy TDLib's database directory.

I get this error when I use a proxy
