### ISSUE TITLE
APP_PUSH_APIKEY_MISSING when trying to registerDevice

### ISSUE THREAD

**Issue by MarkArdman** [tdlib/td#1948]
I am frankly at a complete loss as to how to solve this issue, so any kind of help would be greatly appreciated. I am trying to implement push notifications on Android via Firebase Cloud messaging. I have the client set up, it does receive test messages from firebase console, but whenever I attempt to registerDevice to the tdlib, I get an error APP_PUSH_APIKEY_MISSING. I have added an API Key to my.telegram.org, but maybe it's the wrong key or something of the sort, what am I missing, thank you in advance

**Comment by levlam** [comment]
The error means that the key wasn't added. Could you recheck that you specified correct app platform and actually uploaded a key to my.telegram.prg?

**Comment by MarkArdman** [comment]
Just to be perfectly sure that I am uploading the right thing as the API key, is there any guide to show how to get it?

**Comment by MarkArdman** [comment]
Also, on my.telegram.org I am not entirely sure where can I find the specified app platform

**Comment by levlam** [comment]
There is no guide.

The app platform should have been specified when api_id was created. It can't be changed and it seems there is no way to even verify it. But given that you have an option to upload a certificate, you should have chosen Android or iOS.

**Comment by MarkArdman** [comment]
Yeah, I have chosen Android, but then, uh, is there any way to know where to get they key then??

**Comment by MarkArdman** [comment]
I believe I have just solved my issue, the problem was created by my negligence and had nothing to do with the library itself, thank you most kindly for your help, I will be closing the issue now
