### ISSUE TITLE
Decrypting push notification payload

### ISSUE THREAD

**Issue by MarkArdman** [tdlib/td#1949]
I have read the guide on https://core.telegram.org/api/push-updates, which does explain parts of it and I have seen the example implementation. But if you don't pass the optional auth_key what do you do? How do you decode the message? Is there a way to get some kind of authorization key?

**Comment by levlam** [comment]
TDLib handles push notifications itself. You need to read https://core.telegram.org/tdlib/notification-api/ for description of notification handling with TDLib.

**Comment by MarkArdman** [comment]
That's what I thought but no matter what processPushNotification will not accept the payload, it always returns an error

**Comment by MarkArdman** [comment]
Well I have figured out what the issue was with accepting the payload, now the problem is that no notification is shown

**Comment by levlam** [comment]
You will receive updateNotificationGroup if appropriate. Check that you correctly set notification-related options.
