### ISSUE TITLE
Get first message

### ISSUE THREAD

**Issue by leoMehlig** [tdlib/td#195]
Is it possible to somehow get the first ever message of a chat? 

I've tried `getChatHistory` with `lastMessageId = 0` and `getChatMessageByDate` with `date = 0`. None work. 
I saw that in the normal telegram api, `getHistory` has a dateOffset, which is used to get the first message after a certain date.

**Comment by isopen** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_message.html

**Comment by isopen** [comment]
Here everything can be. So just experiment as much as possible.
Perhaps this all again worth playing. But let's wait for the answers of professionals.

**Comment by levlam** [comment]
You should use getChatHistory with negative offset and a small from_message_id. For example, you can specify from_message_id == 9, offset = -1, limit = 2.

**Comment by leoMehlig** [comment]
@levlam Thank You. Works great!!!

**Comment by isopen** [comment]
In this case, the programmer will try from_message_id == 9, offset = -1, limit = 2. On this he will calm down. 
Leo I think it is necessary for people to experiment more.

**Comment by Mohammadwh** [comment]
hi i test it but result not first message
please help me

**Comment by levlam** [comment]
@Mohammadwh What TDLib version are you using and what exact request are you sending?
