### ISSUE TITLE
Directories are created when the flags are off

### ISSUE THREAD

**Issue by khaperets** [tdlib/td#1951]
I am calling setTdlibParameters method with parameters:
```
use_secret_chats: false
use_file_database: false
use_message_database: false
use_chat_info_database: false
enable_storage_optimizer: false
```
but directories are created even though they are not needed.
List of directories:
animations
documents
music
notification_sounds
passport
photos
profile_photos
secret
secret_thumbnails
stickers
td.binlog
temp
thumbnails
video_notes
videos
voice
wallpapers

**Comment by levlam** [comment]
Directories are needed to store downloaded files.

**Comment by khaperets** [comment]
I understand, but in the client options I specify that I will not store files and these directories are not needed.

**Comment by levlam** [comment]
No. You specified that you don't need file database, i.e. files will be redownloaded again after each app restart. Apps still need to download files regardless of whether a database is used.

**Comment by khaperets** [comment]
But I don't need the files in the app at all

**Comment by levlam** [comment]
File downlaoding is basic functionality and there is no way to disable it.

**Comment by khaperets** [comment]
Very strange. Why do I need extra directories if I don't need them?

**Comment by levlam** [comment]
The content of `database_directory` is managed by TDLib. It can store there whatever files needed for execution.

**Comment by khaperets** [comment]
I understand. Then I will fork for people

**Comment by levlam** [comment]
Completely unrelated to this issue, but file directories are created now only when the first file is downloaded to them.
