### ISSUE TITLE
Create custom handlers for reading/writing of td.binlog file

### ISSUE THREAD

**Issue by khaperets** [tdlib/td#1952]
I want to store td.binlog file data in my store (MongoDB for example).
I suggest creating custom read/write handlers for this file.
By default, the current implementation will be used.
Example: 
const char * **td_set_read_binlog_callback**  ()
void **td_set_write_binlog_callback** (const char *data)

**Comment by levlam** [comment]
It would be extremely ineffective to overwrite the file as a whole, so it is not possible to add anything like this.

**Comment by khaperets** [comment]
First of all, the file size is constantly increasing. Even when I'm doing nothing (only client initialization and authentication).
Secondly, the application needs to somehow work in the cloud, and synchronizing the file between multiple servers is no longer effective.

**Comment by khaperets** [comment]
Or is it better to fork the project and implement the necessary functions? I think a lot of people need this.

**Comment by levlam** [comment]
The file is expected to change very often, constantly increasing and reducing its size.

Also. you can't share a TDLib instance between multiple servers.

**Comment by khaperets** [comment]
I perform some action by user once per minute and close the TDLib instance. I don't need to keep it in memory all the time.

**Comment by khaperets** [comment]
I understand. Then I will fork for people
