### ISSUE TITLE
Compilation error on Linux 16.04 with GCC 6.1.0

### ISSUE THREAD

**Issue by winterNan** [tdlib/td#1953]
Hi,

    When I try to compile tdlib the following error keeps bumping:
    /td/tdnet/td/net/Socks5.h:17:27: error: use of deleted function ‘td::SocketFd::SocketFd(const td::SocketFd&)’
    using TransparentProxy::TransparentProxy;
                           ^~~~~~~~~~~~~~~~
In file included from /home/yuan/Downloads/td/td/mtproto/RawConnection.h:18:0,
                 from /home/yuan/Downloads/td/td/telegram/net/ConnectionCreator.h:18,
                 from /home/yuan/Downloads/td/td/telegram/net/ConnectionCreator.cpp:7:
/home/yuan/Downloads/td/tdutils/td/utils/port/SocketFd.h:34:3: note: declared here
   SocketFd(const SocketFd &) = delete;

Much appreciate for any hint!

**Comment by levlam** [comment]
This is a bug of GCC 6.1: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70972.

**Comment by winterNan** [comment]
Thanks. Issue solved when moved to GCC 5.8.
