### ISSUE TITLE
Detect client_id in td_set_log_message_callback

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#1954]
How can i detect the `client_id` which send the message on the callback function registered with `td_set_log_message_callback`? or is there any method to define separate callback functions for each my `TDLib` clients?

**Comment by levlam** [comment]
TDLib log is global. It isn't bound to any client.

**Comment by levlam** [comment]
> or is there any method to define separate callback functions for each my TDLib clients?

No, the log is global. 

> How can i detect the client_id which send the message on the callback function registered with td_set_log_message_callback?

There is no way generally. For example, lines logged during `td_execute` calls aren't related to any client.
But if the new JSON interface is used, then log lines may contain substring "[#<client_id>]" right after source file name, so you can actually extract the `client_id` from the log message.
