### ISSUE TITLE
how to get nearby people's username by user_id?

### ISSUE THREAD

**Issue by pppdddxxx** [tdlib/td#1957]
after i execute searchChatsNearby API， I got the nearby user's user_id , then I want to get the username of the nearby user. I execute the getChat(user_id)，I got something about the user， but there is no username in it. can you tell me how to get nearby people's username? thanks

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.

**Comment by pppdddxxx** [comment]
> See https://core.telegram.org/tdlib/getting-started.

thanks for your replay. But i still  cant't understand how to get username, can you give me an example to get username by javascript?

**Comment by levlam** [comment]
Class `user` has field `username`. The mentioned links tells, how to get `user` by its ID.

**Comment by AYMENJD** [comment]
@pppdddxxx in another way use getUser(user_id) it will return Class `user` that contains username.

**Comment by pppdddxxx** [comment]
@levlam @AYMENJD thanks, I called getUser by user_id, then I acn get the username.( I write "user_id" to "chat_id" before)
