### ISSUE TITLE
Error while reading RSA public key

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#1960]
I'm trying to build the tdlib library in node js but an error like this appears

```bash
[ 0][t 4][1651287601.773841857][PublicRsaKeyShared.cpp:26][#1][!Td][&r_rsa.is_ok()]	[Error : 0 : Error while reading RSA public key] -----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA6LszBcC1LGzyr992NzE0ieY+BSaOW622Aa9Bd4ZHLl+TuFQ4lo4g
5nKaMBwK/BIb9xUfg0Q29/2mgIR6Zr9krM7HjuIcCzFvDtr+L0GQjae9H0pRB2OO
62cECs5HKhT5DZ98K33vmWiLowc621dQuwKWSQKjWf50XYFw42h21P2KXUGyp2y/
+aEyZ+uVgLLQbRA1dEjSDZ2iGRy12Mk5gpYc397aYp438fsJoHIgJ2lgMv5h7WY9
t6N/byY9Nw9p21Og3AoXSL2q/2IJ1WRUhebgAdGVMlV1fkuOQoEzR7EdpqtQD9Cs
5+bfo3Nhmcyvk5ftB0WkJ9z6bNZ7yxrP8wIDAQAB
-----END RSA PUBLIC KEY-----
Aborted (core dumped)
```
![Screenshot from 2022-04-30 10-00-48](https://user-images.githubusercontent.com/82513502/166088086-c6a11c21-c5ed-45d3-863c-54bd9669f7ac.png)

Source code: 
[index.zip](https://github.com/tdlib/td/files/8595551/index.zip)

how to fix this? 

my pc details

- OS: Pop!_OS 22.04 LTS x86_64 
- OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
- Node-Js v16.14.2

**Comment by levlam** [comment]
OpenSSL is wrongly built. See https://github.com/tdlib/td/issues/18#issuecomment-437909398 for a possible reason for this.

**Comment by azkadev** [comment]
I forgot to update node js version haha, now it's running fine on node js 18

**Comment by levlam** [comment]
Note, that `tdweb` doesn't work in Node.js, because of https://github.com/emscripten-core/emscripten/issues/12813. But the issue has just been fixed in the main Emscripten branch, so it should work if `tdweb` is built with the latest, yet unreleased Emscripten version.
