### ISSUE TITLE
Videos uploaded via tdlib are not streamable 

### ISSUE THREAD

**Issue by whudwl** [tdlib/td#1961]
The same video when uploaded via official telegram client, is streamable. 
But when uploaded via tdlib, it's not streamable, it has to be completely downloaded before the user can start watching it.

**Comment by levlam** [comment]
What did you pass in `inputMessageVideo.supports_streaming`?

**Comment by whudwl** [comment]
> What did you pass in `inputMessageVideo.supports_streaming`?

Thank you for the info. I think that's what I'm missing.
