### ISSUE TITLE
Adding a bot to a channel via the "startchannel" parameter does not work

### ISSUE THREAD

**Issue by esindger** [tdlib/td#1962]
Hello,
Bot API 6.0 adds support for t.me links, which can be used to add bots to groups and channels as admins. I'm trying this feature, but it seems to only work for groups:
```
https://t.me/<bot_username>?startgroup=true&admin=change_info
```

When I follow a link like this:
```
https://t.me/<bot_username>?startchannel=true&admin=change_info
```

It just opens a chat with the bot. There is no channel choice dialog. I'm doing something wrong or it's a bug?

**Comment by AYMENJD** [comment]
You are doing wrong. There is no `startchannel`. Use `startgroup` it will display all chats including groups and channels.

**Comment by esindger** [comment]
No, `startgroup` displays only groups. I've tested on macOs, Desktop and iOS clients.

> There is no `startchannel`.

There is: https://github.com/tdlib/td/blob/da4282a6d94c107b3240425b4c72c877eab89b71/td/telegram/LinkManager.cpp#L930

**Comment by AYMENJD** [comment]
Not all telegram clients support `startchannel`, i have tested Android and IOS and it just open the bot chat.

Android and IOS display channels/groups using `startgroup`.

**Comment by levlam** [comment]
It works correctly in TDLib. Bugs of other clients are better to be reported at https://bugs.telegram.org.
