### ISSUE TITLE
Tdlib android images/video is not send to the super group, only text messages are send

### ISSUE THREAD

**Issue by rishabhhgupta** [tdlib/td#1963]
I create a app that send video and image to the telegram channel, but in the ResultHandler i got return of all the detail of the video and channel here is preview
`id = 13631817
      senderId = MessageSenderChat {
        chatId = -1001572460740
      }
      chatId = -1001572460740
      sendingState = MessageSendingStatePending {
      }
      schedulingState = null
      isOutgoing = true
      isPinned = false
      canBeEdited = false
      canBeForwarded = true
      canBeSaved = true
      canBeDeletedOnlyForSelf = false
      canBeDeletedForAllUsers = true
      canGetStatistics = false
      canGetMessageThread = false
      canGetViewers = false
      canGetMediaTimestampLinks = false
      hasTimestampedMedia = true
      isChannelPost = true
      containsUnreadMention = false
      date = 1651817232
      editDate = 0
      forwardInfo = null
      interactionInfo = MessageInteractionInfo {
        viewCount = 1
        forwardCount = 0
        replyInfo = null
      }
      replyInChatId = 0
      replyToMessageId = 0
      messageThreadId = 0
      ttl = 0
      ttlExpiresIn = 0.000000
      viaBotUserId = 0
      authorSignature = ""
      mediaAlbumId = 0
      restrictionReason = ""
      content = MessagePhoto {
        photo = Photo {
          hasStickers = false
          minithumbnail = null
          sizes = vector[1] {
            PhotoSize {
              type = "i"
              photo = File {
                id = 700
                size = 223850
                expectedSize = 223850
                local = LocalFile {
                  path = "/storage/emulated/0/DCIM/Screenshots/Screenshot_2022-05-05-13-38-57-027_com.instagram.android.jpg"
                  canBeDownloaded = false
                  canBeDeleted = false
                  isDownloadingActive = false
                  isDownloadingCompleted = true
                  downloadOffset = 0
                  downloadedPrefixSize = 223850
                  downloadedSize = 223850
                }
                remote = RemoteFile {
                  id = ""
                  uniqueId = ""
                  isUploadingActive = true
                  isUploadingCompleted = false
                  uploadedSize = 0
                }
              }
              width = 720
              height = 1520
              progressiveSizes = vector[0] {
              }
            }
          }
        }
        caption = FormattedText {
          text = ""
          entities = vector[0] {
          }
        }
        isSecret = false
      }
      replyMarkup = null
    }`

For the sending video i use code
`TdApi.InputFile file = new TdApi.InputFileLocal(getPathFromUri(uri));

                                TdApi.InputMessageContent messageContent = new TdApi.InputMessagePhoto(file,null,
                                        null, width[0], height[0],
                                        null,0);

                                // initialize reply markup just for testing
                                TdApi.InlineKeyboardButton[] row = {new TdApi.InlineKeyboardButton("https://telegram.org?1", new TdApi.InlineKeyboardButtonTypeUrl()), new TdApi.InlineKeyboardButton("https://telegram.org?2", new TdApi.InlineKeyboardButtonTypeUrl()), new TdApi.InlineKeyboardButton("https://telegram.org?3", new TdApi.InlineKeyboardButtonTypeUrl())};
                                TdApi.ReplyMarkup replyMarkup = new TdApi.ReplyMarkupInlineKeyboard(new TdApi.InlineKeyboardButton[][]{row, row, row});

                                client.send(new TdApi.SendMessage(Long.parseLong(snapshot.child("channelId").getValue().toString()),
                                        0, 0, null, replyMarkup, messageContent),
                                        new Client.ResultHandler() {
                                    @Override
                                    public void onResult(TdApi.Object object) throws IllegalAccessException {
                                        switch (object.getConstructor()) {
                                            case TdApi.Error.CONSTRUCTOR:
                                                System.err.println("Receive an error:" + newLine + object);

                                                break;
                                            case TdApi.Ok.CONSTRUCTOR:

                                                break;
                                            default:
                                                    Log.i("objectiss", object.toString());

                                        }
                                    }

                                });`

for the path I uses from intent as like
`/storage/emulated/0/Pictures/RepostForInsta/1651753686844.jpg`
as a string

Any help, how I able to send video and images to the telegram super group

**Comment by levlam** [comment]
Are you sure that the path is accessible? Does your app has relevant permissions? Does Scoped Storage permit the access?

**Comment by levlam** [comment]
You need to handle `updateMessageSendFailed` along with `updateMessageSendSucceeded` and `updateDeleteMessages` to corretly handle message sending.

**Comment by rishabhhgupta** [comment]
I'm able to solve the issue thank you for helping

Is their any tdlib method to filterout object as I get in ResultHandler, I know in java way, but Is their any method or class to filter particular key and value from the TdApi.Object

**Comment by levlam** [comment]
Likely, no.

**Comment by rishabhhgupta** [comment]
Ok, and after uploaded photo and images, what is the tdlib function to get their image/video by their id

**Comment by levlam** [comment]
What exactly do you want to get and for what purposes?

**Comment by rishabhhgupta** [comment]
I use firebase database to store file id's and other info

**Comment by rishabhhgupta** [comment]
do you know any method to download video in the device using their id

**Comment by levlam** [comment]
> do you know any method to download video in the device using their id

This is not really possible. Telegram files has no global ID, suitable for they downloading. But you can download a file from a message or some other place using `downloadFile` method.
