### ISSUE TITLE
Tdlib 1.7.9 output too many updates of users and chats at login

### ISSUE THREAD

**Issue by AndrewTran2018** [tdlib/td#1965]
I'm switching to 1.7.9 from 1.6.6. There is a performance penalty as the new lib outputs tons of users and chat updates at login despite any API call returns.  This behaviour is new as compared to 1.6.6. Is there any option to limit the update output to make sure the API call is returned in nature of realtime way?
@levlam 

Many thanks.

**Comment by levlam** [comment]
No, All sent updates are required and are needed for something.
