### ISSUE TITLE
ProfilePhoto. File download has failed or was canceled

### ISSUE THREAD

**Issue by EinTheFrog** [tdlib/td#1966]
I'm working on android client. I'm trying to load profile photos for chats. To do that:
1. I get file info using `TdApi.GetRemoteFile` with remote file id that I got from chat object
2. I initiate file loading using `TdApi.DownloadFile` with file id that I got from file info

After that I receive `Error 400: File download has failed or was canceled` in my default handler and `TdApi.FileUpdate` with `isDownloadingActive = false` and `isDownloadingCompleted = false` in my update handler. What can I do to fix this?

**Comment by levlam** [comment]
See `GetRemoteFile` docuemntation:
> Even the request succeeds, the file can be used only if it is still accessible to the user. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application

So, if you somehoh saved remote file ID between, instance restarts, then you must ensure that the corresponding chat is known to TDLib, i.e. received from the server after restart.

**Comment by EinTheFrog** [comment]
Okay, I removed `TdApi.GetRemoteFile`. Now I just download file using `new TdApi.DownloadFile(id, 31, 0, 0, true)` wtih local id that I got from the chat object (`chat.photo.small.id`) but result is still the same. I don't save chat objects between restarts and receive them on every app launch with `TdApi.UpdateNewChat`.

**Comment by EinTheFrog** [comment]
Ok, error has gone after app reloading. I guess `TdApi.GetRemoteFile` removal worked after all. Closing the issue. Thanks for your help.
