### ISSUE TITLE
protect_content for bots / userbot

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#1968]
on telegram bot api already supports protect_content

https://core.telegram.org/bots/api#sendmessage

why is it not in tdlib yet?

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html

**Comment by AYMENJD** [comment]
The web documentation is not up-to-date.

Use `td-api.tl` instead for up-to-date: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl

protect_content: https://github.com/tdlib/td/blob/995b06b31781065114d7ee1131991e33cd37d77b/td/generate/scheme/td_api.tl#L2050

**Comment by azkadev** [comment]
> protect_content

finally able to protect content for bots, thank you very much
