### ISSUE TITLE
webrtc  iOS

### ISSUE THREAD

**Issue by liuxingyubm** [tdlib/td#1969]
Is the webrTC version in my Telegramee-ios project too old，Import into my project various WEBRTC erro
<img width="848" alt="2AFA11D8-9CF3-45E6-8AED-1B0753520249" src="https://user-images.githubusercontent.com/100563041/167977950-a05032be-539d-47e6-af31-58dacf6e90e5.png">
r

**Comment by levlam** [comment]
We can't help with WebRTC building for iOS.
