### ISSUE TITLE
type = "API_64BIT_LOGIN_APP_OUTDATED_79"

### ISSUE THREAD

**Issue by ngockhanh14** [tdlib/td#1971]
I can login many accounts but with this account it's like this. I login on the web with this account still ok!!Hope everybody help please

2022-05-14 11:41:17.512 13981-14009/com.xosopro I/DLTD: [ 3][t 4][1652503277.512280225][Td.cpp:3614][#1][!Td][&net_query]	Receive result of [Query:[id:0][tl:0x00000000][state:Result][tl:0x78d4dec1]]
2022-05-14 11:41:17.512 13981-14009/com.xosopro I/DLTD: [ 3][t 4][1652503277.512336015][UpdatesManager.cpp:688][#1][!Td]	Apply without authorization updateShort {
      update = updateServiceNotification {
        flags = 1
        type = "API_64BIT_LOGIN_APP_OUTDATED_79"
        message = "You are using an outdated app that is no longer supported. To access your messages, please update your app to the latest version. If you don’t know how to update your app, go to https://telegram.org/dl"
        media = messageMediaEmpty {
        }
        entities = vector[2] {
          messageEntityBold {
            offset = 91
            length = 37
          }
          messageEntityUrl {
            offset = 178
            length = 23
          }
        }
      }
      date = 1652503279
    }
2022-05-14 11:41:17.512 13981-14009/com.xosopro E/DLTD: [ 1][t 4][1652503277.512420177][MessageContent.cpp:3846][#1][!Td]	Receive without authorization messageMediaEmpty {
    }

**Comment by levlam** [comment]
"You are using an outdated app that is no longer supported. To access your messages, please update your app to the latest version."

**Comment by ngockhanh14** [comment]
update app Tele ? or tdlib ?

**Comment by levlam** [comment]
You need to use the latest TDLib.

**Comment by abdullah5514** [comment]
latest TDLib has some separate issues related to setTdLibParameters. It doesn't update the params. For that, I have to downgrade it. But after downgrading getting this error.

**Comment by levlam** [comment]
@abdullah5514 You need an updated wrapper, which supports the latest TDLib then.

**Comment by levlam** [comment]
TDLib provides a simple C interface: https://github.com/tdlib/td#using-json. Wrappers for specific languages are mostly third-party and some of them must be updated to support specific TDLib versions.

**Comment by levlam** [comment]
The gem was released in 2021 and isn't compatible with the latest TDLib 1.8.13 from master. To use it you need to modify source code of the gem at https://github.com/southbridgeio/tdlib-ruby. or write a simple wrapper yourselves.

**Comment by tilvin** [comment]
> @levlam thanks for replying. I am using tdlib-ruby 3.0.2 which is the latest version. And I used tdlib 1.8.0 which is the latest one. But with these versions, I was getting the tdlibParameters issue. They were not set properly. For that reason, I just downgraded the tdlib version to 1.7.0 which resolves my issue. But when I get the OTP code and enter it I am getting the issue which @ngockhanh14 mentioned.

Pretty late, but you can use [my experience](https://github.com/southbridgeio/tdlib-ruby/issues/63#issuecomment-2210922485) if it's still on agenda.
