### ISSUE TITLE
pkg-config files are broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [tdlib/td#1974]
As per title: `CMake/GeneratePkgConfig.cmake` has
```
  file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/${TARGET}.pc" CONTENT
"[...]
CFlags: -I\"\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}\"
Libs: -L\"\${prefix}/${CMAKE_INSTALL_LIBDIR}\" -l${TARGET}
[...]")
```
and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by levlam** [comment]
Do you manually set `CMAKE_INSTALL_{INCLUDE,LIB,BIN}DIR` during CMake configure step in the standard way for NixOS? Can you then achieve desired outcome by specifying also `CMAKE_INSTALL_PREFIX=/`?

**Comment by levlam** [comment]
TDLib supports a lot of operating systems, and not all of them use GNU rules. Therefore we intentionally don't use `GNUInstallDirs` module and allow to specify all install directories in the way specific to the host OS. If all directories are manually specified with absolute paths, I see no reasons to set a non-empty `CMAKE_INSTALL_PREFIX` and setting it to empty should lead to correct `pkgconfig` files already.

Even [GNU coding standard](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html), mentioned as reference throughout https://cmake.org/cmake/help/v3.24/module/GNUInstallDirs.html#special-cases, states that "All the other installation directories should be subdirectories of one of these two" (`prefix` and `exec_prefix`) and "write it as $(prefix)/include".

But it is true that `install` command in CMake has special handling of absolute paths, for which `CMAKE_INSTALL_PREFIX` is completely ignored. The same logic should be used in the generated `pkgconfig` files, despite it contradicts the GNU coding standard.
