### ISSUE TITLE
`searchSupergroupMembers` and `searchChatMembers` can't find one user

### ISSUE THREAD

**Issue by sshilovsky** [tdlib/td#1975]
I'm trying to search for a user by their first name in a supergroup. Users in this supergroup all have empty last name, and their first names consist of three words each.

Normally, both `searchSupergroupMembers` and `searchChatMembers` work just fine, but there is this one user that can't be found this way. Say, their first name is "alpha beta gamma". It CAN be found with query "beta", or "gamma", but NOT with "alpha", neither with any prefix of "alpha" ("a", "al", "alp", "alph").

This user can be found in contacts list though with query "alpha". Other users in this supergroup don't have such problem. I've double-checked that the queries are correct.

Any hints?

**Comment by sshilovsky** [comment]
@levlam Yes, both for the problematic user, and the other users, which don't have this problem.

**Comment by levlam** [comment]
Search in supergroups doesn't take in account the name given by you for the user. Users can be found only by the name they specified themselves.
