### ISSUE TITLE
Feature Request: allow choosing the network interface to use

### ISSUE THREAD

**Issue by NotesOfReality** [tdlib/td#1977]
Would you please implement the code needed for an option to choose which network interface a td-based telegram client should "listen on"?

I'm a windows user and unfortunately I have to keep my VPN connection active and its split-tunnelling driver fails so hard at *not* routing any td-based telegram client by its net. interf. and all my tries to manually bind any of them to my main ("non-VPN") net. interf. failed too.
I have no experience with proxy and IPv6, if anyone could suggest me a workaround which leverages either or both of these two techs, please let me know.

Just in case anyone's curious about a GUI implementation, my humble concept is a list drop-down menu with all the available net. interf. , just like [QBitTorrent](https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent#qbittorrentspecific-configuration) (maybe [this](https://github.com/qbittorrent/qBittorrent/blob/78eaa49cd6b3b59c064cd461fe6d30eceaeac770/src/gui/advancedsettings.cpp#L68) could be a useful "start"?).
![image](https://user-images.githubusercontent.com/11523796/153656277-c6b1eeb2-a191-4b0a-9d4e-b4607d82d0c3.png)

Thanks in advance to whoever tries to help me in any way, shape or form.

**Comment by levlam** [comment]
Telegram is a messenger and not a Torrent app. The proposed feature is not messenger-related and isn't suitable even for adding to something like Advanced settings.

In your case, you can set up a Socks5 proxy on a local port and enable it in app settings.
