### ISSUE TITLE
Problem formatting text in Persian in html format to send a text message

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#1978]
Hello

I want to send a Persian text with html markup via tdlib 1.8.0, but unfortunately, like the image above, the text is not formatted properly.
I tried an English text with the same style and it was correct.

I do not know why the text is not formatted correctly with Persian letters.

Does anyone know what the problem is and how to solve it?

[Pic problem](https://s6.uupload.ir/files/index_3knb.jpg)

**Comment by levlam** [comment]
The text is sent correctly. The issues is in the app, which shows it incorrectly.
