### ISSUE TITLE
how to get message ASAP from supergroup?

### ISSUE THREAD

**Issue by gorefieend** [tdlib/td#1979]
when there is a supergroup, we all know that all messages go through the owner's DC. so for example: if owner is from Vietnam and he has a supergroup, all channel messages will be sent to Singapore Telegram DC and from there to channel subscribers...
...I know Telegram wasn't built to recieve low latency messages, but what is the fastest way to recieve message from that channel? (method)

1. location -> placing server into Singapore (done)
2. chosing the right method -> what is the fastest method possible? server push? long polling?.. or listener having combination of both? 
thanks a lot :)

**Comment by AYMENJD** [comment]
- Have the nearest server to the chosen Telegram DC.
- Connect to Telegram using an account that placed on the same chosen DC.

> This can improve connection latency.

I recommend to listen to the server push instead of looping a Telegram method that can easily lead to 429th errors.

**Comment by gorefieend** [comment]
i aleady have server in SG and account which is connected has also the same DC :) but what else can i do?

**Comment by gorefieend** [comment]
i mean... i am recieving messages quite fast, but some other accounts are recieving it sooner? what is the reason? it is just coincidence? (faster by xx miliseconds, but it is still faster😀)

**Comment by AYMENJD** [comment]
>  what is the reason? it is just coincidence? (faster by xx miliseconds, but it is still faster😀)

This is up to the telegram server. And maybe your program.
If it is already fast that means no problem.

**Comment by gorefieend** [comment]
i don't think it is up to my program. for example, there are 2 apps which both listen to telegram channel. both apps have telegram account with same datacenter connected, same CPU/specs, same provider and same location of the server


how can one app be constantly faster in recieving messages if both use server push?

**Comment by AYMENJD** [comment]
How this can be issue? if `xx` milliseconds faster it's normal.

**Comment by gorefieend** [comment]
okay, let's say it like this:


there is 100 random user-bots using server push and listening to the same channel

how can my user-bot using server push recieve the message faster than them? just by adding more tg accounts in?

**Comment by AYMENJD** [comment]
See: #1668.

**Comment by gorefieend** [comment]
i found out that server push is faster when client is also using polling. the lower polling interval is, server push is also faster.

am i able to use long-polling as an user? without getting banned😄so polling with interval 0ms
