### ISSUE TITLE
When I use tdlib,call the api  that download the file,the returned file is not downloaded.

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#198]
When I use tdlib，call the api  that download the file，like this;

```
TdApi.DownloadFile downloadFile = new TdApi.DownloadFile(file.id, 1);
Client.send(downloadFile,new new Client.ResultHandler() {
                @Override
                public void onResult(final TdApi.Object object) {
                            if (object instanceof File) {
                                File file = (File) object;
                                if (fileId == file.id) {
                                    Bitmap bitmap = ImageUtils.decodeScaleImage(file.local.path, Constants.screenWidth, Constants.screenHeight);
                                    if (bitmap != null) {
                                        image.setImageBitmap(bitmap);
                                        EaseImageCache.getInstance().put(file.local.path, bitmap);
                                    } else {
                                        image.setImageResource(R.drawable.ease_default_image);
                                    }
                                }
                            }
                        }
                }
            });

```
The moment the code is called, the file is returned immediately, 
but the returned file is not downloaded. like this：

```
    [ 3][t 4][1523697175.945602179][Td.cpp:4642][!Td][&td_requests]	Sending result for request 150: File {
      id = 104
      size = 120644
      expectedSize = 120644
      local = LocalFile {
        path = ""
        canBeDownloaded = true
        canBeDeleted = false
        isDownloadingActive = true
        isDownloadingCompleted = false
        downloadedPrefixSize = 0
        downloadedSize = 0
      }
      remote = RemoteFile {
        id = "AgADBQAD_6cxG9hoWFbNvrl1hz0jQUhc0zIABFDY4wYFsFFxT8cDAAEC"
        isUploadingActive = false
        isUploadingCompleted = true
        uploadedSize = 120644
      }
    }

```
 At this time, the file is still downloading, but you have returned the file.

**Comment by levlam** [comment]
Yes, exactly this behavior is described in a description of the method: "Asynchronously downloads a file from the cloud. updateFile will be used to notify about the download progress and successful completion of the download. Returns file state just after the download has been started". So, you need to handle UpdateFile to found when a file downloading is completed, or when a downloading has failed and isn't active anymore.

**Comment by isopen** [comment]
There is still a moment when the file is in the process of downloading. Still there is a state when the downloading is hanging.

**Comment by liaoyu1992** [comment]
OK, I saw the updatefile callback, but it's unreasonable to just return the undownloaded file.

**Comment by isopen** [comment]
1. There was a rewrite of the functional and maybe it was left from the old mechanism
2. Perhaps this is necessary somewhere

**Comment by restYura** [comment]
@isopen It seems to me that the third point will work.

**Comment by Dhina17** [comment]
> Yes, exactly this behavior is described in a description of the method: "Asynchronously downloads a file from the cloud. updateFile will be used to notify about the download progress and successful completion of the download. Returns file state just after the download has been started". So, you need to handle UpdateFile to found when a file downloading is completed, or when a downloading has failed and isn't active anymore.

I can't understand. Code snippet to handle asynchorous downloads plz. I used UpdateFile in the result handler of DownloadFile. But it runs only once after the download has been started. Then I didn't receive any updates further.

**Comment by levlam** [comment]
@Dhina17 `downloadFile` returns `file`. `updateFile` are sent independently as updates all the time. They must be handled by update handler and not `downloadFile` result handler.

If you don't care about download progress and other file state changes, you can pass `synchronous` == true parameter to `downloadFile` request.

**Comment by Dhina17** [comment]
> @Dhina17 `downloadFile` returns `file`. `updateFile` are sent independently as updates all the time. They must be handled by update handler and not `downloadFile` result handler.
> 
> If you don't care about download progress and other file state changes, you can pass `synchronous` == true parameter to `downloadFile` request.

I need to care about progress. Can you give some examples how to handle file state changes?

**Comment by levlam** [comment]
@Dhina17 https://github.com/tdlib/telegram-bot-api/blob/e2ae8dad02a7c0046e162e12bc0c0c077fff5d14/telegram-bot-api/Client.cpp#L3927

**Comment by Dhina17** [comment]
> @Dhina17 https://github.com/tdlib/telegram-bot-api/blob/e2ae8dad02a7c0046e162e12bc0c0c077fff5d14/telegram-bot-api/Client.cpp#L3927

Thank you
