### ISSUE TITLE
textEntityTypeMentionName not always works

### ISSUE THREAD

**Issue by mdsina** [tdlib/td#1981]
Hi there.

I have problem with `textEntityTypeMentionName`.

For example I have message like

```
[user=1420XXXXXX]

...
```

And send that message with `textEntity`, that have type `textEntityTypeMentionName`. 
But user highlighting not always works, when I browse messages. Mentions like that not always clickable. The offset and length for `textEntity` are correct.
What wrong with that?
Thanks.

**Comment by levlam** [comment]
You can't mention a user, if the user isn't a member of the chat and restricted its mentions with privacy settings.

**Comment by mdsina** [comment]
Ok. Thanks
