### ISSUE TITLE
long polling

### ISSUE THREAD

**Issue by gorefieend** [tdlib/td#1982]
we have a javascript telegram user-bot (listener) and use polling.. if i set poll interval to 0ms, will it behave like long polling? is it possible to do long polling as an user?

**Comment by gorefieend** [comment]
every time when i try to set "poll interval = 0", it automatically sets to "100". How can i achieve long polling? Thanks

**Comment by levlam** [comment]
There is no such thing as "long polling" in Telegram or TDLib.

**Comment by gorefieend** [comment]
then what is the lowest possible interval for polling?

**Comment by levlam** [comment]
There is no such thing as "polling".
