### ISSUE TITLE
Telegram x external error 

### ISSUE THREAD

**Issue by cYoonSeeun** [tdlib/td#1987]
what should I do?

![Screenshot_20220526_005111](https://user-images.githubusercontent.com/103517910/170331041-d6358445-3fc6-4f2e-bc71-705155e6b3e6.jpg)

**Comment by levlam** [comment]
"Device error" means that there are issues with the device hardware, which can't be avoided. All suggested ways to resolve the issue are shown on the screen.

**Comment by cYoonSeeun** [comment]
I've pressed "launch app" but it's still like that, so which one should I
press?

Pada tanggal Kam, 26 Mei 2022 01.00, Aliaksei Levin <
***@***.***> menulis:

**Comment by levlam** [comment]
See "follow these steps" part.

**Comment by samnooij** [comment]
I have the same issue since today. I have > 5GB space left, no SD card and I have rebooted my phone twice. The error persists. Also, other apps work fine. What can we do now? Wait for an update? Reinstall the app?

**Comment by levlam** [comment]
@samnooij Only app reinstall can help. But given that this is a hardware error, it is likely to return after some time.

**Comment by samnooij** [comment]
@levlam Thanks! I uninstalled the app and installed it again and now it works.  :) Let's hope it stays working. I don't think I can fix a hardware problem...
