### ISSUE TITLE
How to cook fried chicken using tdlib?

### ISSUE THREAD

**Issue by isopen** [tdlib/td#199]
1. You can choose the right meat in the store
2. Take the 24 cores computer with 64GB RAM
3. Put the meat in the computer block. Run the tdlib assembly on all cores with ninja

The most important: **Do not repeat at home**

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/38776048-da86c3a0-40ba-11e8-9aae-583c177c3ea3.png)

**Comment by restYura** [comment]
@isopen I tried to assemble a library. Everything turned out the first time.
I try in the language "Go

**Comment by TheNando** [comment]
What was the solution here? I'm currently having the same problem.

**Comment by klamping** [comment]
hmmm, i can't seem to get this to work with brisket. any luck?

**Comment by TheNando** [comment]
Same. No luck with brisket or skirt steak. I think it may only be for chicken, or perhaps poultry in general. I've had minimal success with corned beef. Maybe if you also corn the poultry?

**Comment by klamping** [comment]
how are you seasoning your meats and how long are you letting them marinate?

and no, I wouldn't suggest corning the poultry. the skin gets all shriveled like old man's balls.

**Comment by klamping** [comment]
Any luck? This is preventing my production-ready project from launching.

**Comment by TheNando** [comment]
No luck. My team ended up just going to KFC. Eat Fresh.
