### ISSUE TITLE
Group send failed

### ISSUE THREAD

**Issue by renyhp** [tdlib/td#1990]
I am getting this cryptic error while trying to send two media groups one after the other. However, if I just wait few seconds and retry, after a couple times I get an actual `RetryAfter` error, so I comply, wait for the given amount of time, then retry again, and I manage to send the media group with no problem.

Lines 25915-25924 in `MessagesManager.cpp` look suspicious to me:
```cpp
  if (!success) {
    if (default_status.is_ok()) {
      default_status = Status::Error(400, "Group send failed");
    }
    for (size_t i = 0; i < random_ids.size(); i++) {
      if (random_ids[i] != 0) {
        on_send_message_fail(random_ids[i],
                             request.results[i].is_error() ? std::move(request.results[i]) : default_status.clone());
      }
    }
    pending_message_group_sends_.erase(it);
    return;
  }
```

It looks like it's sending an error related to the first result that has a `random_id`, independently of whether it's actually the one that was in error.

Maybe this should be something like the following? (please don't take this as some kind of PR, I'm not familiar enough with this code and I haven't tested it, but it's just to show the working of how I suspect this is intended to be.)

```cpp
  if (!success) {
    if (default_status.is_ok()) {
      default_status = Status::Error(400, "Group send failed");
    }
    auto random_id = random_ids[0];
    for (size_t i = 0; i < random_ids.size(); i++) {
      if (random_ids[i] != 0) {
        random_id = random_ids[i];
        if (requests.results[i].is_error()) {
          default_status = std::move(request.results[i]));
          break;
        }
      }
    }
    on_send_message_fail(random_id, default_status);
    pending_message_group_sends_.erase(it);
    return;
  }
```

**Comment by levlam** [comment]
> It looks like it's sending an error related to the first result that has a random_id, independently of whether it's actually the one that was in error.

All non-deleted messages has `random_id != 0`. If one message from a message group is failed to be uploaded, the whole message group can't be sent. Therefore, sending of all messages in the group must be canceled. If uploading of a message resulted in an error, the error will be used to cancel message sending and returned in `updateMessageSendFailed`. Otherwise, sending is canceled with a generic error "Group send failed".

After your change, `updateMessageSendFailed` would be send only for one message, despite sending of all other messages also failed.

**Comment by renyhp** [comment]
I see. But still, the HTTP response must be just one. Does it make sense that this response is "Group send failed", which says that there is at least one message that triggered the error, but no info about which and why is returned? I understand that information about a single message is not complete information about the whole group, but it's still *some* information.

**Comment by levlam** [comment]
If you are talking about Bot API response, then it can be made less generic in case the failure was caused by second or subsequent media. This will be improved in the next Bot API update.

**Comment by renyhp** [comment]
Yes, perfect, thank you very much!
