### ISSUE TITLE
.webp images not supported in Image preview for ogImageUrl on Android

### ISSUE THREAD

**Issue by varun0922** [tdlib/td#1991]
![image](https://user-images.githubusercontent.com/45751168/171149152-ed480656-685a-4925-a656-088ee4df2f67.png)

Hey guys I am trying to share content on telegram but when I use a .webp image in an ogImage URL, the image is not shown in the preview window. But if I use .png image in the ogImage url then the image is loaded in the preview view. 
Does Telegram not support the preview for .webp images.

As you can see in the attached image. 

URL with .webp ogImage
https://tokopedia.link/DVuRFsnvtqb

URL with .png/.jpg ogImage
https://tokopedia.link/enRFllAvtqb

**Comment by levlam** [comment]
This is likely to happen, because .WEBP files are stickers for Telegram and not images. Anyway, the behavior is server-side and isn't related to TDLib. You can add a suggestion to change the behavior at https://suggestions.telegram.org/.
