### ISSUE TITLE
Compiling with Android Studio

### ISSUE THREAD

**Issue by BlackMesa123** [tdlib/td#1992]
Hello there,
I'm testing this lib in an Android app and I was wondering if is there a way to avoid using prebuilt binaries and instead include and compile the library directly in the app project. I managed to compile the lib myself but I can't find a way to integrate the tdlib source code in the project, I'm always ending up with "*.h file not found" errors due to missing pregenerated source files which I can create when compiling the lib manually

**Comment by levlam** [comment]
It is definitely possible to build native libraries along with Android app. See https://developer.android.com/studio/projects/add-native-code for examples of how this can be done. You will need a simple CMakeLists.txt file and a JNI-wrapper for TDLib, which you can find at https://github.com/tdlib/td/issues/77#issuecomment-640719893.
