### ISSUE TITLE
`getChat` timeouting most of the times

### ISSUE THREAD

**Issue by brauliobo** [tdlib/td#1994]
```ruby
> Bot.td.get_chat(chat_id: ENV['REPORT_CHAT_ID'].to_i).value
TD::Error: Timeout error
from /home/braulio/.rvm/gems/ruby-2.7.5/bundler/gems/tdlib-ruby-9bf89f60737b/lib/tdlib/client.rb:88:in `block (2 levels) in broadcast'
```

Other calls I've tried work, only this one is timeouting. The library is set with a timeout of 1 minutes. It worked once, now it is back to a timeout
I need this endpoint to get the supergroup_id

**Comment by levlam** [comment]
TDLib has no timeouts for requests, so this is something unrelated. You can enable TDLib log to see, what exactly is going on the library side.
