### ISSUE TITLE
Newer jni wrapper

### ISSUE THREAD

**Issue by BlackMesa123** [tdlib/td#1995]
Would it be possible to have a copy (or an update in the repo) of the newer td_jni.cpp? I've noticed that both the [TGX](https://github.com/TGX-Android/tdlib) and the [prebuild](https://core.telegram.org/tdlib/tdlib.zip) version of tdlib for Android have a different jni wrapper than the one currently in the repo (both [here](https://github.com/tdlib/td/blob/master/example/java/td_jni.cpp) and [here](https://github.com/tdlib/td/issues/77#issuecomment-640719893)).

**Comment by levlam** [comment]
Prebuilt Android library have an old version of td_jni.cpp, which is kept unchanged for compatibility with Telegram X. It will be updated to a new version someday.
