### ISSUE TITLE
How do I get a complete list of chat messages in C#?

### ISSUE THREAD

**Issue by Aleksey250251** [tdlib/td#1997]
I get 20, then 51 messages, then 100 messages(maximum). I realized that the id of the first message received is indicated, but how can I find out the exact number of chat messages in order to get all the messages in parts?

**Comment by Aleksey250251** [comment]
How can I receive messages?

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-chat-messages.
