### ISSUE TITLE
Display list of channels and groups (java)

### ISSUE THREAD

**Issue by Jeffy94** [tdlib/td#1998]
After executing the Client.create method, I am waiting for the UpdateBasicGroup event. I cache the received group IDs in the list of groups.

**How to correctly display a list of Groups and Channels with names and so on?
should i use UpdateBasicGroup and call getBasicGroupFullInfo for each group? Or Use TdApi.Chat list and filter by ChatType?**

Please help me find the right way

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started describes all that.
