### ISSUE TITLE
Telegram Oauth & TDLib

### ISSUE THREAD

**Issue by MaxMyalkin** [tdlib/td#1999]
Hi.
I am trying to use telegram oauth in our service with tdlib on client.  

I checked telegram login widget but it has no required feature:
after oauth login I should use client tdlib features without auth repeat on client

Expected flow:
1. User opens oauth webpage
2. User success login
3. Webpage uses tdlib and gets info about user 
4. After successful login server sends to client telegram token or something else.
5. Client passes the token to tdlib on its side. 
6. Client uses default tdlib interface

I plan to change tdlib implementation to support this behavior.
But there are some difficulties:
- several dc. token is linked to dc. 
- token has binary format
- there are many settings besides token that could potentially affect auth.
- there is no simple way to set token from authmanager. token is set inside session code.

Can I support the expected flow without complex tdlib changes? Is my flow realizable? Or are there any alternatives?

**Comment by levlam** [comment]
Telegram is not a web service and doesn't have OAuth. You can do nothing on behalf of the user, and there is no "token", which would allow this. Telegram Login Widget only allows to receive basic information about a Telegram user.
