### ISSUE TITLE
error in cmake -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake ..

### ISSUE THREAD

**Issue by aliakbarhamzeh1378** [tdlib/td#20]
hi . i have error in this line 

`cmake -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake ..`

and my error detail is

```
Done Building Project "C:\Users\Aliakbar\Desktop\td-master\td-master\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\Aliakbar\Desktop\td-master\td-master\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Aliakbar\Desktop\td-master\td-master\build\td\generate\generate_json.vcxproj" (default target) (6) ->
"C:\Users\Aliakbar\Desktop\td-master\td-master\build\tdutils\tdutils.vcxproj" (default target) (7) ->
"C:\Users\Aliakbar\Desktop\td-master\td-master\build\tdutils\generate\tdmime_auto.vcxproj" (default target) (8) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with co
de 9009. [C:\Users\Aliakbar\Desktop\td-master\td-master\build\tdutils\generate\tdmime_auto.vcxproj]

    0 Warning(s)
    1 Error(s)

```

how can i fix it?

**Comment by levlam** [comment]
Have you installed gperf and added path to it to the %PATH% environment variable?

**Comment by L11R** [comment]
@levlam I also have such problem. Did all as said in instruction. gperf is working fine from cmd (of course everywhere, not only in his directory).

**Comment by aliakbarhamzeh1378** [comment]
@levlam  yeah. i install gperf completly

**Comment by levlam** [comment]
Could you try to manually run from the <path to TDLib source>/tdutils/generate/ directory command
`powershell -ExecutionPolicy ByPass " & gperf -m100 --output-file=auto/mime_type_to_extension.cpp auto/mime_type_to_extension.gperf"`?

**Comment by L11R** [comment]
After installing Windows 10 SDK with VS Build Tools installer it compiled. Don't know what it was.

**Comment by L11R** [comment]
I can't use it with Golang, so just publish here precompiled binaries, maybe will be usefull for someone:
https://drive.google.com/open?id=17xL9TVWlsuPyok7j6FgZ-BJhsV1ZocjE
MSVC, x64.

**Comment by Hamper** [comment]
L11R: you build is x32, not x64
From dumpbin /headers tdjson.dll:
```
FILE HEADER VALUES
             14C machine (x86)
```

**Comment by isopen** [comment]
FinalizeBuildStatus:
  Файл "Win32\Debug\tl_generate_c\tl_generate_c.tlog\unsuccessfulbuild" удаляется.
  Обращение к "Win32\Debug\tl_generate_c\tl_generate_c.tlog\tl_generate_c.lastbuildstate".
Сборка проекта "C:\td\build\td\generate\tl_generate_c.vcxproj" завершена (целевые объекты по умолчанию).
Сборка проекта "C:\td\build\tdc.vcxproj" завершена (целевые объекты по умолчанию) с ошибкой.
Сборка проекта "C:\td\build\ALL_BUILD.vcxproj" завершена (целевые объекты по умолчанию) с ошибкой.
"C:\td\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (1) ->
"C:\td\build\test\all_tests.vcxproj" (целевой объект по умолчанию) (3) ->
"C:\td\build\tdactor\tdactor.vcxproj" (целевой объект по умолчанию) (4) ->
"C:\td\build\tdutils\tdutils.vcxproj" (целевой объект по умолчанию) (5) ->
"C:\td\build\tdutils\generate\tdmime_auto.vcxproj" (целевой объект по умолчанию) (6) ->
(CustomBuild конечный объект) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(17
1,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\td\build\tdutils\generate\tdmime_auto.vcxproj]

Специально для виндузятников пишу на Русском.
Вот тут лежит readline https://sourceforge.net/projects/gnuwin32/files/readline/5.0-1/
Вот тут лежит https://sourceforge.net/projects/gnuwin32/files/gperf/3.0.1/
Не забывайте прописывать переменные окружения. В гугле инфы полно.

**Comment by Hamper** [comment]
This is win64 build: https://drive.google.com/open?id=1j2AADHKj2NJi1LrXoC63oPAqlYf09fP5

For build you need gperf in PATH, vcpkg and cmake
If you want build x64 version you need use x64 vcpkg triplet and x64 cmake generator:
```
.\vcpkg --triplet x64-windows install openssl zlib
[go to td dir]
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake -DVC
PKG_TARGET_TRIPLET=x64-windows -DCMAKE_GENERATOR_PLATFORM=x64 ..
cmake --build . --config Release
```

**Comment by ras0219-msft** [comment]
We (vcpkg) should detect `VCPKG_TARGET_TRIPLET` correctly, so it should work with just:
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=…/vcpkg.cmake -A x64
```

**Comment by isopen** [comment]
@ras0219-msft Please tell your colleagues that it's impossible to use windows 10 in the modern world. Please.

**Comment by levlam** [comment]
Error message, shown when gperf is not found, should be much better in TDLib 1.2.0.
