### ISSUE TITLE
tgcalls library_versions_ TDLIB callProtocol

### ISSUE THREAD

**Issue by tg2sipfork** [tdlib/td#2001]
**InstanceImpl.cpp** - work

not working 
**InstanceV2Impl.cpp**
**InstanceV2ReferenceImpl.cpp** 
**InstanceV2_4_0_0Impl.cpp** 

What would you advise me to check why **any V2 versions** do not work?

**Comment by levlam** [comment]
You must get the list of supported versions from `tgcalls` using the method `tgcalls::Meta::Versions()`. You may also need to reverse returned list before passing to `library_versions_`. This way you should be able to connect with any official client using apporpriate reflector.
