### ISSUE TITLE
How to get progress in number of uploading and downlaoding messages 

### ISSUE THREAD

**Issue by rishabhhgupta** [tdlib/td#2004]
Whether i  use TdApi.SendMessage or TdApi.UploadFile, I'm able to send to send message to the telegram server, but I didn't able to get their uploading progress, Please anyone help me how I able to get uploading progress,

Or help me understand what is updateFile means that give progress
![chrome_2t2sfzI5VN](https://user-images.githubusercontent.com/66349860/173220016-83a9c4d9-b09a-408e-b429-f4f8b556fe85.png)

**Comment by rishabhhgupta** [comment]
I got my answer thank you all

**Comment by levlam** [comment]
This is thoroughly described in https://core.telegram.org/tdlib/getting-started.
