### ISSUE TITLE
addContact return 400 User not found

### ISSUE THREAD

**Issue by k0ry** [tdlib/td#2005]
Hello, 
when calling addContact for addition some contact to my contact  list with id 0 I always receive 400 error User not found.
What's problem?

**Comment by levlam** [comment]
`addContact`: "Adds a user to the contact list or edits an existing contact by their user identifier". Probably, you wanted to use `importContacts`.

**Comment by RakhimovMarat** [comment]
> Hello, when calling addContact for addition some contact to my contact list with id 0 I always receive 400 error User not found. What's problem?

Hello, did you solve this problem? I'm using addContact and set phone_number. Also receive 'User not found' error.
