### ISSUE TITLE
How to set up and generate html meta tags?

### ISSUE THREAD

**Issue by imagine1717** [tdlib/td#2006]
![image](https://user-images.githubusercontent.com/42824481/173613299-80eb3315-d94c-455f-8034-1478f9e6d488.png)

**Comment by levlam** [comment]
This is a question about `javadoc`, not `TDLib`. All options of `javadoc` are described in https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html or see all options with `javadoc -help`.

**Comment by imagine1717** [comment]
> All options of `javadoc` are described in https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html or see all options with `javadoc -help`. The option `-charset UTF-8` is likely the option you are interested in.

thank you
