### ISSUE TITLE
Multihread java unpredictable behavior

### ISSUE THREAD

**Issue by igolyudov** [tdlib/td#2007]
I have 3 registered clients. When sequential initialization of clients in different threads, all clients start using the same connection, initialized last.
[tgclient.log](https://github.com/tdlib/td/files/8904298/tgclient.log)
Source: https://github.com/igolyudov/tgdemo

**Comment by levlam** [comment]
You store all clients in the same static variable:
>    private static Client client = null;

Therefore whenever you create a new TDLib instance, you lose the access to the previous one.

**Comment by igolyudov** [comment]
Thx
