### ISSUE TITLE
How can I use the createCall method?

### ISSUE THREAD

**Issue by loretop** [tdlib/td#2008]
I've tried using the createCall method to start a call, and while it technically starts a call (because I do recieve it on my other phone), it doesn't start the call on my screen (it doesn't show the screen when you're waiting for the other person to answer). Also, if I try to answer from the other phone, it will show an error message. 

I don't know what else should I do? I'm working on Android Studio with Java.

**Comment by levlam** [comment]
TDLib doesn't provide user interface, it needs to be created by the app. And to actually transfer call data, the app needs to use [tgcalls](https://github.com/TelegramMessenger/tgcalls) library.
