### ISSUE TITLE
how get photoCached

### ISSUE THREAD

**Issue by pishnok** [tdlib/td#201]
Hello friends
How can I get photoCached?
I want to have a preview of the pictures before downloading.

**Comment by isopen** [comment]
Perhaps these are the tasks of the library. 
Let's wait for professionals.

P.S.
> The man whose idol is Jobs. Is not free.

**Comment by isopen** [comment]
I agree with Leo. This is a library task and it is wrapped in a common file uploading mechanism.

**Comment by restYura** [comment]
@isopen I tried the mechanism that @levlam suggested. He works
