### ISSUE TITLE
All my channels got removed because of tdlib

### ISSUE THREAD

**Issue by dyats** [tdlib/td#2010]
Hi, I tried to use Tdlib API for private purposes which is filtering & sorting data on my private channels(only for private usage).
So I was using WTelegramClient(C#/.NET) [WTelegramClient | GitHub](https://github.com/wiz0u/WTelegramClient) to get all chats(as a test request) and after this request I tried to send a second request but I got an exception message that says "400 PHONE_NUMBER_BANNED". I didn't flood nor spam anyone with this API and didn't do anything that is considered illegal in Telegram Terms of service.

I emailed the Telegram recover team, they didn't respond to me but the ban from my account was removed, when I logged in I realized that ALL my private channels where I was admin/owner disappeared. Then I checked on another account where I was a subscriber on those channels. It also disappeared from there. It should be a bug, owner's channels should not be removed when the account gets "deleted"(it was like this when the ban was applied).

**Comment by levlam** [comment]
`WTelegramClient` is unrelated to TDLib.

Account bans are also unrelated to TDLib. You need to follow up with the Telegram recover team about restoring access to the channels.

**Comment by dyats** [comment]
@levlam hi, but WTelegramClient uses Telegram API which is not tdlib? Maybe I got this wrong...
Anyway what I should do if Telegram recovery team don't reply to me few days? Wait more? Seems like they don't care :(

**Comment by dyats** [comment]
Yeah, I'm sorry I used Telegram API instead of TDlib, can I find it on GitHub?

**Comment by levlam** [comment]
TDLib is a library using Telegram API internally, so they aren't the same thing.

The Telegram recovery team is available only through email.

**Comment by dyats** [comment]
I emailed them yesterday, on my first message they replied in 8 hours, but on this new email related to channels they don't reply for a third day.
Sorry to bring this here but may be you know how much it takes usually to get a reply from them?

**Comment by bobacCurry** [comment]
> I emailed them yesterday again, on my first message they replied in 8 hours(which was on Sunday related to account unban), but on this new email related to channels they don't reply for a third day. Sorry to bring this here but may be you know how much it takes usually to get a reply from them?

How is this going? My account was banned recently also. If you got some response?

**Comment by dyats** [comment]
> > I emailed them yesterday again, on my first message they replied in 8 hours(which was on Sunday related to account unban), but on this new email related to channels they don't reply for a third day. Sorry to bring this here but may be you know how much it takes usually to get a reply from them?
> 
> How is this going? My account was banned recently also. If you got some response?

Hi, they unbanned my account and said that my channels were recovered, but it seems like channels were just recreated without any messages and all my info is lost, I hope they are still working on it.

**Comment by dyats** [comment]
Looks like Telegram don't want to fix it. No response... Nothing... :(

**Comment by dyats** [comment]
@bobacCurry did they respond to you?

**Comment by bobacCurry** [comment]
> 

No! I have not received a response yet , it's vary sad. I have test this some days, I found that they trend to ban some accounts  register recently.

**Comment by bobacCurry** [comment]
> No! I have not received a response yet , it's vary sad. I have test this some days, I found that they trend to ban some accounts register recently.



> @bobacCurry did they respond to you?

No! I have not received a response yet , it's vary sad. I have test this some days, I found that they trend to ban some accounts register recently.
