### ISSUE TITLE
Prioritisation of channel updates

### ISSUE THREAD

**Issue by nmozzer** [tdlib/td#2011]
Hello,

As far as I can tell from issues such as this - https://github.com/tdlib/td/issues/1663, Channels in Telegram work via a TCP connection, which is bi-directional, and channel notification are pushed to members of that channel.

However, I may be wrong but I think from there, the channel essentially 'throttles' (not sure I have a better way of describing it), the amount of push notifications it sends in a single go, meaning channels can have a few seconds of lag for some users when receiving notifications. 

Is there a way to prioritize this? To ensure that certain participants in a channel, receive updates as quickly as possible? 

Essentially I want notifications to reach my service from Telegram, as instantaneously as they do when messaging peer to peer, if that's possible.

Thank-you

**Comment by levlam** [comment]
> To ensure that certain participants in a channel, receive updates as quickly as possible?

You can make them administrators. There are no other ways. Channels are intended for broadcasting and are not suitable for instant notifications.

**Comment by nmozzer** [comment]
Ahh right, okay thank you. One last one then, do bots in a channel receive messages as a priority? Or only administrators?

**Comment by levlam** [comment]
Yes, bots also receive messages as soon as possible.

**Comment by nmozzer** [comment]
Thank you very much.
