### ISSUE TITLE
Failed to build on UWP

### ISSUE THREAD

**Issue by GuidoBelluomo** [tdlib/td#2012]
I'm trying to build using the commands provided by the configurator, this is the error I'm getting while it builds openssl for the x86-uwp-rel platform:

```
-- Build x86-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: nmake -f makefile install_dev
    Working Directory: C:/tdlib_build/td/vcpkg/buildtrees/openssl/x86-uwp-rel
    Error code: 2
    See logs for more information:
      C:\tdlib_build\td\vcpkg\buildtrees\openssl\build-x86-uwp-rel-1-out.log
      C:\tdlib_build\td\vcpkg\buildtrees\openssl\build-x86-uwp-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/uwp/portfile.cmake:78 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:28 (include)
  scripts/ports.cmake:146 (include)


error: building openssl:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f
[tdlib output.txt](https://github.com/tdlib/td/files/8933035/tdlib.output.txt)
08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: b49b2bdf2 2022-06-17 (7 hours ago)

You can also use the prefilled template from C:\tdlib_build\td\vcpkg\installed\vcpkg\issue_body.md.
```
I'm attaching both log files mentioned in the error, as well as the full output. Windows errors are in italian so bear with that please.
This was the configuration I'm using:

_Language: C#
Platform: UWP
Archiver: 7zip
Shell: Powershell_

I've tried skipping that particular platform but the other platforms that use triplets also fail. I'd still like to go one step at a time, maybe the issue is a common issue. I have enabled Windows 10 SDK support in Visual Studio 2019 and I already had everything else setup.

I've read in a thread that the error pointed to in the build-x86-uwp-rel-1-out.log file could be fixed by compiling with `no-secure-memory`, but I've had a lot of trouble trying to set that configuration for building openssl. Not sure I even can do that if I go through vcpkg.

[tdlib output.txt](https://github.com/tdlib/td/files/8933042/tdlib.output.txt)
[build-x86-uwp-rel-1-err.log](https://github.com/tdlib/td/files/8933048/build-x86-uwp-rel-1-err.log)
[build-x86-uwp-rel-1-out.log](https://github.com/tdlib/td/files/8933049/build-x86-uwp-rel-1-out.log)

**Comment by GuidoBelluomo** [comment]
I've noticed in the repository documentation that gperf needs to be installed, the configurator does not mention this. I have installed it and ran the script a second time. The second run has skipped over the gperf errors that happened later on, but still has the same build error for the `x86-uwp-rel` platform

Attached second output.

I'm not entirely sure why, but the final error might be looking in the wrong path? I did return to the same directory into which I ran the script earlier, before running it again. This is the path it's looking into: `C:\tdlib_build\td\td\tdlib`. It's looking through another td folder within the td repo folder. `C:\tdlib_build\td\td` exists and is correct, but there's no `tdlib` folder in it. I suppose because it didn't successfully build.

Running a third run in a clean folder, if it changes anything I'll update. If it doesn't, then this is my final message until I figure something out or somebody helps me.

[tdlib output 2.txt](https://github.com/tdlib/td/files/8933064/tdlib.output.2.txt)

**Comment by levlam** [comment]
Your errors happen on installation of dependencies through `vcpkg`, so they aren't even related to TDLib itself. It seems that OpenSSL UWP package is broken in the latest `vcpkg` version, so an old one must be used. For example, by modifying build instructions this way:
```
cd vcpkg
git checkout 1b1ae50e1a69f7c659bd7d731e80b358d21c86ad
./bootstrap-vcpkg.bat
```

> I've noticed in the repository documentation that gperf needs to be installed, 

`gperf` is installed through `vcpkg` on Windows nowadays.

**Comment by levlam** [comment]
I updated [build instructions generator](https://tdlib.github.io/td/build.html) to include checking out of specific known-to-work vcpkg commit.
