### ISSUE TITLE
Issue in downloading file

### ISSUE THREAD

**Issue by rishabhhgupta** [tdlib/td#2013]
For downlaoding i use DownlaodFile, i get the download location at data/data/"my app id"/files/.... but the problem is i get diffenent file, 
I try to upload a file by using UploadFile and get their fileId and use same fileId to download file either I get "invalid file Identifier" error or different file, sometimes file locations is same after i change to different file id.

**Comment by rishabhhgupta** [comment]
In UploadFile i get object fileid same as I get in DownlaodFile object fileid, both are same but file are changed

**Comment by levlam** [comment]
`UploadFile` must never be used by the apps, unless they want to upload a file without actually creating a message. In apps this is usually needed only for being recorded voice/video notes. If you want to send a message, you need to use `sendMessage` directly.

**Comment by rishabhhgupta** [comment]
so the question is how i able to get that voice/video notes, I use downlaodFile with id i get from updatefiles from uploadfile, but i get different file

**Comment by rishabhhgupta** [comment]
how the file id look like as  in number(234 or 322 or 234) found in the local section  or like "AQADBQADCq8xG6IhqVYACAMAA6aSUywBAAMXVd6cnYpRoCME" string found in the remote section, I'm using fileId in the local section

**Comment by IRGC** [comment]
tdlib uses local database to store information.

**Comment by rishabhhgupta** [comment]
thank you for quick response, am i using right file id? I got difficulty in downlaod file uploaded in telegram, firstly i use uploadfile but later @levlam  suggest me to use sendMessage rather than uploadfile, so i did but i didn't file, i get wrong file identifier error or sometimes wrong file

`file = File {
        id = 661  ----------------------------------------> this is my fileid?
        size = 633861
        expectedSize = 633861
        local = LocalFile {
          path = "/storage/emulated/0/Download/EAadhaar_0648177110118420220614141806_2106202216456.pdf"
          canBeDownloaded = true
          canBeDeleted = false
          isDownloadingActive = false
          isDownloadingCompleted = true
          downloadOffset = 0
          downloadedPrefixSize = 633861
          downloadedSize = 633861
        }
        remote = RemoteFile {
          id = "BQACAgUAAx0EWdQL3AADA2K3070k_3wH4Y5-bGM9Eqhe2DIpAAK4BgAC2TfAVe2g9Yu8K1Q5IwQ"
          uniqueId = "AgADuAYAAtk3wFU"
          isUploadingActive = false
          isUploadingCompleted = true
          uploadedSize = 633861
        }
      }
    }`

**Comment by rishabhhgupta** [comment]
for downloading above file as their file id is 661 i use code as 

`TdApi.DownloadFile downloadFile = new TdApi.DownloadFile(661, 1, 0,0,true);


                client.send(downloadFile, new Client.ResultHandler() {
                    @Override
                    public void onResult(TdApi.Object object) throws IllegalAccessException {
                        switch (object.getConstructor()) {
                            case TdApi.Error.CONSTRUCTOR:
                                System.err.println("Receive an errori:" + newLine + object);
                                break;
                            case TdApi.Ok.CONSTRUCTOR:
                                break;
                            case TdApi.File.CONSTRUCTOR:
                                Log.i("notthisone", object.toString());
                                
                        }
                    }
                });`




I get log of 

`I/notthisone: File {
      id = 661
      size = 59309
      expectedSize = 59309
      local = LocalFile {
        path = "/data/data/com.promiseek.cloudo/files/profile_photos/4212067018824853417_1.jpg"
        canBeDownloaded = true
        canBeDeleted = true
        isDownloadingActive = false
        isDownloadingCompleted = true
        downloadOffset = 0
        downloadedPrefixSize = 59309
        downloadedSize = 59309
      }
      remote = RemoteFile {
        id = "AQADBQADqacxG6NEdDoACAMAA6NEdDoABHL9ZO19O4yzIwQ"
        uniqueId = "AQADqacxG6NEdDoB"
        isUploadingActive = false
        isUploadingCompleted = true
        uploadedSize = 59309
      }
    }
`

look they both have smae fileid but file is change from pdf to jpg and when i when to the file location, i get completely differnet image, that i didn't know in my life here is the image
![4212067018824853417_1](https://user-images.githubusercontent.com/66349860/175798529-f578e206-fc49-4c79-917a-027b4d929ed2.jpg)

**Comment by rishabhhgupta** [comment]
Am I doing something wrong in my coding please help me,

**Comment by IRGC** [comment]
Make sure you are trying to download file from the same tdlib instance local file id received from.

**Comment by rishabhhgupta** [comment]
yes, that I do above code, i get same file id from uplaoding to downloading but file are change, I share the code of uploading 
`client.send(new TdApi.SendMessage(l,
                                                0, 0, null, null, messageContent),
                                        new Client.ResultHandler() {
                                            @Override
                                            public void onResult(TdApi.Object object) throws IllegalAccessException {
                                                switch (object.getConstructor()) {
                                                    case TdApi.Error.CONSTRUCTOR:
                                                        System.err.println("Receive an error:uploading section" + newLine + object);
                                                        break;
                                                    case TdApi.Ok.CONSTRUCTOR:

                                                        break;
                                                    case TdApi.Message.CONSTRUCTOR:
                                                        Log.i("objectss", object.toString());


                                                        TdApi.Message message = (TdApi.Message) object;
//                                                UploadingIndicator uploadingIndicator = new UploadingIndicator();
//                                                uploadingIndicator.execute((int) message.id);
                                                        long totalMessageSend;

                                                        TdApi.MessageContent content = message.content;
                                                        if(content.getConstructor() == TdApi.MessagePhoto.CONSTRUCTOR){
                                                            TdApi.MessagePhoto messagePhoto = (TdApi.MessagePhoto) content;
                                                            TdApi.Photo photo = messagePhoto.photo;
                                                            TdApi.PhotoSize[] photoSize = photo.sizes;
                                                            TdApi.File file1 = photoSize[0].photo;
                                                            TdApi.LocalFile localFile = file1.local;



                                                            Log.i("fileIddd1", String.valueOf(file1.id));
                                                            FilePogo uploadingPogo = new FilePogo();

                                                            //set name
                                                            uploadingPogo.setName(localFile.path.substring(localFile.path.lastIndexOf("/")+1));

                                                            //set size
                                                            uploadingPogo.setSize(String.valueOf(file1.size));

                                                            //set fileId
                                                            uploadingPogo.setFileId(String.valueOf(file1.id));

                                                            //set Date
                                                            uploadingPogo.setDate(String.valueOf(message.date));




                                                            totalMessageSend= snapshot.getChildrenCount()-1;
                                                            firebaseDatabase.child(phoneNumberFromSp).child("upload").
                                                                    child(String.valueOf(totalMessageSend)).setValue(uploadingPogo);

                                                        }else if(content.getConstructor() == TdApi.MessageVideo.CONSTRUCTOR){
                                                            TdApi.MessageVideo messageVideo = (TdApi.MessageVideo) content;
                                                            TdApi.Video video = messageVideo.video;
                                                            //here you get filename |^

                                                            TdApi.File file1 = video.video;
                                                            //here you get size and file id

                                                            FilePogo uploadingPogo = new FilePogo();

                                                            //set name
                                                            uploadingPogo.setName(video.fileName);

                                                            //set size
                                                            uploadingPogo.setSize(String.valueOf(file1.size));

                                                            //set fileId
                                                            uploadingPogo.setFileId(String.valueOf(file1.id));

                                                            //set Date
                                                            uploadingPogo.setDate(String.valueOf(message.date));




                                                            totalMessageSend= snapshot.getChildrenCount()-1;
                                                            firebaseDatabase.child(phoneNumberFromSp).child("upload").child(String.valueOf(totalMessageSend)).setValue(uploadingPogo);

                                                        }else if(content.getConstructor() == TdApi.MessageAudio.CONSTRUCTOR){
                                                            TdApi.MessageAudio messageAudio = (TdApi.MessageAudio) content;
                                                            TdApi.Audio audio = messageAudio.audio;
                                                            //here you get filename |^

                                                            TdApi.File file1 = audio.audio;
                                                            //here you get size and file id

                                                            FilePogo uploadingPogo = new FilePogo();

                                                            //set name
                                                            uploadingPogo.setName(audio.fileName);

                                                            //set size
                                                            uploadingPogo.setSize(String.valueOf(file1.size));

                                                            //set fileId
                                                            uploadingPogo.setFileId(String.valueOf(file1.id));

                                                            //set Date
                                                            uploadingPogo.setDate(String.valueOf(message.date));




                                                            totalMessageSend= snapshot.getChildrenCount()-1;
                                                            firebaseDatabase.child(phoneNumberFromSp).child("upload").child(String.valueOf(totalMessageSend)).setValue(uploadingPogo);

                                                        }else if(content.getConstructor() == TdApi.MessageDocument.CONSTRUCTOR){
                                                            TdApi.MessageDocument messageDocument = (TdApi.MessageDocument) content;
                                                            TdApi.Document document = messageDocument.document;
                                                            //here you get filename |^

                                                            TdApi.File file1 = document.document;
                                                            //here you get size and file id

                                                            FilePogo uploadingPogo = new FilePogo();

                                                            //set name
                                                            uploadingPogo.setName(document.fileName);

                                                            //set size
                                                            uploadingPogo.setSize(String.valueOf(file1.size));

                                                            //set fileId
                                                            uploadingPogo.setFileId(String.valueOf(file1.id));

                                                            //set Date
                                                            uploadingPogo.setDate(String.valueOf(message.date));




                                                            totalMessageSend= snapshot.getChildrenCount()-1;
                                                            firebaseDatabase.child(phoneNumberFromSp).child("upload").child(String.valueOf(totalMessageSend)).setValue(uploadingPogo);

                                                        }
                                                    default:
                                                }
                                            }

                                        });





                            }`

**Comment by rishabhhgupta** [comment]
can i get some code where downloading and uplaoding are done
