### ISSUE TITLE
Do only bots marked as admins receive messages ASAP

### ISSUE THREAD

**Issue by nmozzer** [tdlib/td#2017]
Hello,

I’m still trying to workout a way in which my service can receive a broadcast message from a channel the quickest way.

Bots and Admins receive messages as soon as possible (is this the same as peer to peer messaging for them?) according to https://github.com/tdlib/td/issues/1668. However, when you say bots, do you mean bots that are admins on the channel? Is there any way a bot can listen to a private channel that the owning account is a a member of, but the bot has not been explicitly invited to or added to as an admin? 

I am not the owner of the private channel, and they may not be amenable to providing admin status to someone other than themselves.

Thank you

**Comment by AYMENJD** [comment]
Bots can be added only as administrator in channels.

Channel administrators(including bots) has higher priority on receiving the broadcast message.

And of course the bot should be added to the channel as an administrator so he can receive the broadcast message.

**Comment by nmozzer** [comment]
Is there a way of disseminating what order the messages are sent in?

**Comment by nmozzer** [comment]
Sorry and another one, do large groups also suffer from this broadcast system? Or are large groups peer to peer?

**Comment by levlam** [comment]
You can't add bots to channels, unless you are an administrator of the channel.
