### ISSUE TITLE
Problem mentioning users when sending messages

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#2018]
Hello
I use tdlib 1.8.3.
I want to send a HTML style text message and mention some users.
My text is completely correct because the test robot does not give any errors.
Only the main robot gives the following error:

`
[ 0][t 3][1655630390.567631244][MessageEntity.cpp:4171][#1][!MessagesManager][&r_input_user.is_ok()]	do_send_message [Error : 400 : User not found]
TDLib fatal error:  b'[ 0][t 3][1655630390.567631244][MessageEntity.cpp:4171][#1][!MessagesManager][&r_input_user.is_ok()]\tdo_send_message [Error : 400 : User not found]\n'
Aborted
`

Thanks for guiding me.

**Comment by levlam** [comment]
Could you send log with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by BarnameESF** [comment]
> Could you send log with verbosity level 4 to https://t.me/tdlib_bot?

Yes, I can send it to you.

**Comment by levlam** [comment]
Did you send the log?
