### ISSUE TITLE
Do large groups also broadcast messages like channel?

### ISSUE THREAD

**Issue by nmozzer** [tdlib/td#2019]
Hello,

Do large groups also broadcast messages? Like channels? And therefore suffer from the same latency issues as channels, or do groups enable peer to peer levels of latency? 

Thank you

**Comment by levlam** [comment]
Unspecified.

**Comment by nmozzer** [comment]
Sorry, to clarify are you suggesting that the answer is unspecified? If so, I’m guessing I want to ask this question elsewhere?

**Comment by levlam** [comment]
Your question has no answer.

**Comment by nmozzer** [comment]
I think I’m being thick, 

channels and groups are different concepts within Telegram. You are telling me that, there is no answer to whether they both have the same underlying broadcast design or not?
