### ISSUE TITLE
I need the name of the standard that you follow when creating the tdlib code

### ISSUE THREAD

**Issue by isopen** [tdlib/td#202]
Leo help urgently. Help

Please tell me the name of the standard that you use to design the code.
Some local professionals are arguing. Tell me, please, what code design standard.

They say that psr-2 is cool (In their understanding, best practice is to do 4 spaces)...
Help please.

**P.S.**
> Very grateful for the early reply

**Comment by levlam** [comment]
What programming language are you talking about?

**Comment by isopen** [comment]
function test
{
}
It's all because of the psr...
Help please

**Comment by isopen** [comment]
class Test
{
      function test() {
        if (...)
        {
              ...
        } elseif (...) {
        }
      }
      function test1() {...}
      function test2() {

}
}

**Comment by restYura** [comment]
@isopen You can write according to the standard that you like. But within the framework of the generally accepted language standard.
