### ISSUE TITLE
.app domains are not parsed in Sticker set display window

### ISSUE THREAD

**Issue by Defuera** [tdlib/td#2021]
Please could you make `.app` domains clickable in Stickers list window?
Example: 
|  <img width="300" alt="image" src="https://user-images.githubusercontent.com/1181883/174617247-210e33b3-312c-4f60-bd13-633b044d60e7.png"> |  <img width="300" alt="image" src="https://user-images.githubusercontent.com/1181883/174617214-3e11b4ff-8faf-4c27-ad29-733e1150d895.png"> |

**Comment by levlam** [comment]
How is this related to TDLib?

**Comment by azkadev** [comment]
> Please could you make `.app` domains clickable in Stickers list window? Example: | <img alt="image" width="300" src="https://user-images.githubusercontent.com/1181883/174617247-210e33b3-312c-4f60-bd13-633b044d60e7.png"> | <img alt="image" width="300" src="https://user-images.githubusercontent.com/1181883/174617214-3e11b4ff-8faf-4c27-ad29-733e1150d895.png"> |

so that you can click on the link,
looks like it's a developer application, not a tdlib library

**Comment by Defuera** [comment]
@levlam I guess you right. Could you hint where can I report this?
It works the same on Telegram desktop and iOS, Android versions

**Comment by AYMENJD** [comment]
@Defuera You can report bugs and suggestions on https://bugs.telegram.org.

**Comment by Defuera** [comment]
Thx, AYMENJD! Will do that 🙏
