### ISSUE TITLE
`updateBasicGroupFullInfo` object has non-negative `basic_group_id_` field

### ISSUE THREAD

**Issue by ImanolBarba** [tdlib/td#2023]
I've been debugging an issue with a client I'm writing: sometimes I get an error when calling `getChat` due to the chat not existing.

I found out that whenever I get an `updateBasicGroupFullInfo` Telegram Update, the `basic_group_id_` field is positive, and to my understanding, the `basic_group_id`, if we understand it as an equivalent of a chat ID, should be negative.

Is this by design? should I be multiplying all basic group IDs with -1 to call `getChat` with the basic group ID? I am doing that as a workaround for the moment, but it feels like a possible mistake in the API.

Thanks

**Comment by ImanolBarba** [comment]
I just had the same issue with `getBasicGroupFullInfo`, looks like I have to provide the positive chat ID, which reinforces the point that this is by design.

Can the docs reflect this bit? I think many devs would expect the chat ID to be equivalent to the basic group/supergroup ID since those are subsets of Chat.

Thanks

**Comment by levlam** [comment]
> the basic_group_id, if we understand it as an equivalent of a chat ID

This is wrong. You can't manually convert between `chat_id`/`basic_group_id`/`supergroup_id`/`secret_chat_id`/`user_id`. They are identifiers of unrelated entities and belong to different sopes.

You need to inspect `Chat.type` field in order to find type-specific information about the chat. 

`createPrivateChat`/`createBasicGroupChat`/`createSupergroupChat`/`createSecretChat` can be used for backward conversion.

**Comment by ImanolBarba** [comment]
So let's say for instance I get a notification that a new message was sent.

The updateNewMessage contains the chat id

Then lets say I want to get the details from this chat ID

I am already inspecting the chat type, but if I wanted to call say, getBasicGroupFullInfo, or anything similar, I have to provide the `basic_group_id`, but I only have the chat_id!

So if only have the new message update, how do I convert that to a basic group id, or a supergroup id?

**Comment by Blood2xaimond** [comment]
I have the same problem!

**Comment by ImanolBarba** [comment]
Ooooh thank you I didn't know that!

I think the issue has been pretty much addressed so I'll close it.

Thank you!

**Comment by jnxyatmjx** [comment]
> chat.type.basic_group_id

Maybe i also need this information
