### ISSUE TITLE
Windows on ARM (WOA) ARM64

### ISSUE THREAD

**Issue by saulozt** [tdlib/td#2024]
Now that Visual Studio 2022 17.3 Preview 2 with native ARM64 support is available, I would like to know if there are any future plans to implement the native library for ARM64 processors on Windows.

I heard that one of the limitations of some unofficial clients like Unigram to port the client natively to ARM64 is that TDlib lacks Windows ARM64 support.

**Comment by levlam** [comment]
TDLib supports ARM64 as any other little endian architecture, for which a modern C++ compiler exists.

The issue with ARM64 is different. Unigram uses private TDLib build for beta versions and the first public release. which is built by me specifically for Unigram. I use Visual Studio 2017 for this, so I can't build ARM64 package. But after TDLib's code is pushed to Github, nothing prevents from building an ARM64 version also.
