### ISSUE TITLE
getChats request responds too long when calling first time

### ISSUE THREAD

**Issue by ViktorKravtsov** [tdlib/td#2025]
Hello, I have noticed that getChats (and loadChats) request responds 10+ seconds when you launch tdlib (compiled tg_cli.exe)
This happens when your account has a lot of chats with a lot of messages in them.

Is any way to make this requests respond faster?

**Comment by levlam** [comment]
If passed limit is low, then response should be fast.

**Comment by ViktorKravtsov** [comment]
> If passed limit is low, then response should be fast.

Even when i pass limit=1, response lasts same time

**Comment by levlam** [comment]
Another common issue is using a big log level and not redirecting TDLib's log from console to a file.

**Comment by ViktorKravtsov** [comment]
verbosity=1 
into console only request and responce are written

**Comment by levlam** [comment]
Could you send TDLib log with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by ViktorKravtsov** [comment]
sended

**Comment by ViktorKravtsov** [comment]
Even limit=1 or 10 makes it slow

**Comment by levlam** [comment]
You have issues with used proxy.

**Comment by levlam** [comment]
Also, log is incomplete because of `slvl 1` call in the middle of the log, so I can't actually check what exactly happened with network queries. But I see that there were protocol-level issues with responses through the proxy.

**Comment by levlam** [comment]
If you really need a proxy to access Telegram, you can use some other proxy, for example, https://t.me/proxy?server=exp.proxy.digitalresistance.dog&port=443&secret=7tQdjNmPALIE6YAJmOz4Mi53d3cuZ29vZ2xlLmNvbQ.
