### ISSUE TITLE
Display names of chat users

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#2026]
Hello!
Could you please suggest on how to correctly display names for users of a chat?
It is clear how to get their ids (from getBasicGroupFullInfo for basic groups and from getSupergroupMembers for supergroups), but what about getting user's firstName and lastName? I suppose it is not ok to call getUser per each user id, but this data can be gotten via tdlib updates?

**Comment by AYMENJD** [comment]
Yes, you can handle `updateUser` which contains user information. Also you can use `getUser(user_id)`.

**Comment by AYMENJD** [comment]
You can't receive an ID from TDLib without receiving corresponding object.

**Comment by Mike497** [comment]
Yes, you're right. I'm getting ids from ChatMember array. But there is no info about user's firstName and lastName.

**Comment by Mike497** [comment]
I'm just curios on how-to-do it in 'tdlib-friendly' way.) Will there be any 'sanctions' possible from Telegram if I'll do 200 getUser requests in short time?

**Comment by AYMENJD** [comment]
"TDLib has a cache which speeds up all requests and gives a big flexibility for the application." –  Aliaksei Levin

So i suggest you to use `getUser`.

**Comment by levlam** [comment]
No, `getUser` is never needed to be used by ordinary apps. See https://core.telegram.org/tdlib/getting-started for details.
