### ISSUE TITLE
Feature Request: synchronous SendMessage (like DownloadFile#synchronous)

### ISSUE THREAD

**Issue by boohba** [tdlib/td#2027]
For now, I have to put the temporary message id in the map and wait for another update. This is an annoying boilerplate. I want to receive a response only when the request has succeeded or failed.

**Comment by levlam** [comment]
There are no Telegram clients, which can benefit from such change, so it will not be added.

**Comment by nordiauwu** [comment]
> For real bots there is Bot API.

It has less functionality and adds overhead.
