### ISSUE TITLE
`td_api::message` int32 timestamp (Year 2038 problem)

### ISSUE THREAD

**Issue by ImanolBarba** [tdlib/td#2028]
Seems like messages have both `date_` and `edit_date_` declared as `td_api::int32`, which translates as `std::int32_t`

Does this mean that Telegram messages have the Year 2038 problem? (https://en.wikipedia.org/wiki/Year_2038_problem)

Why are we not using `uint64_t`?

Thanks

**Comment by IRGC** [comment]
uint64_t require more storage

**Comment by ImanolBarba** [comment]
Yeah I get that much

But that means that all messages on 2038 will show as sent from 1970...

Are there *any* plans to fix this?

**Comment by IRGC** [comment]
No sure if Telegram will stay that long.

**Comment by AYMENJD** [comment]
Telegram will update to `uint64_t` before Y2038 comes. As they did on `user_id`.
