### ISSUE TITLE
Request for get ALL chats return only 150 items.

### ISSUE THREAD

**Issue by igolyudov** [tdlib/td#2029]
After request "client.send(new TdApi.LoadChats(new TdApi.ChatListMain(), limit - mainChatList.size()), new Client.ResultHandler() {..." from documentation (https://core.tlgr.org/tdlib/getting-started#getting-the-lists-of-chats), have only 150 chats, but have more. Cannot find any restrictions in code. It's tdlib restriction?

**Comment by levlam** [comment]
https://core.tlgr.org/tdlib/getting-started#getting-the-lists-of-chats: "For optimal performance, the number of loaded chats is chosen by TDLib and can be smaller than the specified limit. If the Application needs more chats, it must send another loadChats request."
