### ISSUE TITLE
Filter messages by type of message in tdjson.

### ISSUE THREAD

**Issue by sapelkinAV** [tdlib/td#203]
I need to get only messages with audio. Is it possible to specify filter in tdjson request?

I tried 

`td_send({'@type': 'searchChatMessages',
                             'chat_id': id,
                             'sender_user': 0,
                             'from_message_id': 0,
                             'offset': 0,
                             'limit': 100,
                             'filter': 'searchMessagesFilterAudio'})`

but the result was
"Object of type 'builtin_function_or_method' is not JSON serializable"

**Comment by abrehamgezahegn** [comment]
Hey @sapelkinAV did you solve the issue?
