### ISSUE TITLE
no sticker type

### ISSUE THREAD

**Issue by aCLr** [tdlib/td#2030]
Hi.
I have received this message:
![image](https://user-images.githubusercontent.com/6426720/176777989-87923642-4b76-4a51-b5be-118d92490813.png)

As you may see, there is no `type` field, but schema v1.8.0 sais that `sticker` message contains that field with type `StickerType` and does not have any defaults.

Have I missed something?

**Comment by zelenin** [comment]
https://github.com/tdlib/td/blob/b3ab664a18f8611f4dfcd3054717504271eeaa7a/td/generate/scheme/td_api.tl#L282

**Comment by aCLr** [comment]
My bad, I used master version.
Thanks
