### ISSUE TITLE
The problem while calling searchPublicChats

### ISSUE THREAD

**Issue by qing-wang** [tdlib/td#2032]
I am building a client which utilizes tdsharp. However, I have a problem while using SearchPublicChats.

The result returned by the API does not match to "Global Search" result shows on iPhone Official Telegram App.

For instance, by passing "# tesla" as the argument of SearchPublicChats, the result returned by API contains only two chats. However, by entering"# tesla" in search textfield of app, the result list contains more records.

**Comment by levlam** [comment]
It is up to the server, how much chats to return. Usually it returns 3 results, but sometimes it can return more chats.
