### ISSUE TITLE
C++ example crashes

### ISSUE THREAD

**Issue by Slavasil** [tdlib/td#2034]
Hello. I downloaded TDLib for the first time, built it and then wrote a simple program which does basically the same thing as example_td.cpp. I started my program and it had successfully logged into my account, but after 10-20 seconds of idle it crashed with the following error:
``[ 0][t 4][1656766023.181252002][UpdatesManager.cpp:1924][#1][!Td]	Check `use_mpas || update_count == 0` failed``
Then I tried to run the example, but got the same error with 'show chats' command.

**Comment by levlam** [comment]
This was a bug existed for less than 12 hours in master. You need to update to the latest TDLib version from master.

**Comment by Slavasil** [comment]
Thank you! It works perfectly now.
