### ISSUE TITLE
HELP NEEDED: does user access_hash expires ?

### ISSUE THREAD

**Issue by beastzx18** [tdlib/td#2035]
I get the PEER_ID_INVALID error when i use getUsers method, i understand why i get this error, but afaik, if i have the user id & access_hash it should work, so i wanna know if access_hash expires or what, if it is true, how am i supposed to get a users details by this method if i have his/her telegram id but not the access_hash (have but the expires one) ? if i am correct, tell me the duration in which the access_hash expires, if i made a contact again with the user does it reset (the access_hash timer resets ?)

**Comment by AYMENJD** [comment]
Once the `access_hash` doesn't work that means you don't have the right to access to that user. It doesn't matter if it expires or not.

**Comment by beastzx18** [comment]
it does matter, if the access_hash doesn't work that means it expired or something, and this happens i wanna know why and how much is needed to expire, or something else is causing it.
