### ISSUE TITLE
SupergroupMembersFilterRecent has no effect?

### ISSUE THREAD

**Issue by quanpham88** [tdlib/td#2039]
I tried to get most recent active members in group using GetSupergroupMembers with filter is SupergroupMembersFilterRecent.

But when I print out all users along with their status, I got a mix of UserStatusRecently, UserStatusOnline and UserStatusOffline in no order.

Isn't this filter suppose to let us get group members in order like that UserStatusOnline -> UserStatusRecently -> UserStatusOffline ?

**Comment by levlam** [comment]
This filter is supposed to return users in the order of their activity in the chat. It is impossible to sort 200000 chat members by their online status each time.
