### ISSUE TITLE
Choosing an architecture using tdlib

### ISSUE THREAD

**Issue by isopen** [tdlib/td#204]
Leo I have the opportunity to build a project according to the following scheme

frontend(angular(0) || react(1) || vue(2)) + tdlib + backend(api on python(0) || api on php(1) || api on ruby(2))

Which of the tools is best used for maximum performance? (on all the stacks there is an opportunity to write cool). Particularly interested in frontend(which tools will be more convenient to support?). Computer power is enough.

It is also interesting to know the opinion of professionals about this bundle:
frontend(angular(0) || react(1) || vue(2))  + tdlib + p2p (either partially p2p. i think in this case it is necessary to expand tdlib)
Technology for the future development of the project.

I read a lot of best practices, but did not understand what kind of high-load project they want to create. Help please

> And yet I like these madmen. Technologically cool.
> Very grateful for the early reply

**Comment by isopen** [comment]
Crazy house.
Leo can you help determine the choice of the stack?

**Comment by restYura** [comment]
Use relatively independent means. I like the vue + ruby. But everyone has his own taste.
