### ISSUE TITLE
How to stream an audio file via TDLib in group voice(video) calls?

### ISSUE THREAD

**Issue by sf7293** [tdlib/td#2046]
Hi.
How could we send voice messages (by sending specific files) using TDLib in the video calls that we have attended?
@levlam, Would you mind helping me to find a sequence of TDLib API calls that allows me to do so?

**Comment by levlam** [comment]
You can't do this using only TDLib. You need https://github.com/TelegramMessenger/tgcalls to implement voice/video calls.
