### ISSUE TITLE
Need TDLib developer documents

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#2047]
Hi

I want to change the source of TDLib. Is there is developer document for that?

Which IDE you are using for developing TDLib?

**Comment by levlam** [comment]
> Is there is developer document for that?

No.

> Which IDE you are using for developing TDLib?

You can use any IDE you prefer.

**Comment by aghasi** [comment]
> You can use any IDE you prefer.

Using same IDE as yours cause better developing and debugging. 

I used QtCreator but it can't detect many functions, so i can't trace the code.

**Comment by levlam** [comment]
You should use a familiar to you IDE, not some random IDE. There should be no much difference in the end.

Between, you need to build TDLib in order to see source code of auto-generated source files.
