### ISSUE TITLE
How can I change my account privacy settings?

### ISSUE THREAD

**Issue by FiksUpped** [tdlib/td#2051]
I simply can't understand what should I pass to `setUserPrivacySettingRules`. Passing `userPrivacySettingShowPhoneNumber` as `setting `gives 400 error "expected Object, got string". And What should be passed as rules?

**Comment by levlam** [comment]
You are sending a wrong request. You must pass an object with "@type" field.
> The JSON serialization of TDLib API objects is straightforward: all API objects are represented as JSON objects with
> the same keys as the API object field names. The object type name is stored in the special field "@type" which is
> optional in places where type is uniquely determined by the context.
> Fields of Bool type are stored as Boolean, fields of int32, int53, and double types are stored as Number, fields of
> int64 and string types are stored as String, fields of bytes type are base64 encoded and then stored as String,
> fields of array type are stored as Array.

You need to pass the list of rules: "A list of privacy rules. Rules are matched in the specified order. The first matched rule defines the privacy setting for a given user. If no rule matches, the action is not allowed".

**Comment by FiksUpped** [comment]
Got it, thanks
