### ISSUE TITLE
download photo from chat

### ISSUE THREAD

**Issue by Mohammaddn74** [tdlib/td#2054]
hi
i use tdlib in c#
i get chat message history and when i want to download message media(like a photo) IsDownloadingCompleted never be true and alwayse  is false
my code:

                                var content = msg.Content;
                                if (content is TdApi.MessageContent.MessagePhoto)
                                {
                                    TdApi.MessageContent.MessagePhoto photo = (TdApi.MessageContent.MessagePhoto)content;
                                    var id = photo.Photo.Sizes[photo.Photo.Sizes.Length - 1].Photo.Id;
                                    var dn = await _client.DownloadFileAsync(id, 32);
                                    while (dn.Local.IsDownloadingCompleted == false)
                                    {
                                        await Task.Delay(200);
                                    }
                                    
                                }

can somebody tel me what must i do?

tnx

**Comment by levlam** [comment]
The field `.Local.IsDownloadingCompleted` of a local object `dn` can't ever change, no matter how much time passed. You will receive `UpdateFile` with `File.Local.IsDownloadingCompleted == true` when file is downloaded (or with `File.Local.IsDownloadingActive == false` in case of a failure). You also need to check that `dn.Local.IsDownloadingActive` to ensure that downloading has actually started.
