### ISSUE TITLE
Error compiling last commit

### ISSUE THREAD

**Issue by TEHEK1** [tdlib/td#2055]
I succesfully built commit at july 15, but todays commit return me this error:
`/root/td/td/telegram/Application.cpp: In member function ‘void td::SaveAppLogLogEvent::parse(ParserT&)’:
/root/td/td/telegram/Application.cpp:96:54: error: expected primary-expression before ‘>’ token
   96 |     auto buffer = parser.fetch_string_raw<BufferSlice>(parser.get_left_len());
      |                                                      ^
/root/td/td/telegram/Application.cpp: In instantiation of ‘void td::SaveAppLogLogEvent::parse(ParserT&) [with ParserT = td::log_event::LogEventParser]’:
/root/td/tdutils/td/utils/tl_helpers.h:225:3:   required from ‘std::enable_if_t<(! std::is_enum<_Tp>::value)> td::parse(T&, ParserT&) [with T = td::SaveAppLogLogEvent; ParserT = td::log_event::LogEventParser; std::enable_if_t<(! std::is_enum<_Tp>::value)> = void]’
/root/td/td/telegram/logevent/LogEvent.h:196:8:   required from ‘td::Status td::log_event_parse(T&, td::Slice) [with T = td::SaveAppLogLogEvent]’
/root/td/td/telegram/Application.cpp:130:41:   required from here
/root/td/td/telegram/Application.cpp:97:20: error: no matching function for call to ‘td::TlBufferParser::TlBufferParser(<brace-enclosed initializer list>)’
   97 |     TlBufferParser buffer_parser{&buffer};
      |                    ^~~~~~~~~~~~~`

**Comment by levlam** [comment]
Thank you. Fixed in master.
