### ISSUE TITLE
Documentation needed by tdlib

### ISSUE THREAD

**Issue by isopen** [tdlib/td#206]
tdlib.com tdlib.org lib.td tdlib.ru it would be very cool (i like the last)
You can organize the documentation directly on github. There is a wonderful section of the Wiki.

That's cool https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl
But it is not very convenient to send information in parts.

Leo Please give another link to the documentation. Preferably without "Telegram" inscriptions.
Just a list of methods and transitions to the appropriate pages. I do not want to use VPN. Honestly.

Please. Help

**Comment by isopen** [comment]
I spent a whole day torturing myself with the file https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl
I could not smash it into pieces. Because there are too many characters '\n' and the descriptions for attributes can be in one line. In addition, the beginning of the file is not standard.

Please help me with the documentation to your wonderful library :((

**Comment by isopen** [comment]
- Я желаю достойно вознаградить тебя, за прекрасную игру, которую ты придумал(сказал Царь)
- Я достаточно богат, чтобы исполнить самое смелое твоё пожелание(продолжил Царь)
- Назови награду, которая тебя удовлетворит, и ты получишь её.(продолжил Царь)
- Велика доброта твоя, повелитель. Но дай срок обдумать ответ. Завтра, по зрелому размышлению, я сообщу тебе мою просьбу.
- Повелитель. Прикажи выдать мне за первую клетку шахматной доски одно пшеничное зерно.
- Простое пшеничное зерно? (изумился Царь)
- Да, повелитель. За вторую клетку прикажи выдать 2 зерна, за третью 4, за четвёртую 8, за пятую 16, за шестую 32 …
- Ты получишь свои зёрна за все 64 клетки доски, согласно твоему желанию: за каждую вдвое больше предыдущей. Но знай, что просьба твоя недостойна моей щедрости. Прося такую ничтожную награду, ты непочтительно пренебрегаешь моею милостью. Поистине, как учитель, ты мог бы показать лучший пример уважения к доброте своего государя. Ступай. Слуги мои вынесут тебе твой мешок с пшеницей.
...
- С изумлением внимал Царь словам старца.
- Назови же мне это чудовищное число. (сказал он в раздумье).
- 18 квинтильонов 446 квадрильонов 744 триллиона 73 биллиона 709 миллионов 551 тысяча 615, о повелитель!

**Comment by iwantgihub** [comment]
Good task. I liked reading

**Comment by restYura** [comment]
@isopen You need to parse text. Begin by parsing by class. Next you will see the whole construction logic of the file. This is a simple task.

**Comment by Vasyagit** [comment]
Good story

@isopen No documentation required. You can program without documentation.
It seems to me that you did not collect the tdlib library at all...

**Comment by mrjackjakson** [comment]
@isopen Please try my library.
You are good at testing. Thanks

**Comment by UnblockerUsername** [comment]
@isopen I'll try to write a parser for you.

**Comment by UnblockerUsername** [comment]
@isopen Try without documentation.

**Comment by danog** [comment]
I __still__ don't get this guy

**Comment by isopen** [comment]
Fibonacci numbers are elements of a numerical sequence. Please try to imagine a chessboard.

For this case, something unstable happened, but can be expressed as a sequence.
Documentation successfully found.
