### ISSUE TITLE
Java Example has  compilation errors

### ISSUE THREAD

**Issue by arpithavaddu** [tdlib/td#2063]
/Example.java:618: error: modifier static not allowed here
        final static class ThrowError implements Runnable {
                     ^

Example.java:643: error: modifier private,static not allowed here
            private static final class ClientError extends Error {
                                 ^

Example.java:649: error: modifier private,static not allowed here
            private static final class ExternalClientError extends Error {
                                 ^
Example.java:655: error: Illegal static declaration in inner class ThrowError
            private static boolean isDatabaseBrokenError(String message) {
                                   ^
  modifier 'static' is only allowed in constant variable declarations
Example.java:664: error: Illegal static declaration in inner class ThrowError
            private static boolean isDiskFullError(String message) {
                                   ^
  modifier 'static' is only allowed in constant variable declarations
Example.java:669: error: Illegal static declaration in inner class ThrowError
            private static boolean isDiskError(String message) {

**Comment by levlam** [comment]
Thank you. Compatibility with old Java versions has just been fixed in https://github.com/tdlib/td/commit/376476481c5fae682ab571f047f32efada3a9343.
