### ISSUE TITLE
Flutter, error while serializing + deserializing polls 

### ISSUE THREAD

**Issue by Anfet** [tdlib/td#2066]
While deserializing polls flutter version of tdlib throws a error at `poll.dart` line 51, code
`id: int.parse(json['id']),` with error `type int is not a string`.

This happens because when serializing (`"id": id,`) id is being set as `int`, but being retrieved in deserialization as String in `int.parse`.

**Comment by levlam** [comment]
Bindings for specific languages are provided by third-party developers. You need to create an issue in repository of the specific wrapper, or try any other wrapper from https://github.com/tdlib/td/blob/master/example/README.md#dart.
