### ISSUE TITLE
Question: How download profile photo?

### ISSUE THREAD

**Issue by AnatoliyKozlov** [tdlib/td#2067]
I use java.
Call GetUserProfilePhotos that return ChatPhoto[], but ChatPhoto::id is long.
<img width="381" alt="image" src="https://user-images.githubusercontent.com/11912314/180662897-001dc567-0e4b-45fd-9666-bc62839ca18e.png">
But DownloadFile has argument fileId that only int.
<img width="645" alt="image" src="https://user-images.githubusercontent.com/11912314/180663054-a94f358b-53e6-499f-ac66-3f0ce5cda147.png">
Maybe exists another way to download self avatar?

**Comment by levlam** [comment]
`chatPhoto` has a lot of `sizes`. You need to choose appropriate size and download the corresponding file.

**Comment by AnatoliyKozlov** [comment]
Thank you so much
