### ISSUE TITLE
API_ID_INVALID error with `use_test_dc` enabled

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#207]
Got API_ID_INVALID error when test_mode is enabled in tdlib.  In production environment everything ok

here are some logs - https://gist.github.com/zevlg/c5a2ad0d5f1ba807d4edf86583e4edac

what I'm doing wrong?

**Comment by levlam** [comment]
It means that test DC can't recognize the api_id or the api_hash. Probably it was down when the api_id was obtained and has no information about it, or something similar.
