### ISSUE TITLE
Bot falls asleep if there is no action from the user

### ISSUE THREAD

**Issue by Vitaljaz** [tdlib/td#2072]
I implemented a telegram bot to forward messages from one channel to another. I noticed that after the bot started working, for about two hours it works fast enough.

But, if there are no messages in the channel for a long time, the bot will go to "sleep", and will wake up only when a new notification arrives. I understand that he can go to sleep so as not to waste extra resources, but it takes a lot of time to wake up the bot. That is, there is a delay between the processing of messages, which can take more than 10 seconds.

Please tell me how to deal with this. Is it possible to turn off going to sleep?

**Comment by levlam** [comment]
There is nothing like "going to sleep" in TDLib, but it is expected to receive updates in channels with some delay.

**Comment by Vitaljaz** [comment]
And what affects this delay? Because after starting the program, the processing delay takes less than 1 second. And after some time of the program, this delay increases to 20-30 seconds?

**Comment by levlam** [comment]
The delay isn't expected to be less than 1 second, unless the user is an administrator in the channel, so it is hard to say, what could cause such unexpectedly small delay.
