### ISSUE TITLE
uploadFile response after a long time, also the upload speed slow

### ISSUE THREAD

**Issue by Yxue-1906** [tdlib/td#2073]
I'm tring to upload a sample file of 10MB, the first problem is I could only get the response form tdlib after at least 30s;
another question is that it stucked after uploading about 5MB, from the log I found tdlib encountered error like "FLOOD_WAIT_115", how can I avoid such error occurring? also, why tdlib not resume upload after 115 seconds?

**Comment by Yxue-1906** [comment]
> I'm tring to upload a sample file of 10MB, the first problem is I could only get the response form tdlib after at least 30s; another question is that it stucked after uploading about 5MB, from the log I found tdlib encountered error like "FLOOD_WAIT_115", how can I avoid such error occurring? also, why tdlib not resume upload after 115 seconds?

I'm using tdlib of e44418f2b

**Comment by Yxue-1906** [comment]
after consulting to some issues, I upgrade tdlib to the newest commit;
also after some tries, I found updateFile referring to file uploaded by uploadFile never set is_upload_completed to true, even from log it said remote_.uploaded_size equal to local_.downloaded_size; 
flood error occurred too often, I send a 10MB file could trigger flood error 4 times...

**Comment by levlam** [comment]
If you would receive "FLOOD_WAIT_115" for uplaod request, then the upload immediately failed and wasn't "stuck". Anyway, FLOOD_WAIT errors are returned by the server and there is no way to avoid them.

> I found updateFile referring to file uploaded by uploadFile never set is_upload_completed to true

This is expected behavior, because upload can't be completed before you send the file in a message. You must not use `uploadFile` for file uploading and directly use `sendMessage` or any other method for which you upload the file.

**Comment by levlam** [comment]
Test servers exist to test apps, in particular, to test handling of FLOOD_WAIT errors.

**Comment by Yxue-1906** [comment]
> Test servers exist to test apps, in particular, to test handling of FLOOD_WAIT errors.

well, got it.
thanks to your kind replies!

**Comment by Yxue-1906** [comment]
yet another question: what's the correct way resending message contain file triggered flood? should I extract file_id from returned message and resend with inputFileId, or just use inputFileLocal as the failed one? also, is the slow upload speed(~200K) related to test sever?

**Comment by Yxue-1906** [comment]
I tried send file with inputFileRemote, however I got error like "Need full local (or generate, or inactive remote) location for upload", what is the correct way using inputFileRemote?

**Comment by levlam** [comment]
Resending with `inputFileId` is the best way.

Test servers can have a lot of restrictions.

**Comment by Yxue-1906** [comment]
> Resending with `inputFileId` is the best way.
> 
> Test servers can have a lot of restrictions.

I'm tring the procedure like: get file_id by `uploadFile`, send 2 files with `inputFileId` in sendMessageAlbum, but this method failed; say the two files are `file1` and `file2`, I upload them with both priority set to 32, send them in a `sendMessageAlbum` with `inputFileId`, when receive flood error just wait exact second and resent; after resenting some times `file1` uploaded, `file2` had only several bytes left; the next time resent the message album file2 uploaded, but __file1 begun reupload__! Then this situation looped, the album never sent. What's the correct way handling flood in sending album? From log I found when at a time point `file1` uploaded, `file2` was uploading, actually `file1` had a remote_file_id aready.

**Comment by Yxue-1906** [comment]
> > Resending with `inputFileId` is the best way.
> > Test servers can have a lot of restrictions.
> 
> I'm tring the procedure like: get file_id by `uploadFile`, send 2 files with `inputFileId` in sendMessageAlbum, but this method failed; say the two files are `file1` and `file2`, I upload them with both priority set to 32, send them in a `sendMessageAlbum` with `inputFileId`, when receive flood error just wait exact second and resent; after resenting some times `file1` uploaded, `file2` had only several bytes left; the next time resent the message album file2 uploaded, but **file1 begun reupload**! Then this situation looped, the album never sent. What's the correct way handling flood in sending album? From log I found when at a time point `file1` uploaded, `file2` was uploading, actually `file1` had a remote_file_id aready.

here is the [log](https://github.com/tdlib/td/files/9249593/log.txt)

**Comment by levlam** [comment]
You never need to use `uploadFile`, just call `sendMessageAlbum` with whatever `inputFile` objects you pass to uploadFile`.

If you want to avoid flood errors, you should avoid using the test accounts in test DC.
