### ISSUE TITLE
Can a Premium subscription help avoid some account bans?

### ISSUE THREAD

**Issue by aofei** [tdlib/td#2075]
IIRC, if an account is active on an unofficial app (https://my.telegram.org/apps) for a long time, it could be identified as a "userbot" and banned for it. I'm curious if a Premium subscription can help people avoid getting banned for such reasons.

I've been a Premium subscriber since day one. Not because I need any premium features, but simply because I want to show some support to Telegram. So don't get me wrong, I'm not trying to abuse the system.

The reason I need something like a "userbot" is mainly because I want to write a program to help me automate things like persisting/filtering specific chats and messages. And the recently landed "Archive and Mute" feature isn't ideal for me because it doesn't recognize non-spam chats, so I plan to try to implement an improved version by using a server-side session. But I don't want to risk it, I don't want my account that I've used for years to be banned for this simple use. So I'm here looking for an official statement. Thanks! ❤️

**Comment by levlam** [comment]
Userbots aren't banned, just because they are userbots, but also Premium users aren't absolutely protected from accidental bans. In the very unlikely event of a wrong account ban, you can always contact recover@telegram.org and the account will be unbanned.

**Comment by aofei** [comment]
> Userbots aren't banned, just because they are userbots

Really glad to hear this, I think now I can do what I plan to do. 🙏

> you can always contact [recover@telegram.org](mailto:recover@telegram.org) and the account will be unbanned.

Just searched the web for this email address and it seems to have a bad reputation for being slow or non-responding. But anyway is better than nothing. Thanks for the heads up!

BTW, maybe Telegram should offer Premium users a special Support service. Or, you know, make the Premium user's ticket a higher priority than the regular user's. This's common on most paid services.

Thanks again for your reply! 😄
