### ISSUE TITLE
how to determine the connection state?

### ISSUE THREAD

**Issue by arpithavaddu** [tdlib/td#2076]
Hi there,

We need to determine if user's connection is live. For this is it correct to assume that once authorization step has finished the connection is live? and any updates on the connection state will be sent through updateConnectionState? 
Is there any other way to determine the connection state?

**Comment by levlam** [comment]
`updateConnectionState` can be used to show the user it's current connection state to Telegram servers. The update is suitable only for showing a human-readable description of the connection state though.
