### ISSUE TITLE
importContact correct usage

### ISSUE THREAD

**Issue by alexkolzov** [tdlib/td#2077]
Hello,
I started getting error 429 when calling importContacts. Is my account likely to be restricted? I am not a spammer and would like to know how to use this method safely. What frequency is allowed, etc.?

**Comment by levlam** [comment]
This is up to the server. Nothing can be done or predicted client-side.

**Comment by levlam** [comment]
> don't you think this behavior is wrong?

No, the behavior is correct. The only valid usage of `importContacts` is importing the contact list from the user's phone.
