### ISSUE TITLE
How can I send send reactions?

### ISSUE THREAD

**Issue by babakkhan375** [tdlib/td#2078]
How can I send reactions?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/blob/07b7faf66c1cc252d3ab0d3e540f46a15d432354/td/generate/scheme/td_api.tl#L5050

**Comment by babakkhan375** [comment]
> See
> 
> https://github.com/tdlib/td/blob/07b7faf66c1cc252d3ab0d3e540f46a15d432354/td/generate/scheme/td_api.tl#L5050

Thanks
