### ISSUE TITLE
send message with inputFileRemote return error "Need full local (or generate, or inactive remote) location for upload"

### ISSUE THREAD

**Issue by Yxue-1906** [tdlib/td#2079]
what is the correct way using `inputFileRemote`? I received this error under test env, and had not test on production servers.

**Comment by levlam** [comment]
This is described in the documentation of `inputFileRemote`: "The remote ID is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application".

You can't use remote location from `uploadFile`, even it is accidentally present.

**Comment by Yxue-1906** [comment]
oh, I got it.
By the way, will this limitation be removed when login as a bot?

**Comment by Yxue-1906** [comment]
> oh, I got it. By the way, will this limitation be removed when login as a bot?

I mean, I'm sure the message relating to the remote_id exists and can be accessed by the bot, in such situation must I load the corresponding message into tdlib before sending new messages using the remote_id, or just use it as http bot api?

**Comment by levlam** [comment]
Currently, bots can use `remote_id` directly.

**Comment by Yxue-1906** [comment]
> Currently, bots can use `remote_id` directly.

okay, thanks!
