### ISSUE TITLE
Make datacenters configurable

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#208]
Would it be possible to make datacenters configurable (in setTdLibParameters for example)? This would be really useful for writing automated tests and/or debugging.

**Comment by levlam** [comment]
What exactly you want to configure? All implementation details related to datacenters handling are expressly hidden, because correct handling of datacenters is much harder than it can be imagined. But probably processDcUpdate does what you need.

**Comment by levlam** [comment]
This is default addresses of datacenters. They are usually used only to establish the first connection to servers.

**Comment by x2bool** [comment]
Would be really nice to have that configurable.

**Comment by levlam** [comment]
This is unlikely to be done beyond use_test_dc parameter and processDcUpdate method. Making them configurable would be meaningful, only if a complete independent implementation for Telegram server will be run somewhere else and this isn't a case..

**Comment by x2bool** [comment]
> this isn't the case.

Yet.

Closing this for now.
