### ISSUE TITLE
Is the getRemoteFile() function really offline?

### ISSUE THREAD

**Issue by JoshX94** [tdlib/td#2080]
How does the getRemoteFile() function work exactly behind the scene? it's said to be "an offline request" in the documentation but I observed the following:

- I have use_file_database set to True
- I save the td.binlog file right after user login, storing it somewhere else
- I obtain a file.remote.id from the tdlib application
- I close the tdlib application and swap the td.binlog file with the snapshot that I saved before, which should have no data about any file
- I modify the application to do nothing but calling getRemoteFile() with the file.remote.id that I obtained before
- I launch the application, and I am able to get complete information of this file.

It seems like getRemoteFile is still making a call over the network from telegram server?

**Comment by levlam** [comment]
`getRemoteFile` does nothing except registering provided remote `file_id`. It doesn't guarantee that the created file can be downloaded, reused, or is valid for any other purpose.

**Comment by JoshX94** [comment]
Where exactly is the "registering" of a file_id and its remote_id happened? Within local tdlib instance or in telegram server?

For example, If I call downloadFile(file_id), does tdlib send the file_id as is to telegram server, or does tdlib convert the file_id in someway before sending it out because the server don't recognize it?

**Comment by levlam** [comment]
"Registering" is assigning a file identifier for the given TDLib launch, which can be used after that and is required, for example, for `downloadFile`.

Integer file identifiers are valid only for duration of the current TDLib launch.
