### ISSUE TITLE
Queries take too long to complete

### ISSUE THREAD

**Issue by nikolaykusch** [tdlib/td#2082]
I use tdjson in the MAUI Windows 10 project. All authorization requests before receiving "AuthorizationStateReady" work as they should. After receiving "AuthorizationStateReady", requests are executed for more than a minute. Also, tdJson heavily loads the processor. Checked through DotTrace - the result is on the screenshot. There is the basic initialization of the client when the user is already authorized. "SetTdlibParameters" and "CheckDatabaseEncryptionKey" are being sent, then nothing comes for more than a minute
![image](https://user-images.githubusercontent.com/2857804/183383757-3c9889d6-441f-40fd-8c27-d8f7c75c57fb.png)

**Comment by nikolaykusch** [comment]
When logging is enabled, everything works fine. If you disable logging again, requests are executed for a very long time and there is a heavy load on the CPU

**Comment by levlam** [comment]
This is not possible. TDLib logs can only slow down execution.

**Comment by nikolaykusch** [comment]
What is the default path for the log file? And what happens if there is no access to this file?

**Comment by levlam** [comment]
By default log is written to stderr, not a file.

If an unaccessible path is specified in `setLogStream`, then the method will return an error.

**Comment by nikolaykusch** [comment]
Apparently, MAUI for Windows has some problems with outputting logs to stderr. It is necessary to specify the path to the log file explicitly, then everything works as it should.
At least that fixed the problem for me.

**Comment by levlam** [comment]
This makes sense. You actually had logs enabled from the very beginning and writing data to stderr can be very slow if stderr is tied with a terminal.
