### ISSUE TITLE
getChatHistory error only for Telegram official chat 777000

### ISSUE THREAD

**Issue by JoshX94** [tdlib/td#2084]
I am using getChatHistory to get messages but getting the below error only for the Telegram Official chat with chat id = 777000

         {'code': 400, 'message': 'Invalid value of parameter from_message_id specified'}

the from_message_id that I pass in is larger than the max message id in the chat by 1, for example if the max message id in a chat is 12345 I would pass in the value 12346.
This has been working for every other chat, and it has been working before for the Telegram official chat before until today.

If I call getChatHistory() with the max message id, it works fine.

Additional note that might be relevant to the issue is that, I am also using an offset of -99 in order to get messages newer than from_message_id

**Comment by levlam** [comment]
The error message can't be wrong. You send an invalid request with an invalid from_message_id parameter. See https://core.telegram.org/tdlib/getting-started#getting-chat-messages for the correct way to get chat messages and ensure that you pass a message identifier received previously from TDLib to `getChatHistory` as `from_message_id`.

**Comment by JoshX94** [comment]
I was under the assumption that we can use any int53 number as the from_message_id.

But it sounds like if we use a from_message_id that doesn't belong to a message in this chat, there's no guarantee of validness?

**Comment by levlam** [comment]
> But it sounds like if we use a from_message_id that doesn't belong to a message in this chat, there's no guarantee of validness?

If there could be a message with the provided `from_message_id` in the chat, then it will work correctly.

**Comment by JoshX94** [comment]
Thank you
