### ISSUE TITLE
Missing /td/generate/auto/tlo/td_api.tlo

### ISSUE THREAD

**Issue by iamzrn** [tdlib/td#2085]
Hi,

I am trying to install TDLib, but I am facing a lot of issues. The last one that I am unavailable to solve happens when I am running the command in PowerShell: `cmake --build . --target install --config Release`

I am getting this error log:
`CMake Error at td/generate/cmake_install.cmake:55 (file):
    file INSTALL cannot find "C:/Users/MYPC/td/td/generate/auto/tlo/td_api.tlo": No error.
  Call Stack (most recent call first):
    cmake_install.cmake:39 (include)`

`C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: The command "setlocal [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmEnd [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Users\MYPC\td\build\install.vcxpr
oj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmErrorLevel [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: exit /b %1 [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmDone [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Users\MYPC\td\build\install.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\MYPC\td\build\install.vcxproj]`

Previously while executing `cmake -A Win32 -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..` I was facing this issue, 
`-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Error at tdutils/generate/CMakeLists.txt:28 (message):
  Could NOT find gperf.  Add path to gperf executable to PATH environment
  variable or specify it manually using GPERF_EXECUTABLE option, i.e.  'cmake
  -DGPERF_EXECUTABLE:FILEPATH="<path to gperf executable>"'.`

I managed to resolve it with manual install of gperf 3.1.

Any idea how to solve this one?

**Comment by levlam** [comment]
You didn't install dependencies required for TDLib building. Folow https://tdlib.github.io/td/build.html?language=Java and ensure that the following commands succeeded:
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
git checkout 1b1ae50e1a69f7c659bd7d731e80b358d21c86ad
./bootstrap-vcpkg.bat
./vcpkg.exe install gperf:x86-windows openssl:x86-windows zlib:x86-windows
cd ..
```
