### ISSUE TITLE
Can't access Channel data without being a member.

### ISSUE THREAD

**Issue by Rucadi** [tdlib/td#209]
Every time I try to get channel messages from a Channel using the channel_id, I get the error "chat not found". However, if I try the same while being a member of the channel, I can receive the messages just fine.

the petition is the following one:
` GetMessage { ChatId = chid, MessageId = chpost * 1048576 }`

I know it is possible because when I used Telethon (Another implementation of this lib for python) I was able to do this. Also, telegram official apps let you see the messages while not being a member.

I'm using the json client

Am I doing something wrong?

**Comment by Rucadi** [comment]
I found a working approach, call SearchPublicChat and then do the request, I would like to change a little the question, is it possible to do it without needing the chat name?, The name is mutable while the id isn't.

**Comment by levlam** [comment]
You can't use chat_id unless you managed to somehow find the chat. For chats where you aren't a member this can be done generally speaking only through searchPublicChat(s). If message_database is enabled in TDLib parameters, then after calling searchPublicChat once the chat can be used by chat_id in the future at any time.
