### ISSUE TITLE
TDLib stuck building in Docker container

### ISSUE THREAD

**Issue by taguniversalmachine** [tdlib/td#2090]
I am following the instructions given here
https://tdlib.github.io/td/build.html?language=Elixir
For building an Elixir server with a Telegram API endpoint.

Our Dockerfile contains these commands:

# syntax=docker/dockerfile:1
FROM ubuntu:latest as builder

# Install Docker

ENV DOCKER_BUILDKIT=1

RUN apt-get update

RUN apt-get install -y ca-certificates curl gnupg lsb-release

RUN mkdir -p /etc/apt/keyrings

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Install Ansible
RUN apt-get install -y python3-pip
RUN python3 -m pip -V
#RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#RUN python3 get-pip.py --user
RUN python3 -m pip install --user ansible

COPY etc/ansible/hosts /etc/hosts
# End Ansible

# Telegram
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake g++
RUN git clone https://github.com/tdlib/td.git
WORKDIR td
RUN rm -rf build
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
RUN cmake --build . --target install
RUN cd ..
RUN cd ..
RUN ls -l td/tdlib
# End Telegram

<img width="1392" alt="Screen Shot 2022-08-12 at 6 58 45 AM" src="https://user-images.githubusercontent.com/87055551/184349630-fbe9f22c-08fc-4cd7-a940-1de2c313d4b8.png">

It seems stuck because it ran all night without completing. Those look like pretty standard libraries so I'm not sure why it would be having a problem there, is there a way to get more information about what is failing? I didn't see any options in apt-get that would be helpful.

**Comment by levlam** [comment]
In your screenshot apt-get is stuck, so this can't be related to TDLib. You have issues with Docker or with network connection.

**Comment by taguniversalmachine** [comment]
You were right, something to do with running it inside IDEA, it works in a regular terminal. Thanks!

**Comment by taguniversalmachine** [comment]
Just in case anyone else comes up wit this problem, one of the libraries is asking for a time zone or something.

<img width="910" alt="Screen Shot 2022-08-12 at 7 48 57 AM" src="https://user-images.githubusercontent.com/87055551/184357280-1871c8b2-1e24-4501-836e-76526a6c26e4.png">
