### ISSUE TITLE
Incorrect result from getInstalledStickerSets - no video stickers

### ISSUE THREAD

**Issue by weirdo-neutrino** [tdlib/td#2091]
I have 196 sticker sets (archive ones do not count). By doing a request [`getInstalledStickerSets`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_installed_sticker_sets.html) I got only 193 sticker sets. The 3 sticker sets, that were missing, were video stickers from the Telegram winter [update](https://t.me/telegram/168). This is an example of a missing sticker set: https://t.me/addstickers/mgrshed.

I used `python-telegram` library function [`call_method`](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/client.py#L376), which did not interfere in the API call.

Some places in `tdlib`, which can be POI:
- [`StickerType`](https://github.com/tdlib/td/blob/0271bf0be0b8e010d2a3d498e29da67c28b27ce1/td/telegram/StickerType.h#L17) has three types: `Regular`, `Mask` and `CustomEmoji`.
- [`GetInstalledStickerSetsRequest`](https://github.com/tdlib/td/blob/0271bf0be0b8e010d2a3d498e29da67c28b27ce1/td/telegram/Td.cpp#L2014) stores `StickerType` and calls [`get_installed_sticker_sets`](https://github.com/tdlib/td/blob/9a469eef31db455e87780c4a4ee5cc48680ba8a7/td/telegram/StickersManager.cpp#L4399) , which in return calls several other functions, that use `StickerType`: [`load_installed_sticker_sets`](https://github.com/tdlib/td/blob/9a469eef31db455e87780c4a4ee5cc48680ba8a7/td/telegram/StickersManager.cpp#L4662), [`reload_installed_sticker_sets`](https://github.com/tdlib/td/blob/9a469eef31db455e87780c4a4ee5cc48680ba8a7/td/telegram/StickersManager.cpp#L2891), [`on_load_installed_sticker_sets_from_database`](https://github.com/tdlib/td/blob/9a469eef31db455e87780c4a4ee5cc48680ba8a7/td/telegram/StickersManager.cpp#L4687)

**Comment by levlam** [comment]
"Video stickers" is a sticker format, which is completely independent from sticker type. Sticker format doesn't affect returned sticker sets in any way. Could you send TDLib log with verbosity level 4 to https://t.me/tdlib_bot, if you can't still receive the sticker sets?

**Comment by weirdo-neutrino** [comment]
60'091 lines of logs for this amount of code. Do I send this nightmare anyway? 

```python
import time
from telegram.client import Telegram

def call_tg_method(name, params=None):
    resp = tg.call_method(name, params)
    time.sleep(0.5)
    resp.wait()
    if resp.error:
        print(resp.error_info)
    return resp.update

if __name__ == '__main__':
    tg = Telegram(
        api_id=*********,
        api_hash='********************************',
        phone='+****************',
        database_encryption_key='**********',
    )

    tg.login()

    call_tg_method('setLogVerbosityLevel', {
        'new_verbosity_level': 4,
    })

    sticker_infos = call_tg_method('getInstalledStickerSets', {
        'is_masks': False,
    })

    # I have 197 sticker sets but this prints 194
    # missing https://t.me/addstickers/mgrshed
    # missing https://t.me/addstickers/Patrick_Bateman
    # missing https://t.me/addstickers/gachi_tv
    # All are video sticker sets
    print(sticker_infos['set_count']) 

    tg.stop()
```

**Comment by levlam** [comment]
Yes. Wait 5 seconds before `tg.stop()` and send the log as a file to https://t.me/tdlib_bot.

**Comment by levlam** [comment]
> video stickers from the Telegram winter [update](https://t.me/telegram/168).

You use an old TDLib version 1.7.9, released 3 month before the mentioned update. There is no way it can return video sticker sets.

**Comment by weirdo-neutrino** [comment]
Ahhhh. I have never installed tdlib properly. I will file an issue to python-telegram later as this is how it is handled by the first glance:
https://github.com/alexander-akhmetov/python-telegram/tree/master/telegram/lib/linux

This one can be closed as solved.
Thank you.
