### ISSUE TITLE
how can i get sharelink ?

### ISSUE THREAD

**Issue by ThirdPrince** [tdlib/td#2095]
@levlam hi, i have groupId ,then I want to get shareLink ,not invitelink。what can i do?

**Comment by levlam** [comment]
You need to obtain `username` from `supergroup.username` and construct link `https://t.me/<username>`.

**Comment by bennysen** [comment]
@levlam What is the stuff of TdApi.TMeUrl?

**Comment by levlam** [comment]
It is only for official Android and iOS apps.

**Comment by ThirdPrince** [comment]
@levlam thanks.
