### ISSUE TITLE
Threading in WPF with TDLib 1.8

### ISSUE THREAD

**Issue by antonGritsenko** [tdlib/td#2096]
I do have the WPF application that do the very simple parsing of incoming messages and display them in the grid. Part of the process, for sure, is getting chats. It works just well with TDLib v.1.7.x, but few days ago I decide to upgraded the app to use the version 1.8.1, and now the GetChat method just stop working.

The message from the TDLib routed using simple `event` to the main window class. The event contains the message id and chat id. When message received in the main window, I'm getting the chat (_client is TDLib itself here, just for simplification):
```
private void OnNewMessageReceived(object sender, TelegramClient.NewMessageReceivedEventArgs e)
{
......
    var tdChat = await _client.ExecuteAsync(new TdApi.GetChat { ChatId = chatId });
}
```

and this part is never ending, so it looks like the thread blocking. 

So my question is: how to work with TDLib 1.8 regarding threading? Am I have to execute all TDLib code in the main WPF thread?

**Comment by levlam** [comment]
What TDLib wrapper do you use? `ExecuteAsync` isprovided by your wrapper and isn't an interface, provided by TDLib.

**Comment by antonGritsenko** [comment]
@levlam I'm bit confused. The `ExecuteAsync` is part of the `TdClient`, which part of the `packages\tdlib\1.8.1.1\lib\netstandard2.0\TdLib.dll` 

Am I in the wrong GitHub project?

I'm using following packages:
```
    <PackageReference Include="TDLib" Version="1.8.1.1" />
    <PackageReference Include="tdlib.native" Version="1.8.1" />
```

**Comment by levlam** [comment]
For `tdsharp` see https://github.com/egramtel/tdsharp/issues/28. It describes the cause of the issue, which was supposed to be fixed already.

Also. since TDLib 1.8 updates for all clients needs to be received in the same thread, which could affect `tdsharp` usage of TDLib.
