### ISSUE TITLE
 TdApi.SearchPublicChat and TdApi.SearchPublicChats 

### ISSUE THREAD

**Issue by ThirdPrince** [tdlib/td#2097]
@levlam i get a sharelink https://t.me/OmYYds ,the SearchPublicChats(https://t.me/OmYYds) no result,but SearchPublicChat(OmYYds) had result ,why?

There are some links. Which method can I use to get them accurately? Which method do you recommend?

**Comment by levlam** [comment]
Some chats can't be found through global search, for example, chats with pornographic content.

The methods are completely different and serve different purposes. You need to use the method, which is appropriate for your app.
