### ISSUE TITLE
Is there a prelogin/auto-log in option? Android

### ISSUE THREAD

**Issue by Tamada4a** [tdlib/td#2098]
I would like to know if there is any way to log in to your account in advance without constantly entering your phone, and then the confirmation code? Maybe you can somehow enter api_id or api_hash with my.telegram.org and log in to your account right away?

Or after login my session will be saved and then i can use it for auto-login?

**Comment by levlam** [comment]
The behavior is the same as in any other Telegram client.

**Comment by Tamada4a** [comment]
@levlam I don't quite know what you're talking about. Can you explain please?

**Comment by AYMENJD** [comment]
There is no auto-login. You can login using phone number or QR code in desktop.

After you login the session will be saved on your device just like any other official telegram client and you will not need to login again.

**Comment by Tamada4a** [comment]
@AYMENJD Ah, I get that. But can I somehow save the session so that by transferring the application to another device, I can immediately log in to my account, bypassing authorization?

**Comment by AYMENJD** [comment]
This may lead to losing the session.

**Comment by Tamada4a** [comment]
@AYMENJD Is there a way to save the session when transferring the application?

**Comment by AYMENJD** [comment]
You can login on the another device, by entering the phone number and the received in-app code if supported.

**Comment by Tamada4a** [comment]
@AYMENJD But this requires another device where I am authorized in telegram (there is no telegram on the device with my application)

**Comment by Tamada4a** [comment]
As I know, there is a Telethon in python and there is an autologin option using api_id and api_hash. Isn't there something like that in Java? Or if there is, then not in the official api?

**Comment by AYMENJD** [comment]
There is no such thing called "auto-login" in telegram.

API_ID and API_HASH are for accessing Telegram API.

**Comment by Tamada4a** [comment]
Sadly

Thank you very much for the answers!
