### ISSUE TITLE
Restrict who can create a private chat with me

### ISSUE THREAD

**Issue by karl0d** [tdlib/td#2099]
May I have a feature request for you? Can you add a privacy settings restricting who can create chat with me? I mean I'm getting lots of spam messages recently and it really frustrates me. I always report those people/userbots, but that feels useless since they are deleting their account few hours/days later anyway. So, I think restricting people from creating private chats might be the solution to this problem.

**Comment by karl0d** [comment]
I know it might be hard to implement since telegram have to be backward compatible with previous tdlib versions, but I think it's a serious problem that ruins user experience for some users.

**Comment by levlam** [comment]
> but that feels useless since they are deleting their account few hours/days later anyway.

They don't delete accounts themselves. The accounts are deleted by Telegram, often based on user reports, so the reports are very useful.

TDLib is a library for creating Telegram clients and the proposed feature must be implemented server-side first. You can suggest features for Telegram at https://suggestions.telegram.org/.
