### ISSUE TITLE
SearchUserByPhoneNumber different behavior

### ISSUE THREAD

**Issue by skryabinvi3107** [tdlib/td#2101]
Hello!
I have 2 sessions for different users.
I'm trying to find users by phone number using the function SearchUserByPhoneNumber.
Under one session I find people. Under the other - no. At the same time, both sessions do not know anything about these users. They are not in contacts. They never contacted them.

`Session1:
12:07:47.971 [Thread-4] INFO  Try find by number : 7916.......
[ 1][t 4][1660972068.095905542][ContactsManager.cpp:5741][#1][!Td]	Resolve phone number "7916......." to user 35........., but doesn't have it
12:07:48.097 [Thread-4] INFO  User found...
`

`Session2:
12:07:47.971 [Thread-4] INFO  Try find by number : 7916.......
12:07:48.097 [Thread-4] ERROR User not found... Error: "Not Found"
`

Can you please tell me what could be causing this behavior? What's the Difference?

P.S. Sorry for my English. I use google translator.

**Comment by levlam** [comment]
The server returned incorrect response. Could you send log with verbosity level 3 to @tdlib_bot?
