### ISSUE TITLE
Messages not being sent from Telegram-X (Android) to iOS

### ISSUE THREAD

**Issue by snai** [tdlib/td#2103]
Secret Chat between iOS (Telegram 8.9) and Android (Telegram-X 0.24.11) works only One-Way.
Messages from iOS (Partner A) to Android (Partner B) will be received normally.
Messages from B to A are not shown for A. 
A get‘s a notification about a new messages, but the message is not shown in the app.
When B is typing the message the information “… typing” is shown for A. 
The private key is equal for A and B.
The secret chat was already recreated and Telegram on iOS was reinstalled. Problem still persists.
Secret Chats with partners both on iOS work as expected.

See Bug reports at:
https://bugs.telegram.org/c/19900
https://github.com/TGX-Android/Telegram-X/issues/206

**Comment by levlam** [comment]
This should be fixed in Telegram iOS 9.0.

**Comment by MrDemous** [comment]
> This should be fixed in Telegram iOS 9.0.

It's fixed on latest Telegram X beta but Videos don't get delivered on secret chats when sent to iOS devices

**Comment by levlam** [comment]
Videos were fixed in the commit 6917d9c36f60264649f14701d407c33281877839, so the issue should be completely fixed for Telegram X beta, which uses a newer commit.
