### ISSUE TITLE
Is there a way to disable forwarding a message?

### ISSUE THREAD

**Issue by atiyka** [tdlib/td#2107]
When I send a file, using the inputMessageDocument as the message content, can I achieve somehow to disable forwarding this file on recipient's side?

**Comment by levlam** [comment]
Bots can use the parameter `messageSendOptions.protect_content` to disable forwarding of the file. Regular users can use `toggleChatHasProtectedContent` to disable forwarding for all messages in the chat.

**Comment by atiyka** [comment]
Great, thank you for your response!

**Comment by Kenanbatmaz2** [comment]
> When I send a file, using the inputMessageDocument as the message content, can I achieve somehow to disable forwarding this file on recipient's side?
