### ISSUE TITLE
How to get the title of the channel and group

### ISSUE THREAD

**Issue by bear-big-gd** [tdlib/td#2111]
I try to use the getChat method and get a "Chat not found" error, and I try to use "UpdateSupergroup/UpdateSupergroupFullInfo", the field does not contain "title"
Looking forward to reply, thank you

**Comment by levlam** [comment]
You can't use arbitrary identiifers, not previously received from TDLib. Where from did you get identifier of the channel/group?

**Comment by bear-big-gd** [comment]
Thank you very much for your reply, it has been solved, my understanding of tdlib is wrong!
