### ISSUE TITLE
I try build in NETBSD x86_64 but fail because there no gcc5-libs in ftp only gcc5-aux  is the gcc version too old to install

### ISSUE THREAD

**Issue by whp98** [tdlib/td#2115]
https://github.com/whp98/telegram-bot-api-build/runs/8171691464?check_suite_focus=true

 [ 98%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/ClientManager.cpp.o
  [ 98%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/HttpConnection.cpp.o
  [ 98%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/HttpStatConnection.cpp.o
  [ 98%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/Query.cpp.o
  [ 98%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/Stats.cpp.o
  [100%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/WebhookActor.cpp.o
  
  make[2]: stopped in /Users/runner/work/telegram-bot-api-build/telegram-bot-api-build/telegram-bot-api/build
  make[2]: don't know how to make /usr/pkg/gcc5/i486--netbsdelf/lib/libatomic.so. Stop
  *** Error code 2
  
  Stop.
  make[1]: stopped in /Users/runner/work/telegram-bot-api-build/telegram-bot-api-build/telegram-bot-api/build
  *** Error code 1

my build scipt 
https://github.com/whp98/telegram-bot-api-build/blob/test0.0.20220904.13/build-netbsd.sh

my action

https://github.com/whp98/telegram-bot-api-build/blob/test0.0.20220904.13/.github/workflows/build-binary-test-action.yml

**Comment by whp98** [comment]
fix by this code https://github.com/whp98/telegram-bot-api-build/commit/d44f06f294fa1d716d6f001cc1288e553639fadf#r83008784

**Comment by levlam** [comment]
The path to the `libatomic` library can be different for different NetBSD version. The current path is correct for NetBSD 8.0 x86, so it must be kept, but some other search locations can be added. What is your NetBSD version?

**Comment by whp98** [comment]
9.2

**Comment by whp98** [comment]
you can see details in the action

**Comment by whp98** [comment]
in ftp there is not a package named gcc5-libs only gcc5-aux

**Comment by levlam** [comment]
gcc5-aux can contain libatomic.so only accidentally. You can install gcc12-libs instead of gcc5-libs and change path to libatomic.so accordingly.

**Comment by levlam** [comment]
@whp98 Thank you for this issue. TDLib 1.8.6 will include updated build instructions, working out-of-the-box on NetBSD 8.x and 9.x with x86 or x86_64 architectures.

**Comment by whp98** [comment]
ok

**Comment by levlam** [comment]
Build instructions should work out-of-the-box on NetBSD 8.x and 9.x with x86 or x86_64 architectures now.
