### ISSUE TITLE
How to send a photo using td_send(Python)?

### ISSUE THREAD

**Issue by Loshara-coder** [tdlib/td#2117]
I tried sending a photo using only id but i guess it doesn't work like that, i also tried using remote id but it didn't work either. I looked into documentation and example files and there is nothing that can help me solve the issue

`td_send({'@type':'sendMessage', 'chat_id':target_chat_id, 'input_message_content': {
                            '@type': 'inputMessagePhoto',
                            'photo': {
                            'id': message_photo
                        }}}
                         )`

**Comment by Loshara-coder** [comment]
This is one that i tried with remote
`td_send({'@type':'sendMessage', 'chat_id':target_chat_id, 'input_message_content': {
                            '@type': 'inputMessagePhoto',
                            'photo': {
                            'remote': {
                            '@type': 'remoteFile',
                            'id': id
                        }}}}
                         )`

**Comment by AYMENJD** [comment]
That's wrong. `input_message_content.photo` must be [`inputFileRemote`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_remote.html).

I recommend you to start with: https://core.telegram.org/tdlib/getting-started.

**Comment by Loshara-coder** [comment]
> That's wrong. `input_message_content.photo` must be [`inputFileRemote`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_remote.html) in your case.
> 
> I recommend you to start with: https://core.telegram.org/tdlib/getting-started.

Thank you for helping i already worked out myself that my path to the remote id was wrong i also changed `remoteFile` to` InputFileRemote` and now everything works as it should
