### ISSUE TITLE
changing api id and api hash after autho

### ISSUE THREAD

**Issue by dsrana** [tdlib/td#2119]
Given an api id and api hash is used to authorise a user successfully for an application.
If after a while, the api id and hash is changed to use another valid one (from another number).
Should that cause any problems for the authorised user? I tried this and it worked as expected. But I wanted to verify still.

Thanks

**Comment by levlam** [comment]
Yes, the change can cause issues. The app isn't guaranteed to work after keys are changed.

**Comment by dsrana** [comment]
okay. Is there anything in the API to cater for changing the api id and hash? or is best to reauthorize the user with new api id and hash?

**Comment by levlam** [comment]
API ID is supposed to never change after authorization. It is safer to authorize the user again, despite something can work after API ID change.

**Comment by dsrana** [comment]
great, thank you 👍
