### ISSUE TITLE
password db.sqlite

### ISSUE THREAD

**Issue by pishnok** [tdlib/td#212]
Hello friends
I use this library in java
Where can I get this database **db.sqlite** password?

**Comment by levlam** [comment]
It is a random 256-bit string, stored encrypted in another file. There is no easy way to get it.

**Comment by mkliu** [comment]
@levlam which file is it? It'll be useful to get the password so we could explore db schema

**Comment by levlam** [comment]
It is somewhere inside td.binlog, but that information will not help you to get it. As I've said before, there is no easy way to get it. Also manual access to database may lead to unpredictable changes in TDLib behavior.

**Comment by mkliu** [comment]
Hmm, is the data in DB returned in a smart way? For example, if I try to get last 2 days' chat messages from a group chat, then later on I try to get last 7 days' messages, does it need to re-query last 2days' data from server again?

**Comment by levlam** [comment]
It will return messages from the local database if use_message_database TDLib parameter is set to true. If message database is enabled, then only unknown messages needs to be downloaded from the server.

**Comment by m9w** [comment]
Вon't have a solution yet? At least how to get the `auth_key` from the base?
