### ISSUE TITLE
Send nearby user

### ISSUE THREAD

**Issue by njfamirm** [tdlib/td#2122]
Hi

I found many users with `nearby`,
how can send messages to all users found?

**Comment by levlam** [comment]
You need to iterate through the users, create private chat with them and then send message to the chats. But you are likely to be banned soon if the users will report your messages.

**Comment by njfamirm** [comment]
ok, What is the limit for messaging new people?

**Comment by levlam** [comment]
Avvount can be banned even after the first message.

**Comment by njfamirm** [comment]
ok, thanks
