### ISSUE TITLE
PEER_FLOOD error!

### ISSUE THREAD

**Issue by njfamirm** [tdlib/td#2124]
```
[MessagesManager.cpp:30139][#9][!net_actor] Fail to send yet unsent message 0.1 in chat 98567614 with the error [Error : 400 : PEER_FLOOD]
```

why this error occurred when sending a message?
and how can handle it?

**Comment by njfamirm** [comment]
In general, how can you be sure that the message to Darsi has reached the user?

**Comment by levlam** [comment]
You need to handle `updateMessageSendSucceeded`, `updateMessageSendFailed`, and `updateDeleteMessages` updates to know whether a message was successfully sent, failed to send, or deleted before it was able to be sent.
