### ISSUE TITLE
Testing registration with tdlib built custom client

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2125]
Tdlib is a powerful tool to create custom clients, but trying to test registration for new user is very difficult. After I created an account how can I check if sign-in works? There is the possibility to use a developer mode with a demo backend to simulate registration process?

**Comment by levlam** [comment]
The authorization process is the same as in all other clients. You will receive `updateAuthorizationState` if authorization state is changed.

**Comment by Fra078** [comment]
I know, but for testing purposes of registration process (screens and behavior) there is a way to simulate it?

**Comment by levlam** [comment]
No. But you can use test DC, which has test accounts: https://core.telegram.org/api/auth#test-accounts.
