### ISSUE TITLE
Error with tdjni.dll

### ISSUE THREAD

**Issue by CrazyminerMC** [tdlib/td#213]
Hello,
I've been using the lib for a month and it's been two days that when I compile the Java Example I receive this error
`Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\Desktop\output\tdjni.dll: %1 is not a valid Win32 application` if I compile the 32bit version tdjni.dll
or the error `Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\Desktop\output\tdjni.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform` if I compile the 64bit version tdjni.dll
My processor is an Intel i5 7600k
I'm using the latest version of Java, Java 8 171
The IDE I'm using is IntelliJ Idea
Sorry for bad english

**Comment by levlam** [comment]
You probably have 32-bit OpenSSL or zlib dll, which is found before 64-bit one. In that case you need to copy 64-bit LIBEAY.dll, SSLEAY32.dll and zlib1.dll/zlibd1.dll to the folder containing tdjni.dll.

**Comment by levlam** [comment]
If you use vcpkg OpenSSL and zlib 64-bit dll's should be located at a path like `C:\src\vcpkg\installed\x64-windows\bin\` and `C:\src\vcpkg\installed\x64-windows\debug\bin\`.

**Comment by CrazyminerMC** [comment]
Thanks a lot, finally is working

**Comment by mostafa8026** [comment]
@CrazyminerMC  Could you please provide the solution which is worked for you?

**Comment by CrazyminerMC** [comment]
follow the instruction provided by levlam

**Comment by mostafa8026** [comment]
I found the solution in this issue: https://github.com/tdlib/td/issues/349#issuecomment-417461733
