### ISSUE TITLE
Connecting a TDJson client causes ton of warnings/errors 

### ISSUE THREAD

**Issue by zzw96** [tdlib/td#2130]
Hello,

We have a python service which connects to Telegram accounts via TDJson. 
Our steps for connecting clients:
* Create a TDJson client
* Send `setTdlibParameters`
* Send `checkDatabaseEncryptionKey`
* Subscribe to updates via TDJson's `client.receive`.

Everything seems to be working, however recently we've been seeing a constant stream of these two messages:
```
[1;31m[ 1][t12][1663294821.963675260][Session.cpp:400][#3][!Session:1:main]	BindKey failed: [Error : 400 : ENCRYPTED_MESSAGE_INVALID][0m
[1;33m[ 2][t16][1663292782.381464004][Session.cpp:367][#4][!Session:1:main]	Do not drop main key, because it was created too recently[0m
```

Seems like these might be warnings, but I'm curious why they started and if we can resolve them. The only change that occured on our end was that some clients were attempted to be created without sessions. However, this issue was fixed, but we're still getting these errors.

Could someone advise? Thanks!

**Comment by levlam** [comment]
The messages usually means that the client is already logged out by the server with an "AUTH_KEY_DROP_*" service notification. This happens when you manually copy `td.binlog` and try to use it simultaneously from different places. Is it the case?
