### ISSUE TITLE
Problems with TDLib building its own telegram

### ISSUE THREAD

**Issue by fendo8888** [tdlib/td#2131]
I want to develop a dedicated h5 version of the program based on telegram+vue.js. After browsing some information, I found that telegram provides api support for this. I encountered the following problems:
1. I found that TDLib can create its own telegram. I read the api's instructions for login/registration. SMS is required for verification. How to log in/register directly by using username and password? Without SMS verification Register; Login.

**Comment by levlam** [comment]
You can't use Telegram without an owned phone number.

**Comment by fendo8888** [comment]
> You can't use Telegram without an owned phone number.

If I create my own client, do I also need a mobile phone number to obtain a verification code for registration/login? I found that there are other telegram-based APPs that only use username and password to register and log in. What is the situation?

![image](https://user-images.githubusercontent.com/22114481/190834997-ad83a223-4efb-400f-a09a-3046ca5eca59.png)

![image](https://user-images.githubusercontent.com/22114481/190835011-ff6fab47-22bb-4a0f-b6fb-2dc4148f4936.png)

The following source code is the content after decompilation, you can see the tg related code

![image](https://user-images.githubusercontent.com/22114481/190835148-1481bb56-69b6-4498-9e10-df6769b1fc22.png)

<img width="397" alt="20220917092858" src="https://user-images.githubusercontent.com/22114481/190835244-2d598129-bc5a-4653-88f3-d421a91fe336.png">

**Comment by levlam** [comment]
These apps aren't related to Telegram.

**Comment by fendo8888** [comment]
> These apps aren't related to Telegram.

Does it matter? After I traced it, I found that he inherited TLObject and implemented two of his own (protocol or interface?) I want to understand, I don't know where to start, or is it a custom telegral protocol?

login

TL_auth_SignInByPassword

![image](https://user-images.githubusercontent.com/22114481/190854017-b260bbee-8f6d-4f9d-82fa-b7556d52883b.png)

![image](https://user-images.githubusercontent.com/22114481/190854127-95cee8a5-be73-473f-b157-7b52bd357f69.png)


register

TL_auth_SignUpV1

![image](https://user-images.githubusercontent.com/22114481/190854053-5453c1a1-c0cc-40ff-a462-4046db1d781e.png)

![image](https://user-images.githubusercontent.com/22114481/190854104-d5404f9c-9364-4dea-b219-252f48e62873.png)

**Comment by fendo8888** [comment]
He calls ConnectionsManager#native_init to initialize here and finally passes in a parameter

![image](https://user-images.githubusercontent.com/22114481/190857462-264d7723-8add-4f38-8cef-b8a3c530c0ef.png)
![image](https://user-images.githubusercontent.com/22114481/190857481-4c3b5d24-7c80-4390-b68c-0ab5c86da909.png)
![image](https://user-images.githubusercontent.com/22114481/190857499-afa0b316-11a1-4583-9e2a-57192545a656.png)

The 

[Telegram](https://github.com/DrKLO/Telegram/blob/abb896635f849a93968a2ba35a944c91b4978be4/TMessagesProj/src/main/java/org/telegram/tgnet/ConnectionsManager.java )

method in the official telegram repository does not have this parameter, which is a bit strange

`
public static native void native_init(int currentAccount, int version, int layer, int apiId, String deviceModel, String systemVersion, String appVersion, String langCode, String systemLangCode, String configPath, String logPath, String regId, String cFingerprint, String installer, String packageId, int timezoneOffset, long userId, boolean enablePushConnection, boolean hasNetwork, int networkType);
` 
It is estimated that this parameter plays a role. When calling the two custom ones, this parameter is passed in? I don't know what this parameter is used for. I searched around the Internet and couldn't find any instructions.

![image](https://user-images.githubusercontent.com/22114481/190857645-0578c212-0334-4715-b504-09f6554edcca.png)

![image](https://user-images.githubusercontent.com/22114481/190857695-2afe480f-b29d-4f00-a114-1f7f167a3673.png)

**Comment by levlam** [comment]
> Does it matter? 

Yes, the app isn't related to Telegram. You can't have Telegram account without a phone number.
