### ISSUE TITLE
How to get list devices

### ISSUE THREAD

**Issue by LazarenkoA** [tdlib/td#2139]
Hi, I don't know if the telegram API provides information on devices (the one that Settings->Devices menu), if it provides what method? 
The task is to control when I was last online under a certain device.

**Comment by levlam** [comment]
You can use `getActiveSessions` to receive the list of active sessions. The section "Active sessions" was renamed to "Devices" some time ago.

**Comment by LazarenkoA** [comment]
which method is used exactly in MTProto?

**Comment by LazarenkoA** [comment]
probably this method
https://core.telegram.org/method/account.getAuthorizations
