### ISSUE TITLE
TdLib GetChatMembers

### ISSUE THREAD

**Issue by MiguelMonster** [tdlib/td#2146]
I am trying to get the chat members for a given supergroup, and I was a bit confused about how the `memberId` is a `MessageSender`. This implies that it could be either a `MessageSenderChat` or a `MessageSenderUser`.

I checked the docs for [ChatMember](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_member.html), and the explanation for this is as follows:

> Identifier of the chat member. Currently, other chats can be only Left or Banned. Only supergroups and channels can have other chats as Left or Banned members and these chats must be supergroups or channels. 

I have a few questions about this:
1.  How can a chat be a member of another chat?
2. Why can we only see left or banned chats?
3. Does the use of the word 'currently' imply that in the future current members that are chats will be retrievable, an not just those that are past members?

**Comment by levlam** [comment]
> How can a chat be a member of another chat?

If you ask for members with the filter `chatMembersFilterBanned`, then you definitely can receive chats in response.

> Why can we only see left or banned chats?

There is no word "see" in the documentation. It states exactly that "Currently, other chats can be only Left or Banned. Only supergroups and channels can have other chats as Left or Banned members and these chats must be supergroups or channels."

**Comment by MiguelMonster** [comment]
Thanks for your quick response! To clarify, how can you actually ban a chat from a supergroup or channel? By the same token, how can a Telegram Chat be "left" from a supergroup/channel? Is it just if they have been blacklisted?

Also, due to the word "Currently" in the documentation, are there plans for you to be able to see current members who are chats in the future (if they can even be current members)?

**Comment by MiguelMonster** [comment]
Could you maybe provide an example of a chat being a member of another chat?

**Comment by levlam** [comment]
> To clarify, how can you actually ban a chat from a supergroup or channel? 
> Could you maybe provide an example of a chat being a member of another chat?

You can use `banChatMember` to ban any channel in any supergroup if the user have the corresponding administrator right. Then it will be received in the list of banned members.
