### ISSUE TITLE
application offline, message retrieval

### ISSUE THREAD

**Issue by dsrana** [tdlib/td#2148]
a few queries about messages missed when offline:

1. Does an application that uses tdlib get messages when it comes back online? E.g. it goes offline for a few hours, when it comes back online, will tdlib send it the messages it missed when it was offline?
1.1 does that depend on all these flags being true: use_message_database, use_chat_info_database, use_file_database 

2. if a user is authorised with the above database flags as false, and if in next restart when we reconnect user, we enable these to true, is that an expected workflow and will it work as expected?

**Comment by levlam** [comment]
TDLib will send most missed messages regardless of the used databased. There is an option "ignore_background_updates", which allows to skip the updates and can be enabled if all databases are disabled.

**Comment by dsrana** [comment]
What is the recommended config setting to receiving all messages, not missing a single one? For example, I would like my application to continue where it left off from, irrelevant of the time it was offline. It should continue to receive updates for all messages it missed, any groups user joined etc.

**Comment by levlam** [comment]
> What is the recommended config setting/approach to receiving all messages, not missing a single one?

This is not supported by Telegram apps.

**Comment by dsrana** [comment]
thank you for your prompt responses 👍

**Comment by dsrana** [comment]
sorry one more question, what is the purpose of these options then:  use_message_database, use_chat_info_database, use_file_database? What additional behaviour do they allow?
 
The description suggests it will cache it between restarts. Is that for performance?

**Comment by levlam** [comment]
They allow apps to work without internet access and to avoid downloading of the same files twice.
