### ISSUE TITLE
can tdlib based messaging application initiate a chat with a user or a group?

### ISSUE THREAD

**Issue by BHSenid** [tdlib/td#2149]
Hi All,

Could you plz tell me whether a message application which is built using tdlib can initiate a chat with a user or group?
If so could you plz share the documentation?

**Comment by levlam** [comment]
You can send a message to any chat, received from TDLib. But spam accounts are very likely to be immediately banned after that. You can find documentation at https://github.com/tdlib/td#examples-and-documentation.
