### ISSUE TITLE
Cmake java example error,

### ISSUE THREAD

**Issue by alon-sys** [tdlib/td#2150]
Administrator@DESKTOP-AAAAA /cygdrive/d/td/example/java/build
$ cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(readlink -e ../td/lib/cmake/Td) ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.16.27048.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at D:/td/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package):
  By not providing "FindTd.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "Td", but CMake did
  not find one.

  Could not find a package configuration file provided by "Td" with any of
  the following names:

    TdConfig.cmake
    td-config.cmake

  Add the installation prefix of "Td" to CMAKE_PREFIX_PATH or set "Td_DIR" to
  a directory containing one of the above files.  If "Td" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/td/example/java/build/CMakeFiles/CMakeOutput.log".

How can I solve it, thank you！！！

**Comment by levlam** [comment]
You have no TDLib installed at ../td/lib/cmake/Td. Check that the previous step `cmake --build . --target install --config Release` succeeded.

**Comment by alon-sys** [comment]
> 
The previous step has been installed and is successful

**Comment by alon-sys** [comment]
> You have no TDLib installed at ../td/lib/cmake/Td. Check that the previous step `cmake --build . --target install --config Release` succeeded.

The previous step has been installed and is successful

**Comment by levlam** [comment]
> The previous step has been installed and is successful

You also need to check that previous step installed TDLib for the same architecture an configuration. The error message tells exactly that the previous step failed to install needed binaries.

Do you have full console output for all build steps?

**Comment by alon-sys** [comment]
> > The previous step has been installed and is successful
> 
> You also need to check that previous step installed TDLib for the same architecture an configuration. The error message tells exactly that the previous step failed to install needed binaries.
> 
> Do you have full console output for all build steps?



Administrator@DESKTOP-AAAAA /cygdrive/d/td/build
$ cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.16.27048.0
-- The C compiler identification is MSVC 19.16.27048.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: optimized;D:/td/vcpkg/installed/x64-windows/lib/libcrypto.lib;debug;D:/td/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib (found version "1.1.1m")
-- Found OpenSSL: D:/td/vcpkg/installed/x64-windows/include optimized;D:/td/vcpkg/installed/x64-windows/lib/libssl.lib;debug;D:/td/vcpkg/installed/x64-windows/debug/lib/libssl.lib;optimized;D:/td/vcpkg/installed/x64-windows/lib/libcrypto.lib;debug;D:/td/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found Git: D:/PortableGit/cmd/git.exe (found version "2.35.1.windows.2")
-- Git state: 8ab43e5b9f26931f70ad07660850e39ab345a801
-- Found ZLIB: optimized;D:/td/vcpkg/installed/x64-windows/lib/zlib.lib;debug;D:/td/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- Found ZLIB: D:/td/vcpkg/installed/x64-windows/include optimized;D:/td/vcpkg/installed/x64-windows/lib/zlib.lib;debug;D:/td/vcpkg/installed/x64-windows/debug/lib/zlibd.lib
-- Found JNI: C:/Program Files/Java/jdk1.8.0_333/lib/jawt.lib
-- Found JNI: C:/Program Files/Java/jdk1.8.0_333/include;C:/Program Files/Java/jdk1.8.0_333/include/win32;C:/Program Files/Java/jdk1.8.0_333/include C:/Program Files/Java/jdk1.8.0_333/lib/jawt.lib;C:/Program Files/Java/jdk1.8.0_333/lib/jvm.lib
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
-- Could NOT find Readline (this is NOT an error)
-- Configuring done
-- Generating done
-- Build files have been written to: D:/td/build


Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
Does this error message matter?

**Comment by alon-sys** [comment]
> This is not an error.

  Building Custom Rule D:/td/CMakeLists.txt
  -- Install configuration: "Release"
  -- Installing: D:/td/build/../example/java/td/lib/tdjson.lib
  -- Installing: D:/td/build/../example/java/td/bin/tdjson.dll
  -- Installing: D:/td/build/../example/java/td/lib/tdjson_static.lib
  -- Installing: D:/td/build/../example/java/td/lib/tdjson_private.lib
  -- Installing: D:/td/build/../example/java/td/lib/tdclient.lib
  -- Installing: D:/td/build/../example/java/td/lib/tdcore.lib
  -- Installing: D:/td/build/../example/java/td/lib/tdapi.lib
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdutils.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdactor.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdnet.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdsqlite.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tddb.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdcore.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdclient.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdapi.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdjson_private.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdjson.pc
  -- Installing: D:/td/build/../example/java/td/lib/pkgconfig/tdjson_static.pc
  -- Installing: D:/td/build/../example/java/td/lib/cmake/Td/TdTargets.cmake
  -- Installing: D:/td/build/../example/java/td/lib/cmake/Td/TdTargets-release.cmake
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/td_json_client.h
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/td_log.h
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/tdjson_export.h
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/Client.h
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/Log.h
  -- Installing: D:/td/build/../example/java/td/include/td/tl/TlObject.h
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/td_api.h
  -- Installing: D:/td/build/../example/java/td/include/td/telegram/td_api.hpp
  -- Installing: D:/td/build/../example/java/td/include/td/tl/tl_jni_object.h
  -- Up-to-date: D:/td/build/../example/java/td/bin
  -- Installing: D:/td/build/../example/java/td/bin/libcrypto-1_1-x64.dll
  -- Installing: D:/td/build/../example/java/td/bin/libssl-1_1-x64.dll
  -- Up-to-date: D:/td/build/../example/java/td/bin/tdjson.dll
  -- Installing: D:/td/build/../example/java/td/bin/zlib1.dll
  -- Installing: D:/td/build/../example/java/td/lib/cmake/Td/TdConfig.cmake
  -- Installing: D:/td/build/../example/java/td/lib/cmake/Td/TdConfigVersion.cmake
  -- Installing: D:/td/build/../example/java/td/lib/tdutils.lib
  -- Installing: D:/td/build/../example/java/td/bin/td_generate_java_api.exe
  -- Installing: D:/td/build/../example/java/td/bin/td/generate/JavadocTlDocumentationGenerator.php
  -- Installing: D:/td/build/../example/java/td/bin/td/generate/TlDocumentationGenerator.php
  -- Installing: D:/td/build/../example/java/td/bin/td/generate/scheme/td_api.tlo
  -- Installing: D:/td/build/../example/java/td/bin/td/generate/scheme/td_api.tl
  -- Installing: D:/td/build/../example/java/td/lib/tdactor.lib
  -- Installing: D:/td/build/../example/java/td/lib/tdnet.lib
  -- Installing: D:/td/build/../example/java/td/lib/tdsqlite.lib
  -- Installing: D:/td/build/../example/java/td/lib/tddb.lib


cmake --build . --target install --config Release

This is the result without any errors

**Comment by alon-sys** [comment]
It has been solved. Before doing this operation(cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) ..), use Cygwin, and then use PowerShell, Cygwin and PowerShell to compile alternately.
My system is windows 11

**Comment by levlam** [comment]
What is output of `$(readlink -e ../td/lib/cmake/Td)` on your system?

**Comment by alon-sys** [comment]
> What is output of `$(readlink -e ../td/lib/cmake/Td)` on your system from `build/example/java` directory?

According to the official documentation, these paths have not been changed, and the above operation method has been successfully compiled.
Thank you very much for your prompt reply
