### ISSUE TITLE
_ZNSt19_Sp_make_shared_tag5_S_egERKSt9type_info

### ISSUE THREAD

**Issue by aisthetes** [tdlib/td#2151]
Build it on windows 11 and when try using [php-ffi-tdlib](https://github.com/aurimasniekis/php-ffi-tdlib) recive:

The procedure entry point _ZNSt19_Sp_make_shared_tag5_S_egERKSt9type_info could not be located in dynamic link library C:\WINDOWS\SYSTEM32\libtdjson.dll

Any idea?

**Comment by levlam** [comment]
Did you build TDLib on the same machine?

**Comment by aisthetes** [comment]
@levlam yes

**Comment by levlam** [comment]
Why is the library located in C:\WINDOWS\SYSTEM32? It is much better to copy the library and all other dependent libraries to the working directory of your app.

**Comment by aisthetes** [comment]
@levlam if change folder same error. Maybe need copy not only libtdjson.dll?

**Comment by aisthetes** [comment]
Maybe problem in build:

`[182/428] Building CXX object CMakeFiles/tdcore.dir/td/telegram/SecretChatActor.cpp.obj
In file included from D:/_www/tdlib/td/telegram/SecretChatActor.h:12,
                 from D:/_www/tdlib/td/telegram/SecretChatActor.cpp:7:
In static member function 'static td::log_event::EncryptedInputFile td::log_event::EncryptedInputFile::from_input_encrypted_file(const td::telegram_api::InputEncryptedFile&)',
    inlined from 'static td::log_event::EncryptedInputFile td::log_event::EncryptedInputFile::from_input_encrypted_file(td::tl_object_ptr<td::telegram_api::InputEncryptedFile>&)' at D:/_www/tdlib/td/telegram/logevent/SecretChatEvent.h:181:37,
    inlined from 'void td::SecretChatActor::on_outbound_send_message_result(td::NetQueryPtr, td::Promise<td::ObjectPool<td::NetQuery>::OwnerPtr>)' at D:/_www/tdlib/td/telegram/SecretChatActor.cpp:1615:90:
D:/_www/tdlib/td/telegram/logevent/SecretChatEvent.h:189:88: warning: array subscript 'const td::telegram_api::inputEncryptedFileUploaded[0]' is partly outside array bounds of 'unsigned char [24]' [-Warray-bounds]
  189 |         return EncryptedInputFile{Uploaded, uploaded.id_, 0, uploaded.parts_, uploaded.key_fingerprint_};
      |                                                                               ~~~~~~~~~^~~~~~~~~~~~~~~~


In file included from D:/_www/tdlib/td/generate/auto/td/telegram/telegram_api.h:3,
                 from D:/_www/tdlib/td/telegram/EncryptedFile.h:9,
                 from D:/_www/tdlib/td/telegram/SecretChatActor.h:10:
In function 'td::tl_object_ptr<Type> td::make_tl_object(Args&& ...) [with Type = telegram_api::inputEncryptedFile; Args = {long long int&, long long int&}]',
    inlined from 'void td::SecretChatActor::on_outbound_send_message_result(td::NetQueryPtr, td::Promise<td::ObjectPool<td::NetQuery>::OwnerPtr>)' at D:/_www/tdlib/td/telegram/SecretChatActor.cpp:1616:63:
D:/_www/tdlib/td/tl/TlObject.h:203:30: note: object of size 24 allocated by 'operator new'
  203 |   return tl_object_ptr<Type>(new Type(std::forward<Args>(args)...));
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


[315/428] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/binlog/BinlogEvent.cpp.obj
In file included from D:/_www/tdlib/tdutils/td/utils/Storer.h:13,
                 from D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.h:15,
                 from D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.cpp:7:
In member function 'void td::TlStorerUnsafe::store_binary(const T&) [with T = int]',
    inlined from 'void td::TlStorerUnsafe::store_int(td::int32)' at D:/_www/tdlib/tdutils/td/utils/tl_storers.h:35:24,
    inlined from 'static td::BufferSlice td::BinlogEvent::create_raw(td::uint64, td::int32, td::int32, const td::Storer&)' at D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.cpp:56:22:
D:/_www/tdlib/tdutils/td/utils/tl_storers.h:30:16: warning: writing 4 bytes into a region of size 1 [-Wstringop-overflow=]
   30 |     std::memcpy(buf_, &x, sizeof(T));
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~


In member function 'void td::TlStorerUnsafe::store_binary(const T&) [with T = long long int]',
    inlined from 'void td::TlStorerUnsafe::store_long(td::int64)' at D:/_www/tdlib/tdutils/td/utils/tl_storers.h:39:24,
    inlined from 'static td::BufferSlice td::BinlogEvent::create_raw(td::uint64, td::int32, td::int32, const td::Storer&)' at D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.cpp:57:23:
D:/_www/tdlib/tdutils/td/utils/tl_storers.h:30:16: warning: writing 8 bytes into a region of size 0 [-Wstringop-overflow=]
   30 |     std::memcpy(buf_, &x, sizeof(T));
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~


In member function 'void td::TlStorerUnsafe::store_binary(const T&) [with T = int]',
    inlined from 'void td::TlStorerUnsafe::store_int(td::int32)' at D:/_www/tdlib/tdutils/td/utils/tl_storers.h:35:24,
    inlined from 'static td::BufferSlice td::BinlogEvent::create_raw(td::uint64, td::int32, td::int32, const td::Storer&)' at D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.cpp:58:22:
D:/_www/tdlib/tdutils/td/utils/tl_storers.h:30:16: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]
   30 |     std::memcpy(buf_, &x, sizeof(T));
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~


In member function 'void td::TlStorerUnsafe::store_binary(const T&) [with T = int]',
    inlined from 'void td::TlStorerUnsafe::store_int(td::int32)' at D:/_www/tdlib/tdutils/td/utils/tl_storers.h:35:24,
    inlined from 'static td::BufferSlice td::BinlogEvent::create_raw(td::uint64, td::int32, td::int32, const td::Storer&)' at D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.cpp:59:22:
D:/_www/tdlib/tdutils/td/utils/tl_storers.h:30:16: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]
   30 |     std::memcpy(buf_, &x, sizeof(T));
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~


In member function 'void td::TlStorerUnsafe::store_binary(const T&) [with T = long long int]',
    inlined from 'void td::TlStorerUnsafe::store_long(td::int64)' at D:/_www/tdlib/tdutils/td/utils/tl_storers.h:39:24,
    inlined from 'static td::BufferSlice td::BinlogEvent::create_raw(td::uint64, td::int32, td::int32, const td::Storer&)' at D:/_www/tdlib/tddb/td/db/binlog/BinlogEvent.cpp:60:23:
D:/_www/tdlib/tdutils/td/utils/tl_storers.h:30:16: warning: writing 8 bytes into a region of size 0 [-Wstringop-overflow=]
   30 |     std::memcpy(buf_, &x, sizeof(T));
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~


[428/428] Linking CXX executable tg_cli.exe`

**Comment by levlam** [comment]
Those are just false positive warnings and doesn't affect anything. But you seems to use gcc from MinGW instead of MSVC, so it is hard to tell, what is exactly wrong. Between, what's exact version of the compiler?

**Comment by aisthetes** [comment]
@levlam gcc version 12.2.0 (Rev1, Built by MSYS2 project)

**Comment by levlam** [comment]
> gcc version 12.2.0 (Rev1, Built by MSYS2 project)

It is very strange that you see the warnings. The `stringop-overflow` warning is explicitly disabled for GCC 12+ in CMakeLists.txt, because it warns solely about the correct code.

Anyway, I would suggest to switch to MSVC and follow https://tdlib.github.io/td/build.html?language=PHP.

**Comment by aisthetes** [comment]
@levlam now its work, thanks!
