### ISSUE TITLE
Valid api_id must be provided

### ISSUE THREAD

**Issue by PaperPlane28** [tdlib/td#2155]
I can normally use tdjson in version 1.8.5 of tdlib, but in version 1.8.6 I am prompted "Valid api_id must be provided". How can I solve this problem?

**Comment by ChristianB86** [comment]
I can confirm the issue. I'm using tdjson in c++ and setup the parameters with this json-string:
`{
  "@type": "setTdlibParameters",
  "parameters": {
    "database_directory": "xyz",
    "use_message_database": 1,
    "use_secret_chats": 1,
    "api_id": 12345,
    "api_hash": "abcde12345",
    "system_language_code": "en",
    "device_model": "Desktop",
    "application_version": "2.0",
    "enable_storage_optimizer": 1
  }
}`

I get this error right after sending the string with td_send:

> [ 3][t 4][1664643717.633993625][Td.cpp:2947][#1][!Td][&td_requests]	Receive request 3: setTdlibParameters {
>   use_test_dc = false
>   database_directory = ""
>   files_directory = ""
>   database_encryption_key = bytes [0] { }
>   use_file_database = false
>   use_chat_info_database = false
>   use_message_database = false
>   use_secret_chats = false
>   api_id = 0
>   api_hash = ""
>   system_language_code = ""
>   device_model = ""
>   system_version = ""
>   application_version = ""
>   enable_storage_optimizer = false
>   ignore_file_names = false
> }
> [ 3][t 4][1664643717.634454488][Td.cpp:4014][#1][!Td][&td_requests]	Sending error for request 3: error { code = 400 message = "Valid api_id must be provided. Can be obtained at https://my.telegram.org" }

**Comment by PaperPlane28** [comment]
> 我可以确认问题。我在 C++ 中使用 tdjson 并使用这个 json-string 设置参数： `{ "@type": "setTdlibParameters", "parameters": { "database_directory": "xyz", "use_message_database": 1, "use_secret_chats": 1, "api_id": 12345, "api_hash": "abcde12345", "system_language_code": "en", "device_model": "Desktop", "application_version": "2.0", "enable_storage_optimizer": 1 } }`
> 
> 使用 td_send 发送字符串后，我立即收到此错误：
> 
> > [3][t 4][1664643717.633993625][Td.cpp:2947][ #1 ][!Td][&td_requests] 接收请求 3：setTdlibParameters { 
> > use_test_dc = false 
> > database_directory = "" 
> > files_directory = "" 
> > database_encryption_key = bytes [0 ] { } 
> > use_file_database = false 
> > use_chat_info_database = false 
> > use_message_database = false 
> > use_secret_chats = false 
> > api_id = 0 
> > api_hash = "" 
> > system_language_code = "" 
> > device_model = "" 
> > system_version = "" 
> > application_version = "" 
> > enable_storage_optimizer = false 
> > ignore_file_names = false 
> > } 
> > [3] [t 4][1664643717.634454488][Td.cpp:4014][ #1][!Td][&td_requests] 请求 3 发送错误：错误 { code = 400 message = "必须提供有效的 api_id。可在https://my.telegram.org获得" }

Is this an official TD question

**Comment by levlam** [comment]
Authorization flow was significantly changed in TDLib 1.8.6: two new authorization states were added, one authorization state was removed, and `setTdlibParameters` request was changed. See https://github.com/tdlib/td/blob/8ab43e5b9f26931f70ad07660850e39ab345a801/td/generate/scheme/td_api.tl#L77-L119 for up-to-date scheme for authorization states in TDLib 1.8.6 and https://github.com/tdlib/td/blob/8ab43e5b9f26931f70ad07660850e39ab345a801/td/generate/scheme/td_api.tl#L4619-L4678 for methods to be used during authorization.

**Comment by ChristianB86** [comment]
Changed the json-string to:

> {
>   "@type": "setTdlibParameters",
>   "use_test_dc": false,
>   "database_directory": "xyz",
>   "file_directory": "",
>   "use_file_database": false,
>   "use_chat_info_database": false,
>   "use_message_database": 1,
>   "use_secret_chats": 1,
>   "api_id": 12345,
>   "api_hash": "abcdef12345",
>   "system_language_code": "en",
>   "device_model": "Desktop",
>   "system_version": "",
>   "application_version": "2.0",
>   "enable_storage_optimizer": 1,
>   "ignore_file_names": false
> }

Now the error is solved. Thank you

**Comment by PaperPlane28** [comment]
> Authorization flow was significantly changed in TDLib 1.8.6: two new authorization states were added, one authorization state was removed, and `setTdlibParameters` request was changed. See
> 
> https://github.com/tdlib/td/blob/8ab43e5b9f26931f70ad07660850e39ab345a801/td/generate/scheme/td_api.tl#L77-L119
> 
> for up-to-date scheme for authorization states in TDLib 1.8.6 and
> https://github.com/tdlib/td/blob/8ab43e5b9f26931f70ad07660850e39ab345a801/td/generate/scheme/td_api.tl#L4619-L4678
> 
> for methods to be used during authorization.

Thanks for your help

**Comment by PaperPlane28** [comment]
> Changed the json-string to:
> 
> > {
> > "@type": "setTdlibParameters",
> > "use_test_dc": false,
> > "database_directory": "xyz",
> > "file_directory": "",
> > "use_file_database": false,
> > "use_chat_info_database": false,
> > "use_message_database": 1,
> > "use_secret_chats": 1,
> > "api_id": 12345,
> > "api_hash": "abcdef12345",
> > "system_language_code": "en",
> > "device_model": "Desktop",
> > "system_version": "",
> > "application_version": "2.0",
> > "enable_storage_optimizer": 1,
> > "ignore_file_names": false
> > }
> 
> Now the error is solved. Thank you

Thanks for your help

**Comment by andrey882006** [comment]
Hello. Please tell me who has already worked with the stdlib library? Because I have such a problem: after authorization (at the end writes {"@type":"ok"}), I'm trying to send a request like: {"@type":"SendMessage","chat_id":"-1001628740950","input_message_content":{"@type":"inputMessageText","text":{"@type":"FormattedText","text":"Hello!"}}}
However , when listening to the response I get {"@type":"updateOption","name":"message_text_length_max","value":{"@type":"optionValueInteger","value":"4096"}}

If I listen to the answer again, I get for example:
{"@type":"updateOption","name":"suggested_video_note_video_bitrate","value":{"@type":"optionValueInteger","value":"1000"}}

And so on.. That is, the request does not work, but it does not issue any error, it constantly sends some kind of @type":"updateOption" with different parameters.

Please tell me who knows what's wrong? And how should this library work in general?)

**Comment by AYMENJD** [comment]
@andrey882006 You are not correctly handling updates.

See: https://core.telegram.org/tdlib/getting-started.

**Comment by andrey882006** [comment]
> Изменил строку json на:
> 
> > { 
> > "@type": "setTdlibParameters", 
> > "use_test_dc": ложь, 
> > "database_directory": "xyz", 
> > "file_directory": "", 
> > "use_file_database": ложь, 
> > "use_chat_info_database": ложь, 
> > "use_message_database": 1, 
> > "use_secret_chats": 1 , 
> > "api_id": 12345, 
> > "api_hash": "abcdef12345", 
> > "system_language_code": "en", 
> > "device_model": "Desktop", 
> > "system_version": "", 
> > "application_version": "2.0", 
> > "enable_storage_optimizer": 1, 
> > "ignore_file_names": ложь 
> > }
> 
> Теперь ошибка устранена. Спасибо

Hello, I see you already have experience working with the tdlib library. Could you please suggest such a problem: after authorization (at the end writes {"@type":"ok"}), I'm trying to send a request like: {"@type":"SendMessage","chat_id":"-1001628740950","input_message_content":{"@type":"inputMessageText","text":{"@type":"FormattedText","text":"Hello!"}}}
However , when listening to the response I get {"@type":"updateOption","name":"message_text_length_max","value":{"@type":"optionValueInteger","value":"4096"}}

If I listen to the answer again, I get for example:
{"@type":"updateOption","name":"suggested_video_note_video_bitrate","value":{"@type":"optionValueInteger","value":"1000"}}

And so on.. That is, the request does not work, but it does not issue any error, it constantly sends some kind of @type":"updateOption" with different parameters.

Please tell me who knows what's wrong? And how should this library work in general?

**Comment by AYMENJD** [comment]
@andrey882006  The wrong that you are not correctly handling updates.

Each time you call `td_receive` you get an unprocessed update or response to a sent request using `td_send`. And the mentioned updates are unprocessed updates. You must loop through `td_receive` to process all updates and responses.

**Comment by andrey882006** [comment]
> @andrey882006 Ошибка в том, что вы неправильно обрабатываете обновления.
> 
> Каждый раз, когда вы звоните, `td_receive`вы получаете необработанное обновление или ответ на отправленный запрос с использованием `td_send`. И упомянутые обновления являются необработанными обновлениями. Вы должны выполнить цикл `td_receive`для обработки всех обновлений и ответов.
> 
> При инициализации TDLib может отправить ряд важных обновлений, таких как `updateOption`обновления.

OK, tell me, the first time I listen, instead of authorization data, the library gives me the answer: {"@type":"updateOption","name":"version","value":{"@type":"optionValueString","value":"1.7.9"}}

Is this normal at all? And if so, how do I handle this update?

**Comment by AYMENJD** [comment]
@andrey882006 Yes, it's normal because you didn't process that update.

Everything is described in docs: https://core.telegram.org/tdlib/getting-started

TDLib usage examples are here: https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples
