### ISSUE TITLE
tdjson

### ISSUE THREAD

**Issue by PaperPlane28** [tdlib/td#2156]
What is the acquisition frequency and message sending frequency of tdjson？

**Comment by levlam** [comment]
It is up to server and unrelated to tdjson.

**Comment by PaperPlane28** [comment]
Thank you for your help.
 How many milliseconds can I send or receive a new message?
0ms or 100ms? = =

 @levlam

**Comment by levlam** [comment]
This is up to the server.

**Comment by PaperPlane28** [comment]
ok，Thank you for your help.
