### ISSUE TITLE
TDlib bot handling

### ISSUE THREAD

**Issue by hmartinh** [tdlib/td#216]
Hello!
TDlib can handle telegram bots, but is it just wrapper for existing bot api or  I can use any "Telegram API" method and not only handle updates?

**Comment by greyyoung** [comment]
Hi @levlam I want to know which method can be used by bot. But API doc seems not point out. How can I find bot method? Thanks.

**Comment by levlam** [comment]
It isn't documented anywhere to reduce documentation size. To check whether specific method is available for bots, you can look in the source code of [Td.cpp](https://github.com/tdlib/td/blob/master/td/telegram/Td.cpp) and check, whether corresponding on_request method has no "CHECK_IS_USER();".

**Comment by greyyoung** [comment]
@levlam Ok，Thanks.

**Comment by zelenin** [comment]
I parse it to json schema
https://github.com/zelenin/go-tdlib/blob/c780ca35c418c009606df33a9bfea6c29bdfea4b/data/td_api.json#L10632
That's functions with type 1 (common) and type 3 (only bot)
