### ISSUE TITLE
I need built tdlib.dll for Windows

### ISSUE THREAD

**Issue by willowTank** [tdlib/td#2161]
Hello Everyone, 
I failed to build this source on my PC, 
Can anyone help me to send me built files?
Thank you

**Comment by levlam** [comment]
It is impossible to use random prebuilt TDLib version. Your code will require some specific TDLib version and you will need to update it regularly to keep it correctly working with new Telegram features.

Did you follow https://tdlib.github.io/td/build.html? What exactly didn't work out?
