### ISSUE TITLE
namespace "td::td_api" has no member "authorizationStateWaitEncryptionKey"

### ISSUE THREAD

**Issue by tbthek** [tdlib/td#2162]
After I build this TDLib in my PC(Windows X64), I use this TDlib, and configurated my VS2019, but when I want to run the example , there were tow many errors, such as namespace "td::td_api" has no member "authorizationStateWaitEncryptionKey", namespace "td::td_api" has no member "checkDatabaseEncryptionKey", namespace "td::td_api" has no member "tdlibParameters", and so on.

  I searched those problem in Google, but I dont't found any answer or information about this.

  Can any one tell me how to solve those problems? Thanks.

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/2155#issuecomment-1264474111.

**Comment by tbthek** [comment]
Thanks for your help.
