### ISSUE TITLE
Is there a way to get the shared resources in a chat?

### ISSUE THREAD

**Issue by atiyka** [tdlib/td#2163]
Hi,
if I open a user/group/channel info in the official telegram app, I can see a summary about the shared files:
![image](https://user-images.githubusercontent.com/9460253/194325601-8dbff3a6-57ef-4664-ae53-fb789825211d.png)

Is there a way to get this data from tdlib?
I already checked [BasicGroupFullInfo](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1basic_group_full_info.html) and the [UserFullInfo](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1user_full_info.html), but it doesn't contain any information like this.

**Comment by levlam** [comment]
You can use `getChatMessageCount` and `getGroupsInCommon` to receive the counters.

**Comment by atiyka** [comment]
Great, thank you!
