### ISSUE TITLE
Getting updates about the subscriber counter in channels and chats

### ISSUE THREAD

**Issue by wh3r3areyou** [tdlib/td#2164]
Hi, tnx for work. How can I track changes in the number of subscribers in channels/chats using updates? When subscribing and unsubscribing from the channel, `updateSuperGroup` or `updateBasicGroup` updates do not come. There is even an `updateChatOnlineMemberCount`, but there is not just an `updateChatMemberCount`

**Comment by levlam** [comment]
You can't.

**Comment by wh3r3areyou** [comment]
That is, there is no way to track changes in the number of subscribers in the channels? Okay, and if you call the `GetSupergroupFullInfo` method (because there is a field about the number of subscribers in the SuperGroup structure), will timeout occur in requests?

**Comment by levlam** [comment]
You can be definitely limited if a lot of requests are sent.

**Comment by wh3r3areyou** [comment]
Maybe you have any ideas about getting subscribers not only to your channels, but also to others? Thank you for your help

**Comment by levlam** [comment]
There is no intended way for this.

**Comment by wh3r3areyou** [comment]
Okay, got it, thanks for the information
