### ISSUE TITLE
Is there any way to preserve authentication when your IP address changes?

### ISSUE THREAD

**Issue by mikhailvaliev** [tdlib/td#2167]
My application is using tdlib and we deploy it in a docker container. Each time deployment happens a new docker image is built and application changes its host ip address. This leads to a necessity to manually reenter telegram authentication code on each deployment which I want to avoid.

What I noticed, however, is when you are using regular telegram client on your device and that device changes its IP address (e.g you move to another country with your phone in your pocket) - you are not required to login again. How can I implement that mechanism with tdlib? And is there any way to convince telegram server that a newly built docker image is the same device as previously built docker image?  I have a guess that maybe if you preserve the files from "databaseDirectory" from TdApi.TdlibParameters that could work?

**Comment by levlam** [comment]
There is no way to "copy" authorization. You must keep the whole state of "databaseDirectory" and "filesDirectory" for correct behavior, including persistent authorization.

**Comment by mikhailvaliev** [comment]
Thanks, I'll try that out
