### ISSUE TITLE
how to add httpProxy in 

### ISSUE THREAD

**Issue by robinfoxnan** [tdlib/td#2170]
Hi everyone,
I am using td_example.cpp

I want to know how to add HttpProxy in cpp example, 
I add some code like this:
`auto proxy =  td::td_api::object_ptr<td_api::proxyTypeHttp>(new td_api::proxyTypeHttp("","",true));
    td_api::addProxy("10.128.6.130", 1081, true, std::move(proxy));`
but, I don't know where to add these lines,

Thanks a lot 

Robin

**Comment by robinfoxnan** [comment]
I think I got it,
`TdExample() {
    
    
    td::ClientManager::execute(td_api::make_object<td_api::setLogVerbosityLevel>(1));
    client_manager_ = std::make_unique<td::ClientManager>();
    client_id_ = client_manager_->create_client_id();
    
    //send_query(td_api::make_object<td_api::addProxy>("127.0.0.1", 10808, true, td_api::make_object<td_api::proxyTypeSocks5>()), {});
    
    // add proxy by robin
    auto proxy =  td_api::make_object<td_api::proxyTypeHttp>("","",false);
    auto addProxy =  td_api::make_object<td_api::addProxy>("10.128.6.130", 1081, true, std::move(proxy));
    // set http proxy
    send_query(std::move(addProxy), {});

    send_query(td_api::make_object<td_api::getOption>("version"), {});
  }`

**Comment by Stomed** [comment]
>
