### ISSUE TITLE
getUser

### ISSUE THREAD

**Issue by ThirdPrince** [tdlib/td#2174]
I try to get users from the group. The first 100 users spend little time, but it takes a lot of time to get users later，why?

**Comment by AYMENJD** [comment]
Why would you call `getUser` 100+ times?

**Comment by ThirdPrince** [comment]
@ AYMENJD Yes,getUser more than 100+ times.

**Comment by ThirdPrince** [comment]
@ AYMENJD getAllUser save it   once ,not getUser later.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.
