### ISSUE TITLE
Telegram API TOS

### ISSUE THREAD

**Issue by qt-kaneko** [tdlib/td#2175]
Will this violate TOS:
1) Can I get rid of any premium feature if I create my own Telegram client? (as I see in [Premium FAQ](https://telegram.org/faq_premium), then, maybe, yes)
2) Can I re-implement any premium feature without Telegram Premium subscription (e.g. split 4GB file into 2 2GB files and send them separately)?

**Comment by levlam** [comment]
This is a wrong place to ask. These question would be better answered by a lawyer.
