### ISSUE TITLE
[mtproto question] test DCs other than 1 not working on port 5222

### ISSUE THREAD

**Issue by faissaloo** [tdlib/td#2177]
Hello,
I'm writing an MTProto client. I've currently gotten to the stage where I need to implement DC switching, but for some reason it seems like as soon as I try to connect to any test DC other than 1 on port `5222` my connection gets closed by the server before I've even sent anything. This doesn't happen with the production DCs. Is this intentional? I [recall our discussion previously](https://github.com/tdlib/td/issues/1143#issuecomment-663697207) where it was mentioned that certain things are intentionally disabled on them.

**Comment by levlam** [comment]
This is not a bug.
