### ISSUE TITLE
Clear unread messages on init

### ISSUE THREAD

**Issue by vinifr** [tdlib/td#2178]
Is possible to clear all the unread messages on init? 

In my application I have to avoid to read old messages.

**Comment by levlam** [comment]
No. There is no way to read all unread messages.

**Comment by vinifr** [comment]
I dont want to read. I want to clear and ignore them. And from this point, read new messages.

**Comment by levlam** [comment]
If you mistakingly name "old" messages as "unread", then this is possible only if all databases are disabled and "ignore_background_updates" option is enabled by a call to `setOption` before `setTdlibParameters`.

**Comment by vinifr** [comment]
Sometimes I close the application and when I start there are a lot of messages unread. So I have to ignore.

**Comment by levlam** [comment]
It is possible to mark unread messages as read only by viewing them.

**Comment by vinifr** [comment]
> If you mistakingly name "old" messages as "unread", then this is possible only if all databases are disabled and "ignore_background_updates" option is enabled by a call to `setOption` before `setTdlibParameters`.

How do I disable all the databases? 

Will I lose the authorization if I close and open the application when the database are disabled?

**Comment by levlam** [comment]
Databases settings are passed in `setTdlibParameters`.
