### ISSUE TITLE
Not able to read big messages

### ISSUE THREAD

**Issue by vinifr** [tdlib/td#2181]
I am not able to read big messages, even setting message_text_length_max on object init

```
TdExample() {
    td::ClientManager::execute(td_api::make_object<td_api::setLogVerbosityLevel>(1));
    client_manager_ = std::make_unique<td::ClientManager>();
    client_id_ = client_manager_->create_client_id();
    send_query(td_api::make_object<td_api::getOption>("version"), {});
    //
    send_query(td_api::make_object<td_api::setOption>("message_text_length_max",
        td_api::make_object<td_api::optionValueInteger>(8096)), {});
  }
```

**Comment by levlam** [comment]
Option "message_text_length_max" can't be changed. I don't undersand, what you tried to do.

**Comment by vinifr** [comment]
The application is not detecting messages with 1000 bytes or more, for example.
This is not detected:  [https://pastebin.com/wU8bi02V](url)

Only messages with less bytes is detected.

**Comment by levlam** [comment]
I still not sure, what do you call "detecting", but messages with different lengths aren't handled in any specific way, so there is no way messages can be missed based on their length.

**Comment by vinifr** [comment]
updateNewMessage is not called when big messages like this is sending in a group or channel.

**Comment by vinifr** [comment]
Oh crap. Nevermind, I found a bug in my code
