### ISSUE TITLE
Using libtdjson in R

### ISSUE THREAD

**Issue by mrwunderbar666** [tdlib/td#2183]
I am trying to write some simple R bindings for tdjson, but I am really stuck.

I compiled the source and got fully working libraries (`libtdjson.so`) and tested the compiled libs with python.

When I try to interface with the library in R, I do not get any return value from the function calls. Anyone knows how to that?

This is what I've tried in R:

```r
library(jsonlite)

dyn.load("tdlib/lib/libtdjson.so", type = "External")

.C("td_set_log_message_callback", 2)

# setting TDLib log verbosity level to 1 (errors)
log_command = list("@type"="setLogVerbosityLevel",
                   "new_verbosity_level"=1)

td_execute <- function(query) {
  query <- jsonlite::toJSON(query, auto_unbox = T)
  result <- .C("td_execute", charToRaw(query))
  return(result)
}

test_command = list("@type"="getTextEntities",
                    "text"="@telegram /test_command https://telegram.org telegram.me",
                    "@extra"= c("5", 7.0, 'a'))

t <- td_execute(test_command)
rawToChar(t[[1]])
```

The only return values from the lists are basically an echo of the function call parameters.

**Comment by levlam** [comment]
> .C("td_set_log_message_callback", 2)

This call looks very strange.

Anyway, if you call `td_execute` correctly, you should always immeditaly receive JSON response, so the issue could be only in the way `td_execute` is called, or the answer is interpreted.

**Comment by mrwunderbar666** [comment]
Yes, the first part looks a bit weird, because I've tried a lot of stuff. It can be ignored.

I've relayed the question to Stackoverflow and the quick answer is that R requires a custom compilation of the source code with special R header files. That means, tdjson cannot be called from R directly like in other languages. 

I think you can close the issue, even though it isn't solved yet. The solution would also require some more expertise in R development and that is probably out of scope four your repository
