### ISSUE TITLE
How to use the accept Terms Of Service method for a new account?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2186]
I'm trying to build a telegram app but I can't do this method
```json
{
  "@type": "updateAuthorizationState",
  "authorization_state": {
    "@type": "authorizationStateWaitRegistration",
    "terms_of_service": {
      "@type": "termsOfService",
      "text": {
        "@type": "formattedText",
        "text": "By signing up for Telegram, you agree not to:\n\n- Use our service to send spam or scam users.\n- Promote violence on publicly viewable Telegram bots, groups or channels.\n- Post pornographic content on publicly viewable Telegram bots, groups or channels.\n\nWe reserve the right to update these Terms of Service later.",
        "entities": []
      },
      "min_user_age": 0,
      "show_popup": false
    }
  }
}
```

How to fill this key `terms_of_service_id`

**Comment by azkadev** [comment]
I tried this [method](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1register_user.html) when there was an update and it worked, thank you, sorry I didn't read the docs

**Comment by levlam** [comment]
This is correct. During registration terms of service are automatically accepted. If `show_popup` is true, then a blocking popup with terms of service must be shown to the user before registration is continued. `acceptTermsOfService` needs to be used only to handle `updateTermsOfService` updates.
