### ISSUE TITLE
Error when building TDLib

### ISSUE THREAD

**Issue by Hepka** [tdlib/td#2188]
An error occurs when building TDLib.
```
[ 76%] Linking CXX shared library libtdjson.so
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
gmake[2]: *** [CMakeFiles/tdjson.dir/build.make:125: libtdjson.so.1.8.7] Error 254
gmake[1]: *** [CMakeFiles/Makefile2:597: CMakeFiles/tdjson.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

Using the command:
```
apt-get update
apt-get upgrade -y
apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake clang-14 libc++-dev libc++abi-dev
git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DTD_ENABLE_LTO=ON -DCMAKE_AR=/usr/bin/llvm-ar-14 -DCMAKE_NM=/usr/bin/llvm-nm-14 -DCMAKE_OBJDUMP=/usr/bin/llvm-objdump-14 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-14 ..
cmake --build . --target install
cd ..
cd ..
ls -l /usr/local
```

What should I do?

**Comment by levlam** [comment]
Check the checkbox "I have less than ... GB of RAM" in the build instruction generator.

**Comment by levlam** [comment]
But it is unlikely to help either. You have not enough RAM for compiler to build with LTO enabled. You can disable LTO or try on a server with more RAM.

**Comment by Hepka** [comment]
> You can try to check the checkbox "I have less than ... GB of RAM" in the build instruction generator.

Yes, I noted that I have less than N GB, although my server has 16 GB of RAM

> But it is unlikely to help either. You have not enough RAM for compiler to build with LTO enabled. You can disable LTO or try on a server with more RAM.

I have enough RAM for TDLib, but with any building it outputs an error of 77%

**Comment by levlam** [comment]
Then LTO support is somehow broken in the toolchain. Disable LTO and it should build just fine.
