### ISSUE TITLE
What is the timing of the api 'UpdateChatReadInbox' call?

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#219]
When I join a chat, this chat has unread messages all the time, but I'm already on the chat page. There should be no unread messages in this chat.

I found that the api 'UpdateChatReadInbox' returned chat unread messages, I want to know how to call this api.

**Comment by levlam** [comment]
UpdateChatReadInbox is an incoming update, not a method. It is received whenever number of unread messages changes. If you want to mark some messages as read in a chat, you should implement calling of openChat/closeChat whenever a chat is opened/closed and call viewMessages when messages are viewed. You can also use force_read parameter of viewMessages to mark messages as read without opening the chat.

**Comment by liaoyu1992** [comment]
ok,thank you
