### ISSUE TITLE
Dart and Flutter examples

### ISSUE THREAD

**Issue by ivk1800** [tdlib/td#2190]
I suggest to add to the page [examples](https://github.com/tdlib/td/blob/master/example/README.md#tdlib-usage-and-build-examples):
[tdlib-dart](https://github.com/ivk1800/tdlib-dart) — client with automatically generated and fully-documented classes for all TDLib API methods and objects. Supported Android, iOS, MacOs, Linux and Windows.

[telegram-flutter](https://github.com/ivk1800/telegram-flutter) — Telegram client written in Dart and used Flutter.(WIP)  Uses the library above, can be considered a use case.

[td-json-client-prebuilt](https://github.com/ivk1800/td-json-client-prebuilt) — auto build json client by using github actions without manual intervention. It will be useful for those who have problems with build. Can be used not only with Dart.

**Comment by levlam** [comment]
Thank you.

`tdlib-dart` and `telegram-flutter` were added to the list of examples. They look very promising.

Prebuilt binaries are out of scope for the examples.
