### ISSUE TITLE
getMessageAvailableReactions return empty

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#2193]
i open a chat and use `getMessageAvailableReactions` but it return empty lists while i see available reactions in Telegram Desktop.

**Comment by levlam** [comment]
Response of `getMessageAvailableReactions` is correct. There are a lot of reasons, why returned lists of `top`/`recent`/`popular` reactions are empty.

**Comment by aghasi** [comment]
top reactions is not empty if i call `getMessageAvailableReactions` 10 seconds after opening the chat!

**Comment by levlam** [comment]
This is expected and is a correct behavor still.

**Comment by aghasi** [comment]
> This is expected and is a correct behavor still.

why this is a correct behavor ?

i should wait a long time to get correct answer from `getMessageAvailableReactions`.

**Comment by levlam** [comment]
It is impossible for all clients to know exactly the same state for all existing chats. This would require infinite speed of data transfer, infinite bandwidth and near infinite data storage. Apps have some known state and you receive result, which is absolutely correct in accordance with the latest kmown state. There is no way to predict when some changes will become known to specific client.

**Comment by aghasi** [comment]
Let describe the problem completely.

I want to submit reaction on a post. As your said [here ](https://github.com/tdlib/td/issues/1928) i have to call `getMessageAvailableReactions` first and then call the `addMessageReaction`. I call `getMessageAvailableReactions` and it returns empty list of top/recent/popular reactions. Then i call  `addMessageReaction` which returns following error:

`The reaction isn't available for the message`

So what should i do to submit the reaction on the post?

`addMessageReaction` is successful when the output of `getMessageAvailableReactions` isn't empty list.

**Comment by levlam** [comment]
You can't add reaction through TDLib if `getMessageAvailableReactions` returns empty lists.

**Comment by aghasi** [comment]
> You can't add reaction through TDLib if `getMessageAvailableReactions` returns empty lists.

this is a bug in TDLlib. Because i can add reaction on that post by Telegram Desktop.

**Comment by levlam** [comment]
This is expected behavior. Moreover, it would never be noticed by real users, using a real app.

**Comment by aghasi** [comment]
> This is expected behavior. Moreover, it would never be noticed by real users, using a real app.

Does real app use TDLib to communicate with Telegram servers?

**Comment by levlam** [comment]
Yes.
