### ISSUE TITLE
tdweb ".send is not a function."

### ISSUE THREAD

**Issue by Frostswing** [tdlib/td#2195]
How do i send a quary to tdlib using this directory?

my code starts as:
"import React from "react";
import TdClient from "tdweb";

let client=class TdClient{}
client.instanceName='tdlib';
client.isBackground='false';
client.jsLogVerbosityLevel='info';
client.logVerbosityLevel='2';
client.useDatabase='true';
client.readOnly='false';
client.mode='auto';

client.send(..."

then gets error:"TypeError: client.send is not a function."

i saw other issues here using this exact syntax, and i checked the documentation claiming to create an object and call the "send" function.

What am i missing?

Thanks!

**Comment by levlam** [comment]
You can look at source code of [Telegram-react](https://github.com/evgeny-nadymov/telegram-react/blob/afd90f19b264895806359c23f985edccda828aca/src/Controllers/TdLibController.js) for an example of a correct usage of `tdweb`.

**Comment by Frostswing** [comment]
@levlam i just this morning found this Telegram-react project.
Good to know that this is the right direction. Thanks!
