### ISSUE TITLE
Where is getMessagesReactions() in TDLib?

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#2196]
How can i call `getMessagesReactions` in TDLib?  I mean [this](https://core.telegram.org/method/messages.getMessagesReactions).

**Comment by levlam** [comment]
TDLib doesn't provide access to Telegram API methods, you need some other library for this. This method is called automatically by TDLib whenever the list of chosen reactions on a message needs to be refreshed.

**Comment by aghasi** [comment]
> TDLib doesn't provide access to Telegram API methods, you need some other library for this. This method is called automatically by TDLib whenever the list of chosen reactions on a message needs to be refreshed.

So how can i get current status of reactions on a post? i.e the submitted reactions  and  count of them?

**Comment by levlam** [comment]
Reactions are available in `message.interaction_info.reactions` and `updateMessageInteractionInfo` can be sent to update them.

**Comment by aliadibpour** [comment]
@aghasi Do you remember how to solve this?
