### ISSUE TITLE
Authorising user via code sent in email

### ISSUE THREAD

**Issue by dsrana** [tdlib/td#2197]
Hi, with `AuthorizationStateWaitEmailAddress` and `AuthorizationStateWaitEmailCode` - how does Telegram decide to use email to send the auth code rather than on Telegram app? Under what scenario would it ask and send auth code via email?

Thanks

**Comment by levlam** [comment]
It is completely up to the server. Clients must support all authorization states, but it is up to the server, which authorization states to use.
