### ISSUE TITLE
timeout tdlib request in case of network problems

### ISSUE THREAD

**Issue by tg2sipfork** [tdlib/td#2198]
is there any way to set timeout when requesting tdlib query on network failure?

**Comment by levlam** [comment]
No. Network is expected to be unreliable and request will be retried until it succeeds.

**Comment by wowka1319** [comment]
Then what does that mean: `[ 0][t 4][1677421367.798591852][SslStream.cpp:102][#1][!Connect]` ?

**Comment by levlam** [comment]
@wowka1319 It means that you must either update TDLib, or downgrade OpenSSL. TDLib 1.8.4 is a very old version.

**Comment by wowka1319** [comment]
Hmmm. It's interesting this happens sometimes. Not always.

**Comment by levlam** [comment]
This code is accessible only if TDLib can't connect to Telegram DC for a long time.

**Comment by wowka1319** [comment]
However, restarting helps (I say if it matters to you). Thank you.
