### ISSUE TITLE
Issue with Phone Authentification

### ISSUE THREAD

**Issue by ejifloy** [tdlib/td#2199]
Hello,

at the moment im working with the tdlib java [Example](https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java), which i managed to add to my existing java project using IntelliJ.

Now i ran into the problem of an expired authentication code and it seems to have stuck in this state:

![authentication_issue](https://user-images.githubusercontent.com/117834450/200858450-22dc543c-42ba-46d1-b9fe-788d417febfc.PNG)

I do know that there is a method i can call to resend the authentication code during the AuthorizationStateWaitCode-State:

```
            case TdApi.AuthorizationStateWaitCode.CONSTRUCTOR: {
                client.send(new TdApi.ResendAuthenticationCode(), defaultHandler);
                String code = promptString("Please enter authentication code: ");
                client.send(new TdApi.CheckAuthenticationCode(code), new AuthorizationRequestHandler());
                break;
            }
```

When i execute the programm like it is shown above, i do not revceive another code on my phone.
 
Anyone can help?

**Comment by levlam** [comment]
`ResendAuthenticationCode` works only when there is `nextType` in `authorizationStateWaitCode.codeInfo`. If you receive `PHONE_CODE_EXPIRED` error, you need to restart authorization. You should be able to do this by restarting the example.

**Comment by ejifloy** [comment]
Not working... The authorization-process does initialize the connection process by  `case TdApi.AuthorizationStateWaitTdlibParameters.CONSTRUCTOR`, but jumps from there back to the  `case TdApi.AuthorizationStateWaitCode.CONSTRUCTOR:` waiting for code.

Is there any other way to receive a new authentication code or restart the authentication process?

**Comment by levlam** [comment]
Authorization state is reset to AuthorizationStateWaitPhoneNumber in 5 minutes. There are no explicit way to reset authorization state in the example.
