### ISSUE TITLE
400 Can't lock file

### ISSUE THREAD

**Issue by funk-yourself** [tdlib/td#220]
Occures when I send `setTdlibParameters` (after receiving `updateAuthorizationState` with type of `authorizationStateWaitTdlibParameters`, of course).
```
[ 3][t 3][1525341790.876738548][Td.cpp:4633][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

[ 3][t 3][1525341800.785206556][Td.cpp:4663][!Td][&td_requests]	Sending error for request 1: error { code = 400 message = "Can't lock file" }
```
There's no error when I change database_directory to another path (though old path worked well some time ago).

What could be the reason for such behaviour?

P.S. File permissions seem to be correct and are the same for both directories I mentioned.

**Comment by zevlg** [comment]
It might be another instance of your application already running on that directory

**Comment by funk-yourself** [comment]
Yeah, there was a zombie-client which was locking file.

**Comment by adhil28** [comment]
> It might be another instance of your application already running on that directory

How can i unlock it

**Comment by levlam** [comment]
@adhil28 Close the other instance.
