### ISSUE TITLE
Issues : how to find the problem when returning MEDIA_INVALID ? 

### ISSUE THREAD

**Issue by booette520** [tdlib/td#2200]
when I tried sending a inputMediaPoll using messages.sendMedia， the server returned the MEDIA INVALID. I don't know what the wrong direction this error is returning.

**Comment by Gabzygreen11** [comment]
Logz

**Comment by Gabzygreen11** [comment]
Spam

**Comment by levlam** [comment]
This is not related to TDLib. You can hardly receive MEDIA_INVALID when sending a poll with TDLib.

**Comment by booette520** [comment]
@levlam I'm trying to use only parts of the telegram_api, such as sending text messages and sending files. But it seems that I made a mistake when I was trying to send the file, and the server returned me this error code, I kind of don't know what the mistake is. If the question was bad, thanks for answering it.
