### ISSUE TITLE
Td failed to build with "error MSB8066: Custom build for exited with code -1073741819" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [tdlib/td#2204]
Td failed to build with "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'F:\td\build_arm64ec\CMakeFiles\a954abfa5a46cd96a4b331ea9f6015ae\tl_generate_tlo.rule' exited with code -1073741819." with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?
**Versions and configuration**
OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.20)
**Repro steps:**
1. Open a VS 2019 x64 Native Tools Command Prompt
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/tdlib/td F:\td
4. cd f:\vcpkg
5. bootstrap-vcpkg.bat
6. vcpkg.exe install --recurse openssl zlib gperf  --triplet x64-windows --clean-after-build
7. cd F:\td
8. git submodule update --init --recursive
9. mkdir build_arm64ec && cd build_arm64ec
10. cmake -G "Visual Studio 16 2019" -A  ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0  -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 
11. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release TDLib.sln /t:Rebuild 

**Error info:**
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'F:\td\build_arm64ec\CMakeFiles\a954abfa5a46cd96a4b331ea9f6015ae\tl_generate_tlo.rule' exited with code -1073741819. [F:\td\build_arm64ec\td\generate\tl_generate_tlo.vcxproj]

**Error log:**
[Td_build.log](https://github.com/tdlib/td/files/10011606/Td_build.log)

**Comment by levlam** [comment]
You have issues with gperf.

**Comment by levlam** [comment]
Usually, you need to install gperf, matching target architecture, and not for `x64-windows`.

Also, how "-A ARM64EC" and "-DVCPKG_TARGET_TRIPLET=x64-windows" are supposed to work together, given they specify different architectures?

**Comment by YangYang129** [comment]
@levlam Thanks for your info. This issue still repro after vcpkg install gperf on arm64-windows and this project rebuild with MSVC on Windows arm64ec
**Repro steps:**
1. cd f:\vcpkg
2. bootstrap-vcpkg.bat
3. vcpkg.exe install --recurse openssl zlib gperf --triplet arm64-windows --clean-after-build
4. cd F:\td
5. git submodule update --init --recursive
6. mkdir build_arm64ec && cd build_arm64ec
7. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows ..
8. msbuild /p:Platform=ARM64EC /p:Configuration=Release TDLib.sln /t:Rebuild
**Error info:**
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'F:\aa\td\build_arm64ec\CMakeFiles\c20c5a1572906906bbd4c9d5f6b19bed\mime_type_to_extension.gperf.rule;F:\aa\td\build_arm64ec\CMakeFiles\c20c5a1572906906bbd4c9d5f6b19bed\extension_to_mime_type.cpp.rule;F:\aa\td\build_arm64ec\CMakeFiles\c20c5a1572906906bbd4c9d5f6b19bed\mime_type_to_extension.cpp.rule;F:\aa\td\build_arm64ec\CMakeFiles\b6c89d998440aa490645cf58f7fb3158\tdmime_auto.rule' exited with code -1073741819. [F:\aa\td\build_arm64ec\tdutils\generate\tdmime_auto.vcxproj]`

**Error log:**
[Td-remsbuild.log](https://github.com/tdlib/td/files/10017313/Td-remsbuild.log)

**Comment by levlam** [comment]
To find the cause, you can do the following.
1. Find in the file `F:\aa\td\build_arm64ec\CMakeCache.txt` line of the form `GPERF_EXECUTABLE:FILEPATH=F:/vcpkg/installed/arm64-windows/tools/gperf.exe` and note the path to the `gperf` executable used during compilation.
2. Run `cd F:\aa\td\tdutils\generate` to enter the correct working directory.
3. Run `"${GPERF_EXECUTABLE}" -m100 --output-file=auto/mime_type_to_extension.cpp auto/mime_type_to_extension.gperf`, where `GPERF_EXECUTABLE` - path to the executable from Step 1. You should see exact error returned by `gperf`.

**Comment by levlam** [comment]
@YangYang129 Did you find the cause?

**Comment by YangYang129** [comment]
@levlam Thanks for your investigating and info. According to your description, I run these commands, display this error:
![image](https://user-images.githubusercontent.com/86757616/202598162-1c6b72ad-c9f3-422a-8703-d3f39222c911.png)

**Comment by levlam** [comment]
Check architecture of the gperf.exe. It will be strange if the binary isn't for ARM64 and still installed to arm64-windows. If this is the case, then a vcpkg issue needs to be opened.

**Comment by amani64** [comment]
I had the same error, upgrade packages to latest version in pubspec.yaml solved problem.
