### ISSUE TITLE
performing rollbacks to older version of tdlib commits

### ISSUE THREAD

**Issue by dsrana** [tdlib/td#2205]
Hello. We treat new commits in tdlib repo as new versions of tdlib and update our apps accordingly. We were looking at scenarios where we might decide to rollback for whatever reason.

1. Does tdlib interact with Telegram server in anyway where it persists version of tdlib being used? So if we rolled back. it may not work or cause problems? e.g. does it associate any tdlib data against our api_id and hash?

Thanks

**Comment by levlam** [comment]
It is impossible to downgrade TDLib version used by an app. This will work almost never.
