### ISSUE TITLE
How cancel uploading file after restart app?

### ISSUE THREAD

**Issue by nikolaykusch** [tdlib/td#2208]
If I send a message with a large file, or multiple messages with files, it doesn't matter, and I restart the app before the upload is complete, the upload continues. How can I cancel scheduled operations?

Yes, I can cancel all uploads before closing, but I need a way that will work even if the program crashes. Is it possible to somehow cancel scheduled operations during client initialization?

**Comment by levlam** [comment]
You need to delete the message. There is no other way to cancel upload of a being sent file.
