### ISSUE TITLE
Error "Valid api_id must be provided" only on x64

### ISSUE THREAD

**Issue by Maddest** [tdlib/td#2211]
Hi,
I'm using the tdjson.dll v1.8.8 compiled for Windows C++ **win64**. All library functions work fine. However, after I have received the 'authorizationStateWaitTdlibParameters' I use 'td_send' to send the following JSON auth string:

```
{
"@type":"setTdlibParameters",
"parameters":
{
"use_test_dc":false,
"database_directory":"",
"files_directory":"",
"database_encryption_key":[],
"use_file_database":false,
"use_chat_info_database":false,
"use_message_database":false,
"use_secret_chats":false,
"api_id":12345,
"api_hash":"xxxxxxxxxxxxxxxxxxxx",
"system_language_code":"en",
"device_model":"Desktop",
"system_version":"",
"application_version":1,
"enable_storage_optimizer":1,
"ignore_file_names":false
}
}
```

I have followed the hints from https://github.com/tdlib/td/issues/2155 and changed the JSON string accordingly, but then I get a JSON parse error (expecting string, not array).

Any hints what I'm doing wrong here? Thanks a lot!

**Comment by levlam** [comment]
"database_encryption_key" should be a base64-encoded binary string and not an array.

**Comment by Maddest** [comment]
Thanks. I don't have any database encryption keys, so I leave them empty. The last JSON string I used as follows, but I still get the API_ID invalid error.

```
{
"@type":"setTdlibParameters",
"parameters":
{
"use_test_dc":false,
"database_directory":"",
"files_directory":"",
"database_encryption_key":"",
"use_file_database":false,
"use_chat_info_database":false,
"use_message_database":false,
"use_secret_chats":false,
"api_id":1245678,
"api_hash":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"system_language_code":"en",
"device_model":"Desktop",
"system_version":"",
"application_version":"0.1",
"enable_storage_optimizer":false,
"ignore_file_names":false
}
}
```

Did I miss something different? I tried so many combinations, but it won't work.

**Comment by Maddest** [comment]
I have downgraded to v1.8.1 and now it's working with the following JSON:

{"@type":"setTdlibParameters","parameters":{"use_test_dc":true,"database_directory":"C:\\CryptoNiffler\\Hive\\LIB_Libraries\\LIB_Tdlib\\tdlib","files_directory":"","use_file_database":true,"use_chat_info_database":true,"use_message_database":true,"use_secret_chats":true,"api_id":12345678,"api_hash":"xxxxxxxxxxxxxxxxxxxxxx","system_language_code":"en","device_model":"Desktop","system_version":"0.1","application_version":"0.1","enable_storage_optimizer":true,"ignore_file_names":true}}

Since which version is use_test_dc available?

**Comment by AYMENJD** [comment]
@Maddest Starting from TDLib v1.8.6+ `setTdlibParameters` values must be inlined and i can see in your JSON examples you haven't inlined the parameters.

To inline `setTdlibParameters` values remove the key/array `parameters`. So your JSON will be like:
```json
{
"@type":"setTdlibParameters",
"use_test_dc":false,
"database_directory":"",
"files_directory":"",
"database_encryption_key":"",
"use_file_database":false,
"use_chat_info_database":false,
"use_message_database":false,
"use_secret_chats":false,
"api_id":1245678,
"api_hash":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"system_language_code":"en",
"device_model":"Desktop",
"system_version":"",
"application_version":"0.1",
"enable_storage_optimizer":false,
"ignore_file_names":false
}
```

This should work fine in TDLib 1.8.6+. Also i suggest you to read this https://github.com/tdlib/td/issues/2155#issuecomment-1264474111

**Comment by Maddest** [comment]
@AYMENJD That works great...thank you very much for this information. It saved me hours  🥇 

Are these changes documented somewhere? Can't find any changelogs.

**Comment by AYMENJD** [comment]
Yes but not in changelogs. Everytime you update TDLib you must check changes made to [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) which is TDLib API scheme file. Which will help you to know more about the new version that you are updating to.

**Comment by Maddest** [comment]
@AYMENJD Thanks. I'll check this file from time to time. However, a page with all changes listed for each version would be very handy though.
