### ISSUE TITLE
getSupergroupMembers: joinedChatDate contains the date of promotion

### ISSUE THREAD

**Issue by deer-huntress** [tdlib/td#2213]
User was added to the channel. Then he was promoted to administrator.
In accordance with https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_member.html I expect to get the date when user was added to the channel, not promoted to admin.

**getSupergroupMembers** returns this user, but joinedChatDate contains the date of promotion.
_joinedChatDate = 1669703751_
`ChatMembers {
  totalCount = 2
  members = vector[2] {
    ChatMember {
      memberId = MessageSenderUser {
        userId = 5635970666
      }
      inviterUserId = 1117926218
      joinedChatDate = 1669703751
      status = ChatMemberStatusAdministrator {
        customTitle = ""
        canBeEdited = false
        rights = ChatAdministratorRights {
          canManageChat = true
          canChangeInfo = true
          canPostMessages = true
          canEditMessages = true
          canDeleteMessages = true
          canInviteUsers = true
          canRestrictMembers = true
          canPinMessages = false
          canPromoteMembers = false
          canManageVideoChats = true
          isAnonymous = false
        }
      }
    }
    ChatMember {
      memberId = MessageSenderUser {
        userId = 1117926218
      }
      inviterUserId = 0
      joinedChatDate = 0
      status = ChatMemberStatusCreator {
        customTitle = ""
        isAnonymous = false
        isMember = true
      }
    }
  }
}
`

**getChatEventHistory** returns 2 ChatEvents for this user:
_date = 1669703751 (action = ChatEventMemberPromoted)
date = 1669703473 (action = ChatEventMemberInvited)_
`ChatEvents {
  events = vector[2] {
    ChatEvent {
      id = 49837107120
      date = 1669703751
      memberId = MessageSenderUser {
        userId = 1117926218
      }
      action = ChatEventMemberPromoted {
        userId = 5635970666
        oldStatus = ChatMemberStatusMember {
        }
        newStatus = ChatMemberStatusAdministrator {
          customTitle = ""
          canBeEdited = false
          rights = ChatAdministratorRights {
            canManageChat = true
            canChangeInfo = true
            canPostMessages = true
            canEditMessages = true
            canDeleteMessages = true
            canInviteUsers = true
            canRestrictMembers = true
            canPinMessages = false
            canPromoteMembers = false
            canManageVideoChats = true
            isAnonymous = false
          }
        }
      }
    }
    ChatEvent {
      id = 49836054564
      date = 1669703473
      memberId = MessageSenderUser {
        userId = 1117926218
      }
      action = ChatEventMemberInvited {
        userId = 5635970666
        status = ChatMemberStatusMember {
        }
      }
    }
  }
}
`

**Comment by levlam** [comment]
`joined_chat_date` isn't reliable for this. It can change any time user rights are changed in the chat, so field's name is misleading.

**Comment by deer-huntress** [comment]
@levlam Thanks!
Could you please explain whether I can get the initial date when user joined the chat or not?

**Comment by levlam** [comment]
No. This date isn't kept anymore.

**Comment by deer-huntress** [comment]
Thank you for clarification.

**Comment by deer-huntress** [comment]
Thank you for clarification.
