### ISSUE TITLE
Question about getting message reactions updates

### ISSUE THREAD

**Issue by deer-huntress** [tdlib/td#2214]
Hi! 
We have a problem with getting message reactions updates via tdlib: updateMessageInteractionInfo does not always come when reaction is added/removed on/from a message.

https://github.com/tdlib/td/issues/2069? says that "You will receive updateMessageInteractionInfo when appropriate.".
Could you please clarify the logic behind it? When exactly will we receive these updates?

What should we do to get all reaction changes for all messages (that were previously received by tdlib) in the chat?

**Comment by levlam** [comment]
Reactions are updated only for recently viewed messages. You can't get reaction updates for all existing messages.
