### ISSUE TITLE
Please tag more intermediate releases

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2215]
@levlam I can see that tdlib´s last tag is still 1.8.0 from last Dec.

For smaller projects it is really unberable to catch up with one year of changes or more, when you decide to release the next "minor" release. It would be much better if we can track your upstream as we go.

The benefit for you guys is that 3rd party clients stay closer to the head of development, thereby giving less chance to continuing using old, outdated code with performance problems, memleaks, or even security issues.

The benefit for us is that we can offer our users new features in a shorter period of time.

Please, take this forward into your internal discussions, I guess it wont hurt you much.

BR florian

**Comment by levlam** [comment]
Tag is just an alias for a commit, which is supposed to be used by others and marked as such. Telegram development is linear: there are no long-term branches, or side features. Therefore the recommended for use commit always is the latest commit in the master branch. It is definitely more stable than the latest commit of any other Telegram app, or even the latest tagged commit, and is definitely suitable for production releases. You can find mode details in https://github.com/tdlib/td/issues/1627#issuecomment-885993462 and https://github.com/tdlib/td/issues/1656#issuecomment-917622548.

**Comment by ForNeVeR** [comment]
As a maintainer of downstream [tdlib.native](https://github.com/ForNeVeR/tdlib.native), I would still double this suggestion.

Folks, it is really hard to even speak about td without you having some tags or something at least.

[A user asks me to update to 1.8.9](https://github.com/ForNeVeR/tdlib.native/issues/77). But what exactly is 1.8.9? Should I just pick some random commit which has 1.8.9 version from your repository? What if this isn't something the user has in their mind?

**Comment by levlam** [comment]
@ForNeVeR When a user asks about update to 1.8.9, they don't mean 1.8.9, but a master version, which is now 1.8.9.

**Comment by ForNeVeR** [comment]
Okay. And if they ask for 1.8.8? Which commit are they referring to?

**Comment by ForNeVeR** [comment]
Look, you're making this _a lot_ more complicated than it should be.

Refusing to use basic versioning is really defying the idea of having any common ground between people (maintainers and users of different libraries, in this case).

For example, I have two different libraries depending on td: tdsharp.native and tdsharp.

They have to base on the same API version, basically on the same commit of tdlib.

But they have different maintainers (I am a member of both maintainer squads, but that's not a general rule, and that costed me some nerves), and may generally be released on different dates.

So, the answer "just always pick the top of `master`" doesn't work! They all have to pick the same commit, something not so volatile.

If there were a release process in tdlib, I would just pick 1.8.9 for both libraries, there would be no contradictions and no problems.

But now, I have to repeat "1.8.9 from commit 297520733ohmygodpleasekillme3821a8cf853fab5" everywhere, and if I am wrong about the revision, everything will go straight to hell.

**Comment by Gabzygreen11** [comment]
Yes good



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Friedrich von Never ***@***.***>
Date : 2022-12-07 5 h 12 p.m. (GMT-05:00)
À : tdlib/td ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [tdlib/td] Please tag more intermediate releases (Issue #2215)


Okay. And if they ask for 1.8.8? Which commit are they referring to?

**Comment by levlam** [comment]
> And if they ask for 1.8.8?

Then they don't know that the latest version is 1.8.9. It is always bad to use an old app version. Telegram is an app, only the latest version of which is supposed to be used, and so is TDLib.

> They have to base on the same API version, basically on the same commit of tdlib.

Yes. And this could be any commit, which is the latest commit on Github at some point. The newer the commit, the better.

> But they have different maintainers (I am a member of both maintainer squads,

Then they can't be updated simultaneously no matter what.

> So, the answer "just always pick the top of master" doesn't work! 

Within the same TDLib version TDLib API is stable, so even different commits should be fully-compatible in terms of API.

> If there were a release process in tdlib, I would just pick 1.8.9 for both libraries, there would be no contradictions and no problems.

As I explained at https://github.com/tdlib/td/issues/1627#issuecomment-885993462, the issue is that whatever commit is marked as 1.8.9, it is not the commit to be used by apps: "So, basically, each time a version is stable enough and can be marked with a tag, there is a newer version with the latest features, which should be used instead."

**Comment by Kylmakalle** [comment]
To align with Telegram's pace of development, you can try to update your dependencies to each published HEAD commit of TDLib. Just treat each intermediate commit as a patch tag. Why not? I hope you're getting the point.

I use this approach - parsing TDLib's version and providing commit info, so it will be possible to reference it in case some bug or functionality requires additional attention.

You can tag your own software as `<tdlib_version>+<tdlib_commit>`(or `<tdlib_version>-<tdlib_commit>` in some cases). This is also somehow allowed by a [semver](https://semver.org/#spec-item-10).

If you're using TDLib as a submodule and hosting your software on Github, you can leverage [Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) with similar [config](https://github.com/Swiftgram/TDLibFramework/blob/main/.github/dependabot.yml) to ensure TDLib is at it's bleeding edge.

Adding some CI with smoke testing, you can achieve up-to-date software and other benefits mentioned above.
Please take a look at this approach in my [Apple wrapper](https://github.com/Swiftgram/TDLibFramework/tags)
<img width="553" alt="image" src="https://user-images.githubusercontent.com/24507532/206506130-dc4ee4f9-0286-4523-a2e1-4a85cce1c9b9.png">

**Comment by Flohack74** [comment]
@Kylmakalle you name it - using bleeding edge is normally not what a 3rd party user would like to do.

@levlam if you are working in this way, its fine for you guys. you have the manpower and the resources to fix a spotted bug under one day, commit it and roll out new official clients - thats awesome.

But, small projects do not have those abilities. If I decide to track HEAD in my configuration and release it lets say today, and tomorrow I go on holiday - later a critical bug is figured which brings my users offline. But i am not here to move the commit pointer up, nobody can, and the app is broken for 2 weeks or so. I could not live with this feeling.

The whole idea of tagging releases is of course to tag stable code. Code that has been tested (unit, integration tests) and is deemed to be usable for a wider audience for a longer time. In between 2 tags hell can break loose ((c) @ForNeVeR) but it does not matter since external consumers only consume stable tags.

This is a widely recognized best practice in the software world. The argument that "its an app, only the latest version should be used" is not a valid argument, since you also do not publish a new version for every commit, at least I hope so.

We cannot follow your development speed, so we are grateful that you allow older versions to be used for some time - for example we are still on 1.8.0, and now i want to know what is the latest version that has no API breakage. I cannot figure this out if you do not tag patch versions in between 1.8.0 and 1.9.0 (given the fact that 1.8.1 would be free from breaking changes, but I am not even sure that 1.8.0 => HEAD upgrade would be free from that. In fact is HEAD now 1.8.x or 1.9 or what is it?)

**Comment by Kylmakalle** [comment]
> using bleeding edge is normally not what a 3rd party user would like to do.

levlam already covered [this](https://github.com/tdlib/td/issues/2215#issuecomment-1336512663)
> ... latest commit in the master branch ... definitely more stable than ... the latest tagged commit, and is definitely suitable for production releases.

**Comment by Kylmakalle** [comment]
@Flohack74 FYI: TDLib sources are _usually_ not pushed to Github instantly. There's a separate remote for internal development.

I also assume some essential QA is happening in private VCS, but I can't say something specific about it.

**Comment by levlam** [comment]
> you name it - using bleeding edge is normally not what a 3rd party user would like to do.

This is exactly what hundred millions Telegram users do. Telegram apps are updated automatically to the latest bleeding age version.

> to fix a spotted bug under one day, commit it and roll out new official clients

The TDLib's code on Github is highly unlikely to have a critical bug. I described some reasons for this in https://github.com/tdlib/td/issues/1656#issuecomment-917622548. Even there is a minor bug, then it happens because noone spotted the bug yet, so it is very likely to exist in the tagged version either.

> Code that has been tested (unit, integration tests) and is deemed to be usable for a wider audience for a longer time.

This is the code pushed to Github. As @Kylmakalle correctly mentioned, development of new and unstable features takes place in a different remote repository. 

> what is the latest version that has no API breakage

TDLib API is changed with every app release, roughly speaking, once a month. The best way to see most changes between commits is to use `git diff` on td/generate/scheme/td_api.tl.

**Comment by Flohack74** [comment]
@levlam why you tag then at all? If the Github repo is just here for distributing the code and we should not use older commits than HEAD there is no point in having any, and I can see now 10 tags here, which is not much but ok.

**Comment by levlam** [comment]
Yes, there is no much reason to tag them. Tagging is done for TDLib versions, which are available prebuilt for Android at https://core.telegram.org/tdlib/tdlib.zip, have complete Change Log from the previous version, and are tested on all supported platforms. So, it should be safe to use the tagged versions, but it is still recommended to use the latest version instead.

**Comment by Flohack74** [comment]
@levlam yeah thats fine, but a small project really struggles to keep pace with your developments, and now for example I have a delta of one year of development, and I cannot update in small pieces, to minimize regressions and let the users slowly test stuff. We are not able to keep in sync when it would be needed, lets say once a month, but only when time permits it. We all have day jobs ;)
I am afraid that by picking an arbitrary commit somewhere in lets say Jan 2022 I might end up with a buggy tdlib build.

**Comment by levlam** [comment]
> I am afraid that by picking an arbitrary commit somewhere in lets say Jan 2022 I might end up with a buggy tdlib build.

If the commit was the last commit on Github, then this is highly unlikely. You don't need to be afraid of this as you don't afraid to use up-to-date Telegram apps.

If you want to find some old, but otherwise good commits, then you can use a commit after which commit date jumps back in time with a commit message like "Update layer to 123.". The previous commit is the commit, which is definitely suitable for production releases.
