### ISSUE TITLE
[help needed], How can we use this send photo with python?

### ISSUE THREAD

**Issue by mobilelifeful** [tdlib/td#2216]
replacing 
'api_id':  ,
'api_hash': ' ',
of https://github.com/tdlib/td/blob/master/example/python/tdjson_example.py
run 
python tdjson_example.py,
When my account receive chat from others, the code doesn't print out the text? 

Can we use this to send photo with python? Thank you.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started. Among other things it contains links to examples.

**Comment by mobilelifeful** [comment]
> See https://core.telegram.org/tdlib/getting-started. Among other things it contains links to examples.

Thank you for the link. I actually checked the link before and check again, can't find any example of sending photo.

**Comment by levlam** [comment]
There are no examples besides https://github.com/tdlib/td/tree/master/example#python.
