### ISSUE TITLE
I can make payment form for buy Telegram Premium?

### ISSUE THREAD

**Issue by OJIEKCAHDP** [tdlib/td#2221]
I can not find the necessary methods in the documentation, so I decided to turn here. Is it possible to pay for Telegram Premium via TDLib?

**Comment by levlam** [comment]
You can only pay via a credit card to Apple, Google, or a payment provider at https://t.me/PremiumBot.

**Comment by hackers-king957** [comment]
Hi Guy's any one know how can I get visa card for charge telegram premium free
