### ISSUE TITLE
How to close this vulnerability?

### ISSUE THREAD

**Issue by sumatoreo** [tdlib/td#2224]
Other people write through my telegram, but it looks like I am writing it.
In a month, I reinstalled the computer 3 times, changed the password to the telegram twice. But I get hacked all the time.

They write messages to other people from me and delete the history. Can you help find and close the vulnerability?

**Comment by sumatoreo** [comment]
@AYMENJD 
I have already done all this.
Determined the scenario of how the breakdown occurs.
They send a video-modified message, an audio file that does not play, but after opening it, they get remote shell access.
I have some security knowledge, but not enough to kick intruders out of the system or close the vulnerability myself.

**Comment by AYMENJD** [comment]
Sorry, i can't help you with that. You must never open unknown files from unknown people.
