### ISSUE TITLE
AuthorizationStateLoggingOut meaning

### ISSUE THREAD

**Issue by dmitry-kovaliov** [tdlib/td#2226]
When I call `TdApi.LogOut()` function I get into `AuthorizationStateLoggingOut`
Does `AuthorizationStateLoggingOut` means that my session is not valid any more or it just indicates an attempt to logout?
I mean can it get back to `AuthorizationStateReady` in the case when log out attempt fails or it's a one way road?

**Comment by levlam** [comment]
When authorization state is `AuthorizationStateLoggingOut`, then the session is not valid anymore **and** is being logged out. This action is irreversible. If you close and reopen the TDLib instance, it will start from `AuthorizationStateLoggingOut` and continue logging out.

**Comment by SergVG** [comment]
How can I re-authorize in this case?

**Comment by levlam** [comment]
@SergVG You need to create new TDLib instance after the previous is closed.
