### ISSUE TITLE
how to see who is inviting whom?

### ISSUE THREAD

**Issue by Serg95off** [tdlib/td#2227]
Hi, i have a group chat, how can I track who invited whom?
Does anyone have an example of how this can be done?
need to use chatInviteLinkMember or not?

**Comment by levlam** [comment]
You should use [Bot API](https://core.telegram.org/bots/api) for such tasks.

**Comment by levlam** [comment]
Bots can handle "chat_member" [Update](https://core.telegram.org/bots/api#update).
