### ISSUE TITLE
upgraded_from_basic_group_id -> Chat not found

### ISSUE THREAD

**Issue by leoMehlig** [tdlib/td#223]
When I attempt to load the chat history of a supergroup prior to it's upgrade from a basic group (using the `upgraded_from_basic_group_id` and the `upgraded_from_max_message_id`), I get an error:
`code: 6`
`message: Chat not found`

Do I misunderstand the use if those fields?
As I understand it: To get message from the supergroup from before the upgrade, I have to request messages from the basic group.

**Comment by levlam** [comment]
You are right. Field upgraded_from_basic_group_id contains a basic group identifier, which needs to be passed first to createBasicGroupChat to receive corresponding chat. Then you can get messages history in the chat through getChatHistory.

**Comment by leoMehlig** [comment]
Ok thank you. Wasn't clear to me chat I have to create this chat first.
