### ISSUE TITLE
close function not closing the tdlib instance

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2231]
Hello,

we found out that our app is not fully closing on desktop, when its closed with the mouse, and not like on the device where the process is terminated. so we suspect that tdlib is still running a few threads and we found the close function. But I only get this:

```
2022-12-11T23:44:53 Shutting down TELEports, Good Bye!
2022-12-11T23:44:53 [SEND] : QJsonObject({"@type":"close"})
[ 2][t 4][1670798693.805856704][Td.cpp:3550][#1][!Td]	Close Td in state 2
```
and still no shutdown happens. also no auth state closed message comes back. Any infos on thatß

thanks!

**Comment by levlam** [comment]
It is impossible to name the cause without full log with verbosity 4, or even 20 in some cases.

**Comment by Flohack74** [comment]
@levlam ok will try to get more detailed logging...

**Comment by Flohack74** [comment]
Ok it was trivial, our type check for the auth state returning from tdlib had a typo, it seems tdlib closes itself correctly ;)

**Comment by Flohack74** [comment]
@levlam I reopen this, can it be that close doe snot return an Ok message? Our async thread waits forever it seems for that confirmation (in my logging it would come before the shutdown logging which is triggered by auth state change)...
```
2022-12-14T00:30:12 debug (unknown) [SEND] : QJsonObject({"@extra":"req-4","@type":"close"})
2022-12-14T00:30:12 warning (unknown) tdlib has shut down...
```

**Comment by levlam** [comment]
No, It always returns `Ok`.

**Comment by Flohack74** [comment]
So is it guaranteed that Ok comes before updateAuthorizationState ?

**Comment by levlam** [comment]
Yes.

**Comment by Flohack74** [comment]
@levlam we found the problem, seems we had deadlocked the main thread and no signals came through to it anymore. It works now...
