### ISSUE TITLE
class chatEventVideoChatParticipantIsMutedToggled

### ISSUE THREAD

**Issue by Geliusan** [tdlib/td#2234]
I want to use class chatEventVideoChatParticipantIsMutedToggled to keep track of who is muted and who is not. However, when using , everything is urgently closed. I pass through the object Information about the video chat, but as far as I understand, I must pass the id of the video chat participants. But the method by which you can get the id has not been found. Does anyone know how to make this work properly?

else if(action == "mut")
        {
            send_query(td_api::make_object<td_api::getGroupCall>(videochatid_), [this](Object object){
                if (object->get_id() == td_api::error::ID) {
                  return;
                }
                auto videochats = td::move_tl_object_as<td_api::chatEventVideoChatParticipantIsMutedToggled>(object);
                cout << "Microphone is:"<< videochats->is_muted_ << endl;

            });
        }

This is just an example, then I plan to loop a part of the code for constant tracking of who is muted, because. I use a telegram client that connects to the radio station and I need to monitor when the microphone is on or off so that the radio station switches between receiving and output in advance so as not to lose the first voice transmissions

**Comment by levlam** [comment]
`chatEventVideoChatParticipantIsMutedToggled` is an event from chat event log. The call
`videochats = td::move_tl_object_as<td_api::chatEventVideoChatParticipantIsMutedToggled>(object);` absolutely make no sense and access to videochats is expected to crash.

Whenever list of group call participants is changed, you receive `updateGroupCallParticipant`. Make sure that you loaded the list with `loadGroupCallParticipants`.

**Comment by Geliusan** [comment]
> `chatEventVideoChatParticipantIsMutedToggled` is an event from chat event log. The call `videochats = td::move_tl_object_as<td_api::chatEventVideoChatParticipantIsMutedToggled>(object);` absolutely make no sense and access to videochats is expected to crash.
> 
> Whenever list of group call participants is changed, you receive `updateGroupCallParticipant`. Make sure that you loaded the list with `loadGroupCallParticipants`.

I'm really sorry, I'm just pretty dumb. It's just that I still don't understand how exactly I can use chatEventVideoChatParticipantIsMutedToggled to understand who is muted and who is not. I will be very grateful for your help

**Comment by levlam** [comment]
You can't use `chatEventVideoChatParticipantIsMutedToggled`. It represents a completely unrelated object, which can't be used to get real-time data.

**Comment by Geliusan** [comment]
> You can't use `chatEventVideoChatParticipantIsMutedToggled`. It represents a completely unrelated object, which can't be used to get real-time data.

Thanks

**Comment by Geliusan** [comment]
> You can't use `chatEventVideoChatParticipantIsMutedToggled`. It represents a completely unrelated object, which can't be used to get real-time data.

and with the help of what class in td_api can this be implemented?

**Comment by Geliusan** [comment]
> You can't use `chatEventVideoChatParticipantIsMutedToggled`. It represents a completely unrelated object, which can't be used to get real-time data.

Can I use the group Call Participant class to keep track of whether the participants' microphone is turned on and off?

**Comment by levlam** [comment]
Whenever list of group call participants is changed, you receive `updateGroupCallParticipant`. Make sure that you loaded the list with `loadGroupCallParticipants`.
