### ISSUE TITLE
Message with file upload: how to know if is finished?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2235]
Hi,

our phone OS supplies attachments only as temp files which should be cleaned up after processing is finished. So I would need to get an information when InputfileLocal´s backing file can be deleted. Or does tdlib copy over the file into its own folder?

**Comment by levlam** [comment]
To upload a temporary file, you need to use `inputFileGenerated`. See https://github.com/tdlib/td/issues/126 for some examples of `inputFileGenerated` usage.

**Comment by Flohack74** [comment]
Alright understood, you already answered this earlier sorry :)
