### ISSUE TITLE
Question about LoadChats

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2237]
I make `LoadChats`, then in `updateNewChat` i got the user's chats. But in addition to simple chats, I also get chats with comments for all groups that the user is subscribed to.
How can i distinguish `Chat` (for example chat with a friend) it is a chat with comments to some group? Perhaps there is some parameter `isChatComments`?

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started covers this,
