### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by Oct4Pie** [tdlib/td#2239]
I have been trying to ping an MTProto proxy but couldn't find the right way.
Unfortunately, the documentation on the classes and methods are quite poor, or I don't seem to be finding them helpful. 
```cpp
TdProxy(std::string& server, int& port, std::string& secret) {
        auto proxy = td_api::make_object<td_api::proxyTypeMtproto>(secret);
        auto aproxy = td_api::make_object<td_api::addProxy>(server, port, true, std::move(proxy));
        td_api::pingProxy(aproxy->get_id());
        td::ClientManager::execute(td_api::make_object<td_api::setLogVerbosityLevel>(1));
        client_manager_ = std::make_unique<td::ClientManager>();
        client_id_ = client_manager_->create_client_id();
        send_query(std::move(aproxy), {});
        send_query(td_api::make_object<td_api::getOption>("version"), {});
    }
```
There is no way to receive a value from `pingProxy`. `.store()` causes a segmentation fault, and the id comes back as 0.
How should I proceed with this? 
Thank you

**Comment by levlam** [comment]
`ClientManager` and all classes in td_api namespace are fully documented. The provided C++ code makes no sense, so you would better try to use TDLib from a type-safe language instead of C++. You can find basic information about TDLib usage at https://core.telegram.org/tdlib/getting-started, including a lot of examples in different languages.

**Comment by Oct4Pie** [comment]
I understand. I chose c++ because I am intergrating it with other c++ projects. I am just trying to ping the proxy server using `pingProxy`. How should I do that in c/c++ and get back the ping value?

**Comment by levlam** [comment]
You need to read https://core.telegram.org/tdlib/getting-started, then read linked there examples and documentation.

**Comment by Oct4Pie** [comment]
I was able to resolve the issue by having a look at https://en.cppreference.com/w/cpp/experimental/observer_ptr.
Thank you for the Information.
