### ISSUE TITLE
Compile Error - Stat.cpp(ambiguous partial specializations)

### ISSUE THREAD

**Issue by vladimirovmax** [tdlib/td#224]
/td/tdutils/td/utils/port/Stat.cpp:82:20: error:                                                   
 **ambiguous partial specializations of 'TimeNsec<stat, void>'**     

`auto time_nsec = TimeNsec<struct ::stat>::get(buf);`                                         

 /td/tdutils/td/utils/port/Stat.cpp:68:8: note:                                                    
     **partial specialization matches [with T = stat]**

`struct TimeNsec<T, void_t<short, decltype(T::st_atimensec), ...`

/td/tdutils/td/utils/port/Stat.cpp:75:8: note:
      **partial specialization matches [with T = stat]**

`struct TimeNsec<T, void_t<int, decltype(T::st_atim), decltyp...`
    
1 error generated.
make[2]: *** [tdutils/CMakeFiles/tdutils.dir/build.make:180: tdutils/CMakeFiles/tdutils.dir/td/utils/port/Stat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:558: tdutils/CMakeFiles/tdutils.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by levlam** [comment]
Thanks!

Could you apply this [patch](https://github.com/tdlib/td/files/1987730/Stat.cpp.txt) and check whether problem is solved?

**Comment by vladimirovmax** [comment]
Its works:) Thank you:)

**Comment by levlam** [comment]
This is fixed in TDLib 1.3.0.
