### ISSUE TITLE
Polls: how to send user choice?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2243]
For answering polls I do not find the right input message type in the documentation...

**Comment by levlam** [comment]
Poll answers aren't sent as separate messages. You can use `setPollAnswer` for this.

**Comment by Flohack74** [comment]
Thxnks! It would be good if the API documentation search box can search for *poll* so I could find this, by just getting all objects and functions that contain the word poll, instead of only searching for poll* in my case...

**Comment by Flohack74** [comment]
So do I understand right, I can call this multiple times - until the poll is closed? Removing vote means sending empty option id array?

**Comment by levlam** [comment]
Yes, this is right.

Also, some polls allow multiple answers.
