### ISSUE TITLE
Question about UpdateMessageInteractionInfo

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2244]
Why in the `UpdateMessageInteractionInfo` update sometimes for `reactions` in `interactionInfo` values 0 in `totalCount` come, although the message in the supergroup already has more than 1000 reactions?

**Comment by Flohack74** [comment]
Additionally I would like to know how this should be used in normal groups. Should the view count be displayed somewhere?

**Comment by levlam** [comment]
@Flohack74 If view_count > 0, it should be displayed. Forwards from channels have positive view_count.
