### ISSUE TITLE
 get profilePhoto from user

### ISSUE THREAD

**Issue by ThirdPrince** [tdlib/td#2246]
when i get profile photo from user find that small photo RemoteFile id as the same as big photo , but unique is different , why？

**Comment by levlam** [comment]
The photos are different: one of them is small and another one is big.

**Comment by ThirdPrince** [comment]
small photo RemoteFile id as the same as big photo,
 client.send(new TdApi.GetRemoteFile(commands[1], new TdApi.FileTypeProfilePhoto()),
                            new Client.ResultHandler() {
                                @Override
                                public void onResult(final TdApi.Object object) {
                                    //print("GetRemoteFile onResult:"+object.toString());
                                    if (object instanceof File) {
                                        File file = (File) object;
                                        client.send(new TdApi.DownloadFile(file.id, 1, 0, 0, true),
                                                new Client.ResultHandler() {
                                                    @Override
                                                    public void onResult(final TdApi.Object object) {
                                                        print("DownloadFile onResult:"+object.toString());
                                                    }
                                                });
                                    }else {
                                        print(object.toString());
                                    }
                                }
                            });


Without the unique parameter , how to distinguish  small or big ?

**Comment by levlam** [comment]
What do you mean by "to distinguish small or big"? They are received in different fields. Then it ia up to the app, which file identifier to use.

**Comment by assuranceplatform** [comment]
[Express trader profits ](https://assuranceinve-oop7612

**Comment by ThirdPrince** [comment]
@levlam Thanks a lot 。

**Comment by ThirdPrince** [comment]
small photo RemoteFile id not as the same as big photo

**Comment by levlam** [comment]
Yes, they are different files.
