### ISSUE TITLE
The authorization code does not arrive

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2247]
Why can't I receive a code to confirm authorization? I have `AuthorizationStateWaitPhoneNumber`, I do `SetAuthenticationPhoneNumber`, it returns `OK`, the state changes to `AuthorizationStateWaitCode`. But the code never comes. what could be the problem? 
tdlib version **1.8.8**

**Comment by levlam** [comment]
It is up to the server, when and how to send the code.

**Comment by rr8733380** [comment]
What do I need to do to prevent this from happening?

**Comment by levlam** [comment]
There is no way for clients to affect this behavior.
