### ISSUE TITLE
SendMessage issue

### ISSUE THREAD

**Issue by bugbaal** [tdlib/td#2248]
I don't know why sometimes the message is not delivered.
I check the response and I get the right json which shows no difference between that is sent and what remains suspended.
When I try to send another one, just now it sends the previous messages plus the new one.
So, it seems like they stay in the box and when prompted by a new message they wake up and go all together.
I would like to know if there is a way to push all messages or if I miss something to send message in the correct way.
Thanks

**Comment by levlam** [comment]
Do you handle [updateMessageSendSucceeded](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_send_succeeded.html) updates?

**Comment by bugbaal** [comment]
no, I'm using phptdlib that I think manage it

**Comment by levlam** [comment]
It can't manage updates for you. Message object has `sending_state` field. You need to handle `updateMessageSendSucceeded`,  `updateMessageSendFailed` and  `updateDeleteMessages` to know when the message was sent, or failed to send.

**Comment by bugbaal** [comment]
I get the response of the sendMessage and when it really sends or not the message to other device it is always in state "messageSendingStatePending".

**Comment by levlam** [comment]
If it is in the state `messageSendingStatePending`, then the message isn't sent yet.

**Comment by bugbaal** [comment]
ok, and why does it stay in state messageSendingStatePending and does it send the message?

**Comment by levlam** [comment]
It always send messages. And you will receive an update when the message sending is over.

**Comment by bugbaal** [comment]
I solved from the phptdlib side, but you gave me cue to find the solution.
Thank you.
