### ISSUE TITLE
Any way to store sessions not in sql lite db?

### ISSUE THREAD

**Issue by Sopholos** [tdlib/td#225]
I'm planning to make sort of "cloud" client. I need store sessions not in local sql lite db. I could not find such feature in api https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1tdlib_parameters.html

If this is not possible, at least need to know when need I copy local files into cloud.
Did I need to wait till connection closed or have some handlers?

PS: I use .net version

**Comment by levlam** [comment]
If you want to build a really "cloud" client, you will need to store everything on server and there is no difference, whatever is used for the database. The only thing you will need is to transfer updates from a server to a client and transfer requests from a client to a server. It is very dangerous to copy the database even after the library is closed and the database definitely shouldn't be backed up while TDLib is run.

**Comment by Sopholos** [comment]
1. I need copy session db between cloud servers in case of disaster (server down, network down etc). This means that I need fresh copy at central storage in any case,
2. SQL Light have ability to backup online db, so this is not a problem.

I need only to know when need I backup db to be sure that I have latest version and does not do useless backups too often.

But better to NOT backup sqllite but store sessions directly in my cloud storage, so if tdlib have some storage interfaces - will be best option.
