### ISSUE TITLE
updateUser

### ISSUE THREAD

**Issue by Sitnorthfacingsouth** [tdlib/td#2250]
hello
I know that I can't obtain userinfo by method: **getUser(user_id)**.
when receive updateUser notification,sometimes I can get user_id and  username, most of the time there is only user_id without username,Although the user has a username,because anytime when I've used the  mobile client,  and clicks  the user icon on a group can see the **correct username** in profile and start a private chat.
why sometimes  updateUser notification does not contain  username

 code like this
```
user_id = update['user']['id']
private_chat = tg.call_method('createPrivateChat',{'user_id':user_id,'force':True})
private_chat.wait()
chat = privateChat.update
```
sometimes createPrivateChat return a None object (I use python-telegram)
I'm sure the user( identify is user.user_id)and me in a common group.
but **getGroupsInCommon(user_id=user.id,offset_chat_id=0,limit=100)** return None object too.
 Is this some kind of policy of TG?

**Comment by AYMENJD** [comment]
I think you are using `python-telegram` in the wrong way.

**Comment by Sitnorthfacingsouth** [comment]
> I think you are using `python-telegram` in the wrong way.
the code I using python-telegram like this
```
user_id = update['user']['id'
private_chat = tg.call_method('createPrivateChat',{'user_id':user_id,'force':True})
private_chat.wait()
chat = privateChat.update
```
chat will be None object

**Comment by AYMENJD** [comment]
> chat will be None object

AFAIK, if the result is error `python-telegram` will store the response in attribute called `error`. So you may try `privateChat.error` to see the error response. You can always check if the response is error by using `privateChat.is_error`.

**Comment by levlam** [comment]
@Sitnorthfacingsouth What TDLib version are you using?

**Comment by Sitnorthfacingsouth** [comment]
> @Sitnorthfacingsouth What TDLib version are you using?

as python-telegram internal version 
tdlib 1.8.5

**Comment by Sitnorthfacingsouth** [comment]
> 



> > chat will be None object
> 
> AFAIK, if the result is error `python-telegram` will store the response in attribute called `error_info`. So you may try `privateChat.error_info` to see the error response.
> 
> You can always check if the response is error by using `privateChat.error` which has boolean value.

thanks ,
err_info like this
{
    '@type': 'error',
    'code': 400,
    'message': "Can't access the chat"
}
Why do I get this error,I'm already in the common group as this user

**Comment by levlam** [comment]
> tdlib 1.8.5

Update TDLib to the latest version. Old apps can't see NFT usernames.

> Why do I get this error,I'm already in the common group as this user

This is not enough. You must receive the user from TDLib first.
