### ISSUE TITLE
Unsupported message in the Telegram info channel

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2251]
Hi, I received this message as "unsupported" in our Telegram client based on tdlib:

![grafik](https://user-images.githubusercontent.com/16186470/210153560-b8eb793c-1e93-4144-846a-7d991df18bdd.png)

What message type is that, it looks like all the others in that channel?

BR Florian

**Comment by AYMENJD** [comment]
Make sure that you use the lastest TDLib version.

**Comment by Flohack74** [comment]
@AYMENJD I agree, we are not on latest, but we can only upgrade step by step, and if I know the message type I can put this on the roadmap for one of the next updates.

**Comment by AYMENJD** [comment]
See the new added features to telegram and try to implement it on your client. There is newly added entities which can cause `unspported` message on older TDLib versions. Such as custom emojis, spoilers etc.

**Comment by levlam** [comment]
The message contains custom emoji.
