### ISSUE TITLE
what is the difference between acceptCall and acceptCall?

### ISSUE THREAD

**Issue by hatem-amer** [tdlib/td#2252]
Which one should I use?

1st acceptCall():
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1accept_call.html#aaff58457ad6c691f8bcc8e051b75c1bd

2nd acceptCall():
https://core.telegram.org/method/phone.acceptCall

**Comment by levlam** [comment]
The first one is a TDLib API method. The second one is a Telegram API method. When using TDLib you need only TDLib documentation.
