### ISSUE TITLE
td_tdc_client.h not built

### ISSUE THREAD

**Issue by seek-Love** [tdlib/td#2255]
Built for 32-bit C on 64bit WIndows 10 in PowerShell. Followed the instruction in the [TDLib build instructions generator](https://tdlib.github.io/td/build.html?language=C). Trying to work with the C client, but my compiler says it can't find "td/telegram/td_tdc_api.h". I searched the files myself and didn't find it, either. What do I do to correct my mistake? Thanks

**Comment by levlam** [comment]
С client isn't built by default. You need to build it explicitly with `cmake --build . --target tdc`.

**Comment by seek-Love** [comment]
Thanks!
