### ISSUE TITLE
Issue with td_api::loadGroupCallParticipants

### ISSUE THREAD

**Issue by Geliusan** [tdlib/td#2257]
I created a video chat and connected to it from 2 accounts, I'm trying to use td_api::loadGroupCallParticipants, but I get an error: 400 - Can't load group call participants. Here is a code snippet:

 auto participants = td_api::make_object<td_api::loadGroupCallParticipants>();
            participants->group_call_id_ = videochatid_;
            participants->limit_ = 32;
            send_query(move(participants), [this](Object object){
                if (object->get_id() == td_api::ok::ID) {
                    cout << "hren" <<endl;
                } else {
                    cout << "ne hren" << object->get_id() <<endl;
                }
                if(object->get_id() == td_api::error::ID) {
                    cout << "ERRMSG: " << static_cast<td_api::error &>(*object).message_ << endl;
                }
            });

videochatid_ is a variable that I passed the video chat value to, it works, I checked it with td_api::endGroupCall

**Comment by levlam** [comment]
You can't load group call participants without joining the group call.

**Comment by Geliusan** [comment]
> You can't load group call participants without joining the group call.

I'm in a video chat using the tgcalls library.
