### ISSUE TITLE
The content object of a message with several photos contains only one photo object

### ISSUE THREAD

**Issue by Krestol** [tdlib/td#2258]
Is it possible to download all photos are attached to the message? I suppose a media album_id field may help, but unfortunately I can't find a way to use it.

**Comment by levlam** [comment]
Media albums are formed from independent messages with the same media_album_id. You need to collect all consecutive messages with the same media_album_id to show them as an album.

**Comment by Krestol** [comment]
Thanks for the quick and comprehensive answer.
