### ISSUE TITLE
Not changed TdApi.Chat photo local path after download

### ISSUE THREAD

**Issue by igolyudov** [tdlib/td#2260]
I get the chat photo using the download method (TdApi.DownloadFile by chat.photo.small.id) and the photo file appears in the profile_photo folder. But if after that I ask the TdApi.Chat object for the path to the local file (chat.photo.small.local.path), it will be empty. How can I update the file location data in the TdApi.Chat object?

**Comment by levlam** [comment]
You received `updateFile` for the file `chat.photo.small.id` with updated data about the file.

**Comment by igolyudov** [comment]
I received TdApi.File instead TdApi.UpdateFile. But if i am manual update chat.photo.small.local from received file.local it is work.
Thx!
