### ISSUE TITLE
Error 504 when call getFile method

### ISSUE THREAD

**Issue by ysset** [tdlib/td#2262]
I am trying to call getFile method with my test bot but it always return 504 error
```
https://api.telegram.org/bot<botToken>/test/getFile?file_id=<big file id from 'photo' bot event>
```
The method works fine, if i try to call it with wrong id i get an error
```json
{
	"ok": false,
	"error_code": 400,
	"description": "Bad Request: invalid file_id"
}
```
But if photo id is valid i get timeout error(504)
```json
{
	"ok": false,
	"error_code": 504,
	"description": "Gateway Timeout"
}
```

**Comment by levlam** [comment]
Test DC isn't expected to be reliable. It seems to have issues with file downloading now.

**Comment by ysset** [comment]
is there another way to get a link to a file by another method?

**Comment by levlam** [comment]
No. The file can't be downloaded in Test DC now.
