### ISSUE TITLE
Additional error information

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2265]
Do you have a link where i can read about the errors? For example, if the user entered the wrong code during authorization, an error occurs:
`code: 400, message: PHONE_CODE_INVALID`

Is there somewhere i can read about other errors with unsuccessful code entry, as well as for other functions?

**Comment by levlam** [comment]
You can search for something like `"PHONE_CODE_INVALID" site:core.telegram.org` for specific error. Errors such as "PHONE_CODE_INVALID", which are supposed to be handled by apps are very rare, but currently there is no complete documentation even for such errors.
