### ISSUE TITLE
Handle phone number links

### ISSUE THREAD

**Issue by umelikhau** [tdlib/td#2266]
Hello,

I need to handle phone number links:
when I click on ‘https://t.me/+123456789’ I want my app to directly open the chat.

Which method from tdlib can I use to get chatId by phone number link?

**Comment by levlam** [comment]
All links must be handled by calling `getInternalLinkType` first and then following documentation for the returned type. For the link result will be of the type
```
//@description The link is a link to a user by its phone number. Call searchUserByPhoneNumber with the given phone number to process the link @phone_number Phone number of the user
internalLinkTypeUserPhoneNumber phone_number:string = InternalLinkType;
```

**Comment by umelikhau** [comment]
I'm not able to find neither 'internalLinkTypeUserPhoneNumber', nor 'searchUserByPhoneNumber'.

I'm using TDLib for Android in a prebuilt form downloaded from Build instructions. 

Is there a newer prebuilt version available?
Or should I build the latest TDLib by myself?

**Comment by levlam** [comment]
You need to build the latest TDLib using [the example](https://github.com/tdlib/td/tree/master/example/android).

**Comment by Flohack74** [comment]
@levlam searchUserByPhoneNumber is also not in the web page documentation. Was this a recent addition? was the function name different before?

**Comment by levlam** [comment]
The feature was added after 1.8.0, so it isn't present in the on-site documentation.

**Comment by Flohack74** [comment]
Ok we are on 1.8.2 now so it should work? :)

**Comment by levlam** [comment]
Yes.
