### ISSUE TITLE
About sending private chat

### ISSUE THREAD

**Issue by PaperPlane28** [tdlib/td#2270]
For example, some users in the group do not have a username. How can I send a private chat message to these users without a username?

**Comment by levlam** [comment]
You can use `createPrivateChat` to create a private chat with a given user, but the account very likely to be banned for sending messages to group members.

**Comment by PaperPlane28** [comment]
Ok, thank you. I know their disadvantages. I just study them myself. It seems that createPrivateChat cannot be created. It shows chat no fund, but you can use getuser

**Comment by levlam** [comment]
You can't user identifiers, not received from TDLib.

**Comment by PaperPlane28** [comment]
I got the userid from updatuser. Is this the identifiers from tdlib?

**Comment by levlam** [comment]
You must receive the user identifier from the same TDLib instance without restarting it to ensure that you can use it.

**Comment by PaperPlane28** [comment]
I use this in the same tdlib instance = =

**Comment by PaperPlane28** [comment]
When receiving the updateuser, does TDlib get the user's identifier?
