### ISSUE TITLE
getting messages with huge delay on same region

### ISSUE THREAD

**Issue by ne0c0de** [tdlib/td#2271]
Hi,

I'm running multiple servers on same datacenter (same region) but getting messages from same channel with different delays.

Channel has 3xxx members.

Channel message sent time: Mon Jan 16 20:25:01 UTC 2023

This is message is received on one of the server: Mon Jan 16 20:25:07 UTC 2023

on same region but different server: Mon Jan 16 20:25:12 UTC 2023

I'm using same tdlib version with same config of server.

What can be the reason of this delay?

**Comment by AYMENJD** [comment]
This is expected. See https://github.com/tdlib/td/issues/1668#issuecomment-912960761.

**Comment by ne0c0de** [comment]
Actually it's not expected neither normal situation.

I've no idea why Telegram is providing this kind of bad service to channel subscribers. a new miliseconds may be acceptable but there's 11 seconds which is anormous. In some cases it comes in 30 seconds of delay too.

If Telegram will continue to not to make better this service, I'm sure they will loose crypto currency users..

**Comment by levlam** [comment]
Everything there works as expected in the best possible way.

**Comment by ne0c0de** [comment]
I'm saying there's latency up to 30 seconds and you're saying as it's normal as expected?

Waov, congratz..
