### ISSUE TITLE
Upload video with comment from filename

### ISSUE THREAD

**Issue by brothermechanic** [tdlib/td#2272]
Hello
Thank you for developing useful ui for tg!

Now i upload my videoarchive to my channel and wonder about batch uploading.
But main feature will be upload video with comment from filename, because without comment it's not possible to search video by name.

May be this feature aready is, tell me please.

Or May be it's simple to create el script for it.

**Comment by brothermechanic** [comment]
Ohh Sorry
I must open issue on telega repo, not there
But, may be someone can help me?

**Comment by levlam** [comment]
You can add `caption` to messages with videos. This should be supported in some way by `telega`.

**Comment by brothermechanic** [comment]
> You can add `caption` to messages with videos. This should be supported in some way by `telega`.

Hi
Thank you for reply
Yes telega support caption with C-c C-f like 
```
⟬📹 /media/disk/video/2022.06.22 Dark summer day.mp4⟭  2022.06.22 Dark summer day
```
This is manual process
I am looking for auto caption from filename

**Comment by levlam** [comment]
This is not possible to do from the interface of official apps.
