### ISSUE TITLE
Is there a way to get the animated stickers as a GIF file instead of the TGS file?

### ISSUE THREAD

**Issue by atiyka** [tdlib/td#2274]
Unfortunatelly I have lot's of troubles with the Lottie library in my project (WPF+XamlIslands).
Also tried to convert the animated JSON file to a GIF, but I haven't found any way to do this in .NET. I could not even extract the frames from that json file.

It would be great if I could get the animations as GIF or WEBP files from the tdlib.

**Comment by levlam** [comment]
Lottie files can be rendered only by a lottie library and TDLib doesn't bundle one. What issues do you have with https://github.com/TelegramMessenger/rlottie? It can be used with a few lines of C++ code.

**Comment by atiyka** [comment]
Ok, thank you.
The project is developed in C# .NET. I have issues with the [LottieUwp](https://github.com/azchohfi/LottieUWP) (anyway it's marked as deprecated) and with the [Lottie-Windows](https://github.com/CommunityToolkit/Lottie-Windows). As I know I can not use the rlottie C++ lib in a .NET project, or can I?

And there is no other option outside of the lottie to render the animations?

**Comment by levlam** [comment]
You can also see, how rlottie is used in [Unigram](https://github.com/UnigramDev/Unigram).

**Comment by atiyka** [comment]
Great, I could render now with RLottie! Thank you so much!
