### ISSUE TITLE
Rate limits for the createNewBasicGroupChat

### ISSUE THREAD

**Issue by igor-laevsky** [tdlib/td#2275]
Hi! I'm building a small project where I need to automatically add users to the newly created groups. Not doing any spam, rates are expected to be within the normal limits, so definitely much less than 50 new groups per day.

Are there any know current limitations for this api call? I know you don't publish them, but having a ballpark number will greatly help me. Thanks!

**Comment by levlam** [comment]
What kind of limitations do you ask about? If you are concerned only about the number of created groups, then "50 new groups per day" is a pretty close figure.

**Comment by igor-laevsky** [comment]
I think this answers my questions. Thank you.
