### ISSUE TITLE
Animated emojis with '\u{fe0f}' character aren't detected as animated emojis

### ISSUE THREAD

**Issue by YuraIz** [tdlib/td#2276]
'\u{fe0f}' character appends to each emoji by gtk emoji chooser, also you can paste it manually

Left: telegram web/z, not all emojis are animated
Center: telegrand, not all emojis are animated
Right: telegram desktop, all emojis are animated (similar behavior on ios and android versions)
![image](https://user-images.githubusercontent.com/63008755/212903408-3cc62681-38d1-434c-bf5f-fff0c290fd64.png)

**Comment by levlam** [comment]
This should be fixed by https://github.com/tdlib/td/commit/5b451f7e118e78a34b6b0de6c68467410858a9cf.
