### ISSUE TITLE
tdlib 1.8.2: Changed behaviour for deleting messages?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2277]
Hello,

we found out that with tdlib 1.8.2 the flags if a message can be deleted for either self or all users is making problems for group admins. It seems they get a "false" on all messages except their own. Was there a change in what Admins can do?

BR

**Comment by levlam** [comment]
There were no changes. Do you use 7da29e17d636f7dc8609ed88f3e915710daa4bd6 as 1.8.2? Generally, for old versions you need to use the last commit before the "Update layer to ..." commit.

**Comment by Flohack74** [comment]
@levlam yes exactly that commit. Investigating further...

**Comment by Flohack74** [comment]
But as a fact, Admins should be able to delete everything, no?

**Comment by levlam** [comment]
Yes.
There was a bug between d97d20a4209b6974371141a2ecd87c0a1e55e92f and 68db9a03cccbe3973c3d741b9a9f26f446716061, which resulted in the bug. You can downgrade 1.8.2 to 163bfbcc7a86f3faea373ae70aec9aa7b51b71eb to avoid it.
