### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by georgeprokopenko** [tdlib/td#2278]
Hey! Having this issue while trying to build on Apple Watch Ultra
<img width="1224" alt="Screenshot 2023-01-23 at 01 10 47" src="https://user-images.githubusercontent.com/33977689/213945516-0b00585c-0e82-4efe-8cfc-88763552ee0e.png">

Can it be fixed somehow?
Thanks

**Comment by georgeprokopenko** [comment]
Previously I tried to use TDLibFramework & TDLibKit, but now trying to build a raw td with a patch you advised and `./build.sh` gives the following
<img width="1409" alt="Screenshot 2023-01-24 at 11 47 25" src="https://user-images.githubusercontent.com/33977689/214261629-e946aa56-095b-4193-b762-be0ab2bf39e4.png">
<img width="622" alt="Screenshot 2023-01-24 at 11 47 37" src="https://user-images.githubusercontent.com/33977689/214261643-2a318842-f038-49bd-be2f-b36b15a25ca0.png">

**Comment by levlam** [comment]
Sorry, I provided a wrong patch. Here should be the correct one: [patch.txt](https://github.com/tdlib/td/files/10497203/patch.txt).

You can check that it is correct by running `lipo -info third_party/openssl/watchOS/lib/libcrypto.a` and checking that `arm64` architecture is present among others.

**Comment by georgeprokopenko** [comment]
Thank you, now getting this error while trying to build ci
https://github.com/georgeprokopenko/TDLibFramework/actions/runs/4039106882

<img width="1389" alt="Screenshot 2023-01-30 at 01 31 01" src="https://user-images.githubusercontent.com/33977689/215364690-6b2776d2-1e14-4397-bb01-14d9f5f932cd.png">

**Comment by levlam** [comment]
You have Xcode 13.3 or 13.4 in the CI. It is very likely that you need Xcode 14 to use arm64 architecture for watchOS.

**Comment by levlam** [comment]
You need to change value of environment variable DEVELOPER_DIR from "/Applications/Xcode_13.4.1.app/Contents/Developer" to "/Applications/Xcode_14.2.app/Contents/Developer".

**Comment by georgeprokopenko** [comment]
Thank you, have thought about it already, will try

**Comment by Kylmakalle** [comment]
@levlam I can confirm the provided patch enables `arm64` arch for watchOS successfully. [CI run](https://github.com/Swiftgram/TDLibFramework/actions/runs/4155978464)
```
file lib/libtdjson.dylib   
lib/libtdjson.dylib: Mach-O universal binary with 3 architectures: [arm_v7k:Mach-O dynamically linked shared library arm_v7k] [arm64_32_v8] [arm64]
lib/libtdjson.dylib (for architecture armv7k):	Mach-O dynamically linked shared library arm_v7k
lib/libtdjson.dylib (for architecture arm64_32):	Mach-O dynamically linked shared library arm64_32_v8
lib/libtdjson.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```
However, I don't have real devices to test.

Keep in mind, that this patch will require latest WatchOS SDK which was mentioned above
> Xcode 14.2.1

**Comment by levlam** [comment]
@Kylmakalle Thank you for the confirmation. Xcode 14 was released 5 month ago, and it should be already widely available, so I will merge the patch unconditionally and add a notice that Xcode >= 14 is required for watchOS building.

**Comment by levlam** [comment]
ARM64 support for watchOS was added in TDLib 1.8.12.
