### ISSUE TITLE
Using Telegram.Td.dll in ASP.net web api project

### ISSUE THREAD

**Issue by sadeghtkd** [tdlib/td#228]
Hi
I've added a reference to Telegram.Td.dll in  ASP.net web api project but I got runtime error : 
`Could not load file or assembly 'Telegram.Td.DLL' or one of its dependencies. The specified module could not be found.`
I think the problem because of that I can't add reference to LIBEAY32.dll , SSLEAY32.dll and zlibd1.dll
![image](https://user-images.githubusercontent.com/5601781/39852689-23262eb2-5433-11e8-958c-89b45bcdd8df.png)

Any idea ?

**Comment by levlam** [comment]
It seems that there is no way to add native libraries to .Net project and to add different native libraries for Debug and Release configuration through Visual Studio interface, so references to these libraries must be added manually to csproj file by editing it in any text editor. See [TdExample.csproj](https://github.com/tdlib/td/blob/master/example/csharp/TdExample.csproj) for example of adding them to the project.

Also in the current TDLib 1.2.0 version there is a bug in strings mangling between native and C# code, so you will need to replace functions [string_to_unmanaged](https://github.com/tdlib/td/blob/cfe4d9bdcee9305632eb228a46a95407d05b5c7a/tdutils/td/utils/port/CxCli.h#L120) and [string_from_unmanaged](https://github.com/tdlib/td/blob/cfe4d9bdcee9305632eb228a46a95407d05b5c7a/tdutils/td/utils/port/CxCli.h#L127) with the code from https://github.com/tdlib/td/issues/181#issuecomment-380961900.

**Comment by sadeghtkd** [comment]
Yes, that's right.
I've added manually that libraries and also this line to system.web of web.config : 
`<hostingEnvironment shadowCopyBinAssemblies="false" />`
And now the problem is resolved.

**Comment by NitayTubi** [comment]
Hi,
I got into the exact same problem. 
In my development environment,  Im running my app on local IIS (and not IIS Express) and when i add `<hostingEnvironment shadowCopyBinAssemblies="false" />` to my web.config, my app is getting broken and all files are getting locked. I must reboot the whole system to solve it. 
So, without the line in the web.config, i getting this error: 
`Could not load file or assembly 'Telegram.Td.DLL' or one of its dependencies. The specified module could not be found.`
With the line in the web.config, my app is getting broken.
Any idea ? Is there any way to make it work without the line in the web.config? 
Im using VS17, 64-bit as target platform, IIS 10, Windows 10.

**Comment by levlam** [comment]
@NitayTubi Have you already specified path to the libraries in csproj file? The key part is
```
    <Reference Include="Telegram.Td, Version=0.0.0.0, Culture=neutral, processorArchitecture=AMD64">
      <SpecificVersion>False</SpecificVersion>
      <HintPath Condition=" '$(Configuration)' == 'Debug' ">build\Debug\Telegram.Td.dll</HintPath>
      <HintPath Condition=" '$(Configuration)' == 'Release' ">build\Release\Telegram.Td.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Content Include="build\Debug\LIBEAY32.dll">
      <Link>LIBEAY32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="build\Debug\SSLEAY32.dll">
      <Link>SSLEAY32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="build\Debug\zlibd1.dll">
      <Link>zlibd1.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)' == 'Release' ">
    <Content Include="build\Release\LIBEAY32.dll">
      <Link>LIBEAY32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="build\Release\SSLEAY32.dll">
      <Link>SSLEAY32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="build\Release\zlib1.dll">
      <Link>zlib1.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

**Comment by NitayTubi** [comment]
Thanks for the reply.
Yes, I have already specified all the references and paths as you mentioned.
As i mentioned in my first comment, In a regular web api project on IIS Express it works well with the line in the web.config. Without the line in the web.config it doesn't work. 
But in my development environment on Local IIS i cannot add the line in the web.config because it locks the files and breaks the app.
So, i think that the idea is to find a way to disable shadow copy without using this line `<hostingEnvironment shadowCopyBinAssemblies="false" />`.

**Comment by levlam** [comment]
It seems that there are some working solutions [there](https://stackoverflow.com/questions/344608/unmanaged-dlls-fail-to-load-on-asp-net-server).
