### ISSUE TITLE
stuck on ConnectionStateUpdating

### ISSUE THREAD

**Issue by AngadGrewal** [tdlib/td#2280]
```
January 24th 2023, 09:47:48.414 | INFO | TdApi.UpdateConnectionState object received: 'ConnectionStateConnectingToProxy'

January 24th 2023, 09:48:18.591 | INFO | TdApi.UpdateConnectionState object received: 'ConnectionStateConnecting'

January 24th 2023, 09:48:18.743 | INFO | TdApi.UpdateConnectionState object received: 'ConnectionStateUpdating'
```

Occasionally when restarting my java application I receive ConnectionStateUpdating and then it never moves over to ConnectionStateReady,
I first receive ConnectionStateConnectingToProxy, then ConnectionStateConnecting and finally ConnectionStateUpdating and nothing more, and it requires logging out and logging back in to fix.

Are there any potential reasons for this?

**Comment by levlam** [comment]
No. You need to check TDLib logs for details. Probably, there are issues with the used proxy.
