### ISSUE TITLE
Is there a way using tdlib to install/remove sticker sets?

### ISSUE THREAD

**Issue by atiyka** [tdlib/td#2284]
I haven't found any relevant method in the [docs](https://core.telegram.org/tdlib/docs/td__api_8h.html).
I read somewhere that I can add a sticker set to the installed sets, by creating a new sticker set, and addig the stickers to it, but I think this is not a good solution.
Is there any way to do it?

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1change_sticker_set.html.

**Comment by atiyka** [comment]
Great, thank you so much! :)
