### ISSUE TITLE
Error 420 Flood Wait Failed

### ISSUE THREAD

**Issue by bubblecsh** [tdlib/td#2286]
Hey, i have telegram account with high activity and lots of messages sent and received all the time which is connected to tdlib.
If i launch tdlib after being off for some hours first i get a bunch of these delays which i believe are handled by tdlib:

`[ 2][t 4][1674826840.746383666][NetQueryDelayer.cpp:83][#1][!NetQueryDelayer]  Delay: [Query:[id:52822016][tl:0x4423e6c5][state:Query]] [timeout:25][total_timeout:25] because of [Error : 420 : FLOOD_WAIT_25] from Session:2:main::Connect::Tcp::[149.154.167.51:443] to DcId{2} from [172.18.0.2:49696]`

But then there are also lots of these:

`[ 2][t 4][1674826897.016707897][NetQueryDelayer.cpp:74][#1][!NetQueryDelayer]  Failed: [Query:[id:38207488][tl:0x4423e6c5][state:Query]] [timeout:30][total_timeout:90] because of [Error : 420 : FLOOD_WAIT_30] from Session:2:main::Connect::Tcp::[149.154.167.51:443] to DcId{2} from [172.18.0.2:49696]`

Does tdlib handle them? I just want to make sure that there are no missing new chat and new message events.
Thanks.

**Comment by levlam** [comment]
Those are `getChatHistory` requests.

**Comment by bubblecsh** [comment]
Are they initiated by tdlib?

**Comment by levlam** [comment]
This is possible, but very unlikely.

**Comment by bubblecsh** [comment]
My app is only making `getChat` and `downloadFile` requests so idk where `getChatHistory` is coming from.
Can this affect `updateNewMessage` events that are coming from tdlib when it is just launched?

**Comment by levlam** [comment]
No. `getChatHistory` is automatically called only when the last message in a chat becames unknown and must be repaired.

**Comment by bubblecsh** [comment]
Make sense now, thanks!
