### ISSUE TITLE
I think first you need to fix all the blocks above which the TODO section

### ISSUE THREAD

**Issue by UnblockerUsername** [tdlib/td#229]
There are too many of them in the code.
You can find them with grep -R
Next, you need to think about how to adapt it for ordinary people by analogy with React.

Regards

**Comment by UnblockerUsername** [comment]
I read @isopen on facebook https://github.com/facebook/react/issues/12783
Became completely incomprehensible reasons why the @isopen account is locked in tdlib.

Please unblock it here so that he can write new bug reports about tdlib.

For a long time do not answer...

**Comment by levlam** [comment]
@isopen, if you want to write a bug report or something else about TDLib, you can always do that through @tdlib_bot.

**Comment by UnblockerUsername** [comment]
@levlam user @isopen is now busy with work.
I tried to check the bot. He does not understand the subtleties of thought. His answers are not good enough. Your answers are better.
