### ISSUE TITLE
Problem sending user's animated profile as video

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#2290]
Hello
I use tdlib version 1.8.10 with Python language. When I want to send a video message through a user's animated profile ID file, I encounter the following error:

`{'@type': 'error', 'code': 400, 'message': "Can't use file of type Photo as Video", '@extra': None}`

But when I first download the media with the same ID file, an mp4 file is saved in the photo folder, and when I try to send a video message with the address of the file on the hard disk, there is no problem. I think this is a bug.

**Comment by levlam** [comment]
The error is expected. Animated chat photos are photos server-side and can be send only as static photos in messages. To send the corresponding video in a message, you need to download it first.
