### ISSUE TITLE
can bot assigned can_manage_topics permission pin/close topic?

### ISSUE THREAD

**Issue by Yxue-1906** [tdlib/td#2292]
I found method toggleForumTopicIsPinned/toggleForumTopicIsClosed, but as for the former, It returns error "The method is not available to bots"

**Comment by Yxue-1906** [comment]
Also I encountered a problem, there is, I create a bot help me login a user account on my server; the workflow is, I send phone number to the bot, then the auth code, then the pass if exist; problem occurred in the second step, if the account chatting with the bot and the account to login to server are the same, it will stuck in sending message after receiving auth code from Telegram Service Account.
I tried tg_cli to send the auth code to bot and the same issue occurred. From log I found the send message query kept receiving FLOOD_WAIT_0 error

**Comment by Yxue-1906** [comment]
> Also I encountered a problem, there is, I create a bot help me login a user account on my server; the workflow is, I send phone number to the bot, then the auth code, then the pass if exist; problem occurred in the second step, if the account chatting with the bot and the account to login to server are the same, it will stuck in sending message after receiving auth code from Telegram Service Account. I tried tg_cli to send the auth code to bot and the same issue occurred. From log I found the send message query kept receiving FLOOD_WAIT_0 error

![image](https://user-images.githubusercontent.com/20736038/216782950-c40d6f5d-9d50-4752-8188-30cabb4692fd.png)

**Comment by Yxue-1906** [comment]
sometimes I can send out the auth code, but it would receive PHONE CODE EXPIRED error; resend code would encounter code can't resend error;

**Comment by Yxue-1906** [comment]
@levlam would you please pay some time looking into this issue?

**Comment by levlam** [comment]
The method `toggleForumTopicIsPinned` is not available to bots. The method `toggleForumTopicIsClosed` can be used by bots.

I don't know, what can cause FLOOD_WAIT_0.

**Comment by Yxue-1906** [comment]
> The method `toggleForumTopicIsPinned` is not available to bots. The method `toggleForumTopicIsClosed` can be used by bots.
> 
> I don't know, what can cause FLOOD_WAIT_0.

Will the restriction on bot pinning topic be loosen in the future? 
For the second issue, it occurs on both production and test server, no matter tg_cli or official telegram desktop version on linux; it seems like account is restricted on the server side.

**Comment by Yxue-1906** [comment]
well, thx for your answers. I will close this issue.
