### ISSUE TITLE
tdlib 1.8.4 Sometimes receive updateMessageEdited.edit_date=0

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2294]
Sometimes I receive updateMessageEdited with edit_date=0. There is no note in the documentation for that. What does it mean?

**Comment by levlam** [comment]
This is expected behavior. `edit_date == 0` in the update means that the message has no `edited` label, but some of message fields has changed.

**Comment by wowka1319** [comment]
Do you mean reactions, for example?

**Comment by ThanhPhongPhan** [comment]
0939368520
0915457241

Vào 21:44, Th 2, 6 thg 2, 2023 wowka1319 ***@***.***> đã viết:

**Comment by levlam** [comment]
There are a lot of cases, including addition of the first reaction in big supergroups.
