### ISSUE TITLE
setAuthenticationPhoneNumber How to obtain SMS verification code

### ISSUE THREAD

**Issue by mengfeishang** [tdlib/td#2298]
This is my code. I want to know how to set it so that tdlib can send the verification code to the phone instead of sending the verification code to the telegram client
```
                td_send({'@type': 'setAuthenticationPhoneNumber', 'phone_number': phone_number,"settings":{
									"allow_flash_call":True,
                                    "allow_missed_call":True,
                                    "is_current_phone_number": False,
                                    "allow_sms_retriever_api":False
                }})
```

**Comment by wowka1319** [comment]
I think that's only available for the official apps.

**Comment by mengfeishang** [comment]
Another library, telephone, can force mobile phones to receive text messages.So I feel that he is not the official reason

**Comment by levlam** [comment]
User autherntication is completely controlled by the server. Clients have no way to choose the way code is delivered.

**Comment by AYMENJD** [comment]
@Flohack74 See #2310.
