### ISSUE TITLE
PHP Example

### ISSUE THREAD

**Issue by rizhenkov** [tdlib/td#23]
Please write little simple PHP example for easy starting up. Thank you!

**Comment by yaroslavche** [comment]
I really don't know if there is any sense in this extension in PHP. In any case, see [here](https://github.com/yaroslavche/phptdlib) - simple (and ugly) implementation of td_json_client with example.
I'm not even sure what I did it right. Just for fun =)

**Comment by danog** [comment]
Or you could use my client, which is a native PHP implementation of MTProto.

**Comment by levlam** [comment]
You can use TDLib from PHP through [phptdlib](https://github.com/yaroslavche/phptdlib) (already mentioned there) or [PIF-TDPony](https://github.com/danog/pif-tdpony) extensions.
