### ISSUE TITLE
how to use TdApi.SupergroupMembersFilterSearch?

### ISSUE THREAD

**Issue by linhere20** [tdlib/td#230]
SupergroupMembersFilterSearch(java.lang.String query)
Constructor for initialization of all fields.

How to set the value of the query parameter?  any example ?  
thanks

**Comment by levlam** [comment]
```
new SupergroupMembersFilterSearch(query)
```

**Comment by linhere20** [comment]
sorry, i think i did not express myself clear. i understand how to call this function, but I don't know what the parameters(query) mean.  i guess QUERY should be a condition string, like sql: select * from table.

**Comment by levlam** [comment]
Sorry. Roughly speaking, each word in query is a prefix of first name/last name/username of users which will be returned. For example, query "Li" will return all users which first name, last name or username begins with "li" and query "Shw Arnie" can return "Arnold @arnie Schwarzenegger".

**Comment by linhere20** [comment]
thanks a lot
