### ISSUE TITLE
CheckAuthenticationEmailCode function strange behavior

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#2302]
Hi!
I've noticed some strange behavior when authorizing few clients via email.
1. Client enters his email to authorize.
2. Code arrives to this email. Application checks it successfully.
3. According to application logs right after the call to check email code, AuthorizationStateWaitCode event comes to wait and verify authorization code.
4. And there is no code sent to the client's official Telegram application.

This behavior is not expected? Why could tdlib ask to wait for app code besides email code in this case?

**Comment by levlam** [comment]
`authorizationStateWaitCode` is expected after `authorizationStateWaitEmailCode`. It is up to the server to decide, how to verify the user with how many checks, and how to send the authentication codes. You can share TDLib logs with https://t.me/tdlib_bot to double-check that this isn't a TDLib issue.

**Comment by imlifeilong** [comment]
@Mike497 Hello, I want to know how to use email verification code when login, where is this function?  Could you let me know, thank you?

**Comment by mpavlov-sephora-sg** [comment]
> [@Mike497](https://github.com/Mike497) Hello, I want to know how to use email verification code when login, where is this function? Could you let me know, thank you?

Hi @imlifeilong, use regular tdlib login flow: there is no dedicated function to login via email. Telegram servers will decide either your tdlib client will receive phone code or email code. You should take care of related phone/email handlers in your code.
