### ISSUE TITLE
An old session doesn't receive updates

### ISSUE THREAD

**Issue by JoshX94** [tdlib/td#2304]
I have a program that works with a newly logged in session file (td.binlog).

But when I replace the session file with an another one that was logged in before for my another account, I got the following information in the console and I am not able to receive updates from telegram after sending a request. 

Can someone help me understand what these information mean? 

[ 2][t 4][1675980016.933830022][AuthDataShared.cpp:107][#1][!Td]	DcId{4} [auth_key_id:123][state:OK][created_at:12345678.000000]
[ 2][t 4][1675980016.942703247][Session.cpp:241][#1][!SessionProxy:4:main]	Generate new session_id 12345678 for auth key 12345678 for main DC4
[ 2][t 4][1675980017.123697042][Session.cpp:587][#1][!Session:4:main]	Session connection with 0 pending requests was closed: [Error : -404 : MTProto error: -404] Session:4:main::Connect::Tcp::[123.123.123.123:443] to DcId{4} from [192.168.1.1:12345]
[ 2][t 4][1675980017.123707056][Session.cpp:611][#1][!Session:4:main]	Use PFS to check main key
[ 2][t 4][1675980017.219633102][ConnectionCreator.cpp:913][#1][!ConnectionCreator]	[[1234:11:111:1111::1]:443] to DcId{4}: [PosixError : No route to host : 65 : Failed to connect to [[1234:11:111:1111::1]:443]]
[ 2][t 4][1675980019.164831161][SessionProxy.cpp:246][#1][!SessionProxy:4:main]	Have tmp_auth_key 12345678: NoAuth
[ 2][t 4][1675980019.164867162][Session.cpp:1382][#1][!Session:4:main]	Update auth key in session_id 12345678 to 12345678
[ 2][t 4][1675980019.267376184][TempAuthKeyWatchdog.h:117][#1][!TempAuthKeyWatchdog]	Start auth_dropTempAuthKeys except keys {-12345678}
[ 2][t 4][1675980019.267431974][Session.cpp:366][#1][!Session:4:main]	Do not drop main key, because it was created too recently
[ 1][t 4][1675980019.267440319][Session.cpp:399][#1][!Session:4:main]	BindKey failed: [Error : 400 : ENCRYPTED_MESSAGE_INVALID]
[ 2][t 4][1675980019.382149934][Session.cpp:366][#1][!Session:4:main]	Do not drop main key, because it was created too recently
[ 1][t 4][1675980019.382158279][Session.cpp:399][#1][!Session:4:main]	BindKey failed: [Error : 400 : ENCRYPTED_MESSAGE_INVALID]
[ 2][t 4][1675980021.614860057][Session.cpp:366][#1][!Session:4:main]	Do not drop main key, because it was created too recently
[ 1][t 4][1675980021.614876031][Session.cpp:399][#1][!Session:4:main]	BindKey failed: [Error : 400 : ENCRYPTED_MESSAGE_INVALID]
[.... repeats the above 2 messages]

**Comment by levlam** [comment]
The data store in the old td.binlog is invalid and can't be used anymore.

**Comment by JoshX94** [comment]
Can we tell the reason why it became invalid from these info?

**Comment by AYMENJD** [comment]
Because you don't use TDLib in the normal way.

**Comment by levlam** [comment]
The sessio was logged out. Moreover, td.binlog is not a "session file" and it is not supposed to be replaced.
