### ISSUE TITLE
Vision accessibility options broke Telegram UI

### ISSUE THREAD

**Issue by chloe-everhart** [tdlib/td#2306]
Hi,

I use Pop! OS with 200% scaling and the Night Color always turned up most of the way.  Telegram is installed as Flatpak through Pop! Shop.

My accessibility options broke the Telegram UI.  Using 200% scaling from the GNOME settings menu, the area where I type the messages is off the screen, and I can't shrink the window so it will fit on the screen.  I can't get to all the menu options.

When I click the thoughtfully placed icon to switch to 100%, everything gets too small to read easily, but the buttons are back on the page.  When I turn off "use system defaults", and use the slider to increase the scale to where reading it is comfortable, the type box and menu options are off the page and inaccessible again.  

Could you please help me find a solution, so that Telegram won't get bigger than my monitor when I scale to 250% or 300%?

Thank you,

**Comment by levlam** [comment]
It looks like you have an issue with https://github.com/telegramdesktop/tdesktop instead of TDLib.

**Comment by chloe-everhart** [comment]
Thanks
