### ISSUE TITLE
TdApi.GetSupergroupMembers returns 400, but desktop telegram client shows members

### ISSUE THREAD

**Issue by BioRyajenka** [tdlib/td#2309]
Hello!

When I use TdApi.GetSupergroupMembers from my code, it returns 400 `CHAT_ADMIN_REQUIRED`. But at the same time using desktop telegram app I can see the group members. 

Should I use some other function to get members? Or does desktop client have more priviledgies? 

I call the function like this: `new TdApi.GetSupergroupMembers(superGroupId, null, 0, 200)`, which should mean "get first 200 users with "recent" filter"

**Comment by levlam** [comment]
The error `CHAT_ADMIN_REQUIRED` means that you are trying to get members of a channel and aren't an administrator.

**Comment by BioRyajenka** [comment]
I understand @levlam , thank you. But why does Telegram Desktop can see the members? Does it use some hidden functions or has more priviledges?
My expectation was that every client (including mine) should have same permissions.

**Comment by levlam** [comment]
You can't see channel members, unless you are an administrator and Telegram Desktop also can't. If you see members from Telegram Desktop, then either you look from a different account with enough priviledges, or in a different chat.

**Comment by BioRyajenka** [comment]
Its not channel, its just supergroup. Not sure if it is important. 
![Uploading image.png…]()

**Comment by BioRyajenka** [comment]
You're right. I found bug in my code. Sorry for taking your time
