### ISSUE TITLE
Cant downloadFile 

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#231]
Hello!

Your work is brilliant, it helps fast to build Telegram app. Thank you.

I've encountered an issue. cant donwload file of avatar with id 1812616928266659755. It's a user's avatar. I got it from profilePhoto's id. downloadFile is sent, but nothing happens after that. Using json lib in cpp.

``` {\"@type\":\"downloadFile\",\"file_id\":\"1812616928266659755\",\"priority\":12} ```
What is wrong?

**Comment by levlam** [comment]
"1812616928266659755" - isn't a correct file_id, file_id is always small integer number.

**Comment by blacksailer** [comment]
Yes, I should took id from small_ or big_ fields, thanks!
