### ISSUE TITLE
telegram.org's tdlib documentation is outdated

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2311]
There's no reference of `reactions` field or `messageReaction` type in the auto generated references it seems.

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_interaction_info.html

**Comment by AYMENJD** [comment]
On site documentation is outdated, instead use: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.

**Comment by vincentneo** [comment]
Thanks. Will the on site documentation be updated in the future?

**Comment by AYMENJD** [comment]
Yes, on site documentation TDLib version is 1.8.0. And it get updated on every minor version release.

**Comment by vincentneo** [comment]
Ok got it, thanks for the reply.
