### ISSUE TITLE
actions with supergroup chat

### ISSUE THREAD

**Issue by p-vorobyev** [tdlib/td#2313]
Hello!

I want to clarify how correctly use chat api with supergroups(channels in my case). I'm using tdlib v1.8.0 for java.

My steps:
1) Search for public chat using `TdApi.SearchPublicChat("some_chat_name")` and successfully receive Chat object.
2) From `Chat` object I extract info about `id` starting with prefix `-100`, `ChatTypeSupergroup` with `supergroupId` and channel flag.

And I'm stuck on next actions, because `JoinChat` returns 
```
Error {
  code = 400
  message = "Chat not found"
}
```
I'm passing to constructor `supergroupId`(because api not allowed chatId with prefix `-100`). Where can I find correct chatId for channel and how correctly join to it?

Thanks for your time!

**Comment by levlam** [comment]
`JoinChat` expects a `chat_id`, not a `supergroup_id`. Just pass the received `chat_id`.

**Comment by p-vorobyev** [comment]
> `JoinChat` expects a `chat_id`, not a `supergroup_id`. Just pass the received `chat_id`.

Yeap, it's my fault. Thanks for clarification, now it's ok. For some reason I thinked that `supergrupId` should be used instead of `chatId`, but it's wrong of course...
