### ISSUE TITLE
Session connection with x pending requests was closed

### ISSUE THREAD

**Issue by bubblecsh** [tdlib/td#2314]
Hi
What could be the cause to receive this kind of errors sometimes?

`[1;33m[ 2][t 4][1676994325.355236291][Session.cpp:628][#1][!Session:4:main]	Session connection with 3 pending requests was closed: [Error : 0 : No answer for [Query:[id:6029312][tl:0xc8a0ec74][state:Query]] for 61.3s] Session:4:main::Connect::TCP::[149.154.167.91:443] to DcId{4} from [172.31.255.20:47346][0m`

`[ 2][t 4][1676995604.017034053][Session.cpp:628][#1][!Session:4:main]   Session connection with 0 pending requests was closed: [PosixError : Connection reset by peer : 104 : Error on [fd:45]] Session:4:main::Connect::TCP::[149.154.167.92:443] to DcId{4} from [172.18.0.4:50906]`

**Comment by levlam** [comment]
Those are warnings about poor network. Network errors can happen also on otherwise good network. There is no way to avoid them.

**Comment by AYMENJD** [comment]
TDLib can remain stable on poor network, so it shouldn't.
