### ISSUE TITLE
Issue in obtaining WEBRTC server type.

### ISSUE THREAD

**Issue by lollix91** [tdlib/td#2316]
I'm using TdLib in Java. When i receive a new call, i accept it using the following code:

`client.send(new TdApi.AcceptCall(callId, new TdApi.CallProtocol(true, false, 65, 65, null)), defaultHandler);`
setting the udpReflector parameter to false, so i should obtain WebRtc server to connect to the call.

The object i obtain in response, is an UpdateCall, but with 3 Servers "CallServerTypeTelegramReflector".
How can i obtain WebRtc servers?

I need it to connect to the server using a third party RTC library, because, using Java, tdcalls is not available in an "easy" way (without writing a python wrapper for tgcalls).

**Comment by levlam** [comment]
You must provide valid and supported tgcalls library versions as the last parameter of `callProtocol` to receive supported by them reflectors. If you would use `tgcalls` the list of supported versions can be obtained by calling `tgcalls::Meta::Versions()`.
