### ISSUE TITLE
parse_mode is not working

### ISSUE THREAD

**Issue by iamcloner** [tdlib/td#2319]
I'm using TdLib in Python. I tried to send a message with parse_mode using the following methods, but the message is sent without parse_mode

```
{
    '@type': 'sendMessage',
    'chat_id': int(chatId),
    'input_message_content': {
        '@type': 'inputMessageText',
        'text': {'@type': 'formattedText', 'text': 'test','entities':[{'offset':0,'length':3,'TextEntityType':{'@type':'textEntityTypeCode'}}]},
    },
}
```
          
And I tried with this method too

```
{
    '@type': 'sendMessage',
    'chat_id': int(chatId),
    'input_message_content': {
        '@type': 'inputMessageText',
        'text': {'@type': 'parseTextEntities', 'text': '<pre>test</pre>','parse_mode':{'@type':'textParseModeHTML'}},
    },
}
```
The output of both methods is plain text

**Comment by AYMENJD** [comment]
First you must call `parseTextEntities` and then pass the `parseTextEntities` result to `input_message_content.text`.

**Comment by levlam** [comment]
The text entity must be specified as `{'offset':0,'length':3,'type':{'@type':'textEntityTypeCode'}}`.

**Comment by iamcloner** [comment]
> The text entity must be specified as `{'offset':0,'length':3,'type':{'@type':'textEntityTypeCode'}}`.

This method solved the problem. thank you
