### ISSUE TITLE
Support for MTProto proxy 

### ISSUE THREAD

**Issue by omkarnathsingh** [tdlib/td#232]
Tdesktop and 2 other Apple platform apps support it. Its showing great results in regions of blocking. Please add its support so that we can get it on TGX Android platform. 

Thanks.

**Comment by alexmalishev270896** [comment]
Support for MTProto now available in official Telegram on Android. Please, add its support to tdlib.

**Comment by levlam** [comment]
MTProto-proxy support is added to TDLib since 1.3.0.

**Comment by mostafa8026** [comment]
Could you provide a little example of how can we use it?

**Comment by levlam** [comment]
@mostafa8026 You need to call `addProxy` with `proxyTypeMtproto`. Exact syntax depends on your programming language and interface your are using.
