### ISSUE TITLE
Can JSON be UTF-8?

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2321]
I saw example https://github.com/tdlib/td/blob/master/example/python/tdjson_example.py#L65:
```python3
def td_send(query):
    query = json.dumps(query).encode('utf-8')
    _td_send(client_id, query)
```
but that is actually:
```python3
def td_send(query):
    query = json.dumps(query, ensure_ascii=True).encode('utf-8')  # == .encode("ascii")
    _td_send(client_id, query)
```
Your example does: `{'heart':'🤎'} -> '{"heart":"\\ud83e\\udd0e"}' -> b'{"heart":"\\ud83e\\udd0e"}'`

Is it allowed this way:
```python3
def td_send(query):
    query = json.dumps(query, ensure_ascii=False).encode('utf-8')
    _td_send(client_id, query)
```
?
My example does: `{'heart':'🤎'} -> '{"heart":"🤎"}' -> b'{"heart":"\xf0\x9f\xa4\x8e"}'`

**Comment by AYMENJD** [comment]
I tested, it works fine. But i don't know if this is recommended.

**Comment by levlam** [comment]
TDLib JSON parser allows raw UTF-8 characters in JSON strings, therefore `json.dumps` with `ensure_ascii == false` should work.

**Comment by wowka1319** [comment]
Thank you!
