### ISSUE TITLE
Authorization code does not come

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2322]
calling the function: `SetAuthenticationPhoneNumber` 
It returns: `Ok`. 
The state changes to:

> {@type: updateAuthorizationState, authorization_state: {@type: authorizationStateWaitCode, code_info: {@type: authenticationCodeInfo, phone_number: <some_number>, type: {@type: authenticationCodeTypeTelegramMessage, length: 5}, next_type: null, timeout: 0}}}

As a result message does not come to telegram. tried many times and from different phone numbers

This happens very often. This may occur when we decide to release our application.
What to do in such a situation?

**Comment by AYMENJD** [comment]
Sorry, there is an issue with Telegram login system. Please wait until it's fixed.

**Comment by eugene2k** [comment]
I seem to have the same problem developing an alternative Android client (using tdlib's java bindings). The phone number is from a phone that has the official client installed and I'm connecting with the following settings:

deviceModel = "Phone"
applicationVersion = "1.0"
useFileDatabase = false
useChatInfoDatabase = false
useMessageDatabase = false
useSecretChats = false
enableStorageOptimizer = true
systemLanguageCode = "en"
useTestDc = true

I call setAuthenticationPhoneNumber(phoneNumber), receive an Ok, and the state is switched to AuthorizationStateWaitCode with the same contents as in the issue, but I get no notifications in Telegram. Is there something I'm doing wrong or is it something on Telegram's end?

**Comment by levlam** [comment]
@eugene2k You specified `useTestDc = true`. Are you sure that you are logged to the Test DC in the official client?

By the way, you can try to test authorization in Test DC with a [test account](https://core.telegram.org/api/auth#test-accounts) first.

**Comment by eugene2k** [comment]
I haven't realized there's a need to log in to the test dc with the official client. I can't find any mention of this or how it can be done.

**Comment by levlam** [comment]
Test DC is a completely independent environment.
