### ISSUE TITLE
Log level in td_set_log_message_callback() does not work?

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2323]
I set loglevel=1 (FATAL+ERROR):
```python3
@log_message_callback_type
def log_message_callback(verbosity_level, message):
    if verbosity_level == 0:
        sys.exit(f"TDLib fatal error: {message}")

tdlib.td_set_log_message_callback(1, log_message_callback)
```

but I'm watching too much logs. I guess the most ones is not ERROR/FATAL. Example: `Begin to wait for updates with timeout 1.000000`

**Comment by AYMENJD** [comment]
You need to change TDLib verbosity level using: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_log_verbosity_level.html.

**Comment by wowka1319** [comment]
Ok. But what does the first parameter in `td_set_log_message_callback` do?

**Comment by AYMENJD** [comment]
The max verbosity level that can be logged with the specified callback.

**Comment by wowka1319** [comment]
Got it.
That is, given the implementation of the callback, level=2 doesn't matter and 0 would be enough?
```python3
@log_message_callback_type
def on_log_message_callback(verbosity_level, message):
    if verbosity_level == 0:
        sys.exit('TDLib fatal error: %r' % message)
```
```python3
_td_set_log_message_callback(2, on_log_message_callback)  # -> _td_set_log_message_callback(0, on_log_message_callback)

```

**Comment by fatimasandoval798** [comment]
#_td_set_log_message_callback(2, on_log_message_callback)  # -> _td_set_log_message_callback(0, on_log_message_callback)

**Comment by levlam** [comment]
@wowka1319 Most likely, you don't need a callback for log messages at all.

Instead you need to use `setLogVerbosityLevel` and `setLogStream` methods to set up logging.

**Comment by wowka1319** [comment]
Ok. In your example the callback allows handle fatal error. What happens when fatal error if no that callback with `sys.exit(1)`?
I got special update when calling `td_receive()`?

**Comment by AYMENJD** [comment]
All logs including fatal error will be logged to the specified stream using `setLogStream`.

**Comment by wowka1319** [comment]
Just crashing? Then why is `sys.exit("...")` in the example?:
```python3
@log_message_callback_type
def on_log_message_callback(verbosity_level, message):
    if verbosity_level == 0:
        sys.exit('TDLib fatal error: %r' % message)
```
I suspect a fatal error brings the client into an incorrect state without crashing. Or it doesn't?

**Comment by wowka1319** [comment]
When crashing of C++ code (caused by incorrect working with memory for example) there's no chance to stop the application gracefully. That's why it's impossible to log that error. But I see that message as a fatal error. That means handling that case is possible without crashing my python app: recreate a client and so on. I think developers provided this opportunity. Or not?

**Comment by levlam** [comment]
Fatal errors are errors that can't be handled without crashing. The process will be terminated anyway right after the callback returns.

**Comment by wowka1319** [comment]
Thanks guys!
