### ISSUE TITLE
How can you pass the downloaded image from the `downloadFile` function to an `<img>` element? #question

### ISSUE THREAD

**Issue by careverca** [tdlib/td#2324]
Hello! 
I am using **tdweb** inside a **React app** with a Webpack.
The path of the `localFile` (`file.local.path`) from the `downloadFile` function looks like this: 
`/tdlib/inboundfs/photos/5449433374381948026_97.jpg`
When I am trying to pass this path as a `src` attribute to the `<img>` element, I am getting the following error:
```
Uncaught Error: Cannot find module '/tdlib/inboundfs/photos/5449433374381948026_97.jpg'
    at webpackEmptyContext (components|sync:2:1)
    at Pic (Pic.tsx:83:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
```

Due to Webpack, the `src` attribure of my `<img>` element looks like this:
`<img src={require(url)} />}`

As for the downloaded file status, it looks good to me:
```
{@type: 'file', id: 1112, size: 13177, expected_size: 13177, local: {…}, …}
@client_id: 1
@extra: {query_id: 5}
@type: "file"
expected_size: 13177
id: 1112
local: 
  @type: "localFile"
  can_be_deleted: true
  can_be_downloaded: true
  download_offset: 0
  downloaded_prefix_size: 13177
  downloaded_size: 13177
  is_downloading_active: false
  is_downloading_completed: true
  path: "/tdlib/inboundfs/photos/5449433374381948026_97.jpg"
  [[Prototype]]: Object
remote: {@type: 'remoteFile', id: 'AgACAgIAAxUAAWP7bGE4RsfAkB4F91lHxka927a4AAJ6vDEbyEagSylncN-UwShUAQADAgADYQADIwQ', unique_id: 'AQADerwxG8hGoEsAAQ', is_uploading_active: false, is_uploading_completed: true, …}
size: 13177
```

Please help me to pass the downloaded .jpg image to the `<img>` element.
Thank you in advance

**Comment by levlam** [comment]
See https://github.com/evgeny-nadymov/telegram-react/blob/afd90f19b264895806359c23f985edccda828aca/src/Stores/FileStore.js#L812 for the way to get the file as a blob. Then you need to show an image with content of the blob.

**Comment by careverca** [comment]
> See https://github.com/evgeny-nadymov/telegram-react/blob/afd90f19b264895806359c23f985edccda828aca/src/Stores/FileStore.js#L812 for the way to get the file as a blob. Then you need to show an image with content of the blob.

Thank you!
