### ISSUE TITLE
Optimal timeout for td_receive()?

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2325]
In python example is **1.0** https://github.com/tdlib/td/blob/master/example/python/tdjson_example.py#L70

In java example is **100000.0** https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/Client.java#L148

I understand it's easier to control application with smaller value. But despite that is there recommendation?

**Comment by AYMENJD** [comment]
This is up to you. Timeout must be high enough.

**Comment by levlam** [comment]
Any big enough value is suitable. If updates are fetched from a dedidated and never terminated thread, then 1e5 is definitely a good value.
