### ISSUE TITLE
JoinGroupCall class

### ISSUE THREAD

**Issue by Geliusan** [tdlib/td#2327]
ran into a problem.  I want to connect to the created group call.  However, there are two parameters, the receipt of which causes me difficulties - audioSourceId and payload , it is written that they are taken from tgcalls , however, after checking all the library files, I did not find such parameters.  And the documentation itself, examples and projects are mostly written in python, there is nothing in C ++.  Maybe someone has worked with this and can help me?

**Comment by levlam** [comment]
https://github.com/telegramdesktop/tdesktop uses `tgcalls` and is written in C++, so its source code should help.
