### ISSUE TITLE
Problem with TdApi.SendMessageAlbum

### ISSUE THREAD

**Issue by alon-sys** [tdlib/td#2328]
List<TdApi.InputMessageContent> inputMessageContentList = new ArrayList<>();
        for(int i=0;i<9;i++) {
            TdApi.InputFileRemote photoFile1 = new TdApi.InputFileRemote();
            photoFile1.id = "AgACAgUAAx0Cbm1F2AACA8Jj_XPDdylr2Tf25uhC...........";
            TdApi.InputMessagePhoto messagePhoto1 = new TdApi.InputMessagePhoto();
            messagePhoto1.photo = photoFile1;
            TdApi.FormattedText tx = new TdApi.FormattedText();
            tx.text = "xxxx";
            messagePhoto1.caption = tx;
            inputMessageContentList.add(messagePhoto1);
        }
TdApi.InputMessageContent[] inputMessageContents = inputMessageContentList.toArray(new TdApi.InputMessageContent[0]);
TdApi.SendMessageAlbum(chatId, 0, 0,null, inputMessageContents, false)

By calling the TdApi.SendMessageAlbum, one of the pictures will be sent separately. Is there something wrong with my writing?

**Comment by levlam** [comment]
Could you send TDLib logs with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by alon-sys** [comment]
> Could you send TDLib logs with verbosity level 4 to https://t.me/tdlib_bot?

Log has been uploaded

**Comment by levlam** [comment]
This is a known server-side bug. It can sometimes happen when a user sends an album to a supergroup/channel, and the user and the supergroup have different main datacenters.

**Comment by alon-sys** [comment]
> This is a known server-side bug. It can sometimes happen when a user sends an album to a supergroup/channel, and the user and the supergroup have different main datacenters.

How to solve it, or is there any other way to send？

**Comment by levlam** [comment]
There is no workaround if the user and the channel have different main datacenters.

**Comment by levlam** [comment]
@alon-sys Could you check whether the issue can be still reproduced or it was fixed?

**Comment by alon-sys** [comment]
It will still appear

**Comment by levlam** [comment]
@alon-sys Could you send new log with the issue reproduced?

**Comment by levlam** [comment]
@alon-sys Do you still have the issue with albums being split by the server, or they are sent as expected now?

**Comment by alon-sys** [comment]
@levlam I tested it just now, and I didn't find the previous problem. Have you fixed it?

**Comment by levlam** [comment]
Yes. The cause of the issue in your case was supposed to be fixed.

**Comment by alon-sys** [comment]
Thank you for your dedication
