### ISSUE TITLE
`mutable-content` for watchOS platform notifications

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2330]
According to #521, it's only sent if `system_version` is 10.0 and above. 
However, that value is only accurate for iOS, not watchOS. Notification Service Extension is supported since watchOS 6.0.

**Comment by levlam** [comment]
Can you use encrypted VoIP pushes?

**Comment by levlam** [comment]
Could you check that `watchOS` pushes have `mutable-content` flag?

**Comment by vincentneo** [comment]
> Can you use encrypted VoIP pushes on watchOS instead?

I have yet to try that.

> Could you check that `watchOS` pushes have `mutable-content` flag?

If `system_version` is set to 10.0 it does have it.

**Comment by levlam** [comment]
> If `system_version` is set to 10.0 it does have it.

Can you check that it is set for watchOS 6.0+ either now?

**Comment by vincentneo** [comment]
> > If `system_version` is set to 10.0 it does have it.
> 
> Can you check that it is set for watchOS 6.0+ either now?

@levlam yes it seems to be working now. Set `system_version` to 6.0 and works!

Thank you!

**Comment by levlam** [comment]
@vincentneo Could you also confirm that if you pass an empty `system_version`, then it is correctly identified as `watchOS 6.0` by TDLib?

**Comment by vincentneo** [comment]
@levlam I don't know how/if TDLib correctly identified it as whichever watchOS version, but passing an empty `system_version` does work.
