### ISSUE TITLE
updateSupergroup[FullInfo] after updateNewChat only?

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2332]
**updateSupergroup[FullInfo]** is guaranteed to come only after the coresponding **updateNewChat**?
In other words, when receiving **updateSupergroup[FullInfo]** can I be confident that I received **updateNewChat** before?

**Comment by AYMENJD** [comment]
> In other words, when receiving updateSupergroup[FullInfo] can I be confident that I received updateNewChat before?

Yes, `updateNewChat` is always the first update about the chat.

**Comment by wowka1319** [comment]
However I receive **updateSupergroup** first and then **updateNewChat**. The delay is less 0.001 sec, but that **ordering is stable**.

**Comment by levlam** [comment]
`updateSupergroupFullInfo` is an update about a supergroup, so it comes after `updateSupergroup`. But it is completely independent with `updateNewChat`.

**Comment by wowka1319** [comment]
How to get chat_id from Supergroup? Adding prefix -100 doesn't seem to be a durable way (didn't see that guarantee in docs).

**Comment by levlam** [comment]
@wowka1319 You need to use the method `createSupergroupChat` for this.
