### ISSUE TITLE
Getting a 500 "Request aborted" and 401 "Unauthorized" after `authorizationStateReady`

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2334]
Here are the logs: 
[logs.txt](https://github.com/tdlib/td/files/10899225/logs.txt)
1. line 1792: `authorizationStateReady`
2. line 1836: trying to call 
`this.client!.send({
      "@type": "searchPublicChat",
      username: this.name,
});`
4. line 2003: code: 500
5. line 2452: code: 401

Thanks for such a commitment and quick responses!

**Comment by teleothleo** [comment]
Also, after refreshing the page (I am using React), TdLib asks for password again. Without asking anything else. This happens a few times, but eventually you get logged in without a password and the 401 error. The 500 however, persists.

**Comment by AYMENJD** [comment]
> tdweb.js:2100 send to worker:  {@type: 'close'}

It seems like you are closing the instance which will cause 500 and 401 errors.

**Comment by teleothleo** [comment]
> > tdweb.js:2100 send to worker:  {@type: 'close'}
> 
> It seems like you are closing the instance which will cause 500 and 401 errors.

Yes. I somehow reinitialized the Client when the AuthState got updated. Thank you for the right tip!
