### ISSUE TITLE
How to calculate offset/length in formattedText (python)?

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2338]
**text** in `formattedText` is `string` that contains UTF-8, but **offset**/**length** in `textEntity` are in UTF-16 code units.
How to calculate substrings?
`text.encode("utf-16")[offset * 2 : (offset+length) * 2].decode("utf-16")` works almost correctly, but looses the last symbol. How to fix that?
P.S: I use Python

UPD: I change `utf-16` -> `utf-16-be` and it works correctly. Why?

**Comment by levlam** [comment]
> I change utf-16 -> utf-16-be and it works correctly. Why?

Because "utf-16" encoding in Python adds byte order mark to the beginning of the encoded string and "utf-16-be" doesn't.

**Comment by wowka1319** [comment]
I have just discovered that and wanted to write. You got ahead of me) Really, two bytes `FFFE` or `FEFF` are at the beginning of a string. Thank you!
