### ISSUE TITLE
About usernames

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2339]
Upgraded the lib to the last master commit (1.8.12) and noticed a change: `Supergroup.username = string` to `Supergroup.usernames = active_usernames:vector<string>, disabled_usernames:vector<string>, editable_username:string`.
1. Now channels can have multiple usernames at the same time? They are in `active_usernames`? Or only the first username in `active_usernames` works? Otherwise what does primary username mean?
2. What does `editable_username` mean? How it works?

**Comment by wowka1319** [comment]
For public supergroups `usernames` is not null always?

**Comment by levlam** [comment]
Yes.
