### ISSUE TITLE
Illegal region

### ISSUE THREAD

**Issue by zelenin** [tdlib/td#234]
I got a message ```Illegal region``` when I created a client instance.
What is it? How should this work?

full start log: https://gist.github.com/zelenin/95bbbb8141ef3fce453b32751638d528

**Comment by zelenin** [comment]
I checked three cases: 
- alpine/docker on debian 9.4 - not works
- alpine/docker on ubuntu 18.10 - not works
- alpine/docker on ubuntu 18.10 - it works

**Comment by levlam** [comment]
Message "Illegal region" isn't from a TDLib. It looks like some kind of runtime error, but I can't find any mentions of it and what it means. It would be helpful if you will try to run TDLib under some debugger like gdb/lldb and find out the exact cause of the error.

**Comment by zelenin** [comment]
oh, shame. I remote debugged with dlv and found that the error was in 3rd party code locally working without errors.
Thanks.
