### ISSUE TITLE
Deleting telegram accounts

### ISSUE THREAD

**Issue by k0ry** [tdlib/td#2340]
Hello,
we faced with a problem of deleting user's accounts from Telegram's side after some period of using our application, based on tdlib. 
User activity - reading channels, chating and  so on. Usual activity of average user.
Also, sometimes, user's phone numbers are banned after that and they can't register account again.
What can cause this?
![IMAGE 2023-03-12 17:20:58](https://user-images.githubusercontent.com/232878/224550746-1b33bd16-7f9f-40f7-85f4-b75a41d085f5.jpg)

**Comment by ThanhPhongPhan** [comment]
0939368520

***@***.***

Vào 19:27, CN, 12 thg 3, 2023 Filipp ***@***.***> đã viết:

**Comment by levlam** [comment]
You need to contact recover@telegram.org, providing them phone numbers and other details.

**Comment by k0ry** [comment]
Hi, we have dozens of blocked accounts, but from recover@telegram.org no any answer, can you help with that?

**Comment by levlam** [comment]
I can do nothing, only they can help. You can ask affected users to try to log in through an official app and send an appeal to the provided by them email address.

**Comment by k0ry** [comment]
Thank you!

**Comment by GabrielBianconi** [comment]
Hi @k0ry - did you manage to resolve this problem?

I'm building an application and accounts are getting instantly banned after the first log-in using tdlib. I've reached out to recover@telegram.org but haven't heard back in a while.

**Comment by Tecachehahaha** [comment]
https://github.com/tdlib/td/issues/2488#issuecomment-1586316435
