### ISSUE TITLE
Notifications delas on iOS

### ISSUE THREAD

**Issue by SixthTR** [tdlib/td#2341]
Please remove the delay in receiving new notifications.

https://github.com/TelegramMessenger/Telegram-iOS/issues/1022#issuecomment-1462275173

**Comment by ThanhPhongPhan** [comment]
***@***.***

Vào 19:31, CN, 12 thg 3, 2023 SixthTR ***@***.***> đã viết:

**Comment by levlam** [comment]
Push notifications must be delayed for users with other active sessions.

**Comment by SixthTR** [comment]
> Push notifications must be delayed for users with other active sessions.

I have no other active sessions but I have delay.

**Comment by SixthTR** [comment]
@levlam
