### ISSUE TITLE
[400 Chat not found] when openChat for joined channels

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2344]
I migrated 1.8.4 -> 1.8.12 and see that error when calling `openChat` for **joined** channels (not all of them, some don't cause that error).
Yes, I use chat_id saved in an external db, but there was no trouble before. I thought when starting app the lib had to load all joined channels/groups. What is the best way to avoid this error? Just call`getChats` after every starting app?

**Comment by AYMENJD** [comment]
The chat must be known/loaded to the current TDLib instance, you must call `loadChats` on every restart to load chats.

**Comment by wowka1319** [comment]
Ok. `loadChats`.
How to know all chats are loaded? Must I call `loadChats` so many times until a `404` error occurs?

**Comment by AYMENJD** [comment]
Yes.

**Comment by wowka1319** [comment]
After `loadChats` call corresponding updates about all loaded chats (changePosition,changeLastMessage,...) arrive before **ok/404** of `loadChats`?

**Comment by AYMENJD** [comment]
This shouldn't matter.

**Comment by wowka1319** [comment]
In Java example: `if (!haveFullMainChatList && limit > mainChatList.size()) {` https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java#L250
`limit` in docs is for all list or only each call of `loadChats`?

**Comment by wowka1319** [comment]
I mean if there are 150 channels calls with `limit`=100 will load only 100 ones and the next call returns 404, or I'll get all 150?

**Comment by AYMENJD** [comment]
The `limit` is up to TDLib. It may load chats lower than the specified `limit`.

If you want to load all chats you must call `loadChats` until you receive 404.

**Comment by wowka1319** [comment]
Thank you!

**Comment by wowka1319** [comment]
I set limit to 20 and see only 5 `loadChats` calls with **ok** and 6th with **404**. That is maximum 100-120 channels, but the client subscribed on 400+ ones. What is wrong?

**Comment by levlam** [comment]
You need to check actual number of loaded chats. It will be correct.

**Comment by wowka1319** [comment]
You mean `updateChatPosition`/`updateChatLastMessage` to check number of chats?
