### ISSUE TITLE
Using tdlib with flutter

### ISSUE THREAD

**Issue by wassmtg** [tdlib/td#2349]
Hi everyone
Just want someone to tell me how to work with tdlib in flutter
And thanks a lot.

**Comment by levlam** [comment]
See https://github.com/tdlib/td/tree/master/example#dart.

**Comment by wassmtg** [comment]
What should i do next?

**Comment by levlam** [comment]
The link contains a lot of examples and even TDLib-based apps made with Flutter.

**Comment by wassmtg** [comment]
What i want to say that this repo doesn't look like a flutter files

**Comment by levlam** [comment]
There are a lot of examples available there and they definitely contain a lot of "flutter files".

**Comment by wassmtg** [comment]
I'm a little bit confused
I didn't find them

**Comment by levlam** [comment]
See https://github.com/tdlib/td/tree/master/example#dart.

**Comment by wassmtg** [comment]
Those plugins didn't work for me.
Do you know how to build my own plugin?

**Comment by levlam** [comment]
They are mostly wrappers, which allow you to access TDLib from Flutter. You can easily write your own, but any of the existing wrappers should work. Also, you can find there two links to being developed Telegram apps in Flutter.
