### ISSUE TITLE
Uploading is not canceling. 

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#235]
Hello!
I' ve got issue. I can't cancel upload of a file. I trying to call ```cancelUploadFile``` with correct file_id (file_id is matches with file_id in ```updateFile``` )

I even got an ```ok``` type in return, but uploading continues. Even after recreating client uploading continues. How to stop uploading?

Thanks in advance!

**Comment by blacksailer** [comment]
Also I trying to send some smaller files I got this output and  seg fault:
```
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 944856524
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 944839368
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 936675752
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 936675752
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 898863364
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 944856524
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 1055997424
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 936675752
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 936675752
[W] unknown:0 - Trying to construct an instance of an invalid type, type id: 898863364
```

**Comment by levlam** [comment]
cancelUploadFile should be used only for files uploaded using uploadFile. It looks like you are trying to cancel sending a message, so you need to delete the message.

"Trying to construct an instance of an invalid type" warning is not from TDLib.

**Comment by blacksailer** [comment]
Yes, deleteMessages works. 
I thought that cancelDownloadFile works, so cancelUploadFile should too. Maybe add a note to cancelUploadFile? Should I pull request a change to docs?

**Comment by levlam** [comment]
Description of cancelUploadFile already has "Supported only for files uploaded by using uploadFile. For other files the behavior is undefined".

**Comment by blacksailer** [comment]
Ok, my bad. Will be more careful next time.  Thanks!
