### ISSUE TITLE
I use tdlib to generate the td.binlog file, but I want to know how to generate the. session file

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2351]
I use the c++client of tdlib. After starting the login, the td.binlog file is generated. I want to know whether I can generate a session file, or directly read the session file and then log in directly

**Comment by levlam** [comment]
TDLib has no "session files".

**Comment by liaoxingquan** [comment]
> TDLib has no "session files".

What version can generate the. session file. Thank you

**Comment by AYMENJD** [comment]
There is no such thing as ".session" file in TDLib.

**Comment by liaoxingquan** [comment]
What other versions besides tdlib，can be generated . session file

**Comment by AYMENJD** [comment]
TDLib has never generated ".session" file in it's history.

> There is no such thing as ".session" file in TDLib.

**Comment by liaoxingquan** [comment]
tdlib android versions also can not be generated . session file?

**Comment by AYMENJD** [comment]
No. There is nothing as ".session" file.

**Comment by liaoxingquan** [comment]
okey ,thank you
