### ISSUE TITLE
TDlib PC，Why can't I receive registered SMS

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2352]
I just used the C++version of TDlib PC, but I can't receive the registered SMS

**Comment by AYMENJD** [comment]
Login codes of type SMS are only sent to official Telegram apps. You can login to that account using one of the official Telegram apps and then you will receive the code from Telegram service notification account.

**Comment by liaoxingquan** [comment]
But I use the official PC terminal of Telegram, and I also can't receive text messages

**Comment by AYMENJD** [comment]
Try using Telegram Android or IOS.

**Comment by liaoxingquan** [comment]
why PC terminal can not receive

**Comment by AYMENJD** [comment]
Due to high costs of sending SMS Telegram has made only official clients to receive SMS.

**Comment by liaoxingquan** [comment]
Oh, I see

**Comment by Flohack74** [comment]
@levlam one more additional question on that, if we request an SMS code via tdlib, is there an error message that this code method is no longer supported?

**Comment by levlam** [comment]
You can't request an SMS code via TDLib. Instead, TDLib request the app to provide authentication code if appropriate by sending corresponding `updateAuthorizationState`. There is no way to affect the method, which was used to deliver the code.

**Comment by Flohack74** [comment]
Ok so let me explain, our App cannot receive codes anymore since we are not based on Android or iOS IF the user is a first time signup. Is there a way we can evaluate that and tell him, go to another Telegram client, desktop, web, to get you signed up?

**Comment by levlam** [comment]
There is no way. You need to add something like "if you aren't logged in another app, please, log in using an official mobile Telegram app first" to the description of the `authenticationCodeTypeTelegramMessage` code type.
