### ISSUE TITLE
TDLib as Dependency for Java

### ISSUE THREAD

**Issue by Ioakeimis** [tdlib/td#2355]
Hi, 

I am not a very experienced Programmer and as a result I am having a hard time using the Telegram API. Isn't it possible to just import TDLib as a dependency for example for Java through Maven or some other dependency manager? 
If not then how can I use the built API for my Custom Application?
I have successfully managed to build/create a Java Project by following the steps from the instructions generator. But I do not know how to move on from here. Thanks in advance

**Comment by levlam** [comment]
TDLib is a native library and hence it can be used from Java through JNI. TDLib provides the JNI wrapper, so you just need to add TdApi.java and Client.java in the appropriate package to source code of your project, and place `tdjni` shared object in the place from which it can be loaded by `System.loadLibrary("tdjni")`.

**Comment by Ioakeimis** [comment]
Is it possible to give a step by step process using maybe bullet points? or something similar that is easy for inexperienced programmers such as myself? 
And how would the steps look like if I modified the telegram class? I read somewhere that I would need to recompile or something...
Basically my goal is to scrape telegram messages from a public group. i am sure I can figure that out by myself though, if I manage to make the library work in the first place. Thanks

**Comment by levlam** [comment]
Step-by-step instruction is available at https://github.com/tdlib/td/blob/master/example/java/README.md.
