### ISSUE TITLE
Login code doesn't arrive on main DC

### ISSUE THREAD

**Issue by flexagoon** [tdlib/td#2356]
When I run my TDLib app on the Test DC, the  login code gets sent to my account immediately when I set the phone number in TDLib.

However, if I use the main DC, the code does not get sent. TDLib doesn't output any errors, even with verbosity 5, and the state changes to `authorizationStateWaitingCode`. However, the code doesn't arrive.

I tried using a VPN, a different Telegram account and a different API credentials, but none of that helped.

**Comment by AYMENJD** [comment]
On main DC you won't receive the code to your phone number. `authenticationCodeTypeSms` is only for official apps (eg. Telegram Android/IOS).

**Comment by flexagoon** [comment]
I know, I want to get the code to my Telegram account. That's how it works on Test DC.

**Comment by AYMENJD** [comment]
This is up to Telegram server.

**Comment by flexagoon** [comment]
@AYMENJD is there a way to check what the issue is? I don't get any errors, not even a "429 too many requests" or something

**Comment by AYMENJD** [comment]
Telegram won't send to you a login code with type `authenticationCodeTypeSms`. Telegram has made a recent change which restrict third-party apps from receive login code using `SMS` method due to high costs of sending `SMS` login codes.

You can login to your account using official Telegram apps which allows `SMS` login codes and then you can re-attempt to get the login code to your Telegram account.

**Comment by flexagoon** [comment]
@AYMENJD I am not trying to send an SMS code. I want to recieve a login code in the Telegram app where I'm already logged in.

This works for other third party clients. For example, I can open [this client](https://evgeny-nadymov.github.io/telegram-react/), which is unofficial, and enter my number. I get a login code in my Telegram app.

Then I open my TDLib app and type my phone number. The state changes, but I don't get a code.

I don't want to get an `authenticationCodeTypeSms` code. I want to get an `authenticationCodeTypeTelegramMessage`. I assume it is the default, because when I use the test DC that's the type of code that gets sent.

**Comment by AYMENJD** [comment]
As i told you, it's up to Telegram server to choose what code type you should receive.

You could try login to official Telegram Android/IOS client and re-attempt to login on the third-party app it may send you the code with `authenticationCodeTypeTelegramMessage`.

**Comment by levlam** [comment]
@flexagoon Probably, you asked too many times for the login code already. The server can ignore your requests for some time without returning error 429.
