### ISSUE TITLE
How works getChatHistory

### ISSUE THREAD

**Issue by CrazyminerMC** [tdlib/td#236]
How works the method getChatHistory ? 
How can I use the offset function if I have` limit = 50, onlyLocal = false and fromMessageId = chat.lastMessage.Id`
I want to get messages from the newest to the oldest using the offset to avoid duplicate messages

**Comment by levlam** [comment]
You need to specify offset = -51. TDLib currently requires offset + limit > 0 for getChatHistory, so you will usually receive 1 duplicate message.

**Comment by CrazyminerMC** [comment]
-51 + 50 does not> 0 anyway, I can not understand why if I make a request with offset = 0 limit = 50 it works, if I do offset = -50 limit = 100 it works but if I do offset = -100 limit = 150 it does not work

![immagine](https://user-images.githubusercontent.com/25179403/40026656-7f242646-57d6-11e8-9fbe-c8b4ac4bf203.png)

![immagine](https://user-images.githubusercontent.com/25179403/40026705-ba09d63e-57d6-11e8-83b0-2b8526c13ae1.png)

![immagine](https://user-images.githubusercontent.com/25179403/40026623-520082e0-57d6-11e8-825f-b6742e01d7bd.png)

**Comment by levlam** [comment]
Sorry, I've meant offset = -49.

Request with offset = -100 and limit = 150 doesn't work, because limit must be positive and can't be greater than 100.

**Comment by CrazyminerMC** [comment]
so how can I get older messages?

**Comment by levlam** [comment]
You need to adjust from_message_id accordingly on every request.

**Comment by CrazyminerMC** [comment]
Ahhh, ok.
Now how can I see how many messages there are in total in the channel?

**Comment by levlam** [comment]
This number isn't available currently in TDLib.
