### ISSUE TITLE
searchPublicChat sometimes has not callback, why?

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2366]
HANDLE hEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
	td_api::object_ptr<td_api::chat> chat;
	send_query(td_api::make_object<td_api::searchPublicChat>(query),
		[this, &chat, hEvent](Object object) {
		if (object->get_id() == td_api::error::ID) {
			SendErrorMsg(object);
			SetEvent(hEvent);
			return;
		}
		chat = td::move_tl_object_as<td_api::chat>(object);
		SetEvent(hEvent);
	});
	WaitForSingleObject(hEvent_, INFINITE);
	CloseHandle(hEvent);
        return chat;
-------------------------------------------------------------------------------------------
If there is no callback, my process is not return
I don't know why

**Comment by liaoxingquan** [comment]
SendErrorMsg this is my function, I interrupted a bit, process has not going there, but my process is MFC project, how  to check TDLib logs

**Comment by liaoxingquan** [comment]
I don't know which function is output logs

**Comment by levlam** [comment]
You can use `setLogStream` method to set up logging.

**Comment by liaoxingquan** [comment]
ok , I try it

**Comment by liaoxingquan** [comment]
searchPublicChat also has no callback, have no loging info
