### ISSUE TITLE
the problem of working with the tdlib telegram library: requests do not work, and it does not issue errors, it constantly sends some kind of @type":"updateOption" with different parameters in response. Can you tell me how this library should work in general?

### ISSUE THREAD

**Issue by andrey882006** [tdlib/td#2367]
Hello. Please tell me who has already worked with the tdlib library? Because I have such a problem: after authorization (at the end writes {"@type":"ok"}), I'm trying to send a request like: {"@type":"SendMessage","chat_id":"-1001628740950","input_message_content":{"@type":"inputMessageText","text":{"@type":"FormattedText","text":"Hello!"}}}
However , when listening to the response I get {"@type":"updateOption","name":"message_text_length_max","value":{"@type":"optionValueInteger","value":"4096"}}

If I listen to the answer again, I get for example:
{"@type":"updateOption","name":"suggested_video_note_video_bitrate","value":{"@type":"optionValueInteger","value":"1000"}}

And so on.. That is, the request does not work, but it does not issue any error, it constantly sends some kind of @type":"updateOption" with different parameters.

Please tell me who knows what's wrong? And how should this library work in general?)

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started, which expains, how to correctly match requests and responses.

**Comment by levlam** [comment]
```The main TDLib API is fully-asyncronous. An Application can send a request to TDLib through ClientManager.send method and receive a response asynchronously through the ClientManager.receive method when it becomes available. The exact naming of these methods and the way in which requests are matched with responses is different for different TDLib interfaces, but the concept as a whole remains the same. For example, in TDLib [JSON](https://core.telegram.org/tdlib/docs/td__json__client_8h.html) interface these methods are called td_send and td_receive, and their @extra field must be used to match requests with the corresponding responses.```

**Comment by levlam** [comment]
You must specify "@extra" parameter in each request, which you will receive back and can use to match requests and their responses.

**Comment by andrey882006** [comment]
> Вы должны указать "@extra" в каждом запросе, который вырабатывает и может использовать для замены их ответов.

That's exactly what I do. Have you personally worked with this library already?

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/docs/td__json__client_8h.html for complete description of the JSON interface.
