### ISSUE TITLE
dyld: Library not loaded: @rpath/libtdjson.dylib

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#237]
When I use tdlib in iOS, I can't compile it.Report the following error:
` 'cstdint' file not found and 
dyld: Library not loaded: @rpath/libtdjson.dylib
  Referenced from: /Users/yu.liao/Library/Developer/CoreSimulator/Devices/0677F95C-CE2B-47D5-A5C5-4CE4B59B98BA/data/Containers/Bundle/Application/702EEDD4-5AB1-4953-A880-C5D3D2EEEBA1/bicai.app/bicai
  Reason: image not found`

**Comment by remybourgoin** [comment]
You actually need to also embed the library in your package:

<img width="717" alt="capture d ecran 2018-05-14 a 20 34 49" src="https://user-images.githubusercontent.com/349614/40035395-67f67548-57b6-11e8-8f4d-013c45db25d5.png">

**Comment by liaoyu1992** [comment]
thanks
