### ISSUE TITLE
Save message or forward message to myself

### ISSUE THREAD

**Issue by guediagael** [tdlib/td#2375]
The API show how to send a message, but I don't see a place where user can send a message to himself using tdlib.

**Comment by levlam** [comment]
You need to call `getMe` to load the current user, then call `createPrivateChat` to create chat with self and then use received chat as usual.

**Comment by Mashi-91** [comment]
> How to send a message to the "Saved Messages" chat? `chat_id` that is equal to 0 and current user id is not sutable.

Your Saved Message Id is UserId.
😎
