### ISSUE TITLE
The notification is not displayed

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2379]
I have read what is written here (https://core.telegram.org/tdlib/notification-api/#handling-push-notifications) and am doing the following
I am receiving a message via firebase cloud messaging. Then I do:
```
ProcessPushNotification(
  payload: json.encode({
    "google.sent_time": event.sentTime!.millisecondsSinceEpoch,
    "p": payload,
  }),
),
```
This method returns - ok, and then nothing happens. 
Will a notification appear next? Or something else needs to be done to make it appear?

**Comment by levlam** [comment]
You will receive `updateNotificationGroup` if a notification should be shown for the push notification, it isn't shown yet and options "notification_group_count_max" and "notification_group_size_max" are set to a positive value. You can check TDLib log to see, how the push notification was processed.

**Comment by rr8733380** [comment]
I looked at the logs, and this is what I found:
```
Don't need message push notification for server message *****/* from chat ******** sent by user 
*************/chat 0 at ********: [Error : 0 : Ignore notification about known message]
```

I don't understand why the notification should not be shown. For what reason? Chat from which the message was sent, it does not have the notifications disabled.

**Comment by levlam** [comment]
This is the "it isn't shown yet" case. The notification for the message has already been shown, because the message was received directly from Telegram servers. `updateNotificationGroup` has already been sent for the message.

**Comment by levlam** [comment]
The notification for the message has already been shown. Probably, the message is even read already. Most notifications about new messages are received as `notificationTypeNewMessage` from Telegram servers and not as `notificationTypeNewPushMessage` from a push notification service.

**Comment by rr8733380** [comment]
I still haven't been able to fix it. the notification still doesn't show up.

Now I am only authorized on my android device in my app. But the notification is still not showing.  What am I doing wrong?

**Comment by levlam** [comment]
The app needs to show the notification itself whenever it receives `updateNotificationGroup`. TDLib doesn't interact with UI, provided by OS.

**Comment by rr8733380** [comment]
it turns out that I have to decrypt the payload that comes through firebase myself? Is there a code example of how this can be done (preferably on dart)?

**Comment by levlam** [comment]
No, you will not be able to decrypt it yourself. You need to process it as descrbed in https://core.telegram.org/tdlib/notification-api/#handling-push-notifications and show new notifications only if `updateNotificationGroup` is received. You can find an example of the whole workflow in the source code of Telegram X app: https://github.com/TGX-Android/Telegram-X.

**Comment by rr8733380** [comment]
I can't implement the notification display.

Let me try to explain what I'm doing. My android app is open, not running in the background
By steps:
1) I get a notification about a new message via `FirebaseMessaging.onMessage`
2) I take the `tdlib` that was created at the start of the application (Should I create a new `tdlib` when I receive a notification?)
3) I make `ProcessPushNotification` (it returns ok):

    ```
    ProcessPushNotification(
      payload: json.encode({
        "google.sent_time": event.sentTime!.millisecondsSinceEpoch.toString(),
        "p": p,
      }),
    ),
    ```
4) I expect that the `UpdateNotificationGroup` will come in the update, but it never comes

What am I doing wrong?

**Comment by levlam** [comment]
> I expect that the UpdateNotificationGroup will come in the update, but it never comes

If you didn't receive `UpdateNotificationGroup` previously, then the push notification contained nothing to be notified about, for example, the message has already been read, already notified with `notificationTypeNewMessage`, deleted, or an option "notification_group_count_max"/"notification_group_size_max" wasn't set. You can check TDLib log for details.

**Comment by rr8733380** [comment]
> an option "notification_group_count_max"/"notification_group_size_max" wasn't set

that helped, it finally worked out. thank you very much for your help
