### ISSUE TITLE
I can't log in to my account

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2382]
I can't log in to my account all day.
I do not receive a confirmation code when I log in to my account. The current state is `AuthorizationStateWaitCode`. I tried to log in from three different accounts, and the code didn't come to any of them. I tried to log in through the official telegram, the code came immediately. What's the matter?

**Comment by levlam** [comment]
It is up to the server, whether and how to send the code. For non-mobile or non-official apps it is usually sent as a Telegram message to another already logged in device.

**Comment by rr8733380** [comment]
And why does the confirmation code not come when I try to log in to my account through my application that I create? Usually the code came in the official telegram application. At the same time, the application is registered to the account through which I am trying to log in.
How can I solve this problem?

**Comment by levlam** [comment]
Probably, you asked for the code too many times. In this case you can only wait or test in Test DC.

**Comment by rr8733380** [comment]
No. That's not so. I haven't logged into this account for a couple of days. And I haven't logged into the other two accounts for a very long time. This is clearly some kind of mistake

**Comment by levlam** [comment]
It is still up to the server. Nothing can be done app-side.
