### ISSUE TITLE
building the tdlib project in java

### ISSUE THREAD

**Issue by paraleped** [tdlib/td#2384]
hello when i try to build a java project i get the following error:

when i try to build a java project i get the following error:

`MSBuild version 17.5.1+f6fdcf537 for .NET Framework

```
Generating Java TDLib API source files
  Building Java code
  C:\Users\T\Desktop\t\td\example\java\org\drinkless\tdlib\Client.java:229: warning: [removal] finalize() in Obje
  ct has been deprecated and marked for removal
      protected void finalize() throws Throwable {
                     ^
  1 warning
  Generating Javadoc documentation
  Loading source files for package org.drinkless.tdlib...
```

```
CUSTOMBUILD : error : No source files for package org.drinkless.tdlib [C:\Users\T\Desktop\t\td\example\java\build
\generate_javadoc.vcxproj] D:\N\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: custom assembly for "C:\Users\T\Desktop\t\td\example\java\build\CMakeFiles\38a1aee34003018bfa3f2a5c470b9fa0\generate_javadoc.rul
e;C:\Users\T\Desktop\t\td\example\java\CMakeLists.txt" exited with code 2.
 [C:\Users\T\Desktop\t\td
\example\java\build\generate_javadoc.vcxproj]`
```

this happens after trying to enter:

`etc\td\example\java\build> cmake --build . --target install`

*I have windows x64

**Comment by levlam** [comment]
```
  C:\Users\T\Desktop\t\td\example\java\org\drinkless\tdlib\Client.java:229: warning: [removal] finalize() in Obje
  ct has been deprecated and marked for removal
      protected void finalize() throws Throwable {
                     ^
  1 warning
```
This is a warning and not an error. Also, `finalize` usage is absolutely correct in the class and it is sad that Java forces us to remove it, because someone used it incorrectly.

Did you follow https://tdlib.github.io/td/build.html?language=Java?

**Comment by paraleped** [comment]
> CUSTOMBUILD : error : No source files for package org.drinkless.tdlib [C:\Users\T\Desktop\t\td\example\java\build
> \generate_javadoc.vcxproj] D:\N\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: custom assembly for "C:\Users\T\Desktop\t\td\example\java\build\CMakeFiles\38a1aee34003018bfa3f2a5c470b9fa0\generate_javadoc.rul
> e;C:\Users\T\Desktop\t\td\example\java\CMakeLists.txt" exited with code 2.
>  [C:\Users\T\Desktop\t\td
> \example\java\build\generate_javadoc.vcxproj]`

that's the problem, not the finalizer

CUSTOMBUILD : error : No source files for package org.drinkless.tdlib [C:\Users\T\Desktop\t\td\example\java\build
\generate_javadoc.vcxproj] D:\N\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: custom assembly for "C:\Users\T\Desktop\t\td\example\java\build\CMakeFiles\38a1aee34003018bfa3f2a5c470b9fa0\generate_javadoc.rul
e;C:\Users\T\Desktop\t\td\example\java\CMakeLists.txt" exited with code 2.
 [C:\Users\T\Desktop\t\td
\example\java\build\generate_javadoc.vcxproj]`

**Comment by levlam** [comment]
This is not the problem. It is consequences of failures on previous steps, or the files at `C:\Users\T\Desktop\t\td
\example\java\org\drinkless\tdlib` were deleted somehow. The full log for all commands from https://tdlib.github.io/td/build.html?language=Java should contain the cause.
