### ISSUE TITLE
TDLib fatal error

### ISSUE THREAD

**Issue by goodboy-XXX** [tdlib/td#2386]
TDLib fatal error: [SqliteDb.cpp:79][#1][!Td]	Database was deleted during execution and can't be recreated: [WindowsError : 系统找不到指定的文件。 :"db.sqlite" can't be opened for reading for stat]

**Comment by levlam** [comment]
Someone deleted the `db.sqlite` file, required by TDLib. You should be able to start TDLib without issues after that, but some data is lost.

**Comment by goodboy-XXX** [comment]
Yeah,i got it,thanks！
