### ISSUE TITLE
Interfaces for updates data from TDLib for a TypeScript project.

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2387]
Greetings.
I've searched enough, but have not found any `ts` interfaces/types for **type-checking** & autocomplete **of updates** while using `tdweb` -- a js-wrapper for TDLib.
Maybe there are some that I overlooked somehow?
If there aren't any, could you give me some suggestions (I am a junior) how I could generate interfaces for updates received from TDLib? It is very time consuming to write interfaces for all incoming JSON objects by hand.
Thank you in advance!

**Comment by Mammad900** [comment]
Check out [DIBgram/tdweb-ts-types](https://github.com/DIBgram:tdweb-ts-types). It contains auto-generated TypeScript types for TDWeb.
(also check out [DIBgram/tdweb](https://github.com/DIBgram/tdweb) which is pre-built up to date TDWeb).

**Comment by teleothleo** [comment]
> Check out [DIBgram/tdweb-ts-types](https://github.com/DIBgram/tdweb-ts-types). It contains auto-generated TypeScript types for TDWeb. (also check out [DIBgram/tdweb](https://github.com/DIBgram/tdweb) which is pre-built up to date TDWeb).

Looks not bad! Thank you!
