### ISSUE TITLE
Discrepancy behaviour while deleting messages on different clients?

### ISSUE THREAD

**Issue by busslina** [tdlib/td#2388]
Hello, I'm developing Menus based on Telegram Inline Keyboard feature. I'm updating those Menus based on events (like GPS position updates). Also I'm stopping updating those menus when destroyed (by user) when user press Close or Back button option, then Menu message is deleted from Telegram.

The problem comes when this Menu message is deleted manually by the user in the Telegram app. In the next update attempt I'm catching Telegram error that indicates that message no longer exists. Then I destroy that Menu in order to stop any later update attempt.

Then I realised that every Telegram client works in a different way when removing messages:

A) On Windows. (1) Removing selected message/s works fine. Then, when update attempt, a 400 http status code is returned indicating that message no longer exists. (2) Clearing history is not working as expected, because updating attempts are not failing indicating that the message no longer exists.

B) On Android. It works exactly opposite that A) (Windows). When deleting selected messages is not working as expected but when clearing history it is working as expected.

This may be a bug. The thing is that the correct behaviour must be to remove message on the back-end in all cases.

UPDATE: The scenario is a chat between a Bot and an User

**Comment by levlam** [comment]
In private chats messages can be deleted for both users, or only for self. In the latter case there is no way to know that peer deleted the message for self and bot still can edit its copy of the message. There is no way to prevent deletion of messages only for self.

**Comment by busslina** [comment]
> In private chats messages can be deleted for both users, or only for self. In the latter case there is no way to know that peer deleted the message for self and bot still can edit its copy of the message. There is no way to prevent deletion of messages only for self.

In this case it is a chat which involve a Bot and a User.

The main thing I am informing is the different behaviour in procedure of two Telegram clients (Windows and Android). The logic says that its behaviour should be the same.

**Comment by levlam** [comment]
Some apps hide some options for message deletion, but you can't count on it. Still both ways to delete messages are possible in all private chats, including chats with bots. The bot must have explicit way to continue/stop data updating instead of relying on an error from API.

**Comment by busslina** [comment]
My "explicit" way to do this is to catch HTTP 400 errors and parse error description. Then, if message can't be found it means message was deleted and I stop updates on that message. But, if after removing manually that message, the following updates on that message are returning success status code, then I cannot do anything.

**Comment by levlam** [comment]
This is not an "explicit" way. The message is removed as only for the user, but not for the bot and this is intended behavior for the apps. The same can be done in any private chat and is default behavior in the main official apps.

**Comment by busslina** [comment]
No intention to be disrespectful. Do you understand that the main thing is the different behaviour between Windows and Android clients? It is not the different behaviour based on different types of chats (private, bot, group, channel, ...) or the different privileges that we can grant to our bots.

IT IS an scenario in which two different Telegram Clients are behaving differently on the same scenario:
- Same chat
- Same bot
- Same bot privileges

With exactly all the same conditions the behaviour should be the same.
This is the MAIN thing.

After that, there are more things but we can start with the MAIN thing. The obvious thing.

**Comment by levlam** [comment]
Telegram has an open API, which allows both possibilities in any private chat, including chats with bots:
1. To delete a message only for self.
2. To delete a message for the peer also.

Until both possibilities are allowed, there will be apps, which allow to use them. And different apps can have different supported features due to their internal reasons. Users can't be oblidged to delete the message also for their peer when they delete it for self, and they also can delete the message for both.
