### ISSUE TITLE
Keep getting authorizationStateWaitTdlibParameters with golang

### ISSUE THREAD

**Issue by Thankgod20** [tdlib/td#2389]
Running the golang version `github.com/Arman92/go-tdlibf` of this API i cannot authenticate my account. It keep giving error of `authorizationStateWaitTdlibParameters` when all parameters are entered correctly.

**Comment by levlam** [comment]
The library tried to hide authentication details, but doesn't support authentication API in the latest TDLib version yet. You need to edit the libraries code or use another library.

**Comment by Thankgod20** [comment]
Suggestion for any other library? or work arround

**Comment by levlam** [comment]
https://github.com/aliforever/go-tdlib should work with the latest TDLib version, but the library also tries to hide authorization flow from library users, which is a bad idea.
