### ISSUE TITLE
what the TdApi.CheckAuthenticationPassword mean?

### ISSUE THREAD

**Issue by linhere20** [tdlib/td#239]
i have downloaded and run java example project. when I typed the phone number and the verification code, the below code is executed.
`case TdApi.AuthorizationStateWaitPassword.CONSTRUCTOR: {
                String password = promptString("Please enter password: ");
                client.send(new TdApi.CheckAuthenticationPassword(password), new AuthorizationRequestHandler());
                break;
            }`

but I enter any password, the error returned.
`Error {
  code = 400
  message = "PASSWORD_HASH_INVALID"
}
`

**Comment by levlam** [comment]
The error means that a wrong password was entered.

**Comment by linhere20** [comment]
ok. it's my fault
