### ISSUE TITLE
How to send messages to a chat enabling topical structure?

### ISSUE THREAD

**Issue by AndrewTran2018** [tdlib/td#2394]
Receiving messages is okay. However, sending  messages to a topic enabling chat fails. Please help.
@levlam

**Comment by AYMENJD** [comment]
In topcis, each received message has `message_thread_id` you need to pass it to `sendMessage`.

**Comment by AndrewTran2018** [comment]
> In topcis, each received message has `message_thread_id` you need to pass it to `sendMessage`.

At first time, where I can find message_thread_id? In a received message?

**Comment by AYMENJD** [comment]
You can do `message.message_thread_id`.
