### ISSUE TITLE
sendMessage to a private chat returns TdError with code 400, 'Chat not found'.

### ISSUE THREAD

**Issue by AndrewTran2018** [tdlib/td#2398]
I'm using tdlib 1.8.11. Please help
@levlam @sebix

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/578. This particular issue is about user identifiers, but everything written there can be also applied to chat identifiers. You can't use a chat identifier, unless you received it from TDLib after instance restart.

**Comment by AndrewTran2018** [comment]
> See #578. This particular issue is about user identifiers, but everything written there can be also applied to chat identifiers. You can't use a chat identifier, unless you received it from TDLib after instance restart.

This seems to be solved by calling GetChats at the first time login @levlam

**Comment by AndrewTran2018** [comment]
@levlam I solve it by calling CreatePrivateChat(chatId) before sendMessage
