### ISSUE TITLE
getAllChats

### ISSUE THREAD

**Issue by MeanSquaredError** [tdlib/td#2402]
telegram_api.tl lists the following API method
```
messages.getAllChats#875f74be except_ids:Vector<long> = messages.Chats;
```
However it seems that TDLib does not make this call available to the library user.

1. What is the rationale behind not providing access to this API call?
2. Is there any other API call that can give me a list of the channel IDs which the current Telegram user is a member of?

**Comment by levlam** [comment]
1. This method is legacy and never needed by apps.
2. You can't get the list of joined channels without loading whole chat list.
