### ISSUE TITLE
loadChats is causing freezes on larger accounts

### ISSUE THREAD

**Issue by bubblecsh** [tdlib/td#2409]
Each call to loadChats is freezing incoming updates from tdlib for up to 10-20 minutes. Also inputs to tdlib like sendMessage are processed with the same delay.
This account has 8k chats and it took 11h to load them while there are no issues on smaller accounts.
Could you please suggest how to deal with chats loading on these larger accounts?

**Comment by levlam** [comment]
TDLib can't freeze for so long. Are you sure that you don't block the thread, processing request responses and responses, until the chat list is fully loaded?
Then could you send TDLib's log with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by bubblecsh** [comment]
This was not a TDLib issue indeed, apologies.
