### ISSUE TITLE
getChatMember incorrect status

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#241]
I’ve got `getChatMember` returning status `chatMemberStatusLeft` for restricted user

Here is the chat id and user id with such behaviour, this user never leaved the chat, but got restricted to post images/stickers by admin

```
getChatMember chat_id=-1001089508239 user_id=82439953
```

Am I doing something wrong ?

**Comment by levlam** [comment]
It is a server bug. Non-admin chat members can't see restrictions of other users, so that user should be returned as chatMemberStatusMember instead of chatMemberStatusLeft.

**Comment by levlam** [comment]
Could you check that the bug is fixed?

**Comment by zevlg** [comment]
o yes! It is correct right now, thanks
