### ISSUE TITLE
I want to reply to someone in the group，But I don't know how to set the parameters about the api：sendMessage

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2410]

**Comment by liaoxingquan** [comment]
Or is it another interface function？

**Comment by liaoxingquan** [comment]
sendMessage::reply_to_message_id_ is message::id_?

**Comment by liaoxingquan** [comment]
&nbsp;which identifier

---Original---
From: "Aliaksei ***@***.***&gt;
Date: Fri, Apr 21, 2023 21:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tdlib/td] I want to reply to someone in the group，But I don't know how to set the parameters about the api：sendMessage (Issue #2410)




 
Pass identifier of the message, which should be replied.

**Comment by liaoxingquan** [comment]
has some Demo? thanks



---Original---
From: "Aliaksei ***@***.***&gt;
Date: Fri, Apr 21, 2023 21:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tdlib/td] I want to reply to someone in the group，But I don't know how to set the parameters about the api：sendMessage (Issue #2410)




 
Pass identifier of the message, which should be replied.

**Comment by liaoxingquan** [comment]
@levlam Has anyone replied? Please wait, thank you， I want to reply to someone in the group，I has set the sendMessage::reply_to_message_id_ ,But it doesn't seem to work，How should I set it up?

**Comment by levlam** [comment]
Check that you specified a correct message identifier of a message in the same chat, which was received programmatically from TDLib.

**Comment by liaoxingquan** [comment]
class sendMessage final : public Function {
.....
  using ReturnType = object_ptr<message>;
......
}

returned  object_ptr<message>    =>
class message final : public Object {
 public:
  /// Message identifier; unique for the chat to which the message belongs.
  int53 id_;
}

 I am using this id_

**Comment by levlam** [comment]
This is a message identifier and it can be used as identifier of replied message. You must use an identifier, which was received programmatically from the same TDLib instance. You must not use a hardcoded message identifier.
