### ISSUE TITLE
I want to reply to someone in the group

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2412]
I has sett the sendMessage::reply_to_message_id_ ,But it doesn't seem to work，How should I set it up?

**Comment by liaoxingquan** [comment]
Has anyone replied? Please wait, thank you

**Comment by levlam** [comment]
Ensure that you pass Check that you specified a correct message identifier of a message in the same chat, which was received programmatically from the same TDLib instance.

**Comment by Eriter555** [comment]
> Check that you specified a correct message identifier of a message in the same chat, which was received programmatically from the same TDLib instance.

Thank you! Got it. Looks like the problem was in the version of the compiled tdlib library.
