### ISSUE TITLE
What does SetdatabaseenCryptionKey require the system? I tested the prompt Unauthorized Code: 401 under Debian 10.9 and PHP7.4.33, how to solve it?

### ISSUE THREAD

**Issue by quyunet** [tdlib/td#2416]
What does SetdatabaseenCryptionKey require the system? I tested the pr ompt Unauthorized Code: 401 under Debian 10.9 and PHP7.4.33, how to solve it? 

It can work normally in CentOS 7.9 and PHP 7.4.

**Comment by levlam** [comment]
The method can be used only when authorization state is `authorizationStateReady`.
