### ISSUE TITLE
Java process is getting killed after system dependencies update

### ISSUE THREAD

**Issue by grittygear4937** [tdlib/td#2417]
I have been working with TDLib on Macos for more then a three monthes and today I started experiencing weird issue. I would appriciate any assistance as I am stucked.

After todays run `homebrew update/upgrade` the java process that uses tdlib is getting killed just right after it is getting started.
Even Example.java class from td lib experiences the same issue
There are not any java logs that could help

That is how it looks in console
```
$ java '-Djava.library.path=.' org/drinkless/tdlib/example/Example
[12309] killed     java '-Djava.library.path=.' org/drinkless/tdlib/example/Example
```
Could you please advise what can I do to understand what are the reasons for that?

 Thank you in advance!

**Comment by levlam** [comment]
You can open Console.app to see crash reports and find the cause.
