### ISSUE TITLE
Where can I found a precompiled libtdjson.so?

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlib/td#2418]
I want to use TDLib JSON interface from PHP FFI, but i requires `libtdjson.so` to run.
As I understand, [it is not an option](https://github.com/tdlib/td/issues/2188) to compile TDLib on a 1 GB server.
Where can I download a precompiled `libtdjson.so`?

**Comment by levlam** [comment]
We don't provide pre-built binaries. Moreover, binaries aren't portable by definition and usually can be used only with specific OS version.

Also, you definitely can build TDLib on a 1 GB server. Just use https://tdlib.github.io/td/build.html, choose clang as compiler and check an option for reduced RAM requirements during building.
