### ISSUE TITLE
How to get all chat member updates with tdlib client?

### ISSUE THREAD

**Issue by aleksandrchechenev** [tdlib/td#2422]
We have a telegram bot with the following configuration: 
`private fun formBotOptions() = DefaultBotOptions().also { it.allowedUpdates = listOf("chat_member") }`
Right now we are using tdlib client (not bot) to get updates but it can detect new member only if "new member message" appears in the supergroup
![photo_2023-04-28_13-55-55](https://user-images.githubusercontent.com/97525602/235130357-5aeddec1-099a-4ebf-b8a5-7ce65af2d5f1.jpg)
![photo_2023-04-28_13-56-08](https://user-images.githubusercontent.com/97525602/235130362-1d9451a5-5a99-466a-824f-4cb7a119c4ff.jpg)
Otherwise, we can not detect new member has joined the supergroup. How can we specify a list of allowed updates for tdlib client to be sure to receive all types of updates?

**Comment by levlam** [comment]
You always receive all relevant updates through TDLib.

Users doesn't receive `updateChatMember` updates, they are received only for bots.

**Comment by aleksandrchechenev** [comment]
I don't know why, but I don't always get updates that a new user has been added to the supergroup. What should I do to get updates every time a user enters the supergroup?

**Comment by aleksandrchechenev** [comment]
Thanks for your answer!
