### ISSUE TITLE
updateChatLastMessage

### ISSUE THREAD

**Issue by JnZn558** [tdlib/td#2424]
Hello td guru,

tdlib json 1.8.14

the updateChatLastMessage notify with same chat id and message id can occur multiple times? Why is that the case?
for example chat id -1001095525244 and message id 26473398272 notify four times, another message id  occurs more than 10 times.
but in Original windows telegram I see just one message. These message differs only on view_count and (positions compare to the first one). Everytime when view_count is changed, would be a new updateChatLastMessage generated?

**Comment by levlam** [comment]
`updateChatLastMessage` is sent when the last message in the chat changes. The last message must be used only to show it in the chat list. See https://core.telegram.org/tdlib/getting-started#handling-updates for brief description of the most common updates.
