### ISSUE TITLE
C# example uses volatile?

### ISSUE THREAD

**Issue by wrharper-AASP** [tdlib/td#2425]
Is this required? This can actually reduce performance. Is this somehow being handled by the C++ library? I would like details on why this is being used.

**Comment by wrharper-AASP** [comment]
Is it possible to get this library to be upgraded for .net 6 compatibility as well?

**Comment by levlam** [comment]
C# example uses volatile for variables, which can be accessed from multiple threads and are required to be volatile because of this.

You can use TDLib through С++/CLI, C++/CX or as a regular shared library, so you definitely can use it from .NET 6 in some way.

**Comment by wrharper-AASP** [comment]
Is there no standard cloud API without using a library? Just a standard auth header with JSON POST/GET? An entire library is actually a little overkill for my needs.

**Comment by levlam** [comment]
There is no.

**Comment by wrharper-AASP** [comment]
This may have to do with openssl being out of date in the build? I have changed the project settings to use 3 instead of 1_1 but it still errors out. 1.1 is very old, is it required? This applies to libcrypto as well.
<Content Include="build\$(Configuration)\libcrypto-1_1.dll">
<Content Include="build\$(Configuration)\libssl-1_1.dll">

**Comment by wrharper-AASP** [comment]
I think the issue has to do with the vcpkg.exe command being shown in the example. a lot of this appears to be out of date:
![image](https://user-images.githubusercontent.com/117128832/236194580-2545c3f2-f42e-4958-aa26-bd3e74827f35.png)

**Comment by wrharper-AASP** [comment]
i will make a separate post for this since it is technically a different subject.
