### ISSUE TITLE
The code does not come when trying to log in

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2428]
I sent my app to three of my friends yesterday to test it. Each of them logged in once yesterday. Today none of them, myself included, can log in again. It just doesn't come with a code to any of the users. 

I tried another phone number that I haven't tried to sign in with in over a month, and the code didn't come to it either. 

I can't figure out what the problem is. Why is there some kind of restriction? How to fix it. Users just don't get a code to confirm authorization!!!

**Comment by rr8733380** [comment]
I just tried to log in from my phone number through the official telegram website and the code came. Immediately tried in my application, the code does not come!

**Comment by Thom123450** [comment]
Tân thủ tnv thom202020
Sdt 0899161942 Lộc event

**Comment by levlam** [comment]
It is up to the server. There is no way for the app to affect the behavior.

**Comment by rr8733380** [comment]
So what should I do? My users can't log in to the app. No one can use my app because no one can log in to their profile.

**Comment by levlam** [comment]
Probably, they logged in and out too many times. Now you can only wait.

**Comment by rr8733380** [comment]
There are users who haven't logged in to my app yet. They try to log in for the first time, but they don't get the code

**Comment by Thom123450** [comment]
0706741835
