### ISSUE TITLE
Remove C++ Library Static return in ClientResultHandler

### ISSUE THREAD

**Issue by wrharper-AASP** [tdlib/td#2435]
How can I remove the static requirement coming back?
![image](https://github.com/tdlib/td/assets/117128832/1499db3e-18ce-40f7-8c72-dd71bfb53db7)

The C++ code would need to change? static requirements for everything is kind of bad.

I have already fixed the threading issues; this is the only thing that's left.

**Comment by levlam** [comment]
This is C# and not C++.

You can define arbitrary result handlers, which can access whatever they want. Moreover, even the example defines 3 different handlers.

**Comment by wrharper-AASP** [comment]
k
