### ISSUE TITLE
Problemas com telegram 

### ISSUE THREAD

**Issue by Nanda-1988** [tdlib/td#2440]
Há mais ou menos uma semana em determinados horários entre 22:50 e meio dia do dia seguinte entre meio-dia e meia e e 2:30 da tarde tava grande travado as minhas mensagens não são entregues e eu também não recebo eu não sei se esse é o lugar certo para reclamar mas já pintei todos os canais Twitter o próprio telegram e eu não obtive resposta

**Comment by levlam** [comment]
This sounds like a network issue or another temporary issue. It is unlikely that someone can help with it.
