### ISSUE TITLE
authenticationCodeTypeFirebaseAndroid - can be used for registration in tg or just for log in existing account already registered in telegram?

### ISSUE THREAD

**Issue by oksakhartman** [tdlib/td#2443]
```
//@description An authentication code is delivered via Firebase Authentication to the official Android application
//@nonce Nonce to pass to the SafetyNet Attestation API
//@length Length of the code
authenticationCodeTypeFirebaseAndroid nonce:bytes length:int32 = AuthenticationCodeType;
```

`authenticationCodeTypeFirebaseAndroid` 
`authenticationCodeTypeFirebaseIos`
can be used for registration in tg or just for log in existing account already registered in telegram?

**Comment by levlam** [comment]
Apps can't "use" them. They can be chosen by the server in the official mobile apps as the way to authenticate the user. The types are irrelevant for all other apps.

**Comment by oksakhartman** [comment]
> way to authenticate the user

for registration or only log in?

**Comment by levlam** [comment]
It is up to the server.
