### ISSUE TITLE
getChats return error

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2444]
getChats return error:  code:500, message_:Wrong query result returned: last message not found.
What should I do it

**Comment by liaoxingquan** [comment]
Okay, I'll give it a try

**Comment by liaoxingquan** [comment]
I have already sent it

**Comment by liaoxingquan** [comment]
but,next ,what can I do

**Comment by levlam** [comment]
Now you need to wait for a server-side fix of the issue.

**Comment by levlam** [comment]
The latest TDLib version can handle such incorrect server responses, so the issue should be mostly invisible for the user.
