### ISSUE TITLE
Demo account

### ISSUE THREAD

**Issue by rr8733380** [tdlib/td#2447]
I can't publish the app in the App Store. They ask to give them a test account. But I can't give them my account, because there you need to enter a code that comes to my number. 
Do you have any test account that I can give them in order for them to check?

**Comment by AYMENJD** [comment]
Telegram already has a test environment, see: https://core.telegram.org/api/auth#test-accounts.

**Comment by rr8733380** [comment]
I am trying to log in using the number - 79996611234 (7 is the country code). then I enter the code 11111, but it gives out that this is the wrong code. what is the problem?
