### ISSUE TITLE
No documentation for custom emojis

### ISSUE THREAD

**Issue by salut1618** [tdlib/td#2448]
### The Issue
There seems to be no documentation available for how to obtain AnimatedEmojis of custom emojis,
using the normal getAnimatedEmoji requries a text representation of the emoji, and custom_emojis are usually represented by id

### Things i tried
putting the id from "custom_emoji_id" field
putting the unicode of the emoji
tried to embed it in text with "`<embed id=*>emoji</embed>`"

they all resulted in error 404

nothing seemed to work.

### Lastly
I apologize if what i presented was incomplete info, or was previously discussed. its my first issue i open on github

**Comment by levlam** [comment]
You can find documentation for the latest TDLib version at https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl. You can search there for "CustomEmoji"/"custom_emoji" to find all relevant methods. Namely, the method `getCustomEmojiStickers` can be used to get the sticker, corresponding to the custom emoji. If a message consists of a single custom emoji, its content will be automatically changed to `messageAnimatedEmoji` by TDLib.

**Comment by salut1618** [comment]
Thanks for the response and time it took you to write it, it resolved it

Though may i ask how about obtaining the custom emoji packs? how would someone approach obtaining all custom emoji ids

**Comment by levlam** [comment]
Custom emoji packs are created by users. There are a lot of them.
