### ISSUE TITLE
TdLib - kotlin

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2449]
I know that kotlin can use JVM Client class to interface with TDLib, but there is the possibility in future to have an official way using kotlin classes only? I mean using flows, channels and coroutines to manage updates and requests without java handlers

**Comment by levlam** [comment]
Did you check https://github.com/tdlib/td/tree/master/example#using-tdlib-in-kotlin-projects?

**Comment by Fra078** [comment]
Yes, but both kid and td-ktx are very outdated and are using deprecated kotlin APIs

**Comment by levlam** [comment]
Then it should be possible to create your own wrapper based on [JSON](https://github.com/tdlib/td#using-from-other-programming-languages) interface with all aforementioned features.

**Comment by g000sha256** [comment]
@Fra078, you can try [TDL Coroutines](https://github.com/g000sha256/tdl-coroutines)
