### ISSUE TITLE
Message ids aren't unique

### ISSUE THREAD

**Issue by kossnocorp** [tdlib/td#245]
[The API docs states](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message.html) that message ids are unique:

![cloudapp annotation 2018-05-18 at 11 09 54 am png](https://user-images.githubusercontent.com/52201/40220969-0809580c-5a8c-11e8-884d-b353533572bd.png)

Although I just discovered that it's not true. Hence the question: how are they work? Are ids are unique to a chat or combination of a chat and a client? If I'd get the same message on a different client (an instance of TDLib) will message have the same id, or it will be completely different?

Here is an example of an incoming update:

![cloudapp annotation 2018-05-18 at 10 59 28 am png](https://user-images.githubusercontent.com/52201/40220892-bb7afae0-5a8b-11e8-867f-b255f631d2fd.png)

And here is a message stored in my DB:

![cloudapp annotation 2018-05-18 at 11 08 24 am png](https://user-images.githubusercontent.com/52201/40220916-d1f37220-5a8b-11e8-87e1-db0a5c29b8af.png)

This is really confusing. Thank you in advance!

**Comment by kossnocorp** [comment]
Ok. I've found another doc where it clearly states that the message id is unique to the parent chat.

![cloudapp annotation 2018-05-18 at 1 59 45 pm png](https://user-images.githubusercontent.com/52201/40228982-e3d1501c-5aa3-11e8-9723-70c7dd1766f3.png)

**Comment by levlam** [comment]
Yes, all message identifiers are defined inside a chat and they are unique only for that chat.

If you'd get the same server message on a different client for the same user, then message will have the same id. This is not true for local messages and for messages received by different users.

**Comment by kossnocorp** [comment]
@levlam thank you for the clarification!
