### ISSUE TITLE
How can I mark an entire chat as read

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2450]
I want to implement a button in my client which mark the chat as read but there are only methods to read all reactions and mentions but not messages.

**Comment by levlam** [comment]
Chats are read automatically when their messages are viewed using `viewMessages` method. The method also has `force_read` parameter, which can be used to implement the button.

**Comment by Fra078** [comment]
But how can I get all unread messages IDs? What IDs I should put as parameter
