### ISSUE TITLE
Is it a ToS violation, if third-party app features are similar in nature to Telegram Premium feature?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2455]
A user of my app posted a question on supporting default folder selection. The user would like the app to have a feature to select a default folder.

My understanding that this is a Telegram Premium feature.
While the [Terms of Service](https://core.telegram.org/api/terms) does not mention about Telegram Premium, I assume it would be a violation?

**Comment by vincentneo** [comment]
Thanks @levlam for the quick reply!

Will stick to the official ways of implementing by using the `main_chat_list_position` parameter, which will require the user to have Premium.

**Comment by rufatagayev** [comment]
İs there an APİ documentation or a guide for premium features that we should be aware of so we don't implement them without knowing?

**Comment by levlam** [comment]
See classes `PremiumFeature` and `PremiumLimitType` in the documentation.
