### ISSUE TITLE
Put isForum in ChatTypeSupergroup chat

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2457]
It would be useful to check if a chat is a forum directly without request to a cache with supergroup IDs to improve performance when loading lists

**Comment by levlam** [comment]
`is_forum` can be changed any time, so it isn't part of the chat's type. It can be added only with the `updateChatType` update, which sounds a bit strange.

While it is true that this looks like the only reason to fetch the supergroup object from cache while showing chat list, I don't think that the change will result in any reasonable performance improvements.

**Comment by Fredmattwg** [comment]
Hi
