### ISSUE TITLE
node-tlg and tdlib 1.8.14 compatibility issues

### ISSUE THREAD

**Issue by garam-park** [tdlib/td#2459]
env 
- node 18.7.0
- tdlib 1.8.14
- node-tlg : 1.1.4

![image](https://github.com/tdlib/td/assets/7725665/451e2b5e-0b84-4ae4-9977-cd9d1117d1d1)

my `apiId` and `apiHash` is valid but error come out.

note : if you want to test. check node version. latest version(18.14.0) does not work(It has issue - segmentation fault). I recommend 18.7.

**Comment by c0re100** [comment]
Cause you're using a very old version of tdlib wrapper (committed on Dec 24, 2018).

**Comment by levlam** [comment]
The `node-tlg` library expects TDLib to have a fixed API, so it would be really hard to use it with any TDLib version except the version existed 5 years ago. You need to use another wrapper, which allows to send arbitrary requests to TDLib and doesn't depends on any particular TDLib version.
