### ISSUE TITLE
Getting list of pinned chats for `chatListMain`

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2461]
How to get the list of pinned chats from the `chatListMain`? I mean the pinned chats in the first folder, the "all" folder. It is easy to get pinned chats when it comes to `chatListFilter` or from `updateChatPosition` (which is sent only after pinning a chat in real time), but I haven't found the way of getting all pinned chats for `chatListMain`. 
Thanks in advance

**Comment by levlam** [comment]
Pinned chats can be found among all chats in the chat list by the value of `chat.position.is_pinned` field. There is no dedicated method to get all pinned chats without other chats in a chat list.

**Comment by teleothleo** [comment]
Oh now I see, thank you!
