### ISSUE TITLE
Joining supergroup/private channel

### ISSUE THREAD

**Issue by DenisTTTT** [tdlib/td#2463]
Hello!
I have to get messages out of arbitrary telegram channels. UseMessageDatabase is set to false. Tried JoinChat and AddChatMembers providing chat id I know in advance. Both returned "chat is not found". Is there any correct way to do that with TdLib?
Also maybe any way to get chat messages for non-member does exist? 

Thanks,
Denis

**Comment by levlam** [comment]
It is not possible to get a chat by its identifier. You can only use chat identifiers that were received from TDLib.

**Comment by DenisTTTT** [comment]
Could you please advide how could I get one from TDLib? If I know channel name but not subscribed yet...

**Comment by levlam** [comment]
You can use `searchPublicChat` to get a chat by its username.

**Comment by DenisTTTT** [comment]
Thanks a lot, I will try that!
As for the second part of my question - is it possible to get messages out of the public chat without joining it?

**Comment by levlam** [comment]
If something is possible to do with a Telegram app, you can do the same with TDLib.
