### ISSUE TITLE
Validity of td.binlog

### ISSUE THREAD

**Issue by DenisTTTT** [tdlib/td#2464]
Hello.
I have to allow subscription on more than 1000 channels in my tdlib client. As far I understand I can't do it with one account even Premium. So I am going to have few account and swith between them. So I'm wondering - if I  create in advance td.binlog containing valid authorized session and distribute it on various devices - would it stay valid forever? Or would it need to be reactivated at some point later on? 
Thanks,
Denis

**Comment by levlam** [comment]
You must never copy td.binlog. This have no chance to work.
