### ISSUE TITLE
Passing click to button popup type of KeyboardButtonTypeText

### ISSUE THREAD

**Issue by wrharper-AASP** [tdlib/td#2465]
How would you send a click to something like:
TdApi.KeyboardButton testbtn = new KeyboardButton("BUTTON TEXT HERE", new TdApi.KeyboardButtonTypeText());

usually, you would inline to do text but for type KeyboardButtonTypeText there is no inline? This makes sense since you would not be inlining a keyboard. It would be a button you click in response instead.

InlineKeyboardButtonTypeText needs to exist?

**Comment by wrharper-AASP** [comment]
I just used the text of the button with InputMessageText instead and this appears to of worked.
I would like to know if this is possible somehow.
Need InputButtonClick(PICK BUTTON HERE) or something like that.

**Comment by levlam** [comment]
`keyboardButtonTypeText` just sends the text of the button as a message.

**Comment by wrharper-AASP** [comment]
> `keyboardButtonTypeText` just sends the text of the button as a message.

yes, it is the response. how do i respond with a click?

**Comment by levlam** [comment]
`keyboardButtonTypeText` just sends the text of the button as a message.

**Comment by wrharper-AASP** [comment]
Is it possible to click a button that is prompted?

**Comment by levlam** [comment]
There in no such action as "button click". Whenever a button is pressed a button-specific action is performed by the app and for buttons of the type `keyboardButtonTypeText` the action is sending of a text message with the text of the button.

**Comment by wrharper-AASP** [comment]
I understand that that keyboardButtonTypeText is just information about the button just ignore keyboardbuttontypetext to make this easier to understand. That really doesn't matter to the question at hand at this point.
Is there any way at all to click a button that has popped up?

**Comment by wrharper-AASP** [comment]
You can emulate/program clicking a button in any browser or any program. Is this an exception for some reason?

**Comment by levlam** [comment]
App don't "click the button", they perform an action associated with the button.

**Comment by wrharper-AASP** [comment]
I think we are talking about the same thing just using different terminology. How would you perform the action?

**Comment by levlam** [comment]
`keyboardButtonTypeText` just sends the text of the button as a message. i.e. the method `sendMessage` is called with content of the type `inputMessageText`.

**Comment by wrharper-AASP** [comment]
ok, that is actually how I did it. I thought there may be another way, thanks.
