### ISSUE TITLE
Unsubscribed from a channel where I am the only admin

### ISSUE THREAD

**Issue by RodionG** [tdlib/td#2466]
Can I get access to my private channel after unsubscribing? I don't have an invite link, but I have a channel id and a name.

**Comment by levlam** [comment]
You need at least a forwarded message from the private channel to be able to find it.

**Comment by RodionG** [comment]
Yes I have that one, but when I'm trying to follow the link I catch the message
```
Something went wrong
This channel is private
```

**Comment by levlam** [comment]
If you wasn't a creator of the private channel and left it, then you can't return back yourself.

**Comment by RodionG** [comment]
I know, but I'm a creator

**Comment by RodionG** [comment]
I tried to use the function "Export Telegram data" in the desktop app, but I don't see the channel in the list which I've left before.

**Comment by levlam** [comment]
Then you should be able to access it from anywhere, for example, from the forwarded message. Try a TDLib-based app, for example, Telegram X for Android or Unigram for Windows.

**Comment by levlam** [comment]
On the screenshot denitiely nor Unigram, nor Telegram X.

**Comment by RodionG** [comment]
Almost the same (buttons do not work):
![photo_2023-05-31_22-35-12](https://github.com/tdlib/td/assets/97115531/1524a919-fbb0-4c70-b54a-a0be9a37c162)
![photo_2023-05-31_22-35-15](https://github.com/tdlib/td/assets/97115531/bc6b6a2f-ac30-4e75-b117-069d0f57f6cf)

**Comment by RodionG** [comment]
From Telegram X, when I'm trying to join a channel I get the following popup message:
![photo_2023-05-31_23-41-21](https://github.com/tdlib/td/assets/97115531/8a2b83cc-53c5-4187-baf4-73eb19411582)

**Comment by levlam** [comment]
The screenshots shows that the channel was completely deleted, and not just left. There is no way to restore it.

**Comment by RodionG** [comment]
I will suggest that the problem is the same, but different clients display it differently

**Comment by RodionG** [comment]
> The screenshots shows that the channel was completely deleted, and not just left. There is no way to restore it.

Huge thanks for your supporting, have a nice day!
