### ISSUE TITLE
How to create new chat with phone number ?

### ISSUE THREAD

**Issue by kullhy** [tdlib/td#2467]
To send message need chatId, but i have never chat before, is there any way to get chat id. Or is there a way to create a new message?

**Comment by levlam** [comment]
Some users can be found with `searchUserByPhoneNumber` method, but usually you write to people found in some other way.

**Comment by xzwjz2** [comment]
I import contact and then create a new chat. See my project https://github.com/xzwjz2/tdlib-php to see more details.

**Comment by kullhy** [comment]
> I import contact and then create a new chat. See my project https://github.com/xzwjz2/tdlib-php to see more details.

Thanks, i solved the problem

**Comment by Is1111** [comment]
Excelente muchas gracias
