### ISSUE TITLE
MD5

### ISSUE THREAD

**Issue by Salampeace410** [tdlib/td#2469]
a620415696f54ed2ecd4a45914b87a27 is a MD5 hash that corresponds to official Telegram X build.

This build was published to Google Play Beta.

Version: 0.25.8.1629-x86
Commit: 4dfa8893, 28/05/2023, 11:42 UTC

**Comment by Salampeace410** [comment]
> a620415696f54ed2ecd4a45914b87a27 is a MD5 hash that corresponds to official Telegram X build.
> 
> This build was published to Google Play Beta.
> 
> Version: 0.25.8.1629-x86 Commit: 4dfa8893, 28/05/2023, 11:42 UTC



>

**Comment by Tecachehahaha** [comment]
duermete
