### ISSUE TITLE
Call getCallbackQueryAnswer and click on the inline keyboard

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2470]
I called getCallbackQueryAnswer with the parameter next corresponding data (callbackQueryPayloadData), but how do I get the new result

**Comment by liaoxingquan** [comment]
![1685890473070](https://github.com/tdlib/td/assets/66247739/797f2b7e-ff9e-4b42-8c0b-4ba6a5a6a29e)

like this , when i call getCallbackQueryAnswer about group button, and then, the message_id is Invalid， how can i get the new valid message_id

**Comment by liaoxingquan** [comment]
has someone see my question ? or understand my question ?  I am in a hurry !

**Comment by levlam** [comment]
`getCallbackQueryAnswer` returns `CallbackQueryAnswer`. If you receive the error `message_id is Invalid`, then you pass a completely wrong message identifier to the request, which definitely wasn't received from TDLib.
