### ISSUE TITLE
Sending error for request 1: error { code = 400 message = "Can't init database in the directory "tdlib": [PosixError : Permission denied : 13 : Can't create directory "tdlib"]" }

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#248]
When I use tdlib in ios, this error occurs:
`Sending error for request 1: error { code = 400 message = "Can't init database in the directory "tdlib": [PosixError : Permission denied : 13 : Can't create directory "tdlib"]" }`

**Comment by UnblockerUsername** [comment]
"On Apple devices it is very easy to set parental control settings and access restrictions."
Please check whether the application can write to the file at all.

This is not an official recommendation. For an official recommendation, you need to wait @levlam.

Thanks

**Comment by levlam** [comment]
You need to change parameter "database_directory" of setTdlibParameters request. It should point to a writable directory.

**Comment by liaoyu1992** [comment]
thank you

**Comment by wangwanfeng** [comment]
大哥我也遇到这个问题了，麻烦问下你是怎么解决的啊

**Comment by bugbaal** [comment]
I got this error too right now on ubuntu. The directory is writable, I tried different directory but always the same problem

**Comment by levlam** [comment]
@bugbaal The error means that the process can't access the directory and there can be no other reasons. You should check that there is enough rights to access all directories in the provided path.
