### ISSUE TITLE
need help to change the server destination of the library

### ISSUE THREAD

**Issue by arashammm** [tdlib/td#2482]
hello to all
I have a hard time finding where I can change the server address inside the code to which the packets are sending. I intend to use this library to connect to a different server which is using Mtproto and I need to use this library as client.
Can anyone guide me where can I alter server destiantion and ports to connect to the server?

**Comment by levlam** [comment]
It is not that simple. The server's  API must be fully compatible with the latest Telegram API, which is very unlikely.

**Comment by levlam** [comment]
First you must replace the certificate at https://github.com/tdlib/td/blob/e8ee1c51498c060c6f9b8511bf25a6c025e72adf/td/telegram/net/PublicRsaKeyShared.cpp#L20. Then you may change datacenter configuration at https://github.com/tdlib/td/blob/e8ee1c51498c060c6f9b8511bf25a6c025e72adf/td/telegram/net/ConnectionCreator.cpp#L1176.
