### ISSUE TITLE
getting all pinned messages from a chat

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2486]
Is there a simpler way of getting all pinned messages from a chat without calling `getChatHistory` and going through each message and checking whether "isPinned" is set to true? 
Thanks in advance

**Comment by levlam** [comment]
For this and similar queries `searchChatMessages` with appropriate filter is supposed to be used.

**Comment by teleothleo** [comment]
> For this and similar queries `searchChatMessages` with appropriate filter is supposed to be used.

Great, thank you!
