### ISSUE TITLE
How can I know download is completed when I use 'Synchronous=false'

### ISSUE THREAD

**Issue by daijia0201** [tdlib/td#2487]
I send a request ‘DownloadFile’ and set ‘Synchronous = true’，and it response a File immediately。but I don`t know when the file is completed。How do I know it

**Comment by vincentneo** [comment]
You can handle the [`updateFile`](https://github.com/tdlib/td/blob/1886bcf85020f140a59bfec5ff61c06710dbecd1/td/generate/scheme/td_api.tl#L5497) update for that.
