### ISSUE TITLE
How  to edit tdlib source to exclude group and channels?

### ISSUE THREAD

**Issue by lyna-kim** [tdlib/td#2498]

**Comment by levlam** [comment]
I don't think that this is possible. Groups and channels are everywhere.

**Comment by lyna-kim** [comment]
Ok @levlam, How to exclude group/channels load when we call loadChats/getChats ?

**Comment by lyna-kim** [comment]
I would like to load private chat only.

**Comment by levlam** [comment]
There is no way to do this. You need to skip them manually.

**Comment by lyna-kim** [comment]
Ok thank you @levlam
