### ISSUE TITLE
Android Support: AuthorizationStateWaitEmailAddress

### ISSUE THREAD

**Issue by Synaric** [tdlib/td#2503]
Hi, I found that the official document states that AuthorizationStateWaitEmailAddress is supported, but the Android Prebuilt downloaded from [here](https://core.telegram.org/tdlib/tdlib.zip) does not support it. Is email login not supported on the Android side? Thanks.

**Comment by levlam** [comment]
To have the latest Telegram features supported you need to build the latest TDLib yourself using build instructions from https://github.com/tdlib/td/tree/master/example/android.
