### ISSUE TITLE
tg_cli compiled but not installed

### ISSUE THREAD

**Issue by asarubbo** [tdlib/td#2504]
Hello,

on version 1.8.14 I get `tg_cli` compiled but not installed by the `ninja install` process.

Here is the list of the installed files here:

```
/usr/include/td/telegram/Client.h
/usr/include/td/telegram/Log.h
/usr/include/td/telegram/td_api.h
/usr/include/td/telegram/td_api.hpp
/usr/include/td/telegram/td_json_client.h
/usr/include/td/telegram/tdjson_export.h
/usr/include/td/telegram/td_log.h
/usr/include/td/tl/TlObject.h
/usr/lib64/cmake/Td/TdConfig.cmake
/usr/lib64/cmake/Td/TdConfigVersion.cmake
/usr/lib64/cmake/Td/TdTargets.cmake
/usr/lib64/cmake/Td/TdTargets-release.cmake
/usr/lib64/libtdactor.a
/usr/lib64/libtdapi.so
/usr/lib64/libtdapi.so.1.8.14
/usr/lib64/libtdclient.so
/usr/lib64/libtdclient.so.1.8.14
/usr/lib64/libtdcore.a
/usr/lib64/libtddb.a
/usr/lib64/libtdjson_private.a
/usr/lib64/libtdjson.so
/usr/lib64/libtdjson.so.1.8.14
/usr/lib64/libtdjson_static.a
/usr/lib64/libtdnet.a
/usr/lib64/libtdsqlite.a
/usr/lib64/libtdutils.a
/usr/lib64/pkgconfig/tdactor.pc
/usr/lib64/pkgconfig/tdapi.pc
/usr/lib64/pkgconfig/tdclient.pc
/usr/lib64/pkgconfig/tdcore.pc
/usr/lib64/pkgconfig/tddb.pc
/usr/lib64/pkgconfig/tdjson.pc
/usr/lib64/pkgconfig/tdjson_private.pc
/usr/lib64/pkgconfig/tdjson_static.pc
/usr/lib64/pkgconfig/tdnet.pc
/usr/lib64/pkgconfig/tdsqlite.pc
/usr/lib64/pkgconfig/tdutils.pc
/usr/share/doc/tdlib-1.8.14/README.md.bz2
```

**Comment by levlam** [comment]
`tg_cli` is an internal testing tool and is not supposed to be installed or used for anything besides TDLib development.

**Comment by asarubbo** [comment]
I didn't verify case-by-case but I think that the same applies also to:

```
benchmark/bench_actor
benchmark/bench_crypto
benchmark/bench_db
benchmark/bench_empty
benchmark/bench_handshake
benchmark/bench_http
benchmark/bench_http_reader
benchmark/bench_http_server
benchmark/bench_http_server_cheat
benchmark/bench_http_server_fast
benchmark/bench_log
benchmark/bench_misc
benchmark/bench_queue
benchmark/bench_tddb
benchmark/check_proxy
benchmark/check_tls
benchmark/rmdir
benchmark/wget
tdactor/example
tddb/binlog_dump
td/generate/generate_c
td/generate/generate_common
td/generate/generate_json
td/generate/remove_documentation
td/generate/td_generate_java_api
td/generate/tl-parser/tl-parser
tdutils/generate/generate_mime_types_gperf
```

**Comment by levlam** [comment]
See https://github.com/tdlib/td/pull/1127#issuecomment-654501793.

**Comment by asarubbo** [comment]
> See [#1127 (comment)](https://github.com/tdlib/td/pull/1127#issuecomment-654501793).



In that ticket you are saying:
> You need to build TDLib only once, so build time should be irrelevant for ordinary usages

While on the [ticket](https://github.com/tdlib/td/issues/1627) that I was asking to `git tag` more frequently you said that every day there is a commit that add new functionalities.

It is enough clear that both declaration do not have a match, and is clear that there are a lot of people that are asking the same things, so if the discussion is not anymore on technical side, I'm out of idea.

**Comment by levlam** [comment]
Telegram releases comes approximately once a month, so you are not expected to update TDLib every day. But when you are updating, you are supposed to update to the latest version.
