### ISSUE TITLE
Message animation

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2505]
Trying to build and test a UI displaying Message animation content I noticed that telegram converts .gif files to .MP4. so there is a real use case where a .gif file is received by tdlib?

**Comment by levlam** [comment]
Yes. If the GIF was uploaded a long time ago, or is very big (for example, bigger than 30 MB) and was uploaded from Telegram Desktop (or another app, which doesn't support client-side conversion to MPEG4), then the animation will contain a GIF file.
