### ISSUE TITLE
Can't send emoji stickers in messages

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#2508]
Hi!
Could you please advice why when I try to send regular type sticker in send_message it works fine, but when I try to use the same code for sending custom type sticker I get an error:
`Can't send emoji stickers in messages`
?
Here's example code:
```
Long chatId;
Client client;
Client.ResultHandler resultHandler;
TdApi.Sticker sticker;

client.send(new TdApi.SendMessage(chatId, 0, 0, null, null,
        new TdApi.InputMessageSticker(new TdApi.InputFileId(sticker.sticker.id),
                new TdApi.InputThumbnail(new TdApi.InputFileId(sticker.thumbnail.file.id), sticker.thumbnail.width, sticker.thumbnail.height),
                sticker.width, sticker.height, sticker.emoji)), resultHandler);
```

**Comment by levlam** [comment]
Because emoji stickers can't be sent as a message. They can be used only in the message text using `textEntityTypeCustomEmoji` by Telegram Premium users.
