### ISSUE TITLE
 how to convert super group to basic group

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2509]

**Comment by levlam** [comment]
It is not possible.

**Comment by liaoxingquan** [comment]
o，it is how to convert private group to public group and how to convert public group to private group



---Original---
From: "Aliaksei ***@***.***&gt;
Date: Sun, Jun 25, 2023 21:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tdlib/td]  how to convert super group to basic group (Issue#2509)




 
It is not possible.

**Comment by levlam** [comment]
You just need to remove username of the supergroup to make it private.

**Comment by liaoxingquan** [comment]
thanks



---Original---
From: "Aliaksei ***@***.***&gt;
Date: Mon, Jun 26, 2023 15:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tdlib/td]  how to convert super group to basic group (Issue#2509)




 
You just need to remove username of the supergroup to make it private.
