### ISSUE TITLE
How to open the source code in Visual Studio?

### ISSUE THREAD

**Issue by AqlaSolutions** [tdlib/td#2512]
I'm new to C++. There are no vcproj files. How to open the source code in Visual Studio for normal edit, compile, debug experience?

What IDE do you use on Windows to develop this library?

**Comment by levlam** [comment]
See https://github.com/tdlib/td#building.

Also, new enough Visual Studio supports CMake out of the box. See https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio for more details.

**Comment by AqlaSolutions** [comment]
As stated in the linked docs I need to open a folder with CMakeLists.txt. The folder `\td\telegram\` doesn't contain it. If I try to open root folder VS shows this error:

> Error at D:\tgproj\td-master\CMakeLists.txt:9 (project):
>  No CMAKE_CXX_COMPILER could be found.
>  Tell CMake where to find the compiler by setting either the environment
>  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
>  to the compiler, or to the compiler name if it is in the PATH

**Comment by levlam** [comment]
No, it answers your question. See, what is CMake: https://en.wikipedia.org/wiki/CMake.

**Comment by levlam** [comment]
`CMake` isn't a build tool. To build a project with MSVC compiler it generates a Visual Studio solution with multiple projects in the build directory. You can open the solution `build/TDLib.sln` in Visual Studio.

Alternatively, you can open the TDLib root directory in Visual Studio. It will be able to find `CMakeLists.txt` and build the project using it by creating a solution inside "out" subdirectory. Given, `OpenSSL` and `zlib` are required to build TDLib, you will also need to change "CMake Settings for TDLib" by right-clicking the `CMakeLists.txt` file, choosing corresponding menu item, and adding `<full path to vcpkg>/vcpkg/scripts/buildsystems/vcpkg.cmake` as CMake toolchain file. Also, don't forget to delete and regenerate CMake cache after changing the toolchain file if you tried to build the project before specifying the toolchain file.
