### ISSUE TITLE
MtprotoHeader lang_pack value

### ISSUE THREAD

**Issue by AqlaSolutions** [tdlib/td#2514]
What value is set there? Is there a way to control it?

**Comment by levlam** [comment]
See documentation for "localization_target" option at https://core.telegram.org/tdlib/options.

**Comment by AqlaSolutions** [comment]
How can I set these options? I use C# client with C++/CLI tdlib.

**Comment by levlam** [comment]
Use the method `TdApi.SetOption`.

**Comment by AqlaSolutions** [comment]
Ok. It's confusing that in C# `Execute` is a static method while `Send` is instance method. So the difference is not just in being synchronous but in global/instance state.
