### ISSUE TITLE
Forward messages with the replied reference message

### ISSUE THREAD

**Issue by patzu** [tdlib/td#2515]
I am forwarding messages from a channel to another channel, but is there a way to forward replied messages too. When i forward a mssage with its corresponding replied message just new messages is sent and not the reference which is replies to. Is this possible in TDLib using Java?

**Comment by levlam** [comment]
If you forward both replied message and the message, which replies it, then the reply is always kept in forwarded messages in the latest Telegram versions. You need to use the latest TDLib version to access the latest Telegram features.
