### ISSUE TITLE
How to reduce ram usage?

### ISSUE THREAD

**Issue by ClarissaGazalaEvanthe** [tdlib/td#2516]
I only use 1 account but the ram increases with time

The ram memory for running tdlib is increasing over time, is there a way to keep the RAM from being used too much?

**Comment by levlam** [comment]
Make sure that all databases are enabled. If they are, then you can't decrease RAM usage more.

**Comment by vinifr** [comment]
Hello. About that, I was wondering what databases can I enable to save memory besides this one?

`parameters->use_message_database_ = true;`

**Comment by levlam** [comment]
@vinifr Only this one.
