### ISSUE TITLE
How save client?

### ISSUE THREAD

**Issue by ghost** [tdlib/td#2518]
I'm making an Android app!
Everything works, but only when the application closes and reopens Client becomes null.
But this is understandable, as I understand it, in order to save the session, you need to save the client in a third-party database (file).
But how to do it if the Client object is not serialized

**Comment by levlam** [comment]
The app isn't supposed to save anything between restarts. All needed data is saved by TDLib and the app just needs to provide the same database and files directory in `setTdlibParameters` to the newly created `Client` after restart. See https://core.telegram.org/tdlib/getting-started for more details.

**Comment by simonsssa** [comment]
Thahk you
