### ISSUE TITLE
Incorrect if condition

### ISSUE THREAD

**Issue by ivan-gorin** [tdlib/td#2519]
Hi, I've been looking through the tdlib code and noticed this part:

https://github.com/tdlib/td/blob/66234ae2537a99ec0eaf7b0857245a6e5c2d2bc9/td/telegram/ConfigManager.cpp#L941-L946

What is the point of the else, would it ever get called? Is it working as intended?

I've looked at the commit message for this line, but it's not very informative.

**Comment by levlam** [comment]
Yes, it works as intended. The config is reloaded on each restart. If the behavior would be ever unintended, then just " || true" needs to be removed.
