### ISSUE TITLE
How to forward image and video messages from a channel to a topic in a group?

### ISSUE THREAD

**Issue by patzu** [tdlib/td#2520]
First of all, I can forward any type of message (video, text, image, etc) from a source channel to a default topic of a group.

Secondly, I am sending simple text message from source channel to any of the topics in a group as well.

My problem is, I want to forward or send other type of messages as well but unable to get photo from the message object and build InputMessageContent objet and send it!

My question is:
Is it possible to forward or send complex messages like (image with caption, video with text) to topics other than default using TDLib?

**Comment by levlam** [comment]
`forwardMessages` has parameter `message_thread_id` for this.
