### ISSUE TITLE
Tdlib doens't remove chats frome the list if there was no conversation started

### ISSUE THREAD

**Issue by yuraiz** [tdlib/td#2521]
Steps to reproduce:
- Open a chat with someone you don't have messages
- Start a draft to make chat appear in the list on other clients
- Remove the draft: Then the chat gets removed from the list on telegram for android, but you still have it in clients those use tdlib

Unigram
![image](https://github.com/tdlib/td/assets/63008755/24db07dc-f1ea-4313-bbcb-05d8b3a0fb97)

Telegram X
![image](https://github.com/tdlib/td/assets/63008755/e7072499-ba7c-4682-8f0d-50f25e591039)

Paper Plane
![image](https://github.com/tdlib/td/assets/63008755/0d9fdb72-14c2-45ae-9806-dd24ac2c5a2b)

After you open the chat in the client it gets removed and it gets removed properly next times you try to reproduce it (except Paper Plane), but it's still reproducable with a different chat or after reload

**Comment by levlam** [comment]
Thank you. This is fixed internally and the fix will be publicly available in the next TDLib version.

**Comment by levlam** [comment]
This should have been fixed in TDLib 1.8.15.
