### ISSUE TITLE
Expected packet size is too big when testing HTTP proxy availability

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#2522]
Hi!
I try to test HTTP proxy availability with `TdApi.TestProxy` method, but sometimes the return result is like this:
{
  code = 400
  message = "Expected packet size is too big: 1391591938"
}
Can you suggest how can I get positive result? Proxy is actually working and available.

**Comment by levlam** [comment]
The error means that the proxy doesn't work. This is no different from any other error.
