### ISSUE TITLE
How to collect media Albums when there is no any field about their count?

### ISSUE THREAD

**Issue by patzu** [tdlib/td#2523]
I have a grouped image message and I want to forward it. When I am collecting images in a map I don't know how many media are in a message to collect them. Should I use timer to detect the last one? I am collecting them in a map but I don't know how many they are? And when should I send the albums?
```

           if (message.mediaAlbumId != 0) {
                if (!albums.containsKey(message.mediaAlbumId)) {
                    albums.put(message.mediaAlbumId, new ArrayList<>());
                }
                albums.get(message.mediaAlbumId).add(message);
            }
```

**Comment by RememberTheAir** [comment]
You either use a timer or wait for the next message that isn't shipped with that album id. I'm pretty sure there has been discussions here about this - but you can find a couple of strategies on how to deal with albums [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-deal-with-a-media-group)
