### ISSUE TITLE
Question on API id

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2525]
If a developer wishes to develop more than one client that uses the Telegram API/TDLib, is that possible?  
I know that my.telegram.org does not seem to expose the possibility of requesting more than one API ids.

Note: just a question out of curiosity. I do not need another api id at this point.

**Comment by levlam** [comment]
It is not possible to create multiple api_id for the same phone number.

**Comment by vincentneo** [comment]
Got it, thanks!
