### ISSUE TITLE
When i try to use tdlin in tomcat library native crash

### ISSUE THREAD

**Issue by nicolasfarina** [tdlib/td#2528]
Hi, I'm trying to run the example on a tomcat application server to be able to send telegram messages. What happens is that when the library tries to reload "tdblib" I get the following error. And so that it does not happen again I have to restart the tomcat.

![image](https://github.com/tdlib/td/assets/52745496/7d7764d9-9117-4ba7-951b-70fad617ffff)

**Comment by levlam** [comment]
See https://stackoverflow.com/questions/36936948/java-lang-unsatisfiedlinkerror-native-library-xxx-so-already-loaded-in-another.

**Comment by nicolasfarina** [comment]
I tried to do that and it didn't work, the posts are very old.

**Comment by levlam** [comment]
The answers on StackOverflow are correct and exactly descibe the cause of the issue with some solutions. You can find the code, which loads `libtdjni` at https://github.com/tdlib/td/blob/66234ae2537a99ec0eaf7b0857245a6e5c2d2bc9/example/java/org/drinkless/tdlib/Client.java#L16-L22

You need to modify the code as suggested in the answers.

**Comment by Juanma1106** [comment]
Hi @levlam , we try to do that.

**Here is the code:**
![image](https://github.com/tdlib/td/assets/110149053/609c5ff8-6140-46d2-9d50-0b57a13b251a)

**Inside conf, in file catalina.properties, we have this:**
![image](https://github.com/tdlib/td/assets/110149053/ef6a9419-32b0-4ad9-9fe4-eadd37201aef)

**In /opt/tomcat/shared/lib we put the native library "libtdjni.so".**
![image](https://github.com/tdlib/td/assets/110149053/859d8bac-dfae-4288-96d5-e1a015341d71)

**When we deploy the war in tomcat the first time, it's all ok, but when we try to deploy again (cp ...war /opt/tomcat/fastprg/), we have the next error:**
![image](https://github.com/tdlib/td/assets/110149053/32655b9d-7539-4afb-97d0-66cabd958b73)

**Comment by Juanma1106** [comment]
If we remove this load, we have the problema that the tomcat never load the library 
![image](https://github.com/tdlib/td/assets/110149053/6286e498-e3cc-4d86-9cef-743ceed8fb23)

The error we have when we try to create the client is:
![image](https://github.com/tdlib/td/assets/110149053/9fc953ef-95ac-4912-9850-22653e9e2036)

**Comment by levlam** [comment]
You must load the library manually from a proper place.
