### ISSUE TITLE
When I use tdlib in ios, I don't know the name of the type value and the name of the parameter that is requested to tdlib

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#253]
When I use tdlib in ios, I don't know the name of the type value and the name of the parameter that is requested to tdlib.for example:

When I need to set the GetChat, I don't know the value of the type and what parameters are needed, as are other interfaces.like this:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/6285162/40354342-301252b0-5de6-11e8-989a-e6b92c2b5f5a.png">
I don't know if the key 'chatId' and 'getChat' are correct.
There are other requests, such as setProxy, getProxy, GetChat, etc.

Is there a document for each interface type and parameter?

**Comment by levlam** [comment]
See scheme [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) or autogenerated [HTML documentation](https://core.telegram.org/tdlib/docs/td__api_8h.html) for the list of all available TDLib [methods](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html) and [classes](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_object.html).

**Comment by liaoyu1992** [comment]
Ok,thank you.
