### ISSUE TITLE
Logout from all devices including tdlib app

### ISSUE THREAD

**Issue by BigBush3** [tdlib/td#2539]
I used python-telegram with tdlib, everything worked fine, but all of a sudden all the devices left the account and the session was interrupted, after that I could not request the code in any way, it just did not come to telegram when I requested it through the bot, with what can be related to this problem?

**Comment by levlam** [comment]
You need to try to log in from an official mobile app and follow instructions provided by the app if failed to log in.

**Comment by BigBush3** [comment]
log in from an official mobile app is working fine, but i am not receiving inner telegram code when trying to log in with tdlib

**Comment by levlam** [comment]
This is up to the server. Nothing can be done app-side.
