### ISSUE TITLE
Cannot write to secret chat

### ISSUE THREAD

**Issue by Infactum** [tdlib/td#254]
Looks like I'm missing something during secret chat usage with `tdlib_json`.
I'm creating new secret chat with `createNewSecretChat` method. After chat ID is recieved I'm trying to send message with `sendMessage` method but getting this error:
```
{
"@type": "error",
"code": 400,
"message": "Have no write access to the chat",
"@extra": 6
}
```

**Comment by levlam** [comment]
You can't write to a secret chat before it is accepted by the peer.

**Comment by Infactum** [comment]
Under what conditions will the chat go into ready state?
It's still pending even when I'm already sending messages on second party (mobile device).
`updateSecretChant` events with state update are not coming also.
