### ISSUE TITLE
Why do we build tdjson.dll, why could't just release in this repo?

### ISSUE THREAD

**Issue by wawan-ikhwan** [tdlib/td#2541]
It said for another program language interface, we should use tdjson.dll, why didn't this repo provide tdjson.dll built version?

**Comment by levlam** [comment]
Because binary files are not portable. You must build them yourself for target OS and architecture.

**Comment by wawan-ikhwan** [comment]
> Because binary files are not portable. You must build them yourself for target OS and architecture.

I mean, can we just build for all possible common OS such as Windows, Linux, and MacOS.

**Comment by levlam** [comment]
No, it is not possible. Binary files aren't compatible even between different versions of the same OS.

**Comment by wrharper-AASP** [comment]
so, if I make a tool for everyone to use, other people on windows may not even able to use it? is there any way to resolve this issue?

**Comment by levlam** [comment]
@wrharper-AASP 
On Windows you can build the executable for a fixed processor architecture and a chosen minimum supported Windows version. Then the executable will work for that and all newer Windows version, if they support running binaries for the chosen architecture and you ship all the dependent shared libraries along with the executable.
