### ISSUE TITLE
The obtained message is messageUnsupported, what should I do?

### ISSUE THREAD

**Issue by gplgpl775** [tdlib/td#2542]
Project background: node.js, the library uses the following: tdl, tdl-tdlib-addon, prebuilt-tdlib. I am using the interface provided by TDLib to obtain historical messages, and now there is a problem. This problem is: some information is of the "messageUnsupported" type, and the real information content cannot be obtained. Now I want to display the real information text, how should I do it? Thank you for your answer

**Comment by levlam** [comment]
You need to use the latest TDLib version.
