### ISSUE TITLE
Invalid picture dimensions / size?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2544]
Hi,

various 3rd party clients seem to stumble upon this error:

[MessagesManager33.cpp:247][#1][!Td] Failed to send yet unsent message 3775.25 in chat -955389183 with the error [Error : 400 : PHOTO_INVALID_DIMENSIONS]

https://github.com/zhukov/webogram/issues/726
https://github.com/majn/telegram-purple/issues/79
https://github.com/nickoala/telepot/issues/135
https://forum.sailfishos.org/t/the-volla-22-gigaset-gs5-thread/12939/288?u=jcoder

Can you elaborate a bit what are the rules for pictures? One user mentiones a file of 4,5MB or so, it does not sound too big these days ;)

**Comment by levlam** [comment]
The restrictions are described in the documentation of `inputMessagePhoto`:
```//@photo Photo to send. The photo must be at most 10 MB in size. The photo's width and height must not exceed 10000 in total. Width and height ratio must be at most 20```
