### ISSUE TITLE
How to send inline queries

### ISSUE THREAD

**Issue by hui87667137** [tdlib/td#2547]
I am developing a chat feature using Tdlib - Java. I have encountered an issue where a bot sends me content similar to the following:
```
InlineKeyboardButton {
text = "hello"
type = InlineKeyboardButtonTypeCallback {
data = bytes [4] { 61 61 61 61 }
}
}

```
How can I simulate the behavior of the official Telegram app to click this button and initiate a query?

**Comment by levlam** [comment]
Use the method `getCallbackQueryAnswer`.

**Comment by hui87667137** [comment]
Thanks
