### ISSUE TITLE
Error when constructing tdjson

### ISSUE THREAD

**Issue by PaperPlane28** [tdlib/td#2548]
`Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> git clone https://github.com/tdlib/td.git
Cloning into 'td'...
remote: Enumerating objects: 93724, done.
remote: Counting objects: 100% (17304/17304), done.
remote: Compressing objects: 100% (1508/1508), done.
remote: Total 93724 (delta 15993), reused 16808 (delta 15777), pack-reused 76420
Receiving objects: 100% (93724/93724), 45.70 MiB | 1.55 MiB/s, done.

Resolving deltas: 100% (67693/67693), done.
PS C:\Users\Administrator> cd td
PS C:\Users\Administrator\td> git clone https://github.com/Microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 200104, done.
remote: Counting objects: 100% (200104/200104), done.
remote: Compressing objects: 100% (68987/68987), done.
remote: Total 200104 (delta 131009), reused 199519 (delta 130798), pack-reused 0
Receiving objects: 100% (200104/200104), 63.81 MiB | 1.68 MiB/s, done.

Resolving deltas: 100% (131009/131009), done.
Updating files: 100% (10360/10360), done.
PS C:\Users\Administrator\td> cd vcpkg
PS C:\Users\Administrator\td\vcpkg> git checkout 1b1ae50e1a69f7c659bd7d731e80b358d21c86ad
Updating files: 100% (8895/8895), done.
Note: switching to '1b1ae50e1a69f7c659bd7d731e80b358d21c86ad'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 1b1ae50e1 [vcpkg-tools] update cmake and git (windows only) (#22985)
PS C:\Users\Administrator\td\vcpkg> ./bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-02-24/vcpkg.exe -> C:\Users\Administrator\td\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\Users\Administrator\td\vcpkg> ./vcpkg.exe install gperf:x86-windows openssl:x86-windows zlib:x86-windows
Computing installation plan...
The following packages will be built and installed:
    gperf[core]:x86-windows -> 3.1#3
    openssl[core]:x86-windows -> 1.1.1m#2
  * vcpkg-cmake[core]:x64-windows -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
    zlib[core]:x86-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.2.1). Downloading portable powershell-core v7.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/PowerShell-7.2.1-win-x86.zip -> C:\Users\Administrator\td\vcpkg\downloads\PowerShell-7.2.1-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> C:\Users\Administrator\td\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 317.6 us. Use --debug to see more details.
Starting package 1/5: gperf:x86-windows
Building package gperf[core]:x86-windows...
-- Downloading http://ftp.gnu.org/pub/gnu/gperf/gperf-3.1.tar.gz -> gperf-3.1.tar.gz...
-- Extracting source C:/Users/Administrator/td/vcpkg/downloads/gperf-3.1.tar.gz
-- Using source at C:/Users/Administrator/td/vcpkg/buildtrees/gperf/src/gperf-3-d4135ad4b1.clean
-- Found external ninja('1.11.0').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Users/Administrator/td/vcpkg/packages/gperf_x86-windows/share/gperf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Administrator\AppData\Local\vcpkg\archives\68\68437db27dc8b1e59db54f371086fb5d526b8c965d220179af4de964f212082f.zip
Installing package gperf[core]:x86-windows...
Elapsed time for package gperf:x86-windows: 14.16 s
Starting package 2/5: vcpkg-cmake:x64-windows
Building package vcpkg-cmake[core]:x64-windows...
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_get_vars.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/cmake_get_vars
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/cmake_get_vars/CMakeLists.txt
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Administrator\AppData\Local\vcpkg\archives\75\7538345316c21369fe7b3b0d1086dcaa8821a8486bfa56bc9b92d486727edb3a.zip
Installing package vcpkg-cmake[core]:x64-windows...
Elapsed time for package vcpkg-cmake:x64-windows: 123.5 ms
Starting package 3/5: vcpkg-cmake-config:x64-windows
Building package vcpkg-cmake-config[core]:x64-windows...
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: C:/Users/Administrator/td/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Administrator\AppData\Local\vcpkg\archives\5a\5a517fe3d0723ec54658ad16eb2fd6e1ba3e2233625d6e44ff6931128d507579.zip
Installing package vcpkg-cmake-config[core]:x64-windows...
Elapsed time for package vcpkg-cmake-config:x64-windows: 109.4 ms
Starting package 4/5: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- Downloading https://www.openssl.org/source/openssl-1.1.1m.tar.gz;https://www.openssl.org/source/old/1.1.1/openssl-1.1.1m.tar.gz -> openssl-1.1.1m.tar.gz...
-- Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip -> strawberry-perl-5.32.1.1-32bit.zip...
-- Extracting source C:/Users/Administrator/td/vcpkg/downloads/openssl-1.1.1m.tar.gz
-- Using source at C:/Users/Administrator/td/vcpkg/buildtrees/openssl/src/openssl-1-8c9323690c.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(705)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 17 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2364 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 2.591 min (155423700 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:620 (vcpkg_download_distfile)
  ports/openssl/windows/portfile.cmake:6 (vcpkg_find_acquire_program)
  ports/openssl/portfile.cmake:21 (include)
  scripts/ports.cmake:145 (include)

Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
including:
  package: openssl[core]:x86-windows -> 1.1.1m#2
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 1b1ae50e1 2022-02-25 (1 year, 5 months ago)

Additionally, attach any relevant sections from the log files above.
PS C:\Users\Administrator\td\vcpkg> cd ..
PS C:\Users\Administrator\td> Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
PS C:\Users\Administrator\td> mkdir build

    目录: C:\Users\Administrator\td

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2023/7/26      1:17                build

PS C:\Users\Administrator\td> cd build
PS C:\Users\Administrator\td\build> cmake -A Win32 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Building for: Visual Studio 17 2022
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.17763.
-- The CXX compiler identification is MSVC 19.36.32537.0
-- The C compiler identification is MSVC 19.36.32537.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ccache (this is NOT an error)
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.41.0.windows.3")
-- Git state: 8893dc808fa96399629d8d961ea1cbfbbc776480
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Deprecation Warning at td/generate/tl-parser/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning at CMakeLists.txt:185 (message):
  Can't find OpenSSL: stop TDLib building

-- Configuring done (9.1s)
-- Generating done (0.2s)
-- Build files have been written to: C:/Users/Administrator/td/build
PS C:\Users\Administrator\td\build> cmake --build . --target install --config Release
MSBuild version 17.6.3+07e294721 for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/Administrator/td/tdtl/CMakeLists.txt
  tl_config.cpp
  tl_core.cpp
  tl_file_outputer.cpp
  tl_file_utils.cpp
  tl_generate.cpp
  tl_outputer.cpp
  tl_string_outputer.cpp
  tl_writer.cpp
  正在生成代码...
  tdtl.vcxproj -> C:\Users\Administrator\td\build\tdtl\Release\tdtl.lib
  Building Custom Rule C:/Users/Administrator/td/td/generate/CMakeLists.txt
  generate_c.cpp
  generate_c.vcxproj -> C:\Users\Administrator\td\build\td\generate\Release\generate_c.exe
  Building Custom Rule C:/Users/Administrator/td/td/generate/CMakeLists.txt
  generate_common.cpp
  tl_writer_cpp.cpp
  tl_writer_h.cpp
  tl_writer_hpp.cpp
  tl_writer_jni_cpp.cpp
  tl_writer_jni_h.cpp
  tl_writer_td.cpp
  正在生成代码...
  generate_common.vcxproj -> C:\Users\Administrator\td\build\td\generate\Release\generate_common.exe
  Building Custom Rule C:/Users/Administrator/td/tdutils/generate/CMakeLists.txt
  generate_mime_types_gperf.cpp
  generate_mime_types_gperf.vcxproj -> C:\Users\Administrator\td\build\tdutils\generate\Release\generate_mime_types_gpe
  rf.exe
  Generating C:/Users/Administrator/td/tdutils/generate/auto/mime_type_to_extension.gperf, C:/Users/Administrator/td/td
  utils/generate/auto/extension_to_mime_type.gperf
  Extension "wmz" matches more than one type
  Extension "sub" matches more than one type
  Building Custom Rule C:/Users/Administrator/td/tdutils/generate/CMakeLists.txt
  Generating C:/Users/Administrator/td/tdutils/generate/auto/extension_to_mime_type.cpp
  Generating C:/Users/Administrator/td/tdutils/generate/auto/mime_type_to_extension.cpp
  Building Custom Rule C:/Users/Administrator/td/tdutils/CMakeLists.txt
  Clocks.cpp
  FileFd.cpp
  IPAddress.cpp
  MemoryMapping.cpp
  path.cpp
  platform.cpp
  PollFlags.cpp
  rlimit.cpp
  ServerSocketFd.cpp
  signals.cpp
  sleep.cpp
  SocketFd.cpp
  stacktrace.cpp
  Stat.cpp
  StdStreams.cpp
  thread_local.cpp
  UdpSocketFd.cpp
  uname.cpp
  user.cpp
  wstring_convert.cpp
  正在生成代码...
  正在编译...
  Epoll.cpp
  EventFdBsd.cpp
  EventFdLinux.cpp
  EventFdWindows.cpp
  Iocp.cpp
  KQueue.cpp
  NativeFd.cpp
  Poll.cpp
  Select.cpp
  ThreadIdGuard.cpp
  ThreadPthread.cpp
  WineventPoll.cpp
  AsyncFileLog.cpp
  base64.cpp
  BigNum.cpp
  buffer.cpp
  BufferedUdp.cpp
  check.cpp
  crypto.cpp
  emoji.cpp
  正在生成代码...
  正在编译...
  ExitGuard.cpp
  FileLog.cpp
  filesystem.cpp
  find_boundary.cpp
  FlatHashTable.cpp
  FloodControlGlobal.cpp
  Gzip.cpp
  GzipByteFlow.cpp
  Hints.cpp
  HttpUrl.cpp
  JsonBuilder.cpp
  logging.cpp
  misc.cpp
  MpmcQueue.cpp
  OptionParser.cpp
  PathView.cpp
  Random.cpp
  SharedSlice.cpp
  Slice.cpp
  StackAllocator.cpp
  正在生成代码...
  正在编译...
  Status.cpp
  StringBuilder.cpp
  tests.cpp
  Time.cpp
  Timer.cpp
  TsFileLog.cpp
  tl_parsers.cpp
  translit.cpp
  TsCerr.cpp
  TsLog.cpp
  unicode.cpp
  utf8.cpp
  MimeType.cpp
  正在生成代码...
  mime_type_to_extension.cpp
  extension_to_mime_type.cpp
  正在生成代码...
  tdutils.vcxproj -> C:\Users\Administrator\td\build\tdutils\Release\tdutils.lib
  Building Custom Rule C:/Users/Administrator/td/td/generate/CMakeLists.txt
  generate_json.cpp
  tl_json_converter.cpp
  正在生成代码...
  generate_json.vcxproj -> C:\Users\Administrator\td\build\td\generate\Release\generate_json.exe
  Building Custom Rule C:/Users/Administrator/td/td/generate/CMakeLists.txt
  remove_documentation.cpp
  remove_documentation.vcxproj -> C:\Users\Administrator\td\build\td\generate\Release\remove_documentation.exe
  Building Custom Rule C:/Users/Administrator/td/td/generate/CMakeLists.txt
  generate_java.cpp
  tl_writer_java.cpp
  正在生成代码...
  td_generate_java_api.vcxproj -> C:\Users\Administrator\td\build\td\generate\Release\td_generate_java_api.exe
  Building Custom Rule C:/Users/Administrator/td/td/generate/tl-parser/CMakeLists.txt
  crc32.c
  tlc.c
  tl-parser.c
  wgetopt.c
  正在生成代码...
  tl-parser.vcxproj -> C:\Users\Administrator\td\build\td\generate\tl-parser\Release\tl-parser.exe
  Building Custom Rule C:/Users/Administrator/td/CMakeLists.txt
  1>
  -- Install configuration: "Release"
  -- Installing: C:/Users/Administrator/td/build/../tdlib/lib/tdutils.lib
PS C:\Users\Administrator\td\build> cd ..
PS C:\Users\Administrator\td> cd ..
PS C:\Users\Administrator> dir td/tdlib
`

This error occurs：Error: Building package openssl:x86-windows failed with: BUILD_FAILED
May I ask how to solve this problem

**Comment by levlam** [comment]
You have an error with installing dependencies with `vcpkg`, which is likely to be caused by your Internet connection:
```
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410
...
Failed to download file with error: 1
  If you use a proxy, please check your proxy setting. Possible causes are:

  1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
     to `https://address:port`. This is not correct, because `https://` prefix
     claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
     , etc..) is an HTTP proxy. Try setting `http://address:port` to both
     HTTP_PROXY and HTTPS_PROXY instead.

  2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
     will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
     Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
     Change `http=address:port;https=address:port` to `address`, and fill the port number.

  3. Your proxy's remote server is out of service.

  In future vcpkg releases, if you are using Windows, you no longer need to set
  HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
  Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
  and (https://github.com/microsoft/vcpkg-tool/pull/77)

  Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
```

**Comment by PaperPlane28** [comment]
ok，thanks

**Comment by levlam** [comment]
The issue happens, because the site https://www.nasm.us is down. You can find some workarounds at https://github.com/microsoft/vcpkg/issues/32600.
