### ISSUE TITLE
Optimize database

### ISSUE THREAD

**Issue by AqlaSolutions** [tdlib/td#2555]
My message database reaches 1GB. Imagine it happening on multiple accounts. Imagine it running inside UWP sandbox which doesn't allow disk access except appdata folder on drive C:. Now you got the idea.

I want to keep the database but remove unnecessary data from it. Something like `OptimizeStorage` but for database. Is there a way to do it?

I tried just deleting the whole database but then it resets active proxy and looses secret chats history which I need to keep.

**Comment by levlam** [comment]
This is not supported yet, because it is very hard to find whether data in the database is "unnecessary".

By the way, the active proxy isn't deleted by deletion of `db.sqlite`, but messages from secret chats are.

**Comment by AqlaSolutions** [comment]
Deleting everything except secret chats would be a good option. A better option would be to delete everything older than 24h.

**Comment by levlam** [comment]
It is extremely hard to identify, what is "everything except secret chats". Messages in secret chats can reference files, users, other chats and many other objects, which can reference other files, users, or chats. What is "older than 24 hours" is a separate and even more hard question, given the amount of different kinds of data stored in the database.

**Comment by AqlaSolutions** [comment]
Ok, if I just delete the database, are there any dangling folders which I need to delete along with it?

**Comment by levlam** [comment]
No. Just ensure that TDLib isn't run, while the database is deleted.
