### ISSUE TITLE
Attachment not sent

### ISSUE THREAD

**Issue by Juanma1106** [tdlib/td#2559]
We tried to send 4 attachments with TdApi.SendMessage Album.
We have the bytes of the attachments to send in memory, but we can't find a way to send them without first physically saving the files on our server.
Once we have them saved, we use the TdApi.InputFileLocal(path) method.
**Is there a way to send attachments without physically saving them in our server?**

Sometimes all the attachments are sent without problems and other times some of them fail.
In the handler that we associate with sending the message, it tells us that everything was sent correctly.

In the UpdateHandler, we get the error in UpdateMessageSendFailed. If we try to resend the message with TdApi.ResendMessages(chatId, messageIds[]) it gives us an error

Response in UpdateHandler:
![image](https://github.com/tdlib/td/assets/110149053/d487859a-bc06-42b4-b315-eba4e3f201bb)

Error when trying to resend the message:
![image](https://github.com/tdlib/td/assets/110149053/d0806fb6-c6b1-4146-adfb-21212899e6c0)

**Comment by levlam** [comment]
There is no way to send files without buffering them on a file system.

If a message fails to be sent because the specified local file doesn't exist, then there is no way to resend the message. You can only try to send another message with the same file.
