### ISSUE TITLE
Need to have external session storage for stateless services in kubernetes

### ISSUE THREAD

**Issue by Bugathur** [tdlib/td#2560]
Right now there is only a SQLite support that can't be used in stateless clustered services in kubernetes, as there is no mounted persistant volume and also there several instances of same pods are running, so we need to share DB across several pods.
So we need to have cloud native storage for data (PostgreSQL or anything else) and S3 for file storages.

I tried to find any solution and found this old request
https://github.com/tdlib/td/issues/225
Provided solution is applicable only for monoliths or statefull services without cluster support.

**Comment by levlam** [comment]
This is not possible. Telegram apps can't be stateless, because this would be extremely ineffective.
