### ISSUE TITLE
ReplyToMessageId is always 0 even though it's replied message from existing message

### ISSUE THREAD

**Issue by Tieshsteveloml** [tdlib/td#2561]
Hi,

I hope this message finds you well. I wanted to reach out regarding an issue I've been facing with the recent update in my application.

In the UpdateNewMessage, I have noticed that the ReplyToMessageId field consistently shows 0, even when it involves a replied message from an existing message on the channel. I tried setting UseMessageDatabase to true, but unfortunately, it didn't resolve the problem. Strangely, this used to work perfectly in the older version, but after updating to the latest version, I'm encountering this unexpected behavior.

I was wondering if you might have any insights or suggestions on how to address this matter effectively.

Your assistance would be highly appreciated.

Thank you for your time and attention,
Ties

**Comment by Tieshsteveloml** [comment]
> The latest TDLib has no field `ReplyToMessageId` in the message object, which was replaced with `ReplyTo` field. Check that you use up-to-date bindings for TDLib 1.8.15.

Thank you for your confirmation.
My TDLib version is 1.8.12, but it seems like the latest version on Nuget package manager (.Net4.8), Will you please give me the solution for my case?

**Comment by levlam** [comment]
You can build the latest TDLib yourself as described in https://tdlib.github.io/td/build.html?language=C%23 and pack it as a nuget package yourself, or use it with any wrapper listed in https://github.com/tdlib/td/tree/master/example#csharp.

**Comment by Tieshsteveloml** [comment]
I have tried the latest https://github.com/tdlib/td.git and [TDLIb](https://github.com/egramtel/tdsharp.git), but same issue.

**Comment by Tieshsteveloml** [comment]
I had to modify tdsharp project so that it can be worked properly with the latest td libs in c#

Thank you
