### ISSUE TITLE
Unknown contacts warning: Workflow, persistency

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2562]
Hi,

official Apps present a notification bar with "Unknown contact" warning upon receiving a new chat with an unknown person. 3 choices can be made: Add to address book, report and do nothing (by pressing X). After any of these actions the warning will never appear again.

I assume this is a client-side marker that will be set, but how is this persisted across devices? Otherwise if this is a local option it would appear on any client that has not seen this chat. So it must be stored server-side?

**Comment by levlam** [comment]
It's called `chatActionBar`. You need to process the field `chat.action_bar` and the update `updateChatActionBar`. Everything other is done by TDLib, including action bar synchronization with other apps.

**Comment by Flohack74** [comment]
Oh wow that is convenient! Thanks!

**Comment by Flohack74** [comment]
For completeness, to close the chat action bar without any action, call `removeChatActionBar` function.

**Comment by Flohack74** [comment]
@levlam if the action, like in official Apps, would be "report and leave", we would in fact call 2 functions, one is to report spam, and 2nd is to leave the chat right?

**Comment by levlam** [comment]
> we would in fact call 2 functions, one is to report spam, and 2nd is to leave the chat right?

Yes, `reportChat` and `leaveChat`.

**Comment by Flohack74** [comment]
Oh it seems I have to call `removeChatActionBar` for any action, I did an `addContact` now but the bar remained :)

**Comment by levlam** [comment]
Action bar is automatically removed by TDLib on any relevant action.
