### ISSUE TITLE
tdlib prebuilt java library is not up to date / does not support reactions

### ISSUE THREAD

**Issue by rufatagayev** [tdlib/td#2569]
I downloaded the prebuilt tdlib library for java from https://core.telegram.org/tdlib/tdlib.zip and using it in Android Studio. I can't get any reaction info from the TdApi.MessageInteractionInfo. It only has viewCount, forwardCount and replyInfo.

Where can I get the latest prebuilt version? Thanks!

**Comment by levlam** [comment]
There is no newer prebuilt version, but now you can build it yourself following instructions at https://github.com/tdlib/td/blob/master/example/android/README.md.

**Comment by rufatagayev** [comment]
When trying to build it, I supply the Android SDK path and NDK version (25 or 25.2.9519653) to the ./build-openssl.sh script, but I get an error that says: Error: failed to run clang from Android NDK.

**Comment by rufatagayev** [comment]
Got it! Turns out it was an import/namespace issue. The previous build from the website imported `TdApi.java` from `org.drinkless.td.libcore.telegram`. The new one I built now has the namespace `org.drikless.tdlib`. Thank you for the pointers!
