### ISSUE TITLE
td/telegram/tdjson_export.h: No such file

### ISSUE THREAD

**Issue by recoilme** [tdlib/td#257]
When i try link tdlib as static lib i have this error in this line:
https://github.com/tdlib/td/blob/master/td/telegram/td_json_client.h#L50

Help me pls solve it...

**Comment by levlam** [comment]
This file is created by cmake. You can find it at `${CMAKE_CURRENT_BINARY_DIR}/td/telegram/tdjson_export.h`.

**Comment by recoilme** [comment]
Error was on build step with openssl lib
After fix (debian):
```
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/lib/ssl ..
```
i found this file
thank you @levlam
