### ISSUE TITLE
Unable to load forum topics history 

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2571]
I'm trying to load messages from topic with the method TdApi.GetMessageThreadHistory but it works only for general topic. I'm retrieving ids by ForumTopicInfo.messageThreadId

**Comment by levlam** [comment]
Current;y, if the topic isn't the General topic, you need to load the message with identifier `ForumTopicInfo.messageThreadId` before you can use `TdApi.GetMessageThreadHistory`.
