### ISSUE TITLE
Can't find field [useDefaultMuteStories] with signature [Z]

### ISSUE THREAD

**Issue by adrianbartyczak** [tdlib/td#2576]
I built a new libtdjni.so library on Debian 12, and I get a new error (which I wasn't getting on Debian 11).

FATAL ERROR in native method: Can't find field [useDefaultMuteStories] with signature [Z]
	at org.drinkless.tdlib.Client.nativeClientReceive(Native Method)
	at org.drinkless.tdlib.Client.access$000(Client.java:15)
	at org.drinkless.tdlib.Client$ResponseReceiver.run(Client.java:148)
	at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)
	
Anyone know what this means? (I'm a Java developer, not a C++ developer). Thanks!

**Comment by levlam** [comment]
It means that you have incompatible versions of libtdjni.so and TdApi.java from different TDLib versions.

**Comment by adrianbartyczak** [comment]
Oh, I do see the tdlib library in my libs folder. I have it under the name "tdlib-java-src.jar". This is definitely the library that's mismatching.

But I don't remember where I got it from. When I built the libtdjni.so file, I deleted everything else.

And now when I build it, I for some reason get the following error:

```
[ajb@debian-clx:build]$ cmake --build . --target install
[ 20%] Generating Java TDLib API source files
[ 20%] Built target td_generate_java_api
[ 40%] Building Java code
/tmp/td/example/java/org/drinkless/tdlib/example/Example.java:553: error: cannot find symbol
                case TdApi.UpdateChatIsBlocked.CONSTRUCTOR: {
                          ^
  symbol:   variable UpdateChatIsBlocked
  location: class TdApi
/tmp/td/example/java/org/drinkless/tdlib/example/Example.java:554: error: cannot find symbol
                    TdApi.UpdateChatIsBlocked update = (TdApi.UpdateChatIsBlocked) object;
                         ^
  symbol:   class UpdateChatIsBlocked
  location: class TdApi
/tmp/td/example/java/org/drinkless/tdlib/example/Example.java:554: error: cannot find symbol
                    TdApi.UpdateChatIsBlocked update = (TdApi.UpdateChatIsBlocked) object;
                                                             ^
  symbol:   class UpdateChatIsBlocked
  location: class TdApi
/tmp/td/example/java/org/drinkless/tdlib/example/Example.java:557: error: cannot find symbol
                        chat.isBlocked = update.isBlocked;
                            ^
  symbol:   variable isBlocked
  location: variable chat of type Chat
4 errors
gmake[2]: *** [CMakeFiles/build_java.dir/build.make:71: CMakeFiles/build_java] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/build_java.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
Did you guys change anything?

Thanks

**Comment by levlam** [comment]
The Java example wasn't updated to the latest TDLib version. I have just pushed a fix for this.

**Comment by adrianbartyczak** [comment]
Oh, you were right. I copied it to my projects libs folder, but forgot to copy it to /usr/lib/x86_64-linux-gnu/jni.

You have helped me a lot. Thanks!
