### ISSUE TITLE
is the Ad Test Channel still suppose to be working?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2579]
Probably not the right place for this question, but still somewhat relevant:
I realised that the Ad Test Channel (https://t.me/SecretAdTestChannel) no longer shows any sponsored messages, observed in both third party and official apps.

I remember this to be working back in sometime around March when I first implemented the feature in my own client. Not sure when this happened.

**Comment by levlam** [comment]
Could you try the same channel on the test servers?

**Comment by vincentneo** [comment]
I couldn't log in to either web.telegram.org/?test=1 or Telegram Mac with Alt+Shift, to use the test servers.

I tried +999 6612222 as the number, couldn't get pass sms code. Tried another number got pass sms code but stuck when asking me for first and last name (telegram web, could not continue with next button)

**Comment by levlam** [comment]
Telegram Mac should be able to register new account on the other phone number. You can also do this with Telegram for iOS: https://core.telegram.org/bots/webapps#using-bots-in-the-test-environment.

**Comment by vincentneo** [comment]
finally got it working with Telegram for iOS, and yes the channel does work with the test servers. I guess this is the way forward for that channel?

**Comment by levlam** [comment]
Yes, you can use the test channel to test ads.

**Comment by vincentneo** [comment]
Alright thanks!
