### ISSUE TITLE
How to use Setoption To Ignore Restrict Content?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2580]
I want to see adult content because I'm an adult, but why when I use this method 
```
{
    "@type": "setOption",
    "name": "ignore_sensitive_content_restrictions",
    "value": {
        "@type": "optionValueBoolean",
        "value": true
    }
}
```
this error appears

```
{
    "@type": error,
    "code": 400,
    "message": "Option "ignore_sensitive_content_restrictions" can't be changed by the user"
}
```
Btw I'm from Indonesia, is it because of my country?

**Comment by levlam** [comment]
Tes. See "can_ignore_sensitive_content_restrictions" option in https://core.telegram.org/tdlib/options.

**Comment by azkadev** [comment]
> Tes. See "can_ignore_sensitive_content_restrictions" option in https://core.telegram.org/tdlib/options.

I have tried but the results are false, how can my account use this?

**Comment by levlam** [comment]
It is a read-only option. If it is false, them you can't change the "ignore_sensitive_content_restrictions" option.

**Comment by azkadev** [comment]
:(
