### ISSUE TITLE
for Bot's Web App, is the main button implemented at client side?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2581]
I was looking at implementing to let users access [web apps](https://core.telegram.org/bots/webapps) used in bot chats, when accessed via my client.

Testing using [@DurgerKingBot](https://t.me/durgerkingbot) from the link above, I am unable to see the web app's [`MainButton`](https://core.telegram.org/bots/webapps#mainbutton), so I am assuming it should be implemented from the client side, rather than it being a html button?

The url used for displaying the web app, is from the result of calling `openWebApp` in TDLib.

For visual context, I am referring to the green button on the bottom of the web app: 

Official app:
<img width="200" alt="screenshot of durger king web app running within Telegram for Mac." src="https://github.com/tdlib/td/assets/23420208/95fbd9e0-61e9-4591-b406-afcb9e9f0b67">

Third party watchOS based client browser:
![screenshot of durger king web app running within Apple watchOS browser environment](https://github.com/tdlib/td/assets/23420208/79aaf8c4-68e9-4dd2-be18-2e1733bd2908)

**Comment by pantojax23** [comment]
Va

**Comment by levlam** [comment]
Yes, the main button is added by the app. The Web App can control the main button by sending "web_app_setup_main_button" [events](https://core.telegram.org/api/web-events#event-types) to the application.

**Comment by vincentneo** [comment]
How does the TDLib based client receive the event though, is there a particular update that should be looked at?

**Comment by levlam** [comment]
The interaction is done directly between the Web App and the app as described in https://core.telegram.org/api/web-events#webviewproxy.

**Comment by vincentneo** [comment]
oh so basically it is interacted via javascript?

**Comment by levlam** [comment]
Yes.

**Comment by vincentneo** [comment]
Alright! Thanks for the clarification.
