### ISSUE TITLE
Stories media are being downloaded to database directory

### ISSUE THREAD

**Issue by MadRay** [tdlib/td#2583]
Hi,

First of all, thanks for this awesome application.

Currently there is a behavior, that seems strange for me. 

I'm  using `files_directory` parameter to separate DB and media folders. With traditional media files it is ok - all videos, photos and thumbnails are being downloaded to provided path.

But stories uses database directory to store it's media:
```
profile
-> database
---> td.binlog
---> stories   /* stories media */
---> thumbnails  /* stories previews */
-> files
```

Is it correct behavior?

Thanks!

**Comment by levlam** [comment]
Yes, this is intended. Stories are small and private, hence they are stored along with the main database as document thumbnails and some other file types.
