### ISSUE TITLE
About Rate limitation

### ISSUE THREAD

**Issue by Yxue-1906** [tdlib/td#2592]
Hello, I want to know some limitations for bot and user, which are the approximate number for editing, sending message, create/close forum topic(s). And I'm curious about are editMessageText/editMessageReplyMarkup/... share same limitation?

**Comment by levlam** [comment]
The limits for users are high enough to be never exceeded by real users. For bots the limits for message editing are the same as for message sending. They can edit messages about 20 times per minute in a specific chat.

**Comment by Yxue-1906** [comment]
okay, thx for your reply! I want to ask two more questions,
one is are editing/sending message share the limit? (20 times per miniute) or I can send 20 messages and edit 20 messages per minute?
and how about the limit for creating/closing forum topic?

**Comment by levlam** [comment]
They share the limit. Creating a forum topic is sending a message about its creation.

**Comment by Yxue-1906** [comment]
thx!
