### ISSUE TITLE
How to know about all joined Supergroups?

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2594]
If I'm not mistaken the only way to know a supergroup is joined is `chatMemberStatus*` in `updateSupergroup.supergroup.status`.
But to find out about **all** joined ones I need to get **all** `updateSupergroup`. How can I make sure I have received all these updates?

**Comment by levlam** [comment]
There is no way to do this without loading full chat list.

**Comment by wowka1319** [comment]
When I get 404 for `loadChats` can I make sure I got `updateNewChat` for all joined supergroups already?

**Comment by levlam** [comment]
Yes.

**Comment by wowka1319** [comment]
`updateNewChat` for a supergroup contains required `updateNewChat.chat.type.supergroup_id`. Is it guaranteed I got `updateSupergroup` before for it?

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.

**Comment by wowka1319** [comment]
Found the answer. Thanks a lot.
1. When a joined channel is deleted (by its admin or Telegram because of violations) will the subscriber's account received `updateSupergroup`?
2. Will `updateSupergroup.supergroup.status` be `chatMemberStatusLeft` in this case?

**Comment by levlam** [comment]
> When a joined channel is deleted (by its admin or Telegram because of violations) will the subscriber's account received updateSupergroup?

Eventually, yes. The status can be `Left` or `Banned`.

**Comment by wowka1319** [comment]
If the app was off when deleting the channel and then it started, will that `updateSupergroup` be received?

**Comment by levlam** [comment]
The user will definitely know that the chat isn't accessible anymore sooner or later.

**Comment by wowka1319** [comment]
The user finds out that (after long being off) with exact `updateSupergroup` always? Or he has to remember about all chats before switch off and compare a new list after that?
