### ISSUE TITLE
How do I get an update that the message in the topic has been read.

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2596]
Let's say I was sent a message to the topic, and I read it from another client (let's say ios). How do I know that it has been read?

**Comment by levlam** [comment]
This isn't implemented yet. TDLib has only partial support for topics for now.

**Comment by fat-complex** [comment]
@levlam  Is there any way to get around this limitation or write a patch in tdlib (with your help) ?

**Comment by levlam** [comment]
There is no way currently to fully implement the updates. For now, apps can receive updated data only rarely by polling topic data with `getForumTopics`.

**Comment by fat-complex** [comment]
@levlam Thanks) I will be waiting for the new version with full support for topics.

**Comment by fat-complex** [comment]
@levlam One more question. And in which update is full support for topics expected?

**Comment by levlam** [comment]
I can't provide ETA. There are too much things to implement before topics will be usable.
