### ISSUE TITLE
Get all message from MessageCalendarDay

### ISSUE THREAD

**Issue by neoedmund** [tdlib/td#2599]
In `MessageCalendarDay`, there are `totalCount` and one `message`, how to get all the messages in the day?

**Comment by levlam** [comment]
This isn't needed in the calendar interface in the official apps, but if you still want to get all messages, then you can load up to `totalCount` messages using `searchChatMessages` using negative offset and the same filter.

**Comment by neoedmund** [comment]
Thank you. 
By  the way, is `tdlib` used in `telegramdesktop/tdesktop`? I cannot find it included in it.
Do you know any client actually using tdlib?

**Comment by levlam** [comment]
Among official apps only Telegram X uses TDLib, but you can find much more third-party apps in https://github.com/tdlib/td/tree/master/example#readme.
