### ISSUE TITLE
JAVA - Join channel and View Messages

### ISSUE THREAD

**Issue by chiragshah1312** [tdlib/td#260]
I'm working on android project and I'm trying to join a channel and view the messages of the channel, but no success. Can someone help me?

**Comment by levlam** [comment]
What do you mean by "no success"? What have you tried and what had happened?
Have you tried AddChatMember, OpenChat + ViewMessages?

**Comment by levlam** [comment]
Since TDLib 1.3.0 you can also use `JoinChat` instead of `AddChatMember` to join a chat.
