### ISSUE TITLE
chatInviteLinkInfo.type.supergroup_id = 0

### ISSUE THREAD

**Issue by wowka1319** [tdlib/td#2600]
I know `checkChatInviteLink` can return `chatInviteLinkInfo` with `chat_id=0`. But I also observe `checkChatInviteLink.type` as `chatTypeSupergroup` with `supergroup_id=0`. I cannot find this in docs for `chatTypeSupergroup`. Is this error?

**Comment by levlam** [comment]
The behavior is the same as for the `chat_id` field, i.e. the identifier isn't known if the user has no access to the chat before joining. I will explicitly mention this in the documentation.

**Comment by wowka1319** [comment]
Is `0` invalid id for every type (`supergroup`, `basic_group`, `user`, `message_id`, ...)?

**Comment by levlam** [comment]
1. Yes, but you can't receive 0 as the identifier and if you can, then this is documented.
2. No.
3. No.
