### ISSUE TITLE
What is the correct way to handle topics

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2601]
What is the supposed way to handle topics? Should I listen to some update to maintain a list of topics? And also I noticed that messages unread count of topics and of the entire forum is often wrong

**Comment by levlam** [comment]
@bossdeep There were no changes, topics are still supported only partially. But you can refresh the topic list on receiving a new topic message from an unknown message_thread_id, calling `getForumTopics` again.

**Comment by bossdeep** [comment]
> [@bossdeep](https://github.com/bossdeep) There were no changes, topics are still supported only partially. But you can refresh the topic list on receiving a new topic message from an unknown message_thread_id, calling `getForumTopics` again.

thank you, i will implement this!
