### ISSUE TITLE
How to get chat background images?

### ISSUE THREAD

**Issue by sap-nocops** [tdlib/td#2602]
I'm trying to implement chat backgrounds using tdlib json version.
I'm using `getBackgrounds` to get the list of all backgrounds but I don't understand how to get the actual image.
I tried `getBackgroundUrl` but it gives me a link to web page with the image as background, not the actual image.

How can I show the background images to the user?

PS
from `getBackgrounds` some elements have minithumbnail with a data inside that should represent the jpeg bytes
but not all backgrounds have it

thank you

**Comment by levlam** [comment]
`background` object has `document` and `type` fields, which fully descibe background appearance.

If `type` is `backgroundTypeWallpaper`, then you need to download the document's file, which will represent the background in JPEG format.
If `type` is `backgroundTypePattern`, then you need to download the document's file, which will represent the pattern to be shown above `type.fill`.
If `type` is `backgroundTypeFill`, then `document` will be null and you need to show just the background fill. You can find examples of background fill rendering at https://github.com/DrKLO/Telegram/blob/36067f8b38b0b0b1b4f482cf6038a1f60a01b717/TMessagesProj/jni/image.cpp#L968 and https://github.com/DrKLO/Telegram/blob/36067f8b38b0b0b1b4f482cf6038a1f60a01b717/TMessagesProj/jni/image.cpp#L1190.

**Comment by sap-nocops** [comment]
Thank you for your quick response.
I have another question: where to download the document's file? there is no link inside background's document.
starting from the background's url got wih `getBackgroundUrl` I could find: `https://t.me/bg/background_name?pattern_file=1`  is this valid for all backgrounds?

thank you again

**Comment by levlam** [comment]
All files can be downloaded using the method `downloadFile`.

**Comment by levlam** [comment]
Files doesn't have public HTTP links and can't be downloaded over HTTP. You can download them only through TDLib.
