### ISSUE TITLE
How to connect using different port? 

### ISSUE THREAD

**Issue by kuzya-ysu** [tdlib/td#2603]
I need to connect to tdlib using port 7778. How can I do it?

**Comment by levlam** [comment]
TDLib is an embedded library and you can't connect to it via port.

**Comment by Valentyna12** [comment]
***@***.***

**Comment by Loko32155** [comment]
{
  "address":
"0:921f5fbfe83f65c3872edce6a511e83201d66ee88b92323f8823a0762a756344",
  "name": "Auction username telegram ",
  "symbol": "t.me/bigunt",
  "decimals": "9",
  "image": "
https://cache.tonapi.io/imgproxy/WOwgMOGPcFUby9IULqawoGgyx_NsL9jESu-bvysIvrY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9naXRodWIuY29tL3doYWxldG9udG9rZW4vd2hhbGV0b250b2tlbi9ibG9iL21haW4vMzlCREI2N0ItMUQzNC00ODkzLThEMUQtNzIyOUQ5MjZCOEIxLnBuZz9yYXc9dHJ1ZQ.webp
",
  "description": "https://t.me/bigunt"
}
