### ISSUE TITLE
Limits of getMessages method

### ISSUE THREAD

**Issue by ne0c0de** [tdlib/td#2605]
Hi,

I want to get messages from telegram server instead of waiting their system for push.

Hence telegram message ids are incremental for groups, I decide to call getMessages method frequently in a short period of seconds.

Do anyone know what is the limit of this method (meaning how many calls that I can do in a second)?

**Comment by levlam** [comment]
> I want to get messages from telegram server instead of waiting their system for push.

This is not possible.

> Hence telegram message ids are incremental for groups,

This is not guaranteed and isn't always true.

>  I decide to call getMessages method frequently in a short period of seconds.

Your account will be rate-limited and can be even banned because of this.

**Comment by rufatagayev** [comment]
Do you mean the rate limit would be applied to the account of the user who is logged in or the account for the application, i.e. the one using the api key?

**Comment by levlam** [comment]
Automatically registered accounts can be also banned.
