### ISSUE TITLE
Old TdLib for Java

### ISSUE THREAD

**Issue by ilhomsoliev** [tdlib/td#2607]
When or will there be new version of TD library for java? The latest version of the library is back in 2021 and has not new features that Telegram has now like Premium feature or stories, so when it will release or am I looking in a wrong direction?

**Comment by levlam** [comment]
Now you can easily build TDLib for Android yourself, following build instructions at https://github.com/tdlib/td/tree/master/example/android.

**Comment by ilhomsoliev** [comment]
> Now you can easily build TDLib for Android yourself, following build instructions at https://github.com/tdlib/td/tree/master/example/android.

Worked, thank you very much for quick respond, love you!
