### ISSUE TITLE
Java Android SearchPublicChats

### ISSUE THREAD

**Issue by chiragshah1312** [tdlib/td#261]
```
TdApi.SearchPublicChats searchPublicChat = new TdApi.SearchPublicChats("Coindelta");
TgClient.send(searchPublicChat, this);
```
_W/System: ClassLoader referenced unknown path: /system/framework/QPerformance.jar
E/BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]_
...
...
...
V/BoostFramework: BoostFramework() : mPerf = null
A/DLTD: [1527684465.813129425][td_java_api.cpp:384] [!(0) && no_return_func()] 
        --------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7223 (Thread-2)

        [ 05-30 18:17:45.819  3129: 3129 W/         ]
        debuggerd: handling request: pid=6966 uid=10191 gid=10191 tid=7223
I get this Error. I'm doing this on android, can someone guide me?

**Comment by levlam** [comment]
What TDLib version are you using? Have you downloaded it from https://core.telegram.org/tdlib/tdlib.zip?Have you updated native libtdjni.so?

**Comment by levlam** [comment]
Please provide additional details and reopen the issue if the problem still persists. Closing for now.
