### ISSUE TITLE
[Guidance Requested] iOS APNS Push notification structure documentation?

### ISSUE THREAD

**Issue by triton3** [tdlib/td#2613]
This is a question/request for guidance on how exactly the push notifications are structured for iOS APNS/APS.

#2456 seems to indicate that the tdlib notifications API is not suitable on iOS.

The `from_id` seems to correspond to chat id only for one-to-one chats. The `thread_id` is the same for one-to-one chats, however for group chats neither the `from_id` nor `thread_id` correspond to chat id. 

The `msg_id` parameter is not the actual message id.

The `sound` parameter is always seemingly set to `0.m4a`.

So the question is:
- How to reliably get the chat id and message id from the APS payload?

**Comment by 773852362** [comment]
967773852362

في الخميس، 21 شتنبر 2023 10:39 م triton3 ***@***.***> كتب:

**Comment by levlam** [comment]
"from_id" is identifier of the user. You can try to call `getUser` with this identifier and then `createPrivateChat` if the user is known. Alternatively, push can contain "chat_id"/"channel_id"/"encryption_id" fields, which are identifiers of the corresponding basic group/supergroup/secret chat and can be processed in a similar way.

You can get TDLib's message identifier from "msg_id" by multiplying it by 2**20: `msg_id << 20`.

The sound can be different if a different sound was chosen for the chat.

**Comment by levlam** [comment]
You can find description of more possible fields in push notifications at https://core.telegram.org/api/push-updates#notification-structure.

**Comment by triton3** [comment]
@levlam Thank you for the quick response. Appreciate it!

The description helps to understand the fields. I will try the `encryption_id` and `msg_id` per your suggestion.

However, I am not seeing `chat_id` or `channel_id` fields. There is a `thread-id` field, however, for group chats it is not exactly the same chat id as seen from tdlib chat. It seems this `thread-id` is shorter than the actual chat id (if I look at both as strings, then the last _n_ characters of the actual chat id match the `thread-id` in one instance).

- Is there a transformation to extract the full `chat_id` from `thread-id` similar to `msg_id`?

- Regarding sound, the `0.m4a` is not useful because from the list of notification sounds downloaded from tdlib, there is none that match (in fact, those are in `.mp3` fromat and needed to be converted to `.wav` for iOS to even process those sounds in a notification). When I create a local notification manually, I can use the sound id and get the matching file name, but for remote notifications this `sound` parameter doesnt help. Perhaps if I can extract the `chat_id` I can use that to determine the sound for the notification. 

I post some examples below (I dont have an example on-hand for a group chat notification, but these show there is no `chat_id` or `channel_id` fields):

```
{
  "aps" : {
    "thread-id" : "secret",
    "alert" : "New secret chat request",
    "ringtone" : "507**********",
    "sound" : "0.m4a"
  },
  "encryption_id" : "13******"
}
```

```
{
  "aps" : {
    "thread-id" : "secret",
    "alert" : "You have a new message",
    "ringtone" : "507**********",
    "sound" : "0.m4a"
  },
  "encryption_id" : "21******",
  "random_id" : "-77**************"
}
```

```
{
  "aps" : {
    "thread-id" : "55******",
    "mutable-content" : 1,
    "alert" : {
      "title" : "redacted",
      "body" : "📌 redacted"
    },
    "ringtone" : "507**********",
    "category" : "m",
    "sound" : "0.m4a"
  },
  "msg_id" : "1***",
  "from_id" : "55******" // same as thread-id
}
```

```
{
  "aps" : {
    "thread-id" : "59*****",
    "mutable-content" : 1,
    "alert" : {
      "title" : redacted",
      "body" : "📎 redacted"
    },
    "ringtone" : "507**********",
    "category" : "r",
    "sound" : "0.m4a"
  },
  "attachb64" : "2MTUj*****",
  "from_id" : "59******",
  "msg_id" : "1***"
}
```

**Comment by levlam** [comment]
The "thread-id" looks like either "chat_id" or "channel_id". You can try both `getBasicGroup` and `getSupergroup` and use whichever succeeds.

**Comment by triton3** [comment]
Understood. Thank you for the clarification!
