### ISSUE TITLE
How can I get Message sequence id in a channel ?

### ISSUE THREAD

**Issue by dylanpoe** [tdlib/td#2619]
In tdlib,I  can get new message from "Updates", it contains the updates like new message or user status,
While ,my question is  how could I know the message sequence ID for the specific message in the channel?
The update message give me the id in message struct ,but the message id is not the sequence id for message in the channel
If I want visit  the message like    https://t.me/mychannelname/123, like 123 ,means the message is the 123 index in the channel,
how could I know the sequence id like 123?

**Comment by levlam** [comment]
There is no such thing as "message sequence ID". Use the method `getMessageLink` to get an HTTPS link for a given message.

**Comment by dylanpoe** [comment]
ok,thank you
