### ISSUE TITLE
Unable to reply to a non-top post in a particular message thread

### ISSUE THREAD

**Issue by Eriter555** [tdlib/td#2620]
Hello. I am unable to reply to a non-top post in a particular message thread. The reply_to_message_id parameter is ignored. I specify the parameters
 @type: sendMessage
chat_id: chatId (-100123456789)
message_thread_id: MessageThreadId (123456)
reply_to_message_id: ReplyToMessageId (1234567)
input_message_content: ...

I'm trying to do all this in the community discussion chat, i.e. in a group created to discuss community news.

**Comment by levlam** [comment]
It is not possible to use identifiers, which aren't received from TDLib. Did you receive the `reply_to_message_id` from TDLib during the same TDLib instance launch?

**Comment by Eriter555** [comment]
> It is not possible to use identifiers, which aren't received from TDLib. Did you receive the `reply_to_message_id` from TDLib during the same TDLib instance launch?

Just checked, reply_to_message_id is ignored in any chats(checked on private). Yes I get the chat id from TdLib with the getChat command.

**Comment by levlam** [comment]
You must also get the `reply_to_message_id` identifier from TDLib. For example, by preloading the message with `getMessageLinkInfo` or `getMessage` request.

**Comment by Eriter555** [comment]
> You must also get the `reply_to_message_id` identifier from TDLib. For example, by preloading the message with `getMessageLinkInfo` or `getMessage` request.

Thank you! Got it. Looks like the problem was in the version of the compiled tdlib library. Mine 1.8.17. On 1.8.8 it works fine, at least with private chats.

**Comment by levlam** [comment]
Method signature has changed recently. Now `sendMessage` expects the parameter `reply_to` of the type `MessageReplyTo`.

**Comment by Eriter555** [comment]
> Method signature has changed recently. Now `sendMessage` expects the parameter `reply_to` of the type `MessageReplyTo`.

Yes, that was the problem in the new version. I added the lines and everything worked:

`reply_to:`
`{@type: messageReplyToMessage`
`reply_tochat_id: chatId (-100123456789)`
`reply_tomessage_id: ReplyToMessageId  (1234567)}`

Thank you for the answers!

**Comment by tofers** [comment]
"Failed to parse JSON object as TDLib request: Unknown class "messageReplyToMessage""

"Failed to parse JSON object as TDLib request: Unknown class "messageReplyTo""

tdlib 1.8.24

**Comment by levlam** [comment]
@tofers 
Class "messageReplyTo" doesn't exist, but "messageReplyToMessage" is a valid class name for TDLib 1.8.24. Check response of `getOption("version")` to ensure that you use TDLib 1.8.24.
