### ISSUE TITLE
how to carry out user authorization using tdlib in java?

### ISSUE THREAD

**Issue by husanov98** [tdlib/td#2622]
I managed login to my account using AuthenticationSupplier, SimpleTelegramClientBuilder  and etc. But it is working only in idea console . I need enter phone number from front and need wait entering verification code from front without console . I have to do api for front. How to achieve this?

**Comment by husanov98** [comment]
@levlam could you help me?

**Comment by OdilbekOrifjonov** [comment]
Assalomu Aleykum, Javopini Topdizmi Oka, Yordam Bervorin

**Comment by husanov98** [comment]
Vaalaykum assalom telegramdan yozing @Xusanov-MG
