### ISSUE TITLE
CMake Error: failed to create symolic link.

### ISSUE THREAD

**Issue by dejadentendu** [tdlib/td#2624]
Having an issue when attempting to build. I have all of the dependencies installed I believe, and I most of the build goes smoothly until 78%. Screenshot attached.

![error](https://github.com/tdlib/td/assets/56529145/e09d7eea-e5df-47a7-af96-dda525cfdc22)

**Comment by levlam** [comment]
You have a file system, which doesn't support symlinks. You can hardly have Linux distribution on such file system. You can find some examples, when this is possible in https://askubuntu.com/questions/235700/linking-error-when-trying-to-compile-on-a-shared-drive.

**Comment by dejadentendu** [comment]
What file system should I run? This is an SD I’m building it on, so I can easily reformat it to whatever is needed.

**Comment by dejadentendu** [comment]
> You have a file system, which doesn't support symlinks. You can hardly have Linux distribution on such file system. You can find some examples, when this is possible in https://askubuntu.com/questions/235700/linking-error-when-trying-to-compile-on-a-shared-drive.

^

**Comment by levlam** [comment]
Use a filesystem, recommended by your OS, for example, ext4.
