### ISSUE TITLE
Question regards msg_id and db

### ISSUE THREAD

**Issue by wfjsw** [tdlib/td#263]
1. The message_id tdlib gives me seems pretty large. How can I get the (shorter) id relative to a channel/supergroup without using the nasty getPublicMessageLink?

2. What database holds the access_hash? I briefly scanned the issues and find it probably located in the message database, but I am looking for a waybto move it to chat info db as message db accumulates along time and there is no way to purge it.

**Comment by levlam** [comment]
1. See #69. Why do you need that except of getPublicMessageLink?
2. chat_info database.

**Comment by wfjsw** [comment]
Hmm I'm trying to reimplement an Bot API to gain more performance.

**Comment by wfjsw** [comment]
Well it is ok to use getPublicMessageLink as long as it doesn't involve more network activity.

**Comment by levlam** [comment]
Yes, in Bot API we have these conversions:
```
int64 Client::as_tdlib_message_id(int32 message_id) {
  return static_cast<int64>(message_id) << 20;
}

int32 Client::as_client_message_id(int64 message_id) {
  int32 result = static_cast<int32>(message_id >> 20);
  CHECK(as_tdlib_message_id(result) == message_id);
  return result;
}
```

In Bot API we don't use even file database to not use SQLite at all and achieve maximum performance.

Avatars aren't downloaded automatically. Thumbnails are part of a message and always sent by the server, so they are always received.

Between, Bot API source code will be open some time.

**Comment by wfjsw** [comment]
I thought of disabling file database but I have to persist access_hash between restarts.
Actually, I found that even database is on, my identity become unknown after restart.

BTW, a few more questions:
1. Will you export `langpack` methods in the future?
2. What is the mysterious `sendCustomRequest`
3. For debugging purpose, is it possible to disable sqlite encryption at all?

**Comment by levlam** [comment]
1. Yes.
2. It is for Bot API testing purposes without need to update it.
3. Currently, no.

**Comment by wfjsw** [comment]
OK, my question is done.

**Comment by wfjsw** [comment]
Hmm tests indicate access hashes drop when message database is disabled.
BTW as you disable sqlite database, how do you persist these data?

**Comment by levlam** [comment]
If message database is disabled, there is no data about chats in the local database, but information about users/basic groups/supergroups/secret chats is still stored in the database. So you need to use `getUser` + `createPrivateChat` to obtain a corresponding private chat or `getSupergroup` + `createSupergroupChat` for a supergroup chat instead of `getChat`.

**Comment by levlam** [comment]
@wfjsw 
1. You can now disable saving photo thumbnails to hard drive using `ignore_inline_thumbnails` option.
2. Language packs support is available in TDLib 1.3.0.

**Comment by wfjsw** [comment]
Shouldn't this be a TDLib parameter?

**Comment by levlam** [comment]
There are no usability or performance reasons to do that.

**Comment by mugavri** [comment]
> Between, Bot API source code will be open some time.

any update?

**Comment by levlam** [comment]
@mugavri Not yet.
