### ISSUE TITLE
Stuck on “authorizationsStateWaitPhoneNumber”

### ISSUE THREAD

**Issue by ToorajValaee** [tdlib/td#2630]
I try to test the [c#  example], it was stuck after entering the phone number.
I just replace the ApiId and ApiHash

**Comment by levlam** [comment]
Did you send `setAuthenticationPhoneNumber` request? Is Telegram banned in your area?

You can also set verbosity level of TDLib logs to 5 and check, what's going on there.

**Comment by HDJINJIN** [comment]
> Did you send `setAuthenticationPhoneNumber` request? Is Telegram banned in your area?
> 
> 
> 
> You can also set verbosity level of TDLib logs to 5 and check, what's going on there.
