### ISSUE TITLE
Got stuck on "authorizationStateWaitPhoneNumber"

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2632]
For some reason my tdlib does not let me log in after I send my phone number. I tried both using VPN and without it. Here are the logs
[logs.txt](https://github.com/tdlib/td/files/12848473/logs.txt)

**Comment by levlam** [comment]
The log shows that TDLib wasn't able to connect to Telegram servers. It is hard to identify exact cause of this, because for `tdweb` network connections are contolled by browsers.
