### ISSUE TITLE
Scaling bots

### ISSUE THREAD

**Issue by xtinkt** [tdlib/td#2633]
Hello! I have a question. I have a small AI startup and currently, I have around 90 users, all of whom are on one Telegram bot using my personal phone account. However, I am experiencing rapid growth and I'm concerned that I will soon exceed the limits of a single bot. My users are channels, and I need to send messages (or sometimes polls) to each channel 0-15 times a day. Additionally, I need to check the status of each post every 15 minutes and sometimes delete polls or messages if requested by the user.

Currently, I'm not strictly limiting the bot, but I sometimes encounter situations where I receive a 429 error (flood wait). I'm afraid that at some point, I will need to spread out the bot's requests over such a long interval that I won't be able to meet the necessary conditions.

I have a simple solution in mind where I create additional bots and distribute the channels between them. Although it's not very convenient, I believe it should work based on the publicly available information. Another thought I had was creating additional accounts under my name and using a bot on each of them.

Could you please advise me on whether my thoughts align with Telegram's terms of use? Can I create additional bots and accounts (let's say 3-4 accounts with 10 bots each) and ensure that each bot doesn't exceed 30 requests per second (including both publishing and viewing messages)?

**Comment by levlam** [comment]
User accounts aren't intended for such usages, and [bots](https://core.telegram.org/bots/api) have high enough limits to serve thousands users simultaneously.

**Comment by xtinkt** [comment]
> User accounts aren't intended for such usages, and [bots](https://core.telegram.org/bots/api) have high enough limits to serve thousands users simultaneously.

I probably didn't write very well in my previous comment, I use bots instead of users. The question is, if it is a good solution to add another bot and distribute the load between them, as I am starting to reach the limits of one of my bots. Or is it not possible to bypass the limits this way?

**Comment by RememberTheAir** [comment]
It would be helpful to know what requests are triggering the api into rate-limiting you. The operations you have described (sending/deleting 0-15 messages/polls per day in about 90 channels) will not trigger the api's rate-limiting (btw: how do you "check the status of a post"?)

You are probably involuntarily doing something that you shouldn't do

**Comment by levlam** [comment]
Bot API doesn't have `getMessages` request, in particular, because there is no way to scale it. There is no way to get message view counters, which will not lead to exceeding of different limits.

**Comment by xtinkt** [comment]
> Bot API doesn't have `getMessages` request, in particular, because there is no way to scale it. There is no way to get message view counters, which will not lead to exceeding of different limits.

But https://core.telegram.org/method/messages.getMessages bots can use this method (not from bot api) and get views from it, yes?

**Comment by levlam** [comment]
1. Yes, but it is impossible to scale constant polling of data.
2. There is no way.

**Comment by xtinkt** [comment]
> 1. Yes, but it is impossible to scale constant polling of data.
> 
>     2. There is no way.

Ok, thank you for the answer.
