### ISSUE TITLE
tdweb readFilePart issue

### ISSUE THREAD

**Issue by xucoanthony** [tdlib/td#2634]
I use tdweb (install by npm) in my vue project.I need play channel video in html video tag, most of these videos can be directly play while I was calling downloadFile method and meanwhile I called readFile or readFilePart method.
However, some of these videos's moov was in the end of the file, so I have to download the end part of this file and then I download from the begginning. So I will get a temp file with head part and tail part.
Normally, html video tag can be used to play these incomplete-file through blob url, but when I readFilePart method, I can just only get the head-part data. 
example:
downloaded head part 3MB
downloaded tail part 2MB
when call readFilePart(file_id,offset=0,limit=0), it would return 3MB data.
How to fix this promblem, Please, Thanks....

**Comment by xucoanthony** [comment]
I use tdweb (install by npm) in my vue project.
I need play channel video in html <video> tag, most of these videos can be directly play while I was calling downloadFile method and meanwhile I called readFile or readFilePart method.
However, some of these videos's moov was in the end of the file, so I have to download the end part of this file and then I download from the begginning. So I will get a temp file with head part and tail part.
Normally, html video tag can be used to play these incomplete-file through blob url, but when I readFilePart method, I can just only get the head-part data. 
example:
downloaded head part 3MB
downloaded tail part 2MB
when call readFilePart(file_id,offset=0,limit=0), it would return 3MB data.
How to fix this promblem, Please, Thanks....

**Comment by levlam** [comment]
What's the issue?

**Comment by xucoanthony** [comment]
> What's the issue?

I use tdweb (install by npm) in my vue project.I need play channel video in html video tag, most of these videos can be directly play while I was calling downloadFile method and meanwhile I called readFile or readFilePart method.
However, some of these videos's moov was in the end of the file, so I have to download the end part of this file and then I download from the begginning. So I will get a temp file with head part and tail part.
Normally, html video tag can be used to play these incomplete-file through blob url, but when I readFilePart method, I can just only get the head-part data.
example:
downloaded head part 3MB
downloaded tail part 2MB
when call readFilePart(file_id,offset=0,limit=0), it would return 3MB data.
How to fix this promblem, Please, Thanks....

**Comment by levlam** [comment]
You can call `readFilePart` to get the end part of the file, providing offset = file.size - 2MB and limit = 2MB.

**Comment by xucoanthony** [comment]
> You can call `readFilePart` to get the end part of the file, providing offset = file.size - 2MB and limit = 2MB.

Yes,  that's ok. But if I want to read the whole temp file, how to set?

**Comment by levlam** [comment]
If the file is fully downloaded, then you can use `readFilePart` to receive the whole file as `Uint8Array`.
