### ISSUE TITLE
Sticker thumbnail in wrong format

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#264]
Hello!

Sticker thumbnail in wrong format. path is in jpg format, but file actually is in webp format.

td version 1.2.0. Json lib version.

**Comment by levlam** [comment]
Sticker thumbnails can be in webp or jpeg format. The exact format isn't known until the file is downloaded, but we need to create a file before download begins. We can't fix it, so we at least documented that "Sticker thumbnail in WEBP or JPEG format".

**Comment by levlam** [comment]
Since TDLib 1.3.0 some sticker thumbnails will have ".webp" extension if they are more likely to be in WEBP format.
