### ISSUE TITLE
process_response(client_manager_->receive(10)) - why 10? 10 msec?

### ISSUE THREAD

**Issue by sip-for-telegram-com** [tdlib/td#2644]
hi @levlam 

https://github.com/tdlib/td/blob/master/example/cpp/td_example.cpp

`process_response(client_manager_->receive(10)) `- why 10? 10 msec?

what values are allowed?

why exactly 10?

can my account be blocked if I enter 5 15 25 50 here?

**Comment by levlam** [comment]
Check documentation for the function: https://github.com/tdlib/td/blob/7152a5c2e1e61b5d4595d204736bf98da435d126/td/telegram/Client.h#L116.
