### ISSUE TITLE
td/telegram/Td.cpp - f (options_.api_id != 21724)

### ISSUE THREAD

**Issue by sip-for-telegram-com** [tdlib/td#2645]
hi @levlam 
```
  if (options_.api_id != 21724) {
    options_.application_version += ", TDLib ";
    auto version = OptionManager::get_option_synchronously("version");
    CHECK(version->get_id() == td_api::optionValueString::ID);
    options_.application_version += static_cast<const td_api::optionValueString *>(version.get())->value_;
  }

```
what does this check do?

why check whether the api_id matches the Telegram x application or not?

**Comment by RememberTheAir** [comment]
Apparently, the code inside the "if" you mentioned will force-append `, TDLib v1.X` to the provided application version. This checks makes sure it is not appended to the app version if this app is TGX. It's probably because it is not worth mentioning in that officla app

**Comment by levlam** [comment]
Telegram X has multiple other ways to see used TDLib version, so adding it to the app version isn't needed.
