### ISSUE TITLE
Does tdlib allow changes to source code?

### ISSUE THREAD

**Issue by sip-for-telegram-com** [tdlib/td#2646]
hi @levlam 

Does tdlib allow changes to source code?

if for example I comment out the lines in

td/telegram/Td.cpp 

```

//if (options_.api_id != 21724) {
 //   options_.application_version += ", TDLib ";
  //  auto version = OptionManager::get_option_synchronously("version");
  //  CHECK(version->get_id() == td_api::optionValueString::ID);
  //  options_.application_version += static_cast<const td_api::optionValueString *>(version.get())->value_;
//  }
```

could this cause my account to be blocked?

On the server side, are there any integrity checks for the checksums of the tdlib library, some kind of protection against modification of the source code?

**Comment by levlam** [comment]
> Does tdlib allow changes to source code?

See https://github.com/tdlib/td/blob/master/LICENSE_1_0.txt.

> could this cause my account to be blocked?
>
> On the server side, are there any integrity checks for the checksums of the tdlib library, some kind of protection against modification of the source code?

It is up to the server.
