### ISSUE TITLE
Question: what is the purpose of "handlers_" variable in the td_example.cpp

### ISSUE THREAD

**Issue by normalscene** [tdlib/td#2649]
Hi, I have been studying the td_example.cpp and I have a question please.

What is the purpose of the handlers_ variable in the example.

https://github.com/tdlib/td/blob/dd77e4628f1a65f332f0cb81c82a19c0fcfa40c2/example/cpp/td_example.cpp#L143C3-L143C66

The only operation I saw with this handlers_ variable is :

1. we emplace an entry with key as query_id and value as the provided handler in the send_query function.
2. we remove the entry when a response object is received.

But I was not able to understand why did we need to do it and what is being achieved by doing the above said.

Can someone please throw some hints ? thank you.

**Comment by levlam** [comment]
It stores handlers for queries until the queries are completed.
