### ISSUE TITLE
iOS - Client::impl_ gets null sometimes

### ISSUE THREAD

**Issue by GRiMe2D** [tdlib/td#265]
I have built tdlib using patch in #177 and everything works fine until app goes to background.

When app is in background a long time, bringing it to foreground will crash the app.
Currently I have no idea why is happening. Only once I was able to attach debugger before error occurred and found, `unique_ptr<Impl> impl_` is `nullptr`, and crashes in cpplib `unique_ptr<T>.get()` function.

Some background:
I've built objective-c class to wrap c++ class to make iOS friendly API. Wrapper creates object and runs endless loop in a NSThread instance. I've tried to have a boolean indicator to stop the loop, but NSThread is frozen before it reaches the actual condition.

Must I use GCD for this? I'll try it later, however.

**Comment by levlam** [comment]
Are you sure that client was created through td_json_client_create and not destroyed through td_json_client_destroy?

Could it be possible that application was terminated in background and then relaunched, but client wasn't recreated?

**Comment by GRiMe2D** [comment]
I'm not using td_json interface. I'm constructing it directly and using through `Client::Request` and `Client::send()`, `Client::receive()` functions

**Comment by levlam** [comment]
Then could it be possible that application was terminated in background and then relaunched, but Client wasn't recreated?

**Comment by GRiMe2D** [comment]
I was getting `SIGPIPE` in debugger but app didn't crash due to handled signal (actually lldb handled the `SIGPIPE`)

Ignoring signal seems helped, now I'm not getting any crash.

```objective-c
@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    signal(SIGPIPE, SIG_IGN);
    return YES;
}
@end
```

**Comment by Oriient-Michael** [comment]
@GRiMe2D You are a life-saver! `SIGPIPE` handling is mentioned in Apple's documentation about sockets but it is not so easy to remember and connect the dots. I believe this should definitely be addressed in the tdlib for iOS documentation.

**Comment by levlam** [comment]
@Oriient-Michael Thanks for reminding about this. It seems that on macOS/iOS this can be fixed on TDLib's side.

**Comment by levlam** [comment]
@Oriient-Michael Could you check that in the latest TDLib version it isn't required to ignore SIGPIPE?

**Comment by Oriient-Michael** [comment]
@levlam Sure, but I use tdlib only in a pet project and it might take a few days for me to get to it.

**Comment by Oriient-Michael** [comment]
@levlam Tested with the build from master. Looking good without additional SIGPIPE handling. Thank you

**Comment by levlam** [comment]
@Oriient-Michael Thanks!
