### ISSUE TITLE
unable to locate tdlib after build

### ISSUE THREAD

**Issue by rdataforge** [tdlib/td#2650]
I am building tdlib into my Arch linux to be available for telega (telegram emacs implementation) but I dont know where tdlib is located and telega keeps saying there is no tdlib in /usr/lib

where is tdlib located?

**Comment by levlam** [comment]
Did you follow https://tdlib.github.io/td/build.html?language=Other and checked the option "Install built TDLib to /usr/local instead of placing the files to td/tdlib"? Did you install all the mentioned development dependencies "Git, g++ >= 4.9.2, make, CMake >= 3.0.2, OpenSSL-dev, zlib-dev, gperf, PHP"?

**Comment by rdataforge** [comment]
Yes, all dependencies are in place and followed the link to generate commands. Missed the check option referring to /usr/local,  my bad. Thanks for pointing it out

**Comment by GuidoBelluomo** [comment]
Getting a similar issue for C# UWP, "cp build-uwp/vsix/tdlib.vsix ../../../tdlib" fails because it cannot find tdlib.vsix

**Comment by levlam** [comment]
@GuidoBelluomo Follow the build instructions at https://tdlib.github.io/td/build.html?language=C%23.

The first step is "Download and install [Microsoft Visual Studio](https://visualstudio.microsoft.com/vs/community/). Enable C++ and Windows 10 SDK support while installing." Hence, recheck that UWP support is enabled. Also, don't forget to "Close and re-open PowerShell if the PATH environment variable was changed."

**Comment by GuidoBelluomo** [comment]
> @GuidoBelluomo Follow the build instructions at https://tdlib.github.io/td/build.html?language=C%23.
> 
> The first step is "Download and install [Microsoft Visual Studio](https://visualstudio.microsoft.com/vs/community/). Enable C++ and Windows 10 SDK support while installing." Hence, recheck that UWP support is enabled. Also, don't forget to "Close and re-open PowerShell if the PATH environment variable was changed."

I "enabled C++", in fact I enabled a whole bunch of C++ add-ons just to be safe. I also enabled UWP, thing is that it seems to compile a lot of things but still fails at some point.

**Comment by levlam** [comment]
How does it fail?

**Comment by GuidoBelluomo** [comment]
> How does it fail?

Just like I showed earlier, I'll do the whole thing again on my home computer and see how that goes to also get a full log if possible

**Comment by levlam** [comment]
> No CMAKE_CXX_COMPILER could be found.

The error means that compiler/UWP installation isn't complete.

**Comment by GuidoBelluomo** [comment]
[log.txt](https://github.com/tdlib/td/files/13211143/log.txt)

Are you sure that is it? It's finding the compiler three times before failing at the fourth time, whatever it is doing there.

Also, it's installed 
![image](https://github.com/tdlib/td/assets/3173154/98beb2cb-dbdb-43ca-9443-039810c9f298)

**Comment by levlam** [comment]
It fails to find UWP toolset for ARM.

**Comment by dchmelik** [comment]
This problem still exists; can you please add these instructions on github.com/tdlib/td to go to that HTML file?

**Comment by levlam** [comment]
@dchmelik What problem still exists?
