### ISSUE TITLE
when is it correct to call addProxy?

### ISSUE THREAD

**Issue by sip-for-telegram-com** [tdlib/td#2651]
https://core.telegram.org/tdlib/getting-started

before
`setTdlibParameters`
of after it?

if called after `setTdlibParameters`
then because there is no internet
the `setTdlibParameters` request will simply never be executed

but https://core.telegram.org/tdlib/getting-started says

"authorization states may be received. After completing these authorization steps, the Application will receive authorizationStateReady, meaning that authorization was successful and ordinary requests can be sent now"

**Comment by p-vorobyev** [comment]
Calling `AddProxy` immediately after setting `SetTdlibParameters` works fine for me. The documentation says that the `AddProxy` function can be called before authorization.

**Comment by levlam** [comment]
It doesn't matter. Calling it before `setTdlibParameters` just ensures that TDLib will not try to connect without proxy.
