### ISSUE TITLE
how to get responce value in tdlib?

### ISSUE THREAD

**Issue by sip-for-telegram-com** [tdlib/td#2652]
i have this code

`td_api::make_object<td_api::some_function>()`

i got responce in `to_string(response)`

```
user {
  ....
  pattern = 123
  some_other_parameters...
  .....
```

how i can get value of pattern from c++ tdlib?
Is there any ready-made method?

like this - check for error
`if (response->get_id() == td_api::error::ID) {`

what i need to do to get my pattern?
like
`response->pattern `

**Comment by levlam** [comment]
See documentation of the class [ClientManager](https://github.com/tdlib/td/blob/master/td/telegram/Client.h).
