### ISSUE TITLE
TdApi.GetChatHistory() getting newer messages from second time

### ISSUE THREAD

**Issue by rufatagayev** [tdlib/td#2653]
I'm using tdlib java on Android. I know the **TdApi.GetChatHistory()** is for getting older messages and that there is the last _known_ message idea and I have to open the chat and listen for message updates to get the newer messages.

When I call getChatHistory() with lastMessage?.id I get a result. But when I specifically don't call openChat, clear the app from memory and reopen the app, which calls getChatHistory() again - I get newer messages than the last time. Where do these messages come from? Does Tdlib remember my last call with my app id and know which newer messages to provide? Does this mean the last known message has now changed?

How can I make sure I get newer messages from the first launch? Appreciate any pointers!

**Comment by levlam** [comment]
If you get newer messages, then definitely the last known message has changed. There is no way to receive newest messages other than opening the chat and waiting for updates.

**Comment by rufatagayev** [comment]
What if I provide a negative offset in TdApi.GetChatHistory()? Let's say TdApi.GetChatHistory(chat.id, lastMessage.id, -10, 11) - would this give me newer messages from the previous last known message?

**Comment by levlam** [comment]
No.

**Comment by rufatagayev** [comment]
Thanks. Further to that, I do open the chat (TdApi.OpenChat()) and I have an active onUpdate() method that receives updates, but I don't receive any messages. I'm not talking about messages that are sent after the chat is open, but those that are already sent but newer than the last known message. How long does it usually take for those messages to be received?

**Comment by levlam** [comment]
There is no upper bound on the time for new updates to be received. But you should also be aware that in supergroups and channels not all new messages are received through `updateNewMessage` updates. If this happens, then an update `updateChatLastMessage` with `last_message == null` will be sent: "If last_message is null, then the last message in the chat became unknown". The update means that a message gap could have been created in the channel and newer messages can be received only by explicit `getChatHistory` request by the user.

**Comment by rufatagayev** [comment]
So if I understood correctly, I need to watch if I receive an updateChatLastMessage with last_message = null and then I can send another getChatHistory request. This is very helpful - thank you!
