### ISSUE TITLE
"next_offset" value for getting next `searchMessages`

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2655]
tdlib ver 1.8.20, wrapped as tdweb

Here I am trying to get next batch of messages using `searchMessages`. 
this line
`console.log(offset_date, offset_chat_id, offset_message_id);`
prints `1698738902 -1001099350027 169993`

However what I receive from `searchMessages` is this (the result is the old one, the same as before):
[foundMessages.json](https://github.com/tdlib/td/files/13218800/foundMessages.json)
And the next_offset is the same:
`next_offset: "1698738902,-1001099350027,169993"`

Also I've tried to explicitly hardcode the offsets just to be sure that the values are passed correctly. The result is the same.

The problem: I can't get the next batch of messages using next_offset. Maybe I am missing something 

```
export const td_searchMessages = async (
  client: TdClient | undefined,
  query: string,
  limit = 100,
  offset_date = 0,
  offset_chat_id = 0,
  offset_message_id = 0,
  chat_list = null,
  filter = null,
  min_date = 0,
  max_date = 0
): Promise<any> => {
    console.log(offset_date, offset_chat_id, offset_message_id);
    const res = await client!.send({
      "@type": "searchMessages",
      chat_list: chat_list!,
      query,
      offset_date,
      offset_chat_id,
      offset_message_id,
      limit,
      filter: filter!,
      min_date,
      max_date
    });
    console.log(res);
    return res;
  }
};
```

**Comment by levlam** [comment]
In TDLib 1.8.20 the method is declared as
`searchMessages chat_list:ChatList query:string offset:string limit:int32 filter:SearchMessagesFilter min_date:int32 max_date:int32 = FoundMessages;` and you need to pass the value od `next_offset` as received from the previous request as `offset` to the next request.

**Comment by teleothleo** [comment]
Oh! I see, thank you levlam!

**Comment by vortx** [comment]
I spent a lot of time on this, and if I hadn’t gotten here, I would have wanted to try it myself with a similar key. It’s too bad that the documentation does not contain this data!!!
