### ISSUE TITLE
Is this an error when forwarding a message to a topic?

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2656]
When redirecting a message to the recipient's topic, such a message from TDLib: "`[1][t 0][1698837249.406981945][MessagesManager.cpp:24216][!Td] Creating a message in thread of server message 1404 in chat -1001831148835 without reply`" or "`[ 1][t 0][1698846091.421813249][MessagesManager.cpp:35769][!ForumTopicManager]	server message 1711 in chat -1001831148835 has changed is_topic_message to true`". I use the 'forwardMessages' request and set the following parameters to it when sending: chat_id_, from_chat_id_, message_thread_id_, message_ids_. The sending is successful (I see this from the official client (iOS, Android)), but with each such sending I receive this log from TDLib, which I indicated above. Is this a mistake or not?

**Comment by levlam** [comment]
You need to preload the first thread message to be able to correctly send messages to the thread. For this you need to call `getMessageThread` before sending a message to the topic.
