### ISSUE TITLE
Question: Messages with Quoting still NotSupported

### ISSUE THREAD

**Issue by MadRay** [tdlib/td#2657]
Hello!

On 28th October Telegram presented "Quote Formatting". As I can see,  1.8.20 still can't process messages with quotes - we get such messages as NotSupported.

Are there any plans or ideas to get a such messages accessible via TdLib? 

Thanks

**Comment by levlam** [comment]
They are supported in TDLib 1.8.21, which will be publicly released soon. No ETA though.

**Comment by MadRay** [comment]
Thanks, Aliaksei!

**Comment by MadRay** [comment]
Thanks, Aliaksei!
