### ISSUE TITLE
Example.java compilation error, Java build fails, libtdjni cannot be generated

### ISSUE THREAD

**Issue by baikatov** [tdlib/td#2658]
Compilation error in Example.java lines 305-306, master branch

<details> 
  <summary>Unhandled Exception (screenshot)</summary>

   ![image](https://github.com/tdlib/td/assets/32789997/816c5140-eb01-40a3-b52a-9a8eefb2249b)  
</details>
<details> 
  <summary>Inconvertible Types (screenshot)</summary>

  ![image](https://github.com/tdlib/td/assets/32789997/f50b4bde-bce2-4bf2-81c6-3b5eeee86549)  
</details>
<br/>
  
Prevents from compiling `Example.java` and building `libtdjni`  
<br/>
  
Caused by this commit: https://github.com/tdlib/td/commit/dd77e4628f1a65f332f0cb81c82a19c0fcfa40c2, reverting it resolves this issue

**Comment by levlam** [comment]
The regression was fixed in TDLib 1.8.21, which will be released soon. For now, I would recommend to revert the last master commit as you did.
