### ISSUE TITLE
Why is there no new login information

### ISSUE THREAD

**Issue by CMfengbuzhi** [tdlib/td#2659]
I am using Windows tdlib JSON.The main client received login code information, but there was no new login information.How to set the device information and location information in the new login information?

**Comment by levlam** [comment]
What exactly and where do you want to set?

**Comment by CMfengbuzhi** [comment]
When logging in using tdlib, the main client will receive login code messages and new login messages. However, I cannot receive new login messages now and can only receive login code messages

**Comment by CMfengbuzhi** [comment]
The new login message contains device information such as Samsung Galaxy S20 and Desktop information such as Android. Where are these information set and which API should be used?

**Comment by levlam** [comment]
In TDLib 1.8.20 the app receives `updateUnconfirmedSession` whenever a new session is created.

**Comment by CMfengbuzhi** [comment]
tanks
