### ISSUE TITLE
Getting "Invalid segment alignment" error when trying to upload to iTunesConnect

### ISSUE THREAD

**Issue by WingedDoom** [tdlib/td#266]
Hi!

I've been developing an iOS app based on TDLib for past couple of months. As advised in the README.md, I use td_json_client to make requests to TDLib. I've built TDLib for iOS using ./build_openssl.sh and ./build.sh scripts from [example/ios](https://github.com/tdlib/td/tree/master/example/ios). Then I've added the compiled .dylib to `Link Binary with Libraries` and `Embed Libraries` build phases in Xcode. But when I try to submit a build to iTunesConnect after archiving the project using Organizer in Xcode 9.3, I get `Invalid segment alignment` error:

![2018-06-01 05 40 33](https://user-images.githubusercontent.com/6613809/40818384-7d52cfca-655f-11e8-92d6-f70ff217b33e.jpg)

I haven't ever seen such an error in my past experience, and have no idea how to fix it. Any ideas what could I do wrong and what should I check? The app works completely fine when I run it on the simulator or deploy to an iOS device through USB.

**Comment by arseny30** [comment]
As far as I know dylib should work fine since ios 8.
You just should sign it with the same signature as your app. And add it as an embedded framework (General->Embedded binaries).

**Comment by WingedDoom** [comment]
Adding the `.dylib` itself to Embedded binaries setting works during development, but results in errors during publishing to iTunesConnect. [This](https://developer.apple.com/library/content/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING) note states: 

> Dynamic libraries outside of a framework bundle, which typically have the file extension .dylib, are not supported on iOS, watchOS, or tvOS, except for the system Swift libraries provided by Xcode.

It suggests to wrap the `.dylib` into a `.framework`, but I wasn't able to, because there are no example neither in TDLib repo, nor in Apple docs. In the end, the only working solution I came up with was building the TDLib with custom script from [here](https://github.com/tdlib/td/issues/38#issuecomment-371464892)  and combining the static `.a` (not .dylibs) libraries and headers into a framework. 

Could you please provide an example of a working Xcode project or a guide of how to set it up after a successful compilation? Though I have already solved my problem with 3rd party solutions, a more detailed documentation would be helpful for other users.

**Comment by levlam** [comment]
Thanks to @Kylmakalle, [example/ios](https://github.com/tdlib/td/tree/master/example/ios) now creates a fully-featured XCFramework, which shouldn't be affected by these issues.
