### ISSUE TITLE
unable to get content for MessageUnsupported

### ISSUE THREAD

**Issue by eugeneRover** [tdlib/td#2661]
Question is how get content for `MessageUnsupported` (I use latest build of tdlib - 1.8.20).

Once it was received (via `UpdateMessageContent`) after `GetChatHistory` call, but at next program launch when I call `GetChatHistory`, it receives the same `MessageUnsupported` again, but no any `UpdateMessageContent`.

I know, `tdlib` utilizes local DB, maybe updated content of the message is stored in that DB ?
I tried `GetMessageLocally` and `ViewMessages` (with different sources) calls, but still not result (no content, and no updates).

**Comment by micl2e2** [comment]
Similar issues here. 

Also found out that all quoted messages, or similar messages carrying any feature introduced by [latest release](https://telegram.org/blog/reply-revolution), will all be categorized into `messageUnsupported`. Updating TDLib to latest version does not help.

Does TDLib plan to support those new features in subsequent releases?

**Comment by Vadis00** [comment]
The answer is here - https://github.com/tdlib/td/issues/2657#issuecomment-1789638698

**Comment by micl2e2** [comment]
@Vadis00 Thanks!

**Comment by eugeneRover** [comment]
After release 1.8.21, messages are being received OK, no `MessageUnsupported`
