### ISSUE TITLE
Cmake error (Note: Recompile with -Xlint:unchecked for details.)

### ISSUE THREAD

**Issue by culexjj** [tdlib/td#2663]
Hello,

I'm following the notes for building TDLIB for Java & windows.

On the last cmake command (after, _cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) .._ )

**cmake --build . --target install --config Release**

I get one error and i'd like to ask how to fix it or if I can continue anyway 

PS D:\TDLib\td\example\java\build> cmake --build . --target install --config Release
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  1>Checking Build System
  Generating Java TDLib API source files
  Write file D:/TDLib/td/example/java/org/drinkless/tdlib/TdApi.java
  Building Custom Rule D:/TDLib/td/example/java/CMakeLists.txt
  Building Java code
  D:\TDLib\td\example\java\org\drinkless\tdlib\example\Example.java:306: error: incompatible types: Ok cannot be converted to Error
          if (Client.execute(new TdApi.SetLogStream(new TdApi.LogStreamFile("tdlib.log", 1 << 27, false))) instanceof TdApi.Error) {
                            ^
  Note: D:\TDLib\td\example\java\org\drinkless\tdlib\Client.java uses unchecked or unsafe operations.
  Note: Recompile with -Xlint:unchecked for details.
  **1 error
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: Custom build for 'D:\TDLib\td\example\java\build\CMakeFiles\c245905e49752fb61022f5298b7f86ab\build_java.rule;D:\TDLib\td\example\java\CMa
keLists.txt' exited with code 1. [D:\TDLib\td\example\java\build\build_java.vcxproj]**
  Generating Javadoc documentation
  Loading source files for package org.drinkless.tdlib...
  Constructing Javadoc information...
  Creating destination directory: "D:/TDLib/td/tdlib/bin/../docs\"
  Building index for all the packages and classes...

Thank you very much

**Comment by levlam** [comment]
The Java example was broken in the last commit. This was fixed in TDLib 1.8.21, which will be released soon. For now, I would recommend to revert the last master commit and build the example without it.

**Comment by aaalzya** [comment]
محمد الحمامي

في السبت، 4 نونبر 2023 9:19 م Aliaksei Levin ***@***.***> كتب:

**Comment by culexjj** [comment]
> The Java example was broken in the last commit. This was fixed in TDLib 1.8.21, which will be released soon. For now, I would recommend to revert the last master commit and build the example without it.

First, thanks for your reply Levlam

I'm a student and to be honest, I have almost not experience using Git. Do you mean, revert to this one?

_D:\TDLib\td>git log
commit dd77e4628f1a65f332f0cb81c82a19c0fcfa40c2 (HEAD -> master, origin/master, origin/HEAD)
Author: Vyacheslav <6242627+vkryl@users.noreply.github.com>
Date:   Wed Oct 25 00:52:34 2023 +0600_

if yes, should I use this command? --> git revert HEAD

And finally, after doing this, should I redo all steps on ' https://tdlib.github.io/td/build.html?language=Java' ?

Thank you very much

**Comment by levlam** [comment]
> if yes, should I use this command? --> git revert HEAD

Yes. After this the example will build without issues.

**Comment by culexjj** [comment]
it seems ok now 

**PS D:\TDLib\td\example\java\build> cmake --build . --target install --config Release
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  1>Checking Build System
  Generating Java TDLib API source files
  Building Custom Rule D:/TDLib/td/example/java/CMakeLists.txt
  Building Java code
  Building Custom Rule D:/TDLib/td/example/java/CMakeLists.txt
  Generating Javadoc documentation
  Loading source files for package org.drinkless.tdlib...
  Constructing Javadoc information...
  Building index for all the packages and classes...
  Standard Doclet version 20.0.2+9-78
  Building tree for all the packages and classes...
  Generating D:\TDLib\td\tdlib\bin\..\docs\org\drinkless\tdlib\Client.html...**
  

Thank you very much
