### ISSUE TITLE
Serializing objects from Td::TdStatic

### ISSUE THREAD

**Issue by Davidster** [tdlib/td#2664]
Hello! I am using the Td::TdStatic API from c++ and I would like to load the full history of a chat and save the results to a file. 

I was hoping to be able to convert the vector of message objects I receive to a JSON string which I can just write to disk. I noticed that there is a [JsonBuilder](https://github.com/tdlib/td/blob/dd77e4628f1a65f332f0cb81c82a19c0fcfa40c2/tdutils/td/utils/JsonBuilder.cpp) utility that exists in the project but it doesn't seem to be exposed by the library. I don't want to have to switch to the JSON-only API just for this one purpose. Is there a way I can accomplish this?

**Comment by levlam** [comment]
There is no..
