### ISSUE TITLE
Slow initial response from getChatHistory 

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2668]
## Issue Description:
I am using TDLib 1.8.20 with the tdweb wrapper, aiming to retrieve messages from a chat, specifically around the `chat.last_read_inbox_message_id`. I've set `offset = -5` and `limit = 10`. The issue I'm encountering is that the initial call to `getChatHistory` for a `chat_id` is unexpectedly slow, taking anywhere from 0.5 to 4 seconds, regardless of the limit size (either 1 or 100). Subsequent calls to `getChatHistory` for the same `chat_id`, adjusted with the `from_message_id`, perform significantly faster, within 0.01 to 0.2 seconds.

It appears that a "first slow call" is a prerequisite for obtaining quicker responses on later calls for a certain Chat. Prefetching `chat.last_read_inbox_message_id` with `getMessage` did not speed up the `getChatHistory` response. However, a preliminary call to `getChatHistory` with `limit = 1` does result in a faster follow-up call, but this initial call (with `limit = 1`) still suffers from the same slow response time.

For context, I execute `openChat` and `getChat` before `getChatHistory` for any given `chat_id`. This pattern of a slow initial response is also observed with the `searchMessages` method, where the first call takes a long time, but subsequent calls are quick.

## Question:
If I want the user to see messages from a Chat surrounding the first unread message (`chat.last_read_inbox_message_id`) as fast as possible, what should I do?

Thank you for your continuous efforts and contributions to the project!

**Comment by levlam** [comment]
There should be bo difference. Could you send TDLib log with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by teleothleo** [comment]
@levlam done!

**Comment by pypy11** [comment]
> ## Vấn đề mô tả:
> Tôi đang sử dụng TDLib 1.8.20 với trình bao bọc tdweb, nhắm truy xuất tin nhắn từ một cuộc trò chuyện, đặc biệt là xung quanh `chat.last_read_inbox_message_id`. Tôi đã thiết lập `offset = -5`và `limit = 10`. Vấn đề tôi gặp phải là cuộc gọi đầu tiên tới `getChatHistory`một trạng thái `chat_id`chậm bất ngờ, mất từ ​​​​0,5 đến 4 giây, không kể giới hạn kích thước (1 hoặc 100). Các lệnh gọi tiếp theo `getChatHistory`tương tự `chat_id`, được điều chỉnh bằng `from_message_id`, thực hiện nhanh hơn đáng kể, trong vòng 0,01 đến 0,2 giây.
> 
> Có vẻ như "cuộc gọi chậm đầu tiên" là điều kiện tiên quyết để nhận được phản hồi nhanh hơn trong các cuộc gọi sau cho một câu chuyện nhất định. Load `chat.last_read_inbox_message_id`trước đó `getMessage`không tăng tốc độ `getChatHistory`phản hồi. Tuy nhiên, cuộc gọi sơ bộ tới `getChatHistory`sẽ `limit = 1`dẫn đến cuộc gọi tiếp theo nhanh hơn, nhưng cuộc gọi ban đầu này (với `limit = 1`) vẫn gặp phải tình trạng thời gian phản hồi tương tự chậm.
> 
> Đối với bối cảnh, tôi thực thi `openChat`và `getChat`trước `getChatHistory`cho bất kỳ tệp nào `chat_id`. Kiểu phản hồi ban đầu chậm này cũng được quan sát bằng `searchMessages`phương pháp này, trong đó cuộc gọi đầu tiên mất nhiều thời gian nhưng các cuộc gọi tiếp theo sẽ nhanh chóng.
> 
> ## Câu hỏi:
> Nếu tôi muốn người dùng xem tin nhắn từ Trò chuyện xung quanh tin nhắn chưa đọc đầu tiên ( `chat.last_read_inbox_message_id`) nhanh nhất có thể thì tôi phải làm sao?
> 
> Cảm ơn các bạn đã nỗ lực và đóng góp không ngừng cho dự án!

Xong

**Comment by teleothleo** [comment]
In my case it turned out that TDLib (tdweb in browser) itself worked much slower because of the turned on logs + opened console.  Turning off logs helped a lot, but to to fully achieve the desired speed, you have to turn off the console as well.
