### ISSUE TITLE
The purpose of `only_local = true` for `getChatHistory`

### ISSUE THREAD

**Issue by teleothleo** [tdlib/td#2669]
And a follow-up about `getChatHistory`. I've noticed that if the messages were fetched and saved in the database, it does not really matter in terms of speed whether I set `only_local = true` of `only_local = false` for `getChatHistory`. The response time of a tdweb 1.8.20 inside a React project is consistently from 0.01 to 0.03 seconds for messages that are cached. Even if I shutdown the network, the `getChatHistory` with `only_local = false` still works with the same speed. 
So I am curious, for which purposes does `only_local = true` option exist?

**Comment by levlam** [comment]
When a chat is opened, it is better to show messages immediately without progress animation. The correct approach for this is to call `getChatHistory`, wait a short time for response, and if it isn't returned fast enough, then show progress animation.
An alternative "lazy" approach is to call `getChatHistory` with `only_local==true`, wait for response expecting it to be fast enough, and show progress animation only if the response failed to return enough messages.

**Comment by teleothleo** [comment]
@levlam Gotcha! Thank you!
