### ISSUE TITLE
Turn off logs

### ISSUE THREAD

**Issue by puryanms** [tdlib/td#267]
Hi dear
how can i turn off Telegram-bot logs after login.they got a lot of cpu,i want to get less than cpu.
thanks

**Comment by levlam** [comment]
If you ask about tdbot, it has `-v/--verbosity` parameter. TDLib itself provides td_set_log_verbosity_level function for changing log verbosity level.

**Comment by puryanms** [comment]
yes im asking about tdbot.

Where exactly should I edit to turn off the logs?

**Comment by puryanms** [comment]
i mean this logs 
https://i.imgur.com/jete7s4.png

**Comment by levlam** [comment]
It is not a log, it is an stdin/stdout interface. You need to comment lines 364-365 there: https://github.com/vysheng/tdbot/blob/a838e8768f1c405306975763d59d48ca9f347805/cliclient.cpp#L364
to get rid of it.

**Comment by puryanms** [comment]
thanks
I use accounts full of groups.
Is there any other way to use less RAM and CPUs?

**Comment by levlam** [comment]
Likely, no.
