### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by CMfengbuzhi** [tdlib/td#2670]
I am using tdlib json. The account only logs in to receive messages and does not perform any other operations. The memory will continue to grow. I suspect there may be a cache, but how do I clean them up? When there are too many account messages, the program will run out of computer memory and crash in just a few dozen hours

**Comment by levlam** [comment]
If you enabled message databases, then messages can be unloaded from memory.

Also, you can always close a TDLib instance and reopen it.

**Comment by CMfengbuzhi** [comment]
I have used a database. How can I uninstall it and which API is it using?

**Comment by levlam** [comment]
See the method `setTdlibParameters`.

**Comment by CMfengbuzhi** [comment]
Okay, I'll give it a try

**Comment by CMfengbuzhi** [comment]
In the setTdlibParameters function, use_ Message_ The database parameter is set to false, but memory is still growing rapidly

**Comment by levlam** [comment]
If you don't use the message database, then messages can't be unloaded from memory.

**Comment by CMfengbuzhi** [comment]
So how do I unload messages from memory while using message dbdata?

**Comment by levlam** [comment]
This is done automatically.

**Comment by jcai** [comment]
> This is done automatically.


So how do I unload messages from memory while  **not** using message database?

**Comment by levlam** [comment]
By closing TDLib instance.
