### ISSUE TITLE
TextEntityTypeInput not working

### ISSUE THREAD

**Issue by lyna-kim** [tdlib/td#2677]
we would like to mention a bot and execute bot command in private chats but it doesn't work. we tested in Telegram app it works and render correctly. in our code it's just display the bot command itself.

what we tried: textEntityTypeMention, textEntityTypeMentionName, textEntityTypeBotCommand

<img width="425" alt="Screenshot 2023-11-13 at 5 34 46 in the afternoon" src="https://github.com/tdlib/td/assets/50472907/950b370e-64f6-4eea-bac0-4008e5f9c628">

<img width="662" alt="Screenshot 2023-11-13 at 5 37 26 in the afternoon" src="https://github.com/tdlib/td/assets/50472907/24b4e2bb-74e1-4449-8b86-16b9b970d5c7">

![telegram-cloud-photo-size-5-6237912601682098306-y](https://github.com/tdlib/td/assets/50472907/2f5b334e-2d89-441f-983e-bde42a167ef3)

**Comment by lyna-kim** [comment]
![Uploading Screenshot 2023-11-13 at 5.34.46 in the afternoon.png…]()

**Comment by levlam** [comment]
How do you want to mention a bot?

**Comment by lyna-kim** [comment]
Hi @levlam, Thank you for your reply.

**Comment by lyna-kim** [comment]
We would like to execute a bot command in current private chat.

**Comment by levlam** [comment]
See `inputMessageText` documentation:
https://github.com/tdlib/td/blob/6ee64289f3666774fb694c9d33f83ed8bd52b60c/td/generate/scheme/td_api.tl#L3009-L3013.
