### ISSUE TITLE
TdApi.UpdateSupergroup 

### ISSUE THREAD

**Issue by akulik512** [tdlib/td#2678]
Hello :wave: 
I have a question about the `TdApi.UpdateSupergroup` update.
I send the `new TdApi.SearchPublicChat(channelName)` request to get a channel and start listening  the `TdApi.UpdateSupergroup` update to get member count. 
But there is an interesting thing I noticed if I send the `new TdApi.SearchPublicChat(channelName)` to get same channel again I didn't get any `TdApi.UpdateSupergroup` updates. It makes sense because channel was already found but is there a way to get such updates one more time?

**Comment by levlam** [comment]
There is no. Updates must be handled as described in https://core.telegram.org/tdlib/getting-started#handling-updates.
