### ISSUE TITLE
How do I read a message in a topic?

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2681]
I received a message in the topic. I know their messages id. I use
request `viewMessages`. Messages are not marked as read. What do I need to do additionally for this?

**Comment by levlam** [comment]
If you pass proper `source` to `viewMessages`, then messages in the topic will be read. Only updates about message being read in a topic aren't implemented yet.

**Comment by fat-complex** [comment]
@levlam Thank you. Are there any plans to finalize forums and topics? I mean updates for them. And then sometimes you have to make a bunch of requests to have topics up to date.

**Comment by levlam** [comment]
Support for topics will be completed whenever there will be time for this.

**Comment by fat-complex** [comment]
Thanks) It work me
