### ISSUE TITLE
uploadFile error

### ISSUE THREAD

**Issue by xucoanthony** [tdlib/td#2683]
I can call any other tdlib_json request through the method td_send, why not the uploadFile request? Is there something wrong with my query format? Thx..

b'{"@type": "uploadFile", "file": {"@type": "inputFileRemote", "id": "BAACAgUAAx0Cc21izgACVBNlVK0Y2YmUVDz56ul4UbE0QM2qhQACmgoAAkooOFRMCCO9XZJLbzAE"}, "file_type": {"@type": "fileTypeVideo"}, "priority": 32}'

**[ 20:57:47 ]  {"@type": "error", "code": 400, "message": "Failed to parse JSON object as TDLib request: Unknown class \"uploadFile\"", "@client_id": 1}**

```
def td_send(client_id, query):
    query = json.dumps(query).encode('utf-8')
    _td_send(client_id, query)

query = {
        "@type":"uploadFile",
        "file":{
            "@type":"inputFileRemote",
            "id":remote_file_id
        },
        "file_type":{
            "@type":"fileTypeVideo"
        },
        "priority":32
    }


td_send(1,query)
```

**Comment by xucoanthony** [comment]
on tdlib darwin arm64

**Comment by levlam** [comment]
There is no method `uploadFile` anymore. It was renamed to `preliminaryUploadFile` to emphasize that it doesn't create a persistent file and almost never needed by real apps.

**Comment by levlam** [comment]
TDLib API changes in every release, so you need to check documentation for the used TDLib version, which can be found in the file https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl for the latest version.
