### ISSUE TITLE
Difference between telegram API layers

### ISSUE THREAD

**Issue by Syslic** [tdlib/td#2688]
In Telegram API

In td_lib used 165 layer, in file [MtprotoHeader.cpp](https://github.com/tdlib/td/blob/ec788c7505c4f2b31b59743d2f4f97d6fdcba451/td/telegram/net/MtprotoHeader.cpp) used old object [initConnection#785188b8](https://github.com/tdlib/td/blob/ec788c7505c4f2b31b59743d2f4f97d6fdcba451/td/telegram/net/MtprotoHeader.cpp#L36C1-L36C1)
In [telegram_api.tl](https://github.com/tdlib/td/blob/ec788c7505c4f2b31b59743d2f4f97d6fdcba451/td/generate/scheme/telegram_api.tl) used different object,[ initConnection#c1cd5ea9](https://github.com/tdlib/td/blob/ec788c7505c4f2b31b59743d2f4f97d6fdcba451/td/generate/scheme/telegram_api.tl#L1625).
Сould this difference lead to bans, or some other issues?

**Comment by levlam** [comment]
No, this can't affect anything.
