### ISSUE TITLE
tg_cli usage

### ISSUE THREAD

**Issue by panda2048** [tdlib/td#269]
I just got the lib built and I found that there is a tg_cli 
So I plan to use it to test the telegram API ID and hash
However, after starting, and I type command "GetChats" and got "Unauthorised" message

What is possible missing in the setup?
Thanks

[ 3][t 0][1527956843.427442074][cli.cpp:967][!CliClient]	CMD:[GetChats]
[ 3][t 0][1527956843.427522182][Td.cpp:3933][!Td][&td_requests]	Receive request 5: getChats {
  offset_order = 9223372036854775807
  offset_chat_id = 0
  limit = 10000
}

[ 3][t 0][1527956843.427546978][Td.cpp:4663][!Td][&td_requests]	Sending error for request 5: error { code = 401 message = "Unauthorized" }
[ 3][t 0][1527956843.427561998][cli.cpp:560][!Td]	on_error [id=5] error {
  code = 401
  message = "Unauthorized"
}

**Comment by SadDarkAngel** [comment]
Can u provide more examples of commands? The third day I study cli.cpp and I can't figure out how to send a message with a chat id and a message text

**Comment by levlam** [comment]
@SadDarkAngel No. `tg_cli` is a utility for TDLib testing and it should not be used for anything besides that. For everything else TDLib must be used directly. If you really want to call a TDLib method from `tg_cli`, you can find the corresponding command in the [source code](https://github.com/tdlib/td/blob/master/td/telegram/cli.cpp).
