### ISSUE TITLE
Slow connection recovery on the change of the default route

### ISSUE THREAD

**Issue by azhuchkov** [tdlib/td#2690]
In case of creating VPN tunnel message delivery may be delayed up to 2 min. The same after VPN shutting down.
It would be helpful to have some control on watchdog timer that validates TCP session is still alive.

**Comment by levlam** [comment]
You must set "online" option to true whenever the user is online to have fast connection recovery when the user is online.

**Comment by azhuchkov** [comment]
Did you mean that I should set this status periodically? I tried to set it once before login. User status is shown as online, but message processing is still delayed for more than a minute.

**Comment by levlam** [comment]
If the user is online, then all delays are reduced to a bare minimum. If the user is offline, then resource usage is preferred. 

Also, if you somehow know the exact time when default route changes, you can call `setNetworkType` right after this for immediate recovery.
