### ISSUE TITLE
Incoming messages doesn't appear on tdlib unless I click to it on real Telegram client

### ISSUE THREAD

**Issue by ne0c0de** [tdlib/td#2695]
Hi

I have a very strange problem on past few days.

The messages that incoming to channels/groups which has more then 60k followers is not coming to tdlib client unless if I click on that channel.group name on real telegram client (mobile/desktop)

It looks very strange because I didn't have any problem like this in since 3 years.

Is there any new limitation on Telegram side that anyone knows?

**Comment by levlam** [comment]
Messages in big chats aren't expected to be received in real time, but if the user has the chat opened, then they are expected to be received faster. In TDLib you can open a chat using `openChat`, but don't forget to call `closeChat` when the chat is closed. Usually, users have at most one chat opened.

**Comment by FordSmh** [comment]
Have the same issue on much smaller channels

**Comment by AktilaCengiz** [comment]
How can i use openChat event with node.js tdl package ?
