### ISSUE TITLE
Is there an implementation for retrieving media and attachments count in channels/supergroups?

### ISSUE THREAD

**Issue by seanvelasco** [tdlib/td#2697]
I couldn't find any documentation for retrieving the count or number of media files and attachments in a channel.

There is `member_count` for `getSupergroup`, but there exists no member for media count, links count, or files count.

However, previewing a channel on https://t.me/s/channel, the site seems to able to display the above missing counts:

<img width="313" alt="image" src="https://github.com/tdlib/td/assets/67859044/54ea75a0-7d38-44d0-994c-37fdff25969d">
 
 Perhaps this is unspecced?

**Comment by levlam** [comment]
You need to use the method `getChatMessageCount` for this.

**Comment by seanvelasco** [comment]
that was it - thank you very much!

example usage for getting links count:

```javascript
{
    "@type": "getChatMessageCount",
    chat_id: -1001123464890,
    filter: {
        "@type": "searchMessagesFilterUrl"
    }
}
```
