### ISSUE TITLE
Account prohibited when using Tdlib

### ISSUE THREAD

**Issue by Wabash-spring** [tdlib/td#2698]
Recently, when logging in with a new account using tdlib, there is a phenomenon of withdrawal from that account. In addition, you will be withdrawn when you log in with an existing account, not a new one. Do you happen to know about any related documents or issues?
And if there is any improvement or solution, please let me know

**Comment by levlam** [comment]
This behavior is up to the server and isn't directly related to TDLib. It blocks all non-bot accounts with suspicious activity, which don't look like real users.

**Comment by Wabash-spring** [comment]
> This behavior is up to the server and isn't directly related to TDLib. It blocks all non-bot accounts with suspicious activity, which don't look like real users.

It was blocked only by client login using tdlib, not suspicious behavior. Does it affect the tdlib version?

**Comment by levlam** [comment]
It is not directly related to app version. Not doing anything after logging in is also an action, ordinary apps do.

**Comment by dafsas3** [comment]
I encountered the same problem... Did you solve it?
