### ISSUE TITLE
Help for java

### ISSUE THREAD

**Issue by SayedSadat** [tdlib/td#270]
anyone have compiled version and example for java?

i'm new in java :(

**Comment by levlam** [comment]
What have you tried and what problems do you have?

**Comment by SayedSadat** [comment]
compile error 
```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/tdcore.dir/build.make:326: recipe for target 'CMakeFiles/tdcore.dir/td/telegram/AnimationsManager.cpp.o' failed
make[2]: *** [CMakeFiles/tdcore.dir/td/telegram/AnimationsManager.cpp.o] Error 4
CMakeFiles/Makefile2:274: recipe for target 'CMakeFiles/tdcore.dir/all' failed
make[1]: *** [CMakeFiles/tdcore.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by levlam** [comment]
You have not enough RAM to compile using GCC. You can use clang instead, which need less than 2 GB.

**Comment by rickpickles** [comment]
Guys, can u compile java tdlib version? I have problems too... Two days of googling is killing me

**Comment by levlam** [comment]
@rickpickles What problems do you have?

**Comment by rickpickles** [comment]
@levlam im complete new in cmake, and after two days i give up, Why library for java need cmake or something for use?

**Comment by levlam** [comment]
@rickpickles You are not supposed to know how to use cmake, all required commands are written in README. For which OS do you try to compile TDLib? Do you have some problems not covered in README?

**Comment by rickpickles** [comment]
@levlam Я никогда раньше не сталкивался с подобным способом сборки, на windows based машинах если следую readme получаю:
E:\sources\td>cd jnibuild

E:\sources\td\jnibuild>cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON
CMake Error: The source directory "E:/sources/td/jnibuild" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

E:\sources\td\jnibuild>cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=E:\sources\td
CMake Error: The source directory "E:/sources/td/jnibuild" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

E:\sources\td\jnibuild>cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=E:\sources\td\CMakeLists.txt
CMake Error: The source directory "E:/sources/td/jnibuild" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

E:\sources\td\jnibuild>

**Comment by levlam** [comment]
You should use exactly the line from README.md:
```
cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..
```
All your attempts miss `..` in the end and don't specify correct CMAKE_INSTALL_PREFIX.

**Comment by rickpickles** [comment]
@levlam i think im stupid fot that lol. My steps for build
1) i get sources by downloading zip
2) i have path for sources E:\sources\td: ![image](https://user-images.githubusercontent.com/36510673/41098946-a8b93a9a-6a65-11e8-9857-33509a861b61.png)
3) im in this path in "jnibuild" folder
4) im trying to use cmd
E:\sources\td>cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..
CMake Error: The current CMakeCache.txt directory E:/sources/td/CMakeCache.txt is different than the directory e:/telega/td where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source directory "E:/sources" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by rickpickles** [comment]
@levlam 
im trying again. Can u make a complete lib for code monkeys like me? XD
E:\sources\td\>cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..
-- Building for: NMake Makefiles
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "E:/sources/td/CMakeFiles/CMakeOutput.log".
See also "E:/sources/td/CMakeFiles/CMakeError.log".

**Comment by levlam** [comment]
You need to run `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat` before invoking `cmake` as it suggests.
