### ISSUE TITLE
Creating a folder from a contact for which there is no chat

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2700]
I'm trying to create a folder and put there a contact with whom I don't have a chat. But tdlib says it's a mistake. What should I add to the CreateChatFolder request?

**Comment by levlam** [comment]
First, you need to create a chat with the user using `createPrivateChat`.

**Comment by fat-complex** [comment]
I tried to create a private chat for the user. It was created, then I put it in the `included_chat_ids_` field. I make a `createChatFolder` request and get this message: _Chat is not in the chat list_.  As a result, the folder was not created(.

**Comment by levlam** [comment]
You must ensure that the chat in a chat list first. Private chats must be non-empty for this.

**Comment by fat-complex** [comment]
It turns out that it is impossible to create a folder for contacts that I have and for which there are no chats, as in ios?

**Comment by levlam** [comment]
If chat isn't in the main or archive chat lsit, then it is not supposed to be shown in other folders.

**Comment by fat-complex** [comment]
Yes, thank you, I understood that. When you create a folder for such a case in iOS, these contacts do not appear on the main folder. But when you go to the folder settings and open this folder, contacts for which there are no chats are displayed there. Is there any way to do this using stdlib?
