### ISSUE TITLE
openssl build error and no dll found for net or even json dll 

### ISSUE THREAD

**Issue by amirjcr** [tdlib/td#2701]
Hi I'm new to Telegram Database Library So I use  [Tdlib_Build_Insttraction](https://tdlib.github.io/td/build.html?language=C%23)
I face this error while building lib
![Screenshot 2023-11-27 215707](https://github.com/tdlib/td/assets/51033271/4b658aca-5884-4746-919d-f6dbed7bf6a2)

![Screenshot 2023-11-27 215913](https://github.com/tdlib/td/assets/51033271/a5b0460d-f4c3-4e5e-a78f-159ba3f11594)

![Screenshot 2023-11-27 215933](https://github.com/tdlib/td/assets/51033271/d71f19e9-722b-4c59-b7eb-f472d2b1decc)

and commands run after the error how I could solve this error and  build dll files

**Comment by levlam** [comment]
You need to remove the `tools/nasm` directory manually as suggested in https://github.com/microsoft/vcpkg/issues/35123.

**Comment by amirjcr** [comment]
> You need to remove the `tools/nasm` directory manually as suggested in [microsoft/vcpkg#35123](https://github.com/microsoft/vcpkg/issues/35123).

it's worked thanks a lot for your help

**Comment by Tagman** [comment]
Sorry to revive this old thread. Is deleting this tool manually the only way to fix this?

I have builds running on a CI/CD pipeline. So deleting the failing tools every time is a no-go.

**Comment by levlam** [comment]
@Tagman You can't have this issue if install the package from scratch as happens in CI/CD.

**Comment by Tagman** [comment]
> @Tagman You can't have this issue if install the package from scratch as happens in CI/CD.

It is building the port from scratch. But the vcpkg/tools directory is persistent on the build agents. 
Deleting the directory once fixed it for now. But it seems this might be an issue with vcpkg and the specific tool it downloaded.
