### ISSUE TITLE
About whether the document has errors

### ISSUE THREAD

**Issue by CoCoMNT** [tdlib/td#2702]
hi sir
       https://github.com/tdlib/td/blob/404761c525d933df813702c863828058cd26111a/td/generate/scheme/td_api.tl#L3947
      //@`param_description` A short description of the result
       https://github.com/tdlib/td/blob/404761c525d933df813702c863828058cd26111a/td/generate/scheme/td_api.tl#L3953
       i**nputInlineQueryResultArticle id:string url:string hide_url:Bool title:string `description:string` thumbnail_url:string thumbnail_width:int32 thumbnail_height:int32 reply_markup:ReplyMarkup input_message_content:InputMessageContent = InputInlineQueryResult;**
There seems to be a difference between the places I marked and the documentation notes

**Comment by levlam** [comment]
"@param_description" is used to document a parameter with name "description". "param_" is required, because "@description" contains description for the class itself.
