### ISSUE TITLE
download STOP when multiple getfile request send?

### ISSUE THREAD

**Issue by jnxyatmjx** [tdlib/td#2705]
![image](https://github.com/tdlib/td/assets/9018335/8be9f57f-6529-4e73-bc03-c68dd317b942)
when i simultaneously  send getfile request (about 10 request in 1 second)？why the part download processer stop work？

**Comment by jnxyatmjx** [comment]
i use the telegram-bot-api as the local server

**Comment by jnxyatmjx** [comment]
> Currently, to allow at least some files to be downloaded when too many simultaneous `getFile` requests are sent, the files for which `getFile` was called last are downloaded first.

thanks，got it

**Comment by jnxyatmjx** [comment]
> > Currently, to allow at least some files to be downloaded when too many simultaneous `getFile` requests are sent, the files for which `getFile` was called last are downloaded first.
> 
> thanks，got it



> Currently, to allow at least some files to be downloaded when too many simultaneous `getFile` requests are sent, the files for which `getFile` was called last are downloaded first.

Could you tell me the maximum limites amount of send messages simultaneous？

**Comment by levlam** [comment]
https://core.telegram.org/bots/faq#broadcasting-to-users
