### ISSUE TITLE
Need admin access to my group

### ISSUE THREAD

**Issue by Natalia-Fominykh** [tdlib/td#2706]
Hi, I am an admin of this channel https://t.me/katiaharmony77 There is a group connected to this channel, can you make me admin of that group as well please? The previous admin left the channel and forgot to make me an admin of the group

**Comment by Natalia-Fominykh** [comment]
> No, there is no way to do this.

It's just admin rights, can someone help me, do you know?

**Comment by levlam** [comment]
Likely, no.

**Comment by Natalia-Fominykh** [comment]
> Likely, noone.

is it possible to delete group completely (but keep the channel)

**Comment by Natalia-Fominykh** [comment]
> The group and the channel can be deleted independently by their owners. Administrators of the channel with `can_change_info` administrator right can link it with another group. For this there is no need to delete the old group.

thank you so much for your responses Aliaksei!! The problem is that in that in the old group there is no control on the messages right now and a number of participants are writing a lot of spam and bad things about previous owner, that's why I need to delete that group - so they cannot write dirty things anymore. And then I will create a new group and connect it to the channel
