### ISSUE TITLE
Active sessions per device/ip adress

### ISSUE THREAD

**Issue by OleksiyMoroz** [tdlib/td#271]
Hello! 
How many active sessions can be running on one device or web server using tdlib? I heard about limit in 50 but not sure

**Comment by levlam** [comment]
There is no explicit limit. In the Bot API each `TDLib` instance handles more than 21000 active bots simultaneously.

**Comment by OleksiyMoroz** [comment]
@levlam so I can login unlimited numbers using for example one telegram client and created sessions will work stable without flood error on my ip address?

**Comment by levlam** [comment]
That depends on many things. Likely, yes.

**Comment by OleksiyMoroz** [comment]
@levlam Thank you
