### ISSUE TITLE
GetCallbackQueryAnswer could be fast?

### ISSUE THREAD

**Issue by FunkyYang** [tdlib/td#2710]
some groups call ```GetCallbackQueryAnswer``` and response slowly.How can I use it asynchronous?

**Comment by levlam** [comment]
Primary TDLib interface is asynchronous and most methods can be called only asynchronously. What exactly do you mean?

**Comment by FunkyYang** [comment]
I need get reponse which come from bot.

**Comment by FunkyYang** [comment]
I need get reponse which come from bot.that is synchronous

**Comment by levlam** [comment]
It is not possible to receive the response synchronously.

**Comment by FunkyYang** [comment]
```

// Sends a callback query to a bot and returns an answer. Returns an error with code 502 if the bot fails to answer the query before the query timeout expires
func (client *Client) GetCallbackQueryAnswer(req *GetCallbackQueryAnswerRequest) (*CallbackQueryAnswer, error) {
	result, err := client.Send(Request{
		meta: meta{
			Type: "getCallbackQueryAnswer",
		},
		Data: map[string]interface{}{
			"chat_id":    req.ChatId,
			"message_id": req.MessageId,
			"payload":    req.Payload,
		},
	})
	if err != nil {
		return nil, err
	}

	if result.Type == "error" {
		return nil, buildResponseError(result.Data)
	}

	return UnmarshalCallbackQueryAnswer(result.Data)
}
```
this is a library which I use to connect telegram. and that indicate must receive response from server before 60s timeout.this is a synchronously?
