### ISSUE TITLE
Could not find module 'tdjson.dll'

### ISSUE THREAD

**Issue by Tarvitan** [tdlib/td#2711]
I tried to run "tdjson_example.py" but it could not find tdjson.dll or tdjson. I tried to resolve this issue with a method i found previously? but it didnt help:
![Снимок](https://github.com/tdlib/td/assets/62933936/92dc581e-a440-4447-869d-03d9911794bd)
As a different error would pop up: 
Exception has occurred: NameError
name 'os' is not defined
I also tried to put the tdjson.dll directly into the same folder as tdjson_example.py, yet it still didnt work.

**Comment by kLETKA123** [comment]
![Снимо3к](https://github.com/tdlib/td/assets/62933936/531737d1-1c11-4f6e-aa67-dabc91ce72ae)

**Comment by kLETKA123** [comment]
I also just tried putting the whole tdlib folder into the same folder that tdjson_example.py was, but it still didnt work

**Comment by levlam** [comment]
You must copy all dependent library, i.e. all DLLs alongside `tdjson.dll`. There should be no more `libcrypto-1_1-x64.dll` in the build directory if you followed the latest build instructions, but there should be `libcrypto-3-x64.dll`.

**Comment by Tarvitan** [comment]
So all DLL's from tdlib or just all DLL files from the whole td folder?

**Comment by Tarvitan** [comment]
![Снимок](https://github.com/tdlib/td/assets/62933936/af4a44ea-3ba1-41fc-9cb9-18cd14e50bfe)
Also how does it still not see it

**Comment by Tarvitan** [comment]
![Снимок](https://github.com/tdlib/td/assets/62933936/2a664ee4-9fc1-4b75-9357-0a0a363f3d89)
also how does it still not see it

**Comment by Tarvitan** [comment]
I also tried to open TD folder in VS Code. Still doesnt work

**Comment by Tarvitan** [comment]
> You must copy all dependent library, i.e. all DLLs alongside `tdjson.dll`. There should be no more `libcrypto-1_1-x64.dll` in the build directory if you followed the latest build instructions, but there should be `libcrypto-3-x64.dll`.

there is just the libcrypto-3-x64.dll's

**Comment by levlam** [comment]
> So all DLL's from tdlib or just all DLL files from the whole td folder?

All DLLs that were copied to `td/tdlib` directory alongside `tdjson.dll`. Actually, you have all of them on the screenshot, so the issue is different.

It looks like it is caused by changes in Python 3.8, described in https://docs.python.org/3/library/os.html#os.add_dll_directory. Specifyning full DLL path instead of "tdjson.dll", or adding `os.add_dll_directory(os.getcwd())` resolved the issue for me.

**Comment by Tarvitan** [comment]
Alright, I'll try that

**Comment by levlam** [comment]
I have pushed a fix for the Python example to always use `tdjson.dll` from the script's directory using its full path if it isn't found by `find_library`.

**Comment by Tarvitan** [comment]
Well it looks like that works
![Снимок](https://github.com/tdlib/td/assets/62933936/0c406d8f-4d5e-4481-8de1-2588453c3d83)
just pasting in the path worked

**Comment by Tarvitan** [comment]
yeah it works, but it creates an error:
Error "(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape"
But it can be fixed by just putting an r before the path
