### ISSUE TITLE
Can't import messages to telegram

### ISSUE THREAD

**Issue by MistakeHub** [tdlib/td#2714]
There is a problem. I try to put all messages, that were exported from telegram in json format. I use method in c# `Client.ImportMessagesAsync(chatid, new TdApi.InputFile.InputFileLocal() { Path=path });`, in path I indicate to generated json file. After that i get such exception  `TdLib.TdException: 'IMPORT_FORMAT_UNRECOGNIZED'`.

**Comment by levlam** [comment]
Import of messages exported from Telegram isn't supported server-side. Only other popular messenger apps are supported.
