### ISSUE TITLE
How to delete local chat history?

### ISSUE THREAD

**Issue by chenyu1990** [tdlib/td#2717]
like this
![how-to-delete-local-history](https://github.com/tdlib/td/assets/15179320/106f2d82-8f98-484e-babe-ca3575039aa1)

**Comment by levlam** [comment]
Use `deleteChatHistory`.

**Comment by chenyu1990** [comment]
`Deletes all messages in the chat. Use chat.can_be_deleted_only_for_self and chat.can_be_deleted_for_all_users fields to find whether and how the method can be applied to the chat`   
It seems that permission is required.   
And it’s not an offline request

**Comment by levlam** [comment]
It is exactly the method behind the "Clear history" menu option.

**Comment by Fahmedo** [comment]
Hi @levlam can you assign this task to me so I can update the documentation file with the method to be used in order to clear all chat history from locale history.

**Comment by levlam** [comment]
What do you mean?

**Comment by Godswil-Uche** [comment]
The Option in the Chat History Menu can solve this.

**Comment by Fahmedo** [comment]
I guess it would be great to update the documentation to include instructions on how to delete local chat history and also provide step-by-step instructions on how to perform the deletion

**Comment by chenyu1990** [comment]
> It is exactly the method behind the "Clear history" menu option.

it's not work...
got error:
`400 Can't delete history of chat -1001487844290 only for self`

**Comment by levlam** [comment]
This means that you can't clear history of the chat in any app: "use chat.can_be_deleted_only_for_self and chat.can_be_deleted_for_all_users fields to find whether and how the method can be applied to the chat."

**Comment by chenyu1990** [comment]
> This means that you can't clear history of the chat in any app: "use chat.can_be_deleted_only_for_self and chat.can_be_deleted_for_all_users fields to find whether and how the method can be applied to the chat."

so.
How to use this feature? deleteChatHistory can't do it.
![how-to-delete-local-history](https://github.com/tdlib/td/assets/15179320/106f2d82-8f98-484e-babe-ca3575039aa1)

**Comment by levlam** [comment]
It is impossible to delete history in non-owned public supergroups.
