### ISSUE TITLE
Using logging with via tdlib

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2719]
Is it possible to use your logging in my personal project? And if so, how?

**Comment by levlam** [comment]
In what project?

**Comment by fat-complex** [comment]
That's not how I put it. I saw inside your sources that you use logging written by you. Can I use it in my personal project, for example, with redirection to the file I need, and so on ?

**Comment by levlam** [comment]
You edited the question.

You need to use `tdutils` library if you want to use only the logging sybsystem without TDLib. `tdutils` can be used as a self-contained library by copying the whole directory.
