### ISSUE TITLE
Delay in getting msg from channel

### ISSUE THREAD

**Issue by panda2048** [tdlib/td#272]
I have encountered a problem with big delay in message from channel arriving to my app written with tdlib

It comes almost real-time in my test channel
But when it comes to a channel with 5000+ people, there is a delay from 30-60 sec

Is this an expected behavior? Any solution to this?
Thanks

**Comment by OleksiyMoroz** [comment]
@panda2048 I'm using another telegram client library, but have the same situation. 
Maybe it's server side delay and not depend on client. 
Just few tips, for better performance don't use indian numbers or virtual number, more updates incoming - bigger the delay

**Comment by panda2048** [comment]
@oleksiymoroz I was somehow opening the iOS version of telegram at the same time when I spot the issue
I would see the iOS tg Client is showing the message a lot earlier..that’s why I suspect it is a lib issue

For your tips, what is Indian number and virtual number are you referring to? Thx

**Comment by levlam** [comment]
It is an expected behavior. Updates to big channels are sent asynchronously. If a chat is opened in an ordinary client, then updates sometimes can be received faster, but this isn't guaranteed.

**Comment by OleksiyMoroz** [comment]
@levlam Can we found official documentation about the fact that you described?

**Comment by levlam** [comment]
There is no official documentation about that, but it is natural that pushing a lot of messages to their receivers can take some time.
