### ISSUE TITLE
Is it TDLib being stuck?

### ISSUE THREAD

**Issue by eztm** [tdlib/td#2720]
Hey! Appreciate some help as couple days ago we started to experience freezes in some accounts.

The flow is:
1) TDLib client is initiated
2) Starting to loadChats, sending and receiving messages
3) In couple minutes while there are still some movements happening in TDLib logs we dont get any new chats or messages.
4) Waiting any time for up to several hours
5) Trying to close client and not getting authorizationStateClosing and authorizationStateClosed updates
6) Trying to initiate client again and nothing happens

For now it is happening with some particular clients while others have no issues.
We did capture this behaviour with just one client and verbosity level 4 but not sure what exactly to look for.

**Comment by eztm** [comment]
From the logs it seems that TDLib keep sending updates but at some point "Begin to wait for updates with timeout" disappear.
This means it can be only external issue in our code or TDLib wrapper, something around calling `receive` right?

**Comment by levlam** [comment]
Yes, the cause of the issue isn't related to TDLib. I mentioned the most common reasons in the previous message.
