### ISSUE TITLE
Receiving API_ID_PUBLISHED_FLOOD message when running tdlib in JAVA

### ISSUE THREAD

**Issue by ToYashDeepSingh** [tdlib/td#2722]
I was able to successfully clone tdlib repository in my Ubuntu 20 system and build it using Java and run it in my terminal.
I wanted to run the project in IntelliJ IDE and was able to accomplish it.

After a day or so when I tried to run the code in IntelliJ again I got the following message:

```
/usr/lib/jvm/java-1.17.0-openjdk-amd64/bin/java -Djava.library.path=/home/yashdeepsingh/td/tdlib/bin -javaagent:/snap/intellij-idea-community/475/lib/idea_rt.jar=36509:/snap/intellij-idea-community/475/bin -Dfile.encoding=UTF-8 -classpath /home/yashdeepsingh/td/out/production/td org.drinkless.tdlib.example.Example

Please enter phone number: +91xxxxxxxxx

Please enter phone number: Receive an error:
Error {
  code = 400
  message = "API_ID_PUBLISHED_FLOOD"
}

```

To check whether the same was happening in the terminal I ran it in my terminal and it was running fine.
Any help on the matter will be highly appreciated.

**Comment by levlam** [comment]
You must create and use your own `api_id` and `api_hash` as described in https://core.telegram.org/api/obtaining_api_id#obtaining-api-id.

**Comment by ToYashDeepSingh** [comment]
Can you explain why this happens please? And how will it stop if I use the api_id and api_hash generated by: https://core.telegram.org/api/obtaining_api_id#obtaining-api-id.

**Comment by levlam** [comment]
This can't happen if you use your own `api_id` and `api_hash`.
