### ISSUE TITLE
There is a long delay when receiving messages on Android.

### ISSUE THREAD

**Issue by tuchkovkirill** [tdlib/td#2725]
I am using the version from the master branch.

In most cases, my application receives messages very quickly. But sometimes updateHandler is called after 10 or more seconds after receiving a message in the Telegram application on same device. Sometimes, even more than a minute. It's critical for me.

Why is this so? How can I fix this?

**Comment by ne0c0de** [comment]
It's not related with Android I guess, same situation happens on me on Debian Linux, I'm using latest version of tdlib. I suspect this is cause because of Telegram servers but I still couldn't find an evidence yet

**Comment by levlam** [comment]
If the user is online, private messages should be received fast, but channel messages still can be received with arbitrary delay. If the user is offline, then any message can be received with arbitrary delay. When the app is in background, it has no access to network and it can be woken up only by a push notification.

**Comment by ne0c0de** [comment]
The problem here is the app is working on server and there's no offline option for it. It's running as a single app on on server (with nodejs)

Anyway my computer is also open for 7/24 and Telegram client (Mac Desktop Client) is always open (and it's not in background too, it's always open on a separate monitor)

Sometimes I got 2-3 seconds sometimes I got 5-6 seconds delay to getting messages. And this situation started to happening in last 1 month. Before that there was slight delay up to 1 second which was little affordable for me. But currently it's working horrible (I'm also using Telegram Premium service which has no effect on this too...)

**Comment by tuchkovkirill** [comment]
Thanks for the quick reaction, guys.

The situation is as follows:

Two Android phones are on the table. The receiver device is connected to the computer and is in debug mode. Messages are sent in a private chat. My application is active, the message receiver is running in the service.

When there is a problem with delayed reception, notifications from the telegram application appears, but my application does not receive messages. There is nothing in the log, although debugging information should be print in updateHandler(). After a while, all incoming messages are processed instantly.

The same situation occurs when the telegram app is open. I can see incoming messages in it, but nothing in the logs. After about 30 seconds, they get into my service receiver.

Same problem with release builds.

**Comment by tuchkovkirill** [comment]
Does TdLib have its own connection to Telegram server or does receive messages from the Telegram application on the device, for example through broadcast messages or service?

**Comment by levlam** [comment]
@tuchkovkirill How many devices do you have in Devices section in the app settings?

**Comment by tuchkovkirill** [comment]
> @tuchkovkirill How many devices do you have in Devices section in the app settings?

How many devices has logged in this account? I don't have a debugging device right now, but I think less than four. May be only one. 

Does it affect anything?

**Comment by levlam** [comment]
If it is less than four, then it doesn't affect anything, but I would have rechecked this just to be sure.

**Comment by tuchkovkirill** [comment]
No one else has any ideas?

I drew attention to the fact that this situation occurs in places with weak coverage of the cellular provider. Maybe my problem is related to an unstable internet connection?

Why does the Telegram application always receive messages quickly, but the TDLib-based application is sometimes late?

**Comment by tuchkovkirill** [comment]
I found this method:

```
// Creates a function, which sets the current network type. Can be called before authorization. 
// Calling this method forces all network connections to reopen, mitigating the delay in switching between different networks, 
// so it must be called whenever the network is changed, even if the network type remains the same. 
// Network type is used to check whether the library can use the network at all and also for collecting 
// detailed network data usage statistics.

TdApi.SetNetworkType(NetworkType type)
```


What did the author mean by that? Can it help me?

**Comment by levlam** [comment]
The method `SetNetworkType` will have no effect.

**Comment by ne0c0de** [comment]
hence there is no clarification, it's not understandable why this delay comes out

**Comment by tuchkovkirill** [comment]
> The method `SetNetworkType` will have no effect.

At least it really causes reconnection.

What if, there were no incoming messages for ten seconds, then call `SetNetworkType`?

Of course, this is an ugly method, but I have no other ideas.

**Comment by levlam** [comment]
It causes reconnection, but reconnection has nothing to do with receiving of new messages.

**Comment by tuchkovkirill** [comment]
Does TdLib use the same code as the Telegram app? 
Why does the Telegram application always receive messages quickly, but the TDLib-based application is sometimes late?

**Comment by levlam** [comment]
Every app uses different code. TDLib itself has much more reliable network implementation then other apps and isn't different from other apps in terms of receiving new data.

**Comment by tuchkovkirill** [comment]
Is there a way to force check for new messages?

**Comment by levlam** [comment]
No.

**Comment by tuchkovkirill** [comment]
> It causes reconnection, but reconnection has nothing to do with receiving of new messages. It can help only if the connection was dead.

Usually, when the client connects to the server, the client requests new data from the server or the server pushes new data to the client.

Does Telegram and TdLib works another way?

**Comment by levlam** [comment]
Data is pushed whenever there is data to push. Reconnection itself doesn't cause any new data to be requested, as if protocol is connectionless.

**Comment by ne0c0de** [comment]
is it possible to get new messages with placing new server near of each Telegram DC?

I mean, if I'm not wrong Telegram has 5 DC and opening a new server with same Telegram account near of those DC's can able to fast to receive new message?

**Comment by levlam** [comment]
@ne0c0de This can't reduce message delivery time significantly, decreasing it only by half of the ping time.

**Comment by tuchkovkirill** [comment]
> Data is pushed whenever there is data to push. Reconnection itself doesn't cause any new data to be requested, as if protocol is connectionless.

So is the problem on the server side? Then why is there no problem with the Telegram application, but TDLib does?

**Comment by levlam** [comment]
@tuchkovkirill 
There are a lot of things that can affect data delivery, but if everything is eventually delevered, then it works as intended. I mentioned the most common reasons affecting update delivery in the first message.

**Comment by tuchkovkirill** [comment]
Hello, Alexey.

I can't leave this problem as it is, and I'm still trying to fix it.

I have determined that at the time this situation occurs, the state of the active network is the same as when there is no problem. It is connected, has internet, validated, FOREGROUND and so on.

In addition, `TdApi.SetNetworkType` causes reconnection, during which new messages are received. When I call this function, the connection state becomes `"ConnectionStateConnecting"`, then all the delayed messages arrive, and then the state becomes `"ConnectionStateReady"`.

Can you tell me where else to look for the cause of the error?

**Comment by levlam** [comment]
Do you correctly set "online" to true option when the app is in foreground?

**Comment by tuchkovkirill** [comment]
I don't understand what do you mean? Which object are we talking about?

**Comment by levlam** [comment]
If the app switches between background and foreground it is supposed to call `setOption` for the option "online" with appropriate value. That's what I called "If the user is online" in the first message.

**Comment by ne0c0de** [comment]
if tdlib is working in server side, should we need to call this option too?

**Comment by levlam** [comment]
@ne0c0de If the user is online, then yes.

**Comment by tuchkovkirill** [comment]
Hello, Aliaksei!

Well, now when I open and close my program, I change the status of "online" depending on the state of the program. I can't say if the problem has disappeared, since it occurs quite rarely, but I see in the telegram application that the status is changing.

However, when the application is unloaded, my service continues to receive and process incoming messages. And if at this moment it marks the message as "read", then I see in the telegram application, that the status automatically changes to "online".

At this moment have I to call `SetOption("online"...)` or do nothing?

**Comment by levlam** [comment]
The status of the user locally changes to online by the app that receives the update about read message. Your app state isn't affected by this.
