### ISSUE TITLE
I cannot log in as a bot

### ISSUE THREAD

**Issue by mahmoud-syr** [tdlib/td#2726]
I am trying to use `tdsharp` as a wrapper around the `tdlib` API for .NET.
Whenever I try to call `CheckAuthenticationBotTokenAsync` with my bot-token. I get the error: `TdLib.TdException: 'ACCESS_TOKEN_INVALID'` although the exact same token is used for `Bot API` and it's working just fine.

Would be nice to get help here since the documentation is super confusing and there is no direction for people like me as to where to go.

Thanks in advance.

**Comment by levlam** [comment]
Are you sure that you use the correct token as provided by BotFather starting with digits and not "bot"?
Did you correctly specify `use_test_dc == false` in `setTdlibParameters`?

**Comment by mahmoud-syr** [comment]
> Are you sure that you use the correct token as provided by BotFather starting with digits and not "bot"? Did you correctly specify `use_test_dc == false` in `setTdlibParameters`?

Dear @levlam 
Thanks for your reply I was able to find the issue, yes indeed I was using `use_test_dc` to `true`. I thought it sort of make sense, since I am actually testing locally.
Any reason why it doesn't if we are passing `use_test_dc = true`?

Anyways this can be safely closed.
Thanks alot!

**Comment by levlam** [comment]
Test environment is a completely independent environment. You can create accounts and bots there independently and can transfer no data between test and production environment.

**Comment by mahmoud-syr** [comment]
> Test environment is a completely independent environment. You can create accounts and bots there independently and can transfer no data between test and production environment.

Thanks for the clarification @levlam
