### ISSUE TITLE
Get emoji names from searchEmojis

### ISSUE THREAD

**Issue by the-blank-x** [tdlib/td#2727]
[`searchEmojis`] returns a [`td_api::emojis`] class, but the class only has a list of emojis, not emojis and their names. [`searchEmojis` is used by Telegram X], but since TDLib doesn't return any names, [Telegram X cannot show any corresponding names when listing emojis].

[`searchEmojis`]: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1search_emojis.html
[`td_api::emojis`]: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1emojis.html
[`searchEmojis` is used by Telegram X]: https://github.com/TGX-Android/Telegram-X/blob/2f4778e2b1b9ff75dd990cc6f54b6835d047699a/app/src/main/java/org/thunderdog/challegram/helper/InlineSearchContext.java#L1273
[Telegram X cannot show any corresponding names when listing emojis]: https://t.me/tgandroidtests/164057

**Comment by levlam** [comment]
Emoji has no "names". Whatever you call their name, this is fixed and is not related to actual search.

**Comment by the-blank-x** [comment]
> Whatever you call their name, this is fixed and is not related to actual search.

What do you mean?

**Comment by levlam** [comment]
I mean that emoji has no "names".

**Comment by the-blank-x** [comment]
By names, I was referring to the "keywords" of an emoji. For example, 🛞 is mapped to tire, tyre, and wheel. If I were searching for "t", I'd like to get tire and/or tire and tyre.

**Comment by levlam** [comment]
`searchEmojis` works in the opposite direction. There are no keywords mapped to an emoji, but list of emoji mapped to a keyword. An emoji can be found by hundreds of words in each language. The list of words can be very big and isn't supposed to be visible to the user unless the user typed the exact keyword.

**Comment by the-blank-x** [comment]
> There are no keywords mapped to an emoji, but list of emoji mapped to a keyword.

Isn't that what I said?

**Comment by levlam** [comment]
No. You can receive multiple emoji by a keyword. The keyword is just a search term in `searchEmojis`, it isn't supposed to be visible to the user.

**Comment by the-blank-x** [comment]
Multiple emojis sharing the same keyword isn't (or at least shouldn't) be a problem though

**Comment by the-blank-x** [comment]
Thank you! (For anyone else looking, this issue was fixed by https://github.com/tdlib/td/commit/bf6345248fd6e9310eb54306af5700eedebe7386)
