### ISSUE TITLE
telegram API question

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#273]
Hello!

I do not know where to ask about this. Is it possible to regenerate app_hash? I think I might exposed it... 
Is there any steps for changing app_id and app_hash without destroying account?

**Comment by levlam** [comment]
No, there is no way to change app_hash without creating a new app_id with a new account.

**Comment by blacksailer** [comment]
Users must reauthorize after changing appid and apphash?

**Comment by levlam** [comment]
Yes.
