### ISSUE TITLE
Is there any way to get all history messages of  a special others channel?

### ISSUE THREAD

**Issue by jnxyatmjx** [tdlib/td#2732]
In theroy, Can we get all messages from other people's channel? 
if the channel can't forward and copy videos, can we just down them use tdlib python?

**Comment by levlam** [comment]
No, because this violates https://core.telegram.org/api/terms.

**Comment by jnxyatmjx** [comment]
> No, because this violates https://core.telegram.org/api/terms.

got it ,thanks.
