### ISSUE TITLE
Creating bots

### ISSUE THREAD

**Issue by chjrco** [tdlib/td#2741]
I'm quite confused on how to create bots rather than clients. When listening for AuthorizationStateWaitTdlibParameters it requires me to set api hash and api token, where do I find those for the bot? Do I use my personal account's?
If I do that it just logs into my account and I cant "register as a bot" nor call CheckAuthenticationBotToken

**Comment by levlam** [comment]
> Do I use my personal account's?

Yes, you create them at api.telegram.org.

To log in as a bot you need to call `checkAuthenticationBotToken` in the state `authorizationStateWaitPhoneNumber`.

**Comment by chjrco** [comment]
I used my hash and id in `SetTdlibParameters` (with `useTestDc = false`), sent that to Telegram and received `UpdateConnectionState { state = ConnectionStateReady }`. There is no `AuthorizationStateWaitPhoneNumber` update coming. 
Shouldn't it ask for my auth data before logging in?
