### ISSUE TITLE
Precompile Android .so library

### ISSUE THREAD

**Issue by ra1ph** [tdlib/td#275]
Hello, I'm trying to compile the library to use it in Android and having issues. What I do:

At first, I precompile library as it was in java example.

`mkdir jnibuild`
`cd jnibuild`
`/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_TOOLCHAIN_FILE=/home/mikhail/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=27 -DANDROID_TOOLCHAIN=clang -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mikhail/td/jnibuild/ -DCMAKE_MAKE_PROGRAM=/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/ninja -DANDROID_NDK=/home/mikhail/Android/Sdk/ndk-bundle -DOPENSSL_ROOT_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib -DOPENSSL_INCLUDE_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib/openssl-1.0.2o/include -DTD_ENABLE_JNI=ON -DANDROID_STL=c++_static -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..`

`/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/cmake --build . --target install`

It seems that it went fine. After that, I'm trying to link the .so file: 

`cd ../example/java`
`mkdir build`
`cd build`

`/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/cmake -DANDROID_ABI=x86 -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_TOOLCHAIN_FILE=/home/mikhail/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=27 -DANDROID_TOOLCHAIN=clang -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mikhail/td/example/java/lib_out -DCMAKE_MAKE_PROGRAM=/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/ninja -DANDROID_NDK=/home/mikhail/Android/Sdk/ndk-bundle -DOPENSSL_ROOT_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib -DOPENSSL_INCLUDE_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib/openssl-1.0.2o/include -DTd_DIR=/home/mikhail/td/example/java/td/lib/cmake/Td -DANDROID_STL=c++_static -DCMAKE_INSTALL_PREFIX:PATH=.. ..`

And get error
`Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
  JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)`

I have proper JAVA_HOME. I tried to manually set paths 
`-DJAVA_INCLUDE_PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/include 
-DJAVA_AWT_LIBRARY=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/libawt.so 
-DJAVA_JVM_LIBRARY=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/server/libjvm.so 
-DJAVA_AWT_INCLUDE_PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/include 
-DJAVA_INCLUDE_PATH2=/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux `

but in that case I get 
`/home/mikhail/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/server/libjvm.so: incompatible target`

Obviously, I'm doing something wrong, could you point out what exactly?

**Comment by ra1ph** [comment]
I solved it, thanks. The problem was with the incompatible version of JVM

**Comment by fandangos** [comment]
> Hello, I'm trying to compile the library to use it in Android and having issues. What I do:
> 
> At first, I precompile library as it was in java example.
> 
> `mkdir jnibuild`
> `cd jnibuild`
> `/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_TOOLCHAIN_FILE=/home/mikhail/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=27 -DANDROID_TOOLCHAIN=clang -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mikhail/td/jnibuild/ -DCMAKE_MAKE_PROGRAM=/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/ninja -DANDROID_NDK=/home/mikhail/Android/Sdk/ndk-bundle -DOPENSSL_ROOT_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib -DOPENSSL_INCLUDE_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib/openssl-1.0.2o/include -DTD_ENABLE_JNI=ON -DANDROID_STL=c++_static -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..`
> 
> `/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/cmake --build . --target install`
> 
> It seems that it went fine. After that, I'm trying to link the .so file:
> 
> `cd ../example/java`
> `mkdir build`
> `cd build`
> 
> `/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/cmake -DANDROID_ABI=x86 -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_TOOLCHAIN_FILE=/home/mikhail/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=27 -DANDROID_TOOLCHAIN=clang -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mikhail/td/example/java/lib_out -DCMAKE_MAKE_PROGRAM=/home/mikhail/Android/Sdk/cmake/3.6.4111459/bin/ninja -DANDROID_NDK=/home/mikhail/Android/Sdk/ndk-bundle -DOPENSSL_ROOT_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib -DOPENSSL_INCLUDE_DIR=/home/mikhail/Android/Sdk/ndk-bundle/platforms/android-27/arch-arm/usr/lib/openssl-1.0.2o/include -DTd_DIR=/home/mikhail/td/example/java/td/lib/cmake/Td -DANDROID_STL=c++_static -DCMAKE_INSTALL_PREFIX:PATH=.. ..`
> 
> And get error
> `Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)`
> 
> I have proper JAVA_HOME. I tried to manually set paths
> `-DJAVA_INCLUDE_PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -DJAVA_AWT_LIBRARY=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/libawt.so -DJAVA_JVM_LIBRARY=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/server/libjvm.so -DJAVA_AWT_INCLUDE_PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -DJAVA_INCLUDE_PATH2=/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux `
> 
> but in that case I get
> `/home/mikhail/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/server/libjvm.so: incompatible target`
> 
> Obviously, I'm doing something wrong, could you point out what exactly?

Hi Ra1ph,

Sorry to bump this old issue.
I'm working on support full blurays on android (like the nvidia shield). 
Blurays and 4k blurays use java to display the menus.

Do you think you could share your libjvm.so compiled for android, please?
