### ISSUE TITLE
Is TdApi.User id globally unique?

### ISSUE THREAD

**Issue by msamatyrski** [tdlib/td#2752]
In the [Getting started](https://core.telegram.org/tdlib/getting-started#handling-updates) guide it is mentioned that
> A Telegram user is called user. **Each user has a unique identifier** and a first name, and can also have an optional last name, username and profile photo among other useful fields.

In the following [comment](https://github.com/tdlib/td/issues/2270#issuecomment-1384190538):
> You must receive the user identifier from the same TDLib instance without restarting it to ensure that you can use it.

Could you please advise on the following questions:
1. Is user.id globally unique? If not, within which scope can we assume its uniqueness?
2. Can clients  (org.drinkless.tdlib.Client or tdlib instance) of different telegram accounts receive different user.id values for some other telegram account?
3. Can different clients of the same telegram account receive different user.id values for some other telegram account?
4. Can the same client but after a restart receive different user.id values for some other telegram account?

Thank you.

**Comment by levlam** [comment]
1. It is unique for a given user. That is an app can use it as a unique user identifier.
2. Theoretically, yes. 
3. Theoretically, this is possible for regular user accounts, but not for bots.
4. No, after restart all identifiers will be the same for the same user.

**Comment by msamatyrski** [comment]
Thank you for the clarification!
