### ISSUE TITLE
How to get "Posted Stories" for a user?

### ISSUE THREAD

**Issue by rnd4222** [tdlib/td#2753]
In a Telegram Desktop, when I open user info window, there is a "N posts" link which opens "Posted Stories" windows.
This stories doesn't seems to be returned neither by `GetChatArchivedStories` nor `GetChatActiveStories`.
How do I get that?

**Comment by levlam** [comment]
Stories that are available after expiration date are called "pinned" in API, so you need to call `getChatPinnedStories` for this.

**Comment by rnd4222** [comment]
Thanks! That worked.
