### ISSUE TITLE
In which cases updatesTooLong sends

### ISSUE THREAD

**Issue by glcanvas** [tdlib/td#2754]
Hello!
Reading Telegram documentation https://core.telegram.org/api/updates

I'm trying to fetch latest messages from channel, and I'm not interested in outdated (old) messages. I.e. in messages which posted more than 2-3 seconds ago.

Have some questions:
1)
Notice these constructor:
https://core.telegram.org/constructor/updatesTooLong

In which cases these command will be sent to client? 
Am I right this happens during huge delay on a server side, or if in one moment more than 1_000 events occurred?

2) Is it possible to skip `updatesTooLong` and continue to listen actual information? Will new updates be sent to client from server side after  `updatesTooLong` event? 
For me it's ok to skip some messages, much more important to get latest messages.

**Comment by levlam** [comment]
It is documentation for main Telegram API, unrelated to TDLib API.

`updatesTooLong` is unrelated to channel updates. It is also unspecified when the update is sent. Apps like TDLib must just handle it and fetch missed updates if appropriate.

**Comment by glcanvas** [comment]
Yes, agreed, this question unrelated to TDLib API, But thought you may have more information about this.

>  It is also unspecified when the update is sent

Got it, thank you!
