### ISSUE TITLE
how to get  entity for a markdown text

### ISSUE THREAD

**Issue by jnxyatmjx** [tdlib/td#2757]
when i use sendMessage function. like that **sendMessage chat_id:int53 message_thread_id:int53 reply_to:InputMessageReplyTo options:messageSendOptions reply_markup:ReplyMarkup input_message_content:InputMessageContent = Message;**

I need put the parameter input_message_content, my question is how to get correct parameter for a markdown text.
i use **parseTextEntities** but i get  _**Entity begins in a middle of a UTF-16 symbol at byte offset 55**_

**Comment by jnxyatmjx** [comment]
> when i use sendMessage function. like that **sendMessage chat_id:int53 message_thread_id:int53 reply_to:InputMessageReplyTo options:messageSendOptions reply_markup:ReplyMarkup input_message_content:InputMessageContent = Message;**
> 
> I need put the parameter input_message_content, my question is how to get correct parameter for a markdown text. i use **parseTextEntities** but i get _**Entity begins in a middle of a UTF-16 symbol at byte offset 55**_

text example [👍 *amazing videos* \n👉 *Y A Better You* 👈\n👉 *Y Only Wait You* 👈](https://t.me/you/9)

**Comment by levlam** [comment]
`parseTextEntities` can't return invalid entities. The method is designed to be used by bots. Regular users can use `parseMarkdown`, or specify entites manually.

**Comment by jnxyatmjx** [comment]
> `parseTextEntities` can't return invalid entities. The method is designed to be used by bots. Regular users can use `parseMarkdown`, or specify entites manually.

is there any document for entities manually

**Comment by levlam** [comment]
Just specify them as part of `formattedText`.
