### ISSUE TITLE
'td/telegram/td_json_client.h' file not found

### ISSUE THREAD

**Issue by takasurazeem** [tdlib/td#276]
Hi, I have followed all the instructions in the swift example readme file and have built the tdlib as well but I get this error when I try to build the Xcode project.

**Comment by levlam** [comment]
Have you run
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../example/swift/td ..
cmake --build . --target install
```
After that there a folder example/swift/td should be created, containing all needed files.

**Comment by levlam** [comment]
@takasurazeem I hope that your issue was resolved. Please reopen the issue and provide additional details if it isn't a case.
