### ISSUE TITLE
how to update layer to 170?

### ISSUE THREAD

**Issue by xspeed1989** [tdlib/td#2760]
I found the layer 169 is lower than offical app layer 170,how to update it? I can't find any document about this

**Comment by levlam** [comment]
TDLIb has its own API and doesn't expose any particular server-side API layer. There is no way to just update it without changing correspondingly TDLib's source code.

**Comment by levlam** [comment]
Supporting a different server-side API scheme requires really a lot of changes.

**Comment by xspeed1989** [comment]
> Supporting a different server-side API scheme requires really a lot of changes.

I know, So Is there some document about this?

**Comment by levlam** [comment]
There is no documentation. You just need to change all code accordingly.

**Comment by xspeed1989** [comment]
Where can I get the data structure in https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl?

**Comment by levlam** [comment]
This is scheme for server-side API. It will be available at https://core.telegram.org/scheme at some point in the future.

**Comment by xspeed1989** [comment]
> This is scheme for server-side API. It will be available at https://core.telegram.org/scheme at some point in the future.

OK, I need to wait the document update, Do you have plan to update LAYER to newest version?

**Comment by levlam** [comment]
Yes, it will be updated in the future.
