### ISSUE TITLE
Criteria for user disconnect and reauthentication

### ISSUE THREAD

**Issue by sierret** [tdlib/td#2762]
After some time the library "disconnects" the user and asks for credentials(typically phone number and verification code). What is the criteria for these disconnects? Is it based on the amount of updates/surpassng request quota by user or based on some time delay?

**Comment by levlam** [comment]
The behavior is the same as in any other apps: users must explicitly log out to be "disconnected", or be inactive for `inactive_session_ttl` which defaults to 180 days.
