### ISSUE TITLE
How to get a list of folders?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2765]
![Screenshot from 2024-01-19 01-18-31](https://github.com/tdlib/td/assets/82513502/cb69fb79-98f0-4512-87be-40e778a0748d)

**Comment by azkadev** [comment]
and how to use this method addChatFolderByInviteLink

I'm confused about adding the chat_ids parameters

**Comment by azkadev** [comment]
> and how to use this method addChatFolderByInviteLink
> 
> I'm confused about adding the chat_ids parameters

I used the checkChatFolderInviteLink method first then used this addChatFolderByInviteLink and it worked

**Comment by levlam** [comment]
You just need to handle `updateChatFolders` update for this. There is no need to get chat folders explicitly.

`addChatFolderByInviteLink` needs to be used only while processing links of the type `internalLinkTypeChatFolderInvite` after successful `checkChatFolderInviteLink` call. All parameters can be received from `checkChatFolderInviteLink` response.

**Comment by azkadev** [comment]
> updateChatFolders
