### ISSUE TITLE
Case wise when receiving the updateNewChat parameter

### ISSUE THREAD

**Issue by CoCoMNT** [tdlib/td#2768]
{"@type":"updateBasicGroup","basic_group":{"@type":"**basicGroup**","id":4093393850,"member_count":3,"status":{"@type":"chatMemberStatusMember"},"is_active":true,"upgraded_to_supergroup_id":0},"@client_id":1}

{"@type":"updateSupergroup","supergroup":{"@type":"**supergroup**","id":1701774173,"usernames":{"@type":"usernames","active_usernames":["dfadsdsad"],"disabled_usernames":[],"editable_username":"dfadsdsad"},"date":1705682455,"status":{"@type":"chatMemberStatusMember"},"member_count":0,"boost_level":0,"has_linked_chat":false,"has_location":false,"sign_messages":true,"join_to_send_messages":true,"join_by_request":false,"is_slow_mode_enabled":false,"is_channel":false,"is_broadcast_group":false,"is_forum":false,"is_verified":false,"restriction_reason":"","is_scam":false,"is_fake":false,"has_active_stories":false,"has_unread_active_stories":false},"@client_id":1}

basic**G**roup
super**g**roup
I may have OCD，The size is too arbitrary😂

**Comment by levlam** [comment]
"Supergroup" is a single word like "Superman"/"supermodel". "Basic group" is an adjective and a noun like "basic man"/"basic model".
