### ISSUE TITLE
Working with invitations.

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2769]
There are invitations in the telegram. I  have an invitation to a group that I don't have. What should I do to receive this chat or what updates should I wait to see this chat (group) in order to process the invitation?

**Comment by levlam** [comment]
You can't receive the chat most of the time, you can only join it. All links are processed by calling `getInternalLinkType` -> `getExternalLinkInfo` -> `getExternalLink`. These links will have type `internalLinkTypeChatInvite` and should be processed as documented.

**Comment by fat-complex** [comment]
Thx) Here I have a link and I know that this is the `internalLinkTypeChatInvite` type. Can I use join Chat By Invite Link? Or do you need any additional actions?

**Comment by levlam** [comment]
Call `checkChatInviteLink` with the given invite link to process the link. If the link is valid and the user wants to join the chat, then call `joinChatByInviteLink`.

**Comment by fat-complex** [comment]
I called checkChatInviteLink. Why do I get this error when calling `joinChatByInviteLink`: _[ 1][t 0][1705989755.632174015][DialogInviteLinkManager.cpp:84][!Td]	Receive wrong result for ImportChatInviteQuery: updates_ ?

When I call this method a second time, there is no such message.

**Comment by levlam** [comment]
Could you enable TDLib log with verbosity level 4 and send it as a file to https://t.me/tdlib_bot?

**Comment by fat-complex** [comment]
@levlam, sent

**Comment by levlam** [comment]
The mentioned error should be fixed in the latest TDLib version from Github.

**Comment by fat-complex** [comment]
I use this version 1.8.23

**Comment by levlam** [comment]
You need to update to the latest version from master.

**Comment by fat-complex** [comment]
@levlam Thx)
