### ISSUE TITLE
Request to separate can_send_other_messages options in chatPermissions

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#2771]
Hello
In tdlib, for **chatPermissions**, the **can_send_other_messages** option is used, which is related to send animations, games, stickers, and dice and use inline bots, but in Android Telegram, each of these options can be set separately.
Can you add this feature to tdlib?

**Comment by levlam** [comment]
This is not true: all of these can be disabled only together using "Stickers & GIFs" setting in the official Android app. None of the official app can show the settings correctly if some of them have different value.
