### ISSUE TITLE
Cross-compilation instructions

### ISSUE THREAD

**Issue by aplavin** [tdlib/td#2772]
I'm trying to compile tdlib different platforms on the same host machine, but probably doing something wrong here. The end result always is the `so` library for the host machine...

What I do:
```
mkdir build
cd build
CC=$HOSTCC CXX=$HOSTCXX LD=$HOSTLD cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target prepare_cross_compiling

CC=$TARGETCC CXX=$TARGETCXX LD=$TARGETLD cmake -DCMAKE_CROSSCOMPILING=True -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target tdjson
```
What should be the correct sequence of steps?

**Comment by levlam** [comment]
You must use differrent build folders for these CMake invocations. Otherwise, the direction is correct.

**Comment by levlam** [comment]
CMake needs much more variables to be specified to be able correctly build the project for the target architecture. It is better to create a toolchain file that provides all needed variables. See https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html for examples of how to correctly cross-compile with CMake.
