### ISSUE TITLE
Get messageThreadId for forum topic link

### ISSUE THREAD

**Issue by andreymerchenko** [tdlib/td#2776]
Dear tdlib community,

in order to send a message to the forum topic I need to know the messageThreadId of this forum topic. Assume I have a link to a forum topic, e.g. 'https://t.me/mypublicforumgroupname/29'. Looks like the id in the forum topic link (29 in my sample) is the sequential order of the corresponding message in the group, but not the messageId or messageThreadId. And I could not find a good way to retrieve the messageThreadId of the topic by such sequence id of the message.

How by the forum topic link can I retrieve the messageThreadId of the topic?

Thank you.

**Comment by levlam** [comment]
You must receive `messageThreadId` from TDLib. Resolving of a message link with `getMessageLinkInfo` is one of the way to obtain it.
