### ISSUE TITLE
How do I understand by calling serachPublicChat that I can join this group or apply to join

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2787]
I have a public link to the group. I processed it using `getInternalLink` Type and it returned me the type `internalLinkTypePublicChat` which contains the name of the chat. I called `searchPublicChat` and it returned the chat to me. How do I understand that I can log in to it or apply to join the chat?

**Comment by levlam** [comment]
You can always try to join a public chat with `joinChat`.
