### ISSUE TITLE
Phone number banned when testing login flow

### ISSUE THREAD

**Issue by rufatagayev** [tdlib/td#2793]
I was testing my login flow in the app (using tdlib java), and now I get a message that my phone number is banned.

I sent an email to recover@telegram.org with explanation and my API id. Is there a way to expedite this?

**More importantly** - is there way to know why the number was banned and **how I can prevent it** from happening again? I imagine I will be doing a lot of tests while developing the app. Thanks!

**Comment by levlam** [comment]
The best you can do is to try to log in from an official app and send a recover request from there.

**Comment by rufatagayev** [comment]
Thanks. That's what I did. How long does it usually take to get unbanned? Is there any other channel I can try?..

**Comment by IvanMMM** [comment]
Same here with using Gram.js, banned soon after login :\

**Comment by rufatagayev** [comment]
I found out soon after that we were supposed to use test numbers from different data centers, in order not to get flood restricted or banned. Guess I should have RTFM better :).

**Comment by levlam** [comment]
@rufatagayev If you still weren't unbanned, make sure that you exactly followed instructions provided at https://tginfo.me/phone-number-is-banned-en/. The article is very detailed and overall looks good to me.

**Comment by rufatagayev** [comment]
Appreciate it, @levlam , checking it out now. Still not unbanned...

**Comment by rufatagayev** [comment]
API docs say that logging out and in multiple times on production DCs may trigger a ban. That's why we have to use test DCs. But I believe for development purposes there should be a warning at least.

**Comment by shodanalert** [comment]
I'm trying again with new phone number and after login in tdlib it get banned.
I assume new phone number should not login using tdlib , did my assumption make sense ?

**Comment by azkadev** [comment]
> I'm trying again with new phone number and after login in tdlib it get banned. I assume new phone number should not login using tdlib , did my assumption make sense ?

not just you, I also feel, not only for old IDs / many users, maybe this is done to reduce spammers but you can contact Telegram to unban. After being unbanned you can use tdlib without being banned as long as it doesn't break the rules and doesn't spam
