### ISSUE TITLE
How to get number of comments of a message?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2795]
In official Telegram apps, comment buttons of a channel message are shown with the total number of comments.
Is it possible to get such a count using TDLib?

![screenshot showing example of comment count](https://github.com/tdlib/td/assets/23420208/94ffc41c-e158-4e0d-8936-d7b3b3e793d9)

Neither `getMessageThread` nor `getMessageThreadHistory` provides such a value. 

Thanks!

**Comment by levlam** [comment]
The number of comments is shown immediately on the message, so it doesn't require any additional request in TDLib. You can find all needed data in `messageInteractionInfo.reply_info`. `reply_count` is the total number of comments, `recent_replier_ids` - identifiers of the users, which photos are shown. `last_read_inbox_message_id` can be used to identify position, from which to open the comments, and if `last_read_inbox_message_id != 0 && last_message_id > last_read_inbox_message_id`, then a dot that denotes new comments should be shown.

**Comment by vincentneo** [comment]
Thanks @levlam!
