### ISSUE TITLE
Edit Message Prompts error {   code = 400   message = "Message not found" }

### ISSUE THREAD

**Issue by YuAnna9** [tdlib/td#2796]
I use the EditMessageText

I use theEditMessageText to edit a message I just sent, but it prompts ：
error {
  code = 400
  message = "Message not found"
}

How do I edit a sent message？

My code is as follows：

![屏幕截图 2024-02-19 183159](https://github.com/tdlib/td/assets/160484006/f293fecc-c42e-43e0-bd90-12cce2f6503e)

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/2248.

**Comment by YuAnna9** [comment]
@levlam Thank you very much for your guidance, it solved my problem:)

**Comment by YuAnna9** [comment]
@levlam Thank you very much for your guidance, it solved my problem:)
