### ISSUE TITLE
[ASK] How revoke all message for everyone in chat group?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2798]
How to enable this in tdlib, what api method to use
![Screenshot from 2024-02-21 23-28-58](https://github.com/tdlib/td/assets/82513502/d3396cb5-caff-497a-a369-65eee8a23ad4)

**Comment by levlam** [comment]
See `deleteChatHistory` and its documentation.

**Comment by azkadev** [comment]
> See `deleteChatHistory` and its documentation.

I have used the deleteChat history method

and added revoke to true, but it's still not checked

**Comment by azkadev** [comment]
BTW, why are there public channels that can't use method deleteChatHistory?

error
Chat history can't be deleted

**Comment by levlam** [comment]
deleteChatHistory:
> Deletes all messages in the chat. Use chat.can_be_deleted_only_for_self and chat.can_be_deleted_for_all_users fields to find whether and how the method can be applied to the chat
