### ISSUE TITLE
How do I upgrade tdlib from version 1.8.10 to the latest 1.8.25 on Ubuntu?

### ISSUE THREAD

**Issue by kubsite1** [tdlib/td#2799]
On Linux Ubuntu 20 installed tdlib 1.8.10 a year ago (https://tdlib .github.io/td/build.html?language=PHP), then installed phptdlib ([https://github.com/yaroslavche/phptdlib](https://github.com/yaroslavche/phptdlib) ) and created a project - it works successfully. Recently, there were errors when receiving messages - unsupported Message, as I studied - means the stdlib version is outdated and it's time to update it.

I tried to reinstall on the same server: I downloaded stdlib 1.8.25 from the repository and installed it, it was installed, but the messages are also unsupportedMessage.

How do I update stdlib correctly? Do I need to install the phptdlib dependent on it again after updating the tdlib?

I haven't found a solution yet, I'm desperate and I'm asking for help.

**Comment by levlam** [comment]
The latest TDLib supports all currently existing messages. You need to check that you use TDLib 1.8.25 by calling `getOption("version")`. It is likely that you still use libtdjson.so from the old TDLib version.
