### ISSUE TITLE
Can’t download some files with “downloadFile”

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#280]
Sometimes I’m unable to download files from the cloud.  I tried different priorities, waited for 24h with no result.  I have 100% reproduciable case:

For user 82439953 I do `downloadFile file_id=1648`, it generates only single `updateFile` with `is_downloading_active` set to true.  And that is all, no futher updates.  I tried cancaling, deleting, etc, without success to download the file

In official telegram client for iOS this file downloads instantly

For other files I’ve tried to download there was no problems at all, downloads in couple of `updateFile` events

tdlib version: 1.2.0

How to track this problem down? thanks

**Comment by levlam** [comment]
Could you show the whole `File` object received from `downloadFile`? Between, file_id is not persistent, so `file_id=1648` is a different file on every library launch.

**Comment by zevlg** [comment]
Aha, I see the point about `file_id`

Here is the file object I've got from `downloadFile`:

```json
{
  "@type": "file",
  "id": 1648,
  "size": 3537,
  "expected_size": 3537,
  "local": {
    "@type": "localFile",
    "path": "",
    "can_be_downloaded": true,
    "can_be_deleted": false,
    "is_downloading_active": true,
    "is_downloading_completed": false,
    "downloaded_prefix_size": 0,
    "downloaded_size": 0
  },
  "remote": {
    "@type": "remoteFile",
    "id": "BQADBAADsQcAAliioVBKhEf9cllOfAI",
    "is_uploading_active": false,
    "is_uploading_completed": true,
    "uploaded_size": 3537
  },
  "@extra": 1422
}
```

**Comment by levlam** [comment]
Everything is fine there, the file has begun to download. 

It seems that you need a proxy/VPN to download this file from Russia.

**Comment by zevlg** [comment]
Another user was able to download this file using same software from different country, so it looks like Russia related problem.  Though I was using same proxy as was used to download the file with official iOS client.

**Comment by zevlg** [comment]
Finally was able to download the file via vpn, thanks
