### ISSUE TITLE
how to in python?

### ISSUE THREAD

**Issue by atrdev-rgb** [tdlib/td#2801]
how to log out of account in python?

**Comment by levlam** [comment]
Use `logOut` method and wait for `authorizationStateClosed` as usual.

**Comment by atrdev-rgb** [comment]
td_send({"@type": "logOut"})

**Comment by atrdev-rgb** [comment]
How get username from chat if it exists. But it is not issued upon request?
```td_send({"@type": "getChat", "chat_id": chat_id})``` - I get = `'@type':'chat'`

if i use `td_send({"@type": "getSupergroupFullInfo","supergroup_id": supergroup_id,})` - I get = `'@type':'supergroupFullInfo'`

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.

**Comment by atrdev-rgb** [comment]
can I ask one more question?

`td.binlog` somehow I can open this file? 
He grows. I understand that this is some kind of TD session.

**Comment by levlam** [comment]
No, only TDLib can open the file.

**Comment by atrdev-rgb** [comment]
Thank you. And the database is created even if you select True. How can I open it? This is sqlite

**Comment by levlam** [comment]
You can't open the database. it is for internal TDLib usage only.

**Comment by atrdev-rgb** [comment]
'use_message_database': True   <-  This database?

**Comment by atrdev-rgb** [comment]
Thank`s
