### ISSUE TITLE
In what case will updateMessageInteractionInfo's `interaction_info` be null?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2804]
I realised today after triggering `removeMessageReaction` on a message that:
- has 0 view count
- has 0 forward count
- has no other reactions other than the one being removed
- has no reply info

that the subsequent `updateMessageInteractionInfo` contains just the `message_id` and `chat_id` without `interaction_info`.

Does that mean that it is safe to assume that that only happens on the exact scenario in cases such as mentioned above?

Thanks.

**Comment by levlam** [comment]
It is null if message doesn't have interactions. Currently, it means `view_count == 0`, `forward_count == 0`, `reply_info == null` and no reactions.

**Comment by vincentneo** [comment]
got it, thanks!
