### ISSUE TITLE
Get a premium limit for pinning topics in the forum

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2805]
How do I get a premium limit for securing topics in the forum?

**Comment by levlam** [comment]
To get a premium limit call the method `getPremiumLimit`.

**Comment by fat-complex** [comment]
Ok. I see methods to find out the limit on pinned chats for the main list and archive. But I can't find how to find out the limit for pinned topics in the forum

**Comment by levlam** [comment]
Then Premium doesn't affect this limit. There is no way Premium subscription can affect a limit for a supergroup. To get regular limit you can use getOption("pinned_forum_topic_count_max").
