### ISSUE TITLE
Upgrade pattern

### ISSUE THREAD

**Issue by pranavkulkarni7** [tdlib/td#2806]
Hello Team, I am trying to decide upgrade frequency for tdlib in my app, so I would like to understand:

- how frequently changes happen in the source?
- Is there any hint that, certain commit is stable and some may have any issue?

**Comment by levlam** [comment]
> how frequently changes happen in the source?

New versions are pushed to Github a few times in a month, but updating once a month to support the latest Telegram features should be enough for most apps.

> Is there any hint that, certain commit is stable and some may have any issue?

All commits pushed to Github are stable and suitable for production.

**Comment by pranavkulkarni7** [comment]
thanks!
