### ISSUE TITLE
Changes in updateChatLastMessage Event

### ISSUE THREAD

**Issue by JnZn558** [tdlib/td#2808]
Earlier there are property "reply_to_message_id" in this event. Currently I see a change, there is no reply_to_message_id more, reply_to_message_id has been changed into reply_to like below

`
"reply_to": {
            "@type": "messageReplyToMessage",
            "chat_id": xxxxxxxxxxxxxxxx,
            "message_id": xxxxxxxxxxxxxx
        }
`

Are there any Changelog about these changes in pre-announcement about it?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/blob/fe6201556b8a1c0bdd4f9b25027d294d6efd6eba/td/generate/scheme/td_api.tl#L1299-L1314
for the latest TDLib API scheme.
