### ISSUE TITLE
A few minutes after logging into my tdlib, the account becomes Deleted Account

### ISSUE THREAD

**Issue by YuAnna9** [tdlib/td#2810]
A few minutes after logging into my tdlib, the account becomes Deleted Account. May I ask why?
I didn't do anything after I logged in

**Comment by azkadev** [comment]
> A few minutes after logging into my tdlib, the account becomes Deleted Account. May I ask why? I didn't do anything after I logged in

Telegram has too many spammers so it's possible to be on guard against auto-deleting all accounts that use 3rd party APIs/apps,

I feel it too, even though I don't use fire for detrimental actions such as spam / spreading hoax links / phishing scams
