### ISSUE TITLE
moving app to a different computer

### ISSUE THREAD

**Issue by culexjj** [tdlib/td#2813]
Hello,

I trying to make my java app (base on TDlib) on a different computer but I get  the well know error "java.lang.unsatisfiedLinkError  ... tdjni.dll: can't find dependent libraries"

I've already read similar Issues here  and I think I have copied all involved dll in c:\windows\system32 for avoiding troubles but it doesn't work

I've copied these dll but I think I've forget something

libcrypto-3-x64.dll
libssl-3-x64.dll
tdjni.dll
tdjson.dll
zlib1.dll
zlibd1.dll
legacy.dll

What do you think?

Culex

**Comment by culexjj** [comment]
by the way, I'm using version to 1.8.22

**Comment by levlam** [comment]
You can use https://github.com/lucasg/Dependencies to find the missing dependencies.

If you built a debug version, then you must also install Visual C++ Redistributable package.

**Comment by culexjj** [comment]
Hello levlam, 

It is strange, it was related with  Visual C++ Redistributable package but after installing them from here 'https://learn.microsoft.com/es-es/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version'  the problem still

Anyway, with the tool for finding the missing dependencies I have been able to fix it

Thank you very much.
