### ISSUE TITLE
[Advice] Need to find out if there're a way to fix an .ogg file broken due to using pause during recording the voice 

### ISSUE THREAD

**Issue by Proxyarja** [tdlib/td#2818]
**Related to [#27587 ](https://github.com/telegramdesktop/tdesktop/issues/27587) and [#3809](https://github.com/telegramdesktop/tdesktop/issues/3809)** 
I do realize that my request may not be related to the Telegram sphere and maybe it is better to be addressed by someone familiar with how audio files work. However, since the telegram is the source of this issue, maybe there is advice on what telegram mechanisms cause it and if the affected voice file can be reinstated.

### **Issue Description **
**Steps to reproduce:**
1. Initiate a voice message on the Android telegram app. 
2. Pause the record, wait some time (30-60 seconds).
3. Continue recording, finish, send voice.
4. Check the voice message in the desktop Telegram app (Windows 10). The voice cannot be listened, it appears with the file icon instead of the "play" icon and, upon clicking, attempts to be opened with the Systems software for audio instead of being played in Telegram.
5. The .ogg file, regardless of the software used to play it, **will end at the moment when the pause was used during recording**. At the same time, the file size indicates the file includes all the audio content. Converting to .mp3 format does not cure it.
6. The voice message can listened through the Android telegram app as intended without issues. At the same time, the file recorded in the described way will not appear in the telegram folder that stores voices, neither in the telegram cache. Since there's no option in the Android Telegram to download voice through the app, such files cannot be gathered through mobile Telegram at all.

Here is the file in question, if needed for investigation: https://filebin.net/jt8bkhrhjpwn5dme
The actual audio duration is about 42 minutes, not 15 seconds.

Let me know if I need to specify any details additionally.

**Comment by levlam** [comment]
This looks like a bug in the Android app and is unrelated to the mentioned Telegram Desktop bugs. Likely, the file is broken, but if you can listen it from Android, you can record it from another device or using a system-provided voice recorder, which will produce a valid audio file.

**Comment by dkaraush** [comment]
Thanks for the report, this is indeed issue on Android app! Pushed a fix on public beta, would be released in 10.9.3.
