### ISSUE TITLE
Problem with setting api id and api hash

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#282]
ive just compiled it by that way Riza umami said https://github.com/rizaumami/tdbot.git
but when i login to the account it will be deleted
now i wanna compile it with linux-ubuntu but i dunno where should i set the api id and api hash
i wanna compile it for linux version for running bots in lua scrip

**Comment by levlam** [comment]
api_id and api_hash can be changed from source code only. Just like in that pull request: https://github.com/rizaumami/tdbot/pull/1/commits/aa27cf59a5ec980a14cc277dba3451badf43a83a.

**Comment by Kia-Pashang** [comment]
@levlam no i dont wanna use rizaumami's way i just wanna c that where i can change it by my self

**Comment by levlam** [comment]
That's the only way to change api_id and api_hash in tdbot.

**Comment by Kia-Pashang** [comment]
@levlam Unfortunately when ill login to account with tdbot they will be deleted account after couple hours do you know where is the problem ?

**Comment by levlam** [comment]
No.
