### ISSUE TITLE
cannot edit message forwarded by bot

### ISSUE THREAD

**Issue by taskjunki** [tdlib/td#2820]
I have a telegram bot for forwarding group/channel messages to another channel/group, I need to edit message in the group/channel where am forwarding to if they are edited in the channel/group from which I am forwarding from, trying to do that with the editMessageText says  bad request message cannot be edited, please what can I do to this

**Comment by levlam** [comment]
Forwarded messages can't be changed. You can only forward again the messages after they were edited.
