### ISSUE TITLE
chat admin required for GetMegagroupStats

### ISSUE THREAD

**Issue by StegaDP** [tdlib/td#2821]
pyrogram.errors.exceptions.forbidden_403.ChatAdminRequired: Telegram says: [403 CHAT_ADMIN_REQUIRED] - The method requires chat admin privileges (caused by "GetMegagroupStats")

error might seem to be error of pyrogram, but i wouldn't say it is pyrogram's fault.

Notice: I'm group owner with all avaliable rights in my group

**Comment by RememberTheAir** [comment]
Pyrogram doesn't use tdlib. If you think this is a server-side error, ask the in-app support

**Comment by StegaDP** [comment]
isn't this method implemented only in Tdlib?

**Comment by levlam** [comment]
This isn't a TDLib method at all.
