### ISSUE TITLE
getting telegram messages from supergroup

### ISSUE THREAD

**Issue by gorefieend** [tdlib/td#2823]
hello, what is the fastest possible way to get message from specific telegram supergroup? i know there are 3 way how to get a message: server push, polling and long polling.... is it ok so use all 3 methods at the same time?

also... what would you recommend me to do, if i wanna get the supergroup message as fast as user-bot as possible? :) thanks!

**Comment by gorefieend** [comment]
everywhere is the "fastest way". that is why i need i need it "as fast as POSSIBLE = mean without getting banned

 i know there are 3 way how to get a message: server push, polling and long polling.... is it ok so use all 3 methods at the same time?

**Comment by levlam** [comment]
There is no such thing as "polling and long polling" in Telegram apps regarding message fetching.

**Comment by gorefieend** [comment]
i mean using methods to get messages in user-bot with API...

polling (asking for updates in a certain time window) and long polling (0ms poll) and server push are real methods how to get messages from telegram with user-bot and API
