### ISSUE TITLE
Receiving messages is stopping intermittently

### ISSUE THREAD

**Issue by pranavkulkarni7** [tdlib/td#2826]
From last three days, I am observing that the message-receiving is getting stopped intermittently for 40 mins to an hour and then messages incoming starts again. Anyone has faced this issue recently or earlier?
I am using tdlib version: 1.8.23, which was working fine before 3-4 days.

Kindly help.

**Comment by levlam** [comment]
How many items are returned by the call to `getActiveSessions`?

**Comment by pranavkulkarni7** [comment]
@levlam thanks for the response.
How can I find that in the service which is already running?

**Comment by levlam** [comment]
Check in any other app of the user.

**Comment by pranavkulkarni7** [comment]
@levlam 
There are multiple tdLib sessions, out of which one is current and 4 are historical.
Can this be the reason for message interruption?

**Comment by pranavkulkarni7** [comment]
Can someone please provide any hints around this? Additionally, the message volume is reduced to less than half.

**Comment by levlam** [comment]
There should be no issues. Do you have the issue in a specific joined chat?

**Comment by pranavkulkarni7** [comment]
yes, there are multiple chats from which the messages are not coming in. The messages were coming earlier from the same channel earlier.

**Comment by pranavkulkarni7** [comment]
yes. I am part of the chats.

**Comment by levlam** [comment]
Despite possible. I see no specific reason for message delivery delays to be that big.
