### ISSUE TITLE
Receiving message history from several chats at once

### ISSUE THREAD

**Issue by MorozovStVl** [tdlib/td#2827]
Good evening

I'm making a single feed that should contain messages from different chats (sorted by time). Is there a way to do this without making multiple GetChatHistory() requests to each chat?
Tried to use SearchMessages(), but it returns an empty list if you don't specify a query string.

Help me please

**Comment by levlam** [comment]
There is no. You must call `getChatHistory` for all chats in question and merge the results manually.

**Comment by MorozovStVl** [comment]
Maybe the searchGlobal() function will help me?
https://core.telegram.org/method/messages.searchGlobal

As far as I understand, this is a “pure” Telegram API and it is not in TdLib.
Right?

**Comment by MorozovStVl** [comment]
Thanks for your reply!

It's strange that it won't work out. In one of the projects, messages from all chats are received using global search.

self.request = functions.messages.SearchGlobalRequest(
                 q=search or '',
                 filter=filter,
                 min_date=None,
                 max_date=offset_date,
                 offset_rate=0,
                 offset_peer=types.InputPeerEmpty(),
                 offset_id=offset_id,
                 limit=1
             )

https://github.com/LonamiWebs/Telethon/blob/acfde7132b20e0d857b2e0886982461a0d8f7da4/telethon/client/messages.py?plain=1#L77
