### ISSUE TITLE
tdlib Versionsnumber

### ISSUE THREAD

**Issue by JnZn558** [tdlib/td#2828]
Are there version number defined in source code? For example MAJOR 18 MINOR 26 for example, if yes, where do I find the version defines? I could not find about it

**Comment by pannu5788** [comment]
no

**Comment by levlam** [comment]
If you use JSON interface, you can use `td_execute` with `getOption("version")` to get TDLib version in runtime.

If you want instead to get the version from the source code, then you can check https://github.com/tdlib/td/blob/b41f3219dc5a79c337f4c1d128cf6aae60f00a1c/CMakeLists.txt#L9.

If you use a statically typed C/C++ interface, then you can only support one specific version of the library.
