### ISSUE TITLE
Any Demo for ios？

### ISSUE THREAD

**Issue by Z-figaro** [tdlib/td#283]
I follow this： https://github.com/tdlib/td/tree/master/example/ios
But it's not work。
Can anyone help me understand  how to build this for ios？？？

**Comment by levlam** [comment]
What is not working?

You can take a look at https://github.com/leoMehlig/TDJSON as an example of a prebuilt framework for iOS using TDLib.

**Comment by WingedDoom** [comment]
Maybe it's time to provide your own proper example and a build script for iOS (one that won't generate. a .dylib), instead of linking other 3rd party repositories?

**Comment by levlam** [comment]
Thanks to @Kylmakalle, [example/ios](https://github.com/tdlib/td/tree/master/example/ios) now creates a fully-featured XCFramework, which can be used out of the box.
