### ISSUE TITLE
How to understand that this is a link to a bot?

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2831]
I have a link to the @HelpBot bot. How to understand that this is a bot. Which method should I call or how should I pre-prepare @HelpBot so that when calling `getInternalLinkType`, I get `internalLinkTypeBotStart`?
When processing links, I use this `getInternalLinkType` method.

**Comment by levlam** [comment]
`User` object contains `type` of the user.

To create a link of specific type you should use `getInternalLink` unless documented otherwise.
