### ISSUE TITLE
Share phone number with bot

### ISSUE THREAD

**Issue by starkdm** [tdlib/td#2833]
How can I send my contact to the bot in chat? The documentation for [sharePhoneNumber](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1share_phone_number.html) says that the user must be a mutual contact. But the bot cannot be added to contacts.

I use TDLib 1.8.21

Code example:

```
Client = new TdClient();
await Client.SetTdlibParametersAsync(databaseDirectory: DatabaseDir, 
    apiId: apiId, 
    apiHash: apiHash, 
    systemLanguageCode: systemLanguageCode, 
    deviceModel: deviceModel, 
    systemVersion: systemVersion, 
    applicationVersion: version);
await Client.SharePhoneNumberAsync(chatId);
```

Everything works without exceptions, but the contact is not sent. The text message is sent, the contact is not.

**Comment by levlam** [comment]
To send a contact you need to use `sendMessage` with `inputMessageContact`.

**Comment by starkdm** [comment]
@levlam Thanks! It works.

```
await Client.SendMessageAsync(chatId, inputMessageContent: new InputMessageContent.InputMessageContact() {
    Contact = new Contact() { PhoneNumber = PhoneNumber }
});
```
