### ISSUE TITLE
PHP code fails to compile: `Unsupported tl-schema version -1`

### ISSUE THREAD

**Issue by barracuda156** [tdlib/td#2835]
```
[ 10%] Generate common TL source files
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/td-1.8.0/td/generate && /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common && /opt/local/bin/php81 DoxygenTlDocumentationGenerator.php scheme/td_api.tl auto/td/telegram/td_api.h
Unsupported tl-schema version -1
/bin/sh: line 1: 67984 Abort trap              /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common
make[2]: *** [td/generate/CMakeFiles/tl_generate_common] Error 134
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build'
make[1]: *** [td/generate/CMakeFiles/tl_generate_common.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
What could be the reason for this?

**Comment by barracuda156** [comment]
README actually claims that `PHP (optional, for documentation generation)`, but I cannot find a way to get rid of PHP here.

**Comment by barracuda156** [comment]
Same error if building with Ninja:
```
[34/432] cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/td-1.8.0/td/generate && /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common && /opt/local/bin/php81 DoxygenTlDocumentationGenerator.php scheme/td_api.tl auto/td/telegram/td_api.h
FAILED: td/generate/CMakeFiles/tl_generate_common /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/CMakeFiles/tl_generate_common 
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/td-1.8.0/td/generate && /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common && /opt/local/bin/php81 DoxygenTlDocumentationGenerator.php scheme/td_api.tl auto/td/telegram/td_api.h
Unsupported tl-schema version -1
/bin/sh: line 1: 73904 Abort trap              /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common
```

**Comment by barracuda156** [comment]
Also the same error when building from 586bc784138042d2710168cd0b29f5dd6d415f45 (master):
```
[  4%] Generate common TL source files
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/td-586bc784138042d2710168cd0b29f5dd6d415f45/td/generate/auto && /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common && /usr/bin/php ../DoxygenTlDocumentationGenerator.php ../scheme/td_api.tl td/telegram/td_api.h
Unsupported tl-schema version -1
/bin/sh: line 1: 75681 Abort trap              /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build/td/generate/generate_common
make[2]: *** [td/generate/CMakeFiles/tl_generate_common] Error 134
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_tdlib/tdlib/work/build'
```

**Comment by levlam** [comment]
Do you have a big-endian CPU/OS?

**Comment by barracuda156** [comment]
> Do you have a big-endian CPU/OS? TDLib support only little-endian systems.

@levlam Yes, this is on a Big-endian system.

Is it possible to add support for BE systems? While I am running this on an old macOS, which the upstream may not be too motivated to support, Big-endian systems are supported in the modern versions of OpenBSD, FreeBSD and some distros of Linux. So it will benefit quite a number of people.

**Comment by levlam** [comment]
This would be hard to achieve, because it requires many changes in different parts of the code.

**Comment by barracuda156** [comment]
> This would be hard to achieve, because it requires many changes in different parts of the code.

Could you say if it is known to be broken or just nobody tested it? (I mean, beyond initial error – I have no idea at the moment what causes it and therefore how serious it is).

I am asking since FreeBSD, for example, does not seem to restrict it to LE archs: https://github.com/freebsd/freebsd-ports/blob/9c477091cee352b9e783062234ab276bbb61d16c/net-im/tdlib/Makefile (though of course it is possible that they never tried it as well).

Oddly, btw, they do not declare a dependency on any `php` version – can it be actually bypassed?

P. S. Though on Linux the error has been reported earlier: https://github.com/tdlib/td/issues/364
And OpenBSD refers to it: https://github.com/openbsd/ports/blob/737babba1cb7d9d288b6bfe477ffd7b4d36229c9/net/tdlib/Makefile#L1-L2

**Comment by levlam** [comment]
It is known to be broken. There are a few other places that are known to work only on little-endian systems, and unknown number of unidentified places that will work incorrectly on big-endian systems.

Current;y, TDLib will not build on big-endian systems, which is better than failing in runtime.

PHP is optional for TDLib building and the issue has nothing to do with PHP.

**Comment by barracuda156** [comment]
@levlam Is there a ticket or discussion to track the issues on Big-endian? There may be people interested to help here, since this is OS-agnostic problem.

**Comment by levlam** [comment]
You have already mentioned the issue 364. There is no complete list of features that must be ported to big-endian, but it would be a pretty long list. At least all usages of memcpy, as<..> and reinterpret_cast must be checked and some of them must be rewritten.

**Comment by barracuda156** [comment]
@levlam You close this as _completed,_ has it been fixed?

**Comment by levlam** [comment]
It was closed as duplicate of the issue 364.

**Comment by barracuda156** [comment]
@levlam Got it, thank you. An open duplicate is unneeded, of course.
