### ISSUE TITLE
Unknown error in  class "messageReplyToMessage"

### ISSUE THREAD

**Issue by ZdGram** [tdlib/td#2836]
@levlam 
If the bot reply to a message in a content_protector group, the res will be "protected content and can't be forwarded is printed"

But when the content protection is cancelled, it works normally

**Comment by al0mda** [comment]
Me too my friend

**Comment by levlam** [comment]
Check documentation of `inputMessageReplyToMessage.chat_id`, for which you pass a wrong value:
> The identifier of the chat to which the message to be replied belongs; pass 0 if the message to be replied is in the same chat. Must always be 0 for replies in secret chats. A message can be replied in another chat or topic only if message.can_be_replied_in_another_chat
