### ISSUE TITLE
Can someone show the references of the SetAuthenticationPhoneNumber() function

### ISSUE THREAD

**Issue by EllaSedova** [tdlib/td#2839]
I want to register new users in telegram by phone number and manually enter the code from the sms.
I can't get the SetAuthenticationPhoneNumber()  to work.
As I understand it, to run this function, you need to create a tdlibClient  using NewClient(). But how to create an empty tdlibclient?

**Comment by levlam** [comment]
SMS can be received only by official mobile Telegram apps.

**Comment by EllaSedova** [comment]
Are there any other ways to register a new user using your own app?

**Comment by levlam** [comment]
No. Other apps, including official Telegram desktop apps, can't register new users.
