### ISSUE TITLE
/Users/yu.liao/Library/Developer/CoreSimulator/Devices/5EE3FD40-55A2-4C0D-9414-19925F59E7D8/data/Containers/Bundle/Application/79AA79E2-08DA-435F-B325-124F10A7961A/bicai.app/Frameworks/libtdjson.dylib (which was built for iOS 10.99）

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#284]
When I run the program on iPhone4s, there is an error
` /Users/yu.liao/Library/Developer/CoreSimulator/Devices/5EE3FD40-55A2-4C0D-9414-19925F59E7D8/data/Containers/Bundle/Application/79AA79E2-08DA-435F-B325-124F10A7961A/bicai.app/Frameworks/libtdjson.dylib (which was built for iOS 10.99)
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib
 in /Users/yu.liao/Library/Developer/CoreSimulator/Devices/5EE3FD40-55A2-4C0D-9414-19925F59E7D8/data/Containers/Bundle/Application/79AA79E2-08DA-435F-B325-124F10A7961A/bicai.app/Frameworks/libtdjson.dylib `

**Comment by levlam** [comment]
It doesn't look like the whole error message, there should be something before it.

Is it work on emulator or another iPhone?

**Comment by liaoyu1992** [comment]
It is worked on emulator，the iOS 8.2 version of iphone4s。

**Comment by levlam** [comment]
Could you show the whole error message?

**Comment by liaoyu1992** [comment]
That's all the error message.When the application starts, it will quit and report the error.

**Comment by levlam** [comment]
The full message should look like
```
Dyld Error Message:

  Symbol not found: _XPC_COALITION_INFO_KEY_BUNDLE_IDENTIFIER

  Referenced from: /usr/lib/system/libsystem_stats.dylib (which was built for iOS 10.11)

  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libxpc.dylib

in /usr/lib/system/libsystem_stats.dylib
```
and there should be even more information, like shown [there](https://forums.developer.apple.com/thread/5612).

**Comment by levlam** [comment]
Given that iOS build example was rewritten and creates a universal XCFramework, there is no need to keep this 3-year-old issue open, Everything is expected to work now.
