### ISSUE TITLE
I need to build libtdjsonandroid to work on android using Unity (C#)

### ISSUE THREAD

**Issue by nikiraa** [tdlib/td#2841]
I need to build libtdjsonandroid to work on android using Unity (C#)
Please help me build dll. I configured everything as indicated in the [**comment**](https://github.com/tdlib/td/issues/77#issuecomment-640719893):

![image](https://user-images.githubusercontent.com/83750645/162142914-ff827972-07d3-4617-b978-fff75e532dea.png)

After **third_party/crypto/build-all.sh** I have few errors:

![image](https://user-images.githubusercontent.com/83750645/162143414-ca412a9f-4243-49cd-8ee4-af1e101d4dcc.png)

I tried [downloading ](https://developer.android.com/ndk/downloads) the NDK but got the **same** error

![image](https://user-images.githubusercontent.com/83750645/162144771-c039ed03-e479-42dd-ac71-564bca2f354f.png)

_Originally posted by @YauheniKhadanovich in https://github.com/tdlib/td/issues/77#issuecomment-1091180569_

**Comment by levlam** [comment]
It looks like you specified Windows-style path "C:users/..." instead of "/c/users/...".

Also, the scripts were written for NDK r20 and may not work with newer Android NDK.
