### ISSUE TITLE
user-bot rate limit

### ISSUE THREAD

**Issue by gorefieend** [tdlib/td#2845]
hello,

how often can i call function get_Messages() go manually poll for a new messages as user in supergroup?

every 50ms? every 100ms? 500ms?

**Comment by levlam** [comment]
You must not call getMessages to get new messages in a supergroup. All new messages in joined or opened chats are received from TDLib in updates.

**Comment by ne0c0de** [comment]
sometimes Telegram lacks on sending new messages on heavy groups (which has 10k+ users) so calling getMessages is a good way to get news messages but it has limits to call for every X ms. I guess @gorefieend is asking what's the best interval to call this method in order to avoid ban.

**Comment by levlam** [comment]
There is no. Apps are not supposed to call getMessages with identifiers of non-existent messages.

**Comment by gorefieend** [comment]
@ne0c0de  exactly!!

what is the max possible interval without getting limited? in ms

**Comment by Tidalikk** [comment]
@gorefieend Have you found any documentation about the api limit?

**Comment by gorefieend** [comment]
nope. it is not public
