### ISSUE TITLE
Isn't there an instant way to change the hint password?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2846]
Yes, I know this isn't done all the time, but why doesn't the changePasswordHint method exist?

Why do you have to delete the password first then change to a new password then fill in the password hint

**Comment by azkadev** [comment]
btw sorry my english is bad

**Comment by levlam** [comment]
You are wrong. You can provide a new hint while changing the password to a new one, or even use the same new password and change just the hint.

**Comment by azkadev** [comment]
thanks
