### ISSUE TITLE
How to buy/subscribe to Telegram Business/Premium on Test DC?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2847]
Can I buy premium / business in test mode? I want to try the business feature and try to test develop an auto respond bot

I looked for the method but it's not there :(

![Screenshot from 2024-04-14 18-24-15](https://github.com/tdlib/td/assets/82513502/36264571-d33c-4402-a8f4-13e6f5f0c89d)
![Screenshot from 2024-04-14 18-23-45](https://github.com/tdlib/td/assets/82513502/64637f4e-0cd7-40fb-a4f6-d000fc80ca65)

**Comment by levlam** [comment]
All methods for purchasing of Telegram Premium subscription works in Test DC. You can use test card 4242 4242 4242 4242 to pay for it through Store purchases, @Premium bot, direct gift and many other ways.

**Comment by azkadev** [comment]
thanks
