### ISSUE TITLE
Problem with secret messaging in Telegram X

### ISSUE THREAD

**Issue by khafan11** [tdlib/td#2848]
Unfortunately, when I use Telegram X's secret message
Usually, after creating a secret message, it is canceled immediately on other party's app
Or if it is not canceled, the other party's messages will not be shown to me
But my messages are sent!

sometimes It seems ok too, The message is sent and received on both sides , but the other party sends a gif and it is canceled immediately !!!

Telegram on the other side is Vanilla Telegram version 10.10.1 and 10.11.0 and Cherrygram version 8 is based on the same Telegram 10.10.1

My Telegram X version is 0.26.7.1698-arm64-v8a

**Comment by khafan11** [comment]
By "Vanilla Telegram" I meant the original Telegram
 this happens only when I use Telegram X
This does not happen if I use other telegrams 
I saw this problem mentioned in Telegram X group, and apparently its programmer said that it is better to report this issue in tdlib GitHub.

**Comment by levlam** [comment]
It will definitely happen with all other apps to which the original Android Telegram app will send an incorrectly encoded GIF, except the Android app itself which has no separate scheme for secret chats. Because of this it can send incorrectly serialized messages and can parse some of them.

**Comment by levlam** [comment]
This should have been fixed in the latest version of the original Android Telegram app.
