### ISSUE TITLE
provide dll file.

### ISSUE THREAD

**Issue by imkaka** [tdlib/td#285]
to support C# Programs as build process is not working and too complex.

**Comment by levlam** [comment]
What don't work for you in our [example](https://github.com/tdlib/td/tree/master/example/csharp)?

**Comment by imkaka** [comment]
Sir i'am not able to build the file following the instructions for Windows and C# , Please Can you elaborate it more clearly?

**Comment by levlam** [comment]
What have you tried and what you don't understand?

**Comment by UnblockerUsername** [comment]
I managed to compile for C#.
As a result, I simply received a .so file and connected it to the project. According to the instructions of the lion in readme.
