### ISSUE TITLE
[static const] please write code that complies with the C++ standard

### ISSUE THREAD

**Issue by ilyakurdyukov** [tdlib/td#2851]
These repeated lines in `test/secret.cpp` are not compliant with the standard:

```c++
  static const int32 ID = 651135312;
```

Even if it "works" with GCC under -O2.

If you are using `static const` then you MUST declare those variables outside the class in one of the sources, like this:

```c++
const int32 messages_dhConfig::ID;
const int32 encryptedChat::ID;
```

All the `static const` for all the classes. Or you'll get a link-time error, at -O0 for GCC or even at -O3 for EDG-based compilers.

**Comment by ilyakurdyukov** [comment]
Ok, I see that this is partially fixed in the latest version of the code, and for EDG it will work, but still some classes are missing, I don't see where `messages_sentEncryptedMessage::ID` is declared outside the class.

**Comment by levlam** [comment]
This is a valid C++ code and no explicit definition is needed unless the field is odr-used. For example, revision n4713 of C++ standard in the section "Static data members" says:
> If a non-volatile non-inline const static data member is of integral or enumeration type, its declaration
in the class definition can specify a brace-or-equal-initializer in which every initializer-clause that is an
assignment-expression is a constant expression (8.6). The member shall still be defined in a namespace scope
if it is odr-used (6.2) in the program and the namespace scope definition shall not contain an initializer. 

You can also find at https://www.stroustrup.com/bs_faq2.html#in-class that this is the intended way to define static const fields in C++.
