### ISSUE TITLE
How often does TDLib phone back to server to decide on the connection state?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2852]
As always with my queries, its use case is for Apple watchOS/HTTP. 

Curious with how it works, and wondering if there's any fixed timeouts/rates to play around with, for experimentation purposes. (Not a bug report or anything like that, just a technical question, which reading from source code and logs, confuses me so far)

**Comment by levlam** [comment]
If the current user is "online", then connection aliveness is checked every few seconds. Usually, every 3-7 seconds depending on the roundtrip time.
