### ISSUE TITLE
Delays in getting message updates from some specific channels

### ISSUE THREAD

**Issue by Tidalikk** [tdlib/td#2853]
I'm using the lib with python, using the example that was provided, so that's the code i'm using with no changes.

But some messages from specific channels are getting delays of 2 or more minutes while others channels are almost instant.

Is this working as intended or is it a bug? Is there a workaround to get more constant message updates?

**Comment by levlam** [comment]
Messages in channels aren't intended to be delivered in real-time, so this works as intended.

**Comment by Tidalikk** [comment]
Is there a workaround for this? 

Correct me if I'm wrong but doesn't for example the mobile app use this API? And the app always gets the channel updates in real time.

So wouldn't it be possible to replicate this?

**Comment by levlam** [comment]
None of the app get channel updates in real time.

**Comment by Tidalikk** [comment]
> None of the app get channel updates in real time.

The delay im talking about never happens on the telegram app. Even on this channels it's always instant, the date on the notification of the phone matches the date that the message was published to the channel.

Which does not happen when i use the example code provided.

So there must be a difference.

Do you know why this difference happens? And is there no workaround to have the same performance as the phone app?

**Comment by levlam** [comment]
Messages can't be delivered simmultaneously to all users, so there can be some difference, but there are no workarounds. Messages will be delivered when appropriate.
