### ISSUE TITLE
step stuck：Please enter phone number

### ISSUE THREAD

**Issue by tearsmoon** [tdlib/td#2854]
![QQ截图20240422162237](https://github.com/tdlib/td/assets/37906435/faa9bac9-61d9-409a-99a5-d3074816704f)

I kept getting stuck after entering the phone number,
After checking, my network is fine and I can access Telegram,
and the tdlib.log is empty,
May I ask what's going on?

**Comment by levlam** [comment]
You need to increase log verbosity level to see details. For example, pass 4 to `Client.execute(new TdApi.SetLogVerbosityLevel` instead of 0.
