### ISSUE TITLE
[ASK] getChat delayed

### ISSUE THREAD

**Issue by andigian16** [tdlib/td#2856]
Hi, I need help here.

I use getChats to get the chats IDs. And then I use getChat for each chatID to get latest message.
the issue is the message that i got from tdlib is diff with that showing in apps.

lets say I send a new message to my account using another account.
in my apps showing the latest message, but when using tdlib, what i got is not the last message. the latest message still the previous message. not the one i sent.

`await client.login();
const chats = await client.invoke({
            _: 'getChats',
            limit: 10
 });

if (chats && chats.chat_ids.length > 0) {
            for (const chatID of chats.chat_ids) {
                chat = await fetchTelegramChat(chatID, client)
                // Handle the message here
            }
}

await client.close();`

can anyone help me what happen with this?

**Comment by levlam** [comment]
You need to handle `updateChatLastMessage` updates to always know the last messages of chats. In some cases you need to open the chat using `openChat` to update its last message.

**Comment by andigian16** [comment]
@levlam, I did test with your suggestion, seems the openChat didn't work for my case. fetchTelegramChat still cant get latest message.

**Comment by levlam** [comment]
You need to handle `updateChatLastMessage` after calling `openChat`. If you receive no updates, then there are no new messages for your account in the chat.

**Comment by andigian16** [comment]
@levlam. I did try your suggestion above. but I got this error when testing it. can you give me example how to do that?
![image](https://github.com/tdlib/td/assets/167864651/92dc7a64-3093-48cb-8fc7-e01aeaf14efa)
![image](https://github.com/tdlib/td/assets/167864651/3d5529b0-ccc1-4aaf-ad98-5f99c13fa2a4)

**Comment by levlam** [comment]
`updateChatLastMessage` isn't a request. See https://core.telegram.org/tdlib/getting-started.
