### ISSUE TITLE
Chat not found 400

### ISSUE THREAD

**Issue by LsdLucifer** [tdlib/td#2857]
Hello. I have a user who should join a group via its chat ID. However, the user cannot do this because... TO JOIN THE GROUP, YOU NEED TO RECEIVE INFORMATION ABOUT THE GROUP, WHICH CANNOT BE OBTAINED WITHOUT JOINING IT...

**Comment by LsdLucifer** [comment]
Can I somehow retrieve data about groups (chats) from another user-bot's db.sqlite for my new user-bot?

**Comment by levlam** [comment]
No. You can't access chats by their identifier. You must find them in the same way as you would do in any Telegram app.

**Comment by LsdLucifer** [comment]
How can I implement functionality for my program to automatically join a group and subscribe to it?

**Comment by LsdLucifer** [comment]
@levlam How can I implement functionality for my program to automatically join a group and subscribe to it?

**Comment by levlam** [comment]
You need to do exactly the same actions as you would do in a Telegram app.

**Comment by LsdLucifer** [comment]
Why does TdApi.JoinChat even exist then? I want my program to add a user to a group. How can I do that? I'm not interested in doing it manually through Telegram.

**Comment by LsdLucifer** [comment]
@levlam Why does TdApi.JoinChat even exist then? I want my program to add a user to a group. How can I do that? I'm not interested in doing it manually through Telegram.

**Comment by levlam** [comment]
You must do the same actions with appropriate methods.

**Comment by LsdLucifer** [comment]
@levlam When I use this method, I get a 400 error 'chat not found,' as I mentioned above. Please provide an example of using this method.

**Comment by levlam** [comment]
You don't enter chat identifier in apps. You must find the chat first in the same way you do in the apps.

**Comment by LsdLucifer** [comment]
@levlam I understand. You're suggesting that I manually enter the Telegram app and join the group. However, I have a link and a chat ID for the group. I want to join it automatically without opening Telegram. How can I use tdlib Java to join groups using their links or chat IDs? Ideally, I'd like to join via a regular link. (I've been able to join using invitation links, but I need to join the group via a regular link).

**Comment by levlam** [comment]
No, I suggest that you call the same methods, you would use in any other app.

Any internal link can be processed using `getInternalLinkType` and following documentation for the returned object.

**Comment by harlene83774179** [comment]
Fuck your comment

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 30 Apr 2024 at 10:03 PM, Aliaksei ***@***.***> wrote:   


No, I suggest that you call the same methods, you would use in any other app.

Any internal link can be processed using getInternalLinkType and following documentation for the returned object.
