### ISSUE TITLE
got error when Install TDLib in MS VS Community 2017

### ISSUE THREAD

**Issue by xiaoming1970** [tdlib/td#286]
I ran follow to install TDLib in VS Community 2017 but got error. What could be the cause? Thanks.

PM> Install-Package TDLib -Version 1.2.0

Install-Package : Could not install package 'TDLib 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', 
but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package 
author.
At line:1 char:1
+ Install-Package TDLib -Version 1.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.0369354

**Comment by levlam** [comment]
This isn't an official package, so we unlikely can help.

**Comment by xiaoming1970** [comment]
OK.
