### ISSUE TITLE
Unsupported proxy link in tgx

### ISSUE THREAD

**Issue by sepehrbrj** [tdlib/td#2861]
![20240425_134009.jpg](https://github.com/tdlib/td/assets/55192376/4530fd05-82af-4406-9372-53bc21c32296)

https://t.me/mehduox_vpn/1700
https://t.me/PewezaVPN/12425

**Comment by levlam** [comment]
The links are invalid, which can be seen by presence of a lot "A" characters at the end, or "=", or "%" character that must never be used in a valid proxy link secret. You need to find other source of proxy that will not post random garbage.

**Comment by sepehrbrj** [comment]
> The links are invalid, which can be seen by presence of a lot "A" characters at the end, or "=", or "%" character that must never be used in a valid proxy link secret. You need to find other source of proxy that will not post random garbage.

They work fine in official version of telegram

**Comment by levlam** [comment]
Likely, you can truncate the secret to 16 bytes to make the link work in Telegram X, but this doesn't make the initial link correct.

**Comment by sepehrbrj** [comment]
> Likely, you can truncate the secret to 16 bytes to make the link work in Telegram X, but this doesn't make the initial link correct.

How can I shorten the link to 16 bytes?

**Comment by levlam** [comment]
Decode secret part of the link to a binary with base64_decode, then truncate it to 16 bytes, then encode it with base64url_decode. You can do that manually, for example, using https://cryptii.com/pipes/base64-to-hex. The resulting link will be accepted, but given that initial links are invalid there is no any guarantee that resulting link will work.
