### ISSUE TITLE
Why is 'upload_max_fileparts_premium' not being used?

### ISSUE THREAD

**Issue by iiscosd3** [tdlib/td#2863]

**Comment by iiscosd3** [comment]
Could've increased the upload speed in general i suppose.

**Comment by levlam** [comment]
Because it has no use cases and it can't increase performance in any way.

**Comment by iiscosd3** [comment]
What if we start uploading chunks in parallel? Does increasing `static constexpr size_t MAX_PART_SIZE` (td/telegram/files/PartsManager.h) affect the upload speed in any way?

**Comment by levlam** [comment]
Yes, increasing part size decreases upload speed.

**Comment by iiscosd3** [comment]
Are you sure it works that way? increase the chunk size -> decrease upload speed? I think it at least should remain the same if not get faster due to the bigger chunks being uploaded. I am speaking of the file being uploaded, in general.

**Comment by iiscosd3** [comment]
Are you sure that 'calc_part_count(expected_size_, part_size_) > MAX_PART_COUNT' conditions around the file are correct even? Whatever increases the chunk size is never being triggered, basically, due to this part
https://github.com/tdlib/td/blob/master/td/telegram/files/PartsManager.cpp#L137 so it always remains to 65k bytes 

I tried going for 512 << 10, it did work, tried  1024/2048 did not, but its whatever, the issue is its not even trying to reach 512kb by default, because its never greater than MAX_PART_COUNT, even tho the part_size part of those conditions work perfectly fine, shall it be < instead of >?

**Comment by levlam** [comment]
Yes, the code is correct and works in the best possible way.

**Comment by iiscosd3** [comment]
Just try the formula on 4gb,
`(4294967296 + 524288 - 1) / 524288 = 8192`, and MAX_PART_COUNT_PREMIUM is 8000?

**Comment by levlam** [comment]
Telegram files are up to 4000 MB.

**Comment by iiscosd3** [comment]
So only 4000000000 bytes? then why is MAX_FILE_SIZE 4194304000?

**Comment by iiscosd3** [comment]
Could you tell me instead of MB in bytes, and specify whether its in Si or not?

**Comment by levlam** [comment]
Because 4194304000 = 4000 * 1024 * 1024.

**Comment by iiscosd3** [comment]
I am asking what is the limit in bytes bruh, MB is Si, which is 40000...

**Comment by iiscosd3** [comment]
we have set_dialog_has_scheduled_database_messages_impl why cant we expose it to api? but instead of set - get? at least im gonna know what dialogs to look up for and not iterate through 1k dialogs to see which ones have either unsent or pending messages
