### ISSUE TITLE
Clear uploading files/unsent/pending messages queue

### ISSUE THREAD

**Issue by iiscosd3** [tdlib/td#2867]

**Comment by iiscosd3** [comment]
Is there any method to clear it entirely? it keep trying to upload files, the only way i have noticed was by logging uploadFile, so there's no actually indicator of the file being uploaded exposed to the application, need something to clear the uploading media cache before running into the ui

**Comment by iiscosd3** [comment]
But before you say something about `cancelPreliminaryUploadFile`
```js
			await client.invoke({
				'_': 'cancelPreliminaryUploadFile',
				file_id: update.file.id
			});
```

it wont help the case, it remains uploading until i physically either rename file or delete it, making in inaccessible

**Comment by levlam** [comment]
You need to delete the yet unsent message with the file to cancel its uploading.

**Comment by iiscosd3** [comment]
> You need to delete the yet unsent message with the file to cancel its uploading.

How am i supposed to fetch the link of unsent messages from tdlib?

**Comment by levlam** [comment]
You receive the message when call `sendMessage`.

**Comment by iiscosd3** [comment]
> `sendMessage`

I just mentioned, the client is being restarted, so how do i delete unsent message lol? its tdlib internals routine, how do i get access to unsent by tdlib messages tell me?

**Comment by iiscosd3** [comment]
Since you can't answer that question in the proper way lemme ask you this, how do i reset unset messages all at once?

**Comment by levlam** [comment]
You receive updateNewMessage with yet unsent messages after app restart.

**Comment by levlam** [comment]
> Since you can't answer that question in the proper way lemme ask you this, how do i reset unset messages all at once?

In exactly the same way as in any Telegram app. You open each chats with yet unsent message and delete yet unsent messages one by one.

**Comment by iiscosd3** [comment]
How am i supposed to know which messages were unset? getHistory?

**Comment by iiscosd3** [comment]
Why not to expose a single method that would go through database and delete all unsent by tdlib messages? It would be much easier

**Comment by levlam** [comment]
You receive all yet unsent messages from TDLib in updates.

> Why not to expose a single method that would go through database and delete all unsent by tdlib messages? 

Because this is never needed by Telegram apps.

**Comment by iiscosd3** [comment]
> You open each chat with yet unsent message and delete yet unsent messages one by one.

First you are asking to open the chats to see whether messages were sent or not, openChat (classtd_1_1td__api_1_1open_chat.html) causes status set to online i think, what if user's app got crashed and it is no in foreground, yet im trynna revoke file uploading/messages being sent?

> You receive all yet unsent messages from TDLib in updates.

When? On startup? I know i receive them after sendMessage/sendMessageAlbum, what if my app crashed and i didnt preserve them in my internal database, what do i do next? How exactly do i get them? What updates will i receive after starting the tdlib instance? Can u name a couple?

**Comment by levlam** [comment]
> When? On startup?

And on start up also. Apps aren't supposed to have their own database.

**Comment by iiscosd3** [comment]
> > When? On startup?
> 
> And on start up also. Apps aren't supposed to have their own database.

What updates will i receive after starting the tdlib instance? Can u name a couple related to unsentmessages?

**Comment by levlam** [comment]
`updateNewMessage`.

**Comment by iiscosd3** [comment]
lemme check idk why would i receive updateNewMessage on app start if i closed it with pending but if it actually sends then ok

**Comment by iiscosd3** [comment]
So i start uploading a new 4gb file, with premium on, i turn off app, lets say after 20 megabytes were done uploading, message is unsent yet, i log all events related to updateNewMessage (even its name says its unrelated to everything i am speaking about yet u keep suggesting it), i only keep getting uploadFile and no updateNewMessage with status pending, not only no pending, no such events at all, so how do i get all unsent messages, again

**Comment by iiscosd3** [comment]
we have set_dialog_has_scheduled_database_messages_impl why cant we expose it to api? but instead of set - get and for pending messages? at least im gonna know what dialogs to look up for and not iterate through 1k dialogs to see which ones have either unsent or pending messages

**Comment by iiscosd3** [comment]
Levlam: dont use preliminaryUploadFile directly, use sendMessage
Me: Ok bro
Me: how do i cancel file upload? cancelpreliminary doesnt work nor does deleteFile
levlam: delete the message
me: what if i restarted tdlib and forgot message id, should i store message ids?
levlam: just open every chat and delete messages
me: what if we have 1000+ chats it will take time?
levlam: *silence*, then theres always updateNewMessage updates on tdlib startup
me: i just checked theres none, so how do i stop file upload sent via sendMessage? should i use my own databases to store info?
levlam: no
me: then how?


so we went all this path to find out that preliminary is the way to go you need to provide us with proper api instead of asking us running into rate limits on gethistory, 1000+ chats to find out if some of them are uploading files, not only updateFile doesnt contain no useful info about wheres the file going to be posted at, but also is useless and doesnt catch up on cancelPreliminaryUpload

let me repeat once again, 1000 chats, to find 2 of which somewhere in the middle that needs messages revoked, now imagine how much time we have to spend and how many megabytes of the file will be uploaded during our attempts?

**Comment by iiscosd3** [comment]
at least make your sendMessage/updateFile respect cancelPreliminaryUploadFile

**Comment by levlam** [comment]
You must never called `cancelPreliminaryUploadFile` for files for which `preliminaryUploadFile` wasn't called.

**Comment by levlam** [comment]
All being sent messages are received in `updateNewMessage` updates by the app. Apps can keep track of all yet unsent messages in any point in time if they wish to.

**Comment by iiscosd3** [comment]
> You must never called `cancelPreliminaryUploadFile` for files for which `preliminaryUploadFile` wasn't called.

It clearly should be allowed, since if we call things like client.close() they cancel upload as well even on being sent messages
Why not to make an exception for files which are clearly using preliminaryUploadFile in sendMessage/sendMessageAlbum to let us cancel their upload and cause the fail? Its not a big deal, make it possible

> All being sent messages are received in updateNewMessage updates by the app.

Again you just said apps shouldnt use any additional databases for tracking messages you contradict youself without realizing it
lets imagine that databse wasnt close so method client.close() wasnt called, we start tdlib instance again and it proceed uploading, thats the issue do u not understand it? 

> Apps can keep track of all yet unsent messages in any point in time if they wish to.

explain in what way they supposed to track such things if we neither have getAllUnsentMessages (which is easy to implement) and considering ur suggestion of not using custom databases for tracking unsent messages?
also leave your suggestion with gethistory out of scope its not the solution and you know it i already explained what it might run into

**Comment by levlam** [comment]
> Why not to make an exception for files which are clearly using preliminaryUploadFile in sendMessage/sendMessageAlbum 

The only files using `preliminaryUploadFile` are the files for which `preliminaryUploadFile` is called.

> to let us cancel their upload and cause the fail

Apps don't fail message sending when restarting.

**Comment by iiscosd3** [comment]
Can you stop avoiding the direct question? instead just say: theres no way to clear pending states because i havent thought of such cases where a user wouldve needed to dismiss 4gb uploads during the app start, due to crash

pointless conversation all u said had nothing to do with reality honestly

**Comment by levlam** [comment]
I already said multiple times how to abort sending all yet unsent messages.

**Comment by iiscosd3** [comment]
your option is not applicable and will result into account bans on custom apis, proper way is to have a method to clear hem but whatever you say, as i said the only correct thing u mentioned was fetching through chats then fetching all unsent messages (get chats, get chat + get history (yet you dont know how many unsent messages is there, it can be 10k unsent messages) and deleteMessage on them, none of this is useful info
