### ISSUE TITLE
add_update_handler not working for channels

### ISSUE THREAD

**Issue by FredericKanoute** [tdlib/td#2868]
I´m developing an application for telegram with phyton and ```telegram.client```, and I have used the tutorial example which uses ```add_message_handler```.

The program works well when the message sender it's not on a channel. Every time a message is written by a sender in a single chat, it is received and processed instantly and successfully but, when the message is received in a channel, it only is  ```add_message_handler``` function invoked after the message is read manually on the android smartphone telegram application. 

If the message is not read on the smartphone, the function ```add_message_handler``` is not invoked.

Here is mi code:
````
from telegram.client import Telegram

tg = Telegram(
    api_id=00000000,
    api_hash='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    phone='+YYYYYYYYYYY',
    database_encryption_key='ZZZZZZZZZZ',
    tdlib_verbosity=7,
)

tg.login()

# this function will be called
# for each received message
def new_message_handler(update):
    print('New message!')
    message_content = update['message']['content'].get('text', {})
    message_text = message_content.get('text', '').lower()  
    chat_id = update['message']['chat_id']
    print(str(chat_id)+':'+message_text) 

tg.add_message_handler(new_message_handler)
tg.idle()
````
In the log, nothing strange is appreciated. Periodically, the messages alternate between 'Begin to wait for updates with timeout 1.000000' and 'End to wait for updates, returning object'.

I have also tried putting ``setOption`` ``online`` with ``true`` value and the result is the same, it works fine when the message is not posted on a channel.

I am convinced that I am not doing something correctly, but I don't know what it is.

Thanks in advance.

**Comment by levlam** [comment]
Check that you use the latest TDLib with your wrapper. You can check TDLib's version by calling `getOption("version")`.

**Comment by FredericKanoute** [comment]
Thank you very much for the reply.

This afternoon I installed it again on Ubuntu, so I understand that I am using the latest version.
The procedure used has been described in the tdlib installation instructions:

```sudo apt-get update
sudo apt-get upgrade
sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake clang-14 libc++-dev libc++abi-dev
git clone https://github.com/tdlib/td.git
cd td
rm -rf build
mkdir build
cd build
CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target install
cd ..
cd ..
ls -l td/tdlib
```

I tried again and the same happens, the program works well when the message is not received on a channel or group,
In this case, ```add_message_handler``` function only is invoked after the message or messages are read manually on the android smartphone or desktop telegram application.

**Comment by levlam** [comment]
Are you sure that the wrapper uses the manually installed TDLib version? You need to check this with `getOption`.

**Comment by FredericKanoute** [comment]
I have obtained the version and it tells me the following:

``` '@type': 'optionValueString', 'value': '1.8.5' ```

**Comment by levlam** [comment]
This is a very old version. Current TDLib version is 1.8.28.

**Comment by FredericKanoute** [comment]
I have tried updating the library in the wrapper to the latest version and now it works correctly.
Both the channel or group messages are received instantly.

Thank you very much for your help and your work!!!!!
