### ISSUE TITLE
Could you please remove the Airgram JS library from your docs. It doesn't support the lates TDLib version.

### ISSUE THREAD

**Issue by pahaz** [tdlib/td#2870]
[You can find it here](https://github.com/tdlib/td/blob/master/example/README.md#javascript). And at the moment it doesn't well maintained. [As you can see, the last update was 2 years ago](https://github.com/airgram/airgram/commits/master/)

**Comment by levlam** [comment]
It still an example of TDLib usage. One can see the examples and choose to use one of them, or create their own wrapper for the latest TDLib based on one of them.
