### ISSUE TITLE
`TdApi.SearchPublicChats` response is not identical to the official application

### ISSUE THREAD

**Issue by akulik512** [tdlib/td#2876]
I send the ` TdApi.SearchPublicChats` request to find channels/bots/groups/users by keyword but these are distinguished in results returned by tdllib and what I see in the official Telegram Desktop application.
`TdApi.SearchPublicChats` request:
```java
client.send(new TdApi.SearchPublicChats("witcher"), (TdApi.Object object) -> {
    ...
});
```        
Response: 
```text
Chats {
  totalCount = 3
  chatIds = vector[3] {
    -1001917160524
    -1001435825878
    110983051
  }
}
```
Here you can see the response has only 3 chats but this is very different from the result I see in the official app. The result from the official app is much bigger:
![Screenshot from 2024-05-07 17-22-34](https://github.com/tdlib/td/assets/55091941/534f3861-0592-4349-a372-56eeb2459fcf)

What could be the reason for these differences? I would like to get an answer completely identical to the official application.

**Comment by levlam** [comment]
Do you use the latest TDLib?

**Comment by akulik512** [comment]
Hello @levlam 
Thanks for your attention. I have a JNI-generated Java code. Can I get a TDLib version from it?

**Comment by akulik512** [comment]
OptionValueString {
  value = "1.8.11"
}

**Comment by levlam** [comment]
This is a very old version. You need to update to the latest TDLib to get results similar to the latest apps.

**Comment by akulik512** [comment]
Got it. Thanks
