### ISSUE TITLE
InlineKeyboardButton hit with tdlib AP issue

### ISSUE THREAD

**Issue by JrAnTran** [tdlib/td#2877]
@aurimasniekis  @kossnocorp 
I need to simulate InlineKeyboardButton hit from my app. Digging around the internet, there is a few of things related such as GetBotCallbackAnswerRequest...

Could you please help clarify this. Many thanks.

**Comment by JrAnTran** [comment]
in an attempt to openWebApp via hit inlinekeyboadbutton simualtion, I call openWebApp, but its returns "Bot not found"
![Screenshot from 2024-05-10 18-55-05](https://github.com/tdlib/td/assets/169292674/58a7aeed-1afd-4d9c-a3a6-12c0fff2ec6a)

**Comment by levlam** [comment]
You can't pass hardcoded identifiers to TDLib. You can only pass identifiers received from TDLib as function parameters.

**Comment by JrAnTran** [comment]
> You can't pass hardcoded identifiers to TDLib. You can only pass identifiers received from TDLib as function parameters.

@levlam 

chatId, botUserid...received from replyMarkup of the bot

**Comment by JrAnTran** [comment]
> > You can't pass hardcoded identifiers to TDLib. You can only pass identifiers received from TDLib as function parameters.
> 
> @levlam
> 
> chatId, botUserid...received from replyMarkup of the bot

Tell me is there another way to call OpenWebApp?

**Comment by JrAnTran** [comment]
@levlam  all in all, could you please tell me how to simulate an InlineKeyboardButton hit from a Telegram client app..

Many thanks.

**Comment by levlam** [comment]
It depends on the type of the keyboard button and is described in the description of the corresponding class.

**Comment by JrAnTran** [comment]
> It depends on the type of the keyboard button and is described in the description of the corresponding class.

I have done it already. Thanks
