### ISSUE TITLE
Failed assertion: line 60 pos 12: '_client != null': is not true.

### ISSUE THREAD

**Issue by Mashi-91** [tdlib/td#2878]
Showing this when creating a superGroupChannel

![Screenshot 2024-05-10 200154](https://github.com/tdlib/td/assets/56748946/81a98704-8593-475a-979a-79d017ee236e)

It work sometime when reload then run but after that it show this error
Anyone?......

**Comment by levlam** [comment]
The assertion isn't from TDLib's source code.

**Comment by Mashi-91** [comment]
can u tell me how i get the group data. and its not returning anything?

**Comment by levlam** [comment]
You never need to call `getSupergroup` if you correctly handle updates. See https://core.telegram.org/tdlib/getting-started for more details.

**Comment by Mashi-91** [comment]
[updateSupergroup](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_supergroup.html) — This update is received whenever a new supergroup has been discovered or some data about a known supergroup has changed. This update is guaranteed to come before the supergroup identifier is returned to the Application. So, whenever an Application receives a supergroup_id, it never needs to use the

here i got this.. thnx

and one more thing

can i hide the channel like user can't see the channel?

**Comment by levlam** [comment]
What channel do you want to hide?

**Comment by levlam** [comment]
You can try to hide it only in your own app by implementing the hiding.

**Comment by Mashi-91** [comment]
can u tell me how?

**Comment by levlam** [comment]
If you write your own app, then you can skip the chat.

**Comment by Mashi-91** [comment]
[Failed assertion: line 60 pos 12: '_client != null': is not true](https://github.com/tdlib/td/issues/2878#top)

only show this error when i use this function final result = await client!.send(tda.CreatePrivateChat(userId: chat.id,force: false));

![Screenshot 2024-05-11 154151](https://github.com/tdlib/td/assets/56748946/9aaa7fab-94b3-4827-8bed-aa311b9ef0cc)

Need Help Brother....

**Comment by levlam** [comment]
The bug is in your code. You closed the TDLib instance assigned null to the client variable, and then tried to access null object.

**Comment by Mashi-91** [comment]
No bro, i already checked and Client is not null. I am getting everything except few functions by running those i am getting this error.

**Comment by levlam** [comment]
No, it is null. You checked this only at the beginning of the function, but the function is asynchronous and `client` isn't a local variable. A lot of other code can run while the function is invoked, including one that closes the `client` and sets it to null.

**Comment by Mashi-91** [comment]
If it's null then how does it work the first time when trigger the function and not work second.. then again work after hot reload. 🤔

**Comment by levlam** [comment]
That's the question for the rest of your code.

**Comment by levlam** [comment]
@yaakoubDj The issue was in the JavaScript code that used `tdweb` and not in the `TDLib` itself.

**Comment by yaakoubDj** [comment]
Did you find any solution for this ?
