### ISSUE TITLE
Can I login without phone number and code?

### ISSUE THREAD

**Issue by jingming66** [tdlib/td#2879]
I want to achieve one-click login to the management backend, is that possible?

**Comment by levlam** [comment]
What is "the management backend"?

**Comment by jingming66** [comment]
> What is "the management backend"?什么是“管理后端”？

I want login in by just entering api_id and api_hash without having to enter phone number and code .is it possible？

**Comment by levlam** [comment]
It is no possible to have Telegram account without phone number, which is required.
