### ISSUE TITLE
searchPublicChat force online

### ISSUE THREAD

**Issue by gitandboss** [tdlib/td#288]
I use `searchPublicChat` got get `chat` object but in later calls , I think it fetch data from local database

As you know `chat` has `last_message` , When I invoke `searchPublicChat` again the `last_message` is stale 
How can I force tdlib to fetch data from server?

**Comment by levlam** [comment]
What are you trying to achieve? New messages are received only in chats from the chat list, so `last_message` is updated only for these chats.

**Comment by gitandboss** [comment]
@levlam I want to show a preview of last message to user
How is possible to clear cached `searchPublicChat` or force fetch from server?

**Comment by levlam** [comment]
New messages are polled in such chats when the chat is opened, so you need to call openChat and wait for updates. You will also need to call closeChat as soon as new messages from that chat aren't needed in order to be not flood restricted by the server.

**Comment by gitandboss** [comment]
@levlam is it needed to call closeChat even closing app?
If I call openChat and my user closed the application is it needed to call closeChat in next boot?

**Comment by levlam** [comment]
No, there is no need.

**Comment by AaronPorts** [comment]
As I understand searchPublicChat takes message id from tdlib database if we've already searched that before. How to get updated last message id not from local db?

**Comment by levlam** [comment]
@AaronPorts The answer was [there](https://github.com/tdlib/td/issues/288#issuecomment-397816138).
