### ISSUE TITLE
Is there anyway to show messages without downloading?

### ISSUE THREAD

**Issue by Mashi-91** [tdlib/td#2884]

**Comment by levlam** [comment]
You can hardly show any data without downloading it.

**Comment by Mashi-91** [comment]
I mean about images like in memory or something. For showing images/files of chat message, After getting Chat messages?

**Comment by levlam** [comment]
You must download files to show them, and disk is the storage designed to store files.

**Comment by Mashi-91** [comment]
is there anyway to show uploading indicator or downloading?

**Comment by levlam** [comment]
App receives `updateFile` updates whenever any information about a file changes and can use `local.downloaded_size` or `remote.uploaded_size` to show progress.
