### ISSUE TITLE
SendDocument Message Pending

### ISSUE THREAD

**Issue by Mashi-91** [tdlib/td#2886]
Text Message going fine. But on document or photo etc showing pending state

![Screenshot 2024-05-16 112233](https://github.com/tdlib/td/assets/56748946/69838e20-2dd8-470b-a1d6-157d396a7349)
![Screenshot 2024-05-16 112252](https://github.com/tdlib/td/assets/56748946/22adc6b2-2c77-47ae-b901-a7df04687dc5)

{chat_id: 774194172, last_message: {id: 7933526113, sender_id: {user_id: 774194172, @type: messageSenderUser}, chat_id: 774194172, sending_state: {sending_id: 0, @type: messageSendingStatePending}, scheduling_state: null, is_outgoing: true, is_pinned: false, is_from_offline: false, can_be_edited: false, can_be_forwarded: true, can_be_replied_in_another_chat: false, can_be_saved: true, can_be_deleted_only_for_self: true, can_be_deleted_for_all_users: false, can_get_added_reactions: false, can_get_statistics: false, can_get_message_thread: false, can_get_read_date: false, can_get_viewers: false, can_get_media_timestamp_links: false, can_report_reactions: false, has_timestamped_media: true, is_channel_post: false, is_topic_message: false, contains_unread_mention: false, date: 1715838604, edit_date: 0, forward_info: null, import_info: null, interaction_info: null, unread_reactions: [], reply_to: null, message_thread_id: 0, saved_messages_topic_id: 774194172, self_destruct_type: null, self_destruct_in: 0.0, auto_delete_in: 0.0, via_bot_user_id: 0, sender_business_bot_user_id: 0, sender_boost_count: 0, author_signature: , media_album_id: 0, restriction_reason: , content: {document: {file_name: Taska.png, mime_type: image/png, minithumbnail: null, thumbnail: null, document: {id: 39, size: 2173544, expected_size: 2173544, local: {path: C:\Users\aadil\OneDrive\Pictures\Freelance\Taska.png, can_be_downloaded: false, can_be_deleted: false, is_downloading_active: false, is_downloading_completed: true, download_offset: 0, downloaded_prefix_size: 2173544, downloaded_size: 2173544, @type: localFile}, remote: {id: , unique_id: , is_uploading_active: true, is_uploading_completed: false, uploaded_size: 2173544, @type: remoteFile}, @type: file}, @type: document}, caption: {text: -u-t-s- 1715838604389 e-n-d- 1861186925 --lbl--, entities: [{offset: 8, length: 13, type: {@type: textEntityTypeBankCardNumber}, @type: textEntity}], @type: formattedText}, @type: messageDocument}, reply_markup: null, @type: message}, positions: [], @type: updateChatLastMessage}

**Comment by levlam** [comment]
All outgoing messages need some time to be send and have state `messageSendingStatePending` until that.
You can send full TDLib log with verbosity 4 since app launch to https://t.me/tdlib_bot if the message isn't sent for a long time.

**Comment by levlam** [comment]
Log contains private data, so it must not be sent publicly.

**Comment by Mashi-91** [comment]
i just send full log to bot. now wht?

**Comment by Mashi-91** [comment]
Showing this is_uploading_completed true like 50 times and then show nothing. Then show another log

flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   HomeScreen.build.<anonymous closure>.<anonymous closure> (package:CloudInfinity/screens/widgets/home_screen.dart:51:22)
flutter: │ #1   _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Update: {file: {id: 1257, size: 1819735, expected_size: 1819735, local: {path: C:\Users\aadil\OneDrive\Pictures\Wallpaper\sunset standing alone mountains scenery.jpg, can_be_downloaded: false, can_be_deleted: false, is_downloading_active: false, is_downloading_completed: true, download_offset: 0, downloaded_prefix_size: 1819735, downloaded_size: 1819735, @type: localFile}, remote: {id: , unique_id: , is_uploading_active: true, is_uploading_completed: false, uploaded_size: 1819735, @type: remoteFile}, @type: file}, @type: updateFile}
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Then show this log

[ 4][t 5][1715855954.160365104][MultiTimeout.cpp:84][#1][!PendingSendDialogActionTimeout]	Set timeout of PendingSendDialogActionTimeout in 0.063011
[ 3][t 5][1715855954.160404443][MessagesManager.cpp:31111][#1][!MessagesManager]	Receive send_chat_action timeout in chat 774194172
[ 4][t 5][1715855954.160410404][MultiTimeout.cpp:38][#1][!MessagesManager]	Add PendingSendDialogActionTimeout for 774194172 in 4.000000
[ 3][t 5][1715855954.160417318][MessagesManager.cpp:31902][#1][!MessagesManager]	Search for yet unsent message 7573.1 in chat 774194172 found 000002065CDA0AC0
[ 3][t 5][1715855954.160425424][MessagesManager.cpp:31164][#1][!MessagesManager]	Send ChatActionUploadingDocumentAction in chat 774194172
[ 3][t 5][1715855954.160429716][DialogActionManager.cpp:316][#1][!MessagesManager]	Skip unneeded ChatActionUploadingDocumentAction in chat 774194172

**Comment by levlam** [comment]
You don't process `updateFileGenerationStart` and hence the being generated file blocks message queue.

**Comment by Mashi-91** [comment]
1. then how will it take to work again?
2. why msg still showing after deleted?

**Comment by levlam** [comment]
1. Process `updateFileGenerationStart` as documented.
2. Because text messages and some other messages aren't ordered with media messages.

**Comment by Mashi-91** [comment]
why showing 	Sending error for request 12: error { code = 400 message = "Chat not found" }
 after login and after logout when login again showing this
Sending error for request 5: error { code = 401 message = "Unauthorized" }

**Comment by levlam** [comment]
1. You only can use identifiers received from the same TDLib instance.
2. You aren't logged in yet.

**Comment by Mashi-91** [comment]
how i logout completely?

**Comment by levlam** [comment]
By calling `logOut` and waiting for `authorizationStateClosed`.

**Comment by Mashi-91** [comment]
That is how i do it bro. Then i got the error.

**Comment by levlam** [comment]
Which is expected because you have logged out.

**Comment by Mashi-91** [comment]
But it is supposed to login instead of showing unauthorised error even though i was login with new phone number.

**Comment by levlam** [comment]
No. A TDLib instance can't be reused. You must create a bew instance for new authorization.

**Comment by Mashi-91** [comment]
Web showing Unimplementation Error. Can you tell how i can add web one?

**Comment by levlam** [comment]
There is no "Unimplementation" error in TDLib.

**Comment by Mashi-91** [comment]
On this package i am using there's no implementation of web
![Screenshot 2024-05-18 155125](https://github.com/tdlib/td/assets/56748946/4c8ed866-f850-4547-926c-0a4b01c74bad)

**Comment by levlam** [comment]
TDLib supports Web using WebAssembly: https://github.com/tdlib/td/tree/master/example/web, so it can be used from there. You can check https://github.com/tdlib/td/blob/master/example/web/tdweb/README.md for description of TDLib usage from Web.

**Comment by Mashi-91** [comment]
i dont know bro how i do it can guide me?

**Comment by levlam** [comment]
All available information on the usage is written in the example README.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-chat-messages.

**Comment by Mashi-91** [comment]
final tda.User user = await TelegramClient().client!.send(tda.GetMe());

when i first login then call this function and after that call getChatHistory function
show this error chatNotFound until i verify the device from telegram app..

 // Send the message
      await client!.send(
        tda.SendMessage(
          chatId: id,
          messageThreadId: 0, // Specify the message thread ID if applicable
          inputMessageContent: inputMessageContent,
        ),
      );

**Comment by levlam** [comment]
`GetMe()` returns a user. You must use `CreatePrivateChat` to create a private chat with a user.

**Comment by Mashi-91** [comment]
But i am not creating any chat i am getting saved chats. And its works after i verify the device on my telegram app with the same code.

**Comment by levlam** [comment]
You need a chat to send a message. You don't have one after calling `getMe`, because it returns a `user`, but not a `chat`.

**Comment by Mashi-91** [comment]
is there any way to create a folder or is there any field in tdlib, i can use for creating folder like somekind of list?

**Comment by levlam** [comment]
A chat folder can be created using the method `createChatFolder`.

**Comment by Mashi-91** [comment]
is there any field where i can store ids like its not use or like users can't use the field 
Its Must Be List

**Comment by levlam** [comment]
You can store some data using setOption starting with "X", or using "setChatClientData".

**Comment by Mashi-91** [comment]
but i want to store like list

**Comment by Mashi-91** [comment]
i just create lots of folder ids using SetOptions. how i get them all?

**Comment by levlam** [comment]
You receive all up-to-date values of options in updates.

**Comment by Mashi-91** [comment]
Sending error for request 11: error { code = 400 message = "Option can't be set" }

await TelegramClient().client!.send(
                    tda.SetOption(
                        name: 'Hello Another',
                        value: tda.OptionValueString(value: "HEy I am here")),
                  );
                  
showing the error after setOptions

**Comment by levlam** [comment]
Only options starting with 'X' and 'x' are reserverd for app usage.

**Comment by Mashi-91** [comment]
i dont understand bro....🤔?

**Comment by Mashi-91** [comment]
i want to create a folder so is there anyway of do it like. Not the telegram one?

**Comment by Mashi-91** [comment]
can u tell me the name which ( Option ) is best for storing ids?

**Comment by levlam** [comment]
Telegram has only chat folders, that can be created using `createChatFolder`.

**Comment by levlam** [comment]
You can choose arbitrary name for custom options that starts with "x" or "X".

**Comment by Mashi-91** [comment]
│ ⛔ Error fetching file chat: TdFunctionException(function: {chat_id: 774194172, from_message_id: 0, offset: 0, limit: 10, only_local: false, @type: getChatHistory}, error: {code: 400, message: Chat not found, @type: error})|

showing this error. bro even though chat exist which is saved Messages. sometime work sometime didn't.

![Screenshot 2024-06-02 114003](https://github.com/tdlib/td/assets/56748946/c3fa9ffb-9576-46e5-92a8-f23c9c1ec855)

**Comment by levlam** [comment]
You can only pass identifiers received from the same TDLib instance.

If you want to get Saved Messages chat, then you need to call `getMe`, then `createPrivateChat`, and the use the received chat.

**Comment by Mashi-91** [comment]
I already tried GetMe func before calling GetChatHistory function. And still showing the same thing.

**Comment by levlam** [comment]
You must pass `chat_id` to `getChatHistory`. You have no chat after calling `getMe`.

**Comment by Mashi-91** [comment]
I actually store the chat id in local storage when the app starts for the first time.

**Comment by levlam** [comment]
You can only pass identifiers received from the same TDLib instance.

**Comment by Mashi-91** [comment]
i didn't understand bro can u more specific?

**Comment by Mashi-91** [comment]
no i am just storing User data in memory only here look

Rx<UserModel?> userModel = Rx<UserModel?>(null);


![Screenshot 2024-06-24 164209](https://github.com/tdlib/td/assets/56748946/3acf4f54-6ad8-4572-9767-856a58ba86fe)


and getting this error

Error fetching file chat: TdFunctionException(function: {chat_id: 774194172, from_message_id: 0, offset: 0, limit: 10, only_local: false, @type: getChatHistory}, error: {code: 400, message: Chat not found, @type: error})

**Comment by levlam** [comment]
You can't pass a user identifier as `chatId`. If you want to create a chat with user, you need to call `createPrivateChat` first.

**Comment by Mashi-91** [comment]
No, i want to send messages on the (Saved Message) and (Saved Message)  id is the same as userid

**Comment by levlam** [comment]
You can't use an identifier which wasn't received from TDLib and you can't use a user identifier as a chat identifier, file identifier, message identifier ot any other identifier. If you need to pass a chat identifier to a method, then you must create the chat first and pass identifier of the chat.

**Comment by Mashi-91** [comment]
But bro Saved Message Chat Already there, i just want to send message on saved Message....

**Comment by levlam** [comment]
A chat can't exist until you received it from TDLib.

**Comment by Mashi-91** [comment]
and how i do that?

      final tda.User user =
      await TelegramClient().client!.send(const tda.GetMe());
      
      if u talking about this and after getting user from this then provide chat id then i already did that.

**Comment by levlam** [comment]
No, you didn't. You have no `chat`. You never discovered it, or received it from TDLib. Hence you can't have its identifier and pass an unrelated identifier to other methods. You must use `createPrivateChat` to get a chat with a given user.

**Comment by Mashi-91** [comment]
So by doing that I'll get saved message chat?

**Comment by levlam** [comment]
Yes.

**Comment by Mashi-91** [comment]
thnx bro and one more thing.. showing this error can u just tell wht should i put this here showing

[Error : 0 : There is no such key in the database]

        databaseEncryptionKey: '',

on parameters?

**Comment by levlam** [comment]
The error message isn't related to the parameter in any way.

**Comment by Mashi-91** [comment]
Hey Bro i am facing this problem

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:tdlib/src/client/client_impl.dart': Failed assertion: line 83 pos 12: '_state == _ClientState.initialized': is not true.

When the exception was thrown, this was the stack:
#2      ClientImpl.destroy (package:tdlib/src/client/client_impl.dart:83:12)
client_impl.dart:83
#3      MainHomeViewController.didChangeAppLifecycleState (package:CloudInfinity/controllers/main_home_controller.dart:80:34)
main_home_controller.dart:80
#4      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:945:16)
binding.dart:945
#5      List.forEach (dart:core-patch/growable_array.dart:416:8)


Here's the code i just want to close when app in BG.


  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    Logger().i("APPLIFE: ${state}");
    if (state == AppLifecycleState.paused || state == AppLifecycleState.detached) {
      if (TelegramClient().client != null) {
        Logger().i("Destorying:::::");
        TelegramClient().client!.destroy();
        Logger().i("Destoryed:::::");
      }
    }
    super.didChangeAppLifecycleState(state);
  }

**Comment by levlam** [comment]
This is an error from the wrapper's code, unrelated to TDLib.

**Comment by Mashi-91** [comment]
why this is clear OptionValueString after logout?

Future<List<ChatFolder>> getFolders() async {
    try {
      final tda.OptionValueString response =
          await TelegramClient().client!.send(
                tda.GetOption(name: folderSaveName),
              );
              _logger.i('Before everything: $response');
      final serializedFolders = response.value;
      _logger.i('Before anything folders: $serializedFolders');

      if (serializedFolders.isEmpty) {
        _logger.i("No folders found");
        return [];
      }

      final folderStrings = serializedFolders.split(';');
      _logger.i('Before converting folders: $folderStrings');
      final folders = folderStrings
          .where((folderStr) => folderStr.trim().isNotEmpty)
          .map((folderStr) => ChatFolder.fromString(folderStr))
          .toList();

      _logger.i("Parsed folders: ${folders.length} found");
      return folders;
    } catch (e) {
      _logger.e("Error Fetching Folders: $e");
      return [];
    }
  }

**Comment by levlam** [comment]
This is also not a TDLib's code.

**Comment by levlam** [comment]
Do you use the latest TDLib version?

**Comment by levlam** [comment]
Then, options should be cleared only after logging out is completed.

**Comment by Mashi-91** [comment]
I am using this one 1.8.29 from here https://github.com/ivk1800/tdlib-dart

**Comment by levlam** [comment]
Yes, this is a new enough version.

**Comment by Mashi-91** [comment]
here's the log after log out

[tdlib_log_LOGOUT.txt](https://github.com/user-attachments/files/16123756/tdlib_log_LOGOUT.txt)

**Comment by levlam** [comment]
Could you call getOption before "logOut" and check response?

**Comment by Mashi-91** [comment]
Actually I am storing text in it. Yaa I called it  before Logout and I am getting value!

**Comment by Mashi-91** [comment]
so?

**Comment by levlam** [comment]
Before the logging out is completed all options keep their values.

**Comment by Mashi-91** [comment]
yaa

**Comment by Mashi-91** [comment]
so why's this happening man?

**Comment by Mashi-91** [comment]
if there's any another way of saving data then tell me bro?

**Comment by levlam** [comment]
Send logs with calls to getOption before and after call to `logOut`.

**Comment by Mashi-91** [comment]
Before Logout

[Before Logout.txt](https://github.com/user-attachments/files/16125991/Before.Logout.txt)

After LogOut

[After Logout.txt](https://github.com/user-attachments/files/16126009/After.Logout.txt)

**Comment by levlam** [comment]
I meant in the same log, but still you can see that the option is still present in the second log. It can be empty, only if it was empty before the call to logOut`.

**Comment by Mashi-91** [comment]
no i just add some data before logout
