### ISSUE TITLE
Fail to get chat pinned message

### ISSUE THREAD

**Issue by wfjsw** [tdlib/td#289]
Bot account, in a public searchable chat, with both `getMessage<id>` and `getChatPinnedMessage`

Expect the pinned message.
Actually got 404 Not Found.

**Comment by levlam** [comment]
Bot can't receive a message, which isn't accessible due to bots privacy settings even through `getChatPinnedMessage`. The only exception is for replied messages, which can be received through `getRepliedMessage`.

**Comment by wfjsw** [comment]
I see...
