### ISSUE TITLE
why every time you send a message, the RAM always increases? but reduced slightly

### ISSUE THREAD

**Issue by shpiaadev** [tdlib/td#2890]
I made an AI userbot for all group and private chats, but I have tried a lot to keep the RAM to a minimum, but due to many requests, I ended up sending a message every time, I have set a limit of 1 second, limiting sending messages to no more than 30, I also limit it to 1 hour. not more than 1500, but ram usage is no less automatic, it needs to be closed/destroyed first, what else should I do? Is creating a library to connect mtproto good?

**Comment by levlam** [comment]
Check that you have message database enabled in `setTdlibParameters`.

Also, see https://github.com/tdlib/td/issues/2807.

**Comment by shpiaadev** [comment]
yes, I've done that, including setOption, but to no avail, the RAM keeps getting bigger,

**Comment by levlam** [comment]
What do you mean by `setOption`?

**Comment by Flohack74** [comment]
@shpiaadev how do you know that there is a memleak in tdlib, maybe its your application which is leaking memory. Which interface language to tdlib do you use?
