### ISSUE TITLE
Authorize error: timeout

### ISSUE THREAD

**Issue by jingming66** [tdlib/td#2894]
Can multiple programs use the same database？I am using the same database and it has been consistently timed out（Authorize error: timeout），this is my code：
`	client := client.NewClient(client.Config{
		DatabaseDirectory:      "./tdlib-db",
		UseFileDatabase:        false,
		UseChatInfoDatabase:    false,
		UseMessageDatabase:     true,
		UseSecretChats:         true,
		APIID:                  "88",
		APIHash:                "22",
		SystemLanguageCode:     "en",
		DeviceModel:            "Server2",
		SystemVersion:          "",
		ApplicationVersion:     "2.0",
		EnableStorageOptimizer: true,
		IgnoreFileNames:        false,
	})`

**Comment by levlam** [comment]
You must provide a unique database directory for each instance.

**Comment by jingming66** [comment]
good
