### ISSUE TITLE
Some video types are not correctly recognized in tdlib

### ISSUE THREAD

**Issue by benwoniu630353** [tdlib/td#2895]
I built a tdlib small application and found that when the video type is .m4v, it is sent through tdlib and the tag type is video, but the telegram server recognizes it as document.
However, I can upload it through telegram’s PC client or mobile APP and it will be displayed as video type after successful upload.

I don't know why

**Comment by levlam** [comment]
Do you use `inputMessageVideo` to upload video files?

**Comment by benwoniu630353** [comment]
> Do you use `inputMessageVideo` to upload video files?

Yeah，I use it！

TDLIB version 1.8.29 made a document fix. According to my observation, it should have fixed a recognition problem of video types containing the suffix .MEPG4. 
In previous versions, the .mpeg4 video type would also encounter I encountered the same problem. 
Now it can be recognized normally.
But .m4v still cannot be recognized normally. 
If possible, please fix it in the next version.

**Comment by benwoniu630353** [comment]
> Do you use `inputMessageVideo` to upload video files?

MPEG4,not MEPG4

**Comment by levlam** [comment]
If you use `inputMessageVideo` and specify all fields, then it is sent as a video. File extension doesn't matter. Whether an app receiving the video will be able to play it. depends on the target app.
