### ISSUE TITLE
How do I know that the bot is stopped?

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2896]
I need to find out when the bot needs to be restarted. For example, I stopped it from another client, stopped and blocked it, cleared the history. What update should I watch to find out when to restart the bot?

**Comment by levlam** [comment]
There are no update for changes of a user's block list. The latest state is fetched via getUserFullInfo when the chat is opened.

**Comment by fat-complex** [comment]
@levlam Thx)))
