### ISSUE TITLE
Disable storing messages

### ISSUE THREAD

**Issue by maxstaniforth** [tdlib/td#2897]
Hi,

I have an application where once a telegram account is authorised, it listens for tdlib events and then sends them onto a kafka topic. The application has no need to store any messages within the sqlite or memory once the event is sent to the topic. 

Is there a way to disable the saving of messages so the application doesn't run out of disk space/memory? And if not what would the effect of simply deleting the sqlite database be after the account is authorised? Would the messages be start being saved to memory again.

Thanks

**Comment by levlam** [comment]
There is no way, because the data is required to send correct updates to the app.

The file sqlite.db can be manually deleted when the corresponding TDLib instance is closed, but then secret chat messages, local chat settings and some other instance-specific information is lost.

**Comment by maxstaniforth** [comment]
Thanks for such a quick response.

When you say the data is required to send correct updates, is that only necessary for when the update originates from my application. If my application never sends any updates itself, only listens for when updates come from other sessions, is there still a need for the sqlite db to store the messages?

**Comment by levlam** [comment]
Yes.

**Comment by maxstaniforth** [comment]
And if the sqlite database is deleted before the TdLib instance is closed are the messages then stored within memory?

**Comment by maxstaniforth** [comment]
ok thanks
