### ISSUE TITLE
Change file name while sending file

### ISSUE THREAD

**Issue by wfjsw** [tdlib/td#290]
Sometime it is pretty hard to operate on file system for arbitrary file. (Actually when comes to fs, things get difficult)
In Bot API, I can set metas such as file name, mime type etc. How can I achieve that with tdlib?

**Comment by levlam** [comment]
If you can't rename a file, but want to send a file under different name, then you can use inputFileGenerated and provide whatever name you want as `original_name`. Then you will need to handle updateFileGenerationStart and copy the file to TDLib provided location.

**Comment by wfjsw** [comment]
Will there be ways to pass fd directly?
