### ISSUE TITLE
A question about receiving messages

### ISSUE THREAD

**Issue by jingming66** [tdlib/td#2900]
first I opened an application that can receive messages, and then I copied the "tdlib_db" folder (already rename it to tdlib_db2) for the second application to use. The second application can receive messages, but the first application cannot. Why is this happening

**Comment by levlam** [comment]
You must never copy TDLib's directory, only fully move it. Copied directory has no chance to work correctly.

**Comment by jingming66** [comment]
> You must never copy TDLib's directory, only fully move it. Copied directory has no chance to work correctly.您绝不能复制 TDLib 的目录，只能完全移动它。复制的目录没有机会正常工作。

thank you very much
