### ISSUE TITLE
Linux is not an operating system, Linux is kernel.

### ISSUE THREAD

**Issue by MrTrakos2** [tdlib/td#2902]
So, while building TDLib on my device, I've noticed that docs says Linux is an OS (Operating System), which I begin angry on.

So please edit that build.html file..

**Comment by levlam** [comment]
No. Did you try to choose "Linux"? You can choose a specific distro after choosing "Linux". I'm not going to triple size of the list of supported operating systems inlining all Linux distrubitions there.

By the way, see https://en.wikipedia.org/wiki/Linux:
> Linux ([/ˈlɪnʊks/](https://en.wikipedia.org/wiki/Help:IPA/English) [LIN-uuks](https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key))[[11]](https://en.wikipedia.org/wiki/Linux#cite_note-pronunciation-2-14) is a family of [open-source](https://en.wikipedia.org/wiki/Free_and_open-source_software) [Unix-like](https://en.wikipedia.org/wiki/Unix-like) [operating systems](https://en.wikipedia.org/wiki/Operating_system) based on the [Linux kernel](https://en.wikipedia.org/wiki/Linux_kernel)

**Comment by MrTrakos2** [comment]
better to name it GNU/Linux, instead of just Linux. and Please don't use Wikipedia as source of information.

**Comment by levlam** [comment]
See https://en.wikipedia.org/wiki/GNU/Linux_naming_controversy and let's stop this controversy.
