### ISSUE TITLE
chatMemberStatusAdministrator not work

### ISSUE THREAD

**Issue by Big-js-demon** [tdlib/td#2904]
Hi.If create supergroup and add admin method chatMemberStatusAdministrator ,bot or user added as normal  user and  not have admin privegies,but work other methods chatMemberStatusCreator,chatMemberStatusMember ,etc.

```
const right={ 
_: 'chatMemberStatusAdministrator',
can_manage_chat:true,
custom_title:'administrator',
can_delete_messages:true,
can_invite_users:true,
can_restrict_members:true,
can_pin_messages:true,
can_manage_video_chats:true,
is_anonymous:true
};

await client.invoke({
_: 'setChatMemberStatus',
member_id:{_:'messageSenderUser',user_id:bot_id},
chat_id:super_group_id,
status:right
})
.then((e)=>{console.log(e);}).catch((e)=>{console.log(e);})	
```

how add user as admin to the supergroup with tdlib?

**Comment by levlam** [comment]
You create `chatMemberStatusAdministrator` object incorrectly. See documentation for the class in the latest TDLib version:
https://github.com/tdlib/td/blob/fd3154b28727df9e66423d64168fab1202d8c849/td/generate/scheme/td_api.tl#L997

**Comment by Big-js-demon** [comment]
> You create `chatMemberStatusAdministrator` object incorrectly. See documentation for the class in the latest TDLib version:
> 
> https://github.com/tdlib/td/blob/fd3154b28727df9e66423d64168fab1202d8c849/td/generate/scheme/td_api.tl#L997

hello.it`s fine?
 right={ 
_: 'chatMemberStatusAdministrator',
custom_title: 'Robot',
can_be_edited:true,
permissions:{_:'chatPermissions',can_manage_chat:true,can_delete_messages:true,can_invite_users:true,can_restrict_members:true,can_pin_messages:true,can_manage_video_chats:true,is_anonymous:true}
};
