### ISSUE TITLE
Website support does not respond

### ISSUE THREAD

**Issue by Chungaa** [tdlib/td#2906]
Website support does not respond

On the website https://telegram.org/support
I have been contacting support for 2 weeks and have written several e-mails. But none responded. Could someone please ask what's going on? Could someone forward it to the team.
It doesn't leave a good impression.

**Comment by levlam** [comment]
Why don't you use in-app support?

**Comment by Chungaa** [comment]
Because my number was blocked for no reason. I have done nothing illegal. That's why I need support.

**Comment by Chungaa** [comment]
Problem fixed, can Close thank you for your help
