### ISSUE TITLE
Build tdlib on Windows: cannot open include file: 'td/mtproto/mtproto_api.h': No such  file or directory

### ISSUE THREAD

**Issue by andreymerchenko** [tdlib/td#2911]
Hi tdlib community,

when building the new dlls using the commands described in [build instructions](https://tdlib.github.io/td/build.html?language=Java) for the following parameters:
programming language=Java
operating system=Windows
shell application=Powershell (is reproduced for Bash as well)
bitness=64

I am getting errors like:
> C:\tdlib\td\td\mtproto\Handshake.cpp(12,10): error C1083: Cannot open include file: 'td/mtproto/mtproto_api.h': No such file or directory [C:\tdlib\td\build\tdmtproto.vcxproj]
> C:\tdlib\td\td\mtproto\PingConnection.cpp(12,10): error C1083: Cannot open include file: 'td/mtproto/mtproto_api.h': No
 such file or directory [C:\tdlib\td\build\tdmtproto.vcxproj]

The command output has been attached: [command_output_log.txt](https://github.com/user-attachments/files/15536668/command_output_log.txt)

This error happens when executing the command:
`cmake --build . --target install --config Release`

I am performing a build inside an empty C:\tdlib from Powershell as an Administrator.

When I was building dlls last time (a few months ago) the same way, the build was working without errors and dlls were successfully generated.

The command output has been attached.

Could you, please, advise why I am getting such error and how this error can be resolved?

Thanks

**Comment by levlam** [comment]
You can run `cmake --build . --target install --config Release` again and it will succeed.
The issue will be fixed soon.

**Comment by levlam** [comment]
Fixed in master.

**Comment by andreymerchenko** [comment]
Hi @levlam , thank you for the quick fix. 
I am currently facing issues with running a Java example on the latest build, created a separate issue for it: https://github.com/tdlib/td/issues/2912
