### ISSUE TITLE
Firebase cloud messages current protocol will be removed this month

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2914]
[https://firebase.google.com/docs/cloud-messaging/android/upstream](url)
Firebase cloud messages tdlib implementation will not work anymore from July, will it be updated in time?

**Comment by levlam** [comment]
TDLib doesn't need any changes to support the new protocol. Server-side support for new protocol is expected to be added before the deadline.

**Comment by levlam** [comment]
It should be already possible to upload FCM credentials at api.telegram.org to use new push notification API.
