### ISSUE TITLE
mtproto problem on telegram x

### ISSUE THREAD

**Issue by titancomputer** [tdlib/td#292]
hi

we've setup mtproto server on windows server with JSMTProxy (nodejs) and it's work on all clients like android, desktop, ios but it didn't work on telegram x.

it sais error 400 on proxy list in the app.

please fix that.

**Comment by levlam** [comment]
This is a bug in the proxy implementation, which doesn't support MTProto intermediate [TCP transport](https://core.telegram.org/mtproto#tcp-transport) 0xeeeeeeee. [There](https://github.com/FreedomPrevails/JSMTProxy/blob/70a596a3dd5036773be2b29fd7f4a84a0fe6bcf7/mtproxy.js#L201) proxy checks only for abridged TCP transport 0xefefefef. 0xeeeeeeee should be allowed there to allow TDLib to use that proxy.

**Comment by titancomputer** [comment]
how we can edit the code to allow 0xeeeeeeee ?

**Comment by levlam** [comment]
It can be fixed pretty straightforward: only check on the line that I've specified need to be fixed. It currently allows only `0xefefefef` as bytes 56-59 and it should also allow `0xeeeeeeee`.

**Comment by titancomputer** [comment]
sorry i tried many times to edit code with && and || for adding 0xee to this line. can you edit that and type here?

				if (dec_auth_packet[56 + i] != 0xef) {

thanks

**Comment by levlam** [comment]
For example [this](https://github.com/TelegramMessenger/MTProxy/blob/20824f5fa8af3939e667fba5c1785f02059c1c43/net/net-tcp-rpc-ext-server.c#L219) is how it is done in the official MTProto proxy.

**Comment by titancomputer** [comment]
i tried to change that to
for (var i = 0; i < 4; i++) {
				if (dec_auth_packet[56 + i] != 0xeeeeeeee) || (dec_auth_packet[56 + i] != 0xefefefef) {
					socket.destroy();
					return;
				}
			}

but it hangs on loop and didn't start, need i change somewhere else?

**Comment by ea1234567** [comment]
i have problem too
plz someone edit that code and send here
tnx

**Comment by titancomputer** [comment]
@levlam can you give us a help to resolve the issue?

**Comment by Bannerets** [comment]
@titancomputer 
```js
function check (num) {
  for (var i = 0; i < 4; i++) {
    if (dec_auth_packet[56 + i] != num)
      return false;
  }
  return true;
}

if (!check(0xee) && !check(0xef)) {
  socket.destroy();
  return;
}
```

**Comment by titancomputer** [comment]
@Bannerets thank you for codes.

i've replaces this section but didn't work on telegram x android as same as before. all others do fine.

**Comment by levlam** [comment]
@titancomputer It may be also needed to replace [there](https://github.com/FreedomPrevails/JSMTProxy/blob/70a596a3dd5036773be2b29fd7f4a84a0fe6bcf7/mtproxy.js#L63) 0xef with 0xee, but then proxy will work only with Telegram clients, which uses intermediate protocol. More changes are needed to support both protocols.

**Comment by titancomputer** [comment]
@levlam ok, thank you for responding, i'll wait for them to edit.

**Comment by levlam** [comment]
There are no bugs in the TDLib support of MTProto-proxy or MTProro-protocol in general, so I'm closing this issue.
Please address the issue to developers of affected third-party proxies.
