### ISSUE TITLE
example/cpp/td_example.cpp  can not run, td/telegram/td_api.h can not found

### ISSUE THREAD

**Issue by kannr** [tdlib/td#2922]
**build command**

git clone https://github.com/tdlib/td.git
cd td
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../example/cpp/td ..
cmake --build . --target install
cd ../example/cpp
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DTd_DIR=/Users/cy/td/example/cpp/td/lib/cmake/Td ..
cmake --build .

when i run td_example.cpp

fatal error: 'td/telegram/Client.h' file not found
#include <td/telegram/Client.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

the clion ide compilation failed.
<img width="423" alt="截屏2024-06-09 11 25 27" src="https://github.com/tdlib/td/assets/20182703/18657f56-caee-4cbc-9133-cda1fb502384">

**Comment by levlam** [comment]
The build likely succeeded, and the file `td_example.exe` has been generated by the command `cmake --build .`.

If you want to edit the example in CLion and build from there, then you must ensure to create the project from the CMake file and use it with the same options as specified at the command line, namely, `Td_DIR=/Users/cy/td/example/cpp/td/lib/cmake/Td`
