### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by gitandboss** [tdlib/td#293]
I have some issue
```
[Session.cpp:384][!Session:4:main]       on_closed: [PosixError : Connection timed out : 110 : Error on socket [fd_ = 32]] Session:4:main::Connect::Tcp::[149.154.167.92:443] DcId{4}
```

It is take long time to establish session often

I ping 149.154.167.92 and the result is 
```
PING 149.154.167.92 (149.154.167.92) 56(84) bytes of data.
64 bytes from 149.154.167.92: icmp_seq=1 ttl=52 time=84.8 ms
64 bytes from 149.154.167.92: icmp_seq=2 ttl=52 time=84.7 ms
64 bytes from 149.154.167.92: icmp_seq=3 ttl=52 time=84.6 ms
```

How can I fix it?

**Comment by levlam** [comment]
It is a network error. Something prevents the connection from establishing and usually nothing can be done to bypass the error, except using a proxy or switching to another network. You can try to open `http://149.154.167.92:443` in a browser or do `telnet 149.154.167.92 443` to ensure that problem exists.

You may also need to set option `online` to `true` for better user experience.
