### ISSUE TITLE
Bot Answering Chat Join Requests Conditions

### ISSUE THREAD

**Issue by 2ale2** [tdlib/td#2932]
Bot answering to Chat Join Requests should be able to continue the conversation also if the user presses a button from a Keyboard Markup. Currently, it is possible just if the user sends a message. Thank you for your time. 🙏🏻

**Comment by Lagwair1** [comment]
Bb

**Comment by Lagwair1** [comment]
Jdrjm

**Comment by 2ale2** [comment]
Imma close cause no one asnwered.

**Comment by 2ale2** [comment]
Imma close cause no one answered.
