### ISSUE TITLE
mac compile tdlib problem

### ISSUE THREAD

**Issue by yg66** [tdlib/td#2934]
local environment
- clang version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- openssl version: OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)
- gperf version: GNU gperf 3.1
- cmake version: cmake version 3.10.2
- zlib version：v1.2.11
- tdlib build version: v1.8.0 (commit_hash: b3ab664a18f8611f4dfcd3054717504271eeaa7a)

After the build, using the golang client to reference the compiled static library, execution to Gzip.cpp reported an error: 
[ 0][t 4][1718593876.283946037][Status.h:261][#1][!Session:1:main] Unexpected Status [Error : 0 : zlib inflate init failed: -2] in file /ClionProjects/github.com/tdlib/td/tdutils/td/utils/Gzip.cpp at line 159

How to deal with this problem? Does it have anything to do with the compilation environment/version?

**Comment by levlam** [comment]
The error should mean incorrect `zlib` usage, but zlib 1.2.11 is definitely supported and works. It can also happen in the case of heap corruption by other parts of the app, but this is unlikely. Also, if the app has been successfully built it should work.

**Comment by vincentneo** [comment]
@yg66 Regardless of the zlib error,  you might want to try compiling a much newer tdlib commit (such as the latest commit for v1.8.31) as v1.8.0 is very old at this point, maybe it helps.
