### ISSUE TITLE
File (all media) handling

### ISSUE THREAD

**Issue by lexermekongnet** [tdlib/td#2938]
How does tdlib handle files?

I'm creating a chat system which utilizes tdlib, when I receive updateNewMessage, I also get which kind of message it is such as messageText or messagePhoto

When I declutter the messagePhoto fields I can't seem to find the url of the photo, see I'm a newbie in the backend so I assume messageText would contain the text and messagePhoto (or any message Media) would contain a url.

This leads me to my question how can I get the file(s) being emit by updateNewMessage's messagePhoto.

What's in my mind is I would use downloadFile and save it to my own server so I could "view" it on my own web UI.

**Comment by levlam** [comment]
You can download the file by passing its identifier to `downloadFile`.
