### ISSUE TITLE
Taligram

### ISSUE THREAD

**Issue by Shabi209** [tdlib/td#2939]
I am using this telegram account for my business purpose but may account banned please for give me if I did any mistake again please unban my account I will thanks full you 🙏

**Comment by levlam** [comment]
If you think that an account was banned by a mistake, please try to log in to the account from an official mobile app and send an email to recover the account by following instructions provided by the app.

**Comment by Shabi209** [comment]
My mistakes

**Comment by Tarif223311** [comment]
Tarif223311
