### ISSUE TITLE
join channel with id or username

### ISSUE THREAD

**Issue by ShafiqSadat** [tdlib/td#294]
hi, how to join channel with id or userName?

with tdbot

**Comment by levlam** [comment]
Method addChatMember can be used to add a new member (including yourself) to a chat.

Method searchPublicChat can be used to get a chat by a username.

**Comment by levlam** [comment]
Since TDLib 1.3.0 you can alternatively use `joinChat` instead of `addChatMember` for that.

**Comment by Rajkumar1994sof** [comment]
@levlam Any samples or documentation to get the channel id using channel name and to join ?
