### ISSUE TITLE
Clarification on Telegram account irreversible bans on basis of third party app use

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2940]
I recently received this review on my app, which uses TDLib. Here's the relevant snippet of the review:
> So I downloaded this app to be able to use telegram and within 24hrs telegram had banned my account and telephone number and when I contacted support to try to get my number unbanned they refused and **said it was justified since I was trying to use third party apps** so they can clearly detect that you’re using this through your watch somehow. 

The reviewer seems to suggest that Telegram support banned the user simply because of third party app usage, and would not unban on this basis. 

I've advised a few reports of bans post-login in the past, but as far as I know, it very rarely happens and all of them were restored eventually. I don't believe the reviewer's remark, especially since TDLib itself is supported officially by Telegram, though, I would like to hear officially from Telegram that third party app usage itself, is not a reason of an account ban, just to make sure.

While I know that this issue section may not be the right place to discuss about this question, I am unsure where else I should seek clarifications on this, which is why I still decided to post this, regardless. If necessary, please guide me to the right place to ask this question, thank you.

**Comment by levlam** [comment]
> "said it was justified since I was trying to use third party apps"

This is a false claim. Telegram in-app support is done by volunteers, but I wouldn't expect even the volunteers to say this. Moreover, if the user received a response instead of the account just being restored, then they wrote to a wrong place. The user was supposed to follow the instructions that are provided by an official app during logging in to the banned account, which require sending a email.

**Comment by vincentneo** [comment]
Thank you very much @levlam for the quick and clear clarification! Very glad to hear that it is a false claim.
