### ISSUE TITLE
I need some advice on authorization

### ISSUE THREAD

**Issue by annovikava** [tdlib/td#2944]
Hi. I am looking for advice on the logic of authorization. 
I'm trying to upgrade the ruby gem to a new version of tdlib and I don't understand how to work with authorization.
Old version is - [eb80924](https://github.com/tdlib/td/tree/eb80924dad30af4e6d8385d058bb7e847174df5e)

In the old version, every time it was necessary  to send requests to telegram, a new client instance was created, a request was sent to setTdlibParameters, followed by checkDatabaseEncryptionKey, after which the rest of the operations were performed from the same client.
In the new version, setTdlibParameters is missing and after setTdlibParameters it is required to go through the confirmation code, which is absolutely unacceptable for my tasks. 

What can you recommend? I'm thinking about using the singleton pattern to work with the client, but I'm not sure if this is the right option.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#user-authorization.

`checkDatabaseEncryptionKey` doesn't exist anymore and `setTdlibParameters` didn't change conceptually.
