### ISSUE TITLE
Doxygen doesn't generate all documents

### ISSUE THREAD

**Issue by a1ex33** [tdlib/td#2945]
I generated docs on my local machine with the command
```
doxygen
```

But not all classes are available in the docs on my local machine. For example:
- chatAvailableReactionsAll https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_available_reactions_all.html
- chatListFolder https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_list_folder.html

What could be the reason?
`doxygen` command still relevant?

**Comment by levlam** [comment]
Check that you build TDLib before trying to generate the documentation.

**Comment by a1ex33** [comment]
Thanks a lot! It helped me.
