### ISSUE TITLE
The compiled static library file does not work properly

### ISSUE THREAD

**Issue by yg66** [tdlib/td#2946]
Hello, brethren! I have a question to consult you, I want to use docker to compile tdlib locally to build a base image, I am not sure whether it is an environment or a dependency version problem, the compiled static library can never be used in other images, I have tried to use buildpack-deps:bullseye-scm, alpine:3.15, ubuntu:18.04 base image to compile, the compiled code is the latest code of the main branch, I also tried the code submitted by v1.8.31, the compilation can be successful, but the compiled static library file cannot be correctly referenced, I would like to consult you locally in the development or compilation of which tools or dependencies are used, what is the version? Note: Before compilation, the tools required by tdlib in ReadME have been installed, and the versions meet the requirements

**Comment by levlam** [comment]
Binaries aren't portable between different OS versions. You may encounter a lot of issues, trying to use a binary, including static library, on a different OS.

**Comment by yg66** [comment]
The environment is consistent, and the operating system and version used to compile tdlib are consistent with the operating system and version used by the application that rebuilds the static library file compiled by tdlib, because they all use the same docker base image

**Comment by levlam** [comment]
Then, what exactly doesn't work for you?
