### ISSUE TITLE
Issue implementing on android project 

### ISSUE THREAD

**Issue by rabbi-islam** [tdlib/td#2948]
Currently my need is implement this in my kotlin android project to fetch all message/post from a public telegram channel , but the documentation of your is too much complicated to understand for me, since there is not direct dependency to proceed with. so can you please provide my step by step guideline to achieve my functionality by using your library, Will be really grateful to you.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started.

**Comment by thulc-android** [comment]
Hi @levlam I have followed the mentioned document and I have compiled the tdlib using CMake, so Now how should i proceed forward? I don't see any .SO files being generated inside the build folder.

**Comment by levlam** [comment]
@thulc-android 
Did you follow https://github.com/tdlib/td/blob/master/example/README.md?
Did all scripts finish without errors?

**Comment by itsgeniuS** [comment]
Hi @levlam Thanks for your response. I was able to backtrack the errors with the logs and I have fixed them. Now im able to run the scripts and Its running and generating the .SO files as well. 

Thanks.
