### ISSUE TITLE
An unnecessary API?

### ISSUE THREAD

**Issue by Titlehhhh** [tdlib/td#2950]
I am far from C++ topic, but in tdlib code I see such classes and structures: AccentColorId, AccountManager, AudiosManager and others.
What are they for if they cannot be accessed? When you build this library according to the instructions, you get only these header files, which contain several classes that have nothing to do with the above mentioned ones: 
![image](https://github.com/tdlib/td/assets/93156853/355c4210-d27c-49c3-bf88-831871be0aa6)

**Comment by levlam** [comment]
All public API can be used using the classes on the screenshot. See https://core.telegram.org/tdlib/getting-started.

**Comment by Titlehhhh** [comment]
I'm not a native English speaker. so maybe the translation let me down a bit. 

I realized that I can access the API in the screenshot. I am wondering if I can access these classes? ->
![image](https://github.com/tdlib/td/assets/93156853/766cf389-5338-44b7-b965-c1233e689bec)

**Comment by Titlehhhh** [comment]
I've seen that many people don't build tdlib, but just add it as a git submodule.

**Comment by levlam** [comment]
No, you can't. All public API can be accessed using the classes on the screenshot.
