### ISSUE TITLE
Sending an image does not prompt failure, but it did not succeed

### ISSUE THREAD

**Issue by hytRain** [tdlib/td#2953]
The language is golang
`func SendMessageTdLib(tdClient *tdlib.Client, chatId, replyToMessageId int64, content string, imgPath string) (msgId int64, err error) {
	// 发送图片，否则发送文本
	var inputMessageContent tdlib.InputMessageContent
	if len(imgPath) > 0 {
		inputMessageContent = tdlib.NewInputMessagePhoto(tdlib.NewInputFileLocal(imgPath), nil, nil, 0, 0, sendText, 0)
	} else {
		inputMessageContent = tdlib.NewInputMessageText(tdlib.NewFormattedText(content, nil), true, true)
	}
	// 发送消息
	msg, err := tdClient.SendMessage(chatId, int64(0), replyToMessageId, nil, nil, inputMessageContent)
	if err != nil {
		log.Errorf("")
		return
	}
	msgId = msg.ID
	return
}`

**Comment by levlam** [comment]
What error do you receive?

**Comment by hytRain** [comment]
I haven't received any errors

**Comment by levlam** [comment]
Do you receive response for `sendMessage` request?

Do you handle `updateMessageSendSucceeded` and `updateMessageSendFailed` updates?
