### ISSUE TITLE
Getting 401 on authentication attempt.

### ISSUE THREAD

**Issue by tilvin** [tdlib/td#2956]
I am trying to use old Ruby gem, and having hard times to make it work.
But i think my current issue is not related to Ruby lib "old-fashioned".

I authorized and using this lib, then i destroy my client (https://www.rubydoc.info/gems/tdlib-ruby/2.2.0/TD%2FClientMethods:destroy) and since that i can't login back.

```
client.request_qr_code_authentication(other_user_ids: nil).wait
-> getting link
client.confirm_qr_code_authentication(link: "tg://login?token=received link")
-> {"@type":"error","code":401,"message":"Unauthorized","@extra":"some extra"}.
```

Does anyone have any clue?

**Comment by levlam** [comment]
The method `confirm_qr_code_authentication` must be called by another logged in device to confirm authorization. You can't call it before compliting authorization.

**Comment by tilvin** [comment]
Yes, thank you, my issue was related to ruby lib desuetude , thank you, closing here.
