### ISSUE TITLE
clearRecentlyFoundChats does not clear properly?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2957]
It seems like calling `clearRecentlyFoundChats` makes no difference.
After `clearRecentlyFoundChats`, I called `getRecentlyOpenedChats` which returned the same set of chats again.

**Comment by levlam** [comment]
`clearRecentlyOpenedChats` clears the chats returned by `searchRecentlyFoundChats` and `searchChats` with an empty query.

Recently opened chats are used in macOS app in the fast forward menu and can't be cleared.

**Comment by vincentneo** [comment]
Thanks @levlam, guess I misunderstood and instead searchRecentlyFoundChats is what I needed.
