### ISSUE TITLE
Is there any telegram group to discuss usages of tdlib?

### ISSUE THREAD

**Issue by mkliu** [tdlib/td#296]
See one from #133 , but link has expired

**Comment by levlam** [comment]
I don't know an active chat about TDLib, but if you have some questions, you can ask them through @tdlib_bot.

**Comment by mkliu** [comment]
hmm, how does the bot work? @levlam

**Comment by levlam** [comment]
It's a chat bot.

**Comment by wfjsw** [comment]
What is that bot exactly? @tdlib_bot or @tdlibbot 
I got some responses from the latter one.

**Comment by levlam** [comment]
Both.
