### ISSUE TITLE
[question] Why doesn't tdlib support action builds or other means of binary distribution?

### ISSUE THREAD

**Issue by YuHuanTin** [tdlib/td#2961]
In the last two days I tried to build tdlib using github's action and I found that he can work well and reduce the time needed for development (less manual compilation process), so what is the reason for not having the binaries or the action available?

I checked the list of [issue](https://github.com/tdlib/td/issues/30) and found a question saying to have vcpkg support source compilation, and it doesn't seem to be moving, so I'm confused

**Comment by levlam** [comment]
Binaries aren't portable by definition and usually can be used only with specific OS version, so they will be hardly usable by real users. Also, TDLib supports many more operating systems than available on Github actions.

**Comment by YuHuanTin** [comment]
> 二进制文件从定义上来说不可移植，通常只能在特定操作系统版本上使用，因此实际用户几乎无法使用它们。此外，TDLib 支持的操作系统比 Github 操作上提供的操作系统多得多。

I agree with the last point, but binary distribution is indeed feasible on mainstream windows, linux and out of the troublesome build process? (I think)

**Comment by levlam** [comment]
Binary distributions are feasible for Windows and macOS, but not Linux because of too many mutually incompatible distros. Additionally, build process on Linux is very easy.

**Comment by YuHuanTin** [comment]
You're right, I guess I think action is the easiest way to compile on windows (since that's all I use myself at the moment)
