### ISSUE TITLE
UPDATE_APP_FOR_LOGIN

### ISSUE THREAD

**Issue by Giovaxx541** [tdlib/td#2962]
good morning , telegram media player no longer works on my fire stick because I accidentally clicked logout and now when I enter the phone number the text appears 
UPDATE_APP_FOR_LOGIN.
Can anyone help me??

**Comment by levlam** [comment]
You need to update the app/TDLib to the latest version.

**Comment by levlam** [comment]
If you aren't the creator of the app, then you need to wait for the owner of the app to update it.

**Comment by golanguzb70** [comment]
> You need to update the app/TDLib to the latest version.

Can anyone say what is the latest version?

**Comment by levlam** [comment]
The latest version is the version from master branch on Github. Currently, it is 1.8.33.

**Comment by levlam** [comment]
@sepbehroozi 
Follow build instructions https://tdlib.github.io/td/build.html.

**Comment by matthewTaheri** [comment]
hi, I hope you have a good day. can you please update the prebuild version for the Java example? it gives me UPDATE_APP_FOR_LOGIN error. I can't build Tdlib myself and have to use the prebuild.

**Comment by levlam** [comment]
@matthewTaheri
There is no more official prebuilt versions.

**Comment by Parrahimovic** [comment]
dev hasn't updated app in years. Is the app dead?

**Comment by petersonti** [comment]
I have same problem and I don't know other to fix it.

**Comment by Diljithhh** [comment]
Is there any update?
