### ISSUE TITLE
UPDATE_APP_FOR_LOGIN in the Android Pre-built library

### ISSUE THREAD

**Issue by waarlockk** [tdlib/td#2963]
Hi, I am using the pre-build tdlib for Android but when logging in with a mobile number  I am getting 406, UPDATE_APP_FOR_LOGIN error.
I tried building for Android using the Dockerfile but it seems that current master branch is having some unmerged conflicts causing the build failure.

Any help? Thanks!

```
td/CMakeFiles/tdcore.dir/td/telegram/SendCodeHelper.cpp.o -c /home/td/td/telegram/SendCodeHelper.cpp
327.0 /home/td/td/telegram/SendCodeHelper.cpp:232:1: error: version control conflict marker in file
327.0 <<<<<<< HEAD
327.0 ^
327.0 1 error generated.
```

**Comment by levlam** [comment]
Thank you. The compilation error has just been fixed in master.

**Comment by Framidil** [comment]
@levlam Hi. Can you tell me when the precompiled library for Android will be updated?

**Comment by waarlockk** [comment]
Thanks @levlam for the fix. I was able to build for Android.

**Comment by levlam** [comment]
@Framidil Precompiled library for Android will never be updated. https://github.com/tdlib/td/tree/master/example/android should be used instead to build any TDLib commit for Android in the required way.
