### ISSUE TITLE
Delete a message: What should happen on reply messages?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2964]
So when a message is delete we get updateDeleteMessages and remove them from our view model, if they have been loaded there. But lets say, there is a message that is a reply to a now deleted message.

There is no update available to modify the reply_to data of a message. So in this case we would still show the citation header on this message with the summary. But the official client immediately says "deleted message" instead.

How do you propagate this change? Is there a lookup table for message citations that is used to update the replies? Just being curious since currently we crash the app if you click on the citation to jump to the deleted message :)

**Comment by levlam** [comment]
The other clients traverse all messages from the chat that are present in memory and update relevant reply_to data whenever a message is deleted or edited.

**Comment by Flohack74** [comment]
Ah ok so thats actually easy: set it to 0, will default to display a deleted message, thanks!
