### ISSUE TITLE
You may have encountered a bug in the Ruby interpreter or extension libraries.

### ISSUE THREAD

**Issue by dronmaxman** [tdlib/td#297]
ruby 2.3.3p222
debian 9.1
https://github.com/centosadmin/redmine_telegram_common
bundle exec rake telegram_common:bot

I want to use module with redmine plugin, when start plugin I have got error (see log file).

You may have encountered a bug in the Ruby interpreter or extension libraries.
[tdlib_1.log](https://github.com/tdlib/td/files/2136663/tdlib_1.log)

**Comment by levlam** [comment]
You need to specify correct api_id (integer) and api_hash (string) in `setTdlibParameters` request. They can be obtained at https://my.telegram.org.

**Comment by dronmaxman** [comment]
Thanks to all. I found a problem - two factor authentication in telegram.
