### ISSUE TITLE
how to rebuild when at first build for python and then want to build also for java

### ISSUE THREAD

**Issue by zizhuangfly** [tdlib/td#2970]
at first I build td project following the instructions as [python](https://tdlib.github.io/td/build.html?language=Python) page shows, it took over an hour and succeed. after this, I realized that I also need [java](https://tdlib.github.io/td/build.html?language=Java). as to rerun the whole build process will take a lot of time, I'm wondering if "Incremental" build is possible? I tried  [java](https://tdlib.github.io/td/build.html?language=Java) build instructions, it is slow as before, computer fans shouting and I `ctrl+c` interrupted it.
per my shallow understanding,`jni` needs extra wrapper, the bins dylib/so/dll should be shared in common?
How can I build td for `java` when I succeeded building it for `python`?
Thanks so much for offering so powerful tool.

**Comment by levlam** [comment]
No, Java build produces a very different binary, because all interface classes include methods for JNI interface. You need to build them independently.

**Comment by zizhuangfly** [comment]
OK, got it. Thank you so much for respond so quickly.
But still I cannot get my head around, `JNI` is just a bridge to td "island", and there is no need to rebuild the island for the bridge. perhaps for the current `cmake` is impossible to achieve this, but this can be a feature or improvement in the future?

**Comment by levlam** [comment]
JNI interface converts between native C++ classes and Java classes. The conversion uses autogenerated methods and fields that are part of the C++ interface classes and are generated only when TDLib is built with JNI interface. This makes Java build binary incompatible with Python build, which uses ordinary C++ interface classes.

**Comment by zizhuangfly** [comment]
I see what you mean probably.
td keeps the generated bins as a whole and makes it simple. what if  adding a layer of abstraction/wrapper for `jni`, this layer is the bridge written with C++, and dispatches function invoke to the  behind bins. then this auto generated C++ layer can be built independently, and the behind bins can be shared in common. 
I know `jni` only a little, and it's just my guess, so is that possible?

**Comment by levlam** [comment]
It is possible, but currently there is no separate generator for JNI binding. Instead, when TDLib is built with JNI interface, a slightly modified generator for C++ interface classes is used, and a different classes are used throughout the code.

**Comment by zizhuangfly** [comment]
I see, thank you so much for your patient, quick and detail explanation.
I will close this issue, and be looking forward to the alternative way occurs
