### ISSUE TITLE
How to install cmake3

### ISSUE THREAD

**Issue by handsomeQPO** [tdlib/td#2977]
I am a new scholar, as I follow the steps of this tutorial https://tdlib.github.io/td/build.html command line output error No package cmake3 available. How to install cmake3?please teach me,thanks

**Comment by levlam** [comment]
This depends on you operating system and package manager.

**Comment by handsomeQPO** [comment]
My system is Centos7

**Comment by levlam** [comment]
Then you can choose CentOS 7 in the build instruction generator to get exact build instructions.

**Comment by levlam** [comment]
The package cmake3 has been previously available. CentOS 7 isn't supported anymore, so there can be issues with its package manager right now. You can also install CMake manually from https://cmake.org/download/.

**Comment by handsomeQPO** [comment]
There is a CMake environment on my machine,do I need to configure a soft chain？

**Comment by handsomeQPO** [comment]
The basic environment has been improved,but cmake --build . --target install ，console output error during command execution

**Comment by handsomeQPO** [comment]
such as /td/tdutils/td/utils/unique_ptr.h:40:30: error: expected type-specifier

**Comment by levlam** [comment]
This looks like an error from an old g++ version. Make sure to install all packages mentioned by the build instrcutions generator before running CMake for the first time. Delete `build` directory and recreate it if you have run CMake without some packages installed.

**Comment by handsomeQPO** [comment]
My version is 4.8.5, it may be too old

**Comment by handsomeQPO** [comment]
when I execute cmake -- build-- target install,scann CMake Error: The source directory "/home/NetPF/td/build/CMakeFiles/progress.marks" does not appear to contain CMakeLists.txt, why is this ?

**Comment by handsomeQPO** [comment]
Where should I execute it?/td/build/ or /td/ ???

**Comment by handsomeQPO** [comment]
I encountered this error while executing in the/td/build/directory

**Comment by levlam** [comment]
You need to follow the build instructions https://tdlib.github.io/td/build.html and don't change directories between commands.
