### ISSUE TITLE
[Q] Is Java Client production ready?

### ISSUE THREAD

**Issue by ya-ne-vor** [tdlib/td#2979]
Hi! I want to use TDLib in a Java project. I see the example in `example/java` folder. Can I just use `Client.java` and be sure that it's stable enough (meaning most of the time it will work without any issue, e.g. no sudden shutdowns, lost updates, etc)?

Also I have another question: how can I interrupt `ResponseReceiver` if it has [a huge timeout](https://github.com/tdlib/td/blob/cb164927417f22811c74cd8678ed4a5ab7cb80ba/example/java/org/drinkless/tdlib/Client.java#L170)? As I understand the `ResponseReceiver` spawned as a daemon thread, and it's killed by JVM when exiting. Can I interrupt/terminate `ResponseReceiver` (or equally `nativeClientReceive` with a huge timeout) manually? Or, instead, the solution is to set a small timeout?

Thanks!

**Comment by levlam** [comment]
TDLib is very stable.

There are no reasons to interupt `ResponseReceiver` manually.

**Comment by ya-ne-vor** [comment]
> There are no reasons to interupt `ResponseReceiver` manually.

I wanted to write custom runloop, but since `Client.java` is stable, I think, I can use it and don't invent the wheel.
