### ISSUE TITLE
Strange behavior with getChannelDifference

### ISSUE THREAD

**Issue by vitalibr** [tdlib/td#298]
I noticed a strange behavior in **getChannelDifference**.
Some channel messages are sometimes not returned. In some cases of 13 messages sent in a channel (in 1 hour) only 10 were returned, but in the official mobile application (android) appeared the 13 messages. I'm using the [pyrogram](
https://github.com/pyrogram/pyrogram/blob/3409963a4a80ede0a256303e4426f97da255cbf7/pyrogram/client/client.py#L788)

I noticed the same behavior using other libraries (python, java and php). And other people with the same problem (for example [here](https://stackoverflow.com/questions/49226903/not-receiving-all-telegram-notifications-from-telegram-client-api)), I was unable to identify the reason for this, but I am in doubt whether the libraries are using the wrong Tdlib or if it can be a problem in the telegram.

**Comment by levlam** [comment]
If these libraries has `getChannelDifference` method, than they don't use TDLib, TDLib doesn't provide a way to manually fetch updates, because it is really hard to implement updates fetching right. Instead, TDLib internally uses `getChannelDifference` and a lot of other ways to receive all messages and provides application with consistent stream of updates about new messages. There should be no unintentionally missed messages in TDLib updates.

**Comment by levlam** [comment]
Could you collect TDLib logs with verbosity level 3 by changing the line
```
td_set_log_verbosity_level(2)
```
with
```
td_set_log_verbosity_level(3)
td_set_log_max_file_size(100000000)
td_set_log_file_path('tdlib_log.txt')
```
and send the log written to `tdlib_log.txt` to @tdlib_bot?
The log will contain a lot of private data, so feel free to censor whatever data you want before uploading the log.

**Comment by vitalibr** [comment]
Sure, on it @levlam 

changed to:
```td_set_log_verbosity_level(3)
td_set_log_max_file_size(100000000)
td_set_log_file_path(bytes('tdlib_log.txt', encoding='utf-8'))```

I'll keep running the script until it happens again, the channel is not mine, so I can not send messages to force the issue.

**Comment by visor24** [comment]
I'm having a same problem with both of pyrogram and tdjson python example, have you resolved this issue?
