### ISSUE TITLE
Can this be used for mock telegram server?

### ISSUE THREAD

**Issue by doaortu** [tdlib/td#2982]
I want to build a simulation testing for my telegram bot, so I don't have to hit the real telegram api.

I need to test my bot if it can handle thousand of group without breaking, so I need this kind of simulation.
without simulation, I need to create thousand of groups, and automate it somehow.

Is there a better way of doing this? Is this the correct repo to do something like this?

Thanks

**Comment by levlam** [comment]
No.

**Comment by doaortu** [comment]
Ah okay, thanks for answering.

Do you have any pointer for mocking telegram api? Is there any library to do that already?

**Comment by levlam** [comment]
I'm not aware of such libraries.

**Comment by doaortu** [comment]
okay, closing this issue. 
Thanks.
