### ISSUE TITLE
database directory parameter not work

### ISSUE THREAD

**Issue by zizhuangfly** [tdlib/td#2983]
I have a TDLib program in java, which can run well in local dev environment, but cannot work on server.
the question is the `database_directory` param setting is not working on the server, the directory exists and can be written or read, but TDLib seems just ignore the param setting, and creates a subdir named `null` in the current work directory. It's really very weird, the created directory name is just `null` literally, 4 chars.
here is the view of the the directory:

./null
|-- database
|   \`-- td.binlog
`-- files

I cannot figure out how this happens, hope someone can shed a light on this.

**Comment by zizhuangfly** [comment]
sorry, I made a mistake, should check my own code again and again....

**Comment by levlam** [comment]
You pass "null" as the value of `database_directory`.

**Comment by zizhuangfly** [comment]
yes, I supposed the config value had been configured and read correctly, while it was not true.
the configured value was changed by some middle-step, thus correct input but got wrong output.
log showed input, but ignored output. very stupid mistake.
