### ISSUE TITLE
Offset value is incorrect is case Message begins with emoji.

### ISSUE THREAD

**Issue by tilvin** [tdlib/td#2984]
Hello, could please someone help me, i face this problem:
When message string begins with emoji, entities offset is somehow wrong. 
For example: i send a message:
😀q**werty**
I receive a Message with content:
 _content=#<TD::Types::MessageContent::Text text=#<TD::Types::FormattedText text="😀qwerty" entities=[#<TD::Types::TextEntity offset=3 length=5 type=#<TD::Types::TextEntityType::Bold>>]> web_page=nil> reply_markup=nil>_
 
 It says that in my message bold text begins from symbol n 3. So i insert `<b>` tag to third symbol of string and the result is 
 😀qw**erty**.
 
 In case there's no emoji at the beginning of string, offset is correct.
 I send message: q**werty**
 I receive a Message with content:
 _content=#<TD::Types::MessageContent::Text text=#<TD::Types::FormattedText text="qwerty" entities=[#<TD::Types::TextEntity offset=1 length=5 type=#<TD::Types::TextEntityType::Bold>>]> web_page=nil> reply_markup=nil>_
 
 So bold text starts with 1st symbol, which is correct.

**Comment by levlam** [comment]
See documentation for the fields:
```@offset Offset of the entity, in UTF-16 code units
@length Length of the entity, in UTF-16 code units```

See https://en.wikipedia.org/wiki/UTF-16 for description of UTF-16 encoding and how to handle correctly the offset.

**Comment by tilvin** [comment]
Thank you!

**Comment by tilvin** [comment]
If someone face same problem and using Ruby on Rails, please find my comment https://github.com/southbridgeio/tdlib-ruby/issues/66
