### ISSUE TITLE
GetChat/LoadChat not work

### ISSUE THREAD

**Issue by littleboyonearth** [tdlib/td#2985]
before sendMsg, I tried 
``` java
client.send(new TdApi.LoadChats(new TdApi.ChatListMain(), 100)`, handler);
client.send(new TdApi.GetChats(new TdApi.ChatListMain(), 100), handler);     
client.send(new TdApi.GetChat(chatId), new UpdateHandler());
```
but just get 
```
Error {
  code = 400
  message = "Chat not found"
}
```
this error is caused by the last line, `getChatById`.

and after sendMsg, same response received.

pls help.

**Comment by littleboyonearth** [comment]
what I know: if local db not init, or the first launch, then `getChat` has to happen before `sendMsg`.
so after succeeding authentication, I tried to `loadChat`, which had no effect, without any related response received, so I tried to `getChatById`, which just resulted the 400 error as above showed.

**Comment by levlam** [comment]
You must receive the chat from TDLib first before you can use its identifier. You can do this in exactly the same way you would do from a GUI app.

**Comment by littleboyonearth** [comment]
after adjusting the log level, I see what happens. it's a net proxy problem. when logLevel set to 0, there is no any related logs output.
Thank you for support!

**Comment by littleboyonearth** [comment]
I set proxy during sometime before, and later, I comment the setting lines
``` java
client.send(new TdApi.AddProxy(proxyServer, proxyPort, true, new TdApi.ProxyTypeSocks5()), null);
```
and relaunch, I thought that will not bypass proxy, but the logs suggests that TDLib `remember` the proxy setting before and use it even later I don't set.
this behavior is just like an app(even though you run the program just like a command line ), set and remember, and must `disableProxy` if you don't want a proxy.
Hope this will help someone.
