### ISSUE TITLE
UnsatisfiedLinkError using JNI for Java

### ISSUE THREAD

**Issue by MaxiGH** [tdlib/td#299]
I compiled everything so far on a windows 10 system and tried now to execute the example Java code using the given explanation. (for x64 system) I used MSVC and the Visual Studio 15 generator for cmake. 
There were no errors at compile time left and everything built properly.

At the last step I typed:

`java -Djava.library.path=. org/drinkless/tdlib/example/Example`

and I get: 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Maxi\Desktop\One\td\example\java\bin\tdjni.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.drinkless.tdlib.example.Example.<clinit>(Example.java:58)`

It is stated to add the libs which were used to the java/bin/ directory (next to the tdjni.dll I suppose). First of all, I don't even know which lib is used from the tdjni.dll and where to find them. I already tried to copy all the .dll's and .lib's files from my project into the java/bin directory. Still no success. Does anybody have an idea for a solution?

**Comment by levlam** [comment]
You need to copy `LIBEAY32.dll`, `SSLEAY32.dll` and `zlib1.dll` from `example\java\build\Release` folder for Release build or `LIBEAY32.dll`, `SSLEAY32.dll` and `zlibd1.dll` from `example\java\build\Debug` for Debug build.

**Comment by MaxiGH** [comment]
Thanks for the fast reply! I' sure I compiled for release build, but there  is no Release directory next to Debug. So I looked in the Debug dir and found `LIBEAY32.dll, SSLEAY32.dll`, but there is no `zlibd1.dll`. Beside that i tried it with only the 2 of these dll files and I got now a different exception:

`C:\Users\Maxi\Desktop\One\td\example\java\bin>java -Djava.library.path=. org/drinkless/tdlib/example/Example
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Maxi\Desktop\One\td\example\java\bin\tdjni.dll: %1 is no valid win32 application
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.drinkless.tdlib.example.Example.<clinit>(Example.java:58)`

I searched for it and it seems that the dll's are the problem, compiled to another format. While building in jnibuild directory I used the `-A x64` flag. Is that probably causing this problem? I guessed I had to use this flag when creating the cmake configuration before building like this:

`cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=<full path to TDLib sources>/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. .. -A x64`

after that I did:

`cmake --build . --target install`  as described. Is that the right way to compile for a 64 Bit version?

**Comment by levlam** [comment]
If you want to build 64-bit version. you need to specify `-A x64` in both cmake invocations. You will need to delete the whole build directory before re-running cmake with changed parameters.

You can also use 32-bit library version, specifying -d32 parameter to java.

To build for Release using MSVC you need to run `cmake --build . --target install --config Release`.

**Comment by Pepesote** [comment]
Can I know in which directory did you copy the `LIBEAY32.dll, SSLEAY32.dll` libraries please @MaxiGH ?

**Comment by levlam** [comment]
Libraries should be copied to `example\java\bin` folder.

**Comment by MaxiGH** [comment]
Hallo again, I rearranged that project and have some new issues. I want to compile that project for Java x64 on Windows.

So what I am doing, is 2 steps for building. First: Build jnibuild:

`cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td .. -A x64 -DCMAKE_TOOLCHAIN_FILE=<VCPKG_DIR>/scripts/buildsystems/vcpkg.cmake`

and after cmake configuration:

`cmake --build . --target install --config Release`

Now I go into /example/java/build:

`cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=<full path to TDLib sources>/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. .. -A x64 -DCMAKE_TOOLCHAIN_FILE=<VCPKG_DIR>/scripts/buildsystems/vcpkg.cmake`

then I get a note in the progress, 

CMake Error at C:/Users/Maxi/Desktop/td/TdConfig.cmake:3 (include):
include could not find load file:

C:/Users/Maxi/Desktop/td/TdTargets.cmake
Call Stack (most recent call first):
CMakeLists.txt:5 (find_package)

I tried to search for that file and found two, one in td/jnibuild and the other one somewhere in the java directory. I tried to copy both, but it ended with weird file include path errors. So I guess these files are not to be meant to use.

after that I assume to finish building process with:

`cmake --build . --target install --config Release`

I guess using the vcpkg toolchain file for both cmake parts (jnibuild and java/build) is right. I also use -A x64 in both lines.  If it would work, I would have used the same `cmake --build` command than before. Is that a correct assumption? I don't get what I'm missing, for jnibuild everything looked fine. Can you help me out?
