### ISSUE TITLE
Account Banned 

### ISSUE THREAD

**Issue by smartgcfc** [tdlib/td#2991]
Dear Telegram Support Team,
I hope this message finds you well. My name is Smart Gcfc, and I am writing to request your assistance regarding my Telegram account associated with the phone number +2348135082742.
Unfortunately, my business account has been banned, and I am unsure of the reason behind this action. My account is crucial to my business operations, and I would greatly appreciate your help in reviewing and reinstating it.
Here's the information about my device and Telegram app:
App version: 10.14.4 (49312)
OS version: SDK 30
Device Name: INFINIX MOBILITY LIMITEDInfinix X665B
Locale: en
I understand that you have many users and requests to attend to, but your help in this matter is essential for my business. Thank you for taking the time to review my request, and I look forward to hearing from you soon.
Sincerely,
Smart Gcfc

**Comment by levlam** [comment]
You aren't writing to Telegram Support Team.  If you think that the account was banned by a mistake, please try to log in to the account from an official mobile app and send an email to recover the account by following instructions provided by the app.
