### ISSUE TITLE
halo, tolong bantu saya, akun saya telah di bajak orang lain, dan langsung di ubah ke nomor luar negeri, semua foto dan password akun saya di sana semuaa, tolong bantu sayaaa

### ISSUE THREAD

**Issue by keysia547** [tdlib/td#2993]

**Comment by levlam** [comment]
We can't help with this.

**Comment by keysia547** [comment]
> Kami tidak dapat membantu dalam hal ini.

bagaimana cara mendapatkan kode verifikasi dari email??

**Comment by levlam** [comment]
You need a phone number to log in. If you were asked to enter a code sent to an email address, then you need access to the address.

**Comment by keysia547** [comment]
> Anda memerlukan nomor telepon untuk masuk. Jika Anda diminta memasukkan kode yang dikirim ke alamat email, maka Anda memerlukan akses ke alamat tersebut.

sudah, tapi tetap saja di minta kode lagi dari telegram, tolong dong bantu saya

**Comment by levlam** [comment]
You need to enter both codes from email and from the mobile phone when asked.

**Comment by keysia547** [comment]
> Anda perlu memasukkan kedua kode dari email dan dari ponsel saat diminta.

iya tapi nomor akun saya di ubah di bajak ini ke nomor luar negeri, saya tidak dapat menerima kode nya

**Comment by levlam** [comment]
Then, this isn't your account anymore. You can only register a new account to the old number.

**Comment by keysia547** [comment]
> Jadi, ini bukan akun Anda lagi. Anda hanya dapat mendaftarkan akun baru ke nomor lama.

maksudnya gimnaa??

**Comment by levlam** [comment]
If phone number on the account was changed, which is possible to do only if device of the original owner of the account was hacked or the owner allowed the intruder to log in to the account and didn't terminated the new session in 24 hours, then there is no way to return access to the account. But if the phone number was changed, then the old phone number can be used to create a new account.

**Comment by keysia547** [comment]
> Jika nomor telepon pada akun diubah, yang hanya dapat dilakukan jika perangkat pemilik asli akun diretas atau pemilik mengizinkan penyusup masuk ke akun dan tidak mengakhiri sesi baru dalam 24 jam, maka tidak ada cara untuk mengembalikan akses ke akun tersebut. Namun, jika nomor telepon diubah, maka nomor telepon lama dapat digunakan untuk membuat akun baru.

tapi aku gamau akun baru, aku ingin akun aku yang lama kembali, karena semua tersimpan di sanaa

**Comment by levlam** [comment]
If the account phone number was changed, this is impossible now.

**Comment by keysia547** [comment]
> Jika nomor telepon akun diubah, hal ini tidak mungkin lagi dilakukan.

jadi gimana dong solusi nya, masa gabisaa, mohon info untuk nerima kode lewat email

**Comment by levlam** [comment]
You can't choose the way to receive the code. Also, if phone number was changed, then email is likely to be changed too.

**Comment by keysia547** [comment]
tolong bantu bajak akun yang telah di ambil dongg, tolongin saya, bajak aja akunya supaya saya bisa masuk akun lagi

**Comment by levlam** [comment]
This is not possible.
