### ISSUE TITLE
Is it necessary to build tdutils to include it?

### ISSUE THREAD

**Issue by Guitarmadillo** [tdlib/td#2994]
I am needing to include tdutils in order to access td::TlStorerToString functionality. I keep getting an error saying the compiler cannot open the include file td/tdutils/config.h. This file does not exist in that directory. Any help is appreciated.

**Comment by levlam** [comment]
You need to use CMake to correctly manage dependency of your project from `tdutils`.

**Comment by Guitarmadillo** [comment]
I have succeeded in including what I needed. My next question is related to the TlStorerToString type. Is this object meant to be converted to an std::string? I can't seem to find a way to print out the result of this variable after calling the store() method on a chat object, or one of it's member variables.

**Comment by levlam** [comment]
You never need to use TlStorerToString for TDLib API classes. You can find all public methods in td/telegram/td_api.h and you can use td::td_api::to_string to print a TDLib API object.
