### ISSUE TITLE
Easier way to determine if current user is a chat admin than via searchChatMembers ?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2996]
Hi there, 

I I want, lets say, determine if a user can ban a user and delete messages I would need to call searchChatMembers for that particular user every time I enter a chat, with the right query and filter set. And then walk down chatMember->status->chatMemberStatusAdministrator->rights->can_delete_messages|can_restrict_members or of course its chatMember->status->chatMemberStatusCreator 

That sounds complex, is there a better way to do this?

**Comment by levlam** [comment]
There is no. You need to check user rights in chat member status.
