### ISSUE TITLE
I can't send a video to a secret chat.

### ISSUE THREAD

**Issue by fat-complex** [tdlib/td#2997]
I'm trying to send a video to a secret chat. I use a bunch of `SendMessage` and `inputMessageVideo` requests. In regular chats with such a bunch of requests, the video is sent and you can watch it, and in secret chats you can see that you have received a video message but you cannot watch it. It's empty. Do I need to do something extra so that I can send videos to a secret chat?

**Comment by levlam** [comment]
What is the app on the other side?

**Comment by fat-complex** [comment]
@levlam  the client on iOS

**Comment by fat-complex** [comment]
@levlam I use this code: 
```
    auto mc = make_tdobj<inputMessageVideo>();
    mc->thumbnail_ = nullptr;
    mc->video_ = make_tdobj<inputFileLocal>(path.toStdString());
```
This code for sending videos works in other chats instead of the secret one.

**Comment by fat-complex** [comment]
I figured it out. You need to manually generate a thumbnail for the video and set the video dimensions. In my case, it worked.
