### ISSUE TITLE
java, how to convert object to json and have a special field "_" which is the class name

### ISSUE THREAD

**Issue by ngocnk99** [tdlib/td#2998]
below is an object in java (https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_basic_group.html) :

![image](https://github.com/user-attachments/assets/38322f1e-5d31-4bb6-9e69-a953c52c887b)

-----------------------
For use in react native, so I want to convert to json.
But if I use the usual method, such as using Gson, I will get the result as below

![image](https://github.com/user-attachments/assets/74de9f33-ee43-44e7-8b69-ad9a1602601a)

  with the above results, it is unclear which object "status" is in: chatMemberStatusAdministrator, chatMemberStatusCreator, chatMemberStatusMember,...
---------
So i want the result to be the same as in nodeJS for example
![image](https://github.com/user-attachments/assets/0c2c83f3-6d3d-4663-a8cb-13537aa2287a)

**Comment by levlam** [comment]
There is no way to do this. You can only do that only manually.
