### ISSUE TITLE
setProxy before connect client?

### ISSUE THREAD

**Issue by mkliu** [tdlib/td#300]
Am I able to set proxy before connect client? I tried it but program just exits directly.
But if I connect first, then call proxy the code is working. However, I do want to set proxy upfront. I could see the telegram desktop client allows this too.

**Comment by levlam** [comment]
Currently, you can set proxy just after call to setDatabaseEncryptionKey.

**Comment by mkliu** [comment]
thanks @levlam , can you give me an example? Normally I'm not supposed to call setDatabaseEncryptionKey, right?

**Comment by levlam** [comment]
You always need to call setDatabaseEncryptionKey after setTdlibParameters, but that may be done by wrapper you are using.

Between, setProxy can be called any time after library initialization and the proxy persists between application restarts. Why it isn't enough for you?

**Comment by mkliu** [comment]
Thanks. I checked the binding code and did see that handling. I guess setDatabaseEncryptionKey and setTdlibParameters contact telegram data center at all yet? Coz there would be cases where client doesn’t have access to dc and need to setup proxy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by levlam** [comment]
No, they don't need network access. TDLib works fine without network access.

**Comment by mkliu** [comment]
That’s great! Thanks very much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mkliu** [comment]
@levlam I have a followup question. So I'm able to setProxy correctly. Is it feasible to make it take effect immediately? 

Looks like setProxy will trigger a background async operation to actually set proxy. When I give a bad proxy, it would print

`[PosixError : Network is unreachable : 51 : Read from fd 49 has failed]`

But at the same time, the client would continue with previous settings. The effect I want is, if I set proxy, regardless if it's a correct proxy or not, I want it to take effect immediately without testing the proxy. 

Is that feasible?

**Comment by levlam** [comment]
setProxy immediately changes library behavior. When you receive response to the request, you can be sure that the proxy is already used.

`Network is unreachable` is an ordinary network error, which usually means that there is no network connection on the server.

**Comment by levlam** [comment]
Since TDLib 1.3.0 `addProxy` can be called to enable proxy any time, even before `setTdlibParameters`.
