### ISSUE TITLE
"Last server dialog date didn't increased from"

### ISSUE THREAD

**Issue by avosirenfal** [tdlib/td#3004]
I have one particular account that causes this hard crash of tdlib, but only when logging in from a saved auth and message database. What's going on? Is this something I can fix?

This using tdlib and Python as in the [Python example](https://github.com/tdlib/td/blob/master/example/python/tdjson_example.py) on the production servers - not the test DC.

```
<= {'@type': 'updateAuthorizationState', 'authorization_state': {'@type': 'authorizationStateReady'}, '@client_id': 2}

=> {'@type': 'getMe', '@extra': 1}
=> {'@type': 'getChats', 'limit': 100, '@extra': 2}

<= {'@type': 'updateAnimationSearchParameters', 'provider': 'tenor', 'emojis': ['👍', '😘', '😍', '😡', '🥳', '😂', '😮', '🙄', '😎', '👎'], '@client_id': 2}

[ 1][t 8][1722262025.385882377][MessagesManager.cpp:14867][#2][!Td]      Last server dialog date didn't increased from [7331087365533859959, -4163305030] to [9223372036854775807, 0] after receiving 1 chats {chat -1002091911407} from 8 in folder 0. last_dialog_date = [7331087365533859959, -4163305030], last_loaded_database_dialog_date = [0, 0]
```

**Comment by avosirenfal** [comment]
We deleted all the group chats on the account, and it doesn't happen now. I'm not sure what was up with that but I'd like to know in case this occurs again in the future.

**Comment by levlam** [comment]
There is nothing wrong in the log line you have sent.
