### ISSUE TITLE
"Limit reached" error when trying to join a channel or group, even though  joined only ~20.

### ISSUE THREAD

**Issue by king-ma1993** [tdlib/td#3005]
![image](https://github.com/user-attachments/assets/508c152c-2e71-429f-b7a9-5b85c29960e2)

https://www.reddit.com/r/Telegram/comments/1cfwmuo/unexpected_limit_reached_error_when_joining/

"I've encountered a 'Limit reached' issue when trying to join groups or channels, even though I've only joined 10 groups. How can I resolve this problem? I've also experienced the same issue when using third-party clients like Nicegram. Any suggestions on how to fix this?"

**Comment by levlam** [comment]
If the issue happens in all apps, then you can do nothing. Clients can't affect this server-side behavior.

**Comment by king-ma1993** [comment]
> If the issue happens in all apps, then you can do nothing. Clients can't affect this server-side behavior.

"Is this a server-side bug? Would it be possible to report this to the server-side developers for them to fix it?"

**Comment by levlam** [comment]
You can report server-side bugs at https://bugs.telegram.org.

**Comment by king-ma1993** [comment]
> You can report server-side bugs at https://bugs.telegram.org.

https://bugs.telegram.org/c/42032  
https://bugs.telegram.org/c/41830 
https://bugs.telegram.org/c/40151

"I've noticed that many people have reported this issue on the website you mentioned, but it doesn't seem to have been addressed yet. Do you have any estimate on when this problem might be resolved?"
