### ISSUE TITLE
Telegram login

### ISSUE THREAD

**Issue by Dzarma01** [tdlib/td#3006]
Please I can not login to my telegram app
I changed my device from iOS to Android
My phone number is +2347035018841

Uploading screen-20240730-162513.mp4…

**Comment by levlam** [comment]
This isn't related to TDLib.

**Comment by Mohammedobsaa** [comment]
**bank Awash from bole branch**

**Comment by Mohammedobsaa** [comment]
Please send me money

**Comment by Abudl68** [comment]
Did he scam you tell pis
