### ISSUE TITLE
[ 1][t 0][1722393961.183200836][tl_jni_object.cpp:39]	Can't find field [reaction] with signature [Ljava/lang/String;]

### ISSUE THREAD

**Issue by handsomeQPO** [tdlib/td#3007]
when I start with the Java language,an error has occurred,is this because the tdjni.dll file is missing?

**Comment by levlam** [comment]
You have Java code and `tdjni.dll` from different TDLib versions.

**Comment by handsomeQPO** [comment]
i'll give it a try

**Comment by handsomeQPO** [comment]
How can I obtain the latest tdjni.dll file?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/tree/master/example/java.

**Comment by handsomeQPO** [comment]
java.lang.UnsatisfiedLinkError:  libssl.so.1.1 No such file or directory, but there is a libtdjni.so file in my directory,Is my openssl version too low??

**Comment by levlam** [comment]
You need to provide also all dependent libraries if you want to use the shared library on another server.

**Comment by handsomeQPO** [comment]
The dependency package compiled by my Ubuntu operating system machine only has one tdjni.so file

**Comment by levlam** [comment]
You must install the same OpenSSL version on the other machine, or provide relevant OpenSSL libraries along with libtdjni.so.

**Comment by handsomeQPO** [comment]
error: in triplet x64-windows: Unable to find a valid Visual Studio instance,Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat

**Comment by handsomeQPO** [comment]
What's  the reason for this

**Comment by levlam** [comment]
You didn't install Visual Studio, or didn't enable C++ support during installation, or didn't restart shell after installation.

**Comment by handsomeQPO** [comment]
What functions should I send when I receive the CONSTRUCTOR response for OptionValueString?

**Comment by levlam** [comment]
What do you mean?

**Comment by handsomeQPO** [comment]
When i execute new TdApi.SetAuthenticationPhoneNumber(),what steps did TdApi perform.

**Comment by levlam** [comment]
It executes the request with provided parameters.
You may also want to read https://core.telegram.org/tdlib/getting-started.
