### ISSUE TITLE
مساعدة

### ISSUE THREAD

**Issue by Mrogw** [tdlib/td#3008]
مرحبا بدعم تيليجرام 
 أقدم لك شكوى من انتهاك حقوق الطبع والنشر والانتحال  لسوء الحظ، هناك أشخاص يسرقون جهدي وتعبي وينتحلون شخصية اسمي "كالفن"  أطلب منك إيقافهم. لا أريد تقديم شكوى ضدهم في المحكمة. أود حل المشكلة من خلال الدعم الفني برقية  تنتهك هذه القناة مقاطع الفيديو الخاصة بي واسم المستخدم الخاص بي أيضا ولقبي 👇 موقع https://t.me/k727G  موقع https://t.me/K727vbot  
قناتي الرئيسية والشهيرة 👇 موقع https://t.me/k727x

**Comment by Mrogw** [comment]
Hello Telegram Support

I submit to you a complaint of copyright infringement and plagiarism

Unfortunately, there are people who steal my effort and fatigue and are impersonating my name "كالفن"

I ask you to stop them. I do not want to file a complaint against them in court. I would like the issue to be resolved through technical support
Telegram

This channel violates my videos and my username as well and my nickname 👇
https://t.me/k727G
https://t.me/K727vbot


My main and famous channel 👇
https://t.me/k727x

**Comment by levlam** [comment]
This isn't a Telegram Support repository.

**Comment by Mrogw** [comment]
Well, can you help me with this matter?

**Comment by Mrogw** [comment]
I will pay you money if you help me with this matter

Wa.me/966566682304

Contact me on WhatsApp please

**Comment by Mrogw** [comment]
please help me

**Comment by levlam** [comment]
I can't help with this.
