### ISSUE TITLE
when i build example cpp ,i got this : TdConfig.cmake, version: 1.8.34 (32bit)

### ISSUE THREAD

**Issue by karl596** [tdlib/td#3012]
C:\Users\Administrator\td\example\cpp\build (master)
$ cmake -DCMAKE_BUILD_TYPE=Debug -DTd_DIR=C:/Users/Administrator/td/example/cpp/td/lib/cmake/Td ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell

  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a configuration file for package "Td" that is compatible
  with requested version "1.8.34".

  The following configuration files were considered but not accepted:

    C:/Users/Administrator/td/example/cpp/td/lib/cmake/Td/TdConfig.cmake, version: 1.8.34 (32bit)

-- Configuring incomplete, errors occurred!

Actually, i have build all the need in example project
![image](https://github.com/user-attachments/assets/dc862c28-f47a-4a87-8054-eafa71a2d569)

![image](https://github.com/user-attachments/assets/6cad6990-e410-4713-b9e2-eccd99d99046)

**Comment by levlam** [comment]
The error "The following configuration files were considered but not accepted:" means that you build TDLib for x86, but trying to build the example for x64/ARM64. You need to specify the same `-A` parameter to cmake as was specified during TDLib building.

**Comment by karl596** [comment]
> The error "The following configuration files were considered but not accepted:" means that you build TDLib for x86, but trying to build the example for x64/ARM64. You need to specify the same `-A` parameter to cmake as was specified during TDLib building.

Thank you very much, it is working now, thank you.😄
