### ISSUE TITLE
Can't build android tdlib

### ISSUE THREAD

**Issue by ranjitsingha** [tdlib/td#3016]
I am getting this error while running the command  ./fetch-sdk.sh

Downloading SDK Manager...
Installing required SDK tools...
yes: standard output: Broken pipe

**Comment by levlam** [comment]
Do you use `Windows` and `mintty/Bash`?

**Comment by ranjitsingha** [comment]
> Do you use `Windows` and `mintty/Bash`?

i am able to build the sdk using ./fetch-sdk.sh
but while ./build-openssl.sh
i get error

**Comment by levlam** [comment]
What error?
Did you run ./check-environment.sh first?

**Comment by ranjitsingha** [comment]
> What error? Did you run ./check-environment.sh first?
![Uploading Screenshot_20240810-124544_1.jpg…]()

**Comment by ranjitsingha** [comment]
> What error? Did you run ./check-environment.sh first?

![Screenshot_20240810-124544_1](https://github.com/user-attachments/assets/b67eac07-4bf6-415c-87d1-802f89327353)

**Comment by levlam** [comment]
There are no errors on the screenshots.

**Comment by ranjitsingha** [comment]
> There are no errors on the screenshots.

Can you check my workflow. it keeps on running on loop while installing openssl

https://github.com/ranjitsingha/lib/actions/runs/10330093189

**Comment by ranjitsingha** [comment]
> There are no errors on the screenshots.

Oh ya sorry i mistook. it was my fault. I am sorry.
Its working fine now :)
And thank you very much
