### ISSUE TITLE
TdApi.getRemoteFile return size = 0 for existing file

### ISSUE THREAD

**Issue by cdxf** [tdlib/td#3019]
For some file, when using getRemoteFile API , I receive FileInfo with size = 0; What is the problem?

>   id = 3
>   size = 0
>   expectedSize = 0
>   local = LocalFile {
>     path = ""
>     canBeDownloaded = true
>     canBeDeleted = false
>     isDownloadingActive = false
>     isDownloadingCompleted = false
>     downloadOffset = 0
>     downloadedPrefixSize = 0
>     downloadedSize = 0
>   }
>   remote = RemoteFile {
>     id = "BQACAgUAAxkDAAK5EWZGrWwD7cWp3ff5TWpt8vydYeJuAAK_LwACCFYxVn-37MaaYuJ3NQQ"
>     uniqueId = "AgADvy8AAghWMVY"
>     isUploadingActive = false
>     isUploadingCompleted = true
>     uploadedSize = 0
>   }
> }

**Comment by cdxf** [comment]
...

**Comment by levlam** [comment]
This is expected behavior:
> `//@size File size, in bytes; 0 if unknown`
