### ISSUE TITLE
Usage of @object

### ISSUE THREAD

**Issue by Quasarsbq** [tdlib/td#302]
How can I use specific part of @object comes from DefaultHandler?
for example I just need id part of a message but @object contains every details of a client result.

**Comment by levlam** [comment]
`@object` is just an object of some class. You can use dynamic cast to cast it to desired type and access its fields.

**Comment by Quasarsbq** [comment]
Tnx but I'm kinda new on these tdlib and c# things. Could you write an example if u don mind...?

**Comment by Quasarsbq** [comment]
tnx
