### ISSUE TITLE
 "searchUserByPhoneNumber" Method Returns 404 on Production Server

### ISSUE THREAD

**Issue by MasoodGharahi** [tdlib/td#3023]
I'm using TDLib in a .NET application. On my local machine, the searchUserByPhoneNumber method works as expected and successfully finds the user. However, when deployed to the production server, the same method returns a 404 error.

Has anyone encountered this issue? Does the Telegram API have any rate limits or restrictions that might cause this behavior?

**Comment by levlam** [comment]
This is intended behavior. Server may not return the user if it isn't in your contact list.

**Comment by MasoodGharahi** [comment]
@levlam Thanks. you mean it may vary from devices or phone numbers? because as I said it works and returns data on my local machine..

**Comment by levlam** [comment]
It definitely can.
