### ISSUE TITLE
How to disable saving files to disk? (use_file_database=false don't help)

### ISSUE THREAD

**Issue by a1ex33** [tdlib/td#3025]
We recently updated our tdlib from version 1.8.4 to 1.8.31.
After this, session files (photos, videos, voices, etc.) began to be saved on the disk.
We pass the setTdlibParameters command with the following params:
```
setTdlibParameters {
  use_test_dc = false
  database_directory = "/some_directory"
  files_directory = ""
  database_encryption_key = bytes [0] { }
  use_file_database = false
  use_chat_info_database = false
  use_message_database = false
  use_secret_chats = false
  api_id = 111
  api_hash = "our_hash"
  system_language_code = "en"
  device_model = "Compute Cloud"
  system_version = ""
  application_version = "1.0"
}
```
With these params on v1.8.4 everything worked fine.
But after the update, files started saving to disk.
What could be the reason?

**Comment by levlam** [comment]
There were no changes in TDLib behavior. Files are never downloaded automatically by TDLib, they can only be downloaded by your app. Some photos can always have their smallest size, which is received along with the photo and saved on the disk. These photos can be ignored by settings the option "ignore_inline_thumbnails" (see https://core.telegram.org/tdlib/options for details).

**Comment by a1ex33** [comment]
Thanks for the reply. After that I double checked our code and noticed that we use `DownloadFile` method in some cases, which downloads files.
We added a periodic launch of `optimizeStorage` to clean up data.
