### ISSUE TITLE
Creating an instance of inputFile

### ISSUE THREAD

**Issue by jonnjonnjo** [tdlib/td#3027]
I'm using java springboot and use [multiPartFile](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/multipart/MultipartFile.html) for handling the files. I want to create an instance of inputFile, but figured out that there's no function or method that could create an instance of inputFile given a multipartFile. There's also no subclasses that could handle that. what should i do? should i just create the instance of my file into a local directory, take the directory address, and create an instance of inputFileLocal using that path?

**Comment by levlam** [comment]
[multiPartFile](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/multipart/MultipartFile.html) documentation says "In either case, the user is responsible for copying file contents to a session-level or persistent store as and if desired. The temporary storage will be cleared at the end of request processing." Hence, the simplest way is to save the file locally and then use `inputFilleLocal` as you said.

**Comment by jonnjonnjo** [comment]
okay thanks !
