### ISSUE TITLE
FATAL ERROR in native method

### ISSUE THREAD

**Issue by MrKangZuBin** [tdlib/td#3036]
[ 1][t 0][1724935265.820765257][tl_jni_object.cpp:37]	Can't find class [org/drinkless/tdlib/Log]
FATAL ERROR in native method: Can't find class [org/drinkless/tdlib/Log]

**Comment by levlam** [comment]
You use incompatilble libtdjni.so and Java wrapper classes. You must use Java classes and libtdjni.so from exactly the same TDLib version.

**Comment by MrKangZuBin** [comment]
I didn’t see libtdjni.so after I built it.

**Comment by levlam** [comment]
Did you build it as specified at https://tdlib.github.io/td/build.html?language=Java?

**Comment by MrKangZuBin** [comment]
https://tdlib.github.io/td/build.html?language=Java I followed this method. Now I put the libs in the jdk bin and it works, but other errors occur. A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9c4a42f58, pid=19072, tid=21256
#
# JRE version: Java(TM) SE Runtime Environment (17.0.11+7) (build 17.0.11+7-LTS-207)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.11+7-LTS-207, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [msvcp140.dll+0x12f58]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#  
According to the error message, I reinstalled Microsoft Visual C++ Redistributable and restarted the computer, but the error still occurred

**Comment by MrKangZuBin** [comment]
[hs_err_pid9696.log](https://github.com/user-attachments/files/16812665/hs_err_pid9696.log)
this is  log

**Comment by MrKangZuBin** [comment]
Example is  git clone的

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/2912#issuecomment-2156135946 and the answer above.
