### ISSUE TITLE
 IMPORTED_LOCATION not set for imported target "Td::tdclient"

### ISSUE THREAD

**Issue by Igwanya** [tdlib/td#3037]
Hello offer a solution to this problem that i have. Also explain the reason why TdLib is not on the vcpkg 
repository. Thanks

[td_build_cmake_error.txt](https://github.com/user-attachments/files/16817275/td_build_cmake_error.txt)

**Comment by levlam** [comment]
The errors means that you didn't install TDLib for the mentioned configurations, but trying to use it.

TDLib is suppposed to be embedded into a corresponding Telegram app and not used as a standalone system-wide library.

**Comment by Igwanya** [comment]
OK. Retried changing the CMAKE_INSTALL_PREFIX var to no success. I thought i missed a sted in the build instruction for cmake c++ projects but i did not. How do i successfuly install the lib system wide, the telegram app is installed?

**Comment by levlam** [comment]
Usually, you install only Release library version system-wide. There is no easy way to use multiple versions of the same library simultaneously. Likely, you can add -DCMAKE_DEBUG_POSTFIX=d to CMake configuration options and install both Debug and Release libraries to the same directory after that.
