### ISSUE TITLE
getChatHistory()

### ISSUE THREAD

**Issue by cherryymerryy** [tdlib/td#3038]
How can I get the full chat history? I tried to change limit and offset but it didn't change anything and I keep getting +-10 messages.

**Comment by Lawrenzo1989** [comment]
Please be patient with me, I am working on it that you

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-chat-messages.

**Comment by cherryymerryy** [comment]
it didn't solve my problem in any way.

**Comment by levlam** [comment]
I can only suggest reading documentation of the method `getChatHistory` again and reading the additional information from the link.
