### ISSUE TITLE
Some phone numbers do not search for the user by phone number

### ISSUE THREAD

**Issue by DenysSamoiliuk** [tdlib/td#3045]
I have a certain set of phone numbers that are activated in Telegram at different intervals (a week, a month, a year, three months, etc.) in my service there is a way to search for a user by phone number in order to get his identifier for sending a message, but I am facing with the following problem that some numbers cannot find the user even if his number is public, tdlib responds that there is no such user, but there are numbers that find users regardless of their privacy, do you know what the reason could be and how to avoid such cases

ps even if I add a user by number to contacts, I get an error that such a user does not exist

**Comment by levlam** [comment]
This is intended behavior. Server may not return the user and prevent abuse of the API.

**Comment by DenysSamoiliuk** [comment]
> This is intended behavior. Server may not return the user and prevent abuse of the API.

tell me, do you know where you can find out about such names, such as a phone number, since the number has been in Telegram for 3 weeks, but we have not used it for 2 weeks, but the search is still not available, and we regularly search for another user everything is fine for sending information, but searching by username does not present any problems, however, I would like to understand these limitations more transparently

**Comment by DenysSamoiliuk** [comment]
@levlam  i get the following in these methods

https://core.telegram.org/method/contacts.resolvePhone

RPCError: 400: PHONE_NOT_OCCUPIED (caused by contacts.ResolvePhone)
    at RPCMessageToError (/home/hrederik/WebstormProjects/novait/telegram-web-api/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/home/hrederik/WebstormProjects/novait/telegram-web-api/node_modules/telegram/network/MTProtoSender.js:546:58)
    at MTProtoSender._processMessage (/home/hrederik/WebstormProjects/novait/telegram-web-api/node_modules/telegram/network/MTProtoSender.js:476:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MTProtoSender._recvLoop (/home/hrederik/WebstormProjects/novait/telegram-web-api/node_modules/telegram/network/MTProtoSender.js:424:17) {
  code: 400,
  errorMessage: 'PHONE_NOT_OCCUPIED'
}

https://core.telegram.org/method/contacts.importContacts

res {
  CONSTRUCTOR_ID: xxxx,
  SUBCLASS_OF_ID: xxxx,
  className: 'contacts.ImportedContacts',
  classType: 'constructor',
  imported: [],
  popularInvites: [],
  retryContacts: [ Integer { value: 2570974896n } ],
  users: []
}

could you share in more detail the data about the restrictions and if you have any information on how to get rid of them from the number

**Comment by levlam** [comment]
Both search by phone number and by user name are highly limited. It is not possible to harvest Telegram users using these methods.

**Comment by DenysSamoiliuk** [comment]
@levlam 
for example, I found a user from another number whose phone number is private (only for contacts), and I am not his friend and have no previous conversations, that is, he is completely anonymous for me with privacy settings

![photo_2024-09-09_17-45-29](https://github.com/user-attachments/assets/dced8317-dc59-4031-adac-202faca4f289)

user {
  CONSTRUCTOR_ID: xxxx,
  SUBCLASS_OF_ID: xxxxx,
  className: 'contacts.ResolvedPeer',
  classType: 'constructor',
  peer: {
    CONSTRUCTOR_ID: xxxx,
    SUBCLASS_OF_ID: xxxxx,
    className: 'PeerUser',
    classType: 'constructor',
    userId: Integer { value: xxxxx}
  },
  chats: [],
  users: [
    {
      CONSTRUCTOR_ID: xxxx,
      SUBCLASS_OF_ID: xxxx,
      className: 'User',
      classType: 'constructor',
      flags: xxxx,
      self: false,
      contact: false,
      mutualContact: false,
      deleted: false,
      bot: false,
      botChatHistory: false,
      botNochats: false,
      verified: false,
      restricted: false,
      min: false,
      botInlineGeo: false,
      support: false,
      scam: false,
      applyMinPhoto: true,
      fake: false,
      botAttachMenu: false,
      premium: false,
      attachMenuEnabled: false,
      flags2: 16,
      botCanEdit: false,
      closeFriend: false,
      storiesHidden: false,
      storiesUnavailable: true,
      contactRequirePremium: false,
      id: [Integer],
      accessHash: [Integer],
      firstName: 'Vladyslav',
      lastName: null,
      username: 'pc_Vl_6',
      phone: null,
      photo: null,
      status: [Object],
      botInfoVersion: null,
      restrictionReason: null,
      botInlinePlaceholder: null,
      langCode: null,
      emojiStatus: null,
      usernames: null,
      storiesMaxId: null,
      color: null,
      profileColor: null
    }
  ]
}

**Comment by levlam** [comment]
Everything works as intended.

**Comment by DenysSamoiliuk** [comment]
@levlam thx
