### ISSUE TITLE
Temporary authentication

### ISSUE THREAD

**Issue by mrstecklo** [tdlib/td#3053]
Hello,

Telegram API provides ways to share authentication between devices. E.g. with one-time code sent to an authenticated device.
Or in a more explicit way with auth.exportLoginToken (or td_api::requestQrCodeAuthentication).
But all those ways share persistent authentication.

Is there any way to share some temporary session token? Or is there a way not to store persistent auth info with tdlib?

**Comment by levlam** [comment]
No, there are no temporary authentication on Telegram.
