### ISSUE TITLE
Supported video formats

### ISSUE THREAD

**Issue by abitrolly** [tdlib/td#3054]
It would be nice to document what is supported. `.webm` with VP8 apparently doesn't play.

**Comment by levlam** [comment]
The only video format that is guaranteed to work is .MPEG4 with H.264 video codec and AAC audio codec. Some other video formats or codecs may work but this isn't guaranteed. This is documented for bots at https://core.telegram.org/bots/api#sendvideo. Regular apps are supposed to reencode videos using system-provided tools to .MPEG4, or can't affect video format, hence this doesn't usually matter for them.

**Comment by abitrolly** [comment]
@levlam it would be nice to support at least one open source codec in addition to proprietary H.264, because some platforms disallow binary blobs that can not be audited.

**Comment by manishwalia15** [comment]
You shud M use P4 (H.264/AAC):
Browser Support: Universally supported across all major browsers (Chrome, Firefox, Safari, Edge, etc.).

**Comment by abitrolly** [comment]
@manishwalia15 browsers may support, but company or regulator policy may not, especially those who take security seriously.
