### ISSUE TITLE
[Question] How to organize a search among chat/group/etc name

### ISSUE THREAD

**Issue by tilvin** [tdlib/td#3055]
Hello, i ask for advice or a second opinion about my problem.
At my app i have a search field where user types a chat name (or it's part) and the app is supposed to provide a list of found results.
So i take a string which user typed and I trigger `searchPublicChats` and `searchChatsOnServer`. So i getting array of chat ids.
Then i take each chat id and trigger `getChat` , so i receive chat Title and some other info.

Then i want to add chat logo to each chat instance and represent it along with title.
It seems i need to perform an additional request to download an icon to each chat instance.
There's a `Minithumbnail`, but it's really too small.

While it's processing the user is waiting for search result.

Is there any better solution for search? 

Thanks!

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/2616#issuecomment-1735201401 for the methods that are invoked by apps to get results of global search.

Also, you never need to call `getChat`, because chats should be cached as described at https://core.telegram.org/tdlib/getting-started.

**Comment by tilvin** [comment]
Thanks @levlam i'm receiving `updateNewChat` event with chat info.
Any life hacks to get a logo? Or for logo i really should send a request and download a file?
Thanks!
