### ISSUE TITLE
APP_PUSH_APIKEY_MISSING when trying to register device for Huawei Push

### ISSUE THREAD

**Issue by xymeng16** [tdlib/td#3057]
When I set the token type as 13, which means Huawei Push, and attach the token getting from the push kit of my Huawei device, it responds APP_PUSH_APIKEY_MISSING to me.

I refer to #1948 which said that I need to add my credential on my.telegram.org, but I can only find the entry for adding FCM
credential.

Thanks for the help in advance.

**Comment by levlam** [comment]
It is not possible to upload certificate for sending Huawei push notifications now, but this can be supported in the future at my.telegram.org.

**Comment by xymeng16** [comment]
Thanks for your clarification and efforts maintaining Telegram. I hope it would be supported soon as I am developing a Telegram client for Huawei's HarmonyOS Next operating system. It would be wondeful if the push notificaiton is able to be integrated into it semalessly.

**Comment by qianbi321** [comment]
Hope to support Huawei HMS push notifications

**Comment by levlam** [comment]
@Emulond Yes, Huawei Push Service is supported server-side, but my.telegram.org still does not have interface to upload the certificate for its usage by third-party apps.
