### ISSUE TITLE
how to use IntelliJ for java example

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#306]
I finally can build java example. it's cool but how can use IntelliJ to programming and build a project.
I want to use JavaFX and maven in IntelliJ to build a desktop application, can anyone help me?

**Comment by mincong-h** [comment]
I use IntelliJ to develop Java solution. Once you've built the Java example, you can copy all the Java files `*.java` into Maven source directory `src/main/java`. Don't forget the generated one — `org.drinkless.tdlib.TdApi.java`. Once you've copied everything, the structure looks like:

```
$ tree src/main/java/
src/main/java/
├── yourpackage
│   ├── A.java
│   ├── B.java
│   └── C.java
└── org
    └── drinkless
        └── tdlib
            ├── Client.java
            ├── Log.java
            ├── TdApi.java
            └── example
                └── Example.java
```

You can now develop your own solution as a usual Maven project. However, there's a tricky point for execution. You must include the Telegram Database library (JNI) to run your final JAR:

    $ java -Djava.library.path=/path/to/tdlib -jar /path/to/jar

**Comment by sadeghpro** [comment]
tnx @mincong-h,  I don't look to org.drinkless.tdlib folder after the build Java.
it looks like fine but I have two another problem

1. how to run the project from IntelliJ? I add `java.library.path=/Users/peter/Downloads/td/` to VM options of Run/Debug Configurations bug get this error
```Error: Could not find or load main class java.library.path=.Users.peter.Downloads.td.```
2. I use [this](https://github.com/javafx-maven-plugin/javafx-maven-plugin) library for java packager.
how to add tdlib to it or another library for java packager? JavaFX-maven-plugin can add VM option my question is how to add tdlib to it for all windows

**Comment by mincong-h** [comment]
> `-Djava.library.path=/Users/peter/Downloads/td/`

This path is incorrect. The shared library is stored in `/Users/peter/Downloads/td/example/java/bin`, which is relevant with the documentation:

> Now you can run Java example:
> ```
> cd <path to TDLib sources>/example/java/bin
> java '-Djava.library.path=.' org/drinkless/tdlib/example/Example
> ```

**Comment by sadeghpro** [comment]
tnx @mincong-h,  I run this project on IntelliJ with VM options of Run/Debug configurations.
and in maven, I think maybe need other option to set for compile code but this is not and it's like other projects
