### ISSUE TITLE
Can't find native field (jni)

### ISSUE THREAD

**Issue by eumel19900** [tdlib/td#3060]
Hi,

I have a problem getting tdlib with java running on my raspi 5 (arm 64 bit 8 gb ram).
I am developing an java server app using tdlib with jni bindings which worked fine with windows 11 running the app server from my IDE.

I have build linux binaries for my raspi using the official build instructions.

Deploying my server app on my raspi I am getting the following error during logging into telegram:
`2024-09-22T17:10:32.102+02:00  INFO 21964 --- [   TDLib thread] d.r.g.telegramclient.UpdateHandler       : Submitting TdlibParameters
FATAL ERROR in native method: Can't find field [author] with signature [Ljava/lang/String;]
        at org.drinkless.tdlib.Client.nativeClientReceive(Native Method)
        at org.drinkless.tdlib.Client$ResponseReceiver.run(Client.java:170)
        at java.lang.Thread.runWith(java.base@22.0.2/Thread.java:1583)
        at java.lang.Thread.run(java.base@22.0.2/Thread.java:1570)
`

Has anyone seen this before? What am I doing wrong?

Any help would be appreciated.
Thanks in advance.

Greetings
Robert

**Comment by levlam** [comment]
The error means that you have TdApi.java and tdjni.dll from different TDLib versions.

**Comment by HoneyLoves323** [comment]
well please contact me with your telegram lik and I have taken your order
0914191171

**Comment by eumel19900** [comment]
Your right, thanks.

I tought about that and did a rebuild but nothing changed... Now I rebuilt in a clean directory with a fresh checkout, which fixed the issue.

Thanks.
Greetings
Robert
