### ISSUE TITLE
There was an error running tdjson. example. py!

### ISSUE THREAD

**Issue by hhxdestiny** [tdlib/td#3065]
[os]: win11 x64
[python]: 3.12.4
[cmd]: python tdjson. example. py
[commit]: 91aa6c9e4d0774eabf4f8d7f3aa51239032059a6
[console] :
```bash
Traceback (most recent call last):
  File "D:\works\td\example\python\tdjson_example.py", line 63, in <module>
    print(str(td_execute({'@type': 'setLogVerbosityLevel', 'new_verbosity_level': 1, '@extra': 1.01234})).encode('utf-8'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\works\td\example\python\tdjson_example.py", line 55, in td_execute
    result = _td_execute(query)
             ^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000000
```

**Comment by levlam** [comment]
Everything works correctly for me with Python 3.11.9 and I doubt that something was changed with `ctypes` in 3.12.

Could you run the command `dir -l .` from the directory `D:\works\td\example\python` and send its output?

**Comment by hhxdestiny** [comment]
> Everything works correctly for me with Python 3.11.9 and I doubt that something was changed with `ctypes` in 3.12.
> 
> Could you run the command `dir -l .` from the directory `D:\works\td\example\python` and send its output?

Everything works correctly for me with Python 3.11, thanks!
