### ISSUE TITLE
The following paths were examined for Visual Studio instances: 

### ISSUE THREAD

**Issue by romaoatm** [tdlib/td#3068]
PS D:\td\vcpkg> ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
Computing installation plan...
The following packages will be built and installed:
    gperf:x64-windows -> 3.1#6
    openssl:x64-windows -> 3.1.4#1
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
    zlib:x64-windows -> 1.3
Additional packages (*) will be modified to complete this operation.
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat
  
  
![image](https://github.com/user-attachments/assets/d4b85485-7333-4db6-ac39-1b06e29106eb)

**Comment by levlam** [comment]
Check that you install Visual Studio with C++ support.

**Comment by romaoatm** [comment]
> Check that you install Visual Studio with C++ support.

The thing is that I have it installed with C++

**Comment by levlam** [comment]
What is the size of the file "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat"?

**Comment by romaoatm** [comment]
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\

![image](https://github.com/user-attachments/assets/b53dd571-8a7a-4ce4-a520-4648ecafccdb)

**Comment by G4v412345** [comment]
I faced the same problem, have you found a solution yet?
if I find it sooner I will share it with you

**Comment by levlam** [comment]
The content of the directory is as expected.
This is a `vcpkg` issue, which is very likely to be caused by an incomplete MSVC installation.
Check that the following components were selected during MSVC installation:
    - Windows Universal C Runtime
    - C++ core features
    - Visual Studio Build tools:
      * MSVC v143 - VS 2022 C++ x64/x86 build tools
    - MSBuild
    - Windows SDK
    - English language Pack

The last item in the list is the most common source of `vcpkg` fails, so I would check for it first.

**Comment by romaoatm** [comment]
> The content of the directory is as expected. This is a `vcpkg` issue, which is very likely to be caused by an incomplete MSVC installation. Check that the following components were selected during MSVC installation: - Windows Universal C Runtime - C++ core features - Visual Studio Build tools: * MSVC v143 - VS 2022 C++ x64/x86 build tools - MSBuild - Windows SDK - English language Pack
> 
> The last item in the list is the most common source of `vcpkg` fails, so I would check for it first.

I'll try now

**Comment by romaoatm** [comment]
> I faced the same problem, have you found a solution yet?
> if I find it sooner I will share it with you

try what the person above wrote

**Comment by Gava12345** [comment]
I installed everything again, only putting in the components mentioned above. The problem, for me personally, was not resolved

**Comment by Gava12345** [comment]
Personally, I encounter this kind of problem after using the command: `git checkout cd5e746ec203c8c3c61647e0886a8df8c1e78e41`, but skipping it, the subsequent build still does not succeed

**Comment by romaoatm** [comment]
> The content of the directory is as expected. This is a `vcpkg` issue, which is very likely to be caused by an incomplete MSVC installation. Check that the following components were selected during MSVC installation: - Windows Universal C Runtime - C++ core features - Visual Studio Build tools: * MSVC v143 - VS 2022 C++ x64/x86 build tools - MSBuild - Windows SDK - English language Pack
> 
> The last item in the list is the most common source of `vcpkg` fails, so I would check for it first.

![image](https://github.com/user-attachments/assets/430a31d4-9f18-425a-8fad-5a8e58efe6c5)
![image](https://github.com/user-attachments/assets/1837fc44-142a-459b-8055-fa65eb3d502c)
![image](https://github.com/user-attachments/assets/5f3cd7fa-dd0a-4aa0-94f0-4aeb861a57f9)
![image](https://github.com/user-attachments/assets/dd1d8ecc-d628-47f2-ac69-0133d6e87403)

**Comment by romaoatm** [comment]
> The content of the directory is as expected. This is a `vcpkg` issue, which is very likely to be caused by an incomplete MSVC installation. Check that the following components were selected during MSVC installation: - Windows Universal C Runtime - C++ core features - Visual Studio Build tools: * MSVC v143 - VS 2022 C++ x64/x86 build tools - MSBuild - Windows SDK - English language Pack
> 
> The last item in the list is the most common source of `vcpkg` fails, so I would check for it first.

we can contact you via telegram

**Comment by levlam** [comment]
@romaoatm 
Could you also install build tools for MSVC versions 142, 141 and 140?

**Comment by Gava12345** [comment]
I found the solution. Just skip the step `git checkout cd5e746ec203c8c3c61647e0886a8df8c1e78e41`, and everything will be fine. The only other issue that might occur is a manifest error during the `cmake --build . --target install --config Release` stage. I’m not sure how I resolved it; maybe the components mentioned by the person above helped.

**Comment by romaoatm** [comment]
> I found the solution. Just skip the step `git checkout cd5e746ec203c8c3c61647e0886a8df8c1e78e41`, and everything will be fine

Thank you very much, I couldn't install TDLib for a whole week

**Comment by Gava12345** [comment]
> > I found the solution. Just skip the step `git checkout cd5e746ec203c8c3c61647e0886a8df8c1e78e41`, and everything will be fine
> 
> Thank you very much, I couldn't install TDLib for a whole week

Please)
