### ISSUE TITLE
Does this project use api_id and api_hash of telegram api

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#307]
Hi everyone,
I use java example of this project and it works fine. I can log in, see chat list and other thing but my question is does this project use `api_id` and `api_hash` or not? if yes I don't set it why project run and I can log in to my account?

**Comment by levlam** [comment]
You need to specify valid api_id and api_hash in the first request setTdlibParameters. Our examples has hard-coded api_id and api_hash, which aren't suitable for any production use.
