### ISSUE TITLE
TDLib JNI - won't get message reactions in linux/Mac Build

### ISSUE THREAD

**Issue by eumel19900** [tdlib/td#3071]
Hi,

I wrote my software for Windows where I get message reactions on messages in the `message.interactionInfo.reactions` field.
Now I am porting to Linux and Mac and this field is always null:
![image](https://github.com/user-attachments/assets/2f3c587e-e2e9-4a0b-8f88-045bbf2b770d)

The documentation says this field may be null, but it doesn't say how to get the reactions: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_interaction_info.html

I built all TDLib binaries myself for all platforms using the official html build instructions generator.
Mac and Linux is ARM, Windows is x64.

How do I get the message reactions? :-)

Any help would be appreciated.

Greetings
Robert

**Comment by levlam** [comment]
There is no way to get message reactions in TDLib. They are fetched whenever appropriate internally by TDLib for regular users. Bots receive updates whenever reactions change.

**Comment by eumel19900** [comment]
Are you shure? It works in Windows (I took this screenshot right now in Windows):
![image](https://github.com/user-attachments/assets/40dc4a2b-9a2d-4555-ab4a-05620df20d65)

I am writing a tool for filtering group messages based on user feedback.
What options do I have for achieving this?

Any help would be appreciated.
Greetings
Robert

**Comment by levlam** [comment]
> I am writing a tool for filtering group messages based on user feedback.
What options do I have for achieving this?

You should use a regular bot for this and listen for "message_reaction" updates.

**Comment by eumel19900** [comment]
Ok, thx. I will find a solution.
