### ISSUE TITLE
how to imitate method messages.getDialogs using tdlib?

### ISSUE THREAD

**Issue by n1ppl3** [tdlib/td#3072]
Hi, I'm new to **tdlib** and wondering how to get the same result as using method [messages.getDialogs](https://core.telegram.org/method/messages.getDialogs)

I'm interested in online user information especialy actual online status [UserStatus](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_user_status.html)
I tried [getChats](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html) + [getChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat.html) but I get stale information...

Thanks!

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started for the way to fetch chat list.

You can't fetch a user's status from the server using TDLib. It is updated whenever appropriate.

**Comment by n1ppl3** [comment]
I got desired data by listening to UpdateUserStatus event, thanks for hint!
```
    clientBuilder.addUpdateHandler(TdApi.UpdateUserStatus.class, this::onUpdateNewMessage);
    // 
    private void onUpdateNewMessage(TdApi.UpdateUserStatus update) {
        logger.info("{}: {}", update.userId, update.status);
    }
```
(I'm using tdlight-java version 3.3.1+td.1.8.25)
