### ISSUE TITLE
Timeout from downloadFile 

### ISSUE THREAD

**Issue by yuminekosan** [tdlib/td#3073]
Hello again. I am implementing receiving messages via updates. I need to download message attachments, but periodically I get a timeout, after which I cannot receive new updates. Tell me how to solve this problem.

**Comment by levlam** [comment]
This is a problem in your code. TDLib requests has no timeouts.

**Comment by yuminekosan** [comment]
Can telegram itself return timeouts to requests?

**Comment by levlam** [comment]
This can't affect `downloadFile`.
