### ISSUE TITLE
how to change tdlib directory name?

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#308]
Hi,
I use java example of this project. when I run the project it creates a directory named tdlib.
is there any way to change this file name?
there is a `db.sqlite` file in tdlib directory when I want open it wants a password. what is db.sqlite password? how to change password of it to my own password?

the last thing I want to know is how to login with multiple account for example I set tdlib directory name to phone number of user and allow user to login with multiple number

**Comment by levlam** [comment]
1. Name of the directory is set in the source code along with other parameters:
```
                parameters.databaseDirectory = "tdlib";
```
2. Database password is managed by TDLib. You can't change it and you shouldn't access the database directly.
3. You can create as much TDLib instances as you want and provide them with different database directories.
