### ISSUE TITLE
[Question] How can I get Telegram settings?

### ISSUE THREAD

**Issue by cherryymerryy** [tdlib/td#3086]
How can I get or change various parameters inside Telegram? (For example, notifications or privacy and security

**Comment by levlam** [comment]
There are separate methods for each setting. Notifications are changed using `setChatNotificationSettings`, `setScopeNotificationSettings`, `setForumTopicNotificationSettings` and other relevant methods.
Privacy settings can be changed using `setUserPrivacySettingRules`, `setReadDatePrivacySettings` and other relevant methods.

I suggest to overview https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl once to familiarize with the existing methods.

**Comment by Scutua** [comment]
I think they have too many more peoples. I start tried already mornings until mornings. I n full month already. 🙃
