### ISSUE TITLE
Java client native code crash 

### ISSUE THREAD

**Issue by Rajkumar1994sof** [tdlib/td#3088]
1:8200/intake/v2/events, response code is 503
FATAL ERROR in native method: Can't find field [author] with signature [Ljava/lang/String;]
	at org.drinkless.tdlib.Client.nativeClientReceive(Native Method)
	at org.drinkless.tdlib.Client$ResponseReceiver.run(Client.java:170)
	at java.lang.Thread.run(java.base@17.0.12/Thread.java:840)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007feef8bdb941, pid=1, tid=59
#
# JRE version: OpenJDK Runtime Environment (17.0.12+7) (build 17.0.12+7-Ubuntu-1ubuntu220.04)
# Java VM: OpenJDK 64-Bit Server VM (17.0.12+7-Ubuntu-1ubuntu220.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x22941]  abort+0x213
#
# Core dump will be written. Default location: /core.%e.1.%t
#
# An error report file with more information is saved as:
# /app/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-17

**Comment by Rajkumar1994sof** [comment]
Current thread (0x00007f63f427ea00):  JavaThread "TDLib thread" daemon [_thread_in_vm, id=97, stack(0x00007f637857d000,0x00007f637867e000)]

Stack: [0x00007f637857d000,0x00007f637867e000],  sp=0x00007f637867c3c0,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x22941]  abort+0x213
V  [libjvm.so+0x8c26a8]  jni_FatalError+0xc8
C  [libtdjni.so+0x23b8439]  td::jni::fatal_error(JNIEnv_*, td::CSlice)+0x99
C  [libtdjni.so+0x23b8a86]  td::jni::get_field_id(JNIEnv_*, _jclass*, char const*, char const*)+0x166
C  [libtdjni.so+0x21eedb8]  td::td_api::linkPreviewTypePhoto::init_jni_vars(JNIEnv_*)+0x188
C  [libtdjni.so+0x2240683]  td::td_api::linkPreviewTypePhoto::store(JNIEnv_*, _jobject*&) const+0x33
C  [libtdjni.so+0x2273e75]  td::td_api::linkPreview::store(JNIEnv_*, _jobject*&) const+0x1c5
C  [libtdjni.so+0x2274054]  td::td_api::messageText::store(JNIEnv_*, _jobject*&) const+0xb4
C  [libtdjni.so+0x2286194]  td::td_api::message::store(JNIEnv_*, _jobject*&) const+0x6a4
C  [libtdjni.so+0x228bb5a]  td::td_api::updateChatLastMessage::store(JNIEnv_*, _jobject*&) const+0x8a

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.drinkless.tdlib.Client.nativeClientReceive([I[J[Lorg/drinkless/tdlib/TdApi$Object;D)I+0
J 13878% c1 org.drinkless.tdlib.Client$ResponseReceiver.run()V (64 bytes) @ 0x00007f63de476fbc [0x00007f63de476f20+0x000000000000009c]
j  java.lang.Thread.run()V+11 java.base@17.0.12
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

**Comment by levlam** [comment]
The error means that you use libtdjni.so and TdApi.java from different TDLib versions. You must update them simultaneously.

**Comment by Rajkumar1994sof** [comment]
what is the procedure to create libtdjni.so and location of libtdjni.so ?

**Comment by levlam** [comment]
https://tdlib.github.io/td/build.html?language=Java
