### ISSUE TITLE
Last commit "Add class StarGift"  broken build

### ISSUE THREAD

**Issue by s30139** [tdlib/td#3089]
Last commit "Add class StarGift"  broken docker image build
forgot a comma in SplitSource.php file

`Write file td/telegram/td_api.hpp
[100%] Built target tl_generate_common
[100%] Built target prepare_cross_compiling
PHP Parse error:  syntax error, unexpected single-quoted string "star_gift_manager[_(-](?![.]ge...", expecting ")" in /src/SplitSource.php on line 417
The command '/bin/sh -c apk update &&     apk upgrade &&     apk add --update         build-base         ca-certificates         ccache         cmake         git         gperf         linux-headers         openssl-dev         php         php-ctype         readline-dev         zlib-dev &&     git clone "https://github.com/tdlib/td.git" /src &&     cd /src &&     git checkout ${TD_COMMIT} &&     mkdir ./build &&     cd ./build &&     cmake         -DCMAKE_BUILD_TYPE=Release         -DCMAKE_INSTALL_PREFIX:PATH=/usr/local         .. &&     cmake --build . --target prepare_cross_compiling &&     cd .. &&     php SplitSource.php &&     cd build &&     cmake --build . --target install &&     ls -lah /usr/local' returned a non-zero code: 255
`

**Comment by levlam** [comment]
Thank you. Fixed in master.
