### ISSUE TITLE
asynchronous Client receive Feature request

### ISSUE THREAD

**Issue by pabx06** [tdlib/td#309]
Hello is there a way to have asynchronous client receive 👍 
https://core.telegram.org/tdlib/docs/classtd_1_1_client.html#a95ed6da3afd8b605b3bf94f1f8915aff

**Comment by levlam** [comment]
What exactly do you mean by "asynchronous"? Receiving answers to sent request through Client.receive is always asynchronous.

**Comment by pabx06** [comment]
I have noticed High cpu usage in the client receive method with 0 as timeout i think it is because it is nested into a while true loop. I know i could use a higher timeout for receive but i wont get update in real time . Am i wrong ?

**Comment by levlam** [comment]
Yes, it is wrong. Receive will return as soon as any response/update is available. Timeout is a maximum wait time inside the method if there is no any new updates.

**Comment by dancojocaru2000** [comment]
When multiple clients are to be used, blocking in receive is impractical. While waiting for one client to receive something, another one might. 

There is no `select` equivalent for tdlib clients. Because of that, a way to asynchronously receive updates would be preferable.

**Comment by levlam** [comment]
@dancojocaru2000 Blocking a thread in receive is absolutely legal way. You can have thousands threads waiting for updates without any performance impact. They will be woken up by OS only when new data arrives,

**Comment by Thoufak** [comment]
> @dancojocaru2000 Blocking a thread in receive is absolutely legal way. You can have thousands threads waiting for updates without any performance impact. They will be woken up by OS only when new data arrives,

I don't understand how to implement this. If I call _receive_ from a second thread while the call to _recieve_ in the first thread hasn't returned, I get an error:
[Client.cpp:278]	Receive is called after Client destroy, or simultaneously from different threads

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/docs/td__json__client_8h.html. You must receive and handle all updates and request responses in a dedicated thread, which does nothing besides that. It is wrong and impossible to receive events from a specific client in different threads simultaneously.

**Comment by dancojocaru2000** [comment]
The problem is that receiving from multiple clients implies calling receive from multiple threads at once.

**Comment by levlam** [comment]
@dancojocaru2000 And this is not a problem. It is perfectly fine to call `td_json_client_receive` from different threads for different clients.

**Comment by dancojocaru2000** [comment]
@levlam Ah, I see, so the problem arises *only* when receiving on the same client from multiple threads.

**Comment by levlam** [comment]
@dancojocaru2000 Yes.
