### ISSUE TITLE
Banned phone number: 6285933681678

### ISSUE THREAD

**Issue by Pandiirawan** [tdlib/td#3096]
I'm trying to use my mobile phone number: 6285933681678
But Telegram says it's banned. Please help.

App version: 11.2.0 (52992)
OS version: SDK 33
Device Name: OPPOCPH2325
Locale: in

**Comment by levlam** [comment]
Try to log in in an official mobile app and follow the provided instructions.

**Comment by Pandiirawan** [comment]
Buka belokir akun telegram saya ,karna sangat penting :085933681678

Pada Rab, 23 Okt 2024 16.01, Aliaksei Levin ***@***.***>
menulis:
