### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Danielrahimi1** [tdlib/td#31]
And here is the message:
Build FAILED.

"C:\Users\Daniel\Documents\GitHub\td\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Daniel\Documents\GitHub\td\build\test\all_tests.vcxproj" (default target) (3) ->
"C:\Users\Daniel\Documents\GitHub\td\build\tdactor\tdactor.vcxproj" (default target) (4) ->
"C:\Users\Daniel\Documents\GitHub\td\build\tdutils\tdutils.vcxproj" (default target) (5) ->
"C:\Users\Daniel\Documents\GitHub\td\build\tdutils\generate\tdmime_auto.vcxproj" (default target) (6) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(1
71,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Daniel\Documents\GitHub\td\build\tdutils\generate\tdmime_
auto.vcxproj]

    0 Warning(s)
    1 Error(s)

**Comment by levlam** [comment]
This error supposed to happen when gperf isn't found.
Could you try to manually run from the <path to TDLib sources>/tdutils/generate/ directory command
powershell -ExecutionPolicy ByPass " & gperf -m100 --output-file=auto/mime_type_to_extension.cpp auto/mime_type_to_extension.gperf"?

**Comment by mostafa8026** [comment]
I have the same problem, after downloading gperf (not sed) and adding its install path to environment variables, it was fixed.

**Comment by levlam** [comment]
Error message, shown when gperf is not found, was improved in 1.2.0.
