### ISSUE TITLE
org.drinkless.tdlib.TdApi not in project (java)

### ISSUE THREAD

**Issue by Pepesote** [tdlib/td#310]
Hi, I've imported the project and eclipse can't find the file TdApi, can someone tell me what could I do please?

**Comment by mincong-h** [comment]
`TdApi.java` is generated after the TDLib build — did you build it locally? Instruction is available here https://github.com/tdlib/td/tree/master/example/java

**Comment by Pepesote** [comment]
Oh I didn't that, I'm gonna try it... thanks! :D

**Comment by Pepesote** [comment]
Okay, I've compiled the library but it stills not being at the package it should be...

**Comment by Pepesote** [comment]
Done, thanks! :D

**Comment by lixiaodong** [comment]
TDApi.java the file size is exceeds the configured limit 2.56MB

**Comment by lixiaodong** [comment]
it fixed !  
i modify the idea.properties file 
idea.max.intellisense.filesize=4000
