### ISSUE TITLE
About updateAuthorizationState

### ISSUE THREAD

**Issue by kikyou2022** [tdlib/td#3102]
My question may not be related to tdlib but I'm really confused and want an answer

There is updateAuthorizationState push update in tdlib, but I did not find a similar update in the official original api documentation.

Does this mean that if I use the original api, I can only get the account authorization status manually? Or is it the reason I haven't found it?

**Comment by kikyou2022** [comment]
@levlam

**Comment by levlam** [comment]
You have to store and update authorization status yourself when you don't use TDLib.

**Comment by kikyou2022** [comment]
OK thanks
