### ISSUE TITLE
Phone number have been banned shortly after entering authentication code

### ISSUE THREAD

**Issue by thunderquack** [tdlib/td#312]
Hi!
I have just compilied TDLib with CSharp sample console application. Shortly after I had entered phone number and authorization code my phone number was banned. Now while I am trying to sign in, I just receive code = 400, message = "PHONE_NUMBER_BANNED"
It's quite strange because official sample doesn't work with official library

**Comment by 3webmaster** [comment]
I have the same problem.

**Comment by pabx06** [comment]
i have banned two mobile phone numbers thanks to td_example. spent the whole day trying to figure it out... fed up

**Comment by 3webmaster** [comment]
To be honest, the support responded quickly (within 12 hours) and unbanned my phone number. After that, I resorted to the Telethon library (in Python) - it's easier to use, doesn't require compiling and doesn't get your phone number banned. :)

**Comment by korangu** [comment]
telegram accounts randomly getting banned the admin itself either dont know the exact reason for ban or dont want to disclose to the user. 

but i appreciate them,they unban accounts upon user request.

**Comment by zelenin** [comment]
I'm confused with that. I did registration routine with tdlib and new number, sent ```getMe``` request and stop app. I run app second time and I got ban error. There is no ban behavior. It demotivates.

**Comment by levlam** [comment]
The only way to stop spam is to make it unprofitable. If spam account has been allowed to do "ban behavior", then it is too late to ban him, because it has already been justified. I've never heard about complaints about ban from ordinary users, so it seems that the system works good enough.

**Comment by 3webmaster** [comment]
In my opinion, it's the implementation of the library that causes the problem. I don't see similar complaints from users of other Telegram libraries.

**Comment by FrayxRulez** [comment]
I'm using TDLib in production since february and none of my users got banned while using my app.
I think that the same applies to Telegram X.

**Comment by konstantin24121** [comment]
i try use iGram app for windows and all my accounts blocked(

**Comment by levlam** [comment]
@konstantin24121 Please write phone numbers and other details to recover@telegram.org.

**Comment by StagsGit** [comment]
same problem!
this problem occurs after TDlib1.3.0!
there isn't any way to fix it?

**Comment by levlam** [comment]
@StagsGit You need to write phone number and other details to recover@telegram.org.

**Comment by StagsGit** [comment]
@levlam I found the solution
just use API_ID and API_HASH that got from an account that account ID begging with 7******** or under that
ban will not occurred :)

**Comment by ezze** [comment]
Faced the same issue trying to build and run [TELEports](https://gitlab.com/ubports/apps/teleports/issues/154) for Ubuntu Touch. It's weird.

**Comment by iMat1n** [comment]
is it possible that we can back a banned phone number's data back ? this is so fkd up, i need my data!

**Comment by levlam** [comment]
@iMat1n If you believe that your account was blocked accidentally, you need to write its phone number and other details to recover@telegram.org.

**Comment by iMat1n** [comment]
> 
> 
> @iMat1n If you believe that your account was blocked accidentally, you need to write its phone number and other details to [recover@telegram.org](mailto:recover@telegram.org).

i already did, im asking if its possible that i ca get my data back. they were my everything tbh!

**Comment by h3k1ru** [comment]
Looks like there was a huge ban wave right now. Got my main account and sub account banned. Used telethon python library to play a game in one of channels.

**Comment by luizrosevelt** [comment]
> @iMat1n If you believe that your account was blocked accidentally, you need to write its phone number and other details to [recover@telegram.org](mailto:recover@telegram.org).

My two numbers got banned within 24hrs for no reason. I have written to the email but wondering how long it takes to have it resolved or have a response at least.

**Comment by ezze** [comment]
@luizrosevelt In my case it was ~ 12 hours.

**Comment by luizrosevelt** [comment]
> @luizrosevelt In my case it was ~ 12 hours.

Thanks for the response. Seems telegram just blocks numbers randomly without reason.. sad

**Comment by iMat1n** [comment]
> 
> 
> > @luizrosevelt In my case it was ~ 12 hours.
> 
> Thanks for the response. Seems telegram just blocks numbers randomly without reason.. sad

it has to be some reasons because i've never got a ban on my sim card number and a voip number , but they both got banned after a few secounds that i logged in using my bot. it has to be some permissions i think to be granted to your account then u wont get a ban.
not 100% accturate but this is what i think.

**Comment by spiffytwin** [comment]
My phone number was blocked this morning. I have no idea why? What do I do? I have important stuff going on there, I feel like crying o!

**Comment by levlam** [comment]
@spiffytwin Please, write to recover@telegram.org your phone number and description of the problem.

**Comment by spiffytwin** [comment]
I have written to recover@telegram.org. they are yet to reply. Please help
me out. The phone number is 08165250912. I was involved with some telegram
bots, maybe that's the reason for the ban.

**Comment by Sakujes** [comment]
This just happened to me, more than 3 years after this issue was opened, it seems unbelievable that if this is a "bug" and is on such a big scale (it literally bans your account without any warning or questions) it has not been fixed for over 3 years and still does happen, I wrote to recover@telegram.org and waiting for an answer... Anyways thanks everyone here in this thread for helping others and explaining what to do, why it happened and saying it worked for you, I would have already lost my mind if I did not find this issue, lets just hope they will be able to recover my account and I won't lose any data, my contacts already see my account as "Deleted Account" :/

**Comment by iMat1n** [comment]
> This just happened to me, more than 3 years after this issue was opened, it seems unbelievable that if this is a "bug" and is on such a big scale (it literally bans your account without any warning or questions) it has not been fixed for over 3 years and still does happen, I wrote to [recover@telegram.org](mailto:recover@telegram.org) and waiting for an answer... Anyways thanks everyone here in this thread for helping others and explaining what to do, why it happened and saying it worked for you, I would have already lost my mind if I did not find this issue, lets just hope they will be able to recover my account and I won't lose any data, my contacts already see my account as "Deleted Account" :/

Don't worry, they usually resound max 2 days, which happened to me, use an alt account for now and you will have your accounts back as i got mine.
Literally every singe message was recovered, but chats were unmuted and pinned chats were lost their place as a pinned chat.

And about this problem, i don't think this is a "bug", it's more like Telegram is now more sensitive to some numbers and logins which happen not using the official clients.

Anyway, gl with getting your account back.

**Comment by Sakujes** [comment]
My phone number got unbanned but I still can't log-in, because when I try to, they refuse to send me an SMS like they used to, but they want me to enter a code that I was supposed to recieve on a different session, but ALL of my sessions got disconnected (also RIP secret chats...) so I can't do anything, if I try it on an older desktop client, they never send me any SMS, on the newest one it shows this screenshot below: and on my phone clients it literally wants to open my mail app???? so I am "softlocked"/stuck till they fix yet another stupid error... Does anyone have ANY idea what can I do? Like disconnecting all of my sessions from a website if thats possible? Or forcing them to send me an SMS somehow?
![image](https://user-images.githubusercontent.com/64438637/127257738-f96a681a-861d-4502-af8a-e1ca430b5e6e.png)

**Comment by IRGC** [comment]
have you tried to login via mobile apps ?

**Comment by GaGUY2** [comment]
> > @iMat1n If you believe that your account was blocked accidentally, you need to write its phone number and other details to [recover@telegram.org](mailto:recover@telegram.org).
> 
> My two numbers got banned within 24hrs for no reason. I have written to the email but wondering how long it takes to have it resolved or have a response at least.

Yes same problem to me but i didnt unban why? I spent 6 hours but not unban

**Comment by GaGUY2** [comment]
> > This just happened to me, more than 3 years after this issue was opened, it seems unbelievable that if this is a "bug" and is on such a big scale (it literally bans your account without any warning or questions) it has not been fixed for over 3 years and still does happen, I wrote to [recover@telegram.org](mailto:recover@telegram.org) and waiting for an answer... Anyways thanks everyone here in this thread for helping others and explaining what to do, why it happened and saying it worked for you, I would have already lost my mind if I did not find this issue, lets just hope they will be able to recover my account and I won't lose any data, my contacts already see my account as "Deleted Account" :/
> 
> Don't worry, they usually resound max 2 days, which happened to me, use an alt account for now and you will have your accounts back as i got mine.
> Literally every singe message was recovered, but chats were unmuted and pinned chats were lost their place as a pinned chat.
> 
> And about this problem, i don't think this is a "bug", it's more like Telegram is now more sensitive to some numbers and logins which happen not using the official clients.
> 
> Anyway, gl with getting your account back.

Can i get account unbanned?

**Comment by GaGUY2** [comment]
I

> > This just happened to me, more than 3 years after this issue was opened, it seems unbelievable that if this is a "bug" and is on such a big scale (it literally bans your account without any warning or questions) it has not been fixed for over 3 years and still does happen, I wrote to [recover@telegram.org](mailto:recover@telegram.org) and waiting for an answer... Anyways thanks everyone here in this thread for helping others and explaining what to do, why it happened and saying it worked for you, I would have already lost my mind if I did not find this issue, lets just hope they will be able to recover my account and I won't lose any data, my contacts already see my account as "Deleted Account" :/
> 
> Don't worry, they usually resound max 2 days, which happened to me, use an alt account for now and you will have your accounts back as i got mine.
> Literally every singe message was recovered, but chats were unmuted and pinned chats were lost their place as a pinned chat.
> 
> And about this problem, i don't think this is a "bug", it's more like Telegram is now more sensitive to some numbers and logins which happen not using the official clients.
> 
> Anyway, gl with getting your account back.

I spent more than 6 hours 
But no reply and unban
How to make unban bro

**Comment by GaGUY2** [comment]
> > This just happened to me, more than 3 years after this issue was opened, it seems unbelievable that if this is a "bug" and is on such a big scale (it literally bans your account without any warning or questions) it has not been fixed for over 3 years and still does happen, I wrote to [recover@telegram.org](mailto:recover@telegram.org) and waiting for an answer... Anyways thanks everyone here in this thread for helping others and explaining what to do, why it happened and saying it worked for you, I would have already lost my mind if I did not find this issue, lets just hope they will be able to recover my account and I won't lose any data, my contacts already see my account as "Deleted Account" :/
> 
> Don't worry, they usually resound max 2 days, which happened to me, use an alt account for now and you will have your accounts back as i got mine.
> Literally every singe message was recovered, but chats were unmuted and pinned chats were lost their place as a pinned chat.
> 
> And about this problem, i don't think this is a "bug", it's more like Telegram is now more sensitive to some numbers and logins which happen not using the official clients.
> 
> Anyway, gl with getting your account back.

I mail them with when my account was banned there is help button and i report my issue and they didnt reply me i spent 9 hours bt didnt get reply and unban

**Comment by LordRishav** [comment]
My account got banned while playing with telega.el (a Telegram client built on TDLib) on the previous Saturday (almost a week now) and even after multiple mails to recover@telegram.org and login@stel.com, I have not got a single reply from them.

**Comment by levlam** [comment]
@LordRishav Could you send banned phone number to https://t.me/tdlib_bot?

**Comment by LordRishav** [comment]
@levlam My account was unbanned. Thank you :)

**Comment by sergeevabc** [comment]
A few days ago I used 64gram (an unofficial Telegram client) to register an account, because an official desktop client refused to request verification SMS. Right after registration was successfully completed, my number got banned. I filed a report via support section of Telegram website, they didn't respond via e-mail, but it seems ban was removed silently. Now, should I try to login via 64gram again, or it will lead to another ban?

**Comment by Naist4869** [comment]
My account was banned after I entered the verification code, I want to sync messages into Wechat because the Chinese policy makes it difficult for me to log into telegram,It's very difficult,  I'm not sending ads and I'm using my own phone, It's crazy.

**Comment by scrtsct** [comment]
Please how can I unban my telegram number and what are the details i should mail them to get my number unban?

**Comment by levlam** [comment]
@scrtsct You need to try to log in from an official mobile app and send a email to recover the account by following instructions provided by the app.

**Comment by Anas6co** [comment]
Mine has been a month or so and still banned

**Comment by munagodd** [comment]
Please anyone with an updated info about how to get unbanned, I will appreciate. I have written to to team countless times with no reply from them and it's been 2months now

**Comment by iMat1n** [comment]
The support seems dead. They don't answer any emails or support tickets.

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by THAESUMON30** [comment]
Please+959423501808

But
Telegram says it's banned. Please help. Please
check help my account. I have done nothing wrong to be banned I will appreciate if you unbun my account thanks you so much

**Comment by THAESUMON30** [comment]
I'm trying to use my mobile phone number: 959423501808
But Telegram says it's banned. Please help.

App version: 11.0.0 (51439)
OS version: SDK 34
Device Name: Xiaomi22101316G
Locale: en

**Comment by adnankhaki143-netizen** [comment]
Please I need it 🙏 please send me anyone on this Gmail.
adnankhaki143@gmail.com
