### ISSUE TITLE
Correct JSON-query to api

### ISSUE THREAD

**Issue by sprainbrains** [tdlib/td#3122]
Hey, everybody. I'm trying to make a correct JSON query to get a list of chats.
For example, for chatListArchive:
`td_send(client_id, "{\"@type\":\"chatListArchive\"}");`

After that I got error:
![изображение](https://github.com/user-attachments/assets/8faba86e-b5e5-4d20-ae11-f84a8143b453)

How to make the correct query for a getting chat list in tdjson_api?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples for examples of TDLib usage from different languages.

**Comment by sprainbrains** [comment]
> See https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples for examples of TDLib usage from different languages.

I saw it. In tdjson_example in cpp it's not exist.

**Comment by levlam** [comment]
If you want to use JSON interface, it is better to do this from another programming language. See third-party examples on other languages, for example, in Python: https://github.com/tdlib/td/tree/master/example#using-tdlib-in-python-projects.

You can also check examples for the library you use.

**Comment by sprainbrains** [comment]
> If you want to use JSON interface, it is better to do this from another programming language. See third-party examples on other languages, for example, in Python: https://github.com/tdlib/td/tree/master/example#using-tdlib-in-python-projects.
> 
> You can also check examples for the library you use.

I checked it with python - got the same error. Any ideas?

**Comment by levlam** [comment]
Use any wrapper from https://github.com/tdlib/td/tree/master/example#using-tdlib-in-python-projects that provides strong typing and can serialize requests for you. You can find the list of all requests and their description at https://core.telegram.org/tdlib/getting-started.

**Comment by sprainbrains** [comment]
> Use any wrapper from https://github.com/tdlib/td/tree/master/example#using-tdlib-in-python-projects that provides strong typing and can serialize requests for you. You can find the list of all requests and their description at https://core.telegram.org/tdlib/getting-started.

NOT WORK!

```
ERROR|b'{\'@type\': \'error\', \'code\': 400, \'message\': \'Failed to parse JSON object as TDLib request: Unknown class "chatListArchive"\', \'@extra\': \'chatListArchive_extra\'}'
```
I trying to make query for this https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_list_archive.html
How to make it with json? 
Now it didn't work! Please, hear me.

**Comment by levlam** [comment]
This class isn't a function. You have to read https://core.telegram.org/tdlib/getting-started.

**Comment by sprainbrains** [comment]
> This class isn't a function. You have to read https://core.telegram.org/tdlib/getting-started.

I have read this page many times. 
I have looked at all the examples. There is not a single example of how I can get the class via td_json.
That's why I'm asking - how can I do this? Can I do it at all

**Comment by sprainbrains** [comment]
> This class isn't a function. You have to read https://core.telegram.org/tdlib/getting-started.

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/c33c666b-d1fa-41d6-b8c9-d624dc7cd84a">

After almost day in td source I found explaining code. Why couldn't it be written explicitly that td_json only supports working with functions?

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started:
> If the Application needs more chats, it must send another `loadChats` request.

**Comment by sprainbrains** [comment]
> https://core.telegram.org/tdlib/getting-started:
> 
> > If the Application needs more chats, it must send another `loadChats` request.

Of course I using it. But here i can't determine if the  chat belongs in the Archive folder. I found update only for updateChatAddedList

**Comment by levlam** [comment]
> But here i can't determine if the chat belongs in the Archive folder. 

https://core.telegram.org/tdlib/getting-started:
> The [positions](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat.html#a40cebc843050f52a09e2ef471c9091e1) of chats in chat lists are managed by TDLib, so the Application only needs to listen to updates that change the chat.positions field, maintain the list of all chats, sorted by the pair (position.order, chat.id) in descending order

> ow....wait... I can set "chat_list" in loadChats to get chats from needed list?

Yes, `loadChats` has the parameters `chat_list:ChatList limit:int32`.

**Comment by sprainbrains** [comment]
> > But here i can't determine if the chat belongs in the Archive folder.
> 
> https://core.telegram.org/tdlib/getting-started:
> 
> > The [positions](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat.html#a40cebc843050f52a09e2ef471c9091e1) of chats in chat lists are managed by TDLib, so the Application only needs to listen to updates that change the chat.positions field, maintain the list of all chats, sorted by the pair (position.order, chat.id) in descending order
> 
> > ow....wait... I can set "chat_list" in loadChats to get chats from needed list?
> 
> Yes, `loadChats` has the parameters `chat_list:ChatList limit:int32`.

Thanks. And thank you for your patience! it's working)

**Comment by sprainbrains** [comment]
Question resolved)
