### ISSUE TITLE
How do I unset proxy?

### ISSUE THREAD

**Issue by mkliu** [tdlib/td#313]
So I've set socks5 proxy before, but then later on the proxy is not working and I want to unset it.
I tried to set to empty proxy but it's not working. Any suggestions?

**Comment by zevlg** [comment]
"close" your current tdlib client instance and create new one without calling to "setProxy" this time

**Comment by levlam** [comment]
Set to empty proxy should work.

**Comment by mkliu** [comment]
looks like closing the client doesn't work, the next time it comes back, it's still trying to use the same proxy. Set empty proxy worked for me in the end, just have to set it at the right time.
