### ISSUE TITLE
Have no write access to the chat

### ISSUE THREAD

**Issue by asarubbo** [tdlib/td#3131]
I have a python script that uses [python-telegram](https://github.com/alexander-akhmetov/python-telegram)

The script sends a random message in a group where I'm the owner, but today I get:

```
send message error: {'@type': 'error', 'code': 400, 'message': 'Have no write access to the chat', '@extra': {'request_id': 'af17eaddebb046b7b9d3bc059747e940'}}
```

I tried to cleanup the local tdlib database directory but I get the same.
I was using tdlib-1.8.28 but before create this report I updated to 1.8.39

NOTE 1: from the UI I can send message to that group.
NOTE 2: Atm I have no issues in sending message to my contacts in the same way

Can you give hints on what's wrong?

**Comment by levlam** [comment]
Check that the group wasn't converted to a supergroup.

**Comment by asarubbo** [comment]
> Check that the group wasn't converted to a supergroup.

Thanks for the info. There are no traces that it is a supergroup. I didn' convert to supergroup, but maybe it was done automatically when I changed the admin nickname.

Is there something (parameters/field) I can edit to send message to supergroup or is not allowed? Thanks

**Comment by levlam** [comment]
You need to send messages to the supergroup instead of the basic group, hence you must use the identifier of the supergroup chat.

**Comment by asarubbo** [comment]
> You need to send messages to the supergroup instead of the basic group, hence you must use the identifier of the supergroup chat.

Good to know. Didn't think to the fact that the group id was changed.

I changed the group id but I get:

```
send message error: {'@type': 'error', 'code': 400, 'message': 'Chat not found', '@extra': {'request_id': '0ef00702e75f4ae98501fe7884b18272'}}
```

I cleaned up my tdlib database dir and I'm calling `get_chats()` before send the message. Anything I missed?

**Comment by levlam** [comment]
You likely pass a wrong chat identifier. You must receive it from TDLib.

**Comment by levlam** [comment]
> In result_get_chats.update I can see that all other supergrups are prefixed in the same way, so not just a random value.

No, it is just a random value.
