### ISSUE TITLE
Problem sending sendMessageAlbum 

### ISSUE THREAD

**Issue by Fabloid** [tdlib/td#3140]
Hello.
I add pictures using InputFileLocal, the pictures exist and are accessible. Then I send them as SendMessageAlbum. The following response comes, in which I do not see any errors:
messages {
  total_count = 2
  messages = vector[2] {
    message {
      id = 563085425
      sender_id = messageSenderUser {
        user_id = 6822912334
      }
      chat_id = -1002276046439
      sending_state = messageSendingStatePending {
        sending_id = 0
      }
      scheduling_state = null
      is_outgoing = true
      is_pinned = false
      is_from_offline = false
      can_be_edited = false
      can_be_forwarded = true
      can_be_replied_in_another_chat = false
      can_be_saved = true
      can_be_deleted_only_for_self = false
      can_be_deleted_for_all_users = true
      can_get_added_reactions = false
      can_get_statistics = false
      can_get_message_thread = false
      can_get_read_date = false
      can_get_viewers = false
      can_get_media_timestamp_links = false
      can_report_reactions = false
      has_timestamped_media = true
      is_channel_post = false
      is_topic_message = false
      contains_unread_mention = false
      date = 1731662656
      edit_date = 0
      forward_info = null
      import_info = null
      interaction_info = null
      unread_reactions = vector[0] {
      }
      fact_check = null
      reply_to = null
      message_thread_id = 0
      saved_messages_topic_id = 0
      self_destruct_type = null
      self_destruct_in = 0.000000
      auto_delete_in = 0.000000
      via_bot_user_id = 0
      sender_business_bot_user_id = 0
      sender_boost_count = 0
      author_signature = ""
      media_album_id = -5196125781433730563
      effect_id = 0
      restriction_reason = ""
      content = messagePhoto {
        photo = photo {
          has_stickers = false
          minithumbnail = null
          sizes = vector[1] {
            photoSize {
              type = "i"
              photo = file {
                id = 1267
                size = 18720
                expected_size = 18720
                local = localFile {
                  path = "C:\{path}\20241115092417074_01570094-bd18-4c57-937e-90b9d28cb73e.png"
                  can_be_downloaded = false
                  can_be_deleted = false
                  is_downloading_active = false
                  is_downloading_completed = true
                  download_offset = 0
                  downloaded_prefix_size = 18720
                  downloaded_size = 18720
                }
                remote = remoteFile {
                  id = ""
                  unique_id = ""
                  is_uploading_active = false
                  is_uploading_completed = false
                  uploaded_size = 0
                }
              }
              width = 200
              height = 200
              progressive_sizes = vector[0] {
              }
            }
          }
        }
        caption = formattedText {
          text = "asdads"
          entities = vector[0] {
          }
        }
        show_caption_above_media = false
        has_spoiler = false
        is_secret = false
      }
      reply_markup = null
    }
    message {
      id = 563085433
      sender_id = messageSenderUser {
        user_id = 6822912334
      }
      chat_id = -1002276046439
      sending_state = messageSendingStatePending {
        sending_id = 0
      }
      scheduling_state = null
      is_outgoing = true
      is_pinned = false
      is_from_offline = false
      can_be_edited = false
      can_be_forwarded = true
      can_be_replied_in_another_chat = false
      can_be_saved = true
      can_be_deleted_only_for_self = false
      can_be_deleted_for_all_users = true
      can_get_added_reactions = false
      can_get_statistics = false
      can_get_message_thread = false
      can_get_read_date = false
      can_get_viewers = false
      can_get_media_timestamp_links = false
      can_report_reactions = false
      has_timestamped_media = true
      is_channel_post = false
      is_topic_message = false
      contains_unread_mention = false
      date = 1731662656
      edit_date = 0
      forward_info = null
      import_info = null
      interaction_info = null
      unread_reactions = vector[0] {
      }
      fact_check = null
      reply_to = null
      message_thread_id = 0
      saved_messages_topic_id = 0
      self_destruct_type = null
      self_destruct_in = 0.000000
      auto_delete_in = 0.000000
      via_bot_user_id = 0
      sender_business_bot_user_id = 0
      sender_boost_count = 0
      author_signature = ""
      media_album_id = -5196125781433730563
      effect_id = 0
      restriction_reason = ""
      content = messagePhoto {
        photo = photo {
          has_stickers = false
          minithumbnail = null
          sizes = vector[1] {
            photoSize {
              type = "i"
              photo = file {
                id = 1267
                size = 18720
                expected_size = 18720
                local = localFile {
                  path = "C:\{path}\20241115092417074_01570094-bd18-4c57-937e-90b9d28cb73e.png"
                  can_be_downloaded = false
                  can_be_deleted = false
                  is_downloading_active = false
                  is_downloading_completed = true
                  download_offset = 0
                  downloaded_prefix_size = 18720
                  downloaded_size = 18720
                }
                remote = remoteFile {
                  id = ""
                  unique_id = ""
                  is_uploading_active = true
                  is_uploading_completed = false
                  uploaded_size = 0
                }
              }
              width = 200
              height = 200
              progressive_sizes = vector[0] {
              }
            }
          }
        }
        caption = formattedText {
          text = "asdads"
          entities = vector[0] {
          }
        }
        show_caption_above_media = false
        has_spoiler = false
        is_secret = false
      }
      reply_markup = null
    }
  }
}

In TG, the user writes that he sends a photo, but nothing happens. I am writing in C#. If I send using SendMessage with content in the form of a picture, the situation is the same. What am I doing wrong?

**Comment by levlam** [comment]
Do you process [updateMessageSendSucceeded](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_send_succeeded.html) updates to know whether the messages are actually sent?

**Comment by Fabloid** [comment]
You won't believe it, but I just wrote this here and it worked=)))
