### ISSUE TITLE
Force online state

### ISSUE THREAD

**Issue by 0xc0de1e55** [tdlib/td#3144]
Hello!

TDlib automatically track network state and properly operate over them. But there is an issue when TDlib goes offline: it takes about two minutes to be online if it is possible. It seems this is default timeout in TDlib to check if it is online and can connect to server.

But if I know that network is fine now, how can I force TDlib to check network without waiting for two minutes?

**Comment by levlam** [comment]
You can call `setNetworkType` for this.

But instead of this, you must set the option "online" to true, whenever the app is opened, which will make recover almost immediate if the app is opened.

**Comment by levlam** [comment]
"online" option is about the user, not the network.

`setNetworkType` can be used if you know if the network or its type has changed.

**Comment by 0xc0de1e55** [comment]
Great, thanks!
