### ISSUE TITLE
(JAVA) - Project without errors. Can't find org.drinkless.tdlib.example.Example

### ISSUE THREAD

**Issue by Pepesote** [tdlib/td#315]
I've built all the project and I got no errors on it at eclipse; but when I try to run the example, I get a message in which he can't find main class org.drinkless.tdlib.example.Example... any idea?

**Comment by sadeghpro** [comment]
can you give project structure and full error exception and line of code error occurs

**Comment by Pepesote** [comment]
Well, I had to change the imports because I didn't know how to import the project properly, this is my current project structure:

![image](https://user-images.githubusercontent.com/41114193/43009521-3e591346-8c3e-11e8-9038-5829f0471fd2.png)

Now the problem I get is this:

![image](https://user-images.githubusercontent.com/41114193/43009566-511cf998-8c3e-11e8-875a-fe1d55eab74c.png)

And the line at the file is that:

![image](https://user-images.githubusercontent.com/41114193/43009644-7fe0ecda-8c3e-11e8-8770-b9d6cd8dabfb.png)

**Comment by Pepesote** [comment]
I moved the tdjni library to my workspace and I changed the 58th line for this:

![image](https://user-images.githubusercontent.com/41114193/43011081-b0d21bf8-8c42-11e8-8ec1-49d77a14512b.png)

And now my error is this:

![image](https://user-images.githubusercontent.com/41114193/43011100-bf22ea20-8c42-11e8-8912-1a0fcf13ee98.png)

**Comment by levlam** [comment]
Now you need to copy to your workspace dependent libraries `LIBEAY32.dll`, `SSLEAY32.dll` and `zlib1.dll` from `example\java\build\Release` folder for Release build or `LIBEAY32.dll`, `SSLEAY32.dll` and `zlibd1.dll` from `example\java\build\Debug` for Debug build.

**Comment by Pepesote** [comment]
@levlam I did it but:

1. In `example\java\build\Debug` I don't have `zlib1.dll`
2. The error stills appearing

I'm getting mad with this...

**Comment by Pepesote** [comment]
I used `Dependency Walker` to see what libraries I need... I'm gonna try to find the `zlib1.dll` library

[http://www.dependencywalker.com/](url)

**Comment by levlam** [comment]
The library should be anyway in `example\java\build\Debug`  or at least somewhere in `vcpkg/ installed/...-windows/bin` or `vcpkg/ installed/...-windows/debug/bin`.

**Comment by Pepesote** [comment]
I found it and moved it to my workspace, but the error stills appearing. With dependency walker I can see that he find all the dependent libraries but each one needs another libraries I don't have, like this:

![image](https://user-images.githubusercontent.com/41114193/43046169-df5136e2-8dc5-11e8-928b-9d8d142d6b39.png)

**Comment by levlam** [comment]
These libraries aren't missing. DependencyWalker is outdated and doesn't support that kind of libraries, but there is no problem with them. Probably you have copied wrong zlib/openssl dll for different architecture x86/x64 or for different Debug/Release mode.

**Comment by Pepesote** [comment]
I built all in Debug mode and installed the dependencies as explained in [https://github.com/tdlib/td#installing-dependencies](url)

**Comment by levlam** [comment]
Then needed dll's are in `C:\src\vcpkg\installed\x64-windows\debug\bin\`.

**Comment by Pepesote** [comment]
Copying this files, the error stills appearing...

**Comment by levlam** [comment]
Probably, you need to set correct Java library path. See, for example, https://examples.javacodegeeks.com/java-basics/java-library-path-what-is-it-and-how-to-use/ for different ways to achieve this.

**Comment by Pepesote** [comment]
I modified my build path in eclipse to the folder where is tdjni.dll but stills not working...

**Comment by Pepesote** [comment]
I tried to change the line 58 and 59 in this way:

![image](https://user-images.githubusercontent.com/41114193/43328436-4111f8e8-91be-11e8-9947-6cdfae7417c9.png)

And I get the same error, so now I know that I changed succesfully my build path
But the error remains with me

**Comment by levlam** [comment]
Are you sure that you use 64-bit build and not 32-bit? MSVC by default builds 32-bit binaries and you need to delete the whole build directory to reconfigure cmake and MSVC for 64-bit build. If your library is 32-bit, you need dll-s from `C:\src\vcpkg\installed\x86-windows\debug\bin\`.

**Comment by Pepesote** [comment]
I think that if I built it in 32-bit, I would receive the message in this post:

https://github.com/tdlib/td/issues/299

**Comment by Pepesote** [comment]
Any idea?

**Comment by levlam** [comment]
You can try to recompile everything from very beginning, deleting all build directories and specifying option `-A x64` to first CMake invocation and building for Release using `cmake --build . --config Release`.
Then you can try to recreate Eclipse project and make java.library.path point to directory `...\example\java\build\Release\`.

**Comment by levlam** [comment]
If you still have `Can't find dependent libraries` error, then you need to copy dependent libraries to the project Working directory, because java.library.path is completely ignored when dependent libraries are searched. Alternatively, you can add folder with OpenSSL/zlib shared libraries to PATH environment variable.

**Comment by mostafa8026** [comment]
thanks for your comment. It saves my day.

> If you still have `Can't find dependent libraries` error, then you need to copy dependent libraries to the project Working directory, because java.library.path is completely ignored when dependent libraries are searched. Alternatively, you can add folder with OpenSSL/zlib shared libraries to PATH environment variable.

**Comment by githubr111** [comment]
@Pepesote , can you share tdjni.dll, pls, i`m getting struggled with instructions, thanks in advance

**Comment by culexjj** [comment]
Hello pepesote, did you finally make the example work in Eclipse?
