### ISSUE TITLE
Multiple tdlib clients for same user on different workstations

### ISSUE THREAD

**Issue by pfeux** [tdlib/td#3150]
Hello

As the title says, I am trying to upload images using tdlib clients for same user on different workstations at the same time using python. Both got logged in using phone number, separate codes and password but one working fine and other one throwing Unauthorised error when trying to upload the file. I authorised both clients manually one after other and not at the same time. How can I fix this? Please help.

**Comment by levlam** [comment]
The others can be logged out because server detected suspicious behaviour. And using many devices simultaneously is clearly a very suspicious behavior.

**Comment by pfeux** [comment]
Thanks @levlam for your reply. Is there a way to use it on multiple devices by passing different parameter values in setTdLibParameters?

**Comment by levlam** [comment]
No.

**Comment by pfeux** [comment]
Thanks 😄
