### ISSUE TITLE
Consistent message reactions

### ISSUE THREAD

**Issue by true-seeker** [tdlib/td#3155]
Greetings! I've read thread https://github.com/tdlib/td/issues/2312. 

I got that tdlib decides when reactions need to be returned via `GetChatHistory`. But still have a question. 
Is there a guaranteed way to receive message reactions? Probably via `GetMessage` or `GetMessageLocally` methods?

**Comment by levlam** [comment]
There is no way to do this. You must use a bot to receive updates about message reactions as fast as possible.

**Comment by true-seeker** [comment]
Thanks!
