### ISSUE TITLE
JAVA example build but only update the example.class or turn off generating javadocs

### ISSUE THREAD

**Issue by timbierenbreier** [tdlib/td#316]
I have built the java example and it works. Now I want to implement my own stuff in the Example.java. I don't want to build the whole thing again via "cmake --build . --target install" after every little change I make in the Example.java. What is another option? What can I do to just update my changes from the Example.java for the build files and run it then?

Also, every time i build the example, a lot of doc files (.html) are generated. Can I turn it off?

**Comment by levlam** [comment]
No. You can compile Example.java in any way you want. For example, like this:
```
javac -d bin org/drinkless/tdlib/example/Example.java 
```

**Comment by timbierenbreier** [comment]
Thanks!
