### ISSUE TITLE
How to set maximum RAM size used by TDLIB

### ISSUE THREAD

**Issue by vinifr** [tdlib/td#3162]
Hello. is it possible to set maximum RAM size used by TDLIB using setTdlibParameters?

I asked to chatGTP and it gave me this code, but it does not compile:

```
#include <td/telegram/Client.h>

void setTdlibParameters(td::Client *client) {
    td::td_api::setTdlibParameters parameters;
    parameters.use_test_dc_ = false; // Use production servers
    parameters.database_directory_ = "td_database";
    parameters.use_file_database_ = true;
    parameters.use_chat_info_database_ = true;
    parameters.use_message_database_ = true;

    // Limit the database size in memory (in bytes)
    parameters.database_max_size_ = 50 * 1024 * 1024; // 50 MB

    client->send_request(td::td_api::make_object<td::td_api::setTdlibParameters>(parameters),
                         [](auto response) {
                             if (response->get_id() == td::td_api::error::ID) {
                                 // Handle error
                             } else {
                                 // Successfully initialized
                             }
                         });
}
```

**Comment by levlam** [comment]
No, it isn't possible.

**Comment by LinnKhantNaung** [comment]
> Hello. is it possible to set maximum RAM size used by TDLIB using setTdlibParameters?
> 
> I asked to chatGTP and it gave me this code, but it does not compile:
> 
> ```
> #include <td/telegram/Client.h>
> 
> void setTdlibParameters(td::Client *client) {
>     td::td_api::setTdlibParameters parameters;
>     parameters.use_test_dc_ = false; // Use production servers
>     parameters.database_directory_ = "td_database";
>     parameters.use_file_database_ = true;
>     parameters.use_chat_info_database_ = true;
>     parameters.use_message_database_ = true;
> 
>     // Limit the database size in memory (in bytes)
>     parameters.database_max_size_ = 50 * 1024 * 1024; // 50 MB
> 
>     client->send_request(td::td_api::make_object<td::td_api::setTdlibParameters>(parameters),
>                          [](auto response) {
>                              if (response->get_id() == td::td_api::error::ID) {
>                                  // Handle error
>                              } else {
>                                  // Successfully initialized
>                              }
>                          });
> }
> ```
>
