### ISSUE TITLE
Customization of the Telegram channel interface

### ISSUE THREAD

**Issue by gmb15551** [tdlib/td#3168]
There is a user channel. Different types of messages are posted in the channel. The message frequency is high. For this reason, viewing the channel in feed mode can be extremely inconvenient for the user. However, not all messages are relevant to the user. They may only be interested in certain specific messages.

Therefore, I would like the user to be able to view messages through a customized interface that includes several tabs with different types of messages. These tabs can be considered as message filters. The user would be able to switch between the relevant tabs.

As far as I know, there are the following solutions:

1) Create an unofficial Telegram client.
2) Use a web application.

I would prefer not to implement the first option for now. The second option would require a server, which is not actually necessary.

The question is: is there any way to customize the interface for a specific channel within the official Telegram client? Or create a bot for the channel with a customized interface, but without buttons? The goal is to achieve a result similar to a regular app, but inside Telegram, and ideally without needing an unnecessary server.

Is such customization possible, or will I have to use one of the two options mentioned above?
Is it planned to add some kind of plugin store to the Telegram client that will allow customization of the interface of the official client?

**Comment by levlam** [comment]
> The message frequency is high. 

If it is really high, you may be limited by the Telegram server very fast.

> The question is: is there any way to customize the interface for a specific channel within the official Telegram client?

No.

> Or create a bot for the channel with a customized interface, but without buttons?

No.

> Is such customization possible, or will I have to use one of the two options mentioned above?

No.

> Is it planned to add some kind of plugin store to the Telegram client that will allow customization of the interface of the official client?

No.
