### ISSUE TITLE
getChatHistory only returns 1 message?

### ISSUE THREAD

**Issue by mkliu** [tdlib/td#317]
I have this weird problem, I'm using a javascript binding. No matter what I do, it only returns 1 message 

```
client.invoke({
    _: 'getChatHistory',
    chat_id: -232132019321,
    limit: 100,
  })
```

I tried all different configurations, it's always the same. However if I use getChatEventLog, it's working fine. Any suggestions?

**Comment by levlam** [comment]
See #168.
