### ISSUE TITLE
TdApi.DownloadFile receives no update when offset>256KB

### ISSUE THREAD

**Issue by cdxf** [tdlib/td#3170]
I’m trying to download a large file (>100MB) using TdApi.DownloadFile. 
When the offset < 262144 bytes, the download completes successfully and quickly. 
However, when the offset >= 262144  bytes, the download gets stuck. 
I no longer receive any updates, and the temporary directory creates a 512KB file with no further progress.
[tdlib.log](https://github.com/user-attachments/files/18028565/tdlib.log)

**Comment by cdxf** [comment]
In the previous log, I have deleted the temp file then redownload.
But even if I start with a clean state, It still get stuck
Log here:
[tdlib.log](https://github.com/user-attachments/files/18028715/tdlib.log)

**Comment by levlam** [comment]
I pushed fixes for the issue, but as `getRemoteFile` documentation states, your approach isn't guaranteed to work anyway "with a clean state":
> Even the request succeeds, the file can be used only if it is still accessible to the user. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application

**Comment by cdxf** [comment]
When I tried to rebuild TD, I encountered the following build error (even though the build continued). I will report whether the fix works later.

> PartsManager.cpp
> D:\project\td\td\telegram\files\PartsManager.cpp(436,29): error C2672: 'td::min': no matching overloaded function found
>  [D:\project\td\build\tdcore.vcxproj]
>   ResourceManager.cpp
>   D:\project\td\tdutils\td\utils\common.h(109,3):
>   could be 'T td::min(T,T)'
>         D:\project\td\td\telegram\files\PartsManager.cpp(436,29):
>         'T td::min(T,T)': template parameter 'T' is ambiguous
>                 D:\project\td\td\telegram\files\PartsManager.cpp(436,29):
>                 could be 'td::int64'
>                 D:\project\td\td\telegram\files\PartsManager.cpp(436,29):
>                 or       'size_t'
>         D:\project\td\td\telegram\files\PartsManager.cpp(436,29):
>         'T td::min(T,T)': could not deduce template argument for 'T' from 'const td::int64'
> 
> D:\project\td\td\telegram\files\PartsManager.cpp(440,31): error C2672: 'td::min': no matching overloaded function found
>  [D:\project\td\build\tdcore.vcxproj]
>   D:\project\td\tdutils\td\utils\common.h(109,3):
>   could be 'T td::min(T,T)'
>         D:\project\td\td\telegram\files\PartsManager.cpp(440,31):
>         'T td::min(T,T)': template parameter 'T' is ambiguous
>                 D:\project\td\td\telegram\files\PartsManager.cpp(440,31):
>                 could be 'td::int64'
>                 D:\project\td\td\telegram\files\PartsManager.cpp(440,31):
>                 or       'size_t'
>         D:\project\td\td\telegram\files\PartsManager.cpp(440,31):
>         'T td::min(T,T)': could not deduce template argument for 'T' from 'const td::int64'
> 
> D:\project\td\td\telegram\files\PartsManager.cpp(444,26): error C2672: 'td::min': no matching overloaded function found
>  [D:\project\td\build\tdcore.vcxproj]
>   D:\project\td\tdutils\td\utils\common.h(109,3):
>   could be 'T td::min(T,T)'
>         D:\project\td\td\telegram\files\PartsManager.cpp(444,26):
>         'T td::min(T,T)': template parameter 'T' is ambiguous
>                 D:\project\td\td\telegram\files\PartsManager.cpp(444,26):
>                 could be 'td::int64'
>                 D:\project\td\td\telegram\files\PartsManager.cpp(444,26):
>                 or       'size_t'
>         D:\project\td\td\telegram\files\PartsManager.cpp(444,26):
>         'T td::min(T,T)': could not deduce template argument for 'T' from 'const td::int64'

**Comment by cdxf** [comment]
I rebuild the Java example project, get error when run this cmd:

> cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) ..
> **cmake --build . --target install --config Release**


> D:\project\td\example\java\td_jni.cpp(201,16): error C2039: 'get_static_field_id': is not a member of 'td::jni' [D:\pro
> ject\td\example\java\build\tdjni.vcxproj]
>   D:\project\td\example\java\td\include\td\tl\tl_jni_object.h(23,11):
>   see declaration of 'td::jni'
> 
> D:\project\td\example\java\td_jni.cpp(201,16): error C3861: 'get_static_field_id': identifier not found [D:\project\td\
> example\java\build\tdjni.vcxproj]
> D:\project\td\example\java\td_jni.cpp(202,41): error C2039: 'fetch_static_string': is not a member of 'td::jni' [D:\pro
> ject\td\example\java\build\tdjni.vcxproj]
>   D:\project\td\example\java\td\include\td\tl\tl_jni_object.h(23,11):
>   see declaration of 'td::jni'
> 
> D:\project\td\example\java\td_jni.cpp(202,41): error C3861: 'fetch_static_string': identifier not found [D:\project\td\
> example\java\build\tdjni.vcxproj]
> D:\project\td\example\java\td_jni.cpp(203,43): error C2039: 'get_git_commit_hash': is not a member of 'td::td_api' [D:\
> project\td\example\java\build\tdjni.vcxproj]

**Comment by levlam** [comment]
Thank you. I has just pushed a fix for the compilation error.
