### ISSUE TITLE
How to send the user profile photo in a message?

### ISSUE THREAD

**Issue by skygate2012** [tdlib/td#3172]
I tried to pass user.profile_photo.small.remote.id as the inputFileRemote.id and it says `Can't use file of type ChatPhoto as Photo`.

**Comment by levlam** [comment]
That's correct. You must use an identifier from `Photo` object. You can find one in `userFullInfo`.

**Comment by skygate2012** [comment]
I looked at the userFullInfo class but there are also all ChatPhoto objects?

**Comment by skygate2012** [comment]
Thanks I figured it out :) It's userInfo.photo.sizes[0].photo.remote.id
