### ISSUE TITLE
How to get the background color for a default profile photo for users without one?

### ISSUE THREAD

**Issue by skygate2012** [tdlib/td#3177]
There is a `profile_accent_color_id` field under the `user` class. But from the description it seems that this is a custom color premium users instead of the default color? If so, which api should one use to get the default color? If there is no such api, can you share the algorithm for generating the color? I see that it is consistent across the official clients.

**Comment by levlam** [comment]
Use `user.accent_color_id`: "Identifier of the accent color for ... backgrounds of profile photo ..".
The note "For Telegram Premium users only" in the documentation is redundant and will be removed.

**Comment by skygate2012** [comment]
Thank you I was confused about that word.
