### ISSUE TITLE
JAVA - How to get all members of a chat?

### ISSUE THREAD

**Issue by timonNo1** [tdlib/td#318]
Hi,

I have the chatId of the chat of which I want to get all members. After that I want to filter these members depending on their inactivity.

How would I do that? I can't find a function to get users of a specific group chat.

**Comment by levlam** [comment]
Getting of chat members is different for basic groups and supergroups. For basic groups you need to use getBasicGroupFullInfo. For supergroups you need to use getSupergroupMembers.

**Comment by timbierenbreier** [comment]
Okay thank you, I got that.

How can I check if a member is inactive? In this data I can't find any attributes like lastSeen or similar.

`ChatMember {
      userId = 619671961
      inviterUserId = 0
      joinedChatDate = 1531100316
      status = ChatMemberStatusMember {
      }
      botInfo = null
}

UserFullInfo {
  isBlocked = false
  canBeCalled = false
  hasPrivateCalls = false
  bio = ""
  shareText = ""
  groupInCommonCount = 0
  botInfo = null
}`

**Comment by husanov98** [comment]
> Getting of chat members is different for basic groups and supergroups. For basic groups you need to use getBasicGroupFullInfo. For supergroups you need to use getSupergroupMembers.

I got super group id using GetChats and I tried many times to get ChatMembers with getSupergroupMembers from super group which I am member of it but occured  supergroup not foud error. I checked group is super group.

**Comment by levlam** [comment]
@husanov98 

Check taht you don't confuse `chat_id` and `supergroup_id` and you received the identifier from TDLib after instance restart and it isn't hardcoded.

**Comment by husanov98** [comment]
which id should I use chat_id or supergroup_id?

**Comment by levlam** [comment]
See documentation of the used method.
