### ISSUE TITLE
build-tdlib.sh: CMake Error at /mnt/c/Users/egmon/CMakeLists.txt:48 (add_subdirectory)

### ISSUE THREAD

**Issue by egmontr** [tdlib/td#3182]
I am working on WSL2 with Ubuntu 24.04.

When I am starting the last script build-tdlib.sh I am getting the following error:

> ubuntu@egilaptop:/mnt/c/Users/egmon/Downloads/tdlib_compile$ ./build-tdlib.sh
> Generating TDLib source files...
> -- The CXX compiler identification is Clang 18.1.3
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at /mnt/c/Users/egmon/CMakeLists.txt:48 (add_subdirectory):
>   The source directory
> 
>     /mnt/c
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at CMakeLists.txt:67 (add_custom_target):
>   add_custom_target cannot create target "tl_generate_java" because another
>   target with the same name already exists.  The existing target is a custom
>   target created in source directory "/mnt/c/Users/egmon".  See documentation
>   for policy CMP0002 for more details.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/mnt/c/Users/egmon/Downloads/tdlib_compile/build-native-Java/CMakeFiles/CMakeOutput.log". 
> 

So I searched for an existing  "tl_generate_java", but didn't find it. Also CMakeLists.txt ist there.
What could the error be?

**Comment by levlam** [comment]
You must run all scripts from the directory in which they are located.

**Comment by egmontr** [comment]
I did that. I started all scripts from the same directory.

**Comment by levlam** [comment]
You run it from the directory `/mnt/c/Users/egmon/Downloads/tdlib_compile`, but the script is located in `td/example/android`. You must not move scripts to other location.

**Comment by egmontr** [comment]
Indeed. I only copied the scripts and not the whole project. 
I'll try again and come back to report.

**Comment by egmontr** [comment]
It has worked now. Sorry for my dumb questions and thanks for help.

**Comment by egmontr** [comment]
Closed
