### ISSUE TITLE
How to determine the time point when messages can be sent to a bot or channel

### ISSUE THREAD

**Issue by jnxyatmjx** [tdlib/td#3194]
I use tdlib api send messages to myself bot or channel or group. but sometimes catch "Chat not found" error.
my question is  how to determine the point i can send message to myself bot?

**Comment by jnxyatmjx** [comment]
ufter get "updateChatAddedToList" message?

**Comment by levlam** [comment]
You must receive the chat from TDLib to be able to use it. You can do this in any way you would do that in a Telegram app.

**Comment by jnxyatmjx** [comment]
> You must receive the chat from TDLib to be able to use it. You can do this in any way you would do that in a Telegram app.

would you show me more details?

**Comment by levlam** [comment]
There are too many methods to get chats. Just use whatever you would have used in the app.
