### ISSUE TITLE
documentation for td/jnibuild/td/generate/td_generate_java_api

### ISSUE THREAD

**Issue by TunifyBasic** [tdlib/td#3198]
where can i find documentation about this command or how to use it to generate the td_api.cpp.

**Comment by levlam** [comment]
You need to use https://tdlib.github.io/td/build.html to get complete build instructions, which can use the utility.

**Comment by TunifyBasic** [comment]
yes i got a complete build but i wan't to generate a c contains the jni binding so i could compile it and have something like the once in example/java/.../TdApi.java and td_jni.cpp i copied them but is there any better way than coping them into our directory?

**Comment by levlam** [comment]
You must copy the files built along with libtdjni.so.

**Comment by TunifyBasic** [comment]
libtdjni.so built with predefined -DPACKAGE_NAME and set to the java app package (drinkless) i am just asking how to generate this td_jni.cpp.
```
~/td/example/java $ ls
CMakeLists.txt  README.md  build  org  td  td_jni.cpp
```

**Comment by levlam** [comment]
The Java files and libtdjni.so must be compatible. You can't generate them separately. `td_jni.cpp` isn't generated. It is a manually created file.

**Comment by TunifyBasic** [comment]
alright thanks
