### ISSUE TITLE
Possible to have multiple executables share a binlog for TDLib?

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#3199]
Background: in iOS/watchOS etc, often, Siri intents, notifications are handled as separate app extensions, which are basically separate executables that are bundled along the main app. For example, when handling newly received notifications, it is not possible to get data from the main app, or to call TDLib functions or receive TDLib updates from the main app to be used in these app extensions.

Wanted to explore **_wild_** new ways to enhance notifications handling, such as by directly requesting from TDLib, within the app extension. (e.g. to get image without the use of `attachb64` as discussed in the past as impossible, rather to get image by getting the message directly)

Assuming the main app is in background state, would it be safe or possible if:
1. binlog exists in a shared directory that can be accessed by both the main app and its app extensions; to start a new TDLib client instance in the app extension, without database and to be closed immediately once things are done
2. an older binlog periodically copied from the main app to the shared directory; to start a new TDLib client instance in the app extension, without database and to be closed immediately once things are done

Regardless, happy holidays!

**Comment by levlam** [comment]
It is not possible to share the same binlog by multiple executables. Moreover, it is not possible to use data from the same binlog by multiple executables concurrently to send network requests.

Binlog copying also will not work and has unpredictable effects on consistency and interaction with the server.

**Comment by vincentneo** [comment]
Alright got it. Thank you.
