### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by Aex12** [tdlib/td#32]
Whenever I try to compile this lib it always fails at CallActor.cpp.o 

[ 34%] Building CXX object CMakeFiles/tdcore.dir/td/telegram/CallActor.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/tdcore.dir/build.make:374: recipe for target 'CMakeFiles/tdcore.dir/td/telegram/CallActor.cpp.o' failed
make[2]: *** [CMakeFiles/tdcore.dir/td/telegram/CallActor.cpp.o] Error 4
CMakeFiles/Makefile2:155: recipe for target 'CMakeFiles/tdcore.dir/all' failed
make[1]: *** [CMakeFiles/tdcore.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by levlam** [comment]
1. What compiler do you use?
2. What OS do you use?
3. How much RAM do you have?
4. What command do you use to build TDLib?

**Comment by Aex12** [comment]
The error was I didnt have enough ram (just 1gb), compiled it on another machine with more ram and worked.

Now I'm facing another issue, will close this and open a new issue.
