### ISSUE TITLE
Verification code

### ISSUE THREAD

**Issue by rgarciaotc** [tdlib/td#321]
Hi, I'm using this library on a project and I have a problem. Every X time (it can be 1 hour, 4 hours or a day) Telegram sends me a new verification code. Is there any way to have this code automatically renewed or renewed in background?
Why do you ask me for the code from time to time? 

Thank you

**Comment by levlam** [comment]
Verification code is sent only during account authorization. It isn't resent unless the account isn't logged out by explicit call to logOut or destroy or by deleting the local database.

**Comment by rgarciaotc** [comment]
Thank you. It seems to be working.
