### ISSUE TITLE
ReplyMarkup, inlineKeyboard. how to send reply?

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#322]
Hello!

ReplyMarkup, inlineKeyboard. how to send reply after clicking on inline button?

**Comment by levlam** [comment]
`getCallbackQueryAnswer`?

**Comment by blacksailer** [comment]
Thanks!

**Comment by rnyPlanet** [comment]
> `getCallbackQueryAnswer`?
maybe u know how to send reply on ReplyKeyboardMarkup?
https://github.com/tdlib/td/issues/1135 I have this error ((
