### ISSUE TITLE
Kotlin-JVM and Kotlin/Native (for iOS) Support

### ISSUE THREAD

**Issue by joelhandwell** [tdlib/td#326]
For Mobile crossplatform development, [Kotlin language](https://kotlinlang.org) and this library seems good fit because [Kotlin/Native](https://kotlinlang.org/docs/reference/native-overview.html) provides interoperability with C language functions. Defining Kotlin Common interface based on existing Java interface and using ```expect``` declaration and implement it with ```actual``` declaration for both Android and iOS can improve the ease of development. Can Kotlin be considered as scope this library?

**Comment by levlam** [comment]
TDLib can be used from almost any programming language, including Kotlin. See for example, https://github.com/osmandapp/Osmand/blob/1ddb1a76fdab1c3c8f9387bbc94db17b2f7055c9/OsmAnd-telegram/src/net/osmand/telegram/helpers/TelegramHelper.kt.

**Comment by levlam** [comment]
I think that wrappers for particular programming languages are better written by programmers experienced in that language. If there will be such wrapper written in Kotlin, I will be glad to add link to it to examples.

**Comment by joelhandwell** [comment]
@levlam thanks for the clarification. I think it's clear enough to close this issue.

**Comment by g000sha256** [comment]
@joelhandwell, you can try [TDL Coroutines](https://github.com/g000sha256/tdl-coroutines)
