### ISSUE TITLE
Using javac -h instead of javah for JDK10+

### ISSUE THREAD

**Issue by backtozero** [tdlib/td#327]
`javah` was deprecated in java10, so it would be great to eliminate the usage of `javah`.
`javac -h` is equivalent to `javah` and is available from JDK8.

I suppose there is no need to support any JDK less than 1.8.

**Comment by levlam** [comment]
We don't use javah at all. Where did you find it?

**Comment by backtozero** [comment]
When i tried to launch one of this:

```
cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=<full path to TDLib sources>/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. ..
cmake --build . --target install
```

It particularly gave me the error something like **JAVAH_**SOMETHING.
I fixed it by adding JDK8/bin to $PATH.

Will reproduce it later.

**Comment by levlam** [comment]
It is a CMake [issue](https://gitlab.kitware.com/cmake/cmake/issues/17613). It seems that Java 10 was supported in CMake 3.12.0.
