### ISSUE TITLE
get contacts list

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#328]
hi I use tdlib in java and I want to get the contacts list
I see the ImportedContacts object but which function returns this object.
I see the GetImportedContactCount function but its returns only count.

**Comment by levlam** [comment]
You need [searchContacts](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1search_contacts.html).

**Comment by sadeghpro** [comment]
tnx @levlam 
I use this code:
```
client.send(new TdApi.SearchContacts(),object -> {
                        switch (object.getConstructor()) {
                            case TdApi.Users.CONSTRUCTOR:
                                TdApi.Users users = ((TdApi.Users) object);
                                System.out.println(users.totalCount);
                                System.out.println(users.userIds.length);
                                break;

                            default:
                                System.out.println("Receive wrong response from TDLib:" + newLine + object+ newLine+object.getClass());
                        }
                    });
```
this is object return:
```
Users {
  totalCount = 2
  userIds = Array[0] {
  }
}
```
why userIds is empty

**Comment by levlam** [comment]
Because you have specified limit == 0 in the SearchContacts request.

**Comment by sadeghpro** [comment]
tnx @levlam    
this is a stupid mistake from me

**Comment by levlam** [comment]
In TDLib 1.3.0 you can also use `getContacts` instead of `searchContacts` to get all contacts.
