### ISSUE TITLE
Java/Android interface: some updates may be lost

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#332]
TDLib misses each `Client.MAX_EVENTS + 1` event in java interface. This may happen in rare cases when some `onResult` takes too much time and there are many updates from TDLib arrived.

This can be reproduced, for example, by putting `Thread.sleep` with 5-10 seconds delay in `updatesHandler`. Constantly restarting and calling `getChats` may result, for example, in receiving `updateLastMessage` without prior `updateNewChat`.

From client side this may result in missing chats or other undefined behaviors because of data loss.

Since `MAX_EVENTS` is set to `1000` for now, such updates loss happen very rarely even if `onResult` takes pretty much time, however, on low-end devices it seems to happen much more often.

**Comment by levlam** [comment]
Thanks. It will be fixed in 1.3.0.

**Comment by 0823969789** [comment]
@levlam
