### ISSUE TITLE
TDLib max thread count 256

### ISSUE THREAD

**Issue by bobrovde** [tdlib/td#333]
Hello!
At the moment  it's nearly 130-140 accounts run simultaneously on my golang application, when i try to create one more tdclient I get next error `[ 0][t 0][1533122648.990930796][ThreadIdGuard.cpp:27]	Cannot create more than 256 threads`. From documentation:  

> each TDLib instance handles more than 19000 active bots simultaneously

Can you tell me, did i get something wrong or it is problem with OS? 
Golang application run in docker container on Debian 9.

**Comment by levlam** [comment]
Bot API uses low-level TDLib interface ClientActor, available only from C++, and runs all bots on the same 4 threads using it.

This restriction on number of threads, which affects high-level interfaces, will be removed in TDLib 1.3.0, which is planned to be released soon.

**Comment by bobrovde** [comment]
ok, wait for it :)

Thank you!

**Comment by levlam** [comment]
This restriction was removed in TDLib 1.3.0.
