### ISSUE TITLE
internal compiler error:  Killed (program cc1plus)

### ISSUE THREAD

**Issue by samyrooster** [tdlib/td#334]
Hi,
I wanna compile the [github.com/vysheng/tdbot](https://github.com/vysheng/tdbot) , but it returns error on 60% process:

[ 58%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/ConfigManager.cpp.o
[ 60%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/ConfigShared.cpp.o
[ 60%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/Contact.cpp.o
[ 60%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
td/CMakeFiles/tdcore.dir/build.make:590: recipe for target 'td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o' failed
make[3]: *** [td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o] Error 4
CMakeFiles/Makefile2:378: recipe for target 'td/CMakeFiles/tdcore.dir/all' failed
make[2]: *** [td/CMakeFiles/tdcore.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:164: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2

OS: Ubuntu 17.10 x86_64
RAM: 2 GB

![2018-08-04_212327](https://user-images.githubusercontent.com/20831792/43679167-ce8fb41c-9835-11e8-9630-7a456c1f992c.jpg)

**Comment by levlam** [comment]
gcc needs at least 6 GB of RAM to compile TDLib. You can use clang instead, which needs less than 2 GB.

**Comment by jk-1** [comment]
How do I configure cmake to use clang?

**Comment by levlam** [comment]
For Ubuntu: https://stackoverflow.com/a/12843988.
Or you can try to run `CXX=clang++ CC=clang cmake ..`.

**Comment by levlam** [comment]
Please note that you need to delete the whole build directory and recreate it to be able to change compiler.

**Comment by kossnocorp** [comment]
> gcc needs at least 6 GB of RAM to compile TDLib. You can use clang instead, which needs less than 2 GB.

I'm actually managed to build TDLib on 4Gb RAM machine, so I feel that the requirement might be a bit lower than that.

**Comment by levlam** [comment]
@kossnocorp I've tested recently with GCC 4.9.2 and it used 5.5 GB RAM at the peak. I've rounded it up to 6 GB to make the comment correct for the next few months.

**Comment by kossnocorp** [comment]
I see, probably my results were affected by the virtual memory although I'm not sure how it actually works.

**Comment by levlam** [comment]
TDLib 1.4.0 includes a lot of compilation memory usage optimizations and a new script `SplitSource.php`, which can be used to split some source code files before building the library to reduce maximum RAM usage per file at the expense of increased build time. In our tests clang 6.0 with libc++ required less than 500 MB of RAM per file and GCC 4.9/6.3 used less than 1 GB of RAM per file.

**Comment by kossnocorp** [comment]
@levlam that sounds amazing, great work! Is there are extra steps to make it work on 1Gb RAM?

**Comment by levlam** [comment]
@kossnocorp See [building](https://github.com/tdlib/td/blob/master/README.md#building) or a [TDLib build instructions generator](https://tdlib.github.io/td/build.html).

**Comment by kossnocorp** [comment]
@levlam thanks!

**Comment by maxtronic** [comment]
![image](https://user-images.githubusercontent.com/21298969/88839712-0a3e0d00-d1a1-11ea-9ed9-6b5d554046c4.png)
me mandaron a este llink http://raspberrypimaker.com/adding-swap-to-the-raspberrypi/ , cambie a 1024, pero aun persiste error , ahora probaré con un usb externo...

**Comment by levlam** [comment]
@maxtronic Do not try to build using 4 threads. Use clang and SplitSource.php before building as described in https://github.com/tdlib/td#building.

**Comment by buidangdanh** [comment]
help me
![image](https://user-images.githubusercontent.com/84194706/120426289-015a3100-c39a-11eb-8212-6e1a5ce43ab3.png)

**Comment by bearmingo** [comment]
limit make paralel number to little, eg `make -j4`

**Comment by mbuguasamuelwambui** [comment]
Writing HLS project(help me fix this error as i am using hls4ml)

Done
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: error: myproject.o: No such file or directory
Traceback (most recent call last):
  File "/home/sam/Documents/cancer/con.py", line 14, in <module>
    hls_model.compile()
  File "/home/sam/anaconda3/envs/hls4ml_env/lib/python3.11/site-packages/hls4ml/model/graph.py", line 662, in compile
    self._compile()
  File "/home/sam/anaconda3/envs/hls4ml_env/lib/python3.11/site-packages/hls4ml/model/graph.py", line 681, in _compile
    self._top_function_lib = ctypes.cdll.LoadLibrary(lib_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/anaconda3/envs/hls4ml_env/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sam/anaconda3/envs/hls4ml_env/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: my-hls-test/firmware/myproject-F11E53B9.so: cannot open shared object file: No such file or directory
