### ISSUE TITLE
Delete secret chat (closeSecretChat)

### ISSUE THREAD

**Issue by ionwerz** [tdlib/td#337]
How to delete secret chat? 
This command is not working:
`"@type":"closeSecretChat","chat_id":-2001087041572`
So, if I try as chat_id parameter from "id":
`"@type":"updateNewChat","chat":{"@type":"chat","id":-2001087041572`
I get response:
`{"@type":"ok"}`
but it do nothing. If I try to use real secret chat id from:  
`"@type":"chatTypeSecret","secret_chat_id":-1087041572`
I get the same response:
`{"@type":"ok"}`
and there is no reaction, secret chat still exist. So how to do that correctly?

**Comment by levlam** [comment]
`closeSecretChat` parameter is `secret_chat_id`, so the second request is correct. The secret chat state should be `secretChatStateClosed` after that, you will not be able to write to the chat anymore. If you want to additionally remove it from the chat list and delete all messages, you need to call `deleteChatHistory` with `remove_from_chat_list` set to `true`.

**Comment by ionwerz** [comment]
When I try to execute this: 
`"@type":"deleteChatHistory","chat_id":-2001087041572,"remove_from_chat_list":1`
I get that response:
```
{"@type":"updateChatReadInbox","chat_id":-2001087041572,"last_read_inbox_message_id":4194304,"unread_count":0}
{"@type":"updateChatLastMessage","chat_id":-2001087041572,"order":"0"}
{"@type":"updateDeleteMessages","chat_id":-2001087041572,"message_ids":[4194304],"is_permanent":true,"from_cache":false}
{"@type":"ok"}
```
And chat still exist in TDlib and on peer (Telegram for Android) too.

**Comment by levlam** [comment]
The chat is removed from the chat list. You and your peer shouldn't be able to send messages there after call to `closeSecretChat` succeeds. Messages aren't deleted automatically on peer side if a secret chat is closed. You need to first call `deleteChatHistory` and call `closeSecretChat` only after messages are deleted on the other site.

**Comment by ionwerz** [comment]
Unfortunately I'm still able to send and receive messages even after `deleteChatHistory` and `closeSecretChat`. Tell me please `closeSecretChat` it is the same as `Delete Chat` in official telegram client for android? If yes, maybe this is issue of Lua Wrapper that I'm using for TDlib.

**Comment by levlam** [comment]
`Delete Chat` for secret chats is `closeSecretChat` + `deleteChatHistory`. Are you sure that you pass a correct `secret_chat_id`? Because if `secret_chat_id` was correct, TDLib will not allow you to write to the secret chat after `closeSecretChat` has returned `Ok`. Could you collect TDLib DEBUG log with call to `closeSecretChat` and sending message to the chat after that and send it to @tdlib_bot?

**Comment by ionwerz** [comment]
Done, have send all debug info to @tdlib_bot

**Comment by ionwerz** [comment]
levlam, you was right. I was mistaking and have send wrong parameter in `closeSecretChat`, it was `chat_id` and should be `secret_chat_id`
