### ISSUE TITLE
Getting PEER_FLOOD Error by adding users to group

### ISSUE THREAD

**Issue by timonNo1** [tdlib/td#338]
My program is searching users with specifics from a group and adds them to another group. After like 50 users added I can't add anymore and getting the error "PEER_FLOOD" as result.
I have already tried to wait 2 minutes after every added user but still after ~50 users i am getting this error. After this I can't add anyone at all for a day or something. But I can still make requests like getUser().

What exactly are the limits? How can I avoid being markes as spam? How many users in what time period am I allowed to add?

**Comment by levlam** [comment]
You are unallowed to add random users to groups against their will, so the effective limit is 0. Short spikes are allowed, but if invited people will mark you and your chat as spam, you will not be able to invite more people and your account can be spam-blocked. If these people want to join the group, then you can send them invite link and they will join it themselves. 
Anyway, it isn't a question or issue concerning TDLib.

**Comment by timbierenbreier** [comment]
Mhhh i am pretty sure that getting the PEER_FLOOD error is not due to being marked as spam manually. It has to be a mechanism which does it when you reach a limit. Are you sure?
