### ISSUE TITLE
Java CMake error: Could NOT find JNI

### ISSUE THREAD

**Issue by gjkf** [tdlib/td#339]
I cloned the Github repo, `git clone https://github.com/tdlib/td.git`
I moved into it, created the `jnibuild` directory and moved into it again. I then ran `cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..`
[This](https://hastebin.com/huvuzoposa.sql) was the output. [This](https://hastebin.com/lihekucuxo.bash) is the `CMakeError.log` file.

I have tried multiple times and with no success. Running `java -version` i have
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
I can't understand what the error would be, considering that if I have Java I expect to have JNI too.

**Comment by levlam** [comment]
Java 10 support was added to FindJNI CMake module since CMake 3.11.0. You need to update CMake to 3.11 or alternatively you can manually update `/usr/share/cmake-3.10/Modules/FindJNI.cmake` to the latest version https://github.com/Kitware/CMake/blob/master/Modules/FindJNI.cmake.

**Comment by gjkf** [comment]
That seems to have fixed it, thanks for the help.
I also noticed that adding `-DBUILD_SHARED_LIBS=OFF` seems to help, it found the JNI with no problems. Why is that?

**Comment by levlam** [comment]
`BUILD_SHARED_LIBS` shouldn't fix anything. Especially, `BUILD_SHARED_LIBS=OFF`, because it is OFF by default.
