### ISSUE TITLE
JAVA how to remove member form supergroup

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#344]
hi
what is a function of remove member form supergroups, basicgroups, and channels

**Comment by sadeghpro** [comment]
tnx @levlam I check it tomorrow

**Comment by sadeghpro** [comment]
tnx @levlam  it's work but when you not the administrator of supergroup the error is 
```
Error {
  code = 6
  message = "User not found"
}
```

**Comment by levlam** [comment]
"User not found" error isn't related to being a group administrator. You need to load from somewhere information about the user first. For example, if you have enabled chat_info_database and have seen the user somewhere on previous application launch, you can use `getUser` for that. Or you can use `searchChatMembers` or `getSupergroupMembers` to get the user from the server.
