### ISSUE TITLE
Waveform

### ISSUE THREAD

**Issue by leoMehlig** [tdlib/td#346]
Hi, how to I parse or render the waveform of a voice note. I get a string like this (`AQQAgDjruQZjZM7BttxqjqV0AgghhAAAAMAc5aCcETrGGmPPJSQAAAAMIUIAwqQGn3OOhABCAAEMEQIAQoQA`) from tdlib.
Thanks

**Comment by levlam** [comment]
You need to base64-decode it and split resulting binary string in groups of 5 bits. Each group will encode a height of corresponding bar.

**Comment by leoMehlig** [comment]
Thanks I solved it.

**Comment by thebootroo** [comment]
The TDlib doc says nothing about how to encode and decode waveform,
so OK, it is 5 bits bars, but how many of them ?
is the bar count fixed or completely dynamic ? 
how are they computed when we send the voice note ?
couldn't TDlib have a parse method like for text entities, we pass a WAV file and it returns the waveform base64 ?
Thanks in advance.

**Comment by levlam** [comment]
Usually, there are 100 bars, but it isn't guaranteed. It depends on the client, which sent the voice message. 

You can find example of waveform computation in source code of official Telegram clients, for example, [there](https://github.com/DrKLO/Telegram/blob/e222fded6cca5ace3649be6f18b55f526311bc79/TMessagesProj/jni/audio.c#L603).

TDLib will need to depend on libopus and/or other audio libraries to calculate a waveform. Such dependence will make much harder to build and use TDLib and can lead to executable size blow up, so we prefer to leave this calculation for application developer. For voice notes less than 1MB calculation of waveform can be done server-side, so it will work most of the time even without client implementation.
