### ISSUE TITLE
Cannot load/include TdTarget.cmake

### ISSUE THREAD

**Issue by MaxiGH** [tdlib/td#347]
Hallo again, I rearranged that project and have some new issues. I want to compile that project for Java x64 on Windows.

So what I am doing, is 2 steps for building. First: Build jnibuild:

`cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td .. -A x64 -DCMAKE_TOOLCHAIN_FILE=<VCPKG_DIR>/scripts/buildsystems/vcpkg.cmake`

and after cmake configuration:

`cmake --build . --target install --config Release`

Now I go into /example/java/build:

`cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=<full path to TDLib sources>/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. .. -A x64 -DCMAKE_TOOLCHAIN_FILE=<VCPKG_DIR>/scripts/buildsystems/vcpkg.cmake`

then I get a note in the progress, 

CMake Error at C:/Users/Maxi/Desktop/td/TdConfig.cmake:3 (include):
include could not find load file:

C:/Users/Maxi/Desktop/td/TdTargets.cmake
Call Stack (most recent call first):
CMakeLists.txt:5 (find_package)

I tried to search for that file and found two, one in td/jnibuild and the other one somewhere in the java directory. I tried to copy both, but it ended with weird file include path errors. So I guess these files are not to be meant to use.

after that I assume to finish building process with:

`cmake --build . --target install --config Release`

I guess using the vcpkg toolchain file for both cmake parts (jnibuild and java/build) is right. I also use -A x64 in both lines.  If it would work, I would have used the same `cmake --build` command than before. Is that a correct assumption? I don't get what I'm missing, for jnibuild everything looked fine. Can you help me out?

**Comment by MaxiGH** [comment]
I started all over again and it worked surprisingly. I think I changed nothing during the second try, but okay.  :)

**Comment by levlam** [comment]
There should be no TdTargets.cmake in `td/` directory. Possibly it has left from previous tries and has interfered with building.

**Comment by deni2312** [comment]
Okay thanks It works now!

**Comment by sophieonfire** [comment]
@MaxiGH Hey. U solved that Problem??? Are you german? =)
