### ISSUE TITLE
Data center redirect. and network delay for text messages

### ISSUE THREAD

**Issue by pabx06** [tdlib/td#348]
i have been reading.
https://core.telegram.org/api/datacenter#testing-redirects

Since i use tdlib to process event on channel mainly on the DC 5 .

But my client connect seems to connect on DC4.  and can have **delay as much as 55 sec** for simple text message.

i said why not use phone number 99966XYYY with td_example. To test redirect...

```
./td/example/cpp/build/td_example
Enter phone number: 9996651111
Enter your first name: john
Enter your last name: malcovitch
Enter authentication code: 55555
Error: error {
  code = 400
  message = "PHONE_CODE_INVALID"
}
```
Phone prefix redirect  didn't  work.  
My questions : 

1) may i run a second TDLib app on a foreign cloud near the foreign DC ? or i am stuck  because my android app is geo-located near a local DC ?

2)Cloud changing database prams improve speed ?

```
auto parameters = td_api::make_object<td_api::tdlibParameters>();
                                       parameters->database_directory_ = "tdlib";
                                       parameters->use_message_database_ = true;
                                       parameters->use_chat_info_database_ =true;
                                       parameters->ignore_file_names_ = false;
                                       parameters->use_secret_chats_ = true;
                                       parameters->api_id_ = 00000000000000;
                                       parameters->api_hash_ = "BBBBBBBBBBBBBBBBBBBBBBBBBB";
                                       parameters->system_language_code_ = "en";
                                       parameters->device_model_ = "Desktop";
                                       parameters->system_version_ = "Unknown";
                                       parameters->application_version_ = "1.0";
                                       parameters->enable_storage_optimizer_ = true;
                                       send_query(td_api::make_object<td_api::setTdlibParameters>(std::move(parameters)),
                                                  create_authentication_query_handler());
```

NB: tdLib does work fast when channel and app are on the same DC but intra DC com makes it as slow as email.

**Comment by levlam** [comment]
0) Phone numbers 99966XYYY can be used only in test DC. You need to set use_test_dc to true in tdlibParameters to be able to use them.
1) Each user is assigned to unique DC and can receive updates only from that DC. There is no way to change the DC. If creator of the channel is from DC5, then new message needs to go to DC5, then to DC4 and then to you. DC5 is pretty far from DC4, so there is no way to receive update faster then in few hundred milliseconds.
2) They shouldn't make any difference for speed of updates receiving.

**Comment by pabx06** [comment]
I appreciate the clarification.

i also find strange that message arrive 10 sec faster when i am far from DC. see pictures.


![image](https://user-images.githubusercontent.com/4013370/44852860-a2a17f00-ac64-11e8-9bb9-bbe92b083cc4.png)

**Comment by levlam** [comment]
Ping doesn't matter in that case at all, because it is very small compared to message delivery time. Here delay depends mostly on number of channel members, all of which needs to receive new message.

**Comment by pabx06** [comment]
The same app td_example  same Telegrame DC, same telegram phone number.
Running on two different amazon EC2 cloud instance on same regions,same aviability zone with the same clock time:
For the same message of the same channel:
- 1) t2.micro : 1 core 1GB RAM , **1 Gigabit** network bandwidth , took  **11sec**
- 2) m5.24xlarge: 96 cores 300GB RAM , **25 Gigabit** network bandwidth ,took **51sec**
that is getting  slow for real time messaging .

I use date field from message compared to local machine time.
but some times the 96 cores instance get the message first.

- 1)Message ordering is wrong btw the two instances unless filtered by channel. 
- 2)not sure but look like some messages only appears on just one instance.
i realy would like to see a sub 10 sec messaging. but i dont know how to make it happens...

**Comment by levlam** [comment]
Any instance characteristics are irrelevant on such big delays. It completely depends on member count of the channel and a time when server will be able to send an update to client. Channels can have millions of subscribers, so some delay in message delivery is expected.

1) There is no any guarantees on message ordering between message from different supergroup/channels. There is no way such guarantees can be provided.
2) Any message should eventually appear on all instances.

If you need to faster get updates from just one channel, you can use `openChat` on it.

**Comment by pabx06** [comment]
Learned my lesson
1)I am now super near the correct DC. i am Registered with the same DC of the chat channel.
2)i use openChat
```
	void open_chat(std::int64_t 	my_chat_id_) {
		send_query(td::td_api::make_object<td::td_api::openChat>(my_chat_id_),
		[this](Object object) {
			if (object->get_id() == td_api::error::ID) {
				return;
			}
			else {
				std::cerr << "The  Chat has been opened" << std::endl;
			}
		});
	}
```

![image](https://user-images.githubusercontent.com/4013370/44982004-a0953400-af74-11e8-82f2-5b62caef0f77.png)

3) Message **took 41 sec** to make it's ways.

i have no clue on how to fix that.

**Comment by levlam** [comment]
Could you tell how much members are in the channel and whether you are channel admin or an ordinary member?

**Comment by pabx06** [comment]
normal user account with 100K members

**Comment by mvgx** [comment]
@pabx06  did you find the solution? I met the same problem
Running official client and tdlib C++ example on the same machine (Amazom vps), same Telegram account I noticed that:
1) tdlib messages **always** come later
2) the daly varies from 10ms up to **60 seconds!!**

**Comment by levlam** [comment]
Probably, the reason of slower channel messages arrival is that sometimes updates about new channel messages are delivered only with the answers to another queries. The only thing I could suggest is to set the option "online" value to true, so the server knows that the client is online and sends updates more often.

If you still experience the issue, you can help us to investigate it further by providing relevant application logs, but I don't expect a presence of a bug there.
