### ISSUE TITLE
Fat Jar with Intellij Maven Project (JAVA)

### ISSUE THREAD

**Issue by MaxiGH** [tdlib/td#349]
Hey guys, I already performed a successful running of the Example.java with the command line. Now I want to execute it within IntelliJ, that I can improve my workflow. I followed already the instructions [here](https://github.com/tdlib/td/issues/306), what didn't work so far. As mentioned in the post my project structure does look like @mincong-h discribed it there and I added `-Djava.library.path=C:/Users/Me/Desktop/td/example/java/bin` to the VM options. It says: 

> tdjni.dll: Can't find dependent libraries at Example.java: 58

That file is definately available at that location. So when I come to solve that problem I like to do the following:

I want to build a fat jar, including all dependencies the tdlib stuff needs and uses and want to add it as a jar dependency to my primary maven project, so I can implement a new "Example.java" like I need it. In that maven project I want to build a .war file for my tomcat webserver, so it has to run from another endpoint in another class file. Is that even possible in the way I intended it? Please help!

**Comment by levlam** [comment]
`Can't find dependent libraries` should mean that there is no OpenSSL and zlib dlls in `C:/Users/Me/Desktop/td/example/java/bin`. Are `LIBEAY32.dll`, `SSLEAY32.dll` and `zlib1.dll` present there?

**Comment by MaxiGH** [comment]
Yes, all 3 files are located right next to the tdjni.dll file.

**Comment by MaxiGH** [comment]
I guess I got this problem solved but intellij's saying me now: 

`tdjni.dll is not a valid Win32 application.`

I compiled jni for x64 systems, and I don't know where the call is happening to run this file with 32 bit, I do not even have java 32 bit installed. Any ideas?

**Comment by levlam** [comment]
You need to specify `-d32` parameter to java to use 32-bit TDLib version or to compile TDLib to 64-bit dll. By default MSVC builds 32-bit binaries and you need to specify `-A x64` option to CMake on first invocation to override that.

**Comment by MaxiGH** [comment]
I used `-A x64` on both cmake configurations, so the whole java Example is working on 64 bit Java when I use command line interface `/bin> java org/drinkless/tdlib/example/Example`, that's working fine. Now the change to intellij: I took the 3 classes client, tdapi and log and Example .java files and try to execute these with an additional VM option `-Djava.library.path=<path to tdjni.dll>`. With no `-d32` I intend to run it with Java 64 bit like before. Now I get an error: `tdjni.dll is no valid Win32 application`. There must be a problem within Intellij settings or some options are missing. I don't know how to specify things right to successfully build and execute these project in Intellij IDE.

**Comment by levlam** [comment]
I've just tested it and found that `java.library.path` is completely ignored when dependent libraries are searched, so you need to copy them to the project Working directory. Alternatively, you can add folder with them to `PATH` environment variable or copy them to such folder, but it will not help on other computers.
