### ISSUE TITLE
AUTH_KEY_DUPLICATED

### ISSUE THREAD

**Issue by saurabhs2t** [tdlib/td#353]
Hi, I am trying to develop Telegram Service using TdLib (C-sharp) where I have to retrieve the Chat Info from a public Channel. 
The service was working fine, but I am getting AUTH_KEY_DUPLICATED error : { code = 406 }, whenever I am trying to use GetChatHistory for any public Channel.

Any help would be greatly appreciated. Thanks

**Comment by saurabhs2t** [comment]
Hi, Thanks for the response. But I am unable to figure out, how to delete the database directory. Please suggest. 
Thanks

**Comment by levlam** [comment]
You can use TDLib's `destroy` method for that. Or you can delete it manually through any file manager like Explorer.

**Comment by saurabhs2t** [comment]
Many thanks, the issue is resolved after using destroy method.

**Comment by zevlg** [comment]
Is it possible in 1.4.0 to just reset the keys without destroying cached content?

**Comment by levlam** [comment]
TDLib doesn't delete cached files while logging out, only database is deleted, because it contains private data and can't be reused.
