### ISSUE TITLE
Text Encoding Issue in TdLib

### ISSUE THREAD

**Issue by saurabhkr09** [tdlib/td#354]
Hi, I am developing Telegram Service using TdLib (C-sharp) where I have to retrieve the Chat Info from a public Channel.

The chat message returns fine if the text is in English. But for any other language, return message is not readable. See the below screenshots-
English:
![image](https://user-images.githubusercontent.com/42425945/45147939-b581f980-b1f8-11e8-8107-57258b002ce5.png)
Chinese:
![image](https://user-images.githubusercontent.com/42425945/45148111-1c071780-b1f9-11e8-8721-bc339abc7829.png)

So please suggest is there any way to encode this text. Thank you!!

**Comment by levlam** [comment]
What TDLib version are you using?

**Comment by saurabhs2t** [comment]
Hi, I am using version 1.2.0

![image](https://user-images.githubusercontent.com/42425945/45150174-d9940980-b1fd-11e8-8345-f091b835cd68.png)

Thank you.

**Comment by saurabhs2t** [comment]
So update the library and rebuild again using cmake and vcpkg?

**Comment by levlam** [comment]
Yes.
