### ISSUE TITLE
Get Super Group Member Information

### ISSUE THREAD

**Issue by saurabhs2t** [tdlib/td#358]
Hi, I have few more questions regarding the TdLib (C#).

1. How do I implement GetSuperGroupMembers using SuperGroupMemebrsFilter

Any help would be greatly appreciated. Thank you.

**Comment by levlam** [comment]
You can get all supergroup members using `supergroupMembersFilterRecent` filter.

**Comment by saurabhs2t** [comment]
Hi @levlam 

Thanks for the info, implemented the function. Now able to get supergroup members using supergroupMembersFilterRecent filter.

:)
