### ISSUE TITLE
Licensing when porting to a different language

### ISSUE THREAD

**Issue by JuanPotato** [tdlib/td#36]
Hi, I want to port this library to Rust. As far as I can tell, the Boost license you are using requires any derivative works (my port) to also be under the Boost license. I thought I might come and ask if you would allow me to re-license the port under MPL v2.0

**Comment by isopen** [comment]
I join the question. Is it possible to change the license type or clone your license necessarily?

**Comment by arseny30** [comment]
If you are are using tdlib as a library, then you can publish your work under any license you want.
Or not publish at all.

If you are going to make changes in our code, then you probably have to keep the license. 
But why is that a problem?

**Comment by isopen** [comment]
It's not a problem. You have an excellent license! Thank.

**Comment by JuanPotato** [comment]
It's more of a personal preference. MPL 2.0 is a pretty nice license, it let's you use the library in whatever project, and you only have to release changes you've made to the library (not the entire project). So it's a nice way to get back contributions without being a hindrance for who can use the library

**Comment by JuanPotato** [comment]
This issue isn't because I've found some, but because I would prefer it and I figured I'd give it a shot to get permission. But it's fine too if you don't

**Comment by JuanPotato** [comment]
Ok, beyond this, since I intend to try to port this project to Rust, where to you suggest I start? This is a big project

**Comment by levlam** [comment]
There is no need to port the whole project to Rust, you can use the library from a Rust app easily. If you don't mind to use JSON objects for interaction with the library than you only need to make Rust bindings to C functions from td_json_client.h and td_log.h. You can look for an example of such binding in our Python example. In Rust the binding can be created even simpler: https://doc.rust-lang.org/beta/nomicon/ffi.html.

**Comment by JuanPotato** [comment]
Yeah I know that, it's not about whether I should or shouldn't port the
thing. I just want to.
