### ISSUE TITLE
Error in MessageManager.cpp

### ISSUE THREAD

**Issue by ByeCoder** [tdlib/td#360]
Hello,can you help me to solve this error?
`[ 0][t 0][1537041717.442058325][MessagesManager.cpp:5692][!Td]`
I get this error every 12 hours when bot has 10 supergroups and every 10 minutes when the cli bot has about 200 supergroups
UNREACHABLE(); in td/telegram/MessageManager.cpp

this is complete var-dump

`(table)`
` [user_id] = (number) 540405325`
` [action] = (table)`
`  [k1] = (string) chatActionTyping`
` [chat_id] = (string) -1001244007406`
` [k1] = (string) updateUserChatAction`

`[ 0][t 0][1537041717.442058325][MessagesManager.cpp:5692][!Td]`

**Comment by levlam** [comment]
It has been fixed in TDLib 1.3.0.

**Comment by ByeCoder** [comment]
This error occurs after a few days;

`` [ 0][t 1][1566649475.327395439][MessagesManager.cpp:21526][!Td][&!d->being_added_message_id.is_valid()] server message 4538262 server message 4538221 get_message_force ``

and got this
``
(table)
 [_] = (string) ok
 [@type] = (string) ok

Aborted (core dumped)
``

**Comment by levlam** [comment]
@ByeCoder This is an unrelated issue, which was introduced after TDLib 1.3.0, existed for a very short time and was fixed before TDLib 1.4.0 release. Which TDLib version are you using?

**Comment by ByeCoder** [comment]
@levlam I using 1.3.6 TDLib version.there is no way to fix it?

**Comment by levlam** [comment]
It can be fixed only by updating to TDLib 1.4.0 or later.

**Comment by ByeCoder** [comment]
@levlam but there are some problem in 1.4.0 in logging methods that causes to account banned.no way to solve problem the 1.3.6?

**Comment by levlam** [comment]
@ByeCoder No. And TDLib version is not related to accounts ban.
