### ISSUE TITLE
Error install TDLib dependencies using vcpkg

### ISSUE THREAD

**Issue by codesurfer1** [tdlib/td#365]
Hi.

1. I'm installed vcpkg step by step as like in instruction.

![1 install vcpkg](https://user-images.githubusercontent.com/43304244/45631399-7a5ab280-baa3-11e8-9322-21e823c9d3e8.png)

2. Then I trying to execute this command

![2 try command](https://user-images.githubusercontent.com/43304244/45631500-ae35d800-baa3-11e8-94ec-5fb731accd20.png)

3. And have an error

![3 error](https://user-images.githubusercontent.com/43304244/45631530-c4439880-baa3-11e8-9d62-e0f5b23492c8.png)

**Comment by codesurfer1** [comment]
... maybe it because do not need entering extension .exe?

![1](https://user-images.githubusercontent.com/43304244/45632694-9ca1ff80-baa6-11e8-84de-957181cbec28.png)

**Comment by codesurfer1** [comment]
Tried in PowerShell.

`git clone https://github.com/Microsoft/vcpkg.git`
done

`cd vcpkg`
done

`PS> .\bootstrap-vcpkg.bat`
not found, or

`.\bootstrap-vcpkg.bat`
not found too

**Comment by zelenin** [comment]
I use this instruction yesterday. It's ok.
Is `vcpkg.exe` in `vcpkg` directory after `bootstrap-vcpkg.bat`?

**Comment by levlam** [comment]
Could you show output of `.\bootstrap-vcpkg.bat` or `./bootstrap-vcpkg.sh`?

**Comment by codesurfer1** [comment]
[output.txt](https://github.com/tdlib/td/files/2389916/output.txt)

**Comment by ras0219-msft** [comment]
@codesurfer1 Try building `toolsrc/vcpkg.sln` directly in VS and copying the built binary (`toolsrc/Release/vcpkg.exe`) into the root.

**Comment by codesurfer1** [comment]
> @codesurfer1 Try building `toolsrc/vcpkg.sln` directly in VS and copying the built binary (`toolsrc/Release/vcpkg.exe`) into the root.

It worked!

**Comment by codesurfer1** [comment]
> @codesurfer1 Everything is fine there, `vcpkg.exe` should have been created in the `C:\Users\admin\vcpkg\` folder. It is really strange if it isn't created. In that case you can try to copy it from `C:\Users\admin\vcpkg\toolsrc\Release\vcpkg.exe`.

There was no vcpkg.exe :-)
In the output.txt it was printed, but in fact the exe file was not there.

**Comment by codesurfer1** [comment]
Thanks to everybody!
