### ISSUE TITLE
Error: Install TDLib dependencies using vcpkg

### ISSUE THREAD

**Issue by codesurfer1** [tdlib/td#369]
Hi.

In the attachment are two .txt files.

[vs build output.txt](https://github.com/tdlib/td/files/2413195/vs.build.output.txt)
Here output from Visual Studio when I'm build directly from vcpkg\toolsrc\vcpkg.sln.
Directly, because vcpkg.exe not created automatically.

[powershell output.txt](https://github.com/tdlib/td/files/2413194/powershell.output.txt)
And here output from PowerShell with all the process.

Please answer, why i have an error?

**Comment by levlam** [comment]
Could you also attach build log files. They should be at `C:\users\admin\vcpkg\buildtrees\openssl-windows\` folder.

**Comment by codesurfer1** [comment]
It's absent.

![123](https://user-images.githubusercontent.com/43304244/46004337-4b53ca80-c0bb-11e8-8b2c-f46758a55ab6.png)

**Comment by codesurfer1** [comment]
> Everything works fine for me.

powershell output.txt -> Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED

> Do you have enough disk space?

Yes.

> Do you have vcpkg in other directories?

No.

> vcpkg related environment variables?

No. But I did not see that it was written somewhere.

**Comment by levlam** [comment]
> powershell output.txt -> Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED

I've meant that exactly the same commands has worked for me. The only difference I've noticed was that vcpkg has downloaded latest versions of cmake, git and other tools and there is nothing similar in your build log. It should mean that they are already downloaded somewhere. It's also really strange that there is no `buildtrees` folder but vcpkg has tried to build something. Could you try to find `buildtrees` folder somewhere else, for example, find all `buildtrees` directories on your drive?

**Comment by codesurfer1** [comment]
I plan to reinstall the OS soon.
Then I'll try to build again.

Thank you.
