### ISSUE TITLE
Trying to send message but getting None in response

### ISSUE THREAD

**Issue by dhavalp** [tdlib/td#373]
i am trying to send message to chat_id but i am getting None in response.
when i am getting  "authorizationStateReady" as @type then i am putting code for sending message.
and after sending message once i got "updateChatLastMessage" as @type there also i am sending message again but i am getting old message again which i sent first time.

see this code

`import getpass

from generic import *

def logout():
	td_send({'@type': 'logOut'})

print("Starting login sequence")

count = 0
while True:
	event = td_receive()
	
	count = count + 1
	if event:
		print(event)
		# if count == 100 :
			# break
		if event.get('@type') == 'updateAuthorizationState':
			authtype = event.get('authorization_state').get('@type')
			if authtype == "authorizationStateWaitTdlibParameters":
				td_send({'@type': 'setTdlibParameters',
				'parameters': {'use_test_dc': False,
				'api_id':344724,
				'api_hash': '**********************************',
				'device_model': 'Desktop',
				'system_version': 'Unknown',
				'application_version': "0.0",
				'system_language_code': 'en',
				'database_directory': 'Database',
				'files_directory': 'Files',
				'use_file_database': True,
				'use_chat_info_database': True,
				'use_message_database': True,
				}
				})
			elif authtype == 'authorizationStateWaitEncryptionKey':
				td_send({'@type': 'checkDatabaseEncryptionKey', 'encryption_key': 
                                 'randomencryption'})
			elif authtype == "authorizationStateWaitPhoneNumber":
				phone = input('Enter phone number: ')
				td_send({'@type': 'setAuthenticationPhoneNumber',
				'phone_number': str(phone),
				'allow_flash_call': False,
				'is_current_phone_number': False}
				)
			elif authtype == "authorizationStateWaitCode":
				code = input('Enter code:')
				td_send({'@type': 'checkAuthenticationCode', 'code': str(code)})
			elif authtype == "authorizationStateWaitPassword":
				password = getpass.getpass('Password:')
				td_send({'@type': 'checkAuthenticationPassword', 'password': password})
			elif authtype == "authorizationStateReady":
				print("authorizationStateReady go")
				chat_id = str(317681364)
				
				z = td_send({'@type': 'sendMessage',
							'chat_id': "655937284",
							'input_message_content': {
							 '@type': 'inputMessageText',
							 'text': {
							 '@type': 'formattedText',
							 'text': 'hi how are you?'
							}
							}})
				print(z)
				
				
				# break
		
		if event.get('@type') == 'updateChatLastMessage':
			print("updateChatLastMessage")
			z = td_send({'@type': 'sendMessage',
					 'chat_id': "655937284",
					 'input_message_content': {
					 '@type': 'inputMessageText',
					 'text': {
					 '@type': 'formattedText',
					 'text': 'hi  how are you?'
					}
					}})
			print(z)
			event = td_receive()
			print(event)
			# break
		if event.get('@type') == 'updateNewChat':
			print("updateNewChat")
			z = td_send({'@type': 'sendMessage',
					 'chat_id': "655937284",
					 'input_message_content': {
					 '@type': 'inputMessageText',
					 'text': {
						 '@type': 'formattedText',
						 'text': 'hi dhaval how are you?'
						}
					}})
			print(z)
			
			# break

`
generic.py file

`from ctypes import CDLL, c_void_p, c_char_p, c_double, c_int, c_longlong, CFUNCTYPE
from ctypes.util import find_library
import os
import json
if os.name == 'posix':
	tdjson = CDLL("lib/libtdjson.so")
else:
    try:
        tdjson = CDLL("lib/tdjson32.dll")
    except:
        CDLL("lib/zlibd1.dll")
        tdjson = CDLL("lib/tdjson64.dll")

td_json_client_create = tdjson.td_json_client_create
td_json_client_create.restype = c_void_p
td_json_client_create.argtypes = []

td_json_client_receive = tdjson.td_json_client_receive
td_json_client_receive.restype = c_char_p
td_json_client_receive.argtypes = [c_void_p, c_double]

td_json_client_send = tdjson.td_json_client_send
td_json_client_send.restype = None
td_json_client_send.argtypes = [c_void_p, c_char_p]

td_json_client_execute = tdjson.td_json_client_execute
td_json_client_execute.restype = c_char_p
td_json_client_execute.argtypes = [c_void_p, c_char_p]

td_json_client_destroy = tdjson.td_json_client_destroy
td_json_client_destroy.restype = None
td_json_client_destroy.argtypes = [c_void_p]

td_set_log_file_path = tdjson.td_set_log_file_path
td_set_log_file_path.restype = c_int
td_set_log_file_path.argtypes = [c_char_p]

td_set_log_max_file_size = tdjson.td_set_log_max_file_size
td_set_log_max_file_size.restype = None
td_set_log_max_file_size.argtypes = [c_longlong]

td_set_log_verbosity_level = tdjson.td_set_log_verbosity_level
td_set_log_verbosity_level.restype = None
td_set_log_verbosity_level.argtypes = [c_int]

fatal_error_callback_type = CFUNCTYPE(None, c_char_p)

td_set_log_fatal_error_callback = tdjson.td_set_log_fatal_error_callback
td_set_log_fatal_error_callback.restype = None
td_set_log_fatal_error_callback.argtypes = [fatal_error_callback_type]

def on_fatal_error_callback(error_message):
    print('TDLib fatal error: ', error_message)

td_set_log_verbosity_level(2)
c_on_fatal_error_callback = fatal_error_callback_type(on_fatal_error_callback)
td_set_log_fatal_error_callback(c_on_fatal_error_callback)

def td_send(query):
    query = json.dumps(query).encode('utf-8')
    td_json_client_send(client, query)

def td_receive():
    result = td_json_client_receive(client, 1.0)
    if result:
        result = json.loads(result.decode('utf-8'))
    return result
def td_execute(query):
    query = json.dumps(query).encode('utf-8')
    result = td_json_client_execute(client, query)
    if result:
        result = json.loads(result.decode('utf-8'))
    return result
client = td_json_client_create()
`

**Comment by levlam** [comment]
TDLib main interface is asynchronous. td_send only sends request and always returns None. Request results will be received when available through td_receive. If you want to match requests with corresponding responses, you need to use `@extra` request's field. You can find more information about TDLib interface and updates handling there: https://core.telegram.org/tdlib/getting-started#tdlib-interface.

**Comment by dhavalp** [comment]
Thanks for the reply. 

what shall we do about the updateConnectionState ?
i am getting {u'message': u"First name can't be empty", u'code': 8, u'@extra': 1.01234, u'@type': u'error'} this response after updateConnectionState state when trying to receive the message.

**Comment by levlam** [comment]
`updateConnectionState ` is just an update sent to you by `TDLib` when [ConnectionState](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_connection_state.html) changes. It is up to you, how it will be handled.

The second object is a response to `checkAuthenticationCode` request. You need to match them using `@extra` field. The error means that you entered yet unregistered phone number and you are required to enter also `first_name` and `last_name` to complete user registration.

**Comment by dhavalp** [comment]
can i get chat_id by passing username? is there any method to access it?

**Comment by dhavalp** [comment]
i have one chat_id. i am sending message on that chat_id i am getting  this in response: {u'message': u'Chat not found', u'code': 5, u'@extra': 1.01234, u'@type': u'error'}

**Comment by dhavalp** [comment]
thanks @levlam 
i am getting "authorizationStateReady" in response , so after that can i send any method such as getMe , sendMessage , getChats or i have to send any particular method after getting "authorizationStateReady".
for example : when we get "authorizationStateWaitTdlibParameters" in this response we have to send "setTdlibParameters" method.

**Comment by levlam** [comment]
You can use any method now.
