### ISSUE TITLE
Can't pin chat while using proxy with sponsored channel

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#383]
TDLib generates error `Maximum number of pinned chats exceeded`, when trying to pin `pinned_chat_count_max`th chat, while using proxy with sponsored channel.

It's possible to disable proxy, pin chat, then enable proxy back.

**Comment by levlam** [comment]
Thanks. Confirmed.

**Comment by levlam** [comment]
Fixed in TDLib 1.4.0.
