### ISSUE TITLE
Proxy sponsor chat affects UpdateUnreadMessageCount when you are not its participant

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#384]
When you are not a member of a sponsored chat, its messages affect global unread counter. I'm not sure whether it is server or TDLib issue.

Original report:
https://t.me/tgandroidtests/42120

**Comment by levlam** [comment]
The counter is calculated locally, but official Android Telegram client has the same behavior: unread messages in a sponsored chat are included in global unread counter.

**Comment by levlam** [comment]
Since TDLib 1.4.0 the sponsored chat is excluded from unread counters.
