### ISSUE TITLE
Cannot find method to remove user from chat

### ISSUE THREAD

**Issue by Vladyslav120604** [tdlib/td#387]
Hi guys,
In my program i need remove users from diffrent chats, but i cann't find method i need
As i know, all methods are in this list: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html
But there is no such method that can do it.

**Comment by levlam** [comment]
You need to use `setChatMemberStatus` with `chatMemberStatusLeft`/`chatMemberStatusBanned` to do that.
