### ISSUE TITLE
java use http proxy

### ISSUE THREAD

**Issue by leonidUH** [tdlib/td#388]
Hello. 
I added to java example new line for http proxy
  new TdApi.AddProxy("15.15.15.15", 12345, true, new TdApi.ProxyTypeHttp("username","password",false));
But when i checked Active Sessions  -it was my home ip address and not proxy.
Is there something else that I should change in the code?

**Comment by levlam** [comment]
Have you sent this request using `client_.send`? If so, could you send TDLib log with verbosity level 4 to @tdlib_bot?

**Comment by leonidUH** [comment]
oops
 thank you
You're right , I forgot to add client.send
Now it's working fine
client.send(new TdApi.AddProxy("15.15.15.15", 12345, true, new TdApi.ProxyTypeHttp("username","password",false)), new ProxyRequestHandler());

**Comment by mostafa8026** [comment]
client.send accepts tdApi.Function, how could you perform pass tdApi.proxy to it?

**Comment by levlam** [comment]
@mostafa8026 The function is `TdApi.AddProxy` and not `TdApi.Proxy`.
