### ISSUE TITLE
getChatHistory returns messages in wrong order

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#391]
The getChatHistory method gets messages in different order compared to official Telegram clients. Messages close to each other in time often end up at positions slightly different from actual order.

**Comment by levlam** [comment]
The order of server messages is the same in all clients for a chosen users, because it is controlled server-side. In basic group and private chats message order can be different for different users, in supergroups/channels message order is always the same for all chat members.

**Comment by x2bool** [comment]
Thanks for the explanation. That makes sense.
