### ISSUE TITLE
Delphi\fp example?

### ISSUE THREAD

**Issue by mvgx** [tdlib/td#392]
I'd be very grateful to see an example of using TDLib with Pascal, thanks!

**Comment by dieletro** [comment]
I would also very much like an example of using TDLib in Delphi and Lazarus

**Comment by levlam** [comment]
Thanks to @dieletro, you can now find examples of TDLib usage in Pascal in [tdlib-delphi](https://github.com/dieletro/tdlib-delphi) and [tdlib-lazarus](https://github.com/dieletro/tdlib-lazarus).
