### ISSUE TITLE
Message manager.cpp

### ISSUE THREAD

**Issue by artin5912** [tdlib/td#393]
Hi, file MessageManager.cpp When you create a telegram-bot file, it can be configured as my server is RAM 4

**Comment by levlam** [comment]
Currently, you need to use clang instead of GCC to build TDLib with less than 4GB of RAM. See https://github.com/tdlib/td/issues/334 for more information.

**Comment by levlam** [comment]
TDLib 1.4.0 includes a lot of compilation memory usage optimizations and a new script `SplitSource.php`, which can be used to split some source code files before building the library to reduce maximum RAM usage per file at the expense of increased build time. In our tests clang 6.0 with libc++ required less than 500 MB of RAM per file and GCC 4.9/6.3 used less than 1 GB of RAM per file.
