### ISSUE TITLE
Notifications - alert by keyword

### ISSUE THREAD

**Issue by witcold** [tdlib/td#394]
There are three closed issues for Telegram desktop suggesting keyword notfication feature:
- https://github.com/telegramdesktop/tdesktop/issues/554
- https://github.com/telegramdesktop/tdesktop/issues/1727
- https://github.com/telegramdesktop/tdesktop/issues/4615

All of them are closed due to API issue. 

Any chance for this feature to be implemented? In case it's not a responsibility of TDLib, please point to the appropriate repository/etc.

**Comment by levlam** [comment]
It should be supported server-side, because otherwise client will not receive push notification about new message. Server-side feature requests can be submited only through Volunteer Support or @telegram Twitter.
