### ISSUE TITLE
429 - find rate limit .

### ISSUE THREAD

**Issue by leonidUH** [tdlib/td#396]
Hi 
On some requests I get error with code = 429 and  message = "Too Many Requests..."
Where can I find ( maybe in documentation?)  which will show - what is the limit in determining time interval for each function

e.g 
on login i got 429 after ~20 requests in 2-3 minutes  -  message : retry after 24 hour
on getSupergroup,getSupergroupFullInfo  after 150 request in 1 sec -  -  message : retry after 30 sec

P.S. I use java client

**Comment by levlam** [comment]
Limits are subject to change based on a lot of unpredictable events. You don't need to know them in advance and you shouldn't assume any particular limits, you just need to properly handle 429th errors.
