### ISSUE TITLE
Strange, unwanted channels appear out of nothing

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#399]
Hello team,

we are re-implementing Telegram for the Ubuntu Touch phone. In my latest test build I suddenly see those channels flooding my chat list, and they appear out of nothing, and are of course not wanted by me:

![grafik](https://user-images.githubusercontent.com/16186470/47939507-d2c90080-dee7-11e8-8211-63f177220613.png)

I do not see those channels on my desktop, my normal mobile device or the web client. They do persist after a restart of the App.

How can it happen that tdlib pulls channels in that are not in the chat list of the account? I did not have debugging turned on during that session, so I am afraid logfiles will not be much helpful.

**Comment by levlam** [comment]
Are you sure that these chats has Chat.order > 0? Chat order in the chat list is controlled by TDLib and only chats with order > 0 should be shown there.

**Comment by Flohack74** [comment]
lemme check this...

**Comment by Flohack74** [comment]
Thanks for closing, it never appeared again, seems we fixed it or it fixed by itself ;)
