### ISSUE TITLE
Feature request: getTextEntities shall resolve also formatting

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#400]
Currently getTextEntities does only extract action entities like links, mentions etc. It would be good to also include formatting with ** and __ etc. Because now I need to do it like this:
```
    //First call tdlib to markup all complex entities
    auto parseRequest = QJsonObject{
        {"@type", "getTextEntities"}, {"text", message}};
    auto result = QTdClient::instance()->exec(parseRequest);
    result.waitForFinished();
    auto entities = result.result()["entities"].toArray();

    //Then do the text formatting
    QString plainText;
    QTdHelpers::getEntitiesFromMessage(message, plainText, entities);
```
So I ned a second function call that does the parsing for the formatting entities. Or did I understand it wrong?

You would just need to add a second out parameter to strip the formatting from the message text:
`request->setText(plainText);`

**Comment by levlam** [comment]
TDLib does support for now only Bot API-style Markdown and HTML markup parsing through parseTextEntities function, which is unsuitable for ordinary users. So currently app needs to support WYSIWIG editor for message entities or it's own parser for markdown and then call getTextEntities for all still unformatted text parts.

**Comment by levlam** [comment]
Synchronous method `parseMarkdown` was added in TDLib 1.6.2, which implements user-friendly Markdown parsing.
