### ISSUE TITLE
Join chat procedure

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#401]
Hi, I'm having issue when joining chat.
Steps I'm following:

1. Search for my test chat with SearchPublicChat method, extract chat id from response.
2. Try to join chat via JoinChat method with extracted chat id from above step.
And I get an error "Chat not found" when joining chat. I'm sure that extracted id is correct chat id.

PS some of my test users can join that chat. But some - cannot. I've checked via spam bot that these users don't have any restrictions.
PPS I've noticed that when I go to that chat manually via mobile or web app with some user, join that chat, leave and again enter and after that return to my app, system stops to respond with "Chat not found" error and successfully joins chat.

Could you please explain why system behaves that way and what I may be doing wrong?

**Comment by levlam** [comment]
You need to call SearchPublicChat and JoinChat by the same user with message database enabled or without relaunching TDLib. You can't use unknown to current user chat_id or, if message database is disabled, a chat_id got in previous TDLib launches.

**Comment by Mike497** [comment]
Thanks for your help, levlam!
