### ISSUE TITLE
Feature request: Public feed for Telegra.ph

### ISSUE THREAD

**Issue by yusufk** [tdlib/td#405]
Please consider creating a public feed feature on Telegram that pulls published Telegra.ph posts from all contacts into one common conversation.

This will turn Telegra.ph / Telegram into an instant Google+ replacement.

**Comment by levlam** [comment]
There is no way this can be implemented in TDLib, unless it is implemented server-side first. Please send general suggestions through in-app support or by menthioning @telegram on Twitter.
