### ISSUE TITLE
How to link static Tdlib into qt project?

### ISSUE THREAD

**Issue by asok00000** [tdlib/td#408]
Qt isn't static version
when my qt project link to tdlib
the compiler can find the lib but report unreference error.
`/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::TdProxy::tear_down()':
Client.cpp:(.text._ZN2td7TdProxy9tear_downEv[_ZN2td7TdProxy9tear_downEv]+0x1b): undefined reference to `td::Scheduler::instance()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<td::detail::ThreadStl::ThreadStl<td::Client::Impl::init()::{lambda()#1}>(td::Client::Impl::init()::{lambda()#1}&&)::{lambda()#1}> > >::_M_run()':
Client.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN2td6detail9ThreadStlC4IZNS3_6Client4Impl4initEvEUlvE_JEEEOT_DpOT0_EUlvE_EEEEE6_M_runEv[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN2td6detail9ThreadStlC4IZNS3_6Client4Impl4initEvEUlvE_JEEEOT_DpOT0_EUlvE_EEEEE6_M_runEv]+0x3d): undefined reference to `td::ConcurrentScheduler::run_main(double)'
Client.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN2td6detail9ThreadStlC4IZNS3_6Client4Impl4initEvEUlvE_JEEEOT_DpOT0_EUlvE_EEEEE6_M_runEv[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN2td6detail9ThreadStlC4IZNS3_6Client4Impl4initEvEUlvE_JEEEOT_DpOT0_EUlvE_EEEEE6_M_runEv]+0x4a): undefined reference to `td::ConcurrentScheduler::finish()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::ConcurrentScheduler::~ConcurrentScheduler()':
Client.cpp:(.text._ZN2td19ConcurrentSchedulerD2Ev[_ZN2td19ConcurrentSchedulerD5Ev]+0xc8): undefined reference to `td::Scheduler::~Scheduler()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::ConcurrentScheduler::~ConcurrentScheduler()':
Client.cpp:(.text._ZN2td19ConcurrentSchedulerD0Ev[_ZN2td19ConcurrentSchedulerD5Ev]+0xc8): undefined reference to `td::Scheduler::~Scheduler()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::Actor::hangup()':
Client.cpp:(.text._ZN2td5Actor6hangupEv[_ZN2td5Actor6hangupEv]+0x1e): undefined reference to `td::Scheduler::instance()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::TdProxy::on_closed()':
Client.cpp:(.text._ZN2td7TdProxy9on_closedEv[_ZN2td7TdProxy9on_closedEv]+0x54): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td7TdProxy9on_closedEv[_ZN2td7TdProxy9on_closedEv]+0xb1): undefined reference to `td::Scheduler::instance()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::Client::execute(td::Client::Request&&)':
Client.cpp:(.text._ZN2td6Client7executeEONS0_7RequestE+0x42): undefined reference to `td::Td::static_request(std::unique_ptr<td::td_api::Function, std::default_delete<td::td_api::Function> >)'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::ActorInfo::init(int, td::Slice, td::ObjectPool<td::ActorInfo>::OwnerPtr&&, td::Actor*, td::ActorInfo::Deleter, bool)':
Client.cpp:(.text._ZN2td9ActorInfo4initEiNS_5SliceEONS_10ObjectPoolIS0_E8OwnerPtrEPNS_5ActorENS0_7DeleterEb[_ZN2td9ActorInfo4initEiNS_5SliceEONS_10ObjectPoolIS0_E8OwnerPtrEPNS_5ActorENS0_7DeleterEb]+0x188): undefined reference to `td::Scheduler::context()'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::NetQueryCallback::~NetQueryCallback()':
Client.cpp:(.text._ZN2td16NetQueryCallbackD2Ev[_ZN2td16NetQueryCallbackD5Ev]+0x3d): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td16NetQueryCallbackD2Ev[_ZN2td16NetQueryCallbackD5Ev]+0x48): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::Slot::~Slot()':
Client.cpp:(.text._ZN2td4SlotD0Ev[_ZN2td4SlotD5Ev]+0x39): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td4SlotD0Ev[_ZN2td4SlotD5Ev]+0x44): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
Client.cpp:(.text._ZN2td4SlotD0Ev[_ZN2td4SlotD5Ev]+0xd0): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td4SlotD0Ev[_ZN2td4SlotD5Ev]+0xdb): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::Actor::~Actor()':
Client.cpp:(.text._ZN2td5ActorD0Ev[_ZN2td5ActorD5Ev]+0x3d): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td5ActorD0Ev[_ZN2td5ActorD5Ev]+0x48): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::NetQueryCallback::~NetQueryCallback()':
Client.cpp:(.text._ZN2td16NetQueryCallbackD0Ev[_ZN2td16NetQueryCallbackD5Ev]+0x3d): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td16NetQueryCallbackD0Ev[_ZN2td16NetQueryCallbackD5Ev]+0x48): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::Actor::~Actor()':
Client.cpp:(.text._ZN2td5ActorD2Ev[_ZN2td5ActorD5Ev]+0x3d): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td5ActorD2Ev[_ZN2td5ActorD5Ev]+0x48): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
/home/asok00000/td/example/cpp/td/lib/libtdclient.a(Client.cpp.o): In function `td::Slot::~Slot()':
Client.cpp:(.text._ZN2td4SlotD2Ev[_ZN2td4SlotD5Ev]+0x39): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td4SlotD2Ev[_ZN2td4SlotD5Ev]+0x44): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'
Client.cpp:(.text._ZN2td4SlotD2Ev[_ZN2td4SlotD5Ev]+0xcb): undefined reference to `td::Scheduler::instance()'
Client.cpp:(.text._ZN2td4SlotD2Ev[_ZN2td4SlotD5Ev]+0xd6): undefined reference to `td::Scheduler::do_stop_actor(td::Actor*)'`

**Comment by levlam** [comment]
You need to link statically other TDLIb static libraries and their dependencies, namely, all libraries that are copied by `cmake --build . --target install`, OpenSSL libararies and zlib, i.e. `libtdcore.a`, `libtddb.a`, `libtdnet.a`, `libtdsqlite.a`, `libtdactor.a`, `libtdutils.a`, `libcrypto.a`, `libssl.a`, `libz.a`. Be aware that library order in linker parameters is significant.
