### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by tesey27** [tdlib/td#410]
gmake[2]: *** [tdutils/CMakeFiles/tdutils.dir/td/utils/port/Fd.cpp.o] Ошибка 1
gmake[1]: *** [tdutils/CMakeFiles/tdutils.dir/all] Ошибка 2
gmake: *** [all] Ошибка 2

**Comment by levlam** [comment]
Could you show the whole output, including output of all cmake invocations?

**Comment by tesey27** [comment]
[root@rm build]# cmake --build .
[  1%] Generate git_commit.h
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[  1%] Built target git_commit
[  1%] Built target generate_mime_types_gperf
[  2%] Built target tdmime_auto
[  2%] Building CXX object tdutils/CMakeFiles/tdutils.dir/td/utils/port/Fd.cpp.o
In file included from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:11:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/common.h:105:12: ошибка: «std::make_unique» не был декларирова                                    н
 using std::make_unique;
            ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/Slice.h:9:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:12,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:29:35: ошибка: «std::enable_if_t» не был декларир                                    ован
   explicit MutableSlice(T s, std::enable_if_t<std::is_same<char *, T>::value, private_tag> = {});
                                   ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:29:46: ошибка: expected «,» or «...» before «<» t                                    oken
   explicit MutableSlice(T s, std::enable_if_t<std::is_same<char *, T>::value, private_tag> = {});
                                              ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:75:28: ошибка: «std::enable_if_t» не был декларир                                    ован
   explicit Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_t                                    ag> = {});
                            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:75:39: ошибка: expected «,» or «...» before «<» t                                    oken
   explicit Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_t                                    ag> = {});
                                       ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:77:28: ошибка: «std::enable_if_t» не был декларир                                    ован
   explicit Slice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value, pri                                    vate_tag> = {});
                            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:77:39: ошибка: expected «,» or «...» before «<» t                                    oken
   explicit Slice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value, pri                                    vate_tag> = {});
                                       ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:77:12: ошибка: «template<class T> td::Slice::Slic                                    e(T, int)» cannot be overloaded
   explicit Slice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value, pri                                    vate_tag> = {});
            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:75:12: ошибка: with «template<class T> td::Slice:                                    :Slice(T, int)»
   explicit Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_t                                    ag> = {});
            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:127:36: ошибка: «std::enable_if_t» не был деклари                                    рован
   explicit MutableCSlice(T s, std::enable_if_t<std::is_same<char *, T>::value, private_tag> = {}) : M                                    utableSlice(s) {
                                    ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:127:47: ошибка: expected «,» or «...» before «<»                                     token
   explicit MutableCSlice(T s, std::enable_if_t<std::is_same<char *, T>::value, private_tag> = {}) : M                                    utableSlice(s) {
                                               ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:153:29: ошибка: «std::enable_if_t» не был деклари                                    рован
   explicit CSlice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_                                    tag> = {})
                             ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:153:40: ошибка: expected «,» or «...» before «<»                                     token
   explicit CSlice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_                                    tag> = {})
                                        ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:157:29: ошибка: «std::enable_if_t» не был деклари                                    рован
   explicit CSlice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value, pr                                    ivate_tag> = {})
                             ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:157:40: ошибка: expected «,» or «...» before «<»                                     token
   explicit CSlice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value, pr                                    ivate_tag> = {})
                                        ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:157:12: ошибка: «template<class T> td::CSlice::CS                                    lice(T, int)» cannot be overloaded
   explicit CSlice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value, pr                                    ivate_tag> = {})
            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:153:12: ошибка: with «template<class T> td::CSlic                                    e::CSlice(T, int)»
   explicit CSlice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_                                    tag> = {})
            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h: In constructor «td::CSlice::CSlice(const td::Mut                                    ableCSlice&)»:
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:148:73: предупреждение: ISO C++ says that these a                                    re ambiguous, even though the worst conversion for the first is better than the worst conversion for t                                    he second: [по умолчанию включена]
   CSlice(const MutableCSlice &other) : Slice(other.begin(), other.size()) {
                                                                         ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:71:3: замечание: кандидат 1: td::Slice::Slice(con                                    st char*, td::size_t)
   Slice(const char *s, size_t len);
   ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:75:12: замечание: кандидат 2: td::Slice::Slice(T,                                     int) [with T = char*]
   explicit Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_t                                    ag> = {});
            ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:148:73: предупреждение: ISO C++ says that these a                                    re ambiguous, even though the worst conversion for the first is better than the worst conversion for t                                    he second: [по умолчанию включена]
   CSlice(const MutableCSlice &other) : Slice(other.begin(), other.size()) {
                                                                         ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:71:3: замечание: кандидат 1: td::Slice::Slice(con                                    st char*, td::size_t)
   Slice(const char *s, size_t len);
   ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice-decl.h:75:12: замечание: кандидат 2: td::Slice::Slice(T,                                     int) [with T = char*]
   explicit Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, private_t                                    ag> = {});
            ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:12:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/logging.h:27,
                 from /var/www/redmine/tdlib/tdutils/td/utils/Slice.h:11,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:12,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h: В функции «std::unique_ptr<td::Guard> td::create                                    _lambda_guard(F&&)»:
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h:62:10: ошибка: «make_unique» не является элементо                                    м «std»
   return std::make_unique<LambdaGuard<F>>(std::forward<F>(f));
          ^
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h:62:40: ошибка: expected primary-expression before                                     «>» token
   return std::make_unique<LambdaGuard<F>>(std::forward<F>(f));
                                        ^
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h: В функции «auto td::operator+(td::ScopeExit, Fun                                    ctionT&&)»:
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h:72:22: ошибка: «decay_t» не является элементом «s                                    td»
   return LambdaGuard<std::decay_t<FunctionT>>(std::forward<FunctionT>(func));
                      ^
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h:72:22: ошибка: «decay_t» не является элементом «s                                    td»
/var/www/redmine/tdlib/tdutils/td/utils/ScopeGuard.h:72:35: ошибка: некорректный аргумент шаблона 1
   return LambdaGuard<std::decay_t<FunctionT>>(std::forward<FunctionT>(func));
                                   ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/logging.h:27:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/Slice.h:11,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:12,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h: В функции «void td::detail::do_init_threa                                    d_local(P&, ArgsT&& ...)»:
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:46:14: ошибка: «make_unique» не является э                                    лементом «std»
   auto ptr = std::make_unique<T>(std::forward<ArgsT>(args)...);
              ^
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:46:32: ошибка: expected primary-expression                                     before «>» token
   auto ptr = std::make_unique<T>(std::forward<ArgsT>(args)...);
                                ^
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:46:59: ошибка: expected «)» before «...» t                                    oken
   auto ptr = std::make_unique<T>(std::forward<ArgsT>(args)...);
                                                           ^
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:46:62: ошибка: parameter packs not expande                                    d with «...»:
   auto ptr = std::make_unique<T>(std::forward<ArgsT>(args)...);
                                                              ^
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:46:62: замечание:         «args»
/var/www/redmine/tdlib/tdutils/td/utils/port/thread_local.h:46:62: замечание:         «ArgsT»
In file included from /var/www/redmine/tdlib/tdutils/td/utils/logging.h:30:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/Slice.h:11,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:12,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/StringBuilder.h: At global scope:
/var/www/redmine/tdlib/tdutils/td/utils/StringBuilder.h:132:1: ошибка: «enable_if_t» in namespace «st                                     » does not name a type
 std::enable_if_t<std::is_arithmetic<T>::value, string> to_string(const T &x) {
 ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:12:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:37:45: ошибка: «std::enable_if_t» не был декларирован
 inline MutableSlice::MutableSlice(T s, std::enable_if_t<std::is_same<char *, T>::value, private_tag>)                                     : s_(s) {
                                             ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:37:56: ошибка: expected «,» or «...» before «<» token
 inline MutableSlice::MutableSlice(T s, std::enable_if_t<std::is_same<char *, T>::value, private_tag>)                                     : s_(s) {
                                                        ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:162:31: ошибка: «std::enable_if_t» не был декларирован
 inline Slice::Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, privat                                    e_tag>) : s_(s) {
                               ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:162:42: ошибка: expected «,» or «...» before «<» token
 inline Slice::Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, privat                                    e_tag>) : s_(s) {
                                          ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:168:31: ошибка: «std::enable_if_t» не был декларирован
 inline Slice::Slice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value,                                     private_tag>)
                               ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:168:42: ошибка: expected «,» or «...» before «<» token
 inline Slice::Slice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value,                                     private_tag>)
                                          ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:168:8: ошибка: redefinition of «td::Slice::Slice(T, in                                    t)»
 inline Slice::Slice(T s, std::enable_if_t<std::is_same<const char *, std::remove_const_t<T>>::value,                                     private_tag>)
        ^
/var/www/redmine/tdlib/tdutils/td/utils/Slice.h:162:8: ошибка: «td::Slice::Slice(T, int)» previously d                                    eclared here
 inline Slice::Slice(T s, std::enable_if_t<std::is_same<char *, std::remove_const_t<T>>::value, privat                                    e_tag>) : s_(s) {
        ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.h:13:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:7:
/var/www/redmine/tdlib/tdutils/td/utils/Status.h:329:27: ошибка: «std::enable_if_t» не был декларирова                                    н
   template <class S, std::enable_if_t<!std::is_same<std::decay_t<S>, Result>::value, int> = 0>
                           ^
/var/www/redmine/tdlib/tdutils/td/utils/Status.h:329:38: ошибка: expected «>» before «<» token
   template <class S, std::enable_if_t<!std::is_same<std::decay_t<S>, Result>::value, int> = 0>
                                      ^
/var/www/redmine/tdlib/tdutils/td/utils/Status.h: В функции-члене «td::Result<td::CSlice> td::detail::                                    SlicifySafe::operator&(td::Logger&)»:
/var/www/redmine/tdlib/tdutils/td/utils/Status.h:455:29: ошибка: could not convert «(& logger)->td::Lo                                    gger::as_cslice()» from «td::MutableCSlice» to «td::Result<td::CSlice>»
     return logger.as_cslice();
                             ^
/var/www/redmine/tdlib/tdutils/td/utils/Status.h: В функции-члене «td::Result<std::basic_string<char>                                     > td::detail::StringifySafe::operator&(td::Logger&)»:
/var/www/redmine/tdlib/tdutils/td/utils/Status.h:465:35: ошибка: could not convert «td::MutableSlice::                                    str() const()» from «td::string {aka std::basic_string<char>}» to «td::Result<std::basic_string<char>                                     >»
     return logger.as_cslice().str();
                                   ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/format.h:10:0,
                 from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:10:
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h: At global scope:
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:58:8: ошибка: expected type-specifier
     -> std::enable_if_t<std::is_function<T>::value && std::is_base_of<Base, std::decay<Derived>>::val                                    ue,
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:58:8: ошибка: expected initializer
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:66:8: ошибка: expected type-specifier
     -> std::enable_if_t<std::is_function<T>::value && is_reference_wrapper<std::decay_t<RefWrap>>::va                                    lue,
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:66:8: ошибка: expected initializer
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:76:8: ошибка: expected type-specifier
     -> std::enable_if_t<std::is_function<T>::value && !is_reference_wrapper<std::decay_t<Pointer>>::v                                    alue &&
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:76:8: ошибка: expected initializer
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:84:8: ошибка: expected type-specifier
     -> std::enable_if_t<!std::is_function<T>::value && std::is_base_of<Base, std::decay_t<Derived>>::                                    value,
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:84:8: ошибка: expected initializer
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:91:8: ошибка: expected type-specifier
     -> std::enable_if_t<!std::is_function<T>::value && is_reference_wrapper<std::decay_t<RefWrap>>::v                                    alue,
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:91:8: ошибка: expected initializer
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:98:8: ошибка: expected type-specifier
     -> std::enable_if_t<!std::is_function<T>::value && !is_reference_wrapper<std::decay_t<Pointer>>::                                    value &&
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:98:8: ошибка: expected initializer
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:106:8: ошибка: expected type-specifier
     -> std::enable_if_t<!std::is_member_pointer<std::decay_t<F>>::value,
        ^
/var/www/redmine/tdlib/tdutils/td/utils/invoke.h:106:8: ошибка: expected initializer
In file included from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:10:0:
/var/www/redmine/tdlib/tdutils/td/utils/format.h: В функции «td::StringBuilder& td::format::operator<<                                    (td::StringBuilder&, const td::format::Concat<T>&)»:
/var/www/redmine/tdlib/tdutils/td/utils/format.h:289:43: ошибка: parameter declared «auto»
   tuple_for_each(concat.args, [&sb](auto &x) { sb << x; });
                                           ^
/var/www/redmine/tdlib/tdutils/td/utils/format.h: In lambda function:
/var/www/redmine/tdlib/tdutils/td/utils/format.h:289:54: ошибка: нет декларации «x» в этой области вид                                    имости
   tuple_for_each(concat.args, [&sb](auto &x) { sb << x; });
                                                      ^
In file included from /var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:12:0:
/var/www/redmine/tdlib/tdutils/td/utils/misc.h: В функции «auto td::transform(T&&, const Func&)»:
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:77:35: ошибка: «decay_t» не является элементом «std»
   return detail::transform_helper<std::decay_t<T>>().transform(std::forward<T>(v), f);
                                   ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:77:35: ошибка: «decay_t» не является элементом «std»
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:77:48: ошибка: некорректный аргумент шаблона 1
   return detail::transform_helper<std::decay_t<T>>().transform(std::forward<T>(v), f);
                                                ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:77:52: ошибка: expected primary-expression before «)» t                                    oken
   return detail::transform_helper<std::decay_t<T>>().transform(std::forward<T>(v), f);
                                                    ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h: В функции «void td::reset_to_empty(T&)»:
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:83:3: ошибка: «decay_t» не является элементом «std»
   std::decay_t<T> tmp;
   ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:83:17: ошибка: expected primary-expression before «>» t                                    oken
   std::decay_t<T> tmp;
                 ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:83:19: ошибка: нет декларации «tmp» в этой области види                                    мости
   std::decay_t<T> tmp;
                   ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h: At global scope:
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:197:1: ошибка: «enable_if_t» in namespace «std» does no                                    t name a type
 std::enable_if_t<std::is_signed<T>::value, T> to_integer(Slice str) {
 ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:225:1: ошибка: «enable_if_t» in namespace «std» does no                                    t name a type
 std::enable_if_t<std::is_unsigned<T>::value, T> to_integer(Slice str) {
 ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h: В функции «td::Result<T> td::to_integer_safe(td::Slice                                    )»:
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:237:14: ошибка: нет декларации «to_integer» в этой обла                                    сти видимости
   auto res = to_integer<T>(str);
              ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:237:26: ошибка: expected primary-expression before «>»                                     token
   auto res = to_integer<T>(str);
                          ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h: At global scope:
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:296:32: ошибка: «enable_if_t» не является элементом «st                                    d»
 struct safe_undeflying_type<T, std::enable_if_t<std::is_enum<T>::value>> {
                                ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:296:32: ошибка: «enable_if_t» не является элементом «st                                    d»
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:296:66: ошибка: несоответствия типа/значения в аргумент                                    е 2 в списке параметров шаблона для «template<class T, class Enable> struct td::detail::safe_undeflyin                                    g_type»
 struct safe_undeflying_type<T, std::enable_if_t<std::is_enum<T>::value>> {
                                                                  ^
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:296:66: ошибка:   ожидался тип, обнаружено «(<expressio                                    n error> < std::is_enum<_Tp>::value)»
/var/www/redmine/tdlib/tdutils/td/utils/misc.h:296:71: ошибка: expected unqualified-id before «>» toke                                    n
 struct safe_undeflying_type<T, std::enable_if_t<std::is_enum<T>::value>> {
                                                                       ^
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp: В функции-члене «td::Result<long unsigned int> td                                    ::Fd::write_unsafe(td::Slice)»:
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:286:41: ошибка: could not convert «td::detail::Nar                                    rowCast(((const char*)"/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp"), 286).td::detail::NarrowC                                    ast::cast<long unsigned int, long int>((*(const long int*)(& write_res)))» from «long unsigned int» to                                     «td::Result<long unsigned int>»
     return narrow_cast<size_t>(write_res);
                                         ^
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp: В функции-члене «td::Result<long unsigned int> td                                    ::Fd::write(td::Slice)»:
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:296:41: ошибка: could not convert «td::detail::Nar                                    rowCast(((const char*)"/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp"), 296).td::detail::NarrowC                                    ast::cast<long unsigned int, long int>((*(const long int*)(& write_res)))» from «long unsigned int» to                                     «td::Result<long unsigned int>»
     return narrow_cast<size_t>(write_res);
                                         ^
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:305:12: ошибка: could not convert «0» from «int» t                                    o «td::Result<long unsigned int>»
     return 0;
            ^
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp: В функции-члене «td::Result<long unsigned int> td                                    ::Fd::read(td::MutableSlice)»:
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:344:40: ошибка: could not convert «td::detail::Nar                                    rowCast(((const char*)"/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp"), 344).td::detail::NarrowC                                    ast::cast<long unsigned int, long int>((*(const long int*)(& read_res)))» from «long unsigned int» to                                     «td::Result<long unsigned int>»
     return narrow_cast<size_t>(read_res);
                                        ^
/var/www/redmine/tdlib/tdutils/td/utils/port/Fd.cpp:352:12: ошибка: could not convert «0» from «int» t                                    o «td::Result<long unsigned int>»
     return 0;
            ^
gmake[2]: *** [tdutils/CMakeFiles/tdutils.dir/td/utils/port/Fd.cpp.o] Ошибка 1
gmake[1]: *** [tdutils/CMakeFiles/tdutils.dir/all] Ошибка 2
gmake: *** [all] Ошибка 2

**Comment by tesey27** [comment]
[error.txt](https://github.com/tdlib/td/files/2595938/error.txt)

**Comment by levlam** [comment]
Something is wrong with C++14 support or C++ headers. Could you clean the build directory, re-configure CMake with  `cmake ..` and show the whole output of this invocation?

**Comment by tesey27** [comment]
[root@rm build]# cmake ..
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 5.3.1
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ccache
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")
-- Found OpenSSL: /usr/include /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Performing Test HAVE_STD14
-- Performing Test HAVE_STD14 - Failed
-- Performing Test HAVE_STD1Y
-- Performing Test HAVE_STD1Y - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WIMPLICIT_FALLTHROUGH_2
-- Performing Test HAVE_CXX_FLAG_WIMPLICIT_FALLTHROUGH_2 - Failed
-- Performing Test HAVE_CXX_FLAG_WPOINTER_ARITH
-- Performing Test HAVE_CXX_FLAG_WPOINTER_ARITH - Success
-- Performing Test HAVE_CXX_FLAG_WCAST_QUAL
-- Performing Test HAVE_CXX_FLAG_WCAST_QUAL - Success
-- Performing Test HAVE_CXX_FLAG_WSIGN_COMPARE
-- Performing Test HAVE_CXX_FLAG_WSIGN_COMPARE - Success
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_BRANCHES
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_BRANCHES - Failed
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_COND
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_COND - Failed
-- Performing Test HAVE_CXX_FLAG_WALLOC_ZERO
-- Performing Test HAVE_CXX_FLAG_WALLOC_ZERO - Failed
-- Performing Test HAVE_CXX_FLAG_WLOGICAL_OP
-- Performing Test HAVE_CXX_FLAG_WLOGICAL_OP - Success
-- Performing Test HAVE_CXX_FLAG_WTAUTOLOGICAL_COMPARE
-- Performing Test HAVE_CXX_FLAG_WTAUTOLOGICAL_COMPARE - Failed
-- Performing Test HAVE_CXX_FLAG_WVLA
-- Performing Test HAVE_CXX_FLAG_WVLA - Success
-- Performing Test HAVE_CXX_FLAG_WNON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_FLAG_WNON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_CXX_FLAG_WUNUSED_PARAMETER
-- Performing Test HAVE_CXX_FLAG_WUNUSED_PARAMETER - Success
-- Performing Test HAVE_CXX_FLAG_WCONVERSION
-- Performing Test HAVE_CXX_FLAG_WCONVERSION - Success
-- Performing Test HAVE_CXX_FLAG_WSIGN_CONVERSION
-- Performing Test HAVE_CXX_FLAG_WSIGN_CONVERSION - Success
-- Performing Test HAVE_CXX_FLAG_WCXX14_COMPAT_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_WCXX14_COMPAT_PEDANTIC - Failed
-- Performing Test HAVE_CXX_FLAG_WDEPRECATED
-- Performing Test HAVE_CXX_FLAG_WDEPRECATED - Success
-- Performing Test HAVE_CXX_FLAG_QUNUSED_ARGUMENTS
-- Performing Test HAVE_CXX_FLAG_QUNUSED_ARGUMENTS - Failed
-- Performing Test HAVE_CXX_FLAG_WODR
-- Performing Test HAVE_CXX_FLAG_WODR - Failed
-- Performing Test HAVE_CXX_FLAG_FLTO_ODR_TYPE_MERGING
-- Performing Test HAVE_CXX_FLAG_FLTO_ODR_TYPE_MERGING - Failed
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found ZLIB: /usr/include /usr/lib64/libz.so
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Performing Test GNU_READLINE_FOUND
-- Performing Test GNU_READLINE_FOUND - Success
-- Found Readline: /usr/include
-- Found Readline: /usr/include /usr/lib64/libreadline.so
-- Configuring done
-- Generating done
-- Build files have been written to: /var/www/redmine/tdlib/build

**Comment by tesey27** [comment]
Кажется ошибка здесь " The CXX compiler identification is GNU 4.8.5"? версия 4.8.5

**Comment by tesey27** [comment]
Но у меня установлен gcc 5.3.1

**Comment by levlam** [comment]
You can specify correct compiler path manually to CMake, i. e. use something like this: `CC=/usr/bin/gcc-5.3.1 CXX=/usr/bin/g++-5.3.1 cmake -DCMAKE_BUILD_TYPE=Release ..`.
