### ISSUE TITLE
Zero padding for scheme

### ISSUE THREAD

**Issue by DCjanus** [tdlib/td#411]
I am writing a TL scheme parser, on the page of ["﻿Formal description of TL language syntax"](https://core.telegram.org/mtproto/TL-formal), it told me:

```
lc-ident-full ::= lc-ident-ns [ # hex-digit *8 ] 
```

Which means, all constructor number for TL schema should be 8 hex digit character.

But some how, there is an exception: <https://github.com/tdlib/td/blob/d9a18a064fa99130dc9214fb6131ba59e5660892/td/generate/scheme/telegram_api.tl#L83>

I believe this problem is caused by the lack of "zero padding", because `crc_32("storage.fileJpeg = storage.FileType") => 007EFE0E`

**Comment by levlam** [comment]
Server-side [scheme](https://core.telegram.org/schema) doesn't use leading zeros. A long time ago it was decided to allow such notation in TL, and it was supported in [tl-parser](https://github.com/vysheng/tl-parser), but TL documentation wasn't updated accordingly. So you need to accept any number of characters between 1 and 8.
