### ISSUE TITLE
How to handle unpinned message event?

### ISSUE THREAD

**Issue by kossnocorp** [tdlib/td#412]
Hey,

I'm trying to handle pinned messages in a channel and can't get how to handle the unpinned message event.

When a message is pinned, I'm getting a message with `messagePinMessage` content, but there's no such event for the moment when a pinned message is unpinned. As I see Telegram for macOS somehow handles it, so I probably missed something.

Thanks!

**Comment by levlam** [comment]
There is no such event. Clients call `getSupergroupFullInfo` every time a supergroup is opened and get current pinned message in the result. But even there pinned message can be returned some time after it was unpinned.

**Comment by kossnocorp** [comment]
That's weird because I just put two laptops side by side logged in into different accounts with the same channel opened. On the first laptop I was pinning and unpinning a message, and it was reflecting in realtime on the second one. I'm curious how does it work?

**Comment by levlam** [comment]
You are right. There is an update from server about message unpinned, which is a part of `updateSupergroupFullInfo` in TDLib, but to receive it, you need to call `getSupegroupFullInfo` first.

**Comment by levlam** [comment]
It seems, that to receive that update you need to also have the chat opened or be the user, which unpinned the message.

**Comment by kossnocorp** [comment]
@levlam thank you for helping! What does open chat mean internally? Does it send some event? In my case, I run TDLib on a server and don't a chat to open ;-)

It will be great to have an event indicating that a message is unpinned.

**Comment by levlam** [comment]
In TDLib chat opening is done by calling `openChat`. A lot of server requests is done under the hood.

Message unpinning isn't associated with a message, so there is no way to reliably send it to all chat members (there can be 100000 of them in supergroups and unlimited number in channels). So the event is sent immediately only to users, who need it right now. All other users will receive it in `supergroupFullInfo` when the chat will be opened.
