### ISSUE TITLE
c# example - replymarkup is functioning ?

### ISSUE THREAD

**Issue by franc68** [tdlib/td#413]
Hi, in the c# example i'm not able to send an inlinekeyboard.
the code is exactly like the example 
  private static void sendMessage(long chatId, string message)
        {
            // initialize reply markup just for testing
            TdApi.InlineKeyboardButton[] row = { new TdApi.InlineKeyboardButton("https://telegram.org?1", new TdApi.InlineKeyboardButtonTypeUrl()), new TdApi.InlineKeyboardButton("https://telegram.org?2", new TdApi.InlineKeyboardButtonTypeUrl()), new TdApi.InlineKeyboardButton("https://telegram.org?3", new TdApi.InlineKeyboardButtonTypeUrl()) };
            TdApi.ReplyMarkup replyMarkup = new TdApi.ReplyMarkupInlineKeyboard(new TdApi.InlineKeyboardButton[][] { row, row, row });

            TdApi.InputMessageContent content = new TdApi.InputMessageText(new TdApi.FormattedText(message, null), false, true);
            _client.Send(new TdApi.SendMessage(chatId, 0, false, false, replyMarkup, content), _defaultHandler);
        }
What am I doing wrong?

**Comment by levlam** [comment]
You need to be a bot to be able to use ReplyMarkup. Ordinary users can't use it.

**Comment by Khwuanchai** [comment]
Aof​  Jackpot​
