### ISSUE TITLE
joinChatByInviteLink  failed

### ISSUE THREAD

**Issue by asok00000** [tdlib/td#415]
` send_query(td_api::make_object<td_api::joinChatByInviteLink>(joinLink),[this](Object object) {...}`
an error occured,the error message is "Wrong invite link"
 but when  I use the link can join via Telegram APP

**Comment by forconz** [comment]
@asok00000 

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1join_chat_by_invite_link.html

Invite link to import; should begin with "https://t.me/joinchat/", "https://telegram.me/joinchat/", or "https://telegram.dog/joinchat/".

Uses an invite link to add the current user to the chat if possible. The new member will not be added until the chat state has been synchronized with the server

The new member will not be added until the chat state has been synchronized with the server
**But how to do synchronize with the server?**

**Comment by levlam** [comment]
@forconz This phrase means that you must wait request response.

**Comment by Lua12138** [comment]
If a link is not begin with "https://t.me/joinchat/", "https://telegram.me/joinchat/", or "https://telegram.dog/joinchat/", like `https://t.me/publictestgroup`

How to use tdlib to join the chat ?
