### ISSUE TITLE
how to join group via link without joinchat 

### ISSUE THREAD

**Issue by asok00000** [tdlib/td#416]
like this:https://t.me/newbie_guide  which is public group

**Comment by asok00000** [comment]
first，search chat to get chat id
second, join chat by chat id 
join success

**Comment by Pauya** [comment]
> first，search chat to get chat id
> second, join chat by chat id
> join success

If you know the link(like "https://t.me/newbie_guide") only, how to search? What is the query content? Which method to invoke?
