### ISSUE TITLE
Limitation of Bot Api - 30 messages per second - can it be significantly increased with TDLib?

### ISSUE THREAD

**Issue by AndreyPolovodov** [tdlib/td#418]
Hello all, subj.. I need more messages per second in my bot - at least 100 times more - aproximately 3000 per second (to different users). Is it possible to complete this task using TDLib or not? What are limits for TDLib?
Thank you for responses.

**Comment by levlam** [comment]
All flood limits are server-side, so they can't be bypassed by using another Telegram API client instead of Bot API.

**Comment by Tom140931** [comment]
All flood limits are server-side, so they can't be bypassed by using another Telegram API client instead of Bot API.

**Comment by AndreyPolovodov** [comment]
So, is it correct - all limits about messages per second for the TDLib are exactly the same as for Bot API?

**Comment by levlam** [comment]
Yes.

**Comment by AndreyPolovodov** [comment]
Ok, thank you for reply,
