### ISSUE TITLE
Accept terms of service identifier

### ISSUE THREAD

**Issue by StagsGit** [tdlib/td#419]
Hello,
I want to accept telegram terms with lua throgh tdbot, 
What is terms_of_service_id exactly?
It is a string value

`acceptTermsOfService (std::string const &terms_of_service_id_)`

[https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1accept_terms_of_service.html#a0b156da5c174eddcba9d4eae4200b5af](url)

What thing should I put in it?
thanks

**Comment by levlam** [comment]
Currently, you need to call `acceptTermsOfService` only after receiving `updateTermsOfService`, which contains `terms_of_service_id`.

During authorization, user needs to accept ToS contained in `authorizationStateWaitCode`, and there is no need to additionally call `acceptTermsOfService`.

**Comment by StagsGit** [comment]
You mean that, if user doesn't accept `acceptTermsOfService` tdlib doesn't work?

**Comment by levlam** [comment]
During authorization they are accepted automatically, when user logs in: apps doesn't allow to proceed without accepting terms of service if necessary.

After `updateTermsOfService`, user needs to accept new terms of service or delete the account. Requests will work some time after `updateTermsOfService`, but may start to return an error if the user doesn't accept new terms of service.
