### ISSUE TITLE
Implementing payments via tdlib

### ISSUE THREAD

**Issue by isopen** [tdlib/td#42]
This is a question for developers and managers.

I found several classes associated with payments.
```
getPaymentForm
getPaymentReceipt
messagePaymentSuccessful
messagePaymentSuccessfulBot
paymentForm
paymentReceipt
paymentResult
paymentsProviderStripe
sendPaymentForm
```

For example.
As processing your tdlib and server side.
There is provider0, provider1, provider2, provider3, etc.

- Is the bot an provider?
- Can you transfer payments to providers?
- Can this replace the gateway for payments?

**Comment by levlam** [comment]
I can't understand what you are trying to achieve. You can try to find answers in description of the payments platform: https://core.telegram.org/bots/payments.

**Comment by isopen** [comment]
Oppsss. Thank you. This is the answer to all my questions. This is really cool a tool! Thank you.
