### ISSUE TITLE
Can't upload APNS development certificate (push certificate)

### ISSUE THREAD

**Issue by Demetriy** [tdlib/td#421]
Hi! 
Sorry, maybe it not 100% connected to tdlib, but i don't know better place to ask :)

Can't upload APNS development certificate in https://my.telegram.org/apps, all different variants returns no error (just page reload).

I tried this tip https://stackoverflow.com/questions/35515763/how-to-upload-apns-certificates-to-telegram-app-dashboard/36992167 and it works for production certificate, but can't do anything for development.

I would appreciate any help.

**Comment by levlam** [comment]
The certificate file should be valid, i.e. be 100B-100KB in size and have `-----BEGIN CERTIFICATE-----`, `-----END CERTIFICATE-----` and `-----BEGIN *PRIVATE KEY-----`, `-----END *PRIVATE KEY-----` sections.

**Comment by Demetriy** [comment]
Thank you for your response! 

I checked my certificates and they were correct, but i finally found a problem:
Here https://my.telegram.org/apps/apns_cert you can upload production or dev certificate or both, but if you want to upload only development certificate, then i think there were some validation error, but page will reload without any alerts.

When i uploaded both certificates, they finally successfully uploaded.
