### ISSUE TITLE
Directory containing TDlib sources

### ISSUE THREAD

**Issue by DjoleJ** [tdlib/td#423]
> 
> Building
> Install all TDLib dependencies as described in Installing dependencies. **Then enter directory containing TDLib sources** and compile them using CMake:
> 
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Release ..
> cmake --build .                                      

Where do I look for thatt directory cointaining TDlib sources and how can I find it?

**Comment by levlam** [comment]
You need to download TDLib sources from Github to build them. The directory, where you place the source files, is what you need.
For exmaple, you can do
```
git clone https://github.com/tdlib/td.git
cd td
```
to download TDLib source files and enter the directory.

**Comment by levlam** [comment]
@DjoleJ If you still have a problem with building TDLib, please take a look at a [TDLib build instructions generator](https://tdlib.github.io/td/build.html) for the exact build instructions.
