### ISSUE TITLE
[Question] Is this source code the latest?

### ISSUE THREAD

**Issue by l4rzy** [tdlib/td#424]
As I notice that tdlib on Telegram X is at version 1.3.2, but the latest release here is 1.3. I wonder if that was the way you guys doing versioning or the source code here is not the latest source code?
And in case of you're not publishing the latest source code here, may I ask why?
Thanks.

**Comment by levlam** [comment]
For now, we publish on Github only stable releases with finalized new TDLib's API after they are extensively tested in Telgram X, Bot API and Unigram and fully documented. TDLib 1.3.2, which is used in current Telegram X beta, has a lot of unstable API features, which can be frequently changed and improved. If you have a TDLIb's based Telegram client and want to test TDLib's versions with unstable API, you can ask for prebuilt TDLIb binaries through @tdlib_bot. But in that case you need to be ready for a lot of intermediate changes in the TDLib's API.

**Comment by l4rzy** [comment]
Thanks for informing me.
