### ISSUE TITLE
Translation Platform and custom languages

### ISSUE THREAD

**Issue by RadRussianRus** [tdlib/td#427]
Telegram now supports custom languages from Translation Platform. TDLib for now doesn't support it.

**Comment by zevlg** [comment]
It does actually.

You just need to set "localization_target" option (with `setOption`) and then request strings of any available language pack, using `getLanguagePackStrings`, for example:

```json
{"@type": "getLanguagePackStrings", "language_pack_id": "ru", "keys": []}
```

**Comment by levlam** [comment]
@RadRussianRus Support for unofficial language packs, available on Translation Platform, will be added to next TDLib version along with other new features.

**Comment by levlam** [comment]
Support for custom language packs downloaded from the server was added in TDLib 1.4.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
