### ISSUE TITLE
how to download file

### ISSUE THREAD

**Issue by Unix-Coder** [tdlib/td#428]
How to download file?
I use "DownloadFile" method but it not working
i using python

**Comment by levlam** [comment]
Call to `downloadFile` adds file to a list of files to be downloaded. Then you will receive `updateFile` updates with information about download progress. When the file is fully downloaded it will have `is_downloading_completed` field set to `true`. You can find more informatio about `downloadFile` in [TDLib documentation](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1download_file.html).

**Comment by Unix-Coder** [comment]
Thanks, the problem has been resolved
