### ISSUE TITLE
change location of folders [documents,music....]

### ISSUE THREAD

**Issue by Qasemt** [tdlib/td#43]
hi 
how do I change the **location** of folders (**documents,music,photos,profile_photos,.....**) ?

**Comment by levlam** [comment]
Currently, there is no way to change their location except specifying different files_directory in setTdlibParameters.

**Comment by Qasemt** [comment]
We hope، you will Add this **feature to tdlib** :-),we need set parameters before **launch per instance** of client,**so that each client has a special address folder**


```
instance of Client-1 
   .. /client1/music
   ../client1/photo
   ../client1/td.binlog
   
   
instance of Client-2 
   .. /client2/music
   ../client2/photo
   ../client2/td.binlog
```
   
 Thank you so much

**Comment by laitianxu** [comment]
hi Use TdApi.DownloadFile to download images to directory photos, Under what circumstances are images in the directory deleted,Is it the capacity of photos or the number of images,Is there any way to keep the image from being deleted

**Comment by levlam** [comment]
@laitianxu This is up to the application using TDLib. If tdlibParameters.use_storage_optimizer is false, then files are deleted only by explicit calls to `optimizeStorage` and `deleteFile`. In `optimizeStorage` application can choose any combination of total file size, total number of files, last access time, file creation time, file types, source chats to specify which files needs to be deleted.

**Comment by levlam** [comment]
@Qasemt "each client has a special address folder" is how `database_directory` and `files_directory` work now. Why they aren't sufficient for your needs?
