### ISSUE TITLE
[Missing] Pin message in Saved messages

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#430]

**Comment by zevlg** [comment]
Is it possible right now (in 1.3.0) to get pinned message (pinned using official client) for Saved Messages ?

Looks like `getChatPinnedMessage` returns 404

**Comment by levlam** [comment]
It is not possible, because old clients have no access to new API and have no way to get a pinned message in saved messages or in a basic group.

**Comment by levlam** [comment]
Ability to pin messages in saved messages was added in TDLib 1.4.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
