### ISSUE TITLE
run  example errors

### ISSUE THREAD

**Issue by jiangjun147** [tdlib/td#437]
i build the cpp and cshap example to run but have same errors

[ 1][t 2][1545103089.368324280][SslStream.cpp:254][!Wget]	Failed to add certificate
[ 1][t 2][1545103089.374813318][SslStream.cpp:254][!Wget]	Failed to add certificate
[ 1][t 2][1545103089.375215769][SslStream.cpp:161][!Connect]	Before SslFd::read: [Error : 0 : Unprocessed OPENSSL_ERROR{error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table}
                                                                                                                          {error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table}]

**Comment by levlam** [comment]
You have duplicated certificates in Windows trust store. These errors has no bad consequences and can be safely ignored.

**Comment by jiangjun147** [comment]
But it prevents the program from continuing to run.

**Comment by jiangjun147** [comment]
> You have duplicated certificates in Windows trust store. These errors has no bad consequences and can be safely ignored.

But it prevents the program from continuing to run.

**Comment by jiangjun147** [comment]
can you fix the problem？

**Comment by levlam** [comment]
No, it doesn't prevent program from continuing to run.. These errors change nothing in the program behavior. You are likely to have some unrelated problems with connecting to Telegram servers,

**Comment by jiangjun147** [comment]
ok Thanks ！ I am in China maybe the firewall prevent connection。so i must use addProxy api  ？

**Comment by levlam** [comment]
Yes.
