### ISSUE TITLE
Executing SetTdlibParameters is not responding

### ISSUE THREAD

**Issue by zx925745591** [tdlib/td#438]
Executing SetTdlibParameters is not responding
log：
[ 3][t 4][1545190041.650608301][Td.cpp:4238][!Td][&td_requests]	Sending update: UpdateAuthorizationState {
  authorizationState = AuthorizationStateWaitTdlibParameters {
  }
}
code：
client.send(new TdApi.SetTdlibParameters(parameters), new DefaultHandler());

**Comment by jiangjun147** [comment]
you can use the example to test

**Comment by levlam** [comment]
@zx925745591 Please, provide complete example of your code, which doesn't work.
Is it changed our Java [example](https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java)?

**Comment by zx925745591** [comment]
> @ zx925745591请提供完整的代码清单，但不起作用。
> 它是从我们的Java [示例](https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java)派生的吗？

The sample code works fine, but embedding the code into the spring boot project starts unresponsive. Note: The .so file has been placed in the resources file directory.

code：
[PacketGroupSerivce.txt](https://github.com/tdlib/td/files/2697075/PacketGroupSerivce.txt)

**Comment by zx925745591** [comment]
Solved, thanks for the help
