### ISSUE TITLE
error while building the library for iOS

### ISSUE THREAD

**Issue by Alex19881222** [tdlib/td#440]
I installed all dependencies
And I ran the following command

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ ..

And then ran the build-openssl.sh in ios directory
it's Okay here.
but while running the build.sh, I got an error like this.

...
[ 99%] Building CXX object CMakeFiles/tdjson_static.dir/td/telegram/td_log.cpp.o
[100%] Linking CXX shared library libtdjson.dylib
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
ld: warning: ignoring file ../../third_party/openssl/iOS/lib/libssl.a, missing required architecture armv7 in file ../../third_party/openssl/iOS/lib/libssl.a (2 slices)
ld: warning: ignoring file ../../third_party/openssl/iOS/lib/libcrypto.a, missing required architecture armv7 in file ../../third_party/openssl/iOS/lib/libcrypto.a (2 slices)
[100%] Linking CXX static library libtdjson_static.a
[100%] Built target tdjson_static
Undefined symbols for architecture armv7:
  "_EVP_CIPHER_block_size", referenced from:
      _sqlcipher_openssl_get_block_sz in libtdsqlite.a(sqlite3.c.o)
  "_EVP_CIPHER_nid", referenced from:
      _sqlcipher_openssl_get_cipher in libtdsqlite.a(sqlite3.c.o)
  "_EVP_CipherUpdate", referenced from:
      _sqlcipher_openssl_cipher in libtdsqlite.a(sqlite3.c.o)
  "_EVP_CIPHER_CTX_free", referenced from:
      _sqlcipher_openssl_cipher in libtdsqlite.a(sqlite3.c.o)
  "_HMAC_CTX_init", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_HMAC_Update", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_EVP_CIPHER_iv_length", referenced from:
      _sqlcipher_openssl_get_iv_sz in libtdsqlite.a(sqlite3.c.o)
  "_EVP_CipherFinal_ex", referenced from:
      _sqlcipher_openssl_cipher in libtdsqlite.a(sqlite3.c.o)
  "_HMAC_Final", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_HMAC_CTX_cleanup", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_EVP_cleanup", referenced from:
      _sqlcipher_openssl_deactivate in libtdsqlite.a(sqlite3.c.o)
  "_SSL_get_error", referenced from:
      td::detail::SslStreamImpl::process_ssl_error(int) in libtdnet.a(SslStream.cpp.o)
  "_SSL_shutdown", referenced from:
      td::detail::SslStreamImpl::~SslStreamImpl() in libtdnet.a(SslStream.cpp.o)
  "_HMAC_Init_ex", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_SSL_free", referenced from:
      td::detail::SslStreamImpl::~SslStreamImpl() in libtdnet.a(SslStream.cpp.o)
  "_BIO_set_flags", referenced from:
      td::detail::(anonymous namespace)::strm_read(bio_st*, char*, int) in libtdnet.a(SslStream.cpp.o)
  "_X509_get_subject_name", referenced from:
      td::detail::(anonymous namespace)::verify_callback(int, x509_store_ctx_st*) in libtdnet.a(SslStream.cpp.o)
  "_SSL_read", referenced from:
      td::detail::SslStreamImpl::SslReadByteFlow::loop() in libtdnet.a(SslStream.cpp.o)
  "_ERR_peek_error", referenced from:
      td::detail::(anonymous namespace)::openssl_clear_errors(td::Slice) in libtdnet.a(SslStream.cpp.o)
      td::detail::SslStreamImpl::process_ssl_error(int) in libtdnet.a(SslStream.cpp.o)
  "_X509_NAME_oneline", referenced from:
      td::detail::(anonymous namespace)::verify_callback(int, x509_store_ctx_st*) in libtdnet.a(SslStream.cpp.o)
  "_X509_STORE_CTX_get_error", referenced from:
      td::detail::(anonymous namespace)::verify_callback(int, x509_store_ctx_st*) in libtdnet.a(SslStream.cpp.o)
  "_X509_verify_cert_error_string", referenced from:
      td::detail::(anonymous namespace)::verify_callback(int, x509_store_ctx_st*) in libtdnet.a(SslStream.cpp.o)
  "_SSL_CTX_ctrl", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_EVP_PKEY_CTX_new", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_SSL_CTX_load_verify_locations", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_SSL_CTX_set_verify", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_EVP_CIPHER_key_length", referenced from:
      _sqlcipher_openssl_get_key_sz in libtdsqlite.a(sqlite3.c.o)
  "_SSLv23_client_method", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_EVP_PKEY_encrypt_init", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_SSL_get0_param", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_EVP_sha256", referenced from:
      td::pbkdf2_sha256(td::Slice, td::Slice, int, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
      td::hmac_sha256(td::Slice, td::Slice, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_SSL_ctrl", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_PKCS5_PBKDF2_HMAC", referenced from:
      td::pbkdf2_impl(td::Slice, td::Slice, int, td::MutableSlice, env_md_st const*) in libtdutils.a(crypto.cpp.o)
  "_SSL_set_connect_state", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_SSL_CTX_free", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
      td::detail::SslStreamImpl::~SslStreamImpl() in libtdnet.a(SslStream.cpp.o)
  "_BN_bn2bin", referenced from:
      td::BigNum::to_binary(int) const in libtdutils.a(BigNum.cpp.o)
  "_SSL_load_error_strings", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_SSL_library_init", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BN_div", referenced from:
      td::BigNum::div(td::BigNum*, td::BigNum*, td::BigNum const&, td::BigNum const&, td::BigNumContext&) in libtdutils.a(BigNum.cpp.o)
  "_RSA_new", referenced from:
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_BN_is_bit_set", referenced from:
      td::BigNum::is_bit_set(int) const in libtdutils.a(BigNum.cpp.o)
  "_RAND_add", referenced from:
      td::Random::add_seed(td::Slice, double) in libtdutils.a(Random.cpp.o)
      _sqlcipher_openssl_add_random in libtdsqlite.a(sqlite3.c.o)
  "_RAND_bytes", referenced from:
      td::Random::secure_bytes(unsigned char*, unsigned long) in libtdutils.a(Random.cpp.o)
      _sqlcipher_openssl_random in libtdsqlite.a(sqlite3.c.o)
  "_BN_mod_exp", referenced from:
      td::BigNum::mod_exp(td::BigNum&, td::BigNum const&, td::BigNum const&, td::BigNum const&, td::BigNumContext&) in libtdutils.a(BigNum.cpp.o)
  "_EVP_PKEY_free", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_X509_VERIFY_PARAM_set_hostflags", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_SSL_CTX_new", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BIO_vfree", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_BN_mul", referenced from:
      td::BigNum::mul(td::BigNum&, td::BigNum&, td::BigNum&, td::BigNumContext&) in libtdutils.a(BigNum.cpp.o)
  "_BN_gcd", referenced from:
      td::BigNum::gcd(td::BigNum&, td::BigNum&, td::BigNum&, td::BigNumContext&) in libtdutils.a(BigNum.cpp.o)
  "_BN_sub", referenced from:
      td::BigNum::sub(td::BigNum&, td::BigNum const&, td::BigNum const&) in libtdutils.a(BigNum.cpp.o)
  "_RSA_size", referenced from:
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_BN_add", referenced from:
      td::BigNum::add(td::BigNum&, td::BigNum const&, td::BigNum const&) in libtdutils.a(BigNum.cpp.o)
  "_BN_rand", referenced from:
      td::BigNum::random(td::BigNum&, int, int, int) in libtdutils.a(BigNum.cpp.o)
  "_SSL_CTX_set_verify_depth", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BN_bn2dec", referenced from:
      td::BigNum::to_decimal() const in libtdutils.a(BigNum.cpp.o)
  "_X509_STORE_CTX_get_error_depth", referenced from:
      td::detail::(anonymous namespace)::verify_callback(int, x509_store_ctx_st*) in libtdnet.a(SslStream.cpp.o)
  "_CRYPTO_free", referenced from:
      td::BigNum::to_decimal() const in libtdutils.a(BigNum.cpp.o)
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_BN_dup", referenced from:
      td::BigNum::clone() const in libtdutils.a(BigNum.cpp.o)
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_SSL_set_bio", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BN_set_word", referenced from:
      td::BigNum::set_value(unsigned int) in libtdutils.a(BigNum.cpp.o)
  "_BN_dec2bn", referenced from:
      td::BigNum::from_decimal(td::CSlice) in libtdutils.a(BigNum.cpp.o)
  "_BN_mod_mul", referenced from:
      td::BigNum::mod_mul(td::BigNum&, td::BigNum&, td::BigNum&, td::BigNum const&, td::BigNumContext&) in libtdutils.a(BigNum.cpp.o)
  "_BN_mod_word", referenced from:
      td::BigNum::operator%(unsigned int) const in libtdutils.a(BigNum.cpp.o)
  "_BN_div_word", referenced from:
      td::BigNum::operator/=(unsigned int) in libtdutils.a(BigNum.cpp.o)
  "_X509_VERIFY_PARAM_set1_host", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BN_set_bit", referenced from:
      td::BigNum::set_bit(int) in libtdutils.a(BigNum.cpp.o)
  "_BN_bin2bn", referenced from:
      td::BigNum::from_binary(td::Slice) in libtdutils.a(BigNum.cpp.o)
  "_CRYPTO_malloc", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
  "_AES_set_encrypt_key", referenced from:
      td::aes_ige_xcrypt(td::UInt<256ul> const&, td::UInt<256ul>*, td::Slice, td::MutableSlice, bool) in libtdutils.a(crypto.cpp.o)
      td::aes_cbc_xcrypt(td::UInt<256ul> const&, td::UInt<128ul>*, td::Slice, td::MutableSlice, bool) in libtdutils.a(crypto.cpp.o)
      td::AesCtrState::init(td::UInt<256ul> const&, td::UInt<128ul> const&) in libtdutils.a(crypto.cpp.o)
  "_SSL_CTX_set_default_verify_paths", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BN_copy", referenced from:
      td::BigNum::operator=(td::BigNum const&) in libtdutils.a(BigNum.cpp.o)
  "_BN_clear_free", referenced from:
      td::BigNum::operator=(td::BigNum&&) in libtdutils.a(BigNum.cpp.o)
      td::BigNum::~BigNum() in libtdutils.a(BigNum.cpp.o)
      td::BigNum::from_decimal(td::CSlice) in libtdutils.a(BigNum.cpp.o)
  "_SSL_state", referenced from:
      td::detail::SslStreamImpl::~SslStreamImpl() in libtdnet.a(SslStream.cpp.o)
  "_CRYPTO_THREADID_set_pointer", referenced from:
      td::(anonymous namespace)::openssl_threadid_callback(crypto_threadid_st*) in libtdutils.a(crypto.cpp.o)
  "_SHA1", referenced from:
      td::sha1(td::Slice, unsigned char*) in libtdutils.a(crypto.cpp.o)
  "_CRYPTO_get_locking_callback", referenced from:
      td::init_openssl_threads() in libtdutils.a(crypto.cpp.o)
  "_OBJ_nid2sn", referenced from:
      _sqlcipher_openssl_get_cipher in libtdsqlite.a(sqlite3.c.o)
  "_PKCS5_PBKDF2_HMAC_SHA1", referenced from:
      _sqlcipher_openssl_kdf in libtdsqlite.a(sqlite3.c.o)
  "_RSA_free", referenced from:
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_X509_STORE_CTX_get_current_cert", referenced from:
      td::detail::(anonymous namespace)::verify_callback(int, x509_store_ctx_st*) in libtdnet.a(SslStream.cpp.o)
  "_ERR_get_error", referenced from:
      td::detail::(anonymous namespace)::create_openssl_error(int, td::Slice) in libtdnet.a(SslStream.cpp.o)
  "_EVP_PKEY_CTX_free", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_AES_set_decrypt_key", referenced from:
      td::aes_ige_xcrypt(td::UInt<256ul> const&, td::UInt<256ul>*, td::Slice, td::MutableSlice, bool) in libtdutils.a(crypto.cpp.o)
      td::aes_cbc_xcrypt(td::UInt<256ul> const&, td::UInt<128ul>*, td::Slice, td::MutableSlice, bool) in libtdutils.a(crypto.cpp.o)
  "_BN_CTX_new", referenced from:
      td::BigNumContext::BigNumContext() in libtdutils.a(BigNum.cpp.o)
  "_BIO_new_mem_buf", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_BIO_free", referenced from:
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_EVP_get_cipherbyname", referenced from:
      _sqlcipher_openssl_activate in libtdsqlite.a(sqlite3.c.o)
      _sqlcipher_openssl_set_cipher in libtdsqlite.a(sqlite3.c.o)
  "_EVP_PKEY_type", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_EVP_CIPHER_CTX_new", referenced from:
      _sqlcipher_openssl_cipher in libtdsqlite.a(sqlite3.c.o)
  "_BN_num_bits", referenced from:
      td::BigNum::get_num_bits() const in libtdutils.a(BigNum.cpp.o)
      td::BigNum::to_binary(int) const in libtdutils.a(BigNum.cpp.o)
  "_SSL_new", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_BN_add_word", referenced from:
      td::BigNum::operator+=(unsigned int) in libtdutils.a(BigNum.cpp.o)
  "_EVP_sha1", referenced from:
      _sqlcipher_openssl_hmac in libtdsqlite.a(sqlite3.c.o)
      _sqlcipher_openssl_get_hmac_sz in libtdsqlite.a(sqlite3.c.o)
  "_SHA512", referenced from:
      td::sha512(td::Slice, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_CRYPTO_set_locking_callback", referenced from:
      td::init_openssl_threads() in libtdutils.a(crypto.cpp.o)
  "_HMAC", referenced from:
      td::hmac_sha256(td::Slice, td::Slice, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_EVP_PKEY_encrypt", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_SHA256_Final", referenced from:
      td::sha256_final(td::Sha256State*, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_EVP_sha512", referenced from:
      td::pbkdf2_sha512(td::Slice, td::Slice, int, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_BN_sub_word", referenced from:
      td::BigNum::operator-=(unsigned int) in libtdutils.a(BigNum.cpp.o)
  "_EVP_CipherInit_ex", referenced from:
      _sqlcipher_openssl_cipher in libtdsqlite.a(sqlite3.c.o)
  "_PEM_read_bio_PUBKEY", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_BIO_clear_flags", referenced from:
      td::detail::(anonymous namespace)::strm_write(bio_st*, char const*, int) in libtdnet.a(SslStream.cpp.o)
      td::detail::(anonymous namespace)::strm_read(bio_st*, char*, int) in libtdnet.a(SslStream.cpp.o)
  "_CRYPTO_THREADID_set_callback", referenced from:
      td::init_openssl_threads() in libtdutils.a(crypto.cpp.o)
  "_BIO_new", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_SSL_write", referenced from:
      td::detail::SslStreamImpl::SslWriteByteFlow::loop() in libtdnet.a(SslStream.cpp.o)
  "_AES_cbc_encrypt", referenced from:
      td::aes_cbc_xcrypt(td::UInt<256ul> const&, td::UInt<128ul>*, td::Slice, td::MutableSlice, bool) in libtdutils.a(crypto.cpp.o)
  "_AES_ige_encrypt", referenced from:
      td::aes_ige_xcrypt(td::UInt<256ul> const&, td::UInt<256ul>*, td::Slice, td::MutableSlice, bool) in libtdutils.a(crypto.cpp.o)
  "_SHA256", referenced from:
      td::sha256(td::Slice, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_EVP_CIPHER_CTX_set_padding", referenced from:
      _sqlcipher_openssl_cipher in libtdsqlite.a(sqlite3.c.o)
  "_ERR_error_string_n", referenced from:
      td::detail::(anonymous namespace)::create_openssl_error(int, td::Slice) in libtdnet.a(SslStream.cpp.o)
  "_SHA256_Init", referenced from:
      td::sha256_init(td::Sha256State*) in libtdutils.a(crypto.cpp.o)
  "_AES_encrypt", referenced from:
      td::AesCtrState::Impl::encrypt(td::Slice, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_PEM_read_bio_RSAPublicKey", referenced from:
      td::RSA::from_pem(td::Slice) in libtdcore.a(crypto.cpp.o)
  "_EVP_PKEY_CTX_ctrl", referenced from:
      td::rsa_encrypt_pkcs1_oaep(td::Slice, td::Slice) in libtdutils.a(crypto.cpp.o)
  "_BN_cmp", referenced from:
      td::BigNum::compare(td::BigNum const&, td::BigNum const&) in libtdutils.a(BigNum.cpp.o)
  "_BN_CTX_free", referenced from:
      td::BigNumContext::operator=(td::BigNumContext&&) in libtdutils.a(BigNum.cpp.o)
      td::BigNumContext::~BigNumContext() in libtdutils.a(BigNum.cpp.o)
  "_SSL_set_quiet_shutdown", referenced from:
      td::detail::SslStreamImpl::~SslStreamImpl() in libtdnet.a(SslStream.cpp.o)
  "_SSL_CTX_set_cipher_list", referenced from:
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      td::init_crypto() in libtdutils.a(crypto.cpp.o)
      td::detail::SslStreamImpl::init(td::CSlice, td::CSlice, td::SslStream::VerifyPeer) in libtdnet.a(SslStream.cpp.o)
      _sqlcipher_openssl_activate in libtdsqlite.a(sqlite3.c.o)
  "_EVP_MD_size", referenced from:
      td::pbkdf2_impl(td::Slice, td::Slice, int, td::MutableSlice, env_md_st const*) in libtdutils.a(crypto.cpp.o)
      _sqlcipher_openssl_get_hmac_sz in libtdsqlite.a(sqlite3.c.o)
  "_BN_new", referenced from:
      td::BigNum::BigNum() in libtdutils.a(BigNum.cpp.o)
      td::BigNum::BigNum(td::BigNum const&) in libtdutils.a(BigNum.cpp.o)
      td::BigNum::from_decimal(td::CSlice) in libtdutils.a(BigNum.cpp.o)
  "_MD5", referenced from:
      td::md5(td::Slice, td::MutableSlice) in libtdutils.a(crypto.cpp.o)
  "_BN_is_prime_ex", referenced from:
      td::BigNum::is_prime(td::BigNumContext&) const in libtdutils.a(BigNum.cpp.o)
  "_CRYPTO_num_locks", referenced from:
      td::(anonymous namespace)::openssl_locking_function(int, int, char const*, int) in libtdutils.a(crypto.cpp.o)
  "_SHA256_Update", referenced from:
      td::sha256_update(td::Slice, td::Sha256State*) in libtdutils.a(crypto.cpp.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libtdjson.dylib] Error 1
make[1]: *** [CMakeFiles/tdjson.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library libtdc.a
[100%] Built target tdc
make: *** [all] Error 2

How can I fix it?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/372#issuecomment-443405142.

**Comment by levlam** [comment]
Fixed in TDLib 1.4.0.
