### ISSUE TITLE
not issue, but help wanted

### ISSUE THREAD

**Issue by Alex19881222** [tdlib/td#442]
Hi
I have built the libtdjson.dylib and linked it iOS project.
For now I need simple demo for auth, chat.
I want you provide it...
Thank you.

**Comment by levlam** [comment]
You can look at our [Swift example](https://github.com/tdlib/td/blob/master/example/swift/src/main.swift), which implements authorization. There is also a lot of helpful links in [README](https://github.com/tdlib/td#examples-and-documentation), for example, link to [Getting Started](https://core.telegram.org/tdlib/getting-started) tutorial.

**Comment by Alex19881222** [comment]
Hi
How can I use td_api in swift?
if possible, please provide the example

Thank you

**Comment by levlam** [comment]
https://github.com/tdlib/td/tree/master/example/swift
