### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by EeeasyBreezy** [tdlib/td#444]
Hello, everyone!
I have an issue while trying to build TDLib under Windows 10
My output is:
"E:\Browser downloads\td-master\td-master\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (1) ->
"E:\Browser downloads\td-master\td-master\build\test\all_tests.vcxproj" (целевой объект по умолчанию) (3) ->
"E:\Browser downloads\td-master\td-master\build\tdactor\tdactor.vcxproj" (целевой объект по умолчанию) (4) ->
"E:\Browser downloads\td-master\td-master\build\tdutils\tdutils.vcxproj" (целевой объект по умолчанию) (5) ->
"E:\Browser downloads\td-master\td-master\build\tdutils\generate\tdmime_auto.vcxproj" (целевой объект по умолчанию) (6)
 ->
(CustomBuild конечный объект) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(20
9,5): error MSB6006: "cmd.exe" exited with code 4. [E:\Browser downloads\td-master\td-master\build\tdutils\generate\
tdmime_auto.vcxproj]

It was said here https://github.com/tdlib/td/issues/31 that is because gperf is not installed or the location of gperf was not add to PATH variable.
I double checked that gperf is installed exactly (not sed), location of gperf is in PATH variable.

Also, according to issue 31 the following command 

`powershell -ExecutionPolicy ByPass " & gperf -m100 --output-file=auto/mime_type_to_extension.cpp auto/mime_type_to_extension.gperf`

gives me an error of invalid syntax:
If option -e, expression, -f or --file are not set, then forst non optional argument is taken as sed-script for interpretation. Other arguments are input file names; if there are no file names then stdin is read

I've run command from <path to TDLib sources>/tdutils/generate/

I use gperf version 3.0.1

**Comment by levlam** [comment]
Which Shell application do you use?

Do you have Windows PowerShell installed?

Between, there should be `"` at the end of the command, i.e. `powershell -ExecutionPolicy ByPass " & gperf -m100 --output-file=auto/mime_type_to_extension.cpp auto/mime_type_to_extension.gperf"`.

**Comment by levlam** [comment]
This command should work in both cmd and PowerShell and output nothing, just create the file `auto/mime_type_to_extension.cpp` after a while.

**Comment by levlam** [comment]
@EeeasyBreezy I hope that you have managed to successfully build TDLib. If this isn't the case, please take a look at a [TDLib build instructions generator](https://tdlib.github.io/td/build.html) for the exact build instructions.
