### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Lb0728** [tdlib/td#446]
Novice iOS development, is there an oc demo?

**Comment by levlam** [comment]
We have no iOS demo project for now, only example scripts which builds a static/dynamic library for [iOS](https://github.com/tdlib/td/tree/master/example/ios).

**Comment by Lb0728** [comment]
Hello, the dynamic library is generated, how to build iOS, is there a corresponding document?

**Comment by levlam** [comment]
What exactly do you want to build? Dynamic library `libtdjson.dylib` is already built TDLib, which can be used from an iOS application. It can be used directly or wrapped into a framework if the application needs to be submitted to App Store.

**Comment by Lb0728** [comment]
Hello, I want to integrate tdlib into my project, I have compiled tdlib, but I did not find the corresponding document, to tell how to initialize, how to call the method to get authorization, get chat data

**Comment by levlam** [comment]
You need to start from reading [Getting Started](https://core.telegram.org/tdlib/getting-started) and then continue with the rest of [documentation](https://core.telegram.org/tdlib/docs/#usage).
