### ISSUE TITLE
Execute the joinchat and prompt "Can't unrestrict self".

### ISSUE THREAD

**Issue by zx925745591** [tdlib/td#448]
Execute the joinchat and prompt "Can't unrestrict self".

**Comment by levlam** [comment]
Could you show result of `getChatMemberStatus` for self in the chat?

**Comment by levlam** [comment]
It seems that there are issues with `joinChat` due to server-side change. You can use `addChatMember` with self instead to join a chat.

**Comment by Mike497** [comment]
Hi, 'im getting the same issue.

**Comment by Mike497** [comment]
Yes, join chat works fine with addChatMember.
@levlam , could you please help a bit with meaning of "forwardLimit" param for addChatMember? I'm not sure what is the correct value for it? "1" - looks correct but won't there be any problems later?

**Comment by levlam** [comment]
When you join a chat self via `addChatMember`, forwardLimit is competely ignored.

**Comment by zx925745591** [comment]
thanks
