### ISSUE TITLE
Builds for android for python

### ISSUE THREAD

**Issue by sanodin** [tdlib/td#449]
Hello, tell me how to assemble, or maybe use ready? libtdjson.so works great on linux, but does not work on android ""/home/kivy/4/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/__init__.py", line 356, in __init__
OSError: dlopen failed: "/data/data/org.bte.bte/files/lib/libtdjson.so" is 64-bit instead of 32-bit"

 libtdjni.so error "" /home/kivy/4/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/__init__.py ", line 374, in __getitem__
AttributeError: undefined symbol: td_json_client_create "
Well, it's understandable, these functions are not there, And written for java.

Or should libtdjson.so be built for Android?
I want to use in the project on Kivy.
And there is ready assembled libtdjson.so for Android?

**Comment by levlam** [comment]
libtdjson.so should be built using Android NDK to be used on Android. Prebuilt Android library provides only JNI interface, so if you want JSON to use JSON interface, you need to build it manually. It is definitely possible, but you will likely need to write a small CMakeLists.txt file for Android Studio like described in https://developer.android.com/studio/projects/configure-cmake. You will also need to first build OpenSSL for Android.

**Comment by sanodin** [comment]
Thank.
JNI interface, did not find a description of the methods?
createNativeClient
Client_createNativeClient
in the example that are missing in the assembled library.
"AttributeError: undefined symbol:"
Or am I looking there?

**Comment by sanodin** [comment]
This is already understood, thank you.
So I will try to collect JSON.
Although not sure what happens.
Thank you

**Comment by sanodin** [comment]
For iOS, there is an example of an assembly, maybe for Android, post an example of an assembly libtdjson?

**Comment by levlam** [comment]
We may add such example in a future along with example of building Java interface for Android, but given existence of prebuilt Android Java binaries, it is not a priority.

**Comment by kudo108** [comment]
> This is already understood, thank you.
> So I will try to collect JSON.
> Although not sure if I can do it.
> Thank you

I'm trying to build for android, using JSON c++ interface, but still can not build through Cmake. If you can build for android, please give me some instruction, thank you very much!

**Comment by levlam** [comment]
Now you can use the [Android example](https://github.com/tdlib/td/tree/master/example/android) to build TDLib with JSON interface for Android.
