### ISSUE TITLE
on windows,WaitForMultipleObjects just support 64 events

### ISSUE THREAD

**Issue by sunwangme** [tdlib/td#45]
on windows,  poll::run just scan fds，and invoke WaitForMultipleObjects. how about add fatal log if >64, or invoke WaitForMultipleObjects by 64 for many times

**Comment by levlam** [comment]
Fatal log is already here:
```
  if (status == WAIT_FAILED) {
    auto error = OS_ERROR("WaitForMultipleObjects failed");
    LOG(FATAL) << events.size() << " " << timeout_ms << " " << error;
  }
```

Is number of awaited fds exceeds 64 for you?

**Comment by sunwangme** [comment]
yes

**Comment by levlam** [comment]
64 awaitable descriptors supposed to be enough for one TDLib client instance. Are you using one TDLib instance in the process or trying to use many of them? Is it happens after some particular sequence of actions?
