### ISSUE TITLE
After entering login code nothing happens

### ISSUE THREAD

**Issue by alexplisov** [tdlib/td#451]
Hello everyone!

When I try to login with my own phone number everything works fine. I receive code and after entering it an app fetches first 10 chats. When I try to use my friends phone, nothing happens after entering code. No error messages. What can be the problem?

Thanks in advance!

**Comment by levlam** [comment]
What code do you use?
Is there an error returned by the checkAuthenticationCode request?
Are there mentions of network connection problems in TDLib's log after increasing verbosity level?

**Comment by alexplisov** [comment]
> What code do you use?
I'm using https://github.com/Bannerets/tdl tdlib wrapper for nodejs.
> Is there an error returned by the checkAuthenticationCode request?
No errors are present. TDLib doesn't display any information. Problem occurres only for certain phone numbers. Can it be approaching of maximum amount of sessions?
> Are there mentions of network connection problems in TDLib's log after increasing verbosity level?
Which flag should I use in order to increase verbosity level? Does ffi support it?

Thanks for reply.

**Comment by levlam** [comment]
There is no "maximum amount of sessions".

This wrapper has option `verbosityLevel`: https://github.com/Bannerets/tdl#options.
You can set it to 3 or 12 (to get more мукищыу logging) to find the cause.

**Comment by alexplisov** [comment]
My friend was sending me his auth code via telegram. It was triggering this error:  

> [ 3][t 4][1547048682.087437868][NetQuery.h:302][!Session:2:main][&net_query]   Got error [Query:[id:262144][tl:0xbcd51581][state:Query]] [Error : 400 : PHONE_CODE_EXPIRED] 

We tried different way and it worked. Thank you!

**Comment by nas-pras** [comment]
Hi @alexplisov 
can you share what you did and how you resolved this problem?

thanks

**Comment by alexplisov** [comment]
Hi, @vrum4o

Just don't send your auth code in telegram message. Share it if you need via other app. That's it.

Cheers
