### ISSUE TITLE
Please publish TDLib 1.3.2

### ISSUE THREAD

**Issue by ReimuNotMoe** [tdlib/td#452]
Please publish TDLib 1.3.2, or at least tell us where to get its source code.

#424 
I searched and contacted 3 bots, `tdlib_bot`, `tdlibbot`, and `tdlib_test_bot`, none of them replied.

Currently there's no way to build latest Unigram from sources, because no one knows where to get TDLib 1.3.2. 

Most people won't care if it's unstable or not. At least these Unigram guys won't.

**Comment by levlam** [comment]
Unigram uses prebuilt TDLib SDK for UWP. You can request it from @tdlib_bot or Fela can share the SDK with you. Source code of corresponding TDLib's version will be published later.

**Comment by colbycdev** [comment]
Will tdlib ever be updated with official telegram client features?
Currently, no apps built on tdlib can use the official telegram features (polls, instant view 2, see # online, etc)

**Comment by l4rzy** [comment]
As far as I know none of official Telegram application uses tdlib, and Telegram X is out of sync with telegram latest features (due to tdlib I guess)
If this library were good as you guys promoted it, I think those apps would have switched to already. So what I've been wondering was, did this library get abandoned?

**Comment by levlam** [comment]
@l4rzy It is very hard to switch an existing application to another library. In the best case it will take few months of work and will need really a lot of code rewriting. The resulting application will be better in most details and easier to develop in maintain, but in the transition time there will be added a lot less new features then usually.
The library isn't abandonned. For example, TDLib's based Unigram already has all features, mentioned in the previous post. Current developement version has more improvements from 1.3.0 than 1.3.0 had from 1.0.0.

**Comment by dolbyzerr** [comment]
@levlam could we have any timeline on this? I really miss the instant 2.0 in my client and the usage of it increases constantly.

**Comment by levlam** [comment]
@dolbyzerr TDLib 1.4.0 will be released few days after Telegram X stable release, which is currently in Release Candidate stage. It is supposed to be released soon, but I can't provide exact ETA.

**Comment by dolbyzerr** [comment]
@levlam Good enough ETA for me :) Thanks!

**Comment by levlam** [comment]
TDLib has been updated to 1.4.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
