### ISSUE TITLE
Update to stay current 

### ISSUE THREAD

**Issue by alexa-v2** [tdlib/td#453]
According to github, this repo hasn't been updated in four months. That means apps built on it are seriously lacking features, such as polls, IV 2, seeing number of people online in a supergroup, etc. Telegram is supposedly open source, but the building block for other apps isn't being kept up-to-date.
Some of the unofficial apps have additional functionality that users want, but those apps still don't have the core functionality of the official one. This makes the other apps almost unable to compete, because users will choose the client that supports the latest features

**Comment by levlam** [comment]
TDLib has been updated to 1.4.0. Almost 1400 new commits since 1.3.0 are public now. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
