### ISSUE TITLE
Random "Not found" errors in getChatHistory

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#454]
Most of the time getChatHistory works as expected and returns messages according to the input parameters. However there is a rare error when getChatHistory returns "Not found" error without details. Logs do not provide any useful info other than that there was a request and it failed with "Not found" error.

This exact request produces "Not found" error:

```
getChatHistory (
  chat_id = -1001046770970
  from_message_id = 270309261312
  limit = 32
  offset = -15
  only_local = false
)
```

There is plenty of messages before and after the 270309261312 message. So I have no idea what might cause error like that.

Let me know if I can provide more info.

**Comment by levlam** [comment]
`getChatHistory` should never return something like `Not found` error. Could you collect TDLib logs with verbosity at least 4 and send them to @tdlib_bot?

**Comment by x2bool** [comment]
This error is tricky to catch. I will send details next time I see it. BTW tdlib_bot does not seem to react to messages.

**Comment by levlam** [comment]
The bot doesn't react to commands, but it will react to your messages.

**Comment by levlam** [comment]
@x2bool Have you managed to reproduce the issue you told about?

**Comment by x2bool** [comment]
No. Let's close this for now. I'll let you know if this happens again.
