### ISSUE TITLE
Execute AddChatMember, only the "XX added xxx" system information can be seen in the group. However, the number of groups and the list have not changed.

### ISSUE THREAD

**Issue by zx925745591** [tdlib/td#455]
Execute AddChatMember, only the "XX added xxx" system information can be seen in the group. However, the number of groups and the list have not changed.

**Comment by zx925745591** [comment]
> @zx925745591 What exactly do you mean by "number of groups"? Which list was not changed?

![image](https://user-images.githubusercontent.com/22812798/51105009-b835d080-1822-11e9-9434-b748d15d3bf4.png)
Members!!!

**Comment by levlam** [comment]
Everything should be changed. Are your talking about some specific client or old TDLib version?

**Comment by zx925745591** [comment]
> Everything should be changed. Are your talking about some specific client or old TDLib version?

v1.3.0  java

**Comment by levlam** [comment]
Is it a basic group or a supergroup?

**Comment by zx925745591** [comment]
> Is it a basic group or a supergroup?

supergroup

**Comment by levlam** [comment]
Supergroup member count is available in SupergroupFullInfo via GetSupergroupFullInfo. You will receive UpdateSupergroupFullInfo after each member addition if you called GetSupergroupFullInfo previously at least once. The list of supergroup members, returned by GetSupergroupMembers, should also change after that.
