### ISSUE TITLE
crash if using multiple proxies

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#456]
On clean setup, I do `addProxy` (with dummy address/port/login/pass) twice on start, it results every time in crash.  If I add only one proxy, then everything is fine

I attach backtrace and the log I've got

[backtrace.log](https://github.com/tdlib/td/files/2766776/backtrace.log)
[tdlib.log](https://github.com/tdlib/td/files/2766777/tdlib.log)

**Comment by levlam** [comment]
Thanks, for the report. The crash will be fixed in the next TDLib version, but the fix is too hard to be backported to the current version. As a workaround I can suggest calling `addProxy` only after `checkDatabaseEncryptionKey` is called.

**Comment by zevlg** [comment]
> As a workaround I can suggest calling `addProxy` only after `checkDatabaseEncryptionKey` is called.

this helped, thanks!

**Comment by levlam** [comment]
The crash is fixed in TDLib 1.4.0.
