### ISSUE TITLE
On telegram passport request pin or fingerprint to authorize access

### ISSUE THREAD

**Issue by rbenea** [tdlib/td#457]
In case you use Telegram for authentication you have will get a simpls 'Accept' or 'Authorize'  message. The problem is that this message is propagated the all open telegram instances (phones, tablets, computers etc..). In case somebody has access any of them they just have to click 'Accept' and the access is granted. I think this is less secure then a 2FA via SMS because there the message is received on only one device that is easier to control. 

I would like to be asked for my telegram password or on mobile devices for my fingerprint after I click on the 'Accept' button.

**Comment by levlam** [comment]
This isn't related to TDLib or Telegram Passport. This is a description of how Telegram Login Widget works. Telegram Login Widget ensures that owner of a phone number is a registered Telegram user. If someone can press the button then it has access to the account and that is exactly, what Telegram Login Widget confirms. Between, such authorization gives much less data to the website than available directly through a logged in client and the authorization can be revoked anytime from settings.

**Comment by rbenea** [comment]
Thank you for the reply. You are probably right, it's only the fact that on most of the places, event if the account is already logged in, when you try to change some settings it's asking again for the current password just to be sure that you didn't leave your computer unlocked. I think that an extra optional check would be welcomed. 
If this is not the correct thread, can you tell me where I should post the current suggestion?

**Comment by levlam** [comment]
You can send general suggestions through in-app Telegram Support.

But this particular suggestion is unlikely to be implemented, because it doesn't add any additional security. If you want to be protected from physical intruders, then you need to use passcode to protect the whole application, which is supported by all official applications.
