### ISSUE TITLE
About phone number be banned

### ISSUE THREAD

**Issue by asok00000** [tdlib/td#458]
Hi,when I login with tdlib,my phone number will be banned few minutes.But login with telegram app don't.Is my codes error?I used the cpp example codes

**Comment by levlam** [comment]
There are a lot of reasons, why an account can be banned. Please write ro recover@telegram.org your phone number and other details to recover the account.

**Comment by asok00000** [comment]
email sent but no response,I only login with tdlib,no other behaviors done,with telegram desktop app every thing is OK,only when I use tdlib

**Comment by L11R** [comment]
@asok00000 they can respond for weeks. Wait :)

**Comment by levlam** [comment]
They should answer within a day if the ban was accidental and not intended.

@asok00000 Could you send a email address, from which you wrote to recover@telegram.org, to @tdlibbot, if it is still unanswered?

**Comment by asok00000** [comment]
the reason banned must be the tdlib cause.I use telethon with the same number all behaviors like login,send message is OK now,but when I login with tdlib,ban will come immediately

**Comment by crapulent** [comment]
same for me:
(now I am using built version from here https://github.com/mnouraei/TDLibSharp/blob/master/Dependencies.zip , will retest it with dll built myself later)
using mobile client: ok
using tdlib (got code from here https://github.com/tdlib/td/blob/master/example/csharp/TdExample.cs ): login, send auth code => ban

**Comment by crapulent** [comment]
> Because, when you develop an App you cannot endlessly register the same number. You will get a day ban or so after doing it too often. That´s why there is a test server, where this wont happen.

pretty understandable, but in my case my number was banned (not flood_wait'ed) after my first register attempt. will return to my research tomorrow.

**Comment by Flohack74** [comment]
Try test mode in any case, its better during first steps with a new app :)

**Comment by crapulent** [comment]
> Try test mode in any case, its better during first steps with a new app :)

Thank you for advice, I will.

BTW Today I returned to my tests: I
- got mail from support that my number is no longer banned
and
- changed DeviceModel, SystemVersion, ApplicationVersion in SetTdlibParameters arguments
and now I can freely use tdlib without ban (not sure what helped me).
(so problem is gone for me (for now) )

**Comment by Flohack74** [comment]
BTW @levlam where to set API key in tdlib, if we are making a new App now, do we still need this?

**Comment by FrayxRulez** [comment]
@Flohack74 you set the API key by invoking `setTdlibParameters`

**Comment by levlam** [comment]
Since TDLib 1.5.0 if the account is banned by the server, TDLib will suggest through the log to contact recover@telegram.org. That's all that can be done on the TDLib's side.
