### ISSUE TITLE
Mark a message as (read or seen)

### ISSUE THREAD

**Issue by Qasemt** [tdlib/td#46]
hi :) 
how can I **mark** a message as  **(read or seen)** in td !!?

**Comment by levlam** [comment]
To achieve this you need to call OpenChat/CloseChat when chats are opening/closed by the user and call ViewMessages whenever a message is shown to the user. The library will figure out which messages should be read itself. Messages are read only if they are shown in currently opened chat, but if you definitely need to read messages in closed chat, you may use force_read parameter of ViewMessages method.

**Comment by Qasemt** [comment]
tanx :)

**Comment by Qasemt** [comment]
tanx

**Comment by kolopeda** [comment]
This method does not work, the "viewMessages" method works

**Comment by JaEdmuva** [comment]
I have been using all three methods (open, close and viewMessages WITH force read option True) but it won't always work. Is there a way to effectively mark messages as read for sure?

**Comment by CharlesOkwuagwu** [comment]
> I have been using all three methods (open, close and viewMessages WITH force read option True) but it won't always work. Is there a way to effectively mark messages as read for sure?

@JaEdmuva Hi, have you found a reliable way to mark as read?

**Comment by recolic** [comment]
@JaEdmuva @CharlesOkwuagwu 
Update: I got the reason why the `openChat - viewMessages - closeChat` is not reliable.

To mark message as read in a reliable way, you must only `openChat`. You MUST NOT `closeChat`.

In my program, I have another timer thread. It calls `openChat` and `viewMessages` once a second. After 10 seconds, it calls `closeChat`.
You must keep the chat "opened" as long as possible, to make it reliable.

**Comment by CharlesOkwuagwu** [comment]
> @JaEdmuva @CharlesOkwuagwu Update: I got the reason why the `openChat - viewMessages - closeChat` is not reliable.
> 
> To mark message as read in a reliable way, you must only `openChat`. You MUST NOT `closeChat`.
> 
> In my program, I have another timer thread. It calls `openChat` and `viewMessages` once a second. After 10 seconds, it calls `closeChat`. You must keep the chat "opened" as long as possible, to make it reliable.

@recolic 

Are you sending  `openChat `and `viewMessages ` for each chat received?

**Comment by recolic** [comment]
> @recolic
> 
> Are you sending `openChat `and `viewMessages ` for each chat received?

I am creating an anti-spam bot, so I do it for every chat unless it's whitelisted. You need to do that basing on your need.

If you want to mark a message as read, you need to `open` that chat (and keep it opened for a while)
