### ISSUE TITLE
Tglib Library in Nativescript

### ISSUE THREAD

**Issue by arpit2438735** [tdlib/td#461]
In case you are looking for a library in nativescript.
Guess what I created https://github.com/arpit2438735/nativescript-tglib library for that.Currently it has support for iOS.

Have a look and send a feedback or add more features and send pull request.

![Telegram](https://media.giphy.com/media/ya4eevXU490Iw/giphy.gif)

**Comment by levlam** [comment]
Thanks, @arpit2438735! I'll mention it in the [list](https://github.com/tdlib/td/blob/master/example/README.md) of TDLib-based libraries.

**Comment by levlam** [comment]
I added your library to the list of [JavaScript examples](https://github.com/tdlib/td/blob/master/example/README.md#javascript).

**Comment by arpit2438735** [comment]
Thanks @levlam 👍
