### ISSUE TITLE
Json parsing errors silently swallowed

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#463]
If json parsing fails in TDLib, it silently swallows this error without feedback to the caller.  Once I've got a typo somewhere I have no idea if something goes wrong until looking in the logs.  For example, I sent next json (I replaced real `chat_id` with dummy value):
```
{"@type":"sendChatAction","chat_id":111111,"action":{"@type":"chatActionTyping0"},"@extra":138}
```

With obvious typo in chat action, and got in the log:
```
[ 1][t 0][1548000969.140338421][ClientJson.cpp:71]      Failed to parse [request:{\0042@type\0042:\0042sendChatAction\0042,\0042chat_id\0042:111111,\0042action\0042:{\0042@type\0042:\0042chatActionTyping0\0042},\0042@extra\0042:138}] [Error : 0 : Unknown class]
```

However neither error is returned to the caller, nor fatal error callback is triggered.  This makes a little bit harder to debug client app.  In my case I've noticed that action is not applied only in couple days of client running.

**Comment by levlam** [comment]
We have no way to return error to the caller before actually parsing request and getting `@extra` field. In this particular case, when the object is correctly parsed, we can theoretically return an error, but it requires adding a special dummy method to TDLib just for this purpose. Such method possibly can be added in the future, if we don't find a better way to implement this.

**Comment by zevlg** [comment]
What about just triggering `fatal_error_callback` with some JSON_PARSE_ERROR error code?

**Comment by levlam** [comment]
It is possible, but this is not supposed to be a fatal error, because the error can be handled. If you want to achieve this behavior, you can patch [ClientJson.cpp](https://github.com/tdlib/td/blob/master/td/telegram/ClientJson.cpp), replacing `LOG(ERROR)` with `LOG(FATAL)`.

**Comment by zevlg** [comment]
Thanks for the hint.  So, any real fatal error states as can't continue?  So if fatal callback is called, program should exit, correct?

**Comment by levlam** [comment]
Yes. Fatal error means that program state is irrecoverably corrupted or there is not enough system resources to continue, and restart is needed.

**Comment by levlam** [comment]
This was changed in TDLib 1.5.0 and now incorrect JSON requests return proper errors.
