### ISSUE TITLE
UpdateFile is not raised

### ISSUE THREAD

**Issue by NitayTubi** [tdlib/td#464]
Hi,
I'm using DownloadFile to download a file to my local machine.
I'm handling File update and receiving `myFile.Local.IsDownloadingCompleted=fale` and `myFile.Local.Path` is empty. 
Only if I'm calling again to DownloadFile, I'm receiving `myFile.Local.IsDownloadingCompleted=true` and `myFile.Local.Path` contains the path.
I saw that I should handle UpdateFile to know when the download is completed or canceled, but this update is never raised.
Any idea? 
Thanks.

**Comment by NitayTubi** [comment]
Thanks for the reply.
My problem is that `UpdateFile` is never raised from some reason. 
I just need to get the local file path when it becomes available. I can do it by calling `DownloadFile` again from the `File` handler, as long as the path is empty, but it's bad.
The correct way is to handle `UpdateFile`, but as I mentioned, it is never raised. 
Can you think why `UpdateFile` is not raised? It should happen automatically after `DownloadFile` call when the download is complete?

**Comment by levlam** [comment]
Yes, it is supposed to work. Could you collect TDLib logs with verbosity 4 and send them to @tdlib_bot, so I can see, what exactly happens in your case?

**Comment by NitayTubi** [comment]
I added `Log.SetVerbosityLevel(4)`. Where can I find the created log files? 
I looked in tdlib database directory but it's not there.

**Comment by NitayTubi** [comment]
Actually now I'm facing another similar problem.
Sometimes, even the `File` handler is not raised after calling to `DownloadFile`. I can see the downloaded file in my local machine, but the event is not raised. 
What am I missing here? 
Please tell me where can I find the log files so I will send them to you.

**Comment by levlam** [comment]
@NitayTubi See Log.SetFilePath method description, which allows to redirect them to a file instead of stderr.

**Comment by NitayTubi** [comment]
Thanks, I created a log file and sent it to @tdlib_bot as you mentioned.

**Comment by levlam** [comment]
@NitayTubi You are trying to download already downloaded file, The File object has `File.Local.IsDownloadingCompleted == true`, which can be seen in the result of `DownloadFile` call. If `File.Local.IsDownloadingCompleted == true` also before call to `DownloadFile` then there is no reason to call `DownloadFile` at all.

**Comment by NitayTubi** [comment]
I delete the local file from the profile_photos folder, and the `File.Local.IsDownloadingCompleted == false`. Also in this case, when I call `DownloadFile`, I can see the downloaded file again in the profile_photos folder (so the downloading process does work), but the events `File` and `UpdateFile` are not raised.
I sent you another new log file.
If you can take a look it would be great.
Thanks again!

**Comment by levlam** [comment]
In new log UpdateFile after successful download were sent at 1548160846.818920374, 1548160874.346634626 and 1548160995.848951578.

**Comment by NitayTubi** [comment]
It's weird because I don't get the specific `UpdateFile` event. 
The call to `DownloadFile`:
`Client.Send(new DownloadFile(fileIdId, 32), new FileDownloadHandler());`.
And the handler looks like this:
```
    public class FileDownloadHandler : ClientResultHandler
    {
        public void OnResult(BaseObject @object)
        {
            if (@object is Error)
            {
                
            }
            else if (@object is File)
            {

            }
            else if (@object is UpdateFile)
            {

            }
        }
    }
```
Can't get to my breakpoint inside `else if (@object is UpdateFile)`.

**Comment by levlam** [comment]
Request ResultHandlers are triggered exactly once, UpdateFile as any other Update is received by UpdatesHandler set on Client creation. So, this handler will receive only File or Error. If File.IsDownloadingActive, then file download is in progress and there will be UpdateFile updates notifying about download progress.

**Comment by NitayTubi** [comment]
Ok, it actually makes sense, although in that way it's more difficult to synchronize between all downloading processes and handler of the application.
Thanks a lot for your help, problem solved.

**Comment by levlam** [comment]
In TDLib 1.4.0 the parameter `synchronous` was added to `downloadFile` method which causes the request to return the result only after the download is completed, which should be sufficient for basic usages.

**Comment by chairus** [comment]
> @NitayTubi You are trying to download already downloaded file, The File object has `File.Local.IsDownloadingCompleted == true`, which can be seen in the result of `DownloadFile` call. If `File.Local.IsDownloadingCompleted == true` also before call to `DownloadFile` then there is no reason to call `DownloadFile` at all.

@levlam So if `File.Local.IsDownloadingCompleted == true` and you call the `DownloadFile` does it actually download the file again or just send back a `File` object?

**Comment by levlam** [comment]
@chairus It checks that the file wasn't changed externally. If the file wasn't changed, then `File` object is returned immediately, otherwise the file is redownloaded.

**Comment by chairus** [comment]
>  It checks that the file wasn't changed externally.
@levlam You meant the file in the remote server hasn't been modified right?

**Comment by levlam** [comment]
@chairus The file can't be modified on the remote server, but it can be modified locally by some other application.

**Comment by chairus** [comment]
@levlam Thanks!
