### ISSUE TITLE
successfully build, but problems using in Nodejs

### ISSUE THREAD

**Issue by Argon007** [tdlib/td#465]
Hi,

The build went successfull after I had some troubles. I'm using TDLib on Debian 9 Stretch.
I saw I could use a Nodejs Wrapper around this package on the Examples page:
node-tdlib, tglib, Paper Plane

But if I want to install those packages, I always run into trouble with NPM. This is what I get when trying to install "npm i -S tglib"

`> ref-napi@1.4.1 install /home/user/node/node_modules/ref-napi
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/user/node/node_modules/ref-napi/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/user/node/node_modules/ref-napi/.node-gyp'
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/node/node_modules/ref-napi
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN node@1.0.0 No description
npm WARN node@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref-napi@1.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref-napi@1.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-21T13_03_25_726Z-debug.log`

So the package wasn't installed I think. When trying to import the TDL package in a Node Script with the following code:
`const { Client } = require('tdl')`

It gives me this:
`Error: Cannot find module 'tdl'`

I'm having the same with "Paper Plane"

Before I go further in this: the thing I like to achieve is getting real-time updates from a Telegram channel into Nodejs. But is it possible to get realtime updates or not? I often see that there is a 1 a 2 second delay about getting a message in Telegram. If you poll it faster you get flood errors. If I will have the same problem with TDLib I don't have to search any further... :-)

Thanks!

**Comment by levlam** [comment]
This can help to solve permission problems: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally.

For some info about update delivery delay in big channels see discussion in https://github.com/tdlib/td/issues/348. In short, it is impossible to instantly send an update to thousands channel subscribers, you need to be a channel admin or a bot to receive new messages as fast as possible..
