### ISSUE TITLE
Is it real to built an app using only tdlib and libtgvoip?

### ISSUE THREAD

**Issue by sdanny** [tdlib/td#468]
Are these libraries friendly each other and self-sustained?

**Comment by levlam** [comment]
These are the only libraries you need to work with Telegam API and to support Telegram calls respectively. You may need other libraries or frameworks to implment UI and media files processing.

**Comment by Flohack74** [comment]
I can proof that it is possible, we built a Telegram app for Ubuntu Touch with it, and it works pretty well.

**Comment by zevlg** [comment]
> I can proof that it is possible, we built a Telegram app for Ubuntu Touch with it, and it works pretty well.

Do you have it opensource?

**Comment by Khwuanchai** [comment]
I​ need​ it.

**Comment by Flohack74** [comment]
You can look here: https://gitlab.com/Flohack74/teleports -Basically there is an internal lib called qtdlib which does bindings for QML. And it uses Quickflux for message passing in QML.
