### ISSUE TITLE
Registering device for push notifications seems not to work

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#470]
Hello, we try to rebuild the Ubuntu Touch telegram client. Now its time to play with the push functions:
`
[SEND] : QJsonObject({"@type":"registerDevice","device_token":{"@type":"deviceTokenUbuntuPush","token":"<deleted>"}})
`
This seems to be accepted by tdlib, but no push is happening it seems. Any ideas how we can find out whats the issue? Is push implemented fully in tdlib by now?

**Comment by levlam** [comment]
TDib just registers token server-side. After that push notifications supposed to be sent by server to push notification service, then sent to the client and processed by it. So a lot of parties are involved in the process. Am I right that registerDevice returns `ok`, but there is no incomin push notifications after that?

**Comment by Flohack74** [comment]
Yeah it seems that it returns ok. As we are using the same push client as in the old Telegram for UT app, we assume that it should work right away. I am also in contact with Igor, do you think we can make a debugging for that to see if you got the token and start sending notifications, if I send you a test token that should be registered?

**Comment by Flohack74** [comment]
Ok we found the bug on our side. Push is working now! Thx!
