### ISSUE TITLE
[Missing] Call Feedback

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#474]
![photo_2019-01-27_15-40-38](https://user-images.githubusercontent.com/25002879/51799671-01861700-224a-11e9-9208-7e630bdea037.jpg)

**Comment by levlam** [comment]
This is, in fact, pure client-side feature, which uses `sendCallDebugInformation` method with specially crafted `debug_information` string, containing a hashtag for each chosen by the user reason. Some helper method for generation of this string would be helpful though.

**Comment by levlam** [comment]
Support for specifying the exact call problems was added in TDLib 1.5.0 via the new parameter `problems` in the method `sendCallRating`, so clients don't need to modify the `comment` parameter themselves.
