### ISSUE TITLE
Get user phone number

### ISSUE THREAD

**Issue by NitayTubi** [tdlib/td#475]
Hi, 
I'm using `GetUser` method, and the returned `PhoneNumber` field is empty.
When is it possible to receive it? 
Thanks.

**Comment by NitayTubi** [comment]
So I can receive the phone number only if I have it in my contact list?

**Comment by Flohack74** [comment]
Sure, its a privacy thing. Imagine you could retrieve the phone numbers from all Telegram users on the planet, that would be a disaster :)

**Comment by NitayTubi** [comment]
Yes it actually makes sense. Thanks 👍

**Comment by Flohack74** [comment]
But please double-check it: Try to retrieve a user that is in your contacts list in the official App. That should have a Telphone no.
