### ISSUE TITLE
Error : 0 : Can't parse "-1001222207990" as number for supergroup methods

### ISSUE THREAD

**Issue by syfgkjasdkn** [tdlib/td#478]
👋

I've created a channel, and it got -1001222207990 as its id. When I try to get the members of that channel via tdlib-json-cli, I get:

```
[ 1][t 0][1548697912.680639744][ClientJson.cpp:78][&status.is_error()]	Failed to parse [request:{\042supergroup_id\042:-1001222207990,\042offset\042:null,\042limit\042:null,\042filter\042:null,\042@type\042:\042getSupergroupMembers\042}] [Error : 0 : Can't parse "-1001222207990" as number]
```

What am I supposed to pass to tdlib as `supergroup_id`?

**Comment by syfgkjasdkn** [comment]
I also get that parsing error for other supergroup methods, like `getSupergroupFullInfo`.

**Comment by syfgkjasdkn** [comment]
According to https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_supergroup_full_info.html, `supergroup_id` is int32, and -1001222207990 overflows that.

**Comment by syfgkjasdkn** [comment]
Hi @zelenin! I wonder if you could tell me how I can get the supergroup id from a chat id?

**Comment by zevlg** [comment]
> Hi @zelenin! I wonder if you could tell me how I can get the supergroup id from a chat id?

Its in “type” of the chat

**Comment by syfgkjasdkn** [comment]
@zevlg hi! What do you mean by a `chat` here? For example, in a bot I get this for any activity in the channel:

```
chat: {
  first_name: nil,
  id: -1001222207990,
  last_name: nil,
  photo: nil,
  title: "alsdkfjhlkajsdhf",
  type: "channel",
  username: nil
}
```

**Comment by syfgkjasdkn** [comment]
Oh, silly me. I just need to remove the leading `-100`! Thank you both @zevlg and @zelenin!
