### ISSUE TITLE
 Frequent user bans

### ISSUE THREAD

**Issue by Demetriy** [tdlib/td#480]
Hi!

Currently develop mobile app, based on tdlib and now we are beta testing it, have about 40 testers and 2-5 of them got login error "PHONE_NUMBER_BANNED", it's a little strange, because they mostly new in telegram and registered their phones for the first time. 
But maybe it's connected with proxy: while in development i enabled proxy by default (привет Роскомнадзор) and test users from different countries.

**Last issue example from tester:**
Today, I have installed the app, authorized my Telegram account and all was fine. Then, I tried to start it the second time, went to Contacts and clicked on Importing my contacts to see if any of my friends have Telegram. What happened then was that I got logged out and when I tried to reauthorize my account, I found out it was banned.

**Comment by levlam** [comment]
Please write details to recover@telegram.org. Unfortunately, there is nothing we can do to prevent blocking of suspicious accounts by the server.

**Comment by Demetriy** [comment]
Ok, it's sad.
