### ISSUE TITLE
Build FAILED. error C3861: 'rl_free': identifier not found [td\build\tg_cli.vcxproj]

### ISSUE THREAD

**Issue by djykstra** [tdlib/td#481]
![image](https://user-images.githubusercontent.com/23149/52119814-f6b5f280-264c-11e9-8e78-07aa93b84852.png)

windows 10 Home 64 bit
cmake version 3.13.3
Vcpkg version 2018.11.23-nohash
gperf version 3.0.1
visual studio 2017 community (version 15.9.6)

openssl-windows:x64-windows                        1.0.2q           
openssl-windows:x86-windows                        1.0.2q           
openssl:x64-windows                                0                
openssl:x86-windows                                0                
readline-win32:x86-windows                         5.0-2       
readline:x86-windows                               0                
zlib:x64-windows                                   1.2.11-3         
zlib:x86-windows                                   1.2.11-3         

on td path
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE="D:/Telegram Client/vcpkg/scripts/buildsystems/vcpkg.cmake"  ..
cmake --build .

probably I do something wrong?

**Comment by levlam** [comment]
Vcpkg provides Readline 5.0.1, which is too old, we need at least 6.0.0. You can just uninstall Readline and build without it from scratch after removing `build` folder.

**Comment by djykstra** [comment]
levlam: tnx....
I remove all readline...
clean n rebuild..... Build succeeded.
with 1 warning...
warning C4244: '=': conversion from 'const _Ty' to '_Ty', possible loss of data [D:\Telegram Client\td\build\tdutils\tdutils.vcxproj]


![image](https://user-images.githubusercontent.com/23149/52142223-b2e1de00-268a-11e9-8e1f-c5e5cde8444b.png)

**Comment by Michal-Szczepaniak** [comment]
Im getting same error while building on linux from master using cmake:
```[ 67%] Building CXX object CMakeFiles/tg_cli.dir/td/telegram/cli.cpp.o
/home/foidbgen/tdlib/td/telegram/cli.cpp: In static member function ‘static void td::CliClient::cb_linehandler(char*)’:
/home/foidbgen/tdlib/td/telegram/cli.cpp:664:17: error: ‘rl_free’ was not declared in this scope
     rl_free(line);
                 ^
/home/foidbgen/tdlib/td/telegram/cli.cpp: In lambda function:
/home/foidbgen/tdlib/td/telegram/cli.cpp:1166:76: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     cmd.erase(std::remove_if(cmd.begin(), cmd.end(), [](char c) { return 0 <= c && c < 32; }), cmd.end());
                                                                          ~~^~~~
```

**Comment by levlam** [comment]
@Michal-Szczepaniak The problem is also in Readline being to old (i.e. < 6.0.0). Readline isn't needed by TDLib and is only optionally used for testing, so for now you can just remove call to `find_package(Readline)` in https://github.com/tdlib/td/blob/101aa73f132d5124d8da45bae11a29c423420072/CMakeLists.txt#L750, delete build directory and compile again from scratch.

The second warning is useless and should happen only on ARM Linux, because on most other platforms char is signed by default, so the comparison is meaningful there.

**Comment by Michal-Szczepaniak** [comment]
@levlam thanks a lot

**Comment by levlam** [comment]
TDLib 1.4.0 automatically ignores too old GNU Readline versions.
