### ISSUE TITLE
can't get more then 10k members, using getSupergroupMember

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#484]
Hi!
When i call "getSupergroupMember", i can't get more than 10 000 members. If i use offset 10000, then get only one user!
And  i've tested it for several group with total mebers more then 10000.

Could you help me, what i doing wrong?

Thank you.

**Comment by RememberTheAir** [comment]
As far as I know, the 10.000 limit is a serverside limit. Clients (like tdlib) can only get the first 10.000 members of the chat

**Comment by merlinkory** [comment]
Does has some way to get more? Because a lot of supergroups contains more than 10k members

**Comment by levlam** [comment]
@merlinkory No, there is no way to get more than 10000 members in supergroups and 200 members in channels.

**Comment by merlinkory** [comment]
@levlam ok i got it, but how i can display  all users of supergroup in my app, if group contains more then 10k members? may be i can show them partly (bot i'dont know, how)?

thank you

**Comment by levlam** [comment]
There is no reason to show even 10k supergroup members. Noone will be interested in reading so much member names at once. Clients shows last 200 active members and load more when user scrolls down, but user needs to scroll really long to get to the bottom of the list even in that case.

**Comment by zevlg** [comment]
In large chats I use `searchChatMembers` method for completing username mention. In small chats, where all members list is available there is no need to request TDLib
