### ISSUE TITLE
Sometimes message sending twice (instead of once)

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#485]
Sometimes when  i run my app and then call "sendMessage",  message doesn't sending into chat, but in next time when i run my app chat getting 2 message. 
Does anybony known, why it happening?

thank you

**Comment by zelenin** [comment]
Library is asynchronous. The execution of the `sendMessage` does not mean that the message has been delivered. It may not have time to deliver before the closure of the app. But the library works with a local database, and the message will be delivered after a new app start from it.

**Comment by levlam** [comment]
@merlinkory If you want to catch exact time, when a message was sent and close application only after that, you need to handle `updateMessageSendSucceeded`, `updateMessageSendFailed` and `updateDeleteMessages` updates.
