### ISSUE TITLE
FILEREF_UPGRADE_NEEDED 

### ISSUE THREAD

**Issue by mnuguid11** [tdlib/td#486]
TdApi.DownloadFile response is FILEREF_UPGRADE_NEEDED im using the Prebuilt library for android

Logs

[Session.cpp:665][!Session:2:download_small#0]	Session::on_error [id:6655183672085033384][error_code:406][msg:FILEREF_UPGRADE_NEEDED]

**Comment by MalteToenjes** [comment]
Could you fix this issue?

**Comment by levlam** [comment]
This is an error returned to old clients, so you can try to update to the latest TDLib.
