### ISSUE TITLE
Proxy Authentication Required

### ISSUE THREAD

**Issue by mnuguid11** [tdlib/td#488]
new TdApi.AddProxy(Constants.PROXYIP,Constants.PROXYPORT,true,new TdApi.ProxyTypeHttp("username","password",true)) can't connect to proxy always return Proxy Authentication Required

**Comment by levlam** [comment]
For now we support only HTTP basic access authentication. Which kind of authentication uses your HTTP server?

**Comment by levlam** [comment]
Closing this, because there was no feedback from the user and we are unlikely to be able to support other HTTP authentication methods in the near future.
