### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by MuhamadFajarGaray** [tdlib/td#489]
For the next update I ask for the addition of the feature in the form of "forward no quote" feature that I need for the benefit of the channel

**Comment by levlam** [comment]
"forward no quote" is just sending a new message with a content, which is the same as in an original message. It can be easily done now using TDLib and `sendMessage` method.

**Comment by levlam** [comment]
Possibility to forward message as copy was added in TDLib 1.5.0 via new the parameters `send_copy` and `remove_caption` added to the method `forwardMessages` and the class `inputMessageForwarded`.
