### ISSUE TITLE
How to use Client.Send with a json string as input?

### ISSUE THREAD

**Issue by mostafa8026** [tdlib/td#490]
Client.Send accepts Function as input, but is there a way to send with json as input? like: Client.Send(string json_string, handler)?
I'm using dotnet.

**Comment by levlam** [comment]
.Net interface is a native strongly typed safe interface. There is no way you can pass a request as a JSON string instead of an object to it. You need to use JSON interface via tdjson.dll and `td_json_client_send` method to send requests and receive responses as JSON objects.

**Comment by mostafa8026** [comment]
Is there any example of using td_json_client_send in dotnet?

**Comment by levlam** [comment]
You can look at https://github.com/egramtel/egram.tel.
