### ISSUE TITLE
DNS over HTTPS for proxies

### ISSUE THREAD

**Issue by kisik21** [tdlib/td#492]
Hello! Unigram support sent me here. Please add support for DNS over HTTPS for proxies, it will allow to circumvent more blocks (i.e. DNS hijacking). It seems to be present in Telegram Desktop.

**Comment by levlam** [comment]
DNS over HTTPS support was recently implemented in our private version. It will be used for resolving proxy IP addresses in countries, where Telegram is blocked. It will be available in the next Unigram version.

**Comment by kisik21** [comment]
Got it. Will mark as solved as soon as I receive the update via Microsoft Store.

**Comment by levlam** [comment]
TDLib 1.4.0 automatically resolves proxy addresses through Google DNS over HTTPS in countries where Telegram is supposed to be blocked.
