### ISSUE TITLE
Itunes review

### ISSUE THREAD

**Issue by sdanny** [tdlib/td#493]
Working on iOS fork client. How should we pass the apple review since they usually ask for some test user to check the functionality? Can you provide one?

**Comment by levlam** [comment]
There is no such accounts in production DC, but you can use accounts from test DC, mentioned in https://core.telegram.org/api/datacenter#testing-redirects.

**Comment by leoMehlig** [comment]
@sdanny what did you end up entering as a demo account? I have the same problem...

**Comment by sdanny** [comment]
@leoMehlig suggestion by @levlam solution worked for tdlib project. Don't forget about "test_mode" option described [here](https://core.telegram.org/tdlib/options).
