### ISSUE TITLE
Auto-Play videos and GIFs

### ISSUE THREAD

**Issue by readeryy** [tdlib/td#494]
Will be available in next version tdlib or we need wait more?

**Comment by zevlg** [comment]
Is not it already can be implemented with TDLib 1.3.0?  Just download animation file and start playing it :)

**Comment by readeryy** [comment]
i mean about recent update telegram for iOS and Android. Videos and GIFs auto-plays without to enter them.

**Comment by RememberTheAir** [comment]
@readeryy that's just how the Android and iOS clients show them. They pull the file from Telegram and play it inside your chat screen, tdlib already allows to download files and videos (duh) so there's nothing to be done on its side

**Comment by levlam** [comment]
TDLib 1.4.0 supports downloading of any file part, which is enough for streaming and autoplaying Videos and GIFs.
