### ISSUE TITLE
how update view count of a message

### ISSUE THREAD

**Issue by mob2005** [tdlib/td#495]
hi , when i request `getMessage`  any time , view count of response is static and not change , how can get views update for messages?

**Comment by levlam** [comment]
View count is updated only for messages viewed in an open chat. So, you need to porperly call `openChat`/`closeChat`.

**Comment by mib32** [comment]
@levlam If I make openChat, then the view count updated also for very old messages, or for that I need to perform getChatHistory with correct offset?

**Comment by levlam** [comment]
@mlb32 No. View counts are updated only for being viewed messages.
