### ISSUE TITLE
Speed of response to requests

### ISSUE THREAD

**Issue by geroddokar** [tdlib/td#496]
I am writing a client in c #. Faced such a problem: during debug in visual studio, responses to requests of the type _client.Send (new GetChats (offsetOrder, offsetChatId, limit - Participants.Count ()), _updatesHandler); pass very quickly. But if you run the same code not in debug mode, then the time to receive an answer will significantly increase. Sometimes you can wait for a response for about a minute .... I attach the code in the description

**Comment by geroddokar** [comment]
I will add another project file with a description of the connected libraries.
[TGRobus.txt](https://github.com/tdlib/td/files/2910822/TGRobus.txt)

**Comment by levlam** [comment]
Performance in Debug mode should be much worse than in Release mode, but not vise versa. Could you enable TDLib log with verbosity level 4, reproduce slow GetChats response and send the log to @tdlibbot in Telegram?

**Comment by geroddokar** [comment]
Sorry, I added these two lines to the code, and the problem disappeared by itself. I comment them, and the space appears again ... How can this be explained?)

`Td.Log.SetFilePath("logTdLib.txt");
  Td.Log.SetVerbosityLevel(4);`

**Comment by levlam** [comment]
You can try to use MSVC profiler to find out the reason. But I expect that it is something external to the program.

**Comment by levlam** [comment]
@geroddokar Have you managed to reproduce the issue with the TDLib's log enabled?

**Comment by geroddokar** [comment]
If the logs do not turn on - there are problems with speed.

> @geroddokar Have you managed to reproduce the issue with the TDLib's log enabled?

**Comment by geroddokar** [comment]
Problem Solving - Enable Logging

**Comment by levlam** [comment]
@geroddokar Logs can only slow down the application. Maybe you just need to setLogVerbosityLevel to 0 to disable the logging?
