### ISSUE TITLE
Relation between file names and related contact ?

### ISSUE THREAD

**Issue by aminrezaie** [tdlib/td#497]
Hi
I'm trying to load contact and show their profiles images.
I see that profile picture store in a folder named 'profile_images'

my goal is to be able to show the profile for the end user as soon as possible ,So I came up with the idea to get images directly from this folder but unfortunately I have been able to find any relationship between them.
Can you please tell me  that is there any logical relation between these files and the users ?

(I know that I can use local Address in user.ProfilePhoto.Big.Local.Path but this variable is null in the first attempt and it just get value after requesting for TdApi.DownloadFile(user.ProfilePhoto.Big.Id, 1), which of course seems reasonable, but if I want to use UpdatesHandler to get TdApi.UpdateFile I will not be able to find the related user then)

**Comment by levlam** [comment]
If the Local.Path is empty then the file isn't yet downloaded and it doesn't exist in the folder. You need to call DownloadFile to download it and you need to create a Listener for updates of that file, which will show the user photo whenever it is downloaded.

**Comment by aminrezaie** [comment]
I created a handler to receive callback :
 private class DefaultHandler5 : Td.ClientResultHandler
        {
            string phone = "";
            public DefaultHandler5(string _phone)
            {
                this.phone =  _phone;
            }
            void Td.ClientResultHandler.OnResult(TdApi.BaseObject @object)
            {
                Console.WriteLine("receive file callback "+phone);
                TdApi.File a = (TdApi.File)@object;
                 
                    File.WriteAllText( phone + ".txt", @object.ToString());

            }
        }

I Receive this response :
file {
  id = 142
  size = 42305
  expected_size = 42305
  local = localFile {
    path = ""
    can_be_downloaded = true
    can_be_deleted = false
    is_downloading_active = true
    is_downloading_completed = false
    downloaded_prefix_size = 0
    downloaded_size = 0
  }
  remote = remoteFile {
    id = "bla  bla bla"
    is_uploading_active = false
    is_uploading_completed = true
    uploaded_size = 42305
  }
}
As you can see the local address is null here , I tried to get updates of  TdApi.UpdateFile , I receive updates but the problems : 
1. I cannot link the file to related user, its just a file with no more information about the original contact
2.I cannot determine the end of updates ( I can handle it with a counter and compare with the total count of contacts but its a dirty solution)

could you please help me ?

**Comment by levlam** [comment]
DownloadFile begins to asynchronously download file, which can be seen by `is_downloading_active` field. The download of a file is finished when you receive UpdateFile with `is_downloading_active == false`. If `is_downloading_completed == true` at that time, then the file was successfully downloaded to the returned `path`.

You can store correspondence between file_id and user_id, or subscribe a dedicated listener object to all UpdateFile updates about a file with specific ID. There are a lot of ways to implement automatic receiving of updates about file download progress.

**Comment by nopinki** [comment]
Ok
