### ISSUE TITLE
Get a list of contacts with a single request ?

### ISSUE THREAD

**Issue by aminrezaie** [tdlib/td#498]
Hi
I'm trying to get a list of contacts, currently I call new TdApi.GetContacts() and in the callback I get an array of user ids (does not contain any detail of user) and then asking for TdApi.GetUser for every single user to get the details...

It works, but its a bit weird for me. I thought there should be a simpler method to get whole list at once.   
Is there a better any method or solution to get contacts with one request ?

Tnx.

**Comment by FrayxRulez** [comment]
You should use UpdateUser to cache all the users in memory, so you can easily retrieve them by their id.

**Comment by levlam** [comment]
Wherever application receives a user_id from TDLib, the full information about the user has already been received by the application through UpdateUser, So application needs to store information about a user only once and always have up to date information about users. You can find more details about that behavior in https://core.telegram.org/tdlib/getting-started#handling-updates.
