### ISSUE TITLE
osmand telegram canadian area code 1-873 banned

### ISSUE THREAD

**Issue by gignacnic** [tdlib/td#499]
What do you think, can it be related to telegram or osmand telegram:
https://github.com/osmandapp/Osmand/issues/6591 ?
Thanks for letting me know.

**Comment by levlam** [comment]
It is unlikely to be related to OsmAnd Telegram. We also can't do anything to prevent the block. Affected users need to write to recover@telegram.org to unblock their phone numbers and accounts.

**Comment by gignacnic** [comment]
Ok good, I will write once again to [recover@telegram.org](mailto:recover@telegram.org), because they told me last week that it might be the app, api and source code. I will let you know.

**Comment by gignacnic** [comment]
Finally, writing an email with phone number with an error ban to: recover@telegram.org solved the issue.
