### ISSUE TITLE
Temp files in FileUpdate ?

### ISSUE THREAD

**Issue by aminrezaie** [tdlib/td#500]
Im trying to get profile images with **TdApi.UpdateFile** I try to read path of file and sometimes the path is located in "/temp" folder. I think this address is not the final one.
How can I ensure that I have received a final and reliable path ? and if I receive a temp location how can    I get final address ?

**Comment by aminrezaie** [comment]
I found my answer just after creating the issue :D
I should check File.Local.IsDownloadingCompleted

but now Im confused with the non complete files , does  TdApi.UpdateFile trigger again for them (to have final path)?

**Comment by korangu** [comment]
yes

**Comment by levlam** [comment]
@aminrezaie You need to use `downloadFile` method to download a file. Since TDLib 1.4.0 you can use the parameter `synchronous` which causes the `downloadFile` request to return the result only after the download is completed.
