### ISSUE TITLE
Building a Vala binding of TdLib... may need help

### ISSUE THREAD

**Issue by Suzamax** [tdlib/td#505]
Hello! Some months ago i tried to make a Telegram client for Granite library (elementary OS) but the problem is that there is no Vapi out there, but I tried to make some for TdJSON. Here's the _sauce_ in .tar.gz; and feel free to tell me whether has errors or needs improvement :smile: 
[tdjson vapi.tar.gz](https://github.com/tdlib/td/files/2930796/tdjson.vapi.tar.gz)

**Comment by levlam** [comment]
I have no experience with Vala, but vapi files looks correct for me. I've noticed only that TDLib dependencies OpenSSL and zlib aren't sprecified anywhere. Should `-lcrypto -lssl -lz` be added to libs, or they are automatically found in `/usr/local/lib`?

Have you tested it? Does it work for you?

**Comment by Suzamax** [comment]
> I have no experience with Vala, but vapi files looks correct for me. I've noticed only that TDLib dependencies OpenSSL and zlib aren't sprecified anywhere. Should `-lcrypto -lssl -lz` be added to libs, or they are automatically found in `/usr/local/lib`?
> 
> Have you tested it? Does it work for you?

I just compile TdLib then I install it on local. It works without these flags (in my case).

**Comment by levlam** [comment]
See https://github.com/AYMENJD/td-vala for a working Vala binding.
