### ISSUE TITLE
Banned while trying to use test example

### ISSUE THREAD

**Issue by DarkHellbat** [tdlib/td#509]
I have faced next issue : I authorised using example (csharp version), then got chat_ids for that account. Then I tried to get chat with Telegram with the following syntax for 3 times. Ewery time I got an error like "invalid request" or "invalid ID". After 3rd catch I was banned .Is that a bug or I done something wrong?
Syntax is: gc <770000>
gc<770000>

**Comment by levlam** [comment]
If your account was banned, please write ro recover@telegram.org your phone number and other details to recover the account.
