### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by puryanms** [tdlib/td#51]
Hi
how i can solve this problem ?

[ 48%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o
/root/tdbot/td/td/telegram/MessagesManager.cpp: In member function ‘td::Result<td::FormattedText> td::MessagesManager::process_input_caption(td::DialogId, td::tl_object_ptr<td::td_api::formattedText>&&, bool) const’:
/root/tdbot/td/td/telegram/MessagesManager.cpp:13775:26: warning: missing initializer for member ‘td::FormattedText::text’ [-Wmissing-field-initializers]
     return FormattedText{};
                          ^
/root/tdbot/td/td/telegram/MessagesManager.cpp:13775:26: warning: missing initializer for member ‘td::FormattedText::entities’ [-Wmissing-field-initializers]
/root/tdbot/td/td/telegram/MessagesManager.cpp: In member function ‘td::Result<td::InputMessageText> td::MessagesManager::process_input_message_text(td::DialogId, td::tl_object_ptr<td::td_api::InputMessageContent>&&, bool, bool) const’:
/root/tdbot/td/td/telegram/MessagesManager.cpp:13790:45: warning: missing initializer for member ‘td::FormattedText::text’ [-Wmissing-field-initializers]
       return InputMessageText{FormattedText{}, input_message_text->disable_web_page_preview_,
                                             ^
/root/tdbot/td/td/telegram/MessagesManager.cpp:13790:45: warning: missing initializer for member ‘td::FormattedText::entities’ [-Wmissing-field-initializers]
/root/tdbot/td/td/telegram/MessagesManager.cpp: In member function ‘td::unique_ptr<td::MessageContent> td::MessagesManager::get_message_action_content(td::tl_object_ptr<td::telegram_api::MessageAction>&&, td::DialogId, td::MessageId) const’:
/root/tdbot/td/td/telegram/MessagesManager.cpp:20721:49: warning: missing initializer for member ‘td::FormattedText::text’ [-Wmissing-field-initializers]
   return make_unique<MessageText>(FormattedText{}, WebPageId());
                                                 ^
/root/tdbot/td/td/telegram/MessagesManager.cpp:20721:49: warning: missing initializer for member ‘td::FormattedText::entities’ [-Wmissing-field-initializers]

**Comment by levlam** [comment]
It is a warning, not an error. The compiler is overly paranoid here, that warning can be safely ignored. We will fix it in the next update.

Between, what version of GCC is used?

**Comment by puryanms** [comment]
i just using this commands : 

git clone https://github.com/vysheng/tdbot.git
cd tdbot
git submodule update --init --recursive
mkdir build && cd build
cmake ..
make telegram-bot


and after that warning : 

[ 98%] Generate JSON tl source files
[ 98%] Built target tl_generate_json
[ 98%] Linking CXX executable telegram-bot
CMakeFiles/telegram-bot.dir/main.cpp.o: In function `parse_config()':
main.cpp:(.text+0x6fe): undefined reference to `libconfig::Config::lookupValue(char const*, std::string&) const'
CMakeFiles/telegram-bot.dir/main.cpp.o: In function `libconfig::Config::lookupValue(std::string const&, std::string&) const':
main.cpp:(.text._ZNK9libconfig6Config11lookupValueERKSsRSs[_ZNK9libconfig6Config11lookupValueERKSsRSs]+0x32): undefined reference to `libconfig::Config::lookupValue(char const*, std::string&) const'
collect2: error: ld returned 1 exit status
CMakeFiles/telegram-bot.dir/build.make:184: recipe for target 'telegram-bot' failed
make[3]: *** [telegram-bot] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:162: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2

**Comment by levlam** [comment]
It is a problem with linking in libconfig++, required by tdbot. Here is the likely cause of the issue: https://github.com/hyperrealm/libconfig/issues/10. And the only solution is that tdbot should be compiled with the same standard C++ library as libconfig++.

**Comment by puryanms** [comment]
Im installed some libs
But steal i have this erorr
What should i install ?

**Comment by levlam** [comment]
Probably, you need to recompile libconfig++ with the same compiler that is used to compile tdbot.
