### ISSUE TITLE
conflict in Id of the message 

### ISSUE THREAD

**Issue by mostafa8026** [tdlib/td#511]
In my bot Api when it sends message, the received id is not the one which is must be. because later when I want to get this message, it returns null.
Consdier that the message sending status in this case is sendingStatePending and my message has inline query markup.

**Comment by levlam** [comment]
A yet unsent message has a temporary message ID, because persistent message ID can be assigned only by the server. You need to handle updateMessageSendSucceeded to correctly handle this change. Note that a lot of other fields besides message_id can change after successful message sending.
