### ISSUE TITLE
error in terminal 

### ISSUE THREAD

**Issue by Mohammadwh** [tdlib/td#514]
my bot print this error and change status to offline
[ 1][t 1][1553186089.422070026][MessagesManager.cpp:21569][!Td] Have full history in chat -1001081163428, but receive unknown server message 322600 from get history. Last new is server message 326099, last is server message 319292, first database is server message 1, last database is server message 319292, last read inbox is server message 326099, last read outbox is server message 326099, last read all mentions is invalid message 0, max unavailable is invalid message 0, last assigned is invalid message 0

how i can fix this error

**Comment by levlam** [comment]
This error means that TDLib has received supposedly unexisted message, which could be not returned in the chat history previously. It couldn't make the bot go offline or harm in any other way. Probably, you need to increase logs verbosity level to 2 or more to see real cause of your problem.

**Comment by levlam** [comment]
@Mohammadwh Have you resolved your issue?

**Comment by Mohammadwh** [comment]
hello yes i fixed it
but how i can delete all messages in supergroup for all members?

**Comment by levlam** [comment]
@Mohammadwh There is no way to delete all messages in a supergroup for all members except deleting them one by one.

**Comment by Mohammadwh** [comment]
yea but get history do flood :(

**Comment by levlam** [comment]
@Mohammadwh In this case it is intended.
