### ISSUE TITLE
question on getSupergroupMembers

### ISSUE THREAD

**Issue by pk0580** [tdlib/td#515]
Tell me, please, why does the getSupergroupMembers function returns an array less than the length specified in the total_count field? How do I get the actual number of users?

**Comment by levlam** [comment]
You need to repeat the request with adjusted offset parameter. There is no way you can get all supergroup members in one request, because supergroups can have up to 200000 members. It wouldn't work.

**Comment by pk0580** [comment]
Thank you for asking. But I do repeat the request with offset parameter. And still in the end I receive such array

**Comment by levlam** [comment]
See also https://github.com/tdlib/td/issues/507.

**Comment by pk0580** [comment]
Thank you. But there is nothing new for me. Even if the request returned a total_count less than 200, there may be less users in the array than total_count

**Comment by levlam** [comment]
@pk0580 There is no such users and there is nothing unexpected here. From the documentation: "total_count Approximate total count of chat members found". Usually, they are the same, but they can be different in case someone recently joined/left the chat or in some other circumstances.

**Comment by pk0580** [comment]
Thank you
