### ISSUE TITLE
[Missing] Support anonymous forwarding (privacy)

### ISSUE THREAD

**Issue by MarcAnt01** [tdlib/td#517]

**Comment by Sajilck** [comment]
https://telegram.org/blog/unsend-privacy-emoji

**Comment by levlam** [comment]
Support for managing whether a link to the user's account is included with forwarded messages was added in TDLib 1.5.0 via new privacy settings `userPrivacySettingShowLinkInForwardedMessages`. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
