### ISSUE TITLE
[Missing] Delete messages for other people

### ISSUE THREAD

**Issue by MarcAnt01** [tdlib/td#518]

**Comment by levlam** [comment]
In fact, you can already delete messages of other people and revoke messages without time limit. You can verify that by message.can_be_deleted_only_for_self and message.can_be_deleted_for_all_users flags. Any application, correctly handling these flag, already has that new feature.

**Comment by MarcAnt01** [comment]
If I select "delete this chat" I have no way to select if the chat has to be deleted for the other person or not (tested on Unigram and Telegram X).

**Comment by zelenin** [comment]
You asked a question about the function of **deleting a message** in the library, but now you are talking about the function of **deleting a chat** in third-party applications

**Comment by MarcAnt01** [comment]
> You have requested a question about the function of **deleting a message** in the library, but now you are talking about the function of **deleting a chat** in third-party applications

Both apps do use latest release of the library afaik. If it is something app-side it's different

**Comment by MarcAnt01** [comment]
OK, I have now understood that the action is performed, just no message shown by the application, will close this issue and sorry for the inconvenience
