### ISSUE TITLE
Connection through IPv6

### ISSUE THREAD

**Issue by rezam90** [tdlib/td#52]
Hi, I was wondering how to implement a connection through ipv6.
connection server is `IPv4` but the server proxies the connection through `IPv6`.

the `setProxy` with `@type: "proxySocks5"` not connecting.

**Comment by levlam** [comment]
TDlib supposed to work over IPv6 without any additional settings. Do you want to prefer IPv6 over IPv4 or have some proxy that is mandatory for the Internet access?

**Comment by rezam90** [comment]
I couldn't connect. how to connect to `ipv4` which gives an `ipv6`?
Isn't it the `setProxy` method? I do it before Auth and after auth. but gives `ok` and still proxy not working.
i'm using `go` to build and using the tdjson

**Comment by levlam** [comment]
setProxy currently allows only SOCKS5 proxies. Could you give more details on why you need to use a proxy?

**Comment by rezam90** [comment]
I have a SOCKS5 proxy. using the `setProxy` method and giving a `Proxy` json containing `server, port, username, password` fields returns `OK` which is good. but my proxy is IPv6.

I've used the socks5 proxy settings in Telegram X for both Android and iPhone.  But stucks in connecting.

I think It should take the IPv6 of telegram servers listed in DC options after I set to socks5 and IPv6.

**Comment by levlam** [comment]
IPv6 Socks5 proxies are expected to work in TDLib 1.3.0 (and hence in Android Telegram X). Please provide additional details, if IPv6 proxy still doesn't work for you.
