### ISSUE TITLE
Cannot get authorization

### ISSUE THREAD

**Issue by kehuiyu** [tdlib/td#520]
Hello:
       when I build the java project by cmake and run the main method,It stoped on "UpdateConnectionState",seems that caused by "nativeClientReceive" method...
so the authorization state never changed when I entered the phone number.
      Is there any other operation needed?
       many thanks!!

**Comment by levlam** [comment]
Which project did you build? If you are talking about our Java [example](https://github.com/tdlib/td/tree/master/example/java) then the console application should work just fine, provided the Telegram isn't blocked in your country.

You can also change TDLib logs verbosity level to 4, collect logs and send them to @tdlibbot, so I can tell  you exactly, what is wrong.

**Comment by kehuiyu** [comment]
@levlam Year,I mean the Java example, I run it on my IDE for test, according to your suggestion, I tried it again with the logs verbosity level changed to 4, and send the log file to @tdlibbot on Telegram app client(from @kehuiyu). 
  Thanks for checking it.
  BTW,I am In CN and the proxy is on.

**Comment by kehuiyu** [comment]
@levlam What confused me was when and how a new user registered to sqlite? the java Example prompted us to enter password on the third authorization steps but as new user the "setPassword" method have not been called yet..or should I enter nothing as empty?

**Comment by levlam** [comment]
@kehuiyu Something blocks connection to Telegram server, probably access to Telegram is blocked in your region. You need to use an MTProto, SOCKS5 or HTTP proxy to connect to Telegram servers by calling `AddProxy` method just after the client is created like this:
```
client.send(new TdApi.AddProxy("15.15.15.15", 12345, true, new TdApi.ProxyTypeHttp("username","password",false)), null);
```

The login is controlled by TDLib using UpdateAuthorizationState updates, user will not be asked for a password, if it didn't enabled 2SV previously.

**Comment by kehuiyu** [comment]
@levlam Got it，Thanks a lot！
