### ISSUE TITLE
How to add mutable-content to iOS push  notifications issued by

### ISSUE THREAD

**Issue by artua** [tdlib/td#521]
Hello!
How to add mutable-content flag to iOS push notifications issued by Telegram servers? I need to modify notifications before they are presented to user.

**Comment by levlam** [comment]
'mutable-content' is set by the server for non-VoIP pushes only if the system_version, specified by the application, is at least 10.0.0.

**Comment by artua** [comment]
We’re running iOS12 and there is no “mutable-content” set. Do we need to set it somewhere in code?

**Comment by levlam** [comment]
You can't set it, or change whether it is set or not. But you need to provide correct system_version in setTdlibParameters to have it.

**Comment by artua** [comment]
Thanks, it helps
