### ISSUE TITLE
[Missing] Emoji search

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#523]
https://telegram.org/blog/unsend-privacy-emoji

**Comment by levlam** [comment]
GIF search is done using a bot getOption("animation_search_bot_username"), which is available in TDLib 1.3.0. Sticker search is available through `searchStickers` method since TDLib 1.2.0.

Emoji search is a missing feature, which will be added in the future.

**Comment by levlam** [comment]
Support for emoji search was added in TDLib 1.5.0 via the method `searchEmojis`. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
