### ISSUE TITLE
[Missing] Emoji suggestion for first word

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#524]
https://telegram.org/blog/unsend-privacy-emoji

**Comment by Sajilck** [comment]
Duplicate of https://github.com/tdlib/td/issues/523

**Comment by levlam** [comment]
Support for emoji suggestions was added in TDLib 1.5.0 via method `searchEmojis`. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
