### ISSUE TITLE
getChats() not working at all

### ISSUE THREAD

**Issue by WebShark025** [tdlib/td#527]
Hello

I'm getting some troubles when using the 'getChats' method.
offset_order = `2 ^ 63 - 1`
offset_chat_id = `0`
limit = 500

```
    chatss = client.send(GetChats(2 ^ 63 - 1, 0, 50))
    chatss.wait()
    print(chatss.update)
```
and yet it returns:
```
{
    "@type": "chats",
    "chat_ids": []
}
```
and yes i have more than 60 chats open in that account.

What should I do? What am I doing wrong? I want to get a complete list of my open chats/dialogs in one request.

**Comment by zevlg** [comment]
@WebShark025 what was the reason?

**Comment by WebShark025** [comment]
@zevlg me being foolish. instead of **, I used ^ on `2^63-1` because it was used everywhere in the docs.
