### ISSUE TITLE
Import contact with empty first_name/last_name

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#528]
I've imported contact using just phone_number, with next call:

```
{"@type":"importContacts","contacts":[{"@type":"contact","phone_number":"+79033385XXX"}],"@extra":84}
```

Contact has been successfully imported, however first name of returned user is set to phone number and in official app this user appears as "Deleted Account"

Account is definitely not deleted, since we've been able to chat with each other.

Is there method to get first/last name of the user that he specified at registration time?

Thanks

**Comment by levlam** [comment]
First name is replaced with phone number by TDLib, whenever the first name is empty. "Deleted Account" looks like a bug of the official app.

There is no method to get first/last name of a user that he specified at registration time. The only way to get them is to remove the user from contacts. Alternatively, you can forward a message from the user to a bot, which dumps every incoming update. The bot will see a name specified by the user himself.

**Comment by zevlg** [comment]
Removing contact did a trick!  I've got `userUpdate` event with first/last name set.  Also official app corrected the title for that user
