### ISSUE TITLE
Why push notifications come when sending inputMessageText, but do not come when sending inputMessagePhoto?

### ISSUE THREAD

**Issue by descentcornell** [tdlib/td#531]
Messages are sent from the IOS simulator to the real device.
Both messages are successfully delivered. Here is an example of the message body:

{
   "@type" = sendMessage;
    "chat_id" = "-39102”;
    "disable_notification" = 0;
    "input_message_content" =     {
        "@type" = inputMessagePhoto;
        caption =         {
            "clear_draft" = 0;
            "disable_web_page_preview" = 1;
            text = "Hi!";
        };
        height = 729;
        photo =         {
            "@type" = inputFileLocal;
            "expected_size" = 94028;
            path = "/Users/sergeiserg/Library/Developer/CoreSimulator/Devices/221E8B77-B97D-4119-82AC-D9DF3588E0FF/data/Containers/Data/Application/72FE99D1-7FDB-4AF0-A310-C1C4097A1CE9/tmp/576188722.jpg";
        };
        width = 414;
    };
    "reply_to_message_id" = 0;
}

{
    "@type" = sendMessage;
    "chat_id" = "-39102”;
    "disable_notification" = 0;
    "input_message_content" =     {
        "@type" = inputMessageText;
        text =         {
            "clear_draft" = 0;
            "disable_web_page_preview" = 1;
            text = "No problem";
        };
    };
    "reply_to_message_id" = 0;
}

**Comment by levlam** [comment]
Photos with caption currently shown in push notifications as text messages and have `loc_key` "MESSAGE_TEXT", but the notification should be shown nevertheless. You can test that push notification about photos are received in the official Telegram app.
