### ISSUE TITLE
Different message id for same message for different user 

### ISSUE THREAD

**Issue by leonidUH** [tdlib/td#533]
I have two different clients for two different users  that subscribed to the same group.
When i get messages (GetChatHistory) for each user  i see that same message for each user come with different 'id'.
if I have some way to understand that this is the same message or maybe to make something that the messages were returned with the same id?

**Comment by levlam** [comment]
This is an expected behavior. Message id will be the same only in supergroups (and channels). There is no way to surely match the same message for different users.

**Comment by alirezasam** [comment]
۱۳۹۸-۰۲-۱۰ ۰:۳۲ ‎+۰۴:۳۰ گرینویچ, Aliaksei Levin <notifications@github.com>:

**Comment by tka4ukalex** [comment]
have question? what will be if i will try to match by message.date + message.chatId, can it be guaranteed that message date will not be changed for the same message but for different users? talking only about simple direct chat?

**Comment by levlam** [comment]
>  can it be guaranteed that message date will not be changed for the same message but for different users?

No, you can't assume that the date is the same.

> May be someone can create useful documentation for such cases? there is no word about such behavior anywhere except

Data seen by other users are completely unrelated and useless for the current logged in users.
