### ISSUE TITLE
opening new chat fail when two different clients try create a chat with same destination user

### ISSUE THREAD

**Issue by sotobotero** [tdlib/td#535]
Hello, I have a problem trying open a new chat, it is reached when two different clients try to create a chat with the same destination user.

I am susing new TdApi.CreatePrivateChat(userId,false), please I would like to know if TDlib have some mistake.

here is the full log.

I/DLTD: [ 3][t 3][1555260059.309557199][Td.cpp:3302][!Td][&td_requests]	Receive request 24: CreatePrivateChat {
userId = 876252304
force = false
}
I/DLTD: [ 3][t 3][1555260945.418469906][Td.cpp:3302][!Td][&td_requests]	Receive request 25: CreatePrivateChat {
userId = 876252304
force = false
}
[ 3][t 3][1555260945.418592215][Td.cpp:577][!CreateChatRequest]	Receive error for query: [Error : 6 : Chat info not found]
[ 3][t 3][1555260945.418617249][Td.cpp:4262][!Td][&td_requests]	Sending error for request 25: Error { code = 6 message = "Chat info not found" }

horever, if I try to open chat from telegram aplication whit the same destination user, it works, the problems is only in TDlib.
help me please, I have long time working whit this aplication and I do would not like left the project.

**Comment by levlam** [comment]
The error means that there is no information about user 876252304. You need to load it from the database first using getUser method, or in any other way receive it from the server.

**Comment by sotobotero** [comment]
Thankyou for answer but I think I did not make myself understood. For my self app all are working fine, but the problem is reached when try open a chat whit some userid gived(876252304).

My TDLib implementation consist of a lot of  users (app client) that need comunicate each others, but them are not contacts yet, each  app know every user id that wish to contact (ie: the las userid 876252304 is a customer different that me), what is the method for open (create or start new chat ) betwen them? Or maybe it is not posible using TDLlib?

Thankyou in advance.

**Comment by levlam** [comment]
A chat can't be created with a user just by the user_id, otherwise it would be a privacy issue. The app need to receive the user from the server first. There are a lot of ways to find the user. For example, users with a username can be found using `searchPublicChat`/`searchPublicChats`. Users also can be found in the chat list via `getChats`/`searchChatsOnServer` or in a group chat among members.

**Comment by sotobotero** [comment]
Could you explain please, How to send invitation for chatting, or some method for add contact for example? because I can not find one in documentation.

The methods getChats/searchChatsOnServer don not work either because chat are not created yet (That is precisely that I want, to create a new chat with unknown user that have been registered in telegram through my app).

I understand privacy issues, but I can't find a way for start a one2one chat without talk first with the user. (which it could be useless because a chat application should be allow send invitations to unknown user for start a conversation across the same app).
The above method (searchPublicChat/searchPublicChats) that you said, these not work for this case,  because if you want open a chat with unknown user you don't have any data for search a chat, because it do not exist yet. On the other hand, if you try to find user by username it could be empty and not unique (it have tried it) because telegram allow create user with this  empty field.


A lot of thanks.

**Comment by zelenin** [comment]
> if you want open a chat with unknown user you don't have any data for search a chat

do you want start a chat with random user? so you are spammer.
Otherwise you have @username of telegram user and can search with ```searchPublicChat```

**Comment by sotobotero** [comment]
Oh no, I don't want start a chat with random user, I have the userid as I mentioned before, but it no work, and  if I try to use @username what would happen if it is empty ? , because telegram allow create it with empty  username.

**Comment by levlam** [comment]
@sotobotero You can't start a new chat with a user just by the user_id, otherwise spammer could just easily spam users. How exactly you have got the user_id? Have you got it through Telegram Login Widget?

**Comment by sotobotero** [comment]
My main App consist of ecommerce solution  and I am trying to use Telegram for chat module(online messaging).
When some user want to contact with other I force him to logging in telegram through my app using TDlib or registry him if he don’t have account yet in telegram, in this moment my app will know the userId and store in the server with your other data.
Then when some user try to start a chat with him, my application could query your user_id from the server and start a conversation.

**Comment by levlam** [comment]
It is not possible to start the conversation in your situation, because second user never met the first user in Telegram. There is no easy way for users to meet each other. One way to achieve that is to send a message from both users to a dedicated public user account, which can be found by its username through `searchPublicChat` method. Then the dedicated account can pass information about first user to the second user in a message using `textEntityTypeMentionName`.

**Comment by GemChung** [comment]
i need how to createprivatechat with another member in the same supergroup.

**Comment by levlam** [comment]
@GemChung Have you read https://core.telegram.org/tdlib/getting-started? If you have received the user through list of chat members, then you just need to call `createPrivateChat` method with user_id of the user. You will receive `Chat` in response and will be able to use the chat after that.

**Comment by sotobotero** [comment]
> It is not possible to start the conversation in your situation, because second user never met the first user in Telegram. There is no easy way for users to meet each other. One way to achieve that is to send a message from both users to a dedicated public user account, which can be found by its username through `searchPublicChat` method. Then the dedicated account can pass information about first user to the second user in a message using `textEntityTypeMentionName`.

Oh! it's so sad to hear it, because I love telegram and I think there are a lot of developers growing application that had the same needs like me , that could bring a lot of user to telegram, but in other hand if TDLib are not mature enough yet, we will have to change to other alternatives, by the momento I’ll change to firebase.
Thank you.

**Comment by zelenin** [comment]
@sotobotero 
> if TDLib are not mature enough yet

it's a telegram privacy issue, not tdlib.
