### ISSUE TITLE
after i test tdapi clearImportedContacts use my account,

### ISSUE THREAD

**Issue by GemChung** [tdlib/td#536]
i study tdlib , test api clearImportedContacts, after this, now in my phone official version, every time enter telegram , will tip"there are a lot of unsync contact, wheather sync?", then, i click confirm.

but now every time show this tip .

how can i resolve this?

**Comment by levlam** [comment]
It sounds like a bug of the application. Which application are you using on the phone?

**Comment by GemChung** [comment]
my telegram version is Telegram for Android V5.5.0(1545) arm64-v8a

**Comment by levlam** [comment]
Have you granted permission for accessing your contacts to the application?

**Comment by levlam** [comment]
@GemChung I need more details before I can report the problem to the app developer. So, have you granted permission for accessing your contacts to the application? Is it still shown to you every time?

**Comment by levlam** [comment]
Closing this because it doesn't look like a TDLib's issue and the lack of a feedback.
