### ISSUE TITLE
Unable to get PROFILE_PHOTO from user

### ISSUE THREAD

**Issue by dangelm** [tdlib/td#537]
Hi,

When using API TdApi.GetRemoteFile for getting profile photo of a user i am getting an error for multiple photoID's of multiple users.
For example:
When getting a user via the api TdApi.GetUser i am getting the following user:

`User {
  id = *****
  firstName = "*****"
  lastName = ""
  username = "*****"
  phoneNumber = ""
  status = UserStatusOffline {
    wasOnline = 1555502798
  }
  profilePhoto = ProfilePhoto {
    id = 42903528287610799
    small = File {
      id = 1
      size = 0
      expectedSize = 0
      local = LocalFile {
        path = ""
        canBeDownloaded = true
        canBeDeleted = false
        isDownloadingActive = false
        isDownloadingCompleted = false
        downloadedPrefixSize = 0
        downloadedSize = 0
      }
      remote = RemoteFile {
        id = "AQADBQADr6cxG4hsmAAJJRkdLAAESZLcts0JOxKJKAACAg"
        isUploadingActive = false
        isUploadingCompleted = true
        uploadedSize = 0
      }
    }
    big = File {
      id = 2
      size = 0
      expectedSize = 0
      local = LocalFile {
        path = ""
        canBeDownloaded = true
        canBeDeleted = false
        isDownloadingActive = false
        isDownloadingCompleted = false
        downloadedPrefixSize = 0
        downloadedSize = 0
      }
      remote = RemoteFile {
        id = "AQADBQADr6cxG4hsmAAJJRkdLAAEdLAtWIvZa7KLKAACAg"
        isUploadingActive = false
        isUploadingCompleted = true
        uploadedSize = 0
      }
    }
  }
  outgoingLink = LinkStateNone {
  }
  incomingLink = LinkStateNone {
  }
  isVerified = false
  restrictionReason = ""
  haveAccess = true
  type = UserTypeRegular {
  }
  languageCode = ""
}`

Later, when calling api with photo id of the remote file:
TdApi.GetRemoteFile(AQADBQADr6cxG4hsmAAJJRkdLAAESZLcts0JOxKJKAACAg, PROFILE_PHOTO)

I am unable to get the file with local path as empty string.
Please advise.

Thanks!

**Comment by levlam** [comment]
Are you trying to use `getRemoteFile` instead of `downloadFile`? `getRemoteFile` is needed only to save and restore information about a file outside of TDLib database between application restarts.

**Comment by dangelm** [comment]
Actually i am using downloadFile as well.
Moreover, in some cases downloadFile is returning a valid response with path that is not empty

**Comment by levlam** [comment]
`downloadFile` begins to asynchronously download the file. You need to handle `updateFile` and wait until the `local.is_downloading_active` became false. If that's exactly what you do then could you collect TDLib log with verbosity level 4 with failed `downloadFile` request and send it to @tdlib_bot?

**Comment by dangelm** [comment]
Hi,
I found the root cause of this issue.
Telegram was blocking the proxy which i use. I tried a proxy with different country and it worked.

**Comment by levlam** [comment]
@dangelm It is possible, but whoever blocked the proxy is not Telegram.

**Comment by dangelm** [comment]
do i have any possibility to catch such behavior in advance?

**Comment by levlam** [comment]
It is theoretically impossible to know whether a proxy will work before actually trying to use it.

**Comment by dangelm** [comment]
I see..
Ok then.. thanks a lot!
