### ISSUE TITLE
Getting chat ids from void method

### ISSUE THREAD

**Issue by DarkHellbat** [tdlib/td#538]
I need to get user's chat list with its ids and write it into variable. I use tdlib and c# for my project. In example app list written in console by  Client.Send(new TdApi.GetChats(Int64.MaxValue, 0, 100), defaultHandler) method, which is void-like, so I can't get anything from it. I can't try Client.Receive because there is no such method (or IntelliSence told me so). Is there any solution or example for getting chats in another way?

**Comment by levlam** [comment]
In the .Net native wrapper requests ane responses are matched automatically, you need to only pass a handler to `Client.Send` call which will be used to handle the response. You pass `defaultHandler` from our example, which just prints the result. You need to implement another handler if you want another behavior. See https://github.com/tdlib/td/blob/master/td/telegram/ClientDotNet.cpp for the full documentation of the `Client` class.
