### ISSUE TITLE
application stop to getting updates.

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#539]
sometimes, after some actions, my application stop to getting updates.

E.g. when, i send some message to somebody in my native android application (made by telegram) - my application (where i logged also) stoping getting update for some time (for 1 minute or more) but after  i close my application and login to it again, then i'll getting all old updates...

Anybody kown why? it is very strange.
Please help me with it.

**Comment by levlam** [comment]
First, you need to check whether you have an active connection. The client receives `updateConnectionState` for that. Also, make sure that you properly set option "online" to true whenever you use the application. If this doesn't help then enable TDLib logs with verbosity level 3 to see, what's going on.

**Comment by levlam** [comment]
@merlinkory Have you solved the problem? It seems that you are from Russia, so you may need to add a proxy using `addProxy` method to have a stable connection.

**Comment by merlinkory** [comment]
@levlam My app hosted on Amazon (EU). What is option "online", is it some parametrs for "setTdlibParameters" ? And do i can updating my connection state?

Thank you

**Comment by levlam** [comment]
@merlinkory Options are set through `setOption` method. See https://core.telegram.org/tdlib/options for the full list of available options.

The only purpose of `updateConnectioneState` is to show the connection state to the user. You can't affect it, except completely disabling network via `setNetworkType` method.

**Comment by merlinkory** [comment]
@levlam Thank you very much!!!
