### ISSUE TITLE
FR: custom calls

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#540]
I'd like to implement custom P2P communication between two telegram clients.  libtgvoip kind of allows this (see https://github.com/grishka/libtgvoip/issues/84), however in TDLib 1.3.0 there is no way to distinguish ordinary and custom calls.

It would be nice if `createCall` could provide some kind of "token", that is transmitted as a part of `CallState` to the other side.  So telegram client could implement "token" dispatching for custom P2P communication

Thanks

**Comment by FrayxRulez** [comment]
You can use tgvoip capabilities to determine if the other client supports your custom protocol. They're used already for group and video calls.

**Comment by zevlg** [comment]
@FrayxRulez ah, nice to know!  I'll dig into libtgvoip deeper, thanks

**Comment by zevlg** [comment]
@FrayxRulez is it possible to get know "kind" of the call before accepting, by just using libtgvoip without TDLib support?

**Comment by levlam** [comment]
@zevlg It is not possible. It should be supported by the Telegram API and there is no place for such data there.

**Comment by levlam** [comment]
Closing this because there is no way it can be supported by TDLib without corresponding unlikely changes in the Telegram API. The better way to achieve this is to create an ordinary call and agree on a custom protocol through libtgvoip as suggested by @FrayxRulez.
