### ISSUE TITLE
TDLib: Ask questions about user avatars or profile_photo

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#541]
When I use the TDIb getUser to get Userinfo, the profile_photo information should be the data belonging to the avatar information, but how can I make this data appear in my application?Please give a method。

**Comment by levlam** [comment]
If you want to download the photos, you need to use `downloadFile` method.

**Comment by AquariusHunters** [comment]
> 如果要下载照片，则需要使用`downloadFile`方法。

If I use the downloadFile method, this is to generate the corresponding file in the photos directory, but this downloaded file is not the file I want to display the user's avatar. I consulted the TDRib document, the document display will return a file, I Look at the file returned in my log does not have any information attached, and my purpose is not how to download a picture from the chat, but how to let my application display the avatar of the object I chat with on the interface, after all, Chatting with a black frame makes people feel less comfortable.

**Comment by levlam** [comment]
@AquariusHunters Yes, downloadFile will make the file available in the photos directory. After that you can read it and show to the user. Profile picture is a file, and it needs to be downloaded first via `downloadFile`.

**Comment by AquariusHunters** [comment]
> @AquariusHunters是的，downloadFile将使文件在照片目录中可用。之后，您可以阅读并向用户显示。个人资料图片是一个文件，需要先通过下载`downloadFile`。

**Comment by AquariusHunters** [comment]
> @AquariusHunters Yes, downloadFile will make the file available in the photos directory. After that you can read it and show to the user. Profile picture is a file, and it needs to be downloaded first via `downloadFile`.

Sorry, my expression may be misunderstood. I mean how to get the profile photo of the chat object instead of downloading the profile photo to the local directory, so I don't think it is convenient.  I can get a remote URL to download the corresponding profile photo into my program's memory, and then display it. It's not that I want to download it to the local directory. I don't think this is a good way. I should Where is he going to deal with him?

**Comment by levlam** [comment]
A chat photo must be saved to the local directory in order to not be redownloaded on every application restart and to be available without Internet access. There is no way in TDLib you can get a chat photo only in memory without saving it on the drive, Why you can't read a local file and show a photo from the file?

**Comment by AquariusHunters** [comment]
> 必须将聊天照片保存到本地目录，以便在每次重启应用程序时都不会重新加载，并且无需Internet访问即可使用。在TDLib中你无法在内存中获取聊天照片而不将其保存在驱动器上，为什么你无法读取本地文件并显示文件中的照片？

How do I use these downloads to save local images? Did I look at the 10,000 members of the Super Group members and I have to save the profile photos of these 10,000 members locally? If so, how do you map these photos stored locally to these 10,000 members?

**Comment by AquariusHunters** [comment]
> A chat photo must be saved to the local directory in order to not be redownloaded on every application restart and to be available without Internet access. There is no way in TDLib you can get a chat photo only in memory without saving it on the drive, Why you can't read a local file and show a photo from the file?

When I use the getRemoteFile api, I get a json about the file. Can I match the file according to the data value of the remote, then when I use the downloadFile, the ID is the short int in the file. So how do I put him in the directory I want instead of the photos directory? After all, there are some other weird files in this directory.

**Comment by levlam** [comment]
@AquariusHunters Each file has a unique ID, which is used to download the file. You need to listen to `updateFile` updates to follow download progress. Since TDLib 1.4.0 you can also use parameter `synchronous` in `downloadFile` request to receive the response from `downloadFile` only after the download is finished.

**Comment by AquariusHunters** [comment]
> @AquariusHunters Each file has a unique ID, which is used to download the file. You need to listen to `updateFile` updates to follow download progress. Since TDLib 1.4.0 you can also use parameter `synchronous` in `downloadFile` request to receive the response from `downloadFile` only after the download is finished.

Do I need to go to the updatefile to determine and download the user's avatar? Isn't it going to use the download in the file as I thought? But I tested it, I used download under file but didn't see the user avatar file I downloaded in the profile_photo directory.

**Comment by AquariusHunters** [comment]
@levlam 
Json::Value photoInfoJsonx;
photoInfoJsonx["@type"] = "downloadFile";
photoInfoJsonx["file_id"] = root["id"].asString();
photoInfoJsonx["priority"] = 1;
td_json_client_send(client, photoInfoJsonx.toStyledString().c_str());
This is how I use downloadFile. Do you have any problems with this? I am using it under the type of file.

**Comment by levlam** [comment]
@AquariusHunters Does `root["id"].asString();` is an identifier of the file, i.e. user['profile_photo']['small']['id'] or user['profile_photo']['big']['id']?

`updateFile` is an update. It will be sent whenever anything about a file, including number of downloaded bytes, is changed.

**Comment by AquariusHunters** [comment]
@levlam 
I use FileTypeJson["@type"] = "fileTypeProfilePhoto" ;
getRemoteFileJson["@type"] = "getRemoteFile";
getRemoteFileJson["remote_file_id"] =user_remote_profile_photo["id"].asString();
getRemoteFileJson["file_type"] = FileTypeJson;
Td_json_client_send(client, getRemoteFileJson.toStyledString().c_str());
under Userinfo Come to get it file
{"@type":"file","id":876,"size":0,"expected_size":0,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AQADBQADq6cxG23h-RwACJ0n1TIABAb6UKZzz8qSzzYCAAEC","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":0}}
Then use the download according to the id of the file Such as 876

**Comment by levlam** [comment]
@AquariusHunters The ID is correct. The download of the file begins after call to `downloadFile`. After the call you need to wait for `updateFile` for the file with file["local"]["is_downloading_active"] == false. If after the downloading is finished file["local"]["is_downloading_completed"] == true, then in file["local"]["path"] there will be a path to the file. If you use TDLib 1.4.0 and pass "synchronous" == true parameter to `downloadFile`, then you can handle only `downloadFile` response instead of `updateFile` updates.

**Comment by AquariusHunters** [comment]
> @AquariusHunters The ID is correct. The download of the file begins after call to `downloadFile`. After the call you need to wait for `updateFile` for the file with file["local"]["is_downloading_active"] == false. If after the downloading is finished file["local"]["is_downloading_completed"] == true, then in file["local"]["path"] there will be a path to the file. If you use TDLib 1.4.0 and pass "synchronous" == true parameter to `downloadFile`, then you can handle only `downloadFile` response instead of `updateFile` updates.

Thanks for your help, I have already got profile_photo, but I found a problem. Some of the Userinfo I got from UpdateUser have no profile_photo information. I think this is not normal. Every user should not have one. Profile_photo? Even this avatar is the default.

**Comment by AquariusHunters** [comment]
> No. A lot of user has no profile photo. In that case it is generated client-side from first letters of user's name.

thank you very much ，I will be helpless without your help.
