### ISSUE TITLE
TDWeb usage docs?

### ISSUE THREAD

**Issue by mnb3000** [tdlib/td#542]
tdlib 1.4.0 ships with TDWeb lib, any usage docs available?

**Comment by levlam** [comment]
What exactly do you need beyond available in https://www.npmjs.com/package/tdweb?

**Comment by mnb3000** [comment]
Can TDWeb be used within node.js environment?
If so, only with native ES modules, or CommonJS is also available

**Comment by mnb3000** [comment]
Ok, now I see that it's supposed to be used with webpack inside browser environment.

**Comment by levlam** [comment]
tdweb is for web, browsers only.

In Node.js you could use TDLib directly. We have now 7 Node.js wrappers in the [examples](https://github.com/tdlib/td/tree/master/example#javascript).

**Comment by mnb3000** [comment]
Thanks a lot, haven't seen those wrappers
