### ISSUE TITLE
Missing Git tag

### ISSUE THREAD

**Issue by xvitaly** [tdlib/td#543]
Can you create Git tag for version 1.4.0? Maintainers of GNU/Linux distributions need it.

**Comment by danielperez9430** [comment]
@xvitaly devs say: "I need to process pull requests. I will also wait some time for reports before assigning 1.4.0 tag."

You need to wait :smile:

**Comment by xvitaly** [comment]
OK, no problem.

**Comment by levlam** [comment]
TDLib has been updated to 1.4.0.
