### ISSUE TITLE
How can i determine whether a mobile phone number is registered without bothering ？

### ISSUE THREAD

**Issue by mahonglu123** [tdlib/td#545]
How can i determine whether a mobile phone number is registered without bothering ？
thanks

**Comment by levlam** [comment]
There is no method which retruns this information for a given phone number. If you are trying to log in, you will receive `is_registered` field in the `authorizationStateWaitCode`.

**Comment by levlam** [comment]
Authorization workflow was changed in TDLib 1.5.0, so it is impossible now to know whether a mobile phone number is registered without first entering an authentication code.
