### ISSUE TITLE
All the documentation and download links are unresponsive.

### ISSUE THREAD

**Issue by cannizarro** [tdlib/td#546]

**Comment by cannizarro** [comment]
I am trying to build android project on this API and I am having a hard time figuring what to do as there is barely any source out there for it and the documentation links are all unresponsive.
Please help as I have a deadline for an interview to make this project.
You can give recommendations on how and where to get started. Started like from scratch how to add its dependency when there seems to be none. 
Please Help.

**Comment by levlam** [comment]
All the documentation you need is available in our [README](https://github.com/tdlib/td/blob/master/README.md). There you can find how to use and how to build the library.
