### ISSUE TITLE
How do I access the documentation to know the implemented methods and variables of  tdlib?

### ISSUE THREAD

**Issue by cannizarro** [tdlib/td#547]
I want to build a basic android app for testing purposes and I am not able to access the documentation as the pages are unresponsive and not loading. 
Please help as there are very few sources to learn this for android and if you know please share some.

**Comment by mazenkh7** [comment]
I go to the javadoc folder in tdlib and open index.html, works normally
but honestly i don't really find the methods descriptions very useful sometimes

**Comment by cannizarro** [comment]
@levlam In the Java Example while creating a client we run the following code :

`
        // disable TDLib log
        Client.execute(new TdApi.SetLogVerbosityLevel(0));
        if (Client.execute(new TdApi.SetLogStream(new TdApi.LogStreamFile("tdlib.log", 1 << 27))) instanceof TdApi.Error) {
            throw new IOError(new IOException("Write access to the current directory is required"));

        }
`
Even though I have provided read and write permissions it is still throwing the IOError "Write access to the current directory is required".

I am really new to this. Please Help.
