### ISSUE TITLE
Deleting account by your friends

### ISSUE THREAD

**Issue by 4qronda** [tdlib/td#548]
Hi.
As everyone knows the telegram is a highly secure messager. But nobody protect telegram account and private date (information from the chats) from the mobile's loosing or stealing. If mobile phone has been stolen thief can get the access to the private chats.
To reduce the problems after such situation I suggest you to make new fuction by wich you can give someone right to delete your account. This persone can do it with out any your approve. That's mean that if you lose your phone your friend can help you and keep out the private information from strangers.
Or it can be not one person. It can be several persons and your account can be deleted if they activate function of the deleting your account together.

**Comment by indeec05** [comment]
This may be the solution.
+
