### ISSUE TITLE
How do I use Firebase cloud messaging to receive push notifications

### ISSUE THREAD

**Issue by mazenkh7** [tdlib/td#549]
In Android, Java;
Since FCM, should be same as GCM
I did the following after i created a Client object:

FirebaseInstanceId.getInstance().getInstanceId()
                .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                    @Override
                    public void onComplete(@NonNull Task<InstanceIdResult> task) {
                        if (!task.isSuccessful()) {
                            return;
                        }
                        // Get new Instance ID token from Firebase
                        token = task.getResult().getToken();
                        if (getToken() != null && !getToken().isEmpty())
                            client.send(new TdApi.RegisterDevice(new TdApi.DeviceTokenGoogleCloudMessaging(getToken()), null), null);
                    }
                });

the token is registered successfully but i get no notifications at all, the function (onMessageReceived) doesn't get called.

 is there anything else i should do? (i actually don't know what 'otherUserIDs' is and how to use it)

**Comment by mazenkh7** [comment]
Thanks a lot for your help,
now after I did all that, I receive a "pushReceiver ID" from the `registerDevice` function, but that's all
no notifications are received (`onMessageReceived` from the my `FirebaseMessagingService` is never called) or is this normal behavior and I should find the notifications elsewhere?
I read this https://core.telegram.org/tdlib/notification-api but i didn't quite understand where the PUSH notifications are received.
thanks.

**Comment by levlam** [comment]
To use TDLib Notification API you need to receive push notification as usually, then convert notification payload to JSON similar to examples in https://core.telegram.org/tdlib/notification-api#handling-push-notifications and pass it to `ProcessPushNotification`.

If you don't receive notifications through `FirebaseMessagingService.onMessageReceived` you need to recheck that server has accepted your `GCM API key`, that you use your API ID in the app and that you pass correct token to `registerDevice`. If this doesn't help please write API ID, user_id and other details to @tdlib_bot.

**Comment by mazenkh7** [comment]
Thanks its showing successfully now, you're helpful and patient!
The bot is amazing too.

**Comment by levlam** [comment]
If the user is offline, notifications are delayed in order to give him a chance to read the messages from a different device before the notification is shown.

**Comment by MattNguyen** [comment]
> First of all, you need to register your app at https://my.telegram.org, obtaining api_id and api_hash, choose app's operating system as Android and then upload FCM certificates for your app.

@levlam I don't see this section in the app anymore. Is it still possible to register FCM certs?

cc/ @kiasaki

**Comment by MattNguyen** [comment]
Looks like the push-notification option appears when you select android, not web. Is there a way to change the platform or revoke the api key/hash?

**Comment by levlam** [comment]
@MattNguyen FCM certificates is possible to register only if you are developing for Android and have chosen Android as operating system for your application. There is no way to change chosen platform after application is created.

**Comment by ljmartinez1994** [comment]
Hi. I have already registered the device on Firebase, Telegram, have all. I run. Receive correctly the receiver id. So, my question is: Whats next? Because in the documentation say that have to enter on updateActiveNotifications  and is not doing that.
What i have to do,once i have the receiver ID?

**Comment by levlam** [comment]
ReceiverId is needed to launch correct TDLib instance with the same receiverId received from registerDevice. If you have only one account, then you don't need to use receiverId at all.

**Comment by ljmartinez1994** [comment]
Accounts? Do you refer to user telegram account? I don undestand to you very well. 
Even is that, Tdlib is entering on some status, the user have pending notifications and tdlib do nothing.

**Comment by levlam** [comment]
@ljmartinez1994 Send logs with verbosity level 4 to @tdlib_bot.

**Comment by bantonen** [comment]
> recheck that server has accepted your `GCM API key`

@levlam Hi, how can i check that the server has accepted my GCM API key?

**Comment by levlam** [comment]
@bantonen If you didn't receive an error while uploading the certificate at my.telegram.org, then it was accepted,

**Comment by bantonen** [comment]
@levlam but if I am using Android, as I understand it, I do not need a certificate, right?

**Comment by levlam** [comment]
@bantonen You need to upload a valid API key from console.cloud.google.com for your api ID at my.telegram.org. Otherwise, Telegram will not be able to send push notifications to your app.

**Comment by bantonen** [comment]
@levlam You mean these api keys https://firebase.google.com/docs/projects/api-keys#create-api-keys ?

**Comment by levlam** [comment]
@bantonen On this page there is a link to https://console.cloud.google.com/apis/credentials.

**Comment by bantonen** [comment]
@levlam I am loading this api but no notifications are coming. Can you please tell me what the problem might be. My app id (492896)

**Comment by levlam** [comment]
@bantonen You also need to write your user_id to @tdlib_bot.

**Comment by atiyka** [comment]
@levlam I'm also stuck with the push notifications in my android app. I set up correctly the google-services.json in the app (the firebase connection works fine) and set the api key as well on my.telegram.org.
I'm using this code to register the device:
```
FirebaseMessaging.getInstance().getToken().addOnCompleteListener(task -> {
    String token = task.getResult();
    TdApi.DeviceToken dtoken = new TdApi.DeviceTokenFirebaseCloudMessaging(token, false);
    mTdClient.send(new TdApi.RegisterDevice(dtoken, null), result -> { ... });
});
```
It returns error code 400, with message: APP_PUSH_APIKEY_MISSING
But what is missing when I set the correct api key?

**Comment by king-ma1993** [comment]
@levla How can I know if the API key I set is correct? After setting it, I still don't receive notifications. I'm looking forward to your reply.

**Comment by king-ma1993** [comment]
@levlam How can I know if the API key I set is correct? After setting it, I still don't receive notifications. I'm looking forward to your reply.

**Comment by levlam** [comment]
You will receive an error about invalid API keys for any request.

**Comment by king-ma1993** [comment]
@levlam Where can I see the error messages? After setting the API key, I directly saved it and there was no error reported, but I'm developing an Android app.Can I add you on Telegram? I hope you can guide me through this. Thank you very much.

**Comment by levlam** [comment]
Ah, sorry. Currently, there is no way to troubleshoot missing or invalid FCM certificate, because errors happen much later than certificate is set. The app will receive no push notifications, and there is no way to find the reason.

**Comment by king-ma1993** [comment]
@levlam Can you tell me where to obtain the correct API key? Currently, Google Firebase has been modified, and I don't know where to get the correct API key.

**Comment by levlam** [comment]
I don't know, where the certificate can be found now. Support for new FCM API will be added soon, but the old one still work and certificate for it should be available somewhere, unless Google intentionally removed possibility to access it to force switch to the new API.

**Comment by king-ma1993** [comment]
![image](https://github.com/tdlib/td/assets/77381352/834b984a-3867-4379-ae32-caef56501ead)
@levlam I think you should launch support for the new API as soon as possible. I saw in Google's Firebase backend that the old API key will not be usable at all starting from June 20, 2024. So, please update it as soon as possible. Also, will you update support for the new API on https://my.telegram.org at that time?

**Comment by levlam** [comment]
Yes, there should be changes at https://my.telegram.org/.

**Comment by levlam** [comment]
I have found that "Starting from 5/20/2024, new projects will no longer be allowed to enable our legacy APIs.", so you need to wait for the support of the new API, which is expected soon.

**Comment by king-ma1993** [comment]
@levlam How long will it take to support the new API? Thank you for your support.

**Comment by levlam** [comment]
It is supposed to be publicly available before June 20.

**Comment by levlam** [comment]
@king-ma1993
It should be already possible to upload FCM credentials at api.telegram.org to use new push notification API.

**Comment by ponecrazy** [comment]
Hi，I see the change, but why does the credentials JSON file returned by Google(Service Account by Firebase Admin SDK) report as invalid when I try to upload it? Do I need to convert it to a different format? Or did I get the wrong file?

**Comment by ponecrazy** [comment]
@levlam  Hi，I see the change, but why does the credentials JSON file returned by Google(Service Account by Firebase Admin SDK) report as invalid when I try to upload it? Do I need to convert it to a different format? Or did I get the wrong file?

**Comment by levlam** [comment]
@ponecrazy Could you try again now?

**Comment by ponecrazy** [comment]
@levlam I've upload the JSON file successfully, It's weird because i upload the same file which is failed before; 
Regardless, I have successfully uploaded it, but after testing, it seems not to have taken effect. Is there a certain amount of time needed for the configuration to take effect?

**Comment by ponecrazy** [comment]
@levlam Now push is working, previously it was not successful because I changed the appid without relogging in. Thank you for your support.

**Comment by AnotherNNBox** [comment]
> You will receive an error about invalid API keys for any request.

Hi, sorry to bother you.
I think I uploaded the service account JSON file correctly, and then built the apk using my own app id and hash, but the logs always show "registered push = 0", and I'm not receiving any notifications.

**Comment by levlam** [comment]
@AnotherNNBox The error "registered push = 0" isn't from TDLib.

**Comment by AnotherNNBox** [comment]
> [@AnotherNNBox](https://github.com/AnotherNNBox) The error "registered push = 0" isn't from TDLib.

hmm ok, thank you for your reply. I will try again
