### ISSUE TITLE
tdweb: missing support for reading file parts

### ISSUE THREAD

**Issue by Niek** [tdlib/td#550]
From the tdweb source:
https://github.com/tdlib/td/blob/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/example/web/tdweb/src/index.js#L25

However, the tdweb build used in telegram-react does have this functionality:
https://github.com/evgeny-nadymov/telegram-react/blob/35b69bc3d6fcd509f4ddd8e4287af483aed70fbb/public/tdweb.js#L4229-L4230

Any chance to add this to the build of tdweb too?

**Comment by levlam** [comment]
@Niek In fact, telegram-react uses pre-release version of tdweb with non-replaced `readFilePart` method and calls TDLib's `readFilePart` methods. TDLib in tdweb has no access to files after they are downloaded, because they are moved from memory to IndexedDB, so the method there doesn't work for fully downloaded files.

**Comment by levlam** [comment]
Support in tdweb for the non-zero `offset` and `limit` parameters in the method `readFilePart` was added in tdweb 1.4.1.

**Comment by Niek** [comment]
@levlam is this already in the tdweb build on https://www.npmjs.com/package/tdweb? Because that supposed to be 1.4.3 but the code still contains: 
```markdown
* 5. The method <code>readFilePart</code> supports only <code>offset == count == 0</code>.<br>
```
This was removed in this tdlib commit a month ago: https://github.com/tdlib/td/commit/8ae3ac91a4b7c4a23746fd32c92e8c1baab23a06#diff-745180b5a943148d8e4f7d5f3fe7067c

**Comment by levlam** [comment]
@Niek It is in NPM since tdweb 1.4.1. In the mentioned commit only the documentation was updated.

**Comment by Niek** [comment]
Is there any sample on how to use ``readFilePart`` in tdweb? I tried calling the function in two ways:

``readFilePart({path: update.file.local.path, offset: update.file.local.download_offset, size: update.file.local.downloaded_size});`` always returns: "Error: File is not loaded at FileManager._callee8$".

``readFilePart({file_id: update.file.id,
                            offset: update.file.local.download_offset,
                            count: update.file.local.downloaded_size});`` (which is more in line with [the docs](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1read_file_part.html)) throws "count" and "filePart" errors.

**Comment by levlam** [comment]
@Niek Have you already downloaded the file using downloadFile? Could you show the whole file object?
```
count Number of bytes to read. An error will be returned if there are not enough bytes available in the file from the specified position.
```

**Comment by Niek** [comment]
@levlam No, the file is being downloaded and not completed yet. I assumed the readFilePart call would especially be useful for pushing chunks of partially-downloaded files (e.g. to enable streaming)?

**Comment by levlam** [comment]
@Niek Yes, it is. Could you show the `file` object, the `readFilePart` request and its response. All of them can be found in the tdweb info log.

**Comment by Niek** [comment]
Here's the ``update.file`` object:
```javascript
{
    @type: "file",
    expected_size: 1319013670,
    id: 7,
    local: {
        @type: "localFile",
        can_be_deleted: true,
        can_be_downloaded: true,
        download_offset: 0,
        downloaded_prefix_size: 1048576,
        downloaded_size: 1048576,
        is_downloading_active: true,
        is_downloading_completed: false,
        path: "/tdlib/inboundfs/temp/262"
    }
    remote: {
        @type: "remoteFile",
        id: "BQADAgADAwMAAuNfyUsOWwK4Mo67uhYE",
        is_uploading_active: false,
        is_uploading_completed: true,
        uploaded_size: 1319013670
    }
    size: 1319013670
}
```I'm not sure how to see the readFilePart request, I don't get a response either because it throws the error.

**Comment by Niek** [comment]
Yes, that's exactly what I'm doing now. It throws 2 errors in tdweb.js:2117:
```javascript
{
    @extra: {
        query_id: 7
    },
    @type: "count",
    count: 1114112
}
```
and
```javascript
{
    @extra: {
        query_id: 8
    },
    @type: "filePart",
    data: Blob {
        size: 1114112,
        type: ""
    },
    transaction_id: -2
}
```
It's from this code:
```javascript
        (_console5 = console).error.apply(_console5, arguments);
```

**Comment by arseny30** [comment]
Those errors are fine. It is just a debug with a wrong verbosity level.

Are you sure there is no answer to this query? It should be in the log shortly after the error. The log entry starts with "receive ".

**Comment by Niek** [comment]
You are right - it's working fine with the changed signature. I didn't look further because of the errors being dumped. Thanks for the help!
