### ISSUE TITLE
Error Could not load file or assembly 'Telegram.Td.dll' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by masjaya19** [tdlib/td#551]
Hello Guys,

I have a problem when my project ASP.net Web API publish on IIS when I browse the website, I have an error: **Could not load file or assembly 'Telegram.Td.dll' or one of its dependencies. The specified module could not be found.**

but in local use IIS express via visual studio 2017, the website and API is running well.
anyone can help me. 

<img width="899" alt="error tele" src="https://user-images.githubusercontent.com/12791065/57512528-18063900-7336-11e9-971f-f8684e17c8a0.png">

noted: I used .net Framework 4.5

Thanks
Mas Jaya Sutarno

**Comment by levlam** [comment]
@masjaya19 See https://github.com/tdlib/td/issues/228.

**Comment by Quasarsbq** [comment]
I have the exact same problem!

**Comment by levlam** [comment]
@Quasarsbq So whether answers from https://stackoverflow.com/questions/344608/unmanaged-dlls-fail-to-load-on-asp-net-server helps to solve your problem?

**Comment by Quasarsbq** [comment]
> @Quasarsbq So whether answers from https://stackoverflow.com/questions/344608/unmanaged-dlls-fail-to-load-on-asp-net-server helps to solve your problem?

Couldn't find any specific solution  on the stack! so... Nope!

**Comment by levlam** [comment]
@Quasarsbq The answers on stackoverflow says that you need to put all DLLs into a directory available through PATH environment and give some ways to achieve that. Have you tried them?

**Comment by Quasarsbq** [comment]
@levlam yes and the project runs without any problem on localhost.
But seems like running on hosting providers it's another story!
