### ISSUE TITLE
How to get permanent link of a supergroup

### ISSUE THREAD

**Issue by Gimmi7** [tdlib/td#552]
@levlam 
Is there any api in tdlib to get the permanent link of a supergroup.
if not , will this capability  be add in future.
Thanks a lot!

**Comment by levlam** [comment]
Public supergroups can be accessed via link `https://t.me/<supergroup username>`. If you are an admininistarator of a private supergroup, you can generate an invite link to it via method `generateChatInviteLink`. There is no other ways to give a link to a supergroup.

**Comment by Gimmi7** [comment]
Thank you for your reply @levlam . I may need to describe in detail the problems I have encountered.
Suppose I hava joined a public supergroup, then i want to share this supergroup to others, but the only information  i can get is chatId.
* only group owner can get inviteLink of a public supergroup by getSupergroupFullInfo(int );
* SupergroupFullInfo  not contains the "username" property of supergroup.
* I wnat to use `https://t.me/<supergroup username>` , but how can i get the supergroup username.

**Comment by zevlg** [comment]
Chat itself has “username” property

**Comment by chairus** [comment]
I believe if you request for the group chat ([getChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat.html)) the returned object would contain a supergroup_id ([chatTypeSupergroup](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_type_supergroup.html)), you can then use that to get the supergroup using the method ([getSupergroup](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_supergroup.html)). The returned object of that method will contain the username of the group.

**Comment by levlam** [comment]
@Gimmi7 As @chairus correctly described, `username` is a part of the `supergroup` object, and not of the `supergroupFullInfo`,

**Comment by Gimmi7** [comment]
Thanks very much @chairus @levlam !
