### ISSUE TITLE
inlineKeyboardButtonTypeCallback works only if data length is a multiple of 4

### ISSUE THREAD

**Issue by Bannerets** [tdlib/td#553]
`inlineKeyboardButtonTypeCallback` works correctly only if its `data` length is a multiple of 4. For example, `abcd`, `12345678` work, but `ab`, `123456` don't. I see the `Failed to parse [request:{ ... }] [Error : 0 : Wrong string length]` error.

In the Bot API I can use any length.

Query example:

```js
{
'@type': 'sendMessage',
chat_id: 0000000,
reply_markup: {
  '@type': 'replyMarkupInlineKeyboard',
  rows: [
    [
      {
        '@type': 'inlineKeyboardButton',
        text: 'sometext',
        type: {
          '@type': 'inlineKeyboardButtonTypeCallback',
          data: 'abcde'
        }
      }
    ]
  ]
},
input_message_content: {
  '@type': 'inputMessageText',
  text: {
    '@type': 'formattedText',
    text: 'hi'
  }
}
}
```

I use TDLib v1.4.0.

**Comment by levlam** [comment]
Field `data ` has type `bytes`. In JSON API content of all fields of `bytes` type is base64-encoded to be able to store any binary data, so you need to base64-encode the data first.

**Comment by Bannerets** [comment]
Thanks, hadn't known about that.
