### ISSUE TITLE
[Missing] Archived Chats

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#554]
https://telegram.org/blog/archive-and-new-design

**Comment by MattNguyen** [comment]
@levlam any timeline on this?

**Comment by levlam** [comment]
Archive was implemented in the private TDLib version in the August, even before 1.5.0 was publicly released. It will be released publicly in TDLib 1.6.0, but there is no ETA yet. I wouldn't expect it earlier than in November.

**Comment by omkarnathsingh** [comment]
Hope we get it soon :), Excited for this missing feature for long

**Comment by wowkin2** [comment]
@levlam any updates here?

**Comment by levlam** [comment]
@wowkin2 There is no ETA for public release of TDLib 1.6.0, but expect it to be after next Bot API and Telegram X releases.

**Comment by levlam** [comment]
Archive chat list support was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
