### ISSUE TITLE
[Missing] Contacts filter from group/channel member list

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#555]
Categorize group Members as Contacts/Bots/Administrators/Other Members

**Comment by levlam** [comment]
This is an interface feature. All needed chat members search filters (except contacts filter) are available for a very long time.

**Comment by levlam** [comment]
The filters `supergroupMembersFilterContacts` and `chatMembersFilterContacts` was added in TDLib 1.5.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
