### ISSUE TITLE
Building vcpkg.exe ...  MSBUILD : error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by bruev** [tdlib/td#557]
I'm following instructions to install TDLib.
I did
```
git clone https://github.com/tdlib/td.git

cd td

git clone https://github.com/Microsoft/vcpkg.git

cd vcpkg
```
After I run ./bootstrap-vcpkg.bat I get the error:

> Building vcpkg.exe ...
> 
> MSBUILD : error MSB1009: Project file does not exist.
> Switch: C:\Windows\System32\td\vcpkg\toolsrc\dirs.proj
> C:\Windows\System32\td\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed
> Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
> At line:1 char:4
> + & {& 'C:\Windows\System32\td\vcpkg\scripts\bootstrap.ps1' }
> +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

**Comment by levlam** [comment]
You have not enough rights to create files in `C:\Windows\System32\`. You need to move to some other directory.
