### ISSUE TITLE
Windows 10 (python example) 

### ISSUE THREAD

**Issue by rejjin** [tdlib/td#558]
Some wrong with CDLL loading tdjson.dll
This is default python example, I just copy tdjson.dll and other files from build/debug folder to examples/python, and got this error (WinError 182)

![image](https://user-images.githubusercontent.com/692007/57614084-19777180-7581-11e9-8ef8-9b9c72210ffa.png)

cli.exe works fine
Builded with VS 2019. Python 3.7 x64

**Comment by levlam** [comment]
Probably, there is something wrong with the dependencies or with the built library. Could you try to use instructions from https://tdlib.github.io/td/build.html?language=Python to build 64-bit tdjson.dll from scratch. If this doesn't help then you can try to find the reason of the issue as suggested in https://stackoverflow.com/questions/3497301/what-exactly-means-error-invalid-ordinal.

**Comment by levlam** [comment]
@rejjin I hope that you have managed to successfully build TDLib using the build instructions generator.
