### ISSUE TITLE
About the group to which the supergroup member belongs

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#559]
@levlam I use getSupergroupMembers to get the information of the super group, but how do I determine which super group is returned by the chatMembers? After all, he only has these three return value data "@type": "chatMembers", "total_count": 309, "members": Do I need to judge whether the total_count is consistent? But what if I have two identical groups? It is worth mentioning that the value of members is sometimes empty without any data.

**Comment by levlam** [comment]
In TDLib JSON interface requests and responses can be matched via additional `'@extra'` parameter. You specify whatever you want `'@extra'`parameter in the request and receive response with exactly the same `'@extra'` field.

**Comment by AquariusHunters** [comment]
@levlam Do you mean that I can use @extra=my information attached to the json parameter required by the getSupergroupMembers method lock?

**Comment by levlam** [comment]
Yes. In simplest case you can just attach to each query unique number. You can find examles of such usage for your language in https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples.

**Comment by AquariusHunters** [comment]
@levlam Great, thank you for your answer, but I have another doubt, that is, I just mentioned, why is the array of return values of getSupergroupMembers empty?

**Comment by levlam** [comment]
If the array is empty then noone is found.

**Comment by AquariusHunters** [comment]
Under what circumstances will anyone be found? There are even two or three consecutive requests without any data, but the total number of groups returned is enough for people. @levlam

**Comment by levlam** [comment]
@AquariusHunters `getSupergroupMembers` just returns members that you have requested via request parameters. If there are users, which need to be returned, then they will be returned.

**Comment by AquariusHunters** [comment]
Can I name my own avatar when I save it without using file_xxx? @levlam

**Comment by levlam** [comment]
Name of downloaded files are chosen automatically by TDLib to prevent security issues. Between, downloaded profile photos will be never named `file_xxx`, unless you explicitly enabled `ignore_file_names` option in `setTdlibParameters`.

**Comment by AquariusHunters** [comment]
I checked my code, indeed, as you said, I set ignore_file_names to true, it seems that this is really a stupid question, Thank you for your answer.

**Comment by AquariusHunters** [comment]
@levlam When I log in, how do I choose to generate the generated code and send it to the email using SMS instead of other methods?

**Comment by levlam** [comment]
A way the code is sent is chosen by the server. User can ask to resend the code, but it can't choose a way the code will be delivered.

**Comment by AquariusHunters** [comment]
@levlam How do I get the join and leave of a group member?I did not see a description of member joins and leaves in the various methods of Update.

**Comment by levlam** [comment]
Because you can't get that. Sometimes you only receive informational messages `messageChatAddMembers`, `messageChatJoinByLink` or `messageChatDeleteMember`. Whether a message is generated is decided by the server.

**Comment by AquariusHunters** [comment]
@levlam Hello, may have to bother you again, but I still have a problem. When I use TDLib to get the group member information, the total number returned is 19683, but when I get the member ID for display, I provided the identity to distinguish, but the same number of members returned by the same identity is different. I have a lot of different member number information, but most of them show 10002, and some are 9863, but I log in from the official client and display it is 19683.

**Comment by levlam** [comment]
@AquariusHunters Does https://github.com/tdlib/td/issues/484#issuecomment-461034312 answer your question?

Also, in big uspergroups there may be deleted users, which are not returned by `getSupergroupMembers`, but for some short time are counted in the total chat member count.

**Comment by AquariusHunters** [comment]
@levlam How long is this time? One month or one week? But I think the difference in this data is a bit big, although I didn't find a group on the official client to see all the members, and didn't know if the official display is the same, but if I don't look at the data, I also Can't remember whether these people are more than 10,000 or more than 20,000

**Comment by levlam** [comment]
@AquariusHunters None of the clients can show more than 10000 members, but all clients should show correct chat member count.

The time is a few weeks, so it is expected than slightly less than 10000 members can be received.

**Comment by AquariusHunters** [comment]
@levlam Is that the arrangement of the 10,000 members in terms of activity? In that case, the active number of the group should not be higher than this number.

**Comment by levlam** [comment]
@AquariusHunters `supergroupMembersFilterRecent` (default) returns members in the order of they last activity.

**Comment by AquariusHunters** [comment]
@levlam I am bothering you again. I want to know how many chat lists I can get. I found that there are 119 chats updated by update, but I only got 100 chats using getchats.

**Comment by levlam** [comment]
@AquariusHunters https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats

**Comment by AquariusHunters** [comment]
@levlam I don't quite understand the usage of this, if I use the new offset_order and offset_chat_id to get my chat list again, but how do I know my chat list has been obtained? Do I have a way to get the number of exact chat groups I have, and then get the corresponding group information from the server? And I found that there is a lot of message returning about the message in updata. This makes me a bit unclear where I should do some processing and let him display it correctly in my group chat interface.

**Comment by levlam** [comment]
@AquariusHunters If you receive some chats, is the list of chats fully obtained? If you receive 0 chats is there any reason to repeat the same request to receive again 0 chats?

There is no such thing as "number of exact chat groups", because list of chats is constantly changed. Some chats are added to the list and some are removed from the list. A program that tries to use any such value is incorrect.

In chat list all chats with order > 0 needs to be displayed. You need to process updates to always have actual chat state.

**Comment by AquariusHunters** [comment]
What do you mean by the update information I need to send from the server to record the chat list I have? Then go to these lists to request to display some chat information that needs to be displayed to the user for viewing? @levlam

**Comment by levlam** [comment]
@AquariusHunters [Handling updates](https://core.telegram.org/tdlib/getting-started#handling-updates).

**Comment by AquariusHunters** [comment]
@levlam Thank you for your help, it seems that I need to understand the documentation manual again.
