### ISSUE TITLE
a JSON interface for languages

### ISSUE THREAD

**Issue by StagsGit** [tdlib/td#560]
Hi,
is there a complete example of C++?
``https://github.com/tdlib/td/blob/master/example/cpp/td_example.cpp``
this is good for start, but is there a better example for C++/CLI ?
thanks

**Comment by levlam** [comment]
You can look at our [test client](https://github.com/tdlib/td/blob/master/td/telegram/cli.cpp) and [C++ examples](https://github.com/tdlib/td/tree/master/example#cxx).

**Comment by StagsGit** [comment]
thanks for your response,
but is there a complete example of LUA tdjson like [this](https://github.com/tdlib/td/tree/master/example/python/tdjson_example.py)?
or a json for [tdlib-json-cli](https://github.com/oott123/tdlib-json-cli)?

**Comment by levlam** [comment]
What exactly do you mean by "a complete example"? I doubt that there are fully-functional Telegram clients written in Lua. For examples of TDLib usage from Lua see https://github.com/tdlib/td/tree/master/example#lua.

**Comment by StagsGit** [comment]
This title is better!
I just want a lua JSON interface for tdlib
there isn't any json interface that written in lua(that just written in c++)

**Comment by levlam** [comment]
@StagsGit https://github.com/giuseppeM99/tdlua uses TDLib's JSON interface. If you want pure lua wrapper, you can easily write it yourself.

**Comment by StagsGit** [comment]
@levlam but when I try to require the tg_cli or libtdjson.so in lua I receive an error,
there isn't any simple json interface to show how can I write a pure lua wrapper?

**Comment by levlam** [comment]
@StagsGit See http://luajit.org/ext_ffi.html.
