### ISSUE TITLE
can't find method for sign up

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#561]
Hi!
I can't find method for sing up new user!

If  phone number did not register in telegram before,  i getting following  error after SMS send 
PHONE_NUMBER UNOCCUPIED

Help me please with it

**Comment by levlam** [comment]
There is no separate method for sign up, you need to just call `checkAuthenticationCode` whenever TDLib asks for code. See https://core.telegram.org/tdlib/getting-started#user-authorization and [examples](https://github.com/tdlib/td/blob/master/example/README.md) for more details.

**Comment by merlinkory** [comment]
yes and after checkAuthenticationCode  i getting PHONE_NUMBER UNOCCUPIED 
But if number was registred in telegrabe  before - all ok. 

This problem with  new (not registred in telegram before)  phones only

**Comment by levlam** [comment]
Your are likely to pass empty first_name and last_name. See documentation of the [checkAuthenticationCode](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1check_authentication_code.html) method, especially its `first_name` parameter.

**Comment by levlam** [comment]
Since TDLib 1.5.0 the new method `registerUser` needs to be used for user registration in the state `authorizationStateWaitRegistration`.
