### ISSUE TITLE
How to find private chat

### ISSUE THREAD

**Issue by jonua** [tdlib/td#564]
I have a private chat (BasicGroupFullInfo) where I am is member. I want to get all members from that chat. But how I can find this chat? The only method I see - using getChats() method, but in this case I must I have to go through all the chats and compare their titles with the desired. It is the only way to find my private chat by its title?

**Comment by levlam** [comment]
You can use `searchChatsOnServer` method to find a chat by its title.

**Comment by jonua** [comment]
@levlam but `searchChatsOnServer` works only with "[...of already known chats...](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1search_chats_on_server.html#af3db1834d193fd1c5cd7535bcda54e17)" chats, i.e. that is I still have to call `getChats` method before calling the `searchChatsOnServer`, right?

**Comment by levlam** [comment]
It searches among chats from the user's chat list on the server, so the chat doesn't need to be available locally to be found.

**Comment by jonua** [comment]
Hm.. So why if I execute `SearchChatsOnServer(chatName, limit)` - I receive zero results? But if I execute `getChats(Long.MAX_VALUE, 0, 9999)` and after some seconds I execute the `SearchChatsOnServer(chatName, limit)` request, I'm got results with search chat id? What I'm doing wrong in `SearchChatsOnServer` call?

**Comment by levlam** [comment]
@jonua 
Could you also confirm that you don't use message database (can be enabled in setTdlibParameters)?

**Comment by jonua** [comment]
@levlam my TdlibParameters is:
```
TdApi.TdlibParameters parameters = new TdApi.TdlibParameters();
parameters.apiId = API_ID;
parameters.apiHash = API_HASH;
parameters.databaseDirectory = DATABASE_DIRECTORY;
parameters.useMessageDatabase = false;
parameters.useSecretChats = false;
parameters.systemLanguageCode = "en_GB";
parameters.deviceModel = "no-device";
parameters.systemVersion = "0.9";
parameters.applicationVersion = "0.9";
```

**Comment by levlam** [comment]
Then you can fix this behavior of `searchChatsOnServer` by removing lines
```
  while (!dialog_dates.empty() && dialog_dates.back().get_order() == DEFAULT_ORDER) {
    dialog_dates.pop_back();
  }
```
from `td/telegram/MessagesManager.cpp` file and rebuilding TDLib.
If message database is used, only the very first `SearchChatsOnServer` request is affected.

**Comment by chairus** [comment]
On a similar note, if I disable the `TdApi.TdlibParameters#useMessageDatabase` and I make a `TdApi.GetChat(long)` request, does that make a search of all existing chats, i.e. not just the chats known to the user or in the user's chat list?

Thanks

**Comment by levlam** [comment]
@chairus `GetChat` is always a local request, because there is no way to receive a chat by its ID from the server. If message database is disabled it has no chance to return a chat, not previously sent to the client in UpdateNewChat.

`CreateSupergroupChat` is needed only to get by `supergroupId` corresponding `Chat` object.

**Comment by chairus** [comment]
> GetChat is always a local request, because there is no way to receive a chat by its ID from the server. If message database is disabled it has no chance to return a chat, not previously sent to the client in UpdateNewChat.

Thanks for clarifying that.

> `CreateSupergroupChat` is needed only to get by `supergroupId` corresponding `Chat` object.

Does that mean `CreateSuperGroupChat` is and always is a local request?

**Comment by levlam** [comment]
@chairus `CreateSuperGroupChat` is a local request only if parameter `force` == true. Otherwise it is likely to be a network request, becuase there are a lot of data in the `Chat` object, which is available only on the server.

**Comment by chairus** [comment]
@levlam Sorry for asking too much question, I only have one more. Does `CreateSupergroupChat` work if I use it the same way as I have described on my first comment, (without making any other requests such as TdApi.GetChats or TdApi.SearchPublicChat, etc. before calling `CreateSupergroupChat`) except that I know the `supergroupId` this time? In other words, does it return a `Chat` object?

**Comment by levlam** [comment]
@chairus It will work if chat info database is used and the supergroup was previously received by the client.

**Comment by skygate2012** [comment]
I'm not sure if this is a new addition or not, but we can specify `offset_chat_id` (and optionally `limit: 1`) for `getChats`, effectively loading a chat by its id.
