### ISSUE TITLE
messageForwardInfo class documentation is wrong

### ISSUE THREAD

**Issue by mymike00** [tdlib/td#567]
the [messageForwardInfo documentation](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_forward_info.html) and all its child pages ([messageForwardOrigin](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_message_forward_origin.html),  [messageForwardOriginChannel](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_forward_origin_channel.html), [messageForwardOriginHiddenUser](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_forward_origin_hidden_user.html), and [messageForwardOriginUser](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message_forward_origin_user.html).) are wrong: it says I should receive something like
```
"forward_info":{
    "origin": {
        "@type":"messageForwardedFromUser",
        "sender_user_id":0
    },
    "date":0,
    "forwarded_from_chat_id":0,
    "forwarded_from_message_id":0,
}
```
while I receive a different organized json
```
"forward_info":{
    "@type":"messageForwardedFromUser",
    "date":0,
    "forwarded_from_chat_id":0,
    "forwarded_from_message_id":0,
    "sender_user_id":0
}
```

**Comment by levlam** [comment]
It isn't wrong. On-site documentation is for the latest public version TDLib 1.4.0 and you are using some older version. See [Change log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.

**Comment by mymike00** [comment]
oh, thank you. I forgot to check for TDLib updates!
