### ISSUE TITLE
How to search for channel name containing special characters

### ISSUE THREAD

**Issue by Steffx115** [tdlib/td#568]
Im trying to get the id of a channel by calling searchPublicChat with the channelname, which contains a '©', and get an error message that the Name is invalid. Also, using the t.me link of the channel doesnt work. I am using csharp with tdlib.native nuget package and tdsharp

**Comment by levlam** [comment]
`searchPublicChat`  searches chat by its username. You probably need `searchPublicChats` method.

**Comment by Steffx115** [comment]
I used the GetChats method and compared the name of the chat to identify the channel i was looking for
