### ISSUE TITLE
Decrease Verbose or remove print logs!

### ISSUE THREAD

**Issue by StagsGit** [tdlib/td#57]
when I run tdlib it print a lot of LOGs and normally it's on 5.
I want it just print FATAL errors or important errors not debugging.
How i decrease verbosity?or something do to don't print anything?
Thanks

**Comment by levlam** [comment]
It depends on what interface you are using. You need to call either [td_log_set_verbosity_level](https://core.telegram.org/tdlib/docs/td__log_8h.html#a4b098540dd3957b60a67600cba3ebd7f) for C/JSON interface or [td::Log::set_verbosity_level](https://core.telegram.org/tdlib/docs/classtd_1_1_log.html#a9dd71044a37db700da89001c96b978c3)
for C++-interface.

**Comment by StagsGit** [comment]
https://github.com/vysheng/tdbot/
this is my source
replace with SET_VERBOSITY_LEVEL is true?

**Comment by levlam** [comment]
tdbot has an option --verbosity/-v to set log verbosity level, but by default logging level is set to 0 there.

**Comment by StagsGit** [comment]
Yes it set to 0 but why it print LOGs?
Significantly this logs is going increase process of server

**Comment by levlam** [comment]
You could also try to specify --logname <log_file_name> to redirect the log to a file.

**Comment by StagsGit** [comment]
Can I do something to it doesn't write anything on log file?
It is going to pressure on I/O and it increased to up than 5

**Comment by StagsGit** [comment]
I want anything don't write on default db.sqlite on .telegram-bot/data/

**Comment by levlam** [comment]
Both TDLib and tdbot provide methods for managing logs verbosity. I don't know why they aren't working for you.

**Comment by StagsGit** [comment]
Every level I set still it writes logs in db.sqlite
I want It dosen't write any Logs in db.sqlite that it dosen't use I/O
I think some functions like LOGGR or LOG_IMPL do this job and write Logs.is true?

**Comment by levlam** [comment]
db.sqlite is an SQLite database file, it contains no logs, just a data needed for normal library work.

**Comment by StagsGit** [comment]
this means that there is no way to stop writing a lot data?after a few day it will be bigger than 1Gb.
