### ISSUE TITLE
Does the telegram api support long polling?

### ISSUE THREAD

**Issue by Steffx115** [tdlib/td#570]
When developing with tdlib/tdsharp i started wondering if it is possible to retrieve chat messages (for a specific chat) via long polling, is this the case? if yes, which method do i need to use?

**Comment by Steffx115** [comment]
For now i just want to display messages, and if a new message gets written in the chat/channel i want to append that message to the existing chat display

**Comment by levlam** [comment]
You need to handle `updateNewMessage` for that. TDLib sends everything you need through updates.
