### ISSUE TITLE
tdjsonlib document

### ISSUE THREAD

**Issue by dx0eu** [tdlib/td#572]
Hello, I'm looking for tdjsonlib documentation. I'm not sure what json data should be passed to tdjsonlib.

I saw a lot of simple cases, like this one

```json
{
  "@type": "setTdlibParameters",
  "parameters": {
    "api_hash": "qqwertyu123456yu",
    "api_id": 1234567,
    "application_version": "0.4",
    "database_directory": "/home/nemo/.local/share/harbour-depecher",
    "device_model": "Sailfish OS 2.2.0.29 (Mouhijoki)",
    "enable_storage_optimizer": false,
    "files_directory": "/tmp/",
    "system_language_code": "C",
    "system_version": "2.2.0.29",
    "use_chat_info_database": false,
    "use_file_database": false,
    "use_message_database": false,
    "use_secret_chats": false
  }
}
```

Where should I find this document, I have already looked but not found.

**Comment by levlam** [comment]
[Readme](https://github.com/tdlib/td#using-json) has a lot of useful links to documentation of all available methods. You can also read [Getting Started](https://core.telegram.org/tdlib/getting-started) for a general introduction.
