### ISSUE TITLE
GetChats return incorrect chats

### ISSUE THREAD

**Issue by alekseykoshelev** [tdlib/td#573]
I'm leaving group and don't have chat with this group on my telegram client but this group come with UpdateNewChat. Then i deleted chat with LeaveChat but it comes again.

**Comment by levlam** [comment]
The group still exists, so you definitely can receive `UpdateNewChat` with the chat, But the chat shouldn't be returned in `GetChats` and `Chat.order` must be equal to 0, which means that the chat is not in the chat list.

**Comment by alekseykoshelev** [comment]
Thanks.
