### ISSUE TITLE
TelegramX close again and again

### ISSUE THREAD

**Issue by priyankg3** [tdlib/td#576]
SetTdlibParameters: #400: File "/data/data/org.thunderdog.challegram/files/tdlib98/td.binlog" can't be opened/created for reading and writing

**Comment by RememberTheAir** [comment]
Report the bug in [@tgandroidtests](https://t.me/tgandroidtests)

**Comment by levlam** [comment]
@priyankg3 There is likely a problem with the phone's file system. The error means that TDLib can't open/create a file in the internal apps directory, which should be always possible on non-rooted phone, given there is enough space available on the SSD. You can try to clear application data or reinstall the app, but there is no guarantee that it will help.

**Comment by priyankg3** [comment]
So if i release some space from ssd, problem will be solved ?

**Comment by levlam** [comment]
@priyankg3 This is the most likely cause of the crash, so it can help. But there can be others, including hardware of file system failures.

**Comment by priyankg3** [comment]
Okay let me try, will get back to you regarding this later
