### ISSUE TITLE
Closing polls

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#577]
In official client it is possible to "close" the poll.  Is it possible to do the same with TDLib 1.4.0 ?

Thanks

**Comment by levlam** [comment]
See https://github.com/tdlib/td/blame/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/CHANGELOG.md#L26.

**Comment by zevlg** [comment]
> See https://github.com/tdlib/td/blame/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/CHANGELOG.md#L26.

ah, missed this, thanks
