### ISSUE TITLE
TdApi.getMe

### ISSUE THREAD

**Issue by isopen** [tdlib/td#579]
The answer comes in `TdApi.UpdateUser`. Next, find the appropriate type of user.
`UserType -> [userTypeDeleted,  userTypeBot, userTypeRegular, userTypeUnknown]`.
Super! `userTypeRegular` is what you need, but it was expected that inside will be `userTypeMe`.

Is there any alternative mechanism? (to make it work)

**Comment by isopen** [comment]
@levlam Looks like it works here `TdApi.User`

**Comment by levlam** [comment]
Result of the `TdApi.GetMe` request has type `TdApi.User` and can be received in a callback passed as second argument to `Client.Send`. There is no need to process updates to get the response.

**Comment by isopen** [comment]
For example, after successful authorization, `my_id` option is returned to `TdApi.UpdateOption.`
You can then call `TdApi.GetUser` with current user id from the `my_id` option.
Go to the `TdApi.UpdateUser` handler. Perhaps you will not find the appropriate type for distribution in the visual part of the application. This point can be implemented on the client before calling `TdApi.GetUser` (eg: flag, hybrid callback).
