### ISSUE TITLE
Telegram x keeps closing

### ISSUE THREAD

**Issue by javadalizadeh76** [tdlib/td#580]
[ 0][t 4][1559383779.376192093][MessagesManager.cpp:10132][#1][!Td][&last_new_message_id.get() > d->last_new_message_id.get()] server message 5719113 server message 5719113 on_get_channel_dialog 40

**Comment by levlam** [comment]
This is fixed in the latest Telegram X beta, which will be sent to production soon. You can join beta (https://play.google.com/apps/testing/org.thunderdog.challegram) to get this version faster.

**Comment by levlam** [comment]
This was fixed in TDLib 1.5.0.

**Comment by Asedshadeli** [comment]
My telegrams is pond whay please help me
