### ISSUE TITLE
Remove password

### ISSUE THREAD

**Issue by pishgaman-org** [tdlib/td#584]
hi

before tdlib library I was using tlsharp. when an account was 2-step verification enabled and I didn't remember the password, I was using this code to remove its password :
```
        public async Task<bool> RemovePass()
        {
            TLRequestResetAuthorizations request = new TLRequestResetAuthorizations();
            bool auth = await SendRequestAsync<bool>(request);

            TLRequestRegisterDevice request2 = new TLRequestRegisterDevice() { token = "test", token_type = 3};
            bool auth2 = await SendRequestAsync<bool>(request2);

            return auth2;
        }
```
but I can't find reset authorization function in tdlib. is it renamed or removed at all?

**Comment by levlam** [comment]
@pishgaman-org This function does a completely random thing. First request works only when you is already logged in for more than 24 hours and terminates all other sessions. Second request subscribes application for Microsoft Push Notification Service push notifications with a fake token, which have no sense. Both requests has nothing to do with the user's password.

The only way to remove a password when it is forgotten is to recover it via recovery email address using `recoverPassword`. If recovery email address wasn't added, then you will be able to use `deleteAccount` when logging in.

**Comment by pishgaman-org** [comment]
I didn't pay attention to those codes. just was using that function.
yes I don't have any important information in accounts. DeleteAccount is the solution.
Thanks a lot.
