### ISSUE TITLE
Usage of apiId and apiHash 

### ISSUE THREAD

**Issue by egmontr** [tdlib/td#585]
[Question] I register for apiId and apiHash and I use them to develop an App.
Do I deploy the App to the Google Play Store with that apiId and apiHash for all users? Or each user have to get his own apiId and apiHash?

Thank you.

**Comment by levlam** [comment]
For every user of your app apiId and apiHash will be the same.

**Comment by FrayxRulez** [comment]
If you distribute a binary, then it makes sense to use the same id/hash pair, if you distribute source code then you may want to let users to insert their.

**Comment by isopen** [comment]
https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables

> WARNING: Do not store any secrets (such as private API keys) in your React app!
> Environment variables are embedded into the build, meaning anyone can view them by inspecting your app's files.

This warning can be applied here.
