### ISSUE TITLE
is there any way to develop app with tdlib mockup / local server?

### ISSUE THREAD

**Issue by gen4sp** [tdlib/td#586]
I want to make an app and don't want to bother the production server. 
is there any way to develop without connection to the production server? 

Maybe library mockup or local server? Will be glad to any suggestion.

Thank you.

**Comment by levlam** [comment]
You can connect to test DC for testing purposes, specifying `use_test_dc = true` in `setTdlibParameters` request. Test DC has nothing in common with production DC, so you will even need to again register your account there.

**Comment by gen4sp** [comment]
Great, thank you!
And there is any way to connect an oficial client to this dc?
