### ISSUE TITLE
Deleting chat from chat list without discarding history

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#587]
Here is `deleteChatHistory` which can be used to remove chat from chat list, however it discards history as well.  Is it possible to remove chat from chat list (i.e. make its "order" be 0) without discarding all the history?

I can just `leaveChat` and then filter chats where me is member of, but anyway this keeps non-0 order of the chat.

Thanks

**Comment by levlam** [comment]
You can't keep messages in basic group chat and remove it from chat list, because chat list is exactly designed to show chats which contains messages.

Probably, you want to ьфлу the chat [archived](https://telegram.org/blog/archive-and-new-design), but this isn't supported in TDLib 1.4.0.

**Comment by zevlg** [comment]
thanks for the clarification
