### ISSUE TITLE
getChatMember() throws INVALID_USER 

### ISSUE THREAD

**Issue by MattNguyen** [tdlib/td#589]
I'm attempting to use a bot to check whether users are in a group. However, when I call `getChatMember`, the API returns `api error: Bad Request: USER_ID_INVALID`. I have verified that the user is in fact still active and in the group.

**Comment by levlam** [comment]
Currently, the bot needs administrator rights in the supergroup to be able to call `getChatMember` for users, which wasn't received recently by the bot.

**Comment by MattNguyen** [comment]
Thanks! That would explain it!
