### ISSUE TITLE
Feature request: tdclient as shared library

### ISSUE THREAD

**Issue by blacksailer** [tdlib/td#59]
Hello!
Can anyone help, how to build tdclient as shared library?  Can anyone post correct CMake example?

**Comment by arseny30** [comment]
It is not supported. The suggested way is to use static library and [to build TdLib as a part of your project](https://github.com/tdlib/td#using-in-cmake-c-projects).

There are much more problems than benefits when using Td as a shared library.
While TdJson has simple plain C interface which is easy to export as shared library API, Td itself has a complicated C++ interface.

For example, you won't be able to use a built shared library with a different c++ standard library. 
On windows, it will be problematic to destroy our objects with the right allocator.
There are also may be problems if you will try to use compiler different from the one used to build the library.

Different versions of TdLib are not ABI compatible. They are generally not even API compatible.
TdLib API contains all these [classes](https://core.telegram.org/tdlib/docs/classes.html), which may be (and will be) changed in future. It also complicates correct usage of a shared library.

**Comment by korangu** [comment]
how to build tdjson static? 
can it be portable like build on one system and copy executable to another system and run there?

**Comment by blacksailer** [comment]
@korangu You can't create portable tdjson static, because static lib requires other static tdlibs and stdc++ libs. 
You can create tdjson shared with ```-static-libgcc -static-libstdc++ ``` flags. It will include std library and library will bee portable.

**Comment by korangu** [comment]
ok thanks  let me try give an update soon
