### ISSUE TITLE
Supergroup creation date

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#590]
Is there method to get supergroup's creation date?

I can get creator's join date, however this date resets if creator leaves and then rejoins the group

Thanks

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1supergroup.html#a0d05d30cefafcef62fd96cbcbaf4e3d1

**Comment by zevlg** [comment]
I found `messageChatUpgradeTo`, potentially if I get this type of message from original basic group it could be possible to recover the creation date.  Is there way to get original basic group to examine its last message?

**Comment by levlam** [comment]
A supergroup can be created directly and not converted from a basic group.

If you want to get first chat message, see https://github.com/tdlib/td/issues/195#issuecomment-380836359.

**Comment by zevlg** [comment]
nice! date of the first message also suits
