### ISSUE TITLE
[Missing] Exceptions for group chats/members

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#597]
Blog: https://telegram.org/blog/privacy-discussions-web-bots

**Comment by levlam** [comment]
Support for including or excluding all group members in a privacy setting rule was added in TDLib 1.6.0 via classes `userPrivacySettingRuleAllowChatMembers` and `userPrivacySettingRuleRestrictChatMembers`. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
