### ISSUE TITLE
Multi-core assembly in debian stretch

### ISSUE THREAD

**Issue by isopen** [tdlib/td#6]
**You should not experiment with fewer cores.**

Debian stretch. I have 8 cores in my car.
 
I did the following:
zlib from the source code https://packages.debian.org/source/stretch/zlib
apt install libssl-dev libreadline-dev ccache
other packages according to the instructions

**first step:**
mkdir build
cd build
cmake ..
cmake --build . (at this step I was dejected)
ctrl+c

**second step**
make -j 6
the virtual machine hangs. restarting the virtual machine.

**third step**
make -j 4
cautiously somewhere in the middle the system ceases to hang and everything is going to.
just in case cmake --build .

Do not forget about the **ccache** package for subsequent assemblies useful.
Then you can cmake --build .

Are we going to collect in several cores or will we wait a long time in one core according to the instructions?

**Comment by arseny30** [comment]
It probably hangs because all RAM is used. You may try `clang` instead of `g++`, it uses much less memory than `g++` and compiles TDLib quicker.

Also  `cmake -GNinja ..` will use `ninja` instead of `make`. `ninja` will try to determine needed number concurrent jobs by itself, so simple `cmake --build .` will be enough to run a build as fast as possible.

**Comment by isopen** [comment]
Ok :)

apt install ninja-build
cmake -GNinja ..
cmake --build .
![image](https://user-images.githubusercontent.com/7373292/34651766-5f5fcab4-f407-11e7-89ee-ece6615a51bb.png)
Accordingly, the virtual machine hung.
Something went wrong...+ eats 10gb of ozu.
The effect is similar to make -j 6

**Comment by arseny30** [comment]
Ok, ninja won't help here. But it still looks that you just have not enough RAM for concurrent build. Am I right?

**Comment by isopen** [comment]
I do not have much RAM, but there is 16gb ozu.)
Library at assembly is eating nenuchutku. And all resources in general.
I may be in something I do not understand, but it's a kapets.
In 4 cores going 20+ minutes. eats whole RAM.

The moment that in our market most have only 8GB of RAM and 4 cores :))

**Comment by levlam** [comment]
4 GB of RAM should be enough for GCC (at least for Release builds). Clang usually needs only 1,5-2 GB of RAM for each file. You need to adjust job count to not use more RAM than available in the system. It is strange that modern C++ compilers are so slow and need so much RAM to compile simple source files, but it is not a library issue.

**Comment by isopen** [comment]
@levlam thank

**Comment by isopen** [comment]
Nevertheless, if you do not mind, we will continue.

- At this point, the assembly eats about 5GB

![image](https://user-images.githubusercontent.com/7373292/34676338-11c70f48-f4bf-11e7-8fe3-9b5d6589a639.png)
- Further all ok (1,5-3 GB)

- At this place begins to eat the whole RAM

![image](https://user-images.githubusercontent.com/7373292/34676277-e2dd94b8-f4be-11e7-99f2-300afffcdffa.png)
![image](https://user-images.githubusercontent.com/7373292/34676395-4060b7b4-f4bf-11e7-8f87-89c16ba5adab.png)
Building CXX object CMakeFiles/tdcore.dir/td/telegram/Payments.cpp.o
Accordingly, the operating system hangs for a while
- Further all ok (1,5-3 GB)
