### ISSUE TITLE
Information about the compiler needed

### ISSUE THREAD

**Issue by isopen** [tdlib/td#60]
What compiler(version) and which os(version) for building tdlib you used for Telegram X?

**Comment by levlam** [comment]
TDLib based Telegram X is an Android application. Therefore [NDK](https://developer.android.com/ndk/index.html) is used to build native libraries for Android. Compiler is a part of the NDK and changes with every NDK release, host OS doesn't matter.

**Comment by isopen** [comment]
What version of GCC, Clang will you recommend for the best assemblies in Debian 9.3?

**Comment by levlam** [comment]
Latest.

**Comment by isopen** [comment]
Thanks.
