### ISSUE TITLE
[Bug] tdWeb logout issue

### ISSUE THREAD

**Issue by kesha-antonov** [tdlib/td#603]
Hey!

I'm using tdweb and I have a problem when I try to logout
More details here: https://github.com/evgeny-nadymov/telegram-react/issues/31

Please help.

**Comment by isopen** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1authorization_state_closed.html

**Comment by levlam** [comment]
The bug was server-side and is already fixed. Thanks for the report!

**Comment by kesha-antonov** [comment]
@levlam Nice!
