### ISSUE TITLE
Geochats

### ISSUE THREAD

**Issue by emadghav** [tdlib/td#605]
how working with Geochats?

**Comment by levlam** [comment]
Geoсhats is a supergroup with attached location. You can use them as an ordinary supergroups in TDLib 1.4.0. Special methods for creating and locating geochats will be available in the next TDLib version.

**Comment by yegor-pelykh** [comment]
Ok, now the version 1.5.0 has been released. But there are still no special methods for working with geochats? I recently saw them in the documentation, but now they are even removed from there. Could you give an explanation on this subject, please?

**Comment by levlam** [comment]
Supergroups with attached location have never been documented and they aren't supported in the current public TDLib version 1.5.0. They will be publicly availalble in TDLib 1.6.0.

**Comment by yegor-pelykh** [comment]
@levlam sorry, but:
https://web.archive.org/web/20190810150228/https://core.telegram.org/methods
😉

There are some methods here, named as _geochats.*_ .
But I tried them. They don't work, at least for me...

Maybe you could offer some alternative, for testing purposes?
Please.

**Comment by RememberTheAir** [comment]
@yegor-pelykh you are referring to a webarchive snapshot of the API documentation page which, at the time, was 5 years old. "Geochats" there are not the same geochats you can find on Telegram now. They were an old geochats implementation dating back to 2013/2014 that never made it to production and has never been used by Telegram.

TDlib doesn't support geolocation of cuspergroups yet, as it has already being said it will implemented in tdlib with the upcoming release

**Comment by yegor-pelykh** [comment]
As for the obsolete methods, it's clear now. Thank you for the clarification.

But please, could you provide at least some unstable test versions of such methods, which will be released in 1.6? Maybe there are some methods that we may try right now?
And could you clarify please, on what date the release 1.6 is planned (at least approximately)?
Thank you!

**Comment by levlam** [comment]
@yegor-pelykh It is not possible to implement this feature without implementing all other missed features. So, you can't create and locate these chats using TDLib yet.

TDLib 1.6.0 will be released after a corresponding Bot API and Telegram X release. There is no ETA yet, but it definitely wouldn't be in the September.

**Comment by yegor-pelykh** [comment]
Ok, thank you very much for the info!

**Comment by yegor-pelykh** [comment]
Sorry, is the method "contacts.getLocated" working now? I cannot use it for some reason. My tdlib says: "Failed to parse ... [Error : 0 : Unknown class]"

**Comment by levlam** [comment]
It is a Telegram API method, and not a TDLib API method.

**Comment by yegor-pelykh** [comment]
How to find the appropriate TDLib method for this?

**Comment by levlam** [comment]
It doesn't exist in TDLib 1.5.0.

**Comment by yegor-pelykh** [comment]
Will it be exist in TDLib 1.6.0?

And can I use the Telegram API method directly?
Maybe with help of TDLib.

**Comment by levlam** [comment]
Yes, there will be a method for that in TDLib 1.6.0.

No, you can't call Telegram API methods using TDLib.

**Comment by levlam** [comment]
Support for location-based supergroups was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
