### ISSUE TITLE
Import contact with unknown phone number

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#606]
In official app it is possible to import user to contact list even if phone number is unknown.

I'm trying to do the same using TDLib 1.4.0, but

```
{"@type":"importContacts","contacts":[{"@type":"contact","user_id":XXXX,"first_name":"Лена"}],"@extra":9199}
==>
{":@type": "importedContacts", ":user_ids":[0], ":importer_count":[0], ":@extra" 9199}
```

Am I doing something stupid?  What the correct way to add user to contacts without knowing his number?

thanks

**Comment by levlam** [comment]
New server method was added to achieve this. There is no way to do that in TDLib 1.4.0.

**Comment by levlam** [comment]
Support for adding contacts without known phone number was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
