### ISSUE TITLE
[Missing] Add to Contacts/Block User instead Report spam

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#609]
Blog: https://telegram.org/blog/contacts-local-groups

**Comment by smaznet** [comment]
Is there any update for this?

**Comment by levlam** [comment]
@smaznet No, server-generated chat header isn't available in TDLib yet and is expected to be added only in TDLib 1.6.0.

**Comment by levlam** [comment]
Support for new chat action bar was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
