### ISSUE TITLE
An unknown error

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#613]
I run a bot after a while it was stopped working and showed this error ;

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

[ 0][t 0][1561986013.779947758][MessagesManager.cpp:10127][!Td][&last_new_message_id.get() > d->last_new_message_id.get()]       server message 432473 server message 432473 on_get_channel_dialog 40

**Comment by levlam** [comment]
You need to apply this patch to TDLib to fix this: 
[0001-Fix-setting-last_new_message_id.txt](https://github.com/tdlib/td/files/3346102/0001-Fix-setting-last_new_message_id.txt).

**Comment by Kia-Pashang** [comment]
> You need to apply this patch to TDLib to fix this:
> [0001-Fix-setting-last_new_message_id.txt](https://github.com/tdlib/td/files/3346102/0001-Fix-setting-last_new_message_id.txt).

It worked thanks a lot

**Comment by levlam** [comment]
This was fixed in TDLib 1.5.0.
