### ISSUE TITLE
example for replyMarkupInlineKeyboard

### ISSUE THREAD

**Issue by Mohammadwh** [tdlib/td#614]
hello please give example code for replyMarkupInlineKeyboard for lua and python 
whats problem this code:

		reply_markup = 	{
			["@type"] = "replyMarkupInlineKeyboard",
			rows = {
				{
					text = "test",
					type = {
						["@type"] = "inlineKeyboardButtonTypeCallback",
						data = base64encode('test'),
					}
				},
			},
	
	
		}
and i vardump it : 
 {
  ["@type"] = "replyMarkupInlineKeyboard",
  rows = {
    {
      text = "test",
      type = {
        ["@type"] = "inlineKeyboardButtonTypeCallback",
        data = "dGVzdA=="
      }
    }
  }
}

**Comment by levlam** [comment]
Reply markup can be specified only by a bot.

Also, in JSON interface you need to base64-encode `data` field of type `bytes`.

**Comment by Mohammadwh** [comment]
yes i encode to base64 but not send message
