### ISSUE TITLE
[&last_new_message_id.get() > d->last_new_message_id.get()]

### ISSUE THREAD

**Issue by puryanms** [tdlib/td#615]
hey im using python3.7 and tdlib 1.4.0
after 2 days working well
i got this error :
[ 0][t 4][1562181643.643609285][MessagesManager.cpp:10127][#1][!Td][&last_new_message_id.get() > d->last_new_message_id.get()]      server message 7654 server message 7654 on_get_channel_dialog 40

**Comment by puryanms** [comment]
i cant run my script ..
this error aborting..

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/613#issuecomment-507293422.

**Comment by levlam** [comment]
This was fixed in TDLib 1.5.0.
