### ISSUE TITLE
Java : export telegram data

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#616]
Hi
In telegram desktop I see in settings->advanced.how to use that export in java api?

**Comment by levlam** [comment]
Data export is available only in Telegram Desktop and will not be available in TDLib.

**Comment by sadeghpro** [comment]
I see export work per contact and get 100 message each time. I can do that but I thing telegram server ban account for that too many request.

**Comment by levlam** [comment]
Every request has its flood limit, so you will definitely receive a lot of 429th errors and will need to wait a lot if you try to emulate chats export with `getChatHistory`.

**Comment by sadeghpro** [comment]
ok tnx
