### ISSUE TITLE
tdjni.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by kalian** [tdlib/td#617]
i compiled all for x64 windows platform for java(https://tdlib.github.io/td/build.html)
I've tried to copy tdjni.dll libeay32.dll ssleay32dll and zlib1.dll to my project
I've tried to "-Djava.library.path=E:\projects\java\td\example\java\build\Release"
but  on System.loadLibrary("tdjni"); it`s throwing exception

i made test.java
public class test {
    public static void main(String [] argv){
        System.loadLibrary("tdjni");
    }   
}
I've tried System.loadLibrary("libeay32"); BUILD SUCCESS
I've tried System.loadLibrary("zlib1"); BUILD SUCCESS
I've tried System.loadLibrary("ssleay32"); exception again E:\projects\java\td\example\java\build\Release\SSLEAY32.dll: Can't find dependent libraries
what is wrong with it
i spend my day to compile tdlib for 2 times on 2 different PCs

**Comment by levlam** [comment]
java.library.path is ignored for dependent libraries, so you need to copy all the libraries to the working directory of your project or to a directory available through path environment variable. Also see other possible reasons in https://github.com/tdlib/td/issues/315.

**Comment by kalian** [comment]
I've tried to copy tdjni.dll libeay32.dll ssleay32dll and zlib1.dll to my project what else i need to copy?
dependency walker opening ssleay32dll shows libraris from system32 it is in PATH

**Comment by kalian** [comment]
i`ve copied tdjni.dll libeay32.dll ssleay32dll and zlib1.dll to system32 my problem gone? but now ...."Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Windows\System32\tdjni.dll: %1 не является приложением Win32"

**Comment by denisab85** [comment]
I faced this issue at commit [8ab43e5b9f26931f70ad07660850e39ab345a801](https://github.com/tdlib/td/commit/8ab43e5b9f26931f70ad07660850e39ab345a801). Copying `zlib1.dll` to `C:\Windows\System32` does solve the issue. The other DDLs load well from within their standard location inside the td folder and require no copying. Investigation with [Procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) shows that the TD Java process looks for `zlib1.dll` in the system PATHs, but not in `java.library.path` passed as argument.

![image](https://user-images.githubusercontent.com/16647044/194774444-1daf7186-0ef2-4f4d-bb53-d51a36e1ea18.png)

**Comment by levlam** [comment]
@denisab85 
This is expected behavior of DLL loading. `java.library.path` can affect only DLLs explicitly loaded in Java source code. All their dependent DLLs must be automatically loaded by OS and hence they can be only found in standard paths, the directory from which the application loaded. and the current directory. See https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order for more details.
