### ISSUE TITLE
Access to db for contact/chat pictures

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#619]
Hello,

in Ubuntu Touch the push notifications are passed into a push helper executable, which is out-of-process of the main Telegram App process. This helper can optionally display the contact/chat picture and would therefore need to determine the file name for any given chat Id from the notification.

As I understand the tdlib Db is encrypted. But I want to avoid loading/unloading a whole tdlib instance for every incoming notification. How can I map the chat id to the profile_photos folder file names?

**Comment by levlam** [comment]
I don't think there is a way to achieve good user experience with notifications without using TDLib Notification API introduced in TDLib 1.4.0, but this will definitely requires to launch TDLib for all incoming notifications.
Profile photos are saved under name `${volume_id}_${local_id}.jpg`, so if a push notification contains volume_id and local_id fields, you can try to load the photo directly from the drive using this name. But I can't guarantee that it will work in the future.

**Comment by Flohack74** [comment]
Thanks. Is there any description about this API? This will probably be a problem for us since in Ubuntu Touch Apps normally are not allowed to have background activity, so the main Telegram app is suspended when the phone is locked. Thats the reason why there is a separate push helper, Canonical wanted to keep CPU cycles low and not fire up the app for processing notifications.

**Comment by levlam** [comment]
You can find all the new methods and links to the doumentation in the [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md).

**Comment by Flohack74** [comment]
We solved it now by exfiltrating the id and path of the chat picture and accessing this from the push helper for the time being. Until we can advance with the new push API in tdlib thats ok for us.
