### ISSUE TITLE
java: synchronization on local variable

### ISSUE THREAD

**Issue by sadeghpro** [tdlib/td#623]
hi 
in java example in `org.drinkless.tdlib.example.Example` there are many synchronization on local variable in `UpdatesHandler` class like :
```
case TdApi.UpdateChatTitle.CONSTRUCTOR: {
    TdApi.UpdateChatTitle updateChat = (TdApi.UpdateChatTitle) object;
    TdApi.Chat chat = chats.get(updateChat.chatId);
    synchronized (chat) {
            chat.title = updateChat.title;
    }
    break;
}
```
I think they don't work really because for example if another `UpdateChatTitle` receive from server new object create and new object synchronize.
is this ok?

**Comment by levlam** [comment]
Yes, this is ok and this is exactly what is needed there. The block is synchronized not on the local variable, but on the `chat` object, stored in the ConcurrentMap `chats` to ensure that only one thread can access the object at the same time.

**Comment by sadeghpro** [comment]
ok tnx
