### ISSUE TITLE
How to answer on replyMarkup using Telegram java TdApi?

### ISSUE THREAD

**Issue by Pyroblastka** [tdlib/td#626]
Help please to make reply on replyMarkup.

https://stackoverflow.com/questions/56923326/how-to-answer-on-replymarkup-using-telegram-java-tdapi

**Comment by levlam** [comment]
You need to use method `GetCallbackQueryAnswer` to send a callback query to a bot passing `CallbackQueryPayloadData` with `data` from the button as a `payload`.
For example, button
```
          InlineKeyboardButton {
            text = "3"
            type = InlineKeyboardButtonTypeCallback {
              data = bytes [15] { 73 65 6E 64 5F 72 65 61 63 74 69 6F 6E 5F 32 }
            }
          }
```
has `data = bytes [15] { 73 65 6E 64 5F 72 65 61 63 74 69 6F 6E 5F 32 }`.

**Comment by Pyroblastka** [comment]
Thank you so much. It exactly what i looked for.

**Comment by PavelZubkov** [comment]
Hi. Help please to make reply on replyMarkupShowKeyboard.

**Comment by levlam** [comment]
@PavelZubkov `replyMarkupShowKeyboard` contains options of text responses for the user. Application needs only to send a text message with the corresponding text.

**Comment by PavelZubkov** [comment]
Thank you very much

**Comment by FunkyYang** [comment]
error! code: %!d(float64=400) msg: Failed to parse JSON object as TDLib request: Unknown class ""

**Comment by FunkyYang** [comment]
that I use ``` GetCallbackQueryAnswer ``` for use.
