### ISSUE TITLE
How to search user by name?

### ISSUE THREAD

**Issue by kigorw** [tdlib/td#627]
There is `contacts.search` (https://core.telegram.org/method/contacts.search) but it seems there is no way to call it from the tdlib. 
I'm looking for a way to search contacts outside of known contacts (like telegram client does).

**Comment by zevlg** [comment]
I use `searchPublicChats` and then filter private chats, excluding bots

**Comment by kigorw** [comment]
Thanks. But it doesn’t return unknown users

**Comment by levlam** [comment]
@kigorw `searchPublicChats` is exactly the method you are looking for.

**Comment by levlam** [comment]
Between, users not from your chat or contact list can be found only by their username using that method. There is no way to find them by first/last name.

**Comment by kigorw** [comment]
Thanks, your replies helped me to implement what I needed.

**Comment by yxl411174564** [comment]
> Thanks, your replies helped me to implement what I needed.

why i use searchPublicChats doesn't return 
how do you do
