### ISSUE TITLE
Java, after cmake build, cant able to run example

### ISSUE THREAD

**Issue by zahirzoe** [tdlib/td#628]
`[100%] Built target generate_common
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/zkamal/Downloads/tdlib/jnibuild2/../example/java/td/lib/libtdutils.a
-- Installing: /Users/zkamal/Downloads/tdlib/jnibuild2/../example/java/td/bin/td_generate_java_api
-- Up-to-date: /Users/zkamal/Downloads/tdlib/jnibuild2/../example/java/td/bin/td/generate/JavadocTlDocumentationGenerator.php
-- Up-to-date: /Users/zkamal/Downloads/tdlib/jnibuild2/../example/java/td/bin/td/generate/TlDocumentationGenerator.php
-- Up-to-date: /Users/zkamal/Downloads/tdlib/jnibuild2/../example/java/td/bin/td/generate/scheme/td_api.tlo
-- Up-to-date: /Users/zkamal/Downloads/tdlib/jnibuild2/../example/java/td/bin/td/generate/scheme/td_api.tl
`

Logs seems fine, after that i try to run the below command 

 `cd <path to TDLib sources>/example/java/bin
java '-Djava.library.path=.' org/drinkless/tdlib/example/Example`

am getting error:
`Error: Could not find or load main class org.drinkless.tdlib.example.Example`

Seems like Java not built

**Comment by levlam** [comment]
You need to build Java after TDLib is built and insalled. See https://tdlib.github.io/td/build.html?language=Java for the full build instructions.

**Comment by zahirzoe** [comment]
Awesome, great thanks
