### ISSUE TITLE
getMessage returns "Invalid user 0 specified to be a sender"

### ISSUE THREAD

**Issue by MattNguyen** [tdlib/td#629]
I'm currently attempting to query `getMessage` with a valid `chat_id` and `message_id`, but tdlib returns the following:

```
[ 1][t 4][1563318532.004804134][MessagesManager.cpp:9792][#2][!Td]      Invalid user 0 specified to be a sender of the server message XXXX in chat -XXXXXXXXXXXX
```

I'm noticing that this is only happening for _some_ messages, not all. Would greatly appreciate assistance!

**Comment by levlam** [comment]
You can applly patch from https://github.com/tdlib/td/issues/622#issuecomment-508931043 to add support for message from supergroups without a sender, which are automatically forwarded from the linked channel.

**Comment by levlam** [comment]
Support for messages with unknown sender in private chats, basic groups and supergroups was added in TDLib 1.5.0.
