### ISSUE TITLE
Use ipv6 as default connection

### ISSUE THREAD

**Issue by hassandg** [tdlib/td#63]
Hi
Is there any option to use ipv6 as **default** connection. And on migrations choose ipv6 from dcOptions and reconnect to ipv6 servers?

Thanks

**Comment by levlam** [comment]
Currently, no, because the library should automatically switch to IPv6 connection if it is better than IPv4 one. But we may add such option in a future, because it can slightly speed up connection creation time in case of unreliable IPv4.

**Comment by hassandg** [comment]
Waiting to see such option in this great lib :)

**Comment by hassandg** [comment]
Is this option added in new version?

**Comment by levlam** [comment]
No, it wasn't added yet.

**Comment by hassandg** [comment]
Do you have any decision to add this?

**Comment by levlam** [comment]
The option will not harm, but it shouldn't be really helpful. What do you expect from it? Should it be "disable IPv4" or "prefer IPv6"?

**Comment by hassandg** [comment]
I think prefer IPv6 is better
I need the lib to connect and use IPv6 first (Instead of IPv4).

**Comment by levlam** [comment]
If IPv6 works and IPv4 doesn't work, TDLib will find it itself almost immediately and will use IPv6. If IPv6 is more stable than IPv4 then the same should happen.

**Comment by hassandg** [comment]
I know But if we want to force using IPv6 instead of IPv4 first It's not possible unfortunately.

**Comment by levlam** [comment]
That's why I'm asking for expected behavior and 
> "disable IPv4" or "prefer IPv6"
If IPv4 isn't disabled completely it can be used if it is automatically found to be more stable than IPv6.

**Comment by hassandg** [comment]
So maybe disable IPv6 configuration is good. It will be very good if you add such option

**Comment by levlam** [comment]
@hassandg In TDLib 1.3.0 writable option `prefer_ipv6` was added, which can be used to prefer IPv6 connections over IPv4. It should be used with care, because it can prevent TDLib from connecting with Telegram servers in case of unavailable IPv6 network.

**Comment by hassandg** [comment]
Hi
I've tested the new version, It seem's the problem exists in new update too
When setting prefer_ipv6 option to true without any proxy, tdlib uses ipv4 instead

**Comment by levlam** [comment]
With this option it should try only IPv6 connections to DCs which has such IP, i.e. to all DCs currently. Could you send TDLib logs with verbosity level 3 to @tdlib_bot if the option doesn't work for you as expected?
