### ISSUE TITLE
429 error when login

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#630]
Hello,

My team is working on an app based on TDlib from different places (IPs). Sometimes during testing 429 error occurres after many login attempts and it is required to wait for a day to make that error gone. Because every new login for any telegram account in that case brings up error and counter always is 86400:

Error {
  code = 429
  message = "Too Many Requests: retry after 86400"
}

Could you please provide any help on how to avoid this? Maybe there are limits or we're testing application in non-production mode? I'm just curious because if launch the same application from other IPs this error is not displayed. And besides, if accounts that already got logged in, still can call other methods (like send message) without any errors while others cannot login.
Thanks in advance.

UPD:
Could it be caused by the fact that before we had many errors like this during login:

Error {
  code = 401
  message = "Initialization parameters are needed: call setTdlibParameters first"
}

Or due to we had many "PHONE_CODE_INVALID"

?

The main issue here is that not only one user cannot login, but any from the same IP.

**Comment by levlam** [comment]
It happens because you had to much "PHONE_CODE_INVALID" errors, which was taken as a try to brute-force authorization code. There is no way to avoid the error 429, except waiting. In the meanwhile you can use test DC to test authorization.

**Comment by Mike497** [comment]
@levlam , thanks
So it is ok in this case that we cannot authorize even from other accounts that didn't get PHONE_CODE_INVALID errors?

**Comment by levlam** [comment]
Yes, it is expected.
