### ISSUE TITLE
TDlib build Problem in win\c#\.net core 

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#631]
openssl-windows : x86-windows failed .
Any one can give me some methods? tks.

`
./vcpkg.exe install openssl : x86-windows zlib : x86-windows
The following packages will be built and installed:
     opensll[core] : x86-windows
    *openssl-windows[core] : x86-windows
     zlib[core] : x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openssl-windows: x86-windows
Building package openssl-windows[core]: x86-windows...
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg 
-- Build x86-windows-dbg done
CMake Error at scripts/cmake/vcpkg_copy_pdbs.cmake:62 (file):
  file COPY cannot find
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:196 (vcpkg_copy_pdbs)
  scripts/ports.cmake:73 (include)

Error: Building package openssl-windows: x86-windows failed with : BUILD_FAILED

**Comment by levlam** [comment]
What is a full path of the directory vcpkg is run from? Could you try to run vcpkg from another directory, if it contains some non-ASCII characters?

**Comment by Pauya** [comment]
Yes,the directory contains some Chinese characters.
Let me change this,and  have a try.
tks.

**Comment by Pauya** [comment]
![QQ图片20190722003116](https://user-images.githubusercontent.com/53131686/61593950-bfe29180-ac18-11e9-8b74-48d47ab804ba.png)
Did it succeed or fail?

**Comment by Pauya** [comment]
![QQ图片20190722005141](https://user-images.githubusercontent.com/53131686/61594200-79dafd00-ac1b-11e9-98de-914af74bdaa2.png)

**Comment by levlam** [comment]
It is success, but still there is somewhere a problem with encoding. Could you try to run the build commaтв from cmd? If it will not work immediately, you can try to run `chcp 65001` in cmd and try again.

**Comment by Pauya** [comment]
![QQ图片20190722080236](https://user-images.githubusercontent.com/53131686/61599051-99901680-ac57-11e9-93e2-463557974687.png)
![QQ图片20190722080315](https://user-images.githubusercontent.com/53131686/61599058-a14fbb00-ac57-11e9-80fe-ad88f55e6944.png)

**Comment by levlam** [comment]
Could you try to build from scratch using this instruction: https://tdlib.github.io/td/build.html?language=C%23? Does it fails with the same error?

**Comment by Pauya** [comment]
OK,i'll have a try.

**Comment by Pauya** [comment]
> Could you try to build from scratch using this instruction: https://tdlib.github.io/td/build.html?language=C%23? Does it fails with the same error?

Yes, It failed with the same error.

**Comment by levlam** [comment]
@Pauya There is still some incoding issue, which makes compilation errors unreadable, but the error can be in something other.

Which Windows version are you using? What subfolders do you have in "C:\Program Files (x86)\Windows Kits\" and "C:\Program Files (x86)\Windows Kits\10\Include" folders?

**Comment by Pauya** [comment]
win 7 sp1
![QQ图片20190726074901](https://user-images.githubusercontent.com/53131686/61916266-75477900-af7a-11e9-8b26-27dd3869a7e0.png)
![QQ图片20190726074934](https://user-images.githubusercontent.com/53131686/61916270-78db0000-af7a-11e9-8df4-1ef9f560ce1f.png)

**Comment by levlam** [comment]
@Pauya Do you have file `C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\WinSock2.h`.

If it is there, then the problem is likely to be in the console/system encoding. Could you try to install English language pack for Visual Studio:
- Go to https://visualstudio.microsoft.com/downloads/
and download "Build Tools for Visual Studio" (they can be found below main block in the second subsection);
- Run "Build Tools for Visual Studio", choise "Language packs" and add "English"?

**Comment by Pauya** [comment]
> @Pauya Do you have file `C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\WinSock2.h`.
> 
> If it is there, then the problem is likely to be in the console/system encoding. Could you try to install English language pack for Visual Studio:
> 
> * Go to https://visualstudio.microsoft.com/downloads/
>   and download "Build Tools for Visual Studio" (they can be found below main block in the second subsection);
> * Run "Build Tools for Visual Studio", choise "Language packs" and add "English"?

I had added English already before last TDLib building.  Now vs2017 has two language packages,Chinese and English.  Error is remaining. Errors are still there. Should  I remove Chinese package?

**Comment by Pauya** [comment]
That's unuseful. Error again.
![1](https://user-images.githubusercontent.com/53131686/62001081-7b745b80-b11a-11e9-9493-c3eeaebdcb69.png)
![2](https://user-images.githubusercontent.com/53131686/62001082-7fa07900-b11a-11e9-8ff3-6191bbf286d9.png)
The OS is windows 7 sp1 x64 ,Chinese package.

**Comment by levlam** [comment]
There is no error during first CMake invocaition, but there is an error during build stage. Do you have by any chance case-sensitive filesystem?

If not, then let's try to remove the Chinese package, because some errors are still not in English.

**Comment by Pauya** [comment]
“case-sensitive filesystem” I don't know what is it.
I removed Chinese package. The error was still there.

**Comment by levlam** [comment]
> “case-sensitive filesystem” I don't know what is it.

Could you try to run
```
dir 'C:\Program Files (x86)\Windows Kits\10\Include\*\*\Winsock2.h'
```
?

**Comment by Pauya** [comment]
![1](https://user-images.githubusercontent.com/53131686/62007640-967ab600-b182-11e9-8c54-bbb5ccb5a392.png)

**Comment by levlam** [comment]
Everything looks correct to me. I have no idea, why the system headers are not found during build stage by the compiler.

Could you try to check whether answer https://stackoverflow.com/a/38796293 applies to you case, or whether some answers from https://stackoverflow.com/questions/22390539/sdkddkver-h-missing-but-winsdk-installed-c-header-issues helps?

**Comment by Pauya** [comment]
When I reinstalled the OS, build passed.
