### ISSUE TITLE
Error while building master example/java on Ubuntu

### ISSUE THREAD

**Issue by stanleyG123** [tdlib/td#633]
Error while building : 
--------------------------------------------------
.......
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0xc8): undefined reference to `vtable for td::td_api::formattedText'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0xeb): undefined reference to `vtable for td::td_api::textEntity'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x15d): undefined reference to `vtable for td::td_api::photo'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x190): undefined reference to `vtable for td::td_api::photoSize'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x1ab): undefined reference to `vtable for td::td_api::file'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x1c3): undefined reference to `vtable for td::td_api::remoteFile'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x201): undefined reference to `vtable for td::td_api::localFile'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x29a): undefined reference to `vtable for td::td_api::animation'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x2b5): undefined reference to `vtable for td::td_api::file'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x2ce): undefined reference to `vtable for td::td_api::remoteFile'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x305): undefined reference to `vtable for td::td_api::localFile'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x34c): undefined reference to `vtable for td::td_api::photoSize'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x369): undefined reference to `vtable for td::td_api::file'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x380): undefined reference to `vtable for td::td_api::remoteFile'
Game.cpp:(.text._ZNK2td4Game15get_game_objectEPNS_2TdE+0x3b6): undefined reference to `vtable for td::td_api::localFile'
libtdcore.a(Game.cpp.o): In function `td::process_input_message_game(td::ContactsManager const*, td::tl::unique_ptr<td::td_api::InputMessageContent>&&)':
Game.cpp:(.text._ZN2td26process_input_message_gameEPKNS_15ContactsManagerEONS_2tl10unique_ptrINS_6td_api19InputMessageContentEEE+0xbc): undefined reference to `vtable for td::td_api::inputMessageGame'
collect2: error: ld returned 1 exit status
make[2]: *** [tg_cli] Error 1
make[1]: *** [CMakeFiles/tg_cli.dir/all] Error 2
make: *** [all] Error 2

--------------------------------------------
Ubuntu 18.04.2 LTS
cmake  3.10.2
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
OpenSSL 1.1.1  11 Sep 2018
1:1.2.11.dfsg-0ubuntu2
gperf 3.1-1

**Comment by stanleyG123** [comment]
Is it enough information , or should I post a complete log file ? 

I am wondering if I should downgrade some of the tools I am using.  Thanks again whoever is in the know.

**Comment by levlam** [comment]
Do you use LTO?
Could you attach CMakeCache.txt file from the build directory and outpud of `cmake --build .` command?

**Comment by stanleyG123** [comment]
I use all defaults ( From what I understand LTO is no longer default)

[error_out.txt](https://github.com/tdlib/td/files/3418839/error_out.txt)

[CMakeCache.txt](https://github.com/tdlib/td/files/3418853/CMakeCache.txt)

**Comment by levlam** [comment]
I think that the problem is in SplitSource.php usage. `cmake --build . --target prepare_cross_compiling` must be run first to generate some source files and only after that SplitSource.php can be used.

Could you try to follow exact instructions from https://tdlib.github.io/td/build.html?language=Java to rebuild TDLib from scratch?

**Comment by stanleyG123** [comment]
Genius !! I must have messed up a path somewhere . 

all works now.
thanks for your help.
