### ISSUE TITLE
 Could not load file or assembly 'Telegram.Td.dll' or one of its dependencies on windows Form Application

### ISSUE THREAD

**Issue by drmasnavi** [tdlib/td#634]
I've got no problem on my own pc. when I tried to deploy my final project on another pc I have following exception on runtime:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Telegram.Td.dll' or one of its dependencies. The specified module could not be found.
File name: 'Telegram.Td.dll'

Already Tried:
Copying all dependencies 
Setting Path Value 
GAC Installation of  'Telegram.Td.dll'

regards

**Comment by levlam** [comment]
Does solutions from https://github.com/tdlib/td/issues/551 and https://github.com/tdlib/td/issues/228 help you?

**Comment by drmasnavi** [comment]
unfortunately not :| 
I'm still working on it.

**Comment by levlam** [comment]
Have you copied correct Release/Debug Telegram.Td.dll along with corresponding LIBEAY32.dll. SSLEAY32.dll and zlib1.dll/zlibd1.dll? You may also need to install Visual C++ redistributable on the target machine.

**Comment by drmasnavi** [comment]
Yeah I have copied all of them and even installed C++ redist files from here:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I have no problem with my developing machine

what have made me confused is that I can see through process monitor (from sys internals) Telegram.Td.dll is already loaded successfully!!! 👎 

Attachment:
https://pasteboard.co/IplsE2J.png

**Comment by drmasnavi** [comment]
I could finally resolve it by using Dependency walker application.

you have to deploy proper version of ucrtbased.dll with your project into third party user's device.

regards

**Comment by drmasnavi** [comment]
Seems like being in Iran is against helping other people in the world even if you are a person who don't give a fu%$k to politicians & politics.
thank you fu%$king trump! 
======================================================
Due to U.S. trade controls law restrictions, your GitHub account has been restricted. This means we 
have suspended access to private repository services and paid services for your account. For free individual accounts, you still have access to free GitHub public repository services (such as public repositories for open source projects and associated GitHub Pages and Gists). If you believe your account has been flagged in error, and you are not located in or resident in a sanctioned region, please file an appeal. Please read about GitHub and Trade Controls for more information.
=====================================================
