### ISSUE TITLE
correlating response messages with sends

### ISSUE THREAD

**Issue by stanleyG123** [tdlib/td#638]
HI @levlam ,   I want to grab a bunch historical messages from a channel (in Java)  and calling  TdApi.GetChatHistory in a loop repeatedly. In order to make sure that I receive messages consistently and stop when reach the end or an error , do I need a block after send on each request until I get a response ? or there is a better way to go about this. An example would be nice.

thanks.

**Comment by levlam** [comment]
You need to send requests consecutively, because before the previous request is completed you don't know what to pass as `from_message_id` to the next request.

**Comment by stanleyG123** [comment]
I ended up blocking on each call until receive a response. It looks butt ugly now won't even post what I have , but will come back when I get a chance to get CompletableFuture version working.

thanks @levlam for all your help.
