### ISSUE TITLE
TdApi.GetChatHistory when do I stop looping?

### ISSUE THREAD

**Issue by stanleyG123** [tdlib/td#639]
When collecting message history , I decrement _from_message_id_ on each API call. How do I know when I reached the end?  

Currently I compare last message received id with  _from_message_id_  and if from_message_id  == lastMessageId  I stop.

Is there a better way ? 

tanks

**Comment by levlam** [comment]
You will never receive the same message twice if you use `offset == 0` and correctly adjust `from_message_id` as described in https://core.telegram.org/tdlib/getting-started#getting-chat-messages. The end of the history is reached whenever you receive 0 messages in response.

**Comment by zelenin** [comment]
i have an example of getting all messages https://github.com/zelenin/go-tdlib/blob/master/client/puller/chat.go

**Comment by stanleyG123** [comment]
thanks you brother ,

go is awesome
