### ISSUE TITLE
[Feature Request] RPC Version of tdlib

### ISSUE THREAD

**Issue by septs** [tdlib/td#64]
AFAIK, it's hard to call `tdlib` in several language (e.g.: Node.js), so I think it's a good idea to create an **RPC** version. If does so, cross-platform developing would be MUCH easier.

Ref: http://www.jsonrpc.org/specification

**Comment by levlam** [comment]
TDLib provides a JSON interface. Why it's hard to call it from Node.js?

**Comment by levlam** [comment]
Our JSON requests/responses format in fact is very similar to jsonrpc.

**Comment by septs** [comment]
Thank you for replying. However, what I want is **remote** procedure call, instead of calling `tdlib` w/ JSON interface.

**Comment by levlam** [comment]
Then you can look at https://github.com/vysheng/tdbot, which seems to provide TDLib JSON interface over TCP/Unix socket.

**Comment by levlam** [comment]
It uses TDLib as subproject, as a part of its source tree. It should be built as any other CMake project:
```
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by seiya-git** [comment]
@septs try this https://github.com/nodegin/tglib
