### ISSUE TITLE
updateChatUnreadMentionCount not triggered when viewMessages was issued

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#641]
In tdlib 1.3:

- When unread mentions are present in a chat, the updateChatUnreadMentionCount message is only sent when new unread mentions are being made. Reading messages in either any official App or the tdlib App we developed will not trigger a new unreadMentionCount message.

**Comment by Flohack74** [comment]
However, updateMessageMentionRead is triggered and I can use that signal for the time being. Is there any disadvantage in using that also for the chat list summary info?

**Comment by Flohack74** [comment]
Another strange thing, marking all messages read in a chat does not always also clear mentions. How is that supposed to work?

**Comment by levlam** [comment]
`updateMessageMentionRead` also contains `unread_mention_count`, which is the new count of unread mentions, so there is no reason to send also `updateChatUnreadMentionCount`.

It is not enough to read chat history to mark mentions as read. The user must view the message with a mention, or sometimes even to open a content of the message. There is also a separate method `readAllChatMentions` to read all mentions in a chat.

**Comment by Flohack74** [comment]
Well we trigger viewMessages:
`[SEND] : QJsonObject({"@type":"viewMessages","chat_id":-1001189024726,"force_read":false,"message_ids":[20629684224]})
`
for example. In most cases the mention will then be marked as read as well. I can see that I can read all mentions with that method, but what if the user did not yet scroll to that mention?

**Comment by levlam** [comment]
It is wrong that you can read all mentions with that method, and it is wrong to read mentions before they are seen by the user. You need only to properly call `viewMessages` and `viewMessageContent`, then mentions will be read by TDLib when appropriate.
Application anso needs to allow to easily navigate to unread mentions via additional button and `searchChatMessages` with `searchMessagesFilterUnreadMention` filter.

**Comment by Flohack74** [comment]
Oh, so there is another method for the content. That might explain it. We will give it a try...

**Comment by Flohack74** [comment]
Are you sure about that method, I do not find it in the API pages on your site.

**Comment by levlam** [comment]
I've meant `openMessageContent`. It affect mentions using voice and video notes.
