### ISSUE TITLE
Picture compression?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#642]
I know that sending photos is different from using file attachment type, but who is actually compression the picture for photo types? Is it on the server or client?

TELEports users complain that their pictures are being uploaded in full resolution, which takes a long time. I always thought thats the usual way. But does any of the official Apps compress locally before sending?
Thanks!

**Comment by levlam** [comment]
Both client and server compress photos.
First client compresses and scale photos, so they are uploaded size is small enough. This isn't mandatory, but highly recommended.
Upon receiving server scales photos to different sizes and recompresses them if needed.

**Comment by Flohack74** [comment]
Do you have a pointer for me to the compression/resize values used? I.e. in the official Android client maybe? Thanks.

**Comment by levlam** [comment]
See https://github.com/DrKLO/Telegram/blob/9f48ec7ea2dbdf0caef16ed0fc6b6cd1e3f3f368/TMessagesProj/src/main/java/org/telegram/messenger/SendMessagesHelper.java#L4471.
