### ISSUE TITLE
Concurrent calls of tdlib give JSON parse errors

### ISSUE THREAD

**Issue by kigorw** [tdlib/td#643]
I use `airgram` client which uses `ffi-napi` (node js). If I concurrently open sessions for more than 1 telegram account, I'm getting JSON parse errors like these
![image](https://user-images.githubusercontent.com/319966/62051420-65eb5880-b224-11e9-8e76-ef1a535e9f5e.png)

Should tdlib support concurrent sessions, or am I doing something wrong?

**Comment by levlam** [comment]
With is a limitation of the original `ffi-napi`: https://github.com/node-ffi-napi/node-ffi-napi#node-ffi-napi.
```
The original API of node-ffi is left mostly untouched in the N-API wrapper. However, the API did not have very well-defined properties in the context of garbage collection and multi-threaded execution. It is recommended to avoid any multi-threading usage of this library if possible.
```

TDLib itself can be used in multithreaded environment without any limitations.

**Comment by kigorw** [comment]
Would you recommend something better for NodeJS or it makes sense to use
something like Rust?

**Comment by levlam** [comment]
@kigorw There is a discussion about that problem in https://github.com/Bannerets/tdl/issues/18.

**Comment by levlam** [comment]
In the new JSON interface `td_receive` needs to be called from a single thread, regardless of the number of used clients, so it is less prone to drawbacks of `ffi-napi`. Anyway, this is an issue with `ffi-napi` and not TDLib.
