### ISSUE TITLE
The "lastMessage" field in TdApi.Chat in Java doesn't match the actual last message

### ISSUE THREAD

**Issue by chairus** [tdlib/td#644]
When getting the chat object, using the `TdApi.GetChat` of say `chatA` at `timeA` the `lastMessage` field contains the correct last/latest message in the chat, then, some member posted something on the chat at `timeB` (`timeB` > `timeA`, i.e. `timeB` happened after `timeA`), I retrieve the chat object again using `TdApi.GetChat` of the same chat, but to my surprise the `lastMessage` field still contains the message from `timeA`, as if no one has posted something new in the chat. Is this a bug? The `lastMessage` field of the `TdApi.Chat` object should contain the last/latest message. Is there something I should do?

**Comment by chairus** [comment]
I think I might have found the problem. The `use_chat_info_database_` and `use_message_database_` has been set to `true`, which means that it would look into the cached chats if found it will return the cached chat. However, why is it that on some occasions I am able to get the latest message?

**Comment by levlam** [comment]
Everything works as expected, because there is enough data in the database to answer the request offline, There is no such concept as "last chat message", there is only "last **known** chat message". For chats, in which the user is a member it is updated automatically when there is an Internet connection. For hundred millions of other chats it is updated only when the user opens the chat, which can be done using `openChat` call in TDLib.

**Comment by chairus** [comment]
Got it! Thanks @levlam

**Comment by chairus** [comment]
@levlam Sorry for asking too many questions, but are there any advantages of calling the `closeChat` API in TDLib when you are done with the chat? If there are, what are they?

**Comment by levlam** [comment]
@chairus You must call it to
- Ensure correct behavior of other methods.
- Reduce network usage.
- Be not flood-restricted by the server.

**Comment by chairus** [comment]
Awesome those are great points. Just a follow-up question on the first point

>Ensure correct behavior of other methods.

does that include when you call the `openChat` method the next time it ensures that the chat gets updated?

**Comment by levlam** [comment]
@chairus `openChat` will work correctly, but there are methods like `viewMessages` which have different behavior for opened and closed chats.

**Comment by chairus** [comment]
@levlam Just wondering why calling the `getChatHistory` with parameters:
`chatId`: <chatId>
`fromMessageId`: 0
`offset`: -99
`limit`: 100
The returned `TdApi.Messages` doesn't contain the last/latest message in the chat? Shouldn't it send a network request because TDLib cannot guarantee that whatever it is stored in DB it may not be the latest message?

**Comment by levlam** [comment]
@chairus No, a chat can be opened only by explicit call to `openChat`.
