### ISSUE TITLE
Problem  on  TDLib C# example

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#645]
I have built TDLib.
But something is missed.
![1](https://user-images.githubusercontent.com/53131686/62228526-659fb880-b3f0-11e9-9d5a-b7f3e0e397e2.png)
![QQ图片20190731235827](https://user-images.githubusercontent.com/53131686/62228534-6a646c80-b3f0-11e9-967e-a5c480c74d0d.png)

**Comment by levlam** [comment]
Telegram.Td.dll needs to be built in Debug and Release mode and placed in `td\example\csharp\build\Debug\` and `td\example\csharp\build\Release\` folders. Also corresponding LIBEAY32.dll, SSLEAY32.dll and zlibd1.dll/zlib1.dll needs to be placed in these folders. This happens automatically if TDLib is built in `td\example\csharp\build` directory as specified in README for the example.

Alternatively, you can manually edit TdExample.csproj file changing path to these DLLs.

**Comment by Pauya** [comment]
I built the program ,and its app worked.
I enter phone number behind the line "Please enter phone number". But it did not work, it likely waited something, and got no information.
Did it need a proxy? I found the app's destination IP(69.171.239.11). I  pinged it , but its request timed out.
What things do I need to do? 
![QQ图片20190807114532](https://user-images.githubusercontent.com/53131686/62593348-ed158c00-b908-11e9-8111-800ce97990dc.png)

**Comment by Pauya** [comment]
![QQ图片20190807170527](https://user-images.githubusercontent.com/53131686/62610116-96727700-b935-11e9-962a-c92f91561137.jpg)
Did the picture mean that the proxy was working?
But I could not get the anthentication code of phone number. I used  a  Chinese phone number.
What should I do ?

**Comment by Pauya** [comment]
![QQ图片20190807172818](https://user-images.githubusercontent.com/53131686/62611756-c8390d00-b938-11e9-8181-a06606becd7b.png)
Added the region code (+86), and tried again. Got no anthentication code.

**Comment by levlam** [comment]
Do you still have the problem with receiving an authentication code?

**Comment by Pauya** [comment]
Yes, the problem is still there. Was the format of phone number wrong?

**Comment by levlam** [comment]
The phone number must be in the international format. If you still have the problem, you can try to write to sms@telegram.org the phone number and other details.

**Comment by Pauya** [comment]
I had  got the authentication code.
And how to use a username to open a new  chat? 
I've searched the methods about chat, they all need a "ChatId" .

**Comment by levlam** [comment]
You can find a chat by its username using the method `searchPublicChat`.
