### ISSUE TITLE
WASM: long updates after initialization

### ISSUE THREAD

**Issue by MattNguyen** [tdlib/td#647]
We're currently shipping the wasm build to the browser similarly to telegram-react. The biggest difference is that telegram-react's initial load and update time appears much faster. It seems like we're waiting for tdlib to finish updating, which can take a long time. 

Do you have any suggestions to improve initial load performance? Would use_database be helpful here or patches to build tdlib more performant? I don't think telegram-react turns that flag on.

Any guidance would be greatly appreciated. Thanks!

**Comment by arseny30** [comment]
Are you using [tdweb](https://www.npmjs.com/package/tdweb) wrapper for tdlib?

**Comment by MattNguyen** [comment]
@arseny30 yes we're using the wrapper, which is packaged from the examples/web directory I believe.

**Comment by arseny30** [comment]
Maybe .wasm is downloaded every time in your case? In telegram-react it is cached with service-worker.

Also there is a hack for the very first start in telegram-react. It doesn't wait for tdweb to start and just shows login window immediately.

**Comment by levlam** [comment]
@MattNguyen Telegram-react also uses `useDatabase == false` to launch immediately from a clear state without getting all missed updates.

**Comment by MattNguyen** [comment]
Thanks guys.

We ended up implementing a `ReactDOM.unstable_batchedUpdates` which made the app more responsive.

Closing for now.
