### ISSUE TITLE
MessageManager.cpp error

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#648]
Hi , one month ago i had this error :

Exception ignored in: <_io.TextIOWrapper name='' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

[ 0][t 0][1561986013.779947758][MessagesManager.cpp:10127][!Td][&last_new_message_id.get() > d->last_new_message_id.get()] server message 432473 server message 432473 on_get_channel_dialog 40

and you said apply this patch https://github.com/tdlib/td/files/3346102/0001-Fix-setting-last_new_message_id.txt and i did it , it solved

but yesterday i faced this error :

[ 0][t 0][1564852814.998231173][MessagesManager.cpp:10127][!Td][&last_new_message_id.get() > d->last_new_message_id.get()]       server message 831236 server message 831236 on_get_channel_dialog 40

please help me.

**Comment by levlam** [comment]
This is exactly the same error, which is fixed by the patch. There is no way it can happen in TDLib with the patch applied.

**Comment by levlam** [comment]
The error was fixed in TDLib 1.5.0.
