### ISSUE TITLE
No difference for users joining themselves or being added

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#651]
I receive `messageChatAddMembers` in both cases, when I join a group or also when I am being added by someone else. Official clients can make a difference it seems, also our old Telegram app could calculate this from the update message (with a lot of mistakes though, since determining the join action was not easy). Is there a way to distinguish this in tdlib?

**Comment by levlam** [comment]
The messages will have different users as a sender.

**Comment by Flohack74** [comment]
Thanks that solved it! For reference, it will be the same for messageChatDeleteMembers.
