### ISSUE TITLE
what to do next after tdlib instalation with the generator? [help wanted]

### ISSUE THREAD

**Issue by johnbalvin** [tdlib/td#652]
When I finish installing [tdlib][1] with the [generator][2] I'm not quite sure what to do next so my app can use it, there is not more steps for this [![enter image description here][3]][3]

and when running the code example [example][4], it throw an error 

     fatal error: td/telegram/td_json_client.h: No such file or directory 
     #include <td/telegram/td_json_client.h>

So I think there must be some other steps so my app can work properly

Operating system: windows 10

go env:

    set GOARCH=amd64
    set GOBIN=
    set GOCACHE=C:\Users\john\AppData\Local\go-build
    set GOEXE=.exe
    set GOFLAGS=
    set GOHOSTARCH=amd64
    set GOHOSTOS=windows
    set GOOS=windows
    set GOPATH=C:\Users\john\go
    set GOPROXY=
    set GORACE=
    set GOROOT=c:\go
    set GOTMPDIR=
    set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
    set GCCGO=gccgo
    set CC=gcc
    set CXX=g++
    set CGO_ENABLED=1
    set GOMOD=E:\codigo\upwork\telegram\go.mod
    set CGO_CFLAGS=-g -O2
    set CGO_CPPFLAGS=
    set CGO_CXXFLAGS=-g -O2
    set CGO_FFLAGS=-g -O2
    set CGO_LDFLAGS=-g -O2
    set PKG_CONFIG=pkg-config
    set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\john\AppData\Local\Temp\go-build971012578=/tmp/go-build -gno-record-gcc-switches

  [1]: https://github.com/tdlib/td
  [2]: https://tdlib.github.io/td/build.html?language=Go
  [3]: https://i.stack.imgur.com/Hjuox.png
  [4]: https://github.com/zelenin/go-tdlib

**Comment by levlam** [comment]
TDLib was build and installed to the `td/tdlib` directory. You can find there all needed to use it include files and built libraries. On Linux you can install TDLib system-wide (there is a checkbox for that in build instructions generator). On Windows you will probably need to manually specify path to the installed TDLib somewhere.

**Comment by johnbalvin** [comment]
But that is why I'm asking for next step, I don't know what to do next, I manage to run all those steps sucessfully but when trying to compile the code It gives an error

**Comment by levlam** [comment]
It seems that you need to add `td/tdlib` to PATH environment variable.
