### ISSUE TITLE
What does messageContactRegistered do?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#653]
Trying to implement all missing messages I cam across `messageContactRegistered`- But it has no fields. Furthermore, new contacts that have registered seem to come via `messageCustomServiceAction` - what is the first message used for?

**Comment by levlam** [comment]
No, new contacts that have registered are coming with `messageContactRegistered`.

**Comment by Flohack74** [comment]
Hmm in tdlib 1.3 I just receive:
`QTdMessageCustomServiceAction "{\"@type\":\"messageCustomServiceAction\",\"text\":\"joined Telegram\"}"`

**Comment by levlam** [comment]
You need to update to TDLib 1.4.0.

**Comment by Flohack74** [comment]
Yeah we are working on this, but it will take a little bit longer. Thx for the moment!
