### ISSUE TITLE
Handshake is not yet ready

### ISSUE THREAD

**Issue by volcanoxj** [tdlib/td#654]
[ 2][t 4][1565247168.007828951][TdDb.cpp:313][#1][!Td]  Got PRAGMA user_version = 9
[ 2][t 4][1565247168.009821177][AuthDataShared.cpp:112][#1][!Td]        DcId{1} [auth_key_id:0][state:Empty]
[ 2][t 4][1565247168.011228085][SessionMultiProxy.cpp:121][#1][!SessionMultiProxy:1:main]       [session_count:1]
[ 2][t 4][1565247168.012213707][Session.cpp:142][#1][!SessionProxy:1:main]      Generate new session_id 443680779032124158 for auth key 0 for DC1
[ 2][t 3][1565247178.013895988][Session.cpp:1121][#1][!Session:1:main::HandshakeActor]  Failed to open connection: [Error : 0 : Timeout expired : [149.154.175.50:443] to DcId{1} from [127.0.0.1:63098]]
[ 2][t 4][1565247178.014514208][Session.cpp:1055][#1][!Session:1:main]  Handshake is not yet ready
[ 2][t 4][1565247178.015887976][RawConnection.cpp:143][#1][!PingActor<[149.154.175.50:80] to DcId{1} from [127.0.0.1:63103]>]                                                                                                                                                  [Error : 0 : Unknown [quick_ack:2933956718]]

**Comment by levlam** [comment]
You can't connect to Telegram servers. Telegram is likely to be blocked in your country.

**Comment by volcanoxj** [comment]
i use a proxy (Hong Kong)

**Comment by volcanoxj** [comment]
i telegram windows app by this proxy too

**Comment by levlam** [comment]
The proxy was not enabled via a call to `addProxy`, the connection is direct in this log.
Also, `Unknown [quick_ack:2933956718]` means that some garbage was received in the connection instead of response from Telegram servers..
