### ISSUE TITLE
chat.order is always equal "0"

### ISSUE THREAD

**Issue by ildarsaitkulov** [tdlib/td#655]
But in [doc](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat.html) declared as int.
Response:
```
{
	"@type": "chat",
	"id": -1001316515825,
	"type": {
		"@type": "chatTypeSupergroup",
		"supergroup_id": 1316515825,
		"is_channel": false
	},
	"title": "ildar_test_group_4",
	"last_message": {
		"@type": "message",
		"id": 46137344,
		"sender_user_id": 205997042,
		"chat_id": -1001316515825,
		"is_outgoing": true,
		"can_be_edited": true,
		"can_be_forwarded": true,
		"can_be_deleted_only_for_self": false,
		"can_be_deleted_for_all_users": true,
		"is_channel_post": false,
		"contains_unread_mention": false,
		"date": 1565181834,
		"edit_date": 0,
		"reply_to_message_id": 0,
		"ttl": 0,
		"ttl_expires_in": 0.000000,
		"via_bot_user_id": 0,
		"author_signature": "",
		"views": 0,
		"media_album_id": "0",
		"content": {
			"@type": "messageText",
			"text": {
				"@type": "formattedText",
				"text": "ddddddddddddddddddddddddd",
				"entities": []
			}
		}
	},
	"order": "0",
	"is_pinned": false,
	"is_marked_as_unread": false,
	"is_sponsored": false,
	"can_be_deleted_only_for_self": false,
	"can_be_deleted_for_all_users": false,
	"can_be_reported": false,
	"default_disable_notification": false,
	"unread_count": 0,
	"last_read_inbox_message_id": 46137344,
	"last_read_outbox_message_id": 19922944,
	"unread_mention_count": 0,
	"notification_settings": {
		"@type": "chatNotificationSettings",
		"use_default_mute_for": true,
		"mute_for": 0,
		"use_default_sound": true,
		"sound": "default",
		"use_default_show_preview": true,
		"show_preview": false,
		"use_default_disable_pinned_message_notifications": true,
		"disable_pinned_message_notifications": false,
		"use_default_disable_mention_notifications": true,
		"disable_mention_notifications": false
	},
	"pinned_message_id": 0,
	"reply_markup_message_id": 0,
	"client_data": "",
	"@extra": "cfb82727f9629d9bfda7c9c72b3374af"
}
```

**Comment by zevlg** [comment]
There is `updateChatOrder` with correct chat's order for known chats

**Comment by ildarsaitkulov** [comment]
Why is chat.order not update in local storage? Probably i have to call some method on `updateChatOrder` event?

**Comment by zevlg** [comment]
I suppose, because chat order might not be known at the moment of `updateNewChat` arrival, but let's wait what @levlam say

**Comment by levlam** [comment]
`Chat.order` can became known only after a successful call to `getChats` Before that there is no way to ensure that there are no chats before the chat in the chat list. The more calls to `getChats` with adjusted offset are done, the order of more chats became known. Also, see https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats for description of how chat list is supposed to be received.

**Comment by Flohack74** [comment]
So one additional question: I found a note in our code that deleted/left chats have their order set to 0, and therefore we filter them from the chatlist model. But this seems not really true: Some users are missing chats now and then. So is it ok to try to get also those chats into the viewmodel?

**Comment by levlam** [comment]
@Flohack74 No, a chat needs to be shown in the chat list, only if its order > 0.

**Comment by Flohack74** [comment]
Ok it seems I got it to work now. I am now requesting chats as long as `getChats `returns > 0 chats, and then I call `getChat `for each of them, updating my message model accordingly.
Now suddenly the chat with myself (Saved Messages) is back!
I will test with a user who is missing more chats.

**Comment by levlam** [comment]
@Flohack74 This is a race-prone way, because order of a chat can change between the responses to `getChats` and `getChat`. The better way is described here: https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats.

**Comment by Flohack74** [comment]
So you say that I first need to wait for all chat ids and then call getChats on them?
By the way, saved messages chat still has issues for some users, even after calling getChat on it, it has sort order 0. Also, last message date shows as 01.01.1970 even with a message inside sometimes.

**Comment by levlam** [comment]
@Flohack74
No, I said that you need to use `updateNewChat` and other updates changing chat `order` to maintain the correct order of chats in the list. If you do that, you call `getChats` only if the user scrolled to the end of the list. Results of the `getChats` request can be completely ignored in that case, because you have already received all chats with the correct `order` through updates.

Saved messages is no different from any other chats. It will have order 0, if it has no messages. Also a message can't have 0 date. If you experience something like that, you can send TDLib logs with verbosity level 4 to @tdlib_bot for an investigation.
