### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#656]
1st, about method "SearchChatsOnServer". Only group members can get group chat id by group name. If I only know the group name or group link, how can I get its chat Id or group id ,and how to join it . Are there  any Apis to support these?
2nd, only group members can get the information about other members by "GetSupergroupMembers"?  I use it like this :+1: _client.Send(new TdApi.GetSupergroupMembers(groupId,null,0,200), _defaultHandler).  The argument "null" is setting value of filter, I don't know how to set, so I set "null".

**Comment by Pauya** [comment]
3rd,  how to register a new phone?

**Comment by Pauya** [comment]
Please...

**Comment by levlam** [comment]
Method `searchPublicChats` can be used to search private chats by their title and username.
Method `joinChat` can be used to join a chat by their ID.
Method `joinChatByInviteLink` can be used to join a chat by an invite link.
You can find documentation for these and many other methods in the Javadoc documentation and online in https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html.

In public supergroups member list is public.

User is registered if needed during authorization. See https://core.telegram.org/tdlib/getting-started#user-authorization for more details about user authorization.
