### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by SayedSadat** [tdlib/td#66]
Hi 
how i can change @type to exp ID or ( _ ) 

{"@type":"updateNotificationSettings","scope":{"@type":"notificationSettingsScopeChat","chat_id":467453887},"notification_settings":{"@type":"notificationSettings","mute_for":0,"sound":"default","show_preview":true}}
{"@type":"updateNewMessage","message":{"@type":"message","id":10,"sender_user_id":467453887,"chat_id":467453887,"is_outgoing":false,"can_be_edited":false,"can_be_forwarded":false,"can_be_deleted_only_for_self":true,"can_be_deleted_for_all_users":false,"is_channel_post":false,"contains_unread_mention":false,"date":1518282153,"edit_date":0,"reply_to_message_id":0,"ttl":0,"ttl_expires_in":0.000000,"via_bot_user_id":0,"author_signature":"","views":0,"media_album_id":"0","content":{"@type":"messageContactRegistered"}},"disable_notification":false,"contains_mention":false}
{"@type":"updateUserStatus","user_id":146089262,"status":{"@type":"userStatusOnline","expires":1518286785}}

for exp » {"_":"messageContactRegistered"}},"disable_notification":false,"contains_mention":false}

**Comment by levlam** [comment]
You can replace all occurrences of **@type** with whatever name you prefer in the source code:
sed -i'' 's/@type/_/g' td/generate/tl_json_converter.cpp td/telegram/td_json_client.h td/tl/tl_json.h
