### ISSUE TITLE
Problem on log out

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#665]
The app of C# example ran correctly. 
Then I built a winform program . When its app ran at first time. its AuthorizationState was

**Comment by Pauya** [comment]
The app of C# example ran correctly.
Then I built a winform program . When its app ran at first time. its AuthorizationState was AuthorizationStateReady. Then I wrote "_client.Send(new TdApi.LogOut(), _defaultHandler);" below the AuthorizationStateReady code, and execluted it again. Then I deleted the logot code, and  execluted it at the third time. Its AuthorizationState  was AuthorizationStateLoggingOut.  No matter how many times I execluted it, its AuthorizationState remained  AuthorizationStateLoggingOut.
What should I do to logout correctly.

**Comment by Pauya** [comment]
![1](https://user-images.githubusercontent.com/53131686/62925368-ccf03c00-bde4-11e9-83b0-cc245ed277e3.png)  Winform program by myself.
![2](https://user-images.githubusercontent.com/53131686/62925384-d24d8680-bde4-11e9-8f8d-af61cc8e303c.png)  C# example

**Comment by Pauya** [comment]
About this problem. It ran correctly on release version, but incorrectly on debug version .

**Comment by levlam** [comment]
Фку you sure that your proxy works?

**Comment by Pauya** [comment]
Yes. The proxy worked.
The program worked well on release , but bad on debug.
![11](https://user-images.githubusercontent.com/53131686/62988651-adeeba00-be77-11e9-8be4-9caa660596fc.png)
This is release version.  
![1](https://user-images.githubusercontent.com/53131686/62988728-f6a67300-be77-11e9-9d42-ae2f4b81dd7f.png)
This is debug vesion.

**Comment by Pauya** [comment]
On release version , tdlib required phone number but not code each time, while I sent the phone number. 
I searched in logs. I found "Too Many Requests: retry after 85684",

**Comment by levlam** [comment]
@Pauya The log tells opposite, i.e. that TDLib can't log out, because it can't connect to Telegram through the specified proxy. This can't depend on Release or Debug build if they are initialized with the same database directory.

**Comment by DUONGCHIBINH** [comment]
![image](https://user-images.githubusercontent.com/32316237/228773188-6c977c12-0f5e-41d2-bb68-752826e07a62.png)
Try to rename parameters.DatabaseDirectory.
