### ISSUE TITLE
[QUESTION] TDLib local storage

### ISSUE THREAD

**Issue by chairus** [tdlib/td#667]
@levlam I was just wondering if we can set the amount of data that TDLib caches/stores before it starts deleting old data? If yes, would you be able to point me on where I can do that? I know that we can enable the storage optimizer through the `tdlibParameters` or through TDLib options(`use_storage_optimizer`) which will delete "old" data automatically, but the Docs doesn't mention how big the data is before TDLib starts removing stuff. Reading from the C++ source code I think TDLib schedule its own GC to remove stuff everyday or at least GC runs with a day of interval. Is that right?

Thanks

**Comment by levlam** [comment]
@chairus Yes, GC is automatially run once a day using default parameters, which can be found [there](https://github.com/tdlib/td/blob/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/td/telegram/files/FileGcParameters.cpp#L24) and not after some limit expires. If you need more strict control over the storage, you can from time to time use `getStorageStatisticsFast` to quickly get size of TDLib's cache and run the method `optimizeStorage` if needed.

**Comment by chairus** [comment]
@levlam Thanks!

**Comment by jawhien** [comment]
Hello. I don't quite understand what I'm doing wrong. I'm sending the following command:
{'@type': 'optimizeStorage', 'ttl': 180, 'count': -1, 'immunity_delay': -1, 'size': 104857600}
But this does not result in the storage being released within the 100 mb limit.
Please tell me what I am doing wrong.

**Comment by levlam** [comment]
@jawhien 
Likely, the files were created within the last hour and are protected by default *immunity_delay*.

**Comment by jawhien** [comment]
@levlam 
Thank you, probably so.
Do I understand correctly that the size is not strictly considered? If the time limit has expired, the storage can be completely cleared, even though the size is not 0?
Can you tell me where I can find the current list of parameters and their default values?
Thank you!

**Comment by levlam** [comment]
@jawhien You would better pass all values explicitly to `optimizeStorage` if you want specific behavior, for example, set `immunity_delay` to 180 in your case.

**Comment by jawhien** [comment]
@levlam 
Thanks, it works, but the storage is completely cleared in this case, even if I set size.

**Comment by levlam** [comment]
@jawhien That's because you also passed `ttl`= 180, which means that all files older than 180 seconds can be safely deleted.

**Comment by jawhien** [comment]
@levlam
Thank you. 
I also wanted to know what the default values are for these settings, and how I can change them.
What TTL should I set so that the optimization only deletes files when the storage exceeds the specified size?
I searched for this information in the documentation, but I could not find it.

**Comment by levlam** [comment]
The default value for `size` is 100 megabytes, for `ttl` it is 23 hours, for `count` it is 40000, and for `immunity_delay` it is 3600, but they are subject to change without notice, therefore it is recommended to pass specific values.

Too clear anything beyond specific size you need to pass that size as `size`, a very big number as `ttl` and `count`, and 0 as `immunity_delay`.
