### ISSUE TITLE
How to start a secret chat with known user id?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#669]
According to https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_secret_chat.html this method does not really create a chat. How should this work as being the active side (I know we can already handle incoming secret chats)?

**Comment by c0re100** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_new_secret_chat.html
How about this one?

**Comment by Flohack74** [comment]
Dang you are right. so only question remains, how to determine if I already have a secret chat active with a user? I want to make a openorcreate workflow, so that I reuse an existing one.

**Comment by c0re100** [comment]
> Dang you are right. so only question remains, how to determine if I already have a secret chat active with a user? I want to make a openorcreate workflow, so that I reuse an existing one.

You may need use `getChats` method to get all chat id, after that, just loop `getChat` method and check chat type(secret chat).

ref: 
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat.html
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1chat_type_secret.html

**Comment by Flohack74** [comment]
Ok so assuming (I know @levlam doesnt like it but thats how we do it for the moment ;)) if we have a getChats on startup that will pull all chats into our chatlist model, and later on chats that are added or removed are tracked with updates, we can simply loop through our chat list model to see if the user has an active secret chat.

**Comment by levlam** [comment]
@Flohack74 Yes.

**Comment by Flohack74** [comment]
Ok but the method is now a bit complex, see https://gitlab.com/ubports/apps/teleports/blob/add-userlistpage/libs/qtdlib/chat/qtdchatlistmodel.cpp#L59 - Could we have the same convenience method as we have for private chats, so that it will returnan existing secret chat or create a new one if not found?

**Comment by levlam** [comment]
@Flohack74 No, because there can be a lot of secret chats with the same person from different devices.

**Comment by Flohack74** [comment]
Oh ok thats true. So my idea: Click on user in contact list, open first secret chat found is maybe not the best one ;)

**Comment by levlam** [comment]
@Flohack74 This behavior can be convenient sometimes, but there should be a way to create another secret chat with the same person. The app also needs to expect any number of secret chats with the same person.

**Comment by levlam** [comment]
@Flohack74 This behavior can be convenient sometimes, but there should be a way to create another secret chat with the same person. The app also needs to expect any number of secret chats with the same person.

**Comment by Flohack74** [comment]
Yeah I see. Yes we already handle multiple secret chats, its just about the creation thingie. BTW updating to tdlib 1.4 now ^^
