### ISSUE TITLE
parseTextEntities with url containing underscore

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#672]
I'm trying to prepare input message with markdown syntax using `parseTextEntities`, however I got:

```
[ 3][t 4][1566218504.362097025][Td.cpp:3392][#1][!Td][&td_requests]	Receive static request: parseTextEntities {
  text = "_lal_ http://www.ru/here_url"
  parse_mode = textParseModeMarkdown {
  }
}
[ 3][t 4][1566218504.362136602][Td.cpp:3399][#1][!Td][&td_requests]	Sending result for static request: error {
  code = 400
  message = "Can't parse entities: Can't find end of the entity starting at byte offset 24"
}
```

That is simple because of `_` containing in url.  Should not `textParseEntities` handle such urls and return corresponding `textEntity` of `textEntityTypeUrl` type?

Or this is must be done by client application somehow?

Thanks

**Comment by levlam** [comment]
The method `parseTextEntites` is supposed to be used by bots with a machine-generated formatting. The suggested behavior can't be formalized, so it would be impossible to correctly use it by bots. The behavior is acceptable and is better for GUI application, where a user can fix a possible algorithm mistake even after the message was sent, but not for automatic usage.

TDLib currently has no method to handle possibly incorrect markdown formatting provided by users, so this needs to be handled application-side. Most Telegram clients also allows WYSIWIG way to create formatted entities, so application-side support of formatting parsing seems to be unavoidable. But application can use the method `getTextEntities` to detect URLs in the text.
