### ISSUE TITLE
tdlib upgrade, db migration?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#673]
Just wanted to know if there is any db migration which makes tdlib 1.4 incompatible with 1.3. This is important for our testers who mostly test with their productive devices. If they cannot step back to our stable release they need to know.

**Comment by levlam** [comment]
Almost every change in TDLib is only backward compatible and is not forward compatible, You can always update TDLib to newer version, but you can't downgrade it without manual database deletion and full relogin.

**Comment by Flohack74** [comment]
Ok understood. We just tried it and already hit `static_cast<int32>(Version::Next)]  Wrong version 19` lol
