### ISSUE TITLE
security vulnerability on phone searching

### ISSUE THREAD

**Issue by jackyko1991** [tdlib/td#674]
As described by LIHKG [post](https://lihkg.com/thread/1497612/page/1)

one may input all the city's phone number to contact list, telegram will automatically map them:

![alt text](https://i.lihkg.com/540/https://na.cx/i/Q19n3N6.jpg "Insert all combination of numbers to phone contact list")

![alt text](https://i.lihkg.com/540/https://na.cx/i/jPkyq2d.jpg "This will add to the TG contact list automatically")

The user's phone number will be displayed in group member's info
![alt text](https://i.lihkg.com/540/https://na.cx/i/nSJDCax.jpg "The user's phone number will be displayed in group member's info")

One may map the phone number and chat info with API services. That's an easy task for any unversity level developers.

Currently there is no way of security setting to solve the problem but only deleting the account. I hope that TG will figure out a way to hide personal information espeically phone number.

**Comment by christszchingwong** [comment]
it is a matter of life and death to local people, please help.
