### ISSUE TITLE
Unable to send message using proxy？

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#675]
I am using a proxy, I can log in, but sending a message will fail, return 401
 `` client.send(newTdApi.AddProxy("13.70.1.109",8080,true,newTdApi.ProxyTypeSocks5("onessr","free")),defaultHandler);``

**Comment by levlam** [comment]
Are you sure that your account wasn't banned?

**Comment by huang-ju** [comment]
@levlam  I can use Shadowsocks to send message,not banned.

**Comment by levlam** [comment]
401 can be returned only for unauthorized accounts. So, there are only these possibilities:
- You aren't authorized yet.
- You already logged out.
- The account was banned and logged out by the server.
- You receive not error 401.

Could you collect TDLib log with verbosity level 4 and send it to @tdlibbot to find the exact reason?

**Comment by huang-ju** [comment]
@levlam  The account was banned and logged out by the server.
