### ISSUE TITLE
How to join a supergroup by its name/title?

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#677]
If a supergroup's name/title is known, but my account is not a member of it. And it is not in my chat list .
How can I get its chat id, and join it?
I have used the methods like "searchChats" ,"searchPublicChats ","searchChatsOnServer","searchContacts " to try to get the supergroup's chat id by its name/title, but searched nothing.

**Comment by levlam** [comment]
You can find only public chats by their title. The only method that can return public chats by their title is `searchPublicChats`:
```
Searches public chats by looking for specified query in their username and title.
Currently only private chats, supergroups and channels can be public.
Returns a meaningful number of results. Returns nothing if the length
of the searched username prefix is less than 5.
Excludes private chats with contacts and chats from the chat list from the results.
```

If the chat isn't found, then it can't be found by its title and you need to know it's username to join.
If the chat is not public, then you clearly can't find it by its name and need invite link to join it.
