### ISSUE TITLE
searchChatMembers more than 200 users

### ISSUE THREAD

**Issue by pblackbird** [tdlib/td#679]
Hello. I want to get more than 200 users from searchChatMembers response.
Is there something like offset?

**Comment by levlam** [comment]
You need to use `getSupergroupMembers` instead.

**Comment by pblackbird** [comment]
> You need to use `getSupergroupMembers` instead.

With filter supergroupMembersFilterSearch, right?

**Comment by pblackbird** [comment]
But I don't get members more than 200 per search(
I want to get all members using searching by every writable ascii letter, but I cant get more than 200 results per letter(

What should I do?

**Comment by isopen** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_supergroup_members.html
`std::int32_t | limit_ The maximum number of users be returned; up to 200.`

**Comment by levlam** [comment]
@pblackbird First of al,l you shouldn't abuse members search. You are supposed to be able to get up to 10000 members in supergroups and 200 members in channels using `supergroupMembersFilterRecent` and an appropriate `offset` for the method `getSupergroupMembers`.
