### ISSUE TITLE
problem with handle updates

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#680]
sometimes my app "skipping" and don't handle updates. (but they save to tdlib, i'm sure).
Does have any way to 100% getting all updates?

**Comment by Flohack74** [comment]
Can we see your code, its hard to comment just on that remark. On TELEports we do not see any skipping of updates. In fact, we seem to receive all updates, even if we are doing a lot of blocking UI work in Qt/QML.

**Comment by isopen** [comment]
Try to include logging in a file that is implemented in TDLib and monitor responses to requests in the file.

**Comment by levlam** [comment]
@merlinkory What exactly do you mean by "skipping" updates?

**Comment by pk0580** [comment]
He means that if, for example, we insert sleep(1) between calls client->receive(), client->receive() can skip some updates

**Comment by pk0580** [comment]
It seems like the error is somewhere in our code. Thanks for trying to help. The topic is closed.

**Comment by pk0580** [comment]
Excuse me, it's too early to close the topic. We found that the updates are lost when client->query is called between calls of client->recieve . How to avoid this?

**Comment by levlam** [comment]
@pk0580 If the logs show that all updates were obtained, then where and which updates are lost?

**Comment by pk0580** [comment]
I don't know. There is an update in the logs, but I can’t get it using client->receive.

**Comment by isopen** [comment]
Maybe this is a different context?
