### ISSUE TITLE
TDLib：On Multimedia Files in Chats

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#681]
How can I get the multimedia files sent by members in the chats, including but not limited to video and audio? I consulted the API documentation, but I did not find updates and pushes for multimedia files in the update type. How do I handle this information? I hope I can get your help.Please forgive me for my poor English. @levlam

**Comment by Flohack74** [comment]
You can take a look how we solved this in our implementation. First you need the objects for various files: https://gitlab.com/ubports/apps/teleports/tree/master/libs/qtdlib/files and then, you also need the various content types as objects, which could look like this: https://gitlab.com/ubports/apps/teleports/tree/master/libs/qtdlib/messages/content
Then, when you receive a message content of a certain type, you can decode the file in it and see if it has been already downloaded. If not, request the download. When its finished, you can extract a path to the local file.

**Comment by AquariusHunters** [comment]
@Flohack74 Sorry, I understand that I should differentiate between different multimedia files, but I don't quite understand what you mean. I tried to download the links you sent to get your code resources, but it seems that I downloaded other error files?

**Comment by Flohack74** [comment]
Can we have a look at your code? Do you have it online somewhere?

**Comment by AquariusHunters** [comment]
@Flohack74 I didn't upload the information of this project on the Internet. I intend to get the multimedia content pushed by the server through the Update class of API provided. But I didn't find the relevant method. I only found that updatefile can get the processing of picture information. I mean how I should use it. To get chat about multimedia resources and display and play them?

**Comment by Flohack74** [comment]
You get an update about a new message, this does not contain all the multimedia content, that would be much too big.
Instead, when you receive `updateNewMessage `you need to look into the content field. From this field you will know what is the content of this message.
If it is a multimedia file you need to request the download. It will not be automatically downloaded.
See https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_message_content.html for content types.
If for example the content is `messageAudio` type, there is a field inside called `audio`, which has all the metadata about the audio file, and then a field called `file `which will you allow to request download.

**Comment by AquariusHunters** [comment]
Aha, I seem to understand what you mean. You mean that all messages will be pushed to the client through the updatenewmessage method, but it only contains text-type information. Others, such as video, audio and pictures, will include his information in object_ptr<MessageContent>. I need a root. According to this prompt, download these resources or do you want to do the next step?

**Comment by AquariusHunters** [comment]
Aha, I seem to understand what you mean. You mean that all messages will be pushed to the client through the updatenewmessage method, but it only contains text-type information. Others, such as video, audio and pictures, will include his information in object_ptr<MessageContent>. I need a root. According to this prompt, download these resources or do you want to do the next step? @Flohack74

**Comment by Flohack74** [comment]
You seem to understand correctly :) but I dont understand your last question.

**Comment by AquariusHunters** [comment]
Sorry to bother you again. I solved the problem of receiving chat messages according to updatemessage, but I encountered another problem. About coding. They give me feedback that when I use Chinese, I will show error. I see in my log that the string contains Unicode_ XXX data. When I use UTF-8 to convert to GBK, it will scramble. How can I deal with this problem? And it's not limited to Chinese, like the following	{
						"@type" : "inlineKeyboardButton",
						"text" : "\u2795\u041f\u0415\u0420\u0415\u0419\u0422\u0418 \u041d\u0410 \u041a\u0410\u041d\u0410\u041b\u2795 ",
						"type" : 
						{
							"@type" : "inlineKeyboardButtonTypeUrl",
							"url" : "https://t.me/joinchat/AAAAAELWzTrlgDfaVKxBGg"
						}
					} @Flohack74 I think I probably need your help. Trouble you.
