### ISSUE TITLE
TDlib：{"@type":"error","code":429,"message":"Too Many Requests: retry after 86400"}

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#682]
When I got this after using TDLib for a while,

{"@type":"error","code":429,"message":"Too Many Requests: retry after 86400"} 

I wanted to know under what circumstances I would get this reply. When I tested login logout, I couldn't use tdlib again after a while. @levlam

**Comment by Flohack74** [comment]
You got a FLOOD_WAIT error which is a protection on the Telegram servers against too many API requests and also against hacking attempts. Also too many registrations of devices in a short time can lead to this.

You might want to use the test data center where this normally does not happen. There is a flag in tdlib to switch to the test system, especially this is useful when doing initial wok with authentication / authorization.

Try to set `{ "use_test_dc", true }` in your Auth params object.

In your case unfortunately, you are now locked for a whole day (86400 seconds).

**Comment by AquariusHunters** [comment]
I set this up, and used the default ID and hash,

Parameters["use_test_dc"] = true;
Parameters["api_id"] = 94575;
Parameters["api_hash"] = "a3406de8d171bb422bb6ddf3bbd800e2";

 but this happened too. Sometimes this error occurred on this account, but sometimes it happened on all accounts logged in through my computer. However, when I changed the device, he stopped prompting for the error.						
I was puzzled by the situation. I didn't know what I had done to make it happen.

**Comment by Flohack74** [comment]
maybe @levlam can explain further when this will happen. Usually you have just done too many requests, maybe your code has a loop and fired lots of requests until it locked you out?

**Comment by isopen** [comment]
Test benches can behave unpredictably. Probably because the test.

**Comment by levlam** [comment]
@AquariusHunters Flood controls on log in attempts is very tight to mitigate possibility of authentication code brute-forcing. You have exceeded on of them and need to wait for 1 day now to be able to log in.

**Comment by mib32** [comment]
@levlam What about `searchPublicChat` function, it also looks it is quite tight on flood. Do you know what is exact limitations, and is it possible to avoid them? I am making a big catalog of public chats.

**Comment by levlam** [comment]
@mib32 Now it is limited to 200 requests per day. There is no way to increase the limit.

**Comment by Flohack74** [comment]
No offense @mib32 but Telegram is a tool for communication and not a search engine. I also doubt that a full list of public groups will be useful for anything else than spamming. In our team´s public groups we constantly have to remove crypto-spammer these days.
So whatever you do, please do not publish this list to make life so much easier for them. Or do you plan yourself to use it for spamming others? That´s not advisable.

**Comment by mib32** [comment]
@Flohack74 Don't worry, I have of course no intention of spamming the groups, neither I want to transfer that information to the others.

**Comment by isopen** [comment]
I am ready to use Telegram as a search engine.

**Comment by isopen** [comment]
@levlam Ready to use Telegram as a search engine

**Comment by isopen** [comment]
@levlam Ready to use TDLib as a search engine

**Comment by isopen** [comment]
@levlam Ready to use `TDLib` as a search engine

**Comment by chairus** [comment]
While we're on the subject of rate limiting API requests, is there a documentation of what are the rate limits per API endpoint or is 200 a universal limit?

**Comment by levlam** [comment]
@chairus A Telegram client must not assume any particular request limits, because they can change any time without notice. That's why the limits are documented nowhere. But you can be sure that they are always chosen in a such way that an ordinary user never exceeds them, so request can always be sent to Telegram servers and an error 429 is handled very rarely.

**Comment by stanleyG123** [comment]
@levlam   I'm monitoring a channel for new messages and polling in a loop every 1 second using (GetChatHistory API ) . Say I want to monitor 20 channels , we're already looking at 20 requests / second or 1200 per minute . Is this enough to get me rate limited?

**Comment by levlam** [comment]
@stanleyG123 Sure thing. You will not be able to monitor even 2 channels in that way.

**Comment by stanleyG123** [comment]
@levlam  Could you recommend a better way of subscribing and getting updates from a channel?

**Comment by levlam** [comment]
@stanleyG123 See https://github.com/tdlib/td/issues/348#issuecomment-417448366 and other answers from the issue. In short, you can use `openChat`, but you still may be rate-limited if you use it for more than one chat simultaneously.

**Comment by stanleyG123** [comment]
@levlam I have 20 channels and I want to notify my user each time a new message arrives. Are you saying the only way to do it is to call openChat on each channel round robin in a single thread?  And fewer than 200 per minute?

**Comment by levlam** [comment]
@stanleyG123 If the user is subscribed to all the channels and is online, then it will receive all the messages automatically with a small delay. There is no way in the API to speed this up for more than one chat without hitting rate limits.

**Comment by stanleyG123** [comment]
@levlam
This is a program receiving messages and sticking them in a db , not a person with a phone. How does it receive by using the API ?

**Comment by levlam** [comment]
@stanleyG123 I've answered this question in the previous comment. For API there is no difference between a "program" and a "person".

**Comment by stanleyG123** [comment]
@levlan So how do I use the API to receive channel updates without hitting the rate limit?

**Comment by levlam** [comment]
@stanleyG123 Users automatically receive messages from chats, in which they are members, and don't receive updates from millions of other chats. You just need to handle the update `updateNewMessage` to receive messages from your chats.

**Comment by stanleyG123** [comment]
Thanks !! It was me not understanding Telegram and how to handle updates correctly !!!

https://core.telegram.org/tdlib/getting-started#handling-updates

is all I needed.

**Comment by anonym24** [comment]
is this seconds, milliseconds or what?

**Comment by AYMENJD** [comment]
Seconds.
