### ISSUE TITLE
Does TDLib code have graph depth and width graph traversal algorithms?

### ISSUE THREAD

**Issue by isopen** [tdlib/td#683]
@levlam If there is, then show where it is used in the TDLib code. Any implementation of graph traversal algorithms in TDLib. Need with minimal complexity O.

**Comment by levlam** [comment]
There is depth first search on API TL-scheme: https://github.com/tdlib/td/blob/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/tdtl/td/tl/tl_generate.cpp#L426.

**Comment by isopen** [comment]
thank for your reply
