### ISSUE TITLE
Forward origin - invalid user

### ISSUE THREAD

**Issue by mib32** [tdlib/td#685]
Hello! I receive a Message, that is forwarded message, and it has this forward_info:

```
{
  '@type': 'messageForwardInfo',
  origin: {
    '@type': 'messageForwardOriginChannel',
    chat_id: -10011xxxx2142,
    message_id: 990xxx320,
    author_signature: ''
  },
  date: 1567176325,
  from_chat_id: 0,
  from_message_id: 0
}
```

I want to get the history of the channel it was forwarded from. But I cannot - I use getChatHistory with the parameter from origin info (chat_id: -10011xxxx2142) and it says 'Chat not found'. 

Even if I use getMessage with the parameters from origin info (message_id and chat_id) - it says that the Chat is not found.

Is it possible to do it somehow?

Thank you very much for you work on the lib.

**Comment by levlam** [comment]
The error "Chat not found" can be received for `getChatHistory`, only if the user have never seen the chat after it was logged in if the message database is used, or after the client was launched if the message database is disabled. In the second case you need to ensure that you don't restart TDLib between receiving chat_id and trying to use it. 

You will also need to ensure that you have access to the channel you want to get messages from, because it could be private.

**Comment by mib32** [comment]
@levlam Thanks! All clear. 

Am I understanding correctly, that means that if I:
1. I just turned on the client
2. I have only the chat_id like '-10011xxxx2142' - let's say from paper on my desk
then there is no way to receive the chat history from the channel?

**Comment by levlam** [comment]
Yes, this is true.

**Comment by mib32** [comment]
@levlam So, how I do this now is like this:
I just started the client, without using message database. 
I know `username` of the channel, and `chat_id` of the channel, and I want to get the history - so I am calling "searchPublicChat(username)" and then call `getChatHistory(chat_id)`.

How do you think, is this the most simple way to do it? Or is it other methods than `searchPublicChat` to "see" the chat?  I think it's totally fine to do it like that, but I find that there is pretty harsh Rate Limit on searchPublicChat method, so I cannot really call it frequently :(

**Comment by levlam** [comment]
The best way is to enable message database, call `searchPublicChat` once and then just always use the chat by the `chat_id`.
