### ISSUE TITLE
getRecentInlineBots returns empty list

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#686]
I have started using `getInlineQueryResults` with decent success, it does return results from the bots.  However `getRecentInlineBots` always returns empty list even if `getInlineQueryResults` is heavily in use

Is there something tricky I should do (such as notifying bot that some result is selected by user or so) to make `getRecentInlineBots` returning list of recently used inline bots?

Thanks

**Comment by levlam** [comment]
Bots are added to result of the method `getRecentInlineBots` when a message is sent via the bot using the method `sendInlineQueryResultMessage`. This list of bots is local and is updated only when a new message is sent. Alternatively, you can get a server-side list of frequently used bots using the method `getTopChats` with `topChatCategoryInlineBots`.

**Comment by zevlg** [comment]
Ah, there is `sendInlineQueryResultMessage` exists!  I've been crafting input message to send to chat by hand using inline query result from bot answer.

Thanks
