### ISSUE TITLE
How to join a public supergroup?

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#688]
I created a public supergroup, and generated a link("t.me/username",not invite link).
I used a other account to join it by brower, and it worked well. By programming way, how to join it by the public link, which method should I invoke?.

**Comment by Pauya** [comment]
Usually, I could get the public supergroup's share link or exact title only, from other members.
Via method "searchPublicChats" with param exact title, I want to get the exact chat id, but some other chat ids return to me. To find the exact  chat , I need to join all chats via  chat ids,and use "getChat" to get all chats, then compare the chats' titles to the exact title. It's so complex.

**Comment by c0re100** [comment]
You can use `searchPublicChat` method, it will return 1 result only.

**Comment by Pauya** [comment]
> You can use `searchPublicChat` method, it will return 1 result only.

But it can search via username only. Sometimes, I could not know  the supergroup's username, but only title.

**Comment by levlam** [comment]
@Pauya You can find a chat by its username using the method `searchPublicChat`. You can find a public chat by a title only through `searchPublicChats`, but some chats can't be found through that method. Also, there can be millions chats with the same title, so what you are asking for is not possible.
