### ISSUE TITLE
[Missing] Scheduled messages/reminders

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#689]
Blog: https://telegram.org/blog/scheduled-reminders-themes

**Comment by isopen** [comment]
@levlam Yes it's a cool feature. Urgent need to do.

**Comment by hrw** [comment]
issue closed == no plans for implementing?

**Comment by levlam** [comment]
@hrw The issue is not closed yet. Between, the support is already available in the latest version from the master branch.

**Comment by hrw** [comment]
Sorry, had to miss that. Thanks for adding.

**Comment by MattNguyen** [comment]
@levlam I'm using tdweb and getting the following error when sending a scheduled message:

```
{"@type":"error","code":400,"message":"Failed to parse JSON object as TDLib request: Can't parse \"1580276593452\" as number"}
```

We built from master on Jan 10, and I see a bunch of updates have been made. However I haven't seen anything that would have addressed this issue.

**Comment by levlam** [comment]
@MattNguyen This is not a valid int or a Unix Timestamp. The correct time would be 1580276593.

**Comment by MattNguyen** [comment]
Doh 🤦‍♂️sorry! Thanks for your help!

**Comment by levlam** [comment]
Support for scheduled message was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
