### ISSUE TITLE
Error 400 can’t find field “@type”

### ISSUE THREAD

**Issue by MilleniumFalconer** [tdlib/td#692]
Hi, I am trying to send message to user, by bot authentification. I use php extension php-yaroslavche-tdlib. But, when I run query, I get error 400 can’t find field “@type”

**Comment by levlam** [comment]
Please send the whole request you are trying to send.

**Comment by MilleniumFalconer** [comment]
$text_entity_type = ['@type' => 'textEntityTypeBotCommand'];
            $entities = ['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type];
            $formatted_text = ['text' => 'hi', 'entities' => $entities];
            $input_message = ['formattedText' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
            $query = json_encode(['@type' => 'sendMessage', 'chat_id' => '111111', 'reply_to_message_id' => '0', 'disable_notification' => false, 'from_background' => false, 'reply_markup' => null, 'input_message_content' => $input_message]);
            td_json_client_send($client, $query);

**Comment by levlam** [comment]
$input_message has no `@type` field.

**Comment by MilleniumFalconer** [comment]
but in documentation there is no “@type” in input_message_text

**Comment by MilleniumFalconer** [comment]
This must be like that: $input_message = [‘@type’=>’InputMessageText’.....]?

**Comment by levlam** [comment]
It must be [‘@type’=>’inputMessageText’.....]. You must specify the exact type, because `InputMesssageContent` can be of different types.

**Comment by MilleniumFalconer** [comment]
After that it sends me error: Message text can’t be empty

**Comment by MilleniumFalconer** [comment]
Maybe i set come parameters wrong? Now it look like this:             
$text_entity_type = ['@type' => 'textEntityTypeBotCommand'];
            $entities = ['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type];
            $formatted_text = ['text' => 'hi', 'entities' => $entities];
            $input_message = ['@type' => 'inputMessageText', 'FormattedText' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
            $query = json_encode(['@type' => 'sendMessage', 'chat_id' => '111', 'reply_to_message_id' => '0', 'disable_notification' => false, 'from_background' => false, 'reply_markup' => null, 'input_message_content' => $input_message]);
            td_json_client_send($client, $query);

**Comment by levlam** [comment]
@MilleniumFalconer  The field 'entities' needs to be an array of TextEntity, not a single entity.

Between, you can't manually specify entites of type `textEntityTypeBotCommand`, they are always found automatically.

**Comment by MilleniumFalconer** [comment]
So how I can do it?

**Comment by levlam** [comment]
```
$entities[] = ['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type];
```

**Comment by MilleniumFalconer** [comment]
Could I use that: $entities = [[....]]

**Comment by levlam** [comment]
Sure you can.

**Comment by MilleniumFalconer** [comment]
And what I need to put in ‘@type’ in $text_entitity_type

**Comment by levlam** [comment]
Whatever you need. It is up to you, how the message text will be formatted.

**Comment by MilleniumFalconer** [comment]
now it look like that, but i have the same error:             $text_entity_type[] = ['@type' => 'textEntityTypeBotCommand'];
            $entities = ['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type];
            $formatted_text = ['text' => 'hi', 'entities' => $entities];
            $input_message = ['@type' => 'inputMessageText', 'text' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
            $query = json_encode(['@type' => 'sendMessage', 'chat_id' => '111', 'reply_to_message_id' => '0', 'disable_notification' => false, 'from_background' => false, 'reply_markup' => null, 'input_message_content' => $input_message]);
            td_json_client_send($client, $query);

**Comment by levlam** [comment]
```
$text_entity_type = ['@type' => 'textEntityTypeBotCommand'];
$entities[] = ['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type];
$formatted_text = ['text' => 'hi', 'entities' => $entities];
$input_message = ['@type' => 'inputMessageText', 'text' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
$query = json_encode(['@type' => 'sendMessage', 'chat_id' => '111', 'reply_to_message_id' => '0', 'disable_notification' => false, 'from_background' => false, 'reply_markup' => null, 'input_message_content' => $input_message]);
td_json_client_send($client, $query);
```

**Comment by MilleniumFalconer** [comment]
Now it is working, but it dont stop sending messages

**Comment by levlam** [comment]
Your code does exactly what you programmed it to do. It can't send the same message many times, unless you wrote exactly that.

**Comment by MilleniumFalconer** [comment]
Yeah, yo are right. Thanks for answering.
