### ISSUE TITLE
How to disable local database encryption?

### ISSUE THREAD

**Issue by aghasi** [tdlib/td#693]
How can i disable local database (SQLite) encryption? Can i do that without re-compiling TDLib source code?

**Comment by levlam** [comment]
It is not possible and will never be possible.

**Comment by aghasi** [comment]
hmm. i need to check something in DB, how can i decrypt that?

**Comment by levlam** [comment]
TDLib doesn't provide a way to do that.

**Comment by kfur** [comment]
@aghasi just replace `bool encrypt_binlog = !key.is_empty();` with `false` value in `TdDb::init` method.
