### ISSUE TITLE
Don't know what to do

### ISSUE THREAD

**Issue by MilleniumFalconer** [tdlib/td#696]
Hi, i am using php extension yaroslav-che. Trying to print 'new message' when i send new message to my bot, but it does not working.
Code: https://pastebin.com/fi6MCeNk
code print authorization is complete and then this one: https://pastebin.com/9Gc3UY4R
When i send message to bot, nothing changes

**Comment by levlam** [comment]
`updateNewMessage` рфы no field `last_message`.

**Comment by MilleniumFalconer** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_chat_last_message.html

**Comment by MilleniumFalconer** [comment]
There is

**Comment by MilleniumFalconer** [comment]
I meaned ChatLastMessage

**Comment by levlam** [comment]
Don't use `updateChatLastMessage`, you need `updateNewMessage`. Also see https://core.telegram.org/tdlib/getting-started.

**Comment by MilleniumFalconer** [comment]
make this one:
            if($update['message']['is_outgoing'] == false)
            {
                $text_entity_type = ['@type' => 'textEntityTypeBotCommand'];
                $entities = [['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type]];
                $formatted_text = ['text' => 'hi', 'entities' => $entities];
                $input_message = ['@type' => 'inputMessageText', 'text' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
                $query = json_encode(['@type' => 'sendMessage', 'chat_id' => '435322357', 'reply_to_message_id' => '0', 'disable_notification' => false, 'from_background' => false, 'reply_markup' => null, 'input_message_content' => $input_message]);
                td_json_client_send($client, $query);
            }
but nothing changes

**Comment by levlam** [comment]
You don't specified chat_id: `'chat_id' => ''`.

Between you should always receive an error which tells, what was done wrong. You can also find sent request in the TDLib's log.

**Comment by MilleniumFalconer** [comment]
I deleted it before posting here

**Comment by MilleniumFalconer** [comment]
I cant understand why messages are sending? I put 'is_outgoing' == false, not true

**Comment by MilleniumFalconer** [comment]
I run code and after some time messages start sending automatically, without my messages. And the compiler shows no errors

**Comment by levlam** [comment]
You can log all incoming updates to clearly see the reason.

**Comment by MilleniumFalconer** [comment]
There was error in my code. This is the solution: put 'is_outgoing' == fallse
