### ISSUE TITLE
sending contact leads to error 400

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#698]
First try to send a contact. I get an unsent message and this:
`[ 2][t 4][1568410626.113577366][MessagesManager.cpp:20297][#1][!net_actor][&error_code != 403]	Fail to send yet unsent message 351026.25 in chat 156359641 with the error [Error : 400 : MEDIA_EMPTY]`
However, there is of course no media field on the input message or on the contact. tdlib 1.4...

**Comment by Flohack74** [comment]
Ok I found the issue, but the error is misleading: The phone cannot be empty. So obviously we should block sending contacts without phone nos? :)

**Comment by levlam** [comment]
This is a server error message, which is the same for all kind of messages.

Sending contacts with empty phone number doesn't need to be allowed, but you still can't predict all cases when the server will return that error.
