### ISSUE TITLE
disable unwanted logs

### ISSUE THREAD

**Issue by korangu** [tdlib/td#70]
how to disable these logs? 
`[ 2][t 4][1518377013.505827904][MessagesManager.cpp:5518][!Td]  Found a gap in the chat -1001075686122 with pts = 1543315. new_pts = 1543317, pts_count = 1 in update from on_update_new_channel_message`
get only json?

**Comment by arseny30** [comment]
There are several functions to handle log:
https://core.telegram.org/tdlib/docs/td__log_8h.html

You need `td_set_log_verbosity_level(1)` or `td_set_log_verbosity_level(0)`
