### ISSUE TITLE
AUTH_KEY_DROP_DUPLICATE !

### ISSUE THREAD

**Issue by ByeCoder** [tdlib/td#701]
After some days I get this error!
What is the problem?and what thing causes this?
```(table)
 [type] = (string) AUTH_KEY_DROP_DUPLICATE
 [@type] = (string) updateServiceNotification
 [content] = (table)
  [@type] = (string) messageText
  [_] = (string) messageText
  [text] = (table)
   [_] = (string) formattedText
   [@type] = (string) formattedText
   [entities] = (table)
   [text] = (string) Authorization error. Use the "Log out" button to log out, then log in again with your phone number. We apologize for the inconvenience.

Note: Logging out will remove your Secret Chats. Use the "Cancel" button if you'd like to save some data from your secret chats before proceeding.
 [_] = (string) updateServiceNotification

**Comment by levlam** [comment]
The problem is that you copied TDLib database and launched two different instances simultaneously on the database and it's copy.

**Comment by ByeCoder** [comment]
@levlam if I destroy one of them, after that the another one will work?

**Comment by levlam** [comment]
No. You need to relogin again now.

**Comment by emilonpt** [comment]
I'm getting this error message on the Telegram Web Client. As far as I can tell I did nothing to cause it.

**Comment by levlam** [comment]
@emilonpt In which exactly client? There are a lot of them nowadays.

**Comment by emilonpt** [comment]
https://web.telegram.org/z/

It _might_ happen in https://web.telegram.org/k/, I'm unsure though (I tried switching but don't remember if this was after or before the errors started appearing.

Of note is that this seems to happen as well when I do not have any tab with the client open (I receive Windows 10 notifications with the mentioned error message).

Also of note is that there doesn't seem to be a log of the error message in any chat channel (including the official Telegram one).

**Comment by levlam** [comment]
@emilonpt This can be a bug of the client. You can report it at https://bugs.telegram.org specifying that it happened when you had no opened tabs.

**Comment by osevan** [comment]
I have telegram FOSS AND have the same issue
![Uploading Screenshot_20230714_211802.jpg…]()
