### ISSUE TITLE
Kotlin implementation

### ISSUE THREAD

**Issue by whyoleg** [tdlib/td#703]
Some time ago I've created [ktd](https://github.com/whyoleg/ktd/tree/develop) - Kotlin auto-generated bindings for tdlib. Now it's JVM only, but may be will make it multi-platform later.
It's now updated to latest(1.5.0) version.
Is it possible to add it to example implementations? If so, I will create PR

**Comment by levlam** [comment]
Sure. I can add it myself, but if you prefer to do a PR, don't forget to also add Kotlin to the list of languages in build instructions generator.

**Comment by isopen** [comment]
And why is there to bring the `TDLib` interface to the `Kotlin` level? In `Kotlin`, you can use ready-made `Java` bindings from @levlam. The fact is that in the past there was already an experience of switching to Kt at the level of the TDLib interface, but at least it is not convenient.

**Comment by whyoleg** [comment]
@isopen Now,`Kotlin` implementation use under the hood JNI as in java implementation in example, but it don't use any java specific concurrency classes, no locks or others. It uses `kotlinx.coroutines` and `suspend` functions, so it simple to use it ordinary kotlin applications. One more point in this bindings, that, it generate also extension functions for every TdFunction with documentation, so it is easier to use for simple cases. And last point, that in future, I will move this implementation to kotlin multi-platform, so: JVM - will use JNI as it is now, Native/iOS/linux/etc - will use c/c++ implementation and JS will use web. So it will be easy to integrate it in multi-platform projects which use telegram api (one of it, will be mine).

**Comment by isopen** [comment]
Great job. It will be interesting to look at the result.

@levlam Update the schema in the Java implementation.

**Comment by whyoleg** [comment]
@isopen You are wrong about `Kotlin` state, because `Kotlin`, yes it can run on JVM, but it also can be compiled in binary and used from iOS and f.e. app in C, and also can be transpiled to JS and run in browser. So, it's more then TS for JS, it's even more then just Koltin for Java. So it fully separate language like Ruby, Java, C# and many others. But the way how it's designed, give it big possibilities to interop with existing code in Java, JS and Native(C/C++). But it's not the discussion for this issue.

**Comment by isopen** [comment]
Most likely, this is not Kotlin's achievement, but great things like this http://www.xmlvm.org/overview/

**Comment by whyoleg** [comment]
@isopen You are wrong, one more time, I think, you don't know, how Kotlin works, and you just guess. It's almost fully kotlin achievement. Kotlin compiles to different platforms in different ways, so it don't compile to Java byte-code and then compile it to iOS or JS, or smth else. There is 3 different back-end compilers for kotlin: Kotlin/JVM, Kotlin/JS, Kotlin/Native. JVM - process kotlin and java files and generate byte-code. JS - process kotlin and js/ts files and generate js files as output. It can use JS/NPM libraries and also other kotlin/js or kotlin multi-platform libraries. Also for TS (and other type declaration frameworks) there is converter of type declarations to kotlin, called dukat. And for latest, Native - kotlin now uses internal IR and llvm for compiling it with other C/Obj-C/Swift libraries (C++ work in progress) into binaries. So, no containers, no external virtualization like in React for Android or anything else.
So, because of it, multi-platform kotlin bindings for tdlib is not so easy to implement. Or it need to somehow use JSON bindings on all platforms (even connecting it to different platforms differ), or it can be implemented as I had written in one of other comments.

**Comment by isopen** [comment]
These are all pretty cool add-ons over llvm.
https://kotlinlang.org/docs/tutorials/native/apple-framework.html
You can safely use Swift without loading the code with another language.

**Comment by g000sha256** [comment]
@whyoleg, if you are interested, I've created Kotlin Multiplatform [TDL Coroutines](https://github.com/g000sha256/tdl-coroutines)
