### ISSUE TITLE
Simplification of the mechanism for downloading media files

### ISSUE THREAD

**Issue by isopen** [tdlib/td#704]
Now this moment is not very global. I want a more global classification on the side of `TDApi`. Use as few handlers in the code as possible. For example, images.

**Comment by levlam** [comment]
In TDLib 1.4.0 the parameter `synchronous` was added to the method `downloadFile`. It is hard to imagine a simpler way to download a file.

**Comment by isopen** [comment]
Need to think.

**Comment by isopen** [comment]
Levsky, we have not yet come up with.
