### ISSUE TITLE
Why is updateNewMessage event delayed ?

### ISSUE THREAD

**Issue by ildarsaitkulov** [tdlib/td#705]
I've got updateNewMessage event, but message date is yesterday. How did this happen?
I thought only new messages returned by this event.
```
{
    "@type": "updateNewMessage",
    "message": {
      "@type": "message",
      "id": 2995781632,
      "sender_user_id": 0,
      "chat_id": -1001115291906,
      "is_outgoing": false,
      "can_be_edited": false,
      "can_be_forwarded": true,
      "can_be_deleted_only_for_self": false,
      "can_be_deleted_for_all_users": false,
      "is_channel_post": true,
      "contains_unread_mention": false,
      "date": 1568911644,//2019-09-19 19:47:24
      "edit_date": 0,
      "reply_to_message_id": 0,
      "ttl": 0,
      "ttl_expires_in": 0,
      "via_bot_user_id": 0,
      "author_signature": "",
      "views": 4266,
      "media_album_id": "0",
      "content": {
        "@type": "messageText",
        "text": {
          "@type": "formattedText",
          "text": "Из услышанного в лифте:\n\nГотовится награждение Михаила Федотова, советника президента РФ и председателя Совета по развитию гражданского общества и правам человека, которому вчера исполнилось 70 лет.",
          "entities": [
            {
              "@type": "textEntity",
              "offset": 47,
              "length": 16,
              "type": {
                "@type": "textEntityTypeBold"
              }
            }
          ]
        }
      }
    }
  }
```

**Comment by levlam** [comment]
This is a new message yet unknown to the client. There are a lot of possible reasons, why it wasn't received previously. For example, the client was offline for a day, or this is a message from a chat the user is not a member of.

**Comment by vinifr** [comment]
Hello. 

In some channels my tdlib application is not get new messages from updateNewMessage() until I open the telegram in my PC or cellular and click in the channel. Specially in olds groups with a lot of messages. 

What could be the problem?

**Comment by levlam** [comment]
Apps aren't supposed to receive all messages in supergorups and channels if the user doesn't use the app to read them.

**Comment by vinifr** [comment]
> Apps aren't supposed to receive all messages in supergorups and channels if the user doesn't use the app to read them.

By apps you mean the cellular telegram application ? My tdlib application is running 24h  and calling "process_response" to get new messages from groups or channels. 
process_response(client_manager_->receive(10));

Is there something I can do to never miss any messages in my tdlib application regarless if I click or not in the channel from telegram appl? Appreciate

**Comment by levlam** [comment]
Apps can hardly control this.

**Comment by vinifr** [comment]
> Apps can hardly control this.

Sorry, I dont know you what mean by apps. Is tdlib apps or the telegram app?

One more information. The channels I am having problems have 11369 members and the other have 67586 members. Is this a supergorups? Is the reason tdlib is not getting new messages?

**Comment by levlam** [comment]
> Sorry, I dont know what you mean by apps. Is tdlib apps or the telegram app?

Any Telegram app, whether they are based on TDLib or not.

**Comment by Travvy88** [comment]
Hey @vinifr, I faced the same problem. Also, getChatHistory don't see new messages too. Did you solve this problem?

**Comment by dzhendong** [comment]
scheduler.scheduleAtFixedRate(() ->
            client.send(new TdApi.GetChats(new TdApi.ChatListMain(), 100))
                .whenCompleteAsync((chats, error) -> {
                    if (error != null) {
                        System.err.println("获取聊天列表失败: " + error);
                    } else {
                        System.out.println("加载了 " + chats.chatIds.length + " 个聊天");

                        for (long chatId : chats.chatIds) {
                            client.send(new TdApi.GetChat(chatId));

                            // 打开聊天以确保活跃（尤其是频道）
                            client.send(new TdApi.OpenChat(chatId), result -> {
                                if (result.isError()) {
                                    System.err.println("打开聊天 " + chatId + " 失败: " + result.getError());
                                } else {
                                    System.out.println("聊天 " + chatId + " 已打开");
                                }
                            });
                        }
                    }
                }), 0, 30, TimeUnit.SECONDS);
