### ISSUE TITLE
Artifacts to check

### ISSUE THREAD

**Issue by isopen** [tdlib/td#709]
> [td/telegram/MessageEntity.cpp:1055]: (warning) Iterators to containers from different expressions 'mention' and 'text' are used together.
> [td/telegram/MessageEntity.cpp:1062]: (warning) Iterators to containers from different expressions 'bot_command' and 'text' are used together.
> [td/telegram/MessageEntity.cpp:1069]: (warning) Iterators to containers from different expressions 'hashtag' and 'text' are used together.
> [td/telegram/MessageEntity.cpp:1075]: (warning) Iterators to containers from different expressions 'cashtag' and 'text' are used together.
> [td/telegram/MessageEntity.cpp:1089]: (warning) Iterators to containers from different expressions 'url.first' and 'text' are used together.
> [td/telegram/Td.cpp:608] -> [td/telegram/Td.cpp:612] -> [td/telegram/Td.cpp:608]: (error) Returning object that points to local variable 'public_rsa_key' that will be invalid when returning.

**Comment by vidit-bhatia** [comment]
@isopen can you provide a little bit more information

**Comment by levlam** [comment]
@isopen Everything is fine in these places.

In MessageEntity.cpp all iterators point inside the same string, so this is a false positive.

In Td.cpp a pointer to a field is returned, not an object that points to a local variable, so this is a bug of the analyzer.

**Comment by isopen** [comment]
@levlam please check it yet.
> [parse-func.cpp:609]: (error) Memory leak: z
> [parse-func.cpp:1096]: (error) Memory leak: cur_source
