### ISSUE TITLE
How to get and display chat lists

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#710]
Now I have a confusing question. How can I get and display the user's chat list? I can only get a list ID of less than 100 through getchats. How can I get more than that number of chat lists? Is it based on UpdateNewChat? Or do I need to use getchats again to get the rest of the list based on the last order to get the chat based on the return value of getchats?

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats

**Comment by AquariusHunters** [comment]
I know this usage, but what I don't understand now is how I can get chat. order. Is the return value of getchats just chat. id, or can I still use the default offset_order= 2 ^ 63 - 1== 9223372036854775807 to continue getting the rest of the chat list? @levlam

**Comment by levlam** [comment]
See `updateNewChat` description in https://core.telegram.org/tdlib/getting-started#handling-updates. Also see [Java example](https://github.com/tdlib/td/blob/9293f07464276d58974164e41a4bb57d3362a258/example/java/org/drinkless/tdlib/example/Example.java#L235) and pay attention to places where `chatList` variable is changed.

**Comment by AquariusHunters** [comment]
I see this, but I wonder why I see in the log that the order returned by updateNewChat is always zero. Is it because newchatmessage and his chat. order are all in the first place on the list? @levlam

**Comment by levlam** [comment]
The order will be 0 until you call `getChat`. 0 means that position of the chat in the chat list is unknown.

**Comment by AquariusHunters** [comment]
You mean I have to use getchats to get the ID of the chatlist first, and then the TDLib server will updatenewChat order about these chats? Otherwise, the order Tdlib has been pushing is 0?

**Comment by AquariusHunters** [comment]
@levlam Thank you for your help. I think I've now figured out how to deal with this problem. Like Lego, he needs to find his own parts to piece together what you want.

**Comment by levlam** [comment]
You need to call `getChats` if you want to get more chats from the list of chats, You can ignore result of `getChats`, because all needed data has already been received from updates, and client needs to process updates anyway in order to maintain a correct chat list.

**Comment by AquariusHunters** [comment]
@levlam What can I do with bot? For example, can I use BOT to view information about users who use BOT to chat?

**Comment by levlam** [comment]
@AquariusHunters Bots can use only methods needed to implement Bot API, so they can't do much more than they can do through Bot API.
