### ISSUE TITLE
Error for build

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#712]
hello , when i wanna build telegram-bot with tdlib 1.5.0 i face this error :

Scanning dependencies of target telegram-bot
[ 98%] Building CXX object CMakeFiles/telegram-bot.dir/main.cpp.o
In file included from /root/tdbot/cliclient.hpp:20:0,
                 from /root/tdbot/main.cpp:20:
/root/tdbot/td/td/tl/tl_json.h:45:63: error: ‘to_json’ is not a member of ‘td::td_api’
 auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(jv, t)) {
                                                               ^
/root/tdbot/td/td/tl/tl_json.h:45:63: note: suggested alternative:
/root/tdbot/td/td/tl/tl_json.h:37:13: note:   ‘td::to_json’
 inline void to_json(JsonValueScope &jv, const JsonVectorInt64 &vec) {
             ^
/root/tdbot/td/td/tl/tl_json.h:45:63: error: ‘to_json’ is not a member of ‘td::td_api’
 auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(jv, t)) {
                                                               ^
/root/tdbot/td/td/tl/tl_json.h:45:63: note: suggested alternative:
/root/tdbot/td/td/tl/tl_json.h:37:13: note:   ‘td::to_json’
 inline void to_json(JsonValueScope &jv, const JsonVectorInt64 &vec) {
             ^
CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:162: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2

**Comment by Kia-Pashang** [comment]
I applyed the patch , but for building it's juts the same error ;

[ 98%] Building CXX object CMakeFiles/telegram-bot.dir/main.cpp.o
In file included from /root/tdbot/cliclient.hpp:20:0,
                 from /root/tdbot/main.cpp:21:
/root/tdbot/td/td/tl/tl_json.h:45:63: error: ‘to_json’ is not a member of ‘td::td_api’
 auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(j
                                                               ^
/root/tdbot/td/td/tl/tl_json.h:45:63: note: suggested alternative:
/root/tdbot/td/td/tl/tl_json.h:37:13: note:   ‘td::to_json’
 inline void to_json(JsonValueScope &jv, const JsonVectorInt64 &vec) {
             ^
/root/tdbot/td/td/tl/tl_json.h:45:63: error: ‘to_json’ is not a member of ‘td::td_api’
 auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(j
                                                               ^
/root/tdbot/td/td/tl/tl_json.h:45:63: note: suggested alternative:
/root/tdbot/td/td/tl/tl_json.h:37:13: note:   ‘td::to_json’
 inline void to_json(JsonValueScope &jv, const JsonVectorInt64 &vec) {
             ^
CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:162: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2

***********************************************************************
the following error i think it's about the to_json in td::td_api , it could be fixed by removing
template <class T>
auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(jv, t)) {
  return td_api::to_json(jv, t);
}
in tl_json.h ?

**Comment by levlam** [comment]
@Kia-Pashang No, the patch was not applied.

Between, fixing compilation errors by removing a code that triggers them usually is the worst possible strategy.

**Comment by Kia-Pashang** [comment]
@levlam You were right , i didn't apply the patch correctly.
finally i built telegram-bot with your help , thank you so much  ❤
