### ISSUE TITLE
How to resolve sending state is messageSendingStateFailed

### ISSUE THREAD

**Issue by masjaya19** [tdlib/td#713]
Halo, 
I was created API telegram use tdlib C# and I have a problem,
in IIS express, I have log error like below and I checked on my telegram the message does not come. I need your help and advice.

sending_state = **messageSendingStateFailed** {
    }
    is_outgoing = true
    can_be_edited = false
    can_be_forwarded = true
    can_be_deleted_only_for_self = true
    can_be_deleted_for_all_users = false
    is_channel_post = false
    contains_unread_mention = false
    date = 1569924307
    edit_date = 0
    forward_info = null
    reply_to_message_id = 0
    ttl = 0
    ttl_expires_in = 0.000000
    via_bot_user_id = 0
    author_signature = ""
    views = 0
    media_album_id = 0
    content = messageText {
      text = formattedText {
        text = "0xxxxxxxxx"
        entities = vector[0] {
        }
      }
      web_page = null
    }
    reply_markup = null
  }
  order = 0
  is_pinned = true
  can_be_reported = true
  unread_count = 104
  last_read_inbox_message_id = 20116930560
  last_read_outbox_message_id = 20351811584
  unread_mention_count = 0
  notification_settings = notificationSettings {
    mute_for = 577559334
    sound = "default"
    show_preview = true
  }
  reply_markup_message_id = 0
  draft_message = null
  client_data = ""
}

**Comment by levlam** [comment]
The message has failed to send, so something is wrong. You need to update to TDLib 1.5.0 to have the exact error in `messageSendingStateFailed` or process `updateMessageSendFailed`, which also contains the exact error message.

**Comment by masjaya19** [comment]
Halo @levlam 

thanks for the information, right now I found the root cause, the error code is 406 with Error Message is AUTH_KEY_DUPLICATED, what that's mean and what the next step for fixing it?

thanks

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/701#issuecomment-532656371.
