### ISSUE TITLE
How to update current UserStatus

### ISSUE THREAD

**Issue by digabriel** [tdlib/td#714]
I'm building an Android client using the prebuilt Java version of TdLib. Is there a way of setting the current user status to online/offline?

What I need to do is to set the UserStatus to online when the user opens the app and then offline when he leaves.

I didn't find any Function that does this.

Thanks!

**Comment by levlam** [comment]
You need to use `TdApi.SetOption` method with the option "online". See https://core.telegram.org/tdlib/options for the list of other useful options.
