### ISSUE TITLE
Too many requests are same

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#715]
Hello , i'm using tdlib for telegram-bot but i have a big problem and it's :

There is no difference between **LIMITATIONS FOR ALL CHATS (Forward or Send Message To All Chats)** and **LIMITATION FOR ONE CHAT (Slow Mode For Supergroups)** , both of the limitations are showing same details on terminal , how can we realize that wich **error_message** is for **SLOW MODE FOR ONE SUPERGROUP** and wich one is for the **LIMITATION FOR ALL CHATS** ??
Please Help.

**Comment by levlam** [comment]
There is no such thing for a client as "limitations for all chats". All requests to TDLib are independent and if error 429 is returned for a request always means that the request can be repeated only after specified time passed.

Slow mode is special, because clients know in advance, how many seconds it will last. This value will be available in the future TDLib versions.

**Comment by Kia-Pashang** [comment]
"limitation for all chats" i mean ; bot can't send message or forward message at all (not

**Comment by levlam** [comment]
There are "limitations for all chats" but there is no such notion for clients. They can't and shouldn't disinguish whether the limit is for the query or for all similar queries.

**Comment by Kia-Pashang** [comment]
That means we can't realize the limitations ? that wich one is for **Main Supergroup** or wich one is for **All Chats** in telegram-bot ?
If answer is YES , thats a really bad problem for bot designers

**Comment by levlam** [comment]
No, we can't distinguish these situations, because there can be much more different situations than these two. And this is not a problem at all, because bot designers must assume that all limitations are for a specific request, which is always true.

**Comment by Kia-Pashang** [comment]
There is no difference beween them , take a look ;


![All](https://user-images.githubusercontent.com/26571020/66063412-2711a180-e4f8-11e9-8c45-a604c16edcac.JPG)
![OneSupergroup](https://user-images.githubusercontent.com/26571020/66063418-2aa52880-e4f8-11e9-86d2-b8106e21e408.JPG)

**Comment by levlam** [comment]
And there should be no difference between them. First request can be retried in 599 seconds and second in 30 seconds.

**Comment by Kia-Pashang** [comment]
@levlam First one is when bot is totally limited for every kinds of Chats and second one is when Supergroup uses slow mode and bot can't send any messages in that supergroups.
But tdlib is not showing there difference , is there any ways to how can i realize the differences ??

**Comment by levlam** [comment]
There is no way.

**Comment by Kia-Pashang** [comment]
Would you tell me where is the part of the code that is related to  Slow mode and that part is showing the error 429 "Too many requests: try after " ??

**Comment by levlam** [comment]
There is no code at all related to slow mode in TDLib 1.5.0.

**Comment by Kia-Pashang** [comment]
@levlam Alraight , thank you do much for the answers 🌹🌹
