### ISSUE TITLE
After building td(ls -l td/tdlib) has no results

### ISSUE THREAD

**Issue by akbwyfc** [tdlib/td#717]
Hi 

I made td for ubuntu,
After finishing the build successfully, 
I saw there is no tdlib folder in td.
Also when I try to compile a program there are errors like:
golang
When I compile I receive the error as:
src/github.com/go-tdlib/tdlib.go:178:: could not determine kind of name for C.free

Thanks in advance.

**Comment by levlam** [comment]
Please provide full log of shell commands run for TDLib building and their output.

**Comment by akbwyfc** [comment]
Hi, 
Many thanks for your message.
Attached please find the full log of shell commands run for building TDLib and their output:
I used the set of commands for the low memory case(less than
[error.txt](https://github.com/tdlib/td/files/3681875/error.txt)
 3.5GB)

**Comment by levlam** [comment]
CMAKE_INSTALL_PREFIX wasn't specified, so TDLib was successfully built and installed to /usr/local.
After that you should be able to use TDLib as in https://github.com/Arman92/go-tdlib/blob/master/tdlib.go. Could you show `sendText.go`?

**Comment by akbwyfc** [comment]
Many thanks.
Attached please find sendText.go
BTW, in this case can I use TDLib as:
go build sendText.go -I/usr/local/include -L/usr/local/lib -ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdactor -ltddb -ltdnet -ltdutils -lstdc++ -lcrypto -ldl -lz -lm 
I guess I need to provide a path as well.
I receive error as:
can't load package: named files must be .go files: -I/usr/local/include
(please kindly remove .txt at the end)

[sendText.go.txt](https://github.com/tdlib/td/files/3682280/sendText.go.txt)

**Comment by levlam** [comment]
@akbwyfc This should work.

```
export GOPATH=~/go
go get github.com/Arman92/go-tdlib
go build sendText.go
```
builds executable file just fine for me.

**Comment by akbwyfc** [comment]
Many thanks @levlam,
I tried as above, but still have the same problem:
src/github.com/go-tdlib/tdlib.go:178:: could not determine kind of name for C.free

I will try to reinstall go and other libraries, it maybe due to other issues.

**Comment by akbwyfc** [comment]
Hi @levlam,

Btw, I tried to install Golang again and also tdlib again, but had the same error. In case is there any way to check if my tdlib works fine?

Thanks in advance.

**Comment by levlam** [comment]
If the executable is not built, then it definitely doesn't work, but it looks like a problem with golang installation, because it is expected to work.

**Comment by akbwyfc** [comment]
Many thanks. I can build simple go programs like hello.go program. I will try again. Thanks

**Comment by akbwyfc** [comment]
I just tried go get gitgub.com/../go-tdlib
And it works now. Tnx
