### ISSUE TITLE
TdLib for server side (with storing multiple account sessions)

### ISSUE THREAD

**Issue by Crispried** [tdlib/td#718]
Hello,

Actually I'm trying to build server based app where the logic is that multiple users should be able to connect their telegram account to my application. 

I got from here https://github.com/tdlib/td/issues/40 that we should create one database per account. But, which logic I should use to work with database which corresponds to concrete user? For example server gets request to retrieve first 10 chats of user with phone P1 (I guess the best way is to use phone number as user identifier). And lets assume that we already created session for user with phone P1. How tdlib client on server side can know that currently he should use session for user with phone P1?

Also is that possible to check if tdlib created session for user with concrete phone? Or in another words is that possible to get current AuthorizationState based on phone? 

Thanks for your help!

**Comment by levlam** [comment]
TDLib doesn't manage multiple accounts itself. So you will need to create a directory for each phone number, i.e. phonenumber123456789, and initialize a TDLib instance with that directory as database and files directory. After TDLib instance is created it will send you `updateAuthorizationState`, which can be handled by your application.

**Comment by Crispried** [comment]
Ok, thanks

**Comment by deewelop** [comment]
and where we have to give it database directory?
litlle help pls <3

**Comment by deewelop** [comment]
found it, thanks
