### ISSUE TITLE
Photo uploading and size "i"

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#719]
We are now implementing progress and feedback for uploading photos. One thing I noticed that according to https://core.telegram.org/constructor/photoSize there arer various sizes, but during upload there is only size "i" available, but it is not described on the page. Can you give me an idea what it is? Is it Intermediate, Internal, can we use it for preview or so?

**Comment by levlam** [comment]
It is a type of photo which is used internally by TDLib for a local photo files. Generally, you need to ignore `type` field and choose appropriate photo sizes by their width, height and `photo.local.is_downloading_completed`/`photo.local.can_be_downloaded` fields.

**Comment by Flohack74** [comment]
Ok so during upload, will there be already a kind of thumbnail available or do we need to provide it ourselves until upload is finished (and maybe also downloaded has happened)?

**Comment by levlam** [comment]
If you need a thumbnail you need to provide it in `inputMessagePhoto`. Usually `inputFileGenerated` will be used there.
