### ISSUE TITLE
python interpreter can't find "tdjson" library or tdjson.dll file

### ISSUE THREAD

**Issue by msh15** [tdlib/td#72]
When i try to execute python example of tdlib i get this error.
![tdjson](https://user-images.githubusercontent.com/35134604/36088792-da8a9f82-0fed-11e8-84b6-da47b847198c.PNG)

**Comment by msh15** [comment]
there is no "tdjson" .cpp or .h file or tdjson.dll library in any of directories.
should i build tdlib with cmake and after that it will be generated?

**Comment by isopen** [comment]
make install

**Comment by arseny30** [comment]
Yeah, you have to build and install the library.

**Comment by msh15** [comment]
thanks man ...

**Comment by msh15** [comment]
I build it, but ...
tdjson still doesn't show up itself!

**Comment by isopen** [comment]
make install ?

**Comment by msh15** [comment]
yes yes, i did that too, but tdjson was not create.
there's a libtdutils.a file in tdutils sub directory of build directory,
what it is exactly?

**Comment by isopen** [comment]
After make install, you will see a list of paths in the terminal

**Comment by msh15** [comment]
yeah, the paths are for objects,
*.cpp.o files

**Comment by isopen** [comment]
Instruction
https://github.com/isopen/docker/blob/master/tdlib/Dockerfile.debian

**Comment by isopen** [comment]
Check the packages

**Comment by msh15** [comment]
finally i built it successfully,
thanks for helping.
