### ISSUE TITLE
Endless loop in Client destructor when deleting Client

### ISSUE THREAD

**Issue by wertas** [tdlib/td#721]
Hello.
I have a thread that runs Client loop. When i need to close, i delete Client, and its destructor falls into endless loop. It happens while it is in authorizing state.
inside Client destructor i see 
```
auto res = output_queue_->reader_get_unsafe();
      if (res.object == nullptr && res.id == 0) {
        is_closed_ = true;
      }
```
res has res.id = 3 and res,object ID = 0 in debugger, and is_closed_ never true

**Comment by levlam** [comment]
Could you send the whole code, reproducing the issue?

**Comment by wertas** [comment]
I`ll try to do little example now, where i can send it?

**Comment by levlam** [comment]
There or to @tdlib_bot.

**Comment by wertas** [comment]
sent

**Comment by wertas** [comment]
Please, can you say when it could be fixed?
Or how can i avoid that now.
Thanks

**Comment by levlam** [comment]
@wertas Sorry for the long delay with response.

From the logs you sent I see that TDLib really does nothing after databases are closed and doesn't compete the closing, I can't explain it, nor I can reproduce it. It could be really helpful if you reduce your example project more, so I can reproduce the issue on a small self-contained example. The current project you sent is too big for that and requires external resources to be run.

**Comment by wertas** [comment]
Hello
I tried to reduce it already, but not problems appeared.
I can send my debug build if it could help

**Comment by levlam** [comment]
Could you try to remove as most business logic as possible and combine all the source sode and .ini files into a single file?

**Comment by wertas** [comment]
I tried it already before sending first, but problem was gone.

**Comment by levlam** [comment]
@wertas Have you managed to solve the problem?

**Comment by AnnGoldrin** [comment]
Not it that way, i rewrote and refactored to avoid it from scratch. 
If needed i can try to reproduce old problem on new tdlib version

**Comment by wertas** [comment]
Not it that way, i rewrote and refactored to avoid it from scratch.
If needed i can try to reproduce old problem on new tdlib version

**Comment by levlam** [comment]
Let's close this for now.
