### ISSUE TITLE
Can't building TDlib UWP

### ISSUE THREAD

**Issue by fofgogjoj** [tdlib/td#722]
I carefully followed the instructions at https://github.com/tdlib/td/tree/master/example/uwp, but I get an error when I try to build TDLib. Any ideas?
![Безымянный](https://user-images.githubusercontent.com/11699530/66276144-ac020f80-e898-11e9-96cd-23bd64d49d43.png)

**Comment by levlam** [comment]
The command is supposed to be invoked in the `td/example/uwp` directory.

**Comment by levlam** [comment]
I hope that you succeded with TDLib building. If not, please reopen the issue, providing more details.
