### ISSUE TITLE
Wrong info in getUser

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#724]
sometimes (not often) method getUser return incorrect data. 

e.g. i call  getUser with user_id 123456789 but getting  info about another user with user_id 987654321.
But in next time when i call  getUser with user_id 1233456789 i getting true info.

somebody to face with it?

**Comment by levlam** [comment]
Are you sure that you correctly match requests with corresponding responses (for example, using `@extra` parameter in JSON interface)?

**Comment by AquariusHunters** [comment]
Returns information about a user by their identifier. This is an offline request if the current user is not a bot.
I don't quite understand that when the user I want to get is not a robot, the request is offline. Does that mean I query from a local database?
@levlam

**Comment by levlam** [comment]
Yes. There is no way to receive a user from the server just by its ID. See description of `updateUser` in https://core.telegram.org/tdlib/getting-started#handling-updates.
