### ISSUE TITLE
Converting formattedText to HTML or Markdown

### ISSUE THREAD

**Issue by mib32** [tdlib/td#725]
Do you know if there is already a library or a solution that lets convert formattedText to for example HTML or Markdown with respect to textEntities?

**Comment by levlam** [comment]
If you mean convertion to Markdown-style and HTML-style markups used by Bot API, then you can look at Bot API libraries. For example, https://aiogram.readthedocs.io/en/dev-2.x/telegram/types/message.html#aiogram.types.message.Message.html_text.

TDLib doesn't provide a method for that.

**Comment by mib32** [comment]
@levlam Thank you
