### ISSUE TITLE
Is there a caching option if I would like to send one image/video to a higher amount of people?

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#727]
I would like to send larger files to a higher amount of people. Is there an option that the telegram server caches files, so its not necessary to upload a image/video for every user?

**Comment by levlam** [comment]
This is done automatically by TDLib for local/generated files if the file database is enabled in TDLib parameters or if the file is sent simultaneously to different chats.

**Comment by MalteToenjes** [comment]
Ah you mean I should enable the parameter "use_file_database_" ye? What exactly do you mean with "sent simultaneously to different chats"? Is there also an option that guarantees,  a message is sent to different users but at the same time?

**Comment by levlam** [comment]
I meant that if the file database isn't used then a file still will be uploaded once if the messages are sent without TDLib restart.

**Comment by Flohack74** [comment]
@MalteToenjes No, a message as such in Telegram´s structure is an object that is sent initially to one chat only. You might want to add all users to a channel to achieve what you want.
