### ISSUE TITLE
How to register an account? Registered account did not send SMS

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#728]
How to register an account? Registered account did not send SMS

**Comment by levlam** [comment]
New account will be registered if there is no account with the specified phone number. Application will receive `updateAuthorizationState` with `authorizationStateWaitRegistration` if a new account needs to be registered and needs to call the method `registerUser` to finish registration. See https://core.telegram.org/tdlib/getting-started#user-authorization for detailed description of the authorization workflow.

If you have problems with receiving an SMS code, you can write to sms@telegram.org. But they will not be able to help you if you are trying to autoregister bots for spam, scam or cheating.

**Comment by huang-ju** [comment]
I send my Phonenumber and reply

``value(TDLib.AuthorizationState.waitCode(isRegistered: false, termsOfService: Optional(TDLib.TermsOfService(text: TDLib.FormattedText(text: "By signing up for Telegram, you agree not to:\n\n- Use our service to send spam or scam users.\n- Promote violence on publicly viewable Telegram bots, groups or channels.\n- Post pornographic content on publicly viewable Telegram bots, groups or channels.\n\nWe reserve the right to update these Terms of Service later.", entities: []), minUserAge: 0, showPopup: false)), codeInfo: TDLib.AuthenticationCodeInfo(phoneNumber: "+8615625064148", type: TDLib.AuthenticationCodeType.sms(length: 0), nextType: nil, timeout: 0)))``

sms length is 0 and I didn't receive the sms
