### ISSUE TITLE
tdweb: Method 'addProxy' is not supported

### ISSUE THREAD

**Issue by esindger** [tdlib/td#729]
Hello,
do you have plans to add support proxy for `tdweb`?

At the time, I receive an error:
```
{
  "_": "error",
  "@extra": {
    "query_id": 9
  },
  "code": 400,
  "message": "Method 'addProxy' is not supported"
}
```

**Comment by levlam** [comment]
No. There is no way it can be supported, because connections are handled by browser and there is no way to force it to use a Socks5, an HTTP or an MTProto proxy.

**Comment by esindger** [comment]
Ok, thank you for the clarifying
