### ISSUE TITLE
download image file or (any media) from content messages

### ISSUE THREAD

**Issue by Qasemt** [tdlib/td#73]
hi :)

i want to download image file from content  messages
where is **file id** and how to get **file id in message** ?
the file id is  required parameter for **downloadfile funcation** 
```C++
void TdDriver::process_update(td_api::object_ptr<td_api::Object> update)
{
  td_api::downcast_call(
    *update, overloaded(
            [this](td_api::updateNewMessage& update_new_message)
  {

    auto chat_id = update_new_message.message_->chat_id_;
    auto sender_user_name = get_user_name(update_new_message.message_->sender_user_id_);
  
     if (update_new_message.message_->content_->get_id() == td_api::messagePhoto::ID)
    {
      media_id_and_filename = std::to_string(static_cast<td_api::messagePhoto &>(*update_new_message.message_->content_).photo_->id_);
      std::cerr << "MEDIA MESSAGE :" << media_id_and_filename << std::endl;
    }
.
.
.

```

**Comment by arseny30** [comment]
Object photo has a field called `sizes_.` It is a vector which contains photoSize objects. Each of them represents different sizes of photo and has a field `object_ptr<td_api::file> photo_`. You need its `id_` field.

**Comment by Qasemt** [comment]
tanx arseny30 
I found  size field, but why show 4 [number of elements]  in vector, while I sent one image !!?!?
i need last file id ...  :)

![tel_error](https://user-images.githubusercontent.com/2597895/36133761-938f99ae-1095-11e8-8d6f-dcc211748d8c.png)

**Comment by levlam** [comment]
You can't download the original photo. Every sent photo is scaled to many different sizes to allow apps to download photo thumbnails and choose photo size depending on a screen resolution. If you need a largest photo, then you usually need the last photoSize.

**Comment by Qasemt** [comment]
thanks for replay message 
**how can i store original file (largest photo)  in local system !?**
 I have message id and chat id 
Please show me the correct way

**Comment by levlam** [comment]
You need to call downloadFile with the corresponding file.id. Something like photo_->sizes_.back()->photo_->id_ and handle UpdateFile updates for that file.id until it isn't downloaded. 

Between, largest photo isn't an original photo, it is just a largest available photo size.

**Comment by Qasemt** [comment]
**Thanks :)** 👍

**Comment by pabx06** [comment]
do you care sharing the code to download. here.
thanks.

**Comment by sadeghhp** [comment]
> You need to call downloadFile with the corresponding file.id. Something like photo_->sizes_.back()->photo_->id_ and handle UpdateFile updates for that file.id until it isn't downloaded.
> 
> Between, largest photo isn't an original photo, it is just a largest available photo size.

I use tdlib and I found some of these fileId (in photo sizes) has duplications!
are file ids unique globally or just unique in a single chat?
![image](https://user-images.githubusercontent.com/195273/60255519-2a880200-98e5-11e9-99a9-1427a9c50223.png)

**Comment by levlam** [comment]
@sadeghhp FileId is not persistent between client restarts, you can't save it. Instead you can save file.remote.id for files which can be downloaded from the server.

Also, fileId is a unique identifier for a file, but the same file can be used in a lot of places.
