### ISSUE TITLE
Connection timeout, Telegram is not blocked

### ISSUE THREAD

**Issue by a3s** [tdlib/td#730]
I just built tdlib and try to use it with tdl for Node but it doesn't connect:
```
[ 2][t 4][1570906878.001766682][TdDb.cpp:313][#1][!Td]  Got PRAGMA user_version = 9
[ 2][t 4][1570906878.003407240][AuthDataShared.cpp:112][#1][!Td]        DcId{1} [auth_key_id:0][state:Empty]
[ 2][t 4][1570906878.004279375][SessionMultiProxy.cpp:121][#1][!SessionMultiProxy:1:main]       [session_count:1]
[ 2][t 4][1570906878.004398584][Session.cpp:144][#1][!SessionProxy:1:main]      Generate new session_id 2215900976090620296 for auth key 0 for DC1
[ 2][t 3][1570906888.014441252][Session.cpp:1133][#1][!Session:1:main::HandshakeActor]  Failed to open connection: [Error : 0 : Timeout expired : [149.154.175.56:443] to DcId{1} from [xxx]]
[ 2][t 4][1570906888.014577150][Session.cpp:1066][#1][!Session:1:main]  Handshake is not yet ready
[ 2][t 4][1570906888.014752626][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:443] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:443]]
[ 2][t 4][1570906888.071142673][Session.cpp:144][#1][!GetConfigActor]   Generate new session_id 1950937967853393554 for temp auth key 0 for DC4
[ 2][t 4][1570906888.210888624][Session.cpp:1079][#1][!ConfigSession]   Update auth key in session_id 1950937967853393554 to 15783223551251840760
[ 2][t 4][1570906903.430560827][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:80] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:80]]
[ 2][t 4][1570906919.432370901][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:5222] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:5222]]
[ 2][t 4][1570906951.429768801][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:443] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:443]]
[ 2][t 4][1570906999.435061693][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:80] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:80]]
[ 2][t 4][1570907031.431510687][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:5222] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:5222]]
[ 2][t 4][1570907063.434715033][ConnectionCreator.cpp:879][#1][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:443] to DcId{1}: [PosixError : Cannot assign requested address : 99 : Failed to connect to [[2001:b28:f23d:f001::a]:443]]
```
I run it while being connected to my work VPN in Germany.

**Comment by levlam** [comment]
Could you try to run `telnet 149.154.175.56 443` and enusre that connection can't be established?
It seems that some Telegram servers are banned in Germany or by your VPN provider, so you need to use another VPN or try to connect without it.

**Comment by a3s** [comment]
@levlam yea, it doesn't establish connection. No response. 
What is interesting is that I use the same server where my VPN is running as a SOCKS proxy for my telegram apps on PC and mobile and it works without issues.

**Comment by a3s** [comment]
Actually I'm not sure now, I just connected to some Japanese VPN and it also doesn't connect to 149.154.175.56.

**Comment by a3s** [comment]
Meanwhile, it successfully connects to servers that I have in my App configuration page (149.154.167.40:443 and 149.154.167.50:443). 
Is there something I can do in this case?

**Comment by levlam** [comment]
Some Telegram servers and IP addresses are banned and some aren't, so if you are already logged in you will be able to use Telegram.

You can set option "online" to true (via `setOption` method) to speed up blocks bypassing. If TDLib will not be able to establish a working connections in 1 minute after that, then likely only switching to another VPN could help.

**Comment by a3s** [comment]
Is there specific reason why we can't set IP manually then?
I tried using Telethon library and was able to successfully connect and work with Core API. I see how they hardcoded server address but I also set it to the one that App configuration page provided to me and it's working now.

**Comment by levlam** [comment]
You can't do that, because these IPs are from different datacenters and are not interchangeable.

**Comment by a3s** [comment]
Understood, thank you for help.

**Comment by ramikalai** [comment]
@levlam I'm having a similar issue to this, I have two threads (that may be concurrent). One calls getChats for the main and then for the archive list, and the other handles incoming media messages, and calls downloadFile for those messages.

When both are running, then both functions seem to throw a timeout error. If I disable one of the two threads, then the other no longer times out..

Is tdlib thread safe? and if yes, what should I do to eliminate this timeout issue?

**Comment by ramikalai** [comment]
I already ran telnet on the server IP and it connects just fine

**Comment by levlam** [comment]
@ramikalai TDLib is definitely thread-safe. Could you collect TDLib logs with verbosity level 4 and send them to @tdlib_bot?

**Comment by ramikalai** [comment]
@levlam I'm assuming you mean over Telegram? The bot seems inactive though..
