### ISSUE TITLE
is_scam field contains an incorrect value in TDLib json API

### ISSUE THREAD

**Issue by Folleah** [tdlib/td#731]
For example, i found channels with [SCAM] mark: `@hackandrei` and `@privet_lyubimaya`. In Telegram, this channels are marked correctly: 

- ![image](https://user-images.githubusercontent.com/6205767/66713616-910e2e80-edb5-11e9-900b-177f93f0015e.png)
- ![image](https://user-images.githubusercontent.com/6205767/66713618-a08d7780-edb5-11e9-8c00-20ce40df9b25.png)

But when I use the json tdlib API, I get the wrong value:

- ![image](https://user-images.githubusercontent.com/6205767/66713634-c024a000-edb5-11e9-8f31-723c23d3da10.png)

I may have misunderstood something, but I'm definitely using the tdlib API correctly.
Unfortunately, I don't have the knowledge to do PR, but I think the problem is somewhere [here](https://github.com/tdlib/td/commit/666e668163fe7029b36433eac309c3d59188bd22).

**Comment by levlam** [comment]
`is_scam` was added prematurely and is always false in TDLib 1.5.0, because it doesn't returned by the server to clients using the old API layer. This will be automatically fixed in TDLib 1.6.0 with updating to new layer (and there is no way it can be done in TDLib 1.5.0).

**Comment by Folleah** [comment]
@levlam thank you, that makes a lot of sense.

**Comment by levlam** [comment]
The field `is_scam` has correct value since TDLib 1.6.0.
