### ISSUE TITLE
Connect To MTProxy in TDLib 1.5.0

### ISSUE THREAD

**Issue by m-mehdiansari** [tdlib/td#732]
Hi,
I want use mtproxy in my cli bot for change location,What should I do for this?!

**Comment by levlam** [comment]
You can use `addProxy` method to add a proxy.

**Comment by m-mehdiansari** [comment]
Please help more about this is!

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started

**Comment by m-mehdiansari** [comment]
Do you mean to use `setProxy` method?

**Comment by levlam** [comment]
The method `setProxy` exists only in TDLib <= 1.2.0. It was replaced by `addProxy` and other methods in TDLib 1.3.0.

**Comment by m-mehdiansari** [comment]
hi 

can send me this is `addProxy` to me??

**Comment by levlam** [comment]
@m-mehdiansari `addProxy` is a method: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_proxy.html.

**Comment by m-mehdiansari** [comment]
thank you so much :)

but you can send me `addProxy` tdbot_function for lua ?

example: 
assert (tdbot_function ({
    ["@type"] = 'setProxy',
    proxy = {
      ["@type"] = 'proxy' .. proxy,
      server = server,
      port = port,
      username = username,
      password = password
    }
  }, callback or dl_cb, data))

**Comment by levlam** [comment]
I can't help you with the exact way in which methods are called in your wrapper.

**Comment by m-mehdiansari** [comment]
What should I do?

**Comment by levlam** [comment]
Look at the documentation, try, see the errors and try again until success.

**Comment by m-mehdiansari** [comment]
Thanks :||
