### ISSUE TITLE
Error 406: FILEREF_UPGRADE_NEEDED

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#733]
Recently I get this error:

> Fail to send yet unsent message 230693.9 in chat 648245075 with the error [Error : 406 : FILEREF_UPGRADE_NEEDED]

It happens when I try to send the same image twice in a row. I'm not really sure why this happens. First I thought its because I turn the params _use_file_database_ and _use_message_database_ to true, but now even if I turn it to false I got this issue.
Initially I had no problems to send multiple images...

But how to handle this error? Is there any file reference I get when I send an image to the telegram servers? Then there must be also a way to set this file reference for the next call or?

**Comment by levlam** [comment]
You need to update TDLib to 1.5.0.

Also, if you use `inputFileRemote` or `getRemoteFile` you need to ensure that it was obtained from TDLib after restart. I.e. if this is a `remote.id` from a message then the message must be first loaded with `getMessage`, or if this is a user's profile photo then the user must be received from TDLib first.

**Comment by MalteToenjes** [comment]
Okay thanks for your answer. One more question: Do I initially have to upload the file as _inputFileLocal_ and after this I can use _inputFileRemote_? Because I mentioned when I use _inputFileLocal_ I get a callback _updateFile_ with the remote_id.

**Comment by levlam** [comment]
It is better to always use `inputFileLocal` if you have `use_file_database` enabled.

**Comment by MalteToenjes** [comment]
The update to version 1.5 solved my problem btw...thanks :) But I'm wondering if you guys have a blog or something where other developers get informed about such an important release...
And I have to ask one more question about the file_database...I don't get how its work, since inputFileLocal  has only the parameter path...or does tdlib do the whole work for me?

**Comment by levlam** [comment]
Every release is important, because it brings a lot of new features and adjusts to new server-side changes. While time passes a lot of server-side changes are introduced, some of which can broke old clients, so you must always tend to use the latest available version.

Yes, TDLib does all the work in the best possible way.
