### ISSUE TITLE
Not getting telegram code for login on some workstations

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#734]
Hi, I faced some strange behavior in getting telegram code for login.
On one computer Telegram sends me that code without any issues for my app, but when setting-up application on another machine, code just don't come from Telegram. App log is clear, there are no errors. Maybe issue is related to configuration of this new workstation? Could you please give any tips regarding this? What can be wrong with my workstation setup?

UPD: I don't know what was happening, but now everything returned back to normal: getting Telegram codes works fine.

**Comment by levlam** [comment]
It sounds like you was banned from receiving Telegram codes for some time because asked them too much. And after ban time has passed you can receive them again.
