### ISSUE TITLE
deviceModel shows an error  

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#738]
I set the ``deviceModel`` of ``setTdlibParameters`` to iphone, but I log in to the device to display ``Android``.

![66771881-febd7600-eeed-11e9-88b6-e825a400a472](https://user-images.githubusercontent.com/46550127/66990985-ca1e0a00-f0f9-11e9-9a57-bd23cfddc06b.png)

https://github.com/leoMehlig/TDLib-iOS/issues/8

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/66992134-e28f2400-f0fb-11e9-93c2-277d9d68dd91.png)

I am using [TDLib-iOS](https://github.com/leoMehlig/TDLib-iOS)

**Comment by levlam** [comment]
You need to specify full device_model and correct system_version (i.e, iPhone and iOS version). See official iOS app source for examples of a correct values: [device_model](https://github.com/TelegramMessenger/Telegram-iOS/blob/97eca304f8cee20fad75185bce2189cdb3e98005/submodules/MtProtoKit/MTProtoKit/MTApiEnvironment.m#L571) and [system_version](https://github.com/TelegramMessenger/Telegram-iOS/blob/97eca304f8cee20fad75185bce2189cdb3e98005/submodules/MtProtoKit/MTProtoKit/MTApiEnvironment.m#L506).

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/67174915-80356c80-f3f6-11e9-9db7-1313f9064549.png)
not solved

**Comment by levlam** [comment]
You also need to choose correct OS at my.telegram.org.
