### ISSUE TITLE
problem with official java sample code

### ISSUE THREAD

**Issue by soloist624** [tdlib/td#739]
I have downloaded official prebuilt library for android from [here](https://core.telegram.org/tdlib/tdlib.zip) initialized a new android project and added the downloaded files as a module to the project, next I used official sample java code from [here](https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java) added my api key and hash and ran it through an asyncTask.

first problem: 
below lines of code always end up with error code 400 and message ```File "tdlib.log" can't be opened/created for appending``` while my app has write prmissions
```
if (Client.execute(new TdApi.SetLogStream(new TdApi.LogStreamFile("tdlib.log", 1 << 27))) instanceof TdApi.Error) {
            throw new IOError(new IOException("Write access to the current directory is required"));
        }
```

second problem:
after commenting out above two line of codes, app stucks in ```AuthorizationStateWaitEncryptionKey``` state of authentications

no idea what to do

**Comment by levlam** [comment]
You need to specify a correct `databaseDirectory` in `SetTdlibParameters`, to which the application has write access. See https://core.telegram.org/tdlib/getting-started#user-authorization for more details.

**Comment by soloist624** [comment]
Sorry but I cannot figureout which problem is supposed to be solved by your solution.

to clarify more I should say that first problem occures even before creating a client instance as you see in below portion of official sample and debug breakpoint prove it:
```
//******** where my first problem occures********
Client.execute(new TdApi.SetLogVerbosityLevel(0));
        if (Client.execute(new TdApi.SetLogStream(new TdApi.LogStreamFile("tdlib.log", 1 << 27))) instanceof TdApi.Error) {
            throw new IOError(new IOException("Write access to the current directory is required"));
        }

        //******** where client instance is created *******
        client = Client.create(new UpdatesHandler(), null, null);

        // test Client.execute
        defaultHandler.onResult(Client.execute(new TdApi.GetTextEntities("@telegram /test_command https://telegram.org telegram.me @gif @test")));
```

also these are parameters I currently set and pass to client:
```
                parameters.databaseDirectory = "/files";
                parameters.useMessageDatabase = false;
                parameters.useSecretChats = false;
                parameters.apiId = 000000; //my private api id as an integer
                parameters.apiHash = "MY_API_HASH";
                parameters.systemLanguageCode = "en";
                parameters.deviceModel = "Android";
                parameters.systemVersion = "Unknown";
                parameters.applicationVersion = "1.0";
                parameters.enableStorageOptimizer = false;
```

I have also tried this set of parameters, still no chance:
```
                parameters.databaseDirectory = "/files";
                parameters.useMessageDatabase = true;
                parameters.useSecretChats = true;
                parameters.apiId = 000000; //my private api id as an integer
                parameters.apiHash = "MY_API_HASH";
                parameters.systemLanguageCode = "en";
                parameters.deviceModel = "Android";
                parameters.systemVersion = "Unknown";
                parameters.applicationVersion = "1.0";
                parameters.enableStorageOptimizer = true;
```

**Comment by levlam** [comment]
Application can't access "/files" directory, unless you rooted your phone. You need to specify a valid writable directory, for example, `getApplicationContext().getFilesDir().getAbsolutePath()`.

The same is true for "tdlib.log" path that is specified to initialize the log. You need to specify a valid path to an accessible writable file, for example `getApplicationContext().getFilesDir().getAbsolutePath() + "/tdlib.log"`.

**Comment by soloist624** [comment]
great! =))
that's the solution
I thought base address is handled by library
now it works
thanks
