### ISSUE TITLE
td.binlog can't be created

### ISSUE THREAD

**Issue by rafatdin** [tdlib/td#74]
I am trying to write an Android app using your prebuilt Android library. When calling SetTdLibParameters, the TdLib returns error object (after several unsuccessful implementations tried just like in your java console example - same result).
```
"Error {
  code = 30
  message = "File "/td.binlog" can't be opened/created for reading and writing"
}"
```
Thought that library wants to save to external storage and added 
```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```
but this also doesn't help. Am I doing something wrong, or is it your prebuilt Android library?

**Comment by arseny30** [comment]
You should store into database_directory and files_directory some path where your app is allowed to write.
For example: `getApplicationContext().getFilesDir().getAbsolutePath() + "/"` into database_directory and `getApplicationContext().getExternalFilesDir(null).getAbsolutePath() + "/"` into files_directory.

**Comment by rafatdin** [comment]
The description in parameters `if empty, the current working directory will be used.` got me confused thinking that it would set application's directory itself. Anyways, thank you a lot!
