### ISSUE TITLE
Cannot build for watchOS

### ISSUE THREAD

**Issue by BlackWolf** [tdlib/td#742]
I am trying to build tdlib for watchOS, but have been unsuccessful so far. I'm building on macOS and have tried on both macOS 10.14 and 10.15 with the same result.

Here is what I tried:

1) Downloaded 1.5.0

2) Build OpenSSL:
```
cd <path to TDLib sources>/example/ios
./build-openssl.sh
```

3) CMake with the newly built OpenSSL:
```
cd <path to TDLib sources>
mkdir native-build
cd native-build
cmake -DCMAKE_TOOLCHAIN_FILE=../CMake/iOS.cmake -DIOS_PLATFORM=WATCHOS -DIOS_DEPLOYMENT_TARGET=6.0 -DOPENSSL_CRYPTO_LIBRARY=~/td-1.5.0/example/ios/third_party/openssl/watchOS/lib/libcrypto.a -DOPENSSL_SSL_LIBRARY=~/td-1.5.0/example/ios/third_party/openssl/watchOS/lib/libssl.a -DOPENSSL_INCLUDE_DIR=~/td-1.5.0/example/ios/third_party/openssl/watchOS/include ..
cmake --build .
``` 

**This fails with the following error:**
```
make[2]: *** No rule to make target `../tdutils/generate/auto/mime_type_to_extension.cpp', needed by `tdutils/CMakeFiles/tdutils.dir/generate/auto/mime_type_to_extension.cpp.o'.  Stop.
make[1]: *** [tdutils/CMakeFiles/tdutils.dir/all] Error 2
make: *** [all] Error 2
```

-----

(Disclaimer: I tried the instructions here: https://github.com/tdlib/td/tree/master/example/ios but failed, because `build.sh` cannot find OpenSSL, which makes sense I think because we build OpenSSL after creating build files with CMake - if I'm missing something here and it should work please let me know)

**Comment by levlam** [comment]
In native build phase you must not specify CMAKE_TOOLCHAIN_FILE and other things. Just do
```
cmake ..
cmake --build . --target prepare_cross_compiling
```
which will use ordinary macOS toolset to create binaries and generate needed source files.

Then run the `build.sh`  script from the `example/ios` directory.

You will also need to apply patch from https://github.com/tdlib/td/issues/737#issuecomment-543064761 before building to correctly link OpenSSL.

**Comment by BlackWolf** [comment]
Yep, the patch you posted did the trick! Thanks :-)
