### ISSUE TITLE
About add to contacts

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#744]
I want to implement two functions in my application:

1. My user can receive his address book. Who is also registered with telegram?

2. When I meet an interesting person in the chat group, I don't know his mobile number and how to add it to my contacts.

I see it can be implemented on the client, but I don't have it. I think I need your help. @KrauseFx @levlam

**Comment by levlam** [comment]
1. User can only get all registered contacts from his address book using method `getContacts`. To import the whole address book you can use the method `changeImportedContacts`.

2. Adding to contacts users without knowing phone number and sharing phone number with them is not supported yet and will be supported in TDLib 1.6.0.

**Comment by AquariusHunters** [comment]
@levlam 
When I click the close option in the QT menu bar, I am prompted with an authorization error. I should use logout to do the exit processing. However, my intention is not to let him exit, but to let him close but keep my authorization. The next time the user opens, he will automatically log in to the account that did not perform logout before.

**Comment by levlam** [comment]
@AquariusHunters I don't understand what you mean.

If you don't want someone to be logged out, then just don't call `logOut` and call `close` instead.
