### ISSUE TITLE
Adding 64-bit watchOS Support

### ISSUE THREAD

**Issue by BlackWolf** [tdlib/td#745]
I noticed that the architecture for Apple Watch Series 4 and 5 (`arm64_32`) is missing in tdlib. I would love to create a pull request for that, but I'm not sure how to handle the OpenSSL dependency, since it needs to be added there as well. Since right now, TDLib uses an old commit of Python-Apple-support from 2018, I'm not quite sure how to handle this. 

Right now, the only idea I have is to write a script that patches the OpenSSL build script. Any better ideas or approaches to this?

**Comment by levlam** [comment]
Could you try to update the line
https://github.com/tdlib/td/blob/c81e18f5f1220ba8a9d0f03241b271140a3a1066/CMake/iOS.cmake#L200
adding the new architecture and check whether it builds fine?

**Comment by BlackWolf** [comment]
Unfortunately, this fails because arm64_32 is missing from libcrypto and libssl:

```
ld: warning: ignoring file ../../third_party/openssl/watchOS/lib/libssl.a, missing required architecture arm64_32 in file ../../third_party/openssl/watchOS/lib/libssl.a (2 slices)
ld: warning: ignoring file ../../third_party/openssl/watchOS/lib/libcrypto.a, missing required architecture arm64_32 in file ../../third_party/openssl/watchOS/lib/libcrypto.a (2 slices)
Undefined symbols for architecture arm64_32:
```

This can be fixed by editing the Makefile of Python-Apple-support from
```
# watchOS targets
TARGETS-watchOS=watchsimulator.i386 watchos.armv7k
CFLAGS-watchOS=-mwatchos-version-min=4.0
CFLAGS-watchos.armv7k=-fembed-bitcode
PYTHON_CONFIGURE-watchOS=ac_cv_func_sigaltstack=no
```

to

```
# watchOS targets
TARGETS-watchOS=watchsimulator.i386 watchos.armv7k watchos.arm64_32
CFLAGS-watchOS=-mwatchos-version-min=4.0
CFLAGS-watchos.armv7k=-fembed-bitcode
CFLAGS-watchos.arm64_32=-fembed-bitcode
PYTHON_CONFIGURE-watchOS=ac_cv_func_sigaltstack=no
```

But I'm not sure how to put this into a reasonable PR ;-)

**Comment by levlam** [comment]
I don't think there is an easy way to support this without hacking `Python-Apple-support` or completely replacing the way OpenSSL is built.

**Comment by levlam** [comment]
Proposed patch was applied in our example of building TDLib for `watchOS`, so the example can be used now to build TDLib for 64-bit watchOS.
