### ISSUE TITLE
tdlib missing

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#747]
I built tdlib: java - ubunu 18 (mine is 19.04) - g++ successfully.
    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get install make git zlib1g-dev libssl-dev gperf php cmake default-jdk g++
    git clone https://github.com/tdlib/td.git
    cd td
    rm -rf build
    mkdir build
    cd build
    export CXXFLAGS=""
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON ..
    cmake --build . --target install
    cd ..
    cd example/java
    rm -rf build
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DTd_DIR:PATH=$(readlink -e ../td/lib/cmake/Td) ..
    cmake --build . --target install
    cd ../../..
    cd ..
    ls -l td/tdlib
after the process is done there is no tdlib directory in the td directory (which is cloned from git)
![Screenshot from 2019-10-23 18-14-22](https://user-images.githubusercontent.com/45389623/67405193-4a90af00-f5c1-11e9-8ae9-2fe9494519ca.png)

**Comment by levlam** [comment]
Because it was installed to /usr/local/ and not to /tdlib/td. I will fix that for Java build instructions, the last line should be
```
ls -l /usr/local
```

**Comment by levlam** [comment]
The build instructions are fixed in https://tdlib.github.io/td/build.html?language=Java.
