### ISSUE TITLE
About banned account

### ISSUE THREAD

**Issue by Pauya** [tdlib/td#748]
I used the csharp example to register an account. 
After some days, I tried to login the account via the csharp example (had no user interface). Needed no password or code, it succeeded to login( "AuthorizationStateReady" ). I tried to send a message, but got no response all the time.
I deleted  the ".binlog" file, and tried again. After input phone number, it tried to connect all the time before "authorizationStateClosing". As below:
▶ @object {updateConnectionState { state = connectionStateConnecting { } } } 
▶ @object {updateAuthorizationState { authorization_state = authorizationStateClosing { } } } 
▶ @object {error { code = 500 message = "Request aborted" } } Telegram.Td.Api.BaseObject 

I tried login via desptop client, it told me it was banned.

But how can  I get the account's status( banned ro not banned  ) via tdlib?( csharp  Telegram.Td.Api)

**Comment by levlam** [comment]
You receive a corresponding error when you try to log in. TDLib 1.5.0 also writes to the log a big message with description of the issue and how to resolve it if you believe that the ban was done by a mistake.
