### ISSUE TITLE
My six-year-old son sent a ping of rust

### ISSUE THREAD

**Issue by isopen** [tdlib/td#75]
[ping rust](https://github.com/isopen/tdlib/tree/master/rust)
He also said that he would not continue writing on rust. Because he did not like rust very much.

**Comment by msh15** [comment]
jesus :-|
seriously?! :-D
he'll become a geek one day.

**Comment by isopen** [comment]
Yes. Now he is sleeping. He will then tell you how it works.

**Comment by isopen** [comment]
He woke up and explained everything fairly simply.

**Seven things from which he refused six years ago:**
- Alcohol.
- Meat of animals.
- Tablets and any pharmaceutical products.
- Nicotine and other narcotic substances.
- Coffee, black and green tea, energy.
- Fast food, sugar, carbonated drinks.
- Television and its analogues.

**Comment by msh15** [comment]
It's great man, it's fascinating :+1:

**Comment by isopen** [comment]
Maybe I gave him a couple more tasks.
