### ISSUE TITLE
NO ERRORS

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#750]
Hello , there is a problem about **updateMessageSendFailed** ;
in telegram-bot with **TDLIB 1.4.0** when messages (media or sticker or GIFs) were locked in chat permissions the **error_code 400 with CHAT_WRITE_FORBIDDEN or CHAT_SEND_GIFS_FORBIDDEN or CHAT_SEND_MEDIA_FORBIDDEN or CHAT_SEND_STICKERS_FORBIDDEN** could be show in **updateMessageSendFailed** , but now they are not in **TDLIB 1.5.0** , what is the solution ?

**Comment by levlam** [comment]
The error message wasn't removed from `updateMessageSendFailed` in TDLib 1.5.0. Moreover it was added to `messageSendingStateFailed`, accessible any time through message.sending_state.

**Comment by Kia-Pashang** [comment]
@levlam where is _messageSendingStateFailed_ ? when it will be shown ? there is nothing about failed send in terminal and im sure about this.

**Comment by levlam** [comment]
It is a field in `Message` object: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1message.html#accbb4f1c1aca998b5ec10e0a2e7e8f92. But nothing was changed in `updateMessageSendFailed`, `error_message` is still there.

**Comment by Kia-Pashang** [comment]
But when somthing is locked in chat permissions , and i send it , **updateMessageSendFailed** will not be shown to see what happened , thats the problem

**Comment by Kia-Pashang** [comment]
I know that , in **tdlib 1.4.0** when i try to do somthing (sendMessage or forwardMessage) that i cant do i'll receive an error about that in **updateMessageSendFailed** , but in **tdlib 1.5.0** i won't receive any errors about that
Please check it .

**Comment by levlam** [comment]
No, it was never returned through `updateMessageSendFailed` if the request is clearly incorrect. It was always returned as error to `sendMessage` request.

**Comment by Kia-Pashang** [comment]
i will record a video for you , where can i send it to you ?

**Comment by IRGC** [comment]
@tdlib_bot

**Comment by Kia-Pashang** [comment]
@levlam Hello , i sent you the video about this issue in [@TDLIB_BOT](https://t.me/tdlib_bot) i'm waiting for your answer

**Comment by levlam** [comment]
@Kia-Pashang The video shows only expected behavior. There was no support for default chat permissions in TDLib 1.4.0, so it couldn't check them to immediately return an error to `sendMessage` call. But if the user is a personally restricted member, then `sendMessage` returns an error even in TDLib 1.0.0.

**Comment by Kia-Pashang** [comment]
Ok thanks
