### ISSUE TITLE
How to handle closed session?

### ISSUE THREAD

**Issue by kigorw** [tdlib/td#753]
I can't find an event/method that indicates a closed session. (when you close it from another device).
I wan't to handle it both when tdlib is running and when tdlib is connecting.

When starting. I see such log messages
```
[ 2][t 3][1572074461.164262056][Session.cpp:412][#1][!Session:2:main]    Session closed: [Error : -404 : Mtproto error: -404] Session:2:main::Connect::Tcp::[149.154.167.51:443] to DcId{2} from [192.168.7.25:64706]
    [ 2][t 3][1572074461.573957205][ConnectionCreator.cpp:992][#1][!ConnectionCreator]   [[2001:67c:4e8:f002::a]:443] to DcId{2}: [PosixError : No route to host : 65 : Failed to connect to [[2001:67c:4e8:f002::a]:443]]NG [9s]
```

Thanks

**Comment by levlam** [comment]
This is a logging about an MTProto session, which is completely unrelated to Telegram sessions.

If a Telegram session is closed from another device, you will receive ordinary `updateAuthorizationState` with `authorizationStateLoggingOut`.

Could you send TDLib's log with verbosity level 4 to @tdlib_bot, so I can tell exactly, why MTProto error -404 is received?

**Comment by kigorw** [comment]
> If a Telegram session is closed from another device, you will receive ordinary updateAuthorizationState with authorizationStateLoggingOut.
Thanks. It works.

> Could you send TDLib's log with verbosity level 4 to @tdlib_bot, so I can tell exactly, why MTProto error -404 is received?
Maybe it would be enough if I say that it happens when I try to run client over logged out db and in this case I don't get any useful callback to detect that session is invalid.

**Comment by levlam** [comment]
@kigorw If you immediately receive `authorizationStateLoggingOut` then everything works as expected.

**Comment by kigorw** [comment]
thanks. confirm I'm getting `authorizationStateLoggingOut`.
I think a minor problem here (which I caught) is that if you try to launch again a client that already received logginOut event, it will not receive anything and will hang.

**Comment by levlam** [comment]
That's a problem. It should receive `authorizationStateLoggingOut` again if it wasn't successfully logged out, and that's why I asked to send TDLib's log with verbosity level 4 to @tdlib_bot.

**Comment by levlam** [comment]
@kigorw Does the problem with missing `authorizationStateLoggingOut` after restart persists?

**Comment by kigorw** [comment]
@levlam do you mean if I try to work again with logged out db?

**Comment by levlam** [comment]
@kigorw You said
```
I think a minor problem here (which I caught) is that if you try to launch again a client that already received logginOut event, it will not receive anything and will hang.
```
But the TDLib should send you an update with `authorizationStateLoggingOut` on relaunch and shouldn't hang. So, I wanted to know whether can you still reproduce the hang and provide TDLib logs to confirm the problem?

**Comment by kigorw** [comment]
Reproduced and sent it to @tdlib_bot. Sorry for the delay.

I also wanted to share a product I was building (and almost ready to launch) for the last few months. And also thank you for your helpful support/answers that you do here in issues.  Product: https://filter.sitg.app/

**Comment by kigorw** [comment]
In version 1.6.0 bug is not present. Closing this issue.

**Comment by levlam** [comment]
@kigorw Thanks for confirming!
