### ISSUE TITLE
libtdjson.dylib (which was built for iOS 13.1)

### ISSUE THREAD

**Issue by ariesrisk** [tdlib/td#754]
Hi There,

I'm used the latest Xcode Version 11.1 (11A1027) to build libtdjson.dylib.
And I follow step.
https://github.com/tdlib/td/tree/master/example/ios

But I got the message, and I wanna minimum supported version ios 9.
How can I build ios9 or ios10 tdlib version?
Thanks for help, and have nice day.

==============
dyld: Symbol not found: ___chkstk_darwin
  Referenced from: /private/var/containers/Bundle/Application/E2B83911-FDD3-4638-9BDC-ECD8823B6B40/BTChat.app/Frameworks/libtdjson.dylib (which was built for iOS 13.1)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/var/containers/Bundle/Application/E2B83911-FDD3-4638-9BDC-ECD8823B6B40/BTChat.app/Frameworks/libtdjson.dylib
(lldb)

**Comment by levlam** [comment]
See https://stackoverflow.com/questions/58426186/dyld-symbol-not-found-chkstk-darwin.
