### ISSUE TITLE
Disabling updateHavePendingNotifications

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#758]
Is it possible to disable `updateHavePendingNotifications` events?  TDLib logs are spammed with such events, but I have no idea what are the benefits from having them.  They are triggered on every activity, for example user changes online status and I receive couple of `updateHavePendingNotifications`, this is so inconvenient.  Is it possible to disable them, and maybe have some `getPendingNotifications` instead to get values for delayed/unreceived notifications?

Thanks

**Comment by levlam** [comment]
You are wrong about the `updateHavePendingNotifications` update. It is sent very rarely when there are some message notifications which will be delivered soon or are just delivered. It is never sent when just a status of a user changes. The update is essential for `Notification API` and `updateHavePendingNotifications.have_unreceived_notifications` can be really helpful for a lot of other things, so there is no way it can be disabled. Also there is no way to replace it with something like `getHavePendingNotifications`, because the method would be needed to be called all the time. Moreover, the suggested method name `getPendingNotifications` sounds completely unrelated to the meaning of the update `updateHavePendingNotifications`.

I don't understand a problem you have with the update. TDLib has a lot of updates and it will have much more over time. If your application doesn't want to process an update, it can just skip it.

**Comment by zevlg** [comment]
Here is what I mean - some random cut from TDLib logs - https://gist.github.com/zevlg/1abc7d442b3e72b18412e85bd433f131

we have two events: `updateNewMessage` and then `updateChatLastMessage`.  But after that there are *four* subsequent `updateHavePendingNotifications` with just blinking value for `have_unreceived_notifications` with no events or any calls to TDLib inbetween them.

This looks a little bit confusing for me.  TDLib logs are full of `updateHavePendingNotifications` events, thats why I've created this issue.  `updateHavePendingNotifications` is just most received event.   I've collected statistics from ordinary TDLib session and here is the statistics:
```
EVENT: CALLS
updateHavePendingNotifications: 24580
updateUserStatus: 8255
updateChatOnlineMemberCount: 7548
updateChatReadInbox: 1092
updateUnreadMessageCount: 1030
updateChatLastMessage: 996
updateSupergroupFullInfo: 985
updateNewMessage: 905
updateUserChatAction: 861
updateFile: 363
updateDeleteMessages: 361
updateBasicGroupFullInfo: 229
updateUser: 154
updateUnreadChatCount: 154
updateChatReadOutbox: 107
updateMessageEdited: 105
updateMessageContent: 91
updateSupergroup: 60
updateMessageViews: 50
updateChatUnreadMentionCount: 7
updateMessageMentionRead: 7
updateNewChat: 6
updateMessageSendSucceeded: 5
updateRecentStickers: 3
updateChatNotificationSettings: 3
updateChatDraftMessage: 2
updateChatTitle: 2
updateMessageContentOpened: 2
updateChatPinnedMessage: 1
updateChatPhoto: 1
updateBasicGroup: 1
```

For now I simple ignore this event.

If this is OK, then I'm ok with it :)

Thanks

**Comment by levlam** [comment]
@zevlg From the log it seems that the real cause of so much `updateHavePendingNotifications` is missing cooresponding calls `closeChat` to `openChat` calls.

**Comment by zevlg** [comment]
In my client chat keeps opened until user explicitly close it, so having multiple (say 30 or 40) chats opened is ok.  Keeping chat opened is handy, so opened chat can be viewed instantly without fetching history and performing any additional actions, they are already applied in background since chat is opened. This works very well.

I'm OK with just ignoring this permanent storm of `updateHavePendingNotifications` events, so closing this issue

**Comment by levlam** [comment]
@zevlg Keeping chat opened also greately increase network usage and a number of server requests. Of course this is not a problem for a desktop app, but generally only chats with messages currently visible to the user are intended to be kept "open". You can still cache messages and show them instantly without `getChatHistory` request even the correspoding chat was closed and call `openChat` only when you need to show the messages.

**Comment by zevlg** [comment]
Hmm, sounds good!  I'll experiment, thanks.  Indeed, when I keep opened only visible chats, then there is no `updateHavePendingNotifications` events coming in

**Comment by zevlg** [comment]
Ah, I understood what was going on.  I have disabled Notifications API with "notification_group_count_max" option set to 0, so there was no "updateNotificationGroup" events delivered between "updateHavePendingNotifications" two events.  If Notifications API is enabled, then "updateNotificationGroup" event is delivered between "updateHavePendingNotifications" events.
