### ISSUE TITLE
Expected object, got JsonString

### ISSUE THREAD

**Issue by korangu** [tdlib/td#76]
what is this error message for?

i am trying to send a message with a document

`{'@type': 'sendMessage','chat_id': '123456','input_message_content': {'@type':'inputMessageDocument','document': {'@type':'inputFileLocal','path': '/path/to/file'},'caption':'1e2'},'@extra': 1.01234 }  ` 

whats wrong???

**Comment by levlam** [comment]
TDLib 1.1.0 supports formatting of caption, so it now should be of a type formattedText. See full ChangeLog here: https://github.com/tdlib/td/blob/master/CHANGELOG.md.

**Comment by korangu** [comment]
ok thanks. its solved now.

**Comment by blacksailer** [comment]
Got same error trying to sendMessage. Issue was because set ```reply_markup``` to ```null``` .  If I remove this entry, everything ok. Should null object be parsed by tdlib?

**Comment by blacksailer** [comment]
Also tdlib is sensetive to ```\n``` character

**Comment by levlam** [comment]
@blacksailer TDLib supports null. Are you sure that you have used '"reply_markup":null' and not '"reply_markup":"null"'?

**Comment by levlam** [comment]
@blacksailer What do you mean by "sensitive to \n character"?

**Comment by blacksailer** [comment]
1. I investigate little further with ```\n``` character. If put ```\n``` at the end of the json file then will be ```expected object got JsonString``` 

`std::string str = "{\n    \"@type\": \"sendMessage\",\n"
              "\"chat_id\": 394322499,\n    \"disable_notification\": false,\n   "
              " \"from_background\": false,\n    \"input_message_content\": {\n    "
              "\"@type\": \"inputMessageText\",\n        \"clear_draft\": true,\n "
              "\"disable_web_page_preview\": true,\n        \"text\": {\n      "
              "\"@type\": \"formattedText\",\n            \"entities\": [\n            ],\n"
              "\"text\": \"12346\"\n        }\n    },\n    \"reply_to_message_id\": 0\n}\n"`
2. Yep you right, there was no escape in ```null```. Thanks

**Comment by levlam** [comment]
@blacksailer Handling of trailing `\n` characters was fixed in TDLib 1.2.0. 

Original issue was also resolved, so closing this,
