### ISSUE TITLE
deleteChatHistory

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#760]
Hello , i'm using telegram-bot but the function ;
**tdbot_function({["@type"]="deleteChatHistory",chat_id=chatid,remove_from_chat_list=true},callback or dl_cb,data)** does not working , i mean the chat will not be deleted .

**Comment by levlam** [comment]
Why there are square brackets in `["@type"]`? Could you check in the TDLib's log that TDLib receives exactly the request you want to send.

**Comment by Kia-Pashang** [comment]
i build telegram-bot in this [WAY](https://github.com/rizaumami/tdbot) , and all of them were ["@type"] since i used , deleteChatHistory was working in tdlib 1.4.0 , but in 1.5.0 does not work

**Comment by levlam** [comment]
Then send TDLib's log with verbosity level 4 to @tdlib_bot.

**Comment by Kia-Pashang** [comment]
You mean you want me to set verbosity to 4 in config ??

**Comment by Kia-Pashang** [comment]
@levlam i did it.

**Comment by levlam** [comment]
The problem was in third-party client which didn't remove deleted messages. The TDLib's request works as intended.
