### ISSUE TITLE
Started build tdweb

### ISSUE THREAD

**Issue by isopen** [tdlib/td#762]
@levlam It does not always work as it should:
https://github.com/tdlib/td/blob/master/example/web/build-openssl.sh#L3
https://github.com/tdlib/td/blob/master/example/web/build-tdlib.sh#L3
On Linux, these lines may not work.

@levlam Try `! [ -x "$(emconfigure 2> /dev/null)"]` in order to remove the spaces

> For the most part, it will only hurt

**Comment by levlam** [comment]
Building `tdweb` using the latest `emsdk` was fixed in master.
