### ISSUE TITLE
ClassNotFoundException for example/java

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#763]
I generated the code at tdlib.github.io and i did whatever was written at the example/java.
But i got 
"Error: Could not find or load main class org.drinkless.tdlib.example.Example
Caused by: java.lang.ClassNotFoundException: org.drinkless.tdlib.example.Example"
after executing "java '-Djava.library.path=.' org/drinkless/tdlib/example/Example"

**Comment by levlam** [comment]
Make sure that you launching the command from the `td/tdlib` directory, in which the binaries are installed by default by the build instructions from tdlib.github.io.

**Comment by yasharzb** [comment]
This is the first step according to TDLib java example:
```
cd <path to TDLib sources>
mkdir jnibuild
cd jnibuild
cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..
cmake --build . --target install

```
if cd <path to TDLib sources> means got to /td/tdlib so there will be a problem at line 4 because there is no example/java in tdlib directory (as we changed the dir. to jnibuild)
so <path to TDLib sources> should be `/td` no `/td/tdlib`

**Comment by levlam** [comment]
First part of commands needs to be run from `td`.
The second one from `td/example/java`.
If build instructions from README.md are used then built library is placed to `td/example/java/bin`, but if build instructions from tdlib.github.io are used then everything is placed to `td/tdlib` instead.
