### ISSUE TITLE
Build build-tdlib error

### ISSUE THREAD

**Issue by isopen** [tdlib/td#764]
> [100%] Linking CXX executable td_wasm.js
> wasm-ld: error: 'atomics' feature is used by aes_cbc_4ba06c49.o, so --shared-memory must be used
> wasm-ld: error: Target feature 'atomics' used in aes_cbc_4ba06c49.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in aes_core_f7c87078.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in aes_ige_323f027d.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in b_print_0e627439.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in b_addr_efc84b8c.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in b_sock2_df4fa3c6.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in b_sock_2999f67d.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bio_lib_bc62a3a8.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bio_meth_12beb5fa.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bss_mem_21fac8cf.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bss_sock_f4c22d9b.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_add_88aa293f.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_asm_254fd33c.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_ctx_728a34b1.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_div_5735e23b.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_exp_3b7e554a.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_gcd_a48cc8c0.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_lib_9ae9ad4b.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: Target feature 'atomics' used in bn_mod_cfdb127f.o is disallowed by ConcurrentScheduler_9c364199.cpp.o. Use --no-check-features to suppress.
> wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
> shared:ERROR: '/home/user/test/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_gIzQry/td_wasm.wasm --allow-undefined --lto-O0 CMakeFiles/td_wasm.dir/td/telegram/td_emscripten.cpp.o -L/home/user/test/emsdk/upstream/emscripten/system/local/lib libtdjson_static.a -L/home/user/test/emsdk/upstream/emscripten/system/lib tdactor/libtdactor.a -L/user/.emscripten_cache/wasm-obj libtdjson_private.a libtdclient.a libtdcore.a tdnet/libtdnet.a tddb/libtddb.a tdactor/libtdactor.a tdutils/libtdutils.a sqlite/libtdsqlite.a ../crypto/lib/libcrypto.a /user/.emscripten_cache/wasm-obj/libz.a /user/.emscripten_cache/wasm-obj/libc.a /user/.emscripten_cache/wasm-obj/libcompiler_rt.a /user/.emscripten_cache/wasm-obj/libc-wasm.a /user/.emscripten_cache/wasm-obj/libc++-noexcept.a /user/.emscripten_cache/wasm-obj/libc++abi-noexcept.a /user/.emscripten_cache/wasm-obj/libdlmalloc.a /user/.emscripten_cache/wasm-obj/libpthread_stub.a /user/.emscripten_cache/wasm-obj/libc_rt_wasm.a --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export htonl --export htons --export ntohs --export emscripten_builtin_memalign --export memalign --export _get_environ --export strlen --export _get_tzname --export _get_daylight --export _get_timezone --export emscripten_builtin_free -z stack-size=5242880 --initial-memory=16777216 --no-entry --global-base=1024' failed (1)
> make[3]: *** [CMakeFiles/td_wasm.dir/build.make:98: td_wasm.js] Error 1
> make[2]: *** [CMakeFiles/Makefile2:407: CMakeFiles/td_wasm.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:419: CMakeFiles/td_wasm.dir/rule] Error 2
> make: *** [Makefile:279: td_wasm] Error 2

**Comment by isopen** [comment]
@levlam It turned out to adequately collect wasm only through the docker file from @isopen.
Tests began to build poorly.

**Comment by levlam** [comment]
Thanks, we will fix the compilation errors.

All of them are in tests, which don't need to be built at all for WebAssembly version. The updated file https://github.com/isopen/docker/blob/master/tdlib/Dockerfile.wasm always correctly specify target to build, so it has no compilation errors.

**Comment by levlam** [comment]
Compilation errors in tests for Emscripten was fixed in https://github.com/tdlib/td/commit/ba3204a5c20bed282b733d657ad3195cd991cf88.

**Comment by MattNguyen** [comment]
@levlam I'm also running into the same issues compiling to wasm even with the latest changes. I'm attempting to build on macOS.

**Comment by levlam** [comment]
@MattNguyen If you use our build instructions from https://github.com/tdlib/td/tree/master/example/web, you can't get build errors in tests, because tests are not built.

If you receive `wasm-ld: error: 'atomics' feature is used by ...` then you probably need to downgrade to some older Emscripten version, which is known to work, for example, https://github.com/emscripten-core/emscripten/releases/tag/1.38.35.

**Comment by MattNguyen** [comment]
Thanks for the quick response and suggestion!

Now I'm running into another issue.

```
[100%] Linking CXX executable generate_json
ld: warning: ignoring file ../../../crypto/lib/libcrypto.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x23 0x31 0x2F 0x31 0x32 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_OPENSSL_cleanse", referenced from:
      td::MutableSlice::fill_zero_secure() in libtdutils.a(Slice.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [td/generate/generate_json] Error 1
make[2]: *** [td/generate/CMakeFiles/generate_json.dir/all] Error 2
make[1]: *** [CMakeFiles/prepare_cross_compiling.dir/rule] Error 2
make: *** [prepare_cross_compiling] Error 2
```

Does this have to do with the following openssl build step? Would I need to change something here to build on macOS?

```
emconfigure ./Configure linux-generic32 no-shared no-dso no-engine no-unit-test no-ui || exit 1
sed -i.bak 's/CROSS_COMPILE=.*/CROSS_COMPILE=/g' Makefile || exit 1
sed -i.bak 's/-ldl //g' Makefile || exit 1
sed -i.bak 's/-O3/-Os/g' Makefile || exit 1
```

**Comment by levlam** [comment]
Did you run `./build-openssl.sh` again after downgrading Emscripten?

**Comment by isopen** [comment]
On `openssl1.0.2a` works https://github.com/isopen/docker/blob/master/tdlib/Dockerfile.wasm
