### ISSUE TITLE
GetChatHistory

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#766]
First;
I changed `case "gc":` operations in `Example.java` file to:
```
                case "gc":
                    client.send(new TdApi.GetChatHistory(getChatId(commands[1]),0, (int)getChatId(commands[2]),
                    (int) getChatId(commands[3]), false), defaultHandler);
                    break;
```
so i can modify the offset and limit.
I rebuilt the project so I could get the last 10 pms ordered by date (descending) with `gc <chat_id> 0 10`.
But I realized that after a while if I repeat it with (e.g.) `gc <chat_id> 0 10` i get **ONLY** the last message.
Where's the problem?
Second:
I found out that the maximum messages the client can get at once is 100. So I'm looking for a way to get the second last 100 messages(and even more). 
Actually the equivalent method of scrolling in GUI ver.

**Comment by isopen** [comment]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_history.html
```
The messages are returned in a reverse chronological order.
For optimal performance the number of returned messages is chosen by the library.
```
```
std::int32_t | limit_
-- | --
  | The maximum number of messages to be returned; must be positive and can't be greater than 100. If the offset is negative, the limit must be greater or equal to -offset. Fewer messages may be returned than specified by the limit, even if the end of the message history has not been reached.
```

**Comment by levlam** [comment]
@yasharzb See https://core.telegram.org/tdlib/getting-started#getting-chat-messages.

**Comment by yasharzb** [comment]
@isopen 
so you mean there is no insurance to get e.g. 10 last messages i should check it before sending it to the user.

**Comment by isopen** [comment]
Perhaps need to show the user what he managed to get and control the scroll (this may be the responsibility of the component). If you need to show specifically only the last 10 messages, then you can check (but in my opinion this is not good).

**Comment by vinifr** [comment]
Hi, Sorry. is there a getChatHistory example for C++?

**Comment by isopen** [comment]
@levlam I think it's time for a sandbox where the user can test TDLib queries. The sandbox can be filled with sample requests or a request queue.
