### ISSUE TITLE
Generate TL Schema for Java 

### ISSUE THREAD

**Issue by nickdndev** [tdlib/td#770]
We try to generate Java client using the following TL schema https://core.telegram.org/schema

We use the example generation for TD schema https://github.com/tdlib/td/tree/9293f07464276d58974164e41a4bb57d3362a258/example/java
it's ok, code was created.

And then we try to generate TL schema https://core.telegram.org/schema and change some Cmake 
properties :

1.  td-master/td/generate/CMakeLists.txt 
line 30
 from 
set(TL_TD_API_TLO ${CMAKE_CURRENT_SOURCE_DIR}/scheme**/td_api**.tlo)
set(TL_TD_API_TLO ${TL_TD_API_TLO} PARENT_SCOPE)

to 
set(TL_TD_API_TLO ${CMAKE_CURRENT_SOURCE_DIR}/scheme/**telegram_api.**tlo)
set(TL_TD_API_TLO ${TL_TD_API_TLO} PARENT_SCOPE)

2. td-master/example/java/CMakeLists.txt
line 27:
from
set(TD_API_TLO_PATH ${CMAKE_CURRENT_SOURCE_DIR}/td/bin/td/generate/scheme**/td_api**.tlo)
set(TD_API_TL_PATH ${CMAKE_CURRENT_SOURCE_DIR}/td/bin/td/generate/scheme**/td_api**.tl)

to

set(TD_API_TLO_PATH ${CMAKE_CURRENT_SOURCE_DIR}/td/bin/td/generate/scheme/telegram_api.tlo)
set(TD_API_TL_PATH ${CMAKE_CURRENT_SOURCE_DIR}/td/bin/td/generate/scheme/telegram_api.tl)

During build java code we got the following error 
/tdlib/td-master/example/java/org/drinkless/tdlib/TdApi.java:1442: error: <identifier> expected
        public True public;
                   ^
/tdlib/td-master/example/java/org/drinkless/tdlib/TdApi.java:1452: error: <identifier> expected
        public ChatInvite(True channel, True broadcast, True public, True megagroup, String title, Photo photo, Int participantsCount, User[] participants) {

"public" field is a reserved name in java and also for "static" 

Is it possible to generate java code using TL schema and handle case (for instance: https://core.telegram.org/constructor/chatInvite   "public") with reserved name in java ?

Thank you!

**Comment by levlam** [comment]
It is not possible to use TDLib's Java code generator for Telegram API scheme. For example, it doesn't support optional fields and classes having the same name as their abstract base classes. As you noted, also some names in Telegram API scheme are reserved words in some languages. Some of these problems could be hard to fix.

**Comment by nickdndev** [comment]
You mean that need to implement Telegram Client by hand ( for instance for java ) or try to find open source?

**Comment by levlam** [comment]
Why do you need Java bindings for Telegram API? Even you would have these, you would still need to implement Telegram client from scratch. It will not be possible to use them with TDLib, it doesn't work so.

If you need Java bindings for Telegram API methods and classes, you can find them in the source code of [Telegram Android](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/tgnet/TLRPC.java).

**Comment by nickdndev** [comment]
Thank you!
