### ISSUE TITLE
[Tdweb] Can not connect to server

### ISSUE THREAD

**Issue by viet0511** [tdlib/td#774]
I using Tdweb, it current stuck at connecting.

Console log: 
`WebSocket connection to 'wss://flora.web.telegram.org/apiws' failed: WebSocket is closed before the connection is established`
![image](https://user-images.githubusercontent.com/1768904/68191766-d4d60b80-ffe2-11e9-8617-5c8441cc59a5.png)

Other implement tdweb got same error: https://evgeny-nadymov.github.io/telegram-react/
The offical web app (https://web.telegram.org/) working normally. 
Is this error come from server side?

**Comment by levlam** [comment]
Make sure that Telegram is not blocked in your country. If it is blocked you need to use system-wide VPN to circumvent the block.

**Comment by viet0511** [comment]
It working now, maybe my network problem
