### ISSUE TITLE
Sending pictures

### ISSUE THREAD

**Issue by sunzh132334** [tdlib/td#775]
Which method do I need to call to send a picture to a contact?

**Comment by levlam** [comment]
You need to use `sendMessage` with `inputMessagePhoto`.

**Comment by sunzh132334** [comment]
> 您需要使用`sendMessage`带`inputMessagePhoto`。
This is the first time I've used this library.Can you give me a code example?Thank you very much!

**Comment by levlam** [comment]
See https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples.

**Comment by sunzh132334** [comment]
> 参见https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples。

This one doesn't seem to have any information about sending pictures

**Comment by sunzh132334** [comment]
> 参见https://github.com/tdlib/td/tree/master/example#tdlib-usage-and-build-examples。

Because my computer version is win7, so can not open the source code of win10 construction

**Comment by sunzh132334** [comment]
I see. Thank you
