### ISSUE TITLE
Sticker thumbnails: Download errors

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#778]
We are now trying to implement sticker support, and we get those messages when we want to download thumbnails for stickers:
```[ 2][t 4][1572979002.027608156][FileManager.cpp:3271][#1][!FileManager]    Failed to upload/download/generate file 679(0): [Error : 400 : File source is not found]. Query type = 3. File type is thumbnails```

For the time being we use the full resolution version which seems to work:
![grafik](https://user-images.githubusercontent.com/16186470/68281587-4a3feb80-0078-11ea-9a94-85a284176b72.png)

So my question is, are there thumbnails for stickers? Probably it´s a mistake by my colleague, and we should just use the full version?

**Comment by levlam** [comment]
No, there is no mistake. You need to update to TDLib 1.5.0 to fix this.
