### ISSUE TITLE
How to determine what changed in updateMessageContent

### ISSUE THREAD

**Issue by KazamaWataru** [tdlib/td#779]
I am making a chat bot. When the owner of the bot edits the message that has been sent, it needs to modify the message in the corresponding chat, through the methods such as editMessageText and editMessageCaption.

The problem is that when I receive an updateMessageContent , I can't tell what changed, because I can't get the old information, I think, when I call getMessage , it shouldn't be able to return the old one.

I think it's not a good idea to store all the messages in memory, or serialize them and save them in another database or file...

Forgive me for poor English, this is the result of Google Translate :(

**Comment by KazamaWataru** [comment]
By the way, I can compare it with messages that have been copied and sent to other chats, but what if I don't have this message?

**Comment by levlam** [comment]
You can use `getMessage` on a message you a going to change to get its current content and to find what needs to be changed.

**Comment by jagzmz** [comment]
@nekohasekai did u resolve this?
