### ISSUE TITLE
How to  upload any file  with sendMessage function 

### ISSUE THREAD

**Issue by Qasemt** [tdlib/td#78]
I found **[upload file] function** from document ,just ,i could not find **relation** between [upload file] function and sendMessage for transfer 
i'm confused :),document and c++ example  is very poor

**Comment by levlam** [comment]
UploadFile should be used only when uploaded file isn't going to be sent as a message. If you need to send a file in a message, then just call sendMessage with the corresponding InputMessageContent. File to be sent is specified there using InputFile. If you upload a local file, then just use inputFileLocal. Here is an example of the request in JSON-format:
```
{'@type': 'sendMessage','chat_id': '123456','input_message_content': {'@type':'inputMessageDocument','document': {'@type':'inputFileLocal','path': '/path/to/file'}},'@extra': 1 }
```

**Comment by isopen** [comment]
https://github.com/isopen/java/tree/master/Vanilla/app/src/main
Perhaps this will help you master tdlib.
The truth is there is bad code, but I hope you ignore it.

**Comment by isopen** [comment]
I agree the documentation is not for ordinary people like us.

**Comment by isopen** [comment]
Leo please export to pdf on one canvas. It would be much easier for me to navigate through it.

**Comment by isopen** [comment]
The tree on the site enrages. On the phone to read at all uncomfortable

**Comment by isopen** [comment]
But this is better than the documentation of Google and Microsoft for open projects.

**Comment by isopen** [comment]
Especially Microsoft.! Lately it seems that they can not cope with their projects and the pace of the market. Telegram is an excellent alternative to Skype (the new version of Skype is completely bad). About Windows and there are no questions ... It's not at all clear what became with these updates. In practice, two computers with medium iron stopped working.

**Comment by Qasemt** [comment]
**thanx :)** 

```c++
auto send_message = td_api::make_object<td_api::sendMessage>();
send_message->chat_id_ = chat id;

auto message_content = td_api::make_object<td_api::inputMessagePhoto>();
message_content->photo_ = as_local_file(path);
message_content->thumbnail_ = NULL;
message_content->caption_ = td_api::make_object<td_api::formattedText>();
message_content->caption_->text_ = std::move(caption_str);
message_content->added_sticker_file_ids_ = std::vector<INT32>();
message_content->ttl_ = 0;
message_content->height_ = 0;
message_content->width_ = 0;

send_message->input_message_content_ = std::move(message_content);

send_query(std::move(send_message), {});
```

**Comment by korangu** [comment]
@levlam  what is the use of `'@extra': 1 ` ?

**Comment by levlam** [comment]
It is used to match requests with a corresponding response. The corresponding response will have an "@extra" field with the same value.

**Comment by soshiant1992** [comment]
hi qasemt i was wondering what is your function : as_local_file(path) is. can you elaborate?

**Comment by levlam** [comment]
@soshiant1992 This is С++ code, so the function is likely to be the same as in our test client: https://github.com/tdlib/td/blob/master/td/telegram/cli.cpp#L444.

**Comment by soshiant1992** [comment]
Thnx it worked 👍
