### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by sunzh132334** [tdlib/td#781]
[Change Imported Contacts can be called only once at the same time]What does this hint mean, and how do I clear my uploaded contacts

**Comment by levlam** [comment]
It means that app need to wait response for a current `changeImportedContacts` request, before it can send new `changeImportedContacts` request. This is a high-level request, which must not be used, unless you exactly understand what it does. To clear all imported contacts, use the request `clearImportedContacts`.

**Comment by sunzh132334** [comment]
OK，thanks
