### ISSUE TITLE
loop in client:execute

### ISSUE THREAD

**Issue by ByeCoder** [tdlib/td#782]
Hello,
When I try to use some of methods ,for example `getMe `- `joinChatByInviteLink ` and ... , I got a loop of results.
This loop will repeat about x> 100 times, and after a while server-side response back a FLOOD time
I using tdlua and some methods is OK and I checked my source and it is OK too.
What is the problem?

**Comment by levlam** [comment]
The only way to receive multiple response is send multiple requests. You can enable TDLib logging and see these requests in the log.

**Comment by levlam** [comment]
Between, `getMe` could never lead to flood wait and I expect that joining a lot of chats with `joinChatByInviteLink` could easily lead to 429.

**Comment by ByeCoder** [comment]
@levlam Yes exactly multiple requests sent,but there is no loop and just execute one function.
for example:
```
 if data["@type"] == "updateConnectionState" and data.state["@type"] == "connectionStateReady" and not updatesettings then
updatesettings = true
return tdbot.getMe(tdbot.bot_info, nil)
end
```
and in tdbot.bot_info I got about 200 times result,although 200 times it requested.
But why?
