### ISSUE TITLE
How SupergroupMembersFilterSearch in GetSupergroupMembers works?

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#784]
Hi, could you please clarify how filtering for that case works?

Case: I have a supergroup with ~6500 users, I try to get users within that supergroup:

`new TdApi.GetSupergroupMembers(intChatId, new TdApi.SupergroupMembersFilterSearch("."), offset, limit)`

I suppose that I will find all users with any character in name. But this method returns me ~5496 users.
So my question is: what users were filtered?

PS: similar behavior I notice when e.g. using SupergroupMembersFilterRecent as filter, about 1000 users is missing.

**Comment by levlam** [comment]
@Mike497 Other users are likely to be deleted, but yet not removed from the member list.

**Comment by Mike497** [comment]
@levlam, thanks, as always.)

**Comment by forconz** [comment]
How to get all SupergroupMembers?
