### ISSUE TITLE
SendBotStartMessage starting the bot failed  

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#788]
``client.send(new TdApi.SendBotStartMessage(type.userId ,chat.id , "start")``

I am using ``sendBotStartMessage`` to send ``start`` to the bot.

![image](https://user-images.githubusercontent.com/46550127/68786216-5af4f080-067a-11ea-9e1f-ffebcef18833.png)

But the bot did not start

**Comment by levlam** [comment]
The message was successfully sent, so there is no problem there. Are you sure that the bot works?

**Comment by huang-ju** [comment]
I used other robots and the same problem
 
![image](https://user-images.githubusercontent.com/46550127/68820738-49860580-06c7-11ea-84cf-1652a88e3f0d.png)


What I sent
```
Message(id: 4084203529, senderUserId: 387311033, chatId: 52504489, sendingState: Optional(TDLib.MessageSendingState.pending), isOutgoing: true, canBeEdited: false, canBeForwarded: true, canBeDeletedOnlyForSelf: false, canBeDeletedForAllUsers: true, isChannelPost: false, containsUnreadMention: false, date: 1573697364, editDate: 0, forwardInfo: nil, replyToMessageId: 0, ttl: 0, ttlExpiresIn: 0.0, viaBotUserId: 0, authorSignature: "", views: 0, mediaAlbumId: "0", content: TDLib.MessageContent.messageText(text: TDLib.FormattedText(text: "/start", entities: [TDLib.TextEntity(offset: 0, length: 6, type: TDLib.TextEntityType.botCommand)]), webPage: nil), replyMarkup: nil)
```

**Comment by huang-ju** [comment]
The bot is working, I can work by manually clicking the button.

**Comment by huang-ju** [comment]
The first time you use the bot to send ``start`` is working. After deactivating the robot, resend ``start`` and the bot does not work.

![image](https://user-images.githubusercontent.com/46550127/68842204-fe88e400-0700-11ea-9dfb-cdee93e855db.png)

**Comment by levlam** [comment]
If the message "/start" is sent, then `sendBotStartMessage` works, because in private chats this is the only thing the method does. Try the same from an ordinary client.

**Comment by huang-ju** [comment]
I solved the problem with ``UnblockUser``, thank you!
