### ISSUE TITLE
searchChatsOnServer after creating new chat returns empty list

### ISSUE THREAD

**Issue by MattNguyen** [tdlib/td#789]
I'm attempting to search for a new chat created from `createNewBasicGroupChat` and `createNewSupergroupChat` via `searchChatsOnServer`. However, the new chats do not appear in the search results until _after_ I restart tdlib--at which point the same query results in the correct chats being returned.

Couple other notes:
- I see `updateNewChat` and other update events relating to the newly created chat
- I have the following parameters:
```
			"@type":                    "tdlibParameters",
			"use_test_dc":              "0",
			"database_directory":       dbFolder,
			"files_directory":          dbFolder,
			"use_file_database":        true,
			"use_chat_info_database":   true,
			"use_message_database":     true,
			"use_secret_chats":         false,
			"api_id":                   env("TELEGRAM_API_ID", ""),
			"api_hash":                 env("TELEGRAM_API_HASH", ""),
			"system_language_code":     "en",
			"device_model":             "App",
			"system_version":           "0.1.0",
			"application_version":      "0.1.0",
			"enable_storage_optimizer": true,
			"ignore_file_names":        false,
```
- I've tried calling `getChatHistory` and `getChat` after creating the new chat to see if that would change anything, but to no avail

Any help would be appreciated! Thanks!

TDLib Version: 1.5

**Comment by levlam** [comment]
Result of `searchChatsOnServer` is cached until client restart.

This is not a problem, because `searchChatsOnServer` is designed to complement `searchChats` and only add to its results chats unavailable locally. The just created chat can be successfully found by `searchChats`, so there is no practical reason for it to be returned by `searchChatsOnServer`.

**Comment by MattNguyen** [comment]
Make sense, thanks!
