### ISSUE TITLE
"td_json_client_create " how it's work?

### ISSUE THREAD

**Issue by msh15** [tdlib/td#79]
when i build and try to run the example i just see this 
![capture](https://user-images.githubusercontent.com/35134604/36199588-377af960-118f-11e8-9205-202fae1335a5.PNG)
so...
what is this?!
i know these json stuff that printed out here is in python code,
but i can't understand how it authenticated and big question is
"why it's just not to try connect to actual telegram user?"

**Comment by levlam** [comment]
No, it isn't Python code. It is incoming updates from the TDLib. td_json_client documentation can be found here: https://core.telegram.org/tdlib/docs/td__json__client_8h.html.

**Comment by msh15** [comment]
I read the docs in telegram website and even
struggled with c++ codes,
but i coudn't figured it out the authentication flow.
actually libraries like [Telethon ](https://github.com/LonamiWebs/Telethon) is so easy to use and it's straight forward.

**Comment by msh15** [comment]
Alright, i read the documentation but there isn't a single clue or a simple hint to build a client with api_id and api_hash.
is that like developers have to make authentication and signing an logging in from scratch?

**Comment by levlam** [comment]
You can see example of authorization flow in the С++ or Java example:
https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java.

Unlike Telethon login examples it provides handling for all possible errors and allows everything that is allowed by Core Telegram API. Nobody forbids to write a simple wrapper around raw TDLib methods, which will simplify logging, but these methods can't be at the core of the library.

api_id and api_hash are not specific to JSON interface, they should be specified in the setTdlibParameters request.

**Comment by msh15** [comment]
Thanks for explanation.
let me try more :-D

**Comment by levlam** [comment]
Authorization as everything else is update driven, so to properly authorize you need to handle UpdateAuthorizationState. For example, you have received authorizationStateWaitTdParameters which means that you should call setTdlibParameters to proceed.

**Comment by msh15** [comment]
Hi again,
I was trying to send a request with {'@type': 'setTdlibParameters '}
however i got this every time:
{u'message': u'Valid api_id must be provided. Can be obtained at https://my.telegram.org', u'code': 400, u'@extra': None, u'@type': u'error'}.
I use something like this:
{'use_test_dc_': False,
'database_directory_': '',
'files_directory_': '',
'use_file_database_': False,
'use_chat_info_database_': False,
'use_message_database_': False,
'use_secret_chats_': False,
'api_id_': 18**, #myAppIdFromTelegram
'api_hash_': '**myAppHashFromTelegram**',
'system_language_code_': 'en',
'device_model_': 'DESKTOP',
'system_version_': '',
'application_version_': '1.0',
'enable_storage_optimizer_': False,
'ignore_file_names_': False}
I was struggling with that request until now, i don't know where i did it worng.
