### ISSUE TITLE
Getting "Chat not found" -error

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#791]
Hey,
I'm using tdlib now for a while. But out of nowhere, I get a lot of those errors
> {'@type': 'error', 'code': 5, 'message': 'Chat not found'}

But I'm pretty sure I'm using the right chat_id. Are there other possibilities this error could occur?

**Comment by MalteToenjes** [comment]
Okay now I'm calling getChats for every message I sent. I thought this is obsolete since I'm calling this right after login with tdlib.
However this solved the issue...

**Comment by valoricDe** [comment]
Thank you for pointing out. Live saver xD

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/578. This particular issue is about user identifiers, but everything written there can be also applied to chat identifiers.

**Comment by MalteToenjes** [comment]
I have one more question to this behavior: getChats only works if the user has an active chat with me right? So if he removes the chat von chatlist I will get the error "chat not found". But if he saved my number in his contactlist I also could call getContact right? 
So what happens if I build my send_message function like this:
`getChatgetContact
sendMessage
`

**Comment by levlam** [comment]
@MalteToenjes If message database is enabled, you need to only once receive a chat with the user in any way. After that you can use the chat without any additional requests.

**Comment by MalteToenjes** [comment]
Thanks for your reply. But still when the user delete/clear the chat from chatlist I will get a "Chat not found" - Error or? Because I still get some of those I would like try to understand why they came sometimes

**Comment by levlam** [comment]
@MalteToenjes "the user delete/clear the chat from chatlist" is not related to "chat not found". Only the way you get the chat is related. If chat can't be received the way you are trying to get it, then the error happens.
