### ISSUE TITLE
Message ID

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#792]
Hi. I noticed that the messageId I get in TDLib client is different from the messageId I see in "copy post link" in telegram. At first it's 1425014784 and in the second it's like:

> https://t.me/channelName/messageCountNo

I had another client in python using a library which I inserted the _**messageCountNo**_ as the message Id of a channel and it was working. Also I found out that in your client I get another Id for message which is the multiple of **_messageCountNo_** and the coefficient is always 1048576.
What's the reason?

**Comment by levlam** [comment]
For the reasons see https://github.com/tdlib/td/issues/69.

To get a link to a message use method `getMessageLink` or `getPublicMessageLink`. To get a message from a link use method `getMessageLinkInfo`.
