### ISSUE TITLE
PEER_FLOOD when sending message

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#797]
Hi,
Could you please help to understand the behavior of PEER_FLOOD error when sending direct messages? I have an account that actually is not banned (I've checked via @ SpamBot). But, when it is sending messages to some accounts, MessageSendingState says that there is PEER_FLOOD. Maybe it is about the fact that it was banned before?
This account still can send to other people with no issues.

UPD: I'm not sure if it is related, but I also notice that time to time this account is also getting "Not found" error for GetChatMessageByDate function.

**Comment by levlam** [comment]
PEER_FLOOD error is received when the account tries to send private messages to too much non-mutual contacts.

This can't be related to calls to `GetChatMessageByDate`.
