### ISSUE TITLE
next_code_type is always null

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#798]
I want to use ``ResendAuthenticationCode`` but ``next_code_type`` is always null

![image](https://user-images.githubusercontent.com/46550127/69013054-d1fdf200-09b6-11ea-9689-96289628d00a.png)

**Comment by levlam** [comment]
`next_type` is defined by the server. If it is null, then all possibilities available for code sending are exhausted and client can't ask the server to resend the code.

**Comment by huang-ju** [comment]
Do I have other ways to request SMS?

**Comment by levlam** [comment]
No. The SMS was already sent, so user can enter the code after the SMS is received.

**Comment by huang-ju** [comment]
When my account is not registered, I can't receive the SMS. When my account is registered, I can receive the SMS.

**Comment by levlam** [comment]
Do you use TDLib 1.5.0?

**Comment by huang-ju** [comment]
yes

**Comment by levlam** [comment]
Then the answer from https://github.com/tdlib/td/issues/728 still applies.

**Comment by huang-ju** [comment]
I still have not received it, ``Sms@telegram.org`` did not reply to me

**Comment by levlam** [comment]
Could you collect TDLib log with verbosity level 4 and send it to @tdlib_bot in Telegram?

**Comment by levlam** [comment]
It can be a protection from automatic account registration and subsequent spam. You can write to recover@telegram.org your phone number and description of the problem, if you believe that this is an erroneous ban.
