### ISSUE TITLE
Static version of tdjson?

### ISSUE THREAD

**Issue by L11R** [tdlib/td#8]
I am using Golang with C-bindings to use this lib, but I also want to compile static binary. There is shared version `/usr/local/lib/libtdjson.so`, but there is no static one. I tried to use `libtdjson_static.a`, but seems like this is works for C++ only.

**Comment by levlam** [comment]
We haven't tested static linking of the libtdjson_static library to Golang code, but it looks like Golang (using cgo) supports static linking of С libraries and everything should work fine. You will also need to statically link TDLib dependencies, namely libcrypto, libssl, libz and standard C++ library (libc++/libstdc++). What errors do you get?

**Comment by L11R** [comment]
@levlam seems like the libs order occured the problem. After researching CMakeLists.txt I recover order:
```golang
/*
#cgo LDFLAGS: -ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdactor -ltddb -ltdsqlite -ltdnet -ltdutils -lstdc++ -lssl -lcrypto -ldl -lz -lm
#include <stdlib.h>
#include <td/telegram/td_json_client.h>
#include <td/telegram/td_log.h>
*/
import "C"
```
After this I compiled the binary, but with few warnings:
```bash
//usr/local/lib/libtdsqlite.a(sqlite3.c.o): In function `unixDlOpen':
sqlite3.c:(.text+0x15b17): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libtdutils.a(IPAddress.cpp.o): In function `td::IPAddress::init_host_port(td::CSlice, td::CSlice)':
IPAddress.cpp:(.text._ZN2td9IPAddress14init_host_portENS_6CSliceES1_+0x244): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by levlam** [comment]
I have a few suggestions for you:
1. You can try to manually remove calls to some glibc functions that can't be linked statically.
In order to remove call to dlopen in sqlite, just add
target_compile_definitions(tdsqlite PRIVATE -DSQLITE_OMIT_LOAD_EXTENSION)
In order to remove call to getaddrinfo, replace function in tdutils/td/utils/port/IPAddress.cpp with
Status IPAddress::init_host_port(CSlice host, CSlice port) {
  return Status::Error("Unsupported");
}
There is no critical functionality in TDLib which depends on that function, it should work fine.
2. As noted in the linked by you article, you can try to use another libc,, for example, musl.

**Comment by L11R** [comment]
@levlam thanks for suggestions!
1. I tried first one, two warnings were disappeared, but appeared another one :cry: 
```
/usr/lib/x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
2. As I understood correctly, I should compile TDLib with musl, but I got many errors, like:
`/home/savely/td/sqlite/sqlite/sqlite3.c:20258:26: fatal error: openssl/rand.h: No such file`
I tried to add `-I/usr/include` at `sqlite/CMakeLists.txt`, but then got another errors, tried to solve them, but they appearing "avalanche-like".

**Comment by levlam** [comment]
1. This comes from OpenSSL now. You could try to build OpenSSL from sources with `no-dso` configure option, which should remove calls to dlopen. 
2. You probably also need to recompile OpenSSL and zlib with musl and specify musl-compiled libraries as dependencies when building TDLib, It doesn't sounds like an easy way.

**Comment by L11R** [comment]
@levlam thanks for advices. For me easier to link against static TDLib only. Other libs like OpenSSL, ZLib and others is simpler to install on target system from package manager.

**Comment by Arman92** [comment]
I have a full tdlib-tdjson binding package here (Autogenerated all types/methods from tdlib.tl)  : https://github.com/Arman92/go-tdlib
