### ISSUE TITLE
Leo is missing VC

### ISSUE THREAD

**Issue by isopen** [tdlib/td#80]
```
Windows
Download and install gperf. Add the path to gperf to the PATH environment variable.
Install vcpkg.
Run the following commands:
C:\src\vcpkg> .\vcpkg install openssl zlib
Build TDLib with CMake as explained in building, but instead of cmake -DCMAKE_BUILD_TYPE=Release .. use
cmake -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake ..
```
C:\src\vcpkg> .\vcpkg install openssl zlib (you will need a VC and a language pack VC)
A suitable version of cmake was not found (required v3.10.2). Downloading portable cmake v3.10.2...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
Could not locate a complete toolset.

I think you forgot to write about it in the instructions.

**Comment by levlam** [comment]
This is one of the dozens of errors which can happen while building library dependencies with vcpkg and it has no direct relation to the TDLib. We can't mention every such error in the README.

**Comment by isopen** [comment]
I agree, but errors can be categorized for platforms and collected on specific pages. Therefore, in the future, it may be easier to target new users. Thus, you can unload yourself from monotonous work. Unless, of course, you are not a fan of answers to similar questions.
