### ISSUE TITLE
Login Widget for Android

### ISSUE THREAD

**Issue by mghatiya** [tdlib/td#800]
Hi,

I am building an android app for telegram users. For that I need to authenticate the users.

What I have found so far is one way of doing that using Login Widget, and another is using TDLib. 

However, I am not able to figure out a way to add Login Widget to my Android App. All those seem to be suitable for websites only. Do I need to include Login widget as webview in the app? Although I tried that and even that is not working.

And looks like TDLib helps in building one's own fully custom solution like Telegram. e.g. I can create my own interface for login, chat etc.

However, I don't want that. I want to first just authenticate the users of Telegram using Telegram's standard login interface, just like how people login using Google's OAuth. Then I want to access other APIs.

How does one go about doing that? [TDLib Example](https://github.com/tdlib/td/tree/master/example/java) given here seems to have command line based interface for log-in (or so it seems to me by looking at the code, as I couldn't quite compile it). 

I don't want to implement full login process myself, and would just like to reuse existing one.

I have included pre-built library of TDLib, but I couldn't locate any widget kind of thing there.

Please advise.

Thanks,
Mukesh

**Comment by levlam** [comment]
Login Widget is not suitable for login to Telegram, it is a widget for logging in third-party website using ID, name and photo from a Telegram account.

TDLib doesn't provide an interface for user log in, you need to write it yourself.

If you want an app with an interface, you can try to clone official Android app https://github.com/DrKLO/Telegram.

**Comment by mghatiya** [comment]
Thanks Aliaksei.

I'll have to build that on my own, then. That does sound like something that should be used by many though, I thought.

Just checking: Is my need an unusual one? How would anybody else build a companion application on top of Telegram? By using one of such interfaces, right? I think I have seen that Facebook, Google, Pocket provide such interface.

**Comment by levlam** [comment]
What exactly do you mean by a "companion application"? I'm pretty sure that Facebook and Google doesn't provide anything for that, because they apps are usually closed source.

**Comment by mghatiya** [comment]
Companion App: In my view it is an app that complements functionality of the main app. e.g. Some people have built apps on top of google maps app to provide some functionalities that Google Maps in itself doesn't provide. I had read this term somewhere and thought that it is a standard term.
Maybe I am using the wrong terminology. But here is what I meant by FB, Google, Pocket providing the login widget.

Facebook:
If you see on this page (https://developers.facebook.com/docs/facebook-login/android) when users use "Login with facebook" in the third party app, facebook authenticates and returns an "access token" that can be used for further API calls as that user.

As the documentation says ```When people log into your app with Facebook they can grant permissions to your app so you can retrieve information or perform actions on Facebook on their behalf.```

Similar is the process on Google: https://developers.google.com/identity/protocols/OAuth2

I used similar one on Pocket: https://getpocket.com/developer/docs/authentication

In all these cases, the application invokes the Login or the authorisation screen/widget/button of FB/Google/Pocket etc. and gets an access token in return for making subsequent calls. 

Of course there are API calls involved to get these things done, but the interface in itself where users enter the credentials is owned by these authorisation providers.

Am I using wrong terminology, or wrong examples? Did I explain my use-case incorrectly?

Sorry, I am no expert at these things, so I might have messed up.

**Comment by levlam** [comment]
There is no way to do anything on behalf of a Telegram user unless the user is logged in your Telegram application. In the latter case the application can do anything an ordinary application can do.

If you want to add some functionality to a Telegram app, the simplest way is to clone existing application for a target platform and modify its source code. Source code of the Telegram Android app is available at https://github.com/DrKLO/Telegram.

If you don't want to use existing interface, or it would be simpler to write the interface from scratch, then you can use TDLib and create your own app.

**Comment by mghatiya** [comment]
I don't want to enhance Telegram itself per se. I think it is great. 

Just some bits. e.g. Say, in my application I would just show the latest messages a user has received on their telegram account, or will show information about their channels etc. 

My application would have other pieces too, not just Telegram. Just that I would ask users that if they want to show Telegram information, they should login to Telegram and then I can fetch data on their behalf and show.

**Comment by levlam** [comment]
Then it would be simpler for you to use TDLib and embed logging in Telegram in your app interface.

**Comment by mghatiya** [comment]
Hmmm, okay. Sure.

Wish there was a direct login interface of Telegram that I could use to authenticate. 

Thanks for your help though.

**Comment by mghatiya** [comment]
I have written my small login widget now. But it looks ugly.

Other than that, I think it would be good if Telegram did provide such interface directly. I didn't feel very comfortable writing an interface where I take user's "login code" and pass it on to Telegram. Didn't seem very secure.

Ideally, they should directly supply login code etc. to Telegram for my kind of app.

**Comment by VishalMalhotra** [comment]
@mghatiya I want to use telegram login button for user authentication but hasn't found any suitable code.It would be great if you please share your stuff
