### ISSUE TITLE
Cloning tdlib databases - prevent eavesdropping?

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#802]
Hello,

we did a few tests involving security of data stored in tdlib - including to make a full copy of the App data directories. As expected, the new copy could log in to Telegram and read chats, including secret ones. Question is how could we avoid that?
The tdlib DBs are encrypted, and thats fine. But could we find a way for including a device unique ID into that so that tdlib wont even start on a copy of the data?

**Comment by levlam** [comment]
`setDatabaseEncryptionKey` must be used for that. See https://github.com/tdlib/td/issues/188 for the ways it can be used.

Between, if both apps will be used simultaneously, it will be noticed by the server and the user will be logged out.

**Comment by Flohack74** [comment]
Ok thx!
