### ISSUE TITLE
Using getChatStatisticsUrl

### ISSUE THREAD

**Issue by mghatiya** [tdlib/td#804]
I am trying to use ```getChatStatisticsUrl```

The documentation on [this link](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_statistics_url.html) seems to indicate that I need to pass some "parameters", and only description that I get everywhere for this field is this: 
```Parameters from "tg://statsrefresh?params=******" link.```

But how does one access this ```tg://``` url to understand the list of parameters? And what is the format to send this parameters? Should we send them in JSON?

I tried empty string for parameter, but I am getting error ```PEER_ID_INVALID``` .

I also looked at the TDLib code, and following links, but couldn't figure it out.
https://core.telegram.org/method/messages.getStatsURL
https://core.telegram.org/type/StatsURL

It would be great if you could guide me here.

While we are at it, could you also suggest how do I identify whether the ```channel``` that I am looking at belongs to me or someone else? i.e. the author/admin of it is me or someone else.

Thanks,
Mukesh

**Comment by levlam** [comment]
There is also a field `supergroupFullInfo.can_view_statistics`, which indicates whether `getChatStatisticsUrl` can be called for the channel. Currently this field is false for all channels, because the feature is disabled server-side.

To find your privileges in a supergroup or a channel, you can check the field `supergroup.status`.

**Comment by mghatiya** [comment]
Oh, the feature is disabled itself. Thanks for letting me know. I spent my whole of yesterday trying to make it work. 

I don't see the fields ```supergroupFullInfo.can_view_statistics``` and ```supergroup.status``` in my 'chat' object. Do I have to query Group for that?

**Comment by levlam** [comment]
`supergroup` and `supergroupFullInfo` are separate objects. `chat` has `type` field, which will be of type `chatTypeSupergroup` for supergroups and channels.

**Comment by mghatiya** [comment]
Thanks for your help and guidance Aliaksei, as always!
