### ISSUE TITLE
History for supergroup created from basicgroup

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#805]
For supergroups created from basicgroups `getChatHistory` returns old messages only until "messageChatUpgradeFrom" message.  In official client preceding messages are also shown in chat window.

What is the correct method to fetch messages preceding "messageChatUpgradeFrom" message?

Thanks

**Comment by c0re100** [comment]
You need to get Supergroup full info(getSupergroupFullInfo) first.
And getChatHistory by basic group id (upgraded_from_basic_group_id).

ref: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1supergroup_full_info.html

**Comment by levlam** [comment]
@c0re100 is correct.

`messageChatUpgradeFrom` contains `basic_group_id`. Client needs to call `createBasicGroupChat` to get corresponding `chat` object, and then fetch older messages from the received basic group chat. `messageChatUpgradeFrom` and `messageChatUpgradeTo` are skipped in message history by clients in that case.
Also a case when the user never was a member of the basic group needs to be handled with care.

**Comment by zevlg** [comment]
Thanks for your replies!

**Comment by MarioSaldanhaLobo** [comment]
Can't you just add 1000000000000 to supergroupId?

**Comment by levlam** [comment]
@MarioSaldanhaLobo No, this is a very incorrect way.

**Comment by forconz** [comment]
@c0re100 GetChatHistory(long chatId, long fromMessageId, int offset, int limit, bool onlyLocal);

how to get chatId? is it SupergroupFullInfo.LinkedChatId?
how to get fromMessageId? is it SupergroupFullInfo.UpgradedFromMaxMessageId?

How can I get Chat Members from Supergroup?

_client.Send(new TdApi.GetSupergroupMembers(supergroupId, new TdApi.SupergroupMembersFilterContacts(), 0, 100), _defaultHandler);
_client.Send(new TdApi.GetSupergroupMembers(supergroupId, new TdApi.SupergroupMembersFilterAdministrators(), 0, 100), _defaultHandler);
_client.Send(new TdApi.GetSupergroupMembers(supergroupId, new TdApi.SupergroupMembersFilterBots(), 0, 100), _defaultHandler);

return nothing...

**Comment by c0re100** [comment]
> @c0re100 GetChatHistory(long chatId, long fromMessageId, int offset, int limit, bool onlyLocal);
> 
> how to get chatId? is it SupergroupFullInfo.LinkedChatId?
> how to get fromMessageId? is it SupergroupFullInfo.UpgradedFromMaxMessageId?
> 
> How can I get Chat Members from Supergroup?
> 
> _client.Send(new TdApi.GetSupergroupMembers(supergroupId, new TdApi.SupergroupMembersFilterContacts(), 0, 100), _defaultHandler);
> _client.Send(new TdApi.GetSupergroupMembers(supergroupId, new TdApi.SupergroupMembersFilterAdministrators(), 0, 100), _defaultHandler);
> _client.Send(new TdApi.GetSupergroupMembers(supergroupId, new TdApi.SupergroupMembersFilterBots(), 0, 100), _defaultHandler);
> 
> return nothing...

Checkout TDLib doc first...........
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_history.html

**Comment by georgehazan** [comment]
> `messageChatUpgradeFrom` contains `basic_group_id`. Client needs to call `createBasicGroupChat` to get corresponding `chat` object, and then fetch older messages from the received basic group chat. `messageChatUpgradeFrom` and `messageChatUpgradeTo` are skipped in message history by clients in that case. Also a case when the user never was a member of the basic group needs to be handled with care.

@levlam and if it doesn't work, what shall I do?

```
message {
      id = 1048576
      sender_id = messageSenderChat {
        chat_id = -1001985055038
      }
      chat_id = -1001985055038
      ...
      content = messageChatUpgradeFrom {
        title = "Telegram Test Chat"
        basic_group_id = 657860855
      }
}

createBasicGroupChat {
  basic_group_id = 657860855
  force = true
}
chat {
  id = -657860855
  type = chatTypeBasicGroup {
    basic_group_id = 657860855
  }
  title = "Telegram Test Chat"
}

getChatHistory {
  chat_id = -657860855
  from_message_id = 0
  offset = 0
  limit = 100
  only_local = false
}
error {
  code = 400
  message = "PEER_ID_INVALID"
}
```

**Comment by levlam** [comment]
@georgehazan
The error means that the user never was a part of the basic group (or was banned there) and can't get its message history.

**Comment by georgehazan** [comment]
> [@georgehazan](https://github.com/georgehazan) The error means that the user never was a part of the basic group (or was banned there) and can't get its message history.

I was a member of this group from the very beginning, and wasn't banned there for sure. There's another packet about this basic group, which I can't understand:

updateBasicGroup {
  basic_group = basicGroup {
    id = 657860855
    member_count = 0
    status = chatMemberStatusBanned {
      banned_until_date = 0
    }
    is_active = false
    upgraded_to_supergroup_id = 1985055038
  }
}

Perhaps, it should mean that I cannot access it anymore, but, as I said above, the official client loads the basic group's history easily

**Comment by levlam** [comment]
`chatMemberStatusBanned` means exactly that the user never was a part of the basic group (or was banned there).

Recheck that you are trying to get history in the correct basic group.

**Comment by georgehazan** [comment]
> `chatMemberStatusBanned` means exactly that the user never was a part of the basic group (or was banned there).

that's our test group, so I was excluded from it a couple of times, and then re-added back. The very first message in a supergroup is dated by November 2024, and that's what I see in the official client, for example

<img width="623" height="583" alt="Image" src="https://github.com/user-attachments/assets/c59e571d-81a9-42d9-8c24-400cb774c300" />

**Comment by levlam** [comment]
Did you see the messages after a fresh login?

**Comment by georgehazan** [comment]
> Did you see the messages after a fresh login?

yes, just uninstalled Telegram from the phone, returned it back and fetched all histories for this chat till year 2023

![Image](https://github.com/user-attachments/assets/8f355a8c-e1c1-415f-b40d-629e6dbbe0f8)

**Comment by levlam** [comment]
Could you send TDLib logs with verbosity level 4 to https://t.me/tdlib_bot?

**Comment by georgehazan** [comment]
> Could you send TDLib logs with verbosity level 4 to https://t.me/tdlib_bot?

Done, from my Telegram account 95495360
