### ISSUE TITLE
[Arch Linux] Building a Telegram client

### ISSUE THREAD

**Issue by furanzoni** [tdlib/td#806]
I am new to this. I built and installed Arch's AUR tdlib package: `telegram-tdlib`. Now what can I do to have a functional Telegram client? Many thanks.

**Comment by levlam** [comment]
https://core.telegram.org/tdlib/getting-started

**Comment by furanzoni** [comment]
> [core.telegram.org/tdlib/getting-started](https://core.telegram.org/tdlib/getting-started)

Sorry, but I can't seem to find actually where they say how you can build a Telegram desktop linux client with TDLib.

**Comment by levlam** [comment]
You need to program UI for the client using provided by TDLib updates and methods in your preferred programming language.
