### ISSUE TITLE
 Failed to parse `setLogVerbosityLevel` request

### ISSUE THREAD

**Issue by esindger** [tdlib/td#808]
I try to set log level after creating TDLib client. I send the following request:
```
{"new_verbosity_level":1,"@extra":"q1","@type":"setLogVerbosityLevel"}
```

and have this error:

```
[ 1][t 0][1574753677.624523163][ClientJson.cpp:71]      Failed to parse [request:{\0042new_verbosity_level\0042:1,\0042@extra\0042:\0042q1\0042,\0042@type\0042:\0042setLogVerbosityLevel\0042}] [Error : 0 : Unknown class]
```

<img width="678" alt="Снимок экрана 2019-11-26 в 15 39 34" src="https://user-images.githubusercontent.com/5320711/69608721-ff0b6e00-1062-11ea-9e87-fe86e1f62448.png">

What can be wrong?

**Comment by levlam** [comment]
It can be old TDLib < 1.4.0.
