### ISSUE TITLE
How to check what chat a channel's "Discuss" button links to?

### ISSUE THREAD

**Issue by nullpilot** [tdlib/td#809]
I can't seem to find the linked chat of channels I am in. As channels are considered supergroups, I would have expected this information to be part of the supergroup or supergroupFullInfo calls for channels I am a member of, but that doesn't seem to be the case. So I'm wondering how to get that info.

Thanks!

**Comment by levlam** [comment]
Discussion groups are not supported yet in the latest pubic TDLib version 1.5.1.

In TDLib 1.5.2 new fields `supergroup.has_linked_chat` and `supergroupFullInfo.linked_chat_id` was added, but this version is still private.

**Comment by nullpilot** [comment]
Ah, perfect. Thank you for the info.

Is there a rough ETA for 1.5.2?

**Comment by levlam** [comment]
No, there is no ETA.

**Comment by levlam** [comment]
Discussion groups support was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
