### ISSUE TITLE
Caption for inputMessageSticker

### ISSUE THREAD

**Issue by seiya-git** [tdlib/td#81]
Hello. If send sticker by file id using inputMessageDocument class you can specify caption, but using inputMessageSticker you can't. Why? It seems that it returns the same result.

Example: https://t.me/tdlibjs/7

![default](https://user-images.githubusercontent.com/7394323/36257057-1e31e8ea-125e-11e8-9818-9106e6d59f3f.png)
```
{
	"@type": "sendMessage",
	"chat_id": -1001395643121,
	"input_message_content": {
		"@type": "inputMessageDocument",
		"document": {
			"@type": "inputFileRemote",
			"id": "CAADAgADeTkAAuCjggcO05L969heuwI"
		},
		"caption": {
			"@type": "formattedText",
			"text": "test caption"
		}
	}
}
```

**Comment by Hamper** [comment]
But official client (in particular android and linux desktop) show this caption in preview to message link and may be useful some times.

**Comment by levlam** [comment]
It sounds like a preview bug, because the caption isn't shown on the sticker in a chat.
