### ISSUE TITLE
Getting flooded (400) erros just with new telegram account

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#810]
I got a new phone number and just activated it with telegram and connected it to tdlib.
Now I get a strange behavior and I'm getting flooded errors with code 400 when I'm sending messages to a few other users. I'm wondering because its happens also when I just send around 20 messages in 5 minutes.
The strange thing is, there was no problem with another telegram account (which I connected with tdlib api) I used before. There I also could send more messages without getting any issue. 

It feels my new telegram accounts is like blacklisted or something? Is there any possibility?

**Comment by levlam** [comment]
Telegram has a lot of spam-protecting measures, so there is nothing surprising that your account is quickly blocked.

**Comment by ngnam** [comment]
Telegram has a lot of spam-protecting measures, so there is nothing surprising that your account is quickly restricted.
