### ISSUE TITLE
Problem installing with tdlib 1.5

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#811]
Designed github : https://github.com/vysheng/tdbot
I am experiencing the following error while installing, and thank you for publishing the TDLIb-compatible files:
`Scanning dependencies of target telegram-bot
[ 98%] Building CXX object CMakeFiles/telegram-bot.dir/main.cpp.o
In file included from /root/tdbot/cliclient.hpp:20:0,
                 from /root/tdbot/main.cpp:20:
/root/tdbot/td/td/tl/tl_json.h:45:63: error: ‘to_json’ is not a member of ‘td::td_api’
 auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(jv, t)) {
                                                               ^
/root/tdbot/td/td/tl/tl_json.h:45:63: note: suggested alternative:
/root/tdbot/td/td/tl/tl_json.h:37:13: note:   ‘td::to_json’
 inline void to_json(JsonValueScope &jv, const JsonVectorInt64 &vec) {
             ^
/root/tdbot/td/td/tl/tl_json.h:45:63: error: ‘to_json’ is not a member of ‘td::td_api’
 auto lazy_to_json(JsonValueScope &jv, const T &t) -> decltype(td_api::to_json(jv, t)) {
                                                               ^
/root/tdbot/td/td/tl/tl_json.h:45:63: note: suggested alternative:
/root/tdbot/td/td/tl/tl_json.h:37:13: note:   ‘td::to_json’
 inline void to_json(JsonValueScope &jv, const JsonVectorInt64 &vec) {
             ^
CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:162: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2`

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/712#issuecomment-536477650.
