### ISSUE TITLE
Telegram "Another authorization query has started" Code: 9 error

### ISSUE THREAD

**Issue by elwoodprox** [tdlib/td#812]
Hi, 

I am trying to use TDlib with Java client using an Indian phone number and an Indian proxy, and get the following state and error codes. 

Connection State: "ConnectionStateConnectingToProxy" 
Authorization State: "AuthorizationStateWaitPhoneNumber"

_Error {
  code = 9
  message = "Another authorization query has started"
}_

When doing the same with no proxy, it works OK. 
Off course, I have checked the proxy and it is alive and accessible. 

I would appreciate if you can advise on what could be the problem. 

Thanks in advance, 
Elwood

**Comment by levlam** [comment]
The error means that app sends two or more authorization requests to TDLib simultaneously. This doesn't depend on using proxy, solely on a source code of your app.

**Comment by xyunsh** [comment]
Is it possible to cancel the authentication requests?

**Comment by levlam** [comment]
@xyunsh For this you need to call `logOut`, wait for the current instance to be closed, and create new TDLib instance. In rare cases, when there are no pending requests, you can call `setAuthorizationPhoneNumber` again without full logging out.

**Comment by xyunsh** [comment]
> @xyunsh For this you need to call `logOut`, wait for the current instance to be closed, and create new TDLib instance. In rare cases, when there are no pending requests, you can call `setAuthorizationPhoneNumber` again without full logging out.

Thanks a lot
