### ISSUE TITLE
Linking to Image URL 

### ISSUE THREAD

**Issue by stanleyG123** [tdlib/td#813]
I was wondering if it were possible to generate a link to an image in a post. Say I don't want to download an image and store it on my system, would it be possible to generate a link to an image to be opened in Telegram Web Client? 

something like : https://web.telegram.org/<imageId>

**Comment by levlam** [comment]
No, this is impossible.

**Comment by stanleyG123** [comment]
thanks

**Comment by levlam** [comment]
But if the chat has is a supergroup/channel with a username, you can generate a link to the whole post via the method `getPublicMessageLink`.

**Comment by stanleyG123** [comment]
The goal for me is to not store media on my servers. I think I will write an api that will get an image using tdlib and expose it via http for my web/android apps to use.
