### ISSUE TITLE
Problem hanging the robot while clearing messages in several groups

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#814]
If the robot is in a large number of groups and there are several message cleansing operations, the robot will have difficulty receiving the information.
Is there a solution to this problem?
Tdlib version used: 1.4

**Comment by levlam** [comment]
I don't understand the exact problem. What exactly happens and when?

**Comment by BarnameESF** [comment]
The robot is connected to tdlib 1.4 .
The robot is active in 250 active groups.
When several groups of 250 groups clear the group's messages , tdlib disrupts and stops for a few seconds to a minute , During this time no information is passed from tdlib to script.
This sudden halt to tdlib and the volume of new messages cause the robot to slow down and become out of service, and the robot is not serviced.
Is there a solution in the top group if tdlib does not stop receiving new information if multiple groups clear the group messages?

**Comment by levlam** [comment]
There should be no problem at all. TDLib handles much bigger load in Bot API. Could you send TDLib's log with verbosity level 4, which is collected when the issue happens to @tdlib_bot in Telegram.

**Comment by BarnameESF** [comment]
See photo: [link](http://uupload.ir/files/xh39_screenshot_(59)_li.jpg)

**Comment by levlam** [comment]
This is an ordinary network problem, which is not related in any way to what happens in chats with the bot.

**Comment by levlam** [comment]
It also doesn't affect performance, because connection is immediately reestablished.

**Comment by BarnameESF** [comment]
Clearing messages in groups is done by anti-link robots that are several times faster than normal.
I did what you said, but the information displayed is so large that it is difficult to check in the terminal because it moves very fast.

**Comment by levlam** [comment]
Redirect the log to file and send the file to @tdlib_bot.

**Comment by BarnameESF** [comment]
Hello again
I sent the additional information to the relevant robot.
