### ISSUE TITLE
Proxy problem with phone numbers from different countries.

### ISSUE THREAD

**Issue by leonidUH** [tdlib/td#815]
Hi
I have some problem with login.
When i use US number and US proxy login working fine for me and I got connectionState - ConnectionStateReady after ~1 sec
, but when I use Indian phone number with same US proxy  - i'm stuck with 
 connectionState  - ConnectionStateConnectingToProxy

**Comment by levlam** [comment]
It is impossible that connection to proxy depends on the request you send. The proxy is likely to be unreachable from the place you are trying to use it with the Indian phone number.

**Comment by leonidUH** [comment]
I tried from same computer with a difference of 5 minutes. US number work fine and  Indian stuck with
 ConnectionStateConnectingToProxy . I can send you TDLib logs if you want

**Comment by levlam** [comment]
Sure. Send logs with verbosity level 4 to @tdlib_bot.

**Comment by leonidUH** [comment]
i am sending it now

**Comment by levlam** [comment]
There was a problem with HTTP proxies not supporting IPv6 and connecting to the Asian DC. It was fixed in TDLib 1.6.0.
