### ISSUE TITLE
Poll retract vote

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#817]
In official client it is possible to "Retract Vote" from the poll.

In TDLib 1.5.0 there is only `setPollAnswer` is available to change your poll answer.  Specifying option_ids=[-1] results in "Invalid option id specified" error.

Is it possible to retract the vote from the poll with TDLib 1.5.0?

Thanks

**Comment by levlam** [comment]
You need to specify empty list of chosen options.

**Comment by zevlg** [comment]
Thanks, works perfectly!
