### ISSUE TITLE
Android library size added ~23 Meg to apk

### ISSUE THREAD

**Issue by jpage4500** [tdlib/td#818]
Hi,

I was able to use the prebuilt Android library in my Android app but noticed the resulting apk size went up from ~5 Meg to ~28 Meg!! Is that expected? Is there anything that can be removed from the library to reduce this size?

>> To use TDLib to create Android Java applications, use our prebuilt library for Android. (https://core.telegram.org/tdlib/tdlib.zip)

On another note - I didn't see any way to query the version of the TDLIB SDK.. Assuming this library changes over time is that something that can be added? Otherwise, how will anyone know when they're running on an old version?

**Comment by levlam** [comment]
Such size increase is possible only for "universal" apk, which can be installed on any architecture. Usually you need to build separate apk files for different architectures.

TDLib sends its version in the first update `updateOption` to the app. But usually even this is not needed, because app is linked with a specific TDLib version known to the app. When TDLib is updated almost always some code in the app needs to be updated too.

**Comment by jpage4500** [comment]
Thanks for the quick reply!

I'm curious why the library is so large? 

Unfortunately I need a single apk since I want to be able to distribute my app directly and not just via the Play Store where all that is handled for you. Can you think of any other way we can reduce the final size of the Android app using the TDLIB?

>> When TDLib is updated almost always some code in the app needs to be updated too.

I was really just asking how I'd know as a developer that there was a new version of the Android library available? There's just a single Android library .zip file and nothing to indicate when it was last updated. If I do look at the updateOption in the app - how would I know if it's out of date?

thanks
joe

**Comment by levlam** [comment]
No, there is no other way to reduce universal binary size. This is less than 6 MB per architecture from 7+ MB of С++ code. Between, it's really hard to find x86/x86_64 devices and 64-bit ARM devices can run ARMv7 binary, so you still can remove most of the native code.

You need to look for TDLib releases on Github to know when TDLib is updated. If new version is released, then source code, change log and prebuilt library for Android were already updated.
