### ISSUE TITLE
Voice calls

### ISSUE THREAD

**Issue by L11R** [tdlib/td#82]
Well, I guess I understood how to establish `callConnection` and get this:
```
callConnection id:int64 ip:string ipv6:string port:int32 peer_tag:bytes = CallConnection;
```
But what I should do with it? How I can send sound to my peer and where I should get it?

I guess that all official clients use this: https://github.com/grishka/libtgvoip
But there is no any docs and I don't even know what exactly this thing do.

**Comment by isopen** [comment]
The question is interesting, but first you need to get acquainted with the technology itself.
https://en.wikipedia.org/wiki/Voice_over_IP

**Comment by levlam** [comment]
Yes, you need to pass all of these, getOption("call_connect_timeout_ms") and getOption("call_packet_timeout_ms") to libtgvoip, which will be able to manage the call.
We can't help with libtgvoip usage, but source code of official clients, which use libtgvoip, can help a lot.

**Comment by L11R** [comment]
Thanks for answer, will try

**Comment by isopen** [comment]
Slishchik great dependence on Grishka.

**Comment by Flohack74** [comment]
@L11R did you make any progress with calls? Our Telegram client TELEports also needs that, and as we are a small team, we are really thankful for examples so that we do not need to research all details ourselves :)

**Comment by levlam** [comment]
@Flohack74 You can find implementation of calls, group calls and voice chats using https://github.com/TelegramMessenger/tgcalls in the source code of official apps or Unigram. Probably, Telegram Desktop's implementation will be the closest to what you need.

**Comment by Flohack74** [comment]
So one more question, is the relation of libs like this:
```
tdesktop
+- libtgcalls
+- libtgvoip
   +- opus
```

Or is lbtgcalls importing libtgvoip? I am asking because I get `tgcalls/Message.h:4:10: fatal error: api/candidate.h: No such file or directory` when trying to build it. Which candidate.h is being used?
tgcalls would need a cmake or automake config ^^

**Comment by levlam** [comment]
Yes, tgcalls imports libtgvoip and libwebrtc.

You can find CMake build scripts used in TDesktop in https://github.com/desktop-app/tg_owt.

**Comment by jonnius** [comment]
According to the comments in #1903 tgcalls replaces libtgvoip. To me it looks like both are dependent on libtgowt but alternative implementations. Is that correct? Does that mean we need `libtgowt` and `tgcalls` and can ignore `libtgvoip`? Or do we need the latter, too, for compatibility reasons?

**Comment by jonnius** [comment]
And do we need https://github.com/desktop-app/lib_webrtc?

**Comment by levlam** [comment]
@jonnius 

> To me it looks like both are dependent on libtgowt but alternative implementations. Is that correct? 

No. `libtgowt` contains build scripts for `tgcalls`.

> Does that mean we need libtgowt and tgcalls and can ignore libtgvoip?

`libtgvoip` is part of `tgcalls` for compatibility reasons.

**Comment by jonnius** [comment]
Am I looking at the right `libtgowt` [here](https://github.com/desktop-app/tg_owt)? Because I can't find `tgcalls` mentioned there.

**Comment by levlam** [comment]
Yes, this is the correct `libtgowt`. You need to link `libtgcalls` with both `libtgvoip` and `WebRTC`. `libtgowt` provides a way to build WebRTC outside of Chromium project, so you can link `tgcalls` against `libtgvoip` and `libtgowt` besides other libraries.

**Comment by jonnius** [comment]
I think I got it now. `libtgowt` _is_ a WebRTC fork and I don't need yet another WebRTC if I use `libtgowt`. And `tgcalls` depends on `libtgowt` and `libtgvoip`. But there is no CMake config for `tgcalls` anywhere. Correct?

What makes me wonder are some WebRTC includes in [Telegram Desktop](
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/calls/calls_call.cpp) of headers I can't find in libtgowt, e.g.:
 ```cxx
#include "webrtc/webrtc_video_track.h"
#include "webrtc/webrtc_media_devices.h"
#include "webrtc/webrtc_create_adm.h"
```

**Comment by levlam** [comment]
> But there is no CMake config for tgcalls anywhere. Correct?

Yes, but you can find some clues in all Telegram apps.

> What makes me wonder are some WebRTC includes in [Telegram Desktop](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/calls/calls_call.cpp) of headers I can't find in libtgowt

They are from lib_webrtc submodule: https://github.com/telegramdesktop/tdesktop/tree/dev/Telegram.

**Comment by SantiiRepair** [comment]
interesting thread...
