### ISSUE TITLE
React native support.

### ISSUE THREAD

**Issue by simonsisay** [tdlib/td#822]
Is it possible to use the library on a react-native project?

**Comment by abrehamgezahegn** [comment]
What are you upto baba?

**Comment by levlam** [comment]
You can build TDLib for any platform that is supported by React Native. You need just to load and use the prebuilt shared library in React Native project.

**Comment by simonsisay** [comment]
Thank you for you response. Is there a project or code I can look into that uses tdlib in a react native project.

**Comment by levlam** [comment]
@simonsisay I have not seen such project yet.

**Comment by simonsisay** [comment]
Okay. Thanks again.
