### ISSUE TITLE
Request new feature for updateChatPermissions

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#823]
The updateChatPermissions class only specifies chat ID and new permissions, but it is necessary to specify which admin group has made the change.
Please add the corresponding administrator ID to this class.

**Comment by levlam** [comment]
It is not possible to do, because `updateChatPermission` doesn't necessary correspond to a single change. It can accumulate a lot of changes done by different administrators. If you want to know, who and when changed permissions, you need to use `getChatEventLog` method.

**Comment by BarnameESF** [comment]
In chatEventLogFilters class, only setting_changes must be True.
What should the query in getChatEventLog do to bring up the list of permissions only?

**Comment by levlam** [comment]
Do you want to filter events by some text? It seems no, so `query` needs to be empty.

Permission changes schould be in `setting_changes` category.
