### ISSUE TITLE
How to find accounted dilute users With supergroupMembersFilterSearch

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#824]
Using the supergroupMembersFilterSearch class How to find accounted dilute users?
How to write query?

**Comment by levlam** [comment]
Do you mean deleted users? Deleted users aren't returned by `getSupergroupMembers` at all. There is no way to get them from server. They should be automatically removed from the chat after two weeks after deletion.

**Comment by BarnameESF** [comment]
Yes, exactly
There are some unofficial telegram versions for Android!

**Comment by levlam** [comment]
This is not possible for supergroups with more than 5000 members, because they aren't returned by the server. For smaller groups you can try to receive them using `supergroupMembersFilterRecent`.
