### ISSUE TITLE
Problem connecting to telegram server

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#825]
I'm using tdbot 1.4. In my script, the following is repeated:
`{"@type":"updateConnectionState","state":{"@type":"connectionStateConnecting"}}`
After displaying the above code, tdlib pauses for a few seconds and the operation is repeated every 3 minutes.
This process causes the script to slow down.
Is this normal?
If it's anomalous, what's the solution?

**Comment by levlam** [comment]
Please share TDLib's log with @tdlib_bot to find exact reason of connection failures.
