### ISSUE TITLE
Can't register an account

### ISSUE THREAD

**Issue by lsndr** [tdlib/td#826]
Hi!

I use **node-tdlib** for working with **tdlib**. I'm trying to register an account, but when I call **checkAuthenticationCode** method, I get **PHONE_NUMBER_UNOCCUPIED** error and I don't receive **authorizationStateWaitRegistration**.

What am I doing wrong?

**Comment by levlam** [comment]
You are likely using old TDLib version. Due to server-side changes you need to update to TDLib >= 1.5.0.
