### ISSUE TITLE
There is no /bin folder after comiling 

### ISSUE THREAD

**Issue by ibanezn04** [tdlib/td#827]
After i've done the instruction: 
`Cloning into 'td'...
remote: Enumerating objects: 28163, done.
remote: Total 28163 (delta 0), reused 0 (delta 0), pack-reused 28163
Receiving objects: 100% (28163/28163), 9.55 MiB | 362.00 KiB/s, done.
Resolving deltas: 100% (19962/19962), done.
 evgenii@evgenii-PC (/IdeaProjects) $ cd td
 evgenii@evgenii-PC (/IdeaProjects/td) $ mkdir jnibuild
 evgenii@evgenii-PC (/IdeaProjects/td) $ cd jnibuild 

 evgenii@evgenii-PC (/IdeaProjects/td/jnibuild) $ cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..
` 
...output...

`cmake --build . --target install
`
...long output...

I'm trying to run the program by running command:
`cd <path to TDLib sources>/example/java/bin
java '-Djava.library.path=.' org/drinkless/tdlib/example/Example`

But there is no such folder - /bin

`
 evgenii@evgenii-PC (/IdeaProjects/td/jnibuild) $ cd ..
 evgenii@evgenii-PC (/IdeaProjects/td) $ cd /example/java/bin 
 cd: no such file or directory: /example/java/bin
 ✘ evgenii@evgenii-PC (/IdeaProjects/td) $ cd example/java 
 evgenii@evgenii-PC (/IdeaProjects/td/example/java) $ tree  
.
├── CMakeLists.txt
├── org
│   └── drinkless
│       └── tdlib
│           ├── Client.java
│           ├── example
│           │   └── Example.java
│           └── Log.java
├── README.md
├── td
│   ├── bin
│   │   ├── td
│   │   │   └── generate
│   │   │       ├── JavadocTlDocumentationGenerator.php
│   │   │       ├── scheme
│   │   │       │   ├── td_api.tl
│   │   │       │   └── td_api.tlo
│   │   │       └── TlDocumentationGenerator.php
│   │   └── td_generate_java_api
│   ├── include
│   │   └── td
│   │       ├── telegram
│   │       │   ├── Client.h
│   │       │   ├── Log.h
│   │       │   ├── td_api.h
│   │       │   ├── td_api.hpp
│   │       │   ├── td_json_client.h
│   │       │   ├── tdjson_export.h
│   │       │   └── td_log.h
│   │       └── tl
│   │           ├── tl_jni_object.h
│   │           └── TlObject.h
│   └── lib
│       ├── cmake
│       │   └── Td
│       │       ├── TdConfig.cmake
│       │       ├── TdConfigVersion.cmake
│       │       ├── TdTargets.cmake
│       │       └── TdTargets-release.cmake
│       ├── libtdactor.a
│       ├── libtdclient.a
│       ├── libtdcore.a
│       ├── libtddb.a
│       ├── libtdjson_private.a
│       ├── libtdjson.so -> libtdjson.so.1.5.1
│       ├── libtdjson.so.1.5.1
│       ├── libtdjson_static.a
│       ├── libtdnet.a
│       ├── libtdsqlite.a
│       └── libtdutils.a
└── td_jni.cpp

16 directories, 35 files
`

What am i doing wrong?

**Comment by levlam** [comment]
You built only TDLib, but not the Java example. The second part of build instructions was skipped. See https://tdlib.github.io/td/build.html?language=Java for the full build instructions.

**Comment by ibanezn04** [comment]
Thank you very much! But i've got another question:
why do all those *.class files were generated? I've got it all to work when i put .so file next to the project like this 
![image](https://user-images.githubusercontent.com/25910599/70447262-828b7d00-1aaf-11ea-9885-b7c2608e38c5.png) and (added `-Djava.library.path=/home/evgenii/IdeaProjects/TgLib/src/main/java/org/drinkless/tdlib/example` and it's all seems to work.
Do i understand this right that i just call TdApi methods from my Main class and this is all?

**Comment by levlam** [comment]
All TdApi methods and objects are represented as classes, so all of them needs to be built to .class files.

You need to use `org.drinkless.tdlib.Client` to receive updates from TDLib and send requests. You can look at Example.java source code to find exact way of hot to do that. https://core.telegram.org/tdlib/getting-started should be also very helpful.

**Comment by ibanezn04** [comment]
Thanks, really helpful!

**Comment by heroys6** [comment]
Maybe it's better to add this link: https://tdlib.github.io/td/build.html?language=Java
into https://github.com/tdlib/td/blob/master/example/java/README.md ?
How was I supposed to find this link?

**Comment by levlam** [comment]
@heroys6 The link and the README are just different and serve different purposes. The description in the example's README is more general, contains soluitons for common problems and is very specific to the example, placing all built files into the `example/java/bin` directory. Build instructions generator provides a more straightforward list of build instructions for some platforms, but it is not specific to the example.
