### ISSUE TITLE
Clearing the database of received telegram messages

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#828]
Hi
The db.sqlite file created in the .telegram-bot folder in the data folder for each connected account looks as if it saves the received messages. The size of this file increases dramatically over time.
Is there a solution to optimize this file using tdlib functions?

**Comment by levlam** [comment]
You can disable unneded databases, in particular, disable SQLite usage at all, but there is no way to do that in tdbot. You need to manually change corresponding parameters in
https://github.com/vysheng/tdbot/blob/d976a7010df6c15f385eb504b5289e86bca93834/cliclient.cpp#L266
and rebuild tdbot.

**Comment by Kia-Pashang** [comment]
Hi , is it enable storage optimizer ?

**Comment by levlam** [comment]
@Kia-Pashang enable_storage_optimizer affects only downloaded files, not the database.

**Comment by Kia-Pashang** [comment]
> @Kia-Pashang enable_storage_optimizer affects only downloaded files, not the database.

And what is **use_file_db** and **use_chat_info_db** and **use_message_db** ??
which one is related to db.sqlite ?

**Comment by levlam** [comment]
@Kia-Pashang 
All of them use db.sqlite.

**Comment by Kia-Pashang** [comment]
> @Kia-Pashang
> All of them use db.sqlite.

Thank you.
