### ISSUE TITLE
Authorization/Cache

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#829]
Hi! After logging into the client and exiting from it, if i restart the program it doesn't ask me for my phone number. So I think Client class must have cached an auth. token. Is that right? And where is it cached?

**Comment by levlam** [comment]
All persistent data is stored in `database_directory`, provided in `setTdlibParameters` call. But do not try to interfere with stored here data, for example, copying all the data and running two TDLib instances simultaneously will not work.

**Comment by yasharzb** [comment]
Aha. And after logging into my account shall I receive other Authorization Updates or just chat updates?

**Comment by yasharzb** [comment]
I had a question about bot authorization also, but I didn't know where should I ask ? :sweat_smile: 
Does the bot token change or expire?

**Comment by levlam** [comment]
Bot token can be changed only through @BotFather. See https://core.telegram.org/bots#6-botfather.

**Comment by yasharzb** [comment]
Thanks.
