### ISSUE TITLE
terminateAllOtherSessions terminates current session

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#830]
`terminateAllOtherSessions` method name suggests, that after call it will keep current session open. 
 However calling this method I've got `SESSION_REVOKED` after few various update events.  And **all** sessions has been terminated, so it was hard times to find that sim card I've been using to register in Telegram platform :)

Is it supposed to work like so, or am I doing something wrong?

I'm going to use direct calls `terminateSession` method on the list of all non-current sessions in order to terminate all other sessions.

Thanks

**Comment by levlam** [comment]
No, `terminateAllOtherSessions` supposed to work exactly as written. Could you reproduce the issue? Did you have `use_pfs` option enabled?

**Comment by zevlg** [comment]
I do not specify any value to `use_pfs` option.  And I need some time before trying again, because error
```
{"@type":"error","code":406,"message":"FRESH_RESET_AUTHORISATION_FORBIDDEN"}
```
is returned on my call to `terminateAllOtherSessions`.  I'll try again later

**Comment by levlam** [comment]
@zevlg I've tested `terminateAllOtherSessions` a dozen times on different accounts and every time only other sessions was terminated. Could you provide TDLib's log with verbosity level at least 4 if the issue happens again?

**Comment by zevlg** [comment]
I've tried one more time, and it did not repeated, current session remains running!

As I remember I've been experimenting with copying `database_directory` across computers, could with cause former behaviour?  I'll check if logs are still available from that session

Closing it for now, thanks!

**Comment by levlam** [comment]
@zevlg If both copies will be run simultaneously, the client will be logged out.

**Comment by Sbozzolo** [comment]
This (probably) happened to me. All my sessions got killed and I don't have access anymore to the phone number. What can I do to recover the account?

**Comment by levlam** [comment]
@Sbozzolo Unfortunately, there is no way to log in to an account without having access to the phone number or at least one previously logged in session.

**Comment by Sbozzolo** [comment]
One of the computers, where I had a client logged in, is currently turned off. Is there a way I can use this to save my account?

**Comment by levlam** [comment]
@Sbozzolo No, if all your sessions was terminated. You can only manually copy some data before the computer is connected to the internet.

**Comment by casino-api007** [comment]
Today I got this issue too. I clicked the button: "Terminate All Other Sessions" but it killed the current session, lost access to the account.
Since it was virtual number.  Telegram Android v11.7.4
