### ISSUE TITLE
JoinChat

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#831]
I add this:
`case "join":
client.send(new TdApi.JoinChat(getChatId(commands[1])), defaultHandler);
break;`
to getCommand method and when I insert this Id `-1001000431759` e.g. which is a public channel defaultHandler prints 
`Error {
  code = 3
  message = "Chat not found"
}`
why?

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/578. This particular issue is about user identifiers, but everything written there can be also applied to chat identifiers.

**Comment by yasharzb** [comment]
Tnx I used `SearchPublicChat()` and it solved!
