### ISSUE TITLE
Grouping of Chats

### ISSUE THREAD

**Issue by szaimen** [tdlib/td#832]
**Is your feature request related to a problem? Please describe.**
When trying to use Telegram for work, currently you are ending in a lot of chats for every topic, that are put together in one list with private messages etc, which is something you probably don't want.

**Describe the solution you'd like**
Grouping of Chats. So that you are able to create a "Superchat", where you can invite people or usergroups to. When clicking on that "Superchat" you then see a list of topics in a second level. 
(also in an "chatlist" but you should always show just one level, so you would need a "Go Back" arrow in the top left to show, that you are in a second level; placed next to or directly on the back-arrow, you could probably also show a notification dot or count how many new messages have arrived in the chatlist level on top)

Every People and usergroup that you have invited to the "Superchat" should then see automatically every topic from the "Superchat", but you should be able to blacklist or whitelist people or usergroups for each topic alone (or for more than one topic at the same time through a bulk selection). 

e.g. If you create a new topic, all people and usergroups, that are invited into the "Superchat" automatically join all topics. Only if you blacklist them during the creation of a new topic or afterwards, they don't have accessrights and don't join the topic.

One advantage would be, that topics with new messages would arrive at the top of the chatlist inside the "Superchat" and you have always automatically the same people inside each topic, when not manually changed. So it is just really easy to create a new topic with the same people for each new case. (Archiving should also be possible...)

The private chats would then be at the first chatlist level, normal group chats and the "Superchat" too. Topics of a "Superchat" would be on the second level. New messages inside a "Superchat" would then be grouped together in a notification counter for the Whole "Superchat" on the first level. When you are on the second chatlist level with the topics of a "Superchat", all new messages in other Superchats or private chats or normal groups are then grouped together in a notification counter next to the "go back" arrow.

BTW: If you ask because why not adding another 3rd chatlist level: I think everything is already possible with 2 Levels. Since if you have another group of people you then create just another "Superchat" with these people. A 3rd Level would make everything more complicated and much harder to use.

**Describe alternatives you've considered**
I think this second chatlist level is needed to really make Telegram userfriendly and useful for work and not that cluttered.

**Additional context**
If you haven't understand my proposal or wonder how this could work, please feel free to ask!
I have thought that through.

**Comment by levlam** [comment]
There is no way this can be implemented without server-side support, so there is no way this can be added to TDLib until it is supported server-side.

**Comment by szaimen** [comment]
Okay, so where can I send this idea to get this implemented into the server?

**Comment by levlam** [comment]
General suggestions can be sent through in-app support or by menthioning @telegram on Twitter
