### ISSUE TITLE
WPF .Net Core 3

### ISSUE THREAD

**Issue by Lorymi** [tdlib/td#834]
Hi, how i can build TDlib for WPF applications with **.net core 3** ?? (I don't want to use the JSON interface)

**Comment by levlam** [comment]
.NET Core 3.0 doesn't support native code extensions, but .NET Core 3.1 is likely to have such support on Windows. See https://devblogs.microsoft.com/cppblog/the-future-of-cpp-cli-and-dotnet-core-3/ for more details.

But even after such support will be added, only JSON interface could be used portable. You can use https://github.com/egramtel/tdsharp to interact with TDLib using JSON interface and automatically generated classes for TDLib API.

**Comment by Lorymi** [comment]
@levlam Hi, Thanks.
Currently stable version 3.1 has been released
https://dotnet.microsoft.com/download/dotnet-core/3.1

But why are you saying just that only JSON interface can be used? C++/CLI have full support for targeting .NET Core 3.1

**Comment by levlam** [comment]
Because C++/CLI is supported only under Windows.

**Comment by levlam** [comment]
If you don't need portability to Linux or macOS, you can use build instructions 
 from https://tdlib.github.io/td/build.html?language=C%23 to build native C++/CLI TDLib interface.
