### ISSUE TITLE
TDLib is too slow with multiple accounts

### ISSUE THREAD

**Issue by lsndr** [tdlib/td#835]
Hi!

I'm developing a cloud proprietary chat application for my client. It's based on Telegram. 

It requires to keep employees' accounts connected to Telegram 24/7. But when more than 5 accounts are connected, TDLib starts to handle requests slowly. Even connection for 6th, 7th... accounts takes a few seconds.

How to solve this problem? Should I call `receive` method less often? Or should we use proxy?

In general we need around ~30 accounts to be connected to Telegram.

**Comment by levlam** [comment]
In Bot API TDLib handled more than 24000 active bots simultaneously in one process, in Telegram X limit on number of accounts is 65536, so TDLib has no performance problems with multiple accounts. 

Please descibe how exactly you manage multiple accounts, and what exactly do you mean by performance problem?

In any case, `receive` should be called all the time with a smallest delay possible to receive updates as fast as possible. All accounts are independent and should never interfere with each other.
