### ISSUE TITLE
libtdjson.dylib size is too big

### ISSUE THREAD

**Issue by savelichalex** [tdlib/td#836]
Hi, I've built a dylib from example folder for iOS, but a size is huge - 269 Mb. Can I somehow make it smaller?

Example how I'm building a lib:
```
git clone https://github.com/tdlib/td
cd td/example/ios

./build-openssl.sh
./build.sh

cd ../../..

mkdir ios
cp -r td/example/ios/tdjson/iOS/* ios
rm -rf td
```

**Comment by levlam** [comment]
No, this is not possible. The dilyb contains built binaries for all supported architectures and simulators and some other data required by Apple. The actual binary size installed on devices will be much smaller, because only needed for the specific architecture parts will be installed.

**Comment by savelichalex** [comment]
@levlam ok, thanks

**Comment by ibengeu** [comment]
@savelichalex How did you make use of the files after copying, i would like to make use of it for the simulator and in future iphones
