### ISSUE TITLE
getting back all of chats!

### ISSUE THREAD

**Issue by ByeCoder** [tdlib/td#839]
Hello,
after some days db.sqlite is going to be very large and I should delete it,
and when I delete it I loses my chats such as private chats ,...
is there any way to get all of them?
I just can get 100 chats with getChats!

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats.

**Comment by ByeCoder** [comment]
Yes,
it worked
thanks!
