### ISSUE TITLE
Move UpdateUserChatAction timeout management to TDLib

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#84]
For now, all clients with UI are forced to imitate `UpdateUserChatAction(chatId, userId, ChatActionCancel)` on its side in the following cases:

- When UpdateUserChatAction has been sent more than 5 seconds ago
- When new message from user has been received

It would be good to move this logic to TDLib since it should not differ between specific clients.

**Comment by levlam** [comment]
Implemented in TDLib 1.2.0.
