### ISSUE TITLE
Strikethrough text markup

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#840]
Message https://t.me/emacs_telega/9991 has "this" text striked through in official client.

However there is no entities reported in formattedText.  How do we get the info about strikedthrough text using TDLib?

Thanks

**Comment by levlam** [comment]
Underline and Strikethrough entity types was supported in TDLib in the September after TDLib 1.5.0 release, so they are not supported by the latest publicly available TDLib version. TDLib 1.6.0 with that and many other features implemented is expected to be publicly available some time after next Bot API and Telegram X releases.

**Comment by levlam** [comment]
Support for new text entities was added in TDLib 1.6.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.
