### ISSUE TITLE
Remote File

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#841]
Hi. Apparently there is a remote file for each file. Like this: 
```
        remote = RemoteFile {
          id = "CgADBAADtwQAAliEqVO4wB9sQ8CQ7xYE"
          isUploadingActive = false
          isUploadingCompleted = true
          uploadedSize = 2171391
        }
```
So i want to know how can I access this remote file? Can I use it to upload it somewhere else without downloading?

**Comment by levlam** [comment]
You can use [inputFileRemote](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_remote.html) as InoutFile in any class or method.

**Comment by yasharzb** [comment]
I found no method which I can use to download the file by InputFileRemot or InputFile or remoteId :(

**Comment by levlam** [comment]
You can use the method `getRemoteFile` to get a file and file.id by remote.id.

**Comment by yasharzb** [comment]
What is returned value type of GetRemoteFile()?
