### ISSUE TITLE
Deleted Message

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#842]
I am getting history messages via GetMessage. But I forgot to check if the message is not deleted.
How should I know if the message is deleted or not and after that I decide to get it or no?

**Comment by levlam** [comment]
There is no way you can get from TDLib a deleted message.

**Comment by Flohack74** [comment]
What about messages that have `reply_to_message_id `set, and we are offline, how could we know that this message is deleted or not? Our client shows `unavailable`, but people complain that official clients show `deleted`.

**Comment by levlam** [comment]
@Flohack74 `getMessage` returns a message or the error 404, "Not Found". Official clients show "Loading message..." before they receive response to `getMessage`. If the message is deleted, then Telegram X shows "deleted", all other clients hide reply.
