### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#843]
Hi! How should I know if the connection is failed? I use UpdateConnectionState but I didn't receive anything after disconnecting from vpn (I'm using it from Iran)

**Comment by levlam** [comment]
You can listen for UpdateConnectionState, but this is usually useless for applications. The update is intended only to be shown to humans, applications using TDLib must not care about network connections.

Also don't forget to correctly set option "online" and if posiible use `setNetworkType` when a network is changed
