### ISSUE TITLE
Jar file

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#844]
I have compressed Client.java, TdApi.java and Log.java to a jar file and I used it as library for my project which is a Spring Boot. But now I can't use `mvn clean package` to get jar from my prjoect. Is any solution for it?

**Comment by levlam** [comment]
The question seems to be unrelated to TDLib and much more about mvn.

**Comment by yasharzb** [comment]
Ok. I found sth similar to my problem here in [](https://github.com/tdlib/td/issues/299#) I got
`java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]`
At that issue you've talked about copying some dlls. I'm using Ubuntu and I see non of them.
This my build directory:
```
├── CMakeCache.txt
├── CMakeFiles
│   ├── 3.13.4
│   │   ├── CMakeCXXCompiler.cmake
│   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   ├── CMakeSystem.cmake
│   │   └── CompilerIdCXX
│   │       ├── a.out
│   │       ├── CMakeCXXCompilerId.cpp
│   │       └── tmp
│   ├── build_java.dir
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── DependInfo.cmake
│   │   ├── depend.internal
│   │   ├── depend.make
│   │   └── progress.make
│   ├── cmake.check_cache
│   ├── CMakeDirectoryInformation.cmake
│   ├── CMakeOutput.log
│   ├── CMakeRuleHashes.txt
│   ├── CMakeTmp
│   ├── feature_tests.bin
│   ├── feature_tests.cxx
│   ├── generate_javadoc.dir
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── DependInfo.cmake
│   │   ├── depend.internal
│   │   ├── depend.make
│   │   └── progress.make
│   ├── Makefile2
│   ├── Makefile.cmake
│   ├── progress.marks
│   ├── TargetDirectories.txt
│   ├── td_generate_java_api.dir
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── DependInfo.cmake
│   │   ├── depend.internal
│   │   ├── depend.make
│   │   └── progress.make
│   └── tdjni.dir
│       ├── build.make
│       ├── cmake_clean.cmake
│       ├── CXX.includecache
│       ├── DependInfo.cmake
│       ├── depend.internal
│       ├── depend.make
│       ├── flags.make
│       ├── link.txt
│       ├── progress.make
│       └── td_jni.cpp.o
├── cmake_install.cmake
├── install_manifest.txt
├── libtdjni.so
└── Makefile
```

**Comment by yasharzb** [comment]
I solved it by adding jar package of Client, TdApi, Log to a maven repository (is equivalent to add the whole package of `org.drinkless` as classes of your project, out of your spring package) and then change `System.loadlibrary` to `System.load(absolute/path/to/libtdjni.so)` in Example class (your main class).

**Comment by vladbogun1** [comment]
> I have compressed Client.java, TdApi.java and Log.java to a jar file and I used it as library for my project which is a Spring Boot. But now I can't use `mvn clean package` to get jar from my prjoect. Is any solution for it?

can you share compiled jar? i cant compile with cmake, it throwing a lot of errors.
