### ISSUE TITLE
TDLib Fatal Error Version 1.5.3.1248

### ISSUE THREAD

**Issue by piratebazaar** [tdlib/td#849]
I started getting this TDLib fatal error after the recent TelegramX beta update. It's showing me a Aw,Snap! error page with logs and testing utilities. I have attached a screenshot below.

I've also submitted logs via mail and @TDLib_bot but got no responce so far. Please fix it asap and do the needful. Thank you.
![Screenshot_20191223-145152](https://user-images.githubusercontent.com/48173261/71351001-a44d2f80-2598-11ea-87c6-50992423ef9c.png)

**Comment by levlam** [comment]
This was fixed in a private TDLib version. The fix will be available in the future Telegram X version with updated TDLib.

**Comment by piratebazaar** [comment]
> This was fixed in a private TDLib version. The fix will be available in the future Telegram X version with updated TDLib.

Any ETA of the update? I'm asking this because I'm not able to use the telegram at all due to this issue and a "Failed to fetch messages. Tap to resolve" Notification stays 24x7 in my notification panel.

**Comment by levlam** [comment]
@piratebazaar I can't provide ETA for Telegram X update.

**Comment by levlam** [comment]
Telegram X beta was updated. Please update to Telegram X 1.5.3.1249.
