### ISSUE TITLE
JSON can't contain int over 53 bits

### ISSUE THREAD

**Issue by thebootroo** [tdlib/td#85]
Despite this fact, the API has a bunch of int64, knowing that JSON stores all numbers in double precision floats, precision will be lost for approximately the 4 last digits on a big int64 number.

I think it will be an issue at some point, do you plan to fix it ? (workaround by splitting in two int32 maybe, or try to fit officially in int53/aka double)

**Comment by levlam** [comment]
The library already stores int64 as String and int53 as Number (aka double). Have you found some int64 number which is incorrectly marked as int53 in the TDLib API?

**Comment by levlam** [comment]
You can see that in our [TDLib API scheme](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl), from which all binding, including JSON binding, are generated, int53 and int64 are two different types. This is done exactly to mitigate mentioned issue.

**Comment by thebootroo** [comment]
So you mean that if I'm using JSON API, I should be aware that int64 fields in TL file are in fact String field in JSON ? Seems okay for me.

**Comment by levlam** [comment]
Yes. This is documented in description of TDLib [JSON interface](https://core.telegram.org/tdlib/docs/td__json__client_8h.html).
