### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#851]
I got a jar file from my project, loading tdlib as dependency. I set `System.load(/path/to/libtdjni.so);` and it was working on my pc. I even moved the project from its location to another location and it worked.  I moved jar file of my project and libtdjni.so to another pc and ran my project but I got this error:
`java.lang.UnsatisfiedLinkError: /home/yashar/telegram-cli/libtdjni.so: libssl.so.1.1: cannot open shared object file: No such file or directory`
.....
`Caused by: java.lang.UnsatisfiedLinkError: 'org.drinkless.tdlib.TdApi$Object org.drinkless.tdlib.Client.nativeClientExecute(org.drinkless.tdlib.TdApi$Function)'`
I double checked the path of libtdjni.so and I realized that it's correct (by `file.exists()` in java).
The PCs use same dependency repository.

**Comment by levlam** [comment]
The error tells that it can't find `libssl.so.1.1`, not `libtdjni.so`.
