### ISSUE TITLE
TON Support

### ISSUE THREAD

**Issue by jvcmd** [tdlib/td#852]
Please support of TON and create Wallet in TDLib

**Comment by levlam** [comment]
This is not related to TDLib. You need tonlib for that from https://github.com/ton-blockchain/ton.

**Comment by jvcmd** [comment]
@levlam Thanks.
Can you help me for this https://github.com/ton-blockchain/ton/issues/222

**Comment by levlam** [comment]
@jvcmd You need to build tonlib and use it through PInvoke.
