### ISSUE TITLE
Last message from supergroup doesn't match with message from getChatHistory method

### ISSUE THREAD

**Issue by we138** [tdlib/td#853]
Hello, I am trying to get last message from supergroup via `getChatHistory`, but message what I am getting from `td` - does not match with message what I am seeing on desktop telegram client. There is function arguments how I am using: 

`client.get_chat_history(-1001164267096, 0, -1, 10, false)`

and client returns me message with text `"foo"`, but I expect to receive `"bar"`, because there is the last message in supergroup. What I am doing wrong?

client versions:

`td (1.5.0)`
`tdlib-ruby (2.1.0)`

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/644.

**Comment by we138** [comment]
@levlam thanks for quick help, works!
