### ISSUE TITLE
About DeleteMessages

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#854]
How can I delete a certain message in the chat? I tried using the deleteMessages method, but I did not see the corresponding deletion on the client. @levlam

**Comment by levlam** [comment]
You likely specified wrong arguments to the `deleteMessages` request.

**Comment by AquariusHunters** [comment]
Json::Value DeleteMessageJson;
						Json::Value array;
						array.append(root["last_message"]["id"].asInt64());
						DeleteMessageJson["@type"] = "deleteMessages";
						DeleteMessageJson["chat_id"] = 777000;
						DeleteMessageJson["message_ids"] = array;
						DeleteMessageJson["revoke"] = true;
						td_json_client_send(client, DeleteMessageJson.toStyledString().c_str());

This is an example of my simulation, where is the parameter problem? Is the ID of the message? @levlam

**Comment by levlam** [comment]
Probably. Send TDLib log with verbosity level 4 to @tdlib_bot.

**Comment by AquariusHunters** [comment]
But now there are only 3 introductions on the website @levlam

**Comment by levlam** [comment]
@AquariusHunters What do you mean?

**Comment by AquariusHunters** [comment]
Is it possible from another perspective, how can I deletechat, but not quit. @levlam

**Comment by levlam** [comment]
`deleteChatHistory` and `leaveChat` are completely independent methods.

**Comment by Flohack74** [comment]
deleteMessage works fine, we used if for quite some time in TELEports.

**Comment by AquariusHunters** [comment]
@Flohack74 I'm using version 1.4.0, but I get from lastmessage to the ID, but not to delete a record corresponding according to the ID, but the method can be used deleteChatHistory

**Comment by Flohack74** [comment]
Please see https://gitlab.com/ubports/apps/teleports/blob/master/libs/qtdlib/messages/qtdmessagelistmodel.cpp#L577 - 2 methods deleteMessage, and deleteMessages, they are both working fine. The delete message request is very easy to use.
