### ISSUE TITLE
Failed to rename binlog

### ISSUE THREAD

**Issue by daparici** [tdlib/td#857]
Hi,

I use tdsharp to download several files simultaneously from Telegram. Sporadically I receive and exception when tdlid tries to rename binlog and my app crashes. This seems to be a native tdlib error. Do you know how can I avoid this?

[&status.is_error()] Failed to rename binlog: [WindowsError : Access
denied. : 5 : Can't rename "C:------\td.binlog.new" to "C:------\td.binlog"]

I have no antivirus enabled.

**Comment by levlam** [comment]
The most probable reason is still that some external program locks the `td.binlog.new` file. For example, Windows has Windows Defender enabled by default. Or it can be any other program having access to the TDLib's folder. You can try to catch the program using the Resource Monitor.

**Comment by levlam** [comment]
@daparici Have you found the cause?
