### ISSUE TITLE
update CHANGELOG.md

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#858]
Congratulations to you and your colleagues on New Year.

The CHANGELOG.md file is set to tdlib 1.5.0 but tdlib is now updated to 1.5.4 but the list of changes has not been updated.
Please update the CHANGELOG.md file & Also configurable slow_mode_delay add to tdlib.

thank you ...

**Comment by levlam** [comment]
The change log update is pending. It will be updated to TDLib 1.6.0 change log when the corresponding documentation is ready.

**Comment by levlam** [comment]
In the meanwhile, `git diff v1.5.0 td/generate/scheme/td_api.tl` gives a very good approximation of the publicly visible changes.

**Comment by BarnameESF** [comment]
I use [vysheng_tdbot](https://github.com/vysheng/tdbot) & I fixed the 1.5 update errors through the introduced [link](https://github.com/tdlib/td/issues/712#issuecomment-536477650) , But to update to the latest version, the following error occurs:

`[ 98%] Building CXX object CMakeFiles/telegram-bot.dir/main.cpp.o
In file included from /root/tdbot/main.cpp:20:0:
/root/tdbot/cliclient.hpp: In member function ‘void CliClient::run(td::uint64, std::__cxx11::string)’:
/root/tdbot/cliclient.hpp:150:47: error: use of deleted function ‘td::JsonValue::JsonValue(const td::JsonValue&)’
       auto r = from_json(object, as_json_value);
                                               ^
In file included from /root/tdbot/td/td/tl/tl_json.h:14:0,
                 from /root/tdbot/cliclient.hpp:20,
                 from /root/tdbot/main.cpp:20:
/root/tdbot/td/tdutils/td/utils/JsonBuilder.h:473:3: note: declared here
   JsonValue(const JsonValue &other) = delete;
   ^
In file included from /root/tdbot/cliclient.hpp:21:0,
                 from /root/tdbot/main.cpp:20:
/root/tdbot/td/td/generate/auto/td/telegram/td_api_json.h:13:8: note:   initializing argument 2 of ‘td::Status td::td_api::from_json(td::tl_object_ptr<td::td_api::Function>&, td::JsonValue)’
 Status from_json(tl_object_ptr<Function> &to, td::JsonValue from);
        ^
CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:162: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2
`

**Comment by levlam** [comment]
tdbot uses private TDLib functions, so it needs to be fixed after every TDLib update. You need to wait, while someone fixes tdbot to support TDLib 1.6.0, and this is unlikely to happen before 1.6.0 release.

**Comment by whyoleg** [comment]
Hi all, I've just created tool to generate more readable changelog from tl-scheme - [CHANGELOG](https://github.com/whyoleg/ktd/blob/new-generator-cli/api/CHANGELOG.md). May be it can also help.

**Comment by levlam** [comment]
The [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) was updated.
