### ISSUE TITLE
Bot cannot delete messages when there is no local record

### ISSUE THREAD

**Issue by KazamaWataru** [tdlib/td#859]
When onNewInlineCallback is received, using the message's chatId and messageId to call deleteMessages will cause "message cannot be deleted" if the bot restarted after receiving this message when useMessageDatabase is false or data has been deleted

When I try to call getMesage, it returns this message is not found

What went wrong? There is no such problem in the http bot api

**Comment by levlam** [comment]
Please send TDLib's log with verbosity level 4 to @tdlib_bot.

**Comment by levlam** [comment]
@KazamaWataru Could you check on the latest TDLib version from master?
