### ISSUE TITLE
testReturnError fails with "Unknown class" message in log

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#863]
Hi,

We use the testReturnError for testing purposes in https://github.com/egramtel/tdsharp (.NET Core bindings for TDLib).

After upgrading to 1.5 this method started to fail with this error in log:

```
[ 1][t 0][1578052190.699196100][ClientJson.cpp:67]        Failed to parse [request:{\042@type\042:\042testReturnError\042,\042@extra\042:\0421\042,\042error\042:{\042@type\042:\042error\042,\042@extra\042:null,\042code\042:0,\042message\042:\042Error\042}}] [Error : 0 : Unknown class]
```

Request:

```
{"@type":"testReturnError","@extra":"1","error":{"@type":"error","@extra":null,"code":0,"message":"Error"}}
```

**Comment by levlam** [comment]
I can't reproduce this. Are you sure that this is TDLib 1.5.0? Could you check value of the "version" option?

**Comment by x2bool** [comment]
Well, I took the latest version from the master and used it. After building the resulting lib is called "libtdjson.1.5.1.dylib". And in the changelog it also says 1.5.

I am not sure what do you mean by "option". Do I have to pass "v1.5" into the lib to activate it at runtime somehow?

**Comment by levlam** [comment]
I'm talking about the first `updateOption` received from TDLib, which contains option with name "version". But `libtdjson.1.5.1.dylib` is a strong evidence that this is TDLib 1.5.1.

Could you try to reproduce with the latest TDLib 1.5.4 from master?

**Comment by levlam** [comment]
@x2bool Have you managed to reproduce the issue with the latest TDLib 1.5.5 from master? If so, could you send TDLib log with verbosity level 4 to @tdlib_bot?

**Comment by x2bool** [comment]
@levlam I had no chance to look at this so far. I will check 1.5.5, I just need a couple of days.

**Comment by x2bool** [comment]
It does work in the newer versions (1.5.5). Thanks!
