### ISSUE TITLE
Java Client.Close does not release memory

### ISSUE THREAD

**Issue by legobyte** [tdlib/td#865]
In my java app user can have multiple accounts.
When the user wants to close a specific account i call `Client.Close` method but the Closed Client wont release memory..
No memory leak in my code

**Comment by levlam** [comment]
We tested a lot of times that TDLib properly releases all allocated memory.

How do you test that a memory is not released? Previously allocated memory can't be returned to operating system only reused, so it is hard to externally find real memory leaks.

**Comment by levlam** [comment]
@legobyte Do you have more feedback?
