### ISSUE TITLE
"unresolved external symbol OPENSSL_cleanse" when building UWP example

### ISSUE THREAD

**Issue by LohanSolo** [tdlib/td#866]
I tried to build the Telegram UWP example project.

I installed Visual studio 2017, gperf. I have installed openssl, zlib with the help of vcpkg.

Running the command
`powershell -ExecutionPolicy ByPass .\build.ps1 -vcpkg_root E:/Github/Telegram/vcpkg` gives the error

tdutils.lib(Slice.obj) : error LNK2019: unresolved external symbol OPENSSL_cleanse referenced in function "public: void __cdecl td::MutableSlice::fill_zero_secure(void)" (?fill_zero_secure@MutableSlice@td@@QEAAXXZ) [E:\Github\Telegram\td\example\uwp\build-native\td\generate\generate_json.vcxproj]
E:\Github\Telegram\vcpkg\installed\x86-windows\debug\lib\libeay32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64' [E:\Github\Telegram\td\example\uwp\build-native\td\generate\generate_json.vcxproj]
E:\Github\Telegram\vcpkg\installed\x86-windows\debug\lib\zlibd.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64' [E:\Github\Telegram\td\example\uwp\build-native\td\generate\generate_json.vcxproj]

I have attached the entire log in the txt file.
[Uploading Telegram_uwp_error_log.txt…]()

**Comment by levlam** [comment]
As written, you have only x86 OpenSSL zlib and OpenSSL, but need x64 one. See full build instructions in https://tdlib.github.io/td/build.html?language=C%23.

**Comment by LohanSolo** [comment]
That's incorrect. I have installed both. I have attached screenshot of vcpkg.
![image](https://user-images.githubusercontent.com/24791578/71783271-501b6400-300a-11ea-86cd-efeaaab787a3.png)

**Comment by levlam** [comment]
CMake has found only x86-one. You can try to install also `openssl:arm-uwp`, `zlib:arm-uwp` and rebuild from scratch, using commands like
```
powershell -ExecutionPolicy ByPass ./build.ps1 -mode clean
powershell -ExecutionPolicy ByPass ./build.ps1 -vcpkg_root ../../vcpkg
```

The most reliable way is to fully follow build instructions from https://tdlib.github.io/td/build.html?language=C%23, including rebuilding dependencies by vcpkg.

**Comment by levlam** [comment]
@LohanSolo Have you succeeded?

**Comment by LohanSolo** [comment]
Got it working by forcing an x64 build by passing a parameter into cmake.
