### ISSUE TITLE
file RENAME failed to rename

### ISSUE THREAD

**Issue by emwsc** [tdlib/td#868]
I wanted to build TDLib for C# Window (c++/cli) and failed to do so on step: 

`./vcpkg.exe install openssl:x86-windows zlib:x86-windows`

with following error:

> CMake Error at ports/openssl-windows/portfile.cmake:177 (file):
>   file RENAME failed to rename
> 
>     ~/tdlib-c#/td/vcpkg/packages/openssl-windows_x86-windows/bin/openssl.exe
> 
>   to
> 
>     ~/tdlib-c#/td/vcpkg/packages/openssl-windows_x86-windows/tools/openssl/openssl.exe
> 
>   because: File exists
> 
> Call Stack (most recent call first):
>   scripts/ports.cmake:94 (include)
> 
> 
> Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
> 

Thing is that /tdlib-c#/td/vcpkg/packages/openssl-windows_x86-windows/bin/openssl.exe doesnt exist (at least after install error) and /tdlib-c#/td/vcpkg/packages/openssl-windows_x86-windows/tools/openssl is just empty folder.

**Comment by levlam** [comment]
Could you try without '#' in the file path?

**Comment by emwsc** [comment]
Yes, it worked out. Thank you.
