### ISSUE TITLE
Release tdlib 1.6?

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#870]
Has tdlib 1.6 been released?
Because CHANGELOG.md has been updated to 1.6 but README.md is still 1.5.4 and you haven't released version 1.6 at https://github.com/tdlib/td/releases.
Is version 1.6 available at https://github.com/tdlib/td/releases?

**Comment by levlam** [comment]
TDLib 1.6.0 is not released yet, only change log draft is ready.

**Comment by BarnameESF** [comment]
How many days does it take to get ready? We are very much looking forward to this release. For the new features it has.

**Comment by levlam** [comment]
@BarnameESF No ETA yet. But you can safely use current master branch.

**Comment by BarnameESF** [comment]
I downloaded the existing files and uploaded them to the server and made the changes you previously told me to update tbbot 1.5 but it still makes an error.
I think I need to make some new changes to tdbot 1.6.
Error during installation:
`[ 98%] Building CXX object CMakeFiles/telegram-bot.dir/main.cpp.o In file included from /root/tdbot/main.cpp:20:0: /root/tdbot/cliclient.hpp: In member function ‘void CliClient::run(td::uint64, std::__cxx11::string)’: /root/tdbot/cliclient.hpp:150:47: error: use of deleted function ‘td::JsonValue::JsonValue(const td::JsonValue&)’ auto r = from_json(object, as_json_value); ^ In file included from /root/tdbot/td/td/tl/tl_json.h:14:0, from /root/tdbot/cliclient.hpp:20, from /root/tdbot/main.cpp:20: /root/tdbot/td/tdutils/td/utils/JsonBuilder.h:473:3: note: declared here JsonValue(const JsonValue &other) = delete; ^ In file included from /root/tdbot/cliclient.hpp:21:0, from /root/tdbot/main.cpp:20: /root/tdbot/td/td/generate/auto/td/telegram/td_api_json.h:13:8: note: initializing argument 2 of ‘td::Status td::td_api::from_json(td::tl_object_ptr<td::td_api::Function>&, td::JsonValue)’ Status from_json(tl_object_ptr<Function> &to, td::JsonValue from); ^ CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1 CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2 CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2 Makefile:162: recipe for target 'telegram-bot' failed make: *** [telegram-bot] Error 2 `

**Comment by levlam** [comment]
tdbot uses private TDLib functions, so it needs to be fixed after every TDLib update. You need to wait, while someone fixes tdbot to support TDLib 1.6.0, and this is unlikely to happen before 1.6.0 release.
