### ISSUE TITLE
How to reset AuthorizationState ？

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#875]
When I logged in to the first account, I waited in AuthorizationStateWaitCode, but I did n’t receive the verification code, so I want to switch the phone number

**Comment by levlam** [comment]
The usual way is to call `logOut`.

There is also a special exception that `setAuthenticationPhoneNumber` can be called if there is no pending authentication query and the current authorization state is `authorizationStateWaitCode`, `authorizationStateWaitRegistration`, or `authorizationStateWaitPassword`.
