### ISSUE TITLE
Can tdlib handle InlineQuerys by Bot? 

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#876]
Is it with tdlib possible to use [InlineQuery ](https://core.telegram.org/bots/api#inlinequery)which is provided by a bot? In my case I made a Bot which provides a InlineQueryResultArticle which send a InlineButton to a user. So I would like to use this with tdlib...

Edit: I just found this: getInlineQueryResults function. Is this the way to achieve this?

**Comment by levlam** [comment]
To send an inline query, use the method `getInlineQueryResults`, to answer an inline query by a bot use the method `answerInlineQuery`, to choose one of bot responses to an inline query and send a corresponding message use the method `sendInlineQueryResultMessage`.

**Comment by Nukesor** [comment]
Inline queries are broken right now.
Using the switch to private messaging functionality is broken.


@riccardo found this change that has been made 5 days ago:

https://github.com/tdlib/td/commit/a9de33970b19f5dbc97f26bb907ced3e206b604e#diff-a1f80f20552f21f8b7ff9962e3772fadR333
