### ISSUE TITLE
switch_pm_parameter base64 check is broken

### ISSUE THREAD

**Issue by Nukesor** [tdlib/td#878]
Using Inline queries with a switch_pm_parameter is broken right now.
```Unallowed characters in switch_pm_parameter are used```

The bug popped up tonight at 3AM on all my bots. No changes on bot code or anything.
Inline queries seem to be broken for many bots right now. `switch_pm_parameter` doesn't work at all

@remembertheair found this change that has been made 5 days ago:
https://github.com/tdlib/td/commit/a9de33970b19f5dbc97f26bb907ced3e206b604e#diff-a1f80f20552f21f8b7ff9962e3772fadR333

**Comment by levlam** [comment]
This was fixed in https://github.com/tdlib/td/commit/d6dca91ff31494b097f876a31525f74b2f81c234.
