### ISSUE TITLE
Export From: [day], to: [day] is the same day export is empty.

### ISSUE THREAD

**Issue by Zann580** [tdlib/td#879]
When attempting to export messages from a group chat, I had set the 'From' date and the 'To' date as the same to not pull anything outside the targeted date, after exportation the generated HTML file read 'No exported messages'
I had expected the desktop app to either start from GMT 0 midnight to 23:59 the same day or local midnight to 23:59.

Zip file of generated export [ChatExport_09_01_2020 (1).zip](https://github.com/tdlib/td/files/4044230/ChatExport_09_01_2020.1.zip)

**Comment by levlam** [comment]
This is not related to TDLib. Feel free to create an issue in https://github.com/telegramdesktop/tdesktop.
