### ISSUE TITLE
how to sync chat_id before calling sendmessage function

### ISSUE THREAD

**Issue by korangu** [tdlib/td#88]
i am trying to send message using chat_id but its throwing error 

> chat not found

.

**Comment by levlam** [comment]
There are three cases
1. If use_message_database is set to true in setTdlibParameters call, than every previously seen chat is stored in the database and can be used in sendMessage call without any additional step.
2. If message database isn't used, but use_chat_info_database is set to true in setTdlibParameters call, than you need to call create*Chat method to create the chat from corresponding user_id/basic_group_id/supergroup_id/secret_chat_id, before it can be used. This requires one network request, but after that the chat can be used.
3. If even chat info isn't saved to database, then there is no way TDLib can know about a chat which wasn't received in an incoming update or a network query response after library start. You need to somehow find the chat, for example, using searchPublicChat, or by receiving an incoming message in the chat.

**Comment by korangu** [comment]
i am using bot Token so i can't use any of the the above option?

**Comment by levlam** [comment]
Logging as bot or as user is orthogonal to using databases. They can be enabled for bots too.

Also bots has an additional option: they can call getChat, specifying only chat_id, which requires one network request. After this call successfully returns, the chat is known and can be used if bot has access to it.

**Comment by ramikalai** [comment]
@levlam So essentially tdlib does't function if all databases (message & chat info) are set to false?

If I keep a record of the chatID/userID, why can't it send a message?

**Comment by levlam** [comment]
@ramikalai It is not enough to know chat_id/user_id to send a message, otherwise you can spam random users just iterating through all possible chat_id. TDLib stores data needed to use chat_id/user_id in the database, so if databases are disabled, you must reget the data from the server. So if the databases are disabled, you can interact only with users and chats received from server through TDLib. This is not an issue at all for ordinary Telegram clients, because they aren't supposed to store anything between client restarts.

**Comment by ramikalai** [comment]
Ah okay, that makes sense, thanks!

It seems like tdlib functions best with databases enabled as if they are disabled and the client does not cache anything, then it will require more network requests.

Out of curiosity, why not use UUIDs that can't be iterated over easily?

**Comment by levlam** [comment]
@ramikalai Initially, because of performance considerations. Current implemenation also effectively implies that usable chat_id/user_id are different for different users, which is a good property.
