### ISSUE TITLE
error build telegram-bot with tdlib 1.6.0

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#880]
![Capture](https://user-images.githubusercontent.com/26571020/72186066-33d04c00-33a9-11ea-993f-e442db6966b8.JPG)

Hello when i want to build telegram-bot i face the error in the picture.

**Comment by MalteToenjes** [comment]
Well 1.6 seems to be not released yet: https://github.com/tdlib/td/issues/870

**Comment by Kia-Pashang** [comment]
> Well 1.6 seems to be not released yet: #870

If it's not released yet , so the top error is about the 1.5.0, i cant build it the error is about the base64.cpp and base64.h

**Comment by MalteToenjes** [comment]
Not sure if you already did, but did you use this command generator?https://tdlib.github.io/td/build.html

**Comment by Kia-Pashang** [comment]
> Not sure if you already did, but did you use this command generator?https://tdlib.github.io/td/build.html


1- sudo apt install git build-essential cmake libssl-dev liblua5.2-dev gperf libconfig++-dev
2- git clone https://github.com/vysheng/tdbot.git
3- cd tdbot && git clone https://github.com/tdlib/td.git && cd ..
4- cd .. && mkdir build && cd build
5- cmake -DCMAKE_BUILD_TYPE=Release ../tdbot
6- make telegram-bot

**Comment by Kia-Pashang** [comment]
> ![Capture](https://user-images.githubusercontent.com/26571020/72186066-33d04c00-33a9-11ea-993f-e442db6966b8.JPG)
> 
> Hello when i want to build telegram-bot i face the error in the picture.

@levlam Hello , would you please help about this ??

**Comment by levlam** [comment]
The compilation error from the screenshots was fixed in the latest TDLib version.

But tdbot uses private TDLib functions, so it needs to be fixed after every TDLib update and can't use latest TDLib anyway. You need to wait, while someone fixes tdbot to support TDLib 1.6.0, and this is unlikely to happen before 1.6.0 release.

**Comment by Kia-Pashang** [comment]
> The compilation error from the screenshots was fixed in the latest TDLib version.
> 
> But tdbot uses private TDLib functions, so it needs to be fixed after every TDLib update and can't use latest TDLib anyway. You need to wait, while someone fixes tdbot to support TDLib 1.6.0, and this is unlikely to happen before 1.6.0 release.

Thanks for your answer , can i build telegram-bot without any errors now ??

**Comment by levlam** [comment]
You can't build tdbot with the recent TDLib version.

**Comment by Kia-Pashang** [comment]
> You can't build tdbot with the recent TDLib version.

What should i do now ? wait ? till when ?

**Comment by levlam** [comment]
Just wait.
