### ISSUE TITLE
How to getchat before last message?

### ISSUE THREAD

**Issue by masjaya19** [tdlib/td#882]
Halo guys,

Sorry i know this is not an issue but I have a question, I want to get chat before and the last message of the response from a telegram bot. how to do get the response for the last message and before, because i want to combine first and second response. i have a chat telegram twitter also but still not reply yet :) 

Thanks

**Comment by levlam** [comment]
I don't understand what exactly you are trying to achieve, but if you need some help about bots programming, you can ask questions in Telegram in @BotTalk or @BotSupport.

**Comment by masjaya19** [comment]
Halo @levlam 

Currently i've create C# apps use tdlib and i mean in tdlib for getchat method only have 
 `public GetChat(long chatId);` 
because i want to get two last chat or more than two last chat and i've read on https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html
in there have a limit, so my question is how to get a response chat for more than two chat or no limit

Thanks

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats and https://core.telegram.org/tdlib/getting-starting in general.

**Comment by masjaya19** [comment]
I see oke sir. thanks a lot
