### ISSUE TITLE
how to reset language pack database path

### ISSUE THREAD

**Issue by KazamaWataru** [tdlib/td#884]
When using TelegramX's td.binlog, an error log appears every time TDLib starts. (I'm making a feature for users to save their login status via a bot)

```
[ 1][t20][1578816938.786622047][LanguagePackManager.cpp:184][#4][!LanguagePackManager]        Can't open language pack database /data/user/0/org.thunderdog.challegram/files/langpack/main: [Error : 0 : Failed to open database: [Error : 0 : unable to open database file]]
```

**Comment by levlam** [comment]
Language pack database path is specified by the application via `setOption("language_pack_database_path", ...)` method. There is no way the path can be changed through interface.
