### ISSUE TITLE
About groups

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#886]
@levlam 
 What methods can I use to manage more groups? More than 500, in fact, now each user can only manage 500 groups? No matter what method, whether it is a basic group, a super group or a channel? The total cannot be greater than 500. How many can each group type be? Or just the total!

**Comment by levlam** [comment]
500 is a total limit for supergroups and channel alltogether.

**Comment by AquariusHunters** [comment]
@levlam Does this number include the basicgroup?

**Comment by levlam** [comment]
No.

**Comment by AquariusHunters** [comment]
@levlam 
Is there any way I can manage more than 500 groups? Such as becoming a VIP

**Comment by levlam** [comment]
No.

**Comment by AquariusHunters** [comment]
@levlam OK，Thanks
