### ISSUE TITLE
tdweb

### ISSUE THREAD

**Issue by jafri** [tdlib/td#887]
@arseny30 you published latest tdweb 1.5.9 under your own scope to npm, the latest source in this repo also seems to be just 1.5.0

**Comment by levlam** [comment]
`@arseny30/tdweb` contains `tdweb` built with the latest available there TDLib 1.5.4. This is a private `tdweb` version, used for testing purposes.

**Comment by jafri** [comment]
@levlam it is quite annoying as the private package is being used in the repo `telegram-react`, and replacing with `tdweb` does not work

**Comment by levlam** [comment]
@jafri Treat this as a dev branch of the `telegram-react`, and use previous stable version depending on public tdweb 1.5.0 if this matters to you.

**Comment by levlam** [comment]
tdweb was updated to 1.6.0: https://www.npmjs.com/package/tdweb/v/1.6.0.
