### ISSUE TITLE
Search for "Deleted Account"

### ISSUE THREAD

**Issue by lsndr** [tdlib/td#889]
Hello!

I'm trying to use `searchMembers` and `getSupergroupMembers` methods to search for deleted accounts of a chat. Iuse "Deleted Account" as a query. But the methods always return empty arrays. 

When I search with query "Deleted Account" in the official client, it finds deleted accounts, but TDLib doesn't. Why?

**Comment by lsndr** [comment]
`system_language_code` is set to `en`

**Comment by levlam** [comment]
"Deleted Account" is just a string from language pack, which can't affect the search. No users can be found by "Deleted Account" request, unless this is they real name. Also there is no way to find deleted accounts in a supergroup. The deleted accounts even are filtered out by the server if supergroup size is at least 5000. If you somehow manage to find them with query "Deleted Account" in an official app, you can examine the app's source code, to find the cause. Probably this is a some kind of a local search among locally known chat members.

**Comment by KazamaWataru** [comment]
@lsndr  just GetSupergroupMembers 、call  getUser for each user and check if user type equals UserTypeDeleted
