### ISSUE TITLE
CONNECTION_SYSTEM_EMPTY error after tdlib initialization.

### ISSUE THREAD

**Issue by sapelkinAV** [tdlib/td#89]
If someone got this error before, please answer me, how to fix this bug. I'm not sure is this bug or not, maybe I'm doing wrong stuff. But I'm not found any documentation about error code = 400 CONNECTION_SYSTEM_EMPTY.

Error log:

`I/DLTD: [ 3][t 2][1518878394.418695927][ConfigManager.cpp:324][!Recoverer][&config_recoverer]	ON CONNECTING false
I/DLTD: [ 3][t 2][1518878394.418707132][ConfigManager.cpp:438][!Recoverer][&config_recoverer]	false 0.398375
I/DLTD: [ 3][t 2][1518878394.418716908][ConfigManager.cpp:482][!Recoverer][&config_recoverer]	Wakeup NEVER
I/DLTD: [ 3][t 2][1518878394.418736935][Session.cpp:432][!Session:1:main]	new_session_created 5740779990107441533 6523986821830605112
I/DLTD: [ 3][t 2][1518878394.418746233][Session.cpp:434][!Session:1:main]	Sending updatesTooLong to force getDifference
I/DLTD: [ 3][t 2][1518878394.418781042][NetQuery.h:345][!Session:1:main]	[Query:[id:0][tl:0x00000000][state:Result][tl:0xe317af7e]]
I/DLTD: [ 3][t 2][1518878394.418798208][NetQuery.h:239][!Session:1:main][&net_query]	[Query:[id:0][tl:0x00000000][state:Result][tl:0xe317af7e]] [debug:dispatch]
I/DLTD: [ 3][t 2][1518878394.418812037][NetQuery.h:239][!Session:1:main][&net_query]	[Query:[id:0][tl:0x00000000][state:Result][tl:0xe317af7e]] [debug:sent to td (no callback)]
I/DLTD: [ 3][t 2][1518878394.418823957][NetQuery.h:239][!Td][&net_query]	[Query:[id:0][tl:0x00000000][state:Result][tl:0xe317af7e]] [debug:Td: received from DcManager]
I/DLTD: [ 3][t 2][1518878394.418833017][Td.cpp:3691][!Td][&net_query]	on_result [Query:[id:0][tl:0x00000000][state:Result][tl:0xe317af7e]]
I/DLTD: [ 3][t 2][1518878394.418851137][UpdatesManager.cpp:587][!Td]	Receive updatesTooLong {
        }
I/DLTD: [ 3][t 2][1518878394.418863297][UpdatesManager.cpp:590][!Td]	Ignore updates received before authorization or after logout
I/DLTD: [ 3][t 2][1518878394.418891191][Session.cpp:511][!Session:1:main][&net_query]	Ack [msg_id:6523986821830605112][Query:[id:65536][tl:0x1fb33026][state:Query]]
I/DLTD: [ 3][t 2][1518878394.418982029][Session.cpp:511][!Session:1:main][&net_query]	Ack [msg_id:6523986821830608488][Query:[id:131072][tl:0xc4f9186b][state:Query]]
I/DLTD: [ 3][t 2][1518878394.419034958][Session.cpp:1176][!Session:1:main]	Wakeup After 29.999807
D/DLTD: [ 4][t 2][1518878394.423456192][BufferedFd.h:168][!Session:1:main]	flush_read: +248B[total:248B]
D/DLTD: [ 4][t 2][1518878394.423686981][Session.cpp:644][!Session:1:main]	Session::on_error [id:6523986821830605112][error_code:400][msg:CONNECTION_SYSTEM_EMPTY]
I/DLTD: [ 3][t 2][1518878394.423714161][Session.cpp:652][!Session:1:main][&net_query]	return query error [Query:[id:65536][tl:0x1fb33026][state:Query]]
I/DLTD: [ 3][t 2][1518878394.423734188][NetQuery.h:300][!Session:1:main][&net_query]	Got error [Query:[id:65536][tl:0x1fb33026][state:Query]] [Error : 400 : CONNECTION_SYSTEM_EMPTY]
I/DLTD: [ 3][t 2][1518878394.423759937][NetQuery.h:239][!Session:1:main][&net_query]	[Query:[id:65536][tl:0x1fb33026][state:Error][Error : 400 : CONNECTION_SYSTEM_EMPTY]] [debug:dispatch]
I/DLTD: [ 3][t 2][1518878394.423779249][NetQuery.h:239][!Session:1:main][&net_query]	[Query:[id:65536][tl:0x1fb33026][state:Error][Error : 400 : CONNECTION_SYSTEM_EMPTY]] [debug:sent to callback]
I/DLTD: [ 3][t 2][1518878394.423794985][NetQuery.h:239][!Td][&net_query]	[Query:[id:65536][tl:0x1fb33026][state:Error][Error : 400 : CONNECTION_SYSTEM_EMPTY]] [debug:Td: received from DcManager]
I/DLTD: [ 3][t 2][1518878394.423807144][Td.cpp:3691][!Td][&net_query]	on_result [Query:[id:65536][tl:0x1fb33026][state:Error][Error : 400 : CONNECTION_SYSTEM_EMPTY]]
E/DLTD: [ 1][t 2][1518878394.423820019][Td.cpp:129][!Td]	GetNearestDc returned [Error : 400 : CONNECTION_SYSTEM_EMPTY]`

**Comment by msh15** [comment]
I did get that error too ...

[ 1][t 2][1519036496.355624914][Td.cpp:135][!Td]        GetNearestDc returned [Error : 400 : CONNECTION_SYSTEM_EMPTY]
[ 1][t 2][1519036496.356211185][ConfigManager.cpp:597][!ConfigManager]  TODO: getConfig failed: [Error : 400 : CONNECTION_SYSTEM_EMPTY]

any help will be appreciate.

**Comment by korangu** [comment]
this is not a bug, it means you failed to supply some params  in the tdlib init parameters 

make sure you initialize Tdlib with the following params.

`tdlibParameters use_test_dc:Bool database_directory:string files_directory:string use_file_database:Bool use_chat_info_database:Bool use_message_database:Bool use_secret_chats:Bool api_id:int32 api_hash:string system_language_code:string device_model:string system_version:string application_version:string enable_storage_optimizer:Bool ignore_file_names:Bool = TdlibParameters;`

**Comment by msh15** [comment]
I did it exactly as it's documentation said.
I'm using a virtual machine (debian 8) and i used linux machine and environment setup to built tdlib.
is that CONNECTION_SYSTEM_EMPTY becuase of that my vm is running a client and trying to authenticate it to tdlib?

**Comment by msh15** [comment]
You were right about initializing correctly, the faullt was mine.
I just leave empty the system_version:string parameter. :-|

**Comment by msh15** [comment]
@sapelkinAV 
Actually the 400 error code is exactly for this field. pass something to that parameter and you'll see your error would be gone.

**Comment by levlam** [comment]
This error is returned when empty system_version is specified in setTdlibParameters.

**Comment by sapelkinAV** [comment]
Thanks to everyone, it was really helpful. I'm closing issue.
