### ISSUE TITLE
Optional / null arguments with tdjson

### ISSUE THREAD

**Issue by mgrandi** [tdlib/td#890]
I am using `tdjson`, but I have noticed there are several types that have optional arguments, but this is not available for parsers in the TL file, but it does seem to be present in the comment ABOVE the type in the TL file. For example:

(these are taken from the tdlib TL file: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl )

User.profile_photo may be null:
```plaintext
//@description Represents a user @id User identifier @first_name First name of the user @last_name Last name of the user @username Username of the user
//@phone_number Phone number of the user @status Current online status of the user @profile_photo Profile photo of the user; may be null
//@outgoing_link Relationship from the current user to the other user @incoming_link Relationship from the other user to the current user
//@is_verified True, if the user is verified @is_support True, if the user is Telegram support account
//@restriction_reason If non-empty, it contains the reason why access to this user must be restricted. The format of the string is "{type}: {description}".
//-{type} contains the type of the restriction and at least one of the suffixes "-all", "-ios", "-android", or "-wp", which describe the platforms on which access should be restricted. (For example, "terms-ios-android". {description} contains a human-readable description of the restriction, which can be shown to the user)
//@is_scam True, if many users reported this user as a scam
//@have_access If false, the user is inaccessible, and the only information known about the user is inside this class. It can't be passed to any method except GetUser @type Type of the user @language_code IETF language tag of the user's language; only available to bots
user id:int32 first_name:string last_name:string username:string phone_number:string status:UserStatus profile_photo:profilePhoto outgoing_link:LinkState incoming_link:LinkState is_verified:Bool is_support:Bool restriction_reason:string is_scam:Bool have_access:Bool type:UserType language_code:string = User;
```

updateSelectedBackground.background may also be null:
```plaintext
//@description The selected background has changed @for_dark_theme True, if background for dark theme has changed @background The new selected background; may be null
updateSelectedBackground for_dark_theme:Bool background:background = Update;
```
This presents a problem with my code, as unless I specify otherwise, I expect all fields of the type to be present in the JSON, even if the value is `null`. Is the `tdjson` library removing these if they are null? or are they actual optional arguments that can somehow be exposed in the TL file?

**Comment by levlam** [comment]
tdjson removes all objects that are `null` when storing TDLib API objects to JSON. So a field is missing, only if it is `null`.

In incoming requests to TDLib any field can be omitted with the default value `null` for objects. This may form a correct or an incorrect request, depending on other parameters.

**Comment by levlam** [comment]
@mgrandi Why you can't check existence of the field before trying to access it, or just handle it's value as `None` or `null`?

**Comment by mgrandi** [comment]
I figured out a solution, which involved basically what you said, if the value is not present i just set it to `None` in my code that parses the JSON received from `td_json_client_receive` into my model classes 

Ideally i feel this should maybe be an option with tdjson, as some serialization frameworks would probably not be as flexible if there is missing fields

**Comment by levlam** [comment]
@mgrandi Every deserialization framework should be able to check field existence, so I don't expect a problem there. Moreover, I expect that most frameworks are able to silently return None/null for nonexistent fields. For example, the parameter `default=None` can be safely added when parsing all object fields in your code to completely resolve the problem.

**Comment by mgrandi** [comment]
I concede that point, i'll close this to mark it as solved
