### ISSUE TITLE
Enabling TON integration

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#891]
In notes to 1.6.0 changes I see:

>   - Added the option `default_ton_blockchain_config`, containing the default TON Blockchain config. If empty, TON integration is disabled, otherwise the config needs to be passed to tonlib.

This option is empty in my TDLib instance.

Client, that I'm writing, already has integration with tonlib, however it requires proper initialization.  For now initialization is done by hand using external TON config file, this is very inconvenient for users.

Is it possible to "enable" TON integration in TDLib, so it could provide default config for the tonlib?

Thanks

**Comment by levlam** [comment]
This is expected for now. There is no way to force server to provide a valid config, so for now the TON Blockchain can't be integrated with Telegram and `tonlib` needs to be used independently to access the TON Blockchain.

To initialize `tonlib`, you can use a test lite-client config from https://test.ton.org/ton-lite-client-test1.config.json and a blockchain name "testnet2".

The `sendTonLiteServerRequest` and `getTonWalletPasswordSalt` methods also shouldn't be used until the integration is enabled.
