### ISSUE TITLE
About Proxy

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#893]
@levlam 
I used the proxy mode, but I often see [4] [t 5] [1579069626.331792116] [ConnectionCreator.cpp: 720] [# 1] [! ConnectionCreator] Save proxy last used date 1579069625 I ’m not I understand the reason for this problem. Is it because I'm using the proxy incorrectly?

**Comment by levlam** [comment]
This is not a problem at all. This is just a debug logging.

**Comment by AquariusHunters** [comment]
In that case, I only need to submit my proxy information to the server during the authorizationStateWaitTdlibParameters. After that, I don't need to monitor the proxy status, right? @levlam

**Comment by levlam** [comment]
The only thing you need is to enable a proxy via call to `addProxy`/`enableProxy` whenever appropriate.
