### ISSUE TITLE
Java JSON vs JNI performance

### ISSUE THREAD

**Issue by whyoleg** [tdlib/td#894]
Hi, can you give some raw estimation of performance difference between using JSON client or client with generated JNI bindings?

**Comment by levlam** [comment]
The performance and memory consumption difference shouldn't be significant for the most application. The main difference is in the usage convenience and strict type checks.

**Comment by whyoleg** [comment]
Thx, looks optimistic for me!
But nevertheless, may be you can share some thoughts about, how to check the performance difference?
Because, I can't just spam requests to tdlib, even if I use test server, it will block me after some same requests (as I remember, I've tried).
May be it somehow possible to 'mock' requests to telegram api, or ignore them, and just check the difference of my implementations using JNI and JSON?

**Comment by levlam** [comment]
You can use some local request like `getMe`, `getChat` or `getMessage` to measure the performance.

**Comment by whyoleg** [comment]
Oh, Perfect!
I will write some benchmarks for myself
So, now I have one more question, hah. As I see in `td_api.tl` there are methods like you provided with `this is an offline request` in documentation. So only those requests, are offline, yes?

**Comment by levlam** [comment]
Those request are __always__ offline. Most other requests has local cache, so they don't need a network connection to succeed after the first request.
