### ISSUE TITLE
Inconsistent updateNewMessage after TDLib wakeup

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#896]
I'm experiencing inconsistent state for open chat after long sleep time (say 3 days).  Consider events for opened chat(`CHAT1`) just before sleep:
```chat
updateNewMessage MSG1
updateNewMessage MSG2
updateNewMessage MSG3
updateChatLastMessage MSG3
```

Then laptop goes to sleep, and after wake-up we get next events:
```events
updateConnectionState Connecting
updateOption "unix_time" <timestamp>
```
Then suddenly state goes to
```events
updateConnectionState Ready
```
And we get updates for `CHAT1`
```events
updateChatLastMessage <with no last_message!, just updated order>
updateNewMessage MSG10
updateChatLastMessage MSG10
```

And then connection state goes to normal
```events
updateConnectionState Updating
consistent update events for all other chats
updateConnectionState Ready
```

Messages between `MSG3` and `MSG10` for `CHAT1` are not delivered at all, leaving `CHAT1` in inconsistent state.  To recover its state client need to refetch messages history.  Also this `updateChatLastMessage` with unset `last_message` is very suspicious, because there is `updateChatOrder` if TDLib wants to update just the chat order, so there is no reason at all to use `updateChatLastMessage` with unset `last_message`.

I think this issue only triggered if some chat remains opened(`closeChat` is not called), when laptop goes to sleep.  And also sleep time matters, I have not experienced any inconsistencies if sleep time measures in hours.

Unfortunately that wake-up generated too many TDLib logs and only my internal(non-tdlib) logging is available.

I believe I've seen such behaviour for older TDLib versions (since 1.3.0) as well.  Now I use latest TDLib (1.5.4) from master branch

What is the best workaround for now?  Should I just close all the chats if states changes to "Connecting"?

Thanks

**Comment by levlam** [comment]
You have just discovered that clients download not all messages in channels and supergroups and there can be gaps in the message history, which are filled only when the chat is opened. The `updateChatLastMessage` with a null last chat message notifies exactly about a gap creation as noted in the documentation: "If last_message is null, then the last message in the chat became unknown. Some new unknown messages might be added to the chat in this case". The client needs to mark last chat message in the chat as unknown and do not show new messages received through `updateNewMessage` just below the last shown message.

**Comment by zevlg** [comment]
Ah, nice!  I like this feature
