### ISSUE TITLE
Unable to catch some errors in Java: [Error : 406 : AUTH_KEY_DUPLICATED]

### ISSUE THREAD

**Issue by OlivierFreyssinet** [tdlib/td#897]
Hi everyone, I'm using a Java version of `tdlib` to implement a Telegram client in an Android app.
There's one bug that happens very rarely, so it's hard to reproduce:

Some users try to send a message, the message isn't sent but nothing happens, no error is thrown, so it's kind of an invisible error. However this appears in the logs:
```
E DLTD    : [ 1][t 4][1579532844.030200243][ConfigManager.cpp:712][!ConfigManager]	TODO: getConfig failed: [Error : 406 : AUTH_KEY_DUPLICATED]
E DLTD    : [ 1][t 4][1579532847.633707047][UpdatesManager.cpp:140][!Td]	updates.getDifference error: [Error : 406 : AUTH_KEY_DUPLICATED]
```
I read that the only solution for that is basically to delete the Telegram database and re-authenticate the user. I'd like at least to be able to detect this (rare) error when it happens and inform the user.

Is there a way to catch this error using the Java library ? Right now this is how I instantiate the client:

```
public class TelegramClient implements Client.ResultHandler, Client.ExceptionHandler{
    public TelegramClient(){
        Client.setLogVerbosityLevel(1);
        TdApi.GetAuthorizationState authStateRequest = new TdApi.GetAuthorizationState();
        client = Client.create(this, this, this);
        client.send(authStateRequest, this);
    }
    // ...

    @Override
    public void onException(Throwable e) {
      Log.e(TAG, e); // this is never called when the error happens
    }
    // ...
}
```

**Comment by levlam** [comment]
The error happens only if the database was copied by some external means, so the best way is to avoid the copying and therefore the error.

If this happened anyway, the app should receive an update `TdApi.UpdateServiceNotification` from TDLIb with type beginning with "AUTH_KEY_DROP_". After that the notification should be shown to the user with two buttons "Cancel" and "Log out" under it. If user presses the second, all local data should be destroyed using Destroy method. See `TdApi.UpdateServiceNotification` documentation for more details.

**Comment by OlivierFreyssinet** [comment]
Thanks for the quick reply, I'll look into that !
The weird thing is that I'm not doing any sort of manipulation on the database... I'm using react-native so maybe it has something to do with it, but anyway this bug happens very rarely, I just want to be able to at least detect it.

**Comment by levlam** [comment]
The error means that there are two TDLib instances running on a different copies of the database simultaneously. But there is no way to share authorization between two instances, so the server is forced to log out both. It does this gracefully allowing for user to save their data, so this is done using `UpdateServiceNotification` and not through `UpdateAuthorizationState` with `AuthorizationStateLoggingOut` as usual.

**Comment by OlivierFreyssinet** [comment]
Wow that's great ! Thanks a lot for this library 👍 This world would be perfect if everyone would switch from WhatsApp to Telegram haha
