### ISSUE TITLE
Get a list of users in a group (Golang)

### ISSUE THREAD

**Issue by astravexton** [tdlib/td#898]
Currently I'm doing `GetChat` and then passing the `SupergroupId` to `GetSupergroupMembers` which returns a list of members like this:
`&{meta:{Type: Extra:} UserId:55258520 InviterUserId:63391517 JoinedChatDate:1509301864 Status:0xc000262450 BotInfo:<nil>}`

How do I get their names in a group of 500+ people without doing 1 call per member?

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#handling-updates.
