### ISSUE TITLE
getChats returns every single chat

### ISSUE THREAD

**Issue by morojenoe** [tdlib/td#899]
Hello,

when I call getChats() with limit equals to 5, I receive from updates every single chat (nearly 100). Is it intended? Maybe I'm doing something in a wrong way?
I use tdweb 1.5.0, config:
```
{
  useTestDc: false,
  databaseDirectory: 'tdlib',
  useFileDatabase: false,
  useChatInfoDatabase: false,
  useMessageDatabase: false,
  useSecretChats: false,
  apiId: ...,
  apiHash: ...,
  systemLanguageCode: 'en',
  deviceModel: getDeviceModel(),
  systemVersion: getSystemVersion(),
  applicationVersion: '1.0.0',
}
```
request parameters
```
{
        limit: 5,
        offsetOrder: '9223372036854775807',
        offsetChatId: 0
}
```

**Comment by levlam** [comment]
This is expected, The request will return at most 5 chats, but there can be more or less chats loaded and the `updateNewChat` updates sent. The updates are not directly related to any specific request and there are dozens cases leading to the update.
