### ISSUE TITLE
my channel banned can you help my ? 

### ISSUE THREAD

**Issue by zetatechi** [tdlib/td#900]
I had a channel with 80K members for 4 years. Telegram has banned it without a single warning. It's not fair because we didn't do anything wrong during these 4 years.  which is not related to terrorism, not related to sex , not related to spam! not related to child porn , not related to Annoyance for the telegram
![image](https://user-images.githubusercontent.com/60185719/72903668-e22da700-3d42-11ea-8ae0-29c7c9cdb21d.png)

**Comment by levlam** [comment]
This is not related to TDLib. You can ask general questions through in-app support or by mentioning @telegram on Twitter.
