### ISSUE TITLE
How to determine if a message was viewed by the other user?

### ISSUE THREAD

**Issue by digabriel** [tdlib/td#903]
I'm calling `OpenChat` when opening the chat and then calling `GetMessage` for every history message. Even doing this, the`views` property continues to be 0.

Is there any other way to determine if an outgoing message was viewed by the other user? Also, how can I detect this on a ChatList screen, where I don't open the chat yet?

Thank you very much.

**Comment by levlam** [comment]
Every `chat` object has the field `last_read_outbox_message_id`. All messages with ID less or equal to this are read by the peer. On the chat list you can compare the `chat.last_read_outbox_message_id` with `chat.last_message,id`.

**Comment by digabriel** [comment]
Awesome! Thank you!
