### ISSUE TITLE
how to get messages by media_album_id

### ISSUE THREAD

**Issue by GhostLee** [tdlib/td#904]
I want get all messages in a album, but there is no api about how to query message list or message 
count.So how to deal with it?

**Comment by levlam** [comment]
Messages in an album supposed to be successive, so you can use `getChatHistory` with offset -10 and limit 21.

If you want to handle new messages received through updateNewMessage, then you need to wait some time after the first message is received for other messages and can get previous album messages only after that.

**Comment by GhostLee** [comment]
it means that i can only get messages by `getChatHistory` API, and an album_id only used as a mark.anyway~thx
