### ISSUE TITLE
Wrong UpdateDeleteMessages!!!!!

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#905]
Hi,
I get UpdateDeleteMessages at my resultHandler and I receive wrong ones! The updates give me about deletion of a message but that message exists in the channel!!

**Comment by yasharzb** [comment]
I found the solution. I hadn't checked the isPermanent field. But what is this field for? I can't understand it how a message can be deleted from a channel but the deletion is not permanent?

**Comment by levlam** [comment]
@yasharzb There are a lot of cases of non-permanent deletion of messages when the message became inaccessible just for the current user. The simplest way to achieve this is to leave a private channel.
