### ISSUE TITLE
Build for Xamarin 

### ISSUE THREAD

**Issue by Behzod85** [tdlib/td#906]
How to build for Xamarin.Forms?

**Comment by levlam** [comment]
You need to build TDLib with JSON interface for Android and iOS. You can find prebuilt for Android one of the latest TDLib versions in https://t.me/tdlibchat/1245. Example of building for iOS can be found at https://github.com/tdlib/td/tree/master/example/ios.

Then you can use built libraries from C# as described in https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/.

**Comment by Behzod85** [comment]
System.EntryPointNotFoundException
td_json_client_create assembly:<unknown assembly> type:<unknown type> member:(null)

getting this exception.

**Comment by levlam** [comment]
@Behzod85 The prebuilt version for Android uses names beginning with underscore, i.e. "_td_json_client_send".

**Comment by Behzod85** [comment]
Where can I see all methods for prebuild versions for android and ios?

**Comment by levlam** [comment]
iOS has no prebuilt version. The binary will have usual names by default.

**Comment by Behzod85** [comment]
I have a problem making binaries, is ok to use this binary? [https://github.com/leoMehlig/TDJSON/tree/master/lib](url)

**Comment by levlam** [comment]
@Behzod85 This is a prebuilt for iOS TDLib 1.5.0 - an older version.

**Comment by Behzod85** [comment]
I am trying to build prebuilt as written  here:[https://github.com/tdlib/td/tree/master/example/ios](url). Getting error when wrote this: "./build-openssl.sh"

clang: warning: no such sysroot directory: '../SDKs/' [-Wmissing-sysroot]
In file included from cryptlib.c:117:
./cryptlib.h:62:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h>
          ^~~~~~~~~~
1 error generated.
make[2]: *** [cryptlib.o] Error 1
make[1]: *** [build_crypto] Error 1
make: *** [build/tvOS/openssl-1.0.2n-appletvsimulator.x86_64/libssl.a] Error 2
cp: ./Python-Apple-support/build/tvOS/libcrypto.a: No such file or directory
cp: ./Python-Apple-support/build/tvOS/libssl.a: No such file or directory
cp: ./Python-Apple-support/build/tvOS/Support/OpenSSL/Headers/: No such file or directory

**Comment by Behzod85** [comment]
Mine prebuild for iOS became very big (about 300 MB) rather than I mentioned above. Does it mean that the application made using this library also will be more than 300 MB?

**Comment by levlam** [comment]
@Behzod85 No. Only binary needed for target architecture will be installed on the client device. Also, the binary will be compressed.

**Comment by bsglinux16** [comment]
> System.EntryPointNotFoundException
> td_json_client_create assembly: type: member:(null)
> 
> getting this exception.

Rebuild tdsharp libraries and successfuly working
