### ISSUE TITLE
Building for Tizen

### ISSUE THREAD

**Issue by githubcatw** [tdlib/td#908]
How can I compile TDLib for Tizen and Xamarin.Forms? There is a resolved issue about building for Xamarin but does that work for Tizen too?

**Comment by levlam** [comment]
It should be possible to build TDLib for Tizen too.
First you need to run native build to generate some source files:
```
mkdir build
cd build
cmake ..
cmake --build . --target prepare_cross_compiling
```

Than you can copy all source files from directories `td`, `tdactor`, `tddb`, `tdnet`, `tdutils`, `tdutils/generate/auto`, `td/generate/auto` into a single `td/` folder, add the directory to a project in Tizen Studio and build it using the latest available compiler.

**Comment by MarcAnt01** [comment]
> It should be possible to build TDLib for Tizen too.
> First you need to run native build to generate some source files:
> 
> ```
> mkdir build
> cd build
> cmake ..
> cmake --build . --target prepare_cross_compiling
> ```
> 
> Than you can copy all source files from directories `td`, `tdactor`, `tddb`, `tdnet`, `tdutils`, `tdutils/generate/auto`, `td/generate/auto` into a single `td/` folder, add the directory to a project in Tizen Studio and build it using the latest available compiler.

About C# .NET Tizen apps? In the build instructions there doesn't seem to be an option for Tizen.
This kind of apps need to be made in Visual Studio 2019 using a Samsung extension

**Comment by levlam** [comment]
@MarcAnt01 
TDLib can be built for Tizen to a shared library and used there. The workflow should be no different from the other operating systems.

**Comment by githubcatw** [comment]
I can't build using @levlam's instructions on Windows because CMake complains about zlib missing even though I have it in the PATH variable.

```
C:\Users\User\Downloads\td\build>cmake ..
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: C:/Program Files/OpenSSL-Win64/include optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:287 (message):
  Not found zlib: skip TDLib, tdactor, tdnet, tddb


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "tdutils" in directory C:/Users/User/Downloads/td/tdutils

-- Configuring incomplete, errors occurred!
See also "C:/Users/User/Downloads/td/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/User/Downloads/td/build/CMakeFiles/CMakeError.log".
```

**Comment by githubcatw** [comment]
Here are the 2 .log files mentioned by CMake:
[logfiles.zip](https://github.com/tdlib/td/files/4427597/logfiles.zip)

**Comment by levlam** [comment]
@githubcatw If you have OpenSSL installed, you must also have zlib installed. If you temporarily remove OpenSSL, then source code generation will succeed.

**Comment by githubcatw** [comment]
I removed OpenSSL and is somehow still thinks that OpenSSL is installed.

**Comment by githubcatw** [comment]
```
C:\Users\User\Downloads\td\build>cmake ..
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: C:/Program Files/OpenSSL-Win64/include optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:287 (message):
  Not found zlib: skip TDLib, tdactor, tdnet, tddb


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "tdutils" in directory C:/Users/User/Downloads/td/tdutils

-- Configuring incomplete, errors occurred!
See also "C:/Users/User/Downloads/td/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/User/Downloads/td/build/CMakeFiles/CMakeError.log".

C:\Users\User\Downloads\td\build>dir "C:/Program Files/OpenSSL-Win64/"
 Volume in drive C has no label.
 Volume Serial Number is ****-****

 Directory of C:\Program Files\OpenSSL-Win64

File Not Found
```

**Comment by githubcatw** [comment]
Now I get a different error about OpenSSL missing.
```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The CXX compiler identification is MSVC 19.23.28106.4
-- The C compiler identification is MSVC 19.23.28106.4
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ccache (this is NOT an error)
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:279 (message):
  Not found OpenSSL: skip TDLib, tdactor, tdnet, tddb


-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/User/Downloads/td/build
```

**Comment by levlam** [comment]
@githubcatw There are no errors there now.

**Comment by githubcatw** [comment]
It's complaining about zlib missing and skips building TDLib. Is that normal?

**Comment by levlam** [comment]
It is absolutely normal, because native build is needed only for source code generation.

**Comment by githubcatw** [comment]
Thanks.

**Comment by levlam** [comment]
Only *.cpp, *.c, *.h and *.hpp files.

**Comment by cl-ement05** [comment]
> 
> First you need to run native build to generate some source files:
> 
> ```
> cmake --build . --target prepare_cross_compiling
> ```

Do we build native files like you say or just prepare cross-compiling like the ```cmake```command does ?

**Comment by levlam** [comment]
@cl-ement05 You need to build specified target to generate needed source files.

**Comment by cl-ement05** [comment]
> 
> 
> @cl-ement05 You need to build specified target to generate needed source files.

So I just need to build TdLib and put the generated files in td/ tdnet/ ... in the include folder of my Tizen Project ?

**Comment by levlam** [comment]
@cl-ement05 You need to put most TDLib source files (including autogenerated) in a Tizen Project and build them as shared library. Tests, all files with main() method, C++/CLI files aren't needed.

**Comment by cl-ement05** [comment]
> 
> 
> @cl-ement05 You need to put most TDLib source files (including autogenerated) in a Tizen Project and build them as shared library. Tests, all files with main() method, C++/CLI files aren't needed.

Yes but where in the Tizen Shared Library Project ??
When I create a new native Shared Library I get this directory tree :
```
--MyLibrary
   -> inc
   -> res
   -> src
   -> Includes
```
Note Includes folder is for Tizen stuff. So where should I put built TdLib files ?

**Comment by levlam** [comment]
Almost everything in src. Public headers (td/telegram/td_json_client.h) in inc.

**Comment by cl-ement05** [comment]
Ok. And do I need to keep the tree generated by TdLib ? Let's take an exemple. Let's say that I have a file ```<tdlib sources>td/telegram/generate/main.cpp``` should I directly put main.cpp to the root of src of my Project or should I create all the dirs (td/telegram/generate) and then put main.cpp in them ? Same for headers. If a have a file in a subdir of td/ should I put this file in the root in inc folder of my project or should I copy the file to the full path (including subdirectories) ? Sorry if what I wrote is messed up, I hope my question is still clear

**Comment by levlam** [comment]
You should copy everythng to a single td/ folder, i.e.` tdutils/td/utils/common.h` -> `td/utils/common.h`. */generate/* folders don't need to be copied, but autogenerated files in */generate/auto/* must be copied.

**Comment by cl-ement05** [comment]
> 
> 
> Almost everything in src. Public headers (td/telegram/td_json_client.h) in inc.

how can I know if a header file is "public" like you said and that I must put it in inc and not src ?

**Comment by cl-ement05** [comment]
This is how my tree looks like right now 
![image](https://user-images.githubusercontent.com/64481347/111501315-2947da00-8745-11eb-815e-d1aaeb340a5f.png)

**Comment by levlam** [comment]
If you want to include a header in your code, then it is public.

This is wrong, but you have better try to compile this and fix received compiler errors about not found files.

**Comment by cl-ement05** [comment]
> 
> 
> If you want to include a header in your code, then it is public.
> 
> This is wrong, but you have better try to compile this and fix received compiler errors about not found files.

Well actually compiler didn't go into any error and successfully outputed a libtdapi.so file. Now how I am supposed to include it in my main program / how can I use TdLib in my program ?

**Comment by levlam** [comment]
@cl-ement05 It can be used as any other shared library. But I really doubt that it could correctly resolve includes and build source code this such folder layout.
