### ISSUE TITLE
Problem installing tdbot based on tdlib 1.6

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#909]
Hi
Do not be tired . Thank you for releasing the new version.
I want to install tdbot based on Tdlib 1.6 , of course I made the changes you mentioned for version 1.5 but it gives the following error :

Please guide to install tdbot based on tdlib 1.6  . Thanks !

`
[ 98%] Building CXX object CMakeFiles/telegram-bot.dir/main.cpp.o
In file included from /root/tdbot/main.cpp:20:0:
/root/tdbot/cliclient.hpp: In member function ‘void CliClient::run(td::uint64, std::__cxx11::string)’:
/root/tdbot/cliclient.hpp:150:47: error: use of deleted function ‘td::JsonValue::JsonValue(const td::JsonValue&)’
       auto r = from_json(object, as_json_value);
                                               ^
In file included from /root/tdbot/td/td/generate/auto/td/telegram/td_api_json.h:5:0,
                 from /root/tdbot/cliclient.hpp:20,
                 from /root/tdbot/main.cpp:20:
/root/tdbot/td/tdutils/td/utils/JsonBuilder.h:473:3: note: declared here
   JsonValue(const JsonValue &other) = delete;
   ^
In file included from /root/tdbot/cliclient.hpp:20:0,
                 from /root/tdbot/main.cpp:20:
/root/tdbot/td/td/generate/auto/td/telegram/td_api_json.h:13:8: note:   initializing argument 2 of ‘td::Status td::td_api::from_json(td::tl_object_ptr<td::td_api::Function>&, td::JsonValue)’
 Status from_json(tl_object_ptr<Function> &to, td::JsonValue from);
        ^
CMakeFiles/telegram-bot.dir/build.make:62: recipe for target 'CMakeFiles/telegram-bot.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/telegram-bot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/telegram-bot.dir/all' failed
make[2]: *** [CMakeFiles/telegram-bot.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/telegram-bot.dir/rule' failed
make[1]: *** [CMakeFiles/telegram-bot.dir/rule] Error 2
Makefile:162: recipe for target 'telegram-bot' failed
make: *** [telegram-bot] Error 2
`

**Comment by levlam** [comment]
Here is the [patch](https://github.com/tdlib/td/files/4142482/0001-Update-TDLib-to-1.6.0.txt) for tdbot for TDLib 1.6.0 support.
