### ISSUE TITLE
Deallocating strings in json api

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#91]
td_json_client_receive and td_json_client_execute allocate memory for strings. Should clients free memory and what is the right way to do it?

**Comment by arseny30** [comment]
No, you should not deallocate the memory.
The string is stored into preallocated thread local buffer.
So the result should be used before the next call of `td_json_client_receive` or `td_json_client_execute` in the same thread happens.

**Comment by mib32** [comment]
@arseny30 I am using tdlib via ruby (using FFI) and I noticed that when I have many of big strings coming via `td_json_client_receive` my memory grows bigger and bigger. I really wonder why it's like this.

**Comment by levlam** [comment]
@mib32 This should be irrelevant to the memory grow, especially if you receive responses fast enough. Only the last sent update/response is stored in the memory and its storager is immediately replaced by the next `td_json_client_receive` response.
