### ISSUE TITLE
TdLib stopped responding after AuthorizationStateWaitPhoneNumber

### ISSUE THREAD

**Issue by pgwrk** [tdlib/td#910]
Something strange happened a few days ago.

When entering telegram, my application stop receiving all events after AuthorizationStateWaitPhoneNumber.  The last event my app receives is AuthorizationStateWaitPhoneNumber. To send a phone number, the application calls 
 
client.send(new TdApi.SetAuthenticationPhoneNumber(phoneNumber, null), new AuthorizationRequestHandler());

After that, it is supposed to receive AuthorizationStateWaitCode, but, for some reason, it doesn't happen. TdLib stopped responding and I don't get any error messages either. 

Also, as I noticed, some other unofficial clients stopped working at the same stage, too, however, official client don't have this problem.

May be this problem related with Russia?
How to solved this issue?

**Comment by levlam** [comment]
Send TDLib logs to @tdlib_bot.

**Comment by pgwrk** [comment]
Where can get TDLib logs?

**Comment by levlam** [comment]
@pgwrk Use `setLogStream` method to redirect the log to a file.

**Comment by pgwrk** [comment]
ok, will try. Is there any documentation about @tdlib_bot? What commands does it support?

**Comment by levlam** [comment]
@pgwrk Just send the file with the log to it.

**Comment by pgwrk** [comment]
I sent file with logs to bot (attach file and duplicate it in the message body) but bot doesn't reply! What should I do?

**Comment by levlam** [comment]
@pgwrk If you are in Russia or in any other country, where Telegram is blocked, then there is nothing strange.
