### ISSUE TITLE
Example for sendMessageOptions

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#911]
I use lua programming language.
I use sendMessageOptions in the sendMessage method that I wrote in the following way :
`
		options = {
			["@type"] = 'sendMessageOptions',
			disable_notification = disable_notification or 0,
			from_background = from_background or 1,
			scheduling_state = {
				["@type"] = "messageSchedulingStateSendAtDate",
				send_date = 120
			},
		},
`

But scheduling_state is not correct, I want to send the message in 60 seconds or the user is online.
Thanks for giving me a useful example of scheduling_state in programming.

**Comment by levlam** [comment]
`send_date` must be a valid [Unix time](https://en.wikipedia.org/wiki/Unix_time) in the future. Unix time was 120 just two minutes after 1 January 1970.
