### ISSUE TITLE
How to filter/delete chats from deleted users

### ISSUE THREAD

**Issue by digabriel** [tdlib/td#912]
How can I filter/remove/delete a chat from the chat list and the contact list when a user gets deleted from telegram or close their account?

Thank you!

**Comment by levlam** [comment]
Iterate chats. If a private chat with a deleted user is found, then remove it from the chat list using `deleteChatHistory` with `remove_from_chat_list == true` and remove the user from contacts using `removeContacts`.

**Comment by digabriel** [comment]
Ok. I was thinking that the lib itself could have something more automated to do this.
Thank you very much one more time.
