### ISSUE TITLE
TDlib secret chat

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#914]
I'm using TDLib just to use secret chat for sending notification so some kind of one "way chat"
It is possible to configure TDLib to not save or delete the sent messages just for sendere? so I do not have any sent file on file system.
More over images sent in secret chat are stored in tdlib/secret folder, but are not encrypted they are kept as plain jpg: is it the correct behaviour or I'm missing something in configuration?

**Comment by levlam** [comment]
If you disable message database, then the messages will be stored only in memory. There is no way to delete messages in secret chats just for self.

The images are stored in the same directory as the database. It is impossible to encrypt them in a safe way, because there is no place to securely store the encrypton keys. It is app resposibility to pass a protected enough pass as database_directory.

**Comment by micheleselea** [comment]
ok, it's anyway strange to have secret chat stuff stored in plain data without encryption. But if I enable DB storage the image are stored in the encrypted DB or in plain file as without DB?

**Comment by levlam** [comment]
@micheleselea See https://github.com/tdlib/td/issues/188#issuecomment-379536139 for more details about encryption.

Images aren't stored in the database. You can use `deleteFile` to delete them.

**Comment by micheleselea** [comment]
Ok understand: I probably have to change something in TDLib to avoid saving any information to disk because I'm can't storage any critical data.
Do you have some suggestion where can I start to check in source code doing that?

**Comment by levlam** [comment]
@micheleselea There is no way and there is no need to change that in TDLib. Just mount photos folder with tmpfs.

**Comment by micheleselea** [comment]
it's always an ugly walkaroud because the point is that there's one moment you have the image saved plain on the filesystem and I cannot let that happen...I have to found a smart way to do that

**Comment by levlam** [comment]
Whoever can access filesystem is very likely can access memory of your process or/and can inject code to the binary.

**Comment by micheleselea** [comment]
yes I think you are right the point is just to make this the less likely possible and more difficult to do.
Anyway you told me that when you do not have DB enabled information are stored in RAM: do you know if there's some RAM limit to set or some max memory usage?

**Comment by levlam** [comment]
Files are stored on file system regardless of database settings. RAM usage can be limited only extenally by setrlimit.

**Comment by micheleselea** [comment]
Ok, I think in my situation, to keep data as private as possible, is to change tidlib somehow to correct the behavior that could be critical to me
