### ISSUE TITLE
no such function: sqlcipher_export 

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#915]
Using TDlib with 
parameters->use_file_database_ = true;
parameters->use_chat_info_database_ = true;
parameters->use_message_database_ = true;
give me error "no such function: sqlcipher_export " during authentication
I think the lib are compiled with SQLITE_HAS_CODEC flag enabled, so should be defined the function. Did you ever had that issue?

**Comment by levlam** [comment]
No, we have never seen this error. Are you trying to access the database directly?

**Comment by micheleselea** [comment]
no I don't just tdlib should have access to is. I'm going to double check the library compilation to check linker error

**Comment by ramikalai** [comment]
@micheleselea was this a linker issue? I'm having a similar problem, would love to know how you resolved this?

**Comment by micheleselea** [comment]
Hi @ramikalai was not a linker "issue" the problem was that in my application I use sqlite with my library so my library override the sqlite inside tdlib. Because I have SQLITE SEE for crypting db and not the opensource sqlitechiper used by tdlib the only way I managed to make it works was to disable sqlite inside tdlib and make the code chage to use my crypt system

**Comment by egorpugin** [comment]
Also seeing this.

**Comment by borzovplus** [comment]
> micheleselea

There are any updates about this issues? We can not use sqlite in our project with tdlib ??? I try use gorm with tdlib and that is not possible because of this error

**Comment by borzovplus** [comment]
> Hi @ramikalai was not a linker "issue" the problem was that in my application I use sqlite with my library so my library override the sqlite inside tdlib. Because I have SQLITE SEE for crypting db and not the opensource sqlitechiper used by tdlib the only way I managed to make it works was to disable sqlite inside tdlib and make the code chage to use my crypt system

We can not use sqlite in our project with tdlib ??? I try use gorm with tdlib and that is not possible because of this error
