### ISSUE TITLE
ok response returned for archiving saved messages chat

### ISSUE THREAD

**Issue by puppy0cam** [tdlib/td#916]
setChatChatList returns ok when attempting to set saved messages (pm to self) to chatListArchive, but the change does not occur

**Comment by levlam** [comment]
The Saved Messages chat and 777000 (Telegram) can't be archived. Did you expect an error?

**Comment by puppy0cam** [comment]
Yes, I expected to see an error. I believe it also updates the local cache, as recalling the method will return ok within ~10ms rather than the first call which took a few hundred ms

**Comment by levlam** [comment]
This was fixed in TDLib 1.6.2. An error "Chat can't be archived" is returned by the method `addChatToList` if a chat can't be archived.
