### ISSUE TITLE
Prebuild for android

### ISSUE THREAD

**Issue by isopen** [tdlib/td#92]
Many variables are not initialized. When converting classes to another language, many problems arise.
(In TdApi.otherlang all "red" due to uninitialized variables in TdApi.java)
Examples:
public String fileName;
public String mimeType;
public @Nullable PhotoSize thumbnail;
public File animation;
...
lots of
What I expected(example):
public String fileName = ""
At what stage is the interface development for android? (not pre-built)

**Comment by levlam** [comment]
Initializing all fields by an empty object is unneeded. In Java every field is by default initialized to null/0/false, which is more than enough. For example, you can see in answers for https://stackoverflow.com/questions/1277965/should-i-set-the-initial-java-string-values-from-null-to
that null-initialization is much popular than initialization by an empty String.

**Comment by isopen** [comment]
Leo...As soon as I get home. I will explain in more detail what is the essence of.

**Comment by isopen** [comment]
While I'm away from the computer, think about the following. Do you want to broadcast or rewrite?

**Comment by isopen** [comment]
Language A (can be Java). Language B (the language into which you can translate the java code).
Consider the file TdApi.java(Suppose it is written in the language A).
The B language does not allow variables without initialization.
Hence, the disconnect between languages.
Therefore, the programmer will have to edit almost every line of the TdApi.otherlang file.

```
P.S.
I think you understand what I mean.
```

**Comment by levlam** [comment]
Translator should determine the desired default value by variable type, not by a Java field initializer value.

**Comment by isopen** [comment]
Type he translates normally.
The fact is that null/0/false. He does not understand what you mean.
Some kind of dead-end conversation. Try to translate (B already exists).
Google is huge.

**Comment by levlam** [comment]
Your converter should be smart enough to convert
public String fileName;
to
string fileName = "";
in the desired language by looking at the type of variable.

Adding ' = "";' only makes things harder, because you will need to throw away that initializer and provide a way to initialize a String used in the language B.

**Comment by isopen** [comment]
Why did you focus on "".
I suggest that you think about a more competent initialization (for the converter to understand this scribbling)

**Comment by isopen** [comment]
There are several places where the construction is more complicated.
Also by type, but more difficult.
About them later, Leo.

**Comment by levlam** [comment]
Competent initialization should be figured out by field type and not by its initializer, because initializer can be the same for some types in Java, but must be different for them in the target language.

**Comment by isopen** [comment]
Yes, even though 100 times you described the initialization is competent, but it does not plow when translating into the language B.

**Comment by isopen** [comment]
The processor boiled with such competence.
![image](https://user-images.githubusercontent.com/7373292/36496927-6191075c-176c-11e8-8a9b-ce6d003fb87f.png)

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/36518903-008421e8-17bb-11e8-95fb-9a69d03071b5.png)

**Comment by isopen** [comment]
[examle](https://github.com/tdlib/td/issues/95)
