### ISSUE TITLE
Error : 0 : Cannot dup BIGNUM

### ISSUE THREAD

**Issue by anhnhoktvn** [tdlib/td#920]
I got this error:
```
[ 3][t 3][1581290555.027063131][NetQueryDispatcher.cpp:286][#1][!Td]	[main_dc_id:1]
[ 0][t 3][1581290555.027365923][PublicRsaKeyShared.cpp:25][#1][!Td][&r_rsa.is_ok()]	[Error : 0 : Cannot dup BIGNUM] -----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAwVACPi9w23mF3tBkdZz+zwrzKOaaQdr01vAbU4E1pvkfj4sqDsm6
lyDONS789sVoD/xCS9Y0hkkC3gtL1tSfTlgCMOOul9lcixlEKzwKENj1Yz/s7daS
an9tqw3bfUV/nqgbhGX81v/+7RFAEd+RwFnK7a+XYl9sluzHRyVVaTTveB2GazTw
Efz8kg9qv1m6XHVQY3PnEw+QQtqSIXklHwIDAQAB
-----END RSA PUBLIC KEY-----
Aborted (core dumped)
```
system info:
```
node version: v13.8.0
os: linux ubuntu 16
td: 1.6
OpenSSL 1.1.1c  28 May 2019
```
I also tried with openssl version 1.0 but didn't work either.

**Comment by levlam** [comment]
This is the first place where OpenSSL is used. The problem is definitely in the OpenSSL linking.

Node 13.8 depends on OpenSSL 1.1.1, so TDLib must be built against compatible OpenSSL version (1.1.0 or 1.1.1). I would recheck that TDLib is really built against OpenSSL 1.1.1 by inspecting libtdjson dependencies.

**Comment by anhnhoktvn** [comment]
Also tried without succeeded  with:
```
OpenSSL 1.1.1d  10 Sep 2019
node version: 10,12,13
```

**Comment by levlam** [comment]
How did you check that TDLib is built against OpenSSL 1.1.1d?

**Comment by anhnhoktvn** [comment]
I check on the machine that build TDLib by command 
```
openssl version -a
```

**Comment by levlam** [comment]
There can be more than one OpenSSL version installed and cmake could find another one. You need to check CMakeCache.txt file or through `ldd libtdjson.so`.

**Comment by anhnhoktvn** [comment]
Thanks! The Openssl update is a little bit tricky.
