### ISSUE TITLE
Generating JNI library

### ISSUE THREAD

**Issue by alexandr-lebedko** [tdlib/td#922]
Trying to go through TDLib Java example, but after the steps specified for Linux env TdApi is not generated and "libtdjni.so", if I am correct which should be generated after running CMake, is also absent. 
After running all commands structure of the example project is the following:

├── CMakeCache.txt
├── CMakeFiles
│   ├── 3.13.4
│   │   ├── CMakeCXXCompiler.cmake
│   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   ├── CMakeSystem.cmake
│   │   └── CompilerIdCXX
│   │       ├── a.out
│   │       ├── CMakeCXXCompilerId.cpp
│   │       └── tmp
│   ├── cmake.check_cache
│   ├── CMakeOutput.log
│   ├── CMakeTmp
│   ├── feature_tests.bin
│   └── feature_tests.cxx
├── CMakeLists.txt
├── org
│   └── drinkless
│       └── tdlib
│           ├── Client.java
│           ├── example
│           │   └── Example.java
│           └── Log.java
├── README.md
├── td
│   ├── bin
│   │   ├── td
│   │   │   └── generate
│   │   │       ├── JavadocTlDocumentationGenerator.php
│   │   │       ├── scheme
│   │   │       │   ├── td_api.tl
│   │   │       │   └── td_api.tlo
│   │   │       └── TlDocumentationGenerator.php
│   │   └── td_generate_java_api
│   ├── include
│   │   └── td
│   │       ├── telegram
│   │       │   ├── Client.h
│   │       │   ├── Log.h
│   │       │   ├── td_api.h
│   │       │   ├── td_api.hpp
│   │       │   ├── td_json_client.h
│   │       │   ├── tdjson_export.h
│   │       │   └── td_log.h
│   │       └── tl
│   │           ├── tl_jni_object.h
│   │           └── TlObject.h
│   └── lib
│       ├── cmake
│       │   └── Td
│       │       ├── TdConfig.cmake
│       │       ├── TdConfigVersion.cmake
│       │       ├── TdTargets.cmake
│       │       └── TdTargets-release.cmake
│       ├── libtdactor.a
│       ├── libtdclient.a
│       ├── libtdcore.a
│       ├── libtddb.a
│       ├── libtdjson_private.a
│       ├── libtdjson.so -> libtdjson.so.1.6.0
│       ├── libtdjson.so.1.6.0
│       ├── libtdjson_static.a
│       ├── libtdnet.a
│       ├── libtdsqlite.a
│       └── libtdutils.a
└── td_jni.cpp

Is the current guide is relevant or am I missing something? Thank you

**Comment by levlam** [comment]
Yes, the example is relevant. Somehow `CMakeCache.txt` was created in the example folder and not in `build` subfolder. You need to delete `CMakeCache.txt` file and `CMakeFiles` directory and repeat the instructions from the `cd example/java` step.

**Comment by alexandr-lebedko** [comment]
Thank you.
