### ISSUE TITLE
Build failures running TdExample.sln (Namespace 'Telegram' cannot be found)

### ISSUE THREAD

**Issue by Yaboix** [tdlib/td#923]
I followed the instructions for installing TDLib and am trying to run the sample TdExample solution immediately afterward. Have made no changes to the code itself, but the namespace for Telegram is not being recognized. Any ideas on what I am doing wrong?
![image](https://user-images.githubusercontent.com/34358370/74198219-7b572b80-4c26-11ea-971d-3f31b43b5f4e.png)

**Comment by levlam** [comment]
Do you use the latest `vcpkg` version? Versions installed before January 15 needs to be updated. This can be usually done as
```
cd vcpkg
git pull
./bootstrap-vcpkg.bat
./vcpkg upgrade
```

**Comment by SpermesePython** [comment]
I installed vcpkg yesterday and upgraded just now, but no change in output :(

**Comment by levlam** [comment]
Could you delete build folder, run again following commands, collect all terminal output ot a file and send it to @tdlib_bot in Telegram?
```
cd <path to TDLib sources>/example/csharp
mkdir build
cd build
cmake -A Win32 -DTD_ENABLE_DOTNET=ON -DCMAKE_TOOLCHAIN_FILE=<path to vcpkg>/scripts/buildsystems/vcpkg.cmake ../../..
cmake --build . --config Release
cmake --build . --config Debug
```
