### ISSUE TITLE
How to build TDLib for C# in .Netframework version 4.6.1 rather than current 4.0

### ISSUE THREAD

**Issue by zerodwide** [tdlib/td#924]
Hi guys
currently on build TDLib for C# in Windows (through C++/CLI), the dll file is built for .NetFramework v4.0 and only works in project that is targeted v4.0! but my project is targeted v4.6.1.

How i can build it in v4.6.1?

also issue was unresolved in #170 which wanted to build in v4.5.2

thanks in advance

**Comment by levlam** [comment]
TDLib doesn't use .NET Framework internally and doesn't depend on any its particular version. There should be no problems to use the built DLL from any version of the .NET Framework.

4.0 is just a version of the .NET Framework that is used in our example project. It is not related in any way to the TDLib build with C++/CLI interface to the Telegram.Td.dll, which can be used by any .NET application.

**Comment by zerodwide** [comment]
Dear @levlam thanks for reply
I just had the same thoughts at first place!
but in action i got surprised!

here is what i have done:
- Built DLL step by step in https://tdlib.github.io/td/build.html?language=C%23
- Created a project from scratch and referenced Telegram.Td.dll and used like example
BUT: when target is rather than v4.0, in runtime at the moment my class using Telegram.Td namespace get loaded, the error "System.BadImageFormatException" thrown! which means .net version is not compatible!
BUT when target is v4.0 everything is fine!

in visual studio, at references, properties of Telegram.Td.dll in platform shows: .NETFramework,Version=v4.0

so i digged in the source and find a clue:
in td\vcpkg\toolsrc\src\vcpkg\commands.integrate.cpp line 18:
` static std::string create_appdata_targets_shortcut(const std::string& target_path) noexcept
    {
        return Strings::format(R"###(
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Condition="Exists('%s') and '$(VCPkgLocalAppDataDisabled)' == ''" Project="%s" />
</Project>
)###",
                               target_path,
                               target_path);
    }`
 its shows generating target version 4.0 which is hard coded!

should i change all 4.0 in that file or in some other files to 4.6.1?

**Comment by levlam** [comment]
vcpkg manages only dependencies, it doesn't affect the way C++ code is built, so you must not change anything there. 

.NET Framework is fully backward compatible. There should be no problems with loading of Telegram.Td.dll. I've just opened the example project in MSVC, changed its target Framework to 4.6.1, reopened the project and successfully built and launched it. I've checked that both 32-bit and 64-bit versions works with 4.6.1.

Having the `System.BadImageFormatException` exception, you need to check that TDLib was successfully built for the correct architecture, i.e. that 32-bit build is in `build` directory and 64-bit build is in `build64` directory. For example, you can check existence of files `build64\Debug\libcrypto-1_1-x64.dll`, `build64\Release\libcrypto-1_1-x64.dll`, `build\Debug\libcrypto-1_1.dll` and `build\Release\libcrypto-1_1.dll`.

**Comment by zerodwide** [comment]
Thanks @levlam, I followed your guide and it worked on example project

I should mention that i built 64-bit of TDLib, and my project is 64-bit also, but i had same problem until i found a checkbox in project setting, platform : "Any CPU 32-bit preferred" in jetbrain rider and "Prefer 32-bit" in VS. when it is checked everything is fine also in v4.6.1 but if unchecked, project only works in v4.0
really why? :| :|

My guess:
it is correct that `Telegram.Td.dll`, `libcrypto-1_1-x64.dll`, `libssl-1_1-x64.dll` are 64-bit but as `LIBEAY32.dll`, `SSLEAY32.dll`, `zlib1.dll` are still 32-bit, that checkbox should be checked always for compatibility in runtime

by the way my problem solved, but i like to know exact reason.

**Comment by levlam** [comment]
64-bit and 32-bit libraries can't be mixed, so all libraries in a given folder are 64-bit or 32-bit.

The example project has x86 and x64 build configurations defined, which should work out of the box if TDLib is properly build for corresponding architectures in the corresponding directories.

**Comment by levlam** [comment]
@zerodwide From the errors you receive, I would expect that TDLib was built for x86 in the `build64` directory instead of x64.

**Comment by zerodwide** [comment]
@levlam i tried every thing from scratch again, and i confirm that if `Telegram.Td.dll, libcrypto-1_1-x64.dll, libssl-1_1-x64.dll, zlib1.dll` are built in x64 which are only needed libraries, everything is fine even on any dot net version,

i found the problem: we are on a team and some part of project handled by a junior, he did somethings wrong, as including  `LIBEAY32.dll, SSLEAY32.dll` files in project which are none sense and not related!!! and my mistake was following his work.

@levlam  thanks for your sincerely effort and i apologize you, please close the issue.

**Comment by levlam** [comment]
@zerodwide Thanks for the confirmation!
