### ISSUE TITLE
method setAuthenticationPhoneNumber stopped sending code in 90% cases

### ISSUE THREAD

**Issue by merlinkory** [tdlib/td#925]
after call setAuthenticationPhoneNumber() we getting OK fom tdlib, without any errors with state = authorizationStateWaitCode   but  code not sening..
We tested with several phone numbers and getting following results:
1. sometimes  (5-10 % from 100% ) we getting code for some phone number e.g. for 3 attempts, but for 4,5 attempts we don't recive code upto "TOO MANY REQUESTS"
2. many phone number always don't recive code up to  "TOO MANY REQUESTS"

Our servers in Amazon AWS (Frankfurt and Tokyo) and this started yesterday only..

Does anybody face to this problem or know somethong about it?

**Comment by levlam** [comment]
You are likely to be banned by the server. Automatic registering of new users and other suspicious activity is usually prohibited.

**Comment by merlinkory** [comment]
How we can check we banned or not?
but sometimes when call setAuthenticationPhoneNumber() code really sending to user (today, when we was testing it happend sevreal times). 

and if we actually banned, how we can solve this ban?

**Comment by levlam** [comment]
@merlinkory There is no way to check this. But you can write to recover@telegram.org your phone number and description of the problem, if you believe that this is an erroneous ban.

**Comment by merlinkory** [comment]
@levlam  Thank you , i will try write.
But does it may be ban if sometimes setAuthenticationPhoneNumber() work normal?
And always after call, we getting state authorizationStateWaitCode  and without any errors

**Comment by levlam** [comment]
@merlinkory I don't know, but at least you can try.

**Comment by merlinkory** [comment]
@levlam 
Number not blocked, if i try official telegram client, then all right, code are recieved!

But via Tdlib in 90% case we don't recieve code. 

And i have following part of TDlib log:
```

[ 3][t 1][1581587699.610438347][Td.cpp:3592][#1][!Td][&td_requests]     Receive request 5: setAuthenticationPhoneNumber {
  phone_number = "+XXXXXXXXXXXX"
  settings = null
}
[ 3][t 0][1581587699.610669136][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 (nil)
[ 4][t 1][1581587699.610803127][utils.cpp:21][#1][!AuthManager] Create storer for auth_sendCode {
  phone_number = "+XXXXXXXXXXXX"
  api_id = XXXXXX
  api_hash = "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
  settings = codeSettings {
    flags = 0
  }
}
```

and then :

 ```
3][t 1][1581587702.199385643][AuthManager.cpp:456][#1][!AuthManager]  Receive auth_sentCode {
  flags = 2
  type = auth_sentCodeT
  }
  phone_code_hash = "4d8f9d34fe7a1ac94d"
  next_type = auth_codeTyypeApp {
    length = 5peSms {
  }
}
[ 3][t 1][1581587702.199928045][Td.cpp:4707][#1][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitCode {
    code_info = authenticationCodeInfo {
      phone_number = "+XXXXXXXXXXXX"
      type = authenticationCodeTypeTelegramMessage {
        length = 5
      }
      next_type = authenticationCodeTypeSms {
        length = 0
      }
      timeout = 0
    }
  }
}
```

**Comment by levlam** [comment]
@merlinkory Whatever it is, it can't be a TDLib problem.

In the provided logs the code was successfully sent.

**Comment by merlinkory** [comment]
@levlam  but code still not received... (i use 5  different phone numbers)
sometimes code are received  and i can't figure out regularity :(
I've also created new app (on new server with new API_ID) and this still happens.... log the same.. 
Magic :(

**Comment by levlam** [comment]
This still can't be a TDLib issue, because the code is not received by TDLib by some other means like a Telegram message, an SMS, a phone call or a flash call.

**Comment by merlinkory** [comment]
@levlam  ok, thank you!
do you have any advice for solve this problem?

**Comment by levlam** [comment]
The code was sent by a Telegram message from your logs:
```
     type = authenticationCodeTypeTelegramMessage {
       length = 5
     }
```
Have you manually checked Telegram messages for the code?

**Comment by merlinkory** [comment]
after sending code from Tdlib to  XXX number, i checking service message in account for XXX number.
When i sending message with code to XXX number, i have phone with open telegram account in my hand, but don't see code in service message. 
Sometimes , code are recieve - but without any regularity...

**Comment by merlinkory** [comment]
we solved it
this happening on AMAZON AWS only (we was testing in different regions).
But  on local servers or other hosting providers - all right!
