### ISSUE TITLE
BinLog

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#926]
I have some question about BinLog file:

1)Is it a sqlite db? in code I see that the encryption key of authorizationStateWaitEncryptionKey is used for encryption  is it correct?
2)Does log keep informations about authentication?
3)does log keep message in out log and for what reason? is that needed to the library?

**Comment by levlam** [comment]
1) No. Yes.
2) Yes.
3) No.

**Comment by micheleselea** [comment]
thanks, so can I avoid logging message send receiving?
there's some configuration way to do that?

**Comment by levlam** [comment]
What exactly do yoi mean?

**Comment by micheleselea** [comment]
I understand from previews reply that the only BinLog library need is the information about authentication. So all other logs about sending messages receiving messages ecc.. are not mandatory and can be avoided? if so there's some configuration that ca be used to reduce binlog to minimum needed?

**Comment by levlam** [comment]
What "logs about sending messages" do you mean?

**Comment by micheleselea** [comment]
These
LogEvent::HandlerType::SecretChats
LogEvent::HandlerType::SecretChatInfos
LogEvent::HandlerType::ReadHistoryInSecretChat

Is it needed from TDLib or can I disable that logs?

**Comment by levlam** [comment]
No, you can't disable these events.

**Comment by micheleselea** [comment]
Why that events is needed from tdlib? what is saved in that events? text and or captions and or files or images? which log can I disable without affecting functionality?
What I need to do is to save as minimal informations as possible, because I'm in environment where I should save nothing, I should just send messages to secret chats and I can't keep that data

**Comment by levlam** [comment]
The data you are worrying about is not kept.

**Comment by micheleselea** [comment]
So what is BinLog used for?

**Comment by levlam** [comment]
It is used for everything that needs persistent storage and most things can't work without a persistent storage. You can read the code if you have some concerns about it.

**Comment by micheleselea** [comment]
I have to read the code because I have to know what is inside log
thanks

**Comment by micheleselea** [comment]
So let me know if I understand correctly: binlog is a persistent structure aes encrypted used to handle message delivery. Basically information about message sent is removed as soon as the message is sent, correct? File sent are Always kept on directory structure, correct? And if I configure tdlib to not use database, after message is set is removed from binlog and is kept in a ram structure?

**Comment by levlam** [comment]
Basically, this is correct. For example, if message database is not used, then message history in secret chats will not be available after restart.

**Comment by micheleselea** [comment]
ok good
