### ISSUE TITLE
SecretChatActor::send_message_impl

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#927]
Can you tell me more about binlog_event In function send_message_impl?
I need to know about OutboundSecretMessage what is saved in bin log and for what reason? is it permanent or can be deleted?

**Comment by levlam** [comment]
The log event is deleted after the message delivery is confirmed. There is no way secret chats can work without all outgoing messages being saved until they delivery is confirmed.

**Comment by micheleselea** [comment]
ok @levlam it's reasonable to keep that, moreover the binlog is encrypted with AES if I understand well. So if it's some kind of "temporary" and encrypted it's ok for me. is that AES256 encrypted?

**Comment by levlam** [comment]
The binlog is encrypted using AES CTR and the key provided by the app.

**Comment by micheleselea** [comment]
thanks @levlam

**Comment by micheleselea** [comment]
Hi @levlam  another question about binlog. Because it's needed for correct functionality of library and I understand it's a temporary "cache", what is the difference with the sqlite db created when you enable use_file_database_? What information is kept in db?

**Comment by levlam** [comment]
The answer is very-very long, but you can still look at the code, searching for td_db usages.
