### ISSUE TITLE
TdLib .NetCore crash after a while

### ISSUE THREAD

**Issue by jdufaud** [tdlib/td#929]
Hello, i'm using tdlib 1.6.0 in Windows .Net Core, with the lib https://github.com/egramtel/tdsharp to wrap the tdjson into object.

Sorry in advance, i have no logs the bug is not easy to reproduce, i've a customer who can reproduce.
This bug can be reproduced easier if you have a lot of Telegram channel and you receive a lot of message during the day, then after a while the lib just crash.

Maybe a buffer who is full or anything else ?

I've tried to build the 1.5.0 it's worst the app crash faster.

That seems to be like this bug:
https://github.com/tdlib/td/issues/917

but i've tried to build the master yesterday and it's the same case.

Before to use the 1.6.0 in .NetCore i've used the Windows C++ lib, i've no crash with this one but the method to get all chats take a lot of time (5-10 minuts), and with the .NetCore it's really faster.

**Comment by levlam** [comment]
@jdufaud TDLib 1.6.0 is used by millions bots and millions real users in Telegram X with 0 known ways to crash it. Some of the bots has extremely big load, so this can't be a reason by self.

The mentioned issue could really crash the app often, but it existed only for a few commits. It would be really helpful if you can collect TDLib logs before the crash with default verbosity level. If you can connect to the сrashed app via debugger and collect stacktraces, this would be even more helpful.

**Comment by jdufaud** [comment]
I will give you logs as soon as possible

**Comment by jdufaud** [comment]
After building TDLib again with the 1.6.0 tags on Git, the library no longer seems to crash. Therefore we can close this issue.
