### ISSUE TITLE
error cmake on ubuntu 19.10

### ISSUE THREAD

**Issue by Kia-Pashang** [tdlib/td#931]
Hello , i have this error while cmake ;

**-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Warning at td/CMakeLists.txt:287 (message):
  Not found zlib: skip TDLib, tdactor, tdnet, tddb

-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.2.4") 
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file pwd.h
-- Looking for include file pwd.h - found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "tdutils" in directory /root/tdbot/td/tdutils

-- Configuring incomplete, errors occurred!**

**Comment by levlam** [comment]
You didn't install `zlib1g-dev` package.

**Comment by Kia-Pashang** [comment]
> You didn't install `zlib1g-dev` package.

Oh thanks alot.
