### ISSUE TITLE
this phone number is banned

### ISSUE THREAD

**Issue by FJarvan** [tdlib/td#933]
My TG account was suddenly blocked and I don't know what happened. I have send email and send DM on Twitter. But no one reply me !  I'm very shocked, what's going on with this software? Ban accounts for no reason

**Comment by levlam** [comment]
Please write to recover@telegram.org your phone number and other details to recover the account. This is the only place where accidentally blocked accounts can be unblocked.

**Comment by FJarvan** [comment]
> Please write to [recover@telegram.org](mailto:recover@telegram.org) your phone number and other details to recover the account. This is the only place where accidentally blocked accounts can be unblocked.

I have send email by gmail and send DM on Twitter. But no one reply me ! so you think what should i do ? It's been sevreal days and no one has responded

**Comment by IRGC** [comment]
sometimes they don't respond but they do it silently what needs to be done.  so keep checking your account is unbanned or not. 🥺

**Comment by kevinjulio** [comment]
> Please write to [recover@telegram.org](mailto:recover@telegram.org) your phone number and other details to recover the account. This is the only place where accidentally blocked accounts can be unblocked.

i have sent you dm on twitter and gmail, please check. back my account i have asset on there,tank you
