### ISSUE TITLE
inputMessagePhoto SecretChat caption missing formattedText

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#935]
Do you think 1.5.0 of TDLIb should support entities in photo caption? to make text bold italic ecc..
because I try it in standard inputMessageText and is working but in inputMessagePhoto I is not

**Comment by levlam** [comment]
It surely supports them. The field `inputMessagePhoto.caption` has type `formattedText`, so it can contain any entities. Also, note that currently maximum allowed caption length is 1024 characters.

**Comment by micheleselea** [comment]
Can't understand, I'm able to use formattedText in inputmessagetext but not in inoutmessagaphoto caption. I use the HTML parse entries function...but I can't see the bold text on my phone even if text message has html tag removed....I can't figure it out what's wrong...

**Comment by levlam** [comment]
Send the exact requests you are using.

**Comment by micheleselea** [comment]
ok here you are two piece of code

that is working, and I see formatted text on Telegram Application

```
std::string text="<b>some bold</b> <i>some italic</i>";
			auto send_message = td_api::make_object<td_api::sendMessage>();
			send_message->chat_id_ = update_new_message.message_->chat_id_;
			auto message_content = td_api::make_object<td_api::inputMessageText>();
			message_content->disable_web_page_preview_ = true;
			message_content->clear_draft_ = true;
			{
				auto response = td::Client::execute({ 0, td_api::make_object<td_api::parseTextEntities>(text,td_api::make_object<td_api::textParseModeHTML>()) });
				if (response.object) {
					if (response.object->get_id() == td_api::formattedText::ID) {
						auto formatted_text = td::move_tl_object_as<td_api::formattedText>(response.object);
						message_content->text_ = std::move(formatted_text);
					}
				}
				if (!message_content->text_) {
					message_content->text_ = td_api::make_object<td_api::formattedText>();
					message_content->text_->text_ = std::move(text);
				}
			}
			send_message->input_message_content_ = std::move(message_content);
			send_query(std::move(send_message), {});
```

that is not working, I can see the image the caption without html tags but without formatted text. If I breakpoint on formatted_text after parsing I see correct text and entities.

```
int iW=1600;
						int iH=1200;
						int iSize=200*1024; //just example, actualy the size of the image
						std::string sFileName = "path to the image";
		
						auto send_message = td_api::make_object<td_api::sendMessage>();
						send_message->chat_id_ = chat_id;

						auto message_content = td_api::make_object<td_api::inputMessagePhoto>();

						auto inputFile = td_api::make_object<td_api::inputFileGenerated>();
						inputFile->original_path_ = sFileName;
						inputFile->conversion_ = "image/jpg";
						inputFile->expected_size_ = iSize;
						message_content->width_ = iW;
						message_content->height_ = iH;
						message_content->photo_ = std::move(inputFile);

						std::string text="<b>some bold</b> <i>some italic</i>";
						{
							auto response = td::Client::execute({ 0, td_api::make_object<td_api::parseTextEntities>(text,td_api::make_object<td_api::textParseModeHTML>()) });
							if (response.object) {
								if (response.object->get_id() == td_api::formattedText::ID) {
									auto formatted_text = td::move_tl_object_as<td_api::formattedText>(response.object);
									message_content->caption_ = std::move(formatted_text);
								}
							}
							if (!message_content->caption_) {
								message_content->caption_ = td_api::make_object<td_api::formattedText>();
								message_content->caption_->text_ = std::move(text);
							}
						}
						
						message_content->ttl_ = 0;
						send_message->input_message_content_ = std::move(message_content);

						send_query(std::move(send_message),{});
```

Do you see something wrong?

**Comment by levlam** [comment]
Everything looks correct here. Could you check that this is not a problem of your Telegram client, which may not support entities in media captions? For example, the entities in captions are not supported in the web.telegram.org client.

**Comment by micheleselea** [comment]
Already checked with Android and iOS latest Telegram official app from store.
If I receive or create message with formatted text I can see formatted text and receiver can see my formatted text. I can't understand why only in caption does not but in normal text does. If you try that piece of code do you see formatted text?
I ask for 1.5.0 version because I'm using it and I saw there's 1.6.0 but in 1.5.0 should be supported as well I think

**Comment by micheleselea** [comment]
I try with the 1.5.0 from windows as well from linux test application...same result

**Comment by micheleselea** [comment]
I do not use the thumbnail image I keep it null, can be that?

**Comment by levlam** [comment]
This can't be related to the thumbnail. Could you collect log with verbosity level 4, containing sending of both messages and send it to @tdlib_bot in Telegram?

**Comment by micheleselea** [comment]
Ok I'll do it on Monday

**Comment by micheleselea** [comment]
the strange thing is that if I use the same code to send image and caption to a normal chat I can see the formatted text, if I send to a SecretChat I can't see the formatted text. Do you think could be a problem related to SecretChat formatted text in caption?

**Comment by micheleselea** [comment]
the strange thing is that looking at loglevel 4 logs I see

```
updateMessageSendSucceeded {
  message = message {
    id = 32505856
    sender_user_id = 819682842
    chat_id = -1999165855541
    sending_state = null
    is_outgoing = true
    can_be_edited = false
    can_be_forwarded = false
    can_be_deleted_only_for_self = false
    can_be_deleted_for_all_users = true
    is_channel_post = false
    contains_unread_mention = false
    date = 1582550995
    edit_date = 0
    forward_info = null
    reply_to_message_id = 0
    ttl = 345600
    ttl_expires_in = 345600.000000
    via_bot_user_id = 0
    author_signature = ""
    views = 0
    media_album_id = 0
    content = messagePhoto {
      photo = photo {
        has_stickers = false
        minithumbnail = null
        sizes = vector[1] {
          photoSize {
            type = "i"
            photo = file {
              id = 5
              size = 211073
              expected_size = 211073
              local = localFile {
                path = "C:\SALVA\VS2005\CarPlateServer\TelegramBot\tdlib\secret\file_60.jpg"
                can_be_downloaded = true
                can_be_deleted = true
                is_downloading_active = false
                is_downloading_completed = true
                download_offset = 0
                downloaded_prefix_size = 211073
                downloaded_size = 211073
              }
              remote = remoteFile {
                id = "BgADBAADCAYAAjc8oVJA4naI05wz4xYE"
                is_uploading_active = false
                is_uploading_completed = true
                uploaded_size = 211073
              }
            }
            width = 1600
            height = 1200
          }
        }
      }
      caption = formattedText {
        text = "Normal Italic Bold"
        entities = vector[2] {
          textEntity {
            offset = 7
            length = 6
            type = textEntityTypeItalic {
            }
          }
          textEntity {
            offset = 14
            length = 4
            type = textEntityTypeBold {
            }
          }
        }
      }
      is_secret = false
    }
    reply_markup = null
  }
  old_message_id = 9
}
```
But unfortunately the text is not shown as expected

**Comment by micheleselea** [comment]
tested with 1.6.0 version, same result...

**Comment by levlam** [comment]
TDLib had no support for formatting of media captions sent to secret chats. This was fixed in https://github.com/tdlib/td/commit/4cb43a27867dc02526bb5ec26bd428bf41366847 and https://github.com/tdlib/td/commit/0d45de3ffb0c08533d1264200650780c47acce09.

**Comment by vinifr** [comment]
Hi. Sorry for asking here. But How can I read "caption = formattedText" from messagePhoto?

```
[this](td_api::updateNewMessage &update_new_message) {
    auto chat_id = update_new_message.message_->chat_id_;
    std::string sender_name;
    td_api::downcast_call(*update_new_message.message_->sender_id_,
                overloaded(
                    [this, &sender_name](td_api::messageSenderUser &user) {
                        sender_name = get_user_name(user.user_id_);
                    },
                    [this, &sender_name](td_api::messageSenderChat &chat) {
                        sender_name = get_chat_title(chat.chat_id_);
                    }));
    std::string text;
    if (update_new_message.message_->content_->get_id() == td_api::messageText::ID) {
        //
        text = static_cast<td_api::messageText &>(*update_new_message.message_->content_).text_->text_;

    } else if (update_new_message.message_->content_->get_id() == td_api::formattedText::ID) {
        //auto formatted_text = td::move_tl_object_as<td_api::formattedText>(response.object);
        //message_content->caption_ = std::move(formatted_text);
        text = static_cast<td_api::messageText &>( ?? ;
    }

    //
    ,
[](auto &update) {}));```

**Comment by levlam** [comment]
See `messagePhoto` class description:
https://github.com/tdlib/td/blob/44b548c3075818af24409f561bd0390a84d3a727/td/generate/scheme/td_api.tl#L2997

The field `update_new_message.message_->content_` can contain an object of the type `messagePhoto` for photo messages.

**Comment by harlene83774179** [comment]
What the fuck.is wrong with you mother fucker GRO ko.
 
 
  On Wed, 8 May 2024 at 9:42 PM, Vinicius ***@***.***> wrote:   


Hi. Sorry for asking here. But How can I read "caption = formattedText" from messagePhoto?
[this](td_api::updateNewMessage &update_new_message) {
    auto chat_id = update_new_message.message_->chat_id_;
    std::string sender_name;
    td_api::downcast_call(*update_new_message.message_->sender_id_,
                overloaded(
                    [this, &sender_name](td_api::messageSenderUser &user) {
                        sender_name = get_user_name(user.user_id_);
                    },
                    [this, &sender_name](td_api::messageSenderChat &chat) {
                        sender_name = get_chat_title(chat.chat_id_);
                    }));
    std::string text;
    if (update_new_message.message_->content_->get_id() == td_api::messageText::ID) {
        //
        text = static_cast<td_api::messageText &>(*update_new_message.message_->content_).text_->text_;

    } else if (update_new_message.message_->content_->get_id() == td_api::formattedText::ID) {
        //auto formatted_text = td::move_tl_object_as<td_api::formattedText>(response.object);
        //message_content->caption_ = std::move(formatted_text);
        text = static_cast<td_api::messageText &>( ?? ;
    }

    //
    ,
[](auto &update) {}));```
