### ISSUE TITLE
Random users from updateUser

### ISSUE THREAD

**Issue by astravexton** [tdlib/td#937]
I'm currently inserting data from `updateUser` into a database and noticed a lot of bots that I have never used nor share any groups with me, is this a bug or feature of tdlib? Some of them that I have never used or see in any group I'm in: https://i.imgur.com/9J09sfX.png
I've also tested this on a new account that isn't in any group/channel and it seems to get some of the same bots

**Comment by levlam** [comment]
Likely the bots are members in some of your groups and are automatically preloaded with the full info about the group.

**Comment by astravexton** [comment]
> Likely the bots are members in some of your groups and are automatically preloaded with the full info about the group.

I've tried it on a new account with a different number that isn't in any group/channel, but some of them are still showing even after I wiped the DB and .tdlib folder

**Comment by levlam** [comment]
The bots can't be received from nowhere. The exact reason can be found, only if you send the TDLib's log with verbosity level 4 to @tdlib_bot in Telegram.
