### ISSUE TITLE
Correct shutdown sequence

### ISSUE THREAD

**Issue by micheleselea** [tdlib/td#938]
Which is the correct shutdown sequence to do when closing application?
I'm currently call
`send_query(td_api::make_object<td_api::close>(),{});`
So after that what I should do to ensure tdlib client is correctly shutted down?

**Comment by levlam** [comment]
You need to handle `updateAuthorizationState` updates for that. You will receive the update with `authorizationStateClosed` eventually.

**Comment by micheleselea** [comment]
ok thanks
