### ISSUE TITLE
PHONE_NUMBER_UNOCCUPIED

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#939]
@levlam 
When I registered with the client after a while, I found that I was forced to quit. I found this PHONE_NUMBER_UNOCCUPIED in the log and immediately after
RPC Error: request 24 got fail with code 401, error USER_DEACTIVATED_BAN
RPC Error in getDifference: 401 USER_DEACTIVATED_BAN:
I wonder what is causing this?

**Comment by levlam** [comment]
There should be also this description in the log:
```
Your account was suspended for suspicious activity. If you think that this is a mistake, please write to recover@telegram.org your phone number and other details to recover the account.
```

**Comment by AquariusHunters** [comment]
@levlam 

> There should be also this description in the log:
> 
> ```
> Your account was suspended for suspicious activity. If you think that this is a mistake, please write to recover@telegram.org your phone number and other details to recover the account.
> ```

But I just registered it and did n’t use it for any operation

**Comment by levlam** [comment]
@AquariusHunters "did n’t use it for any operation" is also an activity. Do you think the spammers with automatically registered accounts need to be banned only after they already spammed?

**Comment by AquariusHunters** [comment]
@levlam 
What caused my account to be identified as a spammer?
Is it because I have registered too many accounts on the same device for a short period of time or is it for some other reason?

**Comment by levlam** [comment]
@AquariusHunters This is not known.

**Comment by AquariusHunters** [comment]
@levlam OK，Thanks
