### ISSUE TITLE
sendMessage returned wrong id

### ISSUE THREAD

**Issue by anhnhoktvn** [tdlib/td#941]
When I send a message the message id returned from the api is different from the actual message id on the chat.
for example: 
api call return 
```
  _: 'message',
 id: 522190849,
```
actual id in the chat:
```
 _: 'message',
 id: 523239424,
```

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/511.

**Comment by anhnhoktvn** [comment]
Thanks!
