### ISSUE TITLE
checkAuthenticationCode

### ISSUE THREAD

**Issue by bugbaal** [tdlib/td#942]
After some days of testing where all were ok, now I get always this error message when I try to set the authorization code?
{"@type":"error","code":401,"message":"Initialization parameters are needed: call setTdlibParameters first","@extra":1745707221}

Of course I set the TdlibParameters with all the params it needs and also I checked and printed that to see they are all inside.

And sometimes I take a Timeout Exception when he tried to do setTdlibParameters call method.
Is there a way to solve this problem?
thanks

**Comment by levlam** [comment]
The error can be returned only if `setTdlibParameters` was not called or returned an error. You need to check that the method call succeeds.

**Comment by bugbaal** [comment]
when I try to call the setTdlibParameters with all params it goes always in exception with this error message:  Timeout waiting for response

**Comment by levlam** [comment]
There is no such thing as response timeouts in TDLib.

Could you send TDLib log with verbosity level 4 to @tdlib_bot in Telegram?

**Comment by bugbaal** [comment]
you mean the td.binlog file?

**Comment by levlam** [comment]
No, the log which is written to stderr by default. It can be redirected to a file using the method setLogStream.

**Comment by bugbaal** [comment]
ok, I sent you the log to @tdlib_bot

**Comment by bugbaal** [comment]
the error is: error for request 1: error { code = 400 message = "Can't lock file "/var/tmp/tdlib/td.binlog", because it is already in use by current program" }

how can I manage this issue?

**Comment by levlam** [comment]
You are trying to simultaneously launch two TDLib instances for the same account. You need to use the previously created TDLib instance, or close it before trying to create another TDLib instance with the same database directory.

**Comment by bugbaal** [comment]
I'm using PHP that is stateless, so every page start and end itself.
Anyway, which is the method to close an instance?

**Comment by levlam** [comment]
@bugbaal In the sent log there at least 5 instances created from the same process. So someone definitely not closing the TDLib instances. To close an instance, call the method `close` and wait for `updateAuthorizationState` with `authorizationStateClosed`.

**Comment by bugbaal** [comment]
ok, I solved it. Thanks

**Comment by victor-freitas** [comment]
@levlam i'm trying to send the TDlib  parameters to another page (telegram code page), so the user can input the code that he receives on his mobile. The problems is that i'm having trouble to extends the session that the lib creates.

**Comment by levlam** [comment]
@victor-freitas You need to ensure that the same TDLib instance is used for both requests and TDLib isn't restarted in the meanwhile.

**Comment by victor-freitas** [comment]
@levlam , yeah i'm doing like the way you saying, but when i make the request, in the first page where the user insert (phone number and select a api_id) when the user click on ''send'', the telegram code is sent to his phone and the page is loaded but, when i put the code, it says tmplib is already in use by current program. Is there a way to tdlib don't get restarted when i make this request or any other method to call to instance the same tdlib?

**Comment by levlam** [comment]
@victor-freitas This is definitely possible, but you need to implement this. Using the same database directory != using the same TDLib instance. An instance is created with `td_create_client_id`/`td_json_client_create` and it needs to be open all the time, not during a specific request.

**Comment by DilshodbekOtajonov** [comment]
I am also receiving this error when sending code to phone number
```
 public void sendPhoneNumber(String phone) {
        Log.setLogMessageHandler(4,new Slf4JLogMessageHandler());
        SimpleTelegramClient client = telegramClientFactory.buildClient(phone);
        try {
            TdApi.PhoneNumberAuthenticationSettings phoneNumberAuthenticationSettings = new TdApi.PhoneNumberAuthenticationSettings();
            TdApi.SetAuthenticationPhoneNumber phoneNumber = new TdApi.SetAuthenticationPhoneNumber(phone, phoneNumberAuthenticationSettings);
            CompletableFuture<TdApi.Ok> send = client.send(phoneNumber);
            TdApi.Ok ok = send.join();
        } catch (Exception e) {
            TelegramError error = (TelegramError) e.getCause();
            throw new BaseException(ResultCode.telegram_server_error, error.getErrorMessage());
        } finally {
            client.sendClose();
        }
    }

public SimpleTelegramClient buildClient(String phone) {
        try {
            SimpleTelegramClientFactory clientFactory = new SimpleTelegramClientFactory();
            TDLibSettings settings = config.getTDLibSettings(phone);
            SimpleTelegramClientBuilder clientBuilder = config.getBuilder(clientFactory, settings);
            AuthenticationSupplier<?> user = config.getCurrentUser(phone);
            clientBuilder.addUpdateHandler(it.tdlight.jni.TdApi.UpdateAuthorizationState.class, this::onUpdateAuthorizationState);
            clientBuilder.addUpdateHandler(it.tdlight.jni.TdApi.UpdateNewMessage.class, this::onUpdateNewMessage);
            clientBuilder.addCommandHandler("stop", this::onStopCommand);
            Thread.sleep(2000);
            client = clientBuilder.build(user);
            return client;
        } catch (Exception e) {
            telegramSessionService.getTelegramSession(phone).ifPresent(telegramSession -> {
                telegramSession.setStatus(AccountStatus.INACTIVE);
                telegramSessionService.save(telegramSession);
            });
            TelegramError error = (TelegramError) e.getCause();
            throw new BaseException(ResultCode.telegram_server_error, error.getErrorMessage());
        }
    }

  public AuthenticationSupplier getCurrentUser(String phoneNumber) {
        return AuthenticationSupplier.user(phoneNumber);
    }

    public final SimpleTelegramClientBuilder getBuilder(SimpleTelegramClientFactory clientFactory, TDLibSettings settings) {
        return clientFactory.builder(settings);
    }

    public TDLibSettings getTDLibSettings(String phoneNumber) {
        APIToken apiToken = new APIToken(29925404, "022af8cbadbfdc0dfcf3612ca7f80621");

        TDLibSettings settings = TDLibSettings.create(apiToken);

        Path sessionPath = Paths.get("sessions/tdlight-session" + "-" + phoneNumber.substring(1));
        settings.setDatabaseDirectoryPath(sessionPath.resolve("data"));
        settings.setDownloadedFilesDirectoryPath(sessionPath.resolve("downloads"));
        settings.setMessageDatabaseEnabled(true);
        settings.setFileDatabaseEnabled(true);
        settings.setChatInfoDatabaseEnabled(true);
        return settings;
    }
```

**Comment by DilshodbekOtajonov** [comment]
this code was working before I had increased tlight version then suddenly it stopped working and now I am stuck
