### ISSUE TITLE
How can I uninstall TDLib?

### ISSUE THREAD

**Issue by RomanSafe** [tdlib/td#946]
Hello!
I have installed TDLib in Windows 10, using build instruction https://tdlib.github.io/td/build.html?language=Python. Now I'm getting system error. It ask me to uninstall package and reinstall it.
How can I uninstall TDLib?

**Comment by levlam** [comment]
TDLib can't be "installed" on Windows. Building just places built library and headers in the specified directory. You can just delete the files, but this is unlikely to solve your problem. What exactly error do you receive?

**Comment by RomanSafe** [comment]
It was error in python-telegram library - wrapper for your library. I used python-telegram library to build Telegram client. When I had launched python script in PowerShell I got pop-up window with error message. Unfortunately I didn't make a screenshot. The message said that I'm trying to launch file dedicated for another operating system and showed the path to the file contained "linux" directory.
Thank you for your response!
