### ISSUE TITLE
Cannot get chat order from getChats

### ISSUE THREAD

**Issue by eladraviv** [tdlib/td#948]
Hi,
I'm trying to get all chats, but for that I must pass the offset_order (in addition to the offset_chat_id) to getChats in order to the next batch of chats.
Problem is that from the first call to "getChats" (with offset_order = 2^63 - 1 and offset_chat_id = 0) I get only the list of chat id's, but not the chat order, so even though I know what is the last chat id on the list I still don't know what is it's order.
What am I missing?

Thanks!
Elad.

**Comment by levlam** [comment]
See https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats and https://core.telegram.org/tdlib/getting-started#handling-updates.

**Comment by eladraviv** [comment]
Thanks @levlam
