### ISSUE TITLE
TdLib for searchPublicChats() does not return anything

### ISSUE THREAD

**Issue by volodalexey** [tdlib/td#949]
Initially I posted this issue in Airgram https://github.com/airgram/airgram/issues/84
TLDR:
`searchPublicChats()` Returns nothing, however  I see that on the low level TdLib received `Sending update: updateUser {
  user = user {...}`

Any thoughts on this?

**Comment by levlam** [comment]
From description of the method `searchPublicChats` (https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1search_public_chats.html): `Excludes private chats with contacts and chats from the chat list from the results`. If you want to get a chat from your chat list you need to use `searchChats` or `searchChatsOnServer` method.

**Comment by volodalexey** [comment]
Wrong method used. Resolved. Thanks
