### ISSUE TITLE
Fork tdlib-interface on Kotlin

### ISSUE THREAD

**Issue by isopen** [tdlib/td#95]
I do not know if this will work for you. "Everyone who tries to test himself, check for yourself."
I do not even know if it will work for you. Check. Try it. Test.

[Fork on Kotlin](https://github.com/isopen/tdlib/tree/master/kotlin/fork)

Leo, I was frightened by the symbol ^M in Client.java, TdApi.java, NativeClient.java (Notepad++ solves).
![image](https://user-images.githubusercontent.com/7373292/36587472-db992600-18b7-11e8-8ec8-43c36b9bc6ed.png)
Vim Leo Vim Leo Vim Vim Vim...%s/\r//gc

I went to drink Russian Vodka.

**Comment by isopen** [comment]
[Fix ^M](https://github.com/isopen/tdlib/tree/master/java_ref%5EM)

**Comment by levlam** [comment]
^M is a carriage return, which is a part of newline control character on Windows. Giving the fact that newline representation is different for different OSs, there is no way to provide a single zip-archive distribution which has newline representation suitable for any OS. You can use, for example, dos2unix to get rid of ^M on Linux/Mac OS.

**Comment by isopen** [comment]
Good answer. Why does not the ^ M symbol appear in the tdlib code?
I think it was possible to do without a symbol of the return of the correctness. Save a few bytes of code.

**Comment by isopen** [comment]
Cool, but it looks like a crutch.
But the crutch is good.
