### ISSUE TITLE
Video is black screened on iphones when sending via tdlib

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#950]
Hey, I got a strange behavior when I send Videos via tdlib. In some cases, the video doesn't work at user's telegram-client.  In this case, there is sound, but the video is black when running in the messenger. But if the video is downloaded the user can watch the video with normal media player. Also, this issue only appears for iphone users, not for android.

The reason why I think its a tdlib issue is, all videos work fine if I send a video via telegram-client for android or desktop...

**Comment by levlam** [comment]
TDLib doesn't alter sent video files in any way, so any such issue is an issue with the video file.

It works with Android client, because the client compresses and reencodes the video before sending.

**Comment by MalteToenjes** [comment]
But if I send Video-A from telegram-client-1 to telegram-client-2 its works no matter if telegram-client-2 has android or iphone.
If I send the exact Video-A via tdlib to telegram-client-2 , the video only works if telegram-client-2 is android, if iphone -> black screen.

**Comment by levlam** [comment]
Because the "telegram-client-1" compresses and reencodes the video before sending.

**Comment by MalteToenjes** [comment]
Ok alright. Am I assuming right, you have no more information how to compress and reencode a video for iphone?

**Comment by levlam** [comment]
Any popular codecs should work.
