### ISSUE TITLE
thumbnail seems not to work with inputMessageDocument

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#951]
I got problems to set a thumbnail for inputMessageDocument. I'm really not sure what I'm doing wrong. Thats how my json looks like:
```
{                   '@type': 'sendMessage',
                    'chat_id': chat_id,
                    'input_message_content': {
                        '@type': 'inputMessageDocument',
                        'document': {'@type': 'inputFileLocal', 'path': path},
                        'thumbnail': {'@type':'inputThumbnail', 'thumbnail': {'@type': 'inputFileLocal', 'path': thumbnail_path}, 'width':103, 'height':73},
                        'caption': {'@type':'formattedText', 'text':text}
                    }}
```

The path var seems to be right because otherwise I would get an error from tdlib, but I don't get any. 
The image I use as thumb:
JPG | size: 8,9KB | width: 103 | height: 73

Like I said I don't get any errors and the file is sent successfully but there is no thumbnail set.

**Comment by levlam** [comment]
If thumbnail fails to load, the file will be still send successfully without thumbnail. You can find what has happened in the TDLib's log.
