### ISSUE TITLE
tdjson + get* methods not returning extra parameter and no indication of completion

### ISSUE THREAD

**Issue by mgrandi** [tdlib/td#952]
It seems that there is no way to match up the responses you get from any of the `get` methods with the responses with TDJSON

for example, with `getHistory`, if i send this message:

```
getChats(_extra=UUID('d7f62c38-cfa7-4809-9708-6e26a3472393'), offset_order=9223372036854775807, offset_chat_id=0, limit=5
```

I get back 

```
2020-03-11T21:21:02.916147-07:00 MainThread telegram_dl.message_archive    INFO    : updateSupergroup(_extra=None, supergroup=supergroup(_extra=None, id=1105607974, username='', date=1512190220, status=chatMemberStatusMember(_extra=None), member_count=0, sign_messages=True, is_channel=False, is_verified=False, restriction_reason='', is_scam=False))
2020-03-11T21:21:02.919109-07:00 MainThread telegram_dl.message_archive    INFO    : updateNewChat(_extra=None, chat=chat(_extra=None, id=-1001105607974, type=chatTypeSupergroup(_extra=None, supergroup_id=1105607974,

# etc etc
```

so according to the documentation (https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html) , if i were to call this in c++, i would get back a list of chats, but it seems that TDJSON is enumerating that list and sending individual `updateNewChat` or `updateSupergroup` or whatever messages, but it doesn't include the `extra` parameter that i passed in, so i have no idea what messages correspond to the message i sent, so i can emulate what the Java example does : https://github.com/tdlib/td/blob/278c7acdec83c5ac17d8e1ed0bb2cacbcea62460/example/java/org/drinkless/tdlib/example/Example.java#L246

is there a way to have the messages that arrive as a result of the message I sent to have the `extra` parameter set? and maybe an `ok` message to indicate that it is done? (because for example, `getChats` can return less messages than you requested with the `length` parameter

**Comment by levlam** [comment]
All TDLib requests return response with the same "@extra" field, which was used to send the request, when TDLib's JSON interface is used. The response to `getChats` method is of type `chats` and will have the same "@extra" field. Updates you receive are not directly related to the request. You can find more information about updates handling and receiving list of chats in https://core.telegram.org/tdlib/getting-started.

**Comment by mgrandi** [comment]
Hmm, I don't seem to be getting that message then, I'm correctly logged in and receiving messages, and the tdjson send says it succeeded fine, I'll investigate the logs more

**Comment by mgrandi** [comment]
So you were correct (obviously), i was sending it wrong and that was causing telegram to not send anything back

what i was sending:

```
{
  "_extra": "614057bf-94e9-4f6d-b7d1-a12111f8b6b8",
  "offset_order": 9223372036854776000,
  "offset_chat_id": 0,
  "limit": 5,
  "@type": "getChats"
}
```

what i needed to send:

```
{
  "offset_order": 9223372036854776000,
  "offset_chat_id": 0,
  "limit": 5,
  "@type": "getChats",
  "@extra": "f7fe93b3-e479-43b6-98f8-c77cce3e69f2"
}
```

However it is strange that telegram didn't log an error or anything for a valid request (except for the fact that there was an unexpected field)

i remember getting this when setting up my project and trying to call the setLogFile method:

```
# sent
td_execute({ "@type": "setLogStream","log_stream": {"@type": "logStreamFile", "path": "C:/Users/mark/Code/Personal/telegram_dl/scratch/tdlib.log", "max_file_size": 10000000}})

# received
{'@type': 'error', 'code': 400, 'message': 'Can\'t init database in the directory "C:/Users/mark/Code/Personal/telegram_dl/scratch/tdlib": [WindowsError : The system cannot find the path specified. : 3 : Can\'t create directory "C:/Users/mark/Code/Personal/telegram_dl/scratch/tdlib"]'}
```

maybe if telegram rejects a message because it has extra fields it wasn't expecting , it should send an 'error' message back?

**Comment by levlam** [comment]
@mgrandi The request was correct, so it is expected that there was no error. The request wasn't rejected, extra fields are just ignored.

**Comment by mgrandi** [comment]
i could have sworn that it wasn't work, but i checked out my code and tried it and i indeed it does work, i'll close this now
