### ISSUE TITLE
Geting supergroup members as TdApi.User objects. Java/Kotlin

### ISSUE THREAD

**Issue by legobyte** [tdlib/td#953]
I want to show the list of members in a listview.

**Problem**:  function **`GetSupergroupMembers`** only retrieves the userId of the members...
How can i get the Supergroup members as  **`TdApi.User`** objects
Should i call  **`TdApi.GetUser`** for every member?
if so how many requests can i send to server every second to get the user information

Thanks

**Comment by levlam** [comment]
@legobyte You should never call getUser and need to handle updateUser updates instead. See https://core.telegram.org/tdlib/getting-started#handling-updates for more details.

**Comment by legobyte** [comment]
It make sense now.
Thanks @levlam.
