### ISSUE TITLE
MSVC build fail : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj

### ISSUE THREAD

**Issue by nekohasekai** [tdlib/td#954]
https://github.com/NekogramX/LibTDJni/runs/510736023

**Comment by levlam** [comment]
Adding
```
  target_compile_options(tdapi PUBLIC ${BIGOBJ})
```
before
https://github.com/tdlib/td/blob/c407b244a086e71773e0b9f8f64d4fb0536bc447/CMakeLists.txt#L872
should fix the problem. Stable 1.6.0 also should build without the issue.
