### ISSUE TITLE
error: use `emcmake` rather then `emconfigure` for cmake projects

### ISSUE THREAD

**Issue by gasabr** [tdlib/td#955]
I'm trying to patch tdlib with proxies doing [this](https://github.com/evgeny-nadymov/telegram-react/issues/28#issuecomment-508941397).

I've compiled tdlib itself, but encountered a problem while building tdweb: installed emsdk  1.39.10 from source files following instruction on the official site, built openssl using `./build-openssl.sh` just fine. But the `./build-tdlib.sh` produces error from issue title.  Log of the installation can be found here [build-tdlib.log](https://github.com/tdlib/td/files/4339540/build-tdlib.log)

Folder containing `emconfig` and `emcmake` is in $PATH and both commands are available from the shell I'm running `./build-tdlib.sh` in.

I've looked at #18, but it does not look like the same problem.

**Comment by levlam** [comment]
Build with Emscripten breaks every few patch Emscripten versions, so we don't recommend to use the latest Emscripten compiler and SDK anymore. You can use emsdk 1.39.5, which is known to work, as documented in https://github.com/tdlib/td/blob/master/example/web/README.md#building-tdweb-npm-package.

Build instuctions and build scripts will be updated to support the latest emsdk version before the next stable release.

**Comment by gasabr** [comment]
Oh, thank you! I thought that minor release won't break the build. Will try 1.39.5 and report back

**Comment by gasabr** [comment]
1.39.5 has worked just fine, thank you!

**Comment by isopen** [comment]
@levlam https://github.com/tdlib/td/pull/1092/files#diff-99e17a2c3b9d8e59751cf14205ea9cce

Real-time build https://github.com/isopen/td/runs/769502984?check_suite_focus=true
artifact: https://github.com/isopen/td/suites/794685688/artifacts/8512144
