### ISSUE TITLE
Video calls in pandemic crisis

### ISSUE THREAD

**Issue by Pascalio** [tdlib/td#956]
Dear Telegram developers,
The corona virus pandemic is forcing many countries to forbid all sorts of meetings. Worldwide, schools are closed, and people are urged or obliged to work from home. Video calling and conferencing got all of a sudden a central topic in many areas.
Probably, the telegram team plans to deliver video calls when fully ready. Yet, these coming days might prove to be decisive in the adoption or development of one or another communication platform. Aside from the fact that Telegram users would particularly love to see video calls implemented now, it might be a good strategy, so that more new users could find a solution to their present needs in Telegram, instead of moving away to other video-call ready networks.
Pardon me if I'm not writing this post in the right place and in the usual style. Yet I'm sure that you will make your own wise decisions.
Best regards

**Comment by levlam** [comment]
There is no way this can be implemented in TDLib, unless it is implemented server-side first. You can send general feature suggestions through in-app support or by menthioning @telegram on Twitter.
