### ISSUE TITLE
Failed to parse JSON object as TDLib request: Can't find field "@type" when sendMessage

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#958]
Hi, i am using php extension phptdlib. I am trying to sendMessage as bot but i got eror Can't find field "@type". Here is code: https://pastebin.com/FEqkkyGA
I found this question https://github.com/yaroslavche/phptdlib/issues/27 but use_message_database is true

**Comment by levlam** [comment]
You didn't specify a typу of the 'input_message_content' parameter.

Between, it is wrong to do something on `updateChatLastMessage`, you likely want to handle `updateNewMessage` instead.

**Comment by HellFinger-s** [comment]
But i equated 'input_message_contet' with 
$input_message = ['formattedText' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
in line 75. Or i can't equated entities with []

**Comment by levlam** [comment]
Yes, and you didn't specified '@type' => 'inputMessageText'.

**Comment by HellFinger-s** [comment]
I tried this, but i get error Expected Array, got object.
`            $text_entity_type = ['@type' => 'textEntityTypeBotCommand'];
            $entities = ['offset' => '0', 'length' => '2', 'TextEntityType' => $text_entity_type];
            $formatted_text = ['text' => 'Hello', 'entities' => $entities];
            $input_message = ['@type' => 'inputMessageText', 'text' => $formatted_text, 'disable_web_page_preview' => false, 'clear_draft' => false];
            $query = json_encode(['@type' => 'sendMessage', 'chat_id' => '1111', 'reply_to_message_id' => '0', 'disable_notification' => false, 'from_background' => false, 'reply_markup' => null, 'input_message_content' => $input_message]);
            td_json_client_send($client, $query);`

**Comment by HellFinger-s** [comment]
Thanks a lot!!
