### ISSUE TITLE
Multiple accounts, Notifications API

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#959]
I'm trying to implement multiple accounts functionality. For currently active account I need to receive full bunch of the update events as usual.  However for inactive accounts I only need specific info, such as number of chats with unread messages, number of chats with mentions, total number of unread messages and total number of mentions, maybe `updateNewMessage` for unmuted chat to show notification for it.  Is it possible for inactive account to make TDLib send only events such as `updateUnreadMessageCount`, `updateUnreadChatCount` and `updateNewMessage` for unmuted chats?

Maybe this functionality can be done using Notifications API?

What is the best approach to implement multiple accounts, so inactive accounts will generate less update events comparing to active one?

Thanks

**Comment by levlam** [comment]
Mobile clients rely on push notification services and close all inactive accounts after a short idle time. When a push notification is received, they launch corresponding TDLib instance, process the push notification and close again the instance.

If receiving push notifications is not an option, you need to have all the instances always running to receive update. To reduce memory consumption you can still close them and reopen immediately without calling `getChats` and other heavy methods.

TDLib is stateful, so there is no way it can send only some updates. All updates notifies client about state change and if some of them are missed, the client will have partially outdated state. There should be not too much updates, so they shouldn't affect application performance.

**Comment by zevlg** [comment]
Thanks, this very useful!
