### ISSUE TITLE
auto retry function call

### ISSUE THREAD

**Issue by korangu** [tdlib/td#96]
if a function execution failed for whatever reason is it possible to retry automatically?  such option is available?

**Comment by isopen** [comment]
Try it. Here everything can be

**Comment by korangu** [comment]
i am asking for option/way within td lib.

**Comment by isopen** [comment]
I would do so.
You can read the documentation. If there is not what you want, you can read the tdlib code. If in the code tdlib you did not find anything, then set out a detailed log of attempts and ask a question.

**Comment by levlam** [comment]
Every function is retried automatically if it makes sense, i.e. if returned from the server error is 429 and the total request flood wait time don't exceeded 60 seconds.

**Comment by isopen** [comment]
Leo exactly 60?
