### ISSUE TITLE
Internet Speed Connection Update [Feature Request]

### ISSUE THREAD

**Issue by Lorymi** [tdlib/td#961]
I need to show the user Internet speed connection in my client (Download and Upload speed).
This would be a nice feature beside **UpdateConnectionState**

**Comment by zevlg** [comment]
You can just upload/download some file to/from Telegram cloud and calculate the speeds

**Comment by Lorymi** [comment]
@zevlg Thank you. Yes, you're right. but this method/way is only available when downloading or uploading a file.
But I want to get this information always like **UpdateConnectionState**
I know a file needs to be moved (download & upload) to get the connection speed but the TDLib can be return update _UpdateConnectionSpeed_  when we send every request to telegram servers.

**Comment by levlam** [comment]
@Lorymi There is no way to calculate upload/download speed unless constantly download/upload files using the full available bandwidth. This can result in enormous amount of traffic and in the network overload. More over, Telegram has distributed infrastructure, so different files are downloaded from different datacenters and download speed is different for different files. The best you can achieve is to show current upload/download speed based on received updateFile updates for a specific file. You can even try to predict download finish time that way.
