### ISSUE TITLE
Error when trying to send keyboard

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#963]
Hi, i am using php extension phptdlib. I am try to send keyboard with message but i got object of type:
Failed to parse JSON object as TDLib request: Expected Array, got Object"
code: https://pastebin.com/tGVjAYFa

**Comment by levlam** [comment]
Use
```
$keyboard_buttons = [[['text' => '1'],['text' => '2']]];
```
or
```
$keyboard_buttons = [[['text' => '1']],[['text' => '2']]];
```
depending on whether buttons need to be on the same row or not.

**Comment by HellFinger-s** [comment]
Thanks!
