### ISSUE TITLE
Allow more than 5 pinned chats

### ISSUE THREAD

**Issue by Zackptg5** [tdlib/td#965]
Only allowing a max of 5 pinned chats is extremely limiting. Adding a max pin limit for the user to set (which can be default of 5) would be much better.
This is a continuation of [the issue (along with tons of others) created in the telegram-desktop git](https://github.com/telegramdesktop/tdesktop/issues/4037) in which it was said that this is an api problem, not client-side

**Comment by levlam** [comment]
And TDLib is a client library, so this can't be implemented on TDLib's side.

**Comment by Zackptg5** [comment]
Where's the proper place to open this then? I was looking for the API which brought me here

**Comment by levlam** [comment]
There are two ways to send general suggestions. They can be sent through in-app support or by menthioning @telegram on Twitter.

**Comment by Zackptg5** [comment]
I don't have a Twitter so I'll go through the app support route. Thanks
