### ISSUE TITLE
download file very slow

### ISSUE THREAD

**Issue by 110vahid** [tdlib/td#966]
DownloadFile very slow in tdlib but telegram desktop download file fast

**Comment by levlam** [comment]
There are infinite number of possible reasons for that and for the reverse behavior. Download speed is reasonably optimized in TDLib and there is no way to reliably increase it further without significant degradation on other network types.

**Comment by 110vahid** [comment]
I tested a file on pc downloaded one minute with telegram  desktop but downloaded  50 minutes with tdlib!!!!!!!!!

**Comment by levlam** [comment]
There must be a reason for that, but such a big difference is very unlikely to be a TDLib's fault. If you can reproduce this, you can send TDLib and TDesktop logs to @tdlib_bot for the investigation.

**Comment by 110vahid** [comment]
i use tdsharp wrapper.
my code for download file is :
TdClient.DownloadFileAsync(fileId,priority:32,offset:0,limit:0,synchronous:false)

file size is 440 MB.
Is there a mistake in the code?

**Comment by levlam** [comment]
I don't see any problem in the DownloadFile call.

**Comment by 110vahid** [comment]
how find problem for download file?
my app download 8 mb per minute.

**Comment by levlam** [comment]
Collect TDLib logs, send them to @tdlib_bot in Telegram. For comparison, collect TDesktop logs and send them also to the bot. Before collecting logs ensure that the same account is used and the same file is downloaded.

**Comment by 110vahid** [comment]
how Collect TDLib logs?

**Comment by levlam** [comment]
To collect TDLib logs, use [setLogStream](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_log_stream.html) method with [logStreamFile](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1log_stream_file.html) to redirect the log to a file.
To collect TDesktop logs, open Settings and type "debugmode". After that the logs will be created in `DebugLogs` subdirectory of the application directory.

**Comment by levlam** [comment]
@110vahid Have you succeeded in getting the logs?

**Comment by shodanalert** [comment]
try to pass `part_size_kb=512` when download_file
I increased download speed from 1mb per second to 4 mb
