### ISSUE TITLE
Telegram Bot API Scheme

### ISSUE THREAD

**Issue by egorpugin** [tdlib/td#969]
Hi,

The question is more about Telegram bots rather than about tdlib.

Is there anywhere bot api scheme (like in .tl format or in .json) to generate types and functions from it?
Is it possible to ask Telegram team about it? Maybe it is possible to publish it?

Thank you.

**Comment by levlam** [comment]
No, there is no such scheme. Human-readable documentation will remain primary documentation source in the near future. 

But there are parsers of the documentation, for example, https://github.com/aiogram/tg-codegen/blob/d52ce351fce023784688f43b29db7380b0de4a48/generator/parser.py.

**Comment by egorpugin** [comment]
I see. Thanks.
