### ISSUE TITLE
Can't resend local file

### ISSUE THREAD

**Issue by korangu** [tdlib/td#97]
i am randomly getting this **error Can't resend local file** when trying to sendmessage with document.

what is the cause of this error and how can we avoid such error?

**Comment by isopen** [comment]
td/td/telegram/files/FileManager.hpp
```
case FileStoreType::Local: {
  FullLocalFileLocation full_local_location;
  parse(full_local_location, parser);
  int32 size;
  parse(size, parser);
  int32 get_by_hash;
  parse(get_by_hash, parser);
  DialogId owner_dialog_id;
  if (parser.version() >= static_cast<int32>(Version::StoreFileOwnerId)) {
    parse(owner_dialog_id, parser);
   }
   auto r_file_id = register_local(full_local_location, owner_dialog_id, size, get_by_hash != 0);
   if (r_file_id.is_ok()) {
      return r_file_id.move_as_ok();
    }
    LOG(ERROR) << "Can't resend local file " << full_local_location.path_;
    return register_empty(full_local_location.file_type_);
}
```

**Comment by levlam** [comment]
The error means that a local file which started to be uploaded during previous application launch can't continue to be uploaded after relaunch, because the file has been changed. The corresponding sendMessage request will fail. Is it possible for you TDLib usage?

**Comment by isopen** [comment]
Not more than 60 seconds.

**Comment by korangu** [comment]
@levlam application launched only once, and i don't think file has got modified during the sendmessage process. any other reason could be a cause  of this?

**Comment by korangu** [comment]
should i verify md5 hash of the file before and after sendmessage to confirm this?

**Comment by isopen** [comment]
@levlam When sending messages, the ^ M symbol may come along with the message? If it was not sent in the message.

**Comment by levlam** [comment]
@korangu The error usually happens when file modification time was changed.

What error is returned for sendMessage request? It may have no relation to this warning outputted to the log.

**Comment by korangu** [comment]
@levlam  error message was 

> File "/path/to/file" can't be opened for reading

**Comment by levlam** [comment]
This error means that the specified file can't be opened by the library.
Is the file accessible for reading? Is the directories on the path to the file are accessible? What OS is used? Is TDLib ran in some sort of sandbox? How long is the path? Does the path contain some non-ASCII characters?

**Comment by korangu** [comment]
@levlam this error comes only after file is fully uploaded and at the last moment of sending message. 
Is the file accessible for reading? Is the directories on the path to the file are accessible? Yes
What OS is used? Ubuntu 16.04
How long is the path? not fixed but around 30-40
TDLib ran in some sort of sandbox?  no 
Does the path contain some non-ASCII characters? no (a-z 0-9 and _ . only)

**Comment by levlam** [comment]
Could you upload TDLib log from call to sendMessage and up to the error is returned with verbosity at least 4 to Telegram @tdlib_bot?

**Comment by isopen** [comment]
Also.
I told you that you need to bypass the is_ok check.

**Comment by korangu** [comment]
@levlam i no longer facing this issue as something was wrong with my code and i managed to  fix it.
thanks for your all help.
happy to close this.
