### ISSUE TITLE
Editing messages via InputBotInlineMessageID results in MESSAGE_ID_INVALID for some users

### ISSUE THREAD

**Issue by Nukesor** [tdlib/td#971]
Hi!

Recently, while migrating a bot to the Python Telethon library, I stumbled upon a very weird behavior.

For some users, editing messages via inline query doesn't seem to work.
After looking through the code, the maintainer and I couldn't find a reason for this behavior in the python code base, since the payload sent to Telegram was formatted as specified in [the docs](https://core.telegram.org/constructor/inputBotInlineMessageID). The issue seems to even exist in other telegram client libraries.

Original issue: https://github.com/LonamiWebs/Telethon/issues/1398
In there you can find a minimal python example and additional information about the bug.

Symptoms:

Messages shared via inline query cannot be edited for some users and result in a `MESSAGE_ID_INVALID 400`.

- The messages definitely do exist
- Buttons on those messages work, the bot receives the callback query
- When trying to edit the message with the exact same `dc_id`, `id` and `access_hash` as received from the original inline feedback or callback query payload, this error pops up.
- It doesn't happen to everyone, but affected users can reproduce the issue deterministically

Either there's something fundamentally wrong in what we're doing or there is some weird bug.
Anyway, I would appreciate any help with this. This is currently the last blocker to migrate the `Ultimate Pollbot` to Telethon.

Example for a failing payload. Send via @nukes_test_bot:
```
EditInlineBotMessageRequest(
    id=InputBotInlineMessageID(
        dc_id=2,
        id=1815815020588675696,
        access_hash=1957312065933721233
    ),
    no_webpage=True,
    message='Callback response text',
    media=None,
    reply_markup=ReplyInlineMarkup(rows=[KeyboardButtonRow(buttons=[KeyboardButtonCallback(text='callback response', data=b'100:0:0')])]),
    entities=[]
)
```

Relevant TG docs:
https://core.telegram.org/method/messages.editInlineBotMessage
https://core.telegram.org/constructor/inputBotInlineMessageID

Relevant Telethon docs:
https://tl.telethon.dev/methods/messages/edit_inline_bot_message.html
https://tl.telethon.dev/constructors/input_bot_inline_message_id.html

Thanks in advance!

**Comment by Nukesor** [comment]
Relevant Links from Lonami + confirmation that other libraries are affected:
https://github.com/LonamiWebs/Telethon/issues/1398#issuecomment-597638896

**Comment by levlam** [comment]
The problem is in the usage of the method. You send the request to a wrong datacenter. `InputBotInlineMessageID.dc_id` is an exact datacenter ID to which the request must be sent.

**Comment by Nukesor** [comment]
The problem is, that we're using the exact `dc_id` we're getting from over here: https://core.telegram.org/constructor/updateInlineBotCallbackQuery
https://core.telegram.org/type/InputBotInlineMessageID

`updateInlineBotCallbackQuery.msg_id.dc_id` to be exact.

There is no logic in between and no hard-coded ID handling.

Just to be absolutely sure, I just tried to manually set the dc_id and checked if it works for any dc_id in the range of 1 to 5. No luck with that.

However, one thing I noticed is that everything seems to work fine for users in datacenter 4, while users in datacenter 2 seem to experience problems. That might be a red herring, but it fits to your statement about dc_id's being wrong.

**Comment by levlam** [comment]
You must not change the dc_id. You must send the request to the specified datacenter. Telegram has a lot of datacenters. Most requests needs to be sent to the main user DC, but some requests needs to be sent to another specific DC. This is one of such requests, which must be sent to a specified DC and not to the main DC.

**Comment by Nukesor** [comment]
As I already said, I'm not changing the dc_id. I'm sending the dc_id for this specific message as I'm getting it from your API.
Nothing in between.

We use the same dc_id we get from the InputBotInlineMessageID.

Is there a quick way to write a minimal example for this?
My C++ is kind of rusty. Something like a skeleton for a C++ telegram bot using tdlib directly?

**Comment by levlam** [comment]
I said nothing about changing the request, The request is correct. I said that you send the request to the wrong place. Please forward my previous comments to Lonami, so he can answer how to send requests to the right DC using Telethon. to fix the problem

**Comment by Nukesor** [comment]
Ah ok. I misunderstood your responses. Sorry for the unnecessary ping-pong. I wasn't aware that requests are explicitely sent to specific datacenters. I assumed that there is some kind of internal routing for this stuff.

I'll redirect your response to Lonami.
Sorry again for any inconveniences.
