### ISSUE TITLE
getBasicGroupFullInfo returns not complete list of users

### ISSUE THREAD

**Issue by funk-yourself** [tdlib/td#972]
I create new basic group with tdlib (with 2 users initially). Then I join this chat with another telegram client. After that I expect to find 3 users in `members` field of returned result, but there're still only 2. When I wait for some uncertain amount of time, 3rd user finally appears on the list, but it seems to happen sort of randomly.

Is there any way to get actual list of basic group members immediately?

**Comment by levlam** [comment]
This depends only on your network connection with Telegram. You also need to listen to `updateBasicGroupFullInfo`.
