### ISSUE TITLE
searchChatMessages with sender_user_id

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#973]
I'm trying to search photo messages sent by some user inside public chat.  And I got error in return:

```console
==> {"@type":"searchChatMessages","chat_id":-100XXX,"filter":{"@type":"searchMessagesFilterPhoto"},"query":"","from_message_id":74563190784,"offset":-1,"limit":20,"sender_user_id":YYY,"@extra":58}
<== {"@type":"error","code":400,"message":"INPUT_FILTER_INVALID","@extra":58}
```

I "sender_user_id" is not specified, then no error occurs and photo messages from any user are returned.  How to search photo messages sent by given user?

Thanks

**Comment by levlam** [comment]
This combination of filters is not supported server-side, because official clients don't need it. The best you can do is to find all user messages and filter them client-side.
