### ISSUE TITLE
Compile TDLib

### ISSUE THREAD

**Issue by Arbuzzzzzz** [tdlib/td#974]
Hello, I'm compile this library using commands:

`...
cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DTD_ENABLE_DOTNET=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
cmake --build . --target install --config Release
cmake --build . --target install --config Debug
...`

but Telegram.TD.dll don't creating. And \td\example\csharp\TdExample.sh don't build.

What I'm doing wrong?

**Comment by levlam** [comment]
You need to provide the whole console output of the commands you run. Otherwise, there are not enough data to answer the question.

**Comment by Arbuzzzzzz** [comment]
I'm using TDLib build instructions generator with this parameters:
1. programming language - c#
2. operating system (Windows (through c++/cli ))
3. mintty/Bash
4. bitness - 64

Generator givin me instructions

`     git clone https://github.com/tdlib/td.git
    cd td
    git checkout v1.6.0
    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.bat
    ./vcpkg.exe install openssl:x64-windows zlib:x64-windows
    cd ..
    rm -rf build
    mkdir build
    cd build
    cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DTD_ENABLE_DOTNET=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
    cmake --build . --target install --config Release
    cmake --build . --target install --config Debug
    cd ..
    git checkout td/telegram/Client.h td/telegram/Log.h td/tl/TlObject.h
    cd ..
    ls -l td/tdlib`

All instructions execute don't have errors.

**Comment by levlam** [comment]
All the instructions print something to the console, I need to see what exactly is printed by them in your case.

**Comment by Arbuzzzzzz** [comment]
I see this error in log

`42>check_proxy.vcxproj -> D:\td\td\build\benchmark\Debug\check_proxy.exe`
`46>------ Сборка начата: проект: tdjson_static, Конфигурация: Debug x64 ------`
`44>log.cpp`
`43>json.cpp`
`43>log.cpp`
`44>misc.cpp`
`43>misc.cpp`
`46>Building Custom Rule D:/td/td/CMakeLists.txt`
`46>td_json_client.cpp`
`44>MpmcQueue.cpp`
`43>MpmcQueue.cpp`
`45>LINK : fatal error LNK1104: cannot open file "MSCOREE.lib"`
`45>Сборка проекта "tddotnet.vcxproj" завершена с ошибкой.`
`47>------ Сборка начата: проект: tdjson, Конфигурация: Debug x64 ------`

**Comment by levlam** [comment]
See https://stackoverflow.com/questions/41030806/visual-studio-c-cli-mysterious-error-with-template.

**Comment by Arbuzzzzzz** [comment]
Thanks ;-)

**Comment by Arbuzzzzzz** [comment]
I'm sorry, but I have a new error in log
`
`42>------ Build started: Project: wget, Configuration: Debug x64 ------`
`42>wget.vcxproj -> D:\td\td\build\benchmark\Debug\wget.exe`
`32>LINK : error LNK2001: unresolved external symbol _CorDllMain`
`32>C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib\MSCOREE.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'`
`32>D:\td\td\build\Debug\Telegram.Td.dll : fatal error LNK1120: 1 unresolved externals`
`32>Done building project "tddotnet.vcxproj" -- FAILED.`

**Comment by levlam** [comment]
First, delete the build directory and try to rebuild from scratch.
If it wouldn't help, there is still something wrong with the pre-installed software.

**Comment by Arbuzzzzzz** [comment]
I managed. I'm install .NET Framework 4.7.1 SDK, and project comlipe successufull.

Thanks you very much.
