### ISSUE TITLE
Statically linking openssl

### ISSUE THREAD

**Issue by KhushrajRathod** [tdlib/td#975]
I've built TDlib for macOS using the build instructions generator. The library works on my machine, but when trying to use it on a device without openssl installed, I get a dynamic linking error. How can I link openssl statically? I'm building an electron application using [airgram](https://airgram.io).
Thanks

**Comment by levlam** [comment]
You need to install static OpenSSL library and delete dynamic OpenSSL library, and then it will be auotmatically statically linked by cmake during building. You will likely need to build OpenSSL manually from source for that.

**Comment by KhushrajRathod** [comment]
Ok, I've done this and it worked.
Thanks for your help

**Comment by unoexperto** [comment]
@levlam @khrj  Could you please elaborate how exactly you've done it ? Should I install different package instead of `libssl-dev` ? If yes, which one ? I'm building on Debian 10.

**Comment by khrj** [comment]
@unoexperto I'm not sure what exactly I ended up changing here, but I have really old builds here: https://github.com/khrj/tdlib-builder. The scripts should still work, you just need to trigger a build (I don't use Travis CI anymore)

**Comment by khrj** [comment]
As per the .travis.yml file I was still using `libssl-dev`

**Comment by Bannerets** [comment]
@unoexperto If static openssl libraries are available, you can pass the `-DOPENSSL_USE_STATIC_LIBS=TRUE` option to CMake. `libssl-dev` should provide the static libraries.
