### ISSUE TITLE
[Missing] Random Dice Number

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#979]
Blog: https://telegram.org/blog/folders

**Comment by zevlg** [comment]
BTW: if single "🎲" emoji is sent from foreign Telegram client as message, official client displays it as animated dice emoji which always drops with single dot up, and it looks very very similar to random dice animation.  This could lead to some trickery

**Comment by levlam** [comment]
@zevlg This is a bug in iOS client, which will be fixed in the upcoming update.

**Comment by levlam** [comment]
Random dice support was added in TDLib 1.6.3 by addind the classes `messageDice` and `inputMessageDice`,
