### ISSUE TITLE
Thought about the ^M symbol in the distribution for android

### ISSUE THREAD

**Issue by isopen** [tdlib/td#98]
Suppose on your api I was able to build a certain kind of application.
Can you guarantee that the left-hand BLOB characters will not come to me? Formed by your side.

It's connected with
https://github.com/tdlib/td/issues/95
https://github.com/tdlib/td/issues/92 (on the types of data, you perfectly read the lecture)
[fix ^M](https://github.com/isopen/tdlib/tree/master/java_ref%5EM)

**You did not respond!**

**Comment by levlam** [comment]
What do you mean by "left-hand BLOB characters"?

**Comment by isopen** [comment]
I'll just leave it here
echo randString(7, array(
  "abcdefghijklnmopqrstuvwxyz",
  "ABCDEFGHIJKLNMOPQRSTUVWX­YZ",
  "0123456789",
  "!@#\$%^&*()",
));

**Comment by levlam** [comment]
I can't yet understand what you asking about.

**Comment by isopen** [comment]
In words it is not interesting. There are too many of them already.
I'll drop another code snippet a little later here(if you do not mind).

**Comment by isopen** [comment]
I was surprised that you are actively using c BLOB mode for writing code.
Now an example.
https://github.com/isopen/tdlib/blob/master/fiddle_index.rb
Let's look at a lines from the code.
td_send({'@type': 'getAuthorizationState', '@extra': 1.01234})
event = td_receive()
Can you guarantee that there will not be any BLOB coming from you?

**Comment by isopen** [comment]
I was surprised that you are actively using BLOB mode for writing code.
Now an example.
https://github.com/isopen/tdlib/blob/master/fiddle_index.rb
Let's look at a lines from the code.
td_send({'@type': 'getAuthorizationState', '@extra': 1.01234})
...
event = td_receive()
Can you guarantee that there will not be any BLOB coming from you? (I mean the BLOB that were not sent in messages)
