### ISSUE TITLE
[Question] Does td_json_client_destroy remove the directory? If so, how not to auth twice?

### ISSUE THREAD

**Issue by AIshutin** [tdlib/td#980]
Hi!

I've tested tdlib locally and it seems that tdlib removes its files after td_json_client_destroy. I've used [wrapper](https://github.com/alexander-akhmetov/python-telegram) to test, however, it should not influence the behavior. So, my main question is: does td_json_client_destroy remove the directory with files and db?
If so, how to auth only once? Or how to copy the database safely and start tdlib using it?

Excuse me, if this issue is dumb.

**Comment by levlam** [comment]
`td_json_client_destroy` only destroys client instance, freeing all allocated by the instance memory. It does nothing beside that. You can create a new instance using `td_json_client_create` and specify the same `database_directory` in `setTdlibParameters` to continue using the same session.

**Comment by AIshutin** [comment]
thanks
