### ISSUE TITLE
About @extra

### ISSUE THREAD

**Issue by AquariusHunters** [tdlib/td#982]
@levlam 
I'm sorry to disturb you again. This problem bothered me for a day. I added the @extra before sending to join the channel and chat , but I have not received the return information about this command, and my code follows There have been no changes before. I could receive this information before. I used version 1.4.0
Hope to get your help, thank you

**Comment by levlam** [comment]
@AquariusHunters What exactly do you use for sending requests?

**Comment by AquariusHunters** [comment]
@levlam 
When I found some group IDs pushed by the server based on the keywords, I joined the chat based on the IDs of the different lists selected. I used to get whether the user joined the chat from the updateNewMessage method, but now I can't get whether the user joined the chat from here, or prompt him to join the chat failed, how can I do it now? The sending method I use is as follows:

					Json::Value JoinChatJson;
					Json::Value extraJson;
					JoinChatJson["@type"] = "joinChat";
					JoinChatJson["chat_id"] = chatID;
					extraJson["Main"] = 1;
					extraJson["Sub"] = 5;
					extraJson["describe"] = chatID;
					JoinChatJson["@extra"] = extraJson;
					td_json_client_send(client, JoinChatJson.toStyledString().c_str());
					LOG(INFO) << "JoinChatJson.toStyledString()" << JoinChatJson.toStyledString();
It is worth mentioning that the version of TdLib I use is 1.4.0, is it related to the version?

**Comment by levlam** [comment]
@AquariusHunters The `@extra` field in the response to the request will be exactly the same as in the request. This doesn't depend on the TDLib's version.

**Comment by AquariusHunters** [comment]
@levlam 
The current situation is that I cannot receive the returned information about the server that contains these fields. What is the reason? I executed the command to send the request in other threads, but I did not receive information about the identification field, but I received a message such as updateNewChat, but he did not include the @extra I set

**Comment by levlam** [comment]
The method `joinChat` returns `Ok`. Whatever update received after request and between response is not related to the request and shouldn't contain `@extra`. Moreover updates from TDLib never contains `@extra`, because they aren't responding to any request.
