### ISSUE TITLE
CMake Error at CMakeLists

### ISSUE THREAD

**Issue by bsenduran** [tdlib/td#984]
Hi,

I am getting the following error when building the example 

```
senduran@sepc:build$ cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=/home/senduran/projects/telegram/td/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. ..
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindTd.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "Td", but CMake did
  not find one.

  Could not find a package configuration file provided by "Td" with any of
  the following names:

    TdConfig.cmake
    td-config.cmake

  Add the installation prefix of "Td" to CMAKE_PREFIX_PATH or set "Td_DIR" to
  a directory containing one of the above files.  If "Td" provides a separate
  development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/senduran/projects/telegram/td/example/java/build/CMakeFiles/CMakeOutput.log".
```

This error is very similar to #501. But in the above issue he could fix it by re-running the `cmake --build . --target install` from the jnibuild directory.  

In my case it didn't solve the error. 

I have attached the output for both ` cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td ..`  and `cmake --build . --target install` in the jnibuild directory  [prebuild.txt](https://github.com/tdlib/td/files/4431199/prebuild.txt)

I am trying this in Ubuntu 16.04 (`Linux sepc 4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by levlam** [comment]
You need to install OpenSSL dev package (`libssl-dev`). You can find exact build instructions for your OS at https://tdlib.github.io/td/build.html?language=Java.

**Comment by bsenduran** [comment]
Thank you @levlam. 
installing installing OpenSSL dev package solves the issue
