### ISSUE TITLE
Notification title and notifcation body null on android

### ISSUE THREAD

**Issue by thienhaole92** [tdlib/td#985]
I am using tdlib for on android when i receive push notification title and body null 
`{title: null, body: null}, data: {p: AA3oEnnejpx5UxKfXMJtu8z7hv7d_QQi2efKTDXAzGEvJvT2ROhnjko9E_Jv_U14bpeDcpND2AO0TZH3oaDVag2TezZ60MGtvvvIKSEIYtlINqniTsnVYw2sremthB1Gnm9hHj7hwwwOhR8GkRzmJbBhHUYnRyhUy9a8Iomwwi7-a8pA0ldG4lC6RsNHRgq7DaaNQZj5iQa7W4U1lr6ke0cM03mLq2tZ_YJozZbn46fBGnSWpoXBBujWTT3yw9-u-ihRUSU0pnoMXozeCyjGC3bYDRhHRsukLbS6dA0n6U2NYSBEGBLWTeJ0T_Gjj20ZSK7wvLlrFWBBnMJ1aoxLMB41tC4bsDfV}}`

**Comment by theapache64** [comment]
Can you DM me @ [@theapache64](https://t.me/theapache64)

**Comment by levlam** [comment]
@thienhaole92 This is expected behaviour. Telegram doesn't send all your messages in plain text to Google's push notification service. See https://core.telegram.org/tdlib/notification-api/ for the description of how notifications need to be handled.

**Comment by thienhaole92** [comment]
After I send the data to processPushNotification I receive  {@type: ok, @extra: 197}. That means notification payload can be decrypted. So, I want to ask a noob question, How can I get the payload decrypted payload content.

**Comment by levlam** [comment]
@thienhaole92 You can't get the payload. You get a notification or other actions that was triggered by the push notification in the form of updates. You can find https://core.telegram.org/tdlib/notification-api/ in the complete description of how notifications needs to be handled. In particular, to enable Notification API, you need to set "notification_group_count_max" and "notification_group_size_max" options.

**Comment by thienhaole92** [comment]
After I read the docs I still can not find how to handle push notification with tdlib. When app is not on background and forceground I mean app is terminated so how to get push notification like telegram app. Can you tell me more information? Or step to get push notification payload content data. Thank for supporting me.

**Comment by levlam** [comment]
It doesn't matter, whether Telegram is in background or foreground in Android. Push notifications are received through FCM, so it doesn't matter whether app is run or not. It will be automatically launched if needed. When a push notification is received from FCM, it needs to be handled as described in https://core.telegram.org/tdlib/notification-api/#handling-push-notifications. After that you may receive updates with new notifications to show them as described in https://core.telegram.org/tdlib/notification-api/#handling-notification-api-updates. Whenever an `updateNotificationGroup` is received you need to apply it to show new notifications or hide old notifications. Could you elaborate, which step is unclear to you?

**Comment by thienhaole92** [comment]
yah I did these step to integrate tdlib into my flutter app. On ios we can receive push notification but on android we have not received push notification yet. When the app is terminated no notification at all, when it is on background or foreground I can see encrypted notification payload with empty title and body so that no notification banner is displayed. Why I asked the question above because I think if telegram send an encrypted notification payload it means no notification banner displayed. I am sorry if I asked you many noob question.

**Comment by levlam** [comment]
Notifictions works differently on iOS and Android. On iOS main app has no direct control over notifications, they are mostly server-side. Whatever is received from server is shown as notification. On Android app needs to show the notifications by itself. The app is launched by a Firebase service when notification arrives. Then it needs to process incoming encrypted notification and act accordingly. All notification processing is done on the TDLib's side. App needs to handle `updateNotificationGroup` updates sent by TDLib to show the notifications,

**Comment by thienhaole92** [comment]
Hi @levlam. Thank for your supporting. Now I can handle push notification when  the app is in background or foceground but when the app is not run I still can not. Regarding to you answer `Push notifications are received through FCM`, so it means when the app not run push notifications are received through FCM and then I also need to handle `updateNotificationGroup ` too. Is that right? If it is right I have a question when my app not run so that there is no TDLib instance so how do I handle encrypted push notifications

**Comment by levlam** [comment]
When you receive a push notification through FCM, you need to create a TDLib instance, initialize it, handle the push notification using the method `processPushNotification` and wait for updates from TDLib as described in https://core.telegram.org/tdlib/notification-api/#handling-push-notifications. If your app supports multiple account, then you need to execute synchronous method `getPushReceiverId` first, to know which TDLib instance needs to be launched. The correspondence `pushReceiverId` => TDLib instance needs to be stored on the app side in that case.
