### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no tdjni in java.library.path

### ISSUE THREAD

**Issue by theapache64** [tdlib/td#986]
I am tyring to use the `tdlib` with Java. I've followed the [java example](https://github.com/tdlib/td/tree/master/example/java) and I've successfully built the `tdlib` using `cmake --build . --target install`. 

and then I tried to execute this command

```
cd ~/Downloads/td/example/java/bin
```
as I didn't compile the `.java` files, it returned an error saying `bin` doesn't exist. So I compiled the java source code and stored it in `bin` directory

```shell
~/Downloads/td/example/java$ mkdir bin
~/Downloads/td/example/java$ javac -d bin org/drinkless/tdlib/*.java
~/Downloads/td/example/java$ javac -d bin org/drinkless/tdlib/example/Example.java 
```
after that I moved to `bin` directory as in the instruction and executed the `main` method
```
~/Downloads/td/example/java$ cd bin/
~/Downloads/td/example/java/bin$ java '-Djava.library.path=.' org/drinkless/tdlib/example/Example
```

but am getting `UnsatisfiedLinkError`

```
java.lang.UnsatisfiedLinkError: no tdjni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.drinkless.tdlib.example.Example.<clinit>(Example.java:58)
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.drinkless.tdlib.Client.nativeClientExecute(Lorg/drinkless/tdlib/TdApi$Function;)Lorg/drinkless/tdlib/TdApi$Object;
	at org.drinkless.tdlib.Client.nativeClientExecute(Native Method)
	at org.drinkless.tdlib.Client.execute(Client.java:103)
	at org.drinkless.tdlib.example.Example.main(Example.java:308)
```

NOTE: I am using `Ubuntu 16.04`

**Comment by levlam** [comment]
You need to build the example:
```
cd <path to TDLib sources>/example/java
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=<full path to TDLib sources>/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. ..
cmake --build . --target install
```

This builds Java source files and a lot more.

**Comment by theapache64** [comment]
Yes. I've built the library. I said it short with

> I've successfully built the tdlib using cmake --build . --target install

**Comment by theapache64** [comment]
I've rebuilt the project again and it worked. I think the first time I tried the `so` file didn't generate.

**Comment by Voltorane** [comment]
> I've rebuilt the project again and it worked. I think the first time I tried the `so` file didn't generate.

@theapache64 could you please specify, which `so` file did you miss?
