### ISSUE TITLE
Size is 0

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#987]
Hi. I've run two telegram client one of them gets message info and another downloads the file. So I pass the remoteFileId from the 1st to 2nd and then get `fileId` to download it. But sometimes I get 0 at the `size` and `expectedSize` field of recieved `File` class instance.
I use `GetRemoteFile` method in this way:
`client.send(new TdApi.GetRemoteFile(remoteId, null), myResultHandler, myExceptionHandler);`
what's the problem? Is it necessary to use e.g. `new TdApi.FileTypeAnimation()` for getting `fileId` of a gif at 2nd arg. of the method?

**Comment by levlam** [comment]
@yasharzb This is expected, because remoteFile.id doesn't contain file size. Even file size was encoded in the ID, it couldn't be trusted, so it would be mostly useless. The file size became known only after the file is downloaded.

**Comment by yasharzb** [comment]
But I need to know fileSize before download! It's needed in `TdApi.DownloadFile` method. In one client, when I get message, I also get fileId (for that client) and fileSize. And before download the only information about the fileSize is that.Now I wanted to get fileInfo via remote.id. Actually I solved my problem by putting FileType in my `TdApi.GetRemoteFile` method

**Comment by levlam** [comment]
@yasharzb There is no way you can receive a trusted file size from a file ID. It is impossible to store file size in a file ID in a such way, that it can't be spoofed. If you trust the source of the file ID, you can pass file size alongside the file ID. Otherwise, you can't know size of the file before it is actually downloaded.

Passing file type to `getRemoteFile` causes the type to be early checked. There is no way it can cause file size to be known. The file size will be known only if the file has been seen previously.

**Comment by yasharzb** [comment]
You say I can trust the file size only if I download it. How can I download a file without knowing its size?

**Comment by levlam** [comment]
TDLib is able to download files without knowing their size. In fact the size is unknown for a lot of files. Sometime you have expected_size instead, but not always.

The file size from message is reliable, if it is non-zero. I said that you can't trust a file size from a file_id even it would stored there, and there is no way to receive a file size just by file_id.

**Comment by yasharzb** [comment]
So I can get size from the message and I get fileId from the remoteFileId in the other client. I download the file using these two

**Comment by levlam** [comment]
File size is not needed to download the file.

**Comment by yasharzb** [comment]
Yes I was wrong. TdApi.DownloadFile needs limit. For downloading I set limit to 0 (as you said we don't know the exact file size before being downloaded) but I noticed that in some videos I get a file with no extention! What's the problem?

**Comment by yasharzb** [comment]
Also there is another problem. Sometimes it can't get file info with `GetRemoteFile` in 2 minuets. I don't think that is related to the internet connection because for most of the files the download is done quickly.

**Comment by levlam** [comment]
@yasharzb File name also isn't a part of file.remote.id.

`getRemoteFile` is a local request. It returns immediately.

**Comment by yasharzb** [comment]
So....
The only way to download a file is possible with it's id, right? 
How can I get file Id via it's remote id? I thought I can use `getRemoteFile` for getting it.

**Comment by levlam** [comment]
Here is the documentation of `remoteFile.id`:

>Remote file identifier; may be empty. Can be used across application restarts or even from other devices for the current user. Uniquely identifies a file, but a file can have a lot of different valid identifiers. If the ID starts with "http://" or "https://", it represents the HTTP URL of the file. TDLib is currently unable to download files if only their URL is known. If downloadFile is called on such a file or if it is sent to a secret chat, TDLib starts a file generation process by sending updateFileGenerationStart to the client with the HTTP URL in the original_path and "#url#" as the conversion string. Clients should generate the file by downloading it to the specified location

Here is the documentation of `inputFileRemote`:

> A file defined by its remote ID. The remote ID is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the client

And here is the documentation of `getRemoteFile`:

> Returns information about a file by its remote ID; this is an offline request. Can be used to register a URL as a file for further uploading, or sending as a message. Even the request succeeds, the file can be used only if it is still accessible to the user. For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the client

**Comment by yasharzb** [comment]
Thanks. So is that possible to understand whether the client has downloaded a file before? e.g. I have downloaded vid_1 from channel A. Then I delete the file. After a while I want to download vid_1 from channel A.  Can I find out if I downloaded it before or not? What about a same file uploaded to several channels?

**Comment by levlam** [comment]
No, you can't find whether a file was downloaded before, if the file is already deleted.

file.remote.id can change from time to time. You can try to use file.remote.unique_id to identify the same file.
