### ISSUE TITLE
getting user name by user id

### ISSUE THREAD

**Issue by SynthesisOne** [tdlib/td#988]
I get messages from all the chats I’m subscribed to, but I don’t get user_name, how can I get them to correlate user_name and the message in data has a lot of things but no main 

client.on(TD::Types::Update) do |update|
data = update.to_json
puts data

end

**Comment by levlam** [comment]
Every message is received in a chat, which ID is received inside a new message. All needed information about the chat was received before that through updates. You can find a lot of information about updates handling in https://core.telegram.org/tdlib/getting-started#handling-updates.

**Comment by SynthesisOne** [comment]
> Every message is received in a chat, which ID is received inside a new message. All needed information about the chat was received before that through updates. You can find a lot of information about updates handling in


I get the message id but I need the name of the user who sent this message, if possible could you give an example since the documentation is currently too complicated to understand, still it was done to create entire clients but I only need to get the username, thanks

**Comment by levlam** [comment]
This is covered by https://core.telegram.org/tdlib/getting-started. If you have a `user_id`, then you have already received all needed information about the user, including their name, through `updateUser`.

**Comment by SynthesisOne** [comment]
> This is covered by https://core.telegram.org/tdlib/getting-started. If you have a `user_id`, then you have already received all needed information about the user, including their name, through `updateUser`.


I put it wrong, I have sender_user_id, and I want to get the name of the one who sent the message

**Comment by levlam** [comment]
And I answered exactly about that case. You need to read description of `updateUser` in https://core.telegram.org/tdlib/getting-started#handling-updates.

**Comment by SynthesisOne** [comment]
> And I answered exactly about that case. You need to read description of `updateUser` in https://core.telegram.org/tdlib/getting-started#handling-updates.

Sorry to bother you, but I don’t know how to integrate it into my current code, understanding how to integrate will go unreasonably long, thanks for the help

**Comment by levlam** [comment]
If you receive updateUser, you need to save received data to users cache.
When you receive sender_user_id, you just get all the information about the user from the users cache. Alternatively, you can call `getUser` with `sender_user_id`, but this is not how it is supposed to work.

**Comment by SynthesisOne** [comment]
> If you receive updateUser, you need to save received data to users cache.
> When you receive sender_user_id, you just get all the information about the user from the users cache. Alternatively, you can call `getUser` with `sender_user_id`, but this is not how it is supposed to work.

the problem is that I don’t understand how to implement this in the code, I’m not familiar with the TDLib syntax and it’s not possible to correctly describe the above tasks in the code, it’s bad that they don’t give concrete examples in the code (I’m new to this kind of attack for the first time, usually  documentation has sample code

**Comment by levlam** [comment]
TDLib can be used from almost any modern programming language. There is no way there can be examples on all of them, but we have a very long list of examples in different programming languages at https://github.com/tdlib/td/blob/master/example/README.md and an example of `updateUser` handling in Java: https://github.com/tdlib/td/blob/1cb2141fee63e1dff5f2a63b7de22136f71c125f/example/java/org/drinkless/tdlib/example/Example.java#L379.

**Comment by ibengeu** [comment]
For those coming thereafter, the logic is this

- users are returned when an update event is received, this data should be saved somewhere.
- To get the sender information(name or something else), use the key (or id) to access the information from the stored location from above,
