### ISSUE TITLE
Special method for checking username availability (account.checkUsername)

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#99]
For now it seems the only way for clients to check if username is available to be used is to call `SearchPublicChat` method with desired username.

However, it would be better if there would be a special method for such thing, since `SearchPublicChat` may return no longer valid result (e.g. when your contact has removed the username just now and you want to take it – the UI will display "Username is in use", because `SearchPublicChat` will return this chat, but `SetUsername` will succeed anyway).

**Comment by L11R** [comment]
@vkryl use `resolveUsername` method.

**Comment by levlam** [comment]
contacts.resolveUsername is exactly a method behind SearchPublicChat TDLib request. This issue is about lacking of way to call account.checkUsername and channels.checkUsername through TDLib.

**Comment by levlam** [comment]
Method `checkChatUsername` was added in TDLib 1.2.0.
