### ISSUE TITLE
TL WebPage `description` field is wrong type defined

### ISSUE THREAD

**Issue by aurimasniekis** [tdlib/td#990]
The TL-API schema type `webPage` has field `description` which supposed to be `formattedText` but I am receiving the `string` value instead of `formattedText`.

https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L1021

On the main schema, I also see that `description` is a string: https://core.telegram.org/constructor/webPage

**Comment by aurimasniekis** [comment]
Another one issue with schema `draftMessage` has no `date` field as specified in schema

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1draft_message.html

**Comment by levlam** [comment]
Both changes was introduced in the TDLib 1.6.2, which source code can be found in the repository. On-site TDLib documentation is for stable release version 1.6.0,

**Comment by aurimasniekis** [comment]
Ahm, but schema hasn't been updated I think?

https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L1021

**Comment by levlam** [comment]
The schema is a part of the source code, so it corresponds to the latest version.

**Comment by aurimasniekis** [comment]
But then it means those things are not updated?

https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L999-L1021

and draftMessage:

https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L618-L622

**Comment by levlam** [comment]
What do you mean by "not updated"? You are looking at TDLib 1.6.2 scheme, which is part of the current source code, which is by definition up-to-date.

**Comment by aurimasniekis** [comment]
Sorry, I forgot that my lib is old (1.6.0) and that's probably the cause... I somehow thought this schema represented server communication...

Sorry, my bad

**Comment by levlam** [comment]
If you receive description as string, then you are using stable TDLib 1.6.0. The on-site documentation is for TDLib 1.6.0: https://core.telegram.org/tdlib/docs.

**Comment by aurimasniekis** [comment]
Sorry, I meant that I use schema from master branch 😅
