### ISSUE TITLE
tdjson: get version information

### ISSUE THREAD

**Issue by mgrandi** [tdlib/td#994]
a cursory search of the various API methods doesn't return anything on how to get the version of the tdjson library being used, the only thing i see is when you start using tdjson, you get this via `updateOption` (which seems to come from `td/td/telegram/Td.h`)

```
{
  "_extra": null,
  "name": "version",
  "value": {
    "_extra": null,
    "value": "1.6.2",
    "@type": "optionValueString"
  },
  "@type": "updateOption"
}
```

there are various other version numbers i would be interested in, such as the current api layer (`td/td/telegram/Version.h`) and the git commit / is dirty info (`td/auto/git_info.h`) , is there any way to query for these version numbers?

**Comment by levlam** [comment]
No. There is only "version" option, which is sent in a very first update from the TDLib.

**Comment by mgrandi** [comment]
thanks, maybe this will change in the future cause it is potentially useful info
