### ISSUE TITLE
How to create my own message app with this java example?

### ISSUE THREAD

**Issue by mehrdadMP** [tdlib/td#995]
I finally built this example .Now i need to create my own message app in android studio for android OS . So , How can i import this example to android studio and use this classes (i mean TdApi , Client , Log , Example) to develop my own app ? Indeed , I just want to know how to get this example into Android Studio and get a Run from it in the form of an Android app.

**Comment by levlam** [comment]
The example in the repository is a console application for desktop Java. It can't be run on Android. On Android you can use prebuilt TDLib available at https://core.telegram.org/tdlib/tdlib.zip, but you will need to create all the app interface from scratch anyway.

**Comment by mehrdadMP** [comment]
I

> The example in the repository is a console application for desktop Java. It can't be run on Android. On Android you can use prebuilt TDLib available at https://core.telegram.org/tdlib/tdlib.zip, but you will need to create all the app interface from scratch anyway.


I've used this before, but I got this error from build.gradle :
`Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.android.library']`

How can i fix it?

This is my gradle : 
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.1'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"

    sourceSets.main {
        jniLibs.srcDir 'src/main/libs'
        jni.srcDirs = [] //disable automatic ndk-build call
    }

    defaultConfig {
        minSdkVersion 10
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    lintOptions {
        // use this line to check all rules except those listed
        disable 'InvalidPackage'
    }
}

dependencies {
    compile 'com.android.support:support-annotations:25.0.0'
}
```

**Comment by levlam** [comment]
https://stackoverflow.com/questions/37086806/android-studio-failed-to-apply-plugin-id-com-android-application

**Comment by mehrdadMP** [comment]
tnx @levlam it works!
