### ISSUE TITLE
Disable logging to stderr

### ISSUE THREAD

**Issue by dancojocaru2000** [tdlib/td#996]
By default, tdlib logs to stderr. This behaviour is unwanted in console applications.

The way to control logging is by executing with the `setLogStream` class, but, by this time, tdlib already outputs the following:

```
[ 3][t 4][1586652169.693824053][Td.cpp:4707][#1][!Td][&td_requests]	Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.6.0"
  }
}
[ 3][t 4][1586652169.693895102][Td.cpp:4707][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
```

How can logging be disabled **before** calling `td_json_client_create` and getting that output?

**Comment by levlam** [comment]
`setLogStream` is a synchronous method, which can be called through `td_json_client_execute` before a TDLib instance is created.

**Comment by dancojocaru2000** [comment]
But how? `td_json_client_execute` needs a client as the first parameter.

**Comment by dancojocaru2000** [comment]
Nevermind, I just spotted the part of the documentation that says 

> Currently ignored for all requests, so NULL can be passed.

Thanks!
