### ISSUE TITLE
.NET Core - default Timeout for wait for updates = 0.1 second (instead of 10 seconds)

### ISSUE THREAD

**Issue by dimonbelyi** [tdlib/td#998]
Hi,
I've built the library with such parameters: C#, Windows (.NET Core), x64
C++ packages (Windows 10 SDK (10.0.18362.0)) are installed by Visual Studio 2019.
Use it in the project .NET Core 3.0

And when I create a client get a lot of such messages:
```
[ 3][t 0][1586700487.332226515][Client.cpp:270][&td_requests]   Begin to wait for updates with timeout 0.100000
[ 3][t 0][1586700487.332870007][Client.cpp:276][&td_requests]   End to wait for updates, returning object 0 000002417477A5E0
```
After that I've tried to change `Client.cpp` file, add such line to `receive` method:
>    timeout = 10;

Updated Client.cpp:
```
  Client::Response receive(double timeout) {
    timeout = 10;
    VLOG(td_requests) << "Begin to wait for updates with timeout " << timeout;
    auto is_locked = receive_lock_.exchange(true);
    CHECK(!is_locked);
```
And have rebuild the library. **Timeout became 10 seconds.**
But even after that I get such errors in Telegram account to which I try to connect my application (my application call SetAuthenticationPhoneNumberAsync and wait for the Code, which I should send to my Bot):
```
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_3600"}
```
I'm not sure, but maybe this somehow connected with 0.1sec timeout.
Could you help?
Thanks!

**Comment by levlam** [comment]
There is no default timeout for `td_json_client_receive`. 0.1 is likely to be explicitly passed by your wrapper.

Anyway, there is no way it can be connected to exceeding a server-side flood control limit.

**Comment by dimonbelyi** [comment]
But I just use `TdLib.TdClient` from TDLib package (https://www.nuget.org/packages/TDLib/1.6.0/). And there is no way to override Timeout in this class.
Then could you say please how I can set this Timeout correctly (when building or using client)? Because receive updates 10 times per second, this is unnecessary.
Thanks.

**Comment by levlam** [comment]
This is reporistory of the package: https://github.com/egramtel/tdsharp. This is the line, passing the timeout: https://github.com/egramtel/tdsharp/blob/6ff96f3943be88bb79f9e3b68d83a7cb77b361cf/TDLib/Bindings/Receiver.cs#L50.

Timeout 0.1 is acceptable value for desktop applications, so there are no much reasons to change it. It can't cause any problems.

**Comment by dimonbelyi** [comment]
Thank you @levlam very much!
But one more question) may be you guess...
I have a Bot application, which should also initialize TdClient. And as soon as I initialize Telegram Client inside the Bot application (call `SetTdlibParametersAsync`, `CheckDatabaseEncryptionKeyAsync` and `SetAuthenticationPhoneNumberAsync`) then the Bot app **stops receiving messages**, and my account (by which I send messages to Bot and to which I am trying to authorize by TdClient) **is banned for an hour**. 
It's like a magic... Maybe it somehow connected with 2 parallels connections to Telegram (bot and client), I have no ideas...

Or may be you suggest another repo, where I can describe the situation?

**Comment by levlam** [comment]
No, it can't be connected to parallel connections. The problem is somewhere in the code.

**Comment by dimonbelyi** [comment]
Hm, okay.
Than I'll try to create test project just for testing that case and check one more time.
Thank you!
