### ISSUE TITLE
How to manage apiId and apiHash in android ?

### ISSUE THREAD

**Issue by theapache64** [tdlib/td#999]
I am trying to build an android telegram client using this library. Unfortunately, I could not find any good tutorials or documentation about using this library in android. But, I've understood how the library works from the Java examples.

The problem is when implementing the library, I've to pass the `api_id` and `api_hash` to `TDLib`. I think these variables must be unknown to others, as this can be reused for malicious purposes by others. (Even If I obfuscate the variables, It can be decompiled)

As the documentation does not provide any best practices about storing the `api_id` and `api_hash`, **How can I make them unavailable to the public and securely manage it in the android app?**

**Comment by levlam** [comment]
On Android the values can't be accessed without root permissions if they are stored in any reasonable way. From the other side, they can be extracted from the app's memory with root permissions. So you can't do much besides storing them in the apps binary and obfuscating them in any simple way.

**Comment by theapache64** [comment]
Alright. So just asking the worst-case scenario. What if someone decrypts the key and used it for heavy malicious activities? What will happen? Would Telegram block the `apiId` ?

**Comment by levlam** [comment]
No. Usually, only misbehaving users are blocked.

**Comment by theapache64** [comment]
Got it chief. :+1:
